export const questoesHistoria9AnoB2Av1 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "O NAZISMO era a ideologia do Partido Nacional-Socialista de Hitler. Quais eram seus princípios centrais?",
    tip: "O nazismo combinava ultranacionalismo com uma ideia de 'raça superior' — quais eram os principais elementos dessa ideologia?",
    funFact: "\"Você Sabia?\" — Hitler escreveu o 'Mein Kampf' ('Minha Luta') enquanto estava preso em 1923-1924, após o fracassado Putsch da Cervejaria. O livro vendeu 12 milhões de cópias na Alemanha nazista — era dado de presente em casamentos e nascimentos pelo próprio Estado. Continha praticamente todo o programa de Hitler: ódio aos judeus, expansão para o Leste (Lebensraum), unificação dos povos germânicos e destruição do Tratado de Versalhes.",
    points: 1,
    options: [
      { id: "A", text: "Internacionalismo socialista, igualdade entre os povos e redistribuição de riqueza para a classe trabalhadora." },
      { id: "B", text: "Democracia cristã com proteção dos valores religiosos e tradicionais contra o avanço do comunismo." },
      { id: "C", text: "Liberalismo econômico com livre mercado e democracia representativa como base do Estado alemão." },
      { id: "D", text: "Ultranacionalismo, racismo (superioridade da 'raça ariana'), antissemitismo virulento, culto ao líder (Führer), expansionismo territorial (Lebensraum) e rejeição total da democracia." },
    ],
    correctAnswer: "D",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "O Ministro de Propaganda de Hitler, Joseph GOEBBELS, usou os meios de comunicação da época de forma inédita. Como?",
    tip: "Como o nazismo usava o rádio, o cinema e as grandes manifestações para moldar a opinião pública?",
    funFact: "\"Você Sabia?\" — Goebbels colocou rádios baratos ('rádio do povo', o Volksempfänger) em cada lar alemão — e os sintonizou para não captar emissoras estrangeiras. O documentário 'O Triunfo da Vontade' (Leni Riefenstahl, 1935) sobre o Congresso do Partido em Nuremberg foi um marco da propaganda cinematográfica. Os nazistas foram os primeiros a usar o rádio em campanhas eleitorais, a transmitir discursos ao vivo e a criar espetáculos de massa pensados como shows televisivos — décadas antes da TV.",
    points: 1,
    options: [
      { id: "A", text: "O rádio, o cinema e os grandes espetáculos de massa foram usados sistematicamente para manipular emoções, criar o culto ao líder e transformar o povo alemão num todo orgânico identificado com Hitler e com a nação." },
      { id: "B", text: "O governo nazista proibiu todos os meios de comunicação e usou apenas boca-a-boca e panfletos manuais para divulgar sua ideologia." },
      { id: "C", text: "Goebbels usou o sistema educacional exclusivamente — universidades e escolas eram o único canal de propaganda nazista." },
      { id: "D", text: "A propaganda nazista era dirigida exclusivamente às forças armadas para garantir lealdade dos militares ao regime." },
    ],
    correctAnswer: "A",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "A NOITE DOS CRISTAIS (Kristallnacht, 9-10 de novembro de 1938) foi um marco da perseguição nazista. O que aconteceu?",
    tip: "O nome vem dos vidros quebrados nas ruas — o que foi destruído e quem foi atacado?",
    funFact: "\"Você Sabia?\" — Na Noite dos Cristais, 7.500 estabelecimentos judeus foram destruídos, 1.400 sinagogas incendiadas ou demolidas, 30.000 judeus presos e mandados para campos de concentração, e ao menos 91 judeus mortos. O governo obrigou a comunidade judaica a pagar 1 bilhão de marcos pela 'limpeza' dos destroços. O seguro dos prejuízos foi confiscado pelo Estado. A 'Noite dos Cristais' foi o anúncio do que viria a seguir — o Holocausto.",
    points: 1,
    options: [
      { id: "A", text: "Revolta popular espontânea de alemães comuns contra o governo nazista que saiu do controle das autoridades." },
      { id: "B", text: "Ataque alemão a cidades polonesas na fronteira, quebrando vidraças e janelas para intimidar a resistência." },
      { id: "C", text: "Pogrom organizado pelo Estado nazista: lojas, casas e sinagogas judaicas foram sistematicamente destruídas e incendiadas, judeus foram presos e assassinados — um marco da escalada da perseguição antissemita." },
      { id: "D", text: "Manifestação pacífica de judeus alemães contra as Leis de Nuremberg que foi violentamente reprimida pela polícia." },
    ],
    correctAnswer: "C",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "A política de APPEASEMENT ('apaziguamento') adotada por França e Grã-Bretanha diante das agressões de Hitler consistia em:",
    tip: "Por que as democracias europeias cederam às exigências de Hitler em vez de confrontá-lo mais cedo?",
    funFact: "\"Você Sabia?\" — O Acordo de Munique (setembro de 1938) é o símbolo do appeasement. O primeiro-ministro britânico Neville Chamberlain voltou de Munique acenando com um papel e declarando: 'Paz para o nosso tempo'. Em menos de 1 ano, Hitler invadiu o resto da Tchecoslováquia e depois a Polônia. Chamberlain ficou para a história como símbolo de ingenuidade política. Winston Churchill, que se opôs ao appeasement, disse: 'Você escolheu a desonra para evitar a guerra — e terá os dois.'",
    points: 1,
    options: [
      { id: "A", text: "Resposta militar imediata a qualquer agressão de Hitler, mostrando firmeza para dissuadi-lo de avançar." },
      { id: "B", text: "Política de fazer concessões às exigências alemãs esperando satisfazer Hitler e evitar uma nova guerra — que falhou porque encorajou mais agressões." },
      { id: "C", text: "Aliança secreta entre França e GB para armar a resistência interna na Alemanha contra o nazismo." },
      { id: "D", text: "Estratégia de isolar a Alemanha economicamente por meio de sanções comerciais da Liga das Nações." },
    ],
    correctAnswer: "B",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "O PACTO RIBBENTROP-MOLOTOV (agosto de 1939) foi um acordo secreto entre Alemanha e URSS. Qual foi seu impacto?",
    tip: "Por que dois inimigos ideológicos (nazismo e comunismo) fizeram um acordo? O que o pacto secreto previu?",
    funFact: "\"Você Sabia?\" — O pacto tinha cláusulas secretas dividindo a Europa Oriental entre Alemanha e URSS: Alemanha ficaria com a metade ocidental da Polônia, e a URSS com a metade oriental, além dos países bálticos (Estônia, Letônia, Lituânia) e Bessarábia (Romênia). Stalin disse: 'Dei uma rasteira no Hitler.' Hitler pensou o mesmo. Em 1941, Hitler invadiu a URSS — o pacto durou 22 meses. Stalin ficou tão chocado que ficou em silêncio por dias, incapaz de dar ordens.",
    points: 1,
    options: [
      { id: "A", text: "Aliança militar permanente entre Alemanha e URSS para dividir o controle da Europa Ocidental." },
      { id: "B", text: "Acordo de livre comércio que permitiu à Alemanha comprar petróleo e matérias-primas soviéticas." },
      { id: "C", text: "Tratado de paz entre as duas potências que encerrou as hostilidades ideológicas entre nazismo e comunismo." },
      { id: "D", text: "Pacto de não-agressão com protocolo secreto dividindo a Europa Oriental — liberou Hitler para invadir a Polônia sem temer uma guerra em dois frontes, tornando a Segunda Guerra possível." },
    ],
    correctAnswer: "D",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "A SEGUNDA GUERRA MUNDIAL começou oficialmente em 1º de setembro de 1939. Qual foi o evento que a desencadeou?",
    tip: "Qual país foi invadido pela Alemanha nessa data, fazendo França e Grã-Bretanha declararem guerra?",
    funFact: "\"Você Sabia?\" — Para justificar a invasão da Polônia, Hitler encencenou o 'Incidente de Gleiwitz': agentes da SS se disfarçaram de poloneses, invadiram uma rádio alemã na fronteira, fizeram um discurso em polonês e deixaram para trás um cadáver de um prisioneiro como 'prova'. No dia seguinte, Hitler disse ao Reichstag: 'Desde as 5h45 da manhã respondemos ao fogo.' Foi o primeiro false flag da história registrado em vídeo.",
    points: 1,
    options: [
      { id: "A", text: "A invasão da Polônia pela Alemanha, que levou França e Grã-Bretanha a declararem guerra à Alemanha em 3 de setembro de 1939." },
      { id: "B", text: "O bombardeio japonês a Pearl Harbor (Havaí), que fez os EUA declararem guerra ao Eixo em 7 de dezembro de 1941." },
      { id: "C", text: "A invasão italiana da Etiópia e Albânia, que levou a Liga das Nações a declarar guerra à Itália." },
      { id: "D", text: "A Alemanha invadiu a França diretamente em 1939, contornando a linha Maginot pelo sul." },
    ],
    correctAnswer: "A",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "A BLITZKRIEG ('guerra relâmpago') foi a tática militar usada pela Alemanha com grande sucesso. No que consistia?",
    tip: "A Blitzkrieg era o oposto da guerra de trincheiras da Primeira Guerra — como ela funcionava?",
    funFact: "\"Você Sabia?\" — A França caiu em 46 dias (maio-junho de 1940) — uma humilhação para o país que resistiu 4 anos na Primeira Guerra. Os franceses investiram tudo na 'Linha Maginot' — uma linha de fortificações na fronteira com a Alemanha — que os alemães simplesmente contornaram pela Bélgica e pelos Ardennes (floresta considerada intransponível). O general Guderian levou tanques pelos Ardennes e apareceu atrás das linhas francesas. Em 6 semanas, a maior potência militar continental da Europa capitulou.",
    points: 1,
    options: [
      { id: "A", text: "Estratégia defensiva baseada em construção de bunkers e trincheiras para resistir ao avanço inimigo." },
      { id: "B", text: "Combinação de avanços rápidos de tanques blindados, apoio aéreo próximo (Stuka) e infantaria motorizada — buscava romper as linhas inimigas antes que o adversário pudesse reorganizar a defesa." },
      { id: "C", text: "Tática de guerra naval com submarinos para cercar países inimigos e impedir seus suprimentos." },
      { id: "D", text: "Estratégia de bombardeio exclusivo de cidades civis para destruir o moral da população inimiga." },
    ],
    correctAnswer: "B",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "A BATALHA DA GRÃ-BRETANHA (1940) foi travada nos céus da Inglaterra. Qual foi seu significado?",
    tip: "Hitler precisava destruir a aviação britânica (RAF) antes de invadir a Grã-Bretanha — o que aconteceu?",
    funFact: "\"Você Sabia?\" — A RAF tinha 650 aviões Fighter Command; a Luftwaffe atacou com 2.000 aviões. Por três meses (julho-outubro de 1940), a batalha foi acirrada — a RAF perdia pilotos mais rápido do que treinava. Churchill disse: 'Nunca na história dos conflitos humanos tantos deveram tanto a tão poucos'. O radar (tecnologia secreta britânica) foi o diferencial: a RAF sabia de onde e quando os alemães vinham. Quando Hitler mudou o alvo dos aeródromos para as cidades (o Blitz), deu tempo à RAF de se recuperar.",
    points: 1,
    options: [
      { id: "A", text: "Batalha terrestre em que a Grã-Bretanha invadiu a Normandia para libertar a França em 1940." },
      { id: "B", text: "Batalha naval em que a Marinha britânica destruiu a frota alemã no Canal da Mancha." },
      { id: "C", text: "Batalha aérea em que a RAF resistiu à Luftwaffe (força aérea alemã), impedindo a invasão britânica e marcando a primeira derrota de Hitler — com papel decisivo do radar britânico." },
      { id: "D", text: "Batalha em que tropas britânicas defenderam os portos da costa sul contra desembarque anfíbio alemão." },
    ],
    correctAnswer: "C",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "A OPERAÇÃO BARBAROSSA (22 de junho de 1941) foi a invasão alemã da URSS. Por que foi uma decisão tão decisiva para o resultado da guerra?",
    tip: "Por que Hitler invadiu a URSS enquanto ainda lutava contra a Grã-Bretanha — o que ele esperava e o que realmente aconteceu?",
    funFact: "\"Você Sabia?\" — A Operação Barbarossa foi a maior invasão militar da história: 3,8 milhões de soldados alemães e aliados, 3.600 tanques e 2.700 aviões. Nos primeiros 3 meses, os alemães avançaram 1.000 km e capturaram 3 milhões de soldados soviéticos. Stalin estava tão perturbado que os primeiros 9 dias de guerra ficou em silêncio, sem dar ordens. Mas a URSS não capitulou — o inverno russo, as imensas distâncias e a resistência soviética transformaram a 'guerra de 6 semanas' que Hitler esperava numa sangria de 4 anos.",
    points: 1,
    options: [
      { id: "A", text: "Operação de bombardeio naval alemão que destruiu a frota soviética no Mar Negro em uma única noite." },
      { id: "B", text: "Aliança militar entre Alemanha e URSS para dividir o controle da Ásia Central e do Oriente Médio." },
      { id: "C", text: "Retirada estratégica alemã da frente ocidental para concentrar forças contra a URSS no leste." },
      { id: "D", text: "Invasão alemã da URSS que abriu a devastadora frente oriental — a guerra de dois frontes que Hitler devia evitar; a resistência soviética (incluindo o inverno) transformou-a num pesadelo e marcou o início do fim do III Reich." },
    ],
    correctAnswer: "D",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "O ataque japonês a PEARL HARBOR (7 de dezembro de 1941) levou os EUA à guerra. O que isso significou para o conflito?",
    tip: "Os EUA eram a maior potência industrial do mundo — o que sua entrada na guerra mudou?",
    funFact: "\"Você Sabia?\" — O almirante japonês Yamamoto, formado em Harvard, disse após Pearl Harbor: 'Temo que apenas adormecemos um gigante dorminhoco e o enchemos de terrível resolução.' Tinha razão. Em 4 anos, os EUA produziram 300.000 aviões, 100.000 tanques e 2 milhões de caminhões militares — mais do que Alemanha, Japão e Itália juntos. A capacidade industrial americana transformou completamente a equação de forças da Segunda Guerra.",
    points: 1,
    options: [
      { id: "A", text: "A entrada dos EUA selou a vitória dos Aliados ao trazer a maior potência industrial do mundo para o conflito — recursos que Alemanha, Japão e Itália juntos não conseguiriam superar." },
      { id: "B", text: "Os EUA declararam guerra apenas ao Japão, sem envolvimento na Europa — mantiveram neutralidade com a Alemanha." },
      { id: "C", text: "A entrada americana chegou tarde demais — a Alemanha já havia derrotado a URSS quando Pearl Harbor aconteceu." },
      { id: "D", text: "Os EUA entraram na guerra para apoiar o Japão contra a Grã-Bretanha no Pacífico." },
    ],
    correctAnswer: "A",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "O HOLOCAUSTO foi o genocídio sistemático de judeus e outros grupos pelos nazistas. Quantas vítimas ele teve?",
    tip: "O Holocausto foi o maior genocídio da história moderna. Qual é o número de judeus mortos?",
    funFact: "\"Você Sabia?\" — Auschwitz-Birkenau era o maior campo de extermínio — 1,1 milhão de pessoas foram assassinadas lá, a maioria judeus. O Zyklon B (gás) matava em 15-20 minutos. Os corpos eram cremados em fornos industriais. As cinzas eram usadas como fertilizante ou descartadas em rios. Quando o Exército soviético libertou Auschwitz em janeiro de 1945, encontrou 7.000 sobreviventes esqueletos, 370.000 ternos masculinos, 837.000 roupas femininas e 7 toneladas de cabelo humano.",
    points: 1,
    options: [
      { id: "A", text: "Aproximadamente 500.000 judeus foram mortos, principalmente em batalhas urbanas durante a invasão da Polônia." },
      { id: "B", text: "Cerca de 6 milhões de judeus foram sistematicamente assassinados em campos de extermínio, fuzilamentos em massa e ghetos — além de 5-6 milhões de outras vítimas (ciganos, eslavos, deficientes, homossexuais, opositores políticos)." },
      { id: "C", text: "O número exato de mortos nunca foi apurado, mas estima-se entre 200.000 e 1 milhão de vítimas." },
      { id: "D", text: "Apenas soldados judeus do exército britânico foram mortos — civis judeus foram protegidos pelos acordos de Genebra." },
    ],
    correctAnswer: "B",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "A BATALHA DE STALINGRADO (agosto 1942 – fevereiro 1943) foi um ponto de virada decisivo na guerra. Por quê?",
    tip: "Uma das maiores e mais sangrentas batalhas da história — qual foi o resultado e o que ele significou?",
    funFact: "\"Você Sabia?\" — A Batalha de Stalingrado foi a mais sangrenta da Segunda Guerra: ~2 milhões de mortos dos dois lados. Os soldados alemães do 6º Exército foram cercados pelo general soviético Zukov numa operação chamada 'Uranus'. Hitler proibiu a retirada: 'Não darão um passo atrás'. Em fevereiro de 1943, o Marechal Paulus se rendeu com 91.000 soldados (de 330.000 que entraram na batalha). Foi a primeira grande rendição alemã da guerra — e o ponto em que ficou claro que a Alemanha não venceria.",
    points: 1,
    options: [
      { id: "A", text: "Vitória alemã que abriu o caminho para a captura dos campos de petróleo do Cáucaso soviético." },
      { id: "B", text: "Batalha naval em que a URSS destruiu a frota alemã no Mar Negro, isolando o exército alemão." },
      { id: "C", text: "Derrota devastadora da Alemanha na URSS — o 6º Exército alemão foi cercado e forçado a se render, marcando o início da ofensiva soviética que não parou até Berlim." },
      { id: "D", text: "Vitória aliada na África do Norte que abriu o caminho para a invasão da Itália em 1943." },
    ],
    correctAnswer: "C",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "O DIA D (6 de junho de 1944) — o desembarque na Normandia — foi a maior operação anfíbia da história. O que representou?",
    tip: "Mais de 150.000 soldados aliados desembarcaram nas praias da França nesse dia — qual foi a importância estratégica?",
    funFact: "\"Você Sabia?\" — A Operação Overlord (Dia D) envolveu 5.000 navios, 11.000 aviões e 156.000 soldados nas primeiras 24 horas. Na Praia de Omaha, as perdas americanas foram terríveis: 2.000 mortos numa única manhã. O sucesso do desembarque dependeu parcialmente de uma enorme operação de desinformação ('Operação Fortitude') que convenceu Hitler de que o verdadeiro desembarque seria em Pas-de-Calais — ele manteve reservas lá por dias após o Dia D, perdendo a chance de contra-atacar.",
    points: 1,
    options: [
      { id: "A", text: "Rendição da Itália às forças aliadas após invasão pelo sul — a Itália mudou de lado e declarou guerra à Alemanha." },
      { id: "B", text: "Início da ofensiva soviética que capturou Berlim — o Exército Vermelho invadiu a Alemanha pelo lado leste." },
      { id: "C", text: "Batalha naval aliada que destruiu a Marinha alemã no Atlântico, garantindo as rotas de suprimento." },
      { id: "D", text: "Abertura da frente ocidental na França — criou uma guerra em dois frontes para a Alemanha (soviéticos a leste, aliados ocidentais a oeste) que tornava a derrota alemã inevitável." },
    ],
    correctAnswer: "D",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "O fim da Segunda Guerra Mundial na Europa ocorreu em maio de 1945. Como a guerra na Europa terminou?",
    tip: "O que aconteceu com Hitler e com o governo nazista nos últimos dias de abril e início de maio de 1945?",
    funFact: "\"Você Sabia?\" — Hitler se suicidou no bunker da chancelaria em Berlim em 30 de abril de 1945, com as tropas soviéticas a menos de 500 metros. Eva Braun (sua companheira, recém-casada) morreu junto. Seus corpos foram queimados no jardim. Em 8 de maio de 1945 (V-E Day — Victory in Europe Day), a Alemanha assinou a rendição incondicional. A Segunda Guerra na Europa durou exatamente 5 anos, 8 meses e 7 dias.",
    points: 1,
    options: [
      { id: "A", text: "Rendição incondicional da Alemanha em maio de 1945 — Hitler se suicidou em Berlim, cercado pelo Exército Vermelho, e o III Reich capitulou após 6 anos de guerra." },
      { id: "B", text: "Bomba atômica lançada sobre Berlim em abril de 1945 pelos EUA, destruindo o governo nazista instantaneamente." },
      { id: "C", text: "Negociação de paz entre Hitler e os Aliados Ocidentais, com os soviéticos excluídos do acordo final." },
      { id: "D", text: "Golpe militar dos generais alemães que prenderam Hitler e negociaram a rendição separadamente com cada país aliado." },
    ],
    correctAnswer: "A",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "A bomba atômica foi lançada pelos EUA sobre o JAPÃO em agosto de 1945. O que isso representou?",
    tip: "Duas cidades japonesas foram destruídas — qual foi o impacto sobre a guerra e sobre o futuro das relações internacionais?",
    funFact: "\"Você Sabia?\" — Hiroshima (6/8/1945) e Nagasaki (9/8/1945) — as duas únicas vezes que armas nucleares foram usadas em guerra. A bomba de Hiroshima (Little Boy) matou 70.000 pessoas instantaneamente; no total, 140.000 morreram até o fim de 1945. A bomba de Nagasaki (Fat Man) matou 40.000-80.000. O imperador Hirohito anunciou a rendição em 15/8 no rádio — a primeira vez que os japoneses ouviam a voz do imperador, que era considerado divino. A Segunda Guerra terminou em 2 de setembro de 1945.",
    points: 1,
    options: [
      { id: "A", text: "As bombas atômicas não mudaram o resultado da guerra — o Japão já havia capitulado antes do lançamento." },
      { id: "B", text: "O lançamento das bombas atômicas sobre Hiroshima e Nagasaki forçou a rendição japonesa, encerrando a Segunda Guerra Mundial e inaugurando a era nuclear — com impacto sobre toda a política internacional posterior." },
      { id: "C", text: "As bombas foram usadas em Tóquio, capital do Japão, destruindo o governo imperial japonês instantaneamente." },
      { id: "D", text: "O Japão ignorou as bombas atômicas e só capitulou após a invasão terrestre americana do arquipélago japonês." },
    ],
    correctAnswer: "B",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "A ONU (Organização das Nações Unidas) foi criada em 1945. Quais foram suas diferenças em relação à Liga das Nações?",
    tip: "Por que a ONU foi criada para substituir a Liga das Nações? O que ela fez de diferente?",
    funFact: "\"Você Sabia?\" — A Carta da ONU foi assinada em São Francisco em 26 de junho de 1945, por 50 países. O Conselho de Segurança tem 5 membros permanentes com poder de veto: EUA, URSS (hoje Rússia), China, França e Reino Unido. O Brasil queria um assento permanente — Vargas negociou, mas os EUA recusaram. Hoje, o Brasil ainda reivindica um assento permanente. A ONU tem 193 membros — praticamente todos os países do mundo. A Liga das Nações nunca passou de 60 membros.",
    points: 1,
    options: [
      { id: "A", text: "A ONU era um exército internacional permanente criado para intervir militarmente em qualquer conflito no mundo." },
      { id: "B", text: "A ONU era exclusiva para países vencedores da guerra — países derrotados jamais poderiam se tornar membros." },
      { id: "C", text: "A ONU incluía os EUA como membro fundador e tinha o Conselho de Segurança com poder de veto para as grandes potências — corrigindo as principais fraquezas da Liga das Nações." },
      { id: "D", text: "A ONU foi criada apenas como organização econômica — sem competência política ou militar, apenas para reconstruir a economia mundial." },
    ],
    correctAnswer: "C",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "O TRIBUNAL DE NUREMBERG (1945-1946) julgou os líderes nazistas. Qual foi a importância histórica desse julgamento?",
    tip: "Pela primeira vez na história, líderes de Estado foram julgados por crimes cometidos durante a guerra — qual foi o impacto desse precedente?",
    funFact: "\"Você Sabia?\" — 24 dos principais líderes nazistas foram julgados em Nuremberg. Hermann Göring foi condenado à morte mas se suicidou com cianeto escondido no dente horas antes. Rudolf Hess foi condenado à prisão perpétua e ficou na Prisão de Spandau (Berlim Ocidental) até 1987 — quando se suicidou com 93 anos, o último prisioneiro de guerra da Segunda Guerra. O julgamento de Nuremberg criou o conceito de 'crimes contra a humanidade' que usamos até hoje.",
    points: 1,
    options: [
      { id: "A", text: "Estabeleceu que líderes militares nunca podem ser responsabilizados por ordens cumpridas durante guerras." },
      { id: "B", text: "Criou o conceito de 'crimes contra a humanidade' e o precedente de que líderes de Estado podem ser julgados internacionalmente — base do Tribunal Penal Internacional criado em 2002." },
      { id: "C", text: "Absolveu todos os acusados por falta de provas, já que os nazistas destruíram todos os documentos." },
      { id: "D", text: "Foi usado apenas como propaganda aliada sem validade jurídica real — as sentenças nunca foram executadas." },
    ],
    correctAnswer: "A",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "Qual foi o saldo total de MORTES da Segunda Guerra Mundial?",
    tip: "A Segunda Guerra foi muito mais mortífera que a Primeira — qual é a estimativa de mortes totais (soldados + civis)?",
    funFact: "\"Você Sabia?\" — A URSS perdeu mais pessoas na Segunda Guerra do que qualquer outro país: 27 milhões de mortos (11% da população). Por isso, os soviéticos chamam de 'Grande Guerra Patriótica' — foi literalmente uma luta pela sobrevivência do país. Cada família soviética perdeu alguém. Em contraste, os EUA perderam 405.000 pessoas — devastador, mas 0,3% da população. Essa diferença de sacrifício molda até hoje as perspectivas americanas e russas sobre guerras.",
    points: 1,
    options: [
      { id: "A", text: "Aproximadamente 5 milhões de mortos no total, principalmente militares — número semelhante à Primeira Guerra." },
      { id: "B", text: "Cerca de 10 milhões de mortos, sendo a maioria vítimas do Holocausto e dos campos de extermínio nazistas." },
      { id: "C", text: "Menos de 2 milhões de mortos civis, pois a guerra foi travada principalmente em áreas despovoadas." },
      { id: "D", text: "Estimativa de 70-85 milhões de mortos (2/3 civis) — a mais mortífera da história humana, resultado do genocídio, bombardeios de cidades, fome e doenças em larga escala." },
    ],
    correctAnswer: "D",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "A DECLARAÇÃO UNIVERSAL DOS DIREITOS HUMANOS foi adotada pela ONU em 1948. O que ela representa?",
    tip: "Por que era necessário criar um documento internacional de direitos humanos justamente após a Segunda Guerra?",
    funFact: "\"Você Sabia?\" — A Declaração Universal foi redigida em parte por Hansa Mehta (Índia) e Eleanor Roosevelt (EUA). O artigo 1 diz: 'Todos os seres humanos nascem livres e iguais em dignidade e em direitos'. Foi uma resposta direta ao Holocausto — os nazistas haviam mostrado o que acontece quando o Estado decide que alguns seres humanos não têm direitos. Hoje, é o documento mais traduzido do mundo (mais de 500 idiomas) — mas não tem força de lei vinculante, o que limita sua eficácia prática.",
    points: 1,
    options: [
      { id: "A", text: "Tratado militar entre os países aliados para garantir segurança coletiva contra uma nova agressão alemã." },
      { id: "B", text: "Documento que reconhece universalmente que todos os seres humanos têm direitos inalienáveis — resposta direta às atrocidades nazistas e ao Holocausto, criando padrões internacionais mínimos." },
      { id: "C", text: "Acordo econômico para reconstrução da Europa com financiamento americano após a Segunda Guerra." },
      { id: "D", text: "Tratado de paz entre as potências vencedoras e as nações derrotadas da Segunda Guerra Mundial." },
    ],
    correctAnswer: "B",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "O PLANO MARSHALL (1948) foi um programa americano de ajuda econômica à Europa. Qual era seu objetivo?",
    tip: "Além de reconstruir a Europa, qual era o objetivo político do Plano Marshall no contexto do início da Guerra Fria?",
    funFact: "\"Você Sabia?\" — O Plano Marshall injetou US$ 13 bilhões na Europa Ocidental entre 1948 e 1952 (equivalente a ~160 bilhões de dólares atuais). Alemanha e Japão (países derrotados!) também receberam ajuda — para se tornarem aliados democráticos contra a URSS. George Marshall, o secretário de Estado, ganhou o Nobel da Paz em 1953 pelo programa. A URSS recusou o Plano Marshall e proibiu os países da Europa Oriental de aceitá-lo — criando dois blocos econômicos separados.",
    points: 1,
    options: [
      { id: "A", text: "Programa para rearmamento imediato da Europa Ocidental para enfrentar militarmente a URSS." },
      { id: "B", text: "Plano de reparações de guerra que obrigava os países derrotados a pagar pelos danos causados aos aliados." },
      { id: "C", text: "Reconstrução econômica da Europa Ocidental pós-guerra — com objetivo duplo de evitar que a miséria empurrasse países para o comunismo e criar mercados consumidores para a economia americana." },
      { id: "D", text: "Programa de colonização americana da Europa Ocidental, transformando os países europeus em protetorados dos EUA." },
    ],
    correctAnswer: "C",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "O FASCISMO ITALIANO de Mussolini (1922-1943) foi o primeiro regime fascista da história. O que foi o 'corporativismo' fascista?",
    tip: "Como o fascismo organizava as relações entre trabalhadores, patrões e Estado — diferente tanto do capitalismo puro quanto do socialismo?",
    funFact: "\"Você Sabia?\" — O 'Homo Fascistus' de Mussolini deveria ser um guerreiro sempre pronto para morrer pela Itália. O lema fascista era 'Credere, Obbedire, Combattere' (Crer, Obedecer, Combater). Mussolini disse: 'A guerra é para o homem o que a maternidade é para a mulher.' Os fascistas foram os primeiros a criar campos de verão para crianças com treinamento paramilitar, uniformes e hinos — a 'balilla' (8-14 anos) e os 'avanguardisti' (14-18 anos) alistavam compulsoriamente todas as crianças italianas.",
    points: 1,
    options: [
      { id: "A", text: "Sistema em que o Estado planejava toda a economia, como na URSS, mas com propriedade privada mantida formalmente." },
      { id: "B", text: "Modelo econômico em que trabalhadores e patrões organizavam sindicatos independentes para negociar salários livremente." },
      { id: "C", text: "Política de nacionalização completa de todas as empresas, com o Estado assumindo a propriedade dos meios de produção." },
      { id: "D", text: "Sistema que substituía a luta de classes por 'corporações' controladas pelo Estado, unindo trabalhadores e patrões sob supervisão do regime — eliminando sindicatos autônomos e greves." },
    ],
    correctAnswer: "D",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "As LEIS DE NUREMBERG (1935) foram uma escalada da perseguição nazista aos judeus. O que elas determinavam?",
    tip: "Como as Leis de Nuremberg transformaram a discriminação social em discriminação legal?",
    funFact: "\"Você Sabia?\" — As Leis de Nuremberg definiram 'judeu' de forma burocrática: quem tinha 3 ou 4 avós judeus era judeu; 2 avós era 'mischlinge' (mestiço). Famílias que haviam se convertido ao cristianismo há gerações descobriram que eram 'judias' pelo critério nazista. A burocracia da perseguição envolveu milhares de funcionários públicos que verificavam genealogias — mostrando que o Holocausto não foi ato de loucos, mas de um Estado burocrático funcionando normalmente.",
    points: 1,
    options: [
      { id: "A", text: "Regulamentavam a organização dos julgamentos dos líderes nazistas após a derrota alemã na guerra." },
      { id: "B", text: "Retiravam a cidadania alemã dos judeus, proibiam casamentos e relações sexuais entre judeus e alemães — transformando a discriminação em lei do Estado." },
      { id: "C", text: "Determinavam as regras de produção de armamentos para a guerra que a Alemanha já planejava secretamente." },
      { id: "D", text: "Estabeleciam as diretrizes do partido nazista para candidatos a cargos públicos em eleições locais." },
    ],
    correctAnswer: "B",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "O conceito de LEBENSRAUM ('espaço vital') era central na ideologia nazista. O que significava?",
    tip: "Hitler acreditava que o povo alemão precisava de mais território — onde ele pretendia consegui-lo e às custas de quem?",
    funFact: "\"Você Sabia?\" — O conceito de Lebensraum vinha do geógrafo Friedrich Ratzel do século XIX — Hitler o distorceu para criar uma justificativa pseudocientífica para a conquista do leste europeu. O plano 'Generalplan Ost' previa o extermínio ou escravização de 80% dos poloneses, 50% dos tchecos e a maioria dos russos, ucranianos e bielorrussos — para 'liberar espaço' para colonos alemães. Se Hitler tivesse vencido, seria o maior genocídio da história.",
    points: 1,
    options: [
      { id: "A", text: "A conquista do espaço sideral — a ideia nazista de que a Alemanha deveria ser a primeira nação a alcançar as estrelas." },
      { id: "B", text: "O conceito de que a Alemanha precisava expandir para o leste europeu (especialmente URSS) para garantir território e recursos para o povo alemão — justificativa para a invasão e expulsão/extermínio dos povos eslavos." },
      { id: "C", text: "A política nazista de criar colônias agrícolas na África para os alemães que não tinham terras na Europa." },
      { id: "D", text: "A teoria de que os alemães tinham o direito divino de dominar os mares e o comércio internacional." },
    ],
    correctAnswer: "A",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "O EIXO (Alemanha, Itália e Japão) foi a aliança que disputou a Segunda Guerra contra os Aliados. O que unia esses países?",
    tip: "Quais valores políticos e objetivos estratégicos aproximaram Alemanha, Itália e Japão?",
    funFact: "\"Você Sabia?\" — O Pacto Tripartite (setembro de 1940) criou formalmente o Eixo. Na prática, a aliança era frágil: Mussolini só entrou na guerra quando a França estava quase derrotada (junho de 1940) — chamado por Churchill de 'punhal nas costas'. O Japão sequer consultou a Alemanha antes de Pearl Harbor. Quando a Itália capitulou em 1943, Mussolini foi preso pelo próprio rei italiano. Hitler resgatou-o de helicóptero numa operação de commando. Mussolini foi fuzilado por partisans italianos em abril de 1945.",
    points: 1,
    options: [
      { id: "A", text: "Eles eram as três maiores democracias do mundo e se uniram para defender o liberalismo contra o comunismo soviético." },
      { id: "B", text: "Os três países eram potências coloniais decadentes que buscavam reconquistar suas antigas colônias perdidas no século XIX." },
      { id: "C", text: "Os três países eram regimes autoritários expansionistas insatisfeitos com a ordem internacional pós-1919, querendo redividir o mundo por meio da força." },
      { id: "D", text: "Eram aliados desde a Primeira Guerra Mundial — o Eixo era a continuação da antiga Tríplice Aliança com a inclusão do Japão." },
    ],
    correctAnswer: "C",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "A FRENTE AFRICANA (1940-1943) envolveu batalhas no norte da África entre Aliados e Eixo. Qual foi sua importância estratégica?",
    tip: "Por que britânicos e alemães lutaram no deserto africano — o que estava em jogo no Canal de Suez?",
    funFact: "\"Você Sabia?\" — Erwin Rommel, o 'Raposa do Deserto', liderou o Afrika Korps com táticas de Blitzkrieg adaptadas ao deserto — vencendo batalhas com forças inferiores. Bernard Montgomery (britânico) o derrotou em El-Alamein com superioridade numérica e logística. Churchill disse: 'Antes de Alamein, nunca tivemos uma vitória. Depois de Alamein, nunca tivemos uma derrota.' A derrota alemã na África abriu o caminho para a invasão da Itália em 1943.",
    points: 1,
    options: [
      { id: "A", text: "Era uma campanha secundária sem importância estratégica real — servia apenas para desviar forças alemãs da frente soviética." },
      { id: "B", text: "A vitória na África garantiria à Alemanha e Itália o controle do Canal de Suez e do petróleo do Oriente Médio — cortando a ligação britânica com a Índia e o Pacífico." },
      { id: "C", text: "O objetivo era conquistar o ouro e os diamantes sul-africanos para financiar a continuação da guerra alemã." },
      { id: "D", text: "A Frente Africana foi onde os EUA estrearam na guerra, testando equipamentos e táticas antes do Dia D." },
    ],
    correctAnswer: "D",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "A RESISTÊNCIA europeia aos nazistas foi um movimento organizado de civis e militares. Quais formas ela assumiu?",
    tip: "Como os europeus que viviam sob ocupação alemã se opuseram ao regime nazista?",
    funFact: "\"Você Sabia?\" — Na França ocupada, a Résistance organizou células de sabotagem, redes de fuga para pilotos aliados abatidos e informações para o Dia D. Charles de Gaulle, de Londres, coordenava a resistência externa. Na Polônia, o Levante de Varsóvia (1944) foi a maior revolta urbana contra os nazistas — 200.000 poloneses morreram. Os partisans iugoslavos de Tito liberaram a Iugoslávia quase sem ajuda externa. Sophie Scholl, da 'Rosa Branca' alemã, foi guilhotinada aos 21 anos por distribuir panfletos contra Hitler.",
    points: 1,
    options: [
      { id: "A", text: "A resistência foi apenas diplomática — os países ocupados pressionavam a Alemanha por canais diplomáticos." },
      { id: "B", text: "Sabotagem industrial, redes de espionagem e fuga de aliados, publicação clandestina, levantes armados (como o Levante de Varsóvia) e proteção de judeus — a resistência assumiu múltiplas formas nos países ocupados." },
      { id: "C", text: "A resistência foi exclusivamente dos exércitos regulares que se retiraram para a Inglaterra e continuaram lutando." },
      { id: "D", text: "Não houve resistência organizada — as populações europeias colaboraram amplamente com a ocupação nazista." },
    ],
    correctAnswer: "B",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "O COLABORACIONISMO foi uma resposta de alguns governos e cidadãos à ocupação nazista. O que significava?",
    tip: "Nem todos os ocupados resistiram — alguns colaboraram com os nazistas. Quais eram suas motivações?",
    funFact: "\"Você Sabia?\" — O governo de Vichy (França, 1940-1944), liderado pelo Marechal Pétain, não foi forçado pelos alemães a deportar judeus franceses — fez isso voluntariamente, muitas vezes com mais eficiência do que os próprios nazistas pediam. 77.000 judeus franceses foram deportados, a maioria para Auschwitz, por funcionários franceses. Só em 1995 o presidente francês Chirac reconheceu formalmente a responsabilidade do Estado francês — 50 anos depois.",
    points: 1,
    options: [
      { id: "A", text: "Estratégia de fingir cooperação com os nazistas enquanto secretamente enviava informações para os aliados." },
      { id: "B", text: "Resistência passiva — colaborar superficialmente para evitar represálias enquanto se recusava a executar as ordens mais extremas." },
      { id: "C", text: "Cooperação ativa de governos e cidadãos com os nazistas — por convicção ideológica, oportunismo ou medo — como o governo de Vichy na França, que deportou judeus voluntariamente." },
      { id: "D", text: "Movimento internacional que buscava mediar a paz entre nazistas e aliados para evitar mais mortes." },
    ],
    correctAnswer: "C",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "O NAZISMO usou a pseudociência para justificar suas políticas raciais. Como?",
    tip: "O que os nazistas chamavam de 'higiene racial' e como justificavam o extermínio cientificamente?",
    funFact: "\"Você Sabia?\" — O Dr. Josef Mengele ('Anjo da Morte') de Auschwitz realizou 'experimentos médicos' em prisioneiros sem anestesia — especialmente em gêmeos. Seus 'estudos' não tinham valor científico algum, mas eram justificados como pesquisa racial. Após a guerra, fugiu para a América do Sul (Argentina, depois Brasil e Paraguai) com ajuda da rede Odessa. Morreu afogado no Brasil em 1979, nunca julgado. Seus 'experimentos' levaram à criação do Código de Nuremberg — primeiros protocolos de ética médica da história.",
    points: 1,
    options: [
      { id: "A", text: "Os nazistas distorceram a teoria da evolução de Darwin para 'provar' que judeus e povos eslavos eram 'sub-humanos' biologicamente inferiores — justificando extermínio e experimentos em campos de concentração." },
      { id: "B", text: "Os nazistas usaram astrologia e misticismo ariano para convencer a população de que Hitler tinha poderes divinos." },
      { id: "C", text: "A pseudociência nazista baseava-se em numerologia para determinar quais grupos eram 'destinados' a dominar." },
      { id: "D", text: "Os nazistas negavam qualquer base científica para suas políticas — admitiam abertamente que eram movidas apenas pela crença." },
    ],
    correctAnswer: "A",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "A QUESTÃO ALEMÃ após 1945: como os Aliados decidiram tratar a Alemanha derrotada?",
    tip: "Os Aliados aprenderam com os erros do Tratado de Versalhes (1919)? Como trataram a Alemanha desta vez?",
    funFact: "\"Você Sabia?\" — A Alemanha foi dividida em 4 zonas de ocupação (EUA, URSS, França, GB). Berlim, dentro da zona soviética, também foi dividida em 4 setores. Em 1949, as 3 zonas ocidentais se tornaram a Alemanha Ocidental (RFA) e a zona soviética se tornou a Alemanha Oriental (RDA). Em 1961, a URSS construiu o Muro de Berlim para impedir a fuga de alemães orientais para o Ocidente. A Alemanha só se reunificou em outubro de 1990 — 45 anos após o fim da guerra.",
    points: 1,
    options: [
      { id: "A", text: "Impuseram um Tratado de Paz humilhante como Versalhes, com enormes reparações que destruíram a economia alemã." },
      { id: "B", text: "Permitiram que a Alemanha reconstruísse imediatamente sua soberania total e seu exército para conter a URSS." },
      { id: "C", text: "Destruíram completamente a Alemanha como Estado — o país foi dividido e seus territórios distribuídos entre vizinhos." },
      { id: "D", text: "Ocuparam militarmente a Alemanha, a dividiram em zonas de ocupação, a desnazificaram e depois a reconstruíram — com o Plano Marshall para a parte ocidental — aprendendo as lições de Versalhes." },
    ],
    correctAnswer: "D",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Qual foi a principal LIÇÃO HISTÓRICA da Segunda Guerra Mundial que moldou as instituições internacionais criadas em 1945?",
    tip: "Por que a comunidade internacional criou a ONU, a Declaração Universal dos Direitos Humanos e o Tribunal de Nuremberg?",
    funFact: "\"Você Sabia?\" — A expressão 'Nunca mais' (Never Again) tornou-se o símbolo dos sobreviventes do Holocausto e da promessa da humanidade após 1945. Mas genocídios continuaram: Camboja (1975-79, 2M mortos), Ruanda (1994, 800.000 em 100 dias), Bósnia (1992-95, 100.000 mortos). A promessa 'nunca mais' ainda não foi cumprida — mostrando que a criação de instituições internacionais é necessária mas não suficiente sem vontade política para usá-las.",
    points: 1,
    options: [
      { id: "A", text: "Que guerras são inevitáveis e o melhor caminho é garantir superioridade militar permanente sobre possíveis adversários." },
      { id: "B", text: "Que a comunidade internacional deve criar mecanismos para responsabilizar Estados e líderes por violações aos direitos humanos, e cooperar para prevenir conflitos antes que se tornem guerras mundiais." },
      { id: "C", text: "Que regimes autoritários são mais eficientes que democracias e devem ser tolerados desde que não ameacem países vizinhos." },
      { id: "D", text: "Que o poder nuclear é o único garantidor de paz — somente países com armas atômicas podem dissuadir agressores." },
    ],
    correctAnswer: "B",
  },
];
