export const questoesMatematica9AnoB2Av2 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "Uma EQUAÇÃO IRRACIONAL é uma equação em que a incógnita:",
    tip: "Pense no que diferencia uma equação irracional das demais — onde a variável está?",
    funFact: "\"Você Sabia?\" — Equações irracionais aparecem na física ao calcular o período de um pêndulo simples: T = 2π√(L/g), onde resolver para L resulta em uma equação irracional.",
    points: 1,
    options: [
      { id: "A", text: "Aparece sob um radical (dentro de uma raiz)." },
      { id: "B", text: "Tem expoente negativo." },
      { id: "C", text: "Está no denominador de uma fração." },
      { id: "D", text: "Aparece elevada a um expoente fracionário maior que 2." },
    ],
    correctAnswer: "A",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "Para resolver √(x + 3) = 4, qual é o primeiro passo?",
    tip: "Para eliminar o radical, você precisa fazer a operação inversa.",
    funFact: "\"Você Sabia?\" — Ao elevar ao quadrado para eliminar raízes, é fundamental verificar a solução obtida, pois elevar ao quadrado pode introduzir soluções estranhas (raízes extrâneas).",
    points: 1,
    options: [
      { id: "A", text: "Subtrair 3 dos dois lados." },
      { id: "B", text: "Multiplicar os dois lados por √(x + 3)." },
      { id: "C", text: "Elevar os dois lados ao quadrado para eliminar a raiz." },
      { id: "D", text: "Somar 4 aos dois lados." },
    ],
    correctAnswer: "C",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "Resolva a equação irracional √x = 5:",
    tip: "Eleve os dois lados ao quadrado e verifique a solução.",
    funFact: "\"Você Sabia?\" — A condição de existência da raiz quadrada (radicando ≥ 0) é sempre necessária, mas para √x = 5, a condição adicional é que 5 ≥ 0, o que é verdade, então a solução existe.",
    points: 1,
    options: [
      { id: "A", text: "x = 10" },
      { id: "B", text: "x = 25" },
      { id: "C", text: "x = ±5" },
      { id: "D", text: "x = √5" },
    ],
    correctAnswer: "B",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "Ao resolver equações irracionais, por que é OBRIGATÓRIO verificar as soluções encontradas?",
    tip: "Elevar ao quadrado é uma operação que pode 'criar' soluções falsas.",
    funFact: "\"Você Sabia?\" — Uma 'solução estranha' é um valor que satisfaz a equação após transformação, mas não satisfaz a original. Por exemplo, elevar √x = −3 ao quadrado dá x = 9, mas √9 = 3 ≠ −3.",
    points: 1,
    options: [
      { id: "A", text: "Porque a calculadora pode errar." },
      { id: "B", text: "Por exigência formal, mas todas as soluções sempre são válidas." },
      { id: "C", text: "Porque o radical pode ser negativo." },
      { id: "D", text: "Porque elevar ao quadrado pode introduzir raízes extrâneas que não satisfazem a equação original." },
    ],
    correctAnswer: "D",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "Resolva √(2x − 1) = 3:",
    tip: "Eleve ao quadrado: 2x − 1 = 9. Resolva para x e verifique.",
    funFact: "\"Você Sabia?\" — Verificação: √(2(5) − 1) = √9 = 3 ✓. A verificação confirma que x = 5 é válida e não é uma raiz estranha.",
    points: 1,
    options: [
      { id: "A", text: "x = 5" },
      { id: "B", text: "x = 4" },
      { id: "C", text: "x = 10" },
      { id: "D", text: "x = 2" },
    ],
    correctAnswer: "A",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "Uma equação fracionária é uma equação em que a incógnita aparece no denominador. A condição de existência exige que:",
    tip: "Dividir por zero não é definido em matemática — o que isso implica para os denominadores?",
    funFact: "\"Você Sabia?\" — A condição de existência em equações fracionárias (denominador ≠ 0) é análoga ao domínio de uma função racional — valores que tornam o denominador zero estão excluídos.",
    points: 1,
    options: [
      { id: "A", text: "O numerador seja diferente de zero." },
      { id: "B", text: "A equação tenha pelo menos uma solução." },
      { id: "C", text: "Todos os denominadores sejam diferentes de zero." },
      { id: "D", text: "A incógnita seja um número inteiro positivo." },
    ],
    correctAnswer: "C",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "Para resolver uma equação fracionária, o método mais eficiente é:",
    tip: "Pense em como eliminar os denominadores de uma vez.",
    funFact: "\"Você Sabia?\" — Multiplicar pelo MMC dos denominadores transforma a equação fracionária em uma equação polinomial mais simples de resolver — é como 'limpar' os denominadores.",
    points: 1,
    options: [
      { id: "A", text: "Somar todas as frações e igualar ao numerador total." },
      { id: "B", text: "Multiplicar todos os membros pelo MMC dos denominadores para eliminá-los." },
      { id: "C", text: "Dividir ambos os lados pelo maior denominador." },
      { id: "D", text: "Elevar todos os termos ao quadrado para eliminar as frações." },
    ],
    correctAnswer: "B",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "Resolva √(x + 6) = x:",
    tip: "Eleve ao quadrado: x + 6 = x². Reorganize: x² − x − 6 = 0. Resolva e VERIFIQUE cada solução.",
    funFact: "\"Você Sabia?\" — Para √(x+6) = x, elevar ao quadrado dá x²−x−6=0, com raízes 3 e −2. Verificação: √(3+6)=3 ✓ mas √(−2+6)=2≠−2 ✗. A raiz estranha x=−2 é descartada.",
    points: 1,
    options: [
      { id: "A", text: "x = 3 (apenas, pois x = −2 é estranha: √4 = 2 ≠ −2)" },
      { id: "B", text: "x = −2 (apenas, pois x = 3 é estranha)" },
      { id: "C", text: "x = 3 e x = −2 (ambas válidas)" },
      { id: "D", text: "Nenhuma solução real." },
    ],
    correctAnswer: "A",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "Um SISTEMA DE EQUAÇÕES do 1º grau com duas variáveis tem solução ÚNICA quando as retas representadas pelos dois gráficos:",
    tip: "Pense geometricamente: duas retas no plano cartesiano podem se relacionar de três formas.",
    funFact: "\"Você Sabia?\" — A análise geométrica de sistemas lineares foi desenvolvida por René Descartes no século XVII, quando ele criou o plano cartesiano, unindo álgebra e geometria.",
    points: 1,
    options: [
      { id: "A", text: "São paralelas (nunca se encontram)." },
      { id: "B", text: "São coincidentes (sobrepostas)." },
      { id: "C", text: "Não existem no mesmo plano." },
      { id: "D", text: "São concorrentes (se cruzam em um único ponto)." },
    ],
    correctAnswer: "D",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "O MÉTODO DA SUBSTITUIÇÃO para resolver sistemas consiste em:",
    tip: "Substituição significa trocar — o que você troca?",
    funFact: "\"Você Sabia?\" — O método da substituição é atribuído ao matemático árabe Al-Khwarizmi (século IX), considerado o 'pai da álgebra', cujo nome deu origem à palavra 'algoritmo'.",
    points: 1,
    options: [
      { id: "A", text: "Somar as duas equações diretamente para eliminar uma variável." },
      { id: "B", text: "Multiplicar as equações e simplificar os termos comuns." },
      { id: "C", text: "Isolar uma variável em uma equação e substituir na outra." },
      { id: "D", text: "Dividir uma equação pela outra para encontrar a relação entre as variáveis." },
    ],
    correctAnswer: "C",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Resolva o sistema por substituição: { x + y = 10 ; x − y = 4 }",
    tip: "Da primeira equação: x = 10 − y. Substitua na segunda: (10 − y) − y = 4.",
    funFact: "\"Você Sabia?\" — Este sistema tem solução x=7, y=3. Verificação: 7+3=10 ✓ e 7−3=4 ✓. Sempre substitua as soluções em AMBAS as equações para confirmar.",
    points: 1,
    options: [
      { id: "A", text: "x = 6 e y = 4" },
      { id: "B", text: "x = 5 e y = 5" },
      { id: "C", text: "x = 8 e y = 2" },
      { id: "D", text: "x = 7 e y = 3" },
    ],
    correctAnswer: "D",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "O MÉTODO DA ADIÇÃO (ou eliminação) para resolver sistemas consiste em:",
    tip: "Adição = somar. O que você faz com as equações para eliminar uma variável?",
    funFact: "\"Você Sabia?\" — O método da adição é sistematizado na 'eliminação gaussiana', desenvolvida por Carl Friedrich Gauss, e é a base dos algoritmos computacionais para resolver sistemas com centenas de variáveis.",
    points: 1,
    options: [
      { id: "A", text: "Isolar uma variável e substituir na outra equação." },
      { id: "B", text: "Adicionar (ou subtrair) as equações de modo que uma variável seja eliminada." },
      { id: "C", text: "Multiplicar ambas as equações pelo mesmo número." },
      { id: "D", text: "Dividir uma equação pela outra." },
    ],
    correctAnswer: "B",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "Resolva o sistema pelo método da adição: { 2x + y = 7 ; x − y = 2 }",
    tip: "Some as duas equações diretamente — o y é eliminado! Depois encontre y.",
    funFact: "\"Você Sabia?\" — Quando uma variável tem coeficientes opostos (+y e −y), basta somar. Quando os coeficientes não são opostos, você precisa multiplicar uma ou ambas as equações antes de somar.",
    points: 1,
    options: [
      { id: "A", text: "x = 3 e y = 1" },
      { id: "B", text: "x = 2 e y = 3" },
      { id: "C", text: "x = 4 e y = −1" },
      { id: "D", text: "x = 5 e y = −3" },
    ],
    correctAnswer: "A",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "Um sistema de equações é IMPOSSÍVEL quando as retas são paralelas. O que isso significa em termos algébricos?",
    tip: "Paralelas = mesma inclinação, pontos de intersecção diferentes.",
    funFact: "\"Você Sabia?\" — O sistema impossível surge quando tentamos resolver equações contraditórias: é como tentar encontrar um número que seja simultaneamente par e ímpar — é impossível.",
    points: 1,
    options: [
      { id: "A", text: "O sistema tem infinitas soluções." },
      { id: "B", text: "Ao tentar resolver, chegamos a uma igualdade verdadeira como 0 = 0." },
      { id: "C", text: "Ao tentar resolver, chegamos a uma igualdade falsa como 0 = 5." },
      { id: "D", text: "O sistema tem exatamente uma solução negativa." },
    ],
    correctAnswer: "C",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Um sistema é INDETERMINADO quando as retas são coincidentes. Qual é o conjunto solução?",
    tip: "Coincidentes = a mesma reta. Quantos pontos em comum têm?",
    funFact: "\"Você Sabia?\" — O sistema indeterminado tem infinitas soluções porque as duas equações representam a mesma reta — são múltiplos uma da outra. Por exemplo: y = 2x e 2y = 4x.",
    points: 1,
    options: [
      { id: "A", text: "Conjunto vazio (∅)." },
      { id: "B", text: "Apenas a solução (0, 0)." },
      { id: "C", text: "Exatamente dois pares ordenados." },
      { id: "D", text: "Infinitas soluções — todos os pontos da reta." },
    ],
    correctAnswer: "D",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "Resolva o sistema: { 3x − 2y = 5 ; x + y = 5 }",
    tip: "Da segunda equação: x = 5 − y. Substitua na primeira: 3(5 − y) − 2y = 5.",
    funFact: "\"Você Sabia?\" — Solução x=3, y=2. Verificação: 3(3)−2(2)=9−4=5 ✓ e 3+2=5 ✓. Com prática, a substituição se torna tão rápida quanto a adição.",
    points: 1,
    options: [
      { id: "A", text: "x = 5 e y = 0" },
      { id: "B", text: "x = 3 e y = 2" },
      { id: "C", text: "x = 2 e y = 3" },
      { id: "D", text: "x = 1 e y = 4" },
    ],
    correctAnswer: "B",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "Uma equação irracional do tipo √(ax + b) = c tem solução apenas quando:",
    tip: "O resultado da raiz quadrada é sempre não negativo — quando c pode ser resultado de uma raiz?",
    funFact: "\"Você Sabia?\" — A condição c ≥ 0 é muitas vezes esquecida. Por exemplo, √(x + 1) = −2 não tem solução em ℝ, pois uma raiz quadrada nunca é negativa.",
    points: 1,
    options: [
      { id: "A", text: "c ≥ 0 (o lado direito não pode ser negativo)." },
      { id: "B", text: "a > 0 (o coeficiente de x deve ser positivo)." },
      { id: "C", text: "b é um número par." },
      { id: "D", text: "c é um número inteiro." },
    ],
    correctAnswer: "A",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "Resolva a equação fracionária 3/x = 12 (x ≠ 0):",
    tip: "Multiplique ambos os lados por x para eliminar o denominador.",
    funFact: "\"Você Sabia?\" — Equações da forma k/x = c aparecem no cálculo de resistência elétrica em paralelo (1/R = 1/R₁ + 1/R₂) e na relação tempo-velocidade-distância (t = d/v).",
    points: 1,
    options: [
      { id: "A", text: "x = 36" },
      { id: "B", text: "x = 4" },
      { id: "C", text: "x = 1/4" },
      { id: "D", text: "x = 4 ou x = −4" },
    ],
    correctAnswer: "C",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "Um problema de 'encontro' gera o sistema: João tem o dobro da idade de Maria. Daqui a 5 anos, a soma das idades será 40. Qual o sistema que modela esse problema?",
    tip: "João = 2 × Maria agora. Daqui a 5 anos: (João + 5) + (Maria + 5) = 40.",
    funFact: "\"Você Sabia?\" — Problemas de idades são um dos tipos mais antigos de problemas matemáticos — aparecem em papiros egípcios de 3.600 anos atrás e em tabletes babilônicos de 4.000 anos.",
    points: 1,
    options: [
      { id: "A", text: "{ J = 2M ; J + M = 40 }" },
      { id: "B", text: "{ J = 2M + 5 ; J + M = 40 }" },
      { id: "C", text: "{ J + 5 = 2M ; J + M = 40 }" },
      { id: "D", text: "{ J = 2M ; J + M + 10 = 40 }" },
    ],
    correctAnswer: "D",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "Resolva o sistema: { 2x + 3y = 12 ; 4x − 3y = 0 }",
    tip: "Some as equações — o 3y e o −3y são eliminados. Depois encontre y.",
    funFact: "\"Você Sabia?\" — Solução: somando, 6x = 12 → x = 2; substituindo: 4(2) − 3y = 0 → y = 8/3. Sistemas onde os coeficientes de y são opostos são resolvidos em um passo pelo método da adição.",
    points: 1,
    options: [
      { id: "A", text: "x = 1 e y = 8/3" },
      { id: "B", text: "x = 2 e y = 8/3" },
      { id: "C", text: "x = 3 e y = 2" },
      { id: "D", text: "x = 4 e y = 0" },
    ],
    correctAnswer: "B",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Resolva a equação irracional √(x² − 5) = 2:",
    tip: "Eleve ao quadrado: x² − 5 = 4. Resolva para x² e depois para x. VERIFIQUE!",
    funFact: "\"Você Sabia?\" — A equação √(x² − 5) = 2 tem duas soluções (3 e −3) porque a condição √(x²−5) = 2 ≥ 0 é satisfeita por ambos. Verificação: √(9−5) = √4 = 2 ✓",
    points: 1,
    options: [
      { id: "A", text: "x = √9 = 3 apenas" },
      { id: "B", text: "x = 3 (apenas)" },
      { id: "C", text: "x = 3 ou x = −3 (ambas válidas, pois √(9−5) = 2 ✓)" },
      { id: "D", text: "Sem solução real." },
    ],
    correctAnswer: "C",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Um fazendeiro tem galinhas e coelhos totalizando 20 cabeças e 56 patas. Quantas galinhas há?",
    tip: "Galinhas têm 2 patas, coelhos têm 4. Monte o sistema: g + c = 20 e 2g + 4c = 56.",
    funFact: "\"Você Sabia?\" — O problema das 'galinhas e coelhos' é um dos mais antigos da história da matemática, aparecendo em textos chineses do século III a.C. chamado de 'problema das aves e dos coelhos na gaiola'.",
    points: 1,
    options: [
      { id: "A", text: "12 galinhas" },
      { id: "B", text: "8 galinhas" },
      { id: "C", text: "10 galinhas" },
      { id: "D", text: "14 galinhas" },
    ],
    correctAnswer: "A",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Para resolver o sistema { 2x + y = 8 ; x − 2y = 1 } pelo método da adição, qual é o procedimento?",
    tip: "Para eliminar y, multiplique a primeira equação por 2 e some com a segunda.",
    funFact: "\"Você Sabia?\" — Ao multiplicar a primeira equação por 2, temos 4x + 2y = 16. Somando com x − 2y = 1, obtemos 5x = 17, então x = 17/5 e y = 8 − 34/5 = 6/5.",
    points: 1,
    options: [
      { id: "A", text: "Subtrair a segunda da primeira sem modificação." },
      { id: "B", text: "Dividir as equações entre si para eliminar x." },
      { id: "C", text: "Substituir x = 1 diretamente para testar." },
      { id: "D", text: "Multiplicar a primeira por 2 para obter +2y e −2y, depois somar as equações." },
    ],
    correctAnswer: "D",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Qual das alternativas representa um SISTEMA IMPOSSÍVEL?",
    tip: "Um sistema impossível tem equações contraditórias — nenhum par (x, y) satisfaz as duas ao mesmo tempo.",
    funFact: "\"Você Sabia?\" — Sistemas impossíveis aparecem em problemas de engenharia quando se tenta satisfazer condições contraditórias simultaneamente — identificar a impossibilidade evita projetos inviáveis.",
    points: 1,
    options: [
      { id: "A", text: "{ x + y = 5 ; 2x + 2y = 10 }" },
      { id: "B", text: "{ x + y = 5 ; x + y = 7 }" },
      { id: "C", text: "{ x + y = 5 ; 2x + y = 8 }" },
      { id: "D", text: "{ x + y = 5 ; x − y = 1 }" },
    ],
    correctAnswer: "B",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Resolva a equação irracional √(3x + 1) = x − 1:",
    tip: "Condição: x − 1 ≥ 0, então x ≥ 1. Eleve ao quadrado: 3x + 1 = x² − 2x + 1. VERIFIQUE x = 0 e x = 5.",
    funFact: "\"Você Sabia?\" — Para √(3x+1) = x−1, a condição x ≥ 1 já descarta x = 0. Verificando x = 5: √16 = 4 = 5−1 = 4 ✓. Solução: x = 5.",
    points: 1,
    options: [
      { id: "A", text: "x = 0 e x = 5" },
      { id: "B", text: "x = 5 e x = −1" },
      { id: "C", text: "x = 5 apenas (x = 0 é estranha, pois 0 < 1)" },
      { id: "D", text: "Sem solução real." },
    ],
    correctAnswer: "C",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Uma mistura de cafés especiais: 2 kg do tipo A e 1 kg do tipo B custam R$ 28. 1 kg do tipo A e 3 kg do tipo B custam R$ 24. Qual o preço do tipo A?",
    tip: "Monte o sistema: 2A + B = 28 e A + 3B = 24. Da primeira: B = 28 − 2A. Substitua na segunda.",
    funFact: "\"Você Sabia?\" — Substituindo: A + 3(28 − 2A) = 24 → A + 84 − 6A = 24 → −5A = −60 → A = 12. Então B = 28 − 24 = 4. Verificação: 2(12) + 4 = 28 ✓ e 12 + 3(4) = 24 ✓.",
    points: 1,
    options: [
      { id: "A", text: "R$ 12 por kg" },
      { id: "B", text: "R$ 10 por kg" },
      { id: "C", text: "R$ 14 por kg" },
      { id: "D", text: "R$ 8 por kg" },
    ],
    correctAnswer: "A",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Resolva a equação irracional √(x + 4) + 2 = x:",
    tip: "Isole a raiz: √(x + 4) = x − 2. Condição: x ≥ 2. Eleve ao quadrado e verifique as soluções.",
    funFact: "\"Você Sabia?\" — Verificação: x=5: √9 + 2 = 3 + 2 = 5 ✓. x=0: não satisfaz condição x ≥ 2. Sempre a condição + verificação são o método completo para equações irracionais.",
    points: 1,
    options: [
      { id: "A", text: "x = 0 e x = 5" },
      { id: "B", text: "x = 3 e x = 5" },
      { id: "C", text: "x = −4" },
      { id: "D", text: "x = 5 (apenas, pois x = 0 não satisfaz a condição x ≥ 2)" },
    ],
    correctAnswer: "D",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Um sistema de 3 equações com 3 variáveis pode ser resolvido por:",
    tip: "O mesmo princípio das 2 variáveis se extende — como você reduziria para 2 variáveis?",
    funFact: "\"Você Sabia?\" — A eliminação gaussiana (método sistemático de resolver sistemas com n equações e n variáveis) é executada bilhões de vezes por segundo por computadores em aplicações de inteligência artificial, gráficos 3D e previsão do tempo.",
    points: 1,
    options: [
      { id: "A", text: "Apenas pelo método gráfico em 3 dimensões." },
      { id: "B", text: "Apenas por calculadoras programáveis." },
      { id: "C", text: "Aplicando substituição ou adição para reduzir a um sistema de 2 equações e 2 variáveis." },
      { id: "D", text: "O método de Bhaskara generalizado para 3 variáveis." },
    ],
    correctAnswer: "C",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Qual é a condição de existência da equação irracional √(2x − 6)?",
    tip: "Para a raiz quadrada existir em ℝ, o radicando deve ser ≥ 0.",
    funFact: "\"Você Sabia?\" — A condição de existência define o domínio da função f(x) = √(2x − 6), que é [3, +∞). Em física, isso representa os valores de x para os quais o fenômeno modelado é fisicamente possível.",
    points: 1,
    options: [
      { id: "A", text: "x > 0" },
      { id: "B", text: "x ≥ 3" },
      { id: "C", text: "x ≥ 6" },
      { id: "D", text: "x ≠ 6" },
    ],
    correctAnswer: "B",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "O estudo de equações irracionais e sistemas é fundamental em matemática porque:",
    tip: "Pense na diversidade de situações reais que esses conteúdos modelam.",
    funFact: "\"Você Sabia?\" — Sistemas de equações lineares com milhares de variáveis são usados em aprendizado de máquina (machine learning) para 'treinar' modelos de IA, incluindo os algoritmos de reconhecimento facial.",
    points: 1,
    options: [
      { id: "A", text: "Permite modelar e resolver problemas do mundo real que envolvem múltiplas condições simultâneas." },
      { id: "B", text: "São necessários apenas para provas de vestibular, sem aplicação prática." },
      { id: "C", text: "Substituem a necessidade de Bhaskara em todos os problemas." },
      { id: "D", text: "São exigidos apenas por matemáticos puros, sem aplicação em outras ciências." },
    ],
    correctAnswer: "A",
  },
];
