export const questoesGeografia6AnoB4Av2 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'Para onde a agulha de uma bússola sempre aponta?',
    tip: 'Lembra o instrumento que usamos para nos orientar mesmo sem ver o Sol?',
    funFact: 'A bússola foi um dos instrumentos mais importantes da história da navegação!',
    points: 1,
    options: [
      { id: 'A', text: 'Sul magnético' },
      { id: 'B', text: 'Leste' },
      { id: 'C', text: 'Onde o vento sopra' },
      { id: 'D', text: 'Norte magnético' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'O que diferencia uma paisagem natural de uma paisagem transformada?',
    tip: 'Pense em quem "mexeu" ou não naquele espaço: a natureza sozinha ou as pessoas.',
    funFact: 'Muitos lugares do mundo hoje são uma mistura das duas coisas!',
    points: 1,
    options: [
      { id: 'A', text: 'A cor predominante' },
      { id: 'B', text: 'A presença ou ausência de ação humana significativa' },
      { id: 'C', text: 'O tamanho da área' },
      { id: 'D', text: 'A quantidade de fotos tiradas dela' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'Qual é a forma de relevo predominante no território brasileiro?',
    tip: 'Pense na forma de relevo "alta e de topo plano" que é a mais comum no país.',
    funFact: 'A maior parte do território brasileiro é formada por planaltos, formados há centenas de milhões de anos!',
    points: 1,
    options: [
      { id: 'A', text: 'Planalto' },
      { id: 'B', text: 'Vulcão' },
      { id: 'C', text: 'Deserto' },
      { id: 'D', text: 'Geleira' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'Qual é o nome do local onde um rio nasce?',
    tip: 'Pense no "começo da vida" de um rio.',
    funFact: 'Proteger a mata ao redor das nascentes é fundamental para garantir que os rios continuem existindo!',
    points: 1,
    options: [
      { id: 'A', text: 'Foz' },
      { id: 'B', text: 'Afluente' },
      { id: 'C', text: 'Nascente' },
      { id: 'D', text: 'Margem' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'Qual clima predomina na região Norte do Brasil, com altas temperaturas e chuvas o ano todo?',
    tip: 'Pense no clima da região onde fica a Floresta Amazônica.',
    funFact: 'No clima equatorial, praticamente não existem as quatro estações bem definidas!',
    points: 1,
    options: [
      { id: 'A', text: 'Semiárido' },
      { id: 'B', text: 'Equatorial' },
      { id: 'C', text: 'Subtropical' },
      { id: 'D', text: 'Tropical de altitude' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'Qual é o maior bioma do Brasil, conhecido por sua enorme biodiversidade?',
    tip: 'Pense no bioma que abriga a maior floresta tropical do mundo.',
    funFact: 'A Amazônia abriga cerca de 10% de todas as espécies conhecidas do planeta!',
    points: 1,
    options: [
      { id: 'A', text: 'Cerrado' },
      { id: 'B', text: 'Caatinga' },
      { id: 'C', text: 'Pampa' },
      { id: 'D', text: 'Amazônia' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'O que é densidade demográfica?',
    tip: 'Pense em quantas pessoas vivem, em média, em cada km² de um território.',
    funFact: 'Áreas pequenas podem ter densidade demográfica muito alta, mesmo com poucos habitantes no total!',
    points: 1,
    options: [
      { id: 'A', text: 'A quantidade de rios de uma região' },
      { id: 'B', text: 'O tipo de vegetação predominante' },
      { id: 'C', text: 'A relação entre o número de habitantes e a área de um território' },
      { id: 'D', text: 'A altura média das montanhas' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'Como se chama o desenho circular que mostra todas as direções, usado em mapas?',
    tip: 'Tem "rosa" no nome, mas não é uma flor.',
    funFact: 'A rosa dos ventos é usada há séculos por navegadores para desenhar mapas!',
    points: 1,
    options: [
      { id: 'A', text: 'Rosa dos ventos' },
      { id: 'B', text: 'Escala gráfica' },
      { id: 'C', text: 'Legenda' },
      { id: 'D', text: 'Relevo' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'O que é uma bacia hidrográfica?',
    tip: 'Pense em todos os "braços de água" que, juntos, formam um grande sistema de rios.',
    funFact: 'O Brasil tem uma das maiores bacias hidrográficas do mundo: a Bacia Amazônica!',
    points: 1,
    options: [
      { id: 'A', text: 'Um tipo de relevo' },
      { id: 'B', text: 'O conjunto formado por um rio principal e todos os seus afluentes' },
      { id: 'C', text: 'Um tipo de vegetação' },
      { id: 'D', text: 'Uma forma de paisagem transformada' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'Como se chama o processo de saída das pessoas do campo para as cidades?',
    tip: 'Pense em uma "saída em massa" do campo, em direção às cidades.',
    funFact: 'O êxodo rural foi um dos grandes motivos pelos quais a maioria dos brasileiros hoje vive em cidades!',
    points: 1,
    options: [
      { id: 'A', text: 'Imigração' },
      { id: 'B', text: 'Erosão' },
      { id: 'C', text: 'Fuso horário' },
      { id: 'D', text: 'Êxodo rural' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'Qual é o ponto mais alto do Brasil?',
    tip: 'Fica na região Norte, perto da fronteira com a Venezuela.',
    funFact: 'O Pico da Neblina fica tão coberto de nuvens que, por muito tempo, foi difícil enxergar seu topo!',
    points: 1,
    options: [
      { id: 'A', text: 'Pão de Açúcar' },
      { id: 'B', text: 'Corcovado' },
      { id: 'C', text: 'Pico da Neblina' },
      { id: 'D', text: 'Serra do Mar' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'O que caracteriza o clima semiárido, presente no interior do Nordeste?',
    tip: 'Pense na região conhecida como Sertão, marcada pela seca.',
    funFact: 'Apesar de muito seco, o clima semiárido tem plantas bem adaptadas, como os cactos!',
    points: 1,
    options: [
      { id: 'A', text: 'Pouca chuva e longos períodos de seca' },
      { id: 'B', text: 'Chuvas abundantes o ano todo' },
      { id: 'C', text: 'Neve frequente no inverno' },
      { id: 'D', text: 'Umidade extremamente alta o ano todo' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'Qual bioma é caracterizado pela vegetação adaptada à seca, com cactos e arbustos espinhosos?',
    tip: 'Pense na vegetação típica do Sertão nordestino.',
    funFact: 'A palavra "Caatinga" vem de um termo indígena que significa "mata branca"!',
    points: 1,
    options: [
      { id: 'A', text: 'Amazônia' },
      { id: 'B', text: 'Mata Atlântica' },
      { id: 'C', text: 'Pampa' },
      { id: 'D', text: 'Caatinga' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'Qual bioma ficava originalmente ao longo do litoral brasileiro, hoje bastante reduzido?',
    tip: 'Pense na vegetação que os portugueses encontraram ao chegar ao litoral do Brasil.',
    funFact: 'Restou menos de 20% da vegetação original da Mata Atlântica!',
    points: 1,
    options: [
      { id: 'A', text: 'Cerrado' },
      { id: 'B', text: 'Mata Atlântica' },
      { id: 'C', text: 'Pantanal' },
      { id: 'D', text: 'Pampa' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'Qual região do Brasil concentra o maior número de habitantes?',
    tip: 'Pense na região onde ficam São Paulo e Rio de Janeiro.',
    funFact: 'Só o estado de São Paulo tem mais habitantes do que muitos países inteiros!',
    points: 1,
    options: [
      { id: 'A', text: 'Sudeste' },
      { id: 'B', text: 'Norte' },
      { id: 'C', text: 'Centro-Oeste' },
      { id: 'D', text: 'Sul' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'O que é a legenda de um mapa?',
    tip: 'Pense na parte do mapa que explica o que cada símbolo significa.',
    funFact: 'Sem a legenda, um mapa cheio de símbolos ficaria um mistério!',
    points: 1,
    options: [
      { id: 'A', text: 'A distância real entre dois lugares' },
      { id: 'B', text: 'O nome da cidade representada' },
      { id: 'C', text: 'Uma explicação dos símbolos usados no mapa' },
      { id: 'D', text: 'A cor de fundo do mapa' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'O que é uma planície?',
    tip: 'Pense em algo "plano", parecido com a palavra.',
    funFact: 'Muitas planícies brasileiras, como a Amazônica, ficam ao redor de grandes rios!',
    points: 1,
    options: [
      { id: 'A', text: 'Uma área elevada e de topo plano' },
      { id: 'B', text: 'Uma área baixa e bem plana' },
      { id: 'C', text: 'Uma área muito inclinada e alta' },
      { id: 'D', text: 'Uma área afundada em relação ao redor' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'Para que serve a água represada em uma usina hidrelétrica?',
    tip: 'Pense em como a força da água caindo pode fazer uma turbina girar.',
    funFact: 'Grande parte da energia elétrica usada no Brasil vem de usinas hidrelétricas!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas para decorar a paisagem' },
      { id: 'B', text: 'Para regar plantações automaticamente' },
      { id: 'C', text: 'Para resfriar o ar das cidades' },
      { id: 'D', text: 'Para gerar energia elétrica, usando a força da água' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'O que é biodiversidade?',
    tip: 'Pense na "diversidade da vida" que existe em um lugar.',
    funFact: 'O Brasil é um dos países com maior biodiversidade do mundo!',
    points: 1,
    options: [
      { id: 'A', text: 'A variedade de seres vivos em um ambiente' },
      { id: 'B', text: 'A quantidade de chuva de uma região' },
      { id: 'C', text: 'O tipo de relevo predominante' },
      { id: 'D', text: 'A temperatura média de um bioma' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'Por que muitas pessoas migraram do campo para as cidades nas últimas décadas?',
    tip: 'Pense nas oportunidades que muitas pessoas buscam ao se mudar para uma cidade maior.',
    funFact: 'Esse movimento contribuiu para o crescimento acelerado de muitas cidades brasileiras no século 20!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque foram obrigadas por lei' },
      { id: 'B', text: 'Porque o campo tinha mais empregos disponíveis' },
      { id: 'C', text: 'Em busca de emprego, escolas e serviços disponíveis nas áreas urbanas' },
      { id: 'D', text: 'Porque as cidades não ofereciam nenhum serviço' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Durante a viagem de férias, Bernardo usou uma bússola para se orientar numa trilha. A agulha apontou para o Norte. Isso aconteceu porque a bússola:',
    tip: 'Lembra por que a agulha da bússola sempre aponta para o mesmo lugar?',
    funFact: 'A bússola é usada há mais de mil anos para ajudar viajantes a encontrar o caminho certo!',
    points: 1,
    options: [
      { id: 'A', text: 'Aponta sempre para onde o vento sopra' },
      { id: 'B', text: 'Reage ao campo magnético da Terra' },
      { id: 'C', text: 'Segue a direção do Sol' },
      { id: 'D', text: 'Funciona apenas de dia' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Na cidade dos avós, Bernardo viu uma fazenda com plantações organizadas em fileiras. Esse tipo de paisagem é considerado:',
    tip: 'Pense em quem plantou e organizou aquelas fileiras certinhas.',
    funFact: 'Mesmo parecendo natural, uma plantação é fruto de muito planejamento humano!',
    points: 1,
    options: [
      { id: 'A', text: 'Totalmente natural, sem interferência humana' },
      { id: 'B', text: 'Impossível de existir' },
      { id: 'C', text: 'Igual a uma floresta intacta' },
      { id: 'D', text: 'Transformada pela ação humana' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Bernardo aprendeu que a casa dos avós ficava sobre um terreno alto, mas de topo bem plano. Esse tipo de relevo é chamado de:',
    tip: 'Lembra do relevo "alto e de topo plano" mais comum no Brasil?',
    funFact: 'A maior parte das plantações do Brasil fica em áreas de planalto!',
    points: 1,
    options: [
      { id: 'A', text: 'Planalto' },
      { id: 'B', text: 'Planície' },
      { id: 'C', text: 'Depressão' },
      { id: 'D', text: 'Vulcão' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Na viagem, Bernardo viu um rio recebendo a água de outro rio menor. Esse rio menor é chamado de:',
    tip: 'Pense em um rio "ajudante" que entrega mais água ao rio principal.',
    funFact: 'O Rio Amazonas tem centenas de afluentes ao longo do seu percurso!',
    points: 1,
    options: [
      { id: 'A', text: 'Foz' },
      { id: 'B', text: 'Nascente' },
      { id: 'C', text: 'Afluente' },
      { id: 'D', text: 'Litoral' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Bernardo notou que, na região visitada, chovia bastante o ano todo e fazia muito calor. Esse é o clima típico da região:',
    tip: 'Pense no clima da região da Floresta Amazônica.',
    funFact: 'A Amazônia "fabrica" boa parte da sua própria chuva, através dos "rios voadores"!',
    points: 1,
    options: [
      { id: 'A', text: 'Sul, subtropical' },
      { id: 'B', text: 'Nordeste, semiárido' },
      { id: 'C', text: 'Sudeste, tropical' },
      { id: 'D', text: 'Norte, equatorial' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'No documentário, Bernardo viu grandes áreas alagadas cheias de aves e jacarés, no Centro-Oeste. Esse bioma é o:',
    tip: 'Pense no bioma que "enche" de água em certas épocas do ano.',
    funFact: 'O Pantanal é considerado uma das maiores áreas úmidas do mundo!',
    points: 1,
    options: [
      { id: 'A', text: 'Cerrado' },
      { id: 'B', text: 'Pantanal' },
      { id: 'C', text: 'Caatinga' },
      { id: 'D', text: 'Mata Atlântica' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Bernardo reparou que a cidade litorânea que visitou tinha muito mais gente do que a cidade do interior onde moravam os avós. Isso mostra que a população brasileira está:',
    tip: 'Pense em como grandes cidades brasileiras costumam ficar perto do mar.',
    funFact: 'Mais da metade dos brasileiros vive a menos de 200 km da costa!',
    points: 1,
    options: [
      { id: 'A', text: 'Distribuída de forma perfeitamente igual' },
      { id: 'B', text: 'Toda concentrada no interior' },
      { id: 'C', text: 'Distribuída de forma desigual, mais concentrada perto do litoral' },
      { id: 'D', text: 'Ausente das regiões litorâneas' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Na escola, a professora pediu para Bernardo explicar o que aprendeu sobre orientação, usando mapas. Ele respondeu corretamente que a bússola e a rosa dos ventos ajudam a:',
    tip: 'Pense na função principal desses instrumentos e desenhos.',
    funFact: 'Antes do GPS, marinheiros cruzavam oceanos inteiros usando apenas bússola e os pontos cardeais!',
    points: 1,
    options: [
      { id: 'A', text: 'Encontrar direções e se localizar no espaço' },
      { id: 'B', text: 'Prever o clima do dia seguinte' },
      { id: 'C', text: 'Medir a densidade demográfica' },
      { id: 'D', text: 'Calcular a altura de uma montanha' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Ao revisar o conteúdo do ano, Bernardo listou os principais biomas brasileiros que estudou. Qual das opções reúne corretamente alguns deles?',
    tip: 'Pense nos grandes "conjuntos de vida vegetal e animal" que vimos ao longo do ano.',
    funFact: 'O Brasil é um dos países com maior biodiversidade do mundo, graças a essa grande variedade de biomas!',
    points: 1,
    options: [
      { id: 'A', text: 'Planalto, planície e depressão' },
      { id: 'B', text: 'Nascente, afluente e foz' },
      { id: 'C', text: 'Norte, Sul e Sudeste' },
      { id: 'D', text: 'Amazônia, Cerrado, Caatinga, Mata Atlântica, Pampa e Pantanal' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'Ao final do ano, a professora perguntou a Bernardo o que ele mais gostou de aprender em Geografia. Ele respondeu que entendeu como o relevo, o clima, a vegetação, os rios e a população de um lugar estão:',
    tip: 'Pense em tudo o que vimos ao longo do ano sobre como esses temas se conectam.',
    funFact: 'Parabéns, Bernardo! Você concluiu o ano de Geografia do 6º ano entendendo como a natureza e a sociedade se conectam!',
    points: 1,
    options: [
      { id: 'A', text: 'Completamente desconectados uns dos outros' },
      { id: 'B', text: 'Interligados e se influenciam mutuamente, formando o espaço geográfico' },
      { id: 'C', text: 'Presentes apenas em outros países' },
      { id: 'D', text: 'Sem nenhuma relação com o dia a dia das pessoas' },
    ],
    correctAnswer: 'B',
  },
];
