export const questoesEducacaoFisica6AnoB2Av2 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'No voleibol, os jogadores tentam fazer a bola tocar o chão do campo adversário, sem deixá-la tocar o próprio chão. Isso é feito principalmente:',
    tip: 'Pensa em como os jogadores tocam na bola durante uma partida de vôlei, sem usar os pés.',
    funFact: 'O vôlei foi inventado nos Estados Unidos, pouco depois do basquete!',
    points: 1,
    options: [
      { id: 'A', text: 'Chutando a bola' },
      { id: 'B', text: 'Usando um taco' },
      { id: 'C', text: 'Usando as mãos e os braços' },
      { id: 'D', text: 'Usando os pés apenas' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'Quantos jogadores de cada equipe ficam em quadra, ao mesmo tempo, em uma partida oficial de vôlei?',
    tip: 'É um número menor que o do futebol, mas maior que o do vôlei de praia (que tem só 2 por equipe).',
    funFact: 'O vôlei de praia é uma variação do vôlei tradicional, jogada com apenas 2 jogadores por equipe!',
    points: 1,
    options: [
      { id: 'A', text: '6' },
      { id: 'B', text: '5' },
      { id: 'C', text: '7' },
      { id: 'D', text: '11' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'No vôlei, cada equipe pode tocar na bola, no máximo, quantas vezes antes de enviá-la para o outro lado?',
    tip: 'Pensa na sequência clássica: passe, levantamento e ataque — quantos toques são esses?',
    funFact: 'Essa regra é conhecida como "regra dos três toques"!',
    points: 1,
    options: [
      { id: 'A', text: 'Uma vez' },
      { id: 'B', text: 'Duas vezes' },
      { id: 'C', text: 'Cinco vezes' },
      { id: 'D', text: 'Três vezes' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'No handebol, os jogadores marcam pontos ao:',
    tip: 'Pensa em como o handebol mistura elementos do futebol (o gol) com o uso das mãos.',
    funFact: 'O handebol é bastante popular em países da Europa, como a Alemanha e a Dinamarca!',
    points: 1,
    options: [
      { id: 'A', text: 'Arremessar a bola dentro de uma cesta' },
      { id: 'B', text: 'Lançar a bola dentro do gol adversário, usando as mãos' },
      { id: 'C', text: 'Chutar a bola com os pés' },
      { id: 'D', text: 'Rebater a bola com um taco' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'Quantos jogadores de cada equipe ficam em quadra, ao mesmo tempo, em uma partida oficial de handebol?',
    tip: 'É um número entre o do basquete (5) e o do futebol (11).',
    funFact: 'Esse número inclui o goleiro, assim como no futebol!',
    points: 1,
    options: [
      { id: 'A', text: '11' },
      { id: 'B', text: '5' },
      { id: 'C', text: '7' },
      { id: 'D', text: '6' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'No vôlei, o movimento usado para iniciar a jogada, enviando a bola para o campo adversário, é chamado de:',
    tip: 'Pensa no movimento feito no início de cada jogada, batendo na bola para o outro lado da quadra.',
    funFact: 'Existem diferentes tipos de saque no vôlei, como o saque por cima e o saque flutuante!',
    points: 1,
    options: [
      { id: 'A', text: 'Cabeceio' },
      { id: 'B', text: 'Saque' },
      { id: 'C', text: 'Drible' },
      { id: 'D', text: 'Escanteio' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'No handebol, os jogadores podem usar principalmente:',
    tip: 'Pensa em como os jogadores de handebol seguram e lançam a bola durante o jogo.',
    funFact: 'O nome "handebol" vem de "hand" (mão, em inglês) e "ball" (bola)!',
    points: 1,
    options: [
      { id: 'A', text: 'As mãos, para segurar, driblar e arremessar a bola' },
      { id: 'B', text: 'Apenas os pés' },
      { id: 'C', text: 'Uma raquete' },
      { id: 'D', text: 'Um taco' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'No vôlei, quando a bola toca a rede e passa para o outro lado durante o saque, o que geralmente acontece, dependendo da regra usada?',
    tip: 'Pensa em como as regras podem variar um pouco dependendo do tipo de competição ou categoria.',
    funFact: 'Em competições oficiais atuais, esse tipo de saque costuma ser considerado válido!',
    points: 1,
    options: [
      { id: 'A', text: 'O ponto é cancelado sempre' },
      { id: 'B', text: 'O jogo para imediatamente sem decisão' },
      { id: 'C', text: 'A equipe adversária perde automaticamente' },
      { id: 'D', text: 'O saque pode ser válido, dependendo da competição e da regra adotada' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'No handebol, existe uma área próxima ao gol onde os jogadores de linha não podem entrar, chamada de:',
    tip: 'Pensa na área reservada especialmente para o goleiro, perto do gol.',
    funFact: 'Se um jogador de linha entrar nessa área com a bola, isso pode ser marcado como infração!',
    points: 1,
    options: [
      { id: 'A', text: 'Meio de quadra' },
      { id: 'B', text: 'Linha lateral' },
      { id: 'C', text: 'Área de gol' },
      { id: 'D', text: 'Linha de fundo' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'O vôlei e o handebol são exemplos de esportes:',
    tip: 'Pensa em como esses dois esportes precisam de várias pessoas jogando juntas, em equipe.',
    funFact: 'Junto com futebol e basquete, vôlei e handebol formam quatro dos esportes coletivos mais praticados no mundo!',
    points: 1,
    options: [
      { id: 'A', text: 'Individuais' },
      { id: 'B', text: 'Coletivos, praticados em equipe' },
      { id: 'C', text: 'Sem nenhuma regra' },
      { id: 'D', text: 'Sem nenhum contato com a bola' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'Por que a regra dos "três toques" no vôlei é importante para o jogo?',
    tip: 'Pensa em como os três toques costumam ser divididos entre diferentes jogadores da equipe.',
    funFact: 'Cada um desses toques geralmente tem uma função específica: recepção, levantamento e ataque!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque não tem nenhuma função' },
      { id: 'B', text: 'Porque limita o número de jogadores em quadra' },
      { id: 'C', text: 'Porque substitui o saque' },
      { id: 'D', text: 'Porque incentiva a equipe a trabalhar em conjunto para levar a bola ao outro lado, geralmente com passe, levantamento e ataque' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'Se um jogador de handebol entra na área de gol enquanto está com a bola, o que normalmente acontece?',
    tip: 'Lembra que a área de gol é reservada para o goleiro — jogadores de linha não podem entrar nela com a bola.',
    funFact: 'Essa regra ajuda a proteger o goleiro e manter o jogo mais justo!',
    points: 1,
    options: [
      { id: 'A', text: 'Nada acontece' },
      { id: 'B', text: 'A arbitragem pode marcar uma infração, dependendo do momento da jogada' },
      { id: 'C', text: 'O time ganha um ponto extra' },
      { id: 'D', text: 'O jogo é cancelado' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'Por que o saque é considerado um fundamento importante no vôlei?',
    tip: 'Pensa em como um saque bem forte ou bem colocado pode dificultar a vida do time adversário.',
    funFact: 'Alguns jogadores profissionais têm sacadas tão fortes que são quase impossíveis de defender!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque não influencia o resultado do jogo' },
      { id: 'B', text: 'Porque só serve para iniciar o jogo sem nenhuma estratégia' },
      { id: 'C', text: 'Porque pode ser usado como uma jogada ofensiva, dificultando a recepção do adversário' },
      { id: 'D', text: 'Porque é proibido treinar o saque' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'Se uma equipe de handebol consegue armar boas jogadas de ataque, isso geralmente depende de:',
    tip: 'Pensa em como o handebol, assim como outros esportes coletivos, depende de trabalho em equipe.',
    funFact: 'Os passes no handebol precisam ser rápidos e precisos, já que o jogo costuma ser bem dinâmico!',
    points: 1,
    options: [
      { id: 'A', text: 'Passes precisos e cooperação entre os jogadores' },
      { id: 'B', text: 'Apenas um jogador jogando sozinho' },
      { id: 'C', text: 'Nenhuma estratégia coletiva' },
      { id: 'D', text: 'Jogadores parados o tempo todo' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'Por que vôlei e handebol são considerados esportes coletivos, assim como futebol e basquete?',
    tip: 'Pensa no que todos esses quatro esportes (futebol, basquete, vôlei e handebol) têm em comum.',
    funFact: 'Todos esses esportes fazem parte dos Jogos Olímpicos!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque são praticados sempre sozinhos' },
      { id: 'B', text: 'Porque não têm nenhuma regra' },
      { id: 'C', text: 'Porque não envolvem nenhuma bola' },
      { id: 'D', text: 'Porque são praticados em equipe, com cooperação entre os jogadores para atingir um objetivo comum' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'Se um time de vôlei toca na bola quatro vezes antes de mandá-la para o outro lado, o que acontece?',
    tip: 'Lembra da regra dos três toques — tocar uma vez a mais é uma infração.',
    funFact: 'Por isso a comunicação entre os jogadores de vôlei é tão importante, para não ultrapassar o limite de toques!',
    points: 1,
    options: [
      { id: 'A', text: 'O ponto é marcado para o time adversário, por infração da regra dos três toques' },
      { id: 'B', text: 'Nada acontece, é permitido' },
      { id: 'C', text: 'O time ganha um ponto extra' },
      { id: 'D', text: 'O jogo recomeça do zero' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'Por que a posição dos jogadores no vôlei muda ao longo do jogo (rodízio)?',
    tip: 'Pensa em como essa regra ajuda a variar as posições dos jogadores ao longo da partida.',
    funFact: 'Esse rodízio faz com que todos os jogadores passem por diferentes posições da quadra durante o jogo!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque é proibido ficar parado' },
      { id: 'B', text: 'Porque a regra do rodízio faz os jogadores alternarem de posição a cada vez que a equipe ganha o saque' },
      { id: 'C', text: 'Porque os jogadores decidem aleatoriamente' },
      { id: 'D', text: 'Porque não existe nenhuma regra sobre posição' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'No handebol, por que os goleiros têm regras um pouco diferentes dos outros jogadores dentro da área de gol?',
    tip: 'Pensa na função especial do goleiro, parecida com a do futebol.',
    funFact: 'O goleiro de handebol pode usar qualquer parte do corpo para defender, diferente dos jogadores de linha!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque eles não podem tocar na bola' },
      { id: 'B', text: 'Porque não existe distinção entre jogadores' },
      { id: 'C', text: 'Porque o goleiro tem a função específica de defender o gol dentro dessa área' },
      { id: 'D', text: 'Porque só o goleiro pode jogar' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'Por que aprender diferentes esportes coletivos, como futebol, basquete, vôlei e handebol, é importante na Educação Física?',
    tip: 'Pensa em como cada esporte que você estudou tem regras e habilidades um pouco diferentes.',
    funFact: 'Praticar esportes variados ajuda a desenvolver um conjunto mais completo de habilidades motoras!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque só um esporte é suficiente para tudo' },
      { id: 'B', text: 'Porque esportes coletivos não têm nenhum benefício' },
      { id: 'C', text: 'Porque só interessa a atletas profissionais' },
      { id: 'D', text: 'Porque cada esporte desenvolve habilidades e formas diferentes de trabalho em equipe' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'Se dois times de handebol jogam uma partida muito disputada, o que costuma decidir o resultado, além da habilidade individual?',
    tip: 'Pensa em tudo que você aprendeu sobre a importância do trabalho em equipe nos esportes coletivos.',
    funFact: 'Muitas partidas de handebol são decididas nos últimos segundos, mostrando como a estratégia coletiva é importante!',
    points: 1,
    options: [
      { id: 'A', text: 'A cooperação e a estratégia da equipe como um todo' },
      { id: 'B', text: 'Apenas a sorte' },
      { id: 'C', text: 'O tamanho do uniforme' },
      { id: 'D', text: 'A cor da bola' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Na aula de Educação Física, Bernardo joga vôlei e aprende que sua equipe pode tocar na bola, no máximo, três vezes antes de mandá-la para o outro lado. Qual é o nome dessa regra?',
    tip: 'É a mesma regra das questões 3 e 16.',
    funFact: 'Bernardo pode treinar essa sequência de passe, levantamento e ataque com os colegas para melhorar o jogo da equipe!',
    points: 1,
    options: [
      { id: 'A', text: 'Regra do rodízio' },
      { id: 'B', text: 'Regra do saque' },
      { id: 'C', text: 'Regra dos três toques' },
      { id: 'D', text: 'Regra do impedimento' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Durante o jogo, Bernardo faz o movimento que inicia a jogada, enviando a bola para o campo adversário. Como se chama esse movimento?',
    tip: 'É o mesmo movimento das questões 6 e 13.',
    funFact: 'Com a prática, Bernardo pode melhorar bastante a força e a precisão do próprio saque!',
    points: 1,
    options: [
      { id: 'A', text: 'Saque' },
      { id: 'B', text: 'Drible' },
      { id: 'C', text: 'Cabeceio' },
      { id: 'D', text: 'Escanteio' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Na aula seguinte, Bernardo joga handebol e aprende que os jogadores marcam pontos lançando a bola dentro do gol, usando as mãos. Quantos jogadores de cada equipe costumam jogar ao mesmo tempo em uma partida oficial de handebol?',
    tip: 'É o mesmo número da questão 5.',
    funFact: 'O handebol é um esporte bem dinâmico, com jogadas rápidas e muitos gols!',
    points: 1,
    options: [
      { id: 'A', text: '11' },
      { id: 'B', text: '7' },
      { id: 'C', text: '5' },
      { id: 'D', text: '6' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Bernardo percebe que existe uma área perto do gol no handebol onde os jogadores de linha não podem entrar. Como se chama essa área?',
    tip: 'É a mesma área das questões 9 e 12.',
    funFact: 'Essa regra é parecida com a "grande área" do futebol, só que com uma função um pouco diferente!',
    points: 1,
    options: [
      { id: 'A', text: 'Meio de quadra' },
      { id: 'B', text: 'Linha lateral' },
      { id: 'C', text: 'Linha de fundo' },
      { id: 'D', text: 'Área de gol' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'No vôlei, a posição de Bernardo muda a cada vez que sua equipe ganha o direito de sacar. Como se chama essa regra de troca de posições?',
    tip: 'É a mesma regra da questão 17.',
    funFact: 'Graças ao rodízio, Bernardo vai experimentar jogar em várias posições diferentes da quadra!',
    points: 1,
    options: [
      { id: 'A', text: 'Regra dos três toques' },
      { id: 'B', text: 'Regra do impedimento' },
      { id: 'C', text: 'Rodízio' },
      { id: 'D', text: 'Regra do saque' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'O professor explica por que trabalho em equipe é importante tanto no vôlei quanto no handebol. Qual é a explicação correta?',
    tip: 'É a mesma explicação das questões 11, 14 e 15.',
    funFact: 'Bernardo pode perceber que, quanto mais o time treina junto, melhor fica a cooperação em quadra!',
    points: 1,
    options: [
      { id: 'A', text: 'Cada jogador deve jogar sozinho' },
      { id: 'B', text: 'Não existe estratégia coletiva nesses esportes' },
      { id: 'C', text: 'Só um jogador precisa se esforçar' },
      { id: 'D', text: 'As jogadas e estratégias dependem da cooperação entre os jogadores do time' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Bernardo pergunta ao professor por que aprender vários esportes coletivos diferentes é importante na Educação Física. O professor explica que:',
    tip: 'É a mesma explicação da questão 19.',
    funFact: 'Assim, Bernardo pode descobrir qual esporte mais combina com o seu jeito de jogar!',
    points: 1,
    options: [
      { id: 'A', text: 'Cada esporte desenvolve habilidades e formas diferentes de trabalho em equipe' },
      { id: 'B', text: 'Só um esporte é suficiente para tudo' },
      { id: 'C', text: 'Esportes coletivos não têm nenhum benefício' },
      { id: 'D', text: 'Só interessa a atletas profissionais' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Durante o jogo de handebol, Bernardo entra sem querer na área de gol enquanto está com a bola. O que pode acontecer nesse caso?',
    tip: 'É a mesma situação da questão 12.',
    funFact: 'Com a prática, Bernardo vai aprender a controlar melhor os movimentos perto dessa área!',
    points: 1,
    options: [
      { id: 'A', text: 'Nada acontece' },
      { id: 'B', text: 'A arbitragem pode marcar uma infração, dependendo do momento da jogada' },
      { id: 'C', text: 'O time de Bernardo ganha um ponto extra' },
      { id: 'D', text: 'O jogo é cancelado' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Ao final da aula de vôlei, Bernardo percebe que sua equipe jogou bem porque todos cooperaram: um fez o passe, outro o levantamento e outro o ataque. Isso mostra a importância de:',
    tip: 'Pensa em tudo que você aprendeu sobre a regra dos três toques e o trabalho em equipe.',
    funFact: 'Essa sequência de passe, levantamento e ataque é um dos fundamentos mais bonitos de se ver no vôlei!',
    points: 1,
    options: [
      { id: 'A', text: 'Jogar sempre sozinho' },
      { id: 'B', text: 'Ignorar os colegas de equipe' },
      { id: 'C', text: 'Trabalhar em conjunto para conseguir realizar a jogada completa' },
      { id: 'D', text: 'Nenhuma estratégia coletiva' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'Para fechar a aula, o professor resume: "Vôlei e handebol são esportes coletivos porque..." Como ele pode completar a frase?',
    tip: 'Pensa em tudo que você aprendeu neste simulado sobre trabalho em equipe nesses esportes.',
    funFact: 'Parabéns, Bernardo! Agora você já conhece os quatro principais esportes coletivos com bola!',
    points: 1,
    options: [
      { id: 'A', text: '"...são praticados sempre sozinhos."' },
      { id: 'B', text: '"...não têm nenhuma regra."' },
      { id: 'C', text: '"...só podem ser praticados por profissionais."' },
      { id: 'D', text: '"...são praticados em equipe, exigindo cooperação e estratégia entre os jogadores."' },
    ],
    correctAnswer: 'D',
  },
];
