export const questoesCiencias7AnoB1Av1 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'A camada de gases que envolve a Terra e permite a vida é chamada de:',
    tip: 'Pense na palavra "atmosfera" — ela tem a ver com "ar" (do grego "atmos")!',
    funFact: 'Sem a atmosfera, a Terra ficaria exposta diretamente à radiação do Sol e a meteoros, como acontece na Lua!',
    points: 1,
    options: [
      { id: 'A', text: 'Hidrosfera' },
      { id: 'B', text: 'Atmosfera' },
      { id: 'C', text: 'Litosfera' },
      { id: 'D', text: 'Biosfera' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'Qual é o gás mais abundante na atmosfera terrestre?',
    tip: 'Muita gente pensa que é o oxigênio, mas na verdade existe um gás ainda mais abundante no ar que respiramos!',
    funFact: 'O nitrogênio representa cerca de 78% do ar atmosférico — bem mais do que o oxigênio!',
    points: 1,
    options: [
      { id: 'A', text: 'Oxigênio' },
      { id: 'B', text: 'Gás carbônico' },
      { id: 'C', text: 'Hidrogênio' },
      { id: 'D', text: 'Nitrogênio' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'Aproximadamente qual porcentagem do ar atmosférico é composta por oxigênio?',
    tip: 'O oxigênio é importante, mas é bem menos abundante do que o nitrogênio no ar!',
    funFact: 'Os outros gases do ar (como o gás carbônico e o argônio) juntos representam menos de 1%!',
    points: 1,
    options: [
      { id: 'A', text: '21%' },
      { id: 'B', text: '78%' },
      { id: 'C', text: '50%' },
      { id: 'D', text: '1%' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'O gás que os seres humanos e a maioria dos animais respiram para viver é o:',
    tip: 'Esse é o gás que usamos nos pulmões para transformar alimento em energia!',
    funFact: 'Mesmo respirando um ar com só 21% de oxigênio, isso é suficiente para manter todos os seres vivos funcionando!',
    points: 1,
    options: [
      { id: 'A', text: 'Nitrogênio' },
      { id: 'B', text: 'Gás carbônico' },
      { id: 'C', text: 'Oxigênio' },
      { id: 'D', text: 'Hélio' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'O ar atmosférico é uma mistura de gases. Isso significa que:',
    tip: 'Lembre dos gases que você acabou de estudar: nitrogênio, oxigênio e outros — todos juntos no mesmo ar!',
    funFact: 'O ar é tão misturado que não conseguimos ver ou separar esses gases a olho nu!',
    points: 1,
    options: [
      { id: 'A', text: 'É formado por um único gás puro' },
      { id: 'B', text: 'É formado por vários gases diferentes misturados' },
      { id: 'C', text: 'Não existe de verdade' },
      { id: 'D', text: 'É sempre sólido' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'As plantas realizam a fotossíntese e, nesse processo, liberam para a atmosfera o gás:',
    tip: 'Pense no contrário da respiração: as plantas absorvem um gás e liberam outro!',
    funFact: 'As florestas e os oceanos (com suas algas) são responsáveis por boa parte do oxigênio que respiramos!',
    points: 1,
    options: [
      { id: 'A', text: 'Gás carbônico' },
      { id: 'B', text: 'Nitrogênio' },
      { id: 'C', text: 'Hélio' },
      { id: 'D', text: 'Oxigênio' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'Durante a respiração, os seres vivos liberam para a atmosfera o gás:',
    tip: 'É o oposto do que acontece na fotossíntese das plantas!',
    funFact: 'Respiração e fotossíntese formam um ciclo perfeito: um processo usa o que o outro produz!',
    points: 1,
    options: [
      { id: 'A', text: 'Oxigênio' },
      { id: 'B', text: 'Nitrogênio' },
      { id: 'C', text: 'Gás carbônico' },
      { id: 'D', text: 'Hidrogênio' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'A atmosfera é dividida em camadas. A camada mais próxima da superfície da Terra, onde vivemos e ocorrem os fenômenos climáticos, é chamada de:',
    tip: '"Tropo" vem de uma palavra grega relacionada a "mudança" — é onde o tempo muda o tempo todo (chuva, vento, nuvens)!',
    funFact: 'É na troposfera que os aviões comerciais costumam voar!',
    points: 1,
    options: [
      { id: 'A', text: 'Troposfera' },
      { id: 'B', text: 'Estratosfera' },
      { id: 'C', text: 'Mesosfera' },
      { id: 'D', text: 'Exosfera' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'A camada da atmosfera que contém a camada de ozônio, protegendo a Terra dos raios ultravioleta, é a:',
    tip: 'Essa camada fica logo acima da troposfera, onde você vive.',
    funFact: 'A camada de ozônio funciona como um "protetor solar gigante" para todo o planeta!',
    points: 1,
    options: [
      { id: 'A', text: 'Troposfera' },
      { id: 'B', text: 'Estratosfera' },
      { id: 'C', text: 'Termosfera' },
      { id: 'D', text: 'Exosfera' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'Sem a atmosfera, a vida na Terra seria:',
    tip: 'Pense em tudo que a atmosfera faz: fornece ar para respirar, protege dos raios do Sol e mantém a temperatura.',
    funFact: 'É por causa da atmosfera que o céu da Terra é azul — sem ela, o céu pareceria preto, como na Lua!',
    points: 1,
    options: [
      { id: 'A', text: 'Exatamente igual à de hoje' },
      { id: 'B', text: 'Mais fácil' },
      { id: 'C', text: 'Mais colorida' },
      { id: 'D', text: 'Impossível (ou muito diferente)' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'A camada de ozônio é importante porque ela:',
    tip: 'Pense nela como um "filtro de proteção" contra um tipo específico de raio solar.',
    funFact: 'A exposição exagerada aos raios ultravioleta pode causar queimaduras e até problemas de pele nos seres humanos!',
    points: 1,
    options: [
      { id: 'A', text: 'Filtra os raios ultravioleta prejudiciais do Sol' },
      { id: 'B', text: 'Produz oxigênio para respirarmos' },
      { id: 'C', text: 'Causa o efeito estufa' },
      { id: 'D', text: 'Esfria a Terra sozinha' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'O efeito estufa é um fenômeno natural em que certos gases da atmosfera retêm o calor do Sol. Sem ele, a Terra seria:',
    tip: 'O efeito estufa, em quantidade normal, é o que mantém a Terra "aquecidinha" o suficiente para a vida existir!',
    funFact: 'O planeta Vênus tem um efeito estufa tão exagerado que sua superfície chega a mais de 460°C!',
    points: 1,
    options: [
      { id: 'A', text: 'Mais quente' },
      { id: 'B', text: 'Igual a hoje' },
      { id: 'C', text: 'Extremamente fria' },
      { id: 'D', text: 'Sem atmosfera' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'O aumento excessivo de gases do efeito estufa, causado por atividades humanas, está relacionado a qual problema ambiental?',
    tip: 'Pense no que acontece quando o efeito estufa funciona "demais" — a Terra começa a esquentar além do normal.',
    funFact: 'O aquecimento global pode causar o derretimento de geleiras e mudanças sérias no clima do planeta!',
    points: 1,
    options: [
      { id: 'A', text: 'Buraco na camada de ozônio' },
      { id: 'B', text: 'Aquecimento global' },
      { id: 'C', text: 'Chuva ácida (apenas)' },
      { id: 'D', text: 'Maré alta' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'Qual gás é o principal responsável pelo aumento do efeito estufa devido à queima de combustíveis fósseis?',
    tip: 'Pense no gás que é liberado quando queimamos gasolina, carvão ou gás natural.',
    funFact: 'Reduzir o uso de combustíveis fósseis e plantar mais árvores ajuda a diminuir o excesso desse gás no ar!',
    points: 1,
    options: [
      { id: 'A', text: 'Oxigênio' },
      { id: 'B', text: 'Nitrogênio' },
      { id: 'C', text: 'Hélio' },
      { id: 'D', text: 'Gás carbônico (CO2)' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'A poluição do ar nas grandes cidades é causada principalmente por:',
    tip: 'Pense nas coisas que soltam fumaça nas cidades, como carros, ônibus e fábricas.',
    funFact: 'Usar transporte público, bicicleta ou carros elétricos ajuda a diminuir a poluição do ar!',
    points: 1,
    options: [
      { id: 'A', text: 'Fumaça de veículos e indústrias' },
      { id: 'B', text: 'Fotossíntese das plantas' },
      { id: 'C', text: 'Respiração dos animais' },
      { id: 'D', text: 'Evaporação da água do mar' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'A pressão atmosférica é a força que o ar exerce sobre:',
    tip: 'O ar está em toda parte ao nosso redor — e ele empurra tudo o que encontra pela frente!',
    funFact: 'Nós não sentimos o peso do ar porque nosso corpo está acostumado a essa pressão desde que nascemos!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas os oceanos' },
      { id: 'B', text: 'Apenas as montanhas' },
      { id: 'C', text: 'Todos os corpos na superfície da Terra' },
      { id: 'D', text: 'Somente os aviões' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'Em locais de maior altitude, como no topo de uma montanha, a pressão atmosférica é:',
    tip: 'Quanto mais alto você sobe, menos "camada de ar" fica em cima de você empurrando para baixo.',
    funFact: 'Por isso é mais difícil respirar em montanhas muito altas, como o Everest — há menos ar disponível!',
    points: 1,
    options: [
      { id: 'A', text: 'Igual à do nível do mar' },
      { id: 'B', text: 'Impossível de medir' },
      { id: 'C', text: 'Maior do que no nível do mar' },
      { id: 'D', text: 'Menor do que no nível do mar' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'O ar quente, por ser menos denso, tende a:',
    tip: 'Pense no ar de um balão de festa junina: por que ele sobe quando é aquecido?',
    funFact: 'Esse princípio é usado nos balões de ar quente, que sobem justamente por causa do ar aquecido dentro deles!',
    points: 1,
    options: [
      { id: 'A', text: 'Descer' },
      { id: 'B', text: 'Subir' },
      { id: 'C', text: 'Ficar parado' },
      { id: 'D', text: 'Virar água' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'Os ventos são causados principalmente pela diferença de ______ entre duas regiões.',
    tip: 'Lembre que o ar sempre se movimenta de um lugar para outro buscando um "equilíbrio" de força.',
    funFact: 'É essa diferença de pressão que gera desde uma brisa suave até furacões poderosos!',
    points: 1,
    options: [
      { id: 'A', text: 'Pressão atmosférica' },
      { id: 'B', text: 'Cor do céu' },
      { id: 'C', text: 'Quantidade de estrelas' },
      { id: 'D', text: 'Tamanho das nuvens' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'A camada de ozônio ficou com um "buraco" em algumas regiões por causa do uso de certos produtos químicos, como os antigos:',
    tip: 'Pense em produtos que, no passado, eram muito usados em sprays e aparelhos de refrigeração.',
    funFact: 'Depois que o mundo proibiu o uso de CFCs, cientistas notaram que o buraco na camada de ozônio começou a diminuir!',
    points: 1,
    options: [
      { id: 'A', text: 'Plásticos descartáveis' },
      { id: 'B', text: 'Combustíveis de carro apenas' },
      { id: 'C', text: 'CFCs (usados em sprays e geladeiras antigas)' },
      { id: 'D', text: 'Papéis reciclados' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Bernardo subiu uma montanha com sua família e sentiu dificuldade para respirar no topo. Isso aconteceu porque, em altitudes elevadas, a pressão atmosférica é:',
    tip: 'Lembre da relação entre altitude e pressão que você acabou de estudar.',
    funFact: 'Alpinistas que escalam montanhas muito altas, como o Everest, costumam usar cilindros de oxigênio extra!',
    points: 1,
    options: [
      { id: 'A', text: 'Igual à do nível do mar' },
      { id: 'B', text: 'Mais alta' },
      { id: 'C', text: 'Impossível de sentir' },
      { id: 'D', text: 'Mais baixa, com menos oxigênio disponível' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Bernardo aprendeu na escola que, ao abrir uma garrafa de refrigerante, o gás que escapa fazendo aquele barulhinho é um exemplo de gás sob pressão. Esse fenômeno está relacionado ao estudo de:',
    tip: 'Pense no que acontece quando um gás está "comprimido" dentro de um espaço fechado, como a garrafa.',
    funFact: 'O gás do refrigerante é o gás carbônico, dissolvido no líquido sob alta pressão!',
    points: 1,
    options: [
      { id: 'A', text: 'Fotossíntese' },
      { id: 'B', text: 'Pressão dos gases' },
      { id: 'C', text: 'Camada de ozônio' },
      { id: 'D', text: 'Efeito estufa' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Bernardo plantou uma mudinha na escola e aprendeu que, durante o dia, ela realiza fotossíntese. Nesse processo, a planta absorve gás carbônico e libera para o ar o gás:',
    tip: 'É o gás que nós respiramos, produzido pelas plantas durante a fotossíntese!',
    funFact: 'A mudinha de Bernardo, quando crescer, vai ajudar a "limpar" o ar da sua região!',
    points: 1,
    options: [
      { id: 'A', text: 'Nitrogênio' },
      { id: 'B', text: 'Hélio' },
      { id: 'C', text: 'Oxigênio' },
      { id: 'D', text: 'Metano' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Bernardo e sua turma visitaram uma fábrica e observaram fumaça saindo das chaminés. Esse tipo de fumaça contribui para:',
    tip: 'Pense no que a fumaça de fábricas e veículos costuma causar no ar das cidades.',
    funFact: 'Muitas fábricas hoje usam filtros especiais para reduzir a quantidade de poluentes liberados no ar!',
    points: 1,
    options: [
      { id: 'A', text: 'A poluição do ar' },
      { id: 'B', text: 'A limpeza da atmosfera' },
      { id: 'C', text: 'O aumento de oxigênio puro' },
      { id: 'D', text: 'A formação da camada de ozônio' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Bernardo está estudando as camadas da atmosfera para uma prova. A camada onde ele vive, onde o avião voa e onde se formam as nuvens é chamada de:',
    tip: 'É a camada mais próxima da superfície — a primeira que você aprendeu nesse simulado!',
    funFact: 'É na troposfera que acontecem praticamente todos os fenômenos do tempo que vemos no dia a dia!',
    points: 1,
    options: [
      { id: 'A', text: 'Estratosfera' },
      { id: 'B', text: 'Mesosfera' },
      { id: 'C', text: 'Termosfera' },
      { id: 'D', text: 'Troposfera' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Bernardo percebeu que, perto de uma fogueira, o ar quente sobe. Isso acontece porque o ar quente é:',
    tip: 'Pense no balão de ar quente — por que ele sobe quando o ar lá dentro esquenta?',
    funFact: 'Esse mesmo princípio explica por que o ar quente de dentro de casa sobe e escapa pelas frestas mais altas!',
    points: 1,
    options: [
      { id: 'A', text: 'Mais pesado que o ar frio' },
      { id: 'B', text: 'Menos denso que o ar frio' },
      { id: 'C', text: 'Do mesmo peso que o ar frio' },
      { id: 'D', text: 'Sempre invisível' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Bernardo aprendeu que os ventos acontecem por causa da diferença de pressão atmosférica entre dois lugares. O ar sempre se move da região de:',
    tip: 'Pense em uma bexiga furada: o ar sempre escapa do lugar mais "apertado" para o mais "livre".',
    funFact: 'É exatamente assim que se formam as brisas do mar que sentimos na praia!',
    points: 1,
    options: [
      { id: 'A', text: 'Maior pressão para a de menor pressão' },
      { id: 'B', text: 'Menor pressão para a de maior pressão' },
      { id: 'C', text: 'Mesma pressão para outra igual' },
      { id: 'D', text: 'O ar não se move de verdade' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Bernardo descobriu que sem a atmosfera terrestre, não existiria o fenômeno natural que mantém a Terra aquecida, chamado de:',
    tip: 'Esse fenômeno, em quantidade equilibrada, é o que torna a Terra "habitável" em termos de temperatura.',
    funFact: 'O nome "efeito estufa" vem da comparação com as estufas de plantas, que retêm calor dentro de si!',
    points: 1,
    options: [
      { id: 'A', text: 'Buraco de ozônio' },
      { id: 'B', text: 'Chuva ácida' },
      { id: 'C', text: 'Efeito estufa' },
      { id: 'D', text: 'Maré alta' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Na feira de ciências, Bernardo apresentou um cartaz mostrando que o gás mais abundante do ar que respiramos não é o oxigênio, mas sim o:',
    tip: 'Volte à segunda questão desse simulado — é o mesmo gás!',
    funFact: 'O nitrogênio é tão abundante que também é usado para fabricar fertilizantes agrícolas!',
    points: 1,
    options: [
      { id: 'A', text: 'Gás carbônico' },
      { id: 'B', text: 'Hélio' },
      { id: 'C', text: 'Hidrogênio' },
      { id: 'D', text: 'Nitrogênio' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'Depois de estudar bastante, Bernardo resumiu: a camada de gases que envolve a Terra, permite a vida e é formada principalmente por nitrogênio e oxigênio, se chama:',
    tip: 'É a mesma palavra que você aprendeu logo na primeira questão desse simulado!',
    funFact: 'Parabéns, Bernardo! Agora você já entende como funciona a atmosfera que protege e permite a vida em todo o planeta!',
    points: 1,
    options: [
      { id: 'A', text: 'Hidrosfera' },
      { id: 'B', text: 'Atmosfera' },
      { id: 'C', text: 'Litosfera' },
      { id: 'D', text: 'Crosta terrestre' },
    ],
    correctAnswer: 'B',
  },
];
