export const questoesPortugues4AnoB2Av2 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "Qual é o PLURAL correto de \"pão\"?",
    tip: "Palavras terminadas em '-ão' têm plurais irregulares em português. Há três possibilidades: '-ãos', '-ães' ou '-ões'. Qual delas é a forma correta para 'pão'?",
    funFact: "\"Você Sabia?\" — A palavra 'pão' tem o plural 'pães' — um dos três padrões de plural para palavras terminadas em '-ão'. Não há uma regra totalmente previsível, mas existem tendências: palavras oxítonas de origem latina tendem a fazer '-ões' (botão → botões), mas há exceções. 'Mão' faz 'mãos', 'pão' faz 'pães', 'alemão' faz 'alemães' — cada um no seu caminho! Em português, a prática e a leitura ensinam melhor do que qualquer regra.",
    points: 1,
    options: [
      { id: "A", text: "pãos" },
      { id: "B", text: "pões" },
      { id: "C", text: "pãoes" },
      { id: "D", text: "pães" },
    ],
    correctAnswer: "D",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "Qual das palavras é um SUBSTANTIVO COLETIVO?",
    tip: "Substantivos coletivos nomeiam um conjunto de seres ou coisas da mesma espécie com uma única palavra. 'Um cardume' é um grupo de peixes. Qual opção é um coletivo?",
    funFact: "\"Você Sabia?\" — 'Manada' é o coletivo de bovinos, mas também se usa para cavalos, elefantes e outros animais de grande porte que andam em grupos. Em inglês, o equivalente mais próximo é 'herd'. Curiosamente, 'manada' vem do verbo 'manar' (fazer mão, conduzir com a mão) — porque os pastores conduziam os animais com as mãos e varas. A etimologia das palavras revela muito sobre como nossos ancestrais viviam!",
    points: 1,
    options: [
      { id: "A", text: "cachorro" },
      { id: "B", text: "manada" },
      { id: "C", text: "animal" },
      { id: "D", text: "fazenda" },
    ],
    correctAnswer: "B",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "Qual é uma característica do TEXTO DESCRITIVO?",
    tip: "Texto descritivo é aquele que apresenta as características de algo ou alguém, como se fosse uma fotografia em palavras. O que ele principalmente faz?",
    funFact: "\"Você Sabia?\" — A descrição é tão poderosa que pode nos fazer 'ver' coisas que nunca vimos! A escritora inglesa Charlotte Brontë descreveu paisagens de Yorkshire com tanta precisão que turistas do século XXI viajam para o norte da Inglaterra para ver os lugares que ela retratou — mais de 150 anos depois. Uma boa descrição é imortal.",
    points: 1,
    options: [
      { id: "A", text: "Conta uma história com começo, meio e fim." },
      { id: "B", text: "Apresenta dados e informações sobre um tema." },
      { id: "C", text: "Detalha as características de pessoas, lugares ou objetos." },
      { id: "D", text: "Ensina como fazer algo com passos numerados." },
    ],
    correctAnswer: "C",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "Em qual frase a VÍRGULA foi usada corretamente para separar o VOCATIVO (chamamento)?",
    tip: "O vocativo é quando você chama diretamente alguém pelo nome ou título no início de uma frase. Ele sempre deve ser separado por vírgula do resto da frase.",
    funFact: "\"Você Sabia?\" — O vocativo vem do latim 'vocare' (chamar). Quando dizemos 'Maria, venha cá!' ou 'Professor, tenho uma pergunta!', estamos usando o vocativo. Em cartas formais, o vocativo aparece com 'Caro', 'Prezado' ou 'Excelentíssimo'. Em latim, havia até um caso gramatical inteiro dedicado ao vocativo — o 'casus vocativus'. Em português, herdamos o uso, mas não o caso.",
    points: 1,
    options: [
      { id: "A", text: "\"Maria, venha aqui!\"" },
      { id: "B", text: "\"Maria venha, aqui!\"" },
      { id: "C", text: "\"Maria venha aqui,!\"" },
      { id: "D", text: "\",Maria venha aqui!\"" },
    ],
    correctAnswer: "A",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "Qual das palavras é um ADJETIVO?",
    tip: "Adjetivos caracterizam ou qualificam substantivos. Eles dizem como alguém é, como algo parece, qual é a qualidade de uma coisa. Qual das opções faz isso?",
    funFact: "\"Você Sabia?\" — A palavra 'corajoso' vem de 'coração' + '-oso' (sufixo que indica 'cheio de'). Então 'corajoso' literalmente significa 'cheio de coração'! Muitos adjetivos em português são formados assim: 'bondoso' (cheio de bondade), 'perigoso' (cheio de perigo), 'amoroso' (cheio de amor). O sufixo '-oso' é um dos mais produtivos na formação de adjetivos em nossa língua.",
    points: 1,
    options: [
      { id: "A", text: "menina" },
      { id: "B", text: "correr" },
      { id: "C", text: "escola" },
      { id: "D", text: "corajoso" },
    ],
    correctAnswer: "D",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "Qual é o PLURAL correto de \"cidadão\"?",
    tip: "Palavras terminadas em '-ão' têm plurais variados. 'Cidadão' segue qual padrão — '-ãos', '-ães' ou '-ões'?",
    funFact: "\"Você Sabia?\" — 'Cidadão' vem do latim 'civitatem' (cidade) e surgiu na Idade Média para designar os moradores de cidades com direitos específicos, em oposição aos camponeses. Com a Revolução Francesa (1789), 'cidadão' ganhou um sentido político poderoso — todos eram iguais perante a lei. No Brasil, a Constituição de 1988 é chamada de 'Constituição Cidadã' justamente por ampliar os direitos de todos os brasileiros.",
    points: 1,
    options: [
      { id: "A", text: "cidadões" },
      { id: "B", text: "cidadãos" },
      { id: "C", text: "cidadões" },
      { id: "D", text: "cidadaões" },
    ],
    correctAnswer: "B",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "Qual é uma característica do TEXTO NARRATIVO?",
    tip: "O texto narrativo conta uma história — uma sequência de eventos com personagens que passam por situações. O que o diferencia dos outros tipos de texto?",
    funFact: "\"Você Sabia?\" — O maior texto narrativo escrito por um único autor em língua portuguesa é provavelmente 'Memorial de Aires', de Machado de Assis, escrito em 1908, quando o autor tinha 69 anos e estava muito doente. Mas em língua inglesa, o recordista seria Marcel Proust com 'Em Busca do Tempo Perdido' — cerca de 1,5 milhão de palavras! Para comparação, a Bíblia tem aproximadamente 750.000 palavras.",
    points: 1,
    options: [
      { id: "A", text: "Descreve as qualidades de um lugar em detalhes." },
      { id: "B", text: "Apresenta fatos com dados numéricos e estatísticas." },
      { id: "C", text: "Conta uma história com personagens que vivem situações." },
      { id: "D", text: "Ensina a executar uma tarefa com instruções sequenciais." },
    ],
    correctAnswer: "C",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "Qual é o uso correto do PONTO DE EXCLAMAÇÃO (!)?",
    tip: "O ponto de exclamação indica emoção intensa. Em qual situação faz mais sentido usá-lo?",
    funFact: "\"Você Sabia?\" — Na era dos emojis e das redes sociais, o ponto de exclamação sofreu uma 'inflação emocional'. Como todo mundo usa muitos pontos de exclamação, uma frase sem ele pode parecer mais fria do que era pretendido. Linguistas chamam isso de 'marcador de afeição' — um sinal que indica que a mensagem é amigável. É fascinante ver como a linguagem escrita evolui com as novas tecnologias de comunicação!",
    points: 1,
    options: [
      { id: "A", text: "Para expressar emoção intensa como surpresa, alegria ou ordem." },
      { id: "B", text: "Para indicar o final de uma pergunta." },
      { id: "C", text: "Para introduzir uma lista ou explicação." },
      { id: "D", text: "Para indicar pausa entre itens de uma enumeração." },
    ],
    correctAnswer: "A",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "Qual das palavras é um SUBSTANTIVO PRÓPRIO?",
    tip: "Substantivos próprios são nomes específicos e únicos — de pessoas, lugares, rios, empresas. Eles são sempre escritos com letra maiúscula.",
    funFact: "\"Você Sabia?\" — A palavra 'Amazônia' vem de 'Amazonas', nome dado pelos colonizadores espanhóis ao maior rio da América do Sul. Há várias teorias sobre a origem: uma diz que vem de uma tribo indígena chamada 'Amassunu'; outra diz que os exploradores se lembraram das lendárias guerreiras Amazonas da mitologia grega ao ver mulheres indígenas guerreiras. A floresta Amazônica tem mais de 5 milhões de km² e abriga cerca de 10% de toda a biodiversidade do planeta!",
    points: 1,
    options: [
      { id: "A", text: "cidade" },
      { id: "B", text: "menino" },
      { id: "C", text: "escola" },
      { id: "D", text: "Amazônia" },
    ],
    correctAnswer: "D",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "Leia: \"O gato preguiçoso dormia na cadeira velha.\"\n\nOs ADJETIVOS desta frase são:",
    tip: "Adjetivos são palavras que caracterizam os substantivos. Na frase, quais palavras estão descrevendo o gato e a cadeira?",
    funFact: "\"Você Sabia?\" — Gatos dormem em média 12 a 16 horas por dia — e isso os tornaria MUITO 'preguiçosos' segundo os humanos! Mas na verdade, o sono excessivo dos gatos é uma adaptação evolutiva de predadores: após uma caça intensa, precisam recuperar energia. Filhotes de gato chegam a dormir 20 horas por dia! O adjetivo 'preguiçoso', embora apareça na frase, é uma perspectiva humana sobre comportamento animal.",
    points: 1,
    options: [
      { id: "A", text: "gato e cadeira" },
      { id: "B", text: "preguiçoso e velha" },
      { id: "C", text: "dormia e cadeira" },
      { id: "D", text: "preguiçoso e cadeira" },
    ],
    correctAnswer: "B",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Qual das palavras é um SUBSTANTIVO ABSTRATO?",
    tip: "Substantivos abstratos nomeiam sentimentos, estados ou qualidades que não podemos perceber pelos sentidos. Qual das opções você NÃO pode ver, tocar, cheirar ou ouvir?",
    funFact: "\"Você Sabia?\" — 'Tristeza' é um dos substantivos abstratos mais estudados pela psicologia. O psicólogo Paul Ekman identificou seis emoções universais básicas, presentes em todas as culturas humanas: alegria, tristeza, medo, raiva, surpresa e nojo. Isso significa que 'tristeza' (e seu conceito abstrato) existe em TODA língua humana — é um universal linguístico! É fascinante que todas as línguas tenham nomes para esse sentimento.",
    points: 1,
    options: [
      { id: "A", text: "pedra" },
      { id: "B", text: "livro" },
      { id: "C", text: "tristeza" },
      { id: "D", text: "computador" },
    ],
    correctAnswer: "C",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Qual é o PLURAL correto de \"mal\"?",
    tip: "Palavras terminadas em '-l' no singular geralmente fazem seu plural substituindo o '-l' por '-is'. Como fica 'mal' no plural?",
    funFact: "\"Você Sabia?\" — As palavras terminadas em '-al' fazem plural em '-ais': animal → animais, capital → capitais, mal → males... espera! 'Mal' faz 'males', não 'mais' — porque 'mais' já existe com outro significado (more). É uma das exceções do português! 'Cônsul' faz 'cônsules', não 'cônsuis'. A língua, sendo viva, cria exceções para evitar confusão.",
    points: 1,
    options: [
      { id: "A", text: "males" },
      { id: "B", text: "mals" },
      { id: "C", text: "maises" },
      { id: "D", text: "mais" },
    ],
    correctAnswer: "A",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "Leia o texto:\n\n\"Para fazer uma pipa: você vai precisar de papel, vareta de bambu, linha e cola. 1. Faça um losango com as varetas. 2. Cubra com papel. 3. Adicione a cauda.\"\n\nEste texto é:",
    tip: "Observe o objetivo do texto: ele conta uma história? Descreve a aparência da pipa? Informa sobre a origem da pipa? Ou ensina, passo a passo, como construir uma pipa?",
    funFact: "\"Você Sabia?\" — As pipas (ou papagaios, como são chamadas em algumas regiões do Brasil) foram inventadas na China há mais de 2.000 anos! Eram usadas para fins militares, religiosos e para medir distâncias. Chegaram ao Brasil com os colonizadores portugueses, que as conheceram no Oriente. No Brasil, cada região tem um nome diferente: pipa (Sul e Sudeste), papagaio (Centro-Oeste e Norte), arraia (Nordeste), pandorga (Rio Grande do Sul).",
    points: 1,
    options: [
      { id: "A", text: "Texto narrativo — conta a história de como alguém fez uma pipa." },
      { id: "B", text: "Texto descritivo — descreve como a pipa é bonita." },
      { id: "C", text: "Texto informativo — informa sobre a origem da pipa." },
      { id: "D", text: "Texto instrucional — ensina como construir uma pipa." },
    ],
    correctAnswer: "D",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "Qual é a LOCUÇÃO ADJETIVA equivalente ao adjetivo \"áureo\" (que significa 'de ouro' ou 'dourado')?",
    tip: "Locução adjetiva é uma expressão que funciona como adjetivo. O adjetivo 'áureo' (da raiz latina 'aurum' = ouro) equivale a qual locução adjetiva?",
    funFact: "\"Você Sabia?\" — 'Áureo' vem do latim 'aurum' (ouro). O símbolo químico do ouro é 'Au' — a abreviação do latim 'aurum'! Outras palavras derivadas: 'aurora' (o céu dourado do amanhecer), 'auriverde' (amarelo-esverdeado, adjetivo do Brasil), 'áurea' (de ouro, como em 'Lei Áurea' que aboliu a escravidão em 1888). A etimologia conecta palavras aparentemente sem relação!",
    points: 1,
    options: [
      { id: "A", text: "de madeira" },
      { id: "B", text: "de ouro" },
      { id: "C", text: "de ferro" },
      { id: "D", text: "de plástico" },
    ],
    correctAnswer: "B",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "As RETICÊNCIAS (...) são usadas para:",
    tip: "As reticências indicam uma pausa especial na frase — uma ideia que ficou incompleta, suspense, hesitação ou algo que o leitor deve completar com a imaginação.",
    funFact: "\"Você Sabia?\" — As reticências têm EXATAMENTE três pontos — nem dois, nem quatro. Em inglês, são chamadas de 'ellipsis' (do grego 'elleipsis' = omissão). Na escrita literária, as reticências são poderosas porque criam silêncio no texto — e o silêncio pode ser tão expressivo quanto as palavras. Fernando Pessoa usava reticências magistralmente para expressar a inconclusão de pensamentos e emoções.",
    points: 1,
    options: [
      { id: "A", text: "Finalizar uma frase afirmativa." },
      { id: "B", text: "Introduzir uma enumeração ou lista." },
      { id: "C", text: "Indicar que o pensamento ficou incompleto ou criar suspense." },
      { id: "D", text: "Separar o vocativo do restante da frase." },
    ],
    correctAnswer: "C",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "Qual é o PLURAL correto de \"lápis\"?",
    tip: "Algumas palavras no plural ficam iguais ao singular! Palavras terminadas em '-s' na sílaba tônica final não mudam no plural. Como fica 'lápis' no plural?",
    funFact: "\"Você Sabia?\" — 'Lápis' vem do latim 'lapis' (pedra). Os primeiros 'lápis' eram feitos com um mineral chamado grafita, descoberto na Inglaterra em 1565. As pessoas achavam que era uma forma de chumbo (lead, em inglês) e chamavam os lápis de 'pencils de lead'. Por isso, em inglês, o interior do lápis ainda é chamado de 'lead' — mesmo que seja grafita! O lápis de madeira foi inventado pelos alemães no século XVII.",
    points: 1,
    options: [
      { id: "A", text: "lápis" },
      { id: "B", text: "lápises" },
      { id: "C", text: "lápiss" },
      { id: "D", text: "lápeis" },
    ],
    correctAnswer: "A",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "Leia: \"A cidade de São Paulo é grande, movimentada e moderna.\"\n\nQuantos ADJETIVOS há nessa frase?",
    tip: "Adjetivos são palavras que caracterizam substantivos. Na frase, quais palavras descrevem São Paulo?",
    funFact: "\"Você Sabia?\" — São Paulo é a maior cidade do hemisfério sul e a quarta maior do mundo, com mais de 12 milhões de habitantes na capital e mais de 22 milhões na Grande São Paulo. É a cidade com mais heliportos do mundo (mais de 200!) — uma solução para o trânsito caótico, mas que só os mais ricos podem usar. O nome vem do apóstolo São Paulo, porque a fundação jesuíta ocorreu no dia 25 de janeiro de 1554, dia da conversão de São Paulo.",
    points: 1,
    options: [
      { id: "A", text: "Um" },
      { id: "B", text: "Dois" },
      { id: "C", text: "Quatro" },
      { id: "D", text: "Três" },
    ],
    correctAnswer: "D",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "Qual das palavras é um ADJETIVO GENTÍLICO (que indica origem ou nacionalidade)?",
    tip: "Adjetivos gentílicos indicam de onde alguém ou algo é. 'Brasileiro' indica que alguém é do Brasil. Qual das opções indica a origem de alguém?",
    funFact: "\"Você Sabia?\" — 'Paulistano' é o gentílico de quem nasceu na cidade de São Paulo, enquanto 'paulista' é de quem nasceu no estado. Essa distinção entre cidade e estado acontece em vários casos: 'carioca' (cidade do Rio) e 'fluminense' (estado do Rio), 'manauara' (cidade de Manaus) e 'amazonense' (estado do Amazonas). É uma forma linguística de distinguir onde especificamente alguém é de!",
    points: 1,
    options: [
      { id: "A", text: "bonito" },
      { id: "B", text: "paulistano" },
      { id: "C", text: "alto" },
      { id: "D", text: "simpático" },
    ],
    correctAnswer: "B",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "Em qual frase a pontuação está CORRETA para expressar admiração?",
    tip: "Para expressar admiração ou entusiasmo, usamos o ponto de exclamação. Observe as frases e identifique qual usa a pontuação corretamente.",
    funFact: "\"Você Sabia?\" — A frase 'Olha que belo dia!' é um exemplo claro de sentença exclamativa. Em gramática, as frases se classificam por finalidade: declarativas (afirmam ou negam), interrogativas (perguntam), exclamativas (expressam emoção), imperativas (ordenam ou pedem) e optativas (expressam desejo). Cada uma tem seu sinal de pontuação preferencial — embora, na prática, alguns sinais possam ser usados em mais de um tipo.",
    points: 1,
    options: [
      { id: "A", text: "\"Olha que belo dia. O sol brilha com intensidade?\"" },
      { id: "B", text: "\"Olha que belo dia? O sol brilha com intensidade.\"" },
      { id: "C", text: "\"Olha que belo dia! O sol brilha com intensidade.\"" },
      { id: "D", text: "\"Olha que belo dia, O sol brilha com intensidade.\"" },
    ],
    correctAnswer: "C",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "Leia o texto:\n\n\"O leão é o maior felino da África. Vive em grupos chamados matilha, caça em grupo e pode alcançar velocidades de até 80 km/h em corridas curtas.\"\n\nEste texto é:",
    tip: "Observe o objetivo do texto: ele conta uma história sobre leões? Descreve como o leão é bonito? Ensina a caçar? Ou apresenta dados e informações sobre o animal?",
    funFact: "\"Você Sabia?\" — O leão, ao contrário do que muitos pensam, não é o felino mais rápido — o guepardo alcança até 120 km/h! E tecnicamente, o tigre é maior que o leão em peso e comprimento. Mas o leão é chamado de 'rei da selva' por causa do juba impressionante dos machos e de seu comportamento de dominância territorial. A ciência às vezes contradiz mitos culturais populares — e isso é fascinante!",
    points: 1,
    options: [
      { id: "A", text: "Texto informativo — apresenta dados sobre o leão." },
      { id: "B", text: "Texto narrativo — conta uma história sobre o leão." },
      { id: "C", text: "Texto descritivo — descreve a aparência do leão." },
      { id: "D", text: "Texto instrucional — ensina como observar o leão." },
    ],
    correctAnswer: "A",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Qual é o SUBSTANTIVO COLETIVO de navios?",
    tip: "Assim como 'cardume' (peixes) e 'alcateia' (lobos), existe uma palavra específica para designar um conjunto de navios. Qual é ela?",
    funFact: "\"Você Sabia?\" — Uma 'frota' de navios de guerra pode ser chamada de 'armada' ou 'esquadra'. A 'Armada Invencível' era o nome da frota naval espanhola enviada para conquistar a Inglaterra em 1588 — foi derrotada por uma combinação de táticas inglesas e uma tempestade no Mar do Norte. Ironicamente, a 'invencível' foi vencida! O nome ficou como lição histórica sobre o perigo do excesso de confiança.",
    points: 1,
    options: [
      { id: "A", text: "manada" },
      { id: "B", text: "revoada" },
      { id: "C", text: "frota" },
      { id: "D", text: "alcateia" },
    ],
    correctAnswer: "C",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Qual é o SINGULAR de \"cidadãos\"?",
    tip: "Se 'cidadãos' é o plural, qual é a forma singular? Lembre-se dos padrões de plural para palavras terminadas em '-ão'.",
    funFact: "\"Você Sabia?\" — O conceito de 'cidadão' evolui com o tempo. Na Grécia Antiga, eram cidadãos apenas os homens livres nascidos na cidade. Mulheres, escravos e estrangeiros não tinham direitos. No Brasil de 2024, cidadão é todo brasileiro com 16 anos ou mais, com direito a votar, trabalhar, estudar e ser protegido pela lei — um avanço enorme em relação à Grécia Antiga. A história da cidadania é a história da luta pela inclusão!",
    points: 1,
    options: [
      { id: "A", text: "cidadões" },
      { id: "B", text: "cidadão" },
      { id: "C", text: "cidade" },
      { id: "D", text: "cidadaão" },
    ],
    correctAnswer: "B",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Qual das opções é um exemplo de ADJETIVO COMPOSTO (formado por dois elementos unidos)?",
    tip: "Adjetivos compostos são formados pela união de dois adjetivos ou elementos que juntos criam um novo significado. Eles geralmente são escritos com hífen.",
    funFact: "\"Você Sabia?\" — 'Surdo-mudo' foi por muito tempo o termo médico oficial para pessoas com deficiência auditiva severa e sem fala. Hoje, os próprios surdos e profissionais da saúde preferem o termo 'surdo' simplesmente, pois muitos surdos desenvolvem fala com treinamento, e 'surdo-mudo' pode soar pejorativo. A linguagem evolui para ser mais precisa e respeitosa — e isso é um sinal de amadurecimento social.",
    points: 1,
    options: [
      { id: "A", text: "bonito" },
      { id: "B", text: "estudioso" },
      { id: "C", text: "inteligente" },
      { id: "D", text: "surdo-mudo" },
    ],
    correctAnswer: "D",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Qual das opções apresenta uma LOCUÇÃO ADJETIVA?",
    tip: "Locução adjetiva é uma expressão (geralmente preposição + substantivo) que funciona como adjetivo. 'Olhos de mel' = olhos dourados/melados. Qual opção segue esse padrão?",
    funFact: "\"Você Sabia?\" — 'Olhos de mel' é uma das metáforas mais antigas da poesia portuguesa. Em 'Os Lusíadas', de Camões, e em poemas medievais portugueses, a beleza feminina era frequentemente descrita com locuções adjetivas que evocavam a natureza: 'cabelos de ouro', 'lábios de coral', 'pele de alabastro'. Essas expressões criavam imagens sensoriais ricas — uma tradição poética que atravessou séculos!",
    points: 1,
    options: [
      { id: "A", text: "\"olhos de mel\"" },
      { id: "B", text: "\"olhos bonitos\"" },
      { id: "C", text: "\"olhos grandes\"" },
      { id: "D", text: "\"olhos castanhos\"" },
    ],
    correctAnswer: "A",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Qual das palavras é um SUBSTANTIVO COLETIVO?",
    tip: "Substantivos coletivos são palavras no singular que indicam um conjunto de seres da mesma espécie. 'Floresta' é um conjunto de quê?",
    funFact: "\"Você Sabia?\" — 'Floresta' é o coletivo de árvores, mas também existem termos mais específicos: 'mata' (floresta densa), 'bosque' (pequena floresta), 'selva' (floresta tropical), 'capoeira' (vegetação secundária que cresceu onde houve mata), 'cerrado' (savana brasileira) e 'caatinga' (bioma do Nordeste). O Brasil tem a maior biodiversidade florestal do planeta — e cada tipo de vegetação tem seu nome específico!",
    points: 1,
    options: [
      { id: "A", text: "folha" },
      { id: "B", text: "árvore" },
      { id: "C", text: "floresta" },
      { id: "D", text: "raiz" },
    ],
    correctAnswer: "C",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Em qual frase o ADJETIVO concorda corretamente com o substantivo?",
    tip: "Os adjetivos precisam concordar em gênero (masculino/feminino) e número (singular/plural) com os substantivos que acompanham. Analise cada frase.",
    funFact: "\"Você Sabia?\" — 'Os livros interessantes' — aqui 'interessantes' está no plural masculino, concordando com 'livros' (plural masculino). Se fosse 'as revistas interessantes', o adjetivo teria a mesma forma porque 'interessante' não tem variação de gênero (apenas de número). Alguns adjetivos têm forma única para masculino e feminino: inteligente, importante, grande, forte. Outros têm formas diferentes: bonito/bonita, amarelo/amarela, novo/nova.",
    points: 1,
    options: [
      { id: "A", text: "\"Os livros interessante estão na estante.\"" },
      { id: "B", text: "\"Os livros interessantes estão na estante.\"" },
      { id: "C", text: "\"Os livros interessantes está na estante.\"" },
      { id: "D", text: "\"Os livro interessantes estão na estante.\"" },
    ],
    correctAnswer: "B",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Qual é o PLURAL correto de \"animal\"?",
    tip: "Palavras terminadas em '-al' geralmente formam o plural substituindo o '-al' por '-ais'. Como fica 'animal' no plural?",
    funFact: "\"Você Sabia?\" — A palavra 'animal' vem do latim 'anima' (alma, vida, respiração). Originalmente, todos os seres com vida e respiração eram chamados de 'animais' — incluindo os humanos! Aristóteles classificou os humanos como 'animal racional' (animal com razão). A biologia moderna mantém essa classificação: humanos são animais — mamíferos do gênero Homo, espécie Homo sapiens. 'Sapiens' significa 'sábio' em latim — uma escolha otimista de nome para nossa espécie!",
    points: 1,
    options: [
      { id: "A", text: "animals" },
      { id: "B", text: "animales" },
      { id: "C", text: "anmais" },
      { id: "D", text: "animais" },
    ],
    correctAnswer: "D",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Qual das opções apresenta uma LOCUÇÃO ADJETIVA (expressão que funciona como adjetivo)?",
    tip: "Locução adjetiva é uma expressão com preposição + substantivo que caracteriza outro substantivo. 'Olhos de mel' é um exemplo — 'de mel' funciona como adjetivo de 'olhos'.",
    funFact: "\"Você Sabia?\" — 'Olhos de mel' é uma locução adjetiva poética — os olhos não são literalmente de mel, mas têm a cor dourada e a suavidade do mel. Quando usamos locuções adjetivas em sentido figurado, criamos metáforas. A metáfora 'coração de pedra' (de pedra = pedregoso, duro) é tão comum em português que mal percebemos que é uma figura de linguagem. Nossa língua é repleta dessas imagens poeticamente cristalizadas!",
    points: 1,
    options: [
      { id: "A", text: "\"olhos de mel\"" },
      { id: "B", text: "\"olhos bonitos\"" },
      { id: "C", text: "\"olhos grandes\"" },
      { id: "D", text: "\"olhos castanhos\"" },
    ],
    correctAnswer: "A",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Leia: \"Quando era pequeno, meu avô pescava no rio todos os dias.\"\n\nQual é o ADJETIVO nessa frase?",
    tip: "Adjetivos descrevem ou qualificam substantivos. Na frase, qual palavra está descrevendo uma característica de alguém ou algo?",
    funFact: "\"Você Sabia?\" — O adjetivo 'pequeno' tem graus: positivo (pequeno), comparativo (menor/mais pequeno) e superlativo (mínimo/pequeníssimo). Em português, usamos tanto as formas sintéticas latinas (menor, mínimo) quanto as formas analíticas (mais pequeno, muito pequeno). Essa dupla tradição — do latim e do vernáculo — é uma das riquezas e das complexidades da gramática portuguesa!",
    points: 1,
    options: [
      { id: "A", text: "pescava" },
      { id: "B", text: "avô" },
      { id: "C", text: "pequeno" },
      { id: "D", text: "rio" },
    ],
    correctAnswer: "C",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Qual é o PLURAL correto de \"papel\"?",
    tip: "Palavras terminadas em '-el' formam o plural substituindo o '-el' por '-éis' (com acento). Como fica 'papel' no plural?",
    funFact: "\"Você Sabia?\" — O papel foi inventado pelos chineses por volta do ano 105 d.C., pelo eunuco imperial Cai Lun, que usou cascas de árvore, bambu e trapos. O segredo da fabricação foi guardado pelos chineses por séculos, até que árabes capturaram artesãos chineses em 751 d.C. e aprenderam a técnica. O papel chegou à Europa pelo século XII. Antes do papel, os europeus usavam pergaminho (feito de pele de animais) — muito mais caro e difícil de produzir!",
    points: 1,
    options: [
      { id: "A", text: "papeles" },
      { id: "B", text: "papéis" },
      { id: "C", text: "papeis" },
      { id: "D", text: "papels" },
    ],
    correctAnswer: "B",
  },
];
