export const questoesHistoria1EmB3Av1 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "Segundo a tradição romana, Roma foi fundada em 753 a.C. às margens de qual rio, situado na Península Itálica?",
    tip: "O nome desse rio é mencionado até hoje em expressão popular. Ele atravessa a cidade de Roma e foi fundamental para o desenvolvimento da civilização romana.",
    funFact: "\"Você sabia?\" — A expressão 'cruzar o Rubicão' vem de outro rio romano, mas foi o Tibre que viu Roma crescer de uma aldeia de pastores a senhora do mundo. Roma está localizada nos sete montes às suas margens.",
    points: 1,
    options: [
      { id: "A", text: "Rio Pó, no norte da Itália" },
      { id: "B", text: "Rio Arno, na Toscana" },
      { id: "C", text: "Rio Tibre, na região central da Península Itálica, onde Roma cresceu dos Sete Montes" },
      { id: "D", text: "Rio Nilo, no norte da África" },
    ],
    correctAnswer: "C",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "Segundo a mitologia romana, quem fundou Roma e se tornou seu primeiro rei?",
    tip: "A lenda diz que ele e seu irmão gêmeo foram criados por uma loba após serem abandonados num cesto no rio Tibre. Os dois irmãos entraram em conflito pelo poder.",
    funFact: "\"Você sabia?\" — A loba capitolina que amamentou os gêmeos Rômulo e Remo é o símbolo de Roma até hoje. A famosa estátua da Loba Capitolina está nos Museus Capitolinos em Roma.",
    points: 1,
    options: [
      { id: "A", text: "Rômulo, que segundo a tradição fundou Roma em 753 a.C. e matou seu irmão Remo numa disputa pelo poder" },
      { id: "B", text: "Tarquínio, o último rei de Roma antes da República" },
      { id: "C", text: "Enéias, herói troiano que fugiu de Troia e chegou ao Lácio" },
      { id: "D", text: "Júlio César, o grande general que dominou Roma no século I a.C." },
    ],
    correctAnswer: "A",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "A República Romana foi instaurada em 509 a.C. O que motivou a transição da monarquia para a república?",
    tip: "O último rei romano era chamado de 'o Soberbo' — um apelido que reflete como ele era visto. Um ato violento praticado por seu filho foi a gota d'água que detonou a revolta.",
    funFact: "\"Você sabia?\" — O estupro de Lucrécia pelo príncipe Sexto Tarquínio levou seu marido e seu pai a organizar a expulsão dos Tarquínios. Lúcio Júnio Bruto liderou a revolta e se tornou um dos primeiros cônsules.",
    points: 1,
    options: [
      { id: "A", text: "A derrota militar de Roma nas Guerras Púnicas contra Cartago" },
      { id: "B", text: "A expulsão do rei Tarquínio, o Soberbo, após os abusos da monarquia, e a instauração de um governo coletivo dos aristocratas romanos" },
      { id: "C", text: "Uma invasão dos gauleses que destruiu a monarquia romana" },
      { id: "D", text: "A morte de Rômulo sem deixar herdeiro, forçando a adoção de outro sistema" },
    ],
    correctAnswer: "B",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "Na República Romana, os cônsules eram os principais magistrados. Qual era a principal característica do consulado?",
    tip: "Os romanos tinham pavor de que uma única pessoa acumulasse poder demais após a experiência da monarquia. Por isso criaram um sistema com freios e contrapesos no consulado.",
    funFact: "\"Você sabia?\" — Em situações de emergência, Roma podia nomear um ditador com poderes absolutos por no máximo 6 meses. O general Cincinato é o exemplo mais famoso: voltou a arar sua terra assim que a crise passou.",
    points: 1,
    options: [
      { id: "A", text: "Um único cônsul governava por dez anos com poderes ilimitados" },
      { id: "B", text: "Eram vitalícios, escolhidos pelo povo em assembleias populares anuais" },
      { id: "C", text: "Eram escolhidos pelos escravos libertos para representar os pobres no governo" },
      { id: "D", text: "Dois magistrados eleitos anualmente, com poderes iguais e direito de veto mútuo (intercessio), exercendo o poder executivo máximo da República" },
    ],
    correctAnswer: "D",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "O Senado Romano era o órgão mais poderoso da República. Quem compunha o Senado e qual era sua principal função?",
    tip: "O Senado não era eleito pelo povo comum — seus membros vinham de uma classe social específica e acumulavam experiência ao longo de toda a vida.",
    funFact: "\"Você sabia?\" — A expressão latina SPQR (Senatus Populusque Romanus — 'o Senado e o povo romano') era o lema oficial de Roma e ainda aparece nos bueiros e documentos oficiais da cidade de Roma hoje.",
    points: 1,
    options: [
      { id: "A", text: "Era composto por plebeus eleitos anualmente para controlar o tesouro público de Roma" },
      { id: "B", text: "Era formado pelos generais vitoriosos que retornavam das guerras com seus exércitos" },
      { id: "C", text: "Composto por 300 a 600 aristocratas (patrícios e depois também plebeus ricos), controlava as finanças, a política externa e orientava os magistrados com sua autoridade moral (auctoritas)" },
      { id: "D", text: "Era a assembleia popular onde todos os cidadãos (incluindo mulheres e escravos) votavam as leis" },
    ],
    correctAnswer: "C",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "A Lei das XII Tábuas (451-450 a.C.) foi uma conquista fundamental dos plebeus romanos. O que ela representou?",
    tip: "Antes das XII Tábuas, o direito romano não era escrito — os juízes patrícios o interpretavam como queriam. A exigência da plebe era simples: escrever as leis para que todos pudessem conhecê-las.",
    funFact: "\"Você sabia?\" — A Lei das XII Tábuas era exposta em praça pública no Fórum Romano para que todos pudessem ler. Embora tenhamos perdido o original, ela é reconstruída por citações de autores romanos posteriores.",
    points: 1,
    options: [
      { id: "A", text: "Primeira codificação escrita do direito romano, tornando as leis públicas, conhecidas e aplicadas igualmente a patrícios e plebeus" },
      { id: "B", text: "Concedeu plena igualdade política entre patrícios e plebeus desde sua criação" },
      { id: "C", text: "Aboliu a escravidão e libertou todos os servos endividados" },
      { id: "D", text: "Criou o Senado Romano como órgão consultivo dos cônsules" },
    ],
    correctAnswer: "A",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "Os tribunos da plebe eram magistrados especiais criados na República Romana. Qual era o poder mais importante do tribuno?",
    tip: "O tribuno tinha um poder único no sistema romano — uma espécie de escudo contra os abusos dos magistrados patrícios. A palavra latina para esse poder significa 'intervir' ou 'se interpor'.",
    funFact: "\"Você sabia?\" — A pessoa do tribuno era inviolável (sacrossanta): ferir ou matar um tribuno era crime religioso punível com morte. Isso permitia que os tribunos protegessem qualquer plebeu perseguido por autoridades.",
    points: 1,
    options: [
      { id: "A", text: "Presidir o Senado e propor leis em nome dos patrícios" },
      { id: "B", text: "O poder de veto (intercessio) sobre qualquer ato dos magistrados patrícios que prejudicasse os plebeus, protegendo os cidadãos comuns" },
      { id: "C", text: "Comandar as legiões romanas nas guerras de expansão" },
      { id: "D", text: "Arrecadar impostos e distribuí-los entre os cidadãos mais pobres" },
    ],
    correctAnswer: "B",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "A sociedade romana era dividida entre patrícios e plebeus. O longo conflito entre essas classes foi chamado de 'luta da ordem'. Qual foi o resultado dessa luta?",
    tip: "Ao longo de séculos (494-287 a.C.), os plebeus conquistaram direitos gradualmente. Qual foi o ponto de chegada que transformou Roma numa república mais democrática?",
    funFact: "\"Você sabia?\" — A primeira grande conquista plebeia foi a criação do tribunato (494 a.C.) após a chamada 'Secessão da Plebe' — os plebeus se recusaram a servir no exército e se retiraram para o Monte Sagrado. Roma cedeu.",
    points: 1,
    options: [
      { id: "A", text: "Os plebeus foram completamente subjugados e perderam todos os direitos políticos" },
      { id: "B", text: "Os patrícios cederam todas as magistraturas e o Senado passou a ser exclusivamente plebeu" },
      { id: "C", text: "Roma se transformou numa democracia direta idêntica à de Atenas" },
      { id: "D", text: "Os plebeus conquistaram gradualmente igualdade jurídica: acesso às magistraturas, casamento com patrícios e validade legal das decisões das assembleias plebeias (Lei Hortênsia, 287 a.C.)" },
    ],
    correctAnswer: "D",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "A expansão romana pela Península Itálica foi marcada por uma política específica em relação aos povos conquistados. Como Roma garantia sua dominação na Itália?",
    tip: "Roma não simplesmente subjugava os vencidos como escravos — tinha uma política mais sofisticada de integração que criava vínculos de lealdade com os povos itálicos.",
    funFact: "\"Você sabia?\" — A Via Ápia, construída em 312 a.C., foi a primeira grande estrada romana e se estendia de Roma a Brindisi, no sul da Itália. As estradas eram essenciais para mover exércitos e conectar as colônias.",
    points: 1,
    options: [
      { id: "A", text: "Destruía completamente as cidades vencidas e escravizava toda a população" },
      { id: "B", text: "Pagava tributos aos povos vencidos para garantir sua lealdade" },
      { id: "C", text: "Combinava conquistas militares com alianças, fundação de colônias e concessão gradual de cidadania, criando uma rede de lealdades que estabilizava a Itália" },
      { id: "D", text: "Construía muralhas ao redor dos territórios conquistados para impedir fugas" },
    ],
    correctAnswer: "C",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "A Primeira Guerra Púnica (264-241 a.C.) foi o primeiro grande conflito entre Roma e Cartago. Qual foi o principal motivo dessa guerra?",
    tip: "Havia uma ilha no Mediterrâneo que era estrategicamente importante para o comércio e que tanto Roma quanto Cartago queriam controlar. Essa disputa deflagrou a guerra.",
    funFact: "\"Você sabia?\" — Roma não tinha frota de guerra antes da Primeira Guerra Púnica. Capturou um navio cartaginês encalhado, usou-o como modelo e construiu 120 navios de guerra em apenas 60 dias. Esse improviso foi a origem do poderio naval romano.",
    points: 1,
    options: [
      { id: "A", text: "O controle da Sicília, disputada entre Roma (que expandia para o sul) e Cartago (potência comercial do Mediterrâneo), foi a causa imediata da Primeira Guerra Púnica" },
      { id: "B", text: "A captura de comerciantes cartagineses por piratas sicilianos aliados a Roma" },
      { id: "C", text: "A invasão de Cartago pelo exército romano em busca de ouro africano" },
      { id: "D", text: "Um conflito religioso entre os deuses romanos e os deuses cartagineses" },
    ],
    correctAnswer: "A",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Aníbal Barca, general cartaginês da Segunda Guerra Púnica, realizou uma façanha militar considerada impossível. O que ele fez?",
    tip: "Em vez de atacar Roma pelo mar, Aníbal escolhou um caminho terrestre surpreendente que ninguém esperava — passando por uma barreira natural que se achava intransponível.",
    funFact: "\"Você sabia?\" — Aníbal perdeu um olho durante a travessia dos Apeninos, na Itália, por causa de uma infecção. Apesar disso, venceu os romanos repetidamente por 15 anos em solo italiano sem nunca conseguir tomar Roma.",
    points: 1,
    options: [
      { id: "A", text: "Construiu uma frota de 500 navios de guerra em menos de um mês" },
      { id: "B", text: "Conquistou a cidade de Roma depois de um cerco de seis meses" },
      { id: "C", text: "Firmou aliança com os gregos para atacar Roma pelo leste" },
      { id: "D", text: "Cruzou os Alpes com um exército de 40 mil soldados e 37 elefantes de guerra para invadir a Itália pelo norte, surpreendendo completamente os romanos" },
    ],
    correctAnswer: "D",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "A Batalha de Canas (216 a.C.) é estudada em academias militares até hoje. Por que ela foi tão notável?",
    tip: "Aníbal tinha um exército menor que o romano, mas usou uma tática genial de envolvimento. O resultado foi uma catástrofe sem precedentes para Roma.",
    funFact: "\"Você sabia?\" — Na Batalha de Canas, 8 cônsules e ex-cônsules romanos morreram combatendo, além de 80 senadores. Calcula-se que 80% dos soldados romanos foram mortos — a pior derrota da história de Roma.",
    points: 1,
    options: [
      { id: "A", text: "Foi a primeira batalha naval vencida por Roma contra Cartago" },
      { id: "B", text: "Aníbal cercou e destruiu um exército romano de aproximadamente 80 mil homens numa manobra dupla de envolvimento, a maior derrota militar da história de Roma (216 a.C.)" },
      { id: "C", text: "Roma venceu Aníbal e o forçou a recuar para a Espanha" },
      { id: "D", text: "Foi a batalha em que Aníbal finalmente conquistou a cidade de Roma" },
    ],
    correctAnswer: "B",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "Cipião Africano foi o general romano que virou o jogo das Guerras Púnicas. O que ele fez para derrotar Aníbal?",
    tip: "Em vez de perseguir Aníbal na Itália (o que havia levado à catástrofe de Canas), Cipião usou a mesma estratégia que Aníbal: atacar diretamente o território inimigo.",
    funFact: "\"Você sabia?\" — Cipião e Aníbal se encontraram pessoalmente antes da Batalha de Zama para negociar. Cipião recusou as condições de Aníbal. Os dois generais se encontraram novamente décadas depois, já em exílio, e Aníbal disse que Cipião era o maior general da história.",
    points: 1,
    options: [
      { id: "A", text: "Construiu uma muralha ao redor da Itália para impedir que Aníbal recebesse reforços" },
      { id: "B", text: "Recrutou elefantes africanos maiores que os de Aníbal para combatê-lo" },
      { id: "C", text: "Levou a guerra para o território inimigo, invadindo o norte da África e derrotando Aníbal na Batalha de Zama (202 a.C.), encerrando a Segunda Guerra Púnica" },
      { id: "D", text: "Assinou um tratado de paz com Cartago que encerrou as guerras sem batalha decisiva" },
    ],
    correctAnswer: "C",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "A Terceira Guerra Púnica (149-146 a.C.) terminou com a destruição definitiva de Cartago. O que exatamente os romanos fizeram com a cidade?",
    tip: "O senador Catão, o Velho, encerrava todos os seus discursos no Senado com a frase 'Cartago deve ser destruída'. Quando a guerra finalmente aconteceu, os romanos foram muito além de uma simples conquista.",
    funFact: "\"Você sabia?\" — A história de que os romanos salgaram as terras de Cartago para que nada crescesse é provavelmente um mito do século XIX. Mas a destruição foi real e total — a cidade levou séculos para ser repovoada.",
    points: 1,
    options: [
      { id: "A", text: "Roma destruiu completamente Cartago em 146 a.C., matando ou escravizando toda a população e arrasando a cidade, transformando o norte da África na província romana da África" },
      { id: "B", text: "Roma incorporou Cartago como cidade aliada com plena autonomia administrativa" },
      { id: "C", text: "Roma transformou Cartago na sua principal base naval no Mediterrâneo" },
      { id: "D", text: "Os cartagineses fugiram antes da batalha e fundaram uma nova cidade na Espanha" },
    ],
    correctAnswer: "A",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "A estrutura social romana era hierarquizada. Quais eram as principais divisões sociais da Roma republicana?",
    tip: "A sociedade romana tinha divisões muito claras, com privilégios ligados ao nascimento (patrícios vs plebeus) e ao status econômico e jurídico (cidadãos livres vs escravos).",
    funFact: "\"Você sabia?\" — Os escravos chegaram a representar até 40% da população de Roma no auge da República. Diferentemente da escravidão moderna baseada em raça, qualquer pessoa poderia se tornar escrava se fosse capturada em guerra ou incapaz de pagar dívidas.",
    points: 1,
    options: [
      { id: "A", text: "Apenas duas classes: os ricos e os pobres, sem distinção de direitos jurídicos" },
      { id: "B", text: "Três classes iguais: senadores, cavaleiros e plebeus, todos com os mesmos direitos" },
      { id: "C", text: "Quatro classes iguais: patrícios, plebeus, escravos e estrangeiros, todos com igualdade jurídica" },
      { id: "D", text: "Patrícios (aristocracia hereditária), plebeus (cidadãos livres), clientes (dependentes), libertos (ex-escravos) e escravos, cada grupo com direitos específicos" },
    ],
    correctAnswer: "D",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "O exército romano (legião) era a principal ferramenta do poder de Roma. O que tornava as legiões romanas tão eficientes?",
    tip: "O exército romano não era apenas numeroso — era extraordinariamente bem organizado e treinado. Seu sucesso dependia de disciplina, organização e engenharia, não apenas de bravura.",
    funFact: "\"Você sabia?\" — Os soldados romanos (legionários) construíam um forte (castra) a cada noite de campanha. Depois de cada batalha, uma legião podia construir um forte completo com fosso, muralha e torres em poucas horas.",
    points: 1,
    options: [
      { id: "A", text: "O uso de elefantes de guerra superiores aos dos inimigos" },
      { id: "B", text: "Organização em legiões com tática flexível (manípulos e depois coortes), disciplina rígida, engenharia militar avançada e treinamento contínuo" },
      { id: "C", text: "A superioridade numérica — Roma sempre tinha exércitos dez vezes maiores que os inimigos" },
      { id: "D", text: "O uso de armas secretas desenvolvidas por engenheiros gregos a serviço de Roma" },
    ],
    correctAnswer: "B",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "A construção de estradas foi uma das maiores obras da República e do Império Romano. Qual era a função principal das estradas romanas?",
    tip: "As estradas eram obras de engenharia impressionantes — drenas, multicamadas, pavimentadas. Mas por que Roma investia tanto nessa infraestrutura?",
    funFact: "\"Você sabia?\" — O Império Romano construiu cerca de 400 mil km de estradas, sendo 80 mil km pavimentadas. Muitas dessas estradas ainda existem ou foram a base de rodovias modernas europeias.",
    points: 1,
    options: [
      { id: "A", text: "Serviam principalmente para corridas de bigas e espetáculos de entretenimento popular" },
      { id: "B", text: "Foram construídas apenas para o comércio, sem qualquer função militar" },
      { id: "C", text: "Tinham função estratégica: permitiam o deslocamento rápido das legiões, a comunicação, o comércio e a integração das províncias — a espinha dorsal do controle territorial romano" },
      { id: "D", text: "Eram usadas exclusivamente para peregrinações religiosas entre os templos das províncias" },
    ],
    correctAnswer: "C",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "Cartago, a principal rival de Roma nas Guerras Púnicas, era originalmente uma colônia de qual povo?",
    tip: "Cartago foi fundada por um povo famoso por seu domínio do comércio marítimo no Mediterrâneo — os mesmos que inventaram o alfabeto.",
    funFact: "\"Você sabia?\" — A fundação de Cartago é datada em 814 a.C., pela rainha fenícia Dido, que teria comprado apenas a extensão de terra que uma pele de boi pudesse cobrir — e cortou-a em tiras finas para cercar uma colina inteira.",
    points: 1,
    options: [
      { id: "A", text: "Colônia fenícia fundada no norte da África (atual Tunísia) que cresceu até se tornar a maior potência comercial e naval do Mediterrâneo Ocidental, rival de Roma" },
      { id: "B", text: "Colônia grega fundada por colonos de Corinto no norte da África" },
      { id: "C", text: "Cidade fundada por egípcios no período do Novo Império" },
      { id: "D", text: "Colônia persa estabelecida no Mediterrâneo Ocidental para expandir o império" },
    ],
    correctAnswer: "A",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "A religião romana original era muito próxima à grega. Como a influência grega se manifestou na religião romana?",
    tip: "Quando Roma conquistou a Grécia e o mundo helenístico, adotou muito da cultura grega. No campo religioso, esse processo foi especialmente claro.",
    funFact: "\"Você sabia?\" — Os romanos eram tão tolerantes com religiões estrangeiras que incorporavam os deuses dos povos conquistados ao seu panteão. O único limite era a exigência de também prestar culto ao Imperador como símbolo de lealdade política.",
    points: 1,
    options: [
      { id: "A", text: "Os romanos abandonaram completamente sua religião e adotaram exclusivamente os deuses gregos" },
      { id: "B", text: "Roma proibiu o culto a deuses estrangeiros para proteger a religião romana tradicional" },
      { id: "C", text: "Os romanos mantiveram seus deuses originais sem qualquer influência grega" },
      { id: "D", text: "Os romanos identificaram seus deuses com os gregos, renomeando-os: Zeus/Júpiter, Ares/Marte, Afrodite/Vênus, Hermes/Mercúrio, preservando a mitologia mas adaptando os nomes" },
    ],
    correctAnswer: "D",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "Em 146 a.C., o mesmo ano em que destruíram Cartago, os romanos também destruíram a cidade grega de Corinto. O que isso significa historicamente?",
    tip: "No mesmo ano, Roma eliminou as duas grandes potências que ainda podiam desafiá-la — uma no Ocidente e outra no Oriente. Isso marcou o início de algo novo.",
    funFact: "\"Você sabia?\" — A Grécia conquistada fascinou os conquistadores romanos. O poeta Horácio escreveu: 'A Grécia, conquistada, conquistou o feroz vencedor' — referindo-se ao enorme impacto cultural grego sobre a civilização romana.",
    points: 1,
    options: [
      { id: "A", text: "Roma perdeu muito prestígio ao destruir uma cidade culturalmente importante" },
      { id: "B", text: "Roma se tornou a única e incontestável potência do Mediterrâneo, controlando tanto o Ocidente (após as Guerras Púnicas) quanto o Oriente grego, iniciando a era imperial" },
      { id: "C", text: "As destruições de Cartago e Corinto foram condenadas pelo Senado romano" },
      { id: "D", text: "Marcou o início do declínio de Roma, que se enfraqueceu com as guerras constantes" },
    ],
    correctAnswer: "B",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "A cidadania romana conferia direitos específicos a quem a possuía. Quais eram os principais direitos do cidadão romano?",
    tip: "Ser cidadão romano no mundo antigo era como ter um passaporte de superpotência — conferia proteção legal e privilégios onde quer que você estivesse.",
    funFact: "\"Você sabia?\" — O apóstolo Paulo usou sua cidadania romana para apelar ao imperador quando foi preso em Jerusalém. A frase 'Civis Romanus sum' (Sou cidadão romano) era proteção legal em todo o Império.",
    points: 1,
    options: [
      { id: "A", text: "Direito de votar nas assembleias, de recorrer à justiça romana (provocatio), de se candidatar a cargos públicos e de contrair matrimônio legal (conubium)" },
      { id: "B", text: "Apenas o direito de não ser executado sem julgamento" },
      { id: "C", text: "Isenção de impostos e recebimento de terras conquistadas" },
      { id: "D", text: "O direito exclusivo de ser proprietário de escravos" },
    ],
    correctAnswer: "A",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "O Fórum Romano era o centro da vida pública em Roma. O que era o Fórum?",
    tip: "Assim como a ágora grega, o Fórum tinha múltiplas funções — era o coração político, judicial, comercial e religioso da cidade.",
    funFact: "\"Você sabia?\" — O Fórum Romano começou como mercado e pântano. Ao longo dos séculos, foi pavimentado, drenado e tornou-se o centro monumental de uma cidade de 1 milhão de habitantes, rodeado pelos mais importantes templos e edifícios públicos.",
    points: 1,
    options: [
      { id: "A", text: "Era o bairro aristocrático onde moravam as famílias patrícias mais antigas" },
      { id: "B", text: "Era o campo de batalha onde os gladiadores lutavam para entreter o povo" },
      { id: "C", text: "A praça central de Roma onde ficavam os principais templos, tribunais, basilicas e edifícios públicos — coração da vida política, jurídica, comercial e religiosa romana" },
      { id: "D", text: "Era o depósito onde Roma guardava os tesouros saqueados das guerras" },
    ],
    correctAnswer: "C",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "O historiador grego Políbio admirava profundamente a Constituição Romana republicana. Qual era, segundo ele, seu grande diferencial?",
    tip: "Políbio estava fascinado com um aspecto da Constituição Romana que ele julgava explicar a grandeza de Roma — algo que nenhuma cidade-estado grega havia conseguido.",
    funFact: "\"Você sabia?\" — Políbio foi trazido a Roma como refém após a conquista da Macedônia (167 a.C.) e tornou-se amigo próximo de Cipião Emiliano. Sua obra 'Histórias' é uma das principais fontes para o período das Guerras Púnicas.",
    points: 1,
    options: [
      { id: "A", text: "Que Roma tinha o exército mais poderoso do mundo, sem necessidade de organização política" },
      { id: "B", text: "Que o sistema romano era uma democracia pura, onde todos os cidadãos tinham poder igual" },
      { id: "C", text: "Que Roma era governada exclusivamente pelos mais sábios e virtuosos, sem corrupção possível" },
      { id: "D", text: "A Constituição Mista: combinava elementos monárquicos (cônsules), aristocráticos (Senado) e democráticos (assembleias populares), criando equilíbrio que evitava tirania ou demagogia" },
    ],
    correctAnswer: "D",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "A patria potestas era um conceito jurídico fundamental na família romana. O que ela estabelecia?",
    tip: "A família romana era organizada de forma radicalmente diferente da família moderna. O 'pater familias' tinha um poder que seria considerado extremo por padrões atuais.",
    funFact: "\"Você sabia?\" — O pater familias tinha poder de reconhecer ou rejeitar um recém-nascido. Um bebê só era oficialmente membro da família quando o pai o reconhecia publicamente levantando-o nos braços. Caso contrário, era exposto (abandonado).",
    points: 1,
    options: [
      { id: "A", text: "O poder do Estado sobre os cidadãos, similar ao que chamamos hoje de soberania nacional" },
      { id: "B", text: "O poder absoluto do pater familias (pai de família) sobre esposa, filhos (de qualquer idade) e escravos, incluindo teoricamente poder de vida e morte" },
      { id: "C", text: "O direito da pátria de chamar os cidadãos para o serviço militar" },
      { id: "D", text: "O direito do filho mais velho de herdar toda a propriedade da família" },
    ],
    correctAnswer: "B",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "O latim, língua dos romanos, deixou um legado linguístico imenso para o mundo moderno. Qual é a principal herança do latim?",
    tip: "O latim não morreu quando Roma caiu — ele se transformou. Hoje, centenas de milhões de pessoas falam línguas que derivam diretamente do latim popular falado nas províncias romanas.",
    funFact: "\"Você sabia?\" — Mais de 60% do vocabulário inglês vem do latim, seja diretamente (através do latim eclesiástico) ou via francês (língua latina levada pelos normandos à Inglaterra em 1066). O latim nunca morreu — apenas se transformou.",
    points: 1,
    options: [
      { id: "A", text: "É a língua-mãe das línguas românicas (português, espanhol, francês, italiano, romeno) e base do vocabulário científico, jurídico e religioso do mundo ocidental" },
      { id: "B", text: "O latim influenciou apenas o italiano moderno, sem impacto em outras línguas" },
      { id: "C", text: "O latim sobreviveu apenas na liturgia da Igreja Ortodoxa Grega" },
      { id: "D", text: "O latim foi completamente substituído pelo grego como língua do conhecimento no mundo medieval" },
    ],
    correctAnswer: "A",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Os escravos eram fundamentais para a economia da República Romana. Qual era o papel da escravidão no sistema econômico romano?",
    tip: "A escravidão romana era diferente da africana moderna em alguns aspectos (não era racial, escravos educados podiam ter funções altas) mas compartilhava a essência da exploração total do trabalho humano.",
    funFact: "\"Você sabia?\" — Alguns escravos romanos cultos trabalhavam como tutores, médicos e contadores e podiam acumular um pecúlio (pequena poupança) para comprar sua liberdade. Libertos (ex-escravos) podiam alcançar posições importantes.",
    points: 1,
    options: [
      { id: "A", text: "Eram usados apenas em entretenimento (gladiadores), sem papel econômico relevante" },
      { id: "B", text: "A escravidão era rara em Roma — a maioria do trabalho era feita por cidadãos livres" },
      { id: "C", text: "Escravos trabalhavam em minas, latifúndios (villae rusticae), construção civil, artesanato e como domésticos, sendo essenciais para a economia, chegando a 30-40% da população" },
      { id: "D", text: "Escravos eram usados apenas para serviços religiosos nos templos romanos" },
    ],
    correctAnswer: "C",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Durante a Primeira Guerra Púnica, Roma enfrentou a desvantagem de não ter tradição naval. Como os romanos compensaram essa desvantagem?",
    tip: "Os romanos eram gênios da engenharia e da guerra terrestre. Quando precisaram lutar no mar, criaram uma inovação tecnológica que transferia suas vantagens terrestres para o ambiente naval.",
    funFact: "\"Você sabia?\" — O corvus foi tão eficaz que Roma ganhou a batalha naval de Mylae (260 a.C.) com apenas alguns meses de experiência naval. A inovação tecnológica compensou séculos de experiência cartaginesa no mar.",
    points: 1,
    options: [
      { id: "A", text: "Contrataram marinheiros gregos experientes para comandar sua frota" },
      { id: "B", text: "Evitaram batalhas navais e lutaram apenas em terra firme" },
      { id: "C", text: "Compraram a frota cartaginesa inteira através de diplomacia e suborno" },
      { id: "D", text: "Inventaram o corvus — uma ponte de abordagem lançada sobre navios inimigos, transformando batalhas navais em combates terrestres onde os legionários tinham vantagem" },
    ],
    correctAnswer: "D",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "A engenharia romana foi uma das mais avançadas do mundo antigo. Qual foi a principal inovação técnica que permitiu a Roma construir monumentos como o Panteão e o Coliseu?",
    tip: "Os romanos desenvolveram um material de construção que revolucionou a arquitetura — ele era mais resistente que pedras individuais e podia ser moldado em qualquer forma.",
    funFact: "\"Você sabia?\" — O concreto romano (opus caementicium) era feito com cinzas vulcânicas do Monte Vesúvio misturadas com cal e água do mar. Era tão resistente que estruturas de dois mil anos atrás ainda estão de pé, enquanto o concreto moderno dura décadas.",
    points: 1,
    options: [
      { id: "A", text: "Uso de madeira como material principal em todas as construções monumentais" },
      { id: "B", text: "Desenvolvimento do arco romano, da abóbada, da cúpula e do concreto (opus caementicium), que permitiram construções monumentais de grande vão e durabilidade excepcional" },
      { id: "C", text: "Importação de técnicas de construção da Índia para obras monumentais" },
      { id: "D", text: "Uso exclusivo de mármore importado da Grécia para todas as construções públicas" },
    ],
    correctAnswer: "B",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "As províncias romanas eram os territórios conquistados fora da Itália. Como eram administradas e qual era sua relação com Roma?",
    tip: "As províncias eram a base do poder e da riqueza de Roma. Elas enviavam recursos para a capital, mas em troca recebiam proteção, lei e infraestrutura.",
    funFact: "\"Você sabia?\" — Gaius Verres, governador da Sicília (73-71 a.C.), pilhou tanto a província que Cícero o processou num dos mais famosos julgamentos da história romana. As 'Verinas' de Cícero são obras-primas da oratória latina.",
    points: 1,
    options: [
      { id: "A", text: "Territórios conquistados administrados por um governador romano (procônsul ou propretor), que pagavam impostos e forneciam recursos e tropas a Roma em troca de proteção e ordem" },
      { id: "B", text: "Regiões autônomas que governavam a si mesmas sem qualquer interferência de Roma" },
      { id: "C", text: "Colônias militares habitadas exclusivamente por soldados licenciados do exército" },
      { id: "D", text: "Territórios vendidos por Roma a outros reinos em troca de aliança militar" },
    ],
    correctAnswer: "A",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "As Guerras Púnicas tiveram profundas consequências sociais em Roma, especialmente para os pequenos camponeses. Qual foi o impacto mais sério?",
    tip: "As longas campanhas militares nas Guerras Púnicas tiraram os camponeses de suas terras por anos. Quando voltavam, encontravam uma situação econômica muito diferente.",
    funFact: "\"Você sabia?\" — Os irmãos Graco, tribunos dos séculos II e I a.C., tentaram reformar esse problema redistribuindo terras. Tiberio Graco foi assassinado em 133 a.C. em pleno Fórum por senadores conservadores — a primeira violência política de Roma.",
    points: 1,
    options: [
      { id: "A", text: "Os camponeses enriqueceram com o butim das guerras e compraram mais terras" },
      { id: "B", text: "As guerras não afetaram o campo — apenas a cidade sofreu com a falta de mão de obra" },
      { id: "C", text: "O trabalho escravo abundante (prisioneiros de guerra) e a concentração de terras em latifúndios arruinaram os pequenos proprietários rurais, criando uma massa de despossuídos que migrou para Roma" },
      { id: "D", text: "Os camponeses passaram a cultivar terras estrangeiras nas novas províncias romanas" },
    ],
    correctAnswer: "C",
  },
];
