export const questoesPortugues8AnoB3Av1 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "O que é \"discurso direto\"?",
    tip: "Pense em como, nos livros e HQs, você vê as falas dos personagens \"entre aspas\" ou depois de um travessão, exatamente como eles disseram.",
    funFact: "O discurso direto torna os textos mais vivos, pois o leitor \"ouve\" diretamente a voz do personagem, como se estivesse presente na cena!",
    points: 1,
    options: [
      { id: "A", text: "Quando o narrador apenas resume o que um personagem pensou, sem reproduzir suas palavras" },
      { id: "B", text: "Quando a fala de um personagem é reproduzida exatamente como foi dita, geralmente após um travessão ou aspas" },
      { id: "C", text: "Um tipo de pontuação usada apenas em poemas" },
      { id: "D", text: "Um gênero textual usado só em cartas" },
    ],
    correctAnswer: "B",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "O que é \"discurso indireto\"?",
    tip: "Pense em como, ao contar para um amigo o que outra pessoa disse, você pode recontar a ideia sem repetir exatamente as palavras usadas.",
    funFact: "No discurso indireto, a frase original é transformada e incorporada à fala do narrador, como em: \"Ela disse que viria mais tarde\"!",
    points: 1,
    options: [
      { id: "A", text: "Quando o personagem fala diretamente com o leitor" },
      { id: "B", text: "Um tipo de figura de linguagem" },
      { id: "C", text: "Uma forma de pontuação usada só em bilhetes" },
      { id: "D", text: "Quando o narrador conta o que foi dito por um personagem, sem reproduzir as palavras exatas, geralmente usando a conjunção \"que\"" },
    ],
    correctAnswer: "D",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "Qual sinal de pontuação é mais comumente usado para indicar a fala de um personagem no discurso direto, em textos literários?",
    tip: "Pense no sinal de pontuação (uma linha horizontal) que aparece no início da fala de um personagem em muitos livros e histórias.",
    funFact: "Além do travessão, as aspas também podem ser usadas para marcar o discurso direto, especialmente em textos jornalísticos, quando se cita a fala de alguém!",
    points: 1,
    options: [
      { id: "A", text: "Ponto de interrogação" },
      { id: "B", text: "Vírgula" },
      { id: "C", text: "Travessão" },
      { id: "D", text: "Ponto final" },
    ],
    correctAnswer: "C",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "Quais são os principais \"verbos de elocução\" usados para introduzir uma fala no discurso direto?",
    tip: "Pense em verbos que indicam a ação de \"falar\" de alguma forma — são eles que costumam introduzir as falas dos personagens.",
    funFact: "Verbos de elocução ajudam o leitor a entender não só o que foi dito, mas também como foi dito — por exemplo, \"gritou\" indica uma fala bem diferente de \"sussurrou\"!",
    points: 1,
    options: [
      { id: "A", text: "Dizer, perguntar, responder, exclamar" },
      { id: "B", text: "Correr, saltar, nadar" },
      { id: "C", text: "Amarelo, vermelho, azul" },
      { id: "D", text: "Rápido, devagar, silenciosamente" },
    ],
    correctAnswer: "A",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "Na frase em discurso direto '\"Eu vou à festa\", disse Maria', ao transformar para o discurso indireto, a frase ficaria:",
    tip: "Pense em como a fala de Maria, antes entre aspas, se transforma em uma frase contada pelo narrador, com o verbo mudando de pessoa e tempo.",
    funFact: "Observe como o pronome \"eu\" se transforma em \"Maria\" (terceira pessoa) e o verbo \"vou\" se transforma em \"iria\" — essas são mudanças típicas da transposição para o discurso indireto!",
    points: 1,
    options: [
      { id: "A", text: "'\"Eu vou à festa\", perguntou Maria'" },
      { id: "B", text: "'Maria vai à festa, disse ela mesma'" },
      { id: "C", text: "'Vou à festa! - gritou Maria'" },
      { id: "D", text: "'Maria disse que iria à festa'" },
    ],
    correctAnswer: "D",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "Qual destas frases está em discurso direto?",
    tip: "Observe qual das frases reproduz exatamente as palavras ditas pelo personagem, usando aspas ou travessão.",
    funFact: "No discurso direto, é como se o personagem estivesse \"falando\" diretamente para o leitor, sem a intermediação do narrador resumindo a fala!",
    points: 1,
    options: [
      { id: "A", text: "Pedro disse que estava cansado." },
      { id: "B", text: "\"Estou cansado!\", exclamou Pedro." },
      { id: "C", text: "Pedro contou que tinha chegado tarde." },
      { id: "D", text: "O menino afirmou que iria embora." },
    ],
    correctAnswer: "B",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "Qual destas frases está em discurso indireto?",
    tip: "Observe qual frase está sendo contada pelo narrador, sem reproduzir exatamente as palavras do personagem, usando a conjunção \"que\".",
    funFact: "No discurso indireto, a fala original passa por uma transformação gramatical, incluindo mudanças de pessoa verbal e de tempo dos verbos!",
    points: 1,
    options: [
      { id: "A", text: "\"Vou chegar atrasado!\", avisou João." },
      { id: "B", text: "— Estou com fome! — disse a menina." },
      { id: "C", text: "João avisou que chegaria atrasado." },
      { id: "D", text: "\"Estou com fome\", disse a menina, sorrindo." },
    ],
    correctAnswer: "C",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "Por que os jornalistas costumam usar o discurso direto ao citar a fala de uma pessoa entrevistada em uma notícia?",
    tip: "Pense em como, numa notícia, é importante que o leitor saiba exatamente as palavras usadas pela pessoa entrevistada, sem alterações.",
    funFact: "Em notícias, é comum ver frases entre aspas, citando exatamente o que uma autoridade ou especialista disse sobre um assunto — isso é o discurso direto em ação!",
    points: 1,
    options: [
      { id: "A", text: "Para reproduzir exatamente o que a pessoa disse, garantindo precisão e credibilidade à informação" },
      { id: "B", text: "Porque é proibido usar discurso indireto em notícias" },
      { id: "C", text: "Porque o discurso direto é mais curto" },
      { id: "D", text: "Porque jornalistas não sabem usar o discurso indireto" },
    ],
    correctAnswer: "A",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "Na transposição do discurso direto para o indireto, o que normalmente acontece com os pronomes pessoais?",
    tip: "Pense em como, ao contar o que alguém disse sobre si mesmo (\"eu vou\"), você muda para falar sobre essa pessoa (\"ela disse que iria\").",
    funFact: "Essa mudança de pessoa verbal é uma das características mais importantes da transposição do discurso direto para o indireto — é importante prestar atenção a ela!",
    points: 1,
    options: [
      { id: "A", text: "Eles desaparecem completamente da frase" },
      { id: "B", text: "Eles mudam, geralmente da primeira pessoa (eu) para a terceira pessoa (ele/ela)" },
      { id: "C", text: "Eles sempre permanecem exatamente os mesmos" },
      { id: "D", text: "Eles se transformam em adjetivos" },
    ],
    correctAnswer: "B",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "Em uma história em quadrinhos, as falas dos personagens dentro dos balões são um exemplo de:",
    tip: "Pense em como as palavras dentro dos balões de fala representam exatamente o que os personagens estão dizendo, sem intermediação do narrador.",
    funFact: "As histórias em quadrinhos são um ótimo exemplo visual de discurso direto, já que o leitor \"vê\" e \"ouve\" diretamente a fala dos personagens através dos balões!",
    points: 1,
    options: [
      { id: "A", text: "Discurso indireto" },
      { id: "B", text: "Narração em terceira pessoa apenas" },
      { id: "C", text: "Discurso indireto livre" },
      { id: "D", text: "Discurso direto" },
    ],
    correctAnswer: "D",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Na frase em discurso direto '\"Estou aqui agora\", disse ele', ao transpor para o discurso indireto, o advérbio \"aqui\" normalmente se transforma em:",
    tip: "Pense em como, ao contar para alguém o que foi dito em outro momento e lugar, a referência de lugar também muda, assim como a de tempo.",
    funFact: "Assim como \"aqui\" pode se tornar \"ali\", o advérbio \"agora\" também costuma se transformar em \"naquele momento\" na transposição para o discurso indireto!",
    points: 1,
    options: [
      { id: "A", text: "\"Ali\" ou \"lá\"" },
      { id: "B", text: "\"Aqui\" (permanece igual)" },
      { id: "C", text: "\"Depois\"" },
      { id: "D", text: "\"Nunca\"" },
    ],
    correctAnswer: "A",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Na frase '\"Vou estudar hoje\", disse a aluna', ao transpor para o discurso indireto, a palavra \"hoje\" normalmente se transforma em:",
    tip: "Pense em como, ao recontar algo dito em outro momento, a referência de tempo \"hoje\" muda para indicar que já se passou algum tempo.",
    funFact: "Essas mudanças de advérbios de tempo e lugar são importantes na transposição do discurso direto para o indireto, ajudando a manter a coerência da narrativa!",
    points: 1,
    options: [
      { id: "A", text: "\"Sempre\"" },
      { id: "B", text: "\"Hoje\" (permanece igual)" },
      { id: "C", text: "\"Naquele dia\"" },
      { id: "D", text: "\"Nunca\"" },
    ],
    correctAnswer: "C",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "O que é \"discurso indireto livre\", um recurso usado por alguns escritores?",
    tip: "Pense em um estilo de escrita em que fica difícil saber exatamente quando é o narrador falando e quando são os pensamentos do personagem, misturados no texto.",
    funFact: "Grandes escritores, como Machado de Assis, usavam o discurso indireto livre para criar um efeito mais próximo dos pensamentos íntimos dos personagens, sem interrupções claras!",
    points: 1,
    options: [
      { id: "A", text: "Quando o personagem fala diretamente para o leitor através de aspas" },
      { id: "B", text: "Uma mistura entre a voz do narrador e os pensamentos do personagem, sem marcas claras como travessão ou \"que\"" },
      { id: "C", text: "Um tipo de discurso usado apenas em bulas de remédio" },
      { id: "D", text: "Uma forma de pontuação usada no final das frases" },
    ],
    correctAnswer: "B",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "Em uma entrevista publicada em uma revista, por que é importante usar o discurso direto ao citar a fala do entrevistado?",
    tip: "Pense em como é importante, em uma entrevista, que o leitor saiba exatamente o que a pessoa disse, sem interpretações do jornalista.",
    funFact: "Usar aspas corretamente ao citar falas é uma prática fundamental no jornalismo, garantindo credibilidade e respeito às palavras exatas do entrevistado!",
    points: 1,
    options: [
      { id: "A", text: "Porque é proibido usar discurso indireto em entrevistas" },
      { id: "B", text: "Porque o discurso direto é sempre mais engraçado" },
      { id: "C", text: "Porque ninguém entende o discurso indireto" },
      { id: "D", text: "Para garantir que as palavras exatas da pessoa sejam reproduzidas com fidelidade" },
    ],
    correctAnswer: "D",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Qual é uma diferença importante de efeito entre o discurso direto e o discurso indireto em uma narrativa?",
    tip: "Pense em como ouvir a voz exata de um personagem é diferente de apenas saber, pelo narrador, o que ele disse de forma resumida.",
    funFact: "Escritores escolhem usar discurso direto ou indireto dependendo do efeito que querem criar na narrativa — mais próximo e vivo, ou mais distante e resumido!",
    points: 1,
    options: [
      { id: "A", text: "Não existe diferença nenhuma entre eles" },
      { id: "B", text: "O discurso indireto sempre torna o texto mais longo que o direto" },
      { id: "C", text: "O discurso direto dá mais vivacidade e proximidade com a fala do personagem; o indireto cria um efeito mais narrativo e distante" },
      { id: "D", text: "O discurso direto só pode ser usado em poemas" },
    ],
    correctAnswer: "C",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "Qual destes é um erro comum ao transpor uma frase do discurso direto para o indireto?",
    tip: "Pense em como, ao transformar a fala, é importante lembrar de ajustar tanto os pronomes quanto os tempos verbais, para a frase continuar fazendo sentido.",
    funFact: "Prestar atenção a essas mudanças é essencial para que a transposição do discurso direto para o indireto fique gramaticalmente correta e com sentido claro!",
    points: 1,
    options: [
      { id: "A", text: "Esquecer de mudar o pronome pessoal e o tempo verbal de acordo com a nova estrutura da frase" },
      { id: "B", text: "Usar a conjunção \"que\" corretamente" },
      { id: "C", text: "Manter a coerência da frase" },
      { id: "D", text: "Usar verbos de elocução adequados" },
    ],
    correctAnswer: "A",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "Em contos e romances, por que os autores costumam alternar entre discurso direto e indireto?",
    tip: "Pense em como alternar entre ouvir a voz direta de um personagem e ter o narrador resumindo a fala pode tornar a leitura mais interessante e dinâmica.",
    funFact: "Grandes escritores usam essa alternância de forma muito criativa, criando ritmos diferentes dentro da mesma história!",
    points: 1,
    options: [
      { id: "A", text: "Porque é obrigatório por lei usar os dois tipos de discurso" },
      { id: "B", text: "Para variar o ritmo da narrativa e dar diferentes efeitos às falas e pensamentos dos personagens" },
      { id: "C", text: "Porque um dos dois tipos de discurso está sempre errado" },
      { id: "D", text: "Porque não existe diferença entre eles" },
    ],
    correctAnswer: "B",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "Na pontuação do discurso direto, o que geralmente vem logo após o travessão que introduz a fala de um personagem?",
    tip: "Pense em como o travessão \"abre espaço\" para a fala exata do personagem ser reproduzida imediatamente depois dele.",
    funFact: "O uso correto do travessão ajuda o leitor a identificar rapidamente quando um personagem está falando dentro do texto!",
    points: 1,
    options: [
      { id: "A", text: "Um ponto final apenas" },
      { id: "B", text: "Nenhuma pontuação" },
      { id: "C", text: "Sempre uma vírgula" },
      { id: "D", text: "A fala do personagem, exatamente como foi dita" },
    ],
    correctAnswer: "D",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "Por que entender a diferença entre discurso direto e indireto é importante na interpretação de textos literários?",
    tip: "Pense em como saber diferenciar a voz do narrador da voz dos personagens ajuda a entender melhor o que está acontecendo na história.",
    funFact: "Muitas questões de interpretação de texto exigem que o leitor identifique corretamente quando uma fala é do narrador (discurso indireto) ou do próprio personagem (discurso direto)!",
    points: 1,
    options: [
      { id: "A", text: "Porque ajuda a identificar quem está \"falando\" em cada momento do texto — o narrador ou o personagem" },
      { id: "B", text: "Porque não tem nenhuma relação com a interpretação de textos" },
      { id: "C", text: "Porque só serve para decorar regras de pontuação" },
      { id: "D", text: "Porque isso nunca aparece em provas de interpretação de texto" },
    ],
    correctAnswer: "A",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "Qual destas frases está corretamente construída no discurso indireto?",
    tip: "Observe qual frase está sendo contada pelo narrador, com o verbo mudando de pessoa e sem o uso de aspas ou travessão.",
    funFact: "Observe como \"vou sair agora\" se transformou em \"sairia naquele momento\" — essas mudanças de tempo verbal e advérbio são típicas do discurso indireto!",
    points: 1,
    options: [
      { id: "A", text: "\"Vou sair agora!\", disse ela." },
      { id: "B", text: "— Estou com sono — disse o menino." },
      { id: "C", text: "Ela disse que sairia naquele momento." },
      { id: "D", text: "\"Estou com sono\", murmurou o menino." },
    ],
    correctAnswer: "C",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Bernardo escreveu em sua redação: '\"Vou ganhar o campeonato!\", gritou o jogador.' Essa frase está em qual tipo de discurso?",
    tip: "Lembra do tipo de discurso em que a fala do personagem é reproduzida exatamente como foi dita, usando aspas ou travessão?",
    funFact: "Bernardo usou corretamente o discurso direto, deixando a fala do jogador bem viva e emocionante para o leitor!",
    points: 1,
    options: [
      { id: "A", text: "Discurso indireto" },
      { id: "B", text: "Narração sem falas" },
      { id: "C", text: "Discurso indireto livre" },
      { id: "D", text: "Discurso direto" },
    ],
    correctAnswer: "D",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Bernardo transformou a frase '\"Estou com fome\", disse o menino' para o discurso indireto. Qual destas opções está correta?",
    tip: "Lembra de como o pronome e o tempo verbal mudam na transposição para o discurso indireto, e de que não se usam mais aspas ou travessão?",
    funFact: "Bernardo aplicou corretamente a regra — o \"estou\" (primeira pessoa) se transformou em \"estava\" (terceira pessoa), e a conjunção \"que\" foi usada para introduzir a fala!",
    points: 1,
    options: [
      { id: "A", text: "\"Estou com fome\", perguntou o menino." },
      { id: "B", text: "O menino disse que estava com fome." },
      { id: "C", text: "Estou com fome! — gritou o menino." },
      { id: "D", text: "O menino disse: \"estou com fome\"." },
    ],
    correctAnswer: "B",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Bernardo leu uma notícia em que o prefeito da cidade foi citado dizendo, entre aspas, exatamente suas palavras sobre um novo projeto. Isso é um exemplo de uso de:",
    tip: "Lembra de como, em notícias, é comum reproduzir exatamente as palavras ditas por uma pessoa importante, para garantir precisão?",
    funFact: "Jornalistas costumam usar o discurso direto justamente para garantir que as palavras exatas de quem foi entrevistado sejam respeitadas e reproduzidas com fidelidade!",
    points: 1,
    options: [
      { id: "A", text: "Discurso direto" },
      { id: "B", text: "Discurso indireto" },
      { id: "C", text: "Discurso indireto livre" },
      { id: "D", text: "Nenhum tipo de discurso" },
    ],
    correctAnswer: "A",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Bernardo notou que, em uma frase de seu livro, o narrador contava o que um personagem havia dito, sem reproduzir exatamente suas palavras, usando a conjunção \"que\". Esse é um exemplo de:",
    tip: "Lembra do tipo de discurso em que o narrador resume a fala do personagem, geralmente usando a palavra \"que\"?",
    funFact: "Bernardo identificou corretamente — no discurso indireto, a fala original é incorporada à narração, sem o uso de aspas ou travessão!",
    points: 1,
    options: [
      { id: "A", text: "Discurso direto" },
      { id: "B", text: "Discurso indireto livre" },
      { id: "C", text: "Discurso indireto" },
      { id: "D", text: "Nenhum tipo de discurso" },
    ],
    correctAnswer: "C",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Bernardo quis transformar a frase em discurso direto '\"Vou viajar amanhã\", disse a tia' para o discurso indireto. Ele sabe que a palavra \"amanhã\" normalmente se transforma em:",
    tip: "Lembra de como as referências de tempo mudam quando a fala é recontada em um momento diferente, na transposição para o discurso indireto?",
    funFact: "Essa é uma mudança comum na transposição — \"amanhã\" se torna \"no dia seguinte\", já que o momento da fala original foi diferente do momento em que está sendo recontada!",
    points: 1,
    options: [
      { id: "A", text: "\"Amanhã\" (permanece igual)" },
      { id: "B", text: "\"No dia seguinte\"" },
      { id: "C", text: "\"Ontem\"" },
      { id: "D", text: "\"Nunca\"" },
    ],
    correctAnswer: "B",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Bernardo leu um conto em que, por várias páginas, era difícil saber se os pensamentos descritos eram do narrador ou do próprio personagem, misturados no texto. Esse recurso literário é chamado de:",
    tip: "Lembra do recurso que mistura a voz do narrador com os pensamentos do personagem, sem marcas claras de transição?",
    funFact: "Esse recurso é muito usado por grandes escritores para dar um efeito mais íntimo e psicológico aos pensamentos dos personagens!",
    points: 1,
    options: [
      { id: "A", text: "Discurso direto" },
      { id: "B", text: "Discurso indireto comum" },
      { id: "C", text: "Pontuação incorreta" },
      { id: "D", text: "Discurso indireto livre" },
    ],
    correctAnswer: "D",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Bernardo percebeu que, na sua história em quadrinhos favorita, as falas dentro dos balões representam exatamente o que os personagens estão dizendo. Isso é um exemplo de:",
    tip: "Lembra de como as falas dentro dos balões de HQ reproduzem exatamente as palavras dos personagens, sem intermediação do narrador?",
    funFact: "As histórias em quadrinhos são um exemplo visual perfeito de discurso direto, já que o leitor \"ouve\" diretamente o que os personagens estão dizendo através dos balões!",
    points: 1,
    options: [
      { id: "A", text: "Discurso direto" },
      { id: "B", text: "Discurso indireto" },
      { id: "C", text: "Discurso indireto livre" },
      { id: "D", text: "Narração sem falas" },
    ],
    correctAnswer: "A",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Depois de estudar discurso direto e indireto, Bernardo concluiu que a principal diferença entre eles é:",
    tip: "Pense em tudo que você aprendeu sobre a diferença entre reproduzir exatamente uma fala e contar o que foi dito de forma resumida pelo narrador.",
    funFact: "Parabéns, Bernardo! Você entendeu a diferença fundamental entre esses dois tipos de discurso, muito importantes para a leitura e escrita de textos narrativos!",
    points: 1,
    options: [
      { id: "A", text: "O discurso direto nunca pode ser usado em livros" },
      { id: "B", text: "Não existe diferença alguma entre os dois tipos" },
      { id: "C", text: "O discurso direto reproduz exatamente as palavras ditas, enquanto o discurso indireto é contado pelo narrador, sem reprodução exata" },
      { id: "D", text: "O discurso indireto é sempre mais engraçado que o direto" },
    ],
    correctAnswer: "C",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Bernardo quer escrever um diálogo em sua redação, reproduzindo exatamente o que os personagens disseram. Para isso, ele deve usar:",
    tip: "Lembra de qual tipo de discurso é usado quando se quer reproduzir exatamente as palavras dos personagens, com o uso de travessão ou aspas?",
    funFact: "Usar o discurso direto corretamente pode tornar a redação de Bernardo muito mais viva e interessante, dando voz própria aos personagens da história!",
    points: 1,
    options: [
      { id: "A", text: "Discurso indireto, com a conjunção \"que\"" },
      { id: "B", text: "Discurso indireto livre, misturando narrador e personagem" },
      { id: "C", text: "Nenhuma pontuação especial" },
      { id: "D", text: "Discurso direto, com travessão ou aspas" },
    ],
    correctAnswer: "D",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Depois de todo esse estudo, Bernardo resumiu para a família: \"quando reproduzimos exatamente a fala de alguém, usando aspas ou travessão, chamamos de discurso direto; quando o narrador conta o que foi dito, sem reproduzir as palavras exatas, chamamos de discurso...\". Qual palavra completa essa frase?",
    tip: "Pense na palavra oposta a \"direto\", que você aprendeu desde a segunda questão desse simulado.",
    funFact: "Parabéns, Bernardo! Você aprendeu a diferenciar claramente o discurso direto do discurso indireto, uma habilidade muito importante para interpretar e escrever boas narrativas!",
    points: 1,
    options: [
      { id: "A", text: "Direto, novamente" },
      { id: "B", text: "Indireto" },
      { id: "C", text: "Nominal" },
      { id: "D", text: "Textual" },
    ],
    correctAnswer: "B",
  },
];
