export const questoesSociologia1EmB3Av1 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'A distinção entre cultura popular e cultura erudita (ou de elite) é um tema central na Sociologia da Cultura. Qual é a principal característica que os diferencia?',
    tip: 'A diferença não é de qualidade — é de acesso, origem e legitimidade social. Quem produz, quem consome e quem valida cada tipo de cultura?',
    funFact: 'Você sabia? Bourdieu mostrou que a distinção entre cultura "alta" e "baixa" é uma forma de distinção de classe — a elite usa o gosto pela ópera, pelo balé e pela arte abstrata como sinal de superioridade social, não por pura estética!',
    points: 1,
    options: [
      { id: 'A', text: 'A cultura erudita é objetivamente melhor; a cultura popular é simplificada e de baixa qualidade' },
      { id: 'B', text: 'A cultura popular vem das camadas populares e é transmitida oralmente; a erudita é produzida e legitimada por instituições das elites (escolas, museus, academia)' },
      { id: 'C', text: 'A cultura erudita é sempre europeia; a cultura popular é sempre africana ou indígena' },
      { id: 'D', text: 'A cultura popular é moderna e jovem; a erudita é sempre antiga e ultrapassada' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'A Escola de Frankfurt foi um grupo de intelectuais que desenvolveu a Teoria Crítica. Em qual contexto histórico ela surgiu?',
    tip: 'A Escola de Frankfurt nasceu numa Alemanha em crise — e seus pensadores foram forçados a fugir para o exílio quando a situação se tornou perigosa.',
    funFact: 'Você sabia? Muitos membros da Escola de Frankfurt fugiram para os Estados Unidos quando Hitler chegou ao poder em 1933. Foi lá, em Hollywood e Nova York, que Adorno e Horkheimer observaram com horror o que chamaram de "indústria cultural" americana!',
    points: 1,
    options: [
      { id: 'A', text: 'Na República de Weimar alemã, nos anos 1920-1930, em resposta ao nazismo e à ascensão do capitalismo de massas' },
      { id: 'B', text: 'Na Revolução Russa de 1917, como forma de pensar a transição para o socialismo' },
      { id: 'C', text: 'Na França do pós-Segunda Guerra, como resposta ao existencialismo de Sartre' },
      { id: 'D', text: 'Nos Estados Unidos dos anos 1950, em resposta à cultura do consumo durante a Guerra Fria' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'Adorno e Horkheimer, em "Dialética do Esclarecimento" (1944), criaram o conceito de "indústria cultural". O que esse conceito critica?',
    tip: 'Para Adorno e Horkheimer, a cultura produzida em série para o mercado de massas não é simplesmente entretenimento — ela tem uma função ideológica específica.',
    funFact: 'Você sabia? Adorno odiava o jazz! Ele via o jazz como exemplo de pseudocultura: parecia espontâneo e rebelde, mas era produzido em série para o mercado. Essa posição gerou muita crítica — muitos achavam que Adorno era um snob cultural europeu sem sensibilidade!',
    points: 1,
    options: [
      { id: 'A', text: 'A utilização de máquinas e tecnologia industrial para reduzir os custos de produção artística' },
      { id: 'B', text: 'A produção de bens culturais em série pelo mercado capitalista, padronizando e mercantilizando a cultura e transformando os consumidores em passivos receptores' },
      { id: 'C', text: 'A criação de museus e galerias para popularizar a arte erudita para as massas trabalhadoras' },
      { id: 'D', text: 'A utilização da propaganda pelo Estado para controlar o comportamento dos cidadãos' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'Para Adorno e Horkheimer, a principal função ideológica da indústria cultural é:',
    tip: 'A indústria cultural não apenas entretém — ela produz um efeito político e social específico que beneficia o sistema dominante.',
    funFact: 'Você sabia? Adorno argumentava que a cultura de massas cria uma "pseudoindividualidade" — produtos idênticos são vendidos com pequenas diferenças para criar a ilusão de escolha e liberdade individual, quando na verdade todos consomem a mesma coisa!',
    points: 1,
    options: [
      { id: 'A', text: 'Promover a revolução social ao elevar o nível cultural das massas trabalhadoras' },
      { id: 'B', text: 'Desenvolver a criatividade e o pensamento crítico do público consumidor' },
      { id: 'C', text: 'Preservar a cultura erudita tornando-a acessível para todos os grupos sociais' },
      { id: 'D', text: 'Integrar as massas ao sistema capitalista, produzindo conformismo e impedindo o pensamento crítico e a emancipação' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'A cultura de massa surgiu com a industrialização e o desenvolvimento dos meios de comunicação. Qual é sua principal característica?',
    tip: 'A cultura de massa é produzida para ser consumida por um público enorme e diverso — isso exige determinadas escolhas de produção.',
    funFact: 'Você sabia? O cinema foi o primeiro produto da cultura de massa no século XX — por isso Hollywood se tornou uma das maiores indústrias do mundo. Um único filme podia ser assistido por milhões de pessoas simultaneamente em diferentes países!',
    points: 1,
    options: [
      { id: 'A', text: 'É produzida por grupos populares a partir de suas experiências cotidianas e tradições orais' },
      { id: 'B', text: 'É transmitida exclusivamente por meios orais e requer presença física dos produtores e consumidores' },
      { id: 'C', text: 'É produzida em série por empresas culturais, destinada a um grande público heterogêneo, com tendência à padronização e ao maior denominador comum' },
      { id: 'D', text: 'É reservada às elites intelectuais e requer alto nível de escolaridade para ser compreendida' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'O folclore brasileiro é uma expressão da cultura popular. Como pode ser definido?',
    tip: 'O folclore não é simplesmente algo "antigo" — é um conjunto de saberes e práticas que se mantêm vivos porque são transmitidos e renovados pelas comunidades.',
    funFact: 'Você sabia? A palavra "folclore" foi criada pelo inglês William Thoms em 1846, unindo "folk" (povo) + "lore" (saber). Ele queria um termo para designar as tradições e crenças populares que eram passadas de geração em geração!',
    points: 1,
    options: [
      { id: 'A', text: 'Conjunto de saberes, crenças, festas, lendas, músicas e práticas tradicionais de um povo, transmitidos oralmente e renovados pelas comunidades' },
      { id: 'B', text: 'Apenas as danças e músicas folclóricas apresentadas em espetáculos culturais patrocinados pelo governo' },
      { id: 'C', text: 'As tradições importadas da Europa pelos colonizadores portugueses no período colonial' },
      { id: 'D', text: 'As manifestações culturais indígenas registradas por antropólogos em museus e acervos científicos' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'Pierre Bourdieu desenvolveu o conceito de "capital cultural". O que é capital cultural?',
    tip: 'Para Bourdieu, o capital não é apenas econômico — há também um capital simbólico que funciona como recurso social de distinção e poder.',
    funFact: 'Você sabia? Bourdieu identificou três formas de capital cultural: incorporado (habilidades, disposições do corpo e da mente), objetivado (livros, obras de arte) e institucionalizado (diplomas, certificados). Somente o incorporado não pode ser comprado diretamente!',
    points: 1,
    options: [
      { id: 'A', text: 'O patrimônio artístico e histórico de um país avaliado em termos monetários' },
      { id: 'B', text: 'O conjunto de conhecimentos, habilidades, gostos e disposições culturais adquiridos ao longo da vida, que funcionam como recurso social diferenciador' },
      { id: 'C', text: 'Os investimentos financeiros feitos pelo Estado em museus, teatros e centros culturais' },
      { id: 'D', text: 'A capacidade financeira de uma família de pagar por atividades culturais como teatro e ópera' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'A televisão, por décadas o principal veículo de comunicação de massa no Brasil, exerceu um papel importante na formação da identidade cultural brasileira. Qual foi sua função central nesse processo?',
    tip: 'A televisão chegou a lugares onde não havia cinema, teatro ou livros — e influenciou costumes, linguagem e valores de regiões muito diversas do país.',
    funFact: 'Você sabia? A TV Globo, fundada em 1965, foi essencial na construção de uma identidade nacional brasileira — as novelas das 8 criaram personagens e sotaques que influenciaram o falar, o vestir e os valores de norte a sul do país, homogeneizando aspectos da cultura!',
    points: 1,
    options: [
      { id: 'A', text: 'Preservar intactas as diferenças regionais e as culturas locais do Brasil' },
      { id: 'B', text: 'Apenas transmitir noticiários e conteúdo político para informar os cidadãos' },
      { id: 'C', text: 'Desenvolver o pensamento crítico do público por meio de debates filosóficos diários' },
      { id: 'D', text: 'Transmitir cultura de massa de forma homogeneizante, padronizando gostos, linguagem e valores em todo o território nacional' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'O Modernismo brasileiro, movimento artístico da Semana de Arte Moderna de 1922, propôs uma relação específica com a cultura popular. Qual foi essa proposta?',
    tip: 'Os modernistas queriam criar uma arte genuinamente brasileira — e para isso precisavam se inspirar nas raízes da cultura popular, não imitar os modelos europeus.',
    funFact: 'Você sabia? Mário de Andrade viajou pelo Nordeste e pelo Amazonas para coletar músicas, danças e lendas populares e usá-las como base para criar uma literatura e música brasileira autêntica. Seu romance "Macunaíma" é um exemplo desse projeto!',
    points: 1,
    options: [
      { id: 'A', text: 'Rejeitar completamente a cultura popular por ser considerada atrasada e primitiva' },
      { id: 'B', text: 'Importar modelos culturais europeus para elevar o nível da cultura brasileira' },
      { id: 'C', text: 'Valorizar e incorporar elementos da cultura popular brasileira (indígena, africana, sertaneja) como base para uma arte nacional autêntica' },
      { id: 'D', text: 'Separar definitivamente a arte erudita da cultura popular, criando fronteiras rígidas entre elas' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'A Escola de Frankfurt também é conhecida por desenvolver a "Teoria Crítica". Qual é o objetivo central dessa teoria?',
    tip: 'A Teoria Crítica não quer apenas descrever a sociedade — quer transformá-la. Para isso, precisa revelar as formas de dominação que se disfarçam de naturais.',
    funFact: 'Você sabia? Max Horkheimer, em "Teoria Tradicional e Teoria Crítica" (1937), fez uma distinção crucial: enquanto a ciência tradicional busca apenas descrever a realidade, a teoria crítica quer revelar as contradições da sociedade para possibilitar sua transformação!',
    points: 1,
    options: [
      { id: 'A', text: 'Revelar e criticar as formas de dominação, ideologia e irracionalidade presentes nas sociedades modernas capitalistas, visando à emancipação humana' },
      { id: 'B', text: 'Defender o capitalismo liberal como o melhor sistema social possível para a humanidade' },
      { id: 'C', text: 'Estudar as culturas primitivas com objetividade científica e sem julgamentos de valor' },
      { id: 'D', text: 'Promover a arte erudita como superior à cultura de massa e ao entretenimento popular' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'O conceito de "pseudocultura" (Halbbildung), desenvolvido por Adorno, refere-se a:',
    tip: 'Adorno via um paradoxo: nunca antes tantas pessoas tiveram "acesso" à cultura — mas esse acesso era superficial e não gerava pensamento crítico.',
    funFact: 'Você sabia? Adorno exemplificava a pseudocultura com a "música de fundo" — tocar música clássica em elevadores ou shoppings. Isso cria familiaridade superficial com Bach ou Mozart sem o encontro verdadeiro com a obra, que exige atenção e esforço!',
    points: 1,
    options: [
      { id: 'A', text: 'A cultura completamente fabricada pelo Estado para manipular os cidadãos politicamente' },
      { id: 'B', text: 'A cultura popular autêntica que as elites desprezam por ser "inculta" e sem sofisticação' },
      { id: 'C', text: 'A cultura produzida pelos países subdesenvolvidos, considerada inferior à cultura europeia' },
      { id: 'D', text: 'A aparência de cultura sem sua substância: consumo superficial de elementos culturais sem desenvolvimento do pensamento crítico ou experiência autêntica' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'O "habitus" cultural, conceito central em Pierre Bourdieu, pode ser definido como:',
    tip: 'O habitus é algo que está no corpo e na mente das pessoas — é a cultura incorporada, que se manifesta em gestos, gostos e formas de perceber o mundo.',
    funFact: 'Você sabia? Bourdieu mostrou que o habitus pode ser revelado em coisas aparentemente triviais: como as pessoas sentam, como comem, que palavras escolhem, que músicas gostam. Tudo isso é reflexo de uma posição de classe e de um habitus específico!',
    points: 1,
    options: [
      { id: 'A', text: 'O capital financeiro acumulado pela família ao longo de gerações' },
      { id: 'B', text: 'O sistema de disposições duráveis adquiridas ao longo da socialização, que orienta práticas, gostos e percepções sem necessidade de cálculo consciente' },
      { id: 'C', text: 'Os hábitos ruins de consumo cultural que devem ser combatidos pela educação formal' },
      { id: 'D', text: 'O conjunto de regras jurídicas que regulam as práticas culturais de uma sociedade' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'A Indústria Fonográfica é um exemplo de indústria cultural. Segundo Adorno, como ela opera para padronizar a música?',
    tip: 'Para Adorno, há uma fórmula por trás da música de sucesso — o que parece diferente e novo é apenas variação superficial de um padrão rígido.',
    funFact: 'Você sabia? Adorno identificou dois mecanismos na música de massa: a "padronização" (todas as músicas seguem a mesma estrutura básica) e a "pseudo-individualização" (pequenas diferenças superficiais criam a ilusão de variedade e originalidade!',
    points: 1,
    options: [
      { id: 'A', text: 'Pagando royalties altíssimos para compositores inovadores que quebram padrões estabelecidos' },
      { id: 'B', text: 'Promovendo exclusivamente gêneros musicais eruditos como ópera e música clássica' },
      { id: 'C', text: 'Padronizando estruturas musicais e criando pseudo-individualização: músicas seguem fórmulas fixas com pequenas variações superficiais que simulam originalidade' },
      { id: 'D', text: 'Proibindo que músicos independentes gravem fora dos grandes estúdios corporativos' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'O patrimônio cultural imaterial brasileiro reconhecido pelo IPHAN inclui manifestações como:',
    tip: 'O patrimônio imaterial é diferente dos monumentos históricos — ele é vivo, praticado e precisa de comunidades que o mantenham.',
    funFact: 'Você sabia? O IPHAN (Instituto do Patrimônio Histórico e Artístico Nacional) foi criado no Brasil em 1937, durante o Estado Novo, por iniciativa do escritor Mário de Andrade. Ele propôs preservar não apenas monumentos, mas também manifestações culturais vivas!',
    points: 1,
    options: [
      { id: 'A', text: 'O ofício das paneleiras de Goiabeiras, a capoeira, o frevo, o Círio de Nazaré e o sistema culinário tradicional brasileiro' },
      { id: 'B', text: 'Apenas os prédios históricos do período colonial construídos pelos portugueses' },
      { id: 'C', text: 'Somente as obras de arte guardadas em museus e pinacotecas públicas nas capitais' },
      { id: 'D', text: 'Exclusivamente as tradições culturais europeias trazidas pelos imigrantes no século XIX' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'A internet e as redes sociais transformaram a relação entre produção e consumo de cultura. Qual é a principal mudança identificada pelos sociólogos?',
    tip: 'Na era digital, as fronteiras entre quem produz e quem consome cultura ficaram muito mais porosas — qualquer pessoa com smartphone pode publicar conteúdo.',
    funFact: 'Você sabia? O teórico Axel Bruns cunhou o termo "produsagem" (produser = producer + user) para descrever esse novo tipo de participante cultural que tanto produz quanto usa conteúdo. O YouTube, o TikTok e os podcasts são exemplos dessa lógica!',
    points: 1,
    options: [
      { id: 'A', text: 'A internet eliminou completamente a indústria cultural e a produção em série de conteúdo' },
      { id: 'B', text: 'A internet concentrou ainda mais o poder cultural nas mãos de poucas grandes corporações globais' },
      { id: 'C', text: 'A internet não teve nenhum impacto significativo sobre a produção e consumo cultural' },
      { id: 'D', text: 'A internet democratizou a produção cultural, criando o "produsador" — alguém que tanto consome quanto produz conteúdo — e ampliou o acesso à diversidade cultural' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'O Carnaval brasileiro é um exemplo complexo que mistura cultura popular e interesses comerciais. Como os sociólogos analisam essa tensão?',
    tip: 'O Carnaval começou nas ruas como festa popular e foi gradualmente sendo organizado, comercializado e transmitido pela televisão. Isso muda sua natureza?',
    funFact: 'Você sabia? As escolas de samba surgiram nos morros cariocas como forma de organização cultural das comunidades negras e pobres. Com a televisão e o turismo, o Carnaval virou espetáculo milionário — o que gera debate sobre quem "pertence" ao Carnaval!',
    points: 1,
    options: [
      { id: 'A', text: 'O Carnaval é apenas uma festa religiosa católica sem tensões culturais ou comerciais' },
      { id: 'B', text: 'O Carnaval convive com tensão entre suas raízes na cultura popular negra e a mercantilização pela indústria do entretenimento, do turismo e da mídia' },
      { id: 'C', text: 'O Carnaval é apenas invenção das elites para distrair as classes trabalhadoras de seus problemas' },
      { id: 'D', text: 'O Carnaval manteve sua pureza popular original e não foi afetado pela comercialização' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'Herbert Marcuse, outro pensador da Escola de Frankfurt, desenvolveu o conceito de "dessublimação repressiva". O que isso significa?',
    tip: 'Para Marcuse, a sociedade de consumo permite e até incentiva certos "excessos" culturais — mas de uma forma que acaba reforçando o sistema.',
    funFact: 'Você sabia? O livro "O Homem Unidimensional" de Marcuse (1964) se tornou a bíblia da contracultura dos anos 1960. Estudantes em todo o mundo o leram como análise do conformismo da sociedade de consumo que eles queriam superar!',
    points: 1,
    options: [
      { id: 'A', text: 'O processo pelo qual a arte subversiva é reprimida pelo Estado autoritário' },
      { id: 'B', text: 'A forma como a religião sublima os instintos reprimidos dos indivíduos em rituais aceitáveis' },
      { id: 'C', text: 'A liberação superficial de impulsos e necessidades (sexo, prazer) pela cultura de consumo que, paradoxalmente, reforça a conformidade e impede a verdadeira libertação' },
      { id: 'D', text: 'O processo de repressão psicológica dos trabalhadores por meio de normas rígidas de trabalho' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'A MTV Brasil, ao longa de sua história, representou um exemplo de como a indústria cultural global opera localmente. Como os sociólogos analisam esse tipo de empresa?',
    tip: 'A MTV vende uma estética de "rebeldia" e "autenticidade" — mas é uma corporação multinacional. Como isso se encaixa nas críticas da Escola de Frankfurt?',
    funFact: 'Você sabia? A MTV começou em 1981 nos EUA como canal de videoclipes — e transformou a música em espetáculo visual. Muitos artistas passaram a produzir músicas pensando primeiro no videoclipe do que na experiência sonora, invertendo as prioridades artísticas!',
    points: 1,
    options: [
      { id: 'A', text: 'Como empresa cultural global que adapta produtos culturais padronizados aos mercados locais, mesclando homogeneização com pseudolocalização' },
      { id: 'B', text: 'Como exemplo de como os meios de comunicação de massa podem democratizar a produção e o acesso à cultura musical' },
      { id: 'C', text: 'Como instituição educativa que desenvolveu o gosto musical crítico do público jovem brasileiro' },
      { id: 'D', text: 'Como exemplo de empresa que financiou exclusivamente artistas independentes e culturas alternativas' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'O "campo cultural" é um conceito de Bourdieu que descreve o espaço social onde ocorrem as disputas culturais. O que caracteriza esse campo?',
    tip: 'Para Bourdieu, o mundo da arte e da cultura não é uma esfera pura e autônoma — é um campo de lutas pelo poder simbólico de definir o que é "legítimo".',
    funFact: 'Você sabia? Bourdieu mostrou que os "guardiões da cultura legítima" — críticos de arte, professores, curadores — têm um poder enorme de definir o que é "bom" e o que é "ruim". Esse poder simbólico é tão real quanto o poder econômico ou político!',
    points: 1,
    options: [
      { id: 'A', text: 'Um espaço físico (como museus e teatros) onde a cultura é apresentada para o público' },
      { id: 'B', text: 'O conjunto de obras de arte produzidas em um determinado período histórico' },
      { id: 'C', text: 'As políticas públicas governamentais para financiamento da produção cultural' },
      { id: 'D', text: 'Um espaço de lutas entre diferentes agentes (artistas, críticos, instituições) pelo poder de definir o que tem valor cultural legítimo' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'A "indústria cultural" de Adorno e Horkheimer é diferente da "cultura de massa" popular porque:',
    tip: 'Adorno deliberadamente evitou a expressão "cultura de massa" — e isso diz muito sobre sua perspectiva crítica. Por quê ele preferiu "indústria cultural"?',
    funFact: 'Você sabia? Adorno explicou que preferiu "indústria cultural" a "cultura de massa" para deixar claro que não é a massa que produz essa cultura espontaneamente, mas empresas organizadas que produzem para a massa segundo a lógica do lucro!',
    points: 1,
    options: [
      { id: 'A', text: 'A cultura de massa é primitiva e espontânea; a indústria cultural é sofisticada e planejada' },
      { id: 'B', text: 'O termo "indústria cultural" enfatiza que é a produção capitalista organizada que cria e distribui cultura para a massa, não a massa que a cria espontaneamente' },
      { id: 'C', text: 'A cultura de massa é americana; a indústria cultural é um fenômeno exclusivamente europeu' },
      { id: 'D', text: 'A indústria cultural existe apenas na televisão; a cultura de massa abrange também rádio e cinema' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'O funk carioca é um exemplo de cultura popular que enfrentou preconceito e criminalização. Como a Sociologia analisa esse fenômeno?',
    tip: 'O funk passou por um processo de estigmatização que os sociólogos analisam como parte de relações mais amplas de poder, classe e raça.',
    funFact: 'Você sabia? O funk carioca foi proibido na cidade do Rio de Janeiro em 1995 com a "Lei anti-baile-funk". Os sociólogos analisaram que a criminalização do funk era também a criminalização dos jovens negros e pobres das periferias que o criaram!',
    points: 1,
    options: [
      { id: 'A', text: 'Como expressão cultural legítima das periferias urbanas que sofre estigmatização por ser manifestação da cultura popular das classes pobres e negras' },
      { id: 'B', text: 'Como produto da indústria cultural americana que foi importado e distorcido pela cultura brasileira' },
      { id: 'C', text: 'Como exemplo de cultura de massa criada pela Rede Globo para vender publicidade para o público jovem' },
      { id: 'D', text: 'Como manifestação cultural de elite que foi popularizada de cima para baixo para as camadas populares' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Walter Benjamin, pensador associado à Escola de Frankfurt, escreveu "A Obra de Arte na Era de sua Reprodutibilidade Técnica" (1936). Qual era sua tese central?',
    tip: 'Benjamin tinha uma visão mais otimista que Adorno sobre a reprodução técnica da arte — ele via nela tanto perda quanto potencial emancipatório.',
    funFact: 'Você sabia? Benjamin usou o conceito de "aura" para descrever a unicidade e presença de uma obra de arte original. Uma pintura de Da Vinci tem "aura" — uma cópia não. Mas Benjamin via a reprodução técnica como democratizante: ela tira a arte do altar e a coloca nas ruas!',
    points: 1,
    options: [
      { id: 'A', text: 'A tecnologia destrói completamente toda forma de arte e criatividade humana' },
      { id: 'B', text: 'A reprodução técnica fortalece a "aura" das obras originais, tornando-as mais valiosas' },
      { id: 'C', text: 'A reprodução técnica das obras de arte destrói sua "aura" (unicidade e autenticidade), mas também democratiza o acesso à arte e abre possibilidades políticas novas' },
      { id: 'D', text: 'A tecnologia deve ser banida do campo artístico para preservar a autenticidade da criação' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'As "indústrias criativas" (cinema, música, games, moda) são hoje setores econômicos importantes. Como a Sociologia Crítica avalia esse fenômeno?',
    tip: 'As indústrias criativas representam tanto expansão da economia quanto a transformação da criatividade humana em mercadoria — qual é a tensão aí?',
    funFact: 'Você sabia? O Brasil é o maior mercado de games da América Latina — movimentando bilhões de reais por ano. Os games são hoje considerados "sétima arte" em muitos países. Mas os sociólogos discutem se são expressão artística ou produto industrial puro!',
    points: 1,
    options: [
      { id: 'A', text: 'As indústrias criativas representam a democratização plena da cultura sem contradições' },
      { id: 'B', text: 'As indústrias criativas são apenas instrumentos de dominação estatal sobre os trabalhadores' },
      { id: 'C', text: 'A Sociologia Crítica vê nas indústrias criativas tanto a expansão do acesso cultural quanto a mercantilização da criatividade, transformando expressão artística em produto para venda e lucro' },
      { id: 'D', text: 'As indústrias criativas são irrelevantes para a análise sociológica por serem apenas entretenimento' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'O rádio, como meio de comunicação de massa surgido no início do século XX, foi analisado pela Escola de Frankfurt. Qual era a crítica de Adorno ao uso do rádio?',
    tip: 'Para Adorno, o rádio não apenas transmitia música — ele mudava a forma como as pessoas OUVIAM música, criando uma escuta distraída e superficial.',
    funFact: 'Você sabia? Adorno trabalhou durante anos no Princeton Radio Research Project nos EUA, estudando como o rádio afetava os ouvintes. Suas conclusões polêmicas: o rádio criava ouvintes passivos que escutavam sem atenção, reduzindo a experiência musical a "plano de fundo"!',
    points: 1,
    options: [
      { id: 'A', text: 'O rádio era muito caro e inacessível para as classes trabalhadoras nos anos 1930' },
      { id: 'B', text: 'O rádio incentivava excessivamente o pensamento crítico, tornando as pessoas difíceis de governar' },
      { id: 'C', text: 'O rádio deveria transmitir exclusivamente música clássica e excluir o jazz e a música popular' },
      { id: 'D', text: 'O rádio transformava ouvintes em consumidores passivos de música pré-selecionada, criando hábitos de escuta distraída que empobreciam a experiência musical' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'A Semana de Arte Moderna de 1922 é considerada o marco do Modernismo brasileiro. Qual foi seu impacto cultural?',
    tip: 'A Semana de 22 não foi apenas um evento artístico — foi uma ruptura com o modo como a elite brasileira pensava sobre o que seria uma arte e cultura nacionais.',
    funFact: 'Você sabia? A Semana de Arte Moderna causou escândalo em São Paulo — o público vaiou as apresentações de música, literatura e artes plásticas! Mas esse escândalo era parte do projeto: os modernistas queriam provocar e romper com o academicismo dominante!',
    points: 1,
    options: [
      { id: 'A', text: 'Propôs romper com o academicismo europeu e criar uma arte brasileira que incorporasse a cultura popular, o modernismo internacional e a identidade nacional' },
      { id: 'B', text: 'Defendeu a importação e imitação do modernismo europeu sem adaptações à realidade brasileira' },
      { id: 'C', text: 'Limitou-se a reformar o ensino artístico nas escolas de belas artes das capitais brasileiras' },
      { id: 'D', text: 'Criou uma academia artística elitista que excluía qualquer influência da cultura popular' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'O conceito de "cultura dominante", "subcultura" e "contracultura" descreve a hierarquia nas culturas. Qual é a diferença entre subcultura e contracultura?',
    tip: 'Uma subcultura existe ao lado da cultura dominante sem necessariamente questioná-la; a contracultura existe em oposição ativa a ela.',
    funFact: 'Você sabia? O movimento hippie dos anos 1960 é o exemplo clássico de contracultura — ele não apenas era diferente da cultura dominante americana, mas a atacava explicitamente: antibelicista, antinuclear, anticonsumo, antipatriarcal!',
    points: 1,
    options: [
      { id: 'A', text: 'Subcultura e contracultura são sinônimos — ambas representam culturas minoritárias na sociedade' },
      { id: 'B', text: 'Subcultura é sempre mais violenta que contracultura, que é sempre pacífica e artística' },
      { id: 'C', text: 'A subcultura coexiste com a cultura dominante com práticas e valores próprios; a contracultura se posiciona em oposição ativa e propõe alternativas à cultura dominante' },
      { id: 'D', text: 'A subcultura é produzida pelas elites; a contracultura é sempre criada pelas classes populares' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'O cinema hollywoodiano exerce uma forma de poder cultural chamada de "soft power". O que é esse conceito?',
    tip: 'O "soft power" (poder suave) se opõe ao "hard power" (poder militar e econômico) — é a influência exercida não pela força, mas pela atração e persuasão cultural.',
    funFact: 'Você sabia? O conceito de soft power foi criado pelo cientista político Joseph Nye para descrever a influência americana pelo cinema, música, moda e valores (liberdade, democracia). A China hoje investe bilhões em seu próprio soft power: Institutos Confúcio, filmes e aplicativos!',
    points: 1,
    options: [
      { id: 'A', text: 'O uso da força militar para impor a cultura de um país sobre populações conquistadas' },
      { id: 'B', text: 'O uso de sanções econômicas para forçar outros países a adotar determinados valores culturais' },
      { id: 'C', text: 'O poder físico dos atores de Hollywood sobre o processo criativo dos filmes produzidos' },
      { id: 'D', text: 'A capacidade de influenciar outros países e culturas por meio da atração cultural (filmes, música, valores) sem o uso da coerção' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'A crítica de Adorno à astrologia, ao horóscopo e ao esoterismo de massa era que:',
    tip: 'Para Adorno, a popularidade da astrologia nas sociedades modernas não era simplesmente superstição — era sintoma de algo mais profundo.',
    funFact: 'Você sabia? Adorno escreveu um livro inteiro analisando a coluna de astrologia do Los Angeles Times. Sua conclusão: o horóscopo ensinava as pessoas a aceitar sua posição social como destino e a buscar consolo em vez de mudança — uma forma perfeita de ideologia conformista!',
    points: 1,
    options: [
      { id: 'A', text: 'A astrologia era cientificamente falsa e por isso não tinha nenhum valor cultural ou social' },
      { id: 'B', text: 'A astrologia de massa é sintoma de regressão: substitui o pensamento crítico e racional pela submissão a forças externas, funcionando como ideologia de conformismo' },
      { id: 'C', text: 'A astrologia era cara e explorava financeiramente as pessoas mais pobres e vulneráveis' },
      { id: 'D', text: 'A astrologia era utilizada pelo governo para manipular as decisões políticas dos cidadãos' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'As políticas públicas de cultura buscam garantir o acesso da população à produção cultural. Qual é o argumento sociológico que justifica essas políticas?',
    tip: 'Se a cultura é um direito e não apenas um produto de mercado, o Estado tem responsabilidades que o mercado sozinho não cumpre.',
    funFact: 'Você sabia? O PRONAC (Programa Nacional de Apoio à Cultura) e a Lei Rouanet no Brasil permitem que empresas deduzam do imposto o valor investido em cultura. Mas sociólogos criticam que o modelo favorece as artes das grandes cidades e deixa de fora a cultura popular periférica!',
    points: 1,
    options: [
      { id: 'A', text: 'Como a cultura é um direito humano e o mercado tende a concentrar o acesso nas classes com maior poder econômico, o Estado deve intervir para democratizar a produção e o acesso cultural' },
      { id: 'B', text: 'As políticas culturais existem apenas para preservar monumentos históricos de valor econômico para o turismo' },
      { id: 'C', text: 'O mercado cultural, sem intervenção estatal, garante naturalmente o acesso igualitário de todos à cultura' },
      { id: 'D', text: 'As políticas culturais são instrumentos que o Estado usa para impor sua versão oficial da identidade nacional' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'A expressão "indústria cultural" foi proposta como alternativa à "cultura de massa". Qual das afirmativas resume melhor a crítica central da Escola de Frankfurt à cultura produzida nesse modelo?',
    tip: 'Toda a crítica da Escola de Frankfurt converge em uma denúncia central: a cultura transformada em mercadoria perde uma qualidade essencial.',
    funFact: 'Você sabia? Theodor Adorno e Max Horkheimer escreveram "Dialética do Esclarecimento" exilados em Los Angeles — no próprio coração de Hollywood! Essa proximidade dolorosa com a indústria cultural americana deu concretude e urgência às suas análises críticas.',
    points: 1,
    options: [
      { id: 'A', text: 'A cultura popular é sempre inferior à cultura erudita e deveria ser suprimida em favor das artes clássicas' },
      { id: 'B', text: 'Os trabalhadores são muito ignorantes para compreender a cultura de qualidade e precisam ser educados' },
      { id: 'C', text: 'A indústria cultural produz cultura como mercadoria padronizada para o lucro, esvaziando seu potencial crítico e emancipatório e gerando conformismo com o sistema dominante' },
      { id: 'D', text: 'A tecnologia moderna destrói qualquer possibilidade de arte autêntica e criativa na sociedade contemporânea' },
    ],
    correctAnswer: 'C',
  },
];
