export const questoesHistoria1EmB1Av1 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "O período da Pré-história em que os seres humanos viviam como nômades, caçadores e coletores, utilizando ferramentas de pedra lascada, é denominado:",
    tip: "Pense no período mais longo da Pré-história, quando a pedra era trabalhada por lascamento — não por polimento.",
    funFact: "\"Você sabia?\" — O Paleolítico durou cerca de 2,5 milhões de anos, representando mais de 99% de toda a história da humanidade!",
    points: 1,
    options: [
      { id: "A", text: "Neolítico" },
      { id: "B", text: "Idade dos Metais" },
      { id: "C", text: "Paleolítico" },
      { id: "D", text: "Mesolítico Superior" },
    ],
    correctAnswer: "C",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "O Homo sapiens surgiu há aproximadamente 300 mil anos na África. Uma das características que o diferencia dos hominídeos anteriores é:",
    tip: "Pense nas capacidades cognitivas e sociais que definem o ser humano moderno em relação a espécies anteriores.",
    funFact: "\"Você sabia?\" — O nome Homo sapiens significa 'homem sábio' em latim, uma escolha do naturalista Lineu em 1758.",
    points: 1,
    options: [
      { id: "A", text: "Capacidade de raciocínio abstrato, linguagem complexa e produção de arte" },
      { id: "B", text: "Uso exclusivo de ferramentas de ferro forjado" },
      { id: "C", text: "Sedentarismo permanente em cavernas de pedra" },
      { id: "D", text: "Desenvolvimento da agricultura irrigada" },
    ],
    correctAnswer: "A",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "As pinturas encontradas nas cavernas de Lascaux (França) e Altamira (Espanha) são exemplos de arte rupestre paleolítica. Qual a principal interpretação dos historiadores sobre a função dessas pinturas?",
    tip: "Considere que os homens do Paleolítico não pintavam por lazer — as pinturas tinham um propósito prático ligado à sobrevivência e ao sobrenatural.",
    funFact: "\"Você sabia?\" — As pinturas de Lascaux têm cerca de 17 mil anos e foram descobertas por quatro adolescentes que seguiram um cachorro em 1940.",
    points: 1,
    options: [
      { id: "A", text: "Decoração estética dos ambientes de habitação" },
      { id: "B", text: "Registro histórico para gerações futuras" },
      { id: "C", text: "Comunicação entre grupos rivais" },
      { id: "D", text: "Rituais mágico-religiosos ligados à caça e fertilidade" },
    ],
    correctAnswer: "D",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "A Revolução Neolítica, ocorrida por volta de 10 mil a.C., representou uma profunda transformação na vida humana. Qual foi a principal mudança introduzida nesse período?",
    tip: "O Neolítico é chamado de 'revolução' porque transformou radicalmente a relação do ser humano com a natureza — ele parou de apenas coletar e passou a produzir.",
    funFact: "\"Você sabia?\" — A domesticação do trigo e da cevada no Oriente Médio foi um dos primeiros passos da Revolução Neolítica, possibilitando o nascimento das primeiras cidades.",
    points: 1,
    options: [
      { id: "A", text: "Desenvolvimento da metalurgia do bronze" },
      { id: "B", text: "Surgimento da agricultura e da pecuária, levando ao sedentarismo" },
      { id: "C", text: "Invenção da escrita e do calendário" },
      { id: "D", text: "Início das primeiras guerras entre povos" },
    ],
    correctAnswer: "B",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "A Idade dos Metais é dividida em três fases. A sequência cronológica correta dessas fases é:",
    tip: "Pense na evolução tecnológica: cada metal novo era mais resistente e difícil de trabalhar que o anterior.",
    funFact: "\"Você sabia?\" — O bronze é uma liga de cobre e estanho, e sua dureza superior à pedra revolucionou a fabricação de armas e ferramentas por volta de 3300 a.C.",
    points: 1,
    options: [
      { id: "A", text: "Idade do Ferro → Idade do Bronze → Idade do Cobre" },
      { id: "B", text: "Idade do Bronze → Idade do Ferro → Idade do Cobre" },
      { id: "C", text: "Idade do Cobre → Idade do Bronze → Idade do Ferro" },
      { id: "D", text: "Idade do Cobre → Idade do Ferro → Idade do Bronze" },
    ],
    correctAnswer: "C",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "A Mesopotâmia, considerada um dos berços da civilização, estava localizada entre dois grandes rios. Qual é o nome desses rios?",
    tip: "O nome 'Mesopotâmia' vem do grego e significa exatamente a localização geográfica dessa civilização em relação aos rios.",
    funFact: "\"Você sabia?\" — 'Mesopotâmia' significa 'terra entre rios' em grego (meso = meio, potamos = rio). Hoje, essa região corresponde principalmente ao Iraque.",
    points: 1,
    options: [
      { id: "A", text: "Tigre e Eufrates" },
      { id: "B", text: "Nilo e Jordão" },
      { id: "C", text: "Indo e Ganges" },
      { id: "D", text: "Amarelo e Yangtzé" },
    ],
    correctAnswer: "A",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "Os sumérios, povo que habitou o sul da Mesopotâmia por volta de 3500 a.C., são reconhecidos por uma série de contribuições à humanidade. Qual das alternativas a seguir NÃO é uma contribuição suméria?",
    tip: "Os sumérios foram extremamente inovadores, mas há um item que pertence a outro povo ou período. Analise cada opção com cuidado.",
    funFact: "\"Você sabia?\" — Os sumérios inventaram a roda por volta de 3500 a.C., inicialmente usada em tornos de oleiro, antes de ser adaptada para veículos de transporte.",
    points: 1,
    options: [
      { id: "A", text: "Invenção da escrita cuneiforme" },
      { id: "B", text: "Criação das primeiras cidades-estado" },
      { id: "C", text: "Invenção da roda" },
      { id: "D", text: "Construção das pirâmides escalonadas chamadas zigurates" },
    ],
    correctAnswer: "D",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "A escrita cuneiforme, inventada pelos sumérios, recebe esse nome porque:",
    tip: "O nome 'cuneiforme' vem do latim 'cuneus', que significa algo com formato específico — observe as marcas deixadas nas tábuas de argila.",
    funFact: "\"Você sabia?\" — A escrita cuneiforme era feita com um estilete de junco em tábuas de argila úmida, que depois eram secas ao sol ou cozidas em fornos.",
    points: 1,
    options: [
      { id: "A", text: "Era escrita em tiras de papiro no vale do rio Nilo" },
      { id: "B", text: "Os sinais tinham formato de cunha, feitos com estilete em argila" },
      { id: "C", text: "Representava figuras de animais em forma de desenhos detalhados" },
      { id: "D", text: "Era gravada em pedras com formato cônico" },
    ],
    correctAnswer: "B",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "Sargão de Acad, por volta de 2350 a.C., fundou o primeiro grande império da história. Qual povo ele representava?",
    tip: "Sargão conquistou as cidades-estado sumérias e criou algo inédito: um império que unificava diferentes povos sob um único governo.",
    funFact: "\"Você sabia?\" — Sargão de Acad é considerado o primeiro grande conquistador da história. Seu império se estendia do Mediterrâneo ao Golfo Pérsico.",
    points: 1,
    options: [
      { id: "A", text: "Babilônios" },
      { id: "B", text: "Assírios" },
      { id: "C", text: "Acadianos" },
      { id: "D", text: "Fenícios" },
    ],
    correctAnswer: "C",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "O Código de Hamurabi, elaborado pelo rei babilônico Hamurabi por volta de 1750 a.C., é considerado um dos primeiros conjuntos de leis escritas da história. Qual princípio de justiça predominava nesse código?",
    tip: "Pense em uma expressão popular que resume bem a lógica de punição desse código: uma ação merece uma reação equivalente.",
    funFact: "\"Você sabia?\" — O Código de Hamurabi foi gravado em uma estela de basalto de 2,25 metros, que foi descoberta em 1901 e hoje está no Museu do Louvre, em Paris.",
    points: 1,
    options: [
      { id: "A", text: "Talião — 'olho por olho, dente por dente' (punição proporcional ao crime)" },
      { id: "B", text: "Clemência divina — perdão para os criminosos arrependidos" },
      { id: "C", text: "Ressocialização — trabalho forçado em obras públicas" },
      { id: "D", text: "Igualdade absoluta — mesma punição para todas as classes sociais" },
    ],
    correctAnswer: "A",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Os zigurates eram construções características da Mesopotâmia. Qual era a principal função dessas estruturas?",
    tip: "Os zigurates eram construídos no centro das cidades e no topo havia sempre um espaço especial. Pense na relação entre os mesopotâmios e seus deuses.",
    funFact: "\"Você sabia?\" — Acredita-se que a Torre de Babel descrita na Bíblia tenha sido inspirada nos zigurates babilônicos, especialmente o grande zigurate de Ur.",
    points: 1,
    options: [
      { id: "A", text: "Servir como celeiros para armazenar grãos durante as cheias" },
      { id: "B", text: "Funcionar como templos dedicados às divindades, ligando a terra ao céu" },
      { id: "C", text: "Ser fortalezas militares para defesa da cidade" },
      { id: "D", text: "Abrigar o palácio do rei e sua família" },
    ],
    correctAnswer: "B",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Qual foi o principal legado da invenção da escrita para as civilizações antigas da Mesopotâmia?",
    tip: "Pense no que muda quando uma civilização passa a registrar informações por escrito — o que se torna possível que antes não era?",
    funFact: "\"Você sabia?\" — A escrita surgiu inicialmente como uma ferramenta contábil: os sumérios precisavam registrar estoques de grãos, rebanhos e transações comerciais.",
    points: 1,
    options: [
      { id: "A", text: "Permitiu a construção de monumentos maiores e mais duráveis" },
      { id: "B", text: "Garantiu a paz permanente entre as cidades-estado" },
      { id: "C", text: "Facilitou a caça coletiva de grandes animais" },
      { id: "D", text: "Possibilitou o registro de leis, contratos, histórias e conhecimentos, transmitindo-os às gerações futuras" },
    ],
    correctAnswer: "D",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "A divisão do tempo em 60 segundos por minuto, 60 minutos por hora e 24 horas por dia tem sua origem em qual civilização?",
    tip: "Essa civilização era famosa por seu avançado sistema matemático baseado no número 60 — o sistema sexagesimal.",
    funFact: "\"Você sabia?\" — Os sumérios usavam um sistema numérico de base 60 (sexagesimal), que herdamos até hoje no modo como medimos tempo e ângulos.",
    points: 1,
    options: [
      { id: "A", text: "Egípcia" },
      { id: "B", text: "Grega" },
      { id: "C", text: "Suméria/Mesopotâmica" },
      { id: "D", text: "Romana" },
    ],
    correctAnswer: "C",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "Na estrutura social das cidades-estado sumérias, qual era a posição do rei (ou lugal)?",
    tip: "Na visão suméria, o rei não era simplesmente um governante político — ele tinha uma função religiosa fundamental para a cidade.",
    funFact: "\"Você sabia?\" — Em sumérico, 'lugal' significa literalmente 'homem grande'. O rei era visto como intermediário entre os deuses e os homens.",
    points: 1,
    options: [
      { id: "A", text: "Representante dos deuses na Terra, governante militar e religioso supremo" },
      { id: "B", text: "Simples administrador eleito pelos sacerdotes do templo" },
      { id: "C", text: "Líder apenas em tempos de guerra, sem poder em tempos de paz" },
      { id: "D", text: "Chefe de uma das famílias mais ricas da cidade" },
    ],
    correctAnswer: "A",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Os assírios, povo da Mesopotâmia do Norte, são historicamente conhecidos principalmente por:",
    tip: "Os assírios construíram um dos maiores impérios da antiguidade mesopotâmica, e sua reputação nas guerras era bem conhecida pelos povos vizinhos.",
    funFact: "\"Você sabia?\" — A Biblioteca de Assurbanipal em Nínive reuniu mais de 30 mil tábuas de argila e é considerada a primeira grande biblioteca da história.",
    points: 1,
    options: [
      { id: "A", text: "Criação da primeira democracia do mundo antigo" },
      { id: "B", text: "Formação de um poderoso império militar com exército organizado e conquistas violentas" },
      { id: "C", text: "Desenvolvimento do comércio marítimo no Mediterrâneo" },
      { id: "D", text: "Invenção da escrita hieroglífica" },
    ],
    correctAnswer: "B",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "O Épico de Gilgamesh, texto mesopotâmio de cerca de 2100 a.C., é considerado uma das primeiras obras literárias da humanidade. Qual é o tema central dessa narrativa?",
    tip: "Gilgamesh era rei de Uruk e sua jornada envolve questões que os seres humanos se fazem até hoje sobre a condição humana.",
    funFact: "\"Você sabia?\" — O Épico de Gilgamesh contém um relato de um grande dilúvio muito semelhante ao da história de Noé na Bíblia, sugerindo uma fonte comum muito mais antiga.",
    points: 1,
    options: [
      { id: "A", text: "A conquista militar de outras cidades-estado pelo rei Gilgamesh" },
      { id: "B", text: "As leis criadas pelo rei para governar a Mesopotâmia" },
      { id: "C", text: "A fundação da cidade de Babilônia pelos deuses" },
      { id: "D", text: "A busca pela imortalidade e a aceitação da morte como destino humano" },
    ],
    correctAnswer: "D",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "No período Neolítico, qual inovação tecnológica representa a principal diferença no trabalho da pedra em relação ao Paleolítico?",
    tip: "No Paleolítico, a pedra era trabalhada de um jeito; no Neolítico, surgiu uma técnica diferente que permitia objetos mais refinados. Pense no que diferencia 'lascar' de outra técnica.",
    funFact: "\"Você sabia?\" — A técnica do polimento permitiu fabricar machados tão afiados que podiam cortar árvores. Isso foi fundamental para o desmatamento necessário à agricultura.",
    points: 1,
    options: [
      { id: "A", text: "Uso do fogo para fundir metais" },
      { id: "B", text: "Criação de ferramentas de osso e chifre" },
      { id: "C", text: "Polimento da pedra, produzindo ferramentas mais finas e duráveis" },
      { id: "D", text: "Fabricação de armas de bronze" },
    ],
    correctAnswer: "C",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "O controle do fogo pelo ser humano, ainda no Paleolítico, trouxe diversas vantagens. Qual das opções abaixo NÃO é uma consequência direta do domínio do fogo nesse período?",
    tip: "O fogo foi transformador em muitos aspectos — proteção, alimentação, luz, calor. Mas há um item que representa uma mudança de um período totalmente diferente, posterior ao Paleolítico.",
    funFact: "\"Você sabia?\" — Evidências do uso do fogo pelo Homo erectus datam de 1 milhão de anos atrás, na África do Sul. Cozinhar alimentos pode ter contribuído para o desenvolvimento do cérebro humano.",
    points: 1,
    options: [
      { id: "A", text: "Surgimento da agricultura, da criação de animais e do sedentarismo das comunidades" },
      { id: "B", text: "Cozimento dos alimentos, melhorando a digestão e ampliando a dieta" },
      { id: "C", text: "Aquecimento em climas frios, permitindo a colonização de novas regiões" },
      { id: "D", text: "Proteção contra animais predadores e iluminação de cavernas" },
    ],
    correctAnswer: "A",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "A expansão do Homo sapiens pelo planeta, saindo da África e colonizando todos os continentes, ocorreu principalmente durante:",
    tip: "Pense no período em que os humanos ainda eram caçadores-coletores e começaram a explorar novas terras além da África.",
    funFact: "\"Você sabia?\" — Os seres humanos chegaram à América há aproximadamente 15 a 20 mil anos, provavelmente atravessando a Beríngia, uma ponte de terra que conectava a Sibéria ao Alasca.",
    points: 1,
    options: [
      { id: "A", text: "Idade do Bronze" },
      { id: "B", text: "Paleolítico Superior (entre 70 mil e 10 mil a.C.)" },
      { id: "C", text: "Neolítico, após a invenção da agricultura" },
      { id: "D", text: "Idade do Ferro" },
    ],
    correctAnswer: "B",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "A Babilônia, sob o reinado de Hamurabi (séc. XVIII a.C.), tornou-se o centro de um grande império. Além do famoso código de leis, qual outro aspecto distinguia a civilização babilônica?",
    tip: "A Babilônia era conhecida por seu conhecimento do céu noturno e por monumentos impressionantes — pense nos estudos que permitiam prever fenômenos naturais.",
    funFact: "\"Você sabia?\" — Os Jardins Suspensos da Babilônia são uma das Sete Maravilhas do Mundo Antigo, supostamente construídos pelo rei Nabucodonosor II para sua esposa que sentia saudade das montanhas.",
    points: 1,
    options: [
      { id: "A", text: "Invenção da democracia e do voto popular" },
      { id: "B", text: "Construção das primeiras pirâmides escalonadas do mundo" },
      { id: "C", text: "Desenvolvimento das primeiras rotas comerciais marítimas" },
      { id: "D", text: "Avanços em astronomia e matemática, com previsão de eclipses e estações do ano" },
    ],
    correctAnswer: "D",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "A domesticação de animais, iniciada no Neolítico, trouxe importantes benefícios para as sociedades humanas. Qual foi a principal vantagem imediata dessa prática?",
    tip: "Pense no cotidiano de uma comunidade agrícola primitiva: quais tarefas ficaram mais fáceis com a presença de animais domesticados?",
    funFact: "\"Você sabia?\" — O cachorro foi o primeiro animal domesticado pelo ser humano, há cerca de 15 mil anos, provavelmente a partir do lobo cinzento, para auxiliar na caça.",
    points: 1,
    options: [
      { id: "A", text: "Fornecimento constante de alimentos (leite, carne, ovos) e força de trabalho para a agricultura" },
      { id: "B", text: "Proteção militar contra povos invasores" },
      { id: "C", text: "Transporte de mensagens entre cidades distantes" },
      { id: "D", text: "Fabricação de objetos de metal a partir de ossos animais" },
    ],
    correctAnswer: "A",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "O surgimento das primeiras cidades na Mesopotâmia, como Ur, Uruk e Lagash, foi possível graças a qual fator fundamental?",
    tip: "Para existir uma cidade, é preciso que as pessoas não precisem mais gastar todo o tempo produzindo alimento. O que tornou isso possível?",
    funFact: "\"Você sabia?\" — Uruk, por volta de 3000 a.C., tinha cerca de 50 mil habitantes e é considerada por muitos historiadores como a primeira cidade verdadeira da história.",
    points: 1,
    options: [
      { id: "A", text: "Desenvolvimento da metalurgia do ferro" },
      { id: "B", text: "Domínio das rotas comerciais do Mediterrâneo" },
      { id: "C", text: "Excedente agrícola gerado pela agricultura irrigada, liberando parte da população para outras atividades" },
      { id: "D", text: "Conquistas militares que escravizaram povos vizinhos" },
    ],
    correctAnswer: "C",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Na Mesopotâmia, a irrigação era fundamental para a agricultura porque:",
    tip: "Pense na característica climática da região entre o Tigre e o Eufrates — chovia pouco e as cheias eram imprevisíveis.",
    funFact: "\"Você sabia?\" — Os mesopotâmios construíram canais de irrigação tão sofisticados que alguns deles ainda são visíveis por satélite no atual Iraque, milênios depois.",
    points: 1,
    options: [
      { id: "A", text: "A região era muito fria e precisava de água morna para as plantações" },
      { id: "B", text: "O clima seco e as cheias irregulares dos rios exigiam controle artificial da água para garantir as colheitas" },
      { id: "C", text: "Os animais domésticos precisavam de grandes quantidades de água todos os dias" },
      { id: "D", text: "A escassez de rios na região tornava a irrigação a única forma de obter água" },
    ],
    correctAnswer: "B",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Qual povo mesopotâmio é conhecido por ter construído a cidade de Nínive e por possuir um exército considerado um dos mais cruéis e poderosos da antiguidade?",
    tip: "Esse povo dominou a Mesopotâmia durante séculos graças à sua supremacia militar, sendo temido por toda a região.",
    funFact: "\"Você sabia?\" — Os assírios foram pioneiros no uso de cavalaria, cavalos, carros de guerra de ferro e técnicas de cerco a cidades, tornando seu exército praticamente invencível por séculos.",
    points: 1,
    options: [
      { id: "A", text: "Sumérios" },
      { id: "B", text: "Babilônios" },
      { id: "C", text: "Fenícios" },
      { id: "D", text: "Assírios" },
    ],
    correctAnswer: "D",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "A escrita surgiu inicialmente como um sistema pictográfico. O que caracteriza esse tipo de escrita?",
    tip: "O prefixo 'picto' vem do latim e está relacionado a imagens. Pense em como as primeiras escritas representavam as coisas.",
    funFact: "\"Você sabia?\" — Os primeiros textos escritos conhecidos, de Uruk (3300 a.C.), registravam quantidades de grãos e animais — eram basicamente recibos comerciais!",
    points: 1,
    options: [
      { id: "A", text: "Uso de desenhos que representavam diretamente os objetos ou ideias que se queria comunicar" },
      { id: "B", text: "Uso de símbolos sonoros que representavam sílabas" },
      { id: "C", text: "Uso de letras que representavam sons individuais" },
      { id: "D", text: "Uso de números para registrar quantidades apenas" },
    ],
    correctAnswer: "A",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "O método científico utilizado pelos arqueólogos para determinar a idade de materiais orgânicos encontrados em sítios pré-históricos é chamado de:",
    tip: "Esse método usa a desintegração de um isótopo presente em todos os organismos vivos para calcular quanto tempo se passou desde a morte do organismo.",
    funFact: "\"Você sabia?\" — A datação por carbono-14 foi desenvolvida pelo químico Willard Libby em 1949, rendendo-lhe o Prêmio Nobel de Química em 1960.",
    points: 1,
    options: [
      { id: "A", text: "Estratigrafia" },
      { id: "B", text: "Paleografia" },
      { id: "C", text: "Datação por carbono-14 (radiocarbono)" },
      { id: "D", text: "Dendrocronologia" },
    ],
    correctAnswer: "C",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Qual a diferença fundamental entre o Homo habilis e o Homo sapiens no processo evolutivo humano?",
    tip: "Compare a capacidade craniana e as habilidades de cada espécie para identificar o que distingue o sapiens dos hominídeos anteriores.",
    funFact: "\"Você sabia?\" — O cérebro do Homo sapiens é três vezes maior que o do chimpanzé, mas consome 20% da energia do corpo humano — por isso pensar dá fome!",
    points: 1,
    options: [
      { id: "A", text: "O Homo habilis já usava ferramentas de metal, enquanto o sapiens usava pedra" },
      { id: "B", text: "O Homo sapiens possuía maior capacidade craniana, linguagem complexa e habilidade para pensamento abstrato" },
      { id: "C", text: "O Homo habilis vivia em grupos sociais, enquanto o sapiens era solitário" },
      { id: "D", text: "O Homo sapiens foi a primeira espécie a caminhar em posição ereta" },
    ],
    correctAnswer: "B",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "As pinturas rupestres encontradas em cavernas europeias como Altamira e Lascaux retratam principalmente:",
    tip: "Observe o que os artistas paleolíticos escolheram representar — o conteúdo das pinturas reflete as principais preocupações do cotidiano desses grupos.",
    funFact: "\"Você sabia?\" — Os artistas do Paleolítico usavam pigmentos minerais como ocre (vermelho/amarelo) e manganês (preto), misturados com gordura animal, criando tintas que duraram dezenas de milhares de anos.",
    points: 1,
    options: [
      { id: "A", text: "Batalhas entre grupos humanos rivais" },
      { id: "B", text: "Mapas geográficos das regiões habitadas" },
      { id: "C", text: "Plantas cultivadas e ferramentas agrícolas" },
      { id: "D", text: "Animais selvagens (bisões, cavalos, mamutes) e cenas de caça" },
    ],
    correctAnswer: "D",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "As ferramentas de pedra lascada características do Paleolítico eram produzidas a partir de qual técnica?",
    tip: "No Paleolítico, a pedra era trabalhada de forma 'bruta', quebrando-a para criar bordas afiadas — o oposto do polimento que viria no Neolítico.",
    funFact: "\"Você sabia?\" — O sílex era a pedra mais utilizada no Paleolítico por sua capacidade de criar bordas extremamente afiadas quando lascado. Era mais cortante que muitos metais!",
    points: 1,
    options: [
      { id: "A", text: "Golpeando pedras umas contra as outras para criar lascas com bordas cortantes" },
      { id: "B", text: "Polindo as pedras com areia fina e água" },
      { id: "C", text: "Fundindo pedras em altas temperaturas para moldar ferramentas" },
      { id: "D", text: "Gravando designs em pedras com instrumentos de metal" },
    ],
    correctAnswer: "A",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "A religião dos mesopotâmios era politeísta e cada cidade-estado tinha seu deus protetor. Como era chamada a visão religiosa que atribuía força ou espírito a todos os elementos da natureza, como rios, montanhas e tempestades?",
    tip: "Essa crença, presente em muitas culturas antigas, via o mundo natural como habitado por forças ou espíritos sobrenaturais.",
    funFact: "\"Você sabia?\" — Para os mesopotâmios, os deuses haviam criado os humanos para servi-los: o ser humano era um 'funcionário dos deuses', responsável por manter os templos e fazer oferendas.",
    points: 1,
    options: [
      { id: "A", text: "Monoteísmo" },
      { id: "B", text: "Ateísmo" },
      { id: "C", text: "Animismo" },
      { id: "D", text: "Deísmo" },
    ],
    correctAnswer: "C",
  },
];
