export const questoesMatematica5AnoB2Av2 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'O que é um número decimal?',
    tip: 'Pensa em números como 3,5 ou 2,75, que têm uma vírgula separando duas partes...',
    funFact: 'Você sabia que usamos números decimais o tempo todo, principalmente quando lidamos com dinheiro?',
    points: 1,
    options: [
      { id: 'A', text: 'Um número que representa sempre uma quantidade inteira, sem partes' },
      { id: 'B', text: 'Uma forma de representar frações com denominador 10, 100, 1000..., usando uma vírgula' },
      { id: 'C', text: 'Um número usado apenas para contar objetos' },
      { id: 'D', text: 'Um sinal de pontuação em matemática' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'No número decimal 0,1, a primeira casa depois da vírgula representa:',
    tip: 'Pensa: essa casa representa a fração 1/10...',
    funFact: 'Você sabia que "décimo" vem da palavra "dez", já que essa casa representa uma parte em dez?',
    points: 1,
    options: [
      { id: 'A', text: 'Centésimos' },
      { id: 'B', text: 'Milésimos' },
      { id: 'C', text: 'Unidades' },
      { id: 'D', text: 'Décimos' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'No número decimal 0,01, a segunda casa depois da vírgula representa:',
    tip: 'Pensa: essa casa representa a fração 1/100...',
    funFact: 'Você sabia que "centésimo" tem a ver com "cem", já que essa casa representa uma parte em cem?',
    points: 1,
    options: [
      { id: 'A', text: 'Centésimos' },
      { id: 'B', text: 'Décimos' },
      { id: 'C', text: 'Unidades' },
      { id: 'D', text: 'Milhares' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'Como se lê o número 3,5?',
    tip: 'Pensa na parte antes da vírgula (inteiros) e depois da vírgula (décimos)...',
    funFact: 'Você sabia que 3,5 também pode ser lido de forma mais simples como "três e meio"?',
    points: 1,
    options: [
      { id: 'A', text: 'Três vírgula cinquenta' },
      { id: 'B', text: 'Trinta e cinco' },
      { id: 'C', text: 'Três inteiros e cinco décimos' },
      { id: 'D', text: 'Cinco inteiros e três décimos' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'Como se lê o número 2,75?',
    tip: 'Pensa: depois da vírgula, esse número tem duas casas, então são centésimos...',
    funFact: 'Você sabia que 2,75 é o mesmo que dizer "dois reais e setenta e cinco centavos", se estivéssemos falando de dinheiro?',
    points: 1,
    options: [
      { id: 'A', text: 'Dois inteiros e setenta e cinco décimos' },
      { id: 'B', text: 'Dois inteiros e setenta e cinco centésimos' },
      { id: 'C', text: 'Vinte e sete vírgula cinco' },
      { id: 'D', text: 'Setenta e cinco inteiros e dois centésimos' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'Como se escreve, em algarismos, "um inteiro e dois décimos"?',
    tip: 'Pensa em separar a parte inteira (1) da parte decimal (2 décimos)...',
    funFact: 'Você sabia que "um inteiro e dois décimos" também pode ser escrito como a fração 12/10?',
    points: 1,
    options: [
      { id: 'A', text: '12' },
      { id: 'B', text: '0,12' },
      { id: 'C', text: '2,1' },
      { id: 'D', text: '1,2' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'A fração 1/2 é equivalente a qual número decimal?',
    tip: 'Pensa: dividindo 1 por 2, qual é o resultado?',
    funFact: 'Você sabia que 0,5 é uma das transformações de fração para decimal mais usadas no dia a dia?',
    points: 1,
    options: [
      { id: 'A', text: '0,2' },
      { id: 'B', text: '0,12' },
      { id: 'C', text: '0,5' },
      { id: 'D', text: '1,2' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'A fração 1/4 é equivalente a qual número decimal?',
    tip: 'Pensa: dividindo 1 por 4, qual é o resultado?',
    funFact: 'Você sabia que 1/4 também pode ser pensado como "a metade da metade"?',
    points: 1,
    options: [
      { id: 'A', text: '0,25' },
      { id: 'B', text: '0,4' },
      { id: 'C', text: '0,14' },
      { id: 'D', text: '1,4' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'No número 4,75, qual é a parte inteira e qual é a parte decimal?',
    tip: 'Lembra: a parte inteira fica antes da vírgula, e a parte decimal fica depois...',
    funFact: 'Você sabia que a parte inteira de um número decimal funciona exatamente como um número natural comum?',
    points: 1,
    options: [
      { id: 'A', text: 'Parte inteira 75, parte decimal 4' },
      { id: 'B', text: 'Parte inteira 4, parte decimal 75' },
      { id: 'C', text: 'Parte inteira 4,75, parte decimal 0' },
      { id: 'D', text: 'Parte inteira 47, parte decimal 5' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'Para que serve a vírgula em um número decimal?',
    tip: 'Lembra de tudo que vimos nesse bloco sobre a função da vírgula...',
    funFact: 'Você sabia que em alguns países, como os Estados Unidos, usa-se um ponto no lugar da vírgula para separar as casas decimais?',
    points: 1,
    options: [
      { id: 'A', text: 'Para substituir o sinal de multiplicação' },
      { id: 'B', text: 'Para indicar o fim de uma frase' },
      { id: 'C', text: 'Para separar unidades de dezenas apenas' },
      { id: 'D', text: 'Para separar a parte inteira da parte decimal do número' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'Para comparar dois números decimais, o primeiro passo é:',
    tip: 'Pensa: assim como em números naturais, começamos comparando pela parte "maior" do número...',
    funFact: 'Você sabia que essa regra vale mesmo quando os números têm partes decimais bem diferentes?',
    points: 1,
    options: [
      { id: 'A', text: 'Comparar a parte inteira de cada número' },
      { id: 'B', text: 'Comparar apenas a parte decimal' },
      { id: 'C', text: 'Somar os dois números' },
      { id: 'D', text: 'Ignorar a parte inteira completamente' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'Quando dois números decimais têm a mesma parte inteira, para saber qual é o maior, devemos:',
    tip: 'Pensa: se a parte inteira é igual, a diferença vai estar na parte depois da vírgula...',
    funFact: 'Você sabia que, se os décimos também forem iguais, comparamos os centésimos em seguida?',
    points: 1,
    options: [
      { id: 'A', text: 'Somar os dois números' },
      { id: 'B', text: 'Multiplicar as partes inteiras' },
      { id: 'C', text: 'Comparar os décimos (e depois os centésimos, se necessário)' },
      { id: 'D', text: 'É impossível saber qual é maior' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'Qual número é MAIOR: 3,4 ou 3,6?',
    tip: 'Como a parte inteira é igual (3), compare os décimos: 4 ou 6?',
    funFact: 'Você sabia que essa comparação funciona do mesmo jeito que comparar números naturais, só que olhando as casas depois da vírgula?',
    points: 1,
    options: [
      { id: 'A', text: 'Os dois são iguais' },
      { id: 'B', text: '3,4' },
      { id: 'C', text: 'Não é possível saber' },
      { id: 'D', text: '3,6' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'Qual número é MAIOR: 2,45 ou 2,5?',
    tip: 'Pensa: 2,5 é o mesmo que 2,50... comparando com 2,45, qual tem os décimos maiores?',
    funFact: 'Você sabia que acrescentar um zero depois da última casa decimal não muda o valor do número, só ajuda a comparar?',
    points: 1,
    options: [
      { id: 'A', text: '2,45' },
      { id: 'B', text: '2,5' },
      { id: 'C', text: 'Os dois são iguais' },
      { id: 'D', text: 'Não é possível saber' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'Para somar dois números decimais corretamente, é importante:',
    tip: 'Pensa em como organizamos as contas de adição: unidade embaixo de unidade, dezena embaixo de dezena...',
    funFact: 'Você sabia que alinhar as vírgulas é o segredo para não errar contas com números decimais?',
    points: 1,
    options: [
      { id: 'A', text: 'Alinhar as vírgulas, uma embaixo da outra' },
      { id: 'B', text: 'Ignorar a vírgula completamente' },
      { id: 'C', text: 'Somar sempre a parte inteira com a parte decimal do outro número' },
      { id: 'D', text: 'Somar apenas a parte inteira' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'Quanto é 2,5 + 1,3?',
    tip: 'Alinhe as vírgulas e some as partes inteiras e decimais separadamente...',
    funFact: 'Você sabia que somar decimais é parecido com somar números naturais, só que com uma casa extra de cuidado?',
    points: 1,
    options: [
      { id: 'A', text: '3,5' },
      { id: 'B', text: '4,8' },
      { id: 'C', text: '3,8' },
      { id: 'D', text: '2,8' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'Assim como na adição, para subtrair dois números decimais corretamente, é importante:',
    tip: 'Pensa em como organizamos as contas de subtração, alinhando as casas correspondentes...',
    funFact: 'Você sabia que esse mesmo cuidado com o alinhamento vale tanto para a adição quanto para a subtração de decimais?',
    points: 1,
    options: [
      { id: 'A', text: 'Ignorar a parte decimal' },
      { id: 'B', text: 'Alinhar as vírgulas, uma embaixo da outra' },
      { id: 'C', text: 'Somar as duas partes inteiras' },
      { id: 'D', text: 'Sempre arredondar os números antes de subtrair' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'Quanto é 5,7 - 2,4?',
    tip: 'Alinhe as vírgulas e subtraia as partes inteiras e decimais separadamente...',
    funFact: 'Você sabia que conferir o resultado com uma prova real (somando o resultado ao número subtraído) também funciona com decimais?',
    points: 1,
    options: [
      { id: 'A', text: '3,7' },
      { id: 'B', text: '2,3' },
      { id: 'C', text: '4,3' },
      { id: 'D', text: '3,3' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'O valor R$ 3,50 (três reais e cinquenta centavos) é um exemplo de:',
    tip: 'Pensa em como os preços costumam ser escritos, com reais e centavos separados por vírgula...',
    funFact: 'Você sabia que os centavos representam centésimos de um real, por isso usamos duas casas decimais no dinheiro?',
    points: 1,
    options: [
      { id: 'A', text: 'Número decimal usado no dinheiro' },
      { id: 'B', text: 'Número inteiro apenas' },
      { id: 'C', text: 'Fração imprópria' },
      { id: 'D', text: 'Número decimal que não pode ser comparado com outros' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'Por que é importante alinhar as vírgulas ao somar ou subtrair números decimais?',
    tip: 'Lembra de tudo que vimos nesse bloco sobre organizar as contas com decimais...',
    funFact: 'Você sabia que um erro comum é esquecer de alinhar as vírgulas, o que pode mudar completamente o resultado da conta?',
    points: 1,
    options: [
      { id: 'A', text: 'Porque isso não faz nenhuma diferença no resultado' },
      { id: 'B', text: 'Porque a vírgula deve sempre ficar no início da conta' },
      { id: 'C', text: 'Porque alinhar garante que unidades, décimos e centésimos sejam somados ou subtraídos corretamente' },
      { id: 'D', text: 'Porque sem alinhar não é possível escrever números decimais' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Bernardo comprou um suco por R$ 2,50 e um salgado por R$ 3,25. Quanto ele gastou ao todo?',
    tip: 'Alinhe as vírgulas e some os dois valores: 2,50 + 3,25...',
    funFact: 'Você sabia que lanches saudáveis, como sucos naturais, são uma ótima escolha no dia a dia?',
    points: 1,
    options: [
      { id: 'A', text: 'R$ 5,50' },
      { id: 'B', text: 'R$ 6,75' },
      { id: 'C', text: 'R$ 5,25' },
      { id: 'D', text: 'R$ 5,75' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Bernardo pagou com uma nota de R$ 10,00 uma compra de R$ 7,35. Quanto de troco ele deve receber?',
    tip: 'Subtraia o valor da compra do valor pago: 10,00 - 7,35...',
    funFact: 'Você sabia que conferir o troco recebido é um bom hábito para praticar matemática no dia a dia?',
    points: 1,
    options: [
      { id: 'A', text: 'R$ 2,35' },
      { id: 'B', text: 'R$ 2,65' },
      { id: 'C', text: 'R$ 3,65' },
      { id: 'D', text: 'R$ 2,75' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Bernardo mediu sua altura e anotou 1,45 metro. Isso significa que ele tem:',
    tip: 'Pensa: a parte inteira (1) representa metros, e a parte decimal (45) representa centímetros...',
    funFact: 'Você sabia que medir a altura regularmente é uma forma divertida de acompanhar o próprio crescimento?',
    points: 1,
    options: [
      { id: 'A', text: '145 centímetros e mais 45 metros' },
      { id: 'B', text: 'Apenas 45 centímetros' },
      { id: 'C', text: '1 metro e 45 centímetros' },
      { id: 'D', text: '14,5 metros' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Bernardo comparou o preço de dois lápis: um custa R$ 1,90 e o outro custa R$ 1,75. Qual é o mais barato?',
    tip: 'Como a parte inteira é igual (1), compare os décimos: 9 ou 7?',
    funFact: 'Você sabia que comparar preços antes de comprar é uma ótima forma de economizar?',
    points: 1,
    options: [
      { id: 'A', text: 'O que custa R$ 1,75' },
      { id: 'B', text: 'O que custa R$ 1,90' },
      { id: 'C', text: 'Os dois custam o mesmo valor' },
      { id: 'D', text: 'Não é possível saber' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Revisão: como se lê o número 6,25?',
    tip: 'Pensa: depois da vírgula, esse número tem duas casas, então são centésimos...',
    funFact: 'Você sabia que ler corretamente um número decimal ajuda a entender melhor o seu valor real?',
    points: 1,
    options: [
      { id: 'A', text: 'Seis inteiros e vinte e cinco décimos' },
      { id: 'B', text: 'Sessenta e dois vírgula cinco' },
      { id: 'C', text: 'Vinte e cinco inteiros e seis centésimos' },
      { id: 'D', text: 'Seis inteiros e vinte e cinco centésimos' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Revisão: a fração 3/4 é equivalente a qual número decimal?',
    tip: 'Pensa: dividindo 3 por 4, qual é o resultado?',
    funFact: 'Você sabia que 3/4 também pode ser pensado como "três partes de um total dividido em quatro"?',
    points: 1,
    options: [
      { id: 'A', text: '0,34' },
      { id: 'B', text: '0,75' },
      { id: 'C', text: '3,4' },
      { id: 'D', text: '0,25' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Revisão: qual número é MAIOR: 7,2 ou 7,8?',
    tip: 'Como a parte inteira é igual (7), compare os décimos: 2 ou 8?',
    funFact: 'Você sabia que praticar essas comparações ajuda bastante quando formos aprender sobre medidas de líquidos e massas?',
    points: 1,
    options: [
      { id: 'A', text: '7,8' },
      { id: 'B', text: '7,2' },
      { id: 'C', text: 'Os dois são iguais' },
      { id: 'D', text: 'Não é possível saber' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Revisão: quanto é 4,6 + 2,3?',
    tip: 'Alinhe as vírgulas e some as partes inteiras e decimais separadamente...',
    funFact: 'Você sabia que revisar as contas com calma ajuda a evitar pequenos erros de cálculo?',
    points: 1,
    options: [
      { id: 'A', text: '6,3' },
      { id: 'B', text: '7,9' },
      { id: 'C', text: '6,9' },
      { id: 'D', text: '5,9' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Revisão geral: por que é importante saber ler, escrever e operar com números decimais?',
    tip: 'Pensa em quantas vezes você vê números com vírgula no seu dia a dia, como em preços...',
    funFact: 'Você sabia que até resultados esportivos, como o tempo de uma corrida, costumam usar números decimais?',
    points: 1,
    options: [
      { id: 'A', text: 'Porque eles não têm nenhuma utilidade' },
      { id: 'B', text: 'Porque só aparecem em provas de matemática' },
      { id: 'C', text: 'Porque números decimais nunca são usados fora da escola' },
      { id: 'D', text: 'Porque usamos números decimais em muitas situações do dia a dia, como preços, medidas e resultados' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'Parabéns por aprender sobre números decimais! O que é mais importante lembrar desse conteúdo?',
    tip: 'Pensa em tudo que aprendemos: leitura, escrita, comparação e operações com números decimais...',
    funFact: 'Você sabia que dominar números decimais é essencial para lidar bem com dinheiro, medidas e muitas outras situações da vida adulta?',
    points: 1,
    options: [
      { id: 'A', text: 'Que números decimais não têm relação com frações' },
      { id: 'B', text: 'Que a vírgula separa a parte inteira da parte decimal, e por isso ela deve ser alinhada nas operações' },
      { id: 'C', text: 'Que decimais nunca podem ser comparados' },
      { id: 'D', text: 'Que só existem números decimais com uma casa depois da vírgula' },
    ],
    correctAnswer: 'B',
  },
];
