export const questoesMatematica1EmB1Av1 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'Dados os conjuntos A = {1, 2, 3} e B = {2, 3, 4, 5}, qual é o conjunto A ∪ B (união)?',
    tip: 'Na união, você reúne todos os elementos que aparecem em A ou em B, sem repetir nenhum.',
    funFact: 'Você sabia? O símbolo ∪ para união de conjuntos foi introduzido pelo matemático italiano Giuseppe Peano em 1888, inspirado na letra "U" de "união".',
    points: 1,
    options: [
      { id: 'A', text: '{1, 2, 3, 4, 5, 6}' },
      { id: 'B', text: '{2, 3}' },
      { id: 'C', text: '{1, 2, 3, 4, 5}' },
      { id: 'D', text: '{4, 5}' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'Dados os conjuntos A = {1, 2, 3, 4} e B = {3, 4, 5, 6}, qual é o conjunto A ∩ B (interseção)?',
    tip: 'Na interseção, ficam apenas os elementos que estão ao mesmo tempo em A E em B.',
    funFact: 'Você sabia? Os diagramas de Venn foram criados pelo matemático inglês John Venn em 1880 para ilustrar relações entre conjuntos. Hoje são usados até em publicidade!',
    points: 1,
    options: [
      { id: 'A', text: '{3, 4}' },
      { id: 'B', text: '{1, 2, 3, 4, 5, 6}' },
      { id: 'C', text: '{1, 2}' },
      { id: 'D', text: '{5, 6}' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'Dados os conjuntos A = {1, 2, 3, 4, 5} e B = {3, 4, 5, 6, 7}, qual é o conjunto A – B (diferença)?',
    tip: 'A diferença A – B contém os elementos que estão em A, mas NÃO estão em B.',
    funFact: 'Você sabia? A teoria dos conjuntos foi desenvolvida por Georg Cantor no século XIX e inicialmente foi tão polêmica que o próprio Cantor foi atacado por outros matemáticos da época.',
    points: 1,
    options: [
      { id: 'A', text: '{3, 4, 5}' },
      { id: 'B', text: '{6, 7}' },
      { id: 'C', text: '{1, 2, 6, 7}' },
      { id: 'D', text: '{1, 2}' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'Em um diagrama de Venn, sabe-se que n(A) = 12, n(B) = 8 e n(A ∩ B) = 3. Qual é o valor de n(A ∪ B)?',
    tip: 'Existe uma fórmula para isso: n(A ∪ B) = n(A) + n(B) – n(A ∩ B). Subtrair a interseção evita contar os elementos repetidos duas vezes.',
    funFact: 'Você sabia? A fórmula de inclusão-exclusão que usamos aqui pode ser generalizada para três, quatro ou qualquer número de conjuntos — ela é fundamental em combinatória e probabilidade.',
    points: 1,
    options: [
      { id: 'A', text: '20' },
      { id: 'B', text: '17' },
      { id: 'C', text: '23' },
      { id: 'D', text: '14' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'Dado o conjunto universo U = {1, 2, 3, 4, 5, 6, 7, 8} e A = {1, 3, 5, 7}, qual é o conjunto complementar de A, indicado por A\'?',
    tip: 'O complementar de A reúne todos os elementos do universo que NÃO pertencem a A.',
    funFact: 'Você sabia? O conceito de conjunto complementar é amplamente usado em lógica digital: na eletrônica, a operação NOT (negação) é exatamente o complementar — ela inverte 0 para 1 e vice-versa.',
    points: 1,
    options: [
      { id: 'A', text: '{1, 3, 5, 7}' },
      { id: 'B', text: '{1, 2, 3, 4, 5, 6, 7, 8}' },
      { id: 'C', text: '{2, 4, 6, 8}' },
      { id: 'D', text: '{}' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'Uma relação f: A → B é classificada como FUNÇÃO quando:',
    tip: 'A palavra-chave é "exatamente": cada elemento do domínio deve ter exatamente uma imagem — nem zero, nem duas.',
    funFact: 'Você sabia? O conceito moderno de função foi formalizado por Leonhard Euler no século XVIII, mas a ideia já aparecia implicitamente em Newton e Leibniz quando criaram o Cálculo.',
    points: 1,
    options: [
      { id: 'A', text: 'Todo elemento de A tem exatamente uma imagem em B' },
      { id: 'B', text: 'Todo elemento de B tem pelo menos uma pré-imagem em A' },
      { id: 'C', text: 'Os conjuntos A e B possuem a mesma quantidade de elementos' },
      { id: 'D', text: 'A relação é sempre representada por uma reta no plano cartesiano' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'Qual é o domínio máximo (natural) da função f(x) = √(x – 4)?',
    tip: 'Para a raiz quadrada existir nos reais, o que está dentro dela precisa ser maior ou igual a zero. Resolva x – 4 ≥ 0.',
    funFact: 'Você sabia? A raiz quadrada de números negativos levou à criação dos números complexos, que hoje são essenciais em engenharia elétrica e física quântica.',
    points: 1,
    options: [
      { id: 'A', text: 'x ≤ 4' },
      { id: 'B', text: 'x > 4' },
      { id: 'C', text: 'x < 4' },
      { id: 'D', text: 'x ≥ 4' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'Qual é o conjunto imagem da função f(x) = x², com domínio nos números reais?',
    tip: 'Pense: o quadrado de qualquer número real pode ser negativo? Qual é o menor valor possível de x²?',
    funFact: 'Você sabia? A função f(x) = x² é a parábola mais básica e aparece em fenômenos do mundo real como a trajetória de projéteis e o formato de antenas parabólicas.',
    points: 1,
    options: [
      { id: 'A', text: 'ℝ (todos os reais)' },
      { id: 'B', text: '[0, +∞)' },
      { id: 'C', text: '(-∞, 0]' },
      { id: 'D', text: '(0, +∞)' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'Pelo teste da reta vertical, qual das afirmações abaixo é verdadeira sobre um gráfico no plano cartesiano?',
    tip: 'Se você traçar uma reta vertical e ela cortar o gráfico em mais de um ponto, a relação NÃO é função.',
    funFact: 'Você sabia? O plano cartesiano foi criado por René Descartes no século XVII. Conta a lenda que a ideia surgiu enquanto ele observava uma mosca no teto e pensou em descrever sua posição com dois números.',
    points: 1,
    options: [
      { id: 'A', text: 'Uma circunferência completa representa uma função, pois é contínua' },
      { id: 'B', text: 'Uma reta vertical representa uma função, pois é uma reta' },
      { id: 'C', text: 'Uma reta não vertical representa uma função, pois cada x tem exatamente uma imagem' },
      { id: 'D', text: 'Uma elipse representa uma função, pois é uma curva fechada' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'Uma função f: A → B é dita BIJETORA quando:',
    tip: 'Bijetora = dois atributos juntos: injetora (sem repetir imagens) E sobrejetora (atingindo todo o contradomínio).',
    funFact: 'Você sabia? Funções bijetoras são fundamentais em criptografia: elas garantem que cada mensagem criptografada corresponde a exatamente uma mensagem original, permitindo a decodificação.',
    points: 1,
    options: [
      { id: 'A', text: 'É ao mesmo tempo injetora e sobrejetora' },
      { id: 'B', text: 'Cada elemento do contradomínio tem exatamente dois pré-imagens' },
      { id: 'C', text: 'O domínio e o contradomínio são necessariamente iguais' },
      { id: 'D', text: 'A função é estritamente decrescente em todo o domínio' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'Na função afim f(x) = 3x – 5, qual é o coeficiente angular (a)?',
    tip: 'Na forma f(x) = ax + b, o coeficiente angular é o número que multiplica o x.',
    funFact: 'Você sabia? O coeficiente angular representa a taxa de variação da função. Em física, quando a função descreve posição em função do tempo, o coeficiente angular é exatamente a velocidade!',
    points: 1,
    options: [
      { id: 'A', text: '-5' },
      { id: 'B', text: '3' },
      { id: 'C', text: '5' },
      { id: 'D', text: '-3' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'Na função afim f(x) = -2x + 7, qual é o coeficiente linear (b)?',
    tip: 'Na forma f(x) = ax + b, o coeficiente linear é o termo independente, aquele que não multiplica o x.',
    funFact: 'Você sabia? O coeficiente linear indica o ponto onde a reta corta o eixo y — é o valor de f(0). Em economia, pode representar um custo fixo inicial.',
    points: 1,
    options: [
      { id: 'A', text: '-2' },
      { id: 'B', text: '2' },
      { id: 'C', text: '-7' },
      { id: 'D', text: '7' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'Qual é o zero (raiz) da função f(x) = 2x – 6?',
    tip: 'O zero da função é o valor de x para o qual f(x) = 0. Basta resolver a equação 2x – 6 = 0.',
    funFact: 'Você sabia? O zero de uma função afim é também chamado de "ponto de equilíbrio" em modelos econômicos — é quando receita e custo se igualam, por exemplo.',
    points: 1,
    options: [
      { id: 'A', text: 'x = -3' },
      { id: 'B', text: 'x = 2' },
      { id: 'C', text: 'x = 3' },
      { id: 'D', text: 'x = 6' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'Uma função afim f(x) = ax + b é crescente quando:',
    tip: 'Pense: se o coeficiente angular for positivo, a função sobe. Se for negativo, desce.',
    funFact: 'Você sabia? A relação entre o sinal do coeficiente angular e o crescimento da função é análoga à inclinação de uma rampa: inclinada para cima = positivo, inclinada para baixo = negativo.',
    points: 1,
    options: [
      { id: 'A', text: 'a > 0' },
      { id: 'B', text: 'a < 0' },
      { id: 'C', text: 'b > 0' },
      { id: 'D', text: 'b < 0' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'O gráfico de uma função afim f(x) = ax + b com coeficiente angular a < 0 é uma reta:',
    tip: 'Quando o coeficiente angular é negativo, a função perde valor conforme x aumenta — a reta "desce".',
    funFact: 'Você sabia? Em finanças, uma função com coeficiente angular negativo pode modelar a depreciação de um bem: a cada ano, o valor do bem diminui uma quantidade fixa.',
    points: 1,
    options: [
      { id: 'A', text: 'Crescente da esquerda para a direita' },
      { id: 'B', text: 'Decrescente da esquerda para a direita' },
      { id: 'C', text: 'Paralela ao eixo x' },
      { id: 'D', text: 'Paralela ao eixo y' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'Duas retas f(x) = a₁x + b₁ e g(x) = a₂x + b₂ são paralelas quando:',
    tip: 'Retas paralelas nunca se encontram. O que isso diz sobre suas inclinações? E sobre seus coeficientes lineares?',
    funFact: 'Você sabia? Na geometria euclidiana, dois retas paralelas nunca se encontram. Mas em geometrias não euclidianas, como a usada na Teoria da Relatividade de Einstein, isso não é necessariamente verdade!',
    points: 1,
    options: [
      { id: 'A', text: 'a₁ = a₂ e b₁ = b₂' },
      { id: 'B', text: 'a₁ × a₂ = -1' },
      { id: 'C', text: 'b₁ = b₂ e a₁ ≠ a₂' },
      { id: 'D', text: 'a₁ = a₂ e b₁ ≠ b₂' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'Qual é o ponto de interseção das retas f(x) = 2x + 1 e g(x) = x + 3?',
    tip: 'No ponto de interseção, os dois valores de y são iguais. Resolva: 2x + 1 = x + 3.',
    funFact: 'Você sabia? O ponto de interseção de duas retas é a solução de um sistema linear 2×2 — e sistemas lineares são usados em simulações computacionais, GPS e engenharia estrutural.',
    points: 1,
    options: [
      { id: 'A', text: '(1, 3)' },
      { id: 'B', text: '(3, 7)' },
      { id: 'C', text: '(2, 5)' },
      { id: 'D', text: '(4, 9)' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'Um táxi cobra R$ 5,00 de bandeirada (taxa fixa) mais R$ 2,50 por quilômetro rodado. Qual função representa o custo C(x) em reais para x quilômetros percorridos?',
    tip: 'Identifique: qual é o valor fixo (coeficiente linear) e qual é o valor por km (coeficiente angular)?',
    funFact: 'Você sabia? Modelos de preço por assinatura com cobrança fixa mais variável (como planos de celular ou contas de luz) são exatamente funções afins aplicadas ao cotidiano!',
    points: 1,
    options: [
      { id: 'A', text: 'C(x) = 2,5x + 5' },
      { id: 'B', text: 'C(x) = 5x + 2,5' },
      { id: 'C', text: 'C(x) = 2,5x – 5' },
      { id: 'D', text: 'C(x) = 5x – 2,5' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'Dada a função f(x) = 4x – 3, qual é o valor de f(2)?',
    tip: 'Substitua x = 2 na expressão e calcule: f(2) = 4 · 2 – 3.',
    funFact: 'Você sabia? A notação f(x) foi popularizada por Euler no século XVIII. Antes disso, os matemáticos escreviam expressões longas — f(x) foi uma simplificação revolucionária!',
    points: 1,
    options: [
      { id: 'A', text: '3' },
      { id: 'B', text: '5' },
      { id: 'C', text: '8' },
      { id: 'D', text: '11' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'Se f(x) = x + 1 e o domínio é D = {1, 2, 3}, qual é o conjunto imagem dessa função?',
    tip: 'Calcule f para cada elemento do domínio: f(1) = ?, f(2) = ?, f(3) = ?',
    funFact: 'Você sabia? Em computação, o "conjunto imagem" equivale ao conjunto de saídas possíveis de uma função (ou método). Mapear domínio e imagem ajuda a prever o que um programa pode retornar.',
    points: 1,
    options: [
      { id: 'A', text: '{0, 1, 2}' },
      { id: 'B', text: '{1, 2, 3}' },
      { id: 'C', text: '{1, 2, 3, 4}' },
      { id: 'D', text: '{2, 3, 4}' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Uma função do tipo f(x) = b, onde b é uma constante real não nula, é uma função afim com coeficiente angular:',
    tip: 'Se f(x) não depende de x, quanto varia f quando x muda? A taxa de variação é zero.',
    funFact: 'Você sabia? A função constante representa situações sem variação, como a temperatura de um ambiente com ar-condicionado regulado ou um salário fixo mensal.',
    points: 1,
    options: [
      { id: 'A', text: 'igual a zero' },
      { id: 'B', text: 'igual a 1' },
      { id: 'C', text: 'igual a b' },
      { id: 'D', text: 'indefinido' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Duas funções afins f(x) = a₁x + b₁ e g(x) = a₂x + b₂ têm gráficos perpendiculares entre si quando:',
    tip: 'Retas perpendiculares formam ângulo de 90°. Existe uma relação especial entre os coeficientes angulares de retas perpendiculares.',
    funFact: 'Você sabia? A condição de perpendicularidade a₁ · a₂ = -1 é usada em projetos de engenharia para garantir que estruturas se cruzem em ângulo reto, como paredes e vigas.',
    points: 1,
    options: [
      { id: 'A', text: 'a₁ = a₂' },
      { id: 'B', text: 'a₁ + a₂ = 0' },
      { id: 'C', text: 'a₁ × a₂ = -1' },
      { id: 'D', text: 'b₁ × b₂ = -1' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Uma função afim passa pelos pontos (0, 3) e (2, 7). Qual é a expressão dessa função?',
    tip: 'O coeficiente angular é a taxa de variação: a = (y₂ – y₁) / (x₂ – x₁). O ponto (0, 3) dá diretamente o coeficiente linear.',
    funFact: 'Você sabia? Dois pontos distintos determinam uma única reta — esse princípio é usado em topografia para mapear terrenos e em navegação para traçar rotas.',
    points: 1,
    options: [
      { id: 'A', text: 'f(x) = x + 3' },
      { id: 'B', text: 'f(x) = 2x + 3' },
      { id: 'C', text: 'f(x) = 3x + 2' },
      { id: 'D', text: 'f(x) = 2x + 7' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Uma empresa tem custo de produção dado por C(x) = 50x + 200, onde x é o número de peças produzidas. Para que o custo seja exatamente R$ 700,00, quantas peças devem ser produzidas?',
    tip: 'Iguale C(x) = 700 e resolva para x: 50x + 200 = 700.',
    funFact: 'Você sabia? Em administração de empresas, funções afins são usadas para calcular o ponto de equilíbrio — o número de produtos que iguala receita e custo, zerando o prejuízo.',
    points: 1,
    options: [
      { id: 'A', text: '5 peças' },
      { id: 'B', text: '8 peças' },
      { id: 'C', text: '12 peças' },
      { id: 'D', text: '10 peças' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Quantos subconjuntos possui o conjunto A = {a, b, c}?',
    tip: 'Um conjunto com n elementos possui 2ⁿ subconjuntos, incluindo o conjunto vazio e o próprio conjunto.',
    funFact: 'Você sabia? A fórmula 2ⁿ para subconjuntos tem relação direta com a álgebra booleana — base da lógica digital que funciona nos processadores de todos os computadores!',
    points: 1,
    options: [
      { id: 'A', text: '8' },
      { id: 'B', text: '6' },
      { id: 'C', text: '4' },
      { id: 'D', text: '3' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'O conjunto das partes (ou conjunto potência) de A = {1, 2} é:',
    tip: 'Liste todos os subconjuntos possíveis de {1, 2}: o vazio, os unitários e o próprio conjunto.',
    funFact: 'Você sabia? O conjunto das partes de qualquer conjunto finito tem sempre mais elementos do que o conjunto original — Cantor provou isso para conjuntos infinitos também, levando à ideia de "infinitos maiores que outros".',
    points: 1,
    options: [
      { id: 'A', text: '{{1}, {2}, {1, 2}}' },
      { id: 'B', text: '{{}, {1, 2}}' },
      { id: 'C', text: '{{}, {1}, {2}, {1, 2}}' },
      { id: 'D', text: '{{1}, {2}}' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Pela primeira Lei de De Morgan, o complementar de (A ∪ B) é igual a:',
    tip: 'De Morgan diz: o complementar de uma união é a interseção dos complementares. "NOT (A OR B) = (NOT A) AND (NOT B)".',
    funFact: 'Você sabia? As Leis de De Morgan são a base da simplificação de circuitos elétricos! Engenheiros as usam para transformar portas lógicas OR em AND e reduzir o número de componentes.',
    points: 1,
    options: [
      { id: 'A', text: "A' ∪ B'" },
      { id: 'B', text: "A' ∩ B'" },
      { id: 'C', text: 'A ∩ B' },
      { id: 'D', text: "A' ∪ B" },
    ],
    correctAnswer: 'B',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Se A = {1, 2} e B = {a, b}, quantos pares ordenados possui o produto cartesiano A × B?',
    tip: 'O produto cartesiano A × B tem n(A) × n(B) elementos. Cada par combina um elemento de A com um de B.',
    funFact: 'Você sabia? O produto cartesiano leva o nome de René Descartes. O plano cartesiano é um produto cartesiano entre dois conjuntos de números reais: ℝ × ℝ!',
    points: 1,
    options: [
      { id: 'A', text: '2' },
      { id: 'B', text: '3' },
      { id: 'C', text: '6' },
      { id: 'D', text: '4' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'A relação de A = {1, 2, 3} em B = {1, 4, 9} dada por f(x) = x² é uma função porque:',
    tip: 'Verifique: f(1)=1, f(2)=4, f(3)=9. Cada elemento de A tem exatamente uma imagem?',
    funFact: 'Você sabia? A função f(x) = x² é sobrejetora para o conjunto B = {1, 4, 9}, mas não seria sobrejetora se o contradomínio fosse os reais, pois há valores não atingíveis.',
    points: 1,
    options: [
      { id: 'A', text: 'Todo elemento de A tem exatamente uma imagem em B' },
      { id: 'B', text: 'Todo elemento de B tem exatamente uma pré-imagem em A' },
      { id: 'C', text: 'Os dois conjuntos possuem o mesmo número de elementos' },
      { id: 'D', text: 'A relação é representada por uma reta no plano' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'Qual é o zero (raiz) da função f(x) = –3x + 9?',
    tip: 'O zero é o valor de x onde f(x) = 0. Resolva: –3x + 9 = 0.',
    funFact: 'Você sabia? O zero de uma função é também chamado de "raiz" por analogia às raízes de uma planta — são os pontos onde a função "toca o chão" (eixo x) no gráfico.',
    points: 1,
    options: [
      { id: 'A', text: 'x = –3' },
      { id: 'B', text: 'x = –9' },
      { id: 'C', text: 'x = 3' },
      { id: 'D', text: 'x = 9' },
    ],
    correctAnswer: 'C',
  },
];
