export const questoesIngles7AnoB4Av2 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "Choose the correct form: \"She ___ a teacher.\"",
    tip: "\"She\" é terceira pessoa do singular. Qual forma do verbo \"to be\" combina com ela?",
    funFact: "Professores são fundamentais na formação de cada pessoa — eles passam, em média, mais de 180 dias por ano com seus alunos!",
    points: 1,
    options: [
      { id: "A", text: "am" },
      { id: "B", text: "are" },
      { id: "C", text: "be" },
      { id: "D", text: "is" },
    ],
    correctAnswer: "D",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "Which word means \"the opposite of big\"?",
    tip: "Pense em algo bem pequenininho. Qual palavra representa isso?",
    funFact: "A formiga é um dos animais mais \"small\" que existem, mas consegue carregar até 50 vezes o próprio peso!",
    points: 1,
    options: [
      { id: "A", text: "Tall" },
      { id: "B", text: "Small" },
      { id: "C", text: "Happy" },
      { id: "D", text: "Fast" },
    ],
    correctAnswer: "B",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "Which is the correct simple present form: \"My brother ___ breakfast every morning.\"",
    tip: "Com \"he, she, it\" no presente simples, adicionamos \"-s\" ou \"-es\" no verbo. Qual opção tem essa terminação?",
    funFact: "Café da manhã é considerado por muitos nutricionistas a refeição mais importante do dia, pois dá energia para começar bem!",
    points: 1,
    options: [
      { id: "A", text: "eats" },
      { id: "B", text: "eat" },
      { id: "C", text: "eating" },
      { id: "D", text: "ate" },
    ],
    correctAnswer: "A",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "Which food is uncountable?",
    tip: "Três dessas opções podem ser contadas uma a uma. Qual delas não dá para contar \"uma, duas, três...\"?",
    funFact: "Beber bastante \"water\" é essencial para manter o corpo e o cérebro funcionando bem!",
    points: 1,
    options: [
      { id: "A", text: "Eggs" },
      { id: "B", text: "Apples" },
      { id: "C", text: "Water" },
      { id: "D", text: "Cookies" },
    ],
    correctAnswer: "C",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "Which is the past tense of \"go\"?",
    tip: "\"Go\" é um verbo irregular, então não segue a regra do \"-ed\". Lembra da forma especial dele no passado?",
    funFact: "\"Went\" é uma das formas irregulares mais usadas em inglês — vale a pena memorizar bem!",
    points: 1,
    options: [
      { id: "A", text: "Goed" },
      { id: "B", text: "Went" },
      { id: "C", text: "Going" },
      { id: "D", text: "Goes" },
    ],
    correctAnswer: "B",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "What is the comparative form of \"big\"?",
    tip: "\"Big\" é um adjetivo curto. Para comparar duas coisas, dobramos a última letra e adicionamos \"-er\". Qual opção faz isso?",
    funFact: "A baleia azul é o animal \"bigger\" (maior) que já existiu no planeta, até maior que muitos dinossauros!",
    points: 1,
    options: [
      { id: "A", text: "Biggest" },
      { id: "B", text: "Big" },
      { id: "C", text: "More big" },
      { id: "D", text: "Bigger" },
    ],
    correctAnswer: "D",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "Which phrase is used for planned future actions?",
    tip: "As outras palavras falam do passado. Qual expressão fala sobre planos para o futuro?",
    funFact: "\"Going to\" é usado quando já existe uma decisão tomada antes de falar sobre o futuro!",
    points: 1,
    options: [
      { id: "A", text: "Did" },
      { id: "B", text: "Was" },
      { id: "C", text: "Going to" },
      { id: "D", text: "Ago" },
    ],
    correctAnswer: "C",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "Choose the correct question with \"to be\": \"___ you from Brazil?\"",
    tip: "\"You\" sempre usa a mesma forma do verbo \"to be\", seja no singular ou no plural. Qual é essa forma?",
    funFact: "O Brasil é o único país da América do Sul onde o idioma oficial é o português — todos os outros falam espanhol!",
    points: 1,
    options: [
      { id: "A", text: "Are" },
      { id: "B", text: "Is" },
      { id: "C", text: "Do" },
      { id: "D", text: "Does" },
    ],
    correctAnswer: "A",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "Which is the past tense of \"eat\"?",
    tip: "\"Eat\" é irregular. Pense: \"ontem eu já ___ o almoço\" — qual palavra combina?",
    funFact: "\"Ate\" se pronuncia parecido com \"eight\" (oito) — uma dica sonora para ajudar a lembrar!",
    points: 1,
    options: [
      { id: "A", text: "Eated" },
      { id: "B", text: "Eats" },
      { id: "C", text: "Eating" },
      { id: "D", text: "Ate" },
    ],
    correctAnswer: "D",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "Which word do we use with uncountable nouns to ask \"how much\" of something?",
    tip: "\"Much\" é a parceira das palavras incontáveis, como \"water\" e \"sugar\". Qual opção é essa palavra?",
    funFact: "\"Much\" e \"many\" parecem iguais, mas \"much\" é para incontáveis e \"many\" é para contáveis no plural!",
    points: 1,
    options: [
      { id: "A", text: "many" },
      { id: "B", text: "much" },
      { id: "C", text: "a" },
      { id: "D", text: "some" },
    ],
    correctAnswer: "B",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Complete: \"There ___ some cookies on the table.\"",
    tip: "\"Cookies\" está no plural. Qual forma do verbo combina com substantivos no plural?",
    funFact: "A expressão \"that's the way the cookie crumbles\" é um ditado famoso em inglês, parecido com \"assim é a vida\"!",
    points: 1,
    options: [
      { id: "A", text: "are" },
      { id: "B", text: "is" },
      { id: "C", text: "am" },
      { id: "D", text: "be" },
    ],
    correctAnswer: "A",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Complete: \"My grandmother's house is ___ than my house. It was built 100 years ago.\"",
    tip: "A frase compara duas casas e tem a palavra \"than\" — isso pede um comparativo. \"Old\" é curto, então usa \"-er\".",
    funFact: "Casas muito antigas, com mais de 100 anos, geralmente têm uma arquitetura bem diferente das casas modernas!",
    points: 1,
    options: [
      { id: "A", text: "old" },
      { id: "B", text: "oldest" },
      { id: "C", text: "older" },
      { id: "D", text: "more old" },
    ],
    correctAnswer: "C",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "Complete: \"Yesterday, we ___ a movie together.\"",
    tip: "\"Yesterday\" (ontem) mostra que a ação já aconteceu. \"Watch\" é regular — qual opção tem o \"-ed\" do passado?",
    funFact: "Assistir filmes em família é uma ótima forma de criar memórias e conversar sobre histórias juntos!",
    points: 1,
    options: [
      { id: "A", text: "watch" },
      { id: "B", text: "watches" },
      { id: "C", text: "watching" },
      { id: "D", text: "watched" },
    ],
    correctAnswer: "D",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "Complete: \"I ___ going to visit my cousins next weekend.\"",
    tip: "O sujeito é \"I\". Qual forma do verbo \"to be\" combina com \"I\"?",
    funFact: "Visitar primos é uma ótima forma de manter os laços de família, mesmo quando moram em cidades diferentes!",
    points: 1,
    options: [
      { id: "A", text: "is" },
      { id: "B", text: "am" },
      { id: "C", text: "are" },
      { id: "D", text: "was" },
    ],
    correctAnswer: "B",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Complete: \"How ___ sugar do you want in your tea?\"",
    tip: "\"Sugar\" é incontável. Para perguntar sobre a quantidade de algo incontável, usamos \"how much\" ou \"how many\"?",
    funFact: "No Reino Unido, tomar chá com açúcar e leite faz parte de uma tradição muito antiga e importante!",
    points: 1,
    options: [
      { id: "A", text: "many" },
      { id: "B", text: "a" },
      { id: "C", text: "much" },
      { id: "D", text: "some" },
    ],
    correctAnswer: "C",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "Choose the correct sentence.",
    tip: "\"Interesting\" é um adjetivo longo, então não recebe \"-er\" no final — usamos \"more\" antes dele, junto com \"than\".",
    funFact: "Livros interessantes ajudam a melhorar o vocabulário e estimulam a imaginação de quem lê!",
    points: 1,
    options: [
      { id: "A", text: "This book is more interesting than that one" },
      { id: "B", text: "This book is interestinger than that one" },
      { id: "C", text: "This book is most interesting than that one" },
      { id: "D", text: "This book is interesting than that one" },
    ],
    correctAnswer: "A",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "Complete: \"Of all my friends, Lucas is the ___.\"",
    tip: "\"Of all my friends\" compara com TODOS os amigos — isso pede superlativo. \"Funny\" termina em consoante + \"y\", vira \"funniest\".",
    funFact: "Rir com os amigos libera endorfina no cérebro, o \"hormônio da felicidade\"!",
    points: 1,
    options: [
      { id: "A", text: "funny" },
      { id: "B", text: "funniest" },
      { id: "C", text: "funnier" },
      { id: "D", text: "more funny" },
    ],
    correctAnswer: "B",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "Choose the correct negative sentence: \"He ___ like vegetables.\"",
    tip: "\"Like\" é um verbo de ação no presente simples, com \"he\" (terceira pessoa). Qual auxiliar negativo combina com isso?",
    funFact: "Experimentar vegetais de formas diferentes, como em sucos ou pratos coloridos, costuma ajudar quem não gosta muito deles!",
    points: 1,
    options: [
      { id: "A", text: "not" },
      { id: "B", text: "no" },
      { id: "C", text: "isn't" },
      { id: "D", text: "doesn't" },
    ],
    correctAnswer: "D",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "Complete: \"Look at those clouds! It ___ rain soon.\"",
    tip: "A frase mostra uma evidência visível (as nuvens) agora. Isso pede \"going to\", na estrutura certa com o verbo \"to be\".",
    funFact: "Nuvens escuras e carregadas geralmente indicam que uma chuva forte está chegando!",
    points: 1,
    options: [
      { id: "A", text: "is going to" },
      { id: "B", text: "will going to" },
      { id: "C", text: "rains" },
      { id: "D", text: "raining" },
    ],
    correctAnswer: "A",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "Complete: \"We ___ very happy when our team won the game.\"",
    tip: "\"We\" é plural, e a frase fala de algo no passado (o time \"won\", ganhou). Qual forma do verbo \"to be\" no passado combina com \"we\"?",
    funFact: "\"Were\" é usado com \"you, we, they\" no passado, enquanto \"was\" é usado com \"I, he, she, it\"!",
    points: 1,
    options: [
      { id: "A", text: "was" },
      { id: "B", text: "is" },
      { id: "C", text: "were" },
      { id: "D", text: "are" },
    ],
    correctAnswer: "C",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Bernardo wants to introduce himself in English. Which sentence is correct?",
    tip: "\"My name\" é uma coisa só (singular). Qual forma do verbo \"to be\" combina com isso?",
    funFact: "\"Bernardo\" é um nome de origem germânica que significa \"forte como um urso\"!",
    points: 1,
    options: [
      { id: "A", text: "My name be Bernardo" },
      { id: "B", text: "My name is Bernardo" },
      { id: "C", text: "My name are Bernardo" },
      { id: "D", text: "My name am Bernardo" },
    ],
    correctAnswer: "B",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Bernardo describes his best friend as someone who always makes people laugh. Which word fits?",
    tip: "Se o amigo faz todo mundo rir, ele é sério, quieto, triste ou divertido? Pense no significado de cada palavra.",
    funFact: "Ter amigos divertidos é ótimo para a saúde mental — rir junto fortalece amizades e diminui o estresse!",
    points: 1,
    options: [
      { id: "A", text: "Serious" },
      { id: "B", text: "Quiet" },
      { id: "C", text: "Sad" },
      { id: "D", text: "Funny" },
    ],
    correctAnswer: "D",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Every morning, Bernardo ___ his teeth before breakfast. Which word completes it?",
    tip: "\"Every morning\" mostra uma rotina (presente simples), e \"Bernardo\" é terceira pessoa do singular. Qual opção tem a terminação certa?",
    funFact: "Dentistas recomendam escovar os dentes pelo menos duas vezes por dia, por cerca de 2 minutos cada vez!",
    points: 1,
    options: [
      { id: "A", text: "brushes" },
      { id: "B", text: "brush" },
      { id: "C", text: "brushing" },
      { id: "D", text: "brushed" },
    ],
    correctAnswer: "A",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Bernardo's mom says there isn't any milk left in the fridge. Which sentence is correct?",
    tip: "Se não sobrou leite, a frase precisa ser negativa. \"Milk\" é incontável, então o verbo é \"is\", e usamos \"any\" nas negativas.",
    funFact: "O leite, depois de aberto, geralmente dura cerca de uma semana na geladeira!",
    points: 1,
    options: [
      { id: "A", text: "There is some milk" },
      { id: "B", text: "There are some milk" },
      { id: "C", text: "There isn't any milk" },
      { id: "D", text: "There is many milk" },
    ],
    correctAnswer: "C",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Last Saturday, Bernardo visited his grandparents. Which sentence is correct?",
    tip: "\"Last Saturday\" (sábado passado) mostra que isso já aconteceu. Qual frase está no passado, certinho?",
    funFact: "Visitar os avós regularmente é associado, em estudos, a crianças mais seguras emocionalmente!",
    points: 1,
    options: [
      { id: "A", text: "Bernardo visits his grandparents" },
      { id: "B", text: "Bernardo visit his grandparents" },
      { id: "C", text: "Bernardo is visiting his grandparents" },
      { id: "D", text: "Bernardo visited his grandparents" },
    ],
    correctAnswer: "D",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Bernardo is taller than his little sister. Which sentence is correct?",
    tip: "\"Tall\" é um adjetivo curto, então usa \"-er\" para comparar duas pessoas, com \"than\" depois.",
    funFact: "Crianças costumam ter \"estirões\" de crescimento principalmente durante a puberdade!",
    points: 1,
    options: [
      { id: "A", text: "Bernardo is tall than his sister" },
      { id: "B", text: "Bernardo is taller than his sister" },
      { id: "C", text: "Bernardo is more tall than his sister" },
      { id: "D", text: "Bernardo is tallest than his sister" },
    ],
    correctAnswer: "B",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Bernardo has already packed his bag for the school trip tomorrow. Which sentence shows his plan?",
    tip: "Se ele já arrumou a mochila, é um plano certo — isso combina com \"going to\", não com um \"will\" incerto como em \"maybe\".",
    funFact: "Passeios escolares ajudam a aprender de um jeito mais divertido, fora da sala de aula!",
    points: 1,
    options: [
      { id: "A", text: "Bernardo will go on a school trip, maybe" },
      { id: "B", text: "Bernardo goes on a school trip tomorrow" },
      { id: "C", text: "Bernardo is going to go on a school trip tomorrow" },
      { id: "D", text: "Bernardo went on a school trip tomorrow" },
    ],
    correctAnswer: "C",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Bernardo's friend asks him to help right now, and he quickly says, \"Don't worry, I ___ help you!\"",
    tip: "É uma decisão espontânea, tomada na hora. Isso combina com \"will\", lembra da regrinha?",
    funFact: "Ajudar os amigos rapidamente, sem pensar duas vezes, é um sinal de uma amizade forte e verdadeira!",
    points: 1,
    options: [
      { id: "A", text: "will" },
      { id: "B", text: "am going to" },
      { id: "C", text: "is going to" },
      { id: "D", text: "are going to" },
    ],
    correctAnswer: "A",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Bernardo's dog is bigger than his friend's dog. Which sentence is correct?",
    tip: "\"Big\" é curto, então dobramos a última letra e adicionamos \"-er\": \"bigger\". E a frase precisa de \"than\" para comparar dois cachorros.",
    funFact: "Algumas raças de cães, como o São Bernardo, podem pesar mais de 80 kg!",
    points: 1,
    options: [
      { id: "A", text: "Bernardo's dog is big than his friend's dog" },
      { id: "B", text: "Bernardo's dog is bigger than his friend's dog" },
      { id: "C", text: "Bernardo's dog is more big than his friend's dog" },
      { id: "D", text: "Bernardo's dog is biggest than his friend's dog" },
    ],
    correctAnswer: "B",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Bernardo's family has already planned a trip to the beach next month, with everything booked. Which sentence shows this?",
    tip: "Viagem já planejada e reservada = plano certo, decidido com antecedência. Isso pede \"going to\", não \"will\" nem passado.",
    funFact: "O Brasil tem mais de 8 mil km de litoral — são praias de sobra para explorar nas próximas férias!",
    points: 1,
    options: [
      { id: "A", text: "We will go to the beach" },
      { id: "B", text: "We go to the beach" },
      { id: "C", text: "We went to the beach" },
      { id: "D", text: "We are going to go to the beach" },
    ],
    correctAnswer: "D",
  },
];
