export const questoesHistoria9AnoB4Av2 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "O movimento 'DIRETAS JÁ' (1983–1984) foi um dos maiores da história política brasileira. O que foi e qual foi seu resultado imediato?",
    tip: "Milhões foram às ruas — a emenda foi votada e o que aconteceu no Congresso?",
    funFact: "\"Você Sabia?\" — O maior comício das Diretas Já foi em São Paulo, no Vale do Anhangabaú, em 16 de abril de 1984: 1,7 milhão de pessoas. A Rede Globo noticiou como 'show de Roberto Carlos'. A emenda Dante de Oliveira foi derrotada por 22 votos na Câmara (precisava de 2/3 para passar). Tancredo Neves disse: 'A emenda foi derrotada, mas não o povo.' O movimento criou a pressão que levou os dissidentes do PDS a votar com a oposição no Colégio Eleitoral — e elegeu Tancredo.",
    points: 1,
    options: [
      { id: "A", text: "O movimento 'Diretas Já' (1983–84) mobilizou milhões de brasileiros por eleições presidenciais diretas. A emenda Dante de Oliveira foi derrotada no Congresso por 22 votos (faltou 2/3), mas o movimento gerou pressão suficiente para eleger Tancredo Neves indiretamente." },
      { id: "B", text: "O movimento 'Diretas Já' era pró-ditadura — exigia eleições controladas pelo regime militar." },
      { id: "C", text: "O movimento 'Diretas Já' ocorreu em 1989 — e resultou diretamente na eleição direta de Tancredo Neves." },
      { id: "D", text: "O movimento 'Diretas Já' foi organizado pelos militares para controlar a transição democrática." },
    ],
    correctAnswer: "A",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "A ELEIÇÃO INDIRETA de Tancredo Neves pelo Colégio Eleitoral (1985). Como ele foi eleito?",
    tip: "Tancredo era do PMDB, o regime apoiava Paulo Maluf — como a oposição conseguiu vencer pelo Colégio Eleitoral?",
    funFact: "\"Você Sabia?\" — Paulo Maluf era o candidato do PDS (partido do regime). Mas uma dissidência interna do PDS — liderada por José Sarney e Marco Maciel — formou a 'Frente Liberal' (que depois virou PFL, hoje DEM) e se aliou ao PMDB para lançar Tancredo. Com essa aliança, Tancredo tinha votos para vencer no Colégio Eleitoral. A ironia: o Colégio Eleitoral — criado pela ditadura para garantir que ela nunca perdesse — foi o instrumento de sua derrota.",
    points: 1,
    options: [
      { id: "A", text: "Tancredo Neves foi eleito por voto direto popular — o povo foi às urnas em 1985 para escolhê-lo." },
      { id: "B", text: "José Sarney foi o primeiro presidente civil eleito diretamente após a ditadura." },
      { id: "C", text: "Tancredo Neves (PMDB) foi eleito pelo Colégio Eleitoral em janeiro de 1985 — primeira vitória civil em 21 anos — com apoio de dissidentes do PDS (a 'Frente Liberal'). Derrotou Paulo Maluf, candidato do regime." },
      { id: "D", text: "Tancredo Neves foi eleito em 1985 e cumpriu todo o seu mandato de 5 anos normalmente." },
    ],
    correctAnswer: "C",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "A MORTE DE TANCREDO NEVES e a posse de Sarney. O que aconteceu na véspera da posse?",
    tip: "O homem que todo o Brasil esperava que inaugurasse a Nova República nunca chegou a ser empossado — por quê?",
    funFact: "\"Você Sabia?\" — Tancredo entrou no Hospital de Base de Brasília às 23h do dia 14 de março de 1985 — véspera da posse. Passou por 7 cirurgias em 38 dias. Morreu em 21 de abril de 1985 — curiosamente o Dia de Tiradentes, símbolo da liberdade. Sarney, que havia sido presidente do PDS (partido da ditadura), tornava-se o primeiro presidente da Nova República. O Brasil voltou à democracia com uma tragédia como marca fundante.",
    points: 1,
    options: [
      { id: "A", text: "Tancredo foi empossado normalmente e completou seu mandato — transferindo o poder para Sarney em eleições diretas." },
      { id: "B", text: "Tancredo adoeceu na véspera da posse (diverticulite intestinal), passou por 7 cirurgias e morreu em 21 de abril de 1985 sem nunca ter sido empossado. O vice José Sarney assumiu a presidência — ex-senador do PDS, o partido da ditadura." },
      { id: "C", text: "Sarney foi eleito diretamente numa eleição convocada após Tancredo ficar incapacitado." },
      { id: "D", text: "Os militares impediram a posse de Sarney e convocaram novas eleições para 1985." },
    ],
    correctAnswer: "B",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "A ASSEMBLEIA NACIONAL CONSTITUINTE (1987–1988) e a Constituição Cidadã. O que foi e como foi feita?",
    tip: "Quem participou da escrita da Constituição de 1988 e o que a tornou diferente das constituições anteriores?",
    funFact: "\"Você Sabia?\" — A Constituinte de 1987-88 recebeu 72.000 sugestões populares através de emendas populares — cada uma precisava de 30.000 assinaturas. Os movimentos sociais mais ativos: MST (reforma agrária), sindicalistas (UGT, CUT), movimento negro, feministas, indígenas, pessoas com deficiência. Ulysses Guimarães, presidente da Constituinte, disse ao promulgar a Constituição: 'Declaro promulgada o documento da liberdade, da democrança e da justiça do Brasil.' A Constituição de 1988 é o documento mais longo e participativo da história constitucional brasileira.",
    points: 1,
    options: [
      { id: "A", text: "A Constituição foi redigida por um pequeno comitê de juristas, sem participação popular — igual às anteriores." },
      { id: "B", text: "A Constituição de 1988 foi escrita pelos militares como condição para entregar o poder aos civis." },
      { id: "C", text: "A Constituição de 1988 manteve a mesma estrutura institucional da Constituição militar de 1967." },
      { id: "D", text: "A Assembleia Nacional Constituinte (1987–88) foi uma das mais participativas da história — 72.000 emendas populares. Criou direitos sociais (SUS, educação), trabalhistas (FGTS, férias remuneradas) e ambientais. Ulysses Guimarães a chamou de 'Constituição Cidadã'." },
    ],
    correctAnswer: "D",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "A CONSTITUIÇÃO CIDADÃ DE 1988 — seus principais avanços e limitações.",
    tip: "O que a Constituição de 1988 garantiu que nenhuma anterior havia garantido?",
    funFact: "\"Você Sabia?\" — A Constituição de 1988 proibiu explicitamente a tortura (art. 5º, inciso III: 'Ninguém será submetido à tortura'). É irônico: a Constituição que substituiu a ditadura que torturou sistematicamente tornou-se a primeira a proibir a tortura. Mas os torturadores jamais foram julgados — porque a Lei da Anistia (1979), anterior à Constituição, prevaleceu. A 'Constituição Cidadã' nasceu com o pecado original da impunidade dos carrascos.",
    points: 1,
    options: [
      { id: "A", text: "A 'Constituição Cidadã' (1988) criou o SUS (saúde universal), educação pública gratuita, voto a partir de 16 anos (inclusive analfabetos), jornada de 44h semanais, 13.º salário, férias remuneradas. Mas preservou prerrogativas militares e não julgou os torturadores da ditadura." },
      { id: "B", text: "A Constituição de 1988 não adicionou nenhum direito social novo — manteve os direitos da Constituição militar de 1967." },
      { id: "C", text: "A Constituição de 1988 foi rejeitada em referendo popular e nunca entrou em vigor no Brasil." },
      { id: "D", text: "A Constituição de 1988 foi escrita pelos militares para garantir a impunidade da ditadura." },
    ],
    correctAnswer: "A",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "O governo COLLOR DE MELLO (1990–1992) — o Plano Collor e o confisco das poupanças.",
    tip: "Como Collor tentou acabar com a hiperinflação — e por que seu plano chocou a população?",
    funFact: "\"Você Sabia?\" — O confisco do Plano Collor bloqueou as poupanças por 18 meses. Quem tinha dinheiro no banco acordou no dia 16 de março de 1990 sem acesso a seus recursos. Casos dramáticos: dentistas que não conseguiam pagar aluguel, famílias que não tinham como comprar comida, donos de pequenas empresas que faliu sem poder pagar salários. Uma senhora passou mal ao ouvir a notícia e morreu de infarto. O Plano Collor foi o maior confisco de poupança privada da história do Brasil.",
    points: 1,
    options: [
      { id: "A", text: "Collor foi o último presidente militar do Brasil, não foi eleito diretamente." },
      { id: "B", text: "Collor implementou o Plano Real, que acabou definitivamente com a hiperinflação." },
      { id: "C", text: "Collor (1990–92), o primeiro presidente eleito diretamente desde 1960, lançou o Plano Collor: confiscou poupanças acima de 50 mil cruzados por 18 meses para reduzir liquidez monetária e controlar a inflação. Gerou recessão e foi alvo de impeachment em 1992 por corrupção." },
      { id: "D", text: "Collor foi um presidente progressista que ampliou os direitos trabalhistas e reduziu a desigualdade." },
    ],
    correctAnswer: "C",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "O IMPEACHMENT DE COLLOR (1992) — o primeiro na história do Brasil. Como aconteceu?",
    tip: "Qual escândalo derrubou Collor, e o que os 'caras-pintadas' tinham a ver com isso?",
    funFact: "\"Você Sabia?\" — Collor renunciou no dia 29 de dezembro de 1992 às 9h32 da manhã, quando o Senado já estava em sessão de impeachment. Mesmo assim, o Senado continuou a votação e por 73 votos a 8 declarou-o 'inidôneo' — proibindo-o de exercer qualquer função pública por 8 anos. Décadas depois, Collor voltou: foi eleito senador de Alagoas. Em 2022, concorreu à presidência e perdeu para Lula. A história brasileira é marcada por retornos improvados.",
    points: 1,
    options: [
      { id: "A", text: "Collor completou seu mandato e foi reeleito em 1994." },
      { id: "B", text: "Collor renunciou antes do impeachment para manter sua imunidade parlamentar." },
      { id: "C", text: "Collor foi removido por um golpe militar que também destituiu o vice-presidente Itamar Franco." },
      { id: "D", text: "Em 1992, o irmão de Collor revelou o esquema PC Farias. Os estudantes 'caras-pintadas' foram às ruas. A Câmara aprovou o impeachment (setembro/1992). Collor renunciou na véspera da votação no Senado — que mesmo assim o declarou 'inidôneo' por 8 anos. Itamar Franco assumiu." },
    ],
    correctAnswer: "D",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "O PLANO REAL (1994) — como Fernando Henrique Cardoso acabou com a hiperinflação.",
    tip: "O que foi a URV e por que a transição gradual funcionou quando outros planos de choque fracassaram?",
    funFact: "\"Você Sabia?\" — Em 1993, o Brasil tinha inflação de 2.700% ao ano. O Plano Real foi criado pelos economistas da PUC-Rio ('a bíblia da equipe econômica era Keynes, não Milton Friedman') — André Lara Resende, Pérsio Arida, Edmar Bacha. A chave: a URV (Unidade Real de Valor), uma moeda virtual usada por 4 meses para 'desindexar' a economia. Quando o Real foi lançado em 1.º de julho de 1994, já estava estável — porque as pessoas já haviam se adaptado à nova referência de preços.",
    points: 1,
    options: [
      { id: "A", text: "O Plano Real fracassou — o Brasil só controlou a inflação em 2003 com o governo Lula." },
      { id: "B", text: "O Plano Real (1994) criou a URV como moeda de transição para desindexar a economia, depois lançou o Real lastreado no dólar. A inflação caiu de 2.700% (1993) para menos de 10% (1995). FHC foi eleito presidente em outubro de 1994 impulsionado pelo sucesso do plano." },
      { id: "C", text: "O Plano Real foi criado pelo governo Lula em 2003 como parte do ajuste fiscal." },
      { id: "D", text: "O Plano Real foi um fracasso que agravou a hiperinflação no Brasil." },
    ],
    correctAnswer: "B",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "Os dois mandatos de FERNANDO HENRIQUE CARDOSO (FHC, 1995–2002). O que marcou seu governo?",
    tip: "FHC foi o presidente da estabilidade monetária — mas que reformas estruturais ele fez e a que custo?",
    funFact: "\"Você Sabia?\" — FHC aprovou a emenda da reeleição em 1997 após denúncias de compra de votos de parlamentares. O caso do 'palanquinho' (dinheiro trocado entre congressistas para votar a favor da reeleição) nunca foi completamente apurado. A ironia: FHC, o intelectual da 'Teoria da Dependência' (que criticou o capitalismo internacional nos anos 1960), tornou-se o presidente das privatizações e do Consenso de Washington. Seu livro 'Dependência e Desenvolvimento na América Latina' (1969) entrou em contradição com suas próprias políticas econômicas.",
    points: 1,
    options: [
      { id: "A", text: "FHC (1995–2002): privatizações (Telebrás, Vale), agências reguladoras (ANATEL, ANS), Lei de Responsabilidade Fiscal (2000), Bolsa Escola. Aprovação da emenda da reeleição (1997). Crise cambial de 1999 (desvalorização do Real). Dois mandatos de estabilidade macro mas crescimento modesto e dívida pública crescente." },
      { id: "B", text: "FHC reverteu todas as privatizações de Collor e reestatizou as empresas brasileiras." },
      { id: "C", text: "FHC foi destituído em 1999 por corrupção ligada à desvalorização do Real." },
      { id: "D", text: "FHC foi eleito pelo Colégio Eleitoral — nunca venceu uma eleição direta no Brasil." },
    ],
    correctAnswer: "A",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "A ELEIÇÃO DE LULA em 2002 — por que foi considerada historicamente importante?",
    tip: "Por que a eleição de um ex-metalúrgico sem ensino fundamental completo à presidência do Brasil foi um marco?",
    funFact: "\"Você Sabia?\" — A 'Carta ao Povo Brasileiro' (junho de 2002) foi escrita para acalmar o mercado financeiro, que temia uma ruptura caso Lula ganhasse. O dólar subia toda vez que as pesquisas mostravam Lula na frente. Lula comprometeu-se a honrar contratos e manter o superávit primário — rompendo com o discurso de sua própria história como líder sindical radical dos anos 1980. 'Carta ao Povo Brasileiro' foi escrita por Antonio Palocci e acompanhada por José Dirceu. O mercado se acalmou e Lula ganhou.",
    points: 1,
    options: [
      { id: "A", text: "Lula foi eleito em 1994 como o primeiro candidato do PT à presidência." },
      { id: "B", text: "A eleição de Lula em 2002 foi fraudada — ele não ganhou realmente de José Serra." },
      { id: "C", text: "Lula (2002) venceu em sua 4.ª candidatura presidencial (1989, 1994, 1998, 2002). Metalúrgico sem ensino fundamental, foi o símbolo da ascensão da classe trabalhadora. A 'Carta ao Povo Brasileiro' comprometeu-se com a responsabilidade fiscal, tranquilizando os mercados. Ganhou com 61% no 2.º turno." },
      { id: "D", text: "Lula foi nomeado à presidência pelo Supremo Tribunal Federal após a cassação de FHC." },
    ],
    correctAnswer: "C",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "A QUEDA DO MURO DE BERLIM (novembro de 1989). Como aconteceu?",
    tip: "O que levou a população da Alemanha Oriental às ruas e como o muro caiu sem um único tiro?",
    funFact: "\"Você Sabia?\" — A queda do Muro começou com um erro de comunicação ao vivo. O porta-voz do governo da Alemanha Oriental, Günter Schabowski, leu uma nota confusa numa coletiva de imprensa e, quando perguntado 'a partir de quando?', respondeu: 'Imediatamente, sem demora.' Ele não sabia que a medida deveria entrar em vigor no dia seguinte. A notícia se espalhou em minutos — multidões foram aos postos de controle, os guardas não tinham ordens, e o Muro começou a cair. O fim do símbolo da Guerra Fria foi decidido por um funcionário mal-informado.",
    points: 1,
    options: [
      { id: "A", text: "O Muro de Berlim caiu após um ataque militar da Alemanha Ocidental apoiado pela OTAN." },
      { id: "B", text: "Em 9 de novembro de 1989, manifestações populares massivas na Alemanha Oriental e um anúncio confuso do governo levaram multidões aos postos de fronteira — os guardas recuaram e o Muro foi demolido. Símbolo do fim da Guerra Fria e da divisão europeia." },
      { id: "C", text: "O Muro de Berlim caiu em 1991 simultaneamente com a dissolução da União Soviética." },
      { id: "D", text: "O Muro de Berlim foi demolido pelas forças da OTAN após um ultimato nuclear americano." },
    ],
    correctAnswer: "B",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "A DISSOLUÇÃO DA URSS (dezembro de 1991). Como o maior país do mundo deixou de existir?",
    tip: "O que causou o fim da União Soviética — uma derrota militar, uma revolução, ou algo mais complexo?",
    funFact: "\"Você Sabia?\" — Em 25 de dezembro de 1991, Mikhail Gorbachev renunciou e a bandeira vermelha do Kremlin foi abaixada pela última vez. No dia seguinte, o Soviét Supremo votou pela dissolução formal da URSS. Nos dias anteriores, Boris Yeltsin havia tomado as instalações do governo soviético em Moscou — era o Estado russo subindo a rampa enquanto o Estado soviético descia. A dissolução foi única na história: um dos maiores impérios da humanidade desapareceu em 74 anos de existência sem uma guerra de independência.",
    points: 1,
    options: [
      { id: "A", text: "A URSS foi dissolvida por um golpe militar que levou Putin ao poder em 1991." },
      { id: "B", text: "A URSS se dissolveu em 1989, simultaneamente com a queda do Muro de Berlim." },
      { id: "C", text: "A URSS foi dissolvida após uma invasão militar americana autorizada pela ONU." },
      { id: "D", text: "Em dezembro de 1991, após a tentativa de golpe contra Gorbachev (agosto/1991) e a independência em cascata das repúblicas soviéticas, Gorbachev renunciou. Rússia, Ucrânia e Bielorrússia assinaram os Acordos de Beloveza dissolvendo formalmente a URSS — que simplesmente deixou de existir." },
    ],
    correctAnswer: "D",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "O mundo pós-Guerra Fria — a 'NOVA ORDEM MUNDIAL' e o 'momento unipolar' americano.",
    tip: "Com o fim da URSS, qual foi a nova configuração geopolítica do mundo nos anos 1990?",
    funFact: "\"Você Sabia?\" — O jornalista Charles Krauthammer cunhou o termo 'momento unipolar' para descrever os anos 1990. Os EUA respondiam a 75% do orçamento da ONU, tinham 50% dos gastos militares mundiais e o maior PIB por grande margem. Mas o 'momento unipolar' durou apenas até 2001 — quando os atentados de 11/9 mostraram que o poder absoluto não protegia de ataques assimétricos. A ascensão da China como potência econômica e a recuperação da Rússia com Putin encerrariam definitivamente a unipolaridade americana.",
    points: 1,
    options: [
      { id: "A", text: "Com o fim da Guerra Fria, os EUA declararam uma 'Nova Ordem Mundial' de liderança unipolar. Testada pela Guerra do Golfo (Iraque invadiu Kuwait, 1990): Bush pai liderou uma coalizão internacional que expulsou Saddam em 1991. Os EUA emergiram como única superpotência — o 'momento unipolar'." },
      { id: "B", text: "Após a Guerra Fria, a Rússia substituiu a URSS como potência dominante e os EUA ficaram em segundo lugar." },
      { id: "C", text: "Após a Guerra Fria, a China emergiu imediatamente como substituta da URSS no equilíbrio de poder." },
      { id: "D", text: "Após a Guerra Fria, a ONU assumiu o papel de autoridade política dominante no mundo." },
    ],
    correctAnswer: "A",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "A GLOBALIZAÇÃO dos anos 1990. O que foi e quais foram seus impactos?",
    tip: "Como a integração global dos anos 1990 mudou o comércio, as finanças e as culturas ao redor do mundo?",
    funFact: "\"Você Sabia?\" — Em 1995, o Brasil tinha 1,4 milhão de usuários de internet. Em 2000, tinha 9 milhões. Em 2010, tinha 73 milhões. A velocidade da globalização digital foi ímpar: as comunicações que antes levavam semanas agora chegavam em segundos. O e-mail matou a carta. O Orkut matou o caderno de endereços. O Napster matou a música em CD. O Google matou a enciclopédia. Tudo em menos de 20 anos. A globalização não foi apenas econômica — foi uma revolução cultural sem precedentes.",
    points: 1,
    options: [
      { id: "A", text: "A globalização foi um fenômeno apenas cultural, sem implicações econômicas ou políticas." },
      { id: "B", text: "A globalização reduziu as desigualdades entre países ricos e pobres nas décadas de 1990 e 2000." },
      { id: "C", text: "A globalização dos anos 1990: revolução digital (internet, computadores pessoais), integração financeira, abertura comercial (OMC criada em 1995), multinacionais, 'Consenso de Washington'. Ganhos para consumidores (produtos importados mais baratos), perdas para trabalhadores industriais de países em desenvolvimento." },
      { id: "D", text: "A globalização foi rejeitada por todos os países em desenvolvimento, que criaram blocos alternativos." },
    ],
    correctAnswer: "C",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "O CONSENSO DE WASHINGTON (1989) e as reformas neoliberais na América Latina. O que prescrevia?",
    tip: "Quais medidas o FMI e o Banco Mundial recomendavam para os países latino-americanos nos anos 1990?",
    funFact: "\"Você Sabia?\" — O economista John Williamson cunhou o termo 'Consenso de Washington' em 1989, mas depois reclamou que o termo havia sido distorcido: ele queria descrever um consenso técnico, não uma ideologia. O Consenso nunca foi tão consensual quanto o nome sugere — economistas heterodoxos como Stiglitz (Nobel 2001) criticaram sistematicamente suas prescrições. O Consenso virou símbolo do neoliberalismo porque foi implementado de forma rígida pelo FMI em crises: Argentina (2001), Ásia (1997), México (1994) — e em todos os casos gerou recessão e desigualdade.",
    points: 1,
    options: [
      { id: "A", text: "O Consenso de Washington prescrevia desenvolvimento liderado pelo Estado e protecionismo industrial." },
      { id: "B", text: "O Consenso de Washington (1989): privatizações de estatais, austeridade fiscal, abertura comercial, desregulação financeira, abertura ao capital estrangeiro. Orientou reformas do FMI e Banco Mundial. No Brasil, influenciou as privatizações de FHC. Criou crescimento em alguns casos, mas aumentou desigualdade em outros." },
      { id: "C", text: "O Consenso de Washington aumentou o investimento público em educação e saúde na América Latina." },
      { id: "D", text: "O Consenso de Washington foi criado pela URSS como modelo alternativo de desenvolvimento ao capitalismo americano." },
    ],
    correctAnswer: "B",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "Os ATENTADOS DE 11 DE SETEMBRO DE 2001 (11/9). O que aconteceu e qual foi a escala do ataque?",
    tip: "Quem foram os responsáveis pelos ataques e qual foi o impacto imediato no mundo?",
    funFact: "\"Você Sabia?\" — O World Trade Center foi atingido duas vezes: às 8h46 (Torre Norte) e às 9h03 (Torre Sul). Mais de 1 bilhão de pessoas assistiu ao vivo pela TV ao segundo avião bater na Torre Sul. As Torres colapsaram em menos de 2 horas — às 9h59 (Torre Sul) e às 10h28 (Torre Norte). Um terceiro avião atingiu o Pentágono. Um quarto caiu num campo na Pensilvânia depois que passageiros tentaram retomar o controle ('Let's roll', disse o passageiro Todd Beamer). 2.996 mortos no total.",
    points: 1,
    options: [
      { id: "A", text: "Os atentados de 11/9 foram executados pelo Iraque sob ordem de Saddam Hussein." },
      { id: "B", text: "Os atentados de 11/9 foram um acidente causado por falhas técnicas no controle aéreo americano." },
      { id: "C", text: "Os atentados de 11/9 foram organizados pela CIA para justificar a invasão do Iraque." },
      { id: "D", text: "Em 11 de setembro de 2001, 19 membros da Al-Qaeda (15 sauditas) sequestraram 4 aviões: dois atingiram as Torres Gêmeas do World Trade Center (Nova York), um o Pentágono e um caiu na Pensilvânia. 2.996 mortos. O maior ataque terrorista da história transformou a segurança global e as relações internacionais." },
    ],
    correctAnswer: "D",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "A RESPOSTA AMERICANA ao 11/9 — as guerras do Afeganistão (2001) e do Iraque (2003).",
    tip: "Com que justificativas os EUA invadiram o Afeganistão e o Iraque — e quais foram os resultados?",
    funFact: "\"Você Sabia?\" — O secretário de Estado Colin Powell apresentou ao Conselho de Segurança da ONU, em fevereiro de 2003, 'provas' das armas de destruição em massa do Iraque: fotos de satélite de supostos caminhões de armas biológicas. Tudo era falso. Powell disse anos depois que aquele discurso foi 'uma mancha na sua reputação'. Nem o Iraque tinha armas de destruição em massa, nem havia ligação com o 11/9. A invasão do Iraque foi a maior mentira geopolítica desde o incidente do Golfo de Tonkin (Vietnã, 1964).",
    points: 1,
    options: [
      { id: "A", text: "Os EUA responderam ao 11/9 com uma iniciativa puramente diplomática na ONU." },
      { id: "B", text: "Os EUA responderam ao 11/9 invadindo a Arábia Saudita, de onde vieram a maioria dos sequestradores." },
      { id: "C", text: "O governo Bush (filho) invadiu o Afeganistão (outubro/2001) para destruir a Al-Qaeda e o Talibã; depois invadiu o Iraque (março/2003) alegando 'armas de destruição em massa' — que nunca existiram. A 'Guerra ao Terror' durou décadas, custou US$3 trilhões e centenas de milhares de vidas." },
      { id: "D", text: "Os EUA não fizeram nada após o 11/9 para não criar mais terrorismo — Bush se recusou a retaliar." },
    ],
    correctAnswer: "C",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "O LEGADO das guerras do Afeganistão e do Iraque para os Estados Unidos e o mundo.",
    tip: "O que as guerras pós-11/9 custaram e o que deixaram como herança geopolítica?",
    funFact: "\"Você Sabia?\" — O general David Petraeus, que liderou a 'Surge' no Iraque (2007), disse ao jornalista Joe Klein: 'Me diga como isso acaba?' Ele não tinha resposta. Ninguém tinha. Os EUA gastaram US$2,2 trilhões no Iraque. Em 2021, o Talibã voltou ao poder no Afeganistão em 11 dias — após 20 anos de ocupação americana e US$2 trilhões gastos na reconstrução. O Afeganistão ficou exatamente como estava antes da invasão. O maior poder militar da história humana não conseguiu impedir que homens de sandálias retomassem um país montanhoso.",
    points: 1,
    options: [
      { id: "A", text: "As guerras do Afeganistão e do Iraque (2001–2021/2011) custaram US$3 trilhões, mais de 7.000 mortes americanas e estimados 800.000 mortos (incluindo civis). O Iraque não tinha armas de destruição em massa. O 'Patriot Act' restringiu liberdades civis nos EUA. O Talibã voltou ao poder em 2021 — 20 anos depois." },
      { id: "B", text: "As guerras do Afeganistão e do Iraque foram rápidas e baratas, transformando ambos os países em democracias estáveis." },
      { id: "C", text: "A Guerra do Iraque foi um sucesso completo — o Iraque tornou-se uma democracia modelo imediatamente após a invasão." },
      { id: "D", text: "Os EUA saíram de ambas as guerras em 2003 após atingir todos os objetivos militares." },
    ],
    correctAnswer: "A",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "O governo LULA (2003–2010) e seus resultados sociais. O que mudou no Brasil?",
    tip: "Qual foi o impacto do governo Lula na redução da pobreza e na posição internacional do Brasil?",
    funFact: "\"Você Sabia?\" — Em 2010, o coeficiente de Gini do Brasil (que mede a desigualdade: 0 = igualdade total, 1 = desigualdade máxima) caiu de 0,59 (2002) para 0,53 — a menor desigualdade desde que o Brasil começou a medir. 40 milhões de brasileiros saíram da pobreza durante os governos Lula e Dilma (2003–2014). O Brasil foi incluído no grupo dos BRICs (Brasil, Rússia, Índia, China) e tornou-se a 6.ª maior economia do mundo. Lula deixou o cargo com 87% de aprovação — o presidente mais popular da história brasileira.",
    points: 1,
    options: [
      { id: "A", text: "O governo Lula cortou os programas sociais para equilibrar as contas públicas." },
      { id: "B", text: "O governo Lula (2003–2010): Bolsa Família (40 milhões de pessoas), Fome Zero, FIES, PROUNI, aumento real do salário mínimo, Minha Casa Minha Vida, descoberta do pré-sal (2007). Brasil passou de 10.ª para 6.ª maior economia. Gini caiu. Lula saiu com 87% de aprovação." },
      { id: "C", text: "O governo Lula foi marcado por crescimento econômico zero e aumento da pobreza." },
      { id: "D", text: "O governo Lula foi derrubado em 2007 por um golpe militar financiado pelos Estados Unidos." },
    ],
    correctAnswer: "B",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "O FIM DA GUERRA FRIA e o 'fim da história' — o que o politólogo Francis Fukuyama previu e o que aconteceu?",
    tip: "Fukuyama disse que a democracia liberal havia vencido definitivamente — sua tese se confirmou?",
    funFact: "\"Você Sabia?\" — Francis Fukuyama publicou 'O Fim da História e o Último Homem' em 1992. Em 2022, com a invasão russa da Ucrânia, ele publicou um artigo dizendo que a Ucrânia estava provando que o liberalismo não estava morto — mas que a luta ainda não tinha acabado. A ironia: o 'fim da história' foi publicado exatamente quando a história estava esquentando — genocídio em Ruanda (1994), dissolução da Iugoslávia, ascensão do fundamentalismo islâmico, ressurgimento do autoritarismo. O mundo pós-Guerra Fria foi muito mais turbulento do que Fukuyama previa.",
    points: 1,
    options: [
      { id: "A", text: "O fim da Guerra Fria provou que o comunismo era superior ao capitalismo — acabou com o capitalismo ocidental." },
      { id: "B", text: "O fim da Guerra Fria criou um mundo perfeitamente pacífico e estável — guerras nunca mais ocorreram." },
      { id: "C", text: "O fim da Guerra Fria foi irrelevante para países em desenvolvimento como o Brasil." },
      { id: "D", text: "Fukuyama previu o 'fim da história' (democracia liberal como vencedora final), mas o pós-Guerra Fria trouxe: conflitos étnicos (Iugoslávia, Ruanda 1994), ressurgência nacionalista (Rússia/Putin), Estados falidos, 11/9 e ascensão da China. O 'momento unipolar' americano foi breve." },
    ],
    correctAnswer: "D",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "A REDEMOCRATIZAÇÃO do Brasil — foi uma ruptura com a ditadura ou uma transição negociada?",
    tip: "O Brasil passou de ditadura para democracia da mesma forma que a Argentina, que julgou seus generais?",
    funFact: "\"Você Sabia?\" — O general Ernesto Geisel, ao iniciar a abertura em 1974, disse que deveria ser 'lenta, gradual e segura' — segura para quem? Para o regime. Cada passo foi calculado para preservar os interesses militares. A Argentina prendeu e julgou sua Junta Militar em 1985. O Chile julgou Pinochet (antes de sua morte). O Brasil nunca julgou seus torturadores. Em 2014, a CNV publicou seu relatório — mas sem nenhuma consequência legal para os responsáveis identificados.",
    points: 1,
    options: [
      { id: "A", text: "A redemocratização do Brasil foi imposta pelos Estados Unidos como condição para novos empréstimos." },
      { id: "B", text: "A redemocratização foi uma ruptura revolucionária — os militares foram julgados e condenados como na Argentina." },
      { id: "C", text: "A transição brasileira foi 'controlada': o regime ditou o ritmo ('lenta, gradual e segura'), criou a Lei da Anistia protegendo torturadores e manteve prerrogativas militares. Diferente da Argentina (que julgou seus generais), o Brasil teve uma 'transição negociada' — com pecados originais que persistem." },
      { id: "D", text: "A redemocratização do Brasil aconteceu da noite para o dia em 1985, sem nenhum processo anterior." },
    ],
    correctAnswer: "C",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "As ELEIÇÕES DIRETAS DE 1989 — a primeira eleição presidencial direta desde 1960. O que revelaram?",
    tip: "Quem foram os candidatos do 2.º turno e o que o resultado disse sobre a polarização da sociedade brasileira?",
    funFact: "\"Você Sabia?\" — A edição do debate final entre Collor e Lula pelo Jornal Nacional da Globo em 14 de dezembro de 1989 foi manipulada: a Globo escolheu mostrar o melhor momento de Collor e o pior de Lula. O diretor de jornalismo Armando Nogueira renunciou por discordar da edição. Décadas depois, o filho de Roberto Marinho, Roberto Irineu Marinho, pediu desculpas publicamente pela cobertura. Collor ganhou por 5 pontos percentuais (53% vs. 47%). Historiadores debatem se a edição da Globo teria sido suficiente para virar o resultado.",
    points: 1,
    options: [
      { id: "A", text: "A eleição de 1989 revelou profunda polarização de classe: Collor (jovem, telegênico, 'caçador de marajás') venceu Lula por 53% a 47%. A Globo editou o debate final de forma favorável a Collor. Primeiro presidente eleito diretamente desde Jânio Quadros (1960)." },
      { id: "B", text: "A eleição de 1989 foi vencida por Lula — sua primeira de quatro eleições presidenciais." },
      { id: "C", text: "A eleição de 1989 foi boicotada pelo PT e PMDB — apenas o candidato militar concorreu." },
      { id: "D", text: "A eleição de 1989 foi cancelada por causa da hiperinflação — Collor foi indicado pelo Congresso." },
    ],
    correctAnswer: "A",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "A INTERNET e a revolução digital dos anos 1990 no Brasil. Como a tecnologia mudou a sociedade brasileira?",
    tip: "Quando o Brasil adotou a internet e qual foi o impacto nas primeiras décadas?",
    funFact: "\"Você Sabia?\" — O Orkut foi lançado em 2004 e o Brasil se tornou rapidamente seu maior mercado — com 50% dos usuários sendo brasileiros. O Google comprou o Orkut em 2004 e o fechou em 2014. No lugar do Orkut veio o Facebook (2010-2015), depois o WhatsApp (comprado pelo Facebook em 2014), depois o Instagram. Cada plataforma transformou a comunicação brasileira de um jeito diferente. O WhatsApp tornou-se central na política brasileira — em 2018, grupos de WhatsApp foram usados para espalhar desinformação na eleição presidencial.",
    points: 1,
    options: [
      { id: "A", text: "O Brasil adotou a internet apenas nos anos 2010 — chegou décadas depois dos países desenvolvidos." },
      { id: "B", text: "O Brasil lançou sua internet comercial em 1995. A expansão foi veloz: e-commerce, Orkut (maior mercado global), bancos digitais. O Brasil tornou-se um dos maiores mercados digitais do mundo. A revolução digital transformou comércio, comunicação e, eventualmente, a política (redes sociais e desinformação)." },
      { id: "C", text: "O Brasil nunca desenvolveu uma infraestrutura de internet significativa." },
      { id: "D", text: "O Brasil foi o primeiro país do mundo a adotar a internet comercial, em 1993, antes dos EUA." },
    ],
    correctAnswer: "B",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "O PLANO REAL e a estabilidade macroeconômica do Brasil pós-1994. Quais foram seus custos e legados?",
    tip: "O Real controlou a inflação mas a que custo — e quais foram as consequências de longo prazo?",
    funFact: "\"Você Sabia?\" — A âncora cambial do Real (manter o real próximo ao dólar) atraiu capital estrangeiro — mas criou um problema: as exportações ficaram caras e as importações baratas. O Brasil importou tudo, de camisetas a carros, destruindo a indústria têxtil e parte da manufatura. Em 1999, quando a crise asiática e russa exigiu a desvalorização, o real caiu 50% em dias. O 'custo' de manter a paridade cambial era uma taxa SELIC de 45% ao ano — que asfixiava a economia real e engordava a dívida pública. A estabilidade veio com um preço que o Brasil pagaria por décadas.",
    points: 1,
    options: [
      { id: "A", text: "O Plano Real falhou em controlar a inflação — o Brasil só teve estabilidade com o governo Lula." },
      { id: "B", text: "O Plano Real foi criado pelo governo Lula em 2003 como parte de seu ajuste fiscal." },
      { id: "C", text: "O Plano Real foi imposto pelo FMI como condição para um empréstimo emergencial." },
      { id: "D", text: "O Real (1994) acabou com a hiperinflação de forma permanente — mas ao custo de juros altíssimos (SELIC de 45%), câmbio sobrevalorizado que prejudicou a indústria e dívida pública crescente. A desvalorização de 1999 foi necessária mas mostrou a fragilidade do modelo. O legado foi a estabilidade sem crescimento robusto." },
    ],
    correctAnswer: "D",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "O MERCOSUL (1991) e a integração regional da América do Sul. O que foi criado?",
    tip: "Quais países fundaram o Mercosul e qual foi o objetivo dessa integração regional?",
    funFact: "\"Você Sabia?\" — O Mercosul foi criado exatamente quando Argentina e Brasil superavam décadas de rivalidade histórica. Getúlio Vargas e Perón eram líderes populistas rivais que nunca se entenderam. Castelo Branco e os militares argentinos colaboraram na Operação Condor. A democracia dos anos 1980 mudou isso: Sarney e Alfonsín (presidente da Argentina) assinaram o Tratado de Integração em 1988. O Mercosul foi filho da democracia — e da percepção de que integração era mais forte que competição.",
    points: 1,
    options: [
      { id: "A", text: "O Mercosul foi criado após a Guerra Fria como um bloco anti-americano." },
      { id: "B", text: "O Mercosul foi criado pelas ditaduras militares da América do Sul." },
      { id: "C", text: "O Tratado de Assunção (1991) criou o Mercosul — mercado comum entre Brasil, Argentina, Uruguai e Paraguai. O comércio intra-Mercosul triplicou nos anos 1990. Criou uma união aduaneira, facilitou a circulação de pessoas e foi plataforma para a integração sul-americana." },
      { id: "D", text: "O Mercosul foi dissolvido em 1995 após uma disputa comercial entre Argentina e Brasil." },
    ],
    correctAnswer: "C",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "A DITADURA MILITAR BRASILEIRA no contexto latino-americano — a Operação Condor.",
    tip: "Como as ditaduras sul-americanas cooperavam para eliminar opositores que haviam fugido para outros países?",
    funFact: "\"Você Sabia?\" — Um dos casos mais documentados da participação brasileira na Operação Condor foi o de Luís Faustino Salgado Müller, guerrilheiro brasileiro capturado em Buenos Aires em 1978 com ajuda dos serviços de inteligência brasileiros e argentinos. Ele foi torturado na Argentina e depois devolvido ao Brasil, onde 'desapareceu'. A Comissão Nacional da Verdade documentou 20 casos de brasileiros mortos no exterior em operações coordenadas com outros países — com participação do SNI (Serviço Nacional de Informações) brasileiro.",
    points: 1,
    options: [
      { id: "A", text: "A Operação Condor (1975–1985) foi uma rede de repressão transnacional coordenada pelos EUA entre as ditaduras sul-americanas (Brasil, Argentina, Chile, Uruguai, Paraguai, Bolívia) para caçar e eliminar opositores além das fronteiras. O Brasil participou ativamente através do SNI." },
      { id: "B", text: "O Brasil nunca participou da Operação Condor — só os países com ditaduras mais violentas que a brasileira." },
      { id: "C", text: "A Operação Condor foi um acordo de integração progressista entre democracias sul-americanas." },
      { id: "D", text: "O Brasil foi o único país sul-americano sem ditadura militar nos anos 1970." },
    ],
    correctAnswer: "A",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "A TRANSIÇÃO DEMOCRÁTICA BRASILEIRA em perspectiva comparada. O que a diferencia das outras?",
    tip: "Como a transição brasileira se compara com a argentina, a chilena e outras transições latino-americanas?",
    funFact: "\"Você Sabia?\" — O Tribunal de Nuremberg (1946) estabeleceu o princípio de que 'ordens superiores' não são uma defesa válida para crimes contra a humanidade. A Argentina aplicou esse princípio quando condenou os membros da Junta Militar em 1985. O Brasil nunca o aplicou — citando a Lei de Anistia de 1979. Em 2021, a Comissão Interamericana de Direitos Humanos reafirmou que o Brasil violava o direito internacional ao não punir os torturadores. A 'transição por cima' deixou uma ferida que o Brasil ainda não cicatrizou.",
    points: 1,
    options: [
      { id: "A", text: "A transição brasileira foi completamente bem-sucedida — sem nenhum resíduo de autoritarismo." },
      { id: "B", text: "A transição brasileira fracassou — os militares voltaram ao poder em 1990." },
      { id: "C", text: "A transição brasileira foi a mais rápida da América Latina — de ditadura a democracia plena em 6 meses." },
      { id: "D", text: "A transição brasileira (1974–1985) foi a mais longa da América Latina. Ao contrário da Argentina (que julgou generais) e do Chile (que teve referendo), o Brasil teve abertura 'de cima para baixo', Lei de Anistia protegendo torturadores e CNV apenas em 2012 — sem consequências legais para os responsáveis identificados." },
    ],
    correctAnswer: "D",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "A QUESTÃO AMBIENTAL global — a Rio-92 e o Protocolo de Kyoto (1997).",
    tip: "O que a Rio-92 produziu e por que a Amazônia colocou o Brasil no centro das negociações climáticas?",
    funFact: "\"Você Sabia?\" — A Conferência Rio-92 produziu o documento 'Agenda 21' — um plano global de desenvolvimento sustentável para o século XXI. Cada município brasileiro foi convidado a criar sua própria 'Agenda 21 local'. Chico Mendes, seringueiro e ativista ambiental assassinado em 1988, tornou-se símbolo internacional da luta ambiental na Amazônia. Sua morte às vésperas da Rio-92 internacionalizou o debate sobre o desmatamento. A floresta amazônica armazena 150–200 bilhões de toneladas de carbono — mais do que o mundo emite em décadas.",
    points: 1,
    options: [
      { id: "A", text: "A Rio-92 foi uma conferência econômica sem agenda ambiental." },
      { id: "B", text: "A Rio-92 (1992, no Rio de Janeiro) produziu: Agenda 21, Convenção sobre Diversidade Biológica, Convenção-Quadro sobre Mudanças Climáticas (precursora do Protocolo de Kyoto e do Acordo de Paris). Reuniu 172 países. O Protocolo de Kyoto (1997) estabeleceu metas vinculantes de redução de emissões." },
      { id: "C", text: "O Brasil se recusou a participar da Rio-92 por considerar que violava a soberania sobre a Amazônia." },
      { id: "D", text: "O Protocolo de Kyoto foi assinado por todos os países, incluindo os EUA, sem exceção." },
    ],
    correctAnswer: "B",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "A GLOBALIZAÇÃO e seus críticos — o movimento antglobalização e o Fórum Social Mundial.",
    tip: "Quem criticou a globalização neoliberal dos anos 1990 e quais foram os argumentos?",
    funFact: "\"Você Sabia?\" — Porto Alegre sediou os primeiros Fóruns Sociais Mundiais (2001, 2002, 2003). O slogan 'Um outro mundo é possível' tornou-se o grito de resistência de ONGs, movimentos sociais, sindicatos e partidos de esquerda do mundo todo. O FSM foi criado como alternativa ao Fórum Econômico Mundial de Davos (o encontro anual dos bilionários e líderes mundiais na neve suíça). A escolha do Brasil não foi acidental: o PT governava Porto Alegre desde 1988 e a cidade era símbolo do 'orçamento participativo' — democracia direta nas finanças municipais.",
    points: 1,
    options: [
      { id: "A", text: "A globalização foi universalmente aplaudida por todos os países e movimentos sociais sem nenhuma crítica." },
      { id: "B", text: "Apenas os países comunistas se opuseram à globalização." },
      { id: "C", text: "O movimento antiglobalização (protestos em Seattle/1999, Fórum Social Mundial de Porto Alegre/2001: 'Um outro mundo é possível') criticou: aumento da desigualdade, erosão da soberania nacional, crises financeiras globalizadas (Ásia 1997-98), destruição de culturas locais e danos ambientais." },
      { id: "D", text: "Não houve nenhuma oposição significativa à globalização — todos a apoiavam sem crítica." },
    ],
    correctAnswer: "C",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "O BRASIL NO SÉCULO XXI — democracia consolidada ou democracia em risco?",
    tip: "Após a redemocratização, o Brasil construiu uma democracia sólida ou ainda enfrenta desafios fundamentais?",
    funFact: "\"Você Sabia?\" — O Brasil tem o único sistema de votação eletrônica do mundo sem recibo impresso de confirmação para o eleitor. Em 2022, Bolsonaro questionou a urna eletrônica — sem apresentar nenhuma prova de fraude. Três ministros militares saíram do governo após se recusarem a assinar um documento que questionava o sistema eleitoral. O TSE convidou 60 países para auditar o sistema — todos atestaram sua segurança. A urna eletrônica, paradoxalmente, tornou-se símbolo tanto da solidez democrática brasileira quanto de sua fragilidade política.",
    points: 1,
    options: [
      { id: "A", text: "A democracia brasileira no século XXI demonstra consolidação (transferências pacíficas de poder, eleições confiáveis) mas enfrenta desafios: corrupção (Mensalão, Lava Jato), polarização política, desigualdade persistente e ameaças ao Estado Democrático de Direito — mostrando que democracia é construção contínua." },
      { id: "B", text: "O Brasil tornou-se uma ditadura militar novamente em 2013 por causa das manifestações de junho." },
      { id: "C", text: "O Brasil nunca completou sua consolidação democrática — permanece um país em transição." },
      { id: "D", text: "Todos os desafios democráticos do Brasil foram resolvidos durante o governo Lula até 2010." },
    ],
    correctAnswer: "A",
  },
];
