export const questoesCiencias7AnoB1Av2 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'A água presente no ar, em forma de vapor (gás), é chamada de:',
    tip: 'Pense na água que fica "invisível" no ar, misturada aos outros gases da atmosfera.',
    funFact: 'É por causa da umidade do ar que, em dias muito úmidos, nossa roupa demora mais para secar no varal!',
    points: 1,
    options: [
      { id: 'A', text: 'Chuva' },
      { id: 'B', text: 'Orvalho' },
      { id: 'C', text: 'Umidade do ar' },
      { id: 'D', text: 'Granizo' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'O processo em que a água líquida se transforma em vapor de água é chamado de:',
    tip: 'Pense em uma poça de água no sol, desaparecendo aos poucos — para onde ela vai?',
    funFact: 'A evaporação acontece mais rápido em dias quentes porque o calor dá energia para as moléculas de água "escaparem" para o ar!',
    points: 1,
    options: [
      { id: 'A', text: 'Evaporação' },
      { id: 'B', text: 'Condensação' },
      { id: 'C', text: 'Solidificação' },
      { id: 'D', text: 'Fusão' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'O processo em que o vapor de água se transforma em gotículas líquidas, formando nuvens, é chamado de:',
    tip: 'É o processo oposto da evaporação — o vapor "volta" a ser água líquida.',
    funFact: 'Esse mesmo processo acontece no vidro embaçado do carro em dias frios!',
    points: 1,
    options: [
      { id: 'A', text: 'Evaporação' },
      { id: 'B', text: 'Fusão' },
      { id: 'C', text: 'Sublimação' },
      { id: 'D', text: 'Condensação' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'As nuvens são formadas por:',
    tip: 'Pense no que acontece quando o vapor de água esfria lá no alto do céu.',
    funFact: 'Uma nuvem comum pode conter milhões de gotículas de água minúsculas flutuando no ar!',
    points: 1,
    options: [
      { id: 'A', text: 'Fumaça de fábricas' },
      { id: 'B', text: 'Pequenas gotículas de água ou cristais de gelo' },
      { id: 'C', text: 'Poeira apenas' },
      { id: 'D', text: 'Gás oxigênio puro' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'Quando as gotículas de água das nuvens ficam grandes e pesadas demais, elas caem na forma de:',
    tip: 'Pense no que acontece quando você não consegue mais segurar algo pesado — ele cai!',
    funFact: 'Esse processo de "cair das nuvens" tem um nome técnico: precipitação!',
    points: 1,
    options: [
      { id: 'A', text: 'Vento' },
      { id: 'B', text: 'Vapor' },
      { id: 'C', text: 'Chuva' },
      { id: 'D', text: 'Nuvem sólida' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'Em dias muito frios, a chuva pode se transformar em pequenos cristais de gelo, formando a:',
    tip: 'Pense no fenômeno típico de países muito frios, onde tudo fica branco no inverno.',
    funFact: 'No Brasil, a neve é rara e só costuma aparecer em algumas cidades da Serra Gaúcha e de Santa Catarina!',
    points: 1,
    options: [
      { id: 'A', text: 'Neve' },
      { id: 'B', text: 'Lava' },
      { id: 'C', text: 'Maré' },
      { id: 'D', text: 'Umidade' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'Pedras de gelo que caem durante tempestades fortes são chamadas de:',
    tip: 'Diferente da neve (flocos leves), esse fenômeno forma pedrinhas de gelo mais duras.',
    funFact: 'O granizo pode até causar prejuízos, amassando carros e destruindo plantações!',
    points: 1,
    options: [
      { id: 'A', text: 'Neve' },
      { id: 'B', text: 'Granizo' },
      { id: 'C', text: 'Orvalho' },
      { id: 'D', text: 'Geada' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'As pequenas gotas de água que se formam sobre as folhas e gramados de manhã cedo, por causa da condensação durante a noite, são chamadas de:',
    tip: 'Esse fenômeno acontece sem chover — é só o vapor do ar condensando na superfície fria das plantas.',
    funFact: 'O orvalho é mais comum em noites claras e frias, quando a temperatura cai bastante!',
    points: 1,
    options: [
      { id: 'A', text: 'Chuva' },
      { id: 'B', text: 'Granizo' },
      { id: 'C', text: 'Neve' },
      { id: 'D', text: 'Orvalho' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'O conjunto de fenômenos atmosféricos (chuva, vento, temperatura) que ocorre em um determinado lugar, em um curto período de tempo, é chamado de:',
    tip: 'Pense na previsão que você vê na TV todo dia — ela fala sobre hoje ou amanhã, não sobre anos inteiros.',
    funFact: '"Tempo" e "clima" parecem a mesma coisa, mas são diferentes — e essa diferença cai bastante em provas!',
    points: 1,
    options: [
      { id: 'A', text: 'Clima' },
      { id: 'B', text: 'Relevo' },
      { id: 'C', text: 'Tempo (meteorológico)' },
      { id: 'D', text: 'Hidrografia' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'O padrão de temperatura, chuva e vento de uma região, observado ao longo de muitos anos, é chamado de:',
    tip: 'Pense em uma característica mais "permanente" de um lugar, como dizer que a Amazônia é uma região quente e chuvosa.',
    funFact: 'É o clima de uma região que determina, por exemplo, quais plantas e animais conseguem viver ali!',
    points: 1,
    options: [
      { id: 'A', text: 'Clima' },
      { id: 'B', text: 'Tempo (meteorológico)' },
      { id: 'C', text: 'Relevo' },
      { id: 'D', text: 'Vegetação' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'O ciclo da água é o processo contínuo de movimentação da água entre a atmosfera, a superfície terrestre e os oceanos. Qual é a primeira etapa desse ciclo, em que a água dos rios, lagos e mares vira vapor?',
    tip: 'É o mesmo processo que você estudou na segunda questão desse simulado!',
    funFact: 'O Sol é o verdadeiro "motor" do ciclo da água — sem calor, não haveria evaporação!',
    points: 1,
    options: [
      { id: 'A', text: 'Condensação' },
      { id: 'B', text: 'Precipitação' },
      { id: 'C', text: 'Infiltração' },
      { id: 'D', text: 'Evaporação' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'Depois da evaporação, o vapor de água sobe e esfria, formando as nuvens. Essa etapa é chamada de:',
    tip: 'É a mesma etapa que forma as nuvens, estudada no começo desse simulado.',
    funFact: 'Esse ciclo se repete sem parar há bilhões de anos na Terra!',
    points: 1,
    options: [
      { id: 'A', text: 'Evaporação' },
      { id: 'B', text: 'Condensação' },
      { id: 'C', text: 'Precipitação' },
      { id: 'D', text: 'Transpiração' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'Quando a água cai das nuvens em forma de chuva, neve ou granizo, essa etapa do ciclo da água é chamada de:',
    tip: 'Pense na "queda" da água das nuvens — essa é a etapa final visível do ciclo.',
    funFact: 'Depois da precipitação, a água pode infiltrar no solo, escoar para os rios ou ser absorvida pelas plantas!',
    points: 1,
    options: [
      { id: 'A', text: 'Evaporação' },
      { id: 'B', text: 'Condensação' },
      { id: 'C', text: 'Precipitação' },
      { id: 'D', text: 'Sublimação' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'Além da evaporação da água de rios e mares, as plantas também liberam vapor de água para o ar através de um processo chamado:',
    tip: 'É parecido com o suor dos animais, mas feito pelas plantas através das folhas!',
    funFact: 'Uma única árvore grande pode liberar centenas de litros de água para o ar em um único dia, através da transpiração!',
    points: 1,
    options: [
      { id: 'A', text: 'Transpiração (das plantas)' },
      { id: 'B', text: 'Fotossíntese' },
      { id: 'C', text: 'Germinação' },
      { id: 'D', text: 'Polinização' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'O calor do Sol é a principal fonte de energia que impulsiona o ciclo da água porque ele:',
    tip: 'Pense na primeira etapa do ciclo da água — o que o calor do Sol provoca na água dos rios e mares?',
    funFact: 'Sem o Sol, o ciclo da água simplesmente pararia de funcionar!',
    points: 1,
    options: [
      { id: 'A', text: 'Esfria os oceanos' },
      { id: 'B', text: 'Produz chuva diretamente' },
      { id: 'C', text: 'Forma vento apenas' },
      { id: 'D', text: 'Faz a água evaporar' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'Em uma região de clima tropical úmido, como grande parte do Brasil, é comum observar:',
    tip: 'Pense no clima da maior parte do território brasileiro — é um clima quente, com bastante chuva em certas épocas.',
    funFact: 'A Floresta Amazônica, por exemplo, recebe uma quantidade enorme de chuva ao longo do ano!',
    points: 1,
    options: [
      { id: 'A', text: 'Neve frequente' },
      { id: 'B', text: 'Chuvas abundantes e temperaturas altas' },
      { id: 'C', text: 'Gelo o ano todo' },
      { id: 'D', text: 'Ausência total de chuva' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'A umidade relativa do ar indica:',
    tip: 'Pense em uma porcentagem — como se fosse "quão cheio" de vapor de água o ar está, perto do seu limite.',
    funFact: 'Quando a umidade relativa chega perto de 100%, é bem provável que vá chover em breve!',
    points: 1,
    options: [
      { id: 'A', text: 'A quantidade de vapor de água presente no ar, em relação ao máximo que ele poderia conter' },
      { id: 'B', text: 'A temperatura exata do dia' },
      { id: 'C', text: 'A velocidade do vento' },
      { id: 'D', text: 'A quantidade de poluição no ar' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'Em dias de baixa umidade do ar, é comum sentirmos:',
    tip: 'Pense em como fica seu corpo e a natureza ao redor quando o ar está "seco", sem quase nenhuma umidade.',
    funFact: 'Em dias de umidade muito baixa, os órgãos de saúde recomendam beber bastante água e evitar atividades físicas intensas!',
    points: 1,
    options: [
      { id: 'A', text: 'Muito frio sempre' },
      { id: 'B', text: 'Chuva forte imediatamente' },
      { id: 'C', text: 'Boca seca, pele ressecada e maior risco de incêndios' },
      { id: 'D', text: 'Nenhuma diferença' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'As nuvens muito escuras e carregadas, que costumam anunciar chuva forte e trovoadas, são chamadas de:',
    tip: 'Esse é um dos tipos de nuvem mais estudados em ciências, famoso por formar tempestades.',
    funFact: 'Os cumulonimbos podem crescer até mais de 10 quilômetros de altura no céu!',
    points: 1,
    options: [
      { id: 'A', text: 'Cirros' },
      { id: 'B', text: 'Nuvens de poeira' },
      { id: 'C', text: 'Nuvens de verão' },
      { id: 'D', text: 'Cumulonimbos' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'Quando a temperatura do ar está muito baixa, a água que cai das nuvens pode congelar e virar:',
    tip: 'Pense no fenômeno que cobre o chão de branco em países muito frios durante o inverno.',
    funFact: 'Cada floco de neve tem um formato único — nunca existem dois exatamente iguais!',
    points: 1,
    options: [
      { id: 'A', text: 'Granizo somente' },
      { id: 'B', text: 'Neve' },
      { id: 'C', text: 'Vapor' },
      { id: 'D', text: 'Orvalho' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Bernardo observou que, num dia quente, a poça de água no quintal foi diminuindo até sumir. Isso aconteceu por causa da:',
    tip: 'A água da poça não "sumiu" de verdade — ela virou vapor e foi para o ar!',
    funFact: 'Esse é o mesmo processo que seca roupas no varal e faz piscinas perderem um pouco de água com o tempo!',
    points: 1,
    options: [
      { id: 'A', text: 'Evaporação' },
      { id: 'B', text: 'Precipitação' },
      { id: 'C', text: 'Condensação' },
      { id: 'D', text: 'Neve' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Bernardo percebeu que o copo com suco gelado ficou "suado" por fora, com gotinhas de água. Isso acontece porque o vapor de água do ar perto do copo esfriou e virou líquido, num processo chamado de:',
    tip: 'É o mesmo processo que forma as nuvens, só que acontecendo na lateral de um copo gelado!',
    funFact: 'Essas gotinhas no copo não "vazaram" de dentro dele — elas vêm do próprio vapor de água do ar!',
    points: 1,
    options: [
      { id: 'A', text: 'Evaporação' },
      { id: 'B', text: 'Precipitação' },
      { id: 'C', text: 'Condensação' },
      { id: 'D', text: 'Sublimação' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Bernardo viu no telejornal que vai chover bastante no fim de semana. Essa previsão fala sobre o ______ daquele dia específico, e não sobre o clima da região em geral.',
    tip: 'Previsões do telejornal são sempre sobre um dia ou período curto específico.',
    funFact: 'É por isso que a previsão do tempo muda todos os dias, mas o clima de uma região muda muito devagar, ao longo de muitos anos!',
    points: 1,
    options: [
      { id: 'A', text: 'Clima' },
      { id: 'B', text: 'Tempo (meteorológico)' },
      { id: 'C', text: 'Relevo' },
      { id: 'D', text: 'Solo' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Bernardo e sua família ficaram presos em casa durante uma tempestade com pedras de gelo caindo do céu. Esse fenômeno é chamado de:',
    tip: 'Lembre da diferença: neve são flocos leves, mas esse fenômeno forma pedrinhas de gelo duras.',
    funFact: 'O granizo se forma dentro de nuvens cumulonimbos, as mesmas que causam fortes tempestades!',
    points: 1,
    options: [
      { id: 'A', text: 'Neve' },
      { id: 'B', text: 'Orvalho' },
      { id: 'C', text: 'Chuva fina' },
      { id: 'D', text: 'Granizo' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Bernardo aprendeu na escola que a água do mar evapora, forma nuvens, cai como chuva, e volta para os rios e mares. Esse processo contínuo é chamado de:',
    tip: 'É o nome do processo completo que você estudou neste simulado, com todas as suas etapas.',
    funFact: 'Esse ciclo garante que a água do planeta nunca "acabe" — ela só muda de lugar e de estado!',
    points: 1,
    options: [
      { id: 'A', text: 'Ciclo da água' },
      { id: 'B', text: 'Ciclo do carbono' },
      { id: 'C', text: 'Fotossíntese' },
      { id: 'D', text: 'Efeito estufa' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Bernardo notou que, pela manhã, a grama do jardim estava molhada mesmo sem ter chovido durante a noite. Isso aconteceu por causa do:',
    tip: 'Esse fenômeno acontece quando o vapor de água do ar condensa diretamente nas superfícies frias, sem precisar chover.',
    funFact: 'O orvalho é mais comum em noites sem nuvens, porque o calor escapa mais fácil para o espaço, esfriando o chão!',
    points: 1,
    options: [
      { id: 'A', text: 'Granizo' },
      { id: 'B', text: 'Vento forte' },
      { id: 'C', text: 'Orvalho' },
      { id: 'D', text: 'Degelo' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Bernardo mediu a umidade do ar com um instrumento na aula de ciências e descobriu que, naquele dia, o ar estava bem seco. Isso significa que havia ______ vapor de água no ar.',
    tip: '"Ar seco" é justamente o contrário de "ar úmido" — pense na quantidade de vapor de água presente.',
    funFact: 'O instrumento que mede a umidade do ar se chama higrômetro!',
    points: 1,
    options: [
      { id: 'A', text: 'Muito' },
      { id: 'B', text: 'Nenhum' },
      { id: 'C', text: 'Igual quantidade de sempre' },
      { id: 'D', text: 'Pouco' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Bernardo viu no céu uma nuvem bem escura e carregada, e logo depois começou uma forte tempestade com trovões. Esse tipo de nuvem é chamada de:',
    tip: 'É o mesmo tipo de nuvem que você estudou antes, famosa por formar tempestades fortes.',
    funFact: 'Essas nuvens também são responsáveis por boa parte dos raios e trovões que vemos durante tempestades!',
    points: 1,
    options: [
      { id: 'A', text: 'Cirro' },
      { id: 'B', text: 'Cumulonimbo' },
      { id: 'C', text: 'Nuvem de poeira' },
      { id: 'D', text: 'Nuvem artificial' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Bernardo aprendeu que o calor do Sol é essencial para o ciclo da água porque é ele que faz a água dos rios e oceanos:',
    tip: 'Pense na primeira etapa do ciclo da água, que você já revisou várias vezes nesse simulado.',
    funFact: 'Mesmo em dias nublados, a evaporação continua acontecendo, só que de forma mais lenta!',
    points: 1,
    options: [
      { id: 'A', text: 'Evaporar e virar vapor' },
      { id: 'B', text: 'Congelar imediatamente' },
      { id: 'C', text: 'Ficar parada' },
      { id: 'D', text: 'Virar gelo o tempo todo' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'No fim da aula, Bernardo resumiu para a mãe: as nuvens se formam quando o vapor de água esfria e vira gotículas (condensação); quando essas gotículas ficam pesadas, caem na forma de:',
    tip: 'É a última etapa do ciclo da água — quando a água finalmente "volta" para a superfície da Terra.',
    funFact: 'Parabéns, Bernardo! Agora você entende todo o caminho da água: evaporação, condensação e precipitação — um ciclo sem fim que mantém a vida no planeta!',
    points: 1,
    options: [
      { id: 'A', text: 'Vento' },
      { id: 'B', text: 'Vapor' },
      { id: 'C', text: 'Chuva (precipitação)' },
      { id: 'D', text: 'Umidade' },
    ],
    correctAnswer: 'C',
  },
];
