export const questoesArte6AnoB3Av1 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'A arte grega antiga é muito conhecida por suas:',
    tip: 'Pensa nas estátuas de heróis, deuses e atletas gregos, com músculos bem definidos.',
    funFact: 'Muitas estátuas gregas famosas ainda são estudadas hoje como referência de proporção e beleza!',
    points: 1,
    options: [
      { id: 'A', text: 'Esculturas realistas do corpo humano' },
      { id: 'B', text: 'Pinturas rupestres' },
      { id: 'C', text: 'Máscaras funerárias de ouro' },
      { id: 'D', text: 'Pirâmides' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'Os templos gregos, como o Partenon, eram construídos principalmente para:',
    tip: 'Pensa nos deuses gregos que você estudou em História — os templos eram dedicados a eles.',
    funFact: 'O Partenon ainda existe hoje, em Atenas, mesmo depois de milhares de anos!',
    points: 1,
    options: [
      { id: 'A', text: 'Servir de moradia para os cidadãos' },
      { id: 'B', text: 'Guardar alimentos' },
      { id: 'C', text: 'Homenagear os deuses da mitologia grega' },
      { id: 'D', text: 'Servir de escola' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'As colunas usadas na arquitetura grega são um elemento marcante e ainda inspiram construções:',
    tip: 'Pensa em prédios importantes, como museus e tribunais, que às vezes têm colunas parecidas.',
    funFact: 'Muitos prédios governamentais ao redor do mundo usam colunas inspiradas no estilo grego!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas na Grécia' },
      { id: 'B', text: 'Até os dias de hoje, em vários países' },
      { id: 'C', text: 'Somente no Egito' },
      { id: 'D', text: 'Somente no Brasil' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'Um tipo de arte muito comum na Grécia Antiga era a pintura em vasos de cerâmica, retratando:',
    tip: 'Pensa em tudo que era importante para os gregos: mitos, esportes e a vida cotidiana.',
    funFact: 'Muitos vasos gregos antigos sobreviveram até hoje e estão em museus ao redor do mundo!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas números' },
      { id: 'B', text: 'Apenas paisagens modernas' },
      { id: 'C', text: 'Fotografias' },
      { id: 'D', text: 'Cenas de mitologia, esportes e do dia a dia' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'As esculturas gregas antigas buscavam representar o corpo humano de forma:',
    tip: 'Pensa em como os gregos valorizavam a beleza e a proporção do corpo humano em suas esculturas.',
    funFact: 'Os gregos estudavam matemática para calcular as proporções ideais do corpo nas esculturas!',
    points: 1,
    options: [
      { id: 'A', text: 'Bastante realista e equilibrada' },
      { id: 'B', text: 'Totalmente abstrata' },
      { id: 'C', text: 'Apenas com formas geométricas simples' },
      { id: 'D', text: 'Sem nenhuma proporção' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'O Partenon é um famoso templo grego dedicado à deusa:',
    tip: 'Pensa na deusa protetora da cidade de Atenas — o templo tem um nome parecido com ela.',
    funFact: 'A cidade de Atenas recebeu esse nome justamente em homenagem a essa deusa!',
    points: 1,
    options: [
      { id: 'A', text: 'Afrodite' },
      { id: 'B', text: 'Hera' },
      { id: 'C', text: 'Ártemis' },
      { id: 'D', text: 'Atena' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'As esculturas gregas frequentemente representavam:',
    tip: 'Pensa em quem os gregos mais admiravam e queriam homenagear com suas obras de arte.',
    funFact: 'Muitas dessas esculturas representavam vencedores dos Jogos Olímpicos da Antiguidade!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas animais domésticos' },
      { id: 'B', text: 'Apenas objetos do cotidiano' },
      { id: 'C', text: 'Deuses, heróis e atletas' },
      { id: 'D', text: 'Apenas paisagens' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'O teatro grego, além de linguagem cênica, também influenciou muito a:',
    tip: 'Pensa nos grandes espaços ao ar livre construídos para as peças de teatro gregas.',
    funFact: 'Alguns anfiteatros gregos antigos ainda são usados para apresentações até hoje!',
    points: 1,
    options: [
      { id: 'A', text: 'Culinária' },
      { id: 'B', text: 'Arquitetura, com a construção de grandes anfiteatros' },
      { id: 'C', text: 'Escrita cuneiforme' },
      { id: 'D', text: 'Pintura rupestre' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'Diferente da arte egípcia, que representava figuras de perfil, a escultura grega buscava representar o corpo:',
    tip: 'Pensa na diferença entre uma pintura egípcia (sempre de perfil) e uma escultura grega mais realista.',
    funFact: 'Algumas esculturas gregas parecem estar quase "vivas", de tão naturais e em movimento!',
    points: 1,
    options: [
      { id: 'A', text: 'De forma mais natural e em movimento' },
      { id: 'B', text: 'Sempre de perfil, como no Egito' },
      { id: 'C', text: 'Sempre de costas' },
      { id: 'D', text: 'De forma totalmente abstrata' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'A cerâmica grega, com desenhos detalhados, servia tanto para fins:',
    tip: 'Pensa que os vasos gregos, além de bonitos, também serviam para guardar coisas do dia a dia, como azeite e vinho.',
    funFact: 'A cerâmica grega é uma das principais fontes que temos hoje para entender o dia a dia daquela época!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas religiosos' },
      { id: 'B', text: 'Apenas militares' },
      { id: 'C', text: 'Utilitários (guardar líquidos e alimentos) e artísticos' },
      { id: 'D', text: 'Apenas medicinais' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'Se um artista grego esculpisse uma estátua de um atleta, ele provavelmente buscaria mostrar:',
    tip: 'Volta na questão 5 e 9 sobre o naturalismo e a proporção nas esculturas gregas.',
    funFact: 'Muitas dessas estátuas de atletas eram feitas para homenagear vencedores dos Jogos Olímpicos!',
    points: 1,
    options: [
      { id: 'A', text: 'Um corpo totalmente desproporcional' },
      { id: 'B', text: 'Apenas a cabeça, sem o restante do corpo' },
      { id: 'C', text: 'Uma figura sem nenhum movimento' },
      { id: 'D', text: 'O corpo com músculos bem definidos e em uma pose equilibrada, quase em movimento' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'Por que os templos gregos, como o Partenon, usavam tantas colunas?',
    tip: 'Pensa que as colunas serviam tanto para sustentar o telhado quanto para deixar o templo mais bonito.',
    funFact: 'Existem diferentes estilos de colunas gregas, como as dóricas, jônicas e coríntias!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque eram baratas de fazer' },
      { id: 'B', text: 'Porque ajudavam a sustentar a estrutura e também tinham valor estético' },
      { id: 'C', text: 'Porque não tinham outra função além de decorar' },
      { id: 'D', text: 'Porque substituíam as paredes completamente, sem função estrutural' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'Comparando a escultura grega com a egípcia, qual é uma diferença importante?',
    tip: 'Pensa no estilo egípcio (rosto de perfil, corpo rígido) e compare com o estilo grego mais natural.',
    funFact: 'Essa diferença mostra como cada civilização tinha sua própria visão de arte e beleza!',
    points: 1,
    options: [
      { id: 'A', text: 'A escultura grega buscava mais naturalismo e movimento, enquanto a egípcia era mais rígida e frontal' },
      { id: 'B', text: 'As duas são idênticas em tudo' },
      { id: 'C', text: 'A egípcia é mais moderna' },
      { id: 'D', text: 'A grega nunca representava pessoas' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'Se um vaso de cerâmica grego representa uma cena de uma competição esportiva, isso mostra que a arte grega também registrava:',
    tip: 'Pensa em como os Jogos Olímpicos eram importantes para os gregos, algo que também aparecia na arte.',
    funFact: 'Muitos vasos gregos retratam justamente corredores, lutadores e outros atletas em ação!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas mitos religiosos' },
      { id: 'B', text: 'Nada do cotidiano' },
      { id: 'C', text: 'Aspectos importantes da cultura e sociedade da época, como os esportes' },
      { id: 'D', text: 'Apenas números' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'Por que muitos edifícios importantes ao redor do mundo, mesmo hoje, usam colunas inspiradas na arquitetura grega?',
    tip: 'Pensa em prédios de museus, tribunais e universidades que você já viu, com colunas parecidas com as gregas.',
    funFact: 'Esse estilo é chamado de "arquitetura clássica" e ainda é usado em construções modernas!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque é a única forma de construir prédios' },
      { id: 'B', text: 'Porque não existe outra opção' },
      { id: 'C', text: 'Porque colunas são baratas' },
      { id: 'D', text: 'Porque o estilo grego é considerado elegante e influenciou a arquitetura ocidental por séculos' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'Se uma escultura grega representa um deus com músculos definidos e uma pose equilibrada, isso reflete o ideal grego de:',
    tip: 'Volta nas questões 1 e 5 sobre a valorização do corpo humano na arte grega.',
    funFact: 'Os gregos criaram até regras matemáticas para tentar definir o que seria um corpo "perfeito"!',
    points: 1,
    options: [
      { id: 'A', text: 'Fealdade' },
      { id: 'B', text: 'Desproporção' },
      { id: 'C', text: 'Beleza e perfeição do corpo humano' },
      { id: 'D', text: 'Simplicidade extrema, sem detalhes' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'Por que o teatro grego é considerado importante também para a arquitetura?',
    tip: 'Volta na questão 8 sobre a relação entre teatro e arquitetura.',
    funFact: 'Os anfiteatros gregos eram projetados com uma acústica incrível, para que o som chegasse bem a todos os espectadores!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque não tinha nenhuma relação com construções' },
      { id: 'B', text: 'Porque os anfiteatros construídos para as peças são até hoje estudados como obras arquitetônicas' },
      { id: 'C', text: 'Porque as peças não precisavam de nenhum espaço físico' },
      { id: 'D', text: 'Porque os gregos não gostavam de teatro' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'Se você observasse um vaso grego com desenhos de heróis e batalhas mitológicas, poderia concluir que a arte grega, além de bonita, também servia para:',
    tip: 'Pensa em como a mitologia grega era importante para a cultura, e como isso aparecia na arte.',
    funFact: 'Muitos mitos gregos que conhecemos hoje sobrevivem graças a representações em vasos e esculturas antigas!',
    points: 1,
    options: [
      { id: 'A', text: 'Contar histórias e transmitir a cultura do povo grego' },
      { id: 'B', text: 'Nada além de decoração' },
      { id: 'C', text: 'Vender produtos' },
      { id: 'D', text: 'Substituir a escrita' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'Qual é uma semelhança entre a arte grega e a arte egípcia estudada anteriormente?',
    tip: 'Pensa em como tanto egípcios quanto gregos usavam a arte para falar sobre religião e mitologia.',
    funFact: 'Apesar de estilos diferentes, várias civilizações antigas usavam a arte com propósitos parecidos!',
    points: 1,
    options: [
      { id: 'A', text: 'Nenhuma, são completamente diferentes' },
      { id: 'B', text: 'As duas usavam apenas papiro' },
      { id: 'C', text: 'As duas representavam apenas paisagens' },
      { id: 'D', text: 'As duas usavam a arte para representar deuses, heróis e crenças importantes de cada cultura' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'Por que estudar a arte grega antiga é importante até hoje?',
    tip: 'Pensa em tudo que você aprendeu neste simulado sobre a influência grega na arte e arquitetura.',
    funFact: 'A arte grega influenciou diretamente a arte romana, que você vai estudar no próximo simulado!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque ela não influenciou nada depois' },
      { id: 'B', text: 'Porque muitos ideais de beleza, arquitetura e representação do corpo humano vêm dela' },
      { id: 'C', text: 'Porque só interessa a arqueólogos' },
      { id: 'D', text: 'Porque foi feita ontem' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Na aula de Arte, Bernardo faz um desenho inspirado em uma escultura grega, tentando representar o corpo humano de forma equilibrada e realista. Que característica da arte grega ele está reproduzindo?',
    tip: 'É a mesma característica das questões 5 e 9.',
    funFact: 'Desenhar o corpo humano com proporções corretas é um exercício praticado até hoje por artistas!',
    points: 1,
    options: [
      { id: 'A', text: 'O naturalismo e o equilíbrio na representação do corpo humano' },
      { id: 'B', text: 'A escrita hieroglífica' },
      { id: 'C', text: 'A pintura rupestre' },
      { id: 'D', text: 'A escrita cuneiforme' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Bernardo monta uma maquete de um templo grego com várias colunas ao redor. Que templo famoso pode ter inspirado essa maquete?',
    tip: 'É o mesmo templo das questões 2 e 6.',
    funFact: 'Construir maquetes com colunas é uma ótima forma de entender a estrutura dos templos gregos!',
    points: 1,
    options: [
      { id: 'A', text: 'O Coliseu' },
      { id: 'B', text: 'A Grande Pirâmide' },
      { id: 'C', text: 'O Partenon' },
      { id: 'D', text: 'A Esfinge' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Bernardo pinta um vaso de papel, imitando a cerâmica grega, com uma cena de uma competição esportiva. Isso representa qual tema comum na cerâmica grega?',
    tip: 'É o mesmo tema das questões 4 e 14.',
    funFact: 'Bernardo pode se inspirar nos Jogos Olímpicos, que você já estudou na aula de História!',
    points: 1,
    options: [
      { id: 'A', text: 'Receitas culinárias' },
      { id: 'B', text: 'Números e contas' },
      { id: 'C', text: 'Mapas' },
      { id: 'D', text: 'Cenas do cotidiano e de esportes, como os Jogos Olímpicos da Antiguidade' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Na apresentação, Bernardo explica que a deusa homenageada no Partenon era:',
    tip: 'É a mesma deusa da questão 6.',
    funFact: 'Atena era considerada a deusa da sabedoria e da estratégia na mitologia grega!',
    points: 1,
    options: [
      { id: 'A', text: 'Afrodite' },
      { id: 'B', text: 'Atena' },
      { id: 'C', text: 'Hera' },
      { id: 'D', text: 'Ártemis' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Bernardo compara uma escultura grega com uma pintura egípcia e percebe uma diferença. Qual é ela?',
    tip: 'É a mesma comparação da questão 13.',
    funFact: 'Fazer comparações assim ajuda a entender melhor as características únicas de cada civilização!',
    points: 1,
    options: [
      { id: 'A', text: 'A escultura grega busca mais naturalismo, enquanto a pintura egípcia é mais rígida e frontal' },
      { id: 'B', text: 'As duas são idênticas' },
      { id: 'C', text: 'A pintura egípcia é mais moderna' },
      { id: 'D', text: 'A escultura grega nunca representa pessoas' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Bernardo pergunta ao professor por que os gregos usavam tantas colunas em seus templos. O professor explica que:',
    tip: 'É a mesma explicação da questão 12.',
    funFact: 'Algumas colunas gregas antigas ainda estão de pé até hoje, mostrando a qualidade dessa construção!',
    points: 1,
    options: [
      { id: 'A', text: 'Era só para deixar mais bonito, sem função nenhuma' },
      { id: 'B', text: 'As colunas ajudavam a sustentar a estrutura e também tinham valor estético' },
      { id: 'C', text: 'Era proibido construir sem colunas' },
      { id: 'D', text: 'As colunas substituíam o teto completamente' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Bernardo desenha um vaso com cenas de heróis mitológicos, como Hércules. Isso mostra que a cerâmica grega também servia para:',
    tip: 'É a mesma ideia da questão 18.',
    funFact: 'Hércules é um dos heróis mais representados na cerâmica grega antiga!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas guardar água' },
      { id: 'B', text: 'Nada além de decoração' },
      { id: 'C', text: 'Contar histórias e transmitir a cultura grega' },
      { id: 'D', text: 'Substituir a escrita cuneiforme' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Ao comparar a arte grega com a arte egípcia, Bernardo percebe uma semelhança importante. Qual é ela?',
    tip: 'É a mesma semelhança da questão 19.',
    funFact: 'Comparar diferentes civilizações ajuda a perceber tanto as diferenças quanto os pontos em comum entre elas!',
    points: 1,
    options: [
      { id: 'A', text: 'Nenhuma, são completamente diferentes' },
      { id: 'B', text: 'As duas usavam apenas papiro' },
      { id: 'C', text: 'As duas representavam apenas paisagens' },
      { id: 'D', text: 'As duas usavam a arte para representar deuses, heróis e crenças importantes de cada cultura' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Para fechar sua apresentação, Bernardo resume: "A arte grega é importante até hoje porque..." Como ele pode completar a frase?',
    tip: 'É a mesma conclusão da questão 20.',
    funFact: 'No próximo simulado, Bernardo vai descobrir como a arte romana foi muito influenciada pela arte grega!',
    points: 1,
    options: [
      { id: 'A', text: '"...influenciou ideais de beleza, arquitetura e representação do corpo humano até os dias de hoje."' },
      { id: 'B', text: '"...não deixou nenhuma herança."' },
      { id: 'C', text: '"...foi feita ontem."' },
      { id: 'D', text: '"...só interessa a poucas pessoas."' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'Ao encerrar a atividade sobre arte grega, Bernardo percebe que, assim como a Mesopotâmia, o Egito e a Grécia estudados em História, a Arte também acompanha:',
    tip: 'Pensa em como cada civilização que você estudou teve sua própria forma de arte.',
    funFact: 'Estudar arte junto com História ajuda a entender melhor cada época e cultura!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas os tempos modernos' },
      { id: 'B', text: 'Nenhuma civilização antiga' },
      { id: 'C', text: 'A evolução das civilizações ao longo da história' },
      { id: 'D', text: 'Somente o Brasil' },
    ],
    correctAnswer: 'C',
  },
];
