export const questoesBiologia1EmB3Av2 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "A fotossíntese é o processo pelo qual plantas e outros organismos autotróficos convertem energia luminosa em energia química. Qual é a equação geral que resume a fotossíntese?",
    tip: "Na fotossíntese, o CO₂ é absorvido do ar, a H₂O é absorvida do solo e a luz fornece a energia. O que é produzido? Glicose e um gás que liberamos ao respirar.",
    funFact: "\"Você sabia?\" — A fotossíntese produz todo o oxigênio da atmosfera terrestre. Antes do surgimento das cianobactérias (fotossintéticas) há 2,7 bilhões de anos, a atmosfera da Terra era praticamente sem oxigênio livre.",
    points: 1,
    options: [
      { id: "A", text: "C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + energia (respiração celular)." },
      { id: "B", text: "6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂ (sem necessidade de energia luminosa)." },
      { id: "C", text: "6O₂ + C₆H₁₂O₆ + luz → 6CO₂ + 6H₂O + ATP." },
      { id: "D", text: "6CO₂ + 6H₂O + energia luminosa → C₆H₁₂O₆ + 6O₂ (glicose e oxigênio como produtos)." },
    ],
    correctAnswer: "D",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "A fotossíntese ocorre em duas etapas distintas. Onde ocorrem as reações da fase fotoquímica (fase clara ou reações da luz)?",
    tip: "As reações da luz precisam de luz — fazem sentido ocorrer onde os pigmentos fotossintéticos estão localizados. Qual estrutura interna do cloroplasto contém a clorofila?",
    funFact: "\"Você sabia?\" — Os tilacoides são membranas muito compactas: 1 mm² de folha contém cerca de 500.000 cloroplastos, cada um com centenas de tilacoides. Essa organização maximiza a captação de luz.",
    points: 1,
    options: [
      { id: "A", text: "Nos tilacoides (membranas internas do cloroplasto), onde estão os pigmentos fotossintéticos e os fotossistemas que captam a energia luminosa." },
      { id: "B", text: "No estroma do cloroplasto, onde as enzimas catalisam as reações independentes de luz." },
      { id: "C", text: "Na membrana plasmática da célula vegetal, onde ocorre a captação inicial de fótons." },
      { id: "D", text: "No citosol (citoplasma), onde a clorofila livre absorve a energia luminosa." },
    ],
    correctAnswer: "A",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "O Ciclo de Calvin (fase escura ou fase química) é a segunda etapa da fotossíntese. Onde ele ocorre dentro do cloroplasto?",
    tip: "O Ciclo de Calvin usa o ATP e o NADPH produzidos na fase fotoquímica para fixar o CO₂. Ele não precisa diretamente de luz. Qual região do cloroplasto está fora das membranas dos tilacoides?",
    funFact: "\"Você sabia?\" — O Ciclo de Calvin foi descoberto por Melvin Calvin usando carbono radioativo (¹⁴C) para rastrear como o CO₂ é incorporado à glicose. Ele ganhou o Prêmio Nobel de Química em 1961 por essa descoberta.",
    points: 1,
    options: [
      { id: "A", text: "Na membrana externa do cloroplasto, onde o CO₂ entra diretamente da atmosfera." },
      { id: "B", text: "Nos tilacoides, junto com as reações da fase fotoquímica." },
      { id: "C", text: "No estroma do cloroplasto (solução aquosa interna), onde estão as enzimas da fixação do CO₂, como a RuBisCO." },
      { id: "D", text: "No citosol da célula vegetal, fora do cloroplasto." },
    ],
    correctAnswer: "C",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "A taxa fotossintética pode ser limitada por fatores ambientais. Quais são os principais fatores limitantes da fotossíntese?",
    tip: "A fotossíntese precisa de ingredientes e condições: luz (para energia), CO₂ (matéria-prima), água (reagente) e temperatura adequada (para as enzimas funcionarem).",
    funFact: "\"Você sabia?\" — Em estufas agrícolas, os produtores frequentemente enriquecem o ar com CO₂ (elevando de 0,04% para 0,1-0,2%) para aumentar a taxa fotossintética das plantas e assim acelerar o crescimento e a produtividade.",
    points: 1,
    options: [
      { id: "A", text: "Apenas a temperatura, pois as enzimas são sensíveis ao calor." },
      { id: "B", text: "Intensidade luminosa, concentração de CO₂ e temperatura são os três principais fatores limitantes que controlam a taxa fotossintética." },
      { id: "C", text: "Apenas a disponibilidade de água, pois ela é o doador de elétrons na fase clara." },
      { id: "D", text: "Apenas a concentração de oxigênio, pois ele inibe a enzima RuBisCO." },
    ],
    correctAnswer: "B",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "A fase fotoquímica da fotossíntese envolve dois fotossistemas: PS I e PS II. Qual é a função específica do fotossistema II (PS II)?",
    tip: "O PS II age antes do PS I (a numeração histórica ficou invertida). O PS II é responsável por um processo que libera O₂ — o que precisa ser 'quebrado' para liberar oxigênio?",
    funFact: "\"Você sabia?\" — O oxigênio que respiramos foi liberado pela fotólise da água no PS II das cianobactérias e plantas. Portanto, cada inspiração que você dá contém oxigênio produzido pela 'quebra' da água pelas plantas.",
    points: 1,
    options: [
      { id: "A", text: "Reduzir o NADP⁺ a NADPH, que será usado no Ciclo de Calvin." },
      { id: "B", text: "Fixar o CO₂ atmosférico no estroma do cloroplasto." },
      { id: "C", text: "Produzir ATP por fotofosforilação cíclica sem liberação de oxigênio." },
      { id: "D", text: "Realizar a fotólise da água (H₂O → 2H⁺ + 2e⁻ + ½O₂), captando elétrons que serão passados para a cadeia de transporte de elétrons, com liberação de O₂." },
    ],
    correctAnswer: "D",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "A clorofila é o principal pigmento fotossintético. Qual faixa do espectro de luz ela absorve com maior eficiência?",
    tip: "As plantas parecem verdes porque refletem a luz verde. O que elas refletem é justamente o que elas NÃO absorvem muito. Portanto, qual cor elas absorvem mais?",
    funFact: "\"Você sabia?\" — No outono, as folhas ficam vermelhas e amarelas porque as clorofilas são degradadas (revelando outros pigmentos). A cor vermelha vem das antocianinas, produzidas para 'proteger' a folha enquanto ela retira os nutrientes antes de cair.",
    points: 1,
    options: [
      { id: "A", text: "Absorve principalmente a luz vermelha e azul/violeta, refletindo a luz verde (por isso as plantas parecem verdes)." },
      { id: "B", text: "Absorve principalmente a luz verde e amarela, refletindo a luz vermelha." },
      { id: "C", text: "Absorve toda a faixa do espectro visível com igual eficiência." },
      { id: "D", text: "Absorve exclusivamente a luz ultravioleta invisível ao olho humano." },
    ],
    correctAnswer: "A",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "O ATP produzido na fase fotoquímica da fotossíntese ocorre por um processo chamado fotofosforilação. O que é a fotofosforilação?",
    tip: "Foto = luz, fosfori = fosfato, lação = adição. O ATP é formado adicionando um fosfato ao ADP — e a energia para isso vem do fluxo de prótons gerado pelo gradiente criado pela luz.",
    funFact: "\"Você sabia?\" — A ATP sintase dos cloroplastos é quase idêntica à das mitocôndrias — ambas usam o gradiente de prótons (quimiosmose) para produzir ATP. Isso reflete a origem evolutiva comum dessas organelas.",
    points: 1,
    options: [
      { id: "A", text: "A síntese de ADP a partir de ATP e fosfato inorgânico durante a captação de fótons." },
      { id: "B", text: "A transferência de elétrons do CO₂ para a glicose durante o Ciclo de Calvin." },
      { id: "C", text: "A síntese de ATP a partir de ADP e fosfato inorgânico, impulsionada pelo fluxo de prótons através da ATP sintase dos tilacoides, aproveitando a energia luminosa captada." },
      { id: "D", text: "A oxidação da glicose para liberar energia na forma de ATP e calor." },
    ],
    correctAnswer: "C",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "A glicólise é a primeira etapa do catabolismo da glicose. Onde ela ocorre na célula?",
    tip: "A glicólise é a etapa mais antiga do metabolismo energético — ocorre em praticamente todos os organismos vivos. Por ser tão primitiva, ela não ocorre dentro de organelas.",
    funFact: "\"Você sabia?\" — A glicólise surgiu há mais de 3 bilhões de anos, quando a Terra não tinha oxigênio. Até hoje ela ocorre sem O₂ — por isso células musculares usam a glicólise durante exercício intenso, mesmo com O₂ disponível.",
    points: 1,
    options: [
      { id: "A", text: "Na matriz mitocondrial, junto com o Ciclo de Krebs." },
      { id: "B", text: "No citosol (citoplasma) da célula, onde a glicose é convertida em 2 moléculas de piruvato, gerando 2 ATP e 2 NADH." },
      { id: "C", text: "Na membrana interna da mitocôndria, junto com a cadeia respiratória." },
      { id: "D", text: "No retículo endoplasmático liso, especializado no metabolismo de carboidratos." },
    ],
    correctAnswer: "B",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "O Ciclo de Krebs (ciclo do ácido cítrico) é a segunda etapa da respiração aeróbica. Onde ele ocorre?",
    tip: "O Ciclo de Krebs é a continuação do metabolismo do piruvato dentro da mitocôndria. Qual região da mitocôndria, preenchida por enzimas, seria o local lógico?",
    funFact: "\"Você sabia?\" — O Ciclo de Krebs foi descoberto por Hans Adolf Krebs em 1937. Curiosamente, ele fugiu da Alemanha nazista em 1933 e refez toda sua pesquisa no Reino Unido, onde ganhou o Prêmio Nobel em 1953.",
    points: 1,
    options: [
      { id: "A", text: "No citosol da célula, na sequência direta da glicólise." },
      { id: "B", text: "Na membrana interna da mitocôndria, associado à cadeia respiratória." },
      { id: "C", text: "Na membrana externa da mitocôndria, facilitando a entrada do piruvato." },
      { id: "D", text: "Na matriz mitocondrial, onde o piruvato (após conversão em acetil-CoA) entra no ciclo e é completamente oxidado, liberando CO₂ e gerando NADH e FADH₂." },
    ],
    correctAnswer: "D",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "A cadeia respiratória (fosforilação oxidativa) é a etapa mais produtiva da respiração aeróbica. Onde ela ocorre na célula?",
    tip: "A cadeia respiratória usa os elétrons do NADH e FADH₂ para criar um gradiente de prótons que produz ATP. Ela precisa de uma membrana. Qual membrana da mitocôndria tem as proteínas da cadeia?",
    funFact: "\"Você sabia?\" — As dobras (cristas) da membrana interna mitocondrial aumentam muito a superfície disponível para as proteínas da cadeia respiratória. Uma mitocôndria típica tem mais de 17.000 complexos da cadeia respiratória em sua membrana interna.",
    points: 1,
    options: [
      { id: "A", text: "Na membrana interna da mitocôndria (cristas mitocondriais), onde os complexos proteicos transferem elétrons e bombeiam prótons para o espaço intermembrana, gerando gradiente para a ATP sintase." },
      { id: "B", text: "Na matriz mitocondrial, onde o Ciclo de Krebs ocorre simultaneamente." },
      { id: "C", text: "No citosol, junto com a glicólise que é a etapa mais produtiva." },
      { id: "D", text: "Na membrana externa da mitocôndria, voltada para o citosol." },
    ],
    correctAnswer: "A",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "A respiração aeróbica completa de uma molécula de glicose produz uma quantidade considerável de ATP. Qual é o saldo aproximado de ATP produzido?",
    tip: "A glicólise gera 2 ATP; o Ciclo de Krebs gera 2 ATP diretamente; e a cadeia respiratória gera a maior parte. Somando tudo, qual é o total aproximado?",
    funFact: "\"Você sabia?\" — Por muito tempo se acreditava que 1 glicose gerava 38 ATP. Revisões mais recentes indicam 30 a 32 ATP, pois parte da energia do gradiente de prótons é usada para importar o piruvato e o ADP para a mitocôndria.",
    points: 1,
    options: [
      { id: "A", text: "2 ATP, pois a respiração aeróbica não é mais eficiente que a fermentação." },
      { id: "B", text: "Aproximadamente 36 a 38 ATP (ou 30 a 32 em estimativas mais modernas), sendo a maior parte produzida pela fosforilação oxidativa na cadeia respiratória." },
      { id: "C", text: "4 ATP, sendo 2 da glicólise e 2 do Ciclo de Krebs, sem contribuição da cadeia respiratória." },
      { id: "D", text: "Cerca de 100 ATP, pois o O₂ é um oxidante muito eficiente." },
    ],
    correctAnswer: "B",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "A fermentação alcoólica é um processo anaeróbico realizado por leveduras e algumas bactérias. Quais são os produtos finais da fermentação alcoólica?",
    tip: "A fermentação alcoólica ocorre na produção de pão, cerveja e vinho. O que faz o pão crescer e o que dá a 'bebedeira' das bebidas alcoólicas são produtos desta fermentação.",
    funFact: "\"Você sabia?\" — Na fabricação de pão, o CO₂ produzido pelas leveduras forma bolhas que ficam presas na massa, fazendo-a crescer. No forno, o calor mata as leveduras e o álcool evapora — sobra apenas o pão esponjoso.",
    points: 1,
    options: [
      { id: "A", text: "Ácido lático e CO₂, usados na produção de iogurte e queijo." },
      { id: "B", text: "Apenas CO₂, usado pelas plantas como matéria-prima da fotossíntese." },
      { id: "C", text: "Etanol (álcool etílico) e CO₂, com geração líquida de 2 ATP por molécula de glicose." },
      { id: "D", text: "Acetato e água, com produção de 38 ATP em condições anaeróbicas." },
    ],
    correctAnswer: "C",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "A fermentação lática ocorre em bactérias láticas e em células musculares humanas durante exercício intenso. Qual é o produto final da fermentação lática?",
    tip: "Durante corrida intensa, os músculos acumulam uma substância que causa ardência e fadiga. Essa substância é o produto da fermentação lática que 'reconstitui' o NAD⁺ para continuar a glicólise.",
    funFact: "\"Você sabia?\" — O ácido lático produzido pelos músculos não é o responsável direto pela dor muscular que aparece 1-2 dias após o exercício (DOMS). A dor tardia é causada por microrrupturas nas fibras musculares. O lactato é rapidamente metabolizado pelo fígado.",
    points: 1,
    options: [
      { id: "A", text: "Etanol e CO₂, como na fermentação alcoólica das leveduras." },
      { id: "B", text: "Acetilcolina e glicose, como produtos da atividade muscular intensa." },
      { id: "C", text: "CO₂ e H₂O, com produção de grande quantidade de ATP." },
      { id: "D", text: "Ácido lático (lactato), com geração de apenas 2 ATP por molécula de glicose — o lactato é reconvertido em piruvato quando O₂ retorna." },
    ],
    correctAnswer: "D",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "A respiração aeróbica e a fermentação são formas de obter energia a partir da glicose. Qual a principal diferença entre elas em termos de eficiência?",
    tip: "Aeróbica usa O₂ e quebra a glicose completamente. Fermentação não usa O₂ e quebra apenas parcialmente. Qual produz mais ATP por glicose?",
    funFact: "\"Você sabia?\" — A respiração aeróbica é cerca de 18 vezes mais eficiente que a fermentação. É por isso que animais aeróbicos conseguem sustentar atividades prolongadas e de alta energia que seriam impossíveis com fermentação apenas.",
    points: 1,
    options: [
      { id: "A", text: "A respiração aeróbica completa produz ~36-38 ATP por glicose, enquanto a fermentação produz apenas 2 ATP, pois a glicose não é completamente oxidada na ausência de O₂." },
      { id: "B", text: "A fermentação é mais eficiente por não depender de O₂ e produzir mais ATP em menos tempo." },
      { id: "C", text: "Ambas produzem a mesma quantidade de ATP; a diferença está apenas nos subprodutos." },
      { id: "D", text: "A respiração aeróbica produz 2 ATP e a fermentação produz 38 ATP por glicose." },
    ],
    correctAnswer: "A",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "A fotorrespiração é um processo que ocorre em plantas C3 em condições de alta temperatura e baixa concentração de CO₂. O que é a fotorrespiração?",
    tip: "A fotorrespiração ocorre porque a RuBisCO (enzima do Ciclo de Calvin) pode reagir com O₂ em vez de CO₂. Em dias quentes, as plantas fecham os estômatos — o O₂ acumula e 'atrapalha' a fotossíntese.",
    funFact: "\"Você sabia?\" — As plantas C4 (como o milho e a cana-de-açúcar) evoluíram um mecanismo que concentra CO₂ perto da RuBisCO, suprimindo a fotorrespiração. Por isso o milho e a cana crescem tão eficientemente em climas quentes e ensolarados.",
    points: 1,
    options: [
      { id: "A", text: "É o processo de respiração celular que ocorre dentro dos cloroplastos durante a fotossíntese." },
      { id: "B", text: "É o processo no qual a RuBisCO reage com O₂ em vez de CO₂, gerando um composto de 2 carbonos que precisa ser reciclado, desperdiçando energia e reduzindo a eficiência fotossintética." },
      { id: "C", text: "É a síntese de ATP pelos cloroplastos usando energia luminosa e O₂." },
      { id: "D", text: "É a respiração aeróbica acelerada que ocorre nas folhas durante o dia para compensar a fotossíntese." },
    ],
    correctAnswer: "B",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "O NADH e o FADH₂ são moléculas produzidas durante a glicólise e o Ciclo de Krebs. Qual é a função dessas moléculas?",
    tip: "NADH e FADH₂ são formas reduzidas de coenzimas — carregam elétrons e prótons de alta energia. Para onde esses elétrons vão e para que servem?",
    funFact: "\"Você sabia?\" — O NADH leva seus elétrons para o início da cadeia respiratória, gerando cerca de 2,5 ATP por molécula. Já o FADH₂ entra mais adiante na cadeia e gera cerca de 1,5 ATP. É por isso que a glicólise e o Krebs são mais valiosos do que parecem.",
    points: 1,
    options: [
      { id: "A", text: "São produtos finais da respiração aeróbica, eliminados como resíduos pela célula." },
      { id: "B", text: "São hormônios que regulam a taxa de respiração celular nas mitocôndrias." },
      { id: "C", text: "São transportadores de elétrons de alta energia que levam elétrons para a cadeia respiratória, onde esses elétrons são usados para bombear prótons e produzir ATP." },
      { id: "D", text: "São enzimas que catalisam as reações do Ciclo de Krebs e da glicólise." },
    ],
    correctAnswer: "C",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "O piruvato é um composto-chave do metabolismo energético. O que acontece com o piruvato após a glicólise em condições aeróbicas?",
    tip: "Em condições aeróbicas, o piruvato entra na mitocôndria. Antes de entrar no Ciclo de Krebs, ele passa por uma transformação que libera CO₂ e gera acetil-CoA.",
    funFact: "\"Você sabia?\" — A conversão do piruvato em acetil-CoA é catalizada pelo complexo piruvato desidrogenase, um dos maiores complexos enzimáticos conhecidos. Ele é inibido pelo próprio produto (retroalimentação negativa) quando há excesso de acetil-CoA.",
    points: 1,
    options: [
      { id: "A", text: "É imediatamente convertido em glicose pela via da gliconeogênese no citosol." },
      { id: "B", text: "É transportado para a membrana plasmática para ser excretado como resíduo." },
      { id: "C", text: "É convertido em ácido lático no citosol para regenerar NAD⁺." },
      { id: "D", text: "É transportado para a matriz mitocondrial e convertido em acetil-CoA (com liberação de CO₂ e geração de NADH), entrando em seguida no Ciclo de Krebs." },
    ],
    correctAnswer: "D",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "A matriz mitocondrial é um compartimento importante da mitocôndria. Quais processos ocorrem especificamente na matriz mitocondrial?",
    tip: "A matriz é o 'interior' da mitocôndria, envolto pela membrana interna. Ela contém as enzimas do Ciclo de Krebs e é onde o piruvato é convertido em acetil-CoA.",
    funFact: "\"Você sabia?\" — A matriz mitocondrial contém o próprio DNA mitocondrial (DNA circular, similar ao bacteriano) e ribossomos próprios, reforçando a hipótese de que as mitocôndrias foram bactérias que foram incorporadas por células eucarióticas ancestrais.",
    points: 1,
    options: [
      { id: "A", text: "Conversão de piruvato em acetil-CoA e as reações do Ciclo de Krebs, onde o acetil-CoA é completamente oxidado a CO₂ com geração de NADH, FADH₂ e ATP." },
      { id: "B", text: "A glicólise e a fermentação lática, que ocorrem na matriz antes de usar O₂." },
      { id: "C", text: "A fosforilação oxidativa e a síntese de ATP pela ATP sintase." },
      { id: "D", text: "A fotossíntese e o Ciclo de Calvin, quando há luz disponível para as células vegetais." },
    ],
    correctAnswer: "A",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "Plantas C3 e C4 diferem na forma como realizam a fixação do CO₂. Qual é a diferença básica entre elas?",
    tip: "O nome C3 e C4 refere-se ao número de carbonos do primeiro produto estável da fixação do CO₂. Plantas C4 têm uma estratégia adicional que concentra o CO₂ e evita a fotorrespiração.",
    funFact: "\"Você sabia?\" — O milho, a cana-de-açúcar e o sorgo são plantas C4. Elas são muito mais produtivas em climas quentes que as C3 (como trigo e arroz). A cana-de-açúcar tem uma das maiores taxas de fixação de carbono de qualquer planta cultivada.",
    points: 1,
    options: [
      { id: "A", text: "Plantas C3 fixam o CO₂ diretamente pela RuBisCO formando compostos de 3 carbonos; plantas C4 possuem mecanismo adicional que concentra CO₂ nas células do mesófilo antes de enviá-lo para as células da bainha do feixe, evitando a fotorrespiração." },
      { id: "B", text: "Plantas C4 realizam fotossíntese à noite; plantas C3 realizam durante o dia." },
      { id: "C", text: "Plantas C3 não possuem clorofila; plantas C4 possuem dois tipos de clorofila." },
      { id: "D", text: "Plantas C4 não realizam o Ciclo de Calvin; usam apenas a fase fotoquímica." },
    ],
    correctAnswer: "B",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "A fotossíntese ocorre em organelas específicas dentro da célula vegetal. Onde exatamente nas células das folhas a fotossíntese ocorre?",
    tip: "As folhas têm diferentes tipos de células. As células do mesófilo (camada interna da folha) são as principais responsáveis pela fotossíntese, pois ficam expostas à luz após passarem pelos estômatos.",
    funFact: "\"Você sabia?\" — Uma única folha de espinafre pode conter cerca de 500.000 cloroplastos por milímetro quadrado. Cada cloroplasto tem cerca de 40 tilacoides, cada um com dezenas de fotossistemas empacotados nas membranas.",
    points: 1,
    options: [
      { id: "A", text: "Exclusivamente nas células epidérmicas da folha, que ficam diretamente expostas à luz solar." },
      { id: "B", text: "Nas células do xilema, que transportam a água usada como matéria-prima." },
      { id: "C", text: "Nos cloroplastos das células do mesófilo foliar (principalmente parênquima paliçádico e esponjoso), que contêm os pigmentos fotossintéticos e as enzimas necessárias." },
      { id: "D", text: "Nas células guarda dos estômatos, que são as únicas com clorofila na folha." },
    ],
    correctAnswer: "C",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "O ponto de compensação lumínico é um conceito importante na fisiologia vegetal. O que ele representa?",
    tip: "Em baixa luminosidade, a planta respira mais do que fotossintetiza — há saldo negativo. Em alta luminosidade, a fotossíntese supera a respiração. Em que ponto há equilíbrio?",
    funFact: "\"Você sabia?\" — Plantas de sombra têm ponto de compensação muito baixo — conseguem sobreviver com pouca luz porque minimizaram a respiração. Plantas de sol têm ponto de compensação alto, exigindo muita luz para ter lucro líquido de carbono.",
    points: 1,
    options: [
      { id: "A", text: "A intensidade luminosa na qual a taxa de fotossíntese iguala a taxa de respiração celular, resultando em zero de ganho ou perda líquida de carbono pela planta." },
      { id: "B", text: "A intensidade máxima de luz além da qual a fotossíntese não aumenta mais (ponto de saturação)." },
      { id: "C", text: "A intensidade luminosa abaixo da qual a clorofila não consegue absorver fótons." },
      { id: "D", text: "A temperatura ideal para que a fotossíntese e a respiração ocorram com máxima eficiência." },
    ],
    correctAnswer: "A",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "O ATP é a principal moeda energética das células. Como a energia armazenada no ATP é liberada para uso celular?",
    tip: "ATP tem três grupos fosfato. A ligação entre o segundo e o terceiro fosfato é rica em energia. O que acontece quando ela é quebrada?",
    funFact: "\"Você sabia?\" — Uma célula humana típica possui cerca de 1 bilhão de moléculas de ATP em um dado momento. Mas o consumo é tão alto que toda a reserva é reciclada (ADP → ATP → ADP) a cada minuto ou dois durante atividade intensa.",
    points: 1,
    options: [
      { id: "A", text: "O ATP é queimado diretamente como combustível pelas organelas, gerando calor." },
      { id: "B", text: "O ATP é secretado pelas células para ser metabolizado no ambiente extracelular." },
      { id: "C", text: "O ATP é fosforilado para gerar ATPP, que é mais energético que o ATP." },
      { id: "D", text: "A hidrólise do ATP (ATP + H₂O → ADP + Pᵢ + energia) libera energia livre que é usada para realizar trabalho celular (movimento, transporte ativo, síntese de moléculas)." },
    ],
    correctAnswer: "D",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "A respiração aeróbica tem uma equação geral que resume o processo. Qual é essa equação?",
    tip: "A respiração aeróbica é o inverso da fotossíntese em termos de substâncias: usa O₂ e glicose, produz CO₂ e H₂O, e libera energia.",
    funFact: "\"Você sabia?\" — A respiração celular e a queima de açúcar (combustão) têm as mesmas equações gerais e liberam a mesma quantidade de energia, mas na respiração a energia é liberada em pequenas etapas controladas, permitindo que seja capturada como ATP.",
    points: 1,
    options: [
      { id: "A", text: "6CO₂ + 6H₂O + energia → C₆H₁₂O₆ + 6O₂ (fotossíntese)." },
      { id: "B", text: "C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + energia (ATP + calor), com oxidação completa da glicose." },
      { id: "C", text: "C₆H₁₂O₆ → 2C₂H₅OH + 2CO₂ + 2ATP (fermentação alcoólica)." },
      { id: "D", text: "C₆H₁₂O₆ → 2C₃H₆O₃ + 2ATP (fermentação lática)." },
    ],
    correctAnswer: "B",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "A fotólise da água é um processo crucial na fase fotoquímica. O que acontece durante a fotólise da água?",
    tip: "Fotólise = quebra pela luz. A água é quebrada no PS II. Quais são os produtos dessa quebra e para que eles servem na fotossíntese?",
    funFact: "\"Você sabia?\" — A fotólise da água é um dos processos mais estudados da bioquímica porque se trata de uma reação de oxidação da água, algo que pouquíssimos sistemas químicos conseguem realizar. Replicar artificialmente esse processo poderia gerar energia limpa.",
    points: 1,
    options: [
      { id: "A", text: "A água é sintetizada a partir de H⁺ e OH⁻ para repor o que foi consumido na glicólise." },
      { id: "B", text: "A água reage com o CO₂ para formar glicose no Ciclo de Calvin." },
      { id: "C", text: "A energia luminosa captada pelo PS II quebra moléculas de água (2H₂O → 4H⁺ + 4e⁻ + O₂), liberando O₂ como subproduto e fornecendo elétrons para a cadeia de transporte dos tilacoides." },
      { id: "D", text: "A água é quebrada no escuro para fornecer H⁺ ao Ciclo de Calvin durante a noite." },
    ],
    correctAnswer: "C",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Plantas são organismos autótrofos fotossintéticos. Qual é a relação entre fotossíntese e respiração celular nas plantas?",
    tip: "As plantas realizam os dois processos. Durante o dia, qual deles predomina? E à noite? Os dois ocorrem simultaneamente ou exclusivamente um ou outro?",
    funFact: "\"Você sabia?\" — As plantas liberam CO₂ à noite (pela respiração), mas durante o dia absorvem muito mais CO₂ do que liberam (fotossíntese supera respiração). O saldo diário é a fixação de carbono que permite o crescimento vegetal.",
    points: 1,
    options: [
      { id: "A", text: "As plantas realizam fotossíntese e respiração celular simultaneamente; a fotossíntese produz glicose e O₂ e a respiração degrada parte dessa glicose para produzir ATP para as próprias necessidades energéticas da planta." },
      { id: "B", text: "As plantas realizam apenas fotossíntese durante o dia e apenas respiração à noite, alternando completamente entre os dois processos." },
      { id: "C", text: "As plantas realizam fotossíntese e não precisam de respiração celular, pois obtêm todo o ATP direto da fase fotoquímica." },
      { id: "D", text: "As plantas realizam apenas respiração, pois a fotossíntese fornece somente açúcares para uso estrutural." },
    ],
    correctAnswer: "A",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "No Ciclo de Krebs, as coenzimas NAD⁺ e FAD recebem elétrons e são reduzidas. O que acontece com elas após serem reduzidas?",
    tip: "O NADH e o FADH₂ carregam elétrons energéticos. Eles não são o produto final — eles 'entregam' esses elétrons em outro local para gerar mais ATP.",
    funFact: "\"Você sabia?\" — Cada vez que uma molécula de NADH entrega seus elétrons à cadeia respiratória, ela é reoxidada a NAD⁺. O NAD⁺ pode então voltar ao Ciclo de Krebs para ser reduzido novamente. Esse ciclo de oxidação-redução é o coração da bioenergética celular.",
    points: 1,
    options: [
      { id: "A", text: "São eliminadas como resíduos metabólicos pelo lisossomo." },
      { id: "B", text: "São transportadas para o núcleo para regular a expressão gênica." },
      { id: "C", text: "São armazenadas como reserva energética no vacúolo celular." },
      { id: "D", text: "Transportam seus elétrons para a cadeia respiratória (membrana interna mitocondrial), onde são reoxidadas e os elétrons são usados para produzir ATP por fosforilação oxidativa." },
    ],
    correctAnswer: "D",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "A fermentação tem ampla aplicação industrial e alimentícia. Quais são exemplos de produtos industriais que dependem da fermentação?",
    tip: "Pense em bebidas alcoólicas, pães e produtos lácteos fermentados. Todos têm em comum o uso de microrganismos que fermentam açúcares.",
    funFact: "\"Você sabia?\" — A história da cerveja tem mais de 5.000 anos. Os sumérios na Mesopotâmia já fermentavam cevada para produzir cerveja. Eles não sabiam nada sobre leveduras ou fermentação, mas descobriram empiricamente como usar o processo.",
    points: 1,
    options: [
      { id: "A", text: "Plásticos e borracha sintética, produzidos por bactérias modificadas geneticamente." },
      { id: "B", text: "Pão (fermentação alcoólica de leveduras libera CO₂ que faz a massa crescer), cerveja e vinho (fermentação alcoólica), iogurte e queijo (fermentação lática de bactérias)." },
      { id: "C", text: "Apenas combustíveis — o etanol carburante é o único produto industrial da fermentação." },
      { id: "D", text: "Medicamentos como insulina e antibióticos, produzidos pela fermentação aeróbica de fungos." },
    ],
    correctAnswer: "B",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "O gradiente de prótons (íons H⁺) criado na membrana interna mitocondrial é fundamental para a produção de ATP. Como esse gradiente é usado?",
    tip: "Os prótons acumulados no espaço intermembrana 'querem' voltar para a matriz. Eles passam por uma proteína especial que usa essa energia de fluxo para fazer algo muito útil.",
    funFact: "\"Você sabia?\" — O mecanismo de quimiosmose foi proposto por Peter Mitchell em 1961 e considerado herético por anos. Ele ganhou o Prêmio Nobel sozinho em 1978, após finalmente convencer a comunidade científica de sua teoria revolucionária.",
    points: 1,
    options: [
      { id: "A", text: "Os prótons retornam à matriz pelo antiportador Na⁺/H⁺, gerando corrente elétrica usada diretamente." },
      { id: "B", text: "Os prótons são bombeados para o citosol para criar um gradiente que ativa a glicólise." },
      { id: "C", text: "O fluxo de prótons do espaço intermembrana de volta à matriz, através da ATP sintase (quimiosmose), fornece a energia mecânica para girar o rotor da ATP sintase e fosforilar o ADP em ATP." },
      { id: "D", text: "Os prótons reagem com O₂ para formar água, liberando energia que é capturada como calor." },
    ],
    correctAnswer: "C",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Os organismos podem ser classificados como autótrofos ou heterótrofos com base em como obtêm energia e carbono. Qual é a definição correta de autótrofo?",
    tip: "Auto = si mesmo, trofo = nutrição. O autótrofo produz seu próprio alimento. Como ele faz isso? De onde vêm a energia e o carbono?",
    funFact: "\"Você sabia?\" — Existem autótrofos quimiossintetizantes que não usam luz, mas energia química de substâncias inorgânicas (como H₂S) para fixar CO₂. Eles vivem em ambientes extremos como fontes hidrotermais no fundo do oceano.",
    points: 1,
    options: [
      { id: "A", text: "Organismo que produz seus próprios compostos orgânicos a partir de substâncias inorgânicas (CO₂), usando energia luminosa (fotossíntese) ou química (quimiossíntese), sem depender de outros organismos como fonte de carbono." },
      { id: "B", text: "Organismo que obtém energia consumindo outros organismos ou matéria orgânica." },
      { id: "C", text: "Organismo que só se alimenta de vegetais (herbívoro)." },
      { id: "D", text: "Organismo que realiza fermentação para obter energia na ausência de oxigênio." },
    ],
    correctAnswer: "A",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "A oxidação completa de uma molécula de glicose pela respiração aeróbica libera energia. O que ocorre com essa energia no processo celular?",
    tip: "A energia da glicose não é liberada toda de uma vez como uma explosão — ela é capturada gradualmente e armazenada numa forma utilizável pela célula.",
    funFact: "\"Você sabia?\" — A eficiência da respiração celular é de cerca de 40% — ou seja, 40% da energia da glicose é capturada como ATP e 60% é perdida como calor. Apesar disso, é muito mais eficiente que a maioria dos motores artificiais.",
    points: 1,
    options: [
      { id: "A", text: "Toda a energia é liberada como calor, aquecendo a célula e o organismo." },
      { id: "B", text: "Toda a energia é armazenada em moléculas de glicogênio para uso futuro." },
      { id: "C", text: "A energia é usada para duplicar o DNA antes da divisão celular." },
      { id: "D", text: "Parte da energia é capturada em ATP (usada para trabalho celular) e parte é liberada como calor; a maior porção do ATP é produzida pela fosforilação oxidativa na cadeia respiratória." },
    ],
    correctAnswer: "D",
  },
];
