export const questoesEducacaoFisica8AnoB3Av1 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'O frevo é uma dança típica de qual região do Brasil?',
    tip: 'Pensa numa dança bem rápida e agitada, dançada com guarda-chuvas coloridos, no carnaval de uma cidade famosa chamada Recife.',
    funFact: 'O frevo é tão importante culturalmente que foi reconhecido pela UNESCO como Patrimônio Cultural Imaterial da Humanidade!',
    points: 1,
    options: [
      { id: 'A', text: 'Sul' },
      { id: 'B', text: 'Nordeste (Pernambuco)' },
      { id: 'C', text: 'Sudeste' },
      { id: 'D', text: 'Centro-Oeste' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'O que é uma dança de salão?',
    tip: 'Pensa no nome "salão" — geralmente essas danças são feitas em pares, dentro de salões de festa.',
    funFact: 'Existem dezenas de estilos de dança de salão no mundo, como o tango, o forró, a salsa e o bolero!',
    points: 1,
    options: [
      { id: 'A', text: 'Uma dança feita apenas sozinho, sem parceiro' },
      { id: 'B', text: 'Uma dança só praticada em competições olímpicas' },
      { id: 'C', text: 'Uma dança feita apenas ao ar livre' },
      { id: 'D', text: 'Uma dança geralmente feita em casal, com passos coordenados, como o forró e o tango' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'O hip-hop e o break são exemplos de qual tipo de dança?',
    tip: 'Pensa na palavra "urbana" — essas danças nasceram nas ruas das cidades, ligadas à cultura jovem.',
    funFact: 'O hip-hop e o break surgiram nos Estados Unidos, nos bairros de Nova York, nos anos 1970!',
    points: 1,
    options: [
      { id: 'A', text: 'Dança folclórica' },
      { id: 'B', text: 'Dança de salão' },
      { id: 'C', text: 'Dança urbana (street dance)' },
      { id: 'D', text: 'Dança clássica' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'O que caracteriza uma "dança folclórica"?',
    tip: 'Pensa na palavra "folclore" — ela tem a ver com tradições e costumes de um povo, passados de geração em geração.',
    funFact: 'Cada região do Brasil tem suas próprias danças folclóricas, cheias de histórias e significados especiais!',
    points: 1,
    options: [
      { id: 'A', text: 'Uma dança tradicional, ligada à cultura e história de um povo ou região' },
      { id: 'B', text: 'Uma dança criada só para a internet' },
      { id: 'C', text: 'Uma dança sem nenhuma origem cultural' },
      { id: 'D', text: 'Uma dança praticada só por profissionais' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'Qual destas é uma dança folclórica brasileira?',
    tip: 'Pensa numa dança bem animada, dançada em festas de milho e fogueira, no mês de junho.',
    funFact: 'A quadrilha tem origem em danças europeias, mas ganhou um jeitinho bem brasileiro, com roupas e músicas próprias!',
    points: 1,
    options: [
      { id: 'A', text: 'Tango' },
      { id: 'B', text: 'Quadrilha (de festa junina)' },
      { id: 'C', text: 'Balé clássico' },
      { id: 'D', text: 'Hip-hop' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'O break dance (breaking) é conhecido por incluir movimentos de:',
    tip: 'Pensa nos dançarinos de break que você já viu: eles giram no chão, fazem acrobacias e usam bastante força e criatividade.',
    funFact: 'O breaking se tornou tão reconhecido que entrou como modalidade olímpica em Paris 2024!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas caminhada lenta' },
      { id: 'B', text: 'Apenas giros de cabeça para baixo, sem nenhuma outra habilidade' },
      { id: 'C', text: 'Acrobacias, giros e força corporal, com muita criatividade' },
      { id: 'D', text: 'Apenas passos parados, sem movimento' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'O forró é uma dança de salão muito associada a qual festa brasileira?',
    tip: 'Pensa na mesma festa de milho, fogueira e quadrilha que você viu na Questão 5 desta prova.',
    funFact: 'O nome "forró" pode ter vindo da expressão "for all" (para todos), usada em festas antigas, embora essa origem ainda seja discutida!',
    points: 1,
    options: [
      { id: 'A', text: 'Carnaval' },
      { id: 'B', text: 'Natal' },
      { id: 'C', text: 'Páscoa' },
      { id: 'D', text: 'Festa junina' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'O que a dança desenvolve no corpo, além da expressão artística?',
    tip: 'Pensa em tudo que um dançarino precisa fazer ao mesmo tempo: seguir a música, mover o corpo com precisão e saber onde está cada parte dele.',
    funFact: 'Praticar dança regularmente melhora até a postura e o equilíbrio no dia a dia!',
    points: 1,
    options: [
      { id: 'A', text: 'Ritmo, coordenação motora e consciência corporal' },
      { id: 'B', text: 'Apenas força nos braços' },
      { id: 'C', text: 'Apenas velocidade de corrida' },
      { id: 'D', text: 'Nenhuma habilidade física' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'O tango é uma dança de salão de origem:',
    tip: 'Pensa numa dança dramática e elegante, bem famosa em países da América do Sul, perto do Brasil.',
    funFact: 'O tango nasceu nos bairros portuários de Buenos Aires e Montevidéu, no final do século XIX!',
    points: 1,
    options: [
      { id: 'A', text: 'Brasileira' },
      { id: 'B', text: 'Argentina e uruguaia' },
      { id: 'C', text: 'Japonesa' },
      { id: 'D', text: 'Africana' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'Qual é uma característica importante da dança, diferente de outras práticas corporais?',
    tip: 'Pensa em tudo que você já viu nesta prova: a dança sempre junta o corpo se movendo com algum ritmo e uma forma de se expressar.',
    funFact: 'Por isso a dança é considerada tanto uma prática corporal quanto uma forma de arte!',
    points: 1,
    options: [
      { id: 'A', text: 'Ela nunca usa música' },
      { id: 'B', text: 'Ela é sempre praticada sozinho' },
      { id: 'C', text: 'Ela não exige nenhum movimento do corpo' },
      { id: 'D', text: 'Ela combina movimento corporal com ritmo e expressão artística' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'Por que as danças folclóricas são importantes para preservar a cultura de um povo?',
    tip: 'Lembra da definição de dança folclórica, na Questão 4 desta prova? Pensa no que ela carrega consigo.',
    funFact: 'Em muitos lugares, as danças folclóricas são ensinadas desde a infância, justamente para manter essas tradições vivas!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque carregam tradições, histórias e costumes passados de geração em geração' },
      { id: 'B', text: 'Porque são sempre inventadas por uma só pessoa, sem história' },
      { id: 'C', text: 'Porque não têm nenhuma relação com a cultura popular' },
      { id: 'D', text: 'Porque só existem em um único país do mundo' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'O que diferencia a dança urbana (como o hip-hop) das danças de salão?',
    tip: 'Pensa em onde cada uma nasceu: uma nas ruas das cidades, outra em salões de festa mais tradicionais.',
    funFact: 'A dança urbana continua evoluindo até hoje, com novos estilos surgindo a partir das redes sociais!',
    points: 1,
    options: [
      { id: 'A', text: 'A dança urbana é sempre feita em casal, igual à de salão' },
      { id: 'B', text: 'Não existe nenhuma diferença entre elas' },
      { id: 'C', text: 'A dança urbana surgiu nas ruas, com forte conexão à cultura jovem e à música eletrônica/rap, enquanto a de salão é mais tradicional e geralmente em pares' },
      { id: 'D', text: 'A dança de salão só pode ser feita sozinha' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'Qual habilidade é especialmente exigida em danças como o break, com muitos giros e acrobacias?',
    tip: 'Lembra da Questão 6 desta prova? Pensa em tudo que é preciso para fazer giros no chão e se sustentar em posições difíceis.',
    funFact: 'Muitos dançarinos de break também treinam em academias de ginástica, porque as habilidades se parecem bastante!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas velocidade de corrida' },
      { id: 'B', text: 'Força, flexibilidade e equilíbrio corporal' },
      { id: 'C', text: 'Apenas resistência para nadar' },
      { id: 'D', text: 'Nenhuma habilidade especial' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'O que a quadrilha de festa junina costuma representar, em suas coreografias?',
    tip: 'Pensa no contexto da festa junina: fogueira, milho, roupas de caipira... o que essa dança costuma contar?',
    funFact: 'Em muitas quadrilhas, um casal de "noivos" se destaca na coreografia, representando um casamento típico do campo!',
    points: 1,
    options: [
      { id: 'A', text: 'Uma luta marcial japonesa' },
      { id: 'B', text: 'Uma corrida de atletismo' },
      { id: 'C', text: 'Um jogo de futebol' },
      { id: 'D', text: 'Cenas do campo e da vida rural, como casamento e colheita' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'Por que dançar em par, como no forró ou no tango, exige boa comunicação entre os parceiros?',
    tip: 'Pensa: se os dois dançarinos não se entenderem, o que pode acontecer com os passos?',
    funFact: 'Em muitas danças de casal, existe até um sinal silencioso (com as mãos) para avisar o parceiro sobre o próximo movimento!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque os dois precisam se coordenar nos movimentos e passos ao mesmo tempo' },
      { id: 'B', text: 'Porque não é preciso nenhuma coordenação' },
      { id: 'C', text: 'Porque cada um dança sozinho, sem prestar atenção no outro' },
      { id: 'D', text: 'Porque a comunicação não tem relação com a dança' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'Qual destas é uma habilidade desenvolvida por praticamente todos os tipos de dança?',
    tip: 'Lembra da Questão 8 desta prova? Pensa no que todo dançarino precisa ter, seja qual for o estilo de dança.',
    funFact: 'Até bebês já começam a desenvolver noção de ritmo quando ouvem música e se movimentam no colo dos pais!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas força para levantar peso' },
      { id: 'B', text: 'Ritmo e coordenação motora' },
      { id: 'C', text: 'Apenas velocidade para correr' },
      { id: 'D', text: 'Nenhuma habilidade corporal' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'Por que a dança é considerada também uma forma de expressão cultural e não só um exercício físico?',
    tip: 'Pensa na quadrilha, no frevo, no tango... cada uma carrega uma história por trás dos seus passos.',
    funFact: 'Algumas danças são até usadas em rituais religiosos ou celebrações importantes de diferentes culturas pelo mundo!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque ela nunca representa nada além do movimento em si' },
      { id: 'B', text: 'Porque é proibida em festas populares' },
      { id: 'C', text: 'Porque muitas danças contam histórias, tradições e sentimentos de um grupo ou povo' },
      { id: 'D', text: 'Porque a dança nunca usa música' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'O que torna o hip-hop uma dança com forte identidade própria?',
    tip: 'Lembra da Questão 3 desta prova? Pensa em onde e com quem essa dança nasceu.',
    funFact: 'O hip-hop não é só dança: ele também inclui música (rap), grafite e um jeito próprio de se vestir, formando toda uma cultura!',
    points: 1,
    options: [
      { id: 'A', text: 'Ele não tem nenhuma relação com a música' },
      { id: 'B', text: 'Ele é idêntico ao balé clássico' },
      { id: 'C', text: 'Ele só pode ser dançado em competições oficiais' },
      { id: 'D', text: 'Ele surgiu ligado à cultura de rua, ao rap e a movimentos de grupos jovens' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'O que significa dizer que uma dança tem "coreografia"?',
    tip: 'Pensa em como os dançarinos sabem exatamente o que fazer em cada parte da música — alguém planeja isso com antecedência.',
    funFact: 'Criar uma coreografia exige bastante criatividade e organização, como se fosse uma "receita" de movimentos!',
    points: 1,
    options: [
      { id: 'A', text: 'Uma sequência organizada de passos e movimentos combinados' },
      { id: 'B', text: 'Um tipo de instrumento musical' },
      { id: 'C', text: 'Um prêmio dado ao melhor dançarino' },
      { id: 'D', text: 'Uma regra proibindo o uso de música' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'Por que é importante respeitar e valorizar as danças de diferentes culturas, como o frevo e o tango?',
    tip: 'Pensa em tudo que você aprendeu nesta prova sobre o que cada dança carrega consigo.',
    funFact: 'Conhecer danças de diferentes culturas é uma ótima forma de aprender sobre história e geografia também!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque só uma cultura tem danças importantes' },
      { id: 'B', text: 'Porque as danças de outros países não têm valor' },
      { id: 'C', text: 'Porque cada dança representa a identidade e a história de um povo' },
      { id: 'D', text: 'Porque dança não tem relação com cultura' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Bernardo participou de uma apresentação de quadrilha na festa junina da escola. Essa dança representa principalmente:',
    tip: 'É a mesma dança da Questão 5 e da Questão 14 desta prova.',
    funFact: 'Em algumas escolas, a quadrilha é a atração principal das festas de junho, reunindo toda a comunidade!',
    points: 1,
    options: [
      { id: 'A', text: 'Uma luta marcial' },
      { id: 'B', text: 'Uma corrida de atletismo' },
      { id: 'C', text: 'Um jogo de futebol' },
      { id: 'D', text: 'Cenas da vida no campo, como casamento e colheita' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Na aula de dança, Bernardo aprendeu alguns passos de hip-hop. Esse estilo pertence a qual categoria de dança?',
    tip: 'É a mesma categoria das Questões 3 e 18 desta prova.',
    funFact: 'Aprender hip-hop ajuda a desenvolver bastante coordenação, já que os movimentos costumam ser rápidos e cheios de detalhes!',
    points: 1,
    options: [
      { id: 'A', text: 'Dança folclórica' },
      { id: 'B', text: 'Dança urbana (street dance)' },
      { id: 'C', text: 'Dança de salão' },
      { id: 'D', text: 'Balé clássico' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Bernardo assistiu a uma apresentação de frevo na escola. Essa dança é típica de qual região do Brasil?',
    tip: 'É a mesma dança e região da Questão 1 desta prova.',
    funFact: 'O frevo é dançado com passos tão rápidos que os dançarinos precisam de ótimo preparo físico para acompanhar o ritmo!',
    points: 1,
    options: [
      { id: 'A', text: 'Nordeste (Pernambuco)' },
      { id: 'B', text: 'Sul' },
      { id: 'C', text: 'Sudeste' },
      { id: 'D', text: 'Centro-Oeste' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Bernardo tentou dançar forró com um colega na festa da escola e percebeu que precisava se coordenar bem com o par. Isso mostra que a dança de salão exige:',
    tip: 'É a mesma ideia da Questão 15 desta prova.',
    funFact: 'Com a prática, os pares de dança de salão conseguem se comunicar quase sem palavras, só com o movimento do corpo!',
    points: 1,
    options: [
      { id: 'A', text: 'Dançar sempre sozinho' },
      { id: 'B', text: 'Nenhuma coordenação entre os parceiros' },
      { id: 'C', text: 'Boa comunicação e coordenação entre os dançarinos' },
      { id: 'D', text: 'Apenas força física, sem nenhuma técnica' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Bernardo viu um colega fazer giros e acrobacias dançando break. Isso exige principalmente quais habilidades?',
    tip: 'É a mesma resposta das Questões 6 e 13 desta prova.',
    funFact: 'Muitos dançarinos de break treinam tanto quanto atletas de ginástica, por causa da exigência física!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas velocidade de corrida' },
      { id: 'B', text: 'Nenhuma habilidade especial' },
      { id: 'C', text: 'Apenas resistência para nadar' },
      { id: 'D', text: 'Força, flexibilidade e equilíbrio' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Na aula, o professor explicou que Bernardo estava aprendendo uma sequência organizada de passos. Como se chama essa sequência?',
    tip: 'É o mesmo termo da Questão 19 desta prova.',
    funFact: 'Até coreografias simples de dança na escola ajudam a desenvolver memória e concentração!',
    points: 1,
    options: [
      { id: 'A', text: 'Coreografia' },
      { id: 'B', text: 'Golpe' },
      { id: 'C', text: 'Escanteio' },
      { id: 'D', text: 'Drible' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Bernardo descobriu que o tango é uma dança de salão de origem:',
    tip: 'É a mesma origem da Questão 9 desta prova.',
    funFact: 'O tango é tão importante na Argentina que tem até um dia nacional dedicado a ele!',
    points: 1,
    options: [
      { id: 'A', text: 'Brasileira' },
      { id: 'B', text: 'Argentina e uruguaia' },
      { id: 'C', text: 'Japonesa' },
      { id: 'D', text: 'Africana' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Bernardo aprendeu que muitas danças contam histórias e tradições de um povo. Por isso, a dança também é considerada uma forma de:',
    tip: 'É a mesma ideia da Questão 17 desta prova.',
    funFact: 'A dança é uma das formas de expressão cultural mais antigas da humanidade, presente em todas as civilizações!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas exercício físico, sem nenhum outro significado' },
      { id: 'B', text: 'Competição olímpica obrigatória' },
      { id: 'C', text: 'Expressão cultural' },
      { id: 'D', text: 'Luta marcial' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Bernardo quis saber por que as danças folclóricas, como a quadrilha, são importantes. O professor explicou que elas ajudam a:',
    tip: 'É a mesma resposta da Questão 11 desta prova.',
    funFact: 'Muitas famílias ensinam danças folclóricas aos filhos justamente para manter viva a memória de seus antepassados!',
    points: 1,
    options: [
      { id: 'A', text: 'Esquecer a cultura de um povo' },
      { id: 'B', text: 'Substituir totalmente os esportes' },
      { id: 'C', text: 'Evitar qualquer contato com a música' },
      { id: 'D', text: 'Preservar tradições e costumes passados de geração em geração' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'No fim da aula, Bernardo resumiu o que aprendeu sobre dança: ela combina movimento corporal com:',
    tip: 'É a mesma ideia da Questão 10 desta prova.',
    funFact: 'Essa combinação de ritmo e expressão é o que torna a dança única entre todas as práticas corporais!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas força bruta, sem nenhuma técnica' },
      { id: 'B', text: 'Ritmo e expressão artística' },
      { id: 'C', text: 'Apenas velocidade, sem nenhum ritmo' },
      { id: 'D', text: 'Nenhum elemento cultural' },
    ],
    correctAnswer: 'B',
  },
];
