export const questoesSociologia1EmB2Av1 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'O materialismo histórico, desenvolvido por Karl Marx, afirma que o motor da história é:',
    tip: 'Para Marx, o que realmente move a história não são as ideias ou os grandes homens — é algo muito mais concreto e material.',
    funFact: 'Você sabia? Marx inverteu a filosofia de Hegel: enquanto Hegel acreditava que as ideias movem a história, Marx afirmava que são as condições materiais (como as pessoas produzem sua sobrevivência) que determinam as ideias!',
    points: 1,
    options: [
      { id: 'A', text: 'As contradições entre as forças produtivas e as relações de produção, que geram conflitos de classe e impulsionam a mudança histórica' },
      { id: 'B', text: 'A vontade dos grandes líderes e heróis que direcionam os destinos das nações' },
      { id: 'C', text: 'A evolução das ideias filosóficas e religiosas ao longo do tempo' },
      { id: 'D', text: 'O progresso tecnológico espontâneo que transforma as sociedades de forma pacífica' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'Segundo Marx, o que são os modos de produção?',
    tip: 'O modo de produção não é apenas a tecnologia usada — inclui também as relações sociais que se formam em torno da produção.',
    funFact: 'Você sabia? Marx identificou ao longo da história vários modos de produção: comunismo primitivo, escravismo, feudalismo, capitalismo e, no futuro, o socialismo/comunismo. Cada um seria superado pelo seguinte por meio de contradições internas!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas as técnicas e máquinas utilizadas para fabricar mercadorias nas fábricas' },
      { id: 'B', text: 'Somente os métodos de distribuição de mercadorias no comércio internacional' },
      { id: 'C', text: 'O conjunto formado pelas forças produtivas (tecnologia, trabalho) e pelas relações de produção (relações sociais de propriedade e trabalho)' },
      { id: 'D', text: 'As formas de organização política e jurídica de uma sociedade capitalista' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'No capitalismo, Marx identificou duas classes sociais fundamentais em oposição. Quais são elas?',
    tip: 'Para Marx, no capitalismo há quem possui os meios de produção e quem não possui — essa divisão cria as duas grandes classes.',
    funFact: 'Você sabia? Marx reconhecia a existência de outras classes além dessas duas (como a pequena burguesia e os camponeses), mas argumentava que a tendência histórica do capitalismo era polarizar a sociedade entre as duas classes principais!',
    points: 1,
    options: [
      { id: 'A', text: 'Ricos e pobres — divididos apenas pelo nível de renda e consumo individual' },
      { id: 'B', text: 'Burguesia (proprietária dos meios de produção) e proletariado (que vende sua força de trabalho)' },
      { id: 'C', text: 'Nobreza e clero — as classes que dominavam no feudalismo e continuaram no capitalismo' },
      { id: 'D', text: 'Empregadores e empregados — divididos pela posição hierárquica nas empresas' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'A mais-valia é um conceito central da crítica marxista ao capitalismo. O que é mais-valia?',
    tip: 'Pense: se um trabalhador produz em 4 horas o suficiente para pagar seu salário, o que acontece com as outras 4 horas que ele trabalha?',
    funFact: 'Você sabia? Marx dedicou décadas de sua vida ao estudo da mais-valia em "O Capital". O livro era tão complexo que apenas o primeiro volume foi publicado em vida — Engels publicou os outros dois volumes após a morte de Marx!',
    points: 1,
    options: [
      { id: 'A', text: 'O salário extra pago ao trabalhador quando ele produz acima da meta estabelecida' },
      { id: 'B', text: 'Os impostos pagos pelo capitalista ao governo sobre o lucro das vendas' },
      { id: 'C', text: 'O lucro obtido pelo comércio internacional por meio de diferenças de preço entre países' },
      { id: 'D', text: 'O valor criado pelo trabalho do operário além do necessário para reproduzir seu salário, apropriado pelo capitalista como lucro' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'Para Marx, a alienação do trabalho no capitalismo significa que o trabalhador:',
    tip: 'Pense em alguém que trabalha numa linha de montagem fazendo a mesma tarefa repetitiva o dia todo — qual é sua relação com o produto final?',
    funFact: 'Você sabia? Marx baseou sua teoria da alienação no jovem Hegel. Mas onde Hegel via a alienação como problema filosófico (separação da consciência), Marx a via como problema concreto: o trabalhador alienado de seu produto, seu trabalho e seus semelhantes!',
    points: 1,
    options: [
      { id: 'A', text: 'Não se reconhece no produto do seu trabalho, perde o controle sobre o processo produtivo e se torna estranho a si mesmo e aos outros' },
      { id: 'B', text: 'Recebe um salário muito baixo que não cobre suas necessidades básicas de sobrevivência' },
      { id: 'C', text: 'É explorado fisicamente pelo capitalista sofrendo apenas condições insalubres de trabalho' },
      { id: 'D', text: 'Trabalha mais horas do que o contrato de trabalho estabelece legalmente' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'O materialismo dialético de Marx se diferencia do materialismo mecânico porque:',
    tip: 'O que torna o pensamento de Marx "dialético" é a ideia de contradição e conflito como motor da mudança — não uma evolução linear e pacífica.',
    funFact: 'Você sabia? Marx pegou o método dialético de Hegel (tese + antítese = síntese) mas virou de cabeça para baixo: Hegel dizia que o espírito (ideias) era a força motriz; Marx disse que era a matéria (condições econômicas)!',
    points: 1,
    options: [
      { id: 'A', text: 'O materialismo mecânico já considerava a matéria em movimento; Marx apenas copiou essa ideia' },
      { id: 'B', text: 'O materialismo dialético nega a existência da matéria e afirma que tudo é ideia e espírito' },
      { id: 'C', text: 'O materialismo dialético incorpora as contradições e conflitos como motor do desenvolvimento histórico, ao invés de ver a realidade como estática' },
      { id: 'D', text: 'O materialismo mecânico estudava apenas a natureza; Marx estudou apenas a economia capitalista' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'A ideologia, para Marx, cumpre uma função específica nas sociedades capitalistas. Qual é essa função?',
    tip: 'Para Marx, as ideias dominantes de uma época sempre são as ideias da classe dominante — pense no porquê disso.',
    funFact: 'Você sabia? Marx afirmou que "a religião é o ópio do povo" — não para ofender religiosos, mas para mostrar que a religião (como a ideologia em geral) anestesia os trabalhadores, fazendo-os aceitar sua situação de exploração como vontade divina!',
    points: 1,
    options: [
      { id: 'A', text: 'Promover a revolução socialista por meio da conscientização política dos trabalhadores' },
      { id: 'B', text: 'Legitimar e naturalizar as relações de dominação da classe dominante, fazendo as desigualdades parecerem naturais e inevitáveis' },
      { id: 'C', text: 'Criar novas formas de arte e cultura que expressem os valores universais da humanidade' },
      { id: 'D', text: 'Organizar os partidos políticos e os movimentos sociais das classes exploradas' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'O que Marx entendia por infraestrutura (base) na sua concepção de sociedade?',
    tip: 'Na metáfora arquitetônica de Marx, a "base" sustenta tudo o que está acima — é a fundação material sobre a qual se constrói a vida social.',
    funFact: 'Você sabia? Marx usava a metáfora de um edifício: a infraestrutura (economia) é a fundação, e a superestrutura (política, direito, religião, arte) é o que está acima. Mudar a fundação muda o edifício inteiro!',
    points: 1,
    options: [
      { id: 'A', text: 'As leis, o Estado e as instituições políticas que organizam formalmente a sociedade' },
      { id: 'B', text: 'A religião, a moral e os valores culturais que orientam o comportamento dos cidadãos' },
      { id: 'C', text: 'As obras de arte, a literatura e a filosofia produzidas por uma determinada época' },
      { id: 'D', text: 'A base econômica da sociedade: as forças produtivas e as relações de produção' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'A superestrutura, na teoria marxista, é composta por:',
    tip: 'Se a infraestrutura é a "base" econômica, a superestrutura é tudo que está "acima" — as instituições não econômicas da sociedade.',
    funFact: 'Você sabia? Marx argumentava que mudanças profundas na superestrutura (como novas leis ou revoluções políticas) sem mudança na infraestrutura econômica são superficiais — a verdadeira revolução precisa transformar as relações de produção!',
    points: 1,
    options: [
      { id: 'A', text: 'As instituições políticas, jurídicas, religiosas, culturais e ideológicas que se erguem sobre a base econômica' },
      { id: 'B', text: 'As fábricas, máquinas e tecnologias utilizadas na produção capitalista industrial' },
      { id: 'C', text: 'As relações de trabalho diretas entre capitalistas e trabalhadores nas indústrias' },
      { id: 'D', text: 'Os mercados e as bolsas de valores onde se negocia capital financeiro especulativo' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'O "Manifesto Comunista" (1848), escrito por Marx e Engels, termina com uma famosa convocação. Qual era essa convocação?',
    tip: 'Marx e Engels queriam unir os trabalhadores de todos os países — mas o que eles precisariam perder para isso?',
    funFact: 'Você sabia? O "Manifesto Comunista" foi escrito em apenas algumas semanas, a pedido da Liga dos Comunistas. É um dos textos políticos mais influentes da história — e começava com a frase: "Um espectro ronda a Europa — o espectro do comunismo"!',
    points: 1,
    options: [
      { id: 'A', text: '"Proprietários de todos os países, uni-vos para defender a propriedade privada!"' },
      { id: 'B', text: '"Intelectuais de todos os países, uni-vos para educar o povo trabalhador!"' },
      { id: 'C', text: '"Trabalhadores de todos os países, uni-vos! Não temos nada a perder senão as nossas correntes!"' },
      { id: 'D', text: '"Governantes de todos os países, uni-vos para manter a ordem e a paz social!"' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'O que Marx chamava de "luta de classes"?',
    tip: 'Para Marx, a história não é harmônica — ela é marcada pelo conflito entre grupos com interesses opostos ligados à posição na produção.',
    funFact: 'Você sabia? O "Manifesto Comunista" começa com a famosa frase: "A história de toda a sociedade até hoje é a história da luta de classes". Marx via esse conflito em todas as épocas: escravos x senhores, servos x nobres, proletários x burguesia!',
    points: 1,
    options: [
      { id: 'A', text: 'Os debates e conflitos entre partidos políticos no parlamento democrático moderno' },
      { id: 'B', text: 'As disputas militares entre países capitalistas por territórios e recursos naturais' },
      { id: 'C', text: 'As diferenças culturais e religiosas entre grupos sociais de diferentes origens' },
      { id: 'D', text: 'O conflito de interesses entre classes sociais com posições opostas nas relações de produção, que impulsiona a mudança histórica' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'A consciência de classe, para Marx, é diferente da "classe em si". O que é a "classe para si"?',
    tip: 'Uma classe pode existir objetivamente sem que seus membros saibam disso. Quando ela toma consciência de seus interesses, muda de caráter.',
    funFact: 'Você sabia? Marx distinguia o proletariado como "classe em si" (grupo objetivo com interesses comuns) da "classe para si" (grupo com consciência de seus interesses e organizado para defendê-los). A revolução exigiria essa passagem!',
    points: 1,
    options: [
      { id: 'A', text: 'A classe que já atingiu o mais alto nível de prosperidade econômica na sociedade' },
      { id: 'B', text: 'A classe que tomou consciência de seus interesses coletivos e se organiza para transformar a sociedade' },
      { id: 'C', text: 'A classe que aceita sua posição social como natural e não questiona as desigualdades' },
      { id: 'D', text: 'A classe que detém o controle dos meios de comunicação e da produção cultural' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'O conceito marxista de "fetichismo da mercadoria" refere-se ao fenômeno em que:',
    tip: 'Pense em como as marcas de tênis, roupas ou eletrônicos parecem ter um valor e poder "mágico" — não apenas por sua utilidade, mas por aquilo que "significam".',
    funFact: 'Você sabia? Marx usou o termo "fetiche" de forma proposital — na religião animista africana, fetiches eram objetos comuns que ganhavam poderes mágicos. Para Marx, as mercadorias ganham um poder "misterioso" que esconde as relações de trabalho!',
    points: 1,
    options: [
      { id: 'A', text: 'As mercadorias parecem ter valor e relações próprias, ocultando as relações de trabalho humano que as produziram' },
      { id: 'B', text: 'Os consumidores tornam-se viciados em compras e consumo excessivo como forma de identidade' },
      { id: 'C', text: 'Os capitalistas adoram as mercadorias como se fossem objetos sagrados de adoração' },
      { id: 'D', text: 'Os trabalhadores vendem sua força de trabalho como se fosse uma mercadoria qualquer no mercado' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'Marx distinguia "valor de uso" e "valor de troca" das mercadorias. Qual é a diferença entre eles?',
    tip: 'Pense numa garrafa de água: ela tem um valor prático (saciar a sede) e um valor de mercado (o preço que pagamos) — esses são diferentes.',
    funFact: 'Você sabia? Marx usava o famoso exemplo da água e do diamante: a água tem alto valor de uso (essencial para a vida) mas baixo valor de troca; o diamante tem baixo valor de uso mas altíssimo valor de troca. Isso mostrava que valor de mercado não reflete utilidade!',
    points: 1,
    options: [
      { id: 'A', text: 'Valor de uso é o preço no mercado; valor de troca é a utilidade concreta para o consumidor' },
      { id: 'B', text: 'Ambos são sinônimos — toda mercadoria tem apenas um único tipo de valor' },
      { id: 'C', text: 'Valor de uso é a utilidade concreta de uma mercadoria; valor de troca é sua capacidade de ser trocada por outras mercadorias no mercado' },
      { id: 'D', text: 'Valor de uso é determinado pela raridade da mercadoria; valor de troca é determinado pela necessidade' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'Para Marx, a revolução socialista seria inevitável porque:',
    tip: 'Marx não via a revolução como um capricho — ele a via como resultado necessário das contradições internas do capitalismo.',
    funFact: 'Você sabia? Marx acreditava que o capitalismo criava seus próprios "coveiros" — ao concentrar os trabalhadores nas fábricas, proletarizá-los e aprofundar as contradições, o próprio capitalismo preparava as condições para sua superação!',
    points: 1,
    options: [
      { id: 'A', text: 'Os trabalhadores são naturalmente mais numerosos e fisicamente mais fortes que os capitalistas' },
      { id: 'B', text: 'Os governos democráticos aprovariam leis que acabariam pacificamente com a exploração' },
      { id: 'C', text: 'A religião ensinaria aos trabalhadores que a exploração é um pecado grave' },
      { id: 'D', text: 'As contradições internas do capitalismo (concentração de riqueza, empobrecimento do proletariado) tornariam inevitável o colapso do sistema e sua superação' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'O modo de produção feudal se diferenciava do capitalista principalmente porque:',
    tip: 'No feudalismo, o senhor extraía trabalho do servo de forma direta e visível; no capitalismo, a exploração ocorre de forma diferente, mediada pelo salário.',
    funFact: 'Você sabia? Marx chamou a mais-valia capitalista de "mais-valia velada" — ao contrário do trabalho excedente feudal (visível: o servo trabalhava na terra do senhor alguns dias por semana), no capitalismo a exploração fica escondida pelo salário!',
    points: 1,
    options: [
      { id: 'A', text: 'No feudalismo não havia nenhuma desigualdade social; no capitalismo a desigualdade foi criada' },
      { id: 'B', text: 'No feudalismo a exploração era baseada na servidão (trabalho compulsório e tributos); no capitalismo é baseada no trabalho assalariado e na extração da mais-valia' },
      { id: 'C', text: 'No feudalismo havia liberdade total de mercado; no capitalismo o Estado controla toda a economia' },
      { id: 'D', text: 'No feudalismo as mulheres trabalhavam junto com os homens; no capitalismo apenas os homens trabalhavam' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'A teoria do valor-trabalho, base da análise econômica de Marx, afirma que:',
    tip: 'Para Marx, o que determina o valor de uma mercadoria não é o preço que as pessoas pagam por ela — é o que está "contido" nela.',
    funFact: 'Você sabia? A teoria do valor-trabalho não foi inventada por Marx — ele a herdou dos economistas liberais Adam Smith e David Ricardo. Mas Marx desenvolveu a teoria e usou ela para mostrar que o capitalismo é fundamentalmente explorador!',
    points: 1,
    options: [
      { id: 'A', text: 'O valor das mercadorias é determinado pelo tempo de trabalho humano socialmente necessário para produzi-las' },
      { id: 'B', text: 'O valor das mercadorias é determinado pela demanda dos consumidores no mercado livre' },
      { id: 'C', text: 'O valor das mercadorias é determinado pelos custos de matérias-primas e maquinário industrial' },
      { id: 'D', text: 'O valor das mercadorias é determinado pelo prestígio social de quem as produz' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'A "acumulação primitiva do capital" descreve, para Marx, o processo pelo qual:',
    tip: 'Antes de investir capital, os capitalistas precisaram obtê-lo de alguma forma — Marx questionou como esse capital inicial foi acumulado historicamente.',
    funFact: 'Você sabia? Marx descreveu o processo de "cercamento dos campos" na Inglaterra como parte da acumulação primitiva: camponeses foram expulsos de terras comunais, forçados a se tornar proletários nas cidades. Isso não foi um processo pacífico!',
    points: 1,
    options: [
      { id: 'A', text: 'Os trabalhadores pouparam suas economias ao longo de gerações para investir em negócios' },
      { id: 'B', text: 'O Estado distribuiu capital igualmente para todos os cidadãos iniciarem suas empresas' },
      { id: 'C', text: 'Trabalhadores foram separados de seus meios de vida (terra, ferramentas) por meio de violência, colonização e expropriação, criando as condições para o capitalismo' },
      { id: 'D', text: 'Os capitalistas acumularam riqueza por meio de poupança e trabalho árduo por gerações' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'Para Marx, o Estado capitalista é:',
    tip: 'Marx não via o Estado como neutro ou representante de todos — ele tinha uma visão específica sobre a quem o Estado serve.',
    funFact: 'Você sabia? Marx e Engels escreveram no Manifesto Comunista que "o poder executivo do Estado moderno não é mais do que um comitê para gerir os assuntos comuns de toda a burguesia". Essa frase ainda provoca debate nas ciências políticas!',
    points: 1,
    options: [
      { id: 'A', text: 'Uma instituição neutra que representa os interesses de todos os cidadãos igualmente' },
      { id: 'B', text: 'Um árbitro imparcial entre as classes sociais que garante o bem comum' },
      { id: 'C', text: 'Uma organização criada pelos trabalhadores para defender seus direitos fundamentais' },
      { id: 'D', text: 'Um instrumento de dominação da classe dominante (burguesia) para manter as condições de exploração do proletariado' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'A divisão do trabalho no capitalismo, diferente da visão de Durkheim, é vista por Marx como:',
    tip: 'Enquanto Durkheim via a divisão do trabalho como geradora de solidariedade, Marx via um aspecto sombrio nesse mesmo processo.',
    funFact: 'Você sabia? Marx e Durkheim chegaram a conclusões opostas sobre a divisão do trabalho! Para Durkheim, ela criava solidariedade; para Marx, ela criava alienação, fragmentando o trabalhador e separando-o do produto de seu trabalho!',
    points: 1,
    options: [
      { id: 'A', text: 'Uma forma de solidariedade orgânica que une os trabalhadores por interdependência' },
      { id: 'B', text: 'Um mecanismo de alienação que fragmenta o trabalho, priva o trabalhador do controle do processo e separa-o do produto final' },
      { id: 'C', text: 'Uma forma de progresso técnico que beneficia igualmente todos os membros da sociedade' },
      { id: 'D', text: 'Uma organização natural e harmônica do trabalho coletivo baseada nas capacidades individuais' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'O conceito marxista de "superestrutura" inclui quais elementos?',
    tip: 'A superestrutura é tudo que não é base econômica, mas que a reflete e a sustenta ideologicamente.',
    funFact: 'Você sabia? Marx argumentava que a superestrutura tem certa autonomia relativa — ela não muda instantaneamente quando a base econômica muda. Por isso, ideias, crenças e instituições de épocas anteriores sobrevivem muito além de sua época!',
    points: 1,
    options: [
      { id: 'A', text: 'As máquinas, ferramentas e matérias-primas utilizadas na produção industrial moderna' },
      { id: 'B', text: 'O mercado, o sistema bancário e as relações comerciais internacionais capitalistas' },
      { id: 'C', text: 'O Estado, o direito, a religião, a moral, a arte e as ideologias que refletem e sustentam a base econômica' },
      { id: 'D', text: 'Os sindicatos, as cooperativas e as organizações de trabalhadores e seus direitos' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'A mais-valia absoluta, na teoria marxista, é obtida quando:',
    tip: 'Existem duas formas de aumentar o lucro: fazendo o trabalhador trabalhar mais tempo ou fazendo-o produzir mais no mesmo tempo.',
    funFact: 'Você sabia? A mais-valia absoluta foi a forma dominante de extração de lucro no início do capitalismo — daí as jornadas de 14-16 horas na Inglaterra vitoriana! A mais-valia relativa surgiu depois com a mecanização e a "administração científica" do trabalho!',
    points: 1,
    options: [
      { id: 'A', text: 'O capitalista amplia a jornada de trabalho (mais horas) mantendo o salário constante, aumentando o tempo de trabalho não pago' },
      { id: 'B', text: 'O capitalista aumenta a eficiência da produção por meio de automação e tecnologia avançada' },
      { id: 'C', text: 'O capitalista reduz os custos de matérias-primas por meio de negociação com fornecedores' },
      { id: 'D', text: 'O capitalista obtém mais lucro por meio de comércio internacional com países subdesenvolvidos' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'O "exército industrial de reserva" é um conceito marxista que se refere a:',
    tip: 'Para Marx, o desemprego no capitalismo não é um acidente — é funcional para o sistema. Por quê?',
    funFact: 'Você sabia? Marx foi um dos primeiros a mostrar que o desemprego não é apenas um problema conjuntural — é estrutural ao capitalismo. O exército de reserva mantém os salários baixos e os trabalhadores com medo de reivindicar melhorias!',
    points: 1,
    options: [
      { id: 'A', text: 'Os soldados recrutados pelo Estado para proteger as indústrias capitalistas durante greves' },
      { id: 'B', text: 'Os trabalhadores migrantes que vêm de outros países buscar emprego nas cidades industriais' },
      { id: 'C', text: 'Os aposentados e trabalhadores temporários que servem como reserva para épocas de crescimento' },
      { id: 'D', text: 'Os trabalhadores inativos (desempregados) que pressionam os empregados a aceitar baixos salários, sendo estruturalmente funcionais para o capitalismo' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Marx e Engels escreveram em 1848 o "Manifesto Comunista". Qual era o contexto histórico desse documento?',
    tip: 'O Manifesto foi escrito às vésperas de grandes convulsões sociais que sacudiram toda a Europa em 1848.',
    funFact: 'Você sabia? O Manifesto Comunista foi publicado em fevereiro de 1848 — apenas semanas depois, em março, eclodiram revoluções em quase todos os países europeus (França, Alemanha, Áustria, Hungria, Itália). Mas Marx as considerou incompletas!',
    points: 1,
    options: [
      { id: 'A', text: 'A Primeira Guerra Mundial e o surgimento do imperialismo europeu no século XX' },
      { id: 'B', text: 'A industrialização crescente, a formação do movimento operário e as revoluções de 1848 na Europa' },
      { id: 'C', text: 'A Revolução Russa de 1917 e a criação do primeiro Estado socialista do mundo' },
      { id: 'D', text: 'A Grande Depressão de 1929 e o desemprego em massa nos países capitalistas' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Para Marx, o capitalismo contém contradições internas que levam à sua crise. Qual é a principal dessas contradições?',
    tip: 'O capitalismo cresce explorando os trabalhadores — mas ao empobrecê-los, cria um problema: quem vai comprar as mercadorias produzidas?',
    funFact: 'Você sabia? Marx previu que o capitalismo seria periodicamente atingido por crises de "superprodução" — quando as fábricas produzem mais do que os trabalhadores empobrecidos conseguem comprar. A Grande Depressão de 1929 pareceu confirmar essa previsão!',
    points: 1,
    options: [
      { id: 'A', text: 'A contradição entre os interesses de diferentes países capitalistas na disputa por colônias e mercados' },
      { id: 'B', text: 'A contradição entre o Estado e o mercado, que disputam permanentemente o controle da economia' },
      { id: 'C', text: 'A contradição entre a natureza social da produção e a apropriação privada do produto — trabalhadores produzem coletivamente, mas o resultado é apropriado por poucos' },
      { id: 'D', text: 'A contradição entre tecnologia e natureza, pois a indústria destrói o meio ambiente irreversivelmente' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Qual é a diferença entre proletariado e lumpenproletariado na teoria marxista?',
    tip: 'Marx distinguia os trabalhadores que vendem sua força de trabalho (proletários) daqueles que estão completamente excluídos do mercado de trabalho formal.',
    funFact: 'Você sabia? Marx tinha uma visão bastante negativa do lumpenproletariado — para ele, esse grupo não tinha consciência de classe e facilmente poderia ser manipulado pela burguesia como "força de choque" contra os movimentos operários!',
    points: 1,
    options: [
      { id: 'A', text: 'O proletariado vende sua força de trabalho nas indústrias; o lumpenproletariado é formado por marginalizados (mendigos, desempregados crônicos, criminosos) sem inserção produtiva estável' },
      { id: 'B', text: 'O proletariado inclui todos os trabalhadores, incluindo os rurais; o lumpenproletariado inclui apenas os urbanos' },
      { id: 'C', text: 'O proletariado é formado por trabalhadores europeus; o lumpenproletariado por trabalhadores dos países colonizados' },
      { id: 'D', text: 'O proletariado é formado por homens adultos; o lumpenproletariado inclui mulheres e crianças trabalhadores' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Após a revolução, Marx previa a criação de uma fase transitória antes do comunismo pleno. O que é essa fase?',
    tip: 'Para Marx, não se passaria diretamente do capitalismo para o comunismo — seria necessária uma etapa de transição com um novo tipo de Estado.',
    funFact: 'Você sabia? A "ditadura do proletariado" marxista não era o que entendemos hoje por ditadura — era um regime democrático para a maioria (trabalhadores) e ditatorial apenas para a minoria (ex-burguesia). Lenin a implementou de forma diferente na URSS!',
    points: 1,
    options: [
      { id: 'A', text: 'A democracia burguesa — etapa em que os capitalistas fazem concessões voluntárias aos trabalhadores' },
      { id: 'B', text: 'O socialismo utópico — etapa idealizada por intelectuais sem base na realidade material' },
      { id: 'C', text: 'O anarquismo — etapa de abolição imediata do Estado e de toda forma de autoridade' },
      { id: 'D', text: 'A ditadura do proletariado — etapa em que a classe trabalhadora controla o Estado para destruir as condições materiais do capitalismo' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'A alienação religiosa, descrita por Marx em diálogo com Feuerbach, significa que:',
    tip: 'Marx concordou com Feuerbach que a religião é uma criação humana — mas foi além: por que os humanos criariam um Deus?',
    funFact: 'Você sabia? Marx disse que a religião é a "queixa" dos oprimidos — uma forma de expressar a dor da exploração — mas também um "consolo ilusório" que impede os trabalhadores de lutar contra as verdadeiras causas de seu sofrimento!',
    points: 1,
    options: [
      { id: 'A', text: 'Deus criou os humanos e a religião especificamente para justificar as desigualdades sociais' },
      { id: 'B', text: 'Os humanos criam Deus como projeção de suas qualidades, alienando-as em uma entidade fictícia; a religião reflete e consola a miséria real' },
      { id: 'C', text: 'A religião é sempre diretamente inventada pelos capitalistas para controlar os trabalhadores' },
      { id: 'D', text: 'A religião é o único elemento da superestrutura que não reflete de forma alguma a base econômica' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'A teoria marxista influenciou movimentos sociais e políticos ao redor do mundo. Qual das seguintes revoluções foi diretamente inspirada no marxismo?',
    tip: 'Qual foi a primeira revolução que criou um Estado que se declarou socialista e se inspirou nos escritos de Marx?',
    funFact: 'Você sabia? O próprio Marx ficaria surpreso com a Revolução Russa — ele acreditava que a revolução socialista ocorreria primeiro nos países capitalistas mais avançados (Alemanha, Inglaterra), não na Rússia, que ainda era semi-feudal em 1917!',
    points: 1,
    options: [
      { id: 'A', text: 'A Revolução Americana (1776) que criou os Estados Unidos como nação independente' },
      { id: 'B', text: 'A Revolução Francesa (1789) que derrubou a monarquia absoluta de Luís XVI' },
      { id: 'C', text: 'A Revolução Russa (1917) que criou a União Soviética como primeiro Estado socialista do mundo' },
      { id: 'D', text: 'A Revolução Industrial Inglesa (século XVIII) que criou o capitalismo moderno' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'Qual é a crítica central que Marx faz ao capitalismo em "O Capital" (1867)?',
    tip: 'A obra mais importante de Marx não é apenas uma crítica econômica — é uma análise sistemática de como o capitalismo funciona e por que é explorador pela sua própria natureza.',
    funFact: 'Você sabia? "O Capital" é um dos livros mais importantes e ao mesmo tempo menos lidos da história — Marx trabalhou nele por mais de 20 anos, mas apenas o primeiro volume foi publicado em vida. Engels publicou os outros dois volumes postumamente!',
    points: 1,
    options: [
      { id: 'A', text: 'O capitalismo é fundamentalmente um sistema de exploração baseado na extração da mais-valia do trabalho do operário pelo capitalista' },
      { id: 'B', text: 'O capitalismo é ineficiente do ponto de vista econômico e gera desperdício de recursos naturais' },
      { id: 'C', text: 'O capitalismo gera desigualdade apenas nos países pobres; nos países ricos promove igualdade' },
      { id: 'D', text: 'O capitalismo destrói o meio ambiente e os recursos naturais de forma irreversível em toda parte' },
    ],
    correctAnswer: 'A',
  },
];
