export const questoesPortugues7AnoB1Av1 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'O que é um "gênero textual"?',
    tip: 'Pensa em como uma receita, uma notícia e um poema são bem diferentes entre si — cada um tem seu formato e objetivo.',
    funFact: 'Existem centenas de gêneros textuais diferentes, e novos surgem o tempo todo, como os posts de rede social!',
    points: 1,
    options: [
      { id: 'A', text: 'Um tipo de errinho de gramática' },
      { id: 'B', text: 'Apenas um tipo de livro' },
      { id: 'C', text: 'Um sinônimo de "assunto"' },
      { id: 'D', text: 'Um tipo de texto com características e objetivo próprios, como notícia, conto ou receita' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'A "crônica" é um gênero textual que costuma:',
    tip: 'Pensa num texto curto que comenta, de um jeito quase de conversa, algo simples que aconteceu no dia a dia.',
    funFact: 'Muitos jornais brasileiros publicam crônicas semanais, com autores famosos comentando o cotidiano de forma bem-humorada!',
    points: 1,
    options: [
      { id: 'A', text: 'Explicar fórmulas de matemática' },
      { id: 'B', text: 'Comentar, de forma leve e reflexiva, fatos do cotidiano' },
      { id: 'C', text: 'Listar ingredientes de uma receita' },
      { id: 'D', text: 'Apresentar apenas dados científicos' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'Uma "notícia" é um gênero textual cujo principal objetivo é:',
    tip: 'Pensa no que você espera encontrar ao abrir o jornal ou um site de notícias — histórias inventadas ou fatos reais?',
    funFact: 'Uma boa notícia costuma responder a perguntas como "o quê", "quem", "quando", "onde" e "por quê"!',
    points: 1,
    options: [
      { id: 'A', text: 'Informar fatos reais de forma objetiva' },
      { id: 'B', text: 'Contar uma história totalmente inventada' },
      { id: 'C', text: 'Convencer o leitor a comprar um produto' },
      { id: 'D', text: 'Ensinar a fazer uma receita' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'Um "texto de opinião" é caracterizado por:',
    tip: 'Pensa num texto em que o autor diz claramente o que ele pensa sobre um assunto, tentando convencer o leitor.',
    funFact: 'Jornais costumam ter uma seção especial só para textos de opinião, separada das notícias!',
    points: 1,
    options: [
      { id: 'A', text: 'Apresentar apenas fatos, sem nenhuma opinião' },
      { id: 'B', text: 'Ser sempre uma receita culinária' },
      { id: 'C', text: 'Defender um ponto de vista sobre determinado assunto' },
      { id: 'D', text: 'Ser sempre uma poesia' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'O "conto" é um gênero textual narrativo que se caracteriza por:',
    tip: 'Pensa em como um conto pode ser lido de uma vez só, sem precisar de muitos capítulos, diferente de um romance.',
    funFact: 'Alguns dos contos mais famosos do mundo, como os de fadas, têm centenas de anos e ainda são lidos hoje!',
    points: 1,
    options: [
      { id: 'A', text: 'Ser sempre muito longo, como um romance' },
      { id: 'B', text: 'Não ter nenhum personagem' },
      { id: 'C', text: 'Ser escrito apenas em forma de lista' },
      { id: 'D', text: 'Ser uma narrativa curta, geralmente com poucos personagens e um só conflito principal' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'Uma "receita culinária" é um exemplo de gênero textual:',
    tip: 'Pensa em como uma receita ensina, passo a passo, como preparar um prato — isso é uma opinião ou uma instrução?',
    funFact: 'As receitas mais antigas que se tem notícia têm mais de 4 mil anos, escritas em tábuas de argila!',
    points: 1,
    options: [
      { id: 'A', text: 'Argumentativo' },
      { id: 'B', text: 'Instrucional, que orienta passo a passo como fazer algo' },
      { id: 'C', text: 'Poético' },
      { id: 'D', text: 'Jornalístico' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'Uma carta ou um e-mail são exemplos de gêneros textuais usados principalmente para:',
    tip: 'Pensa na função principal de uma carta: ela serve para você conversar com alguém, mesmo estando longe.',
    funFact: 'Hoje, o e-mail é uma versão digital da carta tradicional, criada para agilizar a comunicação entre pessoas!',
    points: 1,
    options: [
      { id: 'A', text: 'Comunicação entre pessoas' },
      { id: 'B', text: 'Contar histórias de ficção apenas' },
      { id: 'C', text: 'Ensinar receitas' },
      { id: 'D', text: 'Divulgar notícias esportivas apenas' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'Qual é a diferença entre um texto "narrativo" e um texto "descritivo"?',
    tip: 'Pensa: contar o que aconteceu numa festa é diferente de descrever como era a decoração da festa — qual é narrativo e qual é descritivo?',
    funFact: 'Muitos textos misturam partes narrativas e descritivas ao mesmo tempo, como em um conto que descreve o cenário antes de contar a ação!',
    points: 1,
    options: [
      { id: 'A', text: 'Não existe diferença nenhuma' },
      { id: 'B', text: 'O narrativo só descreve lugares; o descritivo só conta histórias' },
      { id: 'C', text: 'O narrativo conta uma sequência de fatos; o descritivo detalha características de algo ou alguém' },
      { id: 'D', text: 'Ambos servem apenas para dar instruções' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'Um texto "argumentativo" tem como principal característica:',
    tip: 'Pensa em um texto que tenta te convencer de algo, usando razões e exemplos para sustentar uma ideia.',
    funFact: 'Saber escrever bons argumentos é uma habilidade útil não só na escola, mas também em debates e discussões do dia a dia!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas contar uma história de ficção' },
      { id: 'B', text: 'Listar ingredientes de uma receita' },
      { id: 'C', text: 'Descrever detalhadamente uma paisagem' },
      { id: 'D', text: 'Defender uma ideia com argumentos, buscando convencer o leitor' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'Reconhecer diferentes gêneros textuais é importante porque:',
    tip: 'Pensa em como você lê uma bula de remédio de um jeito diferente de como lê um conto de fadas — reconhecer o gênero ajuda nisso.',
    funFact: 'Saber identificar gêneros textuais ajuda até a perceber quando alguém está tentando te enganar com informações falsas!',
    points: 1,
    options: [
      { id: 'A', text: 'Não tem nenhuma utilidade no dia a dia' },
      { id: 'B', text: 'Ajuda a entender melhor a intenção e o contexto de cada texto que lemos' },
      { id: 'C', text: 'Serve apenas para decorar nomes difíceis' },
      { id: 'D', text: 'Só é útil para quem quer ser escritor profissional' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'Qual desses é um exemplo de gênero textual jornalístico?',
    tip: 'Pensa no tipo de texto que você encontra em jornais e sites de notícias, contando fatos reais e atuais.',
    funFact: 'O jornalismo existe há séculos, e sua função principal sempre foi informar a população sobre fatos importantes!',
    points: 1,
    options: [
      { id: 'A', text: 'Receita de bolo' },
      { id: 'B', text: 'Poema' },
      { id: 'C', text: 'Notícia de jornal' },
      { id: 'D', text: 'Carta pessoal' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'Em uma crônica, é comum encontrar:',
    tip: 'Lembra da Questão 2 — o que caracteriza esse gênero textual tão comum em jornais e revistas?',
    funFact: 'Grandes escritores brasileiros, como Machado de Assis e Clarice Lispector, também escreveram crônicas famosas!',
    points: 1,
    options: [
      { id: 'A', text: 'Reflexões sobre situações simples e cotidianas, muitas vezes com humor' },
      { id: 'B', text: 'Apenas fórmulas matemáticas' },
      { id: 'C', text: 'Somente listas de compras' },
      { id: 'D', text: 'Apenas informações técnicas sem nenhuma opinião' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'Um artigo de opinião publicado em um jornal geralmente apresenta:',
    tip: 'Lembra da Questão 4 — o que caracteriza um texto que defende um ponto de vista?',
    funFact: 'Diferente da notícia, o artigo de opinião pode e deve trazer a visão pessoal de quem escreve!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas uma receita culinária' },
      { id: 'B', text: 'Somente fatos sem nenhuma interpretação' },
      { id: 'C', text: 'Uma história de ficção fantástica' },
      { id: 'D', text: 'A visão do autor sobre um assunto, com argumentos para sustentá-la' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'O gênero "conto de fadas" é um tipo de narrativa que geralmente apresenta:',
    tip: 'Pensa em histórias como "Cinderela" ou "Branca de Neve" — o que elas têm de mágico ou fantástico?',
    funFact: 'Muitos contos de fadas que conhecemos hoje foram passados de geração em geração através da tradição oral, antes de serem escritos!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas fatos reais e comprovados' },
      { id: 'B', text: 'Elementos mágicos ou fantásticos, como fadas, bruxas ou reinos encantados' },
      { id: 'C', text: 'Somente instruções técnicas' },
      { id: 'D', text: 'Apenas dados estatísticos' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'Uma bula de remédio é um exemplo de gênero textual:',
    tip: 'Pensa na função de uma bula: ela conta uma história ou explica como e quando tomar um remédio com segurança?',
    funFact: 'As bulas de remédio precisam seguir regras rígidas para garantir que as informações sejam claras e seguras para todos!',
    points: 1,
    options: [
      { id: 'A', text: 'Poético' },
      { id: 'B', text: 'Narrativo de ficção' },
      { id: 'C', text: 'Instrucional/informativo, explicando como usar o medicamento' },
      { id: 'D', text: 'Argumentativo, tentando convencer alguém' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'Ao ler uma notícia, é importante que o texto seja:',
    tip: 'Lembra da Questão 3 — qual é o principal objetivo de uma notícia?',
    funFact: 'Jornalistas sérios sempre checam suas fontes antes de publicar uma notícia, para garantir que a informação seja verdadeira!',
    points: 1,
    options: [
      { id: 'A', text: 'Claro, objetivo e baseado em fatos verificáveis' },
      { id: 'B', text: 'Cheio de opiniões pessoais sem comprovação' },
      { id: 'C', text: 'Escrito de forma totalmente fictícia' },
      { id: 'D', text: 'Apenas uma lista de ingredientes' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'O gênero "anúncio publicitário" tem como principal objetivo:',
    tip: 'Pensa nos comerciais de televisão — qual é a intenção principal deles?',
    funFact: 'A publicidade usa técnicas de persuasão parecidas com as de textos argumentativos, para convencer o consumidor!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas informar fatos neutros' },
      { id: 'B', text: 'Contar uma história de ficção longa' },
      { id: 'C', text: 'Ensinar uma receita culinária' },
      { id: 'D', text: 'Convencer o público a comprar um produto ou serviço' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'Um bilhete, geralmente curto e informal, costuma ser usado para:',
    tip: 'Pensa em quando você escreve um recado rápido para alguém da família — que gênero textual é esse?',
    funFact: 'Apesar de curtos, bilhetes também seguem uma estrutura, geralmente com destinatário, mensagem e assinatura!',
    points: 1,
    options: [
      { id: 'A', text: 'Publicar notícias em jornais' },
      { id: 'B', text: 'Deixar um recado rápido para alguém' },
      { id: 'C', text: 'Escrever um romance inteiro' },
      { id: 'D', text: 'Fazer uma pesquisa científica' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'Qual desses gêneros textuais tem como característica central contar uma história, com personagens e enredo?',
    tip: 'Lembra da Questão 5 — qual gênero é uma narrativa curta, com personagens e um conflito?',
    funFact: 'Os contos são um dos gêneros narrativos mais antigos da humanidade, usados para transmitir ensinamentos e tradições!',
    points: 1,
    options: [
      { id: 'A', text: 'Receita culinária' },
      { id: 'B', text: 'Bula de remédio' },
      { id: 'C', text: 'Conto' },
      { id: 'D', text: 'Anúncio publicitário' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'Saber identificar o gênero de um texto ajuda o leitor a:',
    tip: 'Lembra da Questão 10 — por que é útil saber reconhecer diferentes gêneros textuais?',
    funFact: 'Reconhecer o gênero também ajuda a saber se um texto pretende informar, divertir, convencer ou instruir!',
    points: 1,
    options: [
      { id: 'A', text: 'Entender melhor o que esperar do texto e como interpretá-lo' },
      { id: 'B', text: 'Ficar confuso sobre o que está lendo' },
      { id: 'C', text: 'Ignorar completamente o conteúdo do texto' },
      { id: 'D', text: 'Nada relacionado à compreensão do texto' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Bernardo leu uma notícia no jornal sobre um evento esportivo na sua cidade. Qual é o principal objetivo desse tipo de texto?',
    tip: 'Lembra da Questão 3 — qual é o principal objetivo de uma notícia de jornal?',
    funFact: 'Bernardo pode comparar diferentes jornais para ver como cada um noticia o mesmo fato de formas um pouco diferentes!',
    points: 1,
    options: [
      { id: 'A', text: 'Convencer o leitor a comprar algo' },
      { id: 'B', text: 'Informar fatos reais de forma objetiva' },
      { id: 'C', text: 'Contar uma história totalmente inventada' },
      { id: 'D', text: 'Ensinar uma receita' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Depois, Bernardo escreveu um bilhete para a mãe avisando que estava na casa de um amigo. Que gênero textual ele usou?',
    tip: 'Lembra da Questão 18 — que gênero é usado para deixar um recado rápido e informal?',
    funFact: 'Mesmo curtos, os bilhetes de Bernardo ajudam bastante a manter a comunicação da família organizada!',
    points: 1,
    options: [
      { id: 'A', text: 'Notícia' },
      { id: 'B', text: 'Conto de fadas' },
      { id: 'C', text: 'Anúncio publicitário' },
      { id: 'D', text: 'Bilhete' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Na aula de Português, o professor pediu para Bernardo escrever um texto defendendo sua opinião sobre a importância da reciclagem. Que gênero textual ele deveria produzir?',
    tip: 'Lembra da Questão 4 e da Questão 9 — que gênero serve para defender um ponto de vista com argumentos?',
    funFact: 'Bernardo pode usar dados e exemplos reais para deixar seu texto de opinião ainda mais convincente!',
    points: 1,
    options: [
      { id: 'A', text: 'Receita culinária' },
      { id: 'B', text: 'Conto de fadas' },
      { id: 'C', text: 'Texto de opinião/argumentativo' },
      { id: 'D', text: 'Bula de remédio' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Bernardo leu uma crônica sobre o dia a dia de uma família, escrita de forma leve e com um toque de humor. O que caracteriza esse gênero textual?',
    tip: 'Lembra da Questão 2 e da Questão 12 — o que caracteriza uma crônica?',
    funFact: 'Bernardo pode até tentar escrever sua própria crônica sobre um dia comum da sua rotina!',
    points: 1,
    options: [
      { id: 'A', text: 'Comentar situações do cotidiano de forma reflexiva, muitas vezes com humor' },
      { id: 'B', text: 'Apresentar apenas dados científicos' },
      { id: 'C', text: 'Listar ingredientes de uma receita' },
      { id: 'D', text: 'Explicar como usar um medicamento' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Ajudando a avó na cozinha, Bernardo seguiu um texto que explicava, passo a passo, como fazer um bolo. Que gênero textual é esse?',
    tip: 'Lembra da Questão 6 — que gênero orienta passo a passo como preparar algo?',
    funFact: 'Bernardo pode notar que uma boa receita sempre tem uma lista de ingredientes e depois o modo de preparo, na ordem certa!',
    points: 1,
    options: [
      { id: 'A', text: 'Notícia' },
      { id: 'B', text: 'Receita culinária' },
      { id: 'C', text: 'Poema' },
      { id: 'D', text: 'Artigo de opinião' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Bernardo viu um anúncio na televisão tentando convencê-lo a comprar um brinquedo novo. Qual é o principal objetivo desse gênero textual?',
    tip: 'Lembra da Questão 17 — qual é a intenção principal de um anúncio publicitário?',
    funFact: 'Bernardo pode aprender a identificar técnicas de persuasão usadas em anúncios, ficando um consumidor mais consciente!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas informar fatos neutros' },
      { id: 'B', text: 'Contar uma história de ficção longa' },
      { id: 'C', text: 'Ensinar uma receita' },
      { id: 'D', text: 'Convencer o público a comprar o produto' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Bernardo leu um conto de fadas para a irmã mais nova, cheio de elementos mágicos, como fadas e reinos encantados. Isso é típico de qual gênero?',
    tip: 'Lembra da Questão 14 — qual gênero costuma ter elementos mágicos e fantásticos?',
    funFact: 'Bernardo pode notar que muitos contos de fadas têm uma lição de moral escondida no final da história!',
    points: 1,
    options: [
      { id: 'A', text: 'Notícia' },
      { id: 'B', text: 'Bula de remédio' },
      { id: 'C', text: 'Conto de fadas' },
      { id: 'D', text: 'Anúncio publicitário' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'O professor de Bernardo explicou que, ao ler qualquer texto, é importante identificar o gênero textual. Por que isso é importante?',
    tip: 'Lembra da Questão 10 e da Questão 20 — por que reconhecer o gênero de um texto é tão importante?',
    funFact: 'Bernardo está desenvolvendo uma habilidade de leitura que vai ajudá-lo em muitos momentos da vida, não só na escola!',
    points: 1,
    options: [
      { id: 'A', text: 'Ajuda a entender melhor a intenção e o contexto do texto' },
      { id: 'B', text: 'Não tem nenhuma utilidade' },
      { id: 'C', text: 'Serve só para confundir o leitor' },
      { id: 'D', text: 'É útil apenas para escritores profissionais' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Bernardo comparou uma notícia de jornal com um conto de fadas e percebeu uma grande diferença entre eles. Qual é essa diferença?',
    tip: 'Pensa em tudo que Bernardo aprendeu: notícia informa fatos reais, conto de fadas é uma história inventada — isso é igual ou diferente?',
    funFact: 'Essa diferença entre fato e ficção é uma das primeiras coisas que aprendemos a reconhecer ao ler diferentes tipos de texto!',
    points: 1,
    options: [
      { id: 'A', text: 'Não existe diferença nenhuma' },
      { id: 'B', text: 'A notícia apresenta fatos reais; o conto de fadas é uma narrativa de ficção' },
      { id: 'C', text: 'Ambos são exatamente iguais' },
      { id: 'D', text: 'Os dois são gêneros instrucionais' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'Ao final da aula, Bernardo entendeu que existem muitos gêneros textuais diferentes, cada um com um objetivo específico. O que ele deveria concluir sobre isso?',
    tip: 'Pensa em tudo que Bernardo estudou: notícia, crônica, conto, receita, anúncio — isso mostra pouca ou muita variedade de objetivos?',
    funFact: 'Parabéns, Bernardo! Agora você já sabe reconhecer vários gêneros textuais e entender a intenção por trás de cada um deles!',
    points: 1,
    options: [
      { id: 'A', text: 'Que todos os textos são exatamente iguais' },
      { id: 'B', text: 'Que só existe um tipo de texto no mundo' },
      { id: 'C', text: 'Que gêneros textuais não têm nenhuma utilidade' },
      { id: 'D', text: 'Que reconhecer o gênero ajuda a compreender melhor qualquer texto que lermos' },
    ],
    correctAnswer: 'D',
  },
];
