export const questoesIngles7AnoB3Av2 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "What is the comparative form of \"big\"?",
    tip: "Comparativo serve para comparar DUAS coisas, e geralmente usa \"-er\" no final de adjetivos curtos. Qual opção tem essa terminação?",
    funFact: "Quando o adjetivo termina em uma vogal + consoante, como \"big\", dobramos a consoante antes do \"-er\": \"bigger\"!",
    points: 1,
    options: [
      { id: "A", text: "Biggest" },
      { id: "B", text: "Bigger" },
      { id: "C", text: "More big" },
      { id: "D", text: "Big" },
    ],
    correctAnswer: "B",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "What is the superlative form of \"tall\"?",
    tip: "Superlativo serve para comparar algo com TODO o resto (o mais alto de todos). Geralmente usa \"-est\". Qual opção tem essa terminação?",
    funFact: "\"The tallest\" sempre vem acompanhado de \"the\" — é por isso que dizemos \"the tallest building in the world\"!",
    points: 1,
    options: [
      { id: "A", text: "Taller" },
      { id: "B", text: "More tall" },
      { id: "C", text: "Most tall" },
      { id: "D", text: "Tallest" },
    ],
    correctAnswer: "D",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "Which suffix do we usually add to short adjectives to make comparatives?",
    tip: "Pense em \"small\" → \"smaller\". Qual terminação foi adicionada?",
    funFact: "Adjetivos com uma só sílaba, como \"big\", \"tall\" e \"small\", quase sempre usam \"-er\" e \"-est\"!",
    points: 1,
    options: [
      { id: "A", text: "-er" },
      { id: "B", text: "-est" },
      { id: "C", text: "more" },
      { id: "D", text: "most" },
    ],
    correctAnswer: "A",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "Which word do we use before long adjectives to make comparatives (like \"beautiful\")?",
    tip: "Adjetivos longos (com 3 ou mais sílabas) não recebem \"-er\" no final — usamos uma palavra separada antes deles. Qual das opções é essa palavra?",
    funFact: "Dizer \"beautifuler\" soaria muito estranho em inglês — por isso usamos \"more beautiful\" para adjetivos longos!",
    points: 1,
    options: [
      { id: "A", text: "-er" },
      { id: "B", text: "-est" },
      { id: "C", text: "more" },
      { id: "D", text: "most" },
    ],
    correctAnswer: "C",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "What is the comparative form of \"happy\"?",
    tip: "Quando o adjetivo termina em consoante + \"y\", trocamos o \"y\" por \"i\" antes de adicionar \"-er\". Qual opção faz isso certo?",
    funFact: "Essa mesma regra do \"y\" para \"i\" também vale para outras palavras, como \"funny\" → \"funnier\"!",
    points: 1,
    options: [
      { id: "A", text: "Happyer" },
      { id: "B", text: "More happy" },
      { id: "C", text: "Happiest" },
      { id: "D", text: "Happier" },
    ],
    correctAnswer: "D",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "What is the superlative form of \"fast\"?",
    tip: "\"Fast\" é um adjetivo curto, então o superlativo usa \"-est\", não \"most\". Qual opção está certa?",
    funFact: "O animal terrestre mais \"fast\" do mundo é o guepardo, que pode chegar a 110 km/h em poucos segundos!",
    points: 1,
    options: [
      { id: "A", text: "Faster" },
      { id: "B", text: "Fastest" },
      { id: "C", text: "More fast" },
      { id: "D", text: "Most fast" },
    ],
    correctAnswer: "B",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "Which word usually comes after a comparative adjective?",
    tip: "Pense na frase \"Ele é mais alto DO QUE eu\". Em inglês, qual palavra substitui o \"do que\"?",
    funFact: "\"Than\" é usado só com comparativos — nunca aparece junto com superlativos como \"the tallest\"!",
    points: 1,
    options: [
      { id: "A", text: "the" },
      { id: "B", text: "a" },
      { id: "C", text: "than" },
      { id: "D", text: "most" },
    ],
    correctAnswer: "C",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "What is the comparative form of \"small\"?",
    tip: "\"Small\" é um adjetivo curto, então usamos \"-er\". Qual opção tem essa terminação?",
    funFact: "O menor país do mundo é o Vaticano — bem menor, ou \"smaller\", que muitos bairros de cidades grandes!",
    points: 1,
    options: [
      { id: "A", text: "Smaller" },
      { id: "B", text: "Smallest" },
      { id: "C", text: "More small" },
      { id: "D", text: "Most small" },
    ],
    correctAnswer: "A",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "What is the superlative form of \"good\"?",
    tip: "\"Good\" é um adjetivo irregular — ele não segue a regra do \"-est\". Pense: \"o melhor de todos\" — qual palavra usamos?",
    funFact: "\"Good\", \"better\" e \"best\" são totalmente diferentes entre si — isso é parecido com \"bom, melhor, ótimo\" em português!",
    points: 1,
    options: [
      { id: "A", text: "Gooder" },
      { id: "B", text: "Best" },
      { id: "C", text: "Goodest" },
      { id: "D", text: "More good" },
    ],
    correctAnswer: "B",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "What is the comparative form of \"bad\"?",
    tip: "\"Bad\" também é irregular, assim como \"good\". Pense: \"isso é pior do que aquilo\" — qual palavra combina?",
    funFact: "\"Worse\" e \"worst\" vêm de uma palavra bem antiga em inglês que já significava \"mais para baixo\" ou \"inferior\"!",
    points: 1,
    options: [
      { id: "A", text: "Badder" },
      { id: "B", text: "Baddest" },
      { id: "C", text: "More bad" },
      { id: "D", text: "Worse" },
    ],
    correctAnswer: "D",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Complete: \"An elephant is ___ than a mouse.\"",
    tip: "A frase compara DUAS coisas (elefante e rato) e tem a palavra \"than\" depois. Isso pede um comparativo. Qual opção é a forma comparativa certa?",
    funFact: "Um elefante pode pesar mais de 6.000 kg, enquanto um camundongo pesa só cerca de 20 gramas!",
    points: 1,
    options: [
      { id: "A", text: "big" },
      { id: "B", text: "biggest" },
      { id: "C", text: "bigger" },
      { id: "D", text: "more big" },
    ],
    correctAnswer: "C",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Complete: \"Mount Everest is the ___ mountain in the world.\"",
    tip: "A frase compara com TODAS as montanhas do mundo (\"in the world\"), então precisa de um superlativo, com \"the\" antes.",
    funFact: "O Monte Everest continua crescendo um pouquinho todos os anos, por causa do movimento das placas tectônicas!",
    points: 1,
    options: [
      { id: "A", text: "tallest" },
      { id: "B", text: "taller" },
      { id: "C", text: "more tall" },
      { id: "D", text: "tall" },
    ],
    correctAnswer: "A",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "Complete: \"This book is ___ than that one. I understood it better.\"",
    tip: "\"Interesting\" é um adjetivo longo, então não usamos \"-er\". E a frase tem \"than\", pedindo um comparativo, não superlativo.",
    funFact: "Ler livros interessantes regularmente ajuda a melhorar o vocabulário e a criatividade, segundo vários estudos!",
    points: 1,
    options: [
      { id: "A", text: "interesting" },
      { id: "B", text: "interestinger" },
      { id: "C", text: "most interesting" },
      { id: "D", text: "more interesting" },
    ],
    correctAnswer: "D",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "Complete: \"My sister is ___ than me. She was born first.\"",
    tip: "\"Old\" é um adjetivo curto, e a frase tem \"than\", pedindo um comparativo. Qual opção usa \"-er\" corretamente?",
    funFact: "Em muitas culturas, o irmão ou irmã mais velho(a) tem a tradição de cuidar dos mais novos — isso é bem comum no Brasil também!",
    points: 1,
    options: [
      { id: "A", text: "old" },
      { id: "B", text: "older" },
      { id: "C", text: "oldest" },
      { id: "D", text: "more old" },
    ],
    correctAnswer: "B",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Complete: \"This is the ___ day of my life! I'm so happy!\"",
    tip: "A frase tem \"the\" antes do espaço, pedindo um superlativo. \"Good\" é irregular — qual é a forma superlativa certa?",
    funFact: "Dizer \"the best day of my life\" é uma expressão bem comum em inglês para mostrar muita emoção e alegria!",
    points: 1,
    options: [
      { id: "A", text: "best" },
      { id: "B", text: "better" },
      { id: "C", text: "goodest" },
      { id: "D", text: "more good" },
    ],
    correctAnswer: "A",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "Choose the correct sentence.",
    tip: "\"Fast\" é curto, então usa \"-er\" (não \"more\") para comparar duas coisas, e precisa da palavra \"than\" depois.",
    funFact: "Os carros de Fórmula 1 podem chegar a mais de 350 km/h — super \"faster\" que um carro comum!",
    points: 1,
    options: [
      { id: "A", text: "This car is fast than that one" },
      { id: "B", text: "This car is more fast than that one" },
      { id: "C", text: "This car is faster than that one" },
      { id: "D", text: "This car is fastest than that one" },
    ],
    correctAnswer: "C",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "Complete: \"Of all the students, Maria is the ___.\"",
    tip: "\"Of all the students\" (de todos os alunos) é uma pista forte de superlativo — comparando com o grupo inteiro.",
    funFact: "Expressões como \"of all\" ou \"in the world\" quase sempre vêm acompanhadas de superlativos nas frases em inglês!",
    points: 1,
    options: [
      { id: "A", text: "tall" },
      { id: "B", text: "tallest" },
      { id: "C", text: "taller" },
      { id: "D", text: "more tall" },
    ],
    correctAnswer: "B",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "Complete: \"Winter is ___ than summer in my city.\"",
    tip: "A frase já tem a palavra \"than\" depois do espaço, então a resposta não deve repetir \"than\". \"Cold\" é curto, use \"-er\".",
    funFact: "No Brasil, mesmo no inverno, muitas cidades do litoral não ficam tão frias quanto em países com neve!",
    points: 1,
    options: [
      { id: "A", text: "cold" },
      { id: "B", text: "coldest" },
      { id: "C", text: "colder than than" },
      { id: "D", text: "colder" },
    ],
    correctAnswer: "D",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "Choose the correct sentence.",
    tip: "\"Easy\" termina em consoante + \"y\", então no superlativo trocamos \"y\" por \"i\" e adicionamos \"-est\": fica parecido com \"happy\" → \"happiest\".",
    funFact: "A regra do \"y\" para \"i\" também vale para o comparativo: \"easy\" → \"easier\"!",
    points: 1,
    options: [
      { id: "A", text: "This is the most easy question" },
      { id: "B", text: "This is the easy most question" },
      { id: "C", text: "This is the easiest question" },
      { id: "D", text: "This is the easier question" },
    ],
    correctAnswer: "C",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "Complete: \"A cheetah is the ___ land animal in the world.\"",
    tip: "\"In the world\" mostra que é uma comparação com TODOS os animais, pedindo superlativo. \"Fast\" é curto, usa \"-est\".",
    funFact: "A chita (cheetah) consegue acelerar de 0 a 100 km/h em menos de 3 segundos — mais rápido que muitos carros esportivos!",
    points: 1,
    options: [
      { id: "A", text: "fastest" },
      { id: "B", text: "faster" },
      { id: "C", text: "more fast" },
      { id: "D", text: "most fast" },
    ],
    correctAnswer: "A",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Bernardo compared his height with his sister's. He is taller than her. Which sentence is correct?",
    tip: "\"Tall\" é um adjetivo curto, então usa \"-er\" para comparar duas pessoas, com \"than\" depois.",
    funFact: "O crescimento das crianças costuma dar \"estirões\" (saltos de altura) principalmente durante a puberdade!",
    points: 1,
    options: [
      { id: "A", text: "Bernardo is tall than his sister" },
      { id: "B", text: "Bernardo is taller than his sister" },
      { id: "C", text: "Bernardo is more tall than his sister" },
      { id: "D", text: "Bernardo is tallest than his sister" },
    ],
    correctAnswer: "B",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Bernardo thinks math is more difficult than English. Which sentence is correct?",
    tip: "\"Difficult\" é um adjetivo longo (3 sílabas), então não usamos \"-er\" — usamos \"more\" antes dele.",
    funFact: "Cada pessoa acha uma matéria mais fácil ou mais difícil, dependendo do seu jeito de aprender — isso é bem normal!",
    points: 1,
    options: [
      { id: "A", text: "Math is difficult than English" },
      { id: "B", text: "Math is difficulter than English" },
      { id: "C", text: "Math is most difficult than English" },
      { id: "D", text: "Math is more difficult than English" },
    ],
    correctAnswer: "D",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Of all his classmates, Bernardo runs the fastest. Which sentence is correct?",
    tip: "\"Of all his classmates\" (de todos os colegas) pede um superlativo, com \"the\" antes de \"fastest\".",
    funFact: "Correr regularmente ajuda a fortalecer o coração e os pulmões, além de deixar o corpo mais disposto!",
    points: 1,
    options: [
      { id: "A", text: "Bernardo is fast of all his classmates" },
      { id: "B", text: "Bernardo is faster of all his classmates" },
      { id: "C", text: "Bernardo is the fastest of all his classmates" },
      { id: "D", text: "Bernardo is more fast of all his classmates" },
    ],
    correctAnswer: "C",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Bernardo says his dog is bigger than his friend's dog. Which sentence is correct?",
    tip: "\"Big\" é curto, então dobra a última letra e adiciona \"-er\": \"bigger\". E a frase precisa de \"than\" para comparar dois cachorros.",
    funFact: "Algumas raças de cães, como o São Bernardo, podem pesar mais de 80 kg — gigantes de verdade!",
    points: 1,
    options: [
      { id: "A", text: "Bernardo's dog is bigger than his friend's dog" },
      { id: "B", text: "Bernardo's dog is big than his friend's dog" },
      { id: "C", text: "Bernardo's dog is more big than his friend's dog" },
      { id: "D", text: "Bernardo's dog is biggest than his friend's dog" },
    ],
    correctAnswer: "A",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Bernardo thinks his new video game is the best game he has ever played. Which sentence is correct?",
    tip: "\"Good\" é irregular. Pense no superlativo dele: não existe \"goodest\" — qual é a forma certa?",
    funFact: "A indústria de videogames já vende mais do que a indústria do cinema e da música juntas, no mundo todo!",
    points: 1,
    options: [
      { id: "A", text: "This is the goodest game" },
      { id: "B", text: "This is the best game" },
      { id: "C", text: "This is the better game" },
      { id: "D", text: "This is the more good game" },
    ],
    correctAnswer: "B",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Bernardo's grandfather is the oldest person in the family. Which sentence is correct?",
    tip: "\"In the family\" (na família) compara com TODOS os membros, pedindo superlativo com \"the\" e \"-est\".",
    funFact: "Em muitas famílias, os avós são responsáveis por contar histórias e tradições para os mais novos — um papel muito importante!",
    points: 1,
    options: [
      { id: "A", text: "Grandfather is old in the family" },
      { id: "B", text: "Grandfather is older in the family" },
      { id: "C", text: "Grandfather is more old in the family" },
      { id: "D", text: "Grandfather is the oldest person in the family" },
    ],
    correctAnswer: "D",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Bernardo says that, of all the subjects, Science is the most interesting for him. Which sentence is correct?",
    tip: "\"Interesting\" é um adjetivo longo, então o superlativo usa \"the most\", nunca \"-est\" no final.",
    funFact: "Experiências práticas, como fazer experimentos, costumam tornar aulas de Ciências ainda mais interessantes para os alunos!",
    points: 1,
    options: [
      { id: "A", text: "Science is interesting for him" },
      { id: "B", text: "Science is more interesting for him" },
      { id: "C", text: "Science is the most interesting subject for him" },
      { id: "D", text: "Science is the interestingest subject for him" },
    ],
    correctAnswer: "C",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Bernardo compared two pizzas and said one was tastier than the other. Which sentence is correct?",
    tip: "\"Tasty\" termina em consoante + \"y\", então trocamos o \"y\" por \"i\" antes do \"-er\": \"tastier\". E a frase precisa de \"than\".",
    funFact: "A pizza foi criada na Itália, mas se tornou um dos pratos mais populares do mundo, incluindo no Brasil!",
    points: 1,
    options: [
      { id: "A", text: "This pizza is tastier than the other one" },
      { id: "B", text: "This pizza is tasty than the other one" },
      { id: "C", text: "This pizza is more tasty than the other one" },
      { id: "D", text: "This pizza is tastiest than the other one" },
    ],
    correctAnswer: "A",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Bernardo's new shoes are more comfortable than his old ones. Which sentence is correct?",
    tip: "\"Comfortable\" é um adjetivo longo, então usamos \"more\" antes dele, nunca \"-er\" no final.",
    funFact: "Tênis confortáveis ajudam a prevenir dores nos pés e nas costas — por isso escolher o calçado certo é importante!",
    points: 1,
    options: [
      { id: "A", text: "My new shoes are comfortable than my old ones" },
      { id: "B", text: "My new shoes are more comfortable than my old ones" },
      { id: "C", text: "My new shoes are comfortabler than my old ones" },
      { id: "D", text: "My new shoes are most comfortable than my old ones" },
    ],
    correctAnswer: "B",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Bernardo believes that, out of all his friends, Lucas is the funniest. Which sentence is correct?",
    tip: "\"Out of all his friends\" pede superlativo. \"Funny\" termina em consoante + \"y\", então vira \"funniest\" (troca o \"y\" por \"i\" + \"-est\").",
    funFact: "Ter amigos \"funny\" (divertidos) é ótimo para a saúde mental — rir junto fortalece as amizades!",
    points: 1,
    options: [
      { id: "A", text: "Lucas is funny of all my friends" },
      { id: "B", text: "Lucas is funnier of all my friends" },
      { id: "C", text: "Lucas is more funny of all my friends" },
      { id: "D", text: "Lucas is the funniest of all my friends" },
    ],
    correctAnswer: "D",
  },
];
