export const questoesGeografia7AnoB4Av1 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'O Brasil é considerado um país altamente urbanizado. O que isso significa?',
    tip: 'Pensa em como a maioria das pessoas hoje vive — em cidades ou no campo?',
    funFact: 'Hoje, mais de 85% da população brasileira vive em áreas urbanas — um dos maiores índices de urbanização do mundo em desenvolvimento!',
    points: 1,
    options: [
      { id: 'A', text: 'Que a maioria das pessoas vive em áreas rurais' },
      { id: 'B', text: 'Que a maioria da população vive em cidades' },
      { id: 'C', text: 'Que o país não tem cidades' },
      { id: 'D', text: 'Que todas as pessoas moram em fazendas' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'O êxodo rural é um fenômeno que marcou o Brasil ao longo do século XX. O que é êxodo rural?',
    tip: '"Êxodo" vem do grego e significa saída — de onde as pessoas saem no êxodo rural?',
    funFact: 'Entre 1950 e 2000, milhões de brasileiros deixaram o campo em busca de empregos nas indústrias das grandes cidades do Sudeste!',
    points: 1,
    options: [
      { id: 'A', text: 'A migração do campo para as cidades em busca de melhores condições de vida e trabalho' },
      { id: 'B', text: 'A migração das cidades para o campo' },
      { id: 'C', text: 'O crescimento das fazendas no interior' },
      { id: 'D', text: 'A saída de pessoas do Brasil para outros países' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'A densidade demográfica mede a concentração de pessoas em um território. Qual é a definição correta?',
    tip: 'Pensa em quantas pessoas vivem em cada quilômetro quadrado de uma área!',
    funFact: 'A densidade demográfica do estado de São Paulo é de mais de 170 hab/km², enquanto o Amazonas tem menos de 3 hab/km²!',
    points: 1,
    options: [
      { id: 'A', text: 'O número total de habitantes de um país' },
      { id: 'B', text: 'O número de cidades em uma região' },
      { id: 'C', text: 'O número de habitantes por quilômetro quadrado de uma área' },
      { id: 'D', text: 'A velocidade de crescimento da população' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'As metrópoles são as maiores cidades do Brasil. Qual é a maior metrópole brasileira?',
    tip: 'Pensa na cidade com a maior concentração de indústrias, serviços e universidades do país!',
    funFact: 'A Região Metropolitana de São Paulo tem mais de 22 milhões de pessoas — é uma das maiores aglomerações urbanas do mundo!',
    points: 1,
    options: [
      { id: 'A', text: 'Belo Horizonte' },
      { id: 'B', text: 'São Paulo' },
      { id: 'C', text: 'Salvador' },
      { id: 'D', text: 'Brasília' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'O planejamento urbano é fundamental para o desenvolvimento das cidades. O que é planejamento urbano?',
    tip: 'Pensa no que acontece quando uma cidade cresce sem organização — trânsito, falta de água, favelas!',
    funFact: 'Curitiba (PR) é reconhecida internacionalmente como modelo de planejamento urbano, especialmente pelo seu sistema de transporte público!',
    points: 1,
    options: [
      { id: 'A', text: 'A construção de prédios sem regras' },
      { id: 'B', text: 'A organização do crescimento e uso do espaço urbano, com previsão de áreas para moradia, trabalho, transporte e serviços públicos' },
      { id: 'C', text: 'A proibição de novas construções nas cidades' },
      { id: 'D', text: 'O controle da entrada de novas pessoas nas cidades' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'A Região Sudeste concentra mais da metade do PIB (produto interno bruto) do Brasil. Quais estados a compõem?',
    tip: 'Pensa nas quatro siglas mais famosas do Sudeste — SP, RJ, MG e ES!',
    funFact: 'São Paulo sozinho produz mais de 30% de toda a riqueza do Brasil — é o estado economicamente mais poderoso do país!',
    points: 1,
    options: [
      { id: 'A', text: 'Rio Grande do Sul, Santa Catarina, Paraná e São Paulo' },
      { id: 'B', text: 'Bahia, Pernambuco, Ceará e Maranhão' },
      { id: 'C', text: 'Mato Grosso, Mato Grosso do Sul, Goiás e Distrito Federal' },
      { id: 'D', text: 'São Paulo, Rio de Janeiro, Minas Gerais e Espírito Santo' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'A desigualdade urbana é um dos maiores problemas das cidades brasileiras. O que é desigualdade urbana?',
    tip: 'Pensa na diferença entre bairros ricos com boa infraestrutura e favelas sem saneamento básico na mesma cidade!',
    funFact: 'No Rio de Janeiro, alguns dos bairros mais ricos e das favelas mais populosas do Brasil ficam lado a lado — símbolo da desigualdade urbana!',
    points: 1,
    options: [
      { id: 'A', text: 'A diferença de tamanho entre cidades pequenas e grandes' },
      { id: 'B', text: 'A concentração de serviços públicos em áreas específicas da cidade, enquanto outras áreas vivem em condições precárias' },
      { id: 'C', text: 'O número de carros por habitante em cada cidade' },
      { id: 'D', text: 'A diferença de temperatura entre os bairros de uma cidade' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'Por que a urbanização acelerada no Brasil gerou problemas ambientais nas cidades?',
    tip: 'Pensa no que acontece com o lixo, o esgoto e o desmatamento quando muitas pessoas se concentram numa área pequena!',
    funFact: 'São Paulo produz mais de 20.000 toneladas de lixo por dia — um desafio imenso de gestão ambiental urbana!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque as cidades são sempre limpas e organizadas' },
      { id: 'B', text: 'Porque o crescimento rápido e desordenado gerou falta de saneamento, impermeabilização do solo, poluição do ar e enchentes' },
      { id: 'C', text: 'Porque as pessoas no campo poluem mais que nas cidades' },
      { id: 'D', text: 'Porque a urbanização sempre melhora o ambiente' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'As favelas são uma realidade em muitas cidades brasileiras. O que explica o surgimento delas?',
    tip: 'Pensa no êxodo rural — quando muitas pessoas migram para as cidades sem ter dinheiro para pagar aluguel, onde elas vão morar?',
    funFact: 'A Rocinha, no Rio de Janeiro, é uma das maiores favelas da América do Sul, com mais de 100.000 habitantes!',
    points: 1,
    options: [
      { id: 'A', text: 'O crescimento urbano acelerado sem políticas de habitação para populações de baixa renda, que ocupam áreas informais' },
      { id: 'B', text: 'A escolha das pessoas por morar de forma diferente' },
      { id: 'C', text: 'A ausência total de empregos nas cidades' },
      { id: 'D', text: 'A proibição do governo de construir prédios populares' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'A distribuição da população brasileira é desigual no território. Qual região tem maior densidade demográfica?',
    tip: 'Pensa na região com mais indústrias, empregos e cidades grandes — para onde as pessoas foram no êxodo rural?',
    funFact: 'A Região Sudeste tem cerca de 42% de toda a população brasileira, mas ocupa apenas 11% do território!',
    points: 1,
    options: [
      { id: 'A', text: 'Região Norte' },
      { id: 'B', text: 'Região Centro-Oeste' },
      { id: 'C', text: 'Região Sul' },
      { id: 'D', text: 'Região Sudeste' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'A industrialização foi um fator decisivo para a urbanização do Brasil. Como ela contribuiu para o crescimento das cidades?',
    tip: 'Pensa: onde ficam as fábricas? E para onde as pessoas foram trabalhar nelas?',
    funFact: 'O ABC Paulista (Santo André, São Bernardo e São Caetano) foi o coração industrial do Brasil nos anos 1950-80, atraindo milhões de migrantes!',
    points: 1,
    options: [
      { id: 'A', text: 'Ao criar empregos nas fábricas, atraiu trabalhadores do campo para as cidades industriais' },
      { id: 'B', text: 'A industrialização não tem relação com a urbanização' },
      { id: 'C', text: 'A industrialização dispersou a população para o campo' },
      { id: 'D', text: 'As fábricas foram instaladas no campo, não nas cidades' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'Bernardo aprende que São Paulo é chamada de "locomotiva do Brasil". O que esse apelido significa?',
    tip: 'Uma locomotiva puxa o trem — ela leva os outros vagões. Qual sentido isso tem para São Paulo?',
    funFact: 'São Paulo abriga a maior bolsa de valores da América Latina (B3) e é o maior polo financeiro do hemisfério sul!',
    points: 1,
    options: [
      { id: 'A', text: 'Que São Paulo tem muitos trens subterrâneos' },
      { id: 'B', text: 'Que São Paulo é o maior produtor de locomotivas do Brasil' },
      { id: 'C', text: 'Que São Paulo é o estado com maior dinamismo econômico, impulsionando o crescimento do restante do país' },
      { id: 'D', text: 'Que São Paulo é a cidade mais fria do Brasil' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'O saneamento básico inclui abastecimento de água, coleta e tratamento de esgoto e gestão do lixo. Por que ele é fundamental para as cidades?',
    tip: 'Pensa no que acontece quando não tem água limpa e esgoto a céu aberto — quais doenças surgem?',
    funFact: 'Ainda hoje, milhões de brasileiros não têm acesso ao saneamento básico — especialmente nas periferias e em cidades do Norte e Nordeste!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque é apenas um luxo para cidades ricas' },
      { id: 'B', text: 'Porque garante saúde pública, qualidade de vida e preservação ambiental' },
      { id: 'C', text: 'Porque saneamento só importa para o campo' },
      { id: 'D', text: 'Porque é obrigatório apenas em capitais' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'Bernardo lê que Brasília foi fundada em 1960 para ser a nova capital do Brasil. Qual era o objetivo principal de transferir a capital para o interior?',
    tip: 'Pensa em por que uma capital no interior seria melhor para desenvolver o Brasil inteiro, e não só o litoral!',
    funFact: 'Antes de Brasília, o Rio de Janeiro era a capital do Brasil — a mudança foi uma aposta ousada de JK para interiorizar o desenvolvimento!',
    points: 1,
    options: [
      { id: 'A', text: 'Desenvolver o interior do Brasil, integrando as regiões e reduzindo o desequilíbrio regional' },
      { id: 'B', text: 'Ficar mais perto do Oceano Atlântico' },
      { id: 'C', text: 'Porque o Rio de Janeiro não tinha espaço' },
      { id: 'D', text: 'Para facilitar a exportação de produtos' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'Qual é o principal problema gerado pelo crescimento desordenado das cidades brasileiras?',
    tip: 'Pensa em tudo que cresce junto com as cidades sem planejamento: favelas, trânsito, poluição, falta de serviços!',
    funFact: 'O "tempo de deslocamento" no trânsito paulistano é um dos maiores do mundo — em dias de congestionamento, pode-se passar mais de 3 horas no carro!',
    points: 1,
    options: [
      { id: 'A', text: 'O excesso de áreas verdes e parques' },
      { id: 'B', text: 'A concentração de empregos apenas no campo' },
      { id: 'C', text: 'A falta de trânsito nas grandes cidades' },
      { id: 'D', text: 'A formação de periferias com carência de infraestrutura, serviços públicos precários e problemas sociais' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'A "hierarquia urbana" classifica as cidades pelo nível de serviços e influência que exercem. Qual é a ordem crescente correta?',
    tip: 'Pensa do menor para o maior: uma cidadezinha, uma cidade média, uma capital regional, uma metrópole!',
    funFact: 'Uma metrópole global como São Paulo influencia economicamente não só o Brasil, mas toda a América do Sul e outros continentes!',
    points: 1,
    options: [
      { id: 'A', text: 'Metrópole → Cidade média → Pequena cidade → Aldeia' },
      { id: 'B', text: 'Pequena cidade → Cidade média → Capital regional → Metrópole' },
      { id: 'C', text: 'Aldeia → Metrópole → Capital regional → Pequena cidade' },
      { id: 'D', text: 'Capital regional → Metrópole → Pequena cidade → Cidade média' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'A violência urbana é um problema sério nas grandes cidades brasileiras. Qual fator socioeconômico está diretamente ligado à violência urbana?',
    tip: 'Pensa nas relações entre pobreza, desigualdade, falta de oportunidades e violência!',
    funFact: 'Pesquisas mostram que cidades com maior desigualdade de renda tendem a ter maiores índices de violência — mas a relação é complexa e envolve muitos fatores!',
    points: 1,
    options: [
      { id: 'A', text: 'Excesso de áreas verdes' },
      { id: 'B', text: 'Muitos museus e teatros' },
      { id: 'C', text: 'A desigualdade social e a falta de oportunidades de emprego, educação e serviços públicos' },
      { id: 'D', text: 'Temperatura alta nas cidades' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'A "ilha de calor" é um fenômeno urbano. O que é isso?',
    tip: 'Pensa no que acontece com a temperatura num bairro cheio de asfalto e prédios comparado a um parque!',
    funFact: 'A ilha de calor em São Paulo pode fazer a temperatura no centro da cidade ser até 8°C mais alta do que nas áreas verdes ao redor!',
    points: 1,
    options: [
      { id: 'A', text: 'Uma ilha no meio da cidade para banho' },
      { id: 'B', text: 'Quando a temperatura nas áreas urbanas é mais alta do que nas áreas rurais ao redor, por causa do asfalto, edifícios e falta de vegetação' },
      { id: 'C', text: 'Um fenômeno que só ocorre em cidades litorâneas' },
      { id: 'D', text: 'Uma área de neve dentro da cidade' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'Bernardo descobre que a Região Norte tem a maior área territorial do Brasil, mas é a menos populosa. Por que isso acontece?',
    tip: 'Pensa nas dificuldades de viver na Amazônia — acesso, serviços, empregos, infraestrutura!',
    funFact: 'A Região Norte tem cerca de 40% do território nacional, mas menos de 10% da população — reflexo das dificuldades históricas de ocupação da Amazônia!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque a Região Norte não tem terras' },
      { id: 'B', text: 'Porque a floresta, o clima e a dificuldade de acesso limitaram historicamente a ocupação humana' },
      { id: 'C', text: 'Porque o governo proibiu moradores na região' },
      { id: 'D', text: 'Porque o clima é polar' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'Na escola, Bernardo estuda sobre o "inchaço urbano" das metrópoles brasileiras. O que esse termo significa?',
    tip: 'Pensa no que acontece quando uma cidade cresce rápido demais sem estrutura para receber tanta gente!',
    funFact: 'O inchaço urbano foi tão intenso que cidades como São Paulo cresceram mais em 50 anos do que países inteiros cresceram em séculos!',
    points: 1,
    options: [
      { id: 'A', text: 'O crescimento planejado e ordenado das cidades' },
      { id: 'B', text: 'O crescimento desordenado e acelerado das cidades, gerando problemas de infraestrutura, habitação e serviços' },
      { id: 'C', text: 'Apenas o aumento do número de prédios' },
      { id: 'D', text: 'A redução da população urbana' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Bernardo pesquisa sobre o "êxodo urbano" — um fenômeno mais recente onde pessoas saem das grandes cidades. Por que isso acontece?',
    tip: 'Pensa: depois de tudo que cresceu nas cidades, por que alguém quereria ir embora?',
    funFact: 'A pandemia de COVID-19 acelerou o êxodo urbano no Brasil, com mais pessoas buscando cidades médias e interiores com melhor qualidade de vida!',
    points: 1,
    options: [
      { id: 'A', text: 'Pela fuga da violência, alto custo de vida e degradação da qualidade de vida nas grandes metrópoles' },
      { id: 'B', text: 'Porque todas as fábricas foram para o campo' },
      { id: 'C', text: 'Porque as cidades foram destruídas' },
      { id: 'D', text: 'Não existe êxodo urbano no Brasil' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Bernardo faz um mapa da distribuição da população no Brasil. O que ele observa sobre a região litorânea?',
    tip: 'Pensa em onde a colonização começou e onde as maiores cidades se desenvolveram historicamente!',
    funFact: 'Mais de 50% da população brasileira vive a menos de 200 km do litoral — a colonização europeia partiu do litoral e as cidades cresceram por lá!',
    points: 1,
    options: [
      { id: 'A', text: 'A faixa litorânea é a menos populosa do Brasil' },
      { id: 'B', text: 'A faixa litorânea concentra grande parte da população, por ser onde se desenvolveram historicamente as principais cidades' },
      { id: 'C', text: 'O interior do Brasil é mais populoso que o litoral' },
      { id: 'D', text: 'A população está igualmente distribuída por todo o território' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Bernardo ouve falar de "conurbação" entre cidades. O que é isso?',
    tip: 'Pensa em duas ou mais cidades que cresceram tanto que suas bordas se "juntaram" — formando uma mancha urbana contínua!',
    funFact: 'A Grande São Paulo abrange mais de 30 municípios que se uniram por conurbação, formando uma das maiores manchas urbanas do planeta!',
    points: 1,
    options: [
      { id: 'A', text: 'Uma cidade dividida em dois países' },
      { id: 'B', text: 'A fusão política de dois municípios' },
      { id: 'C', text: 'O processo em que cidades vizinhas crescem tanto que suas áreas urbanas se encontram e formam uma mancha contínua' },
      { id: 'D', text: 'A demolição de bairros antigos para construção de novos' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Bernardo faz uma redação sobre os desafios do crescimento das cidades. Qual problema ele não deve incluir?',
    tip: 'Elimine a opção que na verdade é uma vantagem das cidades, não um problema!',
    funFact: 'Apesar dos problemas, as cidades também concentram as maiores oportunidades de educação, saúde, cultura e emprego — é por isso que as pessoas continuam migrando para elas!',
    points: 1,
    options: [
      { id: 'A', text: 'Trânsito caótico e poluição do ar' },
      { id: 'B', text: 'Violência urbana e criminalidade' },
      { id: 'C', text: 'Maior acesso a serviços de saúde e educação' },
      { id: 'D', text: 'Favelização e falta de moradia' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Bernardo precisa identificar a região brasileira que mais recebeu migrantes do Nordeste ao longo do século XX. Qual foi ela?',
    tip: 'Pensa em onde estavam as fábricas e os empregos que atraíram os nordestinos!',
    funFact: 'São Paulo recebeu tantos migrantes nordestinos que hoje a cidade tem mais de 3 milhões de descendentes de nordestinos — influenciando muito a cultura paulistana!',
    points: 1,
    options: [
      { id: 'A', text: 'Região Norte' },
      { id: 'B', text: 'Região Centro-Oeste' },
      { id: 'C', text: 'Região Sul' },
      { id: 'D', text: 'Região Sudeste, especialmente São Paulo' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Bernardo lê sobre o "transporte público como solução para o trânsito". Por que o transporte público é importante no contexto da urbanização?',
    tip: 'Pensa em quantos carros menos haveria nas ruas se todo mundo usasse ônibus ou metrô!',
    funFact: 'O metrô de São Paulo transporta mais de 5 milhões de pessoas por dia — sem ele, o caos no trânsito seria ainda pior!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque o transporte público polui mais que os carros individuais' },
      { id: 'B', text: 'Porque reduz o número de veículos nas ruas, diminuindo congestionamentos, poluição e emissão de carbono' },
      { id: 'C', text: 'Porque é mais caro que ter carro' },
      { id: 'D', text: 'Porque só serve para turistas' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Por que a Região Sudeste concentra tanto a indústria e os serviços no Brasil?',
    tip: 'Pensa na história do Brasil: café, imigração europeia, ferrovias — tudo passou pelo Sudeste!',
    funFact: 'A riqueza do café no século XIX financiou as primeiras indústrias de São Paulo — criando o ciclo que tornou a região a mais industrializada do Brasil!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque o governo proibiu indústrias no resto do Brasil' },
      { id: 'B', text: 'Por fatores históricos como a riqueza do café, a imigração que trouxe mão de obra qualificada, a infraestrutura de transportes e a proximidade dos portos' },
      { id: 'C', text: 'Porque o Sudeste tem o clima mais quente do Brasil' },
      { id: 'D', text: 'Porque a região tem mais montanhas que o resto do país' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Bernardo discute na aula a importância das cidades médias para o equilíbrio regional do Brasil. Qual é o papel das cidades médias?',
    tip: 'Pensa em cidades que ficam entre as grandes metrópoles e as pequenas cidades — servindo de polo regional!',
    funFact: 'Cidades médias como Uberlândia (MG), Joinville (SC) e Campo Grande (MS) têm crescido rapidamente como alternativa às metrópoles superpovoadas!',
    points: 1,
    options: [
      { id: 'A', text: 'Nenhum papel — só as metrópoles são importantes' },
      { id: 'B', text: 'Servem como polos regionais, oferecendo serviços e empregos para municípios ao redor, aliviando a pressão sobre as metrópoles' },
      { id: 'C', text: 'As cidades médias só têm função turística' },
      { id: 'D', text: 'São apenas passagem entre grandes cidades' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Bernardo analisa uma notícia sobre um bairro com muito verde, boa iluminação, praças e ciclovias. Qual conceito de urbanismo isso representa?',
    tip: 'Pensa em cidades sustentáveis, onde o planejamento considera a qualidade de vida dos moradores!',
    funFact: 'Cidades como Curitiba (PR) são pioneiras em mobilidade urbana sustentável, com ciclovias, parques e ônibus expressos!',
    points: 1,
    options: [
      { id: 'A', text: 'Cidade fantasma' },
      { id: 'B', text: 'Favela planejada' },
      { id: 'C', text: 'Cidade sustentável, com planejamento que integra qualidade de vida, mobilidade e meio ambiente' },
      { id: 'D', text: 'Zona rural dentro da cidade' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'Para concluir, Bernardo resume: "A urbanização do Brasil foi muito rápida e trouxe tanto avanços como enormes desafios sociais e ambientais." Essa afirmação está:',
    tip: 'Pense em tudo que estudamos — cidades, favelas, êxodo rural, desigualdade, mas também empregos, serviços e cultura!',
    funFact: 'O Brasil passou de um país 70% rural em 1940 para 85% urbano em 2010 — uma transformação que levou séculos em outros países e aqui aconteceu em décadas!',
    points: 1,
    options: [
      { id: 'A', text: 'Errada, a urbanização só trouxe benefícios' },
      { id: 'B', text: 'Correta: o processo foi rápido, trouxe desenvolvimento mas também graves problemas sociais e ambientais' },
      { id: 'C', text: 'Errada, a urbanização nunca trouxe benefícios' },
      { id: 'D', text: 'Correta, mas apenas para o Sudeste' },
    ],
    correctAnswer: 'B',
  },
];
