export const questoesArte6AnoB4Av2 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'Quais são os elementos básicos da linguagem visual estudados este ano?',
    tip: 'Pensa nos cinco elementos que você estudou logo no início do ano.',
    funFact: 'Esses elementos são a base para entender praticamente qualquer obra visual!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas som e ritmo' },
      { id: 'B', text: 'Ponto, linha, forma, cor e textura' },
      { id: 'C', text: 'Apenas números e letras' },
      { id: 'D', text: 'Apenas música e dança' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'Quais são as quatro principais linguagens artísticas estudadas na escola?',
    tip: 'Pensa nas formas de expressão que envolvem imagens, sons, movimentos e atuação.',
    funFact: 'Cada uma dessas linguagens tem suas próprias técnicas e formas de expressão!',
    points: 1,
    options: [
      { id: 'A', text: 'Matemática, Ciências, História e Geografia' },
      { id: 'B', text: 'Português, Inglês, Arte e Educação Física' },
      { id: 'C', text: 'Futebol, Natação, Corrida e Ginástica' },
      { id: 'D', text: 'Artes Visuais, Música, Dança e Teatro' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'As pinturas feitas pelos primeiros seres humanos em paredes de cavernas são chamadas de:',
    tip: '"Rupestre" vem de uma palavra que significa "rocha".',
    funFact: 'Algumas dessas pinturas têm mais de 30 mil anos de idade!',
    points: 1,
    options: [
      { id: 'A', text: 'Mosaicos' },
      { id: 'B', text: 'Hieróglifos' },
      { id: 'C', text: 'Pinturas rupestres' },
      { id: 'D', text: 'Grafismos' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'As pirâmides e as máscaras funerárias, como a de Tutancâmon, são exemplos de arte de qual civilização?',
    tip: 'Pensa na civilização do rio Nilo e dos faraós.',
    funFact: 'A máscara de Tutancâmon é feita de ouro maciço e pedras preciosas!',
    points: 1,
    options: [
      { id: 'A', text: 'Egito Antigo' },
      { id: 'B', text: 'Grécia Antiga' },
      { id: 'C', text: 'Roma Antiga' },
      { id: 'D', text: 'Mesopotâmia' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'As esculturas gregas buscavam representar o corpo humano de forma:',
    tip: 'Pensa em estátuas de atletas e deuses gregos, com músculos bem definidos.',
    funFact: 'Os gregos até usavam matemática para calcular proporções ideais do corpo!',
    points: 1,
    options: [
      { id: 'A', text: 'Totalmente abstrata' },
      { id: 'B', text: 'Realista e equilibrada' },
      { id: 'C', text: 'Apenas com formas geométricas simples' },
      { id: 'D', text: 'Sem nenhuma proporção' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'Os romanos ficaram famosos por criar imagens com pequenas peças coloridas encaixadas, chamadas de:',
    tip: 'Pensa em uma imagem formada por muitos pedacinhos pequenos e coloridos encaixados juntos.',
    funFact: 'Muitos mosaicos romanos antigos ainda estão bem preservados até hoje!',
    points: 1,
    options: [
      { id: 'A', text: 'Mosaicos' },
      { id: 'B', text: 'Hieróglifos' },
      { id: 'C', text: 'Zigurates' },
      { id: 'D', text: 'Pinturas rupestres' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'O grafismo indígena é formado principalmente por:',
    tip: 'Pensa em desenhos com linhas e formas repetidas, cheios de significado.',
    funFact: 'Cada povo indígena tem seus próprios padrões de grafismo!',
    points: 1,
    options: [
      { id: 'A', text: 'Fotografias' },
      { id: 'B', text: 'Letras' },
      { id: 'C', text: 'Números' },
      { id: 'D', text: 'Padrões geométricos e desenhos simbólicos' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'O maracatu e o jongo são exemplos de expressões artísticas de origem:',
    tip: 'Pensa em manifestações culturais brasileiras que unem música, dança e visual.',
    funFact: 'O jongo é considerado Patrimônio Cultural do Brasil!',
    points: 1,
    options: [
      { id: 'A', text: 'Grega' },
      { id: 'B', text: 'Egípcia' },
      { id: 'C', text: 'Afro-brasileira' },
      { id: 'D', text: 'Romana' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'Misturando a cor azul com a amarela, obtemos a cor:',
    tip: 'Pensa na cor da grama e das folhas das árvores.',
    funFact: 'Essa é uma das cores secundárias, formadas pela mistura de duas cores primárias!',
    points: 1,
    options: [
      { id: 'A', text: 'Roxo' },
      { id: 'B', text: 'Verde' },
      { id: 'C', text: 'Laranja' },
      { id: 'D', text: 'Marrom' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'Um bailarino ou uma bailarina se expressa principalmente através de qual linguagem artística?',
    tip: 'Pensa em como um bailarino se expressa em cima do palco, através do movimento do corpo.',
    funFact: 'Existem muitos estilos de dança diferentes ao redor do mundo!',
    points: 1,
    options: [
      { id: 'A', text: 'Pintura' },
      { id: 'B', text: 'Escultura' },
      { id: 'C', text: 'Música' },
      { id: 'D', text: 'Dança' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'Se um artista usa linhas, formas e cores para criar uma pintura, ele está usando os elementos da linguagem:',
    tip: 'Pensa em qual linguagem artística usa esses elementos visuais.',
    funFact: 'Esses elementos podem ser combinados de infinitas formas diferentes para criar obras únicas!',
    points: 1,
    options: [
      { id: 'A', text: 'Musical' },
      { id: 'B', text: 'Teatral' },
      { id: 'C', text: 'Visual' },
      { id: 'D', text: 'Da dança' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'Comparando a arte rupestre com a arte egípcia, o que mudou principalmente?',
    tip: 'Pensa na diferença entre pigmentos simples em uma caverna e pinturas detalhadas dentro de túmulos.',
    funFact: 'Isso mostra como a arte foi evoluindo junto com o desenvolvimento das civilizações!',
    points: 1,
    options: [
      { id: 'A', text: 'A arte egípcia se tornou mais elaborada, com técnicas e materiais mais desenvolvidos' },
      { id: 'B', text: 'Nada mudou' },
      { id: 'C', text: 'A arte rupestre é mais recente' },
      { id: 'D', text: 'A arte egípcia não usava cor' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'Por que os egípcios pintavam figuras com o rosto de perfil, mas o olho e os ombros de frente?',
    tip: 'Pensa em como essa técnica buscava mostrar a figura da forma mais clara possível.',
    funFact: 'Esse estilo se manteve praticamente igual durante milhares de anos na arte egípcia!',
    points: 1,
    options: [
      { id: 'A', text: 'Para confundir quem olhasse' },
      { id: 'B', text: 'Para representar a figura da forma mais completa possível, mesmo sem ser realista' },
      { id: 'C', text: 'Porque não sabiam desenhar de outro jeito' },
      { id: 'D', text: 'Porque era mais rápido' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'Qual é uma diferença entre a escultura grega e a romana?',
    tip: 'Pensa na diferença entre um corpo "perfeito" grego e um retrato bem realista romano.',
    funFact: 'Essa diferença mostra como cada cultura tinha seus próprios objetivos artísticos!',
    points: 1,
    options: [
      { id: 'A', text: 'As duas são idênticas' },
      { id: 'B', text: 'A escultura romana não representava pessoas' },
      { id: 'C', text: 'A escultura grega é mais recente' },
      { id: 'D', text: 'A escultura romana buscava mais realismo individual, enquanto a grega buscava um ideal de beleza' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'Por que os materiais naturais, como fibras, sementes e penas, são tão usados na arte indígena?',
    tip: 'Pensa em como os povos indígenas têm uma relação muito próxima com a natureza.',
    funFact: 'Essa relação com a natureza também influencia os temas retratados na arte indígena!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque não existe outro material' },
      { id: 'B', text: 'Porque são mais caros que tintas industriais' },
      { id: 'C', text: 'Porque estão disponíveis na natureza onde esses povos vivem, fazendo parte da sua relação com o ambiente' },
      { id: 'D', text: 'Porque foram trazidos pelos europeus' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'Se uma escultura tem volume e pode ser vista de vários ângulos, diferente de uma pintura, que é plana, isso é uma característica de qual linguagem artística?',
    tip: 'Pensa na diferença entre algo tridimensional e algo plano.',
    funFact: 'Esculturas podem ser feitas de diferentes materiais, como argila, pedra, madeira e metal!',
    points: 1,
    options: [
      { id: 'A', text: 'Música' },
      { id: 'B', text: 'Dança' },
      { id: 'C', text: 'Teatro' },
      { id: 'D', text: 'Escultura (artes visuais)' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'Por que estudar diferentes civilizações e culturas através da arte (Pré-História, Egito, Grécia, Roma, povos indígenas e africanos) é importante?',
    tip: 'Pensa em tudo que você aprendeu este ano sobre diferentes culturas através da arte.',
    funFact: 'A arte é uma das melhores formas de conhecer como diferentes povos viviam e pensavam!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque ajuda a entender a diversidade e a riqueza da história humana e da cultura brasileira' },
      { id: 'B', text: 'Porque só interessa a especialistas' },
      { id: 'C', text: 'Porque essas culturas não têm relação entre si' },
      { id: 'D', text: 'Porque a arte não tem nenhuma relação com a história' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'As pinturas corporais indígenas, além de decorativas, costumam representar:',
    tip: 'Pensa em como um desenho no corpo pode mostrar a qual grupo uma pessoa pertence.',
    funFact: 'Algumas pinturas corporais são feitas especificamente para rituais e festas importantes!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas moda passageira' },
      { id: 'B', text: 'Identidade, rituais e a cultura de cada povo' },
      { id: 'C', text: 'Nada além de enfeite' },
      { id: 'D', text: 'Apenas números' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'O Coliseu de Roma e o Partenon de Atenas são exemplos de:',
    tip: 'Pensa no tamanho e na complexidade dessas duas famosas construções antigas.',
    funFact: 'As duas ainda são visitadas por milhões de turistas todos os anos!',
    points: 1,
    options: [
      { id: 'A', text: 'Pinturas rupestres' },
      { id: 'B', text: 'Máscaras funerárias' },
      { id: 'C', text: 'Grandes obras de arquitetura da Antiguidade' },
      { id: 'D', text: 'Mosaicos indígenas' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'Ao longo do ano, Bernardo estudou arte desde a Pré-História até as culturas indígena e afro-brasileira. Isso mostra que a Arte:',
    tip: 'Pensa em tudo que você estudou este ano sobre diferentes culturas e épocas.',
    funFact: 'Estudar arte junto com História ajuda a entender melhor cada época e cultura!',
    points: 1,
    options: [
      { id: 'A', text: 'Acompanha e reflete a evolução e a diversidade das culturas humanas' },
      { id: 'B', text: 'Só existe na era moderna' },
      { id: 'C', text: 'Não tem relação com outras disciplinas' },
      { id: 'D', text: 'É algo sem importância para se estudar' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Bernardo organiza um grande mural na escola reunindo tudo que aprendeu de Arte neste ano. No início, ele coloca a imagem de uma mão pintada na parede de uma caverna. A que período isso se refere?',
    tip: 'É o mesmo período da questão 3.',
    funFact: 'Esse mural é uma ótima forma de revisar todo o conteúdo do ano de um jeito visual e divertido!',
    points: 1,
    options: [
      { id: 'A', text: 'Egito Antigo' },
      { id: 'B', text: 'Grécia Antiga' },
      { id: 'C', text: 'Roma Antiga' },
      { id: 'D', text: 'Pré-História (pintura rupestre)' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Mais à frente no mural, Bernardo cola a imagem de uma pirâmide e de uma máscara funerária dourada. A qual civilização essas imagens pertencem?',
    tip: 'É a mesma civilização da questão 4.',
    funFact: 'Essas imagens são símbolos muito conhecidos da cultura egípcia até hoje!',
    points: 1,
    options: [
      { id: 'A', text: 'Grécia' },
      { id: 'B', text: 'Egito' },
      { id: 'C', text: 'Roma' },
      { id: 'D', text: 'Povos indígenas' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Bernardo também coloca a imagem de uma escultura grega de um atleta, com músculos bem definidos. Que característica da arte grega essa imagem representa?',
    tip: 'É a mesma característica da questão 5.',
    funFact: 'Muitas dessas esculturas representavam vencedores dos Jogos Olímpicos da Antiguidade!',
    points: 1,
    options: [
      { id: 'A', text: 'O naturalismo e o equilíbrio na representação do corpo humano' },
      { id: 'B', text: 'A escrita hieroglífica' },
      { id: 'C', text: 'O grafismo indígena' },
      { id: 'D', text: 'O mosaico' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Logo depois, Bernardo cola a imagem de um mosaico colorido e do Coliseu. A que civilização essas imagens se referem?',
    tip: 'É a mesma civilização da questão 6.',
    funFact: 'Tanto o mosaico quanto o Coliseu mostram a habilidade técnica e artística dos romanos!',
    points: 1,
    options: [
      { id: 'A', text: 'Grécia' },
      { id: 'B', text: 'Egito' },
      { id: 'C', text: 'Roma' },
      { id: 'D', text: 'Povos indígenas' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Para representar a cultura brasileira, Bernardo cola a imagem de um cesto de palha e de um padrão geométrico pintado no corpo. A que tipo de arte isso se refere?',
    tip: 'É o mesmo tipo de arte das questões 7 e 15.',
    funFact: 'A cestaria e o grafismo são duas das expressões mais características da arte indígena brasileira!',
    points: 1,
    options: [
      { id: 'A', text: 'Arte grega' },
      { id: 'B', text: 'Arte egípcia' },
      { id: 'C', text: 'Arte romana' },
      { id: 'D', text: 'Arte indígena' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Por fim, Bernardo cola a imagem de uma máscara africana e de dançarinos de maracatu. A que cultura essas imagens se referem?',
    tip: 'É a mesma cultura da questão 8.',
    funFact: 'Essas duas expressões mostram a riqueza e a diversidade da cultura afro-brasileira!',
    points: 1,
    options: [
      { id: 'A', text: 'Grega' },
      { id: 'B', text: 'Egípcia' },
      { id: 'C', text: 'Afro-brasileira' },
      { id: 'D', text: 'Romana' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Ao explicar o mural para a turma, Bernardo diz que todas essas culturas, de formas diferentes, usaram a arte para expressar crenças, identidade e história. Essa frase resume bem:',
    tip: 'Pensa em tudo que você aprendeu este ano sobre o propósito da arte em diferentes culturas.',
    funFact: 'Esse é um dos motivos pelos quais a Arte é estudada em escolas do mundo inteiro!',
    points: 1,
    options: [
      { id: 'A', text: 'Que a arte não tem nenhuma função importante' },
      { id: 'B', text: 'A importância da arte como forma de expressão humana ao longo da história' },
      { id: 'C', text: 'Que só uma dessas culturas tinha arte de verdade' },
      { id: 'D', text: 'Que a arte é sempre igual em todas as culturas' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Bernardo explica que, apesar de tão diferentes, todas essas formas de arte usaram elementos como ponto, linha, forma, cor e textura. O que isso mostra?',
    tip: 'Pensa em como ponto, linha, forma, cor e textura aparecem em praticamente todas as artes visuais que você estudou.',
    funFact: 'Esses elementos conectam formas de arte de culturas e épocas bem diferentes entre si!',
    points: 1,
    options: [
      { id: 'A', text: 'Que os elementos da linguagem visual são a base de praticamente toda obra visual, em qualquer época ou cultura' },
      { id: 'B', text: 'Que só a arte grega usava esses elementos' },
      { id: 'C', text: 'Que esses elementos são uma invenção recente' },
      { id: 'D', text: 'Que cada cultura usava elementos completamente diferentes, sem nenhuma relação' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Na revisão para a prova final, Bernardo cria a pergunta: "Qual civilização é conhecida por suas pirâmides e máscaras funerárias?" Qual é a resposta certa?',
    tip: 'É a mesma civilização das questões 4 e 22.',
    funFact: 'A arte egípcia continua sendo estudada e admirada em museus do mundo todo!',
    points: 1,
    options: [
      { id: 'A', text: 'Grécia' },
      { id: 'B', text: 'Roma' },
      { id: 'C', text: 'Povos indígenas' },
      { id: 'D', text: 'Egito' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'Para encerrar sua apresentação sobre o ano inteiro de Arte, Bernardo resume: "Estudamos várias formas de arte e descobrimos que..." Como ele pode completar a frase?',
    tip: 'Pensa em tudo que você revisou neste simulado, de várias culturas diferentes.',
    funFact: 'Parabéns, Bernardo! Você completou toda a Arte do 6º ano! No próximo simulado, a jornada continua com Educação Física!',
    points: 1,
    options: [
      { id: 'A', text: '"...nenhuma delas tem relação com o mundo atual."' },
      { id: 'B', text: '"...cada cultura, à sua maneira, usou a arte para expressar sua identidade, crenças e história, e isso continua influenciando o mundo até hoje."' },
      { id: 'C', text: '"...a arte não ensina nada."' },
      { id: 'D', text: '"...todas eram exatamente iguais, sem nenhuma diferença."' },
    ],
    correctAnswer: 'B',
  },
];
