export const questoesArte8AnoB3Av1 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'Em que país surgiu o movimento artístico conhecido como Impressionismo?',
    tip: 'Pense num país europeu que também foi importante para o Neoclassicismo e o Romantismo!',
    funFact: 'O Impressionismo surgiu em Paris, na década de 1870!',
    points: 1,
    options: [
      { id: 'A', text: 'Itália' },
      { id: 'B', text: 'França' },
      { id: 'C', text: 'Espanha' },
      { id: 'D', text: 'Alemanha' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'De onde veio o nome "Impressionismo"?',
    tip: 'Pense no título de uma pintura que retratava o nascer do sol num porto, de forma bem solta e rápida!',
    funFact: 'Um crítico de arte usou o termo "impressionismo" de forma depreciativa, mas o nome acabou sendo adotado pelos próprios artistas!',
    points: 1,
    options: [
      { id: 'A', text: 'De um livro de poesia famoso' },
      { id: 'B', text: 'De uma cidade francesa' },
      { id: 'C', text: 'De um tipo de tinta usada pelos artistas' },
      { id: 'D', text: 'De uma pintura de Claude Monet chamada "Impressão, Nascer do Sol"' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'Qual técnica os impressionistas costumavam usar para capturar a luz e os momentos rapidamente?',
    tip: 'Pense em pinturas que parecem feitas rapidamente, capturando um momento antes que ele mudasse!',
    funFact: 'Essas pinceladas rápidas ajudavam a capturar efeitos de luz que mudam a cada segundo!',
    points: 1,
    options: [
      { id: 'A', text: 'Pinceladas rápidas e visíveis' },
      { id: 'B', text: 'Linhas perfeitamente retas e detalhadas' },
      { id: 'C', text: 'Cores escuras e sombrias' },
      { id: 'D', text: 'Formas totalmente geométricas' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'Onde os pintores impressionistas costumavam pintar suas obras, diferente dos artistas anteriores que trabalhavam em estúdios?',
    tip: 'Pense em artistas saindo de seus ateliês para pintar diretamente na rua, no campo ou perto de rios!',
    funFact: 'Essa prática de pintar ao ar livre é chamada de "en plein air", expressão francesa para "ao ar livre"!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas em igrejas' },
      { id: 'B', text: 'Apenas em museus' },
      { id: 'C', text: 'Ao ar livre, observando diretamente a natureza e a luz' },
      { id: 'D', text: 'Apenas durante a noite, sem luz nenhuma' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'Qual pintor francês é considerado um dos fundadores do Impressionismo, autor da obra "Impressão, Nascer do Sol"?',
    tip: 'Esse pintor é muito famoso por suas pinturas de jardins, lagoas e efeitos de luz na natureza!',
    funFact: 'Claude Monet pintou a mesma paisagem várias vezes, em diferentes horários, para capturar como a luz mudava!',
    points: 1,
    options: [
      { id: 'A', text: 'Vincent van Gogh' },
      { id: 'B', text: 'Claude Monet' },
      { id: 'C', text: 'Gustave Courbet' },
      { id: 'D', text: 'Jacques-Louis David' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'Qual era um tema comum nas pinturas impressionistas, relacionado à vida moderna da época?',
    tip: 'Pense em pinturas mostrando pessoas comuns se divertindo, passeando ou tomando café em Paris!',
    funFact: 'Os impressionistas adoravam retratar a vida moderna e urbana de sua época!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas batalhas históricas' },
      { id: 'B', text: 'Apenas retratos de reis' },
      { id: 'C', text: 'Apenas paisagens do deserto' },
      { id: 'D', text: 'Cenas do cotidiano, como cafés, parques e momentos de lazer' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'Por que o Impressionismo foi inicialmente rejeitado pela Academia oficial de arte da época?',
    tip: 'Pense em como as pinceladas rápidas e soltas podiam parecer "incompletas" para quem estava acostumado com pinturas mais detalhadas!',
    funFact: 'Por serem rejeitados, muitos impressionistas expuseram suas obras em uma mostra alternativa, separada da Academia oficial!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque as obras eram consideradas perfeitas demais' },
      { id: 'B', text: 'Porque usavam apenas preto e branco' },
      { id: 'C', text: 'Porque a técnica era considerada "inacabada" e diferente demais do padrão tradicional' },
      { id: 'D', text: 'Porque retratavam apenas temas religiosos' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'Qual pintor francês é conhecido por retratar bailarinas e cenas de teatro, com uma perspectiva única e dinâmica?',
    tip: 'Esse pintor adorava capturar o movimento e a dança, retratando bailarinas em ensaios e apresentações!',
    funFact: 'Suas pinturas de bailarinas são algumas das obras mais famosas do Impressionismo!',
    points: 1,
    options: [
      { id: 'A', text: 'Edgar Degas' },
      { id: 'B', text: 'Claude Monet' },
      { id: 'C', text: 'Pierre-Auguste Renoir' },
      { id: 'D', text: 'Vincent van Gogh' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'Qual pintor francês é conhecido por retratar cenas de lazer e festas, com cores vibrantes e alegres?',
    tip: 'Esse pintor adorava retratar momentos felizes, como festas ao ar livre e encontros entre amigos!',
    funFact: 'Suas pinturas são conhecidas por capturar a luz e a alegria de momentos sociais!',
    points: 1,
    options: [
      { id: 'A', text: 'Edgar Degas' },
      { id: 'B', text: 'Pierre-Auguste Renoir' },
      { id: 'C', text: 'Jean-François Millet' },
      { id: 'D', text: 'Gustave Courbet' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'Qual é uma diferença importante entre o Impressionismo e o Realismo?',
    tip: 'Pense em como cada movimento lidava com os detalhes: um buscava capturar um instante rápido, o outro, mostrar a realidade com cuidado!',
    funFact: 'Apesar das diferenças, os dois movimentos compartilhavam o interesse pela vida cotidiana!',
    points: 1,
    options: [
      { id: 'A', text: 'Os dois estilos são exatamente iguais' },
      { id: 'B', text: 'O Realismo usava cores mais vibrantes que o Impressionismo' },
      { id: 'C', text: 'O Impressionismo não se importava com a luz' },
      { id: 'D', text: 'O Impressionismo focava na captura rápida da luz e do momento, enquanto o Realismo focava em retratar a vida comum com precisão' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'Por que Claude Monet pintou a mesma paisagem várias vezes, em diferentes horários do dia?',
    tip: 'Pense em como a luz do sol muda de manhã, ao meio-dia e ao anoitecer, criando efeitos diferentes!',
    funFact: 'Essa série de pinturas sobre o mesmo tema, em momentos diferentes, é uma das marcas mais famosas da obra de Monet!',
    points: 1,
    options: [
      { id: 'A', text: 'Para capturar como a luz e as cores mudavam ao longo do dia' },
      { id: 'B', text: 'Porque ele não conseguia decidir qual pintura preferia' },
      { id: 'C', text: 'Porque era obrigado a repetir o mesmo tema' },
      { id: 'D', text: 'Porque não tinha outros temas para pintar' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'Qual é a importância da prática de pintar "en plein air" para o movimento Impressionista?',
    tip: 'Pense em como pintar diretamente na natureza, observando a luz real, era diferente de pintar dentro de um estúdio fechado!',
    funFact: 'Essa prática só se tornou mais fácil depois da invenção de tintas em tubos, que podiam ser levadas para fora do ateliê!',
    points: 1,
    options: [
      { id: 'A', text: 'Ela não teve nenhuma importância' },
      { id: 'B', text: 'Ela só era usada em dias chuvosos' },
      { id: 'C', text: 'Ela permitia aos artistas observar e capturar diretamente os efeitos reais da luz natural' },
      { id: 'D', text: 'Ela proibia qualquer uso de cores vivas' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'Por que as pinceladas rápidas e visíveis são consideradas uma marca registrada do Impressionismo?',
    tip: 'Pense em como pinceladas soltas podem dar a sensação de movimento e de um momento passageiro!',
    funFact: 'De longe, essas pinceladas se misturam na visão do espectador, criando um efeito de luz vibrante!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque elas escondem completamente a imagem' },
      { id: 'B', text: 'Porque elas ajudavam a capturar a sensação de um momento rápido e cheio de luz' },
      { id: 'C', text: 'Porque elas eram feitas só em preto e branco' },
      { id: 'D', text: 'Porque elas eram proibidas pela Academia' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'Qual foi a reação inicial da crítica de arte oficial em relação às obras impressionistas?',
    tip: 'Pense em como pinturas com pinceladas soltas podiam parecer "estranhas" para quem só conhecia obras mais detalhadas e polidas!',
    funFact: 'Essa rejeição inicial levou os impressionistas a organizar suas próprias exposições independentes!',
    points: 1,
    options: [
      { id: 'A', text: 'Elas foram imediatamente aceitas e elogiadas' },
      { id: 'B', text: 'Elas foram consideradas perfeitas desde o início' },
      { id: 'C', text: 'Elas não geraram nenhuma reação' },
      { id: 'D', text: 'Elas foram rejeitadas, sendo consideradas inacabadas e diferentes do padrão tradicional' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'Qual é a importância das pinturas de Edgar Degas sobre bailarinas para o movimento Impressionista?',
    tip: 'Pense em como esse pintor conseguia capturar o movimento das bailarinas de forma muito viva e interessante!',
    funFact: 'Degas também gostava de retratar cenas de corridas de cavalos, sempre com muito movimento!',
    points: 1,
    options: [
      { id: 'A', text: 'Elas mostram um olhar dinâmico e único sobre o movimento e a vida urbana da época' },
      { id: 'B', text: 'Elas não têm nenhuma relação com o Impressionismo' },
      { id: 'C', text: 'Elas retratam apenas paisagens naturais' },
      { id: 'D', text: 'Elas são completamente abstratas, sem nenhuma figura humana' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'Por que o Impressionismo é considerado um movimento ligado à vida moderna de sua época?',
    tip: 'Pense em pinturas mostrando pessoas passeando, se divertindo e vivendo o dia a dia nas cidades da época!',
    funFact: 'Essa conexão com a vida moderna tornou o Impressionismo um movimento bem diferente dos estilos históricos e religiosos anteriores!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque retratava apenas temas medievais' },
      { id: 'B', text: 'Porque evitava qualquer tema urbano' },
      { id: 'C', text: 'Porque os artistas retratavam cenas do cotidiano urbano, como cafés, parques e lazer' },
      { id: 'D', text: 'Porque só pintava cenas do campo, sem nenhuma relação com cidades' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'Qual foi a importância da invenção de tintas em tubos para o desenvolvimento do Impressionismo?',
    tip: 'Pense em como seria difícil pintar fora de casa sem um jeito prático de levar as tintas!',
    funFact: 'Antes dessa invenção, os artistas precisavam misturar suas próprias tintas no estúdio, o que dificultava pintar ao ar livre!',
    points: 1,
    options: [
      { id: 'A', text: 'Ela não teve nenhuma relação com o movimento' },
      { id: 'B', text: 'Ela impediu os artistas de pintar ao ar livre' },
      { id: 'C', text: 'Ela só servia para pinturas em estúdio' },
      { id: 'D', text: 'Ela facilitou que os artistas levassem suas tintas para pintar ao ar livre, diretamente da natureza' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'Qual é uma diferença importante entre as pinturas impressionistas e as pinturas acadêmicas tradicionais da época?',
    tip: 'Pense no contraste de técnicas: uma buscava capturar um momento rápido, a outra buscava um acabamento mais perfeito e detalhado!',
    funFact: 'Essa diferença de técnica foi um dos motivos da rejeição inicial do Impressionismo pela Academia!',
    points: 1,
    options: [
      { id: 'A', text: 'As pinturas acadêmicas usavam pinceladas rápidas e soltas' },
      { id: 'B', text: 'As pinturas impressionistas tinham pinceladas mais soltas e rápidas, enquanto as acadêmicas eram mais detalhadas e polidas' },
      { id: 'C', text: 'Não existe nenhuma diferença entre elas' },
      { id: 'D', text: 'As pinturas impressionistas eram sempre maiores que as acadêmicas' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'Por que os impressionistas organizaram suas próprias exposições, separadas da Academia oficial?',
    tip: 'Pense em como artistas rejeitados por uma instituição podem criar seus próprios espaços para mostrar seu trabalho!',
    funFact: 'Essas exposições independentes ajudaram o Impressionismo a se tornar um dos movimentos mais importantes da história da arte!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque suas obras eram rejeitadas pela Academia tradicional' },
      { id: 'B', text: 'Porque queriam vender suas obras mais caras' },
      { id: 'C', text: 'Porque a Academia pedia isso' },
      { id: 'D', text: 'Porque não gostavam de expor suas obras' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'Qual é a importância de se estudar o Impressionismo para entender a arte moderna?',
    tip: 'Pense em como esse movimento foi uma ruptura importante com as regras tradicionais da arte acadêmica!',
    funFact: 'Vários movimentos artísticos posteriores, como o Expressionismo, foram influenciados pela liberdade trazida pelo Impressionismo!',
    points: 1,
    options: [
      { id: 'A', text: 'O Impressionismo não teve nenhuma influência na arte depois dele' },
      { id: 'B', text: 'Ele só existiu na França, sem nenhuma influência mundial' },
      { id: 'C', text: 'Ele abriu caminho para novos movimentos artísticos, ao valorizar a liberdade de expressão e a experimentação' },
      { id: 'D', text: 'Ele não tem nenhuma relação com a vida moderna' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Bernardo está estudando sobre o Impressionismo. Em que país esse movimento surgiu?',
    tip: 'Pense num país europeu que também foi importante para o Neoclassicismo e o Romantismo!',
    funFact: 'O Impressionismo surgiu em Paris, na década de 1870!',
    points: 1,
    options: [
      { id: 'A', text: 'Itália' },
      { id: 'B', text: 'Espanha' },
      { id: 'C', text: 'Alemanha' },
      { id: 'D', text: 'França' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Bernardo quer saber de onde veio o nome "Impressionismo". Qual é a origem desse nome?',
    tip: 'Pense no título de uma pintura que retratava o nascer do sol num porto, de forma bem solta e rápida!',
    funFact: 'Um crítico usou esse termo de forma depreciativa, mas ele acabou sendo adotado pelos próprios artistas!',
    points: 1,
    options: [
      { id: 'A', text: 'De uma pintura de Claude Monet chamada "Impressão, Nascer do Sol"' },
      { id: 'B', text: 'De uma cidade francesa' },
      { id: 'C', text: 'De um tipo de tinta usada pelos artistas' },
      { id: 'D', text: 'De um livro de poesia famoso' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Bernardo descobriu uma técnica muito usada pelos impressionistas para capturar a luz rapidamente. Qual é ela?',
    tip: 'Pense em pinturas que parecem feitas rapidamente, capturando um momento antes que ele mudasse!',
    funFact: 'Essas pinceladas rápidas ajudavam a capturar efeitos de luz que mudam a cada segundo!',
    points: 1,
    options: [
      { id: 'A', text: 'Linhas perfeitamente retas' },
      { id: 'B', text: 'Pinceladas rápidas e visíveis' },
      { id: 'C', text: 'Cores escuras e sombrias' },
      { id: 'D', text: 'Formas totalmente geométricas' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Bernardo quer saber onde os impressionistas costumavam pintar suas obras. Onde era isso?',
    tip: 'Pense em artistas saindo de seus ateliês para pintar diretamente na rua, no campo ou perto de rios!',
    funFact: 'Essa prática é chamada de "en plein air"!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas em igrejas' },
      { id: 'B', text: 'Apenas em museus' },
      { id: 'C', text: 'Ao ar livre, observando diretamente a natureza e a luz' },
      { id: 'D', text: 'Apenas durante a noite' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Bernardo quer saber qual pintor francês é considerado um dos fundadores do Impressionismo. Quem foi ele?',
    tip: 'Esse pintor é muito famoso por suas pinturas de jardins, lagoas e efeitos de luz na natureza!',
    funFact: 'Ele pintou a mesma paisagem várias vezes, em diferentes horários, para capturar como a luz mudava!',
    points: 1,
    options: [
      { id: 'A', text: 'Vincent van Gogh' },
      { id: 'B', text: 'Gustave Courbet' },
      { id: 'C', text: 'Jacques-Louis David' },
      { id: 'D', text: 'Claude Monet' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Bernardo quer saber qual era um tema comum nas pinturas impressionistas. Qual era esse tema?',
    tip: 'Pense em pinturas mostrando pessoas comuns se divertindo, passeando ou tomando café em Paris!',
    funFact: 'Os impressionistas adoravam retratar a vida moderna e urbana de sua época!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas batalhas históricas' },
      { id: 'B', text: 'Cenas do cotidiano, como cafés, parques e momentos de lazer' },
      { id: 'C', text: 'Apenas retratos de reis' },
      { id: 'D', text: 'Apenas paisagens do deserto' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Bernardo quer saber por que o Impressionismo foi inicialmente rejeitado pela Academia oficial. Qual foi o motivo?',
    tip: 'Pense em como as pinceladas rápidas e soltas podiam parecer "incompletas" para quem estava acostumado com pinturas mais detalhadas!',
    funFact: 'Por serem rejeitados, muitos impressionistas expuseram suas obras em uma mostra alternativa!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque a técnica era considerada "inacabada" e diferente demais do padrão tradicional' },
      { id: 'B', text: 'Porque as obras eram consideradas perfeitas demais' },
      { id: 'C', text: 'Porque usavam apenas preto e branco' },
      { id: 'D', text: 'Porque retratavam apenas temas religiosos' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Bernardo quer saber qual pintor francês retratava bailarinas e cenas de teatro. Quem foi ele?',
    tip: 'Esse pintor adorava capturar o movimento e a dança, retratando bailarinas em ensaios e apresentações!',
    funFact: 'Suas pinturas de bailarinas são algumas das obras mais famosas do Impressionismo!',
    points: 1,
    options: [
      { id: 'A', text: 'Claude Monet' },
      { id: 'B', text: 'Pierre-Auguste Renoir' },
      { id: 'C', text: 'Edgar Degas' },
      { id: 'D', text: 'Vincent van Gogh' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Bernardo quer saber qual pintor francês retratava cenas de lazer e festas com cores vibrantes. Quem foi ele?',
    tip: 'Esse pintor adorava retratar momentos felizes, como festas ao ar livre e encontros entre amigos!',
    funFact: 'Suas pinturas são conhecidas por capturar a luz e a alegria de momentos sociais!',
    points: 1,
    options: [
      { id: 'A', text: 'Edgar Degas' },
      { id: 'B', text: 'Jean-François Millet' },
      { id: 'C', text: 'Gustave Courbet' },
      { id: 'D', text: 'Pierre-Auguste Renoir' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'Para resumir seus estudos sobre o Impressionismo, Bernardo quer lembrar sua principal característica. Qual é ela?',
    tip: 'Pense em tudo que você aprendeu: luz, pinceladas rápidas e cenas do cotidiano moderno!',
    funFact: 'Essas características tornaram o Impressionismo um dos movimentos mais revolucionários da história da arte!',
    points: 1,
    options: [
      { id: 'A', text: 'Formas totalmente abstratas e geométricas' },
      { id: 'B', text: 'Captura rápida da luz e dos momentos, com pinceladas visíveis, retratando a vida moderna' },
      { id: 'C', text: 'Cópia exata da arte greco-romana' },
      { id: 'D', text: 'Ausência total de cores' },
    ],
    correctAnswer: 'B',
  },
];
