export const questoesMatematica7AnoB1Av2 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'Múltiplos de um número são obtidos multiplicando esse número por 0, 1, 2, 3... Qual das opções mostra APENAS múltiplos de 5?',
    tip: 'Todo múltiplo de 5 termina em 0 ou 5! Confira número por número em cada alternativa.',
    funFact: 'Todo número tem infinitos múltiplos — a lista nunca acaba!',
    points: 1,
    options: [
      { id: 'A', text: '5, 6, 7, 8' },
      { id: 'B', text: '2, 5, 8, 11' },
      { id: 'C', text: '5, 12, 15, 20' },
      { id: 'D', text: '5, 10, 15, 20' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'Divisores de um número são números que dividem esse número exatamente (resto zero). Quais são os divisores de 12?',
    tip: 'Teste dividir 12 por cada número da lista. Se sobrar resto, esse número NÃO é divisor!',
    funFact: 'Diferente dos múltiplos, os divisores de um número são sempre em quantidade limitada!',
    points: 1,
    options: [
      { id: 'A', text: '1, 2, 3, 4, 5, 6, 12' },
      { id: 'B', text: '1, 2, 3, 4, 6, 12' },
      { id: 'C', text: '1, 2, 4, 6, 8, 12' },
      { id: 'D', text: '2, 3, 4, 6, 12' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'Um número é considerado PRIMO quando:',
    tip: 'Pense no número 7: só dá para dividir por 1 e por 7 mesmo, sem sobrar resto. Essa é a "marca registrada" de um primo!',
    funFact: 'O único número primo par é o 2 — todos os outros primos são ímpares!',
    points: 1,
    options: [
      { id: 'A', text: 'É divisível por todos os números' },
      { id: 'B', text: 'Tem exatamente 3 divisores' },
      { id: 'C', text: 'Tem exatamente dois divisores: 1 e ele mesmo' },
      { id: 'D', text: 'É sempre um número par' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'Qual das alternativas apresenta APENAS números primos?',
    tip: 'Cuidado com o número 1 — ele NÃO é considerado primo! E o 9 também não é (9 = 3 x 3).',
    funFact: 'Existem infinitos números primos, e cientistas ainda hoje procuram novos primos gigantes usando supercomputadores!',
    points: 1,
    options: [
      { id: 'A', text: '2, 3, 5, 7' },
      { id: 'B', text: '2, 4, 6, 8' },
      { id: 'C', text: '1, 3, 5, 9' },
      { id: 'D', text: '3, 5, 9, 11' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'Um número é divisível por 2 quando:',
    tip: 'Olhe só para o último algarismo do número — é o único que importa nesse critério!',
    funFact: 'Esse "truque" de olhar o último algarismo é chamado de critério de divisibilidade — existem vários, um para cada número!',
    points: 1,
    options: [
      { id: 'A', text: 'A soma de seus algarismos é múltipla de 3' },
      { id: 'B', text: 'Termina em 0 ou 5' },
      { id: 'C', text: 'É maior que 10' },
      { id: 'D', text: 'Termina em algarismo par (0, 2, 4, 6, 8)' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'Um número é divisível por 3 quando:',
    tip: 'Teste com o número 123: 1+2+3 = 6, que é múltiplo de 3. Por isso 123 é divisível por 3!',
    funFact: 'Esse critério funciona para números de qualquer tamanho, por maior que seja!',
    points: 1,
    options: [
      { id: 'A', text: 'Termina em 3' },
      { id: 'B', text: 'A soma de seus algarismos é um múltiplo de 3' },
      { id: 'C', text: 'É um número primo' },
      { id: 'D', text: 'É divisível por 9' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'O número 235 é divisível por 5 porque:',
    tip: 'O critério de divisibilidade por 5 é bem simples: o número tem que terminar em 0 ou em 5.',
    funFact: 'Esse é um dos critérios mais fáceis de decorar — só precisa olhar o último algarismo!',
    points: 1,
    options: [
      { id: 'A', text: 'Termina em 5' },
      { id: 'B', text: 'É um número par' },
      { id: 'C', text: 'A soma de seus algarismos é 10' },
      { id: 'D', text: 'É múltiplo de 2' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'Ao decompor o número 12 em fatores primos, obtemos:',
    tip: 'Cada fator da decomposição precisa ser um número PRIMO. Repare que 6 e 4 ainda podem ser divididos mais!',
    funFact: 'Essa decomposição também é chamada de "fatoração em números primos" e é a base para calcular MMC e MDC!',
    points: 1,
    options: [
      { id: 'A', text: '2 x 6' },
      { id: 'B', text: '3 x 4' },
      { id: 'C', text: '2 x 2 x 3' },
      { id: 'D', text: '1 x 12' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'Um número composto é aquele que:',
    tip: 'Pense no oposto dos primos! Enquanto o primo tem só 2 divisores, o composto tem 3 ou mais.',
    funFact: 'Todo número inteiro maior que 1 é primo ou composto — não existe uma terceira opção!',
    points: 1,
    options: [
      { id: 'A', text: 'Só pode ser dividido por 1' },
      { id: 'B', text: 'É sempre par' },
      { id: 'C', text: 'É sempre maior que 100' },
      { id: 'D', text: 'Tem mais de dois divisores' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'Qual é o menor número primo?',
    tip: 'Lembre-se: o 1 não conta como primo, e o 0 também não! O menor primo de todos é bem conhecido...',
    funFact: 'O 2 é especial: além de ser o menor primo, é o único primo que também é par!',
    points: 1,
    options: [
      { id: 'A', text: '0' },
      { id: 'B', text: '2' },
      { id: 'C', text: '1' },
      { id: 'D', text: '3' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'MMC significa Mínimo Múltiplo Comum. Qual é o MMC entre 4 e 6?',
    tip: 'Liste os múltiplos de cada número (4, 8, 12, 16... e 6, 12, 18...) e procure o primeiro que aparece nas duas listas!',
    funFact: '"Mínimo" no nome MMC quer dizer que é o MENOR de todos os múltiplos comuns — existem outros, mas 12 é o primeiro!',
    points: 1,
    options: [
      { id: 'A', text: '12' },
      { id: 'B', text: '24' },
      { id: 'C', text: '6' },
      { id: 'D', text: '10' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'MDC significa Máximo Divisor Comum. Qual é o MDC entre 8 e 12?',
    tip: 'Liste os divisores dos dois números e veja qual é o maior que aparece nas duas listas.',
    funFact: '"Máximo" no nome MDC significa o MAIOR divisor que os dois números compartilham!',
    points: 1,
    options: [
      { id: 'A', text: '2' },
      { id: 'B', text: '8' },
      { id: 'C', text: '4' },
      { id: 'D', text: '24' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'Qual é o MMC entre 3 e 5?',
    tip: 'Quando dois números não têm divisores em comum (além do 1), o MMC deles é sempre o produto dos dois!',
    funFact: 'Números assim, sem divisores comuns, são chamados de "primos entre si"!',
    points: 1,
    options: [
      { id: 'A', text: '3' },
      { id: 'B', text: '5' },
      { id: 'C', text: '8' },
      { id: 'D', text: '15' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'Qual é o MDC entre 15 e 25?',
    tip: 'Liste os divisores de 15 (1,3,5,15) e de 25 (1,5,25). Qual número aparece nas duas listas e é o maior?',
    funFact: 'O MDC nunca pode ser maior do que o menor dos dois números envolvidos!',
    points: 1,
    options: [
      { id: 'A', text: '1' },
      { id: 'B', text: '5' },
      { id: 'C', text: '15' },
      { id: 'D', text: '25' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'Dois ônibus saem juntos de uma estação: um a cada 6 minutos e outro a cada 8 minutos. Depois de quantos minutos eles sairão juntos novamente?',
    tip: 'Esse tipo de problema, de "coisas que acontecem juntas de novo", sempre se resolve com MMC!',
    funFact: 'Esse é um dos usos mais comuns do MMC no dia a dia — até em horários de ônibus e trens de verdade!',
    points: 1,
    options: [
      { id: 'A', text: '24 minutos' },
      { id: 'B', text: '48 minutos' },
      { id: 'C', text: '14 minutos' },
      { id: 'D', text: '8 minutos' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'Uma professora quer dividir 18 lápis e 24 canetas em grupos iguais, sem sobrar nada, usando o maior número possível de grupos. Quantos grupos ela pode formar?',
    tip: 'Quando o problema fala em "dividir em partes iguais, sem sobrar, com o maior número possível", pense em MDC!',
    funFact: 'Com 6 grupos, cada um receberia 3 lápis e 4 canetas — tudo dividido certinho!',
    points: 1,
    options: [
      { id: 'A', text: '3' },
      { id: 'B', text: '4' },
      { id: 'C', text: '6' },
      { id: 'D', text: '12' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'Para calcular o MMC por fatoração, decompomos os números em fatores primos e multiplicamos os fatores:',
    tip: 'Para o MMC, você pega TODOS os fatores (repetidos ou não), sempre escolhendo o de maior expoente quando aparecer nos dois.',
    funFact: 'Esse método de fatoração é mais rápido para números grandes do que ficar listando múltiplos um por um!',
    points: 1,
    options: [
      { id: 'A', text: 'Comuns, com o menor expoente' },
      { id: 'B', text: 'Comuns e não comuns, com o maior expoente' },
      { id: 'C', text: 'Somente os não comuns' },
      { id: 'D', text: 'Somente os comuns' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'Para calcular o MDC por fatoração, multiplicamos os fatores primos:',
    tip: 'Para o MDC, você pega SÓ os fatores que aparecem nos dois números ao mesmo tempo, com o menor expoente.',
    funFact: 'MMC e MDC usam quase a mesma fatoração, só muda a regra de qual fator escolher!',
    points: 1,
    options: [
      { id: 'A', text: 'Comuns e não comuns' },
      { id: 'B', text: 'Somente os não comuns' },
      { id: 'C', text: 'Com o maior expoente' },
      { id: 'D', text: 'Comuns, com o menor expoente' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'Se dois números são primos entre si (não têm divisores comuns além do 1), o MDC entre eles é sempre:',
    tip: '"Primos entre si" significa que o único divisor em comum é o número 1 — e é exatamente isso que define o MDC deles!',
    funFact: '8 e 9 são primos entre si, mesmo sem nenhum dos dois ser um número primo sozinho!',
    points: 1,
    options: [
      { id: 'A', text: '1' },
      { id: 'B', text: '0' },
      { id: 'C', text: 'O maior dos dois números' },
      { id: 'D', text: 'A soma dos dois números' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'O produto de dois números é igual ao produto do MMC pelo MDC deles. Se o MMC de dois números é 24 e o MDC é 2, qual é o produto dos dois números?',
    tip: 'Use a fórmula: número1 x número2 = MMC x MDC. Basta multiplicar 24 x 2!',
    funFact: 'Essa relação entre MMC, MDC e o produto dos números é uma propriedade super útil da matemática!',
    points: 1,
    options: [
      { id: 'A', text: '26' },
      { id: 'B', text: '12' },
      { id: 'C', text: '48' },
      { id: 'D', text: '22' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Bernardo tem um treino de natação a cada 4 dias e um treino de futebol a cada 6 dias. Se ele fez os dois treinos hoje, depois de quantos dias eles vão coincidir novamente?',
    tip: '"Coincidir de novo" é a palavra-chave para pensar em MMC! Calcule o MMC entre 4 e 6.',
    funFact: 'Esportes com agendas diferentes são um jeito ótimo de praticar MMC sem nem perceber!',
    points: 1,
    options: [
      { id: 'A', text: '10 dias' },
      { id: 'B', text: '12 dias' },
      { id: 'C', text: '24 dias' },
      { id: 'D', text: '6 dias' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Bernardo quer organizar 20 figurinhas e 30 cartinhas em pacotinhos iguais, sem sobrar nenhuma, usando o maior número de pacotinhos possível. Quantos pacotinhos ele pode fazer?',
    tip: '"Sem sobrar, com o maior número possível de grupos" é a dica clássica de MDC! Calcule o MDC entre 20 e 30.',
    funFact: 'Cada pacotinho de Bernardo teria 2 figurinhas e 3 cartinhas, tudo bem dividido!',
    points: 1,
    options: [
      { id: 'A', text: '5' },
      { id: 'B', text: '20' },
      { id: 'C', text: '30' },
      { id: 'D', text: '10' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Na escola de Bernardo, o sinal para o recreio toca a cada 90 minutos e o sinal da troca de aula toca a cada 45 minutos. Se os dois sinais tocaram juntos às 8h, qual é o MMC entre 90 e 45?',
    tip: 'Repare que 90 já é um múltiplo de 45 (45 x 2 = 90)! Quando um número já é múltiplo do outro, o MMC é o próprio maior número.',
    funFact: 'Isso acontece sempre que um número "cabe" exatamente dentro do outro!',
    points: 1,
    options: [
      { id: 'A', text: '90' },
      { id: 'B', text: '45' },
      { id: 'C', text: '135' },
      { id: 'D', text: '4050' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Bernardo está separando seus 16 carrinhos e 24 bonecos de ação em prateleiras, cada prateleira com a mesma quantidade de cada brinquedo, sem sobrar nenhum. Qual é o maior número de prateleiras que ele pode usar?',
    tip: 'Calcule o MDC entre 16 e 24 — ele mostra o maior número de grupos iguais possível.',
    funFact: 'Com 8 prateleiras, cada uma teria 2 carrinhos e 3 bonecos — organização perfeita!',
    points: 1,
    options: [
      { id: 'A', text: '4' },
      { id: 'B', text: '16' },
      { id: 'C', text: '8' },
      { id: 'D', text: '24' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Bernardo percebeu que o número 17 só pode ser dividido por 1 e por ele mesmo. Isso significa que 17 é um número:',
    tip: 'Lembre da definição: só dois divisores (1 e ele mesmo) é a "assinatura" de um número primo!',
    funFact: 'Os números primos entre 1 e 20 são: 2, 3, 5, 7, 11, 13, 17 e 19 — tente decorar essa lista!',
    points: 1,
    options: [
      { id: 'A', text: 'Composto' },
      { id: 'B', text: 'Primo' },
      { id: 'C', text: 'Par' },
      { id: 'D', text: 'Múltiplo de 3' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Bernardo e sua irmã ganham mesada: ele a cada 5 dias e ela a cada 7 dias. Se os dois ganharam mesada hoje, qual é o MMC entre 5 e 7?',
    tip: 'Como 5 e 7 são primos entre si (não têm divisores em comum além do 1), o MMC deles é o produto direto: 5 x 7.',
    funFact: 'Quando dois números são primos entre si, calcular o MMC fica bem mais rápido — é só multiplicar!',
    points: 1,
    options: [
      { id: 'A', text: '12' },
      { id: 'B', text: '5' },
      { id: 'C', text: '7' },
      { id: 'D', text: '35' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Bernardo listou os divisores de 9: 1, 3 e 9. Como 9 tem mais de dois divisores, ele concluiu corretamente que 9 é um número:',
    tip: 'Mais de dois divisores é exatamente a definição de número composto — o contrário do número primo!',
    funFact: 'Muita gente confunde e acha que 9 é primo por engano, mas ele é composto porque 3 x 3 = 9!',
    points: 1,
    options: [
      { id: 'A', text: 'Primo' },
      { id: 'B', text: 'Par' },
      { id: 'C', text: 'Composto' },
      { id: 'D', text: 'Impossível de classificar' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Bernardo quer saber o MDC entre 10 e 10. Qual é o resultado?',
    tip: 'Quando os dois números são iguais, o maior divisor comum entre eles é o próprio número!',
    funFact: 'Esse é um caso especial que vale para qualquer número: o MDC de um número com ele mesmo é sempre ele mesmo!',
    points: 1,
    options: [
      { id: 'A', text: '10' },
      { id: 'B', text: '0' },
      { id: 'C', text: '1' },
      { id: 'D', text: '100' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Bernardo decompôs o número 30 em fatores primos e encontrou 2 x 3 x 5. Isso está correto porque 2, 3 e 5 são números:',
    tip: 'Uma fatoração só está completa quando TODOS os fatores são números primos — e 2, 3 e 5 são exatamente isso!',
    funFact: '30 também pode ser escrito como 2 x 3 x 5 de uma única forma — essa unicidade é chamada de "Teorema Fundamental da Aritmética"!',
    points: 1,
    options: [
      { id: 'A', text: 'Compostos' },
      { id: 'B', text: 'Primos' },
      { id: 'C', text: 'Pares' },
      { id: 'D', text: 'Múltiplos de 10' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'No fim do simulado, Bernardo revisou: o MMC de dois números é sempre ______ ao maior deles, e o MDC é sempre ______ ao menor deles.',
    tip: 'Pense nos exemplos que você já resolveu: o MMC sempre foi igual ou maior que o maior número, e o MDC sempre foi igual ou menor que o menor número!',
    funFact: 'Parabéns por chegar até aqui, Bernardo! Você já domina múltiplos, divisores, MMC e MDC — a base para tudo o que vem depois em frações!',
    points: 1,
    options: [
      { id: 'A', text: 'menor / maior' },
      { id: 'B', text: 'igual / igual' },
      { id: 'C', text: 'menor / menor' },
      { id: 'D', text: 'maior ou igual / menor ou igual' },
    ],
    correctAnswer: 'D',
  },
];
