export const questoesMatematica8AnoB3Av1 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "O que é uma equação do 1º grau?",
    tip: "Pense: é uma \"balança\" matemática que tem um sinal de igual e uma letra desconhecida com expoente 1.",
    funFact: "\"Equação\" vem do latim \"aequare\", que significa \"igualar\"!",
    points: 1,
    options: [
      { id: "A", text: "uma operação sem resultado" },
      { id: "B", text: "uma igualdade matemática com uma incógnita de expoente 1" },
      { id: "C", text: "uma divisão de números" },
      { id: "D", text: "um tipo de gráfico" },
    ],
    correctAnswer: "B",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "Na equação 2x + 3 = 7, o número que \"resolve\" a equação é chamado de:",
    tip: "É o valor que, colocado no lugar da letra, torna a igualdade verdadeira.",
    funFact: "A solução também é chamada de \"raiz\" da equação!",
    points: 1,
    options: [
      { id: "A", text: "coeficiente" },
      { id: "B", text: "expoente" },
      { id: "C", text: "termo" },
      { id: "D", text: "solução" },
    ],
    correctAnswer: "D",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "Na equação 2x + 3 = 7, tudo que está antes do sinal de igual é chamado de:",
    tip: "Pense na equação como uma balança: o lado esquerdo do \"=\" é o primeiro, o direito é o segundo.",
    funFact: "Numa balança de verdade, os dois lados (membros) sempre precisam ficar equilibrados, assim como na equação!",
    points: 1,
    options: [
      { id: "A", text: "1º membro" },
      { id: "B", text: "2º membro" },
      { id: "C", text: "solução" },
      { id: "D", text: "incógnita" },
    ],
    correctAnswer: "A",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "Qual é a regra de equivalência das equações?",
    tip: "Pense numa balança equilibrada: se você tira um peso de um lado, precisa tirar o mesmo peso do outro para continuar equilibrado!",
    funFact: "Essa regra é o segredo por trás de TODA equação que você vai resolver na vida!",
    points: 1,
    options: [
      { id: "A", text: "só podemos somar de um lado" },
      { id: "B", text: "a equação muda de valor sempre" },
      { id: "C", text: "o que fizermos de um lado, fazemos do outro também" },
      { id: "D", text: "nunca podemos mudar os dois lados" },
    ],
    correctAnswer: "C",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "Para resolver x + 5 = 12, qual operação você faz dos dois lados?",
    tip: "Você quer deixar o \"x\" sozinho. Como ele está \"+5\", que operação desfaz essa soma?",
    funFact: "Subtrair é a operação \"oposta\" da soma — por isso ela desfaz o que a soma fez!",
    points: 1,
    options: [
      { id: "A", text: "somar 5" },
      { id: "B", text: "subtrair 5" },
      { id: "C", text: "multiplicar por 5" },
      { id: "D", text: "dividir por 5" },
    ],
    correctAnswer: "B",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "Qual é a solução de x + 5 = 12?",
    tip: "Subtraia 5 dos dois lados: 12 − 5.",
    funFact: "Você pode confirmar fazendo o caminho contrário: 7 + 5 realmente dá 12!",
    points: 1,
    options: [
      { id: "A", text: "7" },
      { id: "B", text: "17" },
      { id: "C", text: "60" },
      { id: "D", text: "5" },
    ],
    correctAnswer: "A",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "Para resolver 3x = 15, qual operação você faz dos dois lados?",
    tip: "O \"x\" está sendo multiplicado por 3. Qual operação desfaz uma multiplicação?",
    funFact: "Divisão é a operação \"oposta\" da multiplicação, assim como subtração é da soma!",
    points: 1,
    options: [
      { id: "A", text: "somar 3" },
      { id: "B", text: "subtrair 3" },
      { id: "C", text: "multiplicar por 3" },
      { id: "D", text: "dividir por 3" },
    ],
    correctAnswer: "D",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "Qual é a solução de 3x = 15?",
    tip: "Divida os dois lados por 3: 15 ÷ 3.",
    funFact: "Você pode confirmar: 3 × 5 realmente dá 15!",
    points: 1,
    options: [
      { id: "A", text: "45" },
      { id: "B", text: "12" },
      { id: "C", text: "5" },
      { id: "D", text: "18" },
    ],
    correctAnswer: "C",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "Para verificar se x=5 é realmente a solução de 2x+1=11, você deve:",
    tip: "Troque o \"x\" pelo número 5 na equação original e resolva as contas com calma.",
    funFact: "Verificar a solução é como \"revisar a prova\" antes de entregar — sempre vale a pena!",
    points: 1,
    options: [
      { id: "A", text: "substituir x por 5 e ver se a igualdade fica verdadeira" },
      { id: "B", text: "somar 5 ao resultado" },
      { id: "C", text: "multiplicar a equação por 5" },
      { id: "D", text: "ignorar a verificação" },
    ],
    correctAnswer: "A",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "Resolvendo 2x − 3 = 9, qual é o primeiro passo?",
    tip: "Primeiro você precisa \"desfazer\" o −3, antes de lidar com a multiplicação por 2.",
    funFact: "Resolver equações é como descascar uma cebola: tira-se uma camada por vez, na ordem certa!",
    points: 1,
    options: [
      { id: "A", text: "dividir por 2" },
      { id: "B", text: "somar 3 nos dois lados" },
      { id: "C", text: "subtrair 2" },
      { id: "D", text: "multiplicar por 3" },
    ],
    correctAnswer: "B",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Qual é a solução de 2x − 3 = 9?",
    tip: "Depois de somar 3 nos dois lados (2x=12), o que falta fazer para isolar o x?",
    funFact: "Confirme: 2×6−3 realmente dá 9!",
    points: 1,
    options: [
      { id: "A", text: "12" },
      { id: "B", text: "3" },
      { id: "C", text: "6" },
      { id: "D", text: "18" },
    ],
    correctAnswer: "C",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Para resolver uma equação com parênteses, como 2(x+3)=10, o primeiro passo é:",
    tip: "Lembra da propriedade distributiva dos polinômios? O número de fora multiplica cada termo de dentro.",
    funFact: "Essa é a mesma propriedade distributiva que você usou no Bloco 2 com monômios e polinômios!",
    points: 1,
    options: [
      { id: "A", text: "aplicar a propriedade distributiva" },
      { id: "B", text: "ignorar os parênteses" },
      { id: "C", text: "somar os parênteses direto" },
      { id: "D", text: "dividir por 2 antes de tudo" },
    ],
    correctAnswer: "A",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "Aplicando a distributiva em 2(x+3)=10, a equação se transforma em:",
    tip: "Multiplique o 2 por cada termo dentro do parêntese: 2×x e 2×3.",
    funFact: "Depois dessa etapa, a equação fica bem mais fácil de resolver!",
    points: 1,
    options: [
      { id: "A", text: "2x + 3 = 10" },
      { id: "B", text: "x + 6 = 10" },
      { id: "C", text: "2x + 6 = 5" },
      { id: "D", text: "2x + 6 = 10" },
    ],
    correctAnswer: "D",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "Qual é a solução de 2(x+3)=10?",
    tip: "Depois de aplicar a distributiva (2x+6=10), resolva como uma equação comum.",
    funFact: "Confirme: 2×(2+3) = 2×5 = 10!",
    points: 1,
    options: [
      { id: "A", text: "5" },
      { id: "B", text: "2" },
      { id: "C", text: "8" },
      { id: "D", text: "10" },
    ],
    correctAnswer: "B",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Quando uma equação tem termos com x dos dois lados, como 5x + 2 = 3x + 8, o que devemos fazer primeiro?",
    tip: "Pense em organizar: todos os \"x\" de um lado da igualdade, todos os números soltos do outro.",
    funFact: "Esse é o mesmo princípio de \"juntar termos semelhantes\" que você usou com polinômios!",
    points: 1,
    options: [
      { id: "A", text: "juntar os termos com x de um lado e os números do outro" },
      { id: "B", text: "somar todos os números direto" },
      { id: "C", text: "multiplicar os dois lados por x" },
      { id: "D", text: "dividir tudo por 5" },
    ],
    correctAnswer: "A",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "Qual é a solução de 5x + 2 = 3x + 8?",
    tip: "Passe o 3x para o lado esquerdo (subtraindo) e o 2 para o lado direito (subtraindo): 2x = 6.",
    funFact: "Confirme: 5×3+2=17 e 3×3+8=17 — os dois lados ficam iguais!",
    points: 1,
    options: [
      { id: "A", text: "5" },
      { id: "B", text: "6" },
      { id: "C", text: "3" },
      { id: "D", text: "10" },
    ],
    correctAnswer: "C",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "Resolvendo 4x − 1 = 2x + 5, qual equação resulta depois de juntar os termos com x?",
    tip: "Passe o 2x para a esquerda e o −1 para a direita, cuidando dos sinais.",
    funFact: "Organizar passo a passo evita confusão — nunca faça duas mudanças de uma vez!",
    points: 1,
    options: [
      { id: "A", text: "2x = 4" },
      { id: "B", text: "2x = 6" },
      { id: "C", text: "6x = 6" },
      { id: "D", text: "2x = −6" },
    ],
    correctAnswer: "B",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "Qual é a solução de 4x − 1 = 2x + 5?",
    tip: "De 2x=6, qual operação isola o x?",
    funFact: "Confirme: 4×3−1=11 e 2×3+5=11!",
    points: 1,
    options: [
      { id: "A", text: "1" },
      { id: "B", text: "2" },
      { id: "C", text: "6" },
      { id: "D", text: "3" },
    ],
    correctAnswer: "D",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "Resolvendo a equação 3(x − 2) = 9, qual é o valor de x?",
    tip: "Primeiro aplique a distributiva (3x−6=9), depois resolva como equação comum.",
    funFact: "Confirme: 3×(5−2) = 3×3 = 9!",
    points: 1,
    options: [
      { id: "A", text: "3" },
      { id: "B", text: "7" },
      { id: "C", text: "5" },
      { id: "D", text: "1" },
    ],
    correctAnswer: "C",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "Numa equação, quando encontramos a solução, é importante verificar substituindo o valor porque:",
    tip: "Pense: se você errou uma conta no meio do caminho, a verificação te ajuda a descobrir isso.",
    funFact: "Até matemáticos profissionais sempre verificam seus resultados!",
    points: 1,
    options: [
      { id: "A", text: "garante que não cometemos erro nas contas" },
      { id: "B", text: "muda o resultado" },
      { id: "C", text: "é uma regra sem motivo" },
      { id: "D", text: "só é necessário em provas" },
    ],
    correctAnswer: "A",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Bernardo pensou em um número. Se ele somar 8 a esse número, obtém 15. Qual equação representa essa situação?",
    tip: "\"Pensei em um número\" é o x. \"Somar 8\" é +8. \"Obtém 15\" é = 15.",
    funFact: "Transformar um problema em equação é a parte mais importante — depois disso, resolver é fácil!",
    points: 1,
    options: [
      { id: "A", text: "x − 8 = 15" },
      { id: "B", text: "8x = 15" },
      { id: "C", text: "x + 15 = 8" },
      { id: "D", text: "x + 8 = 15" },
    ],
    correctAnswer: "D",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Qual é o número que Bernardo pensou?",
    tip: "Resolva x+8=15 subtraindo 8 dos dois lados.",
    funFact: "Confirme: 7+8 realmente dá 15!",
    points: 1,
    options: [
      { id: "A", text: "23" },
      { id: "B", text: "7" },
      { id: "C", text: "1,875" },
      { id: "D", text: "120" },
    ],
    correctAnswer: "B",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Bernardo tem o triplo de um número de figurinhas, que é igual a 24. Qual é a equação e a solução?",
    tip: "\"O triplo\" significa multiplicar por 3. Para achar x, divida 24 por 3.",
    funFact: "\"Triplo\" é outra forma de dizer \"o dobro e mais uma vez\" — ou seja, três vezes o número!",
    points: 1,
    options: [
      { id: "A", text: "3x=24, x=72" },
      { id: "B", text: "x+3=24, x=21" },
      { id: "C", text: "3x=24, x=8" },
      { id: "D", text: "3x=24, x=3" },
    ],
    correctAnswer: "C",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Bernardo tem x reais. Depois de gastar 10 reais, ficou com 25 reais. Qual equação representa isso?",
    tip: "\"Gastar\" significa diminuir. O que ele tinha (x), menos o que gastou (10), é igual ao que ficou (25).",
    funFact: "Esse tipo de equação é usado em qualquer app de controle financeiro!",
    points: 1,
    options: [
      { id: "A", text: "x − 10 = 25" },
      { id: "B", text: "x + 10 = 25" },
      { id: "C", text: "10 − x = 25" },
      { id: "D", text: "10x = 25" },
    ],
    correctAnswer: "A",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Quanto Bernardo tinha antes de gastar os 10 reais (resolvendo x − 10 = 25)?",
    tip: "Some 10 nos dois lados para isolar o x: 25 + 10.",
    funFact: "Confirme: 35−10 realmente dá 25!",
    points: 1,
    options: [
      { id: "A", text: "15" },
      { id: "B", text: "25" },
      { id: "C", text: "35" },
      { id: "D", text: "250" },
    ],
    correctAnswer: "C",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Bernardo tem o dobro da idade de sua irmã mais 2 anos, que resulta em 12 anos. Qual é a equação (sendo x a idade da irmã)?",
    tip: "\"O dobro\" é 2x, \"mais 2\" é +2, \"resulta em 12\" é =12.",
    funFact: "Problemas de idade são um dos tipos mais comuns de equação em provas — fique atento às palavras-chave!",
    points: 1,
    options: [
      { id: "A", text: "2x − 2 = 12" },
      { id: "B", text: "x + 2 = 12" },
      { id: "C", text: "2x = 12" },
      { id: "D", text: "2x + 2 = 12" },
    ],
    correctAnswer: "D",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Qual é a idade da irmã de Bernardo, resolvendo 2x + 2 = 12?",
    tip: "Primeiro subtraia 2 dos dois lados (2x=10), depois divida por 2.",
    funFact: "Confirme: 2×5+2 realmente dá 12!",
    points: 1,
    options: [
      { id: "A", text: "5" },
      { id: "B", text: "10" },
      { id: "C", text: "7" },
      { id: "D", text: "6" },
    ],
    correctAnswer: "A",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Bernardo comprou 3 pacotes iguais de figurinhas e usou mais um cupom de 2 figurinhas de bônus, totalizando 20 figurinhas. Qual equação representa isso (x = figurinhas por pacote)?",
    tip: "\"3 pacotes iguais\" é 3x, \"mais um cupom de 2\" é +2, \"totalizando 20\" é =20.",
    funFact: "Esse tipo de situação aparece direto em promoções de loja, com \"compre e ganhe\"!",
    points: 1,
    options: [
      { id: "A", text: "3x − 2 = 20" },
      { id: "B", text: "3x + 2 = 20" },
      { id: "C", text: "x + 2 = 20" },
      { id: "D", text: "3x = 20 + 2" },
    ],
    correctAnswer: "B",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Quantas figurinhas tinha cada pacote, resolvendo 3x + 2 = 20?",
    tip: "Primeiro subtraia 2 dos dois lados (3x=18), depois divida por 3.",
    funFact: "Confirme: 3×6+2 realmente dá 20!",
    points: 1,
    options: [
      { id: "A", text: "18" },
      { id: "B", text: "22" },
      { id: "C", text: "7,33" },
      { id: "D", text: "6" },
    ],
    correctAnswer: "D",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Revisando: para resolver qualquer equação do 1º grau, Bernardo deve lembrar de:",
    tip: "Pense na balança equilibrada: toda operação que você faz de um lado, precisa fazer do outro também.",
    funFact: "Essa é a ideia mais importante de toda a álgebra — e você já domina ela!",
    points: 1,
    options: [
      { id: "A", text: "resolver só um lado da equação" },
      { id: "B", text: "ignorar os sinais" },
      { id: "C", text: "manter a igualdade fazendo a mesma operação dos dois lados, até isolar a incógnita" },
      { id: "D", text: "sempre multiplicar por zero" },
    ],
    correctAnswer: "C",
  },
];
