export const questoesCiencias5AnoB3Av2 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "O que é uma estrela?",
    tip: "As estrelas são os astros mais abundantes e luminosos do universo. O que as caracteriza e as diferencia dos planetas?",
    funFact: "\"Você Sabia?\" — O Sol é uma estrela do tipo 'anã amarela' — uma classificação intermediária. Estrelas são classificadas por temperatura e cor: das mais quentes (azuis) para as mais frias (vermelhas), passando por brancas, amarelas e laranjas. A maioria das estrelas do universo são 'anãs vermelhas' — menores e mais frias que o Sol, mas incrivelmente duradouras: algumas vivem por trilhões de anos (o universo tem apenas 13,8 bilhões de anos, então nenhuma anã vermelha ainda morreu)!",
    points: 1,
    options: [
      { id: "A", text: "Um planeta que reflete a luz de outra estrela." },
      { id: "B", text: "Um satélite natural de um planeta." },
      { id: "C", text: "Um astro que produz e emite luz e calor próprios por meio de reações nucleares em seu núcleo." },
      { id: "D", text: "Um grande asteroide que orbita o Sol." },
    ],
    correctAnswer: "C",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "Qual é o movimento que a Lua faz ao redor da Terra?",
    tip: "O mesmo movimento que a Terra faz ao redor do Sol, a Lua faz ao redor da Terra. Como esse movimento se chama e quanto tempo leva?",
    funFact: "\"Você Sabia?\" — A Lua realiza dois movimentos que levam exatamente o mesmo tempo: translação (ao redor da Terra) e rotação (ao redor do próprio eixo), ambos com duração de aproximadamente 29,5 dias. Isso não é coincidência — é resultado de séculos de influência das forças de maré da Terra sobre a Lua. Por isso sempre vemos a mesma face da Lua! Esse fenômeno de 'trava gravitacional' é comum no universo: muitas luas de outros planetas estão travadas da mesma forma para seus planetas-mãe.",
    points: 1,
    options: [
      { id: "A", text: "Translação — a Lua orbita ao redor da Terra levando aproximadamente 29,5 dias para completar uma volta." },
      { id: "B", text: "Rotação — a Lua gira ao redor de seu próprio eixo levando 24 horas." },
      { id: "C", text: "Precessão — a Lua oscila em torno do eixo terrestre." },
      { id: "D", text: "Revolução solar — a Lua orbita ao redor do Sol." },
    ],
    correctAnswer: "A",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "O que é o equinócio?",
    tip: "O equinócio ocorre duas vezes por ano e está relacionado ao equilíbrio entre dia e noite. O que exatamente acontece nesse momento?",
    funFact: "\"Você Sabia?\" — O nome 'equinócio' vem do latim 'aequus nox' (noite igual) — porque nesse dia, o dia e a noite têm aproximadamente a mesma duração em qualquer ponto da Terra. Isso ocorre quando o eixo terrestre não aponta nem para o Sol nem para longe dele, mas fica perpendicular à linha Sol-Terra. Ocorre duas vezes por ano: por volta de 21 de março (início do outono no hemisfério sul / primavera no norte) e 23 de setembro (início da primavera no hemisfério sul / outono no norte).",
    points: 1,
    options: [
      { id: "A", text: "O dia em que ocorre o eclipse solar mais longo do ano." },
      { id: "B", text: "O período do ano em que a Lua está mais próxima da Terra." },
      { id: "C", text: "O momento em que a Terra está mais longe do Sol em sua órbita." },
      { id: "D", text: "O momento do ano em que o dia e a noite têm a mesma duração, resultado da posição do eixo terrestre em relação ao Sol." },
    ],
    correctAnswer: "D",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "Qual das seguintes estações do ano ocorre no hemisfério sul do Brasil durante os meses de dezembro a março?",
    tip: "O Brasil fica no hemisfério sul. As estações do hemisfério sul são opostas às do hemisfério norte — quando é verão no Brasil, é inverno na Europa. Qual estação vai de dezembro a março no Brasil?",
    funFact: "\"Você Sabia?\" — O Brasil é um país tão extenso que diferentes regiões experimentam as estações de formas bem diferentes. A região Sul tem inverno marcado com temperaturas baixas e até neve em alguns locais serranos. A região Norte, perto do equador, tem praticamente apenas duas estações: seca e chuvosa. O Nordeste tem um inverno 'ao contrário' — as chuvas ocorrem de março a julho (o 'inverno' nordestino). E a Amazônia tem chuvas intensas praticamente o ano todo. Um único país, múltiplos climas!",
    points: 1,
    options: [
      { id: "A", text: "Inverno" },
      { id: "B", text: "Verão" },
      { id: "C", text: "Primavera" },
      { id: "D", text: "Outono" },
    ],
    correctAnswer: "B",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "O que é uma nebulosa?",
    tip: "Nebulosas são estruturas observáveis no espaço com formas variadas e muitas vezes coloridas. O que são e por que são importantes para a formação de estrelas?",
    funFact: "\"Você Sabia?\" — A nebulosa mais famosa é a Nebulosa de Órion, visível a olho nu em noites claras como uma 'estrelinha borrada' abaixo das três estrelas alinhadas do cinturão de Órion. A Nebulosa do Olho de Gato, a da Cabeça de Cavalo, a de Carina — cada uma tem forma e composição única. O telescópio espacial Hubble revelou que o interior de muitas nebulosas são regiões de formação estelar ativa — os chamados 'Pilares da Criação' na Nebulosa da Águia são imagens icônicas de estrelas nascendo no espaço!",
    points: 1,
    options: [
      { id: "A", text: "Um tipo de planeta gasoso muito distante do Sol." },
      { id: "B", text: "Um cometa muito grande que se aproximou demais do Sol e explodiu." },
      { id: "C", text: "Uma nuvem de gás e poeira no espaço, onde novas estrelas frequentemente se formam." },
      { id: "D", text: "Um aglomerado de asteroides que orbita entre os planetas gigantes." },
    ],
    correctAnswer: "C",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "Qual é a estação do ano que se segue ao inverno no hemisfério sul?",
    tip: "As estações do ano se sucedem em uma ordem específica: primavera, verão, outono, inverno — e depois recomeça. Qual vem logo depois do inverno?",
    funFact: "\"Você Sabia?\" — A primavera é a estação dos 'renascentistas' na natureza — temperatura amena, dias maiores, plantas florescendo e animais saindo da hibernação (nos países de inverno mais rigoroso). No hemisfério sul, a primavera começa por volta de 23 de setembro e vai até 21 de dezembro. É a estação preferida de poetas e pintores ao longo da história — Vivaldi a imortalizou em 'As Quatro Estações', e Botticelli a pintou em 'A Primavera'. No Brasil, a primavera varia muito por região — no Sul é florido e agradável; no Norte, quase imperceptível.",
    points: 1,
    options: [
      { id: "A", text: "Primavera" },
      { id: "B", text: "Verão" },
      { id: "C", text: "Outono" },
      { id: "D", text: "Outro inverno" },
    ],
    correctAnswer: "A",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "O que é a força gravitacional?",
    tip: "A força gravitacional é fundamental para manter o universo organizado — mantém planetas em órbita, estrelas em galáxias, e nos mantém no chão. O que é exatamente essa força?",
    funFact: "\"Você Sabia?\" — A gravidade é a mais fraca das quatro forças fundamentais da natureza (gravitacional, eletromagnética, nuclear fraca, nuclear forte). Mas é a única que não pode ser blindada ou cancelada — e age a distâncias infinitas! Por isso domina em escalas astronômicas: estrelas, galáxias e o universo são moldados pela gravidade. Um fato curioso: você está atraindo o Sol agora mesmo — e o Sol está te atraindo. Apenas a diferença enorme de massa faz com que seja o Sol que 'fica parado' e a Terra que orbita!",
    points: 1,
    options: [
      { id: "A", text: "A força que move os planetas ao redor de seu próprio eixo." },
      { id: "B", text: "A força de atração que todo objeto com massa exerce sobre outros objetos, mantendo planetas em órbita e a Lua ao redor da Terra." },
      { id: "C", text: "A força que impede o Sol de se mover no espaço." },
      { id: "D", text: "A força elétrica que cria os campos magnéticos dos planetas." },
    ],
    correctAnswer: "B",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "Qual foi o primeiro ser humano a pisar na Lua?",
    tip: "A missão Apollo 11, em julho de 1969, marcou a história da humanidade. Qual astronauta deu o primeiro passo na superfície lunar?",
    funFact: "\"Você Sabia?\" — Neil Armstrong e Buzz Aldrin pousaram na Lua em 20 de julho de 1969. Ao descer do módulo lunar, Armstrong disse: 'That's one small step for [a] man, one giant leap for mankind' (Um pequeno passo para um homem, um salto gigante para a humanidade). O terceiro astronauta da missão, Michael Collins, ficou orbitando a Lua na cápsula de comando. Entre 1969 e 1972, 12 astronautas americanos caminharam na Lua — os últimos foram Eugene Cernan e Harrison Schmitt, em dezembro de 1972. Até hoje, são os únicos seres humanos a ter pisado em outro mundo.",
    points: 1,
    options: [
      { id: "A", text: "Yuri Gagarin" },
      { id: "B", text: "Buzz Aldrin" },
      { id: "C", text: "John Glenn" },
      { id: "D", text: "Neil Armstrong" },
    ],
    correctAnswer: "D",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "O que é a luz-ano?",
    tip: "Apesar de ter 'ano' no nome, a luz-ano não é uma medida de tempo — é uma medida de distância. O que ela representa?",
    funFact: "\"Você Sabia?\" — A luz percorre aproximadamente 300.000 km por segundo — em um ano, ela percorre cerca de 9,46 trilhões de quilômetros. Para ter uma ideia: a distância da Terra ao Sol é de apenas 150 milhões de km — ou seja, apenas 8 minutos-luz. A estrela mais próxima (Próxima Centauri) fica a 4,22 anos-luz. A galáxia de Andrômeda, a galáxia espiral mais próxima, está a 2,5 milhões de anos-luz — isso significa que a luz que vemos hoje partiu dela quando os primeiros humanos anatômicos começavam a surgir na África!",
    points: 1,
    options: [
      { id: "A", text: "A quantidade de luz que o Sol produz em um ano." },
      { id: "B", text: "O tempo que a Terra leva para completar uma translação ao redor do Sol." },
      { id: "C", text: "A distância que a luz percorre em um ano no vácuo — aproximadamente 9,46 trilhões de quilômetros." },
      { id: "D", text: "O brilho de uma estrela medido em comparação ao Sol." },
    ],
    correctAnswer: "C",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "Em qual hemisfério fica a maior parte do Brasil?",
    tip: "O Brasil é um país grande que cruza o equador. Mas a maior parte de seu território fica em qual hemisfério?",
    funFact: "\"Você Sabia?\" — O Brasil é o único país das Américas que cruza tanto o equador quanto o Trópico de Capricórnio! O equador cruza os estados do Amapá, Pará, Amazonas e Roraima (ao norte). O Trópico de Capricórnio cruza os estados de Mato Grosso do Sul, São Paulo, Paraná, Santa Catarina e Rio Grande do Sul (ao sul). Isso faz do Brasil um país com uma diversidade climática extraordinária — da floresta equatorial amazônica ao clima subtropical frio do Sul, tudo dentro de um único país.",
    points: 1,
    options: [
      { id: "A", text: "Hemisfério sul (maior parte) e hemisfério oeste." },
      { id: "B", text: "Hemisfério norte e hemisfério leste." },
      { id: "C", text: "Completamente no hemisfério norte." },
      { id: "D", text: "Completamente no hemisfério sul e leste." },
    ],
    correctAnswer: "A",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "O que é uma constelação?",
    tip: "Desde a antiguidade, as pessoas agruparam as estrelas em figuras imaginárias no céu. Como se chama esse agrupamento e para que serviu historicamente?",
    funFact: "\"Você Sabia?\" — As 88 constelações oficiais foram definidas pela União Astronômica Internacional em 1930. As culturas ocidentais herdaram as constelações dos gregos e babilônios, mas cada civilização tinha as suas próprias: os maias, os incas, os tupi-guaranis, os aborígenes australianos — todos criaram suas próprias constelações. Interessante: as estrelas de uma constelação geralmente não têm nenhuma relação física — podem estar a distâncias completamente diferentes. São apenas coincidências visuais da perspectiva da Terra!",
    points: 1,
    options: [
      { id: "A", text: "Um grupo de planetas que se formam ao redor de uma mesma estrela." },
      { id: "B", text: "O nome dado às estrelas que piscam no céu noturno." },
      { id: "C", text: "Uma galáxia vizinha da Via Láctea." },
      { id: "D", text: "Um grupo de estrelas que, observadas da Terra, formam um padrão no céu, usados para navegação e calendário." },
    ],
    correctAnswer: "D",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Por que sentimos mais calor no VERÃO do que no inverno?",
    tip: "A causa das estações não é a distância da Terra ao Sol (que varia pouco). A causa real tem a ver com como a luz solar chega à superfície em diferentes épocas do ano.",
    funFact: "\"Você Sabia?\" — Aqui vai uma demonstração simples: ilumine uma mesa com uma lanterna de cima (ângulo reto) — a luz concentra-se em um círculo pequeno e brilhante. Agora incline a lanterna — a mesma luz se espalha por uma área maior e menos intensa. É exatamente isso que acontece no inverno: o Sol está mais inclinado em relação ao horizonte, sua luz se espalha por uma área maior e cada metro quadrado recebe menos energia. No verão, o Sol fica mais alto no céu e a mesma energia solar concentra-se em menos área — mais calor!",
    points: 1,
    options: [
      { id: "A", text: "Porque a Terra está muito mais perto do Sol no verão." },
      { id: "B", text: "Porque o eixo terrestre inclina o hemisfério em direção ao Sol, fazendo a luz solar cair mais diretamente e por mais horas." },
      { id: "C", text: "Porque o Sol produz mais energia e calor no período do verão." },
      { id: "D", text: "Porque a rotação da Terra é mais rápida durante o verão." },
    ],
    correctAnswer: "B",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "O que é um buraco negro?",
    tip: "Um buraco negro é uma das estruturas mais extremas do universo. O que o define e o que o torna tão especial?",
    funFact: "\"Você Sabia?\" — A primeira imagem de um buraco negro foi obtida em 2019, pelo Telescópio de Horizonte de Eventos — uma rede global de radiotelescópios. A imagem mostrou o buraco negro no centro da galáxia M87, a 55 milhões de anos-luz da Terra, com uma massa 6,5 bilhões de vezes maior que o Sol! Em 2022, foi obtida a imagem do buraco negro supermassivo no centro da Via Láctea, chamado Sagittarius A*. No centro de praticamente toda galáxia grande existe um buraco negro supermassivo — incluindo o centro da nossa galáxia!",
    points: 1,
    options: [
      { id: "A", text: "Uma estrela muito brilhante no centro de uma galáxia." },
      { id: "B", text: "Uma região do espaço onde não existe absolutamente nada." },
      { id: "C", text: "Uma região com gravidade tão intensa que nem a luz consegue escapar, formada pelo colapso de estrelas muito massivas." },
      { id: "D", text: "Um planeta tão denso que absorve toda a luz ao seu redor." },
    ],
    correctAnswer: "C",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "O que é o eixo terrestre?",
    tip: "O eixo terrestre é imaginário — não existe fisicamente — mas é fundamental para entender os movimentos da Terra. O que é esse eixo?",
    funFact: "\"Você Sabia?\" — O eixo terrestre não é perpendicular (90°) ao plano orbital — ele está inclinado cerca de 23,5° em relação a essa perpendicular. Essa inclinação é a causa das estações do ano. Mas a inclinação do eixo não é fixa para sempre: ela oscila entre 22,1° e 24,5° ao longo de um ciclo de cerca de 41.000 anos (ciclo de Milankovitch). Essas oscilações, combinadas com outras variações orbitais, estão associadas aos ciclos de glaciações da Terra — períodos de muito frio que moldaram o planeta!",
    points: 1,
    options: [
      { id: "A", text: "Uma linha imaginária que passa pelos polos Norte e Sul da Terra, ao redor da qual ela gira durante a rotação." },
      { id: "B", text: "A faixa ao redor da Terra que divide os hemisférios norte e sul." },
      { id: "C", text: "O plano em que a Terra orbita ao redor do Sol." },
      { id: "D", text: "O ponto mais alto da atmosfera terrestre." },
    ],
    correctAnswer: "A",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Qual foi o primeiro satélite artificial lançado ao espaço?",
    tip: "A corrida espacial entre os EUA e a União Soviética marcou a segunda metade do século XX. Qual foi o primeiro satélite artificial enviado ao espaço?",
    funFact: "\"Você Sabia?\" — O Sputnik 1 foi lançado em 4 de outubro de 1957 pela União Soviética, inaugurando a era espacial. Era uma esfera de alumínio de 58 cm de diâmetro com 4 antenas de rádio. Ele não fazia nada além de emitir um simples 'bip-bip' pelo rádio — mas esse som foi ouvido em todo o mundo e causou um choque enorme nos EUA, que acreditavam ter superioridade tecnológica. O Sputnik levou à criação da NASA (1958) e acelerou enormemente a corrida espacial. O Sputnik 2, meses depois, levou a cadela Laika ao espaço — o primeiro ser vivo a orbitar a Terra!",
    points: 1,
    options: [
      { id: "A", text: "Apollo 11" },
      { id: "B", text: "Hubble" },
      { id: "C", text: "Voyager 1" },
      { id: "D", text: "Sputnik 1 (União Soviética, 1957)" },
    ],
    correctAnswer: "D",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "O que é a Zona Habitável de uma estrela?",
    tip: "A busca por vida extraterrestre considera uma região específica ao redor de estrelas como candidata a abrigar planetas com vida. O que é essa zona?",
    funFact: "\"Você Sabia?\" — A Terra está exatamente na Zona Habitável do Sol — a uma distância que permite água líquida. Vênus está ligeiramente mais perto e Marte ligeiramente mais longe — ambos fora da zona ideal (embora Marte tenha tido água líquida no passado). A sonda Kepler e o telescópio James Webb estão descobrindo planetas em zonas habitáveis de outras estrelas. Até hoje já foram encontrados mais de 5.000 exoplanetas, e alguns estão na zona habitável de suas estrelas — a busca por vida extraterrestre nunca foi tão promissora!",
    points: 1,
    options: [
      { id: "A", text: "A região de uma galáxia onde se formam novas estrelas." },
      { id: "B", text: "A região ao redor de uma estrela onde a temperatura permite que a água exista no estado líquido." },
      { id: "C", text: "A área da Terra onde os seres humanos podem viver sem equipamentos especiais." },
      { id: "D", text: "O espaço entre dois planetas no Sistema Solar." },
    ],
    correctAnswer: "B",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "O que é o equador terrestre?",
    tip: "O equador é uma linha imaginária fundamental da geografia terrestre. O que ele representa e onde fica?",
    funFact: "\"Você Sabia?\" — O equador tem exatamente 40.075 km de comprimento — e é o maior círculo que pode ser traçado ao redor da Terra. Cidades localizadas no equador têm dias e noites de quase exatamente 12 horas o ano todo — porque o Sol nasce e se põe quase perpendicular ao horizonte. Em Macapá (AP), que é cortada pelo equador, há uma estátua comemorativa e um campo de futebol onde a linha do equador passa exatamente pelo meio do campo — um time joga no hemisfério norte, o outro no sul!",
    points: 1,
    options: [
      { id: "A", text: "O polo norte magnético da Terra." },
      { id: "B", text: "O eixo inclinado da Terra em relação ao plano orbital." },
      { id: "C", text: "Uma linha imaginária que divide a Terra em dois hemisférios — norte e sul — equidistante dos polos." },
      { id: "D", text: "O ponto de maior altitude da superfície terrestre." },
    ],
    correctAnswer: "C",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "O que é a rotação LUNAR?",
    tip: "A Lua, como a Terra, também gira ao redor do próprio eixo. Qual é uma consequência interessante desse fato?",
    funFact: "\"Você Sabia?\" — A 'rotação síncrona' da Lua (girar ao seu redor no mesmo tempo que leva para orbitar a Terra) é causada pelas forças de maré que a Terra exerceu sobre a Lua durante bilhões de anos. O mesmo processo está acontecendo com a Terra em relação à Lua — só que muito mais lentamente. Daqui a bilhões de anos (se o Sol ainda existir), a Terra também estará sempre com a mesma face voltada para a Lua — cada 'dia' terrestre durará um 'mês' lunar. O sistema Terra-Lua está em um processo lento e constante de sincronização gravitacional!",
    points: 1,
    options: [
      { id: "A", text: "A Lua gira ao redor do seu próprio eixo no mesmo tempo que leva para orbitar a Terra — por isso sempre vemos a mesma face da Lua." },
      { id: "B", text: "O movimento da Lua ao redor do Sol." },
      { id: "C", text: "As fases da Lua que mudam a cada semana." },
      { id: "D", text: "A variação na distância entre a Lua e a Terra." },
    ],
    correctAnswer: "A",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "O que é um telescópio?",
    tip: "O telescópio é o instrumento mais importante da astronomia observacional. O que ele faz e como permite observar o que não pode ser visto a olho nu?",
    funFact: "\"Você Sabia?\" — O telescópio foi inventado por Hans Lippershey em 1608, mas Galileu Galilei foi o primeiro a usá-lo sistematicamente para observar o céu em 1609. Com ele, Galileu descobriu as quatro maiores luas de Júpiter (chamadas 'luas galileanas'), as fases de Vênus e as manchas solares — evidências que apoiavam o modelo heliocêntrico de Copérnico. Hoje, o telescópio espacial James Webb, operacional desde 2022, é o maior já construído — pode detectar o calor de uma abelha a 300 km de distância!",
    points: 1,
    options: [
      { id: "A", text: "Um instrumento usado para medir a temperatura das estrelas." },
      { id: "B", text: "Um equipamento que detecta ondas de rádio emitidas pelos planetas." },
      { id: "C", text: "Um aparelho que filtra a luz solar para proteção dos olhos." },
      { id: "D", text: "Um instrumento óptico que amplifica objetos distantes, permitindo observar estrelas e planetas com muito mais detalhes." },
    ],
    correctAnswer: "D",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "Por que o Brasil tem estações do ano MENOS extremas do que países como a Rússia ou o Canadá?",
    tip: "A intensidade das estações do ano está diretamente relacionada à localização geográfica de um país. O que faz as estações do Brasil serem menos extremas?",
    funFact: "\"Você Sabia?\" — Enquanto no Brasil o inverno mais intenso raramente chega a -20°C (no interior do RS e SC), na Sibéria as temperaturas podem chegar a -70°C! A diferença não é apenas conforto — ela molda toda a infraestrutura de uma cidade: construções, vestuário, alimentação, transporte. Yakutsk, na Rússia, é considerada a cidade habitada mais fria do mundo: em janeiro, a temperatura média é de -43°C. Os carros precisam ficar ligados 24 horas no inverno para não congelar, e respirar ao ar livre pode causar dor nos pulmões. Uma realidade inconcebível para a maioria dos brasileiros!",
    points: 1,
    options: [
      { id: "A", text: "Porque o Brasil está muito mais próximo do Sol do que esses países." },
      { id: "B", text: "Porque o Brasil está próximo do equador, onde o efeito da inclinação do eixo terrestre sobre a quantidade de luz solar é menor." },
      { id: "C", text: "Porque o Brasil tem florestas extensas que aquecem o ar no inverno." },
      { id: "D", text: "Porque o Brasil gira mais rapidamente ao redor do seu próprio eixo." },
    ],
    correctAnswer: "B",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Em que estação do ano o hemisfério sul está inclinado EM DIREÇÃO ao Sol?",
    tip: "As estações ocorrem porque o eixo terrestre está inclinado. Quando o hemisfério sul aponta em direção ao Sol, qual estação está acontecendo no Brasil?",
    funFact: "\"Você Sabia?\" — No verão do hemisfério sul, o Sol fica mais alto no céu ao meio-dia (mais próximo do zênite) e os dias são mais longos. Em cidades do sul do Brasil como Porto Alegre, em dezembro, o Sol pode durar até 14 horas. Em Belém (PA), próxima ao equador, a variação entre verão e inverno é mínima — os dias têm quase sempre 12 horas. Quanto mais longe do equador, mais extrema é a diferença entre as estações — isso porque o efeito da inclinação do eixo é maior nas latitudes mais altas!",
    points: 1,
    options: [
      { id: "A", text: "Inverno" },
      { id: "B", text: "Outono" },
      { id: "C", text: "Verão" },
      { id: "D", text: "Primavera" },
    ],
    correctAnswer: "C",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "O que é a superlua?",
    tip: "A superlua é um fenômeno em que a Lua aparece maior e mais brilhante que o normal. Por que isso acontece?",
    funFact: "\"Você Sabia?\" — A órbita da Lua ao redor da Terra não é um círculo perfeito — é uma elipse. O ponto mais próximo chama-se perigeu (cerca de 356.000 km) e o mais distante, apogeu (cerca de 406.000 km). Quando uma Lua Cheia coincide com o perigeu, temos a 'superlua' — ela pode parecer até 14% maior e 30% mais brilhante que em seu ponto mais distante. Em média, há 3 a 4 superluas por ano. Apesar do nome dramático, a diferença de tamanho é difícil de notar a olho nu sem comparação direta!",
    points: 1,
    options: [
      { id: "A", text: "O fenômeno em que a Lua aparece maior porque está no ponto mais próximo de sua órbita em relação à Terra (perigeu)." },
      { id: "B", text: "A fase de Lua Cheia que ocorre no solstício de verão." },
      { id: "C", text: "A Lua vista em um eclipse lunar total." },
      { id: "D", text: "Uma Lua Nova excepcionalmente brilhante." },
    ],
    correctAnswer: "A",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Qual é o nome da galáxia em que vivemos?",
    tip: "Nossa galáxia tem um nome poético que vem da mitologia grega e da aparência que ela tem no céu noturno. Qual é?",
    funFact: "\"Você Sabia?\" — A Via Láctea é uma galáxia espiral barrada — tem dois braços espirais principais e uma estrutura de barra no centro. O Sistema Solar fica em um dos braços espirais menores, chamado 'Braço de Órion', a cerca de 26.000 anos-luz do centro galáctico. O centro da Via Láctea contém um buraco negro supermassivo chamado Sagittarius A*, com uma massa equivalente a 4 milhões de sóis. Toda a galáxia demora aproximadamente 225 milhões de anos para girar — uma 'volta completa' que os astrônomos chamam de 'ano galáctico' ou 'ano cósmico'.",
    points: 1,
    options: [
      { id: "A", text: "Andrômeda" },
      { id: "B", text: "Grande Nuvem de Magalhães" },
      { id: "C", text: "Triângulo" },
      { id: "D", text: "Via Láctea" },
    ],
    correctAnswer: "D",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Qual das afirmações sobre o Sol está CORRETA?",
    tip: "O Sol é frequentemente descrito de formas exageradas — 'maior estrela', 'centro do universo'. Qual das afirmações é cientificamente precisa?",
    funFact: "\"Você Sabia?\" — O Sol é considerado uma estrela 'de população I' — uma estrela de terceira geração, formada de restos de estrelas anteriores que explodiram como supernovas. O carbono, oxigênio, ferro e todos os elementos pesados que formam seu corpo foram fabricados no interior de estrelas que viveram e morreram antes do Sol nascer. O astrônomo Carl Sagan costumava dizer: 'Somos feitos de pó de estrelas' — e é literalmente verdade! Cada átomo de ferro no seu sangue foi forjado no núcleo de uma estrela que explodiu há bilhões de anos.",
    points: 1,
    options: [
      { id: "A", text: "O Sol é a maior estrela do universo." },
      { id: "B", text: "O Sol é uma estrela de tamanho médio, a aproximadamente 150 milhões de quilômetros da Terra." },
      { id: "C", text: "O Sol orbita ao redor da Terra uma vez por ano." },
      { id: "D", text: "O Sol é um planeta gigante que produz calor por combustão." },
    ],
    correctAnswer: "B",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "O que é o perigeu?",
    tip: "A Lua não orbita a Terra em círculo perfeito — sua órbita é elíptica, com pontos mais próximos e mais distantes. Como se chama o ponto mais próximo?",
    funFact: "\"Você Sabia?\" — As palavras 'perigeu' e 'apogeu' vêm do grego: 'peri' (próximo) + 'geo' (Terra) e 'apo' (longe) + 'geo' (Terra). Para planetas ao redor do Sol, os termos equivalentes são 'periélio' (ponto mais próximo do Sol) e 'afélio' (mais distante), do grego 'helios' (Sol). No perigeu, a Lua está cerca de 356.000 km da Terra; no apogeu, cerca de 406.000 km. Essa diferença de 50.000 km pode parecer grande, mas representa apenas 12% da distância média — por isso a variação de tamanho aparente da Lua é discreta!",
    points: 1,
    options: [
      { id: "A", text: "O ponto da órbita terrestre mais próximo do Sol." },
      { id: "B", text: "O nome científico para o eclipse solar total." },
      { id: "C", text: "O ponto mais próximo da Terra na órbita da Lua." },
      { id: "D", text: "A posição do Sol durante o solstício de inverno." },
    ],
    correctAnswer: "C",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "O que é o afélio?",
    tip: "A Terra não orbita o Sol em círculo perfeito — a órbita é elíptica. O afélio é um dos dois pontos extremos dessa órbita. Qual é ele?",
    funFact: "\"Você Sabia?\" — Contrariando a intuição, a Terra está no afélio (mais distante do Sol) em julho — no meio do inverno do hemisfério sul e verão do norte! E está no periélio (mais próximo) em janeiro — no verão do hemisfério sul. Isso confirma que a distância Terra-Sol não causa as estações: a diferença de distância entre periélio e afélio é de apenas 5 milhões de km (cerca de 3%), o que tem impacto mínimo na temperatura. As estações são causadas pela inclinação do eixo terrestre, não pela distância ao Sol.",
    points: 1,
    options: [
      { id: "A", text: "O ponto da órbita terrestre mais distante do Sol." },
      { id: "B", text: "O ponto da órbita lunar mais próximo da Terra." },
      { id: "C", text: "O momento do equinócio de primavera no hemisfério sul." },
      { id: "D", text: "O centro geométrico da galáxia Via Láctea." },
    ],
    correctAnswer: "A",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Por que as estrelas PISCAM quando observadas a olho nu à noite?",
    tip: "As estrelas não piscam de verdade — são elas que emitem luz constante. O que acontece com essa luz antes de chegar até nossos olhos?",
    funFact: "\"Você Sabia?\" — Esse fenômeno se chama 'cintilação' estelar. Os planetas do Sistema Solar não piscam como as estrelas — ou piscam muito menos! Isso ocorre porque os planetas, mais próximos, apresentam um disco visível (mesmo que microscópico) — a luz de múltiplos pontos se media, reduzindo a cintilação. As estrelas, muito mais distantes, são pontos de luz tão pequenos que qualquer perturbação atmosférica afeta toda a imagem. Isso permite uma dica prática para identificar planetas no céu noturno: se um 'astro brilhante' não pisca, provavelmente é um planeta!",
    points: 1,
    options: [
      { id: "A", text: "Porque as estrelas variam de intensidade constantemente." },
      { id: "B", text: "Porque a rotação da Terra muda a posição das estrelas." },
      { id: "C", text: "Porque as estrelas são muito pequenas para serem vistas com clareza." },
      { id: "D", text: "Por causa da turbulência atmosférica — camadas de ar com diferentes temperaturas refratam a luz das estrelas de formas variáveis." },
    ],
    correctAnswer: "D",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "O que é o apogeu?",
    tip: "O apogeu é o ponto oposto ao perigeu na órbita da Lua. Se o perigeu é o ponto mais próximo, o apogeu é...?",
    funFact: "\"Você Sabia?\" — Quando a Lua está no apogeu (mais distante), um eclipse solar total é impossível — a Lua aparece menor que o Sol no céu e não consegue cobri-lo completamente. Em vez de eclipse total, ocorre um eclipse anular — a Lua cobre o centro do Sol, mas deixa um anel de fogo brilhante ao redor. Um eclipse anular tem uma aparência igualmente impressionante: um 'anel de fogo' no céu, diferente da escuridão dramática do eclipse total. Qual você prefere ver?",
    points: 1,
    options: [
      { id: "A", text: "O ponto da órbita terrestre mais distante do Sol." },
      { id: "B", text: "O ponto mais distante da Terra na órbita da Lua." },
      { id: "C", text: "O momento em que a Lua está completamente iluminada." },
      { id: "D", text: "O ponto da órbita de Marte mais próximo da Terra." },
    ],
    correctAnswer: "B",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Qual é a diferença entre um PLANETA e um PLANETA ANÃO?",
    tip: "Em 2006, a UAI (União Astronômica Internacional) estabeleceu três critérios para ser planeta. Planeta anão cumpre dois, mas não o terceiro. Qual é essa diferença?",
    funFact: "\"Você Sabia?\" — Plutão não é o único planeta anão! A UAI reconhece cinco planetas anões: Plutão, Eris, Makemake, Haumea e Ceres. Ceres é o único do Cinturão de Asteroides; os outros ficam no Cinturão de Kuiper, além de Netuno. Eris é tão grande quanto Plutão — foi justamente sua descoberta em 2005 que acelerou o debate que levou ao rebaixamento de Plutão. Muitos astrônomos acreditam que existem dezenas ou centenas de planetas anões ainda não descobertos além de Netuno!",
    points: 1,
    options: [
      { id: "A", text: "Os planetas anões são menores que a Lua." },
      { id: "B", text: "Os planetas anões ficam fora do Sistema Solar." },
      { id: "C", text: "Além de orbitar o Sol e ter forma esférica, um planeta deve ter limpado a vizinhança de sua órbita — o que Plutão não fez." },
      { id: "D", text: "Os planetas anões não têm satélites naturais." },
    ],
    correctAnswer: "C",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "O que é a astronomia?",
    tip: "A astronomia é uma das ciências mais antigas da humanidade. O que ela estuda?",
    funFact: "\"Você Sabia?\" — A astronomia é considerada a ciência mais antiga do mundo — há registros de observações astronômicas de 3.000 a 5.000 anos atrás no Egito, Mesopotâmia, China e Índia. As pirâmides do Egito, Stonehenge na Inglaterra e o observatório de Chichén Itzá no México são exemplos de estruturas construídas com alinhamentos astronômicos precisos. Já a astrologia, que prevê o futuro com base na posição dos astros, não é ciência — é uma crença sem base científica comprovada, muito diferente da astronomia, que usa o método científico.",
    points: 1,
    options: [
      { id: "A", text: "A ciência que estuda os astros, o espaço e os fenômenos que ocorrem no universo." },
      { id: "B", text: "A ciência que estuda a composição química da atmosfera terrestre." },
      { id: "C", text: "O estudo dos efeitos da gravidade nos seres vivos." },
      { id: "D", text: "A ciência que prevê o futuro com base na posição dos astros." },
    ],
    correctAnswer: "A",
  },
];
