export const questoesPortugues9AnoB4Av2 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "A VARIAÇÃO LINGUÍSTICA ocorre porque a língua:",
    tip: "Pense em como as pessoas falam de formas diferentes dependendo da região, da idade e da situação.",
    funFact: "\"Você Sabia?\" — Não existe variação linguística 'certa' ou 'errada' — cada variedade é adequada ao seu contexto. A linguística moderna rejeita o preconceito linguístico.",
    points: 1,
    options: [
      { id: "A", text: "É sempre estável e não muda ao longo do tempo." },
      { id: "B", text: "Pertence exclusivamente às classes sociais mais escolarizadas." },
      { id: "C", text: "Varia de acordo com fatores geográficos, sociais, históricos e situacionais." },
      { id: "D", text: "É idêntica em todos os países que falam o português." },
    ],
    correctAnswer: "C",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "A NORMA CULTA da língua portuguesa é:",
    tip: "Norma culta é a variedade usada em contextos formais — não é a 'melhor', é a mais valorizada socialmente.",
    funFact: "\"Você Sabia?\" — A norma culta é ensinada na escola e usada em textos formais, mas não é a única variedade legítima da língua — todas as variedades têm sua gramática própria.",
    points: 1,
    options: [
      { id: "A", text: "A única variedade correta da língua, sendo todas as demais erros." },
      { id: "B", text: "Um dialeto regional usado apenas no sudeste do Brasil." },
      { id: "C", text: "A variedade exclusivamente literária, usada apenas em obras clássicas." },
      { id: "D", text: "A variedade de prestígio social usada em contextos formais e ensinada na escola." },
    ],
    correctAnswer: "D",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "A FUNÇÃO REFERENCIAL da linguagem é predominante quando o texto:",
    tip: "Referencial = focado no referente (no assunto). Qual tipo de texto tem essa característica?",
    funFact: "\"Você Sabia?\" — Roman Jakobson, linguista russo, identificou seis funções da linguagem: referencial, emotiva, conativa, fática, metalinguística e poética — cada uma predomina em um tipo de comunicação.",
    points: 1,
    options: [
      { id: "A", text: "Transmite informações objetivas sobre a realidade, com foco no assunto." },
      { id: "B", text: "Expressa sentimentos e emoções do emissor de forma subjetiva." },
      { id: "C", text: "Explora os recursos sonoros e estéticos da própria linguagem." },
      { id: "D", text: "Tem como objetivo principal persuadir o receptor a agir." },
    ],
    correctAnswer: "A",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "No GÊNERO TEXTUAL 'crônica', o texto se caracteriza por:",
    tip: "Crônica é um texto jornalístico-literário — tem leveza, humor ou lirismo e fala do cotidiano.",
    funFact: "\"Você Sabia?\" — A crônica surgiu no jornalismo brasileiro e ganhou identidade própria como gênero literário com autores como Machado de Assis, Rubem Braga e Clarice Lispector.",
    points: 1,
    options: [
      { id: "A", text: "Ser sempre um texto longo com análise histórica aprofundada." },
      { id: "B", text: "Abordar fatos cotidianos de forma leve, geralmente com humor ou reflexão." },
      { id: "C", text: "Apresentar dados estatísticos e embasamento científico rigoroso." },
      { id: "D", text: "Narrar batalhas épicas de heróis nacionais em versos." },
    ],
    correctAnswer: "B",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "As FIGURAS DE LINGUAGEM são recursos expressivos que ampliam o poder comunicativo do texto. A METÁFORA consiste em:",
    tip: "A metáfora diz que uma coisa É outra (sem o 'como') — ela transfere o significado.",
    funFact: "\"Você Sabia?\" — A metáfora não existe só na literatura — usamos metáforas no cotidiano o tempo todo: 'ele é uma raposa' (esperto), 'ela tem um coração de pedra' (insensível).",
    points: 1,
    options: [
      { id: "A", text: "Imitar os sons da natureza por meio de palavras." },
      { id: "B", text: "Exagerar uma situação para criar efeito dramático ou cômico." },
      { id: "C", text: "Usar uma palavra no sentido figurado, transferindo características de uma coisa para outra." },
      { id: "D", text: "Comparar duas coisas explicitamente usando 'como' ou 'assim como'." },
    ],
    correctAnswer: "C",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "A IRONIA como figura de linguagem consiste em:",
    tip: "Ironia é dizer o contrário do que se pensa — mas de forma que o contexto permita perceber o verdadeiro sentido.",
    funFact: "\"Você Sabia?\" — A ironia socrática era usada pelo filósofo grego Sócrates para fingir ignorância e levar o interlocutor a reconhecer suas próprias contradições — base do método socrático.",
    points: 1,
    options: [
      { id: "A", text: "Repetir a mesma palavra no início de vários versos seguidos." },
      { id: "B", text: "Omitir palavras que podem ser deduzidas pelo contexto." },
      { id: "C", text: "Exagerar uma característica para criar efeito expressivo." },
      { id: "D", text: "Usar palavras com sentido contrário ao real para criar efeito crítico ou humorístico." },
    ],
    correctAnswer: "D",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "O TEXTO ARGUMENTATIVO tem como elemento central:",
    tip: "Sem esse elemento, o texto argumentativo não existe — ele é o ponto de partida obrigatório.",
    funFact: "\"Você Sabia?\" — Uma boa tese deve ser controversa (nem todo mundo concorda) — afirmações óbvias como 'a saúde é importante' não geram argumentação real.",
    points: 1,
    options: [
      { id: "A", text: "Uma narrativa de um fato histórico marcante." },
      { id: "B", text: "Uma tese — posição do autor que será defendida com argumentos." },
      { id: "C", text: "Uma descrição detalhada de personagens e ambientes." },
      { id: "D", text: "Um conjunto de dados científicos sem posicionamento do autor." },
    ],
    correctAnswer: "B",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "Em poesia, a RIMA CONSOANTE ocorre quando:",
    tip: "Rima consoante é a mais completa — o que exatamente coincide no final dos versos?",
    funFact: "\"Você Sabia?\" — A rima consoante é a mais usada na poesia clássica e no cordel — palavras como 'amor/dor', 'vida/corrida' têm rima consoante.",
    points: 1,
    options: [
      { id: "A", text: "Vogais e consoantes finais dos versos coincidem completamente." },
      { id: "B", text: "Apenas as vogais finais dos versos são iguais." },
      { id: "C", text: "Apenas o início dos versos apresenta sons semelhantes." },
      { id: "D", text: "O número de sílabas dos versos é igual." },
    ],
    correctAnswer: "A",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "O SONETO, forma poética clássica, é composto por:",
    tip: "Lembre-se da estrutura do soneto — quantos versos e como estão distribuídos?",
    funFact: "\"Você Sabia?\" — Camões, Shakespeare e Fernando Pessoa são os maiores sonetistas das literaturas de língua portuguesa e inglesa — o soneto atravessou séculos mantendo sua estrutura básica.",
    points: 1,
    options: [
      { id: "A", text: "Três quartetos e um dístico, totalizando 14 versos." },
      { id: "B", text: "Quatro tercetos, totalizando 12 versos." },
      { id: "C", text: "Dois quartetos e dois tercetos, totalizando 14 versos." },
      { id: "D", text: "Cinco estrofes de três versos, totalizando 15 versos." },
    ],
    correctAnswer: "C",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "A CONJUNÇÃO ADVERSATIVA 'mas' é usada para:",
    tip: "Quando uma ideia vem depois do 'mas', ela contradiz ou restringe o que veio antes.",
    funFact: "\"Você Sabia?\" — 'Mas', 'porém', 'contudo', 'todavia', 'entretanto', 'no entanto' são conjunções adversativas — todas indicam oposição, mas têm registros diferentes: 'mas' é mais informal; as demais são formais.",
    points: 1,
    options: [
      { id: "A", text: "Indicar a conclusão lógica da oração anterior." },
      { id: "B", text: "Expressar uma ideia contrária ou restritiva em relação à oração anterior." },
      { id: "C", text: "Ligar duas orações com sentido de adição." },
      { id: "D", text: "Introduzir uma condição necessária para a oração principal." },
    ],
    correctAnswer: "B",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "A COESÃO TEXTUAL é garantida principalmente por:",
    tip: "Coesão é a ligação formal entre partes do texto — quais elementos realizam essa ligação?",
    funFact: "\"Você Sabia?\" — Um texto sem coesão é como um quebra-cabeça desmontado: as peças (informações) estão lá, mas sem encaixe. Os conectivos e pronomes são as 'peças' que encaixam o texto.",
    points: 1,
    options: [
      { id: "A", text: "O emprego de figuras de linguagem em todos os parágrafos." },
      { id: "B", text: "O uso exclusivo de frases curtas e diretas." },
      { id: "C", text: "A repetição constante das palavras-chave em todos os parágrafos." },
      { id: "D", text: "Conectivos, pronomes e expressões referenciais que ligam as partes do texto." },
    ],
    correctAnswer: "D",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "A COERÊNCIA TEXTUAL diz respeito à:",
    tip: "Coerência é diferente de coesão — ela trata da lógica e do sentido geral do texto.",
    funFact: "\"Você Sabia?\" — Um texto pode ter boa coesão (conectivos certos) e ser incoerente (sem lógica). Um texto incoerente é aquele em que as ideias se contradizem ou não têm relação lógica entre si.",
    points: 1,
    options: [
      { id: "A", text: "Quantidade de conectivos e pronomes usados no texto." },
      { id: "B", text: "Lógica e unidade de sentido do texto, sem contradições internas." },
      { id: "C", text: "Extensão do texto — textos mais longos são mais coerentes." },
      { id: "D", text: "Uso correto da ortografia e da pontuação." },
    ],
    correctAnswer: "B",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "O VERSO LIVRE, muito usado no Modernismo, se caracteriza por:",
    tip: "Livre significa ausência de restrições — o que fica ausente no verso livre?",
    funFact: "\"Você Sabia?\" — O verso livre não é 'verso sem arte' — exige muito controle rítmico e expressivo. Drummond e Manuel Bandeira demonstraram isso ao criar obras de grande beleza sem métrica fixa.",
    points: 1,
    options: [
      { id: "A", text: "Ter exatamente dez sílabas poéticas e usar rimas obrigatórias." },
      { id: "B", text: "Ser exclusivo de poemas narrativos sobre temas épicos." },
      { id: "C", text: "Não seguir padrões fixos de métrica ou rima obrigatória." },
      { id: "D", text: "Usar apenas palavras monossilábicas para criar brevidade." },
    ],
    correctAnswer: "C",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "A oração subordinada adjetiva RESTRITIVA se diferencia da EXPLICATIVA porque:",
    tip: "Restritiva limita; explicativa acrescenta. Como isso aparece na pontuação?",
    funFact: "\"Você Sabia?\" — A distinção entre adjetiva restritiva e explicativa pode mudar completamente o sentido de uma frase — e é por isso que a vírgula antes do 'que' faz toda a diferença.",
    points: 1,
    options: [
      { id: "A", text: "A restritiva é introduzida por 'cujo'; a explicativa por 'que'." },
      { id: "B", text: "A restritiva não usa vírgulas e limita o sentido do substantivo; a explicativa é separada por vírgulas e acrescenta informação." },
      { id: "C", text: "A restritiva é mais longa e detalhada; a explicativa é sempre mais curta." },
      { id: "D", text: "A restritiva aparece no final da frase; a explicativa sempre no início." },
    ],
    correctAnswer: "B",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "O gênero ARTIGO DE OPINIÃO se distingue do editorial jornalístico porque:",
    tip: "Pense em quem assina cada um — o artigo de opinião tem autoria individual; o editorial, não.",
    funFact: "\"Você Sabia?\" — Os maiores articulistas brasileiros, como Elio Gaspari e Eliane Brum, são reconhecidos por seu estilo próprio e ponto de vista identificável — algo impossível no editorial anônimo.",
    points: 1,
    options: [
      { id: "A", text: "O artigo de opinião é sempre mais longo e aprofundado do que o editorial." },
      { id: "B", text: "O artigo de opinião usa dados científicos; o editorial usa apenas opiniões." },
      { id: "C", text: "O artigo de opinião nunca defende uma tese; o editorial sempre o faz." },
      { id: "D", text: "O artigo de opinião tem autoria individual identificada; o editorial representa a posição do veículo." },
    ],
    correctAnswer: "D",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "A FUNÇÃO POÉTICA da linguagem é predominante quando o texto:",
    tip: "A função poética privilegia a forma — o texto chama atenção para si mesmo, para os sons e as imagens.",
    funFact: "\"Você Sabia?\" — A função poética não é exclusiva da poesia — ela aparece em slogans publicitários, trocadilhos, músicas e até em conversas cotidiano quando alguém usa uma linguagem criativa.",
    points: 1,
    options: [
      { id: "A", text: "Explora os recursos estéticos da linguagem — sons, ritmo, imagens — como elemento central." },
      { id: "B", text: "Transmite informações objetivas com linguagem técnica e impessoal." },
      { id: "C", text: "Tem como objetivo principal persuadir o leitor a adotar uma posição." },
      { id: "D", text: "Verifica se o canal de comunicação está funcionando." },
    ],
    correctAnswer: "A",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "O HAIKU japonês é uma forma poética caracterizada por:",
    tip: "O haiku é extremamente sintético — captura um único momento da natureza em pouquíssimos versos.",
    funFact: "\"Você Sabia?\" — O haiku tradicional japonês sempre faz referência a uma estação do ano ('kigo') e busca capturar uma experiência sensorial imediata com economia máxima de palavras.",
    points: 1,
    options: [
      { id: "A", text: "Catorze versos organizados em dois quartetos e dois tercetos." },
      { id: "B", text: "Seis versos com rimas alternadas, muito usado no cordel nordestino." },
      { id: "C", text: "Três versos geralmente com 5, 7 e 5 sílabas, que capturam um momento da natureza." },
      { id: "D", text: "Dez versos decassílabos com temas épicos e heroicos." },
    ],
    correctAnswer: "C",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "O MODERNISMO BRASILEIRO (a partir de 1922) trouxe como ruptura central:",
    tip: "O Modernismo rejeitou as formas fixas do Parnasianismo e do Simbolismo — o que ele colocou no lugar?",
    funFact: "\"Você Sabia?\" — A Semana de Arte Moderna de 1922 foi patrocinada por aristocratas paulistas que, paradoxalmente, financiaram a revolução artística que subvertia seus próprios valores culturais.",
    points: 1,
    options: [
      { id: "A", text: "Retorno às formas clássicas gregas e latinas como o soneto e a ode." },
      { id: "B", text: "Valorização do português europeu e abandono do falar brasileiro." },
      { id: "C", text: "Exclusividade de temas religiosos e patrióticos." },
      { id: "D", text: "Verso livre, linguagem cotidiana, identidade brasileira e experimentação estética." },
    ],
    correctAnswer: "D",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "As ORAÇÕES COORDENADAS SINDÉTICAS CONCLUSIVAS são introduzidas por conjunções que indicam:",
    tip: "Conclusiva = conclusão. O que essas conjunções introduzem em relação à oração anterior?",
    funFact: "\"Você Sabia?\" — 'Portanto', 'logo', 'então', 'por conseguinte', 'assim' são as principais conjunções conclusivas — elas são muito usadas em textos argumentativos para indicar a conclusão de um raciocínio.",
    points: 1,
    options: [
      { id: "A", text: "Uma oposição ou contraste com a ideia da oração anterior." },
      { id: "B", text: "Uma consequência ou conclusão lógica derivada da oração anterior." },
      { id: "C", text: "Uma adição de informação à oração anterior." },
      { id: "D", text: "Uma alternativa excludente entre duas possibilidades." },
    ],
    correctAnswer: "B",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "A INTERTEXTUALIDADE consiste em:",
    tip: "O prefixo 'inter' significa 'entre' — o que acontece entre dois textos quando há intertextualidade?",
    funFact: "\"Você Sabia?\" — A intertextualidade está em toda a literatura: nenhum texto surge do nada — todo autor dialoga com os textos que leu. Julia Kristeva foi a primeira a teorizar sistematicamente esse fenômeno.",
    points: 1,
    options: [
      { id: "A", text: "Um texto dialogar com, citar, imitar ou transformar outro texto preexistente." },
      { id: "B", text: "A publicação de dois textos no mesmo livro ou coletânea." },
      { id: "C", text: "A tradução de um texto de outra língua para o português." },
      { id: "D", text: "O texto usar exclusivamente palavras simples e do cotidiano." },
    ],
    correctAnswer: "A",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "A LITERATURA DE CORDEL é um gênero literário tipicamente brasileiro que se caracteriza por:",
    tip: "O cordel tem características muito específicas de forma, distribuição e temática — o que o define?",
    funFact: "\"Você Sabia?\" — A literatura de cordel recebeu esse nome porque os folhetos eram pendurados em cordéis (barbantes) nas feiras do Nordeste para serem vendidos. Em 2018, foi reconhecida como patrimônio cultural imaterial do Brasil.",
    points: 1,
    options: [
      { id: "A", text: "Ser escrito em prosa, tratando de temas urbanos contemporâneos." },
      { id: "B", text: "Usar verso livre e linguagem poética modernista." },
      { id: "C", text: "Apresentar narrativa em versos rimados (sextilhas), com temas populares, heroicos ou humorísticos." },
      { id: "D", text: "Ser exclusivamente de autores eruditos das universidades nordestinas." },
    ],
    correctAnswer: "C",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Na análise do DISCURSO, o CONTEXTO DE PRODUÇÃO de um texto inclui:",
    tip: "Todo texto é produzido em uma situação específica — quem escreve, para quem, quando, onde e por quê.",
    funFact: "\"Você Sabia?\" — O contexto de produção é fundamental para interpretar textos históricos: um discurso de 1500 precisa ser analisado no contexto do Brasil colonial, não com os valores do século XXI.",
    points: 1,
    options: [
      { id: "A", text: "Apenas o vocabulário e as estruturas gramaticais usados no texto." },
      { id: "B", text: "O autor, o suporte de publicação, a época, o destinatário e o propósito comunicativo." },
      { id: "C", text: "Somente os dados biográficos do autor do texto." },
      { id: "D", text: "Apenas a análise das figuras de linguagem presentes no texto." },
    ],
    correctAnswer: "B",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "A PERSUASÃO em textos argumentativos pode ser alcançada por meio de:",
    tip: "Aristóteles identificou três pilares da persuasão — razão, emoção e credibilidade do autor.",
    funFact: "\"Você Sabia?\" — Os três apelos retóricos de Aristóteles — logos (razão), pathos (emoção) e ethos (credibilidade) — continuam sendo as bases do ensino de argumentação em todo o mundo.",
    points: 1,
    options: [
      { id: "A", text: "Apenas repetir a tese várias vezes ao longo do texto." },
      { id: "B", text: "Usar somente gírias e linguagem informal para aproximar o leitor." },
      { id: "C", text: "Ignorar completamente os argumentos contrários para manter o foco." },
      { id: "D", text: "Argumentos racionais (dados, exemplos), apelos emocionais e credibilidade do autor." },
    ],
    correctAnswer: "D",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "O PERÍODO COMPOSTO por SUBORDINAÇÃO se caracteriza por:",
    tip: "Subordinação cria dependência — uma oração precisa da outra para ter sentido completo.",
    funFact: "\"Você Sabia?\" — Períodos compostos por subordinação costumam ser mais complexos do que os por coordenação — por isso aparecem mais em textos formais e literários do que em conversas cotidianas.",
    points: 1,
    options: [
      { id: "A", text: "Ser formado por orações que dependem umas das outras para ter sentido completo." },
      { id: "B", text: "Ter obrigatoriamente mais de cinco orações no mesmo período." },
      { id: "C", text: "Apresentar orações independentes ligadas por vírgulas ou ponto e vírgula." },
      { id: "D", text: "Usar exclusivamente conjunções aditivas para ligar as orações." },
    ],
    correctAnswer: "A",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "O PRONOME RELATIVO 'CUJO' estabelece no período uma relação de:",
    tip: "'Cujo' funciona como 'do qual' ou 'da qual' — essa substituição revela sua função.",
    funFact: "\"Você Sabia?\" — 'Cujo' é um dos pronomes relativos mais cobrados em provas porque seu uso exige atenção especial: ele sempre indica posse e concorda com o substantivo seguinte, não com o antecedente.",
    points: 1,
    options: [
      { id: "A", text: "Tempo em que a ação ocorre." },
      { id: "B", text: "Lugar onde a ação se desenvolve." },
      { id: "C", text: "Posse entre o antecedente e o substantivo que o segue." },
      { id: "D", text: "Causa da ação expressa na oração principal." },
    ],
    correctAnswer: "C",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "A PERSONIFICAÇÃO (prosopopeia) consiste em:",
    tip: "Personificar = atribuir características humanas. A quê isso pode ser feito?",
    funFact: "\"Você Sabia?\" — A personificação da natureza foi um dos recursos mais explorados pelo Romantismo — em poemas românticos, o mar chora, o vento suspira e a tempestade expressa a angústia do poeta.",
    points: 1,
    options: [
      { id: "A", text: "Criar uma história fictícia para ilustrar um argumento." },
      { id: "B", text: "Atribuir características, sentimentos ou ações humanas a seres não humanos ou inanimados." },
      { id: "C", text: "Comparar dois elementos usando termos comparativos explícitos." },
      { id: "D", text: "Usar palavras que imitam sons naturais." },
    ],
    correctAnswer: "B",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "A ORAÇÃO SUBORDINADA ADVERBIAL CONCESSIVA é introduzida por conjunções como 'embora', 'apesar de que', 'mesmo que'. Ela indica:",
    tip: "Concessão = admitir algo desfavorável sem que isso impeça o resultado da oração principal.",
    funFact: "\"Você Sabia?\" — As concessivas são a marca de um texto argumentativo maduro — ao reconhecer pontos contrários (concessão) e depois refutá-los, o autor demonstra conhecimento do tema.",
    points: 1,
    options: [
      { id: "A", text: "A condição necessária para que a ação principal aconteça." },
      { id: "B", text: "O motivo ou causa da ação expressa na oração principal." },
      { id: "C", text: "Uma consequência extrema que decorre da ação principal." },
      { id: "D", text: "Uma situação contrária que, apesar de existir, não impede a realização da oração principal." },
    ],
    correctAnswer: "D",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "A INTERPRETAÇÃO DE TEXTO exige do leitor a habilidade de:",
    tip: "Interpretar vai além de apenas decodificar palavras — envolve relacionar, inferir e contextualizar.",
    funFact: "\"Você Sabia?\" — A interpretação de texto é a habilidade mais valorizada no ENEM: a maioria das questões de linguagens exige que o aluno vá além do que está escrito e faça inferências e conexões.",
    points: 1,
    options: [
      { id: "A", text: "Identificar sentido literal, inferir informações e relacionar o texto ao contexto." },
      { id: "B", text: "Copiar trechos do texto como resposta às perguntas." },
      { id: "C", text: "Decorar todas as regras gramaticais da língua portuguesa." },
      { id: "D", text: "Identificar apenas as figuras de linguagem presentes no texto." },
    ],
    correctAnswer: "A",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "A PROGRESSÃO TEMÁTICA em um texto dissertativo garante que:",
    tip: "Progressão = avanço. Em um bom texto, o que deve avançar de parágrafo a parágrafo?",
    funFact: "\"Você Sabia?\" — Textos sem progressão temática ficam marcados pela nota zero na competência de 'desenvolvimento do tema' no ENEM — o avaliador espera que cada parágrafo acrescente algo novo.",
    points: 1,
    options: [
      { id: "A", text: "Cada parágrafo repita a tese para garantir que o leitor entenda bem." },
      { id: "B", text: "O texto use o maior número possível de conectivos e pronomes." },
      { id: "C", text: "Cada parágrafo avance o raciocínio, acrescentando novos argumentos ou informações." },
      { id: "D", text: "O texto apresente apenas os argumentos favoráveis à tese, ignorando os contrários." },
    ],
    correctAnswer: "C",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Ao finalizar o 9º ano, o estudo de Língua Portuguesa visa, em última análise, a:",
    tip: "Pense no objetivo maior de todo o aprendizado de língua materna — para que serve dominar a língua?",
    funFact: "\"Você Sabia?\" — A BNCC (Base Nacional Comum Curricular) define o ensino de Língua Portuguesa como promotor de 'práticas de linguagem', não apenas de regras gramaticais — a língua como ferramenta de participação social.",
    points: 1,
    options: [
      { id: "A", text: "Decorar todas as regras gramaticais para passar em provas." },
      { id: "B", text: "Ampliar a competência comunicativa, a leitura crítica e a participação ativa na sociedade." },
      { id: "C", text: "Aprender exclusivamente o português literário dos clássicos." },
      { id: "D", text: "Eliminar as variações linguísticas regionais em favor da norma culta." },
    ],
    correctAnswer: "B",
  },
];
