export const questoesGeografia8AnoB1Av2 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "O processo de integração econômica, cultural e tecnológica entre os países do mundo, intensificado nas últimas décadas, é chamado de:",
    tip: "Pense no nome que descreve a conexão cada vez maior entre os países do mundo todo, em diversas áreas.",
    funFact: "\"Você sabia?\" — A palavra 'globalização' vem de 'globo', referindo-se ao planeta Terra como um todo interconectado!",
    points: 1,
    options: [
      { id: "A", text: "Neocolonialismo" },
      { id: "B", text: "Industrialização" },
      { id: "C", text: "Urbanização" },
      { id: "D", text: "Globalização" },
    ],
    correctAnswer: "D",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "Os avanços na internet, nos transportes e nas telecomunicações contribuíram diretamente para intensificar o processo de:",
    tip: "Pense em como essas tecnologias aproximaram as pessoas e os países, facilitando trocas e comunicação.",
    funFact: "\"Você sabia?\" — Hoje é possível fazer uma videochamada com alguém do outro lado do mundo instantaneamente, algo impensável há poucas décadas!",
    points: 1,
    options: [
      { id: "A", text: "Colonização" },
      { id: "B", text: "Globalização" },
      { id: "C", text: "Isolamento econômico" },
      { id: "D", text: "Nenhum processo específico" },
    ],
    correctAnswer: "B",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "Um grupo de países que se une por meio de acordos para facilitar o comércio entre si é chamado de:",
    tip: "Pense no nome que descreve essa união de países com objetivos comerciais em comum.",
    funFact: "\"Você sabia?\" — Existem blocos econômicos em praticamente todos os continentes do mundo!",
    points: 1,
    options: [
      { id: "A", text: "Colônia" },
      { id: "B", text: "Império" },
      { id: "C", text: "Bloco econômico" },
      { id: "D", text: "Estado unitário" },
    ],
    correctAnswer: "C",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "O Mercosul é um bloco econômico formado principalmente por países da:",
    tip: "Pense no continente onde está localizado o Brasil, um dos principais membros desse bloco.",
    funFact: "\"Você sabia?\" — O Mercosul foi criado em 1991, com o objetivo de facilitar o comércio entre Brasil, Argentina, Paraguai e Uruguai!",
    points: 1,
    options: [
      { id: "A", text: "América do Sul" },
      { id: "B", text: "Europa" },
      { id: "C", text: "Ásia" },
      { id: "D", text: "África" },
    ],
    correctAnswer: "A",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "A União Europeia é um bloco econômico e político formado por diversos países do continente:",
    tip: "Pense no próprio nome do bloco — ele já indica diretamente o continente ao qual pertence.",
    funFact: "\"Você sabia?\" — Muitos países da União Europeia usam a mesma moeda, o euro, facilitando ainda mais o comércio entre eles!",
    points: 1,
    options: [
      { id: "A", text: "Americano" },
      { id: "B", text: "Europeu" },
      { id: "C", text: "Asiático" },
      { id: "D", text: "Africano" },
    ],
    correctAnswer: "B",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "Empresas que atuam em diversos países ao mesmo tempo, com fábricas e filiais em diferentes continentes, são chamadas de empresas:",
    tip: "Pense no prefixo 'multi', que significa 'muitos' — são empresas presentes em muitas nações diferentes.",
    funFact: "\"Você sabia?\" — Algumas multinacionais têm receitas anuais maiores do que o PIB de vários países pequenos!",
    points: 1,
    options: [
      { id: "A", text: "Estatais" },
      { id: "B", text: "Familiares" },
      { id: "C", text: "Locais apenas" },
      { id: "D", text: "Multinacionais (ou transnacionais)" },
    ],
    correctAnswer: "D",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "A globalização facilitou o acesso das pessoas a produtos, informações e culturas de:",
    tip: "Pense em como hoje conseguimos acessar filmes, músicas e produtos de qualquer lugar do mundo com facilidade.",
    funFact: "\"Você sabia?\" — Hoje é possível assistir a filmes e séries de outros países quase no mesmo dia do lançamento original!",
    points: 1,
    options: [
      { id: "A", text: "Diferentes países do mundo" },
      { id: "B", text: "Apenas sua própria cidade" },
      { id: "C", text: "Apenas seu próprio país" },
      { id: "D", text: "Nenhum lugar diferente" },
    ],
    correctAnswer: "A",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "Uma das críticas à globalização é que ela pode aumentar a desigualdade entre:",
    tip: "Pense na diferença econômica entre nações que já são bem desenvolvidas e aquelas que ainda estão se desenvolvendo.",
    funFact: "\"Você sabia?\" — Economistas debatem bastante se a globalização diminui ou aumenta essa desigualdade, dependendo de como é conduzida!",
    points: 1,
    options: [
      { id: "A", text: "Diferentes cores de pele apenas" },
      { id: "B", text: "Diferentes religiões apenas" },
      { id: "C", text: "Países ricos e países pobres" },
      { id: "D", text: "Nenhum grupo específico" },
    ],
    correctAnswer: "C",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "A revolução técnico-científica-informacional, que impulsionou a globalização, está relacionada principalmente ao avanço:",
    tip: "Pense no próprio nome dessa revolução — ela tem relação direta com avanços tecnológicos e de informação.",
    funFact: "\"Você sabia?\" — Essa revolução também é chamada de 'Terceira Revolução Industrial', marcada pela informática e pelas telecomunicações!",
    points: 1,
    options: [
      { id: "A", text: "Da agricultura tradicional" },
      { id: "B", text: "Do artesanato manual" },
      { id: "C", text: "Da pecuária extensiva" },
      { id: "D", text: "Da tecnologia e da informação" },
    ],
    correctAnswer: "D",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "Um exemplo de bloco econômico formado por países da América do Norte é o:",
    tip: "Pense nos três países da América do Norte que fizeram um acordo comercial famoso, renovado mais recentemente.",
    funFact: "\"Você sabia?\" — Esse acordo facilitou muito o comércio entre esses três países, mudando de nome de NAFTA para USMCA em 2020!",
    points: 1,
    options: [
      { id: "A", text: "Mercosul" },
      { id: "B", text: "Acordo entre Estados Unidos, México e Canadá (antigo NAFTA, hoje USMCA)" },
      { id: "C", text: "ASEAN" },
      { id: "D", text: "União Europeia" },
    ],
    correctAnswer: "B",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Quando uma pessoa no Brasil compra, pela internet, um produto fabricado em outro país e recebido em poucos dias, isso é um exemplo direto de como a globalização facilita:",
    tip: "Pense no que realmente está acontecendo nessa compra — um produto cruzando fronteiras rapidamente até chegar ao comprador.",
    funFact: "\"Você sabia?\" — O comércio eletrônico internacional cresceu muito nas últimas décadas, graças à globalização e à internet!",
    points: 1,
    options: [
      { id: "A", text: "O comércio internacional e a troca de produtos entre países" },
      { id: "B", text: "Apenas o comércio dentro do próprio país" },
      { id: "C", text: "O isolamento econômico" },
      { id: "D", text: "Nenhuma mudança na economia" },
    ],
    correctAnswer: "A",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Países que fazem parte de um bloco econômico, como o Mercosul, costumam ter benefícios como a redução de:",
    tip: "Pense no principal objetivo de criar um bloco econômico — facilitar o comércio entre os países que fazem parte dele.",
    funFact: "\"Você sabia?\" — Essa redução de taxas torna produtos de outros países do bloco mais baratos e competitivos no mercado interno!",
    points: 1,
    options: [
      { id: "A", text: "Impostos apenas para fora do bloco" },
      { id: "B", text: "Barreiras comerciais e taxas entre os países-membros apenas para alguns produtos" },
      { id: "C", text: "Barreiras comerciais e taxas entre os países-membros" },
      { id: "D", text: "Nenhum benefício real" },
    ],
    correctAnswer: "C",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "A globalização também trouxe desafios, como a possibilidade de empresas multinacionais buscarem países com:",
    tip: "Pense no motivo econômico pelo qual algumas empresas procuram países com regras mais flexíveis — isso reduz os custos de produção.",
    funFact: "\"Você sabia?\" — Esse tema gera debates importantes sobre direitos dos trabalhadores e proteção ambiental em escala global!",
    points: 1,
    options: [
      { id: "A", text: "Leis trabalhistas e ambientais mais rígidas" },
      { id: "B", text: "Salários mais altos para os trabalhadores" },
      { id: "C", text: "Impostos sempre mais altos" },
      { id: "D", text: "Leis trabalhistas e ambientais mais flexíveis, reduzindo custos" },
    ],
    correctAnswer: "D",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "A difusão global de músicas, filmes e produtos culturais de diferentes países é um exemplo de globalização:",
    tip: "Pense no tipo de globalização relacionada a hábitos, costumes, arte e entretenimento, e não apenas a dinheiro ou política.",
    funFact: "\"Você sabia?\" — Músicas e séries de diferentes países, como K-pop coreano e animes japoneses, fazem sucesso mundial graças a essa globalização cultural!",
    points: 1,
    options: [
      { id: "A", text: "Apenas econômica" },
      { id: "B", text: "Cultural" },
      { id: "C", text: "Apenas política" },
      { id: "D", text: "Nenhum tipo específico" },
    ],
    correctAnswer: "B",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Um país que exporta matérias-primas e importa produtos industrializados mais caros tende a ter uma relação:",
    tip: "Pense na diferença de valor entre matéria-prima bruta e produto já industrializado — isso cria um desequilíbrio comercial.",
    funFact: "\"Você sabia?\" — Produtos industrializados costumam valer muito mais no mercado do que as matérias-primas usadas para fabricá-los!",
    points: 1,
    options: [
      { id: "A", text: "Totalmente equilibrada e vantajosa" },
      { id: "B", text: "Sem nenhuma consequência econômica" },
      { id: "C", text: "Comercial desigual, dependendo mais dos países mais industrializados" },
      { id: "D", text: "Independente da economia mundial" },
    ],
    correctAnswer: "C",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "A criação de blocos econômicos, como a União Europeia, busca fortalecer a economia dos países-membros através da:",
    tip: "Pense no verdadeiro objetivo de formar um bloco — trabalhar junto, não isolar cada país ou eliminar o comércio.",
    funFact: "\"Você sabia?\" — A União Europeia começou como um acordo mais simples, focado só no carvão e no aço, e foi crescendo até se tornar o bloco que é hoje!",
    points: 1,
    options: [
      { id: "A", text: "Cooperação e integração comercial entre eles" },
      { id: "B", text: "Competição isolada entre cada país" },
      { id: "C", text: "Independência total de qualquer acordo" },
      { id: "D", text: "Eliminação do comércio internacional" },
    ],
    correctAnswer: "A",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "A rapidez com que notícias e informações se espalham pelo mundo hoje é um exemplo direto de como a tecnologia impulsionou a:",
    tip: "Pense em como as notícias de qualquer parte do mundo chegam até nós quase instantaneamente hoje em dia.",
    funFact: "\"Você sabia?\" — Antigamente, uma notícia poderia levar semanas ou meses para atravessar o oceano — hoje, isso acontece em segundos!",
    points: 1,
    options: [
      { id: "A", text: "Diminuição da comunicação global" },
      { id: "B", text: "Globalização da informação" },
      { id: "C", text: "Isolamento cultural" },
      { id: "D", text: "Nenhuma mudança na comunicação" },
    ],
    correctAnswer: "B",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "Multinacionais que instalam fábricas em diferentes países geralmente buscam, entre outros fatores, locais com:",
    tip: "Pense no motivo financeiro pelo qual uma empresa escolhe instalar fábricas em determinados países — geralmente é para reduzir custos.",
    funFact: "\"Você sabia?\" — Essa busca por custos mais baixos é uma das razões pelas quais muitas fábricas de roupas e eletrônicos estão localizadas em países asiáticos!",
    points: 1,
    options: [
      { id: "A", text: "Impostos sempre mais altos" },
      { id: "B", text: "Leis trabalhistas sempre mais rígidas" },
      { id: "C", text: "Nenhuma vantagem econômica" },
      { id: "D", text: "Mão de obra mais barata e menos regulamentações" },
    ],
    correctAnswer: "D",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "A globalização também pode gerar uma 'padronização cultural', em que produtos e costumes de poucos países dominam o mundo, o que gera debates sobre a:",
    tip: "Pense no que pode acontecer com culturas locais quando poucos países e marcas dominam o que o mundo consome.",
    funFact: "\"Você sabia?\" — Esse tema é tão debatido que existem movimentos para preservar línguas e tradições locais frente à globalização!",
    points: 1,
    options: [
      { id: "A", text: "Perda de diversidade cultural local" },
      { id: "B", text: "Nenhuma preocupação cultural" },
      { id: "C", text: "Valorização exclusiva das culturas locais" },
      { id: "D", text: "Eliminação total da cultura global" },
    ],
    correctAnswer: "A",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "O comércio entre os países-membros de um bloco econômico, como o Mercosul, costuma ser facilitado por meio da redução de:",
    tip: "Pense no principal objetivo econômico de criar um bloco — tornar mais barato comerciar entre os países que fazem parte dele.",
    funFact: "\"Você sabia?\" — Essa redução de tarifas ajuda a tornar produtos de países vizinhos mais competitivos dentro do próprio bloco!",
    points: 1,
    options: [
      { id: "A", text: "Investimentos estrangeiros" },
      { id: "B", text: "População total" },
      { id: "C", text: "Tarifas e impostos entre os países do bloco" },
      { id: "D", text: "Produção industrial" },
    ],
    correctAnswer: "C",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Bernardo comprou, pela internet, um produto eletrônico fabricado em outro país e o recebeu em poucos dias no Brasil. Isso é um exemplo direto de como a globalização facilita:",
    tip: "Pense no que realmente aconteceu nessa compra de Bernardo — um produto cruzando fronteiras rapidamente.",
    funFact: "\"Você sabia?\" — O comércio eletrônico internacional cresceu muito nas últimas décadas, graças à globalização e à internet!",
    points: 1,
    options: [
      { id: "A", text: "Apenas o comércio dentro do próprio país" },
      { id: "B", text: "O comércio internacional e a troca de produtos entre países" },
      { id: "C", text: "O isolamento econômico" },
      { id: "D", text: "Nenhuma mudança na economia" },
    ],
    correctAnswer: "B",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Bernardo descobriu que empresas que atuam em diversos países ao mesmo tempo, com fábricas e filiais em diferentes continentes, são chamadas de empresas:",
    tip: "Pense no prefixo 'multi', relacionado a 'muitos' países diferentes onde essas empresas atuam.",
    funFact: "\"Você sabia?\" — Algumas multinacionais têm receitas anuais maiores do que o PIB de vários países pequenos!",
    points: 1,
    options: [
      { id: "A", text: "Estatais" },
      { id: "B", text: "Familiares" },
      { id: "C", text: "Locais apenas" },
      { id: "D", text: "Multinacionais (ou transnacionais)" },
    ],
    correctAnswer: "D",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Bernardo aprendeu que o Mercosul é um bloco econômico formado principalmente por países da:",
    tip: "Pense no continente onde está localizado o Brasil, um dos principais membros desse bloco.",
    funFact: "\"Você sabia?\" — O Mercosul foi criado em 1991, facilitando o comércio entre Brasil, Argentina, Paraguai e Uruguai!",
    points: 1,
    options: [
      { id: "A", text: "América do Sul" },
      { id: "B", text: "Europa" },
      { id: "C", text: "Ásia" },
      { id: "D", text: "África" },
    ],
    correctAnswer: "A",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Bernardo pesquisou sobre blocos econômicos e descobriu que eles costumam trazer benefícios como a redução de:",
    tip: "Pense no principal objetivo de criar um bloco econômico — facilitar o comércio entre os países-membros.",
    funFact: "\"Você sabia?\" — Essa redução de taxas torna produtos de outros países do bloco mais baratos e competitivos!",
    points: 1,
    options: [
      { id: "A", text: "Impostos apenas para fora do bloco" },
      { id: "B", text: "Barreiras comerciais apenas para alguns produtos" },
      { id: "C", text: "Barreiras comerciais e taxas entre os países-membros" },
      { id: "D", text: "Nenhum benefício real" },
    ],
    correctAnswer: "C",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Bernardo entendeu que a globalização também trouxe desafios, como a possibilidade de empresas multinacionais buscarem países com:",
    tip: "Pense no motivo econômico pelo qual algumas empresas procuram países com regras mais flexíveis.",
    funFact: "\"Você sabia?\" — Esse tema gera debates importantes sobre direitos dos trabalhadores e proteção ambiental em escala global!",
    points: 1,
    options: [
      { id: "A", text: "Leis trabalhistas e ambientais mais rígidas" },
      { id: "B", text: "Salários mais altos para os trabalhadores" },
      { id: "C", text: "Impostos sempre mais altos" },
      { id: "D", text: "Leis trabalhistas e ambientais mais flexíveis, reduzindo custos" },
    ],
    correctAnswer: "D",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Bernardo percebeu que a difusão global de músicas, filmes e produtos culturais de diferentes países é um exemplo de globalização:",
    tip: "Pense no tipo de globalização relacionada a costumes, arte e entretenimento, e não apenas a dinheiro.",
    funFact: "\"Você sabia?\" — Músicas e séries de diferentes países fazem sucesso mundial graças a essa globalização cultural!",
    points: 1,
    options: [
      { id: "A", text: "Apenas econômica" },
      { id: "B", text: "Cultural" },
      { id: "C", text: "Apenas política" },
      { id: "D", text: "Nenhum tipo específico" },
    ],
    correctAnswer: "B",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Bernardo descobriu que um país que exporta matérias-primas e importa produtos industrializados mais caros tende a ter uma relação:",
    tip: "Pense na diferença de valor entre matéria-prima bruta e produto já industrializado.",
    funFact: "\"Você sabia?\" — Produtos industrializados costumam valer muito mais no mercado do que as matérias-primas usadas para fabricá-los!",
    points: 1,
    options: [
      { id: "A", text: "Totalmente equilibrada e vantajosa" },
      { id: "B", text: "Sem nenhuma consequência econômica" },
      { id: "C", text: "Comercial desigual, dependendo mais dos países mais industrializados" },
      { id: "D", text: "Independente da economia mundial" },
    ],
    correctAnswer: "C",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Bernardo entendeu que a criação de blocos econômicos, como a União Europeia, busca fortalecer a economia dos países-membros através da:",
    tip: "Pense no verdadeiro objetivo de formar um bloco econômico — trabalhar junto, e não isolar cada país.",
    funFact: "\"Você sabia?\" — A União Europeia começou como um acordo mais simples e foi crescendo até se tornar o bloco que é hoje!",
    points: 1,
    options: [
      { id: "A", text: "Cooperação e integração comercial entre eles" },
      { id: "B", text: "Competição isolada entre cada país" },
      { id: "C", text: "Independência total de qualquer acordo" },
      { id: "D", text: "Eliminação do comércio internacional" },
    ],
    correctAnswer: "A",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Bernardo percebeu que a rapidez com que notícias e informações se espalham pelo mundo hoje é um exemplo direto de como a tecnologia impulsionou a:",
    tip: "Pense em como as notícias de qualquer parte do mundo chegam até Bernardo quase instantaneamente hoje em dia.",
    funFact: "\"Você sabia?\" — Antigamente, uma notícia poderia levar semanas para atravessar o oceano — hoje, acontece em segundos!",
    points: 1,
    options: [
      { id: "A", text: "Diminuição da comunicação global" },
      { id: "B", text: "Globalização da informação" },
      { id: "C", text: "Isolamento cultural" },
      { id: "D", text: "Nenhuma mudança na comunicação" },
    ],
    correctAnswer: "B",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Bernardo entendeu que multinacionais que instalam fábricas em diferentes países geralmente buscam, entre outros fatores, locais com:",
    tip: "Pense no motivo financeiro pelo qual uma empresa escolhe instalar fábricas em determinados países.",
    funFact: "\"Você sabia?\" — Essa busca por custos mais baixos é uma das razões pelas quais muitas fábricas estão localizadas em países asiáticos!",
    points: 1,
    options: [
      { id: "A", text: "Impostos sempre mais altos" },
      { id: "B", text: "Leis trabalhistas sempre mais rígidas" },
      { id: "C", text: "Nenhuma vantagem econômica" },
      { id: "D", text: "Mão de obra mais barata e menos regulamentações" },
    ],
    correctAnswer: "D",
  },
];
