export const questoesGeografia6AnoB4Av1 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'O que é "densidade demográfica"?',
    tip: 'Pense em quantas pessoas vivem, em média, em cada pedacinho de terra (como 1 km²).',
    funFact: 'Uma cidade pode ter poucos habitantes, mas se for pequena em área, ainda ter uma densidade demográfica alta!',
    points: 1,
    options: [
      { id: 'A', text: 'A quantidade total de rios de um país' },
      { id: 'B', text: 'O tipo de vegetação predominante numa região' },
      { id: 'C', text: 'A relação entre o número de habitantes e a área de um território (habitantes por km²)' },
      { id: 'D', text: 'A altura média das pessoas de uma região' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'Como está distribuída a população brasileira pelo território, de forma geral?',
    tip: 'Pense em como as grandes cidades brasileiras, como Rio de Janeiro e Salvador, ficam perto do mar.',
    funFact: 'Mais da metade da população brasileira vive a menos de 200 km do litoral!',
    points: 1,
    options: [
      { id: 'A', text: 'De forma desigual, mais concentrada perto do litoral' },
      { id: 'B', text: 'De forma perfeitamente igual, com o mesmo número de pessoas em cada km²' },
      { id: 'C', text: 'Toda concentrada no interior da Amazônia' },
      { id: 'D', text: 'Toda concentrada em áreas de montanha' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'Qual é o nome do órgão brasileiro responsável por fazer o Censo e contar a população do país?',
    tip: 'Pense na sigla de três letras que aparece quando se fala em dados sobre a população do Brasil.',
    funFact: 'O Censo do IBGE visita praticamente todos os domicílios do país para coletar informações!',
    points: 1,
    options: [
      { id: 'A', text: 'Ministério da Agricultura' },
      { id: 'B', text: 'Corpo de Bombeiros' },
      { id: 'C', text: 'Banco Central' },
      { id: 'D', text: 'IBGE (Instituto Brasileiro de Geografia e Estatística)' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'Como se chama o processo de as pessoas saírem do campo para morar nas cidades?',
    tip: 'Pense em uma "saída em massa" do campo, em direção às cidades.',
    funFact: 'O êxodo rural foi um dos grandes motivos pelos quais a maior parte da população brasileira hoje vive em cidades!',
    points: 1,
    options: [
      { id: 'A', text: 'Imigração' },
      { id: 'B', text: 'Êxodo rural' },
      { id: 'C', text: 'Fuso horário' },
      { id: 'D', text: 'Erosão' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'Hoje, a maior parte da população brasileira vive em áreas:',
    tip: 'Pense em onde moram a maioria das pessoas que você conhece: no campo ou na cidade?',
    funFact: 'Mais de 80% da população brasileira vive hoje em áreas urbanas!',
    points: 1,
    options: [
      { id: 'A', text: 'Urbanas (cidades)' },
      { id: 'B', text: 'Totalmente desabitadas' },
      { id: 'C', text: 'Exclusivamente rurais' },
      { id: 'D', text: 'Apenas em ilhas' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'Qual região do Brasil é a mais populosa, concentrando o maior número de habitantes?',
    tip: 'Pense na região onde ficam São Paulo e Rio de Janeiro.',
    funFact: 'Só o estado de São Paulo tem mais habitantes do que muitos países inteiros!',
    points: 1,
    options: [
      { id: 'A', text: 'Norte' },
      { id: 'B', text: 'Centro-Oeste' },
      { id: 'C', text: 'Sudeste' },
      { id: 'D', text: 'Sul' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'Qual região do Brasil tem, em geral, a menor densidade demográfica, apesar de ser uma das maiores em área?',
    tip: 'Pense na região onde fica a Floresta Amazônica, com grandes áreas pouco habitadas.',
    funFact: 'Apesar de ser a maior região em território, o Norte tem uma das menores densidades demográficas do Brasil!',
    points: 1,
    options: [
      { id: 'A', text: 'Sudeste' },
      { id: 'B', text: 'Norte' },
      { id: 'C', text: 'Sul' },
      { id: 'D', text: 'Nordeste' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'O que pode explicar por que uma grande cidade tem uma densidade demográfica muito alta?',
    tip: 'Pense em como um prédio de apartamentos pode ter muita gente morando em um espaço pequeno.',
    funFact: 'Alguns bairros de São Paulo têm uma densidade demográfica altíssima!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque tem uma área territorial imensa e poucos habitantes' },
      { id: 'B', text: 'Porque não tem nenhum morador' },
      { id: 'C', text: 'Porque fica isolada no meio de uma floresta' },
      { id: 'D', text: 'Porque concentra muitos habitantes em uma área relativamente pequena' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'Por que muitas pessoas migraram do campo para as cidades nas últimas décadas?',
    tip: 'Pense nas oportunidades que muitas pessoas buscam ao se mudar para uma cidade maior.',
    funFact: 'Esse movimento contribuiu para o crescimento acelerado de muitas cidades brasileiras no século 20!',
    points: 1,
    options: [
      { id: 'A', text: 'Em busca de emprego, escolas e serviços disponíveis nas áreas urbanas' },
      { id: 'B', text: 'Porque as cidades não oferecem nenhum tipo de serviço' },
      { id: 'C', text: 'Porque o campo tinha mais empregos disponíveis' },
      { id: 'D', text: 'Porque foram obrigadas por lei a se mudar' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'Por que é importante conhecer a distribuição da população em um país?',
    tip: 'Pense em como saber onde as pessoas moram ajuda o governo a planejar melhor os serviços que elas precisam.',
    funFact: 'Os dados do Censo ajudam a decidir onde construir novas escolas e hospitais!',
    points: 1,
    options: [
      { id: 'A', text: 'Não existe nenhuma importância prática' },
      { id: 'B', text: 'Serve apenas para fazer provas de Geografia' },
      { id: 'C', text: 'Ajuda no planejamento de escolas, hospitais, moradias e serviços públicos' },
      { id: 'D', text: 'Serve só para definir o nome das cidades' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'O que significa dizer que a população brasileira está "envelhecendo", em termos demográficos?',
    tip: 'Pense em como a proporção de pessoas mais velhas pode crescer com o tempo.',
    funFact: 'O aumento da expectativa de vida é um dos motivos que fazem a população de um país envelhecer aos poucos!',
    points: 1,
    options: [
      { id: 'A', text: 'Que todos os brasileiros já são idosos' },
      { id: 'B', text: 'Que a proporção de pessoas idosas na população vem aumentando' },
      { id: 'C', text: 'Que as crianças estão desaparecendo' },
      { id: 'D', text: 'Que a população total está diminuindo rapidamente' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'O que é "expectativa de vida"?',
    tip: 'Pense em uma "previsão" de quantos anos, em média, as pessoas costumam viver em um lugar.',
    funFact: 'A expectativa de vida do brasileiro aumentou bastante graças a avanços na saúde e no saneamento!',
    points: 1,
    options: [
      { id: 'A', text: 'A quantidade de filhos que uma pessoa tem' },
      { id: 'B', text: 'A altura média da população' },
      { id: 'C', text: 'O número de cidades de um país' },
      { id: 'D', text: 'A estimativa de quantos anos, em média, uma pessoa deve viver' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'Qual desses fatores pode influenciar o crescimento populacional de um país?',
    tip: 'Pense em quem "entra" (nascimentos e imigração) e quem "sai" (mortes e emigração) de uma população.',
    funFact: 'Quando nascem mais pessoas do que morrem, dizemos que há um "crescimento natural" da população!',
    points: 1,
    options: [
      { id: 'A', text: 'A cor do céu' },
      { id: 'B', text: 'O tipo de relevo predominante' },
      { id: 'C', text: 'O número de nascimentos e mortes, além da migração' },
      { id: 'D', text: 'A quantidade de rios navegáveis' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'O que é migração?',
    tip: 'Pense em pessoas se mudando de um lugar para viver em outro.',
    funFact: 'Existem a migração interna (dentro do mesmo país) e a internacional (entre países)!',
    points: 1,
    options: [
      { id: 'A', text: 'O deslocamento de pessoas de um lugar para outro, seja dentro do país ou entre países' },
      { id: 'B', text: 'Um tipo de relevo' },
      { id: 'C', text: 'Uma forma de vegetação' },
      { id: 'D', text: 'Um tipo de clima' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'O que é "emigração"?',
    tip: 'Pense no prefixo "e" de "emigrar", que lembra a ideia de "sair".',
    funFact: 'Muitos brasileiros já emigraram para outros países em busca de trabalho e novas oportunidades!',
    points: 1,
    options: [
      { id: 'A', text: 'A chegada de pessoas vindas de outro país' },
      { id: 'B', text: 'A saída do campo para a cidade' },
      { id: 'C', text: 'O aumento da população idosa' },
      { id: 'D', text: 'A saída de pessoas de um país para morar em outro' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'O que é "imigração"?',
    tip: 'Pense no prefixo "i" de "imigrar", que lembra a ideia de "entrar".',
    funFact: 'O Brasil recebeu imigrantes de países como Itália, Japão, Alemanha e Portugal!',
    points: 1,
    options: [
      { id: 'A', text: 'A saída de pessoas de um país' },
      { id: 'B', text: 'A chegada de pessoas de outro país para viver em um novo lugar' },
      { id: 'C', text: 'O crescimento da vegetação nativa' },
      { id: 'D', text: 'A diminuição da densidade demográfica' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'Por que grandes cidades costumam enfrentar desafios como trânsito intenso e moradias precárias?',
    tip: 'Pense em como muita gente morando perto pode gerar desafios de planejamento urbano.',
    funFact: 'O planejamento urbano busca organizar melhor o crescimento das cidades para reduzir esses problemas!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque concentram um grande número de pessoas em um espaço limitado' },
      { id: 'B', text: 'Porque têm pouquíssimos habitantes' },
      { id: 'C', text: 'Porque ficam sempre no meio do deserto' },
      { id: 'D', text: 'Porque não têm nenhuma infraestrutura' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'Qual é a relação entre o crescimento das cidades e o êxodo rural?',
    tip: 'Pense em como a saída de pessoas do campo ajudou a aumentar a população das cidades.',
    funFact: 'Muitas grandes cidades brasileiras cresceram rapidamente no século 20 por causa desse movimento!',
    points: 1,
    options: [
      { id: 'A', text: 'Não existe nenhuma relação entre os dois' },
      { id: 'B', text: 'O êxodo rural sempre diminui a população das cidades' },
      { id: 'C', text: 'O êxodo rural foi um dos fatores que contribuiu para o crescimento acelerado das cidades brasileiras' },
      { id: 'D', text: 'O êxodo rural só acontece em outros países' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'O que uma pirâmide etária mostra sobre a população de um país?',
    tip: 'Pense em um gráfico que mostra quantas pessoas existem em cada faixa de idade.',
    funFact: 'Países com muitos jovens têm pirâmides com base larga; países envelhecidos têm o topo mais largo!',
    points: 1,
    options: [
      { id: 'A', text: 'A altura das montanhas do território' },
      { id: 'B', text: 'O tipo de vegetação predominante' },
      { id: 'C', text: 'A quantidade de rios do país' },
      { id: 'D', text: 'A distribuição da população por idade e sexo' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'Por que estudar a população de um país é importante para o planejamento do futuro?',
    tip: 'Pense em como saber quantas crianças ou idosos existem ajuda a planejar escolas e hospitais.',
    funFact: 'Governos usam dados populacionais para planejar políticas de saúde, educação e previdência com anos de antecedência!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque não tem nenhuma relação com planejamento' },
      { id: 'B', text: 'Porque ajuda a prever necessidades futuras, como vagas em escolas e aposentadorias' },
      { id: 'C', text: 'Porque serve só para fazer gráficos bonitos' },
      { id: 'D', text: 'Porque é obrigatório apenas para fins de censo, sem outra utilidade' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Na viagem de férias, Bernardo notou que a cidade litorânea onde estava hospedado tinha muito mais gente e prédios do que a pequena cidade do interior onde moravam os avós. Isso mostra que a população brasileira está:',
    tip: 'Pense em como grandes cidades costumam ficar perto do mar no Brasil.',
    funFact: 'Mais da metade dos brasileiros vive a menos de 200 km da costa!',
    points: 1,
    options: [
      { id: 'A', text: 'Distribuída de forma desigual, mais concentrada perto do litoral' },
      { id: 'B', text: 'Espalhada de forma perfeitamente igual por todo o território' },
      { id: 'C', text: 'Toda concentrada apenas no interior' },
      { id: 'D', text: 'Ausente das regiões litorâneas' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'O avô de Bernardo contou que, quando era jovem, morava no campo, mas se mudou para a cidade em busca de trabalho e melhores escolas. Esse tipo de movimento é chamado de:',
    tip: 'Pense na saída de pessoas do campo em direção às cidades.',
    funFact: 'O êxodo rural fez muitas famílias brasileiras se mudarem para cidades ao longo do século 20!',
    points: 1,
    options: [
      { id: 'A', text: 'Imigração internacional' },
      { id: 'B', text: 'Fuso horário' },
      { id: 'C', text: 'Êxodo rural' },
      { id: 'D', text: 'Erosão do solo' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Na escola, a professora mostrou um mapa com "manchas" mais escuras (mais gente) perto do litoral e mais claras (menos gente) na Amazônia. Esse mapa mostrava a:',
    tip: 'Pense no que um mapa de "mais gente" e "menos gente" representa.',
    funFact: 'Mapas assim ajudam a visualizar rapidamente onde vivem mais ou menos pessoas em um território!',
    points: 1,
    options: [
      { id: 'A', text: 'Vegetação do Brasil' },
      { id: 'B', text: 'Distribuição da população pelo território' },
      { id: 'C', text: 'Quantidade de chuva de cada região' },
      { id: 'D', text: 'Localização dos rios brasileiros' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Bernardo descobriu que sua bisavó havia vindo de outro país para morar no Brasil, décadas atrás. Esse tipo de movimento, de entrada de pessoas vindas de fora, é chamado de:',
    tip: 'Pense no prefixo "i" de "imigrar", lembrando a ideia de "entrar" em um novo país.',
    funFact: 'O Brasil tem uma população bem diversa justamente por causa da imigração de diferentes povos!',
    points: 1,
    options: [
      { id: 'A', text: 'Êxodo rural' },
      { id: 'B', text: 'Emigração' },
      { id: 'C', text: 'Densidade demográfica' },
      { id: 'D', text: 'Imigração' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Na feira de ciências, Bernardo apresentou um gráfico mostrando quantas pessoas de cada idade existiam em sua cidade, separadas entre homens e mulheres. Esse tipo de gráfico é chamado de:',
    tip: 'Pense no gráfico que mostra a população dividida por faixas de idade.',
    funFact: 'Olhando para uma pirâmide etária, é possível saber se um país tem mais jovens ou mais idosos!',
    points: 1,
    options: [
      { id: 'A', text: 'Mapa de relevo' },
      { id: 'B', text: 'Bacia hidrográfica' },
      { id: 'C', text: 'Pirâmide etária' },
      { id: 'D', text: 'Rosa dos ventos' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Bernardo comparou dois bairros de sua cidade: um pequeno, mas com muitos prédios e moradores, e outro bem maior em área, mas com poucas casas. O bairro pequeno e cheio de gente tem uma densidade demográfica:',
    tip: 'Pense em como muita gente num espaço pequeno aumenta a densidade demográfica.',
    funFact: 'Alguns bairros bem pequenos em área podem ter uma densidade demográfica maior do que cidades inteiras!',
    points: 1,
    options: [
      { id: 'A', text: 'Mais alta' },
      { id: 'B', text: 'Mais baixa' },
      { id: 'C', text: 'Igual à do outro bairro' },
      { id: 'D', text: 'Impossível de calcular' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Ao pesquisar sobre a região Norte do Brasil, Bernardo descobriu que, apesar de ser a maior região em área, ela tem relativamente poucos habitantes por km². Isso mostra que essa região tem:',
    tip: 'Pense em como uma área muito grande com poucos habitantes resulta em uma densidade baixa.',
    funFact: 'Grande parte da Região Norte é ocupada pela Floresta Amazônica, com áreas de difícil acesso!',
    points: 1,
    options: [
      { id: 'A', text: 'A maior densidade demográfica do Brasil' },
      { id: 'B', text: 'A mesma densidade demográfica de São Paulo' },
      { id: 'C', text: 'População igual à do Sudeste' },
      { id: 'D', text: 'Uma densidade demográfica baixa, em comparação com outras regiões' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Bernardo ajudou a mãe a preencher um formulário do Censo, respondendo perguntas sobre quantas pessoas moravam em casa. Ele aprendeu que essas informações são coletadas por um órgão chamado:',
    tip: 'Pense na sigla que aparece sempre que se fala sobre dados da população brasileira.',
    funFact: 'O Censo do IBGE ajuda o governo a planejar desde escolas até políticas de saúde!',
    points: 1,
    options: [
      { id: 'A', text: 'Ministério da Saúde' },
      { id: 'B', text: 'IBGE' },
      { id: 'C', text: 'Corpo de Bombeiros' },
      { id: 'D', text: 'Polícia Federal' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Na aula de Geografia, a professora perguntou por que era importante saber onde a população de um país está concentrada. Bernardo respondeu corretamente que isso ajuda a:',
    tip: 'Pense em como saber onde as pessoas moram ajuda o governo a planejar serviços.',
    funFact: 'Cidades muito populosas costumam precisar de um planejamento especial!',
    points: 1,
    options: [
      { id: 'A', text: 'Decorar mapas na parede' },
      { id: 'B', text: 'Prever o clima de cada estação' },
      { id: 'C', text: 'Planejar melhor escolas, hospitais e serviços públicos para essas áreas' },
      { id: 'D', text: 'Nada relacionado à vida das pessoas' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'Ao final do bimestre, a professora perguntou a Bernardo o que ele aprendeu sobre a população brasileira. Ele respondeu corretamente que:',
    tip: 'Pense em tudo que aprendemos sobre onde vivem a maioria dos brasileiros.',
    funFact: 'Parabéns, Bernardo! Agora você já entende como e por que a população do Brasil está distribuída dessa forma!',
    points: 1,
    options: [
      { id: 'A', text: 'A população está distribuída de forma desigual pelo território, concentrada principalmente nas cidades e perto do litoral' },
      { id: 'B', text: 'A população brasileira está toda concentrada no campo' },
      { id: 'C', text: 'Todas as regiões do Brasil têm exatamente a mesma quantidade de habitantes' },
      { id: 'D', text: 'A população do Brasil nunca muda' },
    ],
    correctAnswer: 'A',
  },
];
