export const questoesCiencias7AnoB2Av2 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'A Estação de Tratamento de Água (ETA) é responsável por:',
    tip: 'ETA = onde a água bruta se transforma em água potável.',
    funFact: 'O Brasil trata apenas cerca de 50% de todo o esgoto produzido. Nos países mais desenvolvidos, esse índice chega a 90-100%. Ampliar o saneamento básico é um dos maiores desafios ambientais e de saúde pública do país!',
    points: 1,
    options: [
      { id: 'A', text: 'Produzir água mineral natural' },
      { id: 'B', text: 'Tornar a água bruta própria para consumo humano' },
      { id: 'C', text: 'Tratar apenas águas residuais de indústrias' },
      { id: 'D', text: 'Armazenar água da chuva para irrigação' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'A primeira etapa do tratamento de água nas ETAs, em que produtos químicos (como sulfato de alumínio) são adicionados para agrupar as impurezas em flocos, é chamada de:',
    tip: 'O nome vem de "floco" — as impurezas se juntam formando flocos.',
    funFact: 'O sulfato de alumínio, usado na floculação, é um dos produtos químicos mais baratos e eficazes já descobertos. Ele carrega carga positiva e atrai as partículas de argila e sujeira (carga negativa), fazendo-as se agrupar em flocos visíveis!',
    points: 1,
    options: [
      { id: 'A', text: 'Filtração' },
      { id: 'B', text: 'Decantação' },
      { id: 'C', text: 'Cloração' },
      { id: 'D', text: 'Floculação' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'Na decantação, o que acontece com os flocos de impurezas formados na etapa anterior?',
    tip: 'O que acontece com objetos pesados dentro de um recipiente com água parada?',
    funFact: 'O tanque de decantação nas ETAs pode levar horas para o processo acontecer. Durante esse tempo, os flocos pesados se depositam no fundo como "lodo" — esse lodo pode ser seco e reutilizado como adubo!',
    points: 1,
    options: [
      { id: 'A', text: 'Os flocos pesados afundam e se depositam no fundo do tanque' },
      { id: 'B', text: 'Os flocos são filtrados por camadas de areia' },
      { id: 'C', text: 'As bactérias são eliminadas pelo cloro adicionado' },
      { id: 'D', text: 'As partículas são vaporizadas pelo calor' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'A filtração da água, realizada após a decantação, tem como objetivo principal:',
    tip: 'A filtração "peneira" o que sobrou após a decantação.',
    funFact: 'Os filtros de areia e cascalho das ETAs funcionam como filtros naturais semelhantes aos do solo. Uma camada de areia fina no fundo retém até as partículas microscópicas que não afundaram na decantação!',
    points: 1,
    options: [
      { id: 'A', text: 'Eliminar bactérias e vírus' },
      { id: 'B', text: 'Adicionar flúor à água' },
      { id: 'C', text: 'Reter partículas sólidas finas que não sedimentaram' },
      { id: 'D', text: 'Ajustar o pH da água' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'A adição de cloro à água tratada (cloração) tem como objetivo principal:',
    tip: 'Cloro é usado em piscinas justamente para essa finalidade.',
    funFact: 'A cloração da água pública começou nos EUA em 1908 e é considerada uma das maiores conquistas de saúde pública da história. Ela praticamente eliminou epidemias de cólera e febre tifoide em países que a adotaram!',
    points: 1,
    options: [
      { id: 'A', text: 'Melhorar o sabor e o odor da água' },
      { id: 'B', text: 'Eliminar microrganismos patogênicos (bactérias e vírus)' },
      { id: 'C', text: 'Aumentar a concentração de minerais benéficos' },
      { id: 'D', text: 'Reduzir a acidez da água' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'O esgoto doméstico não tratado lançado diretamente em rios e lagos causa principalmente:',
    tip: 'Pense nos microrganismos e substâncias que o esgoto contém.',
    funFact: 'Segundo a OMS, doenças causadas por água contaminada matam mais de 1,5 milhão de crianças por ano no mundo — principalmente por diarreia. O saneamento básico salva mais vidas do que qualquer vacina!',
    points: 1,
    options: [
      { id: 'A', text: 'Aumento da biodiversidade aquática' },
      { id: 'B', text: 'Melhora na qualidade e transparência da água' },
      { id: 'C', text: 'Redução da temperatura da água' },
      { id: 'D', text: 'Contaminação da água e proliferação de doenças' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'A fluoretação da água é uma medida de saúde pública adotada no Brasil desde 1974. Qual é seu objetivo?',
    tip: 'O flúor é o componente ativo de muitos cremes dentais.',
    funFact: 'A fluoretação da água é considerada pela OMS uma das 10 maiores realizações de saúde pública do século XX. Onde é adotada, reduz em até 60% a incidência de cáries na população, especialmente nas crianças!',
    points: 1,
    options: [
      { id: 'A', text: 'Eliminar vírus e bactérias patogênicas' },
      { id: 'B', text: 'Melhorar o sabor e a transparência da água' },
      { id: 'C', text: 'Prevenir cáries dentárias na população' },
      { id: 'D', text: 'Reduzir a turbidez e a cor da água' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'Doenças como cólera, febre tifoide e hepatite A têm em comum o fato de serem transmitidas principalmente por:',
    tip: 'Essas doenças são mais comuns em locais sem saneamento básico.',
    funFact: 'A cólera é causada pela bactéria Vibrio cholerae e pode matar em horas por desidratação severa. Ao longo da história, epidemias de cólera mataram milhões de pessoas — tudo por causa da água contaminada com esgoto!',
    points: 1,
    options: [
      { id: 'A', text: 'Consumo de água contaminada por microrganismos patogênicos' },
      { id: 'B', text: 'Contato com solo seco e poeirento' },
      { id: 'C', text: 'Inalação de ar frio e úmido' },
      { id: 'D', text: 'Exposição prolongada ao sol' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'O saneamento básico, que é um direito garantido pela Constituição Brasileira, inclui:',
    tip: 'Saneamento é mais do que só ter água encanada.',
    funFact: 'Cada R$1 investido em saneamento básico gera R$4 de economia em saúde pública, segundo estudos. Ainda assim, mais de 30 milhões de brasileiros não têm acesso à água tratada e 100 milhões não têm coleta de esgoto adequada!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas o fornecimento de água encanada tratada' },
      { id: 'B', text: 'Abastecimento de água, coleta e tratamento de esgoto, e manejo adequado do lixo' },
      { id: 'C', text: 'Somente o tratamento de esgoto de indústrias' },
      { id: 'D', text: 'A purificação natural de rios e lagos urbanos' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'Qual das seguintes práticas é uma forma inteligente de reduzir o desperdício de água em casa?',
    tip: 'Pense em reutilizar a água que já foi usada para uma função.',
    funFact: 'Reutilizar a água do enxágue da máquina de lavar para limpar quintais e calçadas pode economizar até 80 litros por lavagem. Multiplicando por todas as lavagens do ano, uma família pode economizar mais de 4.000 litros!',
    points: 1,
    options: [
      { id: 'A', text: 'Usar a máquina de lavar com meia carga sempre' },
      { id: 'B', text: 'Lavar o carro com mangueira de água corrente aberta' },
      { id: 'C', text: 'Regar plantas ao meio-dia, quando o calor é maior' },
      { id: 'D', text: 'Reutilizar a água do enxágue da roupa para limpar o chão' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'A eutrofização é um processo de poluição da água causado pelo excesso de nutrientes (nitrogênio e fósforo) que provoca:',
    tip: 'Nutrientes em excesso "fertilizam" a água — com consequências negativas.',
    funFact: 'A eutrofização pode causar o fenômeno da "maré vermelha" nos oceanos e o "bloom" de cianobactérias em rios e reservatórios. Essas algas produzem toxinas que matam peixes, animais e são perigosas para humanos!',
    points: 1,
    options: [
      { id: 'A', text: 'Crescimento excessivo de algas que consomem o oxigênio e matam a fauna aquática' },
      { id: 'B', text: 'Aumento da biodiversidade aquática pela fertilidade da água' },
      { id: 'C', text: 'Melhora na qualidade da água pela presença de vegetação aquática' },
      { id: 'D', text: 'Redução da temperatura da água pelo sombreamento das algas' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'A turbidez da água está relacionada à:',
    tip: 'Água turva é aquela que não está transparente — o que pode causar isso?',
    funFact: 'A turbidez da água é medida em UNT (Unidades Nefelométricas de Turbidez). A água potável deve ter turbidez abaixo de 5 UNT. Água com alta turbidez pode conter bactérias "escondidas" entre as partículas, dificultando a ação do cloro!',
    points: 1,
    options: [
      { id: 'A', text: 'Temperatura elevada da água' },
      { id: 'B', text: 'Quantidade de sal dissolvido' },
      { id: 'C', text: 'Presença de partículas sólidas em suspensão que impedem a passagem da luz' },
      { id: 'D', text: 'Nível de pH alcalino da água' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'O chorume, líquido tóxico escuro que escorre de aterros sanitários e lixões, pode contaminar:',
    tip: 'O chorume é muito líquido e pode se infiltrar no solo.',
    funFact: 'O chorume é 200 vezes mais poluente que o esgoto doméstico comum. Um litro de chorume pode contaminar até 1 bilhão de litros de água subterrânea! Por isso aterros sanitários modernos têm impermeabilização e coletam o chorume para tratamento.',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas rios e lagos da superfície' },
      { id: 'B', text: 'Rios superficiais e lençóis freáticos subterrâneos' },
      { id: 'C', text: 'Apenas o ar atmosférico da região' },
      { id: 'D', text: 'Somente o solo superficial ao redor do aterro' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'A água de qualidade para consumo humano deve, entre outras características, ser:',
    tip: 'Água potável vai além de apenas ser transparente.',
    funFact: 'A água potável brasileira passa por mais de 60 análises físico-químicas e microbiológicas antes de chegar às torneiras. O padrão de potabilidade está definido na Portaria nº 888/2021 do Ministério da Saúde!',
    points: 1,
    options: [
      { id: 'A', text: 'Inodora, incolor e completamente sem gosto' },
      { id: 'B', text: 'Levemente salgada e totalmente transparente' },
      { id: 'C', text: 'Fria e com pH neutro exato de 7,0' },
      { id: 'D', text: 'Tratada, segura microbiologicamente e livre de contaminantes prejudiciais à saúde' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'Uma das principais formas de poluição dos rios e lagos urbanos é:',
    tip: 'O problema começa nas casas e vai parar nos rios.',
    funFact: 'No Brasil, mais de 60% dos rios que cortam as cidades apresentam algum grau de poluição por esgoto doméstico. O Rio Tietê, em São Paulo, recebe o esgoto de milhões de pessoas — mesmo com programas de recuperação, ainda está longe de ser limpo!',
    points: 1,
    options: [
      { id: 'A', text: 'O descarte inadequado de esgoto doméstico sem tratamento' },
      { id: 'B', text: 'A presença de peixes herbívoros em grande quantidade' },
      { id: 'C', text: 'O excesso de chuvas em épocas chuvosas' },
      { id: 'D', text: 'A evaporação intensa em períodos de seca' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'O tratamento de esgoto em Estações de Tratamento de Esgoto (ETEs) visa principalmente:',
    tip: 'O esgoto tratado deve poder voltar ao ambiente com segurança.',
    funFact: 'O esgoto tratado adequadamente pode ser reutilizado para irrigação de jardins, campos esportivos e até para recarga de aquíferos. Em países com escassez hídrica, como Israel, até 90% do esgoto tratado é reutilizado!',
    points: 1,
    options: [
      { id: 'A', text: 'Reutilizar a água do esgoto para consumo humano imediato' },
      { id: 'B', text: 'Separar apenas os resíduos sólidos dos resíduos líquidos' },
      { id: 'C', text: 'Remover poluentes e microrganismos antes de devolver a água ao ambiente' },
      { id: 'D', text: 'Transformar esgoto em água mineral engarrafável' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'O derramamento de petróleo nos oceanos afeta gravemente os seres vivos marinhos porque:',
    tip: 'Pense na camada que o óleo forma sobre a água.',
    funFact: 'O desastre do Deepwater Horizon (Golfo do México, 2010) liberou 780 milhões de litros de petróleo no mar — o maior vazamento acidental da história. Afetou mais de 68.000 km² de oceano e matou milhares de animais marinhos!',
    points: 1,
    options: [
      { id: 'A', text: 'Aumenta a temperatura da água, causando choque térmico' },
      { id: 'B', text: 'Elimina as algas que servem de alimento para os peixes' },
      { id: 'C', text: 'Reduz drasticamente a salinidade da água' },
      { id: 'D', text: 'Forma uma camada que impede a oxigenação e a entrada de luz solar na água' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'A chuva ácida é causada principalmente pela dissolução na água da chuva de:',
    tip: 'Vem de emissões de fábricas e veículos.',
    funFact: 'A chuva normal já é levemente ácida (pH ~5,6) por causa do CO₂ do ar. A chuva ácida industrial pode ter pH de 4 ou menos — 10 vezes mais ácida que o normal! Ela destrói florestas, corrói estátuas de mármore e acidifica lagos inteiros.',
    points: 1,
    options: [
      { id: 'A', text: 'Oxigênio e dióxido de carbono naturais do ar' },
      { id: 'B', text: 'Óxidos de enxofre e nitrogênio de indústrias e veículos' },
      { id: 'C', text: 'Cloro e flúor provenientes das ETAs' },
      { id: 'D', text: 'Vapor de água aquecido por atividade vulcânica' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'Em regiões sem saneamento básico adequado, qual é a doença mais diretamente relacionada à água contaminada com esgoto?',
    tip: 'É a causa número 1 de mortalidade infantil em países em desenvolvimento.',
    funFact: 'A diarreia causada por água contaminada mata uma criança a cada 2 minutos no mundo. Praticamente todas essas mortes são evitáveis com água tratada e saneamento básico — problemas que têm solução tecnológica conhecida!',
    points: 1,
    options: [
      { id: 'A', text: 'Diarreia, que pode ser fatal especialmente em crianças pequenas' },
      { id: 'B', text: 'Gripe e infecções respiratórias' },
      { id: 'C', text: 'Pneumonia viral' },
      { id: 'D', text: 'Dengue' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'A reutilização de águas cinzas (água de pias, chuveiros e máquinas de lavar) é indicada para:',
    tip: 'Águas cinzas são mais limpas que o esgoto, mas não são potáveis.',
    funFact: 'Numa residência típica, as águas cinzas correspondem a cerca de 65% de todo o consumo de água. Reutilizá-las em descargas e irrigação de jardins pode reduzir o consumo total de água potável em até 30%!',
    points: 1,
    options: [
      { id: 'A', text: 'Consumo direto após fervura simples' },
      { id: 'B', text: 'Irrigação de hortas para consumo humano direto' },
      { id: 'C', text: 'Descarga de vasos sanitários e irrigação de jardins ornamentais' },
      { id: 'D', text: 'Preparação de alimentos e bebidas' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'O desmatamento das margens dos rios (destruição da mata ciliar) afeta diretamente a qualidade da água porque:',
    tip: 'As raízes das plantas seguram o solo — o que acontece sem elas?',
    funFact: 'A mata ciliar funciona como uma "esponja" natural: retém água da chuva, libera aos poucos e mantém os rios com água mesmo na seca. Por isso, rios em regiões desmatadas têm cheias extremas no inverno e secam no verão!',
    points: 1,
    options: [
      { id: 'A', text: 'Reduz a evaporação da superfície do rio, melhorando a qualidade' },
      { id: 'B', text: 'Aumenta a oxigenação da água pela exposição ao sol' },
      { id: 'C', text: 'Diminui a temperatura média da água do rio' },
      { id: 'D', text: 'Aumenta o assoreamento e a entrada de sedimentos no leito do rio' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Qual é a importância da mata ciliar para os recursos hídricos?',
    tip: 'Ciliar vem de "cílio" — imagine as franjas de folhas sobre o rio.',
    funFact: 'O Código Florestal Brasileiro (Lei 12.651/2012) exige a preservação de matas ciliares em faixas que variam de 30 a 500 metros nas margens de rios, dependendo de sua largura. É uma proteção legal para garantir a saúde dos rios!',
    points: 1,
    options: [
      { id: 'A', text: 'Aumentar a velocidade das correntezas dos rios' },
      { id: 'B', text: 'Proteger as margens do rio, filtrar sedimentos e manter a umidade local' },
      { id: 'C', text: 'Reduzir a biodiversidade aquática para controlar predadores' },
      { id: 'D', text: 'Impedir a recarga de lençóis freáticos' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'O conceito de "água virtual" refere-se a:',
    tip: 'Toda produção de alimentos e produtos industriais consome água.',
    funFact: 'Produzir 1 kg de carne bovina consome cerca de 15.000 litros de água virtual; 1 kg de trigo, 1.300 litros; uma camiseta de algodão, 2.700 litros! Escolhas alimentares têm impacto enorme no consumo global de água!',
    points: 1,
    options: [
      { id: 'A', text: 'Água que não existe fisicamente, apenas em modelos computacionais' },
      { id: 'B', text: 'Reservas de água armazenadas nas nuvens' },
      { id: 'C', text: 'A quantidade de água utilizada em toda a cadeia de produção de um bem' },
      { id: 'D', text: 'A água contida no interior de frutas e vegetais' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'O Sistema de Abastecimento de Água (SAA) engloba o conjunto de obras e instalações com a finalidade de:',
    tip: 'SAA é o sistema que garante água nas torneiras das residências.',
    funFact: 'A maior estação de tratamento de água do mundo é a Guaraú, em São Paulo, com capacidade para tratar 33 mil litros de água por segundo — o suficiente para abastecer mais de 9 milhões de pessoas por dia!',
    points: 1,
    options: [
      { id: 'A', text: 'Captar, tratar e distribuir água potável à população' },
      { id: 'B', text: 'Tratar apenas o esgoto doméstico da cidade' },
      { id: 'C', text: 'Monitorar em tempo real a qualidade dos rios' },
      { id: 'D', text: 'Construir represas e barragens para geração de energia' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'O uso excessivo de agrotóxicos na agricultura pode contaminar:',
    tip: 'Os agrotóxicos não ficam só nas plantas — eles se espalham pelo ambiente.',
    funFact: 'O Brasil é um dos maiores consumidores de agrotóxicos do mundo. Estudos detectaram resíduos de agrotóxicos em 99% das amostras de água do Paraná — inclusive em águas subterrâneas, mostrando que a contaminação se infiltra no subsolo!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas o ar atmosférico imediato da lavoura' },
      { id: 'B', text: 'Apenas o solo superficial das plantações' },
      { id: 'C', text: 'Somente os trabalhadores rurais em contato direto' },
      { id: 'D', text: 'Solo, rios, lençóis freáticos e a cadeia alimentar inteira' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'A fervura da água é um método eficaz caseiro para:',
    tip: 'O calor destrói microrganismos, mas não elimina substâncias químicas.',
    funFact: 'Para eliminar todos os microrganismos patogênicos, basta ferver a água por 1 minuto (ou 3 minutos em altitudes acima de 2.000 metros). Não é necessário ferver por 20 minutos, como muita gente pensa!',
    points: 1,
    options: [
      { id: 'A', text: 'Eliminar todas as substâncias químicas tóxicas e metais pesados' },
      { id: 'B', text: 'Eliminar microrganismos patogênicos como bactérias e vírus' },
      { id: 'C', text: 'Remover metais pesados como chumbo e mercúrio' },
      { id: 'D', text: 'Reduzir a salinidade e a dureza da água' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Qual das alternativas descreve corretamente uma ação de coleta seletiva que indiretamente protege os recursos hídricos?',
    tip: 'Lixo mal descartado pode ir parar nos rios.',
    funFact: 'Estima-se que 8 milhões de toneladas de plástico entram nos oceanos todo ano. Pesquisadores encontraram microplásticos até nos lugares mais remotos — das fossas das Marianas ao Ártico. A coleta seletiva reduz diretamente esse problema!',
    points: 1,
    options: [
      { id: 'A', text: 'Separar e reciclar o lixo, evitando que resíduos contaminem rios e lençóis' },
      { id: 'B', text: 'Lavar a louça com água corrente e muita esponja' },
      { id: 'C', text: 'Descartar medicamentos vencidos na pia do banheiro' },
      { id: 'D', text: 'Jogar óleo de cozinha usado diretamente na pia' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'A temperatura da água em rios e lagos influencia diretamente:',
    tip: 'Água quente tem menos oxigênio dissolvido — pense nas consequências.',
    funFact: 'A água fria consegue dissolver mais oxigênio que a água quente. Por isso, muitos peixes não sobrevivem quando a temperatura da água sobe demais — seja por aquecimento climático ou por despejo de água quente de usinas termelétricas (poluição térmica)!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas a cor e a turbidez da água' },
      { id: 'B', text: 'Somente a velocidade de evaporação superficial' },
      { id: 'C', text: 'A quantidade de oxigênio dissolvido, as reações químicas e a vida dos organismos aquáticos' },
      { id: 'D', text: 'Apenas a pressão atmosférica local' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'O indicador mais simples e eficaz para verificar se uma fonte de água está contaminada com esgoto é a presença de:',
    tip: 'Esse indicador mostra a presença de contaminação fecal.',
    funFact: 'A E. coli é uma bactéria que vive no intestino de humanos e animais. Sua presença na água indica contaminação por fezes — mesmo que a água pareça limpa e transparente! Por isso, análises laboratoriais são essenciais para garantir a segurança da água.',
    points: 1,
    options: [
      { id: 'A', text: 'Algas verdes em excesso' },
      { id: 'B', text: 'Alta turbidez e cor amarelada' },
      { id: 'C', text: 'Cheiro forte de cloro' },
      { id: 'D', text: 'Bactérias coliformes fecais (como Escherichia coli)' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'A Política Nacional de Recursos Hídricos (Lei 9.433/97, chamada "Lei das Águas") estabelece que a água é:',
    tip: 'Essa lei definiu as bases da gestão da água no Brasil.',
    funFact: 'A Lei das Águas brasileira é considerada uma das mais avançadas do mundo em gestão hídrica. Ela criou os Comitês de Bacia Hidrográfica, onde sociedade civil, governo e usuários decidem juntos sobre o uso da água — um modelo democrático de gestão!',
    points: 1,
    options: [
      { id: 'A', text: 'Um bem privado que pode ser comercializado livremente' },
      { id: 'B', text: 'Um bem público de domínio da União e dos estados, de uso limitado e com valor econômico' },
      { id: 'C', text: 'Um recurso exclusivo para uso das indústrias e do agronegócio' },
      { id: 'D', text: 'Um recurso gerenciado exclusivamente pelos municípios' },
    ],
    correctAnswer: 'B',
  },
];
