export const questoesGeografia7AnoB1Av2 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'Quantas são as regiões oficiais do Brasil, segundo a divisão do IBGE?',
    tip: 'Pensa nos nomes das regiões que você já ouviu falar: Norte, Nordeste, Centro-Oeste, Sudeste e Sul — quantas são no total?',
    funFact: 'O IBGE (Instituto Brasileiro de Geografia e Estatística) é o órgão responsável por essa divisão oficial do Brasil!',
    points: 1,
    options: [
      { id: 'A', text: '3' },
      { id: 'B', text: '4' },
      { id: 'C', text: '5' },
      { id: 'D', text: '7' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'Quais são as cinco regiões do Brasil?',
    tip: 'Repare que uma das opções mistura nomes de biomas com nomes de regiões — não confunda os dois!',
    funFact: 'Cada uma dessas cinco regiões tem características próprias de clima, cultura, economia e paisagem!',
    points: 1,
    options: [
      { id: 'A', text: 'Norte, Sul, Leste, Oeste e Centro' },
      { id: 'B', text: 'Norte, Nordeste, Centro-Oeste, Sudeste e Sul' },
      { id: 'C', text: 'Amazônia, Pantanal, Cerrado, Caatinga e Mata Atlântica' },
      { id: 'D', text: 'Brasil Central, Brasil Norte, Brasil Sul, Brasil Leste e Brasil Oeste' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'A região Norte do Brasil é conhecida principalmente por abrigar:',
    tip: 'Pensa na maior floresta tropical do mundo, que ocupa boa parte dessa região brasileira.',
    funFact: 'A região Norte é a maior em território, mas uma das menos povoadas do Brasil!',
    points: 1,
    options: [
      { id: 'A', text: 'A maior parte da Floresta Amazônica' },
      { id: 'B', text: 'O maior número de habitantes do país' },
      { id: 'C', text: 'As maiores indústrias do Brasil' },
      { id: 'D', text: 'O Pantanal' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'A região Nordeste do Brasil é famosa por ter, entre outras paisagens, o bioma:',
    tip: 'Pensa numa vegetação adaptada ao clima seco e quente, com plantas cheias de espinhos, muito comum no interior nordestino.',
    funFact: 'A Caatinga é o único bioma que existe exclusivamente no Brasil, não sendo encontrado em nenhum outro país!',
    points: 1,
    options: [
      { id: 'A', text: 'Pantanal' },
      { id: 'B', text: 'Floresta Amazônica' },
      { id: 'C', text: 'Pampa' },
      { id: 'D', text: 'Caatinga' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'A região Centro-Oeste do Brasil é conhecida por abrigar o bioma:',
    tip: 'Pensa nas savanas brasileiras e nas áreas alagadas, famosas pela grande quantidade de animais como onças e jacarés.',
    funFact: 'O Pantanal é considerado a maior planície alagável do mundo!',
    points: 1,
    options: [
      { id: 'A', text: 'Mata Atlântica' },
      { id: 'B', text: 'Caatinga' },
      { id: 'C', text: 'Cerrado e o Pantanal' },
      { id: 'D', text: 'Floresta Amazônica' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'A região Sudeste do Brasil é conhecida por ser:',
    tip: 'Pensa em cidades como São Paulo e Rio de Janeiro — elas têm poucos ou muitos habitantes e indústrias?',
    funFact: 'A região Sudeste concentra a maior parte da riqueza produzida no Brasil, mesmo não sendo a maior em território!',
    points: 1,
    options: [
      { id: 'A', text: 'A menos populosa do país' },
      { id: 'B', text: 'A região mais populosa e mais industrializada do Brasil' },
      { id: 'C', text: 'A única região sem grandes cidades' },
      { id: 'D', text: 'A região com menor atividade econômica' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'A região Sul do Brasil é conhecida por ter clima:',
    tip: 'Pensa em lugares onde às vezes até neva no Brasil, e em sobrenomes de origem italiana e alemã muito comuns por lá.',
    funFact: 'Cidades da região Sul, como Gramado (RS), até organizam festivais de inverno por causa do clima frio!',
    points: 1,
    options: [
      { id: 'A', text: 'Mais frio, com influência de imigrantes europeus na cultura' },
      { id: 'B', text: 'Extremamente quente o ano todo' },
      { id: 'C', text: 'Apenas desértico' },
      { id: 'D', text: 'Igual ao da região Norte' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'Quantos estados formam a região Sul do Brasil?',
    tip: 'Pensa em Paraná, Santa Catarina e Rio Grande do Sul — quantos estados são esses?',
    funFact: 'A região Sul é a menor em território entre as cinco regiões do Brasil!',
    points: 1,
    options: [
      { id: 'A', text: '5' },
      { id: 'B', text: '9' },
      { id: 'C', text: '7' },
      { id: 'D', text: '3' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'São Paulo, Rio de Janeiro, Minas Gerais e Espírito Santo são estados de qual região?',
    tip: 'Pensa nas maiores cidades do Brasil, como São Paulo e Rio de Janeiro — em qual região elas ficam?',
    funFact: 'Apesar de ser a menor região em número de estados (só 4), o Sudeste é o mais populoso do Brasil!',
    points: 1,
    options: [
      { id: 'A', text: 'Nordeste' },
      { id: 'B', text: 'Norte' },
      { id: 'C', text: 'Sudeste' },
      { id: 'D', text: 'Sul' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'A divisão regional do Brasil, feita pelo IBGE, leva em conta principalmente:',
    tip: 'Pensa em por que estados como Amazonas e Pará foram colocados juntos na mesma região — eles têm o quê em comum?',
    funFact: 'Essa divisão ajuda o governo a planejar melhor políticas públicas para cada parte do país, de acordo com suas necessidades!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas o tamanho da população de cada cidade' },
      { id: 'B', text: 'Características naturais, econômicas e sociais semelhantes entre os estados' },
      { id: 'C', text: 'Apenas a cor da bandeira de cada estado' },
      { id: 'D', text: 'Sorteio aleatório dos estados' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'Qual dessas capitais fica na região Nordeste do Brasil?',
    tip: 'Pensa na capital da Bahia, famosa por suas praias e por ser uma das cidades mais antigas do Brasil.',
    funFact: 'Salvador foi a primeira capital do Brasil colonial, antes de a capital ser transferida para o Rio de Janeiro!',
    points: 1,
    options: [
      { id: 'A', text: 'Salvador' },
      { id: 'B', text: 'Curitiba' },
      { id: 'C', text: 'Manaus' },
      { id: 'D', text: 'Porto Alegre' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'A região Norte do Brasil é a maior em extensão territorial, mas é conhecida por ter:',
    tip: 'Pensa: uma região enorme, coberta principalmente por floresta, costuma ter muita ou pouca gente por quilômetro quadrado?',
    funFact: 'Apesar de ser a maior região do Brasil em território, a região Norte tem menos habitantes do que só o estado de São Paulo!',
    points: 1,
    options: [
      { id: 'A', text: 'A maior população do país' },
      { id: 'B', text: 'As maiores indústrias do país' },
      { id: 'C', text: 'O maior número de estados' },
      { id: 'D', text: 'Uma densidade populacional baixa, com muitas áreas de floresta' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'O Rio São Francisco, importante para a região Nordeste, é conhecido também pelo apelido de:',
    tip: 'Pensa num apelido carinhoso, quase como se o rio fosse uma pessoa importante e antiga da família nordestina.',
    funFact: 'O Rio São Francisco é conhecido como o "rio da integração nacional" por atravessar várias regiões do Nordeste!',
    points: 1,
    options: [
      { id: 'A', text: 'Rio-Mar' },
      { id: 'B', text: 'Rio Gigante' },
      { id: 'C', text: 'Velho Chico' },
      { id: 'D', text: 'Rio Dourado' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'Além do agronegócio, a região Centro-Oeste do Brasil também é conhecida por sediar a capital do país, que é:',
    tip: 'Pensa na cidade planejada, construída para ser a capital federal do Brasil, no meio do território brasileiro.',
    funFact: 'Brasília foi inaugurada em 1960 e é uma das poucas capitais do mundo totalmente planejada antes de ser construída!',
    points: 1,
    options: [
      { id: 'A', text: 'São Paulo' },
      { id: 'B', text: 'Brasília' },
      { id: 'C', text: 'Salvador' },
      { id: 'D', text: 'Belo Horizonte' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'A região Sudeste concentra a maior parte da população e da economia do Brasil, principalmente por causa de:',
    tip: 'Pensa em como cidades como São Paulo cresceram tanto ao longo dos anos, com fábricas e muita gente se mudando para lá.',
    funFact: 'A cidade de São Paulo é hoje uma das maiores metrópoles do mundo, com milhões de habitantes!',
    points: 1,
    options: [
      { id: 'A', text: 'Grande industrialização e urbanização ao longo da história' },
      { id: 'B', text: 'Ser a menor região em território' },
      { id: 'C', text: 'Não ter nenhuma cidade grande' },
      { id: 'D', text: 'Ser a região com menos indústrias' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'A imigração europeia (italiana, alemã, entre outras) teve forte influência na cultura de qual região do Brasil?',
    tip: 'Lembra da Questão 7 — em qual região existem sobrenomes, comidas e festas de origem europeia muito fortes?',
    funFact: 'Por causa dessa imigração, algumas cidades do Sul do Brasil até têm arquitetura parecida com cidades da Alemanha e da Itália!',
    points: 1,
    options: [
      { id: 'A', text: 'Norte' },
      { id: 'B', text: 'Nordeste' },
      { id: 'C', text: 'Centro-Oeste' },
      { id: 'D', text: 'Sul' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'Qual desses estados faz parte da região Norte do Brasil?',
    tip: 'Pensa no nome do maior rio do Brasil — um dos estados da região Norte tem esse mesmo nome!',
    funFact: 'O estado do Amazonas é o maior estado do Brasil em território, maior até que muitos países do mundo!',
    points: 1,
    options: [
      { id: 'A', text: 'Bahia' },
      { id: 'B', text: 'Paraná' },
      { id: 'C', text: 'Amazonas' },
      { id: 'D', text: 'Goiás' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'O agronegócio (produção de soja, milho e criação de gado) é uma atividade econômica muito forte em qual região?',
    tip: 'Pensa nas grandes plantações de soja e nas fazendas de gado que ficam nos estados perto de Brasília, como Mato Grosso e Goiás.',
    funFact: 'O Brasil é um dos maiores produtores e exportadores de soja do mundo, muito por causa da região Centro-Oeste!',
    points: 1,
    options: [
      { id: 'A', text: 'Nordeste' },
      { id: 'B', text: 'Centro-Oeste' },
      { id: 'C', text: 'Sul apenas' },
      { id: 'D', text: 'Norte apenas' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'O forró e o frevo são exemplos de manifestações culturais fortemente associadas a qual região?',
    tip: 'Pensa nas festas juninas e no carnaval de Recife e Olinda, cheios desses ritmos animados.',
    funFact: 'O forró é tão popular que já ultrapassou as fronteiras do Nordeste e é dançado em festas por todo o Brasil!',
    points: 1,
    options: [
      { id: 'A', text: 'Nordeste' },
      { id: 'B', text: 'Sul' },
      { id: 'C', text: 'Centro-Oeste' },
      { id: 'D', text: 'Norte' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'Comparando as regiões brasileiras, é correto dizer que cada uma delas tem:',
    tip: 'Pensa em tudo que vimos até agora: biomas diferentes, culturas diferentes, economias diferentes — isso é igual ou diferente entre as regiões?',
    funFact: 'Essa diversidade entre as regiões é uma das razões pelas quais o Brasil é considerado um país tão rico culturalmente!',
    points: 1,
    options: [
      { id: 'A', text: 'Exatamente as mesmas características, sem nenhuma diferença' },
      { id: 'B', text: 'Só características econômicas, sem cultura própria' },
      { id: 'C', text: 'Nenhuma diferença de clima ou paisagem' },
      { id: 'D', text: 'Características naturais, econômicas e culturais próprias' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Bernardo estava montando um quebra-cabeça do mapa do Brasil dividido em regiões. Quantas peças grandes (regiões) ele precisava encaixar?',
    tip: 'Lembra da Questão 1 — quantas são as regiões oficiais do Brasil?',
    funFact: 'Bernardo pode até pintar cada região de uma cor diferente para memorizar melhor o mapa!',
    points: 1,
    options: [
      { id: 'A', text: '3' },
      { id: 'B', text: '4' },
      { id: 'C', text: '5' },
      { id: 'D', text: '7' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Ao montar o quebra-cabeça, Bernardo colocou a peça da Floresta Amazônica na região correspondente. Qual região era essa?',
    tip: 'Lembra da Questão 3 — qual região abriga a maior parte da Floresta Amazônica?',
    funFact: 'Se Bernardo pesquisar, vai descobrir que a região Norte tem rios tão grandes que às vezes são chamados de "rios-mar"!',
    points: 1,
    options: [
      { id: 'A', text: 'Norte' },
      { id: 'B', text: 'Sul' },
      { id: 'C', text: 'Nordeste' },
      { id: 'D', text: 'Sudeste' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Bernardo pesquisou sobre o forró e o frevo para um trabalho da escola. A qual região esses ritmos estão mais associados?',
    tip: 'Lembra da Questão 19 — em qual região esses ritmos animados são mais tradicionais?',
    funFact: 'Bernardo pode até pedir para a família assistir a um vídeo de forró para sentir o ritmo típico dessa região!',
    points: 1,
    options: [
      { id: 'A', text: 'Sul' },
      { id: 'B', text: 'Centro-Oeste' },
      { id: 'C', text: 'Norte' },
      { id: 'D', text: 'Nordeste' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Na aula de Geografia, o professor perguntou a Bernardo qual região concentra a maior população e a maior atividade industrial do Brasil. O que ele respondeu?',
    tip: 'Lembra da Questão 6 — qual região tem as maiores cidades e indústrias do Brasil?',
    funFact: 'Bernardo vai descobrir que só o estado de São Paulo tem mais habitantes do que a região Norte inteira!',
    points: 1,
    options: [
      { id: 'A', text: 'Norte' },
      { id: 'B', text: 'Sudeste' },
      { id: 'C', text: 'Nordeste' },
      { id: 'D', text: 'Centro-Oeste' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Bernardo descobriu que sua cidade fica em um estado com forte influência da imigração europeia no jeito de falar e nas comidas típicas. Em qual região do Brasil isso é mais comum?',
    tip: 'Lembra da Questão 16 — em qual região a imigração italiana e alemã teve mais influência na cultura?',
    funFact: 'Bernardo pode notar isso em pratos como o chucrute e em festas como a Oktoberfest, bem comuns na região Sul!',
    points: 1,
    options: [
      { id: 'A', text: 'Nordeste' },
      { id: 'B', text: 'Norte' },
      { id: 'C', text: 'Sul' },
      { id: 'D', text: 'Centro-Oeste' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Olhando um mapa, Bernardo identificou o Cerrado e o Pantanal como biomas de uma mesma região. Qual região é essa?',
    tip: 'Lembra da Questão 5 — em qual região ficam esses dois biomas famosos pela biodiversidade?',
    funFact: 'Bernardo pode se surpreender ao saber que o Pantanal abriga uma das maiores concentrações de onças-pintadas do mundo!',
    points: 1,
    options: [
      { id: 'A', text: 'Centro-Oeste' },
      { id: 'B', text: 'Sudeste' },
      { id: 'C', text: 'Norte' },
      { id: 'D', text: 'Sul' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Bernardo quis saber onde fica Brasília, a capital do país. Em qual região ela está localizada?',
    tip: 'Lembra da Questão 14 — em qual região fica a capital federal do Brasil?',
    funFact: 'Bernardo pode notar, olhando o mapa, que Brasília fica bem no "meio" do território brasileiro!',
    points: 1,
    options: [
      { id: 'A', text: 'Sudeste' },
      { id: 'B', text: 'Nordeste' },
      { id: 'C', text: 'Norte' },
      { id: 'D', text: 'Centro-Oeste' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'No mapa, Bernardo encontrou o Rio São Francisco, apelidado de "Velho Chico". Esse rio é muito importante para qual região?',
    tip: 'Lembra da Questão 13 — para qual região esse rio é tão importante que ganhou até um apelido carinhoso?',
    funFact: 'Bernardo pode descobrir que o Rio São Francisco nasce em Minas Gerais (Sudeste) mas é mais famoso por atravessar o Nordeste!',
    points: 1,
    options: [
      { id: 'A', text: 'Sul' },
      { id: 'B', text: 'Nordeste' },
      { id: 'C', text: 'Norte' },
      { id: 'D', text: 'Sudeste' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Bernardo aprendeu que cada região do Brasil tem características próprias de clima, cultura e economia. O que isso mostra sobre a divisão regional do país?',
    tip: 'Lembra da Questão 10 — o que o IBGE leva em conta na hora de dividir o Brasil em regiões?',
    funFact: 'Bernardo está aprendendo a enxergar o Brasil não como um lugar único, mas como um país cheio de diversidades regionais!',
    points: 1,
    options: [
      { id: 'A', text: 'Que todas as regiões são exatamente iguais' },
      { id: 'B', text: 'Que a divisão foi feita por sorteio' },
      { id: 'C', text: 'Que a divisão leva em conta semelhanças naturais, econômicas e sociais' },
      { id: 'D', text: 'Que não existe nenhuma diferença entre elas' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'Ao final do trabalho sobre as regiões brasileiras, Bernardo concluiu que conhecer bem o Brasil ajuda a entender:',
    tip: 'Pensa em tudo que Bernardo descobriu: biomas diferentes, culturas diferentes, economias diferentes — isso mostra um país pobre ou rico em diversidade?',
    funFact: 'Parabéns, Bernardo! Agora você conhece as cinco regiões do Brasil e um pouquinho da riqueza natural e cultural de cada uma delas!',
    points: 1,
    options: [
      { id: 'A', text: 'A grande diversidade natural e cultural do país' },
      { id: 'B', text: 'Que o Brasil é um país pequeno e sem diversidade' },
      { id: 'C', text: 'Que todas as cidades brasileiras são idênticas' },
      { id: 'D', text: 'Que não vale a pena estudar geografia' },
    ],
    correctAnswer: 'A',
  },
];
