export const questoesGeografia7AnoB3Av1 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'O relevo brasileiro é composto principalmente por quais duas grandes formas de relevo?',
    tip: 'Pensa nas partes mais altas e nas partes mais baixas e planas do mapa do Brasil!',
    funFact: 'O Brasil não tem grandes cadeias de montanhas jovens como os Andes — por isso seu relevo é mais antigo e desgastado, com altitudes menores!',
    points: 1,
    options: [
      { id: 'A', text: 'Planaltos e planícies' },
      { id: 'B', text: 'Vulcões e geleiras' },
      { id: 'C', text: 'Desertos e cânions' },
      { id: 'D', text: 'Montanhas nevadas e oceanos' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'O ponto mais alto do Brasil é o Pico da Neblina. Em qual estado ele está localizado?',
    tip: 'Pensa no estado mais ao Norte do Brasil, que faz fronteira com a Venezuela!',
    funFact: 'O Pico da Neblina tem quase 3.000 metros de altitude e fica em uma região tão remota que só foi explorado por expedições científicas décadas após a independência do Brasil!',
    points: 1,
    options: [
      { id: 'A', text: 'Minas Gerais' },
      { id: 'B', text: 'Santa Catarina' },
      { id: 'C', text: 'Mato Grosso' },
      { id: 'D', text: 'Amazonas' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'A Serra do Mar é uma importante feição do relevo brasileiro localizada no litoral. Qual é sua principal característica?',
    tip: 'Pensa numa cadeia de serras que acompanha o litoral do Sudeste — quase como uma "muralha" natural!',
    funFact: 'A Serra do Mar foi um grande obstáculo para a colonização do interior do Brasil — por isso foram construídas estradas difíceis para subir a serra!',
    points: 1,
    options: [
      { id: 'A', text: 'É uma planície no centro do país' },
      { id: 'B', text: 'É uma cadeia de escarpas que acompanha o litoral Sudeste, separando o litoral do interior' },
      { id: 'C', text: 'É um deserto no Nordeste' },
      { id: 'D', text: 'É uma área de charco permanente' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'As planícies brasileiras são áreas de relevo baixo e plano. Onde está localizada a maior planície do Brasil?',
    tip: 'Pensa no bioma que é a maior planície inundável do mundo — já vimos isso no bimestre passado!',
    funFact: 'A Planície do Pantanal tem áreas que chegam a menos de 100 metros de altitude e ficam completamente alagadas durante as cheias!',
    points: 1,
    options: [
      { id: 'A', text: 'No litoral do Nordeste' },
      { id: 'B', text: 'Na Serra Gaúcha' },
      { id: 'C', text: 'Na Planície do Pantanal, no Centro-Oeste' },
      { id: 'D', text: 'No Planalto Nordestino' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'O que são as "chapadas" no relevo brasileiro?',
    tip: 'Pensa num planalto com o topo bem plano, como se fosse uma mesa gigante!',
    funFact: 'A Chapada Diamantina, na Bahia, recebeu esse nome porque era rica em diamantes — hoje é um dos destinos de ecoturismo mais famosos do Brasil!',
    points: 1,
    options: [
      { id: 'A', text: 'Vales profundos cortados por rios' },
      { id: 'B', text: 'Planaltos com superfície plana e bordas íngremes, comuns no Centro-Oeste e Nordeste' },
      { id: 'C', text: 'Planícies alagadas no Sul do Brasil' },
      { id: 'D', text: 'Ilhas oceânicas do litoral brasileiro' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'O relevo brasileiro é considerado antigo e desgastado. O que isso significa?',
    tip: 'Pensa no que o tempo, a chuva e o vento fazem com as rochas ao longo de milhões de anos!',
    funFact: 'As rochas do escudo cristalino brasileiro têm mais de 500 milhões de anos — são algumas das mais antigas da Terra!',
    points: 1,
    options: [
      { id: 'A', text: 'Que as montanhas são jovens e muito altas, como os Andes' },
      { id: 'B', text: 'Que o relevo nunca muda ao longo do tempo' },
      { id: 'C', text: 'Que o relevo foi formado há muito tempo e sofreu erosão intensa, tornando-se menos acidentado e com altitudes menores' },
      { id: 'D', text: 'Que existem vulcões ativos no Brasil' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'A Depressão Sertaneja está localizada no interior do Nordeste. O que é uma depressão no contexto do relevo?',
    tip: 'Pensa: "depressão" no relevo é o oposto de montanha — uma área mais baixa em relação ao entorno!',
    funFact: 'Algumas depressões brasileiras foram formadas pela erosão de rochas mais fracas ao longo de milhões de anos!',
    points: 1,
    options: [
      { id: 'A', text: 'Uma área de relevo mais elevada que o entorno' },
      { id: 'B', text: 'Uma área de relevo mais baixa em relação às terras ao redor' },
      { id: 'C', text: 'Um tipo de vale glacial' },
      { id: 'D', text: 'Uma elevação cônica como um vulcão' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'A erosão é um processo que modifica o relevo. O que é erosão?',
    tip: 'Pensa no que a água da chuva, o vento e os rios fazem com o solo e as rochas ao longo do tempo!',
    funFact: 'O Grand Canyon nos EUA foi formado pela erosão do Rio Colorado ao longo de milhões de anos — prova do poder transformador da erosão!',
    points: 1,
    options: [
      { id: 'A', text: 'O processo de formação de novas montanhas por vulcões' },
      { id: 'B', text: 'O desgaste e transporte do solo e das rochas pela ação da água, vento e outros agentes' },
      { id: 'C', text: 'O crescimento das plantas em terrenos inclinados' },
      { id: 'D', text: 'A construção de terraços agrícolas' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'Os planaltos brasileiros ocupam a maior parte do território nacional. Qual é uma característica dos planaltos?',
    tip: 'Pensa: um planalto é alto, mas diferente de uma montanha — como ele é por cima?',
    funFact: 'A cidade de Brasília foi construída sobre o Planalto Central Brasileiro, a mais de 1.000 metros de altitude!',
    points: 1,
    options: [
      { id: 'A', text: 'São áreas completamente planas no nível do mar' },
      { id: 'B', text: 'São áreas elevadas com superfície irregular, formadas por rochas antigas e resistentes à erosão' },
      { id: 'C', text: 'São apenas encontrados no litoral do Brasil' },
      { id: 'D', text: 'São formados apenas por vulcões' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'O deslizamento de terra é um evento comum em áreas de relevo acidentado, especialmente após chuvas fortes. Qual condição aumenta o risco de deslizamentos?',
    tip: 'Pensa: o que acontece quando tira as raízes das plantas que seguram o solo em encostas íngremes?',
    funFact: 'Tragédias como as ocorridas na Serra Fluminense são exemplos de como a ocupação irregular de encostas sem vegetação aumenta o risco de deslizamentos!',
    points: 1,
    options: [
      { id: 'A', text: 'Presença de muita vegetação nas encostas' },
      { id: 'B', text: 'Terrenos completamente planos' },
      { id: 'C', text: 'Falta de chuvas na região' },
      { id: 'D', text: 'Encostas íngremes com solo exposto (sem vegetação) e chuvas intensas' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'A Planície Amazônica é uma extensa área plana acompanhada pelo Rio Amazonas. Qual é sua principal característica?',
    tip: 'Pensa num terreno muito plano que fica às margens do maior rio do mundo!',
    funFact: 'Durante as cheias do Rio Amazonas, enormes áreas da Planície Amazônica ficam submersas, formando um ecossistema chamado de várzea!',
    points: 1,
    options: [
      { id: 'A', text: 'É uma área de montanhas vulcânicas ativas' },
      { id: 'B', text: 'É uma área de relevo elevado com serras nevadas' },
      { id: 'C', text: 'É uma vasta área de terreno plano às margens do Rio Amazonas, sujeita a inundações periódicas' },
      { id: 'D', text: 'É um deserto no centro da floresta' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'O Planalto das Guianas, ao Norte do Brasil, é parte de um dos escudos cristalinos mais antigos do planeta. O que são escudos cristalinos?',
    tip: 'Pensa em rochas muito, muito antigas — formadas há centenas de milhões de anos!',
    funFact: 'O Monte Roraima, no Planalto das Guianas, é um dos marcos geográficos mais antigos do mundo, com mais de 2 bilhões de anos de formação!',
    points: 1,
    options: [
      { id: 'A', text: 'Áreas de sedimento recente e solo mole' },
      { id: 'B', text: 'Grandes áreas de rochas antigas e resistentes, que formam a base do relevo' },
      { id: 'C', text: 'Regiões vulcânicas do Brasil' },
      { id: 'D', text: 'Zonas de alagamento permanente' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'As serras brasileiras são áreas elevadas e acidentadas. Qual é a diferença entre uma serra e um planalto?',
    tip: 'Pensa: um planalto é alto, mas tem topo relativamente plano; a serra tem picos e vales mais acidentados!',
    funFact: 'A Serra da Mantiqueira tem picos que ultrapassam 2.800 metros — é uma das regiões mais frias e chuvosas do Sudeste brasileiro!',
    points: 1,
    options: [
      { id: 'A', text: 'São sinônimos exatos — não existe diferença' },
      { id: 'B', text: 'Uma serra é sempre menor que um planalto' },
      { id: 'C', text: 'A serra é mais acidentada, com picos elevados e vales; o planalto tem superfície mais plana no alto' },
      { id: 'D', text: 'Planaltos ficam apenas no litoral' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'Por que o relevo influencia diretamente onde as pessoas escolhem morar?',
    tip: 'Pensa: é mais fácil construir casas, estradas e plantar em terrenos planos ou em encostas íngremes?',
    funFact: 'Cidades como São Paulo cresceram sobre planaltos, enquanto o litoral íngreme da Serra do Mar foi ocupado mais lentamente por causa da dificuldade de acesso!',
    points: 1,
    options: [
      { id: 'A', text: 'O relevo não influencia nada na escolha das pessoas' },
      { id: 'B', text: 'Áreas planas facilitam a construção, a agricultura e o transporte, tornando-as mais densamente habitadas' },
      { id: 'C', text: 'As pessoas preferem morar em montanhas nevadas' },
      { id: 'D', text: 'O relevo só importa para agricultores, não para cidades' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'A região do Quadrilátero Ferrífero, em Minas Gerais, é famosa pelo relevo rico em quê?',
    tip: 'O nome já diz: "ferrífero" vem de ferro — pensa no que se extrai dali!',
    funFact: 'O Quadrilátero Ferrífero é uma das maiores reservas de minério de ferro do planeta, responsável por grande parte das exportações brasileiras de minério!',
    points: 1,
    options: [
      { id: 'A', text: 'Diamantes e esmeraldas apenas' },
      { id: 'B', text: 'Petróleo e gás natural' },
      { id: 'C', text: 'Recursos minerais, especialmente minério de ferro' },
      { id: 'D', text: 'Sal-gema e potássio' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'O relevo de uma região influencia o tipo de clima local. Como o relevo pode modificar o clima?',
    tip: 'Lembra da relação entre altitude e temperatura que estudamos no bimestre anterior!',
    funFact: 'A encosta voltada para o mar (barlavento) recebe muito mais chuva do que a encosta voltada para o interior (sotavento) — fenômeno chamado de "sombra de chuva"!',
    points: 1,
    options: [
      { id: 'A', text: 'O relevo não tem nenhuma influência sobre o clima' },
      { id: 'B', text: 'Áreas mais altas são geralmente mais quentes e secas' },
      { id: 'C', text: 'A altitude altera a temperatura e o relevo pode bloquear ou direcionar chuvas e ventos' },
      { id: 'D', text: 'Apenas os vulcões influenciam o clima' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'Por que cidades localizadas em encostas das serras do Sudeste frequentemente sofrem com deslizamentos?',
    tip: 'Pensa no que estudamos sobre deslizamentos: inclinação + solo exposto + chuva!',
    funFact: 'A tragédia da região serrana do Rio de Janeiro em 2011 foi um dos maiores desastres naturais da história do Brasil, com milhares de desabrigados!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque o terreno é sempre muito plano' },
      { id: 'B', text: 'Porque não chove nessas regiões' },
      { id: 'C', text: 'Porque o relevo acidentado, as chuvas intensas e a ocupação desordenada de encostas sem vegetação aumentam o risco' },
      { id: 'D', text: 'Porque a altitude é muito baixa' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'As bacias sedimentares brasileiras são importantes para a economia. Por que?',
    tip: 'Pensa em recursos que ficam guardados em camadas de sedimento, muito usados como combustível!',
    funFact: 'A Bacia Sedimentar do Paraná é uma das maiores do mundo e abriga, além de petróleo, importantes aquíferos de água doce!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque são fontes apenas de rochas ornamentais' },
      { id: 'B', text: 'Porque abrigam depósitos de petróleo, gás natural, carvão mineral e água subterrânea' },
      { id: 'C', text: 'Porque servem apenas para turismo' },
      { id: 'D', text: 'Porque geram energia elétrica diretamente' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'Bernardo está estudando o mapa do relevo do Brasil para uma prova. Ele percebe que Brasília fica sobre um planalto. Que vantagem isso trouxe na hora de construir a capital?',
    tip: 'Pensa no que um terreno mais elevado e relativamente plano oferece para a construção de uma cidade moderna!',
    funFact: 'Brasília foi planejada e construída em apenas 41 meses sobre o Planalto Central — um feito de engenharia impressionante!',
    points: 1,
    options: [
      { id: 'A', text: 'Nenhuma vantagem — era mais fácil construir no litoral' },
      { id: 'B', text: 'O planalto ofereceu terreno firme, altitude e posição central no país, facilitando o acesso a todas as regiões' },
      { id: 'C', text: 'Porque o planalto era o único lugar sem habitantes' },
      { id: 'D', text: 'Porque o relevo plano do planalto permite neve no inverno' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'Em qual estado está localizada a Serra da Mantiqueira, importante feição do relevo do Sudeste?',
    tip: 'A Serra da Mantiqueira fica no encontro de três estados do Sudeste — Minas Gerais, São Paulo e Rio de Janeiro!',
    funFact: 'A Serra da Mantiqueira é o lar do Pico das Agulhas Negras (2.791 m), o terceiro ponto mais alto do Brasil!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas no Pará' },
      { id: 'B', text: 'Apenas no Rio Grande do Sul' },
      { id: 'C', text: 'Nos estados de Minas Gerais, São Paulo e Rio de Janeiro' },
      { id: 'D', text: 'Apenas no Ceará' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Bernardo visita uma fazenda em Goiás e observa um terreno muito plano, com vegetação de Cerrado. Qual tipo de relevo ele está vendo?',
    tip: 'Pensa no tipo de relevo mais comum no Centro-Oeste — alto, mas relativamente plano!',
    funFact: 'O Planalto Central Goiano é um dos principais produtores de soja e milho do Brasil, graças ao solo e relevo favoráveis à mecanização agrícola!',
    points: 1,
    options: [
      { id: 'A', text: 'Um vulcão inativo' },
      { id: 'B', text: 'Parte da planície costeira' },
      { id: 'C', text: 'Uma geleira' },
      { id: 'D', text: 'Um planalto' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'No trabalho de Geografia, Bernardo precisa apontar um problema ambiental diretamente ligado ao relevo. Qual ele deve citar?',
    tip: 'Já estudamos um problema grave que acontece em encostas íngremes com solo exposto!',
    funFact: 'A erosão causa o assoreamento dos rios — quando o solo carregado pela chuva entra nos rios e torna o leito mais raso!',
    points: 1,
    options: [
      { id: 'A', text: 'A poluição do mar por plástico' },
      { id: 'B', text: 'O desmatamento não tem relação com o relevo' },
      { id: 'C', text: 'A erosão e os deslizamentos, causados pela combinação de relevo acidentado, desmatamento e chuvas intensas' },
      { id: 'D', text: 'A seca no Nordeste, independente do relevo' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Bernardo lê que o Planalto Nordestino tem altitudes menores que o Planalto Atlântico. O que isso implica em termos de temperatura?',
    tip: 'Lembra: altitude menor = temperatura maior, de forma geral!',
    funFact: 'Mesmo no Nordeste, existem partes altas ("Brejos de Altitude") onde o clima é mais fresco — como se fossem "ilhas de frescor" no calor do sertão!',
    points: 1,
    options: [
      { id: 'A', text: 'O Planalto Nordestino é mais frio que o Atlântico' },
      { id: 'B', text: 'A altitude não influencia a temperatura' },
      { id: 'C', text: 'O Planalto Nordestino tende a ser mais quente, pois está em altitude menor' },
      { id: 'D', text: 'Os dois têm a mesma temperatura sempre' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Bernardo assiste a um documentário sobre os "tepuis" no extremo Norte do Brasil, formações rochosas de topos planos na fronteira com a Venezuela. A que tipo de relevo eles correspondem?',
    tip: 'Pensa nas chapadas, que já estudamos — topos planos e bordas íngremes!',
    funFact: 'Os tepuis são tão isolados que abrigam espécies de plantas e animais que não existem em mais lugar nenhum do mundo!',
    points: 1,
    options: [
      { id: 'A', text: 'A planícies alagadas permanentemente' },
      { id: 'B', text: 'A vulcões extintos' },
      { id: 'C', text: 'A dunas de areia' },
      { id: 'D', text: 'A planaltos com topos planos e bordas íngremes (tipo chapada)' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Bernardo precisa explicar por que o Brasil não tem terremoto frequente. Qual é a explicação correta relacionada ao relevo e à estrutura geológica?',
    tip: 'Terremotos acontecem principalmente nas bordas das placas tectônicas — e o Brasil fica no meio de uma placa!',
    funFact: 'O Brasil está localizado no centro da Placa Sul-Americana, longe das bordas onde ocorrem os sismos mais intensos!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque o Brasil tem muitos vulcões que absorvem a energia' },
      { id: 'B', text: 'Porque o Brasil está posicionado no interior de uma placa tectônica estável, longe das zonas de colisão' },
      { id: 'C', text: 'Porque o solo brasileiro é muito mole e absorve tremores' },
      { id: 'D', text: 'Porque as serras brasileiras bloqueiam os terremotos' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Na prova, Bernardo tem que associar cada formação a uma região. Qual associação está correta?',
    tip: 'Revise as formas de relevo que estudamos e suas localizações!',
    funFact: 'Conhecer a localização das formas de relevo ajuda a entender a distribuição das cidades, dos rios e dos biomas!',
    points: 1,
    options: [
      { id: 'A', text: 'Pantanal — é uma área de planalto elevado' },
      { id: 'B', text: 'Pico da Neblina — é o ponto mais alto do Brasil, no Amazonas' },
      { id: 'C', text: 'Serra do Mar — fica no interior do Centro-Oeste' },
      { id: 'D', text: 'Planalto Central — fica no litoral do Nordeste' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Bernardo observa no mapa que as grandes cidades do interior do Brasil estão localizadas, em geral, sobre planaltos. Por que isso aconteceu historicamente?',
    tip: 'Pensa nos motivos práticos: defesa, saúde, transportes, agricultura!',
    funFact: 'Em épocas antigas, cidades sobre planaltos eram mais fáceis de defender de invasores — uma vantagem estratégica importante!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque os planaltos têm neve, o que atraiu colonizadores' },
      { id: 'B', text: 'Porque o relevo elevado oferecia defesa natural, clima mais ameno e terras agricultáveis' },
      { id: 'C', text: 'Porque a legislação colonial proibiu cidades em planícies' },
      { id: 'D', text: 'Porque os planaltos têm mais rios que as planícies' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'As falésias são formas de relevo encontradas no litoral Nordestino. O que são falésias?',
    tip: 'Pensa naquelas paredes de rocha colorida que aparecem em fotos de praias do Nordeste!',
    funFact: 'As falésias de Morro Branco (CE) e de Maragogi (AL) são famosas por suas cores avermelhadas e laranjas, causadas pelos minerais presentes nas rochas sedimentares!',
    points: 1,
    options: [
      { id: 'A', text: 'Dunas de areia no interior do Nordeste' },
      { id: 'B', text: 'Grandes pântanos próximos ao oceano' },
      { id: 'C', text: 'Cortes abruptos de terreno formados pela erosão das ondas do mar no litoral' },
      { id: 'D', text: 'Recifes de coral' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Bernardo precisa escrever sobre a relação entre relevo e agricultura no Brasil. Qual é o ponto principal desta relação?',
    tip: 'Pensa em onde é mais fácil usar máquinas agrícolas e onde é mais difícil!',
    funFact: 'A mecanização da agricultura é muito mais fácil em planaltos planos — por isso o Centro-Oeste tornou-se o celeiro do Brasil!',
    points: 1,
    options: [
      { id: 'A', text: 'O relevo não interfere na agricultura' },
      { id: 'B', text: 'Áreas mais planas (planícies e planaltos) facilitam o cultivo mecanizado; áreas acidentadas dificultam' },
      { id: 'C', text: 'Quanto mais montanhoso, mais produtiva é a agricultura' },
      { id: 'D', text: 'O relevo só importa para a pesca' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'Para concluir o simulado, Bernardo resume: "O relevo brasileiro é variado, antigo e influencia diretamente o clima, os rios e a ocupação humana." Essa afirmação está:',
    tip: 'Pense em tudo que você estudou sobre as formas de relevo e suas influências!',
    funFact: 'Entender o relevo é entender a base de tudo: onde chove, onde nasce o rio, onde se constrói a cidade — o relevo é o "cenário" de toda a história do Brasil!',
    points: 1,
    options: [
      { id: 'A', text: 'Errada, o relevo nunca influencia o clima' },
      { id: 'B', text: 'Correta: o relevo, por ser antigo e variado, define muito da realidade geográfica e humana do Brasil' },
      { id: 'C', text: 'Correta apenas para o litoral' },
      { id: 'D', text: 'Errada, pois o Brasil tem relevo jovem como os Andes' },
    ],
    correctAnswer: 'A',
  },
];
