export const questoesPortugues8AnoB4Av1 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "O que é um \"período composto\"?",
    tip: "Pense em uma frase mais longa, formada pela união de duas ou mais \"frasezinhas\" menores, cada uma com seu próprio verbo.",
    funFact: "Enquanto o período simples tem apenas uma oração (um verbo), o período composto pode ter duas, três ou até mais orações combinadas!",
    points: 1,
    options: [
      { id: "A", text: "Uma frase formada por duas ou mais orações, ligadas entre si" },
      { id: "B", text: "Uma frase com apenas uma palavra" },
      { id: "C", text: "Um tipo de pontuação" },
      { id: "D", text: "Um texto sem nenhum verbo" },
    ],
    correctAnswer: "A",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "O que é uma \"oração coordenada\"?",
    tip: "Pense em duas frases que fazem sentido mesmo separadas, mas que estão ligadas por uma palavra de conexão, como \"e\" ou \"mas\".",
    funFact: "As orações coordenadas são \"independentes\" uma da outra em termos de sentido, mesmo estando ligadas na mesma frase!",
    points: 1,
    options: [
      { id: "A", text: "Uma oração que depende totalmente de outra para ter sentido completo" },
      { id: "B", text: "Um tipo de figura de linguagem" },
      { id: "C", text: "Uma oração que tem sentido completo por si só e está ligada a outra oração, mantendo uma relação de igualdade" },
      { id: "D", text: "Um sinal de pontuação" },
    ],
    correctAnswer: "C",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "Qual destas é uma \"conjunção coordenativa aditiva\", usada para somar ideias?",
    tip: "Pense na conjunção usada para \"adicionar\" uma informação a outra, como em \"Maria estudou e passou na prova\".",
    funFact: "Além de \"e\", outras conjunções aditivas incluem \"nem\" (quando a frase é negativa) e \"também\", usadas para somar ideias em uma frase!",
    points: 1,
    options: [
      { id: "A", text: "\"Mas\"" },
      { id: "B", text: "\"E\"" },
      { id: "C", text: "\"Ou\"" },
      { id: "D", text: "\"Porque\"" },
    ],
    correctAnswer: "B",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "Qual destas é uma \"conjunção coordenativa adversativa\", usada para indicar oposição ou contraste entre ideias?",
    tip: "Pense na conjunção usada quando duas ideias se contrastam, como em \"Ele estudou muito, mas não passou na prova\".",
    funFact: "Outras conjunções adversativas incluem \"porém\", \"todavia\" e \"contudo\" — todas usadas para indicar contraste entre ideias!",
    points: 1,
    options: [
      { id: "A", text: "\"E\"" },
      { id: "B", text: "\"Ou\"" },
      { id: "C", text: "\"Portanto\"" },
      { id: "D", text: "\"Mas\"" },
    ],
    correctAnswer: "D",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "Qual destas é uma \"conjunção coordenativa alternativa\", usada para indicar escolha entre possibilidades?",
    tip: "Pense na conjunção usada quando há uma escolha entre duas opções, como em \"Você quer suco ou água?\".",
    funFact: "A conjunção \"ou\" também pode ser repetida para dar mais ênfase à ideia de alternativa, como em \"ou estuda, ou brinca\"!",
    points: 1,
    options: [
      { id: "A", text: "\"E\"" },
      { id: "B", text: "\"Mas\"" },
      { id: "C", text: "\"Ou\"" },
      { id: "D", text: "\"Portanto\"" },
    ],
    correctAnswer: "C",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "Qual destas é uma \"conjunção coordenativa conclusiva\", usada para indicar uma conclusão?",
    tip: "Pense na conjunção usada para \"concluir\" uma ideia a partir do que foi dito antes, como em \"Estudei muito, portanto passarei na prova\".",
    funFact: "Outras conjunções conclusivas incluem \"logo\", \"por isso\" e \"assim\" — todas usadas para indicar uma conclusão lógica!",
    points: 1,
    options: [
      { id: "A", text: "\"Portanto\"" },
      { id: "B", text: "\"E\"" },
      { id: "C", text: "\"Ou\"" },
      { id: "D", text: "\"Mas\"" },
    ],
    correctAnswer: "A",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "Qual destas é uma \"conjunção coordenativa explicativa\", usada para explicar ou justificar uma ideia?",
    tip: "Pense na conjunção usada para justificar o motivo de algo, como em \"Não saí de casa, porque estava chovendo muito\".",
    funFact: "A conjunção \"porque\" pode também introduzir orações subordinadas, dependendo do contexto — mas, quando explica uma afirmação anterior, tem valor coordenativo explicativo!",
    points: 1,
    options: [
      { id: "A", text: "\"Mas\"" },
      { id: "B", text: "\"Porque\"" },
      { id: "C", text: "\"Ou\"" },
      { id: "D", text: "\"E\"" },
    ],
    correctAnswer: "B",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "Na frase \"Ele estudou muito, mas não passou na prova\", qual é a relação de sentido criada pela conjunção \"mas\"?",
    tip: "Pense em como a segunda parte da frase contrasta com a primeira — ele estudou muito, mas o resultado não foi o esperado.",
    funFact: "O uso de \"mas\" é muito comum para criar esse efeito de surpresa ou contraste entre duas ideias dentro de uma mesma frase!",
    points: 1,
    options: [
      { id: "A", text: "Adição de ideias" },
      { id: "B", text: "Conclusão" },
      { id: "C", text: "Explicação" },
      { id: "D", text: "Oposição ou contraste entre as duas ideias" },
    ],
    correctAnswer: "D",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "Na pontuação, qual sinal normalmente é usado antes de conjunções adversativas, como \"mas\" e \"porém\"?",
    tip: "Pense em como, antes dessas conjunções que indicam contraste, costuma aparecer uma pequena pausa na escrita.",
    funFact: "Essa vírgula ajuda o leitor a perceber que uma ideia contrastante está por vir, como em \"Ele é tímido, mas muito gentil\"!",
    points: 1,
    options: [
      { id: "A", text: "Vírgula" },
      { id: "B", text: "Ponto de exclamação" },
      { id: "C", text: "Dois pontos" },
      { id: "D", text: "Travessão" },
    ],
    correctAnswer: "A",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "Qual é a principal diferença entre uma oração coordenada e uma oração subordinada?",
    tip: "Pense em como uma oração coordenada poderia \"funcionar\" separadamente, enquanto uma subordinada, separada, ficaria incompleta.",
    funFact: "Essa diferença é fundamental para entender a estrutura do período composto — você vai estudar mais sobre orações subordinadas em outras aulas!",
    points: 1,
    options: [
      { id: "A", text: "Não existe diferença alguma entre elas" },
      { id: "B", text: "A oração subordinada sempre vem antes da coordenada" },
      { id: "C", text: "A oração coordenada tem sentido completo por si só; a subordinada depende de outra oração para ter sentido completo" },
      { id: "D", text: "A oração coordenada nunca pode ser usada em textos formais" },
    ],
    correctAnswer: "C",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Na frase \"Estudei bastante e tirei uma boa nota\", qual tipo de conjunção coordenativa está presente?",
    tip: "Pense em como a conjunção \"e\" está somando duas ideias nessa frase — estudar e tirar uma boa nota.",
    funFact: "As conjunções aditivas são muito usadas para unir ações ou ideias que acontecem em sequência ou em conjunto!",
    points: 1,
    options: [
      { id: "A", text: "Adversativa" },
      { id: "B", text: "Alternativa" },
      { id: "C", text: "Conclusiva" },
      { id: "D", text: "Aditiva" },
    ],
    correctAnswer: "D",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Na frase \"Vou de ônibus ou de bicicleta\", qual tipo de conjunção coordenativa está presente?",
    tip: "Pense em como a conjunção \"ou\" está apresentando duas opções de transporte, das quais apenas uma será escolhida.",
    funFact: "As conjunções alternativas são muito úteis quando queremos apresentar escolhas ou possibilidades em uma frase!",
    points: 1,
    options: [
      { id: "A", text: "Explicativa" },
      { id: "B", text: "Alternativa" },
      { id: "C", text: "Conclusiva" },
      { id: "D", text: "Aditiva" },
    ],
    correctAnswer: "B",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "Na frase \"Choveu muito, por isso a festa foi cancelada\", qual tipo de conjunção coordenativa está presente?",
    tip: "Pense em como a segunda parte da frase apresenta uma consequência lógica (conclusão) da primeira parte.",
    funFact: "A expressão \"por isso\" tem o mesmo valor de conjunções como \"portanto\" e \"logo\", todas indicando uma conclusão!",
    points: 1,
    options: [
      { id: "A", text: "Conclusiva" },
      { id: "B", text: "Adversativa" },
      { id: "C", text: "Aditiva" },
      { id: "D", text: "Alternativa" },
    ],
    correctAnswer: "A",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "Na frase \"Ele não foi à escola, pois estava doente\", qual tipo de conjunção coordenativa está presente?",
    tip: "Pense em como a segunda parte da frase está explicando o motivo pelo qual ele não foi à escola.",
    funFact: "A conjunção \"pois\", quando usada depois da oração principal para justificar algo, tem valor explicativo — diferente de quando é usada no início da frase, com valor conclusivo!",
    points: 1,
    options: [
      { id: "A", text: "Adversativa" },
      { id: "B", text: "Alternativa" },
      { id: "C", text: "Explicativa" },
      { id: "D", text: "Aditiva" },
    ],
    correctAnswer: "C",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Qual é o efeito de sentido criado pela conjunção adversativa \"porém\" na frase \"Ela é tímida, porém muito talentosa\"?",
    tip: "Pense em como a frase quer mostrar que, mesmo sendo tímida, essa pessoa tem outra qualidade importante e, de certa forma, inesperada.",
    funFact: "Conjunções adversativas como \"porém\" ajudam a criar frases mais ricas, mostrando contrastes interessantes entre características ou situações!",
    points: 1,
    options: [
      { id: "A", text: "Soma duas qualidades sem nenhum contraste" },
      { id: "B", text: "Cria um contraste entre a timidez e o talento, destacando que, apesar de uma característica, a outra também está presente" },
      { id: "C", text: "Indica uma conclusão lógica" },
      { id: "D", text: "Apresenta duas opções de escolha" },
    ],
    correctAnswer: "B",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "Qual destas frases apresenta um erro no uso da pontuação antes de uma conjunção adversativa?",
    tip: "Observe qual frase está sem a vírgula antes da conjunção adversativa \"mas\", que normalmente deveria estar presente.",
    funFact: "Essa vírgula antes de conjunções como \"mas\", \"porém\" e \"contudo\" ajuda o leitor a perceber a pausa e o contraste que está por vir na frase!",
    points: 1,
    options: [
      { id: "A", text: "\"Ele é gentil, mas muito tímido.\"" },
      { id: "B", text: "\"Estudei bastante, porém não fui bem na prova.\"" },
      { id: "C", text: "\"Ela é simpática, contudo exigente.\"" },
      { id: "D", text: "\"Ele é gentil mas muito tímido.\"" },
    ],
    correctAnswer: "D",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "Em um texto argumentativo, por que o uso de conjunções coordenativas conclusivas, como \"portanto\" e \"logo\", é importante?",
    tip: "Pense em como, em um texto que defende um ponto de vista, é importante mostrar como as ideias se encaixam, levando a uma conclusão clara.",
    funFact: "Conjunções conclusivas ajudam o leitor a entender a lógica do argumento, mostrando como uma ideia leva à outra, até chegar numa conclusão!",
    points: 1,
    options: [
      { id: "A", text: "Para ajudar a organizar as ideias, mostrando uma conclusão lógica a partir dos argumentos apresentados" },
      { id: "B", text: "Porque é proibido usar outras conjunções em textos argumentativos" },
      { id: "C", text: "Porque essas conjunções tornam o texto mais engraçado" },
      { id: "D", text: "Porque esses textos nunca podem ter conclusão" },
    ],
    correctAnswer: "A",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "Na frase \"Não fui à festa nem avisei que não iria\", qual tipo de conjunção coordenativa está presente, mesmo em uma frase negativa?",
    tip: "Pense em como \"nem\" está somando duas ações negativas na mesma frase — não ir e não avisar.",
    funFact: "A conjunção \"nem\" é uma variação da conjunção aditiva \"e\", usada especificamente quando a frase tem sentido negativo!",
    points: 1,
    options: [
      { id: "A", text: "Adversativa" },
      { id: "B", text: "Alternativa" },
      { id: "C", text: "Aditiva" },
      { id: "D", text: "Conclusiva" },
    ],
    correctAnswer: "C",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "Qual destas frases apresenta uma oração coordenada ligada por uma conjunção explicativa?",
    tip: "Observe qual frase está explicando o motivo pelo qual alguém deveria ficar em casa.",
    funFact: "Nessa frase, a conjunção \"que\" tem valor explicativo, equivalente a \"porque\" — mostrando o motivo da recomendação de ficar em casa!",
    points: 1,
    options: [
      { id: "A", text: "\"Estudei e passei na prova.\"" },
      { id: "B", text: "\"Vou de carro ou de ônibus.\"" },
      { id: "C", text: "\"Estudei muito, mas fiquei nervoso.\"" },
      { id: "D", text: "\"Fique em casa, que está chovendo muito.\"" },
    ],
    correctAnswer: "D",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "Por que é importante saber identificar os diferentes tipos de conjunções coordenativas em um texto?",
    tip: "Pense em como cada tipo de conjunção cria uma relação de sentido diferente entre as ideias — soma, contraste, conclusão ou explicação.",
    funFact: "Saber identificar essas conjunções ajuda bastante na interpretação de textos, pois cada uma indica uma relação lógica diferente entre as ideias apresentadas!",
    points: 1,
    options: [
      { id: "A", text: "Para decorar uma lista de palavras sem nenhuma utilidade" },
      { id: "B", text: "Para entender melhor as relações de sentido entre as ideias de um texto, como adição, oposição, conclusão e explicação" },
      { id: "C", text: "Porque isso nunca aparece em provas de português" },
      { id: "D", text: "Porque só existe um tipo de conjunção na língua portuguesa" },
    ],
    correctAnswer: "B",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Bernardo escreveu na redação: \"Estudei bastante e aprendi muita coisa nova.\" Qual tipo de conjunção coordenativa ele usou?",
    tip: "Lembra da conjunção usada para somar duas ideias, como estudar e aprender?",
    funFact: "Bernardo usou corretamente a conjunção aditiva \"e\", somando duas ações que aconteceram juntas em sua experiência de estudo!",
    points: 1,
    options: [
      { id: "A", text: "Adversativa" },
      { id: "B", text: "Alternativa" },
      { id: "C", text: "Conclusiva" },
      { id: "D", text: "Aditiva" },
    ],
    correctAnswer: "D",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Bernardo escreveu: \"Quero ir ao parque ou ao cinema no fim de semana.\" Qual tipo de conjunção coordenativa ele usou?",
    tip: "Lembra da conjunção usada para apresentar opções de escolha, como entre duas atividades diferentes?",
    funFact: "Bernardo usou a conjunção alternativa \"ou\", mostrando duas possibilidades de lazer para o fim de semana!",
    points: 1,
    options: [
      { id: "A", text: "Alternativa" },
      { id: "B", text: "Explicativa" },
      { id: "C", text: "Aditiva" },
      { id: "D", text: "Adversativa" },
    ],
    correctAnswer: "A",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Bernardo escreveu: \"Estudei muito, mas fiquei nervoso na hora da prova.\" Qual tipo de conjunção coordenativa ele usou?",
    tip: "Lembra da conjunção usada para mostrar um contraste entre duas ideias, como estudar muito e, ainda assim, ficar nervoso?",
    funFact: "Bernardo usou a conjunção adversativa \"mas\", mostrando que, apesar de ter estudado bastante, ainda sentiu nervosismo na hora da prova!",
    points: 1,
    options: [
      { id: "A", text: "Aditiva" },
      { id: "B", text: "Alternativa" },
      { id: "C", text: "Adversativa" },
      { id: "D", text: "Conclusiva" },
    ],
    correctAnswer: "C",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Bernardo escreveu: \"Treinei muito, por isso fiquei mais rápido na corrida.\" Qual tipo de conjunção coordenativa ele usou?",
    tip: "Lembra da conjunção usada para indicar uma conclusão lógica a partir do que foi dito antes?",
    funFact: "Bernardo usou a expressão conclusiva \"por isso\", mostrando como o treino o levou ao resultado de ficar mais rápido!",
    points: 1,
    options: [
      { id: "A", text: "Adversativa" },
      { id: "B", text: "Conclusiva" },
      { id: "C", text: "Alternativa" },
      { id: "D", text: "Explicativa" },
    ],
    correctAnswer: "B",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Bernardo escreveu: \"Não fui à escola, porque estava com febre.\" Qual tipo de conjunção coordenativa ele usou?",
    tip: "Lembra da conjunção usada para explicar o motivo de algo que aconteceu?",
    funFact: "Bernardo usou a conjunção explicativa \"porque\", justificando o motivo pelo qual não foi à escola!",
    points: 1,
    options: [
      { id: "A", text: "Explicativa" },
      { id: "B", text: "Aditiva" },
      { id: "C", text: "Alternativa" },
      { id: "D", text: "Adversativa" },
    ],
    correctAnswer: "A",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Bernardo percebeu que faltava uma vírgula na frase \"Ele é esforçado mas um pouco distraído.\" Onde ele deveria colocar a vírgula?",
    tip: "Lembra de que, antes de conjunções adversativas como \"mas\", normalmente se usa uma vírgula?",
    funFact: "Bernardo corrigiu corretamente a frase, que deveria ficar assim: \"Ele é esforçado, mas um pouco distraído\" — respeitando a pontuação adequada!",
    points: 1,
    options: [
      { id: "A", text: "No início da frase" },
      { id: "B", text: "Depois da palavra \"distraído\"" },
      { id: "C", text: "Não é necessário usar vírgula nessa frase" },
      { id: "D", text: "Antes da conjunção adversativa \"mas\"" },
    ],
    correctAnswer: "D",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Bernardo escreveu um texto argumentativo defendendo que as escolas deveriam ter mais tempo de recreio, usando a palavra \"portanto\" para concluir seu argumento. Essa conjunção tem valor:",
    tip: "Lembra da conjunção usada para indicar uma conclusão lógica a partir dos argumentos apresentados em um texto?",
    funFact: "Usar conjunções conclusivas, como \"portanto\", ajuda Bernardo a organizar melhor as ideias do seu texto argumentativo, mostrando como os argumentos levam a uma conclusão!",
    points: 1,
    options: [
      { id: "A", text: "Aditivo" },
      { id: "B", text: "Alternativo" },
      { id: "C", text: "Conclusivo" },
      { id: "D", text: "Explicativo" },
    ],
    correctAnswer: "C",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Bernardo identificou, em uma frase do seu livro, a conjunção \"nem\" sendo usada para somar duas ideias negativas. Essa conjunção tem valor:",
    tip: "Lembra de que \"nem\" é uma variação da conjunção \"e\", usada quando a frase tem sentido negativo?",
    funFact: "Bernardo identificou corretamente — \"nem\" tem o mesmo valor de soma da conjunção \"e\", mas é usada especificamente em frases negativas!",
    points: 1,
    options: [
      { id: "A", text: "Adversativo" },
      { id: "B", text: "Aditivo" },
      { id: "C", text: "Conclusivo" },
      { id: "D", text: "Explicativo" },
    ],
    correctAnswer: "B",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Depois de estudar as conjunções coordenativas, Bernardo concluiu que elas são importantes porque:",
    tip: "Pense em tudo que você aprendeu sobre como cada conjunção cria uma relação de sentido diferente entre as ideias de uma frase.",
    funFact: "Parabéns, Bernardo! Você aprendeu como as conjunções coordenativas ajudam a organizar e dar sentido às ideias dentro de um texto!",
    points: 1,
    options: [
      { id: "A", text: "Tornam os textos mais confusos de propósito" },
      { id: "B", text: "Não têm nenhuma utilidade real na escrita" },
      { id: "C", text: "Servem apenas para decorar listas de palavras" },
      { id: "D", text: "Ajudam a estabelecer diferentes relações de sentido entre as ideias de um texto, como adição, oposição, conclusão e explicação" },
    ],
    correctAnswer: "D",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Depois de todo esse estudo, Bernardo resumiu para a família: \"quando duas orações têm sentido completo e estão ligadas por palavras como 'e', 'mas', 'ou', 'portanto' ou 'porque', elas formam um período composto por...\". Qual palavra completa essa frase?",
    tip: "Pense na palavra que você aprendeu desde o início desse simulado, usada para descrever orações independentes ligadas entre si.",
    funFact: "Parabéns, Bernardo! Você aprendeu sobre o período composto por coordenação e os diferentes tipos de conjunções coordenativas — uma base importante para estudos gramaticais mais avançados!",
    points: 1,
    options: [
      { id: "A", text: "Coordenação" },
      { id: "B", text: "Subordinação" },
      { id: "C", text: "Discurso indireto" },
      { id: "D", text: "Voz passiva" },
    ],
    correctAnswer: "A",
  },
];
