export const questoesHistoria8AnoB3Av1 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "Em que data o Brasil se tornou independente de Portugal?",
    tip: "Essa data é feriado nacional no Brasil até hoje! Pensa num mês de primavera, bem no início...",
    funFact: "Nesse dia há sempre desfiles militares e escolares em todo o Brasil para comemorar a data!",
    points: 1,
    options: [
      { id: "A", text: "25 de dezembro de 1822" },
      { id: "B", text: "15 de novembro de 1822" },
      { id: "C", text: "1º de janeiro de 1822" },
      { id: "D", text: "7 de setembro de 1822" },
    ],
    correctAnswer: "D",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "Quem foi o responsável por proclamar a independência do Brasil?",
    tip: "Essa pessoa era filho do rei de Portugal e decidiu ficar no Brasil para governar como imperador!",
    funFact: "Ele tinha apenas 23 anos quando proclamou a independência!",
    points: 1,
    options: [
      { id: "A", text: "D. Pedro I" },
      { id: "B", text: "D. João VI" },
      { id: "C", text: "José Bonifácio" },
      { id: "D", text: "Simón Bolívar" },
    ],
    correctAnswer: "A",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "Onde a independência do Brasil foi proclamada?",
    tip: "Esse lugar é tão famoso que até um hino nacional tem o nome dele!",
    funFact: "Hoje existe um monumento enorme chamado \"Monumento à Independência\" exatamente nesse local, em São Paulo!",
    points: 1,
    options: [
      { id: "A", text: "No Rio de Janeiro" },
      { id: "B", text: "Em Lisboa, Portugal" },
      { id: "C", text: "Às margens do Rio Ipiranga, em São Paulo" },
      { id: "D", text: "Na Bahia" },
    ],
    correctAnswer: "C",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "Qual foi a famosa frase dita por D. Pedro I no momento da independência, conhecida como \"Grito do Ipiranga\"?",
    tip: "Essa frase mostra que D. Pedro estava decidido a romper com Portugal, nem que fosse preciso lutar!",
    funFact: "Essa frase é cantada até hoje em uma das estrofes do Hino da Independência!",
    points: 1,
    options: [
      { id: "A", text: "\"Fico com o povo\"" },
      { id: "B", text: "\"Independência ou morte\"" },
      { id: "C", text: "\"Viva o rei\"" },
      { id: "D", text: "\"Paz e liberdade\"" },
    ],
    correctAnswer: "B",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "O que foi o \"Dia do Fico\", ocorrido meses antes da independência?",
    tip: "Pensa no próprio nome do episódio: \"fico\" quer dizer que ele decidiu permanecer em algum lugar!",
    funFact: "Esse episódio aconteceu em janeiro de 1822, poucos meses antes da independência!",
    points: 1,
    options: [
      { id: "A", text: "O dia em que D. Pedro foi coroado" },
      { id: "B", text: "O dia em que o Brasil ganhou uma bandeira nova" },
      { id: "C", text: "O dia em que Portugal declarou guerra ao Brasil" },
      { id: "D", text: "O dia em que D. Pedro decidiu ficar no Brasil, desobedecendo às Cortes portuguesas" },
    ],
    correctAnswer: "D",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "Por que as Cortes portuguesas queriam que D. Pedro voltasse para Portugal?",
    tip: "Pensa no interesse de Portugal: eles queriam voltar a controlar o Brasil como antes, sem tanta liberdade!",
    funFact: "Essa tentativa de recolonização foi um dos principais motivos que levaram à independência!",
    points: 1,
    options: [
      { id: "A", text: "Queriam recolonizar o Brasil e diminuir sua autonomia" },
      { id: "B", text: "Queriam que ele estudasse em Portugal" },
      { id: "C", text: "Queriam que ele se casasse em Portugal" },
      { id: "D", text: "Queriam dar mais poder ao Brasil" },
    ],
    correctAnswer: "A",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "Quem era o rei de Portugal e pai de D. Pedro I?",
    tip: "Esse rei veio para o Brasil fugindo de Napoleão, lembra? Ele voltou para Portugal e deixou o filho aqui!",
    funFact: "D. João VI governou o Reino Unido de Portugal, Brasil e Algarves antes de retornar à Europa em 1821!",
    points: 1,
    options: [
      { id: "A", text: "D. Miguel" },
      { id: "B", text: "D. Afonso" },
      { id: "C", text: "D. João VI" },
      { id: "D", text: "D. Carlos" },
    ],
    correctAnswer: "C",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "Qual era a relação política entre Brasil e Portugal antes da independência?",
    tip: "Pensa num \"reino unido\": o Brasil tinha sido elevado à mesma categoria de Portugal, mas ainda fazia parte do mesmo reino!",
    funFact: "Essa união foi criada em 1815, deixando o Brasil com mais importância política do que quando era só colônia!",
    points: 1,
    options: [
      { id: "A", text: "Eram países totalmente separados" },
      { id: "B", text: "O Brasil era parte do Reino Unido de Portugal, Brasil e Algarves" },
      { id: "C", text: "O Brasil governava Portugal" },
      { id: "D", text: "Não existia nenhuma relação entre eles" },
    ],
    correctAnswer: "B",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "Que tipo de governo o Brasil se tornou depois da independência?",
    tip: "Pensa que o Brasil continuou tendo um governante único, só que agora com o título de imperador, e não mais rei!",
    funFact: "O Brasil foi o único país das Américas a manter uma monarquia por tanto tempo depois de sua independência!",
    points: 1,
    options: [
      { id: "A", text: "República" },
      { id: "B", text: "Ditadura" },
      { id: "C", text: "Confederação" },
      { id: "D", text: "Império (uma monarquia)" },
    ],
    correctAnswer: "D",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "Quem foi a imperatriz que apoiou fortemente a causa da independência ao lado de D. Pedro I?",
    tip: "Essa imperatriz era de origem austríaca e assinou documentos importantes a favor da independência enquanto D. Pedro estava viajando!",
    funFact: "Há relatos de que ela assinou o decreto preparando a independência antes mesmo de D. Pedro voltar de São Paulo!",
    points: 1,
    options: [
      { id: "A", text: "Leopoldina" },
      { id: "B", text: "Isabel" },
      { id: "C", text: "Teresa Cristina" },
      { id: "D", text: "Maria da Glória" },
    ],
    correctAnswer: "A",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Por que a elevação do Brasil a Reino Unido de Portugal, Brasil e Algarves, em 1815, foi importante no caminho até a independência?",
    tip: "Pensa em como ganhar mais importância política pode ser um passo para depois buscar mais autonomia!",
    funFact: "Essa mudança aconteceu ainda com D. João VI governando a partir do Rio de Janeiro!",
    points: 1,
    options: [
      { id: "A", text: "Porque deu ao Brasil um exército próprio imediatamente" },
      { id: "B", text: "Porque separou o Brasil de Portugal na hora" },
      { id: "C", text: "Porque elevou o status político do Brasil, deixando-o mais próximo da igualdade com Portugal" },
      { id: "D", text: "Porque proibiu qualquer comércio brasileiro" },
    ],
    correctAnswer: "C",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Qual foi o papel de José Bonifácio no processo de independência do Brasil?",
    tip: "Esse nome ganhou um título de \"pai\" da independência por sua importância nos bastidores políticos!",
    funFact: "José Bonifácio também defendia o fim gradual da escravidão, uma ideia avançada para a época!",
    points: 1,
    options: [
      { id: "A", text: "Ele foi o rei de Portugal" },
      { id: "B", text: "Ele foi um importante conselheiro de D. Pedro I, conhecido como Patriarca da Independência" },
      { id: "C", text: "Ele foi general do exército espanhol" },
      { id: "D", text: "Ele foi o primeiro presidente do Brasil" },
    ],
    correctAnswer: "B",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "O que foi a Confederação do Equador, ocorrida pouco depois da independência do Brasil?",
    tip: "Pensa numa região do Nordeste brasileiro que, insatisfeita, tentou formar seu próprio país separado do Império!",
    funFact: "Esse movimento mostrou que, mesmo após a independência, existiam divergências políticas dentro do novo Império!",
    points: 1,
    options: [
      { id: "A", text: "Um acordo de paz entre Brasil e Portugal" },
      { id: "B", text: "Uma nova capital do Império" },
      { id: "C", text: "Um tratado comercial com a Inglaterra" },
      { id: "D", text: "Uma revolta separatista ocorrida em Pernambuco" },
    ],
    correctAnswer: "D",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "Por que D. Pedro I decidiu romper com Portugal, mesmo sendo filho do rei português?",
    tip: "Pensa nos interesses da elite brasileira: eles queriam manter seus privilégios e não voltar a ser simples colônia!",
    funFact: "Ao ficar no Brasil, D. Pedro conseguiu o apoio de grande parte da população e das elites locais!",
    points: 1,
    options: [
      { id: "A", text: "Porque queria manter o trono no Brasil e atender aos interesses da elite brasileira" },
      { id: "B", text: "Porque Portugal pediu que ele fosse embora" },
      { id: "C", text: "Porque ele não gostava do Brasil" },
      { id: "D", text: "Porque a Espanha o convenceu a fazer isso" },
    ],
    correctAnswer: "A",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Qual foi a reação de Portugal à declaração de independência do Brasil?",
    tip: "Pensa no tamanho de Portugal comparado ao Brasil: era difícil manter uma guerra tão distante e cara!",
    funFact: "Apesar de alguns conflitos pontuais, a independência do Brasil foi considerada relativamente pacífica comparada a outras da época!",
    points: 1,
    options: [
      { id: "A", text: "Reconheceu a independência imediatamente, sem problemas" },
      { id: "B", text: "Enviou toda a família real de volta ao Brasil" },
      { id: "C", text: "Tentou reagir, mas não teve forças militares suficientes para reconquistar o Brasil" },
      { id: "D", text: "Desistiu de todas as colônias que tinha no mundo" },
    ],
    correctAnswer: "C",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "Qual país foi um dos primeiros a reconhecer oficialmente a independência do Brasil?",
    tip: "Pensa num país que também já tinha conquistado sua própria independência de uma potência europeia antes!",
    funFact: "Os Estados Unidos reconheceram a independência do Brasil já em 1824, apenas dois anos depois do Grito do Ipiranga!",
    points: 1,
    options: [
      { id: "A", text: "Espanha" },
      { id: "B", text: "França" },
      { id: "C", text: "Inglaterra" },
      { id: "D", text: "Estados Unidos" },
    ],
    correctAnswer: "D",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "Qual foi uma característica importante da independência do Brasil, comparada a outras independências da época?",
    tip: "Pensa em comparação com as guerras de independência na América espanhola, que duraram muito mais tempo e tiveram mais conflitos!",
    funFact: "Isso não significa que não houve conflitos — algumas províncias, como a Bahia, só se consolidaram como parte do Brasil depois de batalhas!",
    points: 1,
    options: [
      { id: "A", text: "Foi a mais violenta de todas as Américas" },
      { id: "B", text: "Foi um processo relativamente mais pacífico, apesar de conflitos pontuais" },
      { id: "C", text: "Durou mais de 50 anos de guerra" },
      { id: "D", text: "Não envolveu nenhuma figura política importante" },
    ],
    correctAnswer: "B",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "Qual título D. Pedro I assumiu ao se tornar o governante do Brasil independente?",
    tip: "Pensa no tipo de governo que o Brasil se tornou: uma monarquia, mas com um título um pouco diferente de \"rei\"!",
    funFact: "Esse título de imperador seria usado também pelo seu filho, D. Pedro II, décadas depois!",
    points: 1,
    options: [
      { id: "A", text: "Imperador do Brasil" },
      { id: "B", text: "Rei do Brasil" },
      { id: "C", text: "Presidente do Brasil" },
      { id: "D", text: "Governador-Geral" },
    ],
    correctAnswer: "A",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "Qual foi o papel da elite brasileira, como grandes proprietários de terra, no processo de independência?",
    tip: "Pensa nos interesses dessa elite: eles queriam continuar mandando nas suas terras sem depender tanto de Portugal!",
    funFact: "Muitos desses grandes proprietários continuaram influentes na política do Brasil durante todo o período do Império!",
    points: 1,
    options: [
      { id: "A", text: "Eles lutaram contra a independência" },
      { id: "B", text: "Eles não se importavam com o assunto" },
      { id: "C", text: "Eles apoiaram a independência para manter seus privilégios e poder" },
      { id: "D", text: "Eles pediram para virar colônia espanhola" },
    ],
    correctAnswer: "C",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "Por que a independência do Brasil manteve a monarquia, diferente dos Estados Unidos, que se tornaram república?",
    tip: "Pensa em quem liderou cada processo: nos EUA foram colonos comuns, e no Brasil foi o próprio príncipe herdeiro!",
    funFact: "O Brasil só se tornaria uma república décadas depois, em 1889!",
    points: 1,
    options: [
      { id: "A", text: "Porque o Brasil não tinha elite política" },
      { id: "B", text: "Porque o próprio filho do rei português liderou o processo, mantendo a mesma forma de governo" },
      { id: "C", text: "Porque os Estados Unidos pediram ao Brasil para ser república" },
      { id: "D", text: "Porque a Espanha exigiu isso" },
    ],
    correctAnswer: "B",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Bernardo quer saber a data exata da independência do Brasil. Qual é ela?",
    tip: "É a mesma data comemorada todos os anos com desfiles pelo Brasil inteiro!",
    funFact: "Esse feriado é um dos mais importantes do calendário nacional brasileiro!",
    points: 1,
    options: [
      { id: "A", text: "15 de novembro de 1889" },
      { id: "B", text: "25 de dezembro de 1822" },
      { id: "C", text: "1º de maio de 1822" },
      { id: "D", text: "7 de setembro de 1822" },
    ],
    correctAnswer: "D",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Bernardo quer saber quem proclamou a independência do Brasil. Quem foi?",
    tip: "Foi o filho do rei de Portugal, que decidiu ficar no Brasil e se tornar o primeiro imperador!",
    funFact: "Depois da independência, ele se tornou o primeiro imperador da história do Brasil!",
    points: 1,
    options: [
      { id: "A", text: "D. Pedro I" },
      { id: "B", text: "D. João VI" },
      { id: "C", text: "Tiradentes" },
      { id: "D", text: "Napoleão Bonaparte" },
    ],
    correctAnswer: "A",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Bernardo leu sobre o \"Dia do Fico\". O que esse episódio representou?",
    tip: "Pensa no próprio nome: \"fico\" significa que ele decidiu permanecer aqui, e não voltar para a Europa!",
    funFact: "Esse episódio aconteceu poucos meses antes da independência, mostrando que D. Pedro já estava decidido a ficar!",
    points: 1,
    options: [
      { id: "A", text: "D. Pedro decidiu voltar para Portugal" },
      { id: "B", text: "O Brasil ganhou uma nova bandeira" },
      { id: "C", text: "D. Pedro decidiu ficar no Brasil, desobedecendo às Cortes portuguesas" },
      { id: "D", text: "Portugal declarou guerra ao Brasil" },
    ],
    correctAnswer: "C",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Bernardo descobriu a frase famosa gritada por D. Pedro no Ipiranga. Qual foi ela?",
    tip: "Essa frase mostra a decisão firme de D. Pedro de romper definitivamente com Portugal!",
    funFact: "Essa frase está até hoje presente em versos do Hino da Independência do Brasil!",
    points: 1,
    options: [
      { id: "A", text: "\"Viva o rei de Portugal\"" },
      { id: "B", text: "\"Independência ou morte\"" },
      { id: "C", text: "\"Paz para sempre\"" },
      { id: "D", text: "\"Fico com Portugal\"" },
    ],
    correctAnswer: "B",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Bernardo quer saber quem ajudou D. Pedro a organizar o processo de independência, sendo chamado de Patriarca da Independência. Quem foi essa pessoa?",
    tip: "Esse conselheiro ganhou um título de \"patriarca\" por sua grande importância nos bastidores da independência!",
    funFact: "Ele também já defendia ideias avançadas para a época, como o fim gradual da escravidão!",
    points: 1,
    options: [
      { id: "A", text: "D. João VI" },
      { id: "B", text: "Simón Bolívar" },
      { id: "C", text: "George Washington" },
      { id: "D", text: "José Bonifácio" },
    ],
    correctAnswer: "D",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Bernardo ficou curioso sobre qual país reconheceu a independência do Brasil logo em 1824. Qual foi esse país?",
    tip: "Pensa num país que também já tinha conquistado sua independência de uma potência europeia antes do Brasil!",
    funFact: "Esse reconhecimento rápido ajudou o Brasil a ser aceito mais facilmente entre as nações do mundo!",
    points: 1,
    options: [
      { id: "A", text: "Espanha" },
      { id: "B", text: "França" },
      { id: "C", text: "Estados Unidos" },
      { id: "D", text: "Rússia" },
    ],
    correctAnswer: "C",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Bernardo aprendeu que tipo de governo o Brasil se tornou depois da independência. Qual foi?",
    tip: "Pensa que o Brasil continuou tendo um único governante no poder, só que agora chamado de imperador!",
    funFact: "O Brasil manteria esse tipo de governo até 1889, quando se tornaria uma república!",
    points: 1,
    options: [
      { id: "A", text: "Monarquia (Império)" },
      { id: "B", text: "República" },
      { id: "C", text: "Ditadura militar" },
      { id: "D", text: "Confederação de estados" },
    ],
    correctAnswer: "A",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Bernardo quer saber qual título D. Pedro assumiu depois da independência. Qual foi?",
    tip: "Pensa no tipo de governo que o Brasil se tornou: ele usou um título parecido com o de outros grandes impérios da história!",
    funFact: "Esse mesmo título seria usado décadas depois pelo seu filho, D. Pedro II!",
    points: 1,
    options: [
      { id: "A", text: "Rei do Brasil" },
      { id: "B", text: "Imperador do Brasil" },
      { id: "C", text: "Presidente do Brasil" },
      { id: "D", text: "Príncipe Regente" },
    ],
    correctAnswer: "B",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Bernardo está comparando a independência do Brasil com a dos Estados Unidos. Qual é uma diferença importante entre elas?",
    tip: "Pensa em quem liderou cada processo: no Brasil foi o próprio príncipe herdeiro, e nos Estados Unidos foram colonos comuns!",
    funFact: "Apesar dessa diferença, os dois processos foram inspirados por ideias parecidas de liberdade e autonomia!",
    points: 1,
    options: [
      { id: "A", text: "O Brasil não teve nenhum líder na independência" },
      { id: "B", text: "Os Estados Unidos continuaram sendo colônia inglesa" },
      { id: "C", text: "As duas aconteceram no mesmo ano" },
      { id: "D", text: "O Brasil se tornou uma monarquia, enquanto os Estados Unidos se tornaram uma república" },
    ],
    correctAnswer: "D",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Para resumir seus estudos, Bernardo quer lembrar o principal fato sobre a independência do Brasil. Qual frase resume bem esse momento?",
    tip: "Pensa em tudo que você aprendeu: a data, o líder e o tipo de governo que surgiu depois!",
    funFact: "Essa história é contada até hoje em livros, músicas e até pinturas famosas, como o quadro \"Independência ou Morte\"!",
    points: 1,
    options: [
      { id: "A", text: "O Brasil continuou sendo colônia de Portugal para sempre" },
      { id: "B", text: "A independência do Brasil não teve nenhuma importância histórica" },
      { id: "C", text: "O Brasil se separou de Portugal em 1822, liderado por D. Pedro I, e se tornou um Império" },
      { id: "D", text: "O Brasil se tornou uma república logo após a independência" },
    ],
    correctAnswer: "C",
  },
];
