export const questoesArte1EmB4Av2 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "O Surrealismo surgiu em Paris na década de 1920 e foi fundado por André Breton. O que define o Surrealismo como movimento artístico?",
    tip: "O nome 'surrealismo' vem de 'sur' (acima de) + 'realismo'. O que há 'acima da realidade' que os surrealistas queriam explorar?",
    funFact: "\"Você sabia?\" — O Manifesto Surrealista (1924) foi escrito por André Breton inspirado nas teorias de Sigmund Freud sobre o inconsciente. Para Breton, os sonhos e o inconsciente revelavam uma realidade mais verdadeira que a realidade visível. O movimento transformou para sempre a arte, a literatura, o cinema e a publicidade.",
    points: 1,
    options: [
      { id: "A", text: "A exploração do inconsciente, dos sonhos e do irracional como fontes de criação artística, indo além da realidade consciente e lógica" },
      { id: "B", text: "A representação da realidade com perfeição técnica através de métodos científicos de observação" },
      { id: "C", text: "A criação de arte para servir à revolução política e à educação das massas trabalhadoras" },
      { id: "D", text: "A busca da abstração total, eliminando qualquer referência ao mundo visível" },
    ],
    correctAnswer: "A",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "'A Persistência da Memória' (1931), de Salvador Dalí, é provavelmente a pintura surrealista mais famosa do mundo. O que os relógios derretendo representam?",
    tip: "O próprio Dalí disse que a ideia veio ao olhar para um queijo camembert derretendo no calor. O que o tempo derretendo evoca?",
    funFact: "\"Você sabia?\" — Dalí pintou A Persistência da Memória em apenas algumas horas, enquanto Gala (sua esposa e musa) havia saído. Quando ela voltou, olhou para o quadro e disse que era impossível esquecê-lo uma vez que fosse visto. Dalí concordou, dizendo: 'Era o que eu queria.'",
    points: 1,
    options: [
      { id: "A", text: "A velocidade do progresso tecnológico moderno, que derrete as fronteiras entre passado e futuro" },
      { id: "B", text: "A crise econômica da Grande Depressão, onde até o tempo se tornara sem valor e fluido" },
      { id: "C", text: "A influência da teoria da relatividade de Einstein sobre a arte, tornando o tempo visualmente relativo" },
      { id: "D", text: "A fluidez e subjetividade do tempo nos sonhos e no inconsciente — onde o tempo não obedece às leis físicas da vigília" },
    ],
    correctAnswer: "D",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "René Magritte criou 'A Traição das Imagens' (1929) — uma pintura de um cachimbo com a legenda 'Ceci n'est pas une pipe' ('Isto não é um cachimbo'). O que Magritte quis dizer?",
    tip: "Magritte estava comentando algo fundamental sobre a diferença entre um objeto e sua representação. O que é uma pintura de um cachimbo?",
    funFact: "\"Você sabia?\" — Magritte foi professor de arte e costumava explicar a obra assim: 'Claro que não é um cachimbo — tente enchê-lo com tabaco!' A obra é uma meditação filosófica sobre semiótica (o estudo dos signos) que antecipou discussões da filosofia da linguagem e inaugurou questões que a arte conceitual exploraria décadas depois.",
    points: 1,
    options: [
      { id: "A", text: "A pintura é uma crítica irônica à sociedade francesa que nunca entendeu o surrealismo" },
      { id: "B", text: "O cachimbo na pintura é invisível para quem não acredita na arte surrealista" },
      { id: "C", text: "A representação de um objeto não é o objeto — a imagem é um signo que se interpõe entre o espectador e a realidade" },
      { id: "D", text: "Magritte não sabia pintar cachimbos, então a imagem era tecnicamente imprecisa" },
    ],
    correctAnswer: "C",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "Frida Kahlo (1907-1954) foi a mais importante artista mexicana do século XX. O que tornava sua obra única no contexto da arte moderna?",
    tip: "Frida sofreu um acidente grave em 1925 que a deixou com dores crônicas para o resto da vida. Como isso se refletiu em sua obra?",
    funFact: "\"Você sabia?\" — Frida começou a pintar durante a convalescença após o acidente, com um espelho especialmente instalado no teto sobre sua cama. Isso explica a enorme quantidade de autorretratos em sua obra — era literalmente a única modelo disponível quando estava imobilizada.",
    points: 1,
    options: [
      { id: "A", text: "Por ser a única artista a usar pigmentos naturais extraídos de plantas medicinais mexicanas em vez de tintas industriais" },
      { id: "B", text: "Por combinar o pessoal com o político — sua experiência corporal, dor física, identidade mexicana e feminismo numa arte única e autobiográfica" },
      { id: "C", text: "Por criar um sistema de perspectiva radicalmente novo baseado nas tradições visuais astecas pré-colombianas" },
      { id: "D", text: "Por ser a primeira artista latina a expor no MoMA de Nova York, abrindo espaço para artistas não-europeus" },
    ],
    correctAnswer: "B",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "O Surrealismo foi profundamente influenciado pelas teorias de Sigmund Freud sobre o inconsciente. Como os surrealistas usavam essas ideias?",
    tip: "Freud descobriu que os sonhos revelam conteúdos inconscientes reprimidos. Como os artistas podiam acessar esse conteúdo?",
    funFact: "\"Você sabia?\" — Freud ficou profundamente desconfiado do Surrealismo. Quando Dalí o visitou em Londres em 1938, Freud escreveu a um amigo: 'Até hoje eu tendia a encarar os surrealistas como loucos completos. Este jovem espanhol com seus olhos fanáticos me convenceu de rever meu julgamento.' O encontro foi um momento histórico.",
    points: 1,
    options: [
      { id: "A", text: "Valorizavam o sonho, a associação livre e o automatismo psíquico para criar imagens que vinham do inconsciente sem censura da razão" },
      { id: "B", text: "Pintavam retratos de pacientes psiquiátricos como forma de documentar as descobertas de Freud para o público" },
      { id: "C", text: "Criavam obras que exigiam interpretação psicanalítica profissional — sem análise, a obra era incompreensível" },
      { id: "D", text: "Usavam técnicas de hipnose nos espectadores para que vissem os significados ocultos nas obras" },
    ],
    correctAnswer: "A",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "Salvador Dalí desenvolveu o 'método paranoico-crítico' para criar suas obras. Em que consistia esse método?",
    tip: "Dalí queria acessar conteúdos irracionais sem perder o controle técnico da execução. Como ele equilibrava esses opostos?",
    funFact: "\"Você sabia?\" — Dalí dormia com uma colher de metal na mão sobre um prato. No momento em que adormecia, a colher caía, o barulho o acordava, e ele tinha acesso a imagens hipnagógicas — o estado entre sono e vigília. Essas imagens alimentavam suas obras. Era um método surpreendentemente científico para acessar o irracional.",
    points: 1,
    options: [
      { id: "A", text: "Criar pinturas em estado de transe hipnótico, sem nenhum controle consciente sobre os resultados" },
      { id: "B", text: "Estudar casos clínicos de paranoia para reproduzir alucinações com precisão fotográfica" },
      { id: "C", text: "Trabalhar apenas com assistentes que tinham diagnóstico de algum transtorno mental" },
      { id: "D", text: "Estimular visões delirantes irracionais para depois representá-las com hiperrealismo técnico rigoroso" },
    ],
    correctAnswer: "D",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "René Magritte pintou repetidamente homens de chapéu-coco sem rosto (ou com o rosto obscurecido). O que esse personagem representa em sua obra?",
    tip: "O homem de chapéu-coco era a figura do burguês comum, anônimo e intercambiável. Qual era o questionamento de Magritte?",
    funFact: "\"Você sabia?\" — Magritte era um homem extremamente discreto e convencional na aparência — usava exatamente os chapéus-coco que pintava. Sua arte violentamente perturbadora vinha de um homem que parecia o mais comum dos vizinhos. Essa contradição entre aparência e realidade era o coração de sua obra.",
    points: 1,
    options: [
      { id: "A", text: "A superioridade intelectual dos artistas sobre a classe burguesa que não compreendia a arte" },
      { id: "B", text: "A alienação do trabalhador numa sociedade capitalista que o torna uma mercadoria fungível" },
      { id: "C", text: "O questionamento sobre identidade e realidade — a ideia de que o que vemos nunca é a coisa em si, mas sempre uma representação que obscurece o real" },
      { id: "D", text: "A nostalgia pelos valores tradicionais da sociedade belga do século XIX" },
    ],
    correctAnswer: "C",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "Frida Kahlo pintou mais de 55 autorretratos num total de cerca de 143 obras. Por que o autorretrato era tão central em sua produção?",
    tip: "Frida passava longos períodos acamada ou em recuperação cirúrgica. Qual era o único modelo sempre disponível?",
    funFact: "\"Você sabia?\" — Frida disse: 'Pinto a mim mesma porque sou o tema que conheço melhor'. Mas os autorretratos não eram vaidade — eram investigações filosóficas sobre identidade, dor, política e pertencimento. André Breton tentou associá-la ao Surrealismo, mas Frida rejeitou: 'Nunca pintei sonhos — pintei minha própria realidade.'",
    points: 1,
    options: [
      { id: "A", text: "Porque o autorretrato era a única forma de arte que vendia bem no mercado mexicano da época" },
      { id: "B", text: "Porque Frida usava o autorretrato para documentar sua dor física, identidade cultural e história pessoal — o próprio corpo como campo político e autobiográfico" },
      { id: "C", text: "Porque o marido Diego Rivera exigia que ela pintasse apenas a si mesma para não ser comparada a ele" },
      { id: "D", text: "Porque técnicas surrealistas de escrita automática adaptadas à pintura produziam invariavelmente autorretratos" },
    ],
    correctAnswer: "B",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "André Breton, fundador do Surrealismo, definiu o movimento no Manifesto Surrealista de 1924. Como ele definiu o surrealismo?",
    tip: "A definição de Breton é quase técnica — o que o surrealismo é, como método e como filosofia.",
    funFact: "\"Você sabia?\" — André Breton foi extremamente autoritário na gestão do Surrealismo — expulsou artistas que discordavam de suas posições políticas, incluindo Dalí (demasiado simpático ao fascismo), Artaud, Bataille e outros. Ironicamente, o movimento que celebrava a libertação do inconsciente era administrado com rígidos critérios de exclusão.",
    points: 1,
    options: [
      { id: "A", text: "Automatismo psíquico puro pelo qual se propõe exprimir, verbalmente ou por escrito, o funcionamento real do pensamento — sem controle da razão nem preocupações estéticas ou morais" },
      { id: "B", text: "Arte que supera a realidade ao representar visualmente os conteúdos da psicanálise em imagens simbólicas codificadas" },
      { id: "C", text: "Movimento estético que busca a beleza no inesperado, no casual e no misterioso, em oposição ao racionalismo acadêmico" },
      { id: "D", text: "Arte que combina sonho e realidade numa síntese superior que transcende ambos, chamada de 'realidade absoluta'" },
    ],
    correctAnswer: "A",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "A 'escrita automática' era uma técnica surrealista adaptada para artes visuais. Como os artistas surrealistas aplicavam o princípio do automatismo à pintura?",
    tip: "O automatismo busca eliminar o controle consciente e deixar o inconsciente guiar o processo. Como fazer isso numa pintura?",
    funFact: "\"Você sabia?\" — Joan Miró desenvolveu uma técnica de 'pintura onírica' que começava com manchas acidentais de tinta sobre a tela. Ele então 'lia' essas manchas com olhos quase em estado de sonho e a partir delas desenvolvia formas biológicas e lunares que ficaram como sua marca registrada. O acidente como ponto de partida.",
    points: 1,
    options: [
      { id: "A", text: "Pintando apenas durante a noite, quando o sono reduzia a autocensura do artista" },
      { id: "B", text: "Copiando com precisão fotográfica as imagens de sonhos anotadas ao acordar, sem nenhuma alteração ou interpretação" },
      { id: "C", text: "Consultando um psicanalista antes de cada obra para decidir qual conteúdo inconsciente seria representado" },
      { id: "D", text: "Deixando a mão guiar-se livremente sobre o papel sem controle consciente, gerando imagens que vinham do inconsciente" },
    ],
    correctAnswer: "D",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Wassily Kandinsky é considerado o criador da arte abstrata. Qual influência foi decisiva para que Kandinsky abandonasse a representação figurativa?",
    tip: "Kandinsky era músico além de pintor e as duas artes se fundiram em sua teoria. Qual arte ele queria que a pintura imitasse?",
    funFact: "\"Você sabia?\" — Kandinsky teve uma experiência reveladora ao ver uma de suas próprias pinturas de cabeça para baixo à noite — não a reconheceu imediatamente e ficou perturbado com a beleza daquela composição de cores e formas sem significado figurativo. Esse momento foi decisivo: percebeu que a forma pura comunicava emoções independentemente da representação.",
    points: 1,
    options: [
      { id: "A", text: "A matemática — Kandinsky queria que a pintura tivesse a precisão e universalidade da linguagem matemática" },
      { id: "B", text: "A arquitetura — Kandinsky queria que as pinturas funcionassem como espaços tridimensionais habitáveis" },
      { id: "C", text: "A música — que emociona profundamente sem representar nada do mundo visível — mostrou a Kandinsky que a pintura podia fazer o mesmo" },
      { id: "D", text: "A poesia — Kandinsky queria que as pinturas contassem histórias através de símbolos visuais como a poesia faz com palavras" },
    ],
    correctAnswer: "C",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Piet Mondrian (1872-1944) desenvolveu um estilo de abstracionismo completamente diferente do de Kandinsky. O que caracterizava o estilo abstrato de Mondrian?",
    tip: "Mondrian partiu de paisagens naturalistas e foi simplificando progressivamente até chegar a algo radicalmente geométrico. Onde chegou?",
    funFact: "\"Você sabia?\" — O processo de abstração de Mondrian pode ser seguido em suas pinturas de uma árvore: começou com uma árvore naturalista, foi simplificando até linhas curvas, depois linhas retas, até que a árvore desapareceu completamente e sobrou apenas uma grade de linhas pretas e retângulos coloridos. Um dos mais documentados processos de abstração da história.",
    points: 1,
    options: [
      { id: "A", text: "Formas orgânicas biológicas em cores primárias que evocavam a vitalidade da natureza microscópica" },
      { id: "B", text: "Grade de linhas pretas horizontais e verticais com retângulos preenchidos pelas cores primárias (vermelho, azul, amarelo) e pelos neutros (branco, preto, cinza)" },
      { id: "C", text: "Composições de triângulos, hexágonos e polígonos irregulares que representavam cristais e estruturas minerais" },
      { id: "D", text: "Manchas livres de cor pura aplicadas com espátula para criar superfícies vibrantes e emocionalmente intensas" },
    ],
    correctAnswer: "B",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "Kandinsky criou sua primeira aquarela abstrata por volta de 1910 — considerada a primeira obra de arte abstrata da história ocidental. O que a tornava radicalmente nova?",
    tip: "Antes de Kandinsky, toda pintura ocidental — mesmo a mais estilizada — representava algo do mundo visível. O que havia de novo?",
    funFact: "\"Você sabia?\" — Há uma polêmica histórica sobre quem foi o 'primeiro abstrato' — alguns historiadores apontam František Kupka ou Hilma af Klint como anteriores a Kandinsky. Af Klint, artista sueca, produziu obras completamente abstratas a partir de 1906, mas não as exibiu publicamente em vida. O debate continua.",
    points: 1,
    options: [
      { id: "A", text: "Pela primeira vez uma obra ocidental não representava nada do mundo visível — eram apenas cores, linhas e formas expressando sensações e estados emocionais" },
      { id: "B", text: "Por ser a primeira pintura a usar tinta acrílica ao invés de tinta a óleo, criando efeitos de transparência nunca vistos" },
      { id: "C", text: "Por ser a primeira obra de arte criada com técnicas de projeção de diapositivos sobre a tela" },
      { id: "D", text: "Por ser a primeira obra a representar simultaneamente a visão de múltiplos espectadores diferentes" },
    ],
    correctAnswer: "A",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "Mondrian chamou seu sistema visual de 'Neoplasticismo'. Qual era a teoria por trás dessa escolha de elementos reduzidos ao mínimo?",
    tip: "Mondrian não estava apenas fazendo decoração — havia uma filosofia por trás da escolha das linhas verticais e horizontais e das três cores primárias.",
    funFact: "\"Você sabia?\" — Mondrian era teósofo — seguia uma filosofia espiritual que buscava princípios universais por trás das aparências do mundo. Para ele, vertical e horizontal representavam o masculino e o feminino, o espiritual e o material em equilíbrio universal. Cada quadro era uma meditação sobre o equilíbrio cósmico.",
    points: 1,
    options: [
      { id: "A", text: "As linhas e cores foram escolhidas por serem as mais fáceis de reproduzir industrialmente, facilitando a democratização da arte" },
      { id: "B", text: "As formas foram inspiradas nas tradições visuais das tribos aborígines australianas que Mondrian estudou" },
      { id: "C", text: "As formas foram escolhidas por serem as mais econômicas em termos de material — Mondrian era muito pobre e precisava economizar tinta" },
      { id: "D", text: "As linhas verticais e horizontais representavam as tensões fundamentais do universo; as cores primárias, os elementos irredutíveis da realidade — um vocabulário visual universal e absoluto" },
    ],
    correctAnswer: "D",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Mondrian fundou o movimento 'De Stijl' (em holandês, 'O Estilo') junto com Theo van Doesburg. O De Stijl influenciou principalmente qual área além da pintura?",
    tip: "O De Stijl buscava um estilo total, aplicável a todas as artes. Onde seu impacto foi mais duradouro e visível no dia a dia?",
    funFact: "\"Você sabia?\" — A poltrona 'Red and Blue Chair' (1917) de Gerrit Rietveld é o objeto do De Stijl mais reproduzido. Ela nunca foi pensada para conforto (é incômoda de sentar) — era um manifesto tridimensional que aplicava os princípios de Mondrian ao espaço. Hoje é um ícone do design moderno.",
    points: 1,
    options: [
      { id: "A", text: "Na moda — o De Stijl revolucionou o design de roupas com listras verticais e horizontais e uso exclusivo de cores primárias" },
      { id: "B", text: "Na música — o De Stijl propôs uma reforma da harmonia tonal para usar apenas os três acordes primários" },
      { id: "C", text: "Na arquitetura e no design de interiores, de móveis e objetos — buscando um 'estilo total' geométrico e funcional" },
      { id: "D", text: "No cinema — o De Stijl desenvolveu uma teoria de montagem cinematográfica baseada em planos geométricos" },
    ],
    correctAnswer: "C",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "O abstracionismo pode ser dividido em duas vertentes principais: o abstracionismo lírico (ou informal) e o abstracionismo geométrico. Qual é a diferença essencial entre eles?",
    tip: "Um se organiza emocionalmente, com formas livres; o outro se organiza racionalmente, com formas calculadas. Quais artistas representam cada um?",
    funFact: "\"Você sabia?\" — Kandinsky ensinou na Bauhaus (Alemanha) ao mesmo tempo que Paul Klee — outra coluna do abstracionismo lírico. Mondrian nunca ensinou na Bauhaus, mas seus princípios de De Stijl chegaram indiretamente à escola através de colaboradores. A Bauhaus foi o ponto de encontro das duas vertentes abstratas.",
    points: 1,
    options: [
      { id: "A", text: "O lírico usa tintas naturais; o geométrico usa tintas industriais e acrílicas" },
      { id: "B", text: "O lírico (Kandinsky) usa formas orgânicas livres e cores emocionais; o geométrico (Mondrian) usa formas calculadas — linhas retas, ângulos e cores primárias" },
      { id: "C", text: "O lírico é exclusivamente escultura; o geométrico é exclusivamente pintura" },
      { id: "D", text: "O lírico surgiu na Europa; o geométrico foi desenvolvido exclusivamente nos Estados Unidos" },
    ],
    correctAnswer: "B",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "Jackson Pollock (1912-1956) ficou famoso pela técnica do 'dripping' ou 'action painting'. O que era essa técnica?",
    tip: "Pollock não usava pincéis convencionais. Como ele aplicava a tinta na tela?",
    funFact: "\"Você sabia?\" — O crítico de arte Harold Rosenberg cunhou o termo 'Action Painting' em 1952 para descrever o método de Pollock. Para Rosenberg, a tela era um 'campo de ação' onde o artista 'atuava' — a pintura era um registro de gestos corporais, não uma composição planejada. A performance vinha antes do resultado.",
    points: 1,
    options: [
      { id: "A", text: "Espalhar, pingar e jogar tinta sobre a tela posta no chão, usando o movimento de todo o corpo — o gesto físico e o acidente eram parte do processo" },
      { id: "B", text: "Usar rolo de pintura sobre superfícies texturizadas, criando padrões irregulares por pressão variável" },
      { id: "C", text: "Criar gotejamentos controlados com pipeta e seringa para formar padrões geométricos precisos" },
      { id: "D", text: "Usar tintas que escorregavam naturalmente pela tela inclinada, sem intervenção do artista" },
    ],
    correctAnswer: "A",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "Jackson Pollock foi influenciado pelo Surrealismo e pelo automatismo antes de criar seu estilo do dripping. O que o Surrealismo deu a Pollock?",
    tip: "O automatismo surrealista — criar sem controle consciente — foi uma semente para o método de Pollock. Como essa ideia se transformou?",
    funFact: "\"Você sabia?\" — Pollock foi paciente do psicanalista junguiano Joseph Henderson, com quem trabalhou produzindo desenhos que eram analisados psicanaliticamente. Esse mergulho no inconsciente através do Surrealismo foi decisivo para liberar Pollock da pintura figurativa que havia feito antes.",
    points: 1,
    options: [
      { id: "A", text: "A influência da arte indígena americana do sudoeste, que Pollock conheceu através de viagens ao Novo México" },
      { id: "B", text: "A técnica de usar areia misturada à tinta, que os navajo usavam em pinturas rituais de areia" },
      { id: "C", text: "A influência de muralistas mexicanos como Diego Rivera e Siqueiros, com quem Pollock trabalhou brevemente" },
      { id: "D", text: "A ideia de que o processo criativo podia ser guiado pelo inconsciente, liberando o gesto físico da censura racional e do controle estético prévio" },
    ],
    correctAnswer: "D",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "O Expressionismo Abstrato foi o primeiro movimento artístico genuinamente americano a ter influência global. Por que ele surgiu especificamente nos Estados Unidos?",
    tip: "Pense nas condições históricas dos anos 1940 — o que havia acontecido na Europa e como isso mudou o mapa do mundo da arte.",
    funFact: "\"Você sabia?\" — O galerista Peggy Guggenheim foi fundamental para o surgimento do Expressionismo Abstrato americano. Ela fugiu da Europa ocupada pelos nazistas com uma coleção enorme de arte surrealista e abstrata, abriu a galeria 'Arte Deste Século' em Nova York e foi a primeira a expor Pollock. Sem ela, o movimento talvez não tivesse acontecido.",
    points: 1,
    options: [
      { id: "A", text: "Porque os americanos criaram uma indústria de tintas acrílicas que permitia técnicas impossíveis na Europa" },
      { id: "B", text: "Porque o governo americano financiou a arte abstrata como política cultural durante a Guerra Fria" },
      { id: "C", text: "Porque artistas europeus refugiados da Segunda Guerra Mundial trouxeram o Surrealismo e o abstracionismo para Nova York, que se tornou o novo centro mundial da arte" },
      { id: "D", text: "Porque os Estados Unidos tinham uma tradição de arte expressiva e gestual que vinha dos indígenas americanos" },
    ],
    correctAnswer: "C",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "Além de Pollock, o Expressionismo Abstrato americano tinha outros grandes nomes. Qual artista, também expressionista abstrato, é famoso pelas enormes pinturas de campos de cor (Color Field)?",
    tip: "Este artista não usava o gesto violento de Pollock — criava imensos retângulos de cor que pareciam irradiar luz de dentro. Trabalhava com meditação e espiritualidade.",
    funFact: "\"Você sabia?\" — Mark Rothko disse que queria que as pessoas que ficassem em frente às suas obras grandes sentissem a mesma emoção que ele havia sentido ao pintá-las — emoções primárias como medo, êxtase, alegria. Quando soube que suas pinturas seriam usadas como decoração num restaurante de luxo (Four Seasons), ficou tão furioso que devolveu o pagamento e recusou a encomenda.",
    points: 1,
    options: [
      { id: "A", text: "Willem de Kooning — famoso pelas figuras femininas distorcidas em pinceladas violentas" },
      { id: "B", text: "Mark Rothko — conhecido pelos imensos campos de cor flutuantes que criavam uma experiência quase espiritual" },
      { id: "C", text: "Franz Kline — conhecido pelas pinceladas negras de grande escala sobre fundo branco" },
      { id: "D", text: "Lee Krasner — conhecida pelas pinturas de colagem com pedaços de seus próprios trabalhos anteriores" },
    ],
    correctAnswer: "B",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Jackson Pollock tinha múltiplas influências em seu trabalho além do Surrealismo. Qual outra influência importante está documentada em sua formação?",
    tip: "Pollock cresceu no sudoeste dos Estados Unidos e tinha fascínio por uma prática espiritual indígena que usava material similar à tinta.",
    funFact: "\"Você sabia?\" — Pollock viu demonstrações de pintura de areia Navajo nos anos 1940 em Nova York. A ideia de o artista caminhar ao redor da obra, jogando material colorido de diferentes ângulos e alturas, com a obra no chão (não num cavalete), influenciou diretamente sua técnica de dripping. Ele nunca negou essa influência.",
    points: 1,
    options: [
      { id: "A", text: "A pintura japonesa de caligrafia zen, que Pollock estudou durante uma viagem ao Japão nos anos 1930" },
      { id: "B", text: "Os muralistas mexicanos Rivera, Orozco e Siqueiros, com quem Pollock trabalhou brevemente em Nova York" },
      { id: "C", text: "A arquitetura brutalista de Le Corbusier, cujas superfícies texturizadas de concreto Pollock imitou na pintura" },
      { id: "D", text: "As pinturas de areia cerimoniais dos indígenas Navajo, onde o artista caminhava ao redor e sobre a obra, jogar areia colorida de cima" },
    ],
    correctAnswer: "D",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Wassily Kandinsky escreveu 'Do Espiritual na Arte' (1911), um dos mais importantes textos teóricos da arte moderna. O que Kandinsky afirmava sobre cor e forma?",
    tip: "Para Kandinsky, as cores e as formas não eram arbitrárias — tinham propriedades específicas e podiam comunicar algo diretamente.",
    funFact: "\"Você sabia?\" — Kandinsky tinha sinestesia — um fenômeno em que estímulos de um sentido evocam sensações em outro. Para ele, cada cor tinha um som específico, cada nota musical uma cor. Quando ouvia Schoenberg, via cores. Essa capacidade especial foi fundamental para construir sua teoria da correspondência entre cor, forma e emoção.",
    points: 1,
    options: [
      { id: "A", text: "Cores e formas têm qualidades emocionais e espirituais independentes — o amarelo vibra e agride, o azul é profundo e espiritual, o círculo é perfeição e o ângulo agudo é agressivo" },
      { id: "B", text: "Cores e formas são completamente arbitrárias — seu significado é dado exclusivamente pelo contexto cultural de cada espectador" },
      { id: "C", text: "A cor é o único elemento expressivo da pintura — as formas são irrelevantes para a comunicação emocional" },
      { id: "D", text: "As formas derivam das formas da natureza e as cores das cores naturais — a abstração deve permanecer ligada ao mundo visível" },
    ],
    correctAnswer: "A",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Mondrian chegou ao seu estilo de neoplasticismo após uma longa evolução que começou com paisagens naturalistas. Como foi esse processo?",
    tip: "Mondrian pintou árvores, depois as simplificou progressivamente. O que sobrou quando o processo chegou ao fim?",
    funFact: "\"Você sabia?\" — Mondrian fugiu de Paris com a ocupação nazista em 1940 e foi para Nova York, onde ficou encantado com o jazz e o ritmo urbano. Suas obras finais — 'Broadway Boogie Woogie' e 'Victory Boogie Woogie' — são as mais vibrantes e coloridas de toda sua carreira, com a influência direta da música americana.",
    points: 1,
    options: [
      { id: "A", text: "Mondrian partiu da escultura para chegar à pintura, e seu estilo geométrico foi influenciado pelas formas dos cristais que ele colecionava" },
      { id: "B", text: "Mondrian começou com arte africana, depois incorporou o Cubismo e chegou a padrões geométricos baseados em fractais naturais" },
      { id: "C", text: "Mondrian partiu do Impressionismo, depois do Cubismo, e chegou à eliminação total de linhas curvas — só linhas retas e ângulos de 90 graus, horizontais e verticais" },
      { id: "D", text: "Mondrian começou copiando mestres holandeses como Vermeer e chegou à abstração ao eliminar progressivamente as figuras humanas das composições" },
    ],
    correctAnswer: "C",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Frida Kahlo incorporou elementos da cultura mexicana pré-colombiana e popular em sua obra. Por que essa escolha tinha dimensão política?",
    tip: "Frida viveu na época do Pós-Revolução Mexicana (1910-1920) — um período de construção de identidade nacional. O que representar a cultura mexicana naquele momento significava?",
    funFact: "\"Você sabia?\" — Frida usava roupas tradicionais tehuanas em público — mesmo quando viajava a Paris ou Nova York — como afirmação política. André Breton ficou encantado com seu visual mas via-o como exótico. Frida irritava-se com esse olhar colonialista: para ela, era simplesmente sua identidade, não performance.",
    points: 1,
    options: [
      { id: "A", text: "Era uma estratégia comercial para diferenciar suas obras no mercado internacional de arte dominado por europeus" },
      { id: "B", text: "Era uma afirmação de identidade cultural — contra o colonialismo cultural europeu e em defesa das culturas indígenas e mestiças como legítimas e belas" },
      { id: "C", text: "Era uma exigência do marido Diego Rivera, que queria que Frida pintasse temas mexicanos para complementar seus murais" },
      { id: "D", text: "Era uma influência do Surrealismo de Breton, que valorizava culturas 'primitivas' como fonte de inconsciente coletivo" },
    ],
    correctAnswer: "B",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "O Surrealismo influenciou profundamente o cinema. Qual cineasta, em parceria com Salvador Dalí, criou os filmes surrealistas mais famosos?",
    tip: "Era um cineasta espanhol que, como Dalí, viveu em Paris nos anos 1920 e foi profundamente influenciado pelo ambiente surrealista.",
    funFact: "\"Você sabia?\" — 'Um Cão Andaluz' (1928) tem uma das cenas mais chocantes da história do cinema — o olho de uma mulher sendo cortado por uma navalha. Buñuel disse que ele e Dalí escolhiam as imagens por um único critério: se qualquer um dos dois conseguisse explicar racionalmente por que aquela imagem estava ali, ela era descartada. Só o inexplicável entrava.",
    points: 1,
    options: [
      { id: "A", text: "Federico Fellini — o cineasta italiano que criou 'Amarcord' com Dalí como designer de produção" },
      { id: "B", text: "Jean Cocteau — o poeta e cineasta francês que filmou 'A Bela e a Fera' com cenários desenhados por Dalí" },
      { id: "C", text: "Alfred Hitchcock — que contratou Dalí para criar a sequência de sonho de 'Spellbound'" },
      { id: "D", text: "Luis Buñuel — parceiro de Dalí nos filmes 'Um Cão Andaluz' (1928) e 'A Idade do Ouro' (1930), marcos do cinema surrealista" },
    ],
    correctAnswer: "D",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "O abstracionismo na arte moderna surge de dois caminhos históricos diferentes. Quais são esses dois caminhos?",
    tip: "Uma via passa pelo Expressionismo — pela intensificação emocional; outra passa pelo Cubismo — pela simplificação formal. Como chegam à abstração?",
    funFact: "\"Você sabia?\" — Hilma af Klint (1862-1944) produziu obras completamente abstratas a partir de 1906 — antes de Kandinsky e Mondrian. Ela era espiritualista e criava as obras em estados meditativos. Por instrução de seus guias espirituais, proibiu que as obras fossem expostas em vida. Só foram mostradas ao público em 1986 e hoje estão em museus do mundo todo.",
    points: 1,
    options: [
      { id: "A", text: "O caminho da simplificação e redução das formas visuais (Cubismo → Mondrian) e o caminho da intensificação emocional que transcende a figura (Expressionismo → Kandinsky)" },
      { id: "B", text: "O caminho da abstração matemática (geometria euclidiana) e o caminho da abstração biológica (formas orgânicas)" },
      { id: "C", text: "O caminho europeu (lento e teórico) e o caminho americano (rápido e instintivo)" },
      { id: "D", text: "O caminho da arte sacra (abstração espiritual medieval) e o caminho da arte científica (abstração baseada em física quântica)" },
    ],
    correctAnswer: "A",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "O 'Color Field Painting' foi uma vertente do Expressionismo Abstrato americano, diferente do Action Painting de Pollock. O que caracterizava o Color Field?",
    tip: "Mark Rothko e Barnett Newman são exemplos. Não havia gesto violento ou dripping — havia outra forma de intensidade. Qual?",
    funFact: "\"Você sabia?\" — As pinturas de Mark Rothko eram intencionalmente grandes para que o espectador não pudesse ver toda a obra de longe — era preciso ficar perto, e a cor então envolvia completamente o campo visual. Rothko queria que o espectador fosse 'consumido' pela cor, não que ficasse observando-a de fora como num museu convencional.",
    points: 1,
    options: [
      { id: "A", text: "Pintura que usa campos magnéticos para distribuir a cor uniformemente pela tela" },
      { id: "B", text: "Pintura que usa exclusivamente as três cores primárias — vermelho, azul e amarelo — como Mondrian" },
      { id: "C", text: "Grandes superfícies de cor pura, sem gesto visível, que criam imersão emocional e quase espiritual no espectador" },
      { id: "D", text: "Pintura inspirada nas paisagens americanas do Meio-Oeste, com campos de trigo e céu renderizados em estilo abstrato" },
    ],
    correctAnswer: "C",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Mark Rothko pertencia ao Expressionismo Abstrato e era profundamente influenciado pela filosofia e pela tragédia grega. Como isso se manifestava em sua arte?",
    tip: "Rothko queria que a pintura tivesse a grandeza emocional e espiritual da tragédia grega — drama puro, sem narração, sem figuras.",
    funFact: "\"Você sabia?\" — Rothko ficou clinicamente deprimido nos últimos anos de vida e as pinturas foram ficando cada vez mais escuras — das cores quentes (vermelhos, laranjas, amarelos dos anos 1950) para os marrons e pretos dos anos 1960. Em 1970 suicidou-se no ateliê, a poucos meses da abertura da Rothko Chapel em Houston, para a qual havia pintado obras especialmente.",
    points: 1,
    options: [
      { id: "A", text: "Rothko usava referências iconográficas diretas à mitologia grega nas composições abstratas" },
      { id: "B", text: "As enormes telas de cor pulsante tinham a ambição de provocar emoções tão fundamentais quanto a tragédia grega — catarse, êxtase, terror — sem figuras ou narrativas" },
      { id: "C", text: "Rothko organizava suas exposições seguindo a estrutura da trilogia trágica grega — três pinturas em sequência com clímax central" },
      { id: "D", text: "Rothko usava apenas as cores da cerâmica grega — terracota, preto e branco — como referência à civilização mediterrânea" },
    ],
    correctAnswer: "B",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "O Surrealismo, o Abstracionismo e o Expressionismo Abstrato representam três respostas diferentes à mesma questão fundamental da arte moderna. Qual é essa questão?",
    tip: "Todos esses movimentos surgem depois que a arte representacional foi 'resolvida' pela fotografia. Para onde vai a pintura quando não é mais necessária para representar a realidade?",
    funFact: "\"Você sabia?\" — O crítico de arte Clement Greenberg argumentou nos anos 1950 que a pintura abstrata americana era a arte mais 'pura' porque havia se libertado de qualquer função narrativa ou ilustrativa. Para ele, o auge da pintura era a absoluta 'pinturidade' — cor e plano bidimensional sem ilusão alguma. Era um argumento radical que influenciou toda uma geração.",
    points: 1,
    options: [
      { id: "A", text: "Como criar arte que seja mais barata e acessível à classe trabalhadora em economias capitalistas" },
      { id: "B", text: "Como representar objetos do cotidiano de forma mais fiel que a fotografia" },
      { id: "C", text: "Como criar arte que possa competir com o cinema como forma de entretenimento de massa" },
      { id: "D", text: "O que a pintura pode comunicar além da representação visual — inconsciente, emoção pura, sensação espiritual — explorando dimensões que a câmera não alcança" },
    ],
    correctAnswer: "D",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "O Surrealismo deixou uma herança enorme na cultura contemporânea, além das artes plásticas. Em quais outras áreas sua influência é mais evidente hoje?",
    tip: "Pense em filmes, publicidade, literatura, moda... O que você vê no dia a dia que tem a marca do Surrealismo?",
    funFact: "\"Você sabia?\" — A publicidade moderna é profundamente surrealista — usa imagens ilógicas, combinações inesperadas e associações irracionais que buscam criar impacto emocional sem explicação racional. O fundador da Publicidade moderna David Ogilvy estudou o Surrealismo. A próxima vez que você ver um comercial com imagens estranhas, você estará vendo a herança de Dalí e Magritte.",
    points: 1,
    options: [
      { id: "A", text: "Na publicidade, no cinema (Lynch, Gondry, Buñuel), na moda (Alexander McQueen) e na literatura — a lógica do sonho invadiu toda a cultura visual contemporânea" },
      { id: "B", text: "Exclusivamente na arte plástica e na literatura — o Surrealismo nunca foi assimilado pelas indústrias culturais de massa" },
      { id: "C", text: "Principalmente na arquitetura e no design industrial — as formas orgânicas do Surrealismo influenciaram a forma dos objetos cotidianos" },
      { id: "D", text: "Principalmente na música eletrônica contemporânea — os DJs usam técnicas de composição inspiradas no automatismo psíquico surrealista" },
    ],
    correctAnswer: "A",
  },
];
