export const questoesHistoria7AnoB2Av2 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "Durante o período colonial, quais dois grupos foram submetidos à escravização no território brasileiro?",
    tip: "Pensa em quem já vivia aqui e em quem foi trazido forçadamente de outro continente!",
    funFact: "O Brasil foi um dos países que mais recebeu pessoas escravizadas trazidas da África em todo o mundo!",
    points: 1,
    options: [
      { id: "A", text: "Apenas europeus" },
      { id: "B", text: "Apenas asiáticos" },
      { id: "C", text: "Apenas colonos portugueses" },
      { id: "D", text: "Povos indígenas e, principalmente a partir do século XVI, pessoas trazidas da África" },
    ],
    correctAnswer: "D",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "Por que, ao longo do tempo, os colonizadores portugueses passaram a recorrer cada vez mais à mão de obra africana escravizada, em vez de depender apenas da escravização indígena?",
    tip: "Pensa em tudo que estudamos sobre doenças europeias afetando os indígenas e o interesse comercial dos colonizadores!",
    funFact: "O tráfico de pessoas escravizadas da África se tornou um dos negócios mais lucrativos para comerciantes da época, o que infelizmente incentivou sua continuidade!",
    points: 1,
    options: [
      { id: "A", text: "Porque os indígenas se recusavam a qualquer tipo de trabalho" },
      { id: "B", text: "Por fatores como resistência indígena, doenças que afetavam a população indígena e interesses comerciais ligados ao tráfico de pessoas escravizadas da África" },
      { id: "C", text: "Porque não existiam mais indígenas no território" },
      { id: "D", text: "Porque a escravização indígena era proibida desde o início" },
    ],
    correctAnswer: "B",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "O que era o \"tráfico negreiro\"?",
    tip: "Pensa: esse \"comércio\" envolvia produtos ou pessoas sendo tratadas como mercadoria, contra sua vontade?",
    funFact: "Estima-se que milhões de pessoas africanas foram forçadamente trazidas para as Américas através desse comércio desumano!",
    points: 1,
    options: [
      { id: "A", text: "O comércio forçado de pessoas trazidas da África para serem escravizadas nas colônias" },
      { id: "B", text: "Um tipo de comércio de especiarias" },
      { id: "C", text: "Uma rota apenas de produtos agrícolas" },
      { id: "D", text: "Uma forma de comércio voluntário entre iguais" },
    ],
    correctAnswer: "A",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "As pessoas escravizadas trazidas da África eram, principalmente, utilizadas no Brasil colonial para:",
    tip: "Lembra do simulado anterior sobre os engenhos de açúcar e quem trabalhava neles!",
    funFact: "O trabalho forçado de pessoas escravizadas foi fundamental para sustentar praticamente toda a economia colonial, de forma profundamente injusta!",
    points: 1,
    options: [
      { id: "A", text: "Cargos políticos na Coroa portuguesa" },
      { id: "B", text: "Atividades apenas de lazer" },
      { id: "C", text: "Nenhuma atividade econômica" },
      { id: "D", text: "Trabalho forçado em diversas atividades, como nos engenhos de açúcar e, depois, na mineração" },
    ],
    correctAnswer: "D",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "Por que a escravidão é considerada, pela história e pelos direitos humanos atuais, uma violação grave e injusta?",
    tip: "Pensa no que significa perder completamente a liberdade e ser forçado a trabalhar contra a própria vontade!",
    funFact: "Hoje, a escravidão é reconhecida mundialmente como uma grave violação dos direitos humanos, proibida em todos os países!",
    points: 1,
    options: [
      { id: "A", text: "Porque não causava nenhum sofrimento às pessoas escravizadas" },
      { id: "B", text: "Porque era uma prática moderna e recente" },
      { id: "C", text: "Porque retirava a liberdade das pessoas, submetendo-as à força a trabalhos e maus-tratos" },
      { id: "D", text: "Porque beneficiava igualmente todos os envolvidos" },
    ],
    correctAnswer: "C",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "Apesar da escravização, como os povos indígenas e africanos resistiram a essa condição durante o período colonial?",
    tip: "Pensa: será que as pessoas escravizadas simplesmente aceitaram tudo, ou lutaram por sua liberdade?",
    funFact: "Essas formas de resistência deixaram marcas profundas na cultura brasileira, incluindo músicas, religiões e tradições até hoje!",
    points: 1,
    options: [
      { id: "A", text: "Aceitando passivamente e sem nenhuma forma de resistência" },
      { id: "B", text: "Através de fugas, revoltas, formação de quilombos e preservação de aspectos de sua cultura" },
      { id: "C", text: "Apenas obedecendo completamente aos colonizadores" },
      { id: "D", text: "Não houve absolutamente nenhuma forma de resistência" },
    ],
    correctAnswer: "B",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "O que eram os quilombos, formados principalmente por pessoas que fugiam da escravidão?",
    tip: "Pensa num lugar onde pessoas que fugiam da escravidão podiam viver livres e em comunidade!",
    funFact: "Existiram centenas de quilombos em diferentes regiões do Brasil durante o período colonial!",
    points: 1,
    options: [
      { id: "A", text: "Comunidades organizadas por pessoas escravizadas fugidas, que buscavam liberdade e preservavam suas culturas" },
      { id: "B", text: "Fortalezas construídas pela Coroa portuguesa" },
      { id: "C", text: "Escolas religiosas no litoral" },
      { id: "D", text: "Áreas exclusivas de produção de açúcar" },
    ],
    correctAnswer: "A",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "Qual é um dos quilombos mais conhecidos da história brasileira, localizado principalmente no atual estado de Alagoas?",
    tip: "Esse quilombo é um dos mais estudados nas escolas — pensa no nome mais famoso!",
    funFact: "O Quilombo dos Palmares chegou a reunir milhares de pessoas e resistiu por quase 100 anos!",
    points: 1,
    options: [
      { id: "A", text: "Quilombo de Salvador" },
      { id: "B", text: "Quilombo de Brasília" },
      { id: "C", text: "Quilombo dos Palmares" },
      { id: "D", text: "Quilombo do Rio de Janeiro" },
    ],
    correctAnswer: "C",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "Zumbi dos Palmares é uma figura histórica lembrada por:",
    tip: "Lembra da questão 8 deste simulado sobre o Quilombo dos Palmares!",
    funFact: "O dia 20 de novembro, data da morte de Zumbi, é hoje celebrado como o Dia Nacional de Consciência Negra!",
    points: 1,
    options: [
      { id: "A", text: "Ter sido um governador português" },
      { id: "B", text: "Ter apoiado integralmente a escravidão" },
      { id: "C", text: "Ter fundado uma capitania hereditária" },
      { id: "D", text: "Ter liderado a resistência do Quilombo dos Palmares contra tentativas de destruição desse espaço de liberdade" },
    ],
    correctAnswer: "D",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "Por que estudar a história da escravidão indígena e africana é importante para compreender a sociedade brasileira atual?",
    tip: "Pensa: a história da escravidão tem efeitos até hoje na sociedade brasileira, ou desapareceu completamente?",
    funFact: "Muitas tradições culturais brasileiras — na música, na culinária e na religião — têm raízes nas culturas indígenas e africanas preservadas mesmo durante a escravidão!",
    points: 1,
    options: [
      { id: "A", text: "Porque essa história não tem nenhuma relação com o presente" },
      { id: "B", text: "Porque ajuda a entender desigualdades históricas e a valorizar as contribuições culturais desses povos à formação do Brasil" },
      { id: "C", text: "Porque a escravidão não deixou nenhuma marca na sociedade" },
      { id: "D", text: "Porque esse tema só interessa a especialistas, nunca a estudantes" },
    ],
    correctAnswer: "B",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Comparando a escravização indígena e a escravização africana no Brasil colonial, qual foi um fator que contribuiu para a substituição gradual da mão de obra indígena pela africana?",
    tip: "Lembra da questão 2 deste simulado sobre os motivos dessa substituição!",
    funFact: "Esse processo histórico envolveu, infelizmente, interesses econômicos cruéis que ignoravam a dignidade humana dos dois grupos!",
    points: 1,
    options: [
      { id: "A", text: "A resistência indígena, as doenças trazidas pelos europeus e interesses econômicos ligados ao tráfico negreiro" },
      { id: "B", text: "Os indígenas pediram para serem substituídos" },
      { id: "C", text: "Não existia nenhuma diferença entre as duas formas de escravização" },
      { id: "D", text: "A escravização africana era proibida pela Coroa" },
    ],
    correctAnswer: "A",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Se muitas pessoas escravizadas resistiam à escravidão através de fugas e formação de quilombos, o que isso demonstra sobre a relação entre escravizados e colonizadores?",
    tip: "Lembra da questão 6 e 7 deste simulado sobre as fugas e os quilombos!",
    funFact: "Essa luta por liberdade é hoje reconhecida como uma parte fundamental e inspiradora da história brasileira!",
    points: 1,
    options: [
      { id: "A", text: "Que os escravizados aceitavam totalmente sua condição, sem nenhuma resistência" },
      { id: "B", text: "Que não existia nenhum tipo de conflito entre os dois grupos" },
      { id: "C", text: "Que havia uma relação de intensa resistência e luta por liberdade por parte das pessoas escravizadas" },
      { id: "D", text: "Que os colonizadores nunca tentaram impedir as fugas" },
    ],
    correctAnswer: "C",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "Por que o Quilombo dos Palmares é tão importante na história da resistência à escravidão no Brasil?",
    tip: "Lembra da questão 8 deste simulado sobre o tamanho e a duração desse quilombo!",
    funFact: "Palmares resistiu a diversas expedições enviadas para destruí-lo antes de finalmente ser derrotado em 1694!",
    points: 1,
    options: [
      { id: "A", text: "Porque nunca existiu de fato" },
      { id: "B", text: "Porque foi fundado pela própria Coroa portuguesa" },
      { id: "C", text: "Porque não teve nenhuma relação com pessoas escravizadas" },
      { id: "D", text: "Porque se tornou um dos maiores e mais duradouros espaços de liberdade organizados por pessoas fugidas da escravidão" },
    ],
    correctAnswer: "D",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "Comparando a vida em um quilombo com a vida sob escravidão nos engenhos, qual era uma diferença fundamental?",
    tip: "Pensa: num quilombo, as pessoas eram livres ou continuavam escravizadas como nos engenhos?",
    funFact: "Dentro dos quilombos, as pessoas podiam organizar sua própria forma de viver, cultivar a terra e preservar tradições culturais!",
    points: 1,
    options: [
      { id: "A", text: "No quilombo, as pessoas buscavam viver livres, organizando sua própria comunidade; nos engenhos, viviam sob trabalho forçado" },
      { id: "B", text: "As duas situações eram exatamente iguais" },
      { id: "C", text: "Nos quilombos, as pessoas também eram escravizadas pelos próprios quilombolas" },
      { id: "D", text: "Não existia nenhuma diferença de liberdade entre as duas situações" },
    ],
    correctAnswer: "A",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Por que a figura de Zumbi dos Palmares é lembrada até hoje como um símbolo de resistência?",
    tip: "Lembra da questão 9 deste simulado sobre o papel de Zumbi!",
    funFact: "Zumbi dos Palmares é hoje um dos nomes mais importantes quando se fala em luta por liberdade e igualdade no Brasil!",
    points: 1,
    options: [
      { id: "A", text: "Porque ele apoiava a escravidão" },
      { id: "B", text: "Porque ele liderou a defesa do Quilombo dos Palmares contra ataques que buscavam destruir aquele espaço de liberdade" },
      { id: "C", text: "Porque ele nunca existiu de fato" },
      { id: "D", text: "Porque ele foi um governador português" },
    ],
    correctAnswer: "B",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "Se o tráfico negreiro trazia forçadamente pessoas da África para serem escravizadas nas colônias, que tipo de violação de direitos isso representa, mesmo analisando pelos critérios da própria época?",
    tip: "Lembra da questão 3 e 5 deste simulado sobre o tráfico negreiro e a escravidão!",
    funFact: "Reconhecer essa gravidade histórica é importante para entender por que a escravidão é tão condenada nos dias de hoje!",
    points: 1,
    options: [
      { id: "A", text: "Nenhuma violação, pois era uma prática comum" },
      { id: "B", text: "Apenas uma questão econômica, sem nenhum sofrimento humano envolvido" },
      { id: "C", text: "Uma grave violação da liberdade e da dignidade das pessoas escravizadas" },
      { id: "D", text: "Uma forma de ajuda às pessoas trazidas da África" },
    ],
    correctAnswer: "C",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "Comparando o uso de mão de obra escravizada nos engenhos de açúcar com seu uso posterior na mineração, o que se mantém como característica central da escravidão em ambos os casos?",
    tip: "Pensa: tanto no açúcar quanto no ouro, quem fazia o trabalho mais pesado, de forma forçada?",
    funFact: "A escravidão acompanhou praticamente todos os principais \"ciclos\" econômicos do Brasil colonial, do açúcar ao ouro!",
    points: 1,
    options: [
      { id: "A", text: "A ausência completa de qualquer trabalho forçado" },
      { id: "B", text: "A escravidão deixava de existir quando mudava a atividade econômica" },
      { id: "C", text: "A escravidão só existia na mineração, nunca nos engenhos" },
      { id: "D", text: "A exploração do trabalho forçado de pessoas escravizadas, independentemente da atividade econômica" },
    ],
    correctAnswer: "D",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "Por que é importante reconhecer as diferentes formas de resistência das pessoas escravizadas, e não apenas os aspectos de sofrimento e exploração?",
    tip: "Pensa: reconhecer a luta e a resistência tira o valor da história, ou mostra força e coragem dessas pessoas?",
    funFact: "Hoje, muitos historiadores buscam contar essa história destacando tanto o sofrimento quanto a força e a resistência dos povos escravizados!",
    points: 1,
    options: [
      { id: "A", text: "Porque a resistência nunca existiu de fato" },
      { id: "B", text: "Porque reconhecer a resistência ajuda a valorizar a luta por liberdade e a agência histórica dessas pessoas, além do sofrimento imposto a elas" },
      { id: "C", text: "Porque a resistência não tem nenhuma importância histórica" },
      { id: "D", text: "Porque isso diminui a gravidade da escravidão" },
    ],
    correctAnswer: "B",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "Comparando a escravidão no Brasil colonial com os valores de direitos humanos reconhecidos atualmente, qual conclusão é mais adequada?",
    tip: "Lembra da questão 5 e 16 deste simulado sobre a gravidade da escravidão!",
    funFact: "A Declaração Universal dos Direitos Humanos, de 1948, afirma claramente que nenhuma pessoa deve ser escravizada!",
    points: 1,
    options: [
      { id: "A", text: "A escravidão é hoje reconhecida como uma grave violação de direitos humanos, incompatível com a dignidade da pessoa humana" },
      { id: "B", text: "A escravidão era considerada aceitável segundo os direitos humanos atuais" },
      { id: "C", text: "Não existe nenhuma diferença entre os valores da época colonial e os atuais sobre esse tema" },
      { id: "D", text: "Os direitos humanos atuais não têm nenhuma relação com a análise histórica da escravidão" },
    ],
    correctAnswer: "A",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "Por que a história da escravidão indígena e africana deve ser estudada também a partir da perspectiva de resistência e contribuição cultural desses povos, e não apenas como sofrimento?",
    tip: "Lembra da questão 10 e 18 deste simulado sobre a importância de reconhecer esses dois aspectos juntos!",
    funFact: "Capoeira, samba e muitas religiões afro-brasileiras nasceram justamente dessa mistura de resistência e preservação cultural!",
    points: 1,
    options: [
      { id: "A", text: "Porque não houve nenhuma contribuição cultural desses povos" },
      { id: "B", text: "Porque o sofrimento é o único aspecto relevante dessa história" },
      { id: "C", text: "Porque isso ajuda a reconhecer tanto as injustiças históricas quanto as imensas contribuições culturais, sociais e de resistência desses povos à formação do Brasil" },
      { id: "D", text: "Porque esse tema não deve ser estudado nas escolas" },
    ],
    correctAnswer: "C",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Bernardo está estudando sobre a escravidão no Brasil colonial e descobre que, com o tempo, a mão de obra africana foi substituindo gradualmente a indígena. Qual explicação ele deve dar sobre esse processo?",
    tip: "Lembra da questão 2 e 11 deste simulado sobre essa substituição!",
    funFact: "Esse processo histórico mostra como interesses econômicos, de forma muito cruel, influenciaram decisões que afetaram milhões de vidas!",
    points: 1,
    options: [
      { id: "A", text: "Os indígenas pediram para serem substituídos" },
      { id: "B", text: "Fatores como resistência indígena, doenças trazidas pelos europeus e interesses do tráfico negreiro contribuíram para essa mudança" },
      { id: "C", text: "A escravização africana era proibida pela Coroa" },
      { id: "D", text: "Não existia nenhuma diferença entre as duas formas de escravização" },
    ],
    correctAnswer: "B",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Na aula de História, Bernardo aprende sobre os quilombos e sua importância como espaços de resistência. Qual explicação ele deve dar sobre o que eram os quilombos?",
    tip: "Lembra da questão 7 e 12 deste simulado sobre o que eram os quilombos!",
    funFact: "Muitas comunidades quilombolas existem até hoje no Brasil, mantendo viva a memória e a cultura de seus antepassados!",
    points: 1,
    options: [
      { id: "A", text: "Fortalezas construídas pela própria Coroa portuguesa" },
      { id: "B", text: "Escolas religiosas no litoral" },
      { id: "C", text: "Áreas exclusivas de produção de açúcar" },
      { id: "D", text: "Comunidades organizadas por pessoas fugidas da escravidão, que buscavam liberdade e preservavam suas culturas" },
    ],
    correctAnswer: "D",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Bernardo pesquisa sobre o Quilombo dos Palmares e descobre que ele resistiu por muitos anos contra tentativas de destruição. O que isso demonstra sobre esse quilombo?",
    tip: "Lembra da questão 8 e 13 deste simulado sobre a importância do Quilombo dos Palmares!",
    funFact: "Estudos arqueológicos ainda hoje buscam entender melhor como era a vida cotidiana dentro de Palmares!",
    points: 1,
    options: [
      { id: "A", text: "Que ele foi um dos maiores e mais duradouros espaços de resistência e liberdade organizados por pessoas escravizadas fugidas" },
      { id: "B", text: "Que ele nunca existiu de fato" },
      { id: "C", text: "Que ele foi fundado pela própria Coroa portuguesa" },
      { id: "D", text: "Que ele não teve nenhuma relação com a escravidão" },
    ],
    correctAnswer: "A",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Durante um trabalho escolar sobre Zumbi dos Palmares, Bernardo precisa explicar por que essa figura histórica é lembrada até hoje. Qual é a explicação correta?",
    tip: "Lembra da questão 9 e 15 deste simulado sobre a importância de Zumbi dos Palmares!",
    funFact: "Existem hoje praças, escolas e até prêmios no Brasil que levam o nome de Zumbi, em sua homenagem!",
    points: 1,
    options: [
      { id: "A", text: "Porque ele apoiava a escravidão" },
      { id: "B", text: "Porque ele liderou a defesa do Quilombo dos Palmares, tornando-se um símbolo de resistência e luta por liberdade" },
      { id: "C", text: "Porque ele nunca existiu de fato" },
      { id: "D", text: "Porque ele foi um governador português" },
    ],
    correctAnswer: "B",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Bernardo conversa com a professora sobre por que a escravidão é considerada, pelos valores atuais, uma grave violação de direitos. Qual explicação ele pode usar?",
    tip: "Lembra da questão 5 e 19 deste simulado sobre a gravidade da escravidão!",
    funFact: "Entender essa gravidade histórica ajuda a valorizar ainda mais as lutas por igualdade e direitos até hoje!",
    points: 1,
    options: [
      { id: "A", text: "Porque a escravidão não causava nenhum sofrimento" },
      { id: "B", text: "Porque era uma prática moderna e recente" },
      { id: "C", text: "Porque retirava a liberdade das pessoas, submetendo-as à força a trabalhos forçados e maus-tratos" },
      { id: "D", text: "Porque beneficiava igualmente todos os envolvidos" },
    ],
    correctAnswer: "C",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Bernardo organiza um resumo sobre as diferentes formas de resistência das pessoas escravizadas durante o período colonial. Qual frase resume corretamente essas formas de resistência?",
    tip: "Lembra da questão 6 e 12 deste simulado sobre as formas de resistência!",
    funFact: "Mesmo em condições extremamente difíceis, essas formas de resistência mostram a força e a coragem dessas pessoas!",
    points: 1,
    options: [
      { id: "A", text: "As pessoas escravizadas nunca resistiram de nenhuma forma" },
      { id: "B", text: "A única forma de resistência era a aceitação total da escravidão" },
      { id: "C", text: "A resistência não existiu, pois a escravidão era aceita por todos" },
      { id: "D", text: "As pessoas escravizadas resistiram através de fugas, revoltas, formação de quilombos e preservação de sua cultura" },
    ],
    correctAnswer: "D",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Na prova, Bernardo precisa explicar a diferença entre a vida em um quilombo e a vida sob escravidão nos engenhos. Qual é a resposta correta?",
    tip: "Lembra da questão 14 deste simulado sobre essa diferença entre quilombo e engenho!",
    funFact: "Essa busca por liberdade nos quilombos é considerada, por muitos historiadores, um dos primeiros grandes movimentos de resistência da história do Brasil!",
    points: 1,
    options: [
      { id: "A", text: "No quilombo, buscava-se viver em liberdade e organizar uma comunidade própria; nos engenhos, as pessoas viviam sob trabalho forçado" },
      { id: "B", text: "As duas situações eram exatamente iguais" },
      { id: "C", text: "Nos quilombos, as pessoas também eram escravizadas pelos próprios quilombolas" },
      { id: "D", text: "Não existia diferença alguma de liberdade entre essas duas situações" },
    ],
    correctAnswer: "A",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Bernardo quer explicar por que é importante reconhecer tanto o sofrimento causado pela escravidão quanto a resistência e as contribuições culturais dos povos escravizados. Qual explicação ele deve usar?",
    tip: "Lembra da questão 18 e 20 deste simulado sobre a importância de reconhecer esses dois aspectos juntos!",
    funFact: "Essa forma mais completa de contar a história é cada vez mais valorizada nas escolas brasileiras atualmente!",
    points: 1,
    options: [
      { id: "A", text: "Porque apenas o sofrimento deve ser estudado" },
      { id: "B", text: "Porque não houve nenhuma contribuição cultural desses povos" },
      { id: "C", text: "Porque reconhecer ambos os aspectos ajuda a entender de forma mais completa e justa a história e a formação cultural do Brasil" },
      { id: "D", text: "Porque esse tema não deve ser discutido na escola" },
    ],
    correctAnswer: "C",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Para seu resumo final sobre o tema, Bernardo escreve: \"A escravidão indígena e africana foi uma grave injustiça histórica, mas também existiram intensas formas de resistência e luta por liberdade.\" Essa afirmação está:",
    tip: "Pensa em tudo que você revisou neste simulado sobre sofrimento e resistência!",
    funFact: "Esse equilíbrio entre reconhecer o sofrimento e valorizar a resistência é um dos grandes aprendizados do estudo desse período da história!",
    points: 1,
    options: [
      { id: "A", text: "Errada, não existiu nenhuma forma de resistência durante a escravidão" },
      { id: "B", text: "Correta, pois a escravidão causou grande sofrimento, mas também gerou fugas, quilombos e revoltas como formas de resistência" },
      { id: "C", text: "Errada, a escravidão nunca existiu no Brasil colonial" },
      { id: "D", text: "Errada, apenas os colonizadores tiveram participação ativa nesse período histórico" },
    ],
    correctAnswer: "B",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Bernardo conclui seu caderno de estudos destacando que \"conhecer a história da escravidão e da resistência dos povos indígenas e africanos é essencial para entender a formação social e cultural do Brasil.\" Essa conclusão está:",
    tip: "Pensa em tudo que você revisou neste simulado sobre a importância dessa história para entender o Brasil de hoje!",
    funFact: "A cultura brasileira, com suas músicas, danças, religiões e sabores, é profundamente marcada pela herança indígena e africana!",
    points: 1,
    options: [
      { id: "A", text: "Errada, essa história não tem relação com a formação do Brasil" },
      { id: "B", text: "Errada, apenas a história europeia é relevante para entender o Brasil" },
      { id: "C", text: "Errada, a escravidão não deixou nenhuma marca na sociedade atual" },
      { id: "D", text: "Correta, pois essa história explica tanto desigualdades históricas quanto as grandes contribuições culturais desses povos à identidade brasileira" },
    ],
    correctAnswer: "D",
  },
];
