export const questoesSociologia1EmB1Av1 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'A Sociologia é uma ciência que tem como objeto de estudo principal:',
    tip: 'Pense em qual é a diferença entre a Psicologia, que estuda o indivíduo, e a Sociologia.',
    funFact: 'Você sabia? A palavra "Sociologia" foi inventada por Auguste Comte em 1838, unindo o latim "socius" (companheiro) com o grego "logos" (estudo). É uma das únicas ciências com nome "híbrido"!',
    points: 1,
    options: [
      { id: 'A', text: 'O comportamento individual e os processos mentais do ser humano' },
      { id: 'B', text: 'A economia de mercado e as relações de troca entre países' },
      { id: 'C', text: 'A sociedade humana, os grupos sociais e as relações entre os indivíduos' },
      { id: 'D', text: 'Os fenômenos naturais e sua influência sobre as populações' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'O surgimento da Sociologia como ciência está diretamente ligado a dois grandes eventos do século XVIII e XIX. Quais são eles?',
    tip: 'Um evento transformou a economia e o trabalho; o outro transformou a política e os direitos.',
    funFact: 'Você sabia? Antes da Sociologia existir como ciência, questões sobre a sociedade eram estudadas pela Filosofia. Foi só com as grandes transformações do século XIX que surgiu a necessidade de uma ciência específica para a sociedade!',
    points: 1,
    options: [
      { id: 'A', text: 'A Revolução Industrial e a Revolução Francesa' },
      { id: 'B', text: 'A Revolução Americana e a independência das colônias africanas' },
      { id: 'C', text: 'A Primeira Guerra Mundial e a Revolução Russa' },
      { id: 'D', text: 'O Renascimento Cultural e a Reforma Protestante' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'A Revolução Industrial, iniciada na Inglaterra no século XVIII, provocou profundas transformações sociais. Qual das alternativas melhor descreve uma dessas consequências?',
    tip: 'Pense no que aconteceu com os trabalhadores rurais que migraram para as cidades em busca de emprego nas fábricas.',
    funFact: 'Você sabia? Na Inglaterra do século XIX, crianças de 5 anos trabalhavam nas fábricas por até 16 horas por dia! Foram essas condições desumanas que motivaram os primeiros sociólogos a estudar as desigualdades sociais.',
    points: 1,
    options: [
      { id: 'A', text: 'Reduziu as desigualdades sociais ao criar mais empregos para todos' },
      { id: 'B', text: 'Fortaleceu o poder da aristocracia rural sobre os trabalhadores' },
      { id: 'C', text: 'Melhorou imediatamente as condições de vida da população europeia' },
      { id: 'D', text: 'Gerou novas classes sociais (burguesia industrial e proletariado) e intensas desigualdades sociais' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'A Revolução Francesa de 1789 influenciou o surgimento da Sociologia ao trazer novos questionamentos sobre a sociedade. Qual foi o principal impacto desse evento?',
    tip: 'A Revolução Francesa derrubou a ordem social antiga — isso gerou a necessidade de entender como construir uma nova ordem.',
    funFact: 'Você sabia? O lema da Revolução Francesa — "Liberdade, Igualdade e Fraternidade" — ainda é o lema oficial da França hoje, mais de 230 anos depois!',
    points: 1,
    options: [
      { id: 'A', text: 'Consolidou o poder absoluto dos reis e da Igreja Católica' },
      { id: 'B', text: 'Questionou a ordem social baseada no nascimento e gerou debate sobre como organizar a sociedade racionalmente' },
      { id: 'C', text: 'Eliminou completamente as desigualdades sociais na Europa' },
      { id: 'D', text: 'Fortaleceu o feudalismo e os privilégios da nobreza' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'Auguste Comte é considerado o "pai da Sociologia" e fundador de uma corrente filosófica que acredita que só o conhecimento baseado em fatos observáveis é válido. Essa corrente é chamada de:',
    tip: 'O próprio nome dessa corrente indica que o conhecimento deve ser "positivo", ou seja, baseado em fatos concretos.',
    funFact: 'Você sabia? Auguste Comte queria que a Sociologia fosse a "rainha das ciências" — a mais importante de todas, responsável por reorganizar a sociedade com base na razão e na ciência!',
    points: 1,
    options: [
      { id: 'A', text: 'Marxismo' },
      { id: 'B', text: 'Relativismo' },
      { id: 'C', text: 'Positivismo' },
      { id: 'D', text: 'Funcionalismo' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'Segundo Auguste Comte, a humanidade passa por três estágios de desenvolvimento do pensamento. Quais são eles, em ordem cronológica?',
    tip: 'Lembre-se: Comte propôs que o pensamento humano evoluiu do mais primitivo (sobrenatural) ao mais avançado (científico).',
    funFact: 'Você sabia? A bandeira do Brasil tem o lema "Ordem e Progresso", que foi retirado diretamente da filosofia positivista de Auguste Comte! Os militares que proclamaram a República em 1889 eram grandes admiradores do positivismo.',
    points: 1,
    options: [
      { id: 'A', text: 'Estado teológico, estado metafísico e estado positivo (científico)' },
      { id: 'B', text: 'Estado primitivo, estado civilizado e estado desenvolvido' },
      { id: 'C', text: 'Estado feudal, estado capitalista e estado socialista' },
      { id: 'D', text: 'Estado natural, estado racional e estado espiritual' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'O lema "Ordem e Progresso" na bandeira do Brasil foi inspirado na filosofia de Auguste Comte. Para Comte, qual era a relação entre ordem e progresso?',
    tip: 'Para Comte, a sociedade precisava de estabilidade (ordem) para avançar (progresso) — um não existia sem o outro.',
    funFact: 'Você sabia? Benjamin Constant, um dos líderes da proclamação da República no Brasil, era professor de Positivismo e militante dessa filosofia. Por isso o positivismo deixou sua marca na bandeira brasileira!',
    points: 1,
    options: [
      { id: 'A', text: 'A ordem deveria ser destruída para que o progresso ocorresse livremente' },
      { id: 'B', text: 'O progresso era inimigo da ordem, e por isso a sociedade deveria escolher um deles' },
      { id: 'C', text: 'A ordem e o progresso eram conceitos independentes, sem relação entre si' },
      { id: 'D', text: 'O progresso só seria possível com a manutenção da ordem social; eram complementares' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'Émile Durkheim é um dos pais da Sociologia científica. Qual era o objeto de estudo central da Sociologia para Durkheim?',
    tip: 'Durkheim queria estudar algo que existisse fora e acima dos indivíduos — algo que a própria sociedade criasse.',
    funFact: 'Você sabia? Durkheim foi o primeiro professor universitário de Sociologia da França, em 1887. Antes disso, a Sociologia nem era reconhecida como disciplina acadêmica séria!',
    points: 1,
    options: [
      { id: 'A', text: 'As motivações psicológicas individuais de cada pessoa' },
      { id: 'B', text: 'Os fatos sociais — fenômenos coletivos que exercem pressão sobre os indivíduos' },
      { id: 'C', text: 'A economia e as relações de produção entre as classes' },
      { id: 'D', text: 'A biologia humana e sua influência sobre o comportamento social' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'Para Durkheim, os fatos sociais têm características que os tornam diferentes dos fenômenos individuais. Qual das características abaixo é própria dos fatos sociais?',
    tip: 'Um fato social existe antes de você nascer, influencia seu comportamento e você pode ser punido se o ignorar — isso é coercitividade.',
    funFact: 'Você sabia? Para Durkheim, até a língua que falamos é um fato social: ela existia antes de nós, nos é imposta desde a infância e seria praticamente impossível não aprendê-la vivendo em sociedade!',
    points: 1,
    options: [
      { id: 'A', text: 'São individuais, privados e dependem da vontade de cada pessoa' },
      { id: 'B', text: 'São criados conscientemente por cada indivíduo para satisfazer suas necessidades' },
      { id: 'C', text: 'São coercitivos, exteriores ao indivíduo e generalizados na sociedade' },
      { id: 'D', text: 'São exclusivamente econômicos e relacionados ao mercado de trabalho' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'Durkheim identificou dois tipos de solidariedade social em sua obra "A Divisão do Trabalho Social". Qual tipo de solidariedade é característico de sociedades tradicionais, onde as pessoas se assemelham e partilham os mesmos valores?',
    tip: 'Em sociedades pequenas e tradicionais, as pessoas se unem porque são parecidas — mesma religião, mesmas tradições, mesmo trabalho.',
    funFact: 'Você sabia? Durkheim escreveu "A Divisão do Trabalho Social" em 1893, quando tinha apenas 35 anos! A obra foi sua tese de doutorado e já era considerada revolucionária na época.',
    points: 1,
    options: [
      { id: 'A', text: 'Solidariedade mecânica — baseada na semelhança e na consciência coletiva forte' },
      { id: 'B', text: 'Solidariedade orgânica — baseada na interdependência das funções especializadas' },
      { id: 'C', text: 'Solidariedade anômica — baseada na ausência de normas sociais claras' },
      { id: 'D', text: 'Solidariedade positivista — baseada na ciência e na razão' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'Na sociedade moderna e industrializada, com divisão do trabalho especializada, Durkheim identificou um tipo diferente de coesão social. Esse tipo é chamado de:',
    tip: 'Nas sociedades modernas, as pessoas se unem não por serem iguais, mas por serem DIFERENTES e precisarem umas das outras — como os órgãos de um corpo.',
    funFact: 'Você sabia? Durkheim usou a metáfora biológica propositalmente: nas sociedades modernas, cada pessoa tem uma função especializada, como os órgãos de um corpo. Por isso chamou de solidariedade "orgânica"!',
    points: 1,
    options: [
      { id: 'A', text: 'Solidariedade mecânica — baseada na repetição e na tradição' },
      { id: 'B', text: 'Solidariedade orgânica — baseada na interdependência gerada pela divisão do trabalho especializada' },
      { id: 'C', text: 'Solidariedade anômica — baseada no enfraquecimento das normas coletivas' },
      { id: 'D', text: 'Solidariedade positivista — baseada na aplicação do método científico' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'O conceito de "anomia", desenvolvido por Durkheim, refere-se a:',
    tip: 'A palavra vem do grego "a-nomos" — "sem normas". O que acontece com uma sociedade quando suas normas coletivas enfraquecem?',
    funFact: 'Você sabia? Durkheim aplicou o conceito de anomia para explicar o aumento do número de suicídios na Europa industrializada do século XIX. Ele mostrou que o suicídio, algo aparentemente individual, era também influenciado por fatores sociais!',
    points: 1,
    options: [
      { id: 'A', text: 'Um estado de harmonia social em que todos seguem as mesmas normas' },
      { id: 'B', text: 'A solidariedade presente nas sociedades primitivas baseada em laços familiares' },
      { id: 'C', text: 'A hierarquia rígida de normas presente nas sociedades industrializadas' },
      { id: 'D', text: 'Um estado de ausência ou enfraquecimento das normas sociais, gerando desordem e desorientação' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'Em sua obra "O Suicídio" (1897), Durkheim demonstrou algo revolucionário para a época. O que ele provou com esse estudo?',
    tip: 'Suicídio parece ser uma decisão totalmente individual e privada. Mas Durkheim mostrou que há padrões coletivos nesse fenômeno.',
    funFact: 'Você sabia? O estudo do suicídio de Durkheim é considerado o primeiro exemplo de pesquisa sociológica empírica moderna. Ele analisou estatísticas de suicídio de vários países europeus e encontrou padrões sociais sistemáticos!',
    points: 1,
    options: [
      { id: 'A', text: 'O suicídio é um ato puramente individual e não pode ser estudado pela Sociologia' },
      { id: 'B', text: 'O suicídio é causado exclusivamente por doenças mentais individuais' },
      { id: 'C', text: 'O suicídio, mesmo sendo individual, é influenciado por fatores sociais (integração e regulação social) e pode ser estudado como fato social' },
      { id: 'D', text: 'O suicídio ocorre apenas em sociedades modernas e industrializadas' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'Auguste Comte propunha uma hierarquia das ciências, em que cada ciência dependia das anteriores. Qual era a ciência que Comte colocava no topo dessa hierarquia?',
    tip: 'Para Comte, a ciência mais complexa, que estuda o objeto mais complexo (a sociedade humana), seria a mais importante.',
    funFact: 'Você sabia? Comte chamou inicialmente a Sociologia de "Física Social", comparando-a com a física — que estuda as leis da natureza — mas aplicada à sociedade. Só depois ele criou o termo "Sociologia".',
    points: 1,
    options: [
      { id: 'A', text: 'A Sociologia, por ser a mais complexa e estudar o objeto mais elaborado da natureza' },
      { id: 'B', text: 'A Física, por ser a mais exata e rigorosa das ciências' },
      { id: 'C', text: 'A Matemática, por ser a base de todas as outras ciências' },
      { id: 'D', text: 'A Biologia, por estudar os seres vivos, incluindo os humanos' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'Qual das alternativas abaixo apresenta uma definição correta de Sociologia?',
    tip: 'A Sociologia é uma ciência — portanto usa métodos científicos para estudar um objeto específico: a sociedade.',
    funFact: 'Você sabia? A Sociologia foi incluída como disciplina obrigatória no Ensino Médio brasileiro apenas em 2008, com a Lei nº 11.684. Antes disso, ela ficou fora das escolas por quase 40 anos!',
    points: 1,
    options: [
      { id: 'A', text: 'Ciência que estuda os seres vivos e sua evolução ao longo do tempo' },
      { id: 'B', text: 'Ciência que investiga a sociedade, os grupos sociais, as instituições e as relações humanas coletivas' },
      { id: 'C', text: 'Disciplina filosófica que reflete sobre questões morais e éticas individuais' },
      { id: 'D', text: 'Ciência que analisa os fenômenos econômicos e as leis do mercado' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'Para Durkheim, um fato social deve ser tratado "como coisa". O que ele queria dizer com isso?',
    tip: 'Durkheim queria que a Sociologia fosse tão científica quanto a Física ou a Química — estudando fatos observáveis, não opiniões.',
    funFact: 'Você sabia? A frase "tratar os fatos sociais como coisas" foi muito polêmica na época de Durkheim. Muitos filósofos achavam impossível estudar a sociedade com o mesmo rigor das ciências naturais!',
    points: 1,
    options: [
      { id: 'A', text: 'A sociedade é formada apenas por objetos materiais e não por relações entre pessoas' },
      { id: 'B', text: 'Os fatos sociais são criados pelas indústrias e empresas capitalistas' },
      { id: 'C', text: 'Os fatos sociais são objetos de consumo que as pessoas compram e vendem' },
      { id: 'D', text: 'Os fatos sociais devem ser estudados de forma objetiva e científica, sem preconceitos ou senso comum' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'A consciência coletiva, conceito central em Durkheim, pode ser definida como:',
    tip: 'A consciência coletiva é diferente da soma de consciências individuais — ela é algo que pertence ao grupo como um todo.',
    funFact: 'Você sabia? Durkheim afirmava que a religião era a forma mais primitiva de consciência coletiva — ela une as pessoas em torno de crenças e rituais compartilhados, criando um "nós" coletivo.',
    points: 1,
    options: [
      { id: 'A', text: 'A soma de todas as opiniões individuais dos membros de uma sociedade' },
      { id: 'B', text: 'A consciência que cada indivíduo tem de si mesmo e de seus desejos' },
      { id: 'C', text: 'O conjunto de crenças, valores e sentimentos comuns a uma sociedade, que transcende os indivíduos' },
      { id: 'D', text: 'A capacidade de cada pessoa de pensar racionalmente e tomar decisões' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'O positivismo de Comte defendia que a sociedade poderia ser reorganizada com base em qual princípio?',
    tip: 'Para Comte, a religião e a metafísica eram formas ultrapassadas de explicar o mundo — o que deveria guiar a sociedade era o conhecimento científico.',
    funFact: 'Você sabia? Comte chegou a fundar uma "Religião da Humanidade", substituindo Deus pela Humanidade como objeto de adoração. Muitos de seus seguidores no Brasil construíram templos positivistas — o mais famoso ainda existe em Porto Alegre!',
    points: 1,
    options: [
      { id: 'A', text: 'Na ciência e na razão, aplicando o método científico para organizar e reformar a sociedade' },
      { id: 'B', text: 'Na tradição religiosa, mantendo os valores medievais cristãos' },
      { id: 'C', text: 'Na luta de classes, transformando a sociedade pela revolução dos trabalhadores' },
      { id: 'D', text: 'Na liberdade individual absoluta, sem interferência do Estado' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'Em qual dos seguintes contextos a anomia, segundo Durkheim, tende a surgir com maior frequência?',
    tip: 'A anomia ocorre quando as normas sociais não conseguem mais regular o comportamento das pessoas — isso acontece em momentos de grande mudança.',
    funFact: 'Você sabia? Durkheim identificou que até em momentos de prosperidade econômica pode haver anomia — quando a riqueza cresce muito rápido, as pessoas perdem a noção do que é "suficiente" e ficam desorientadas!',
    points: 1,
    options: [
      { id: 'A', text: 'Em sociedades estáveis com normas claras e amplamente aceitas' },
      { id: 'B', text: 'Em períodos de crise ou rápida transformação social, quando as normas antigas perdem força' },
      { id: 'C', text: 'Em sociedades primitivas com forte solidariedade mecânica' },
      { id: 'D', text: 'Em comunidades religiosas com forte coesão em torno de crenças comuns' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'Segundo Durkheim, qual é a principal função da divisão do trabalho nas sociedades modernas?',
    tip: 'A divisão do trabalho não serve apenas para aumentar a produção econômica — ela também cria laços sociais de um tipo novo.',
    funFact: 'Você sabia? Durkheim discordou de Adam Smith, que via a divisão do trabalho apenas como meio de aumentar a produção. Para Durkheim, sua principal função era social: criar solidariedade entre pessoas com funções complementares!',
    points: 1,
    options: [
      { id: 'A', text: 'Aumentar a exploração dos trabalhadores pelas classes dominantes' },
      { id: 'B', text: 'Gerar conflito de classes e preparar a revolução social' },
      { id: 'C', text: 'Simplificar o trabalho para torná-lo mais eficiente economicamente' },
      { id: 'D', text: 'Criar solidariedade orgânica ao tornar os indivíduos interdependentes uns dos outros' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Em uma tribo indígena isolada em que todos cultivam a terra, compartilham as mesmas crenças religiosas e têm os mesmos valores, qual tipo de solidariedade durkheimiana predomina?',
    tip: 'Onde todos fazem as mesmas atividades e compartilham os mesmos valores, a coesão social vem da semelhança.',
    funFact: 'Você sabia? Durkheim estudou sociedades australianas para entender a solidariedade mecânica. Ele analisou os rituais totêmicos dessas tribos como forma primitiva de consciência coletiva!',
    points: 1,
    options: [
      { id: 'A', text: 'Solidariedade mecânica, pois há forte semelhança entre os membros e consciência coletiva intensa' },
      { id: 'B', text: 'Solidariedade orgânica, pois há divisão do trabalho especializada' },
      { id: 'C', text: 'Anomia, pois não há normas jurídicas escritas na tribo' },
      { id: 'D', text: 'Solidariedade positivista, pois a ciência guia as decisões do grupo' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Em uma cidade moderna em que médicos, engenheiros, professores e operários precisam uns dos outros para que a sociedade funcione, qual tipo de solidariedade durkheimiana predomina?',
    tip: 'Nas cidades modernas, as pessoas são diferentes entre si e se unem pela necessidade mútua — como peças de uma máquina.',
    funFact: 'Você sabia? Durkheim previu que, nas sociedades modernas, o direito civil e comercial (que regula contratos e cooperação) seria mais importante do que o direito penal (que pune transgressores) — exatamente o oposto das sociedades tradicionais!',
    points: 1,
    options: [
      { id: 'A', text: 'Solidariedade mecânica, pois todos os cidadãos têm os mesmos direitos na democracia' },
      { id: 'B', text: 'Anomia, pois há muitas profissões diferentes gerando confusão social' },
      { id: 'C', text: 'Solidariedade orgânica, pois a interdependência das funções especializadas une as pessoas' },
      { id: 'D', text: 'Solidariedade religiosa, pois a religião ainda une as pessoas nas cidades' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Qual é a principal característica que diferencia os fatos sociais dos atos puramente individuais, segundo Durkheim?',
    tip: 'O fato social vem de fora e de cima do indivíduo — ele não escolhe ter aquele comportamento, a sociedade o impõe.',
    funFact: 'Você sabia? Um exemplo claro de fato social é o modo de se cumprimentar: no Brasil damos beijo no rosto, no Japão fazem uma reverência, na França dão dois ou três beijos — ninguém inventou esses costumes, eles existiam antes de nós!',
    points: 1,
    options: [
      { id: 'A', text: 'Os fatos sociais são sempre conscientes e voluntários, ao contrário dos atos individuais' },
      { id: 'B', text: 'Os fatos sociais são exteriores ao indivíduo, exercem coerção sobre ele e são gerais na sociedade' },
      { id: 'C', text: 'Os fatos sociais são internos ao indivíduo e refletem apenas sua psicologia' },
      { id: 'D', text: 'Os fatos sociais são exclusivamente econômicos e mensuráveis em dinheiro' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Segundo Comte, no estado teológico do desenvolvimento humano, como as pessoas explicavam os fenômenos naturais?',
    tip: 'No estágio mais primitivo do pensamento, as pessoas buscavam explicações sobrenaturais para tudo que não conseguiam entender.',
    funFact: 'Você sabia? Para Comte, mesmo a física e a química passaram pelo estágio teológico antes de se tornarem ciências. Por exemplo, os alquimistas medievais buscavam forças mágicas para transformar metais em ouro!',
    points: 1,
    options: [
      { id: 'A', text: 'Por meio de experimentos científicos e observação sistemática dos fatos' },
      { id: 'B', text: 'Por meio de entidades abstratas e forças impessoais da natureza' },
      { id: 'C', text: 'Por meio de leis científicas descobertas pela razão humana' },
      { id: 'D', text: 'Por meio de deuses, espíritos e forças sobrenaturais' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'O suicídio altruísta, identificado por Durkheim em sua tipologia, ocorre quando:',
    tip: 'Nesse tipo de suicídio, o indivíduo se mata não por estar desligado da sociedade, mas por estar demasiadamente ligado a ela.',
    funFact: 'Você sabia? Durkheim citou os soldados japoneses (kamikazes) e os guerreiros de tribos como exemplos de suicídio altruísta — pessoas que se matam em nome de um valor coletivo maior que a própria vida!',
    points: 1,
    options: [
      { id: 'A', text: 'O indivíduo se mata porque está excessivamente integrado ao grupo, sacrificando-se por ele' },
      { id: 'B', text: 'O indivíduo se mata por estar completamente desvinculado da sociedade, sem laços sociais' },
      { id: 'C', text: 'O indivíduo se mata por não conseguir atingir objetivos ilimitados em uma sociedade anômica' },
      { id: 'D', text: 'O indivíduo se mata por depressão e doença mental individual' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'O suicídio egoísta, na tipologia de Durkheim, está associado a:',
    tip: 'O suicídio egoísta é o oposto do altruísta: enquanto no altruísta há integração demais, no egoísta há integração de menos.',
    funFact: 'Você sabia? Durkheim descobriu que protestantes tinham taxas de suicídio maiores que católicos — e explicou isso pela maior individualização do protestantismo, que encoraja a relação direta com Deus sem mediação comunitária!',
    points: 1,
    options: [
      { id: 'A', text: 'Excesso de integração social que leva o indivíduo a se sacrificar pelo grupo' },
      { id: 'B', text: 'Excesso de regulação social que impede o indivíduo de realizar seus objetivos' },
      { id: 'C', text: 'Fraca integração social, onde o indivíduo perde os laços com a comunidade e vive isolado' },
      { id: 'D', text: 'Ausência total de normas sociais em períodos de crise econômica' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'O método positivista proposto por Comte e aplicado por Durkheim à Sociologia defende que o conhecimento científico deve ser baseado em:',
    tip: 'O método positivista segue a mesma lógica das ciências naturais: observar, medir, comparar, formular leis.',
    funFact: 'Você sabia? A ideia de Durkheim de usar estatísticas para estudar o suicídio foi revolucionária — antes, ninguém imaginava que algo tão íntimo quanto a decisão de se matar pudesse ter padrões sociais mensuráveis!',
    points: 1,
    options: [
      { id: 'A', text: 'Tradição, senso comum e sabedoria popular transmitida pelas gerações' },
      { id: 'B', text: 'Observação dos fatos, dados empíricos e comprovação pela experiência' },
      { id: 'C', text: 'Especulação filosófica e reflexão abstrata sobre conceitos universais' },
      { id: 'D', text: 'Revelação divina e interpretação de textos sagrados' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Para Comte, o estado positivo (científico) é o terceiro e mais elevado estágio do pensamento humano. O que caracteriza esse estado?',
    tip: 'No estado positivo, as perguntas deixam de ser "por quê Deus fez assim?" e passam a ser "como isso funciona? que lei governa esse fenômeno?"',
    funFact: 'Você sabia? Comte acreditava que todas as sociedades passam pelos três estados, mas em ritmos diferentes. Por isso países como a França (mais industrializada) estariam mais avançados no estado positivo do que países agrários.',
    points: 1,
    options: [
      { id: 'A', text: 'A explicação dos fenômenos por meio de forças divinas e sobrenaturais' },
      { id: 'B', text: 'A explicação dos fenômenos por meio de entidades abstratas e forças impessoais' },
      { id: 'C', text: 'A total rejeição da ciência em favor da filosofia e da meditação' },
      { id: 'D', text: 'A explicação dos fenômenos por meio de leis científicas observáveis e verificáveis' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'A Revolução Francesa defendia três grandes princípios que influenciaram o pensamento sociológico posterior. Quais eram esses princípios?',
    tip: 'O lema da Revolução Francesa é uma das frases mais famosas da história política — três palavras que resumem seus ideais.',
    funFact: 'Você sabia? A Declaração dos Direitos do Homem e do Cidadão, aprovada em 1789 durante a Revolução Francesa, foi um dos primeiros documentos da história a afirmar direitos universais para todos os seres humanos.',
    points: 1,
    options: [
      { id: 'A', text: 'Liberdade, Igualdade e Fraternidade' },
      { id: 'B', text: 'Ordem, Progresso e Disciplina' },
      { id: 'C', text: 'Trabalho, Família e Pátria' },
      { id: 'D', text: 'Fé, Razão e Ciência' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'Por que a Sociologia surgiu como ciência no século XIX e não antes, como a Filosofia ou a Matemática?',
    tip: 'Para que uma ciência específica sobre a sociedade surgisse, era preciso que a sociedade passasse por transformações profundas que gerassem novos problemas sociais urgentes.',
    funFact: 'Você sabia? Antes da Sociologia, o estudo da sociedade era responsabilidade da Filosofia Política — de Platão a Rousseau, os filósofos discutiam como a sociedade deveria ser organizada. A Sociologia veio para estudar como ela realmente é!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque os gregos antigos não tinham interesse em estudar a sociedade' },
      { id: 'B', text: 'Porque a Igreja Católica proibiu o estudo da sociedade até o século XIX' },
      { id: 'C', text: 'Porque as transformações da Revolução Industrial e da Revolução Francesa criaram novos problemas sociais urgentes que exigiam compreensão científica' },
      { id: 'D', text: 'Porque a Sociologia só pode existir em sociedades democráticas, que surgiram no século XIX' },
    ],
    correctAnswer: 'C',
  },
];
