export const questoesPortugues7AnoB2Av1 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'O que é um "pronome"?',
    tip: 'Pensa em como, em vez de repetir "Maria" várias vezes, podemos usar "ela" — o que essa palavrinha está fazendo?',
    funFact: 'A palavra "pronome" vem do latim e significa, mais ou menos, "no lugar do nome"!',
    points: 1,
    options: [
      { id: 'A', text: 'Uma palavra que indica ação' },
      { id: 'B', text: 'Uma palavra que caracteriza um substantivo' },
      { id: 'C', text: 'Uma palavra que substitui ou acompanha um substantivo' },
      { id: 'D', text: 'Uma palavra que liga duas orações' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'Os "pronomes pessoais" têm a função de:',
    tip: 'Pensa em "eu", "tu", "ele" — essas palavras substituem os nomes de quem está envolvido na conversa.',
    funFact: 'Existem pronomes pessoais para cada uma das três "pessoas" da conversa: quem fala, com quem se fala e de quem se fala!',
    points: 1,
    options: [
      { id: 'A', text: 'Substituir o nome das pessoas do discurso (quem fala, com quem se fala, de quem se fala)' },
      { id: 'B', text: 'Indicar apenas quantidade' },
      { id: 'C', text: 'Substituir apenas verbos' },
      { id: 'D', text: 'Ligar duas frases' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'Qual das opções apresenta pronomes pessoais do caso reto?',
    tip: 'Pensa nos pronomes que geralmente aparecem no início da frase, fazendo o papel de sujeito.',
    funFact: 'Os pronomes do caso reto são os mais usados como sujeito de uma oração!',
    points: 1,
    options: [
      { id: 'A', text: 'Me, te, se, nos' },
      { id: 'B', text: 'Meu, teu, seu, nosso' },
      { id: 'C', text: 'Este, esse, aquele' },
      { id: 'D', text: 'Eu, tu, ele, nós' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'Qual das opções apresenta pronomes pessoais do caso oblíquo?',
    tip: 'Pensa em frases como "Ele me chamou" — qual palavra está no lugar de "chamou a mim"?',
    funFact: 'Os pronomes oblíquos costumam aparecer em frases como complemento do verbo, e não como sujeito!',
    points: 1,
    options: [
      { id: 'A', text: 'Eu, tu, ele, nós' },
      { id: 'B', text: 'Me, te, se, nos' },
      { id: 'C', text: 'Meu, teu, seu, nosso' },
      { id: 'D', text: 'Este, esse, aquele' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'Os "pronomes possessivos" indicam:',
    tip: 'Pensa em "meu caderno", "sua mochila" — o que essas palavras estão indicando sobre o objeto?',
    funFact: 'A palavra "possessivo" vem de "posse", que significa ter algo como seu!',
    points: 1,
    options: [
      { id: 'A', text: 'A localização de algo no espaço' },
      { id: 'B', text: 'Uma pergunta' },
      { id: 'C', text: 'Posse ou pertencimento de algo a alguém' },
      { id: 'D', text: 'Uma ação no passado' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'Qual das opções é um exemplo de pronome possessivo?',
    tip: 'Pensa em qual dessas palavras indica que algo pertence a alguém.',
    funFact: 'Os pronomes possessivos variam de acordo com a pessoa: meu, teu, seu, nosso, entre outros!',
    points: 1,
    options: [
      { id: 'A', text: 'Meu' },
      { id: 'B', text: 'Este' },
      { id: 'C', text: 'Quem' },
      { id: 'D', text: 'Ele' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'Os "pronomes demonstrativos" têm a função de:',
    tip: 'Pensa em "este", "esse" e "aquele" — eles ajudam a indicar se algo está perto ou longe de quem fala.',
    funFact: '"Este" indica algo perto de quem fala, "esse" indica algo perto de quem ouve, e "aquele" indica algo distante dos dois!',
    points: 1,
    options: [
      { id: 'A', text: 'Indicar posse' },
      { id: 'B', text: 'Substituir apenas verbos' },
      { id: 'C', text: 'Fazer perguntas' },
      { id: 'D', text: 'Indicar a posição de algo em relação às pessoas do discurso' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'Qual das opções é um exemplo de pronome demonstrativo?',
    tip: 'Pensa em qual dessas palavras indica a posição de algo, como "este livro aqui".',
    funFact: 'Os pronomes demonstrativos ajudam a "apontar" para algo dentro da frase, mesmo sem usar o dedo!',
    points: 1,
    options: [
      { id: 'A', text: 'Meu' },
      { id: 'B', text: 'Este' },
      { id: 'C', text: 'Nós' },
      { id: 'D', text: 'Qual' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: '"Você", "senhor" e "senhora" são exemplos de pronomes de:',
    tip: 'Pensa em como você se dirige a um adulto desconhecido, de forma educada — que tipo de pronome usamos nesse caso?',
    funFact: 'Alguns pronomes de tratamento, como "Vossa Excelência", são usados em situações muito formais, como discursos oficiais!',
    points: 1,
    options: [
      { id: 'A', text: 'Pronomes possessivos' },
      { id: 'B', text: 'Pronomes demonstrativos' },
      { id: 'C', text: 'Tratamento' },
      { id: 'D', text: 'Pronomes indefinidos' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'Usar pronomes em um texto é importante porque:',
    tip: 'Pensa em como ficaria estranho repetir sempre o mesmo nome em vez de usar "ele" ou "ela".',
    funFact: 'Um texto sem pronomes ficaria bem repetitivo e cansativo de ler!',
    points: 1,
    options: [
      { id: 'A', text: 'Ajuda a evitar repetições desnecessárias de palavras' },
      { id: 'B', text: 'Torna o texto mais confuso' },
      { id: 'C', text: 'Não tem nenhuma função no texto' },
      { id: 'D', text: 'Serve apenas para textos formais' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'Na frase "Maria pegou o livro dela", a palavra "dela" é um pronome:',
    tip: 'Lembra da Questão 5 — que tipo de pronome indica que o livro pertence a Maria?',
    funFact: '"Dela" é uma forma equivalente a "seu", mostrando posse de forma mais específica!',
    points: 1,
    options: [
      { id: 'A', text: 'Demonstrativo' },
      { id: 'B', text: 'Possessivo' },
      { id: 'C', text: 'Pessoal do caso reto' },
      { id: 'D', text: 'De tratamento' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'Na frase "Aquele carro é muito bonito", a palavra "aquele" é um pronome:',
    tip: 'Lembra da Questão 7 — que tipo de pronome indica a posição de algo, geralmente mais distante?',
    funFact: '"Aquele" indica que o carro está mais afastado tanto de quem fala quanto de quem ouve!',
    points: 1,
    options: [
      { id: 'A', text: 'Possessivo' },
      { id: 'B', text: 'Pessoal' },
      { id: 'C', text: 'De tratamento' },
      { id: 'D', text: 'Demonstrativo' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'Na frase "Nós vamos viajar amanhã", a palavra "nós" é um pronome pessoal do caso:',
    tip: 'Lembra da Questão 3 — em qual grupo de pronomes pessoais está a palavra "nós"?',
    funFact: '"Nós" é o pronome pessoal que representa a primeira pessoa do plural, incluindo quem fala e mais alguém!',
    points: 1,
    options: [
      { id: 'A', text: 'Reto' },
      { id: 'B', text: 'Oblíquo' },
      { id: 'C', text: 'Possessivo' },
      { id: 'D', text: 'Demonstrativo' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'Na frase "Ele me chamou para brincar", a palavra "me" é um pronome pessoal do caso:',
    tip: 'Lembra da Questão 4 — em qual grupo de pronomes pessoais está a palavra "me"?',
    funFact: '"Me" é uma forma reduzida de "a mim", muito usada no dia a dia da fala e da escrita!',
    points: 1,
    options: [
      { id: 'A', text: 'Reto' },
      { id: 'B', text: 'Demonstrativo' },
      { id: 'C', text: 'Oblíquo' },
      { id: 'D', text: 'Possessivo' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'Qual é a função principal dos pronomes pessoais em um texto?',
    tip: 'Lembra da Questão 2 — qual é a função central dos pronomes pessoais numa frase?',
    funFact: 'Sem os pronomes pessoais, teríamos que repetir sempre o nome completo de todo mundo numa conversa!',
    points: 1,
    options: [
      { id: 'A', text: 'Descrever características físicas' },
      { id: 'B', text: 'Indicar quem fala, com quem se fala ou de quem se fala, evitando repetição do nome' },
      { id: 'C', text: 'Dar ordens' },
      { id: 'D', text: 'Ligar duas orações' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'Na frase "Este é o meu caderno favorito", há dois tipos de pronomes. Quais são eles?',
    tip: 'Lembra das Questões 5 e 7 — que tipo de pronome é "este" e que tipo é "meu"?',
    funFact: 'É bem comum uma frase ter mais de um tipo de pronome ao mesmo tempo!',
    points: 1,
    options: [
      { id: 'A', text: 'Pessoal e de tratamento' },
      { id: 'B', text: 'Apenas demonstrativos' },
      { id: 'C', text: 'Apenas possessivos' },
      { id: 'D', text: 'Demonstrativo ("este") e possessivo ("meu")' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'O uso correto de pronomes de tratamento, como "senhor" e "senhora", geralmente indica:',
    tip: 'Lembra da Questão 9 — que sentimento geralmente está associado ao uso desses pronomes?',
    funFact: 'Usar pronomes de tratamento adequados é uma forma de demonstrar boa educação em situações formais!',
    points: 1,
    options: [
      { id: 'A', text: 'Respeito e formalidade com quem se fala' },
      { id: 'B', text: 'Falta de educação' },
      { id: 'C', text: 'Uma pergunta' },
      { id: 'D', text: 'Uma negação' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'Na frase "Essa camisa é sua?", a palavra "essa" é um pronome:',
    tip: 'Lembra da Questão 7 — que tipo de pronome indica a posição de algo perto de quem ouve?',
    funFact: '"Essa" indica que a camisa está mais perto de quem está ouvindo a pergunta!',
    points: 1,
    options: [
      { id: 'A', text: 'Possessivo' },
      { id: 'B', text: 'Pessoal' },
      { id: 'C', text: 'Demonstrativo' },
      { id: 'D', text: 'De tratamento' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'Substituir "Pedro foi à escola. Pedro esqueceu o material" por "Pedro foi à escola. Ele esqueceu o material" é um exemplo de uso de:',
    tip: 'Lembra da Questão 10 — para que serve usar pronomes em vez de repetir sempre o mesmo nome?',
    funFact: 'Essa técnica deixa o texto mais fluido e agradável de ler!',
    points: 1,
    options: [
      { id: 'A', text: 'Pronome demonstrativo' },
      { id: 'B', text: 'Pronome pessoal para evitar repetição' },
      { id: 'C', text: 'Pronome possessivo' },
      { id: 'D', text: 'Pronome de tratamento' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'Reconhecer os diferentes tipos de pronomes ajuda o estudante a:',
    tip: 'Pensa em tudo que aprendemos sobre pronomes até agora — isso ajuda a escrever melhor ou pior?',
    funFact: 'Conhecer bem os pronomes é uma das bases para escrever textos claros e corretos!',
    points: 1,
    options: [
      { id: 'A', text: 'Escrever textos mais confusos' },
      { id: 'B', text: 'Ignorar a gramática da língua portuguesa' },
      { id: 'C', text: 'Nada relacionado à escrita' },
      { id: 'D', text: 'Escrever e interpretar textos com mais clareza e correção' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Bernardo escreveu uma frase: "Eu adoro futebol." Que tipo de pronome é a palavra "eu"?',
    tip: 'Lembra da Questão 3 — em qual grupo de pronomes pessoais está a palavra "eu"?',
    funFact: 'Bernardo usou o pronome mais comum para falar sobre si mesmo em uma frase!',
    points: 1,
    options: [
      { id: 'A', text: 'Pronome pessoal do caso reto' },
      { id: 'B', text: 'Pronome possessivo' },
      { id: 'C', text: 'Pronome demonstrativo' },
      { id: 'D', text: 'Pronome de tratamento' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Na redação de Bernardo, havia a frase: "Aquele livro pertence à biblioteca." Que tipo de pronome é "aquele"?',
    tip: 'Lembra da Questão 7 e da Questão 12 — que tipo de pronome indica a posição de algo mais distante?',
    funFact: 'Bernardo usou corretamente um pronome que indica que o livro está mais afastado de quem fala e de quem ouve!',
    points: 1,
    options: [
      { id: 'A', text: 'Pronome possessivo' },
      { id: 'B', text: 'Pronome pessoal' },
      { id: 'C', text: 'Pronome demonstrativo' },
      { id: 'D', text: 'Pronome de tratamento' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Bernardo escreveu para o avô: "Este presente é seu." A palavra "seu" nessa frase é um pronome:',
    tip: 'Lembra da Questão 5 — que tipo de pronome indica que o presente pertence ao avô?',
    funFact: 'Bernardo usou o pronome certo para mostrar carinho e cuidado ao presentear o avô!',
    points: 1,
    options: [
      { id: 'A', text: 'Demonstrativo' },
      { id: 'B', text: 'Possessivo' },
      { id: 'C', text: 'Pessoal do caso reto' },
      { id: 'D', text: 'De tratamento' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Na escola, o professor pediu que Bernardo se dirigisse ao diretor de forma respeitosa, usando "o senhor". Esse é um exemplo de pronome de:',
    tip: 'Lembra da Questão 9 e da Questão 17 — que tipo de pronome se usa para tratar alguém com respeito e formalidade?',
    funFact: 'Bernardo aprendeu uma forma importante de demonstrar boa educação com adultos na escola!',
    points: 1,
    options: [
      { id: 'A', text: 'Pronome possessivo' },
      { id: 'B', text: 'Pronome demonstrativo' },
      { id: 'C', text: 'Pronome pessoal do caso reto' },
      { id: 'D', text: 'Tratamento' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Bernardo reescreveu uma frase para evitar repetir o nome do amigo: "João chegou. João estava atrasado" virou "João chegou. Ele estava atrasado." Que tipo de pronome ele usou?',
    tip: 'Lembra da Questão 19 — que tipo de pronome ajuda a evitar repetir o mesmo nome várias vezes?',
    funFact: 'Bernardo deixou seu texto bem mais fluido usando essa estratégia simples!',
    points: 1,
    options: [
      { id: 'A', text: 'Pronome pessoal' },
      { id: 'B', text: 'Pronome possessivo' },
      { id: 'C', text: 'Pronome demonstrativo' },
      { id: 'D', text: 'Pronome de tratamento' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Na frase que Bernardo escreveu, "Essa mochila é minha", há dois pronomes. Quais são eles?',
    tip: 'Lembra da Questão 16 — como identificar dois tipos diferentes de pronomes numa mesma frase?',
    funFact: 'Bernardo está aprendendo a combinar diferentes tipos de pronomes em suas frases do dia a dia!',
    points: 1,
    options: [
      { id: 'A', text: 'Pessoal e de tratamento' },
      { id: 'B', text: 'Apenas demonstrativos' },
      { id: 'C', text: 'Demonstrativo ("essa") e possessivo ("minha")' },
      { id: 'D', text: 'Apenas possessivos' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Bernardo aprendeu que usar pronomes em vez de repetir sempre o mesmo nome deixa o texto:',
    tip: 'Lembra da Questão 10 e da Questão 20 — qual é o benefício de usar pronomes num texto?',
    funFact: 'Textos bem escritos costumam usar pronomes de forma equilibrada, sem exageros nem repetições!',
    points: 1,
    options: [
      { id: 'A', text: 'Mais confuso' },
      { id: 'B', text: 'Mais fluido e sem repetições desnecessárias' },
      { id: 'C', text: 'Sem nenhuma diferença' },
      { id: 'D', text: 'Mais difícil de entender' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Na aula, o professor pediu para Bernardo identificar o pronome pessoal do caso oblíquo na frase "Ela me contou um segredo". Qual é esse pronome?',
    tip: 'Lembra da Questão 4 e da Questão 14 — qual palavra dessa frase pertence ao caso oblíquo dos pronomes pessoais?',
    funFact: 'Bernardo está treinando a identificar pronomes mesmo dentro de frases do cotidiano!',
    points: 1,
    options: [
      { id: 'A', text: 'Ela' },
      { id: 'B', text: 'Contou' },
      { id: 'C', text: 'Segredo' },
      { id: 'D', text: 'Me' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Bernardo entendeu que existem diferentes tipos de pronomes, cada um com uma função específica. Isso mostra a importância de:',
    tip: 'Pensa em tudo que Bernardo aprendeu: pessoal, possessivo, demonstrativo, tratamento — isso ajuda a comunicar melhor ou pior?',
    funFact: 'Bernardo está construindo uma base gramatical que vai ajudá-lo em todos os textos que escrever daqui para frente!',
    points: 1,
    options: [
      { id: 'A', text: 'Conhecer bem a gramática para escrever e interpretar textos com clareza' },
      { id: 'B', text: 'Ignorar completamente as regras gramaticais' },
      { id: 'C', text: 'Usar sempre o mesmo tipo de pronome' },
      { id: 'D', text: 'Nada relacionado à comunicação' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'Ao final do estudo sobre pronomes, Bernardo concluiu que essas palavras são importantes porque:',
    tip: 'Pensa em tudo que Bernardo aprendeu sobre a função principal dos pronomes num texto.',
    funFact: 'Parabéns, Bernardo! Agora você sabe reconhecer e usar os principais tipos de pronomes da língua portuguesa!',
    points: 1,
    options: [
      { id: 'A', text: 'Servem apenas para textos muito formais' },
      { id: 'B', text: 'Não têm nenhuma função na frase' },
      { id: 'C', text: 'Ajudam a substituir substantivos e evitar repetições no texto' },
      { id: 'D', text: 'Só são usadas na fala, nunca na escrita' },
    ],
    correctAnswer: 'C',
  },
];
