export const questoesIngles9AnoB2Av2 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "Choose the correct modal verb: 'You _____ wear a seatbelt in the car. It's the law.'",
    tip: "A lei exige o uso do cinto. Qual modal expressa obrigação forte e intransferível, como uma lei?",
    funFact: "Seatbelts became mandatory in most countries between the 1960s and 1980s. The word 'must' for legal obligations appears on official signs worldwide: 'You must carry your ID.'",
    points: 1,
    options: [
      { id: "A", text: "must" },
      { id: "B", text: "might" },
      { id: "C", text: "should" },
      { id: "D", text: "could" },
    ],
    correctAnswer: "A",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "Change to indirect speech: 'She said, \"I am happy.\"' → 'She said that she _____ happy.'",
    tip: "No discurso indireto, os tempos verbais recuam. O presente simples vira qual tempo?",
    funFact: "In indirect speech, tenses 'backshift': am/is/are → was/were, will → would, can → could, have → had. This is called the 'sequence of tenses' and is a key feature of English grammar!",
    points: 1,
    options: [
      { id: "A", text: "is" },
      { id: "B", text: "was being" },
      { id: "C", text: "was" },
      { id: "D", text: "has been" },
    ],
    correctAnswer: "C",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "He eats breakfast every single day without exception. He _____ skips it.",
    tip: "Se ele come café da manhã absolutamente todos os dias, com que frequência ele pula a refeição?",
    funFact: "Adverbs of frequency go in order of frequency: always (100%) > usually > often > sometimes > rarely > never (0%). 'He never skips breakfast' means it happens 0% of the time!",
    points: 1,
    options: [
      { id: "A", text: "usually" },
      { id: "B", text: "never" },
      { id: "C", text: "sometimes" },
      { id: "D", text: "rarely" },
    ],
    correctAnswer: "B",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "The verb 'communicate' can be turned into a noun by adding which suffix? Choose the correct form.",
    tip: "O sufixo '-tion' é muito comum para criar substantivos a partir de verbos. Como o acréscimo desse sufixo modifica 'communicate'?",
    funFact: "The suffix '-tion' (and its variants '-ation', '-ition', '-sion') creates thousands of English nouns: communicate → communication, educate → education, invent → invention!",
    points: 1,
    options: [
      { id: "A", text: "communicatetion" },
      { id: "B", text: "communicator" },
      { id: "C", text: "communicateness" },
      { id: "D", text: "communication" },
    ],
    correctAnswer: "D",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "Choose the correct modal verb: 'You look tired. You _____ get some rest.'",
    tip: "Alguém está dando um conselho baseado em uma observação. Qual modal é usado para dar conselhos ou recomendações?",
    funFact: "'Should' expresses advice and recommendations. Compare: 'You must rest' (obligation/command) vs 'You should rest' (advice — it's up to you). 'Ought to' is a slightly more formal synonym of 'should'!",
    points: 1,
    options: [
      { id: "A", text: "should" },
      { id: "B", text: "must" },
      { id: "C", text: "can" },
      { id: "D", text: "shall" },
    ],
    correctAnswer: "A",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "Which of the following sentences uses FORMAL language?",
    tip: "Linguagem formal evita gírias, contrações e expressões coloquiais. Qual opção parece apropriada para um ambiente profissional?",
    funFact: "Formal English is used in business emails, academic papers, and official documents. Informal English is for conversations with friends and family. Knowing both styles is a sign of true language proficiency!",
    points: 1,
    options: [
      { id: "A", text: "Hey, can you send me that file?" },
      { id: "B", text: "Gonna need that report ASAP." },
      { id: "C", text: "I would appreciate it if you could forward the document." },
      { id: "D", text: "Thanks for the stuff!" },
    ],
    correctAnswer: "C",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "What is the correct noun form of 'happy' using a suffix?",
    tip: "Qual sufixo transforma adjetivos em substantivos abstratos? Pense em 'sad → sadness', 'dark → darkness'.",
    funFact: "Abstract nouns ending in '-ness' are often used in positive psychology and self-help contexts: happiness, mindfulness, awareness, kindness. They describe states of mind or being!",
    points: 1,
    options: [
      { id: "A", text: "happyment" },
      { id: "B", text: "happiness" },
      { id: "C", text: "happiless" },
      { id: "D", text: "happiful" },
    ],
    correctAnswer: "B",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "Change to indirect speech: 'He asked, \"Are you coming to the party?\"' → 'He asked _____ I was coming to the party.'",
    tip: "A pergunta original é de sim/não (yes/no question). Qual palavra introduz perguntas indiretas de sim/não?",
    funFact: "In indirect yes/no questions, use 'if' or 'whether': 'He asked if I was coming.' In indirect wh-questions, use the question word: 'She asked where I lived.' The word order becomes statement order!",
    points: 1,
    options: [
      { id: "A", text: "what" },
      { id: "B", text: "where" },
      { id: "C", text: "that" },
      { id: "D", text: "if" },
    ],
    correctAnswer: "D",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "Choose the correct modal verb: 'When she was young, she _____ speak three languages.'",
    tip: "A frase fala de uma habilidade que existia no passado. Qual modal expressa capacidade/habilidade no passado?",
    funFact: "'Could' is the past form of 'can' and expresses past ability. Compare: 'I can swim' (present ability) vs 'I could swim when I was five' (past ability). Children's language acquisition is truly amazing!",
    points: 1,
    options: [
      { id: "A", text: "could" },
      { id: "B", text: "should" },
      { id: "C", text: "must" },
      { id: "D", text: "will" },
    ],
    correctAnswer: "A",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "In an argumentative text, which part presents the writer's main position or claim?",
    tip: "Todo texto argumentativo tem uma ideia central que o escritor defende. Onde essa ideia é geralmente apresentada pela primeira vez?",
    funFact: "The word 'thesis' comes from Greek, meaning 'position' or 'proposition'. A strong thesis statement is specific, debatable, and guides the entire essay. Without it, an argumentative essay has no direction!",
    points: 1,
    options: [
      { id: "A", text: "The conclusion" },
      { id: "B", text: "The body paragraphs" },
      { id: "C", text: "The thesis statement" },
      { id: "D", text: "The bibliography" },
    ],
    correctAnswer: "C",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "What does the suffix '-ful' mean in the word 'colorful'?",
    tip: "Pense no significado de 'colorful' — algo que tem muitas cores. O que o sufixo '-ful' acrescenta ao substantivo 'color'?",
    funFact: "The suffix '-ful' originally meant 'full of'. Today it means 'having the quality of': colorful, beautiful, powerful, wonderful, helpful, graceful. It's one of the most productive adjective suffixes in English!",
    points: 1,
    options: [
      { id: "A", text: "Without" },
      { id: "B", text: "To become" },
      { id: "C", text: "The act of" },
      { id: "D", text: "Full of / having the quality of" },
    ],
    correctAnswer: "D",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Fill in the blank: 'She sings _____ — it's wonderful to hear her.'",
    tip: "O advérbio modifica o verbo 'sings'. Como formamos advérbios de modo a partir de adjetivos?",
    funFact: "Most adverbs of manner are formed by adding '-ly' to the adjective: beautiful → beautifully, quick → quickly, careful → carefully. But some are irregular: good → well, fast → fast, hard → hard!",
    points: 1,
    options: [
      { id: "A", text: "beautiful" },
      { id: "B", text: "beautifully" },
      { id: "C", text: "more beautiful" },
      { id: "D", text: "beautify" },
    ],
    correctAnswer: "B",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "Choose the correct modal verb: 'It _____ rain tomorrow — the sky looks cloudy.'",
    tip: "O céu nublado sugere a possibilidade de chuva, mas não é certeza. Qual modal indica possibilidade ou incerteza?",
    funFact: "'Might' and 'may' both express possibility, but 'might' suggests a lower probability. Compare: 'It may rain' (maybe 50%) vs 'It might rain' (maybe 30-40%). Context usually makes the difference!",
    points: 1,
    options: [
      { id: "A", text: "might" },
      { id: "B", text: "must" },
      { id: "C", text: "shall" },
      { id: "D", text: "would" },
    ],
    correctAnswer: "A",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "Which expression is INFORMAL?",
    tip: "Linguagem informal usa gírias, abreviações e um tom casual. Qual opção parece típica de uma mensagem de texto entre amigos?",
    funFact: "The boundary between formal and informal language is constantly shifting. Words like 'okay' were once informal but are now acceptable in many formal contexts. Language evolves with society!",
    points: 1,
    options: [
      { id: "A", text: "I am writing to request further information." },
      { id: "B", text: "Please find attached the requested documents." },
      { id: "C", text: "I need info about this ASAP!" },
      { id: "D", text: "Yours faithfully, James Brown" },
    ],
    correctAnswer: "C",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "What does the suffix '-less' mean in the word 'careless'?",
    tip: "Pense no significado de 'careless'. Se alguém é 'careless', o que falta a essa pessoa?",
    funFact: "'-less' (without) and '-ful' (full of) are opposites: careful / careless, hopeful / hopeless, powerful / powerless, colorful / colorless. Many adjectives can take both suffixes with opposite meanings!",
    points: 1,
    options: [
      { id: "A", text: "Having a lot of" },
      { id: "B", text: "Related to" },
      { id: "C", text: "Able to" },
      { id: "D", text: "Without" },
    ],
    correctAnswer: "D",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "Change to indirect speech: 'She said, \"Close the door!\"' → 'She told him _____ the door.'",
    tip: "A fala original é um imperativo (ordem). Como as ordens são reportadas no discurso indireto?",
    funFact: "Commands in indirect speech use 'to + infinitive': tell/ask/order/instruct + object + to + verb. 'She told him to close the door.' Negative commands use 'not to': 'She told him not to open it.'",
    points: 1,
    options: [
      { id: "A", text: "close" },
      { id: "B", text: "to close" },
      { id: "C", text: "closing" },
      { id: "D", text: "closed" },
    ],
    correctAnswer: "B",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "Choose the correct modal verb: '_____ you speak any foreign languages?'",
    tip: "A pergunta é sobre a habilidade de falar idiomas. Qual modal pergunta sobre capacidade ou habilidade?",
    funFact: "'Can' is the most common modal for ability in everyday speech. 'Could' is its past form but also used for polite requests: 'Could you help me?' is more polite than 'Can you help me?'",
    points: 1,
    options: [
      { id: "A", text: "Can" },
      { id: "B", text: "Must" },
      { id: "C", text: "Shall" },
      { id: "D", text: "Ought to" },
    ],
    correctAnswer: "A",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "Where does the adverb of frequency usually appear in an English sentence?",
    tip: "Pense em exemplos: 'She always arrives late', 'He is never happy'. Onde está o advérbio em relação ao verbo principal?",
    funFact: "Position rule: adverbs of frequency go BEFORE main verbs ('She always studies') but AFTER the verb 'to be' ('She is always late'). With modals, they go between the modal and main verb: 'You should always check'!",
    points: 1,
    options: [
      { id: "A", text: "At the beginning of the sentence" },
      { id: "B", text: "At the end of the sentence" },
      { id: "C", text: "Before the main verb (after auxiliary verbs)" },
      { id: "D", text: "After the direct object" },
    ],
    correctAnswer: "C",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "What does the suffix '-able' mean in the word 'comfortable'?",
    tip: "Pense no significado de 'comfortable'. O sufixo '-able' acrescenta qual ideia ao substantivo base?",
    funFact: "'-able' and '-ible' both mean 'capable of' or 'worthy of': comfortable, readable, acceptable, flexible, possible, responsible. There are no firm rules for when to use '-able' vs '-ible' — they must be memorized!",
    points: 1,
    options: [
      { id: "A", text: "Without" },
      { id: "B", text: "Having done" },
      { id: "C", text: "Making someone feel" },
      { id: "D", text: "Capable of / having the quality of" },
    ],
    correctAnswer: "D",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "In an argumentative essay, what comes AFTER the thesis statement?",
    tip: "Depois de apresentar a posição central do ensaio, o escritor precisa desenvolvê-la e sustentá-la. O que vem a seguir?",
    funFact: "The structure of an argumentative essay: Introduction (with thesis) → Body paragraphs (arguments + evidence) → Conclusion (restatement + call to action). This structure appears in essays around the world!",
    points: 1,
    options: [
      { id: "A", text: "The conclusion paragraph" },
      { id: "B", text: "The body paragraphs with supporting arguments" },
      { id: "C", text: "The bibliography" },
      { id: "D", text: "A second introduction" },
    ],
    correctAnswer: "B",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Choose the correct modal verb: 'I _____ go to the doctor — I've had this headache for a week.' (strong personal necessity)",
    tip: "Não é uma sugestão externa — o próprio falante sente a necessidade forte e urgente. Qual modal expressa isso?",
    funFact: "'Must' for obligation comes from the speaker's own judgment; 'have to' often comes from external rules. 'I must see a doctor' (I feel I need to) vs 'I have to see a doctor' (the hospital requires it)!",
    points: 1,
    options: [
      { id: "A", text: "should" },
      { id: "B", text: "could" },
      { id: "C", text: "must" },
      { id: "D", text: "might" },
    ],
    correctAnswer: "C",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "What is the correct noun form of 'develop' using the suffix '-ment'?",
    tip: "O sufixo '-ment' transforma verbos em substantivos. Como é formado o substantivo de 'develop'?",
    funFact: "'Development' is one of the most important words in international discourse — economic development, personal development, sustainable development. The suffix '-ment' is incredibly productive in formal English!",
    points: 1,
    options: [
      { id: "A", text: "development" },
      { id: "B", text: "developful" },
      { id: "C", text: "developness" },
      { id: "D", text: "developless" },
    ],
    correctAnswer: "A",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Change to indirect speech: 'He said, \"I will call you.\"' → 'He said he _____ call me.'",
    tip: "No discurso indireto, 'will' muda para qual modal? Os tempos recuam no tempo.",
    funFact: "In indirect speech: will → would, can → could, may → might, shall → should. These backshifts make indirect speech consistent with the past reporting verb ('said', 'told', 'asked')!",
    points: 1,
    options: [
      { id: "A", text: "will" },
      { id: "B", text: "shall" },
      { id: "C", text: "can" },
      { id: "D", text: "would" },
    ],
    correctAnswer: "D",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Which greeting is appropriate for a formal letter?",
    tip: "Cartas formais têm convenções específicas de abertura. Qual opção usa o formato correto para contato profissional formal?",
    funFact: "Formal letter structure: greeting (Dear Mr./Ms./Dr. + surname), body, closing (Yours sincerely if name is known / Yours faithfully if not), signature. This format is used in business worldwide!",
    points: 1,
    options: [
      { id: "A", text: "Hey there!" },
      { id: "B", text: "Dear Mr. Johnson," },
      { id: "C", text: "Hi! What's up?" },
      { id: "D", text: "Yo, John!" },
    ],
    correctAnswer: "B",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Choose the best modal verb: 'You _____ read this book — it's fantastic!' (recommendation)",
    tip: "O falante está recomendando o livro — não é uma obrigação ou lei. Qual modal é mais adequado para dar uma recomendação?",
    funFact: "The strength of modals in recommendations: must (very strong — almost an order) > should (strong recommendation) > ought to (slightly formal advice) > might want to (gentle suggestion). Choose based on how insistent you want to be!",
    points: 1,
    options: [
      { id: "A", text: "must" },
      { id: "B", text: "might" },
      { id: "C", text: "should" },
      { id: "D", text: "would" },
    ],
    correctAnswer: "C",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "How are most adverbs of manner formed in English?",
    tip: "Pense em exemplos: slow → slowly, careful → carefully, loud → loudly. O que todos têm em comum?",
    funFact: "Most adverbs of manner are formed by adding '-ly'. But watch out for exceptions: fast → fast (not fastly), hard → hard (not hardly — 'hardly' means almost not!), good → well (not goodly)!",
    points: 1,
    options: [
      { id: "A", text: "Add '-ly' to the adjective" },
      { id: "B", text: "Add '-ful' to the adjective" },
      { id: "C", text: "Add '-ment' to the adjective" },
      { id: "D", text: "Add '-ness' to the adjective" },
    ],
    correctAnswer: "A",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "What is the correct adjective form of 'create' using the suffix '-ive'?",
    tip: "O sufixo '-ive' transforma verbos ou substantivos em adjetivos. Qual é a forma correta?",
    funFact: "The suffix '-ive' creates adjectives meaning 'having a tendency to' or 'relating to': create → creative, act → active, attract → attractive, describe → descriptive. It's very common in academic vocabulary!",
    points: 1,
    options: [
      { id: "A", text: "creately" },
      { id: "B", text: "createness" },
      { id: "C", text: "createment" },
      { id: "D", text: "creative" },
    ],
    correctAnswer: "D",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Change to indirect speech: 'She said, \"I love this place.\"' → 'She said that _____ loved that place.'",
    tip: "No discurso indireto, os pronomes mudam para refletir o ponto de vista do narrador. Que pronome substitui 'I' quando falamos sobre uma mulher?",
    funFact: "In indirect speech, both tenses AND pronouns change to reflect the narrator's perspective: 'I' → he/she, 'my' → his/her, 'we' → they, 'this' → that, 'here' → there, 'now' → then!",
    points: 1,
    options: [
      { id: "A", text: "I" },
      { id: "B", text: "she" },
      { id: "C", text: "they" },
      { id: "D", text: "we" },
    ],
    correctAnswer: "B",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Which sentence is MORE polite and formal when asking for help?",
    tip: "Entre 'can' e 'could', qual deles soa mais formal e educado em inglês?",
    funFact: "'Could you...?' is more polite than 'Can you...?' because 'could' creates more distance and sounds less direct. Adding 'please' makes any request more polite. In very formal contexts: 'Would you mind...?'",
    points: 1,
    options: [
      { id: "A", text: "Can you help me?" },
      { id: "B", text: "Must you help me?" },
      { id: "C", text: "Could you help me, please?" },
      { id: "D", text: "Should you help me?" },
    ],
    correctAnswer: "C",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Which of the following is NOT typically found as the main structure of an argumentative text?",
    tip: "Um texto argumentativo tem características específicas que o diferenciam de outros gêneros. O que é fundamental num texto argumentativo?",
    funFact: "Argumentative texts are different from narrative texts (which tell stories) and descriptive texts (which paint pictures with words). Arguments need logic, evidence, and a clear position — not just personal tales!",
    points: 1,
    options: [
      { id: "A", text: "A narrative story about the writer's personal experiences as the main structure" },
      { id: "B", text: "A clear thesis statement presenting the writer's position" },
      { id: "C", text: "Supporting evidence and examples to back up arguments" },
      { id: "D", text: "A conclusion that restates the main position" },
    ],
    correctAnswer: "A",
  },
];
