export const questoesCiencias8AnoB1Av2 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "Qual é a função principal do sistema respiratório?",
    tip: "Pense no que você faz a cada respiração: você \"pega\" um gás do ar e \"devolve\" outro.",
    funFact: "Você respira, em média, mais de 20 mil vezes por dia, sem nem perceber!",
    points: 1,
    options: [
      { id: "A", text: "digerir os alimentos" },
      { id: "B", text: "bombear o sangue" },
      { id: "C", text: "realizar a troca de gases (absorver oxigênio e eliminar gás carbônico)" },
      { id: "D", text: "formar os ossos" },
    ],
    correctAnswer: "C",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "Por onde o ar normalmente entra no nosso corpo?",
    tip: "Pense na primeira estrutura por onde o ar passa, logo no início do seu rosto.",
    funFact: "Respirar pelo nariz é mais saudável do que pela boca, porque o ar é filtrado antes de entrar!",
    points: 1,
    options: [
      { id: "A", text: "pelos pulmões" },
      { id: "B", text: "pelo nariz" },
      { id: "C", text: "pela traqueia" },
      { id: "D", text: "pela laringe" },
    ],
    correctAnswer: "B",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "Dentro do nariz, o ar é filtrado por pelos e:",
    tip: "Pense naquela substância pegajosa que prende poeira e partículas — ela ajuda a limpar o ar.",
    funFact: "O muco também ajuda a umidificar e aquecer o ar antes dele chegar aos pulmões!",
    points: 1,
    options: [
      { id: "A", text: "saliva" },
      { id: "B", text: "sangue" },
      { id: "C", text: "ossos" },
      { id: "D", text: "muco" },
    ],
    correctAnswer: "D",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "Qual é a função da laringe?",
    tip: "Pense em quando você fala ou canta — qual parte do corpo vibra para produzir o som?",
    funFact: "Quando você está gripado e fica \"rouco\", geralmente é a laringe que está inflamada!",
    points: 1,
    options: [
      { id: "A", text: "produzir a voz, através das cordas vocais" },
      { id: "B", text: "digerir alimentos" },
      { id: "C", text: "bombear sangue" },
      { id: "D", text: "filtrar a urina" },
    ],
    correctAnswer: "A",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "Depois da laringe, o ar passa por um tubo chamado:",
    tip: "Cuidado para não confundir com o esôfago, que é do sistema digestório! Esse tubo é só para o ar.",
    funFact: "Se você passar os dedos na frente do pescoço, pode sentir os anéis dessa estrutura!",
    points: 1,
    options: [
      { id: "A", text: "esôfago" },
      { id: "B", text: "traqueia" },
      { id: "C", text: "intestino" },
      { id: "D", text: "fígado" },
    ],
    correctAnswer: "B",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "A traqueia é formada por anéis de uma substância resistente e flexível chamada:",
    tip: "Pense no mesmo material flexível que forma a ponta do seu nariz e suas orelhas.",
    funFact: "Esses anéis mantêm a traqueia sempre aberta, mesmo quando você vira o pescoço!",
    points: 1,
    options: [
      { id: "A", text: "osso" },
      { id: "B", text: "músculo" },
      { id: "C", text: "cartilagem" },
      { id: "D", text: "gordura" },
    ],
    correctAnswer: "C",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "A traqueia se divide em dois tubos chamados:",
    tip: "Pense na primeira divisão da traqueia, logo na entrada dos pulmões — um tubo para cada lado.",
    funFact: "Cada bronquio leva o ar para um dos dois pulmões!",
    points: 1,
    options: [
      { id: "A", text: "bronquios" },
      { id: "B", text: "alvéolos" },
      { id: "C", text: "bronquíolos" },
      { id: "D", text: "pulmões" },
    ],
    correctAnswer: "A",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "Dentro dos pulmões, os bronquios se dividem em tubos menores chamados:",
    tip: "Pense num nome parecido com \"bronquio\", só que no \"diminutivo\" — tubos ainda menores.",
    funFact: "Os pulmões têm milhares de bronquíolos, parecendo os ramos de uma árvore ao contrário!",
    points: 1,
    options: [
      { id: "A", text: "traqueias" },
      { id: "B", text: "laringes" },
      { id: "C", text: "veias" },
      { id: "D", text: "bronquíolos" },
    ],
    correctAnswer: "D",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "No final dos bronquíolos, encontramos pequenas bolsas de ar chamadas:",
    tip: "Pense nas pequenas \"bolhinhas\" no final do caminho do ar, onde a troca gasosa realmente acontece.",
    funFact: "Os pulmões têm cerca de 300 milhões de alvéolos no total!",
    points: 1,
    options: [
      { id: "A", text: "vilosidades" },
      { id: "B", text: "alvéolos" },
      { id: "C", text: "válvulas" },
      { id: "D", text: "papilas" },
    ],
    correctAnswer: "B",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "É nos alvéolos que ocorre:",
    tip: "Pense no objetivo final de todo o caminho do ar — o que precisa acontecer entre o ar e o sangue?",
    funFact: "Se você esticasse todos os alvéolos dos seus pulmões, eles cobririam uma área do tamanho de uma quadra de tênis!",
    points: 1,
    options: [
      { id: "A", text: "a digestão dos alimentos" },
      { id: "B", text: "a produção de saliva" },
      { id: "C", text: "a troca gasosa entre o ar e o sangue" },
      { id: "D", text: "a formação dos ossos" },
    ],
    correctAnswer: "C",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Qual músculo é o principal responsável pelos movimentos de respiração?",
    tip: "Pense no músculo que fica embaixo dos pulmões e se move toda vez que você respira.",
    funFact: "Quando você soluça, é justamente esse músculo que está se contraindo de forma descontrolada!",
    points: 1,
    options: [
      { id: "A", text: "o diafragma" },
      { id: "B", text: "o coração" },
      { id: "C", text: "o fígado" },
      { id: "D", text: "o estômago" },
    ],
    correctAnswer: "A",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Durante a inspiração (quando o ar entra), o diafragma:",
    tip: "Pense: para o ar entrar e os pulmões se expandirem, o diafragma precisa \"abrir espaço\" descendo.",
    funFact: "Esse movimento é parecido com uma seringa sendo puxada, criando espaço para o ar entrar!",
    points: 1,
    options: [
      { id: "A", text: "relaxa e sobe" },
      { id: "B", text: "desaparece" },
      { id: "C", text: "fica parado" },
      { id: "D", text: "se contrai e desce" },
    ],
    correctAnswer: "D",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "Durante a expiração (quando o ar sai), o diafragma:",
    tip: "É o movimento contrário da inspiração — o diafragma volta à posição de descanso, empurrando o ar para fora.",
    funFact: "Você pode sentir esse movimento colocando a mão na barriga enquanto respira fundo!",
    points: 1,
    options: [
      { id: "A", text: "se contrai mais ainda" },
      { id: "B", text: "relaxa e sobe" },
      { id: "C", text: "desaparece" },
      { id: "D", text: "fica do mesmo tamanho" },
    ],
    correctAnswer: "B",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "Nos alvéolos, o oxigênio do ar passa para o sangue e é transportado principalmente por:",
    tip: "Pense nas células do sangue que dão a cor vermelha a ele — são elas que \"carregam\" o oxigênio pelo corpo.",
    funFact: "As hemácias têm um formato especial, como um disco achatado, perfeito para transportar oxigênio!",
    points: 1,
    options: [
      { id: "A", text: "os ossos" },
      { id: "B", text: "a saliva" },
      { id: "C", text: "as hemácias (células vermelhas do sangue)" },
      { id: "D", text: "o muco" },
    ],
    correctAnswer: "C",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Ao mesmo tempo que o oxigênio entra no sangue nos alvéolos, o que sai do sangue para o ar?",
    tip: "Pense no gás que o corpo produz como \"lixo\" depois de usar o oxigênio — ele precisa ser eliminado.",
    funFact: "É esse gás que faz embaçar o espelho quando você respira perto dele!",
    points: 1,
    options: [
      { id: "A", text: "o gás carbônico (CO2)" },
      { id: "B", text: "a água só" },
      { id: "C", text: "o nitrogênio" },
      { id: "D", text: "nada sai" },
    ],
    correctAnswer: "A",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "Por que é importante não fumar para a saúde do sistema respiratório?",
    tip: "Pense em tudo que aprendemos sobre os alvéolos — a fumaça suja e danifica essas estruturas tão importantes.",
    funFact: "Os pulmões de uma pessoa que fuma ficam escurecidos, diferente dos pulmões saudáveis e rosados!",
    points: 1,
    options: [
      { id: "A", text: "porque deixa os dentes amarelos só" },
      { id: "B", text: "porque não tem nenhum efeito nos pulmões" },
      { id: "C", text: "porque melhora a respiração" },
      { id: "D", text: "porque a fumaça prejudica os pulmões e dificulta a troca gasosa" },
    ],
    correctAnswer: "D",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "A tosse e o espirro são mecanismos de defesa do corpo que servem para:",
    tip: "Pense em quando você espirra por causa de poeira — o que seu corpo está tentando fazer?",
    funFact: "Um espirro pode expulsar o ar a uma velocidade de até 150 km/h!",
    points: 1,
    options: [
      { id: "A", text: "produzir mais muco só por diversão" },
      { id: "B", text: "aumentar a quantidade de ar nos pulmões" },
      { id: "C", text: "expulsar partículas estranhas das vias respiratórias" },
      { id: "D", text: "fortalecer os músculos" },
    ],
    correctAnswer: "C",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "A poluição do ar pode prejudicar o sistema respiratório porque:",
    tip: "Pense em fumaça de carros e fábricas — o que esse tipo de ar sujo faz com os pulmões?",
    funFact: "Em cidades muito poluídas, é comum ver mais pessoas com problemas respiratórios, como asma!",
    points: 1,
    options: [
      { id: "A", text: "deixa o ar mais gostoso" },
      { id: "B", text: "contém partículas e gases que irritam e danificam as vias respiratórias" },
      { id: "C", text: "aumenta o oxigênio do ar" },
      { id: "D", text: "não tem nenhum efeito" },
    ],
    correctAnswer: "B",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "Qual é a ordem correta do caminho do ar ao entrar no corpo?",
    tip: "Vá revendo cada estrutura que estudamos hoje, na ordem em que o ar realmente passa por elas.",
    funFact: "Esse caminho inteiro acontece em menos de 2 segundos a cada respiração!",
    points: 1,
    options: [
      { id: "A", text: "nariz → faringe → laringe → traqueia → bronquios → bronquíolos → alvéolos" },
      { id: "B", text: "nariz → traqueia → faringe → laringe → alvéolos" },
      { id: "C", text: "alvéolos → bronquios → traqueia → nariz" },
      { id: "D", text: "laringe → nariz → traqueia → faringe" },
    ],
    correctAnswer: "A",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "Os pulmões ficam protegidos dentro de uma estrutura óssea chamada:",
    tip: "Pense nos ossos curvos que você sente no seu peito e costas, protegendo os órgãos internos.",
    funFact: "A caixa torácica também protege o coração, outro órgão muito importante!",
    points: 1,
    options: [
      { id: "A", text: "crânio" },
      { id: "B", text: "coluna vertebral só" },
      { id: "C", text: "bacia" },
      { id: "D", text: "caixa torácica (formada pelas costelas)" },
    ],
    correctAnswer: "D",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Bernardo fez um exercício físico forte e notou que estava respirando mais rápido. Por que isso acontece?",
    tip: "Pense: durante o exercício, os músculos trabalham mais e por isso precisam de mais desse gás importante.",
    funFact: "É por isso que atletas treinam a respiração para melhorar seu desempenho nos esportes!",
    points: 1,
    options: [
      { id: "A", text: "porque os pulmões encolhem" },
      { id: "B", text: "porque o corpo precisa de mais oxigênio para os músculos durante o exercício" },
      { id: "C", text: "porque o coração para de bater" },
      { id: "D", text: "porque o ar fica mais pesado" },
    ],
    correctAnswer: "B",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Bernardo sentiu um cheiro forte de poeira e começou a espirrar. Isso é um exemplo de:",
    tip: "Lembre da Questão 17 — qual é a função do espirro?",
    funFact: "O espirro é um reflexo tão rápido que é quase impossível segurá-lo completamente!",
    points: 1,
    options: [
      { id: "A", text: "problema permanente nos pulmões" },
      { id: "B", text: "sinal de que parou de respirar" },
      { id: "C", text: "mecanismo de defesa, expulsando partículas estranhas" },
      { id: "D", text: "sinal de que os alvéolos pararam de funcionar" },
    ],
    correctAnswer: "C",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Bernardo está aprendendo sobre o caminho do ar. Depois de passar pela traqueia, por onde o ar passa?",
    tip: "Lembre da Questão 7 — qual estrutura vem logo depois da traqueia?",
    funFact: "Cada bronquio continua se dividindo em tubos cada vez menores dentro do pulmão!",
    points: 1,
    options: [
      { id: "A", text: "pelos bronquios" },
      { id: "B", text: "pelo esôfago" },
      { id: "C", text: "pelo estômago" },
      { id: "D", text: "pelo fígado" },
    ],
    correctAnswer: "A",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Bernardo quer saber onde ocorre a troca de oxigênio por gás carbônico no seu corpo.",
    tip: "Lembre da Questão 9 e 10 — qual é a estrutura final do caminho do ar, onde a troca realmente acontece?",
    funFact: "Os alvéolos ficam rodeados por vasos sanguíneos bem finos, para facilitar essa troca!",
    points: 1,
    options: [
      { id: "A", text: "no nariz" },
      { id: "B", text: "na traqueia" },
      { id: "C", text: "na laringe" },
      { id: "D", text: "nos alvéolos pulmonares" },
    ],
    correctAnswer: "D",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Bernardo observou que, ao respirar fundo, sua barriga (abdômen) se expande. Isso acontece porque:",
    tip: "Lembre da Questão 11 e 12 — qual músculo se move para baixo durante a respiração?",
    funFact: "Essa é chamada de \"respiração diafragmática\" e é usada por cantores para controlar melhor a voz!",
    points: 1,
    options: [
      { id: "A", text: "os pulmões descem até a barriga" },
      { id: "B", text: "o estômago aumenta de tamanho" },
      { id: "C", text: "o diafragma se contrai e desce, empurrando os órgãos abaixo dele" },
      { id: "D", text: "o ar entra direto na barriga" },
    ],
    correctAnswer: "C",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Bernardo aprendeu que fumar é prejudicial à saúde. Qual parte do sistema respiratório é mais afetada pelo cigarro?",
    tip: "Lembre da Questão 16 — qual órgão é mais prejudicado pela fumaça do cigarro?",
    funFact: "Parar de fumar, mesmo depois de anos, já começa a melhorar a saúde dos pulmões!",
    points: 1,
    options: [
      { id: "A", text: "só os dentes" },
      { id: "B", text: "os pulmões (e as vias respiratórias em geral)" },
      { id: "C", text: "só as unhas" },
      { id: "D", text: "nenhuma parte é afetada" },
    ],
    correctAnswer: "B",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Bernardo mediu sua respiração e notou que, em repouso, respira mais lentamente do que durante um jogo de futebol. Isso mostra que:",
    tip: "Lembre da Questão 21 — por que respiramos mais rápido durante o exercício?",
    funFact: "Em repouso, respiramos entre 12 e 20 vezes por minuto, mas durante exercícios esse número pode dobrar!",
    points: 1,
    options: [
      { id: "A", text: "a respiração nunca muda" },
      { id: "B", text: "o corpo respira sempre no mesmo ritmo" },
      { id: "C", text: "o sistema respiratório para de funcionar durante o jogo" },
      { id: "D", text: "a frequência respiratória aumenta conforme a necessidade de oxigênio do corpo" },
    ],
    correctAnswer: "D",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Bernardo quer entender por que o ar que ele inspira (puro) é diferente do ar que ele expira (usado).",
    tip: "Lembre da Questão 14 e 15 — o que entra e o que sai do sangue nos alvéolos?",
    funFact: "É por isso que, num ambiente fechado com muita gente, o ar pode ficar com menos oxigênio depois de um tempo!",
    points: 1,
    options: [
      { id: "A", text: "porque no corpo o oxigênio é absorvido e o gás carbônico é liberado" },
      { id: "B", text: "porque o ar não muda nunca" },
      { id: "C", text: "porque os pulmões produzem oxigênio puro" },
      { id: "D", text: "porque o nariz transforma todo o ar em água" },
    ],
    correctAnswer: "A",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Bernardo percebeu que, quando está gripado, respira com mais dificuldade pelo nariz. Isso geralmente acontece por causa do:",
    tip: "Lembre da Questão 3 — qual substância do nariz aumenta quando estamos gripados?",
    funFact: "O excesso de muco durante uma gripe é, na verdade, uma defesa do corpo tentando \"prender\" os vírus!",
    points: 1,
    options: [
      { id: "A", text: "crescimento dos ossos do nariz" },
      { id: "B", text: "aumento dos alvéolos" },
      { id: "C", text: "excesso de muco produzido para combater a infecção" },
      { id: "D", text: "diminuição do diafragma" },
    ],
    correctAnswer: "C",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Revisando tudo: qual é a principal função do sistema respiratório no corpo de Bernardo?",
    tip: "Pense em tudo que vimos hoje: nariz, traqueia, bronquios, pulmões e alvéolos — todos trabalham juntos para esse objetivo final.",
    funFact: "Parabéns! Agora você entende todo o caminho que o ar faz dentro do seu corpo!",
    points: 1,
    options: [
      { id: "A", text: "digerir os alimentos que ele come" },
      { id: "B", text: "realizar a troca gasosa, levando oxigênio ao sangue e eliminando gás carbônico" },
      { id: "C", text: "bombear o sangue pelo corpo" },
      { id: "D", text: "controlar os movimentos dos músculos" },
    ],
    correctAnswer: "B",
  },
];
