export const questoesArte1EmB3Av2 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "O Expressionismo surgiu na Europa (especialmente na Alemanha) no início do século XX. O que caracteriza essa corrente artística?",
    tip: "O nome 'expressionismo' diz muito: não é impressionismo (a impressão de fora) — é algo diferente que o artista faz. O quê?",
    funFact: "\"Você sabia?\" — O Expressionismo surgiu parcialmente como resposta ao otimismo da Belle Époque e antecipou as atrocidades que viriam. Muitos expressionistas previram a Primeira Guerra Mundial em suas obras — como se os pintores sentissem a catástrofe antes de ela acontecer.",
    points: 1,
    options: [
      { id: "A", text: "A representação objetiva da realidade visível sem qualquer distorção ou emoção pessoal" },
      { id: "B", text: "O uso de cores pastel e formas suaves para criar ambientes decorativos e agradáveis" },
      { id: "C", text: "A reprodução científica das propriedades da luz usando pontos de cor pura justapostos" },
      { id: "D", text: "A distorção deliberada das formas e o uso intenso de cores para expressar estados emocionais internos" },
    ],
    correctAnswer: "D",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "'O Grito' (1893), de Edvard Munch, é considerado o símbolo do Expressionismo. O que a obra representa e qual sua importância?",
    tip: "Munch descreveu a experiência que originou a obra em seu diário — não era um observador neutro mas alguém vivenciando algo muito intenso.",
    funFact: "\"Você sabia?\" — Munch existiu quatro versões de O Grito: duas em pastel, uma em têmpera e uma em litografia. Em 2012, a versão em pastel de 1895 foi vendida por 119,9 milhões de dólares — o preço mais alto pago por uma obra de arte em leilão até então.",
    points: 1,
    options: [
      { id: "A", text: "Uma figura em pânico existencial ante a imensidão da natureza — o grito da angústia humana moderna, onde o céu e a paisagem ondulam com a emoção do ser" },
      { id: "B", text: "Uma cena cotidiana de pessoas gritando numa manifestação política em Oslo" },
      { id: "C", text: "Um retrato de Munch gritando durante um acesso de epilepsia no cais de Christiania" },
      { id: "D", text: "Uma cena bíblica de angústia baseada no Livro de Jó, com fundo de céu tempestuoso" },
    ],
    correctAnswer: "A",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "Die Brücke ('A Ponte') foi um grupo expressionista alemão fundado em Dresden em 1905. O que unia esses artistas?",
    tip: "O nome 'A Ponte' era simbólico — uma ponte para onde? Entre o quê e o quê?",
    funFact: "\"Você sabia?\" — Ernst Ludwig Kirchner, principal artista do Die Brücke, desenvolveu um estilo de figuras angulosas e cores agressivas que criava um retrato perturbador da vida urbana de Berlim. Depois de servir na Primeira Guerra Mundial, sofreu colapso nervoso e nunca mais se recuperou completamente.",
    points: 1,
    options: [
      { id: "A", text: "O interesse pela arte flamenga do século XVII como modelo para um realismo social alemão" },
      { id: "B", text: "A admiração pelas obras de Monet e o desejo de levar o Impressionismo à Alemanha" },
      { id: "C", text: "A rejeição da arte burguesa acadêmica e a busca por uma nova expressão emocional e espiritual — uma 'ponte' rumo à arte do futuro" },
      { id: "D", text: "O interesse pela arquitetura gótica medieval como fonte de espiritualidade para a arte moderna" },
    ],
    correctAnswer: "C",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "Der Blaue Reiter ('O Cavaleiro Azul') foi um grupo expressionista fundado em Munique em 1911 por Wassily Kandinsky e Franz Marc. O que os diferenciava do Die Brücke?",
    tip: "O Die Brücke tinha um estilo mais angular e urbano; o Der Blaue Reiter foi em outra direção — mais espiritual e lírica.",
    funFact: "\"Você sabia?\" — O nome 'Der Blaue Reiter' veio de uma conversa entre Kandinsky e Marc sobre sua cor favorita (azul) e tema favorito (cavaleiros). Kandinsky acreditava que o azul era a cor mais espiritual, capaz de elevar a alma acima do mundo material.",
    points: 1,
    options: [
      { id: "A", text: "O Der Blaue Reiter focava em temas urbanos e sociais enquanto o Die Brücke explorava paisagens naturais" },
      { id: "B", text: "Der Blaue Reiter buscava uma arte mais lírica, espiritual e abstrata — Kandinsky avançaria para a abstração total" },
      { id: "C", text: "O Der Blaue Reiter era exclusivamente escultura enquanto o Die Brücke era exclusivamente pintura" },
      { id: "D", text: "Der Blaue Reiter foi o grupo expressionista francês em contraposição ao grupo alemão Die Brücke" },
    ],
    correctAnswer: "B",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "O Fauvismo surgiu na França por volta de 1905. O que caracteriza a pintura fauvista?",
    tip: "O nome vem de 'fauves' (feras em francês) — o que havia de 'selvagem' nessa arte para o público da época?",
    funFact: "\"Você sabia?\" — O nome 'Fauvismo' foi criado pelo crítico Louis Vauxcelles no Salon d'Automne de 1905, ao ver uma escultura renascentista cercada de pinturas de cores intensas e exclamar: 'Donatello parece cercado de feras!' O insulto virou nome de movimento.",
    points: 1,
    options: [
      { id: "A", text: "Uso de cores realistas e naturalistas com técnica de sfumato para criar volumes suaves" },
      { id: "B", text: "Pinturas monocromáticas com contornos rígidos e figuras angulosas de influência africana" },
      { id: "C", text: "Rejeição completa da figura humana em favor de formas geométricas puras" },
      { id: "D", text: "Uso de cores intensas e puras diretamente do tubo, sem mistura, com fins expressivos e não descritivos" },
    ],
    correctAnswer: "D",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "Henri Matisse é considerado o líder do Fauvismo. Qual foi a evolução de sua arte ao longo da carreira?",
    tip: "Matisse nunca parou de experimentar — de pintor fauvista tornou-se algo ainda mais radical no final da vida. O quê?",
    funFact: "\"Você sabia?\" — Nos últimos anos de vida, impossibilitado de pintar pela doença, Matisse criou seus 'Papéis Recortados' (découpages) — pintava folhas de papel com guache e depois as recortava em formas que seus assistentes colavam sob sua orientação. Chamou isso de 'desenhar com tesoura'.",
    points: 1,
    options: [
      { id: "A", text: "Partiu do Fauvismo com cores puras e evoluiu para colagens de papéis recortados, sempre buscando simplicidade e alegria de viver" },
      { id: "B", text: "Começou fauvista mas converteu-se ao Cubismo após amizade com Picasso" },
      { id: "C", text: "Abandonou a pintura para se dedicar exclusivamente à escultura monumental" },
      { id: "D", text: "Iniciou no Fauvismo mas acabou o Realismo após viagem aos Estados Unidos" },
    ],
    correctAnswer: "A",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "O Art Nouveau foi um estilo decorativo que floresceu entre 1890 e 1910 em toda a Europa. Quais são suas características visuais mais marcantes?",
    tip: "Art Nouveau significa 'arte nova' em francês. Pense em formas orgânicas, plantas e elementos naturais usados de forma ornamental.",
    funFact: "\"Você sabia?\" — O Art Nouveau foi o primeiro estilo artístico a integrar deliberadamente todas as artes — arquitetura, móveis, joias, cartazes, vidro e cerâmica — numa visão decorativa unificada. A ideia era que não deveria haver separação entre 'arte erudita' e 'artes aplicadas'.",
    points: 1,
    options: [
      { id: "A", text: "Formas geométricas rígidas, ângulos retos e cores industriais como o cinza e o preto" },
      { id: "B", text: "Retorno às formas clássicas greco-romanas com colunas, frontões e proporções matemáticas" },
      { id: "C", text: "Linhas sinuosas e orgânicas inspiradas na natureza (flores, plantas, insetos), ornamentação exuberante e integração entre arte e design" },
      { id: "D", text: "Figuras humanas deformadas e angulosas em cenas de angústia existencial urbana" },
    ],
    correctAnswer: "C",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "Antoni Gaudí foi o principal arquiteto do Art Nouveau na Espanha. Qual obra sua é considerada a mais extraordinária e ainda está inacabada?",
    tip: "É uma catedral em Barcelona que mistura formas orgânicas com simbolismo religioso e continua sendo construída até hoje.",
    funFact: "\"Você sabia?\" — A Sagrada Família de Gaudí tem previsão de conclusão para 2026 — 144 anos após o início da construção em 1882. Gaudí morreu atropelado por um bonde em 1926 e está sepultado na cripta da própria catedral que ainda não estava terminada.",
    points: 1,
    options: [
      { id: "A", text: "O Museu do Louvre em Paris, reformado por Gaudí no estilo Art Nouveau" },
      { id: "B", text: "A Sagrada Família (Basílica da Sagrada Família) em Barcelona — catedral Art Nouveau de formas orgânicas únicas" },
      { id: "C", text: "A Torre Eiffel em Paris, projetada originalmente por Gaudí como estrutura Art Nouveau" },
      { id: "D", text: "O Palácio do Parlamento em Budapeste, com decoração Art Nouveau de Gaudí" },
    ],
    correctAnswer: "B",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "O Simbolismo foi um movimento literário e artístico do final do século XIX. O que diferencia a arte simbolista das outras correntes do período?",
    tip: "Os simbolistas não queriam descrever o mundo visível — queriam evocar estados de espírito e mistérios. Como faziam isso?",
    funFact: "\"Você sabia?\" — O poeta Charles Baudelaire, com o livro 'As Flores do Mal' (1857), é considerado o precursor espiritual do Simbolismo. Sua ideia de 'sinestesia' — que cores têm sons, sons têm cheiros — influenciou profundamente a arte visual simbolista.",
    points: 1,
    options: [
      { id: "A", text: "Representação científica da realidade visual com técnica pontilhista e estudo da luz" },
      { id: "B", text: "Representação do cotidiano das classes trabalhadoras com realismo social engajado" },
      { id: "C", text: "Geometrização das formas naturais visando à abstração total das figuras" },
      { id: "D", text: "Uso de símbolos, mitos e temas oníricos para evocar emoções, mistérios e estados espirituais além do visível" },
    ],
    correctAnswer: "D",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "O pintor simbolista Gustave Moreau (1826-1898) foi mestre de Matisse e Rouault. Quais eram os temas predominantes em sua obra?",
    tip: "Moreau era fascinado por algo bem específico — figuras da mitologia e da Bíblia com uma atmosfera particular. Qual?",
    funFact: "\"Você sabia?\" — Moreau era tão recluso que a maioria de suas obras permaneceu trancada em seu ateliê até depois de sua morte. Ele legou ao Estado francês a casa-ateliê e toda a coleção, que se tornou o Museu Gustave Moreau em Paris — um dos mais extraordinários museus de artista do mundo.",
    points: 1,
    options: [
      { id: "A", text: "Temas mitológicos, bíblicos e orientais com figuras ornamentadas de joias e rodeadas de mistério decadente" },
      { id: "B", text: "Cenas do cotidiano parisiense como cafés, parques e bailes populares" },
      { id: "C", text: "Paisagens industriais e urbanas críticas ao progresso moderno francês" },
      { id: "D", text: "Nus femininos acadêmicos em poses clássicas sobre fundo neutro" },
    ],
    correctAnswer: "A",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Henri Rousseau (1844-1910), apelidado 'Le Douanier' (o aduaneiro), foi um pintor naïf (ingênuo). O que caracteriza o estilo naïf?",
    tip: "Rousseau nunca teve treinamento artístico formal — e isso aparece em sua obra de uma forma que o distingue de todos os outros.",
    funFact: "\"Você sabia?\" — Rousseau era gozado pelos intelectuais parisienses que frequentavam seus jantares. Picasso chegou a fazer uma festa de 'homenagem' a ele que era meio irônica. Mas Rousseau era genuinamente indiferente à ironia — e acreditava que era o maior pintor de Paris ao lado de Picasso.",
    points: 1,
    options: [
      { id: "A", text: "Arte técnica e sofisticada que imita propositalmente a ingenuidade infantil como recurso estilístico" },
      { id: "B", text: "Arte criada sem treinamento acadêmico formal, com perspectiva intuitiva, cores vivas e mundo pessoal encantado" },
      { id: "C", text: "Arte exclusivamente de paisagens urbanas criada por trabalhadores das classes populares" },
      { id: "D", text: "Arte de temática religiosa criada por monges e artesãos de conventos medievais" },
    ],
    correctAnswer: "B",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "As obras de Rousseau são famosas por suas selvas exóticas com animais e figuras enigmáticas. Qual aspecto de sua arte surpreende mais considerando que ele era um simples funcionário público?",
    tip: "Rousseau nunca viajou para nenhuma selva tropical — de onde vinham então suas extraordinárias imagens de jaguares, florestas e figuras exóticas?",
    funFact: "\"Você sabia?\" — Rousseau visitava o Jardim Botânico e o Museu de História Natural de Paris, onde havia plantas tropicais e espécimes taxidermizados de animais exóticos. Suas 'selvas' são, portanto, composições imaginárias baseadas em observação de segunda mão — o que as torna ainda mais extraordinárias.",
    points: 1,
    options: [
      { id: "A", text: "Rousseau viajou extensamente pela África e pela América do Sul como funcionário colonial" },
      { id: "B", text: "Rousseau tinha um ateliê no meio de uma floresta da Bretanha onde observava a natureza diariamente" },
      { id: "C", text: "Rousseau visitava o Jardim Botânico e o Museu de História Natural de Paris, estudando plantas tropicais e animais taxidermizados com obsessão" },
      { id: "D", text: "Rousseau copiou fotografias de exploradores contratados especialmente para lhe fornecer referências visuais" },
    ],
    correctAnswer: "C",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "O Dadaísmo surgiu em Zurique em 1916, durante a Primeira Guerra Mundial. O que o Dada propunha?",
    tip: "O Dada não era um estilo — era uma atitude. Era a negação radical de algo específico. O quê?",
    funFact: "\"Você sabia?\" — O nome 'Dada' foi escolhido aleatoriamente num dicionário francês-alemão, e significa 'cavalinho de madeira' em francês. Essa escolha sem sentido era proposital — repudiando qualquer racionalidade num mundo que havia produzido a guerra mais devastadora até então.",
    points: 1,
    options: [
      { id: "A", text: "A criação de uma arte nova baseada na lógica matemática e na razão científica" },
      { id: "B", text: "O retorno à arte artesanal medieval, rejeitando as máquinas da industrialização" },
      { id: "C", text: "A fusão de todas as vanguardas anteriores numa síntese internacional unificada" },
      { id: "D", text: "A negação radical da arte, da razão e dos valores burgueses — arte como antiarte, provocação e absurdo" },
    ],
    correctAnswer: "D",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "Marcel Duchamp inventou o conceito de 'ready-made'. O que é um ready-made?",
    tip: "Duchamp escolhia objetos industriais comuns e os apresentava em galerias — o que isso questionava sobre a arte?",
    funFact: "\"Você sabia?\" — Duchamp afirmou que o ato de escolher um objeto era suficiente para torná-lo arte — sem qualquer habilidade técnica ou transformação artesanal. Isso foi a mais radical redefinição do que é arte na história ocidental, e ainda hoje é debatido nas faculdades de arte do mundo todo.",
    points: 1,
    options: [
      { id: "A", text: "Um objeto industrial comum deslocado de seu contexto funcional e apresentado como obra de arte — o artista cria por escolha, não por fabricação" },
      { id: "B", text: "Uma pintura feita diretamente no local, 'pronta' para o público sem passar por ateliê" },
      { id: "C", text: "Uma escultura moldada a partir de objetos naturais encontrados sem qualquer intervenção do artista" },
      { id: "D", text: "Uma obra coletiva feita por vários artistas sem assinatura, 'pronta' desde o início" },
    ],
    correctAnswer: "A",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Marcel Duchamp enviou para uma exposição de arte em Nova York, em 1917, um urinol de porcelana branca assinado com pseudônimo 'R. Mutt'. Como essa obra se chama e o que ela provocou?",
    tip: "É um dos ready-mades mais famosos — e foi recusado pelo júri da própria exposição que deveria aceitar qualquer obra enviada.",
    funFact: "\"Você sabia?\" — A Fonte original de Duchamp foi perdida — a que se vê em museus hoje são réplicas autorizadas pelo próprio artista nos anos 1960. Em 2004, 500 críticos e historiadores de arte elegeram a Fonte como 'a obra mais influente do século XX', acima da Guernica de Picasso.",
    points: 1,
    options: [
      { id: "A", text: "Roda de Bicicleta — foi ovacionada pelo público e comprada imediatamente pelo Museu de Arte Moderna" },
      { id: "B", text: "A Fonte — gerou escândalo, foi recusada e abriu o debate radical sobre o que pode ser considerado arte" },
      { id: "C", text: "L.H.O.O.Q. — uma Mona Lisa com bigode que foi aceita e premiada com medalha de ouro" },
      { id: "D", text: "Nu Descendo uma Escada — foi recusada pelos próprios cubistas por ser excessivamente dinâmica" },
    ],
    correctAnswer: "B",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "A palavra 'Dada' foi escolhida como nome do movimento de forma deliberadamente nonsense. O que esse gesto representava?",
    tip: "Num mundo que havia produzido a Primeira Guerra Mundial, qual era o valor da 'lógica' e do 'significado' para os dadaístas?",
    funFact: "\"Você sabia?\" — O Cabaret Voltaire, onde o Dada nasceu em Zurique em 1916, era frequentado por Lenin, que morava no mesmo quarteirão. Os dadaístas e o futuro líder da Revolução Russa eram vizinhos sem se conhecer — duas revoluções diferentes gestadas no mesmo lugar.",
    points: 1,
    options: [
      { id: "A", text: "Uma homenagem à filosofia de Diderot e d'Alembert, cujos nomes começam com 'Da'" },
      { id: "B", text: "Uma referência à arte primitiva africana com raízes fonéticas em línguas bantu" },
      { id: "C", text: "O nome foi achado ao acaso num dicionário — 'dada' significa 'cavalinho de madeira' em francês, e a escolha nonsense era deliberadamente proposital" },
      { id: "D", text: "Que o fundador Tristan Tzara escolheu a palavra da região de sua cidade natal na Romênia" },
    ],
    correctAnswer: "C",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "O Dadaísmo surgiu durante a Primeira Guerra Mundial (1914-1918). Como o contexto histórico da guerra influenciou o surgimento do movimento?",
    tip: "Se a 'razão' e o 'progresso' europeu produziram o conflito mais destrutivo da história, qual deveria ser a postura da arte diante disso?",
    funFact: "\"Você sabia?\" — Zurique, capital do Dada, era neutro na guerra. Isso atraiu refugiados e exilados de toda a Europa — artistas, escritores, políticos e intelectuais fugindo do conflito. O Cabaret Voltaire era um caldeirão de ideias radicais de pessoas que tinham perdido a fé nas instituições europeias.",
    points: 1,
    options: [
      { id: "A", text: "A guerra inspirou obras heroicas e patrióticas de exaltação ao sacrifício dos soldados" },
      { id: "B", text: "A guerra não influenciou o Dada, que surgiu como resposta a questões puramente estéticas" },
      { id: "C", text: "A guerra motivou o Dada a criar arte de propaganda pacifista para convencer os líderes políticos" },
      { id: "D", text: "A barbárie da guerra levou os dadaístas a concluir que a razão ocidental era falsa e que a arte deveria responder com o absurdo e a provocação" },
    ],
    correctAnswer: "D",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "Gustav Klimt foi o maior representante do Art Nouveau austríaco. Qual característica visual mais define sua pintura?",
    tip: "Klimt usou algo muito incomum em pinturas — um material que vem de formas de vida não-animal. Qual é?",
    funFact: "\"Você sabia?\" — O ouro que Klimt usava em suas pinturas era folha de ouro real de 24 quilates, aplicada sobre a superfície pintada. A técnica foi inspirada nos mosaicos bizantinos de Ravenna que Klimt visitou e que o impressionaram profundamente pela luminosidade do ouro.",
    points: 1,
    options: [
      { id: "A", text: "O uso de folha de ouro real, padrões decorativos planos e figuras sensuais em composições simbolistas ornamentadas" },
      { id: "B", text: "Pinceladas expressionistas em espiral com cores intensas como azul e verde vibrantes" },
      { id: "C", text: "Composições cubistas com figuras fragmentadas vistas de múltiplos ângulos simultaneamente" },
      { id: "D", text: "Paisagens campestres austríacas em paleta impressionista de cores claras e luminosas" },
    ],
    correctAnswer: "A",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "Ernst Ludwig Kirchner, principal artista do grupo Die Brücke, criou obras que retratavam a vida urbana de Berlim. Como essas cenas eram representadas?",
    tip: "Kirchner não pintava a cidade moderna com admiração ou entusiasmo — qual era o tom emocional de suas obras?",
    funFact: "\"Você sabia?\" — As 'Cenas de Rua Berlinenses' de Kirchner mostram mulheres elegantes em poses angulosas com expressões vazias, em ruas que parecem ameaçadoras. Kirchner via a modernidade urbana como uma forma de alienação e desumanização — um retrato da solidão na multidão.",
    points: 1,
    options: [
      { id: "A", text: "Com entusiasmo e alegria, celebrando o progresso e a modernidade da metrópole alemã" },
      { id: "B", text: "Com figuras angulosas e cores agressivas que transmitiam a angústia, alienação e desumanização da vida urbana moderna" },
      { id: "C", text: "Com realismo fotográfico e documentário, registrando a vida cotidiana sem distorção" },
      { id: "D", text: "Com suavidade e romantismo, evocando a nostalgia pela vida rural perdida na industrialização" },
    ],
    correctAnswer: "B",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "O nome 'Fauvismo' deriva da palavra francesa 'fauves' (feras). Por que os pintores receberam esse apelido?",
    tip: "Foi um crítico de arte que criou o nome — o que havia naquelas pinturas que parecia 'selvagem' aos olhos do público de 1905?",
    funFact: "\"Você sabia?\" — O Fauvismo durou apenas três anos como movimento coeso (1905-1908). Depois, cada artista seguiu seu caminho: Matisse continuou com cores vibrantes, Derain se tornou mais clássico, Braque se uniu a Picasso no Cubismo. Foi um dos movimentos mais curtos e mais influentes da história da arte.",
    points: 1,
    options: [
      { id: "A", text: "Porque usavam pincéis feitos de pelo de animais selvagens importados da África" },
      { id: "B", text: "Porque suas obras retratavam cenas de caça e animais selvagens com intensidade realista" },
      { id: "C", text: "Porque o crítico Louis Vauxcelles, vendo em 1905 uma escultura renascentista cercada de suas pinturas explosivas, exclamou: 'Donatello entre as feras!'" },
      { id: "D", text: "Porque recusavam assinar suas obras, agindo como animais sem identidade cultural reconhecível" },
    ],
    correctAnswer: "C",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Edvard Munch foi um precursor do Expressionismo, embora norueguês e anterior ao movimento alemão. Como sua obra influenciou os expressionistas alemães?",
    tip: "Munch mostrou algo que os expressionistas alemães do século XX iriam radicalizar — o que ele demonstrou ser possível fazer com formas e cores?",
    funFact: "\"Você sabia?\" — Munch era obcecado com a morte — sua mãe e irmã morreram cedo de tuberculose, e ele próprio teve episódios de colapso nervoso. Essa obsessão alimentou toda sua arte, transformando experiências pessoais de perda e angústia em imagens universais de condição humana.",
    points: 1,
    options: [
      { id: "A", text: "Demonstrou que arte podia usar distorção e cor não-naturalista para expressar estados psicológicos internos com intensidade" },
      { id: "B", text: "Mostrou como a técnica pontilhista podia ser aplicada a temas dramáticos e existenciais" },
      { id: "C", text: "Introduziu o uso de máscaras africanas na arte europeia como fonte de primitivismo estilístico" },
      { id: "D", text: "Provou que arte puramente abstrata podia evocar emoções sem qualquer referência figurativa" },
    ],
    correctAnswer: "A",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "O Dadaísmo inventou a técnica da colagem e da fotomontagem como estratégia artística. O que essa técnica permitia?",
    tip: "Recortar imagens de jornais e revistas e juntá-las aleatoriamente — o que isso cria que a pintura tradicional não criaria?",
    funFact: "\"Você sabia?\" — Hannah Höch foi uma artista dadaísta alemã que usou a fotomontagem para fazer crítica política feroz ao governo de Weimar. Sua obra 'Recorte da Última Coleção da Cerveja Barriga da República de Weimar de Kitchen Knife Dada' (1919) é considerada uma das obras políticas mais radicais do século XX.",
    points: 1,
    options: [
      { id: "A", text: "Criar obras de precisão técnica similar à fotografia, mas com intervenção artística mínima" },
      { id: "B", text: "Reproduzir obras do passado em novas composições como homenagem às vanguardas anteriores" },
      { id: "C", text: "Produzir arte em série industrial que poderia ser vendida mais barato para o público de massa" },
      { id: "D", text: "Criar imagens que subvertiam a realidade, yuxtapondo elementos incompatíveis para criar estranhamento e crítica" },
    ],
    correctAnswer: "D",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Alphonse Mucha foi um artista tcheco que criou pôsteres de Art Nouveau para a atriz Sarah Bernhardt em Paris. O que tornou sua arte tão popular?",
    tip: "Mucha criou um estilo específico de representação feminina que se tornou icônico do Art Nouveau — o que havia de especial?",
    funFact: "\"Você sabia?\" — O pôster de Mucha para o espetáculo 'Gismonda' de Sarah Bernhardt, criado em 1894, foi tão popular que as pessoas arrancavam os pôsteres das paredes de Paris para guardar como obras de arte. Foi o primeiro caso documentado de um pôster sendo tratado como objeto artístico colecionável.",
    points: 1,
    options: [
      { id: "A", text: "Retratos hiper-realistas com técnica fotográfica que reproduzia fielmente a aparência das atrizes" },
      { id: "B", text: "Figuras femininas envolvidas em ornamentações florais sinuosas com halos decorativos e paleta suave — o estilo 'Mucha' tornou-se sinônimo de Art Nouveau" },
      { id: "C", text: "Pôsteres com letras grandes e composições geométricas de impacto visual imediato" },
      { id: "D", text: "Caricaturas expressivas com distorção proposital para capturar a personalidade das celebridades" },
    ],
    correctAnswer: "B",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "O pintor simbolista Fernand Khnopff (1858-1921) e outros simbolistas frequentemente criavam imagens enigmáticas sem explicação clara. Qual era a intenção por trás dessa ambiguidade?",
    tip: "Os simbolistas não queriam mensagens diretas — preferiam o mistério e a sugestão. Por quê?",
    funFact: "\"Você sabia?\" — O Simbolismo tinha raízes no Romantismo mas ia além: enquanto os românticos expressavam emoções identificáveis como melancolia ou terror, os simbolistas queriam criar sensações indescritíveis, estados de consciência que a linguagem não podia capturar — só a arte.",
    points: 1,
    options: [
      { id: "A", text: "Para esconder mensagens políticas subversivas das autoridades censoras" },
      { id: "B", text: "Para vender mais obras — imagens misteriosas geravam mais curiosidade e interesse do mercado" },
      { id: "C", text: "Para evocar estados de espírito e emoções inexprimíveis por palavras — a arte como sugestão e mistério, não como descrição ou narrativa" },
      { id: "D", text: "Para demonstrar que nenhum artista era capaz de criar uma obra com significado claro e definitivo" },
    ],
    correctAnswer: "C",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Matisse criou 'A Dança' (1909-1910), uma obra síntese do Fauvismo. O que caracteriza essa obra?",
    tip: "É uma imagem de alegria e vitalidade — como Matisse usou cor e forma para expressar a energia da dança?",
    funFact: "\"Você sabia?\" — O colecionador russo Sergei Shchukin encomendou dois painéis de Matisse — A Dança e A Música — para decorar a escadaria de seu palácio em Moscou. Depois da Revolução, a coleção foi confiscada pelo Estado soviético e hoje está no Museu Hermitage de São Petersburgo.",
    points: 1,
    options: [
      { id: "A", text: "Cinco figuras nuas em círculo sobre fundo de azul e verde intensos, com formas simplificadas que evocam energia primitiva e alegria vital" },
      { id: "B", text: "Bailarinas de tutu branco numa cena de bastidores da Ópera de Paris ao estilo de Degas" },
      { id: "C", text: "Uma procissão solene de figuras femininas em trajes orientais ao estilo de Ingres" },
      { id: "D", text: "Uma festa popular no campo, com dezenas de figuras numa composição pontilhista ao estilo de Seurat" },
    ],
    correctAnswer: "A",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Wassily Kandinsky, fundador do Der Blaue Reiter, foi um dos pioneiros da abstração total na pintura. Quais eram as bases teóricas de sua arte?",
    tip: "Kandinsky não era apenas intuitivo — tinha uma teoria filosófica sólida sobre a arte. O que ele acreditava sobre cor e forma?",
    funFact: "\"Você sabia?\" — Kandinsky escreveu 'Do Espiritual na Arte' (1911), um tratado sobre as relações entre cor, forma e espiritualidade. Ele acreditava que cada cor tinha um equivalente sonoro — que o amarelo era agudo como uma trombeta, o azul profundo como um violoncelo.",
    points: 1,
    options: [
      { id: "A", text: "Que a arte devia imitar a natureza o mais fielmente possível para atingir a verdade espiritual" },
      { id: "B", text: "Que apenas formas geométricas rigorosas podiam transmitir a racionalidade da espiritualidade moderna" },
      { id: "C", text: "Que cores e formas agiam diretamente na alma do espectador como notas musicais, sem necessidade de representar objetos reconhecíveis" },
      { id: "D", text: "Que a arte abstrata era uma forma de propaganda política para as massas trabalhadoras" },
    ],
    correctAnswer: "C",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "O manifesto do Der Blaue Reiter (1912), organizado por Kandinsky e Franz Marc, incluía obras de arte de diferentes culturas e épocas. Qual era a proposta dessa curadoria inusitada?",
    tip: "Ao incluir arte medieval, africana, infantil e popular ao lado de arte moderna, o manifesto sugeria algo sobre o que tornava uma obra 'artisticamente válida'.",
    funFact: "\"Você sabia?\" — Franz Marc morreu na Batalha de Verdun em 1916, com apenas 36 anos. Pouco antes de partir para a guerra, teve um pressentimento de que não voltaria. Seus últimos quadros, com cavalos em cores impossíveis, são de uma intensidade espiritual que impressiona mesmo hoje.",
    points: 1,
    options: [
      { id: "A", text: "Que apenas a arte europeia moderna tinha valor espiritual genuíno" },
      { id: "B", text: "Que a intensidade espiritual e expressiva de uma obra era mais importante que sua origem cultural ou técnica acadêmica" },
      { id: "C", text: "Que a arte africana e medieval eram inferiores e precisavam ser 'corrigidas' pela arte moderna" },
      { id: "D", text: "Que toda arte devia ser anônima, pois a autoria individual corromperia sua pureza espiritual" },
    ],
    correctAnswer: "B",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "'Nu Descendo uma Escada nº 2' (1912) de Marcel Duchamp causou escândalo inclusive entre os cubistas. Por quê?",
    tip: "Os cubistas rejeitaram a obra do próprio salão cubista — o que Duchamp fez que violava as regras não apenas da academia, mas também do Cubismo?",
    funFact: "\"Você sabia?\" — O Nu Descendo uma Escada foi recusado pelos próprios organizadores do Salon des Indépendants em 1912, que incluíam cubistas. Duchamp foi pessoalmente humilhado e se afastou do grupo. A obra triunfou no Armory Show de Nova York em 1913, onde foi chamada de 'explosão numa fábrica de telhas'.",
    points: 1,
    options: [
      { id: "A", text: "Por mostrar nudez feminina frontal numa exposição pública, violando leis de obscenidade de Nova York" },
      { id: "B", text: "Por ser pintada com técnica realista, recusando completamente a fragmentação cubista" },
      { id: "C", text: "Por combinar a fragmentação cubista com a ideia futurista do movimento no tempo, mostrando as fases de um corpo descendo uma escada" },
      { id: "D", text: "Por ser assinada com pseudônimo, recusando-se a revelar a identidade do artista" },
    ],
    correctAnswer: "C",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Arnold Böcklin (1827-1901) foi um pintor simbolista suíço. Qual obra sua se tornou a mais reproduzida da era vitoriana e influenciou inúmeros artistas?",
    tip: "É uma pintura melancólica de uma ilha rochosa e misteriosa — o título mesmo evoca silêncio e morte.",
    funFact: "\"Você sabia?\" — 'A Ilha dos Mortos' de Böcklin foi tão popular que havia reproduções em quase todos os lares burgueses alemães e suíços da virada do século. Hitler tinha uma cópia no escritório, Freud outra em sua sala de espera — a obra parecia ressonar com a angústia do fin-de-siècle europeu.",
    points: 1,
    options: [
      { id: "A", text: "'A Ilha dos Mortos' — uma ilha rochosa ao entardecer com ciprestes e uma figura encapuzada numa barca, evocando o mistério da morte" },
      { id: "B", text: "'O Beijo' — dois amantes fundidos numa composição dourada que se tornou símbolo do Art Nouveau" },
      { id: "C", text: "'O Grito' — figura em terror existencial num cais com céu ondulante em vermelho-alaranjado" },
      { id: "D", text: "'O Pecado' — serpente em jardim com figura feminina numa paleta sombria de verdes e pretos" },
    ],
    correctAnswer: "A",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "O Dadaísmo teve grande influência em movimentos posteriores. Qual movimento artístico dos anos 1920 nasceu diretamente do Dada?",
    tip: "O movimento seguinte manteve a busca pelo inconsciente e o irracional mas deu a isso um sistema teórico diferente, baseado em Freud.",
    funFact: "\"Você sabia?\" — André Breton, fundador do Surrealismo, começou como dadaísta antes de romper com o movimento. Sua crítica ao Dada era que a pura negação e o absurdo não bastavam — era preciso construir algo novo. O Surrealismo foi sua resposta: usar o inconsciente como método criativo positivo.",
    points: 1,
    options: [
      { id: "A", text: "O Construtivismo russo, que pegou a energia dadaísta e a aplicou à propaganda revolucionária" },
      { id: "B", text: "O Expressionismo Abstrato americano, que importou os dadaístas europeus durante a Segunda Guerra" },
      { id: "C", text: "O Neoplasticismo de Mondrian, que sistematizou o absurdo dadaísta em geometria rigorosa" },
      { id: "D", text: "O Surrealismo, que aprofundou a exploração do irracional e do inconsciente iniciada pelo Dada" },
    ],
    correctAnswer: "D",
  },
];
