export const questoesFisica1EmB3Av1 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "A quantidade de movimento (momento linear) p de um corpo é definida como:",
    tip: "Quantidade de movimento combina duas propriedades do objeto em movimento: sua massa e sua velocidade.",
    funFact: "\"Você sabia?\" — Um caminhão de 10 toneladas a 1 m/s tem a mesma quantidade de movimento que uma bicicleta de 10 kg a 1000 m/s. Mesma p, situações muito diferentes!",
    points: 1,
    options: [
      { id: "A", text: "p = F / t" },
      { id: "B", text: "p = m / v" },
      { id: "C", text: "p = m · v" },
      { id: "D", text: "p = F · d" },
    ],
    correctAnswer: "C",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "O teorema impulso-quantidade de movimento afirma que o impulso recebido por um corpo é igual à:",
    tip: "O impulso está relacionado à mudança do estado de movimento de um objeto. Qual grandeza vetorial descreve esse estado?",
    funFact: "\"Você sabia?\" — O airbag dos carros usa esse princípio: ao aumentar o tempo de atuação da força de parada (Δt maior), reduz a força necessária — mesmo impulso, muito menos força!",
    points: 1,
    options: [
      { id: "A", text: "Variação da quantidade de movimento (Δp = pf − pi)" },
      { id: "B", text: "Variação da energia cinética" },
      { id: "C", text: "Produto da força pelo deslocamento" },
      { id: "D", text: "Variação da energia potencial" },
    ],
    correctAnswer: "A",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "Em uma colisão perfeitamente inelástica, o que acontece aos dois objetos após o impacto?",
    tip: "Pense na colisão mais 'grudenta' possível — qual é o resultado final?",
    funFact: "\"Você sabia?\" — Colisões perfeitamente inelásticas são as que mais dissipam energia cinética em calor, som e deformação. Um acidente de carro em que os veículos ficam presos é um exemplo trágico.",
    points: 1,
    options: [
      { id: "A", text: "Ricocheteiam com velocidades iguais às iniciais" },
      { id: "B", text: "Ficam presos e se movem juntos com a mesma velocidade" },
      { id: "C", text: "Conservam a energia cinética total" },
      { id: "D", text: "Param completamente (velocidade final zero)" },
    ],
    correctAnswer: "B",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "Em um sistema sem forças externas (sistema isolado), o que se pode afirmar sobre a quantidade de movimento total?",
    tip: "Sem força resultante externa, o que diz a 1ª Lei de Newton sobre o estado de movimento do sistema?",
    funFact: "\"Você sabia?\" — A conservação do momento é a razão pela qual o recuo de uma arma existe: ao expelir a bala para frente, a arma recua para trás para conservar o momento total (inicialmente zero).",
    points: 1,
    options: [
      { id: "A", text: "Aumenta continuamente" },
      { id: "B", text: "Diminui até zero" },
      { id: "C", text: "Varia de forma imprevisível" },
      { id: "D", text: "Se conserva (permanece constante)" },
    ],
    correctAnswer: "D",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "Uma força de 30 N age sobre um objeto por 4 segundos. Qual é o impulso produzido?",
    tip: "Impulso I = F · Δt. Multiplique a força pelo intervalo de tempo.",
    funFact: "\"Você sabia?\" — 120 N·s é equivalente a um soco de boxeador profissional de curta duração (~0,02 s): a força fica em torno de 6000 N — o equivalente ao peso de 600 kg!",
    points: 1,
    options: [
      { id: "A", text: "34 N·s" },
      { id: "B", text: "7,5 N·s" },
      { id: "C", text: "120 N·s" },
      { id: "D", text: "60 N·s" },
    ],
    correctAnswer: "C",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "Um objeto de 5 kg se move com velocidade de 8 m/s. Qual é a quantidade de movimento do objeto?",
    tip: "Use p = m · v. Substitua m = 5 kg e v = 8 m/s.",
    funFact: "\"Você sabia?\" — 40 kg·m/s é a quantidade de movimento de uma bola de futebol de 0,43 kg viajando a 93 m/s (≈ 335 km/h) — um chute de bicicleta de Pelé poderia ter algo assim!",
    points: 1,
    options: [
      { id: "A", text: "40 kg·m/s" },
      { id: "B", text: "1,6 kg·m/s" },
      { id: "C", text: "80 kg·m/s" },
      { id: "D", text: "13 kg·m/s" },
    ],
    correctAnswer: "A",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "Em uma colisão elástica, qual grandeza é conservada além da quantidade de movimento?",
    tip: "Colisões elásticas são caracterizadas pela ausência de deformação permanente ou geração de calor. O que isso implica sobre a energia?",
    funFact: "\"Você sabia?\" — Colisões entre bolas de bilhar são aproximadamente elásticas. Entre partículas subatômicas (prótons, elétrons) as colisões podem ser perfeitamente elásticas!",
    points: 1,
    options: [
      { id: "A", text: "Força" },
      { id: "B", text: "Energia cinética" },
      { id: "C", text: "Aceleração" },
      { id: "D", text: "Posição" },
    ],
    correctAnswer: "B",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "Em uma colisão inelástica, o que acontece com a energia cinética total do sistema?",
    tip: "Colisões inelásticas envolvem deformação, calor, som. Pense em como isso afeta a energia cinética.",
    funFact: "\"Você sabia?\" — Na colisão inelástica, parte da energia cinética é convertida em deformação plástica dos materiais — é por isso que carros modernos têm zonas de amortecimento projetadas para absorver energia e proteger os ocupantes.",
    points: 1,
    options: [
      { id: "A", text: "Se conserva totalmente" },
      { id: "B", text: "Aumenta após a colisão" },
      { id: "C", text: "É transferida completamente para energia potencial" },
      { id: "D", text: "É parcialmente transformada em calor, som e deformação" },
    ],
    correctAnswer: "D",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "Um corpo de 2 kg tem sua velocidade alterada de 5 m/s para 15 m/s. Qual é o impulso recebido?",
    tip: "Impulso = Δp = m · Δv = m · (vf − vi). Substitua os valores.",
    funFact: "\"Você sabia?\" — 20 N·s é o impulso médio de um chute de futebol razoável. Uma bola de 0,43 kg que sai do chute a ~46 m/s recebeu exatamente esse impulso em frações de segundo.",
    points: 1,
    options: [
      { id: "A", text: "40 N·s" },
      { id: "B", text: "10 N·s" },
      { id: "C", text: "20 N·s" },
      { id: "D", text: "30 N·s" },
    ],
    correctAnswer: "C",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "Ao resolver problemas de colisão em sistema isolado, qual lei física é sempre aplicada?",
    tip: "Em sistema isolado, sem forças externas, qual lei fundamental da mecânica se aplica diretamente?",
    funFact: "\"Você sabia?\" — A conservação do momento é considerada uma das leis mais fundamentais da natureza — ela vale tanto para partículas subatômicas quanto para galáxias em colisão!",
    points: 1,
    options: [
      { id: "A", text: "Conservação da quantidade de movimento" },
      { id: "B", text: "Segunda Lei de Newton (F = ma)" },
      { id: "C", text: "Conservação da energia mecânica" },
      { id: "D", text: "Lei de Hooke (F = kx)" },
    ],
    correctAnswer: "A",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "O impulso de uma força constante F que age por um intervalo de tempo Δt é definido como:",
    tip: "Impulso relaciona força com tempo de aplicação. Qual é a operação matemática entre eles?",
    funFact: "\"Você sabia?\" — O conceito de impulso explica por que lutadores treinam a 'queda' em tatames macios: ao aumentar o tempo de impacto, reduzem a força média sofrida pelo corpo.",
    points: 1,
    options: [
      { id: "A", text: "I = F / Δt" },
      { id: "B", text: "I = F + Δt" },
      { id: "C", text: "I = F − Δt" },
      { id: "D", text: "I = F · Δt" },
    ],
    correctAnswer: "D",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Em qualquer tipo de colisão (elástica ou inelástica) num sistema isolado, qual grandeza é sempre conservada?",
    tip: "Mesmo que a energia cinética não se conserve em colisões inelásticas, há uma grandeza vetorial que sempre se conserva em sistemas isolados.",
    funFact: "\"Você sabia?\" — A conservação do momento é mais fundamental que a conservação de energia cinética: o momento se conserva em TODA colisão isolada, enquanto a Ec só se conserva nas elásticas.",
    points: 1,
    options: [
      { id: "A", text: "A energia cinética total" },
      { id: "B", text: "A quantidade de movimento total" },
      { id: "C", text: "As velocidades individuais dos corpos" },
      { id: "D", text: "A posição do centro de massa" },
    ],
    correctAnswer: "B",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "A quantidade de movimento é uma grandeza:",
    tip: "Verifique a definição p = m·v: m é escalar e v é vetorial. O produto de escalar por vetor é...",
    funFact: "\"Você sabia?\" — Por ser vetorial, a quantidade de movimento de dois objetos que se movem em sentidos opostos com mesma massa e velocidade é zero — e suas colisão perfeitamente inelástica resulta em repouso!",
    points: 1,
    options: [
      { id: "A", text: "Escalar, pois depende apenas da velocidade" },
      { id: "B", text: "Escalar, dependendo apenas da massa" },
      { id: "C", text: "Vetorial, com mesma direção e sentido da velocidade" },
      { id: "D", text: "Vetorial, com sentido oposto à velocidade" },
    ],
    correctAnswer: "C",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "Uma bola de 0,1 kg é lançada contra uma parede com velocidade de 20 m/s e para após o impacto. Qual é o módulo do impulso sofrido?",
    tip: "Impulso = |Δp| = m · |vf − vi|. A velocidade final é zero.",
    funFact: "\"Você sabia?\" — Se a bola ricocheteasse com a mesma velocidade (20 m/s), o impulso seria o dobro: 4 N·s! Paredes rígidas exercem mais impulso que paredes que absorvem o impacto.",
    points: 1,
    options: [
      { id: "A", text: "2 N·s" },
      { id: "B", text: "0,5 N·s" },
      { id: "C", text: "20 N·s" },
      { id: "D", text: "200 N·s" },
    ],
    correctAnswer: "A",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Um carro de 1000 kg a 20 m/s colide perfeitamente inelasticamente com um carro de 500 kg parado. Qual é a velocidade final dos dois carros juntos?",
    tip: "Conservação do momento: p_total = (m₁ + m₂) · vf. Calcule p_total = 1000 × 20 + 500 × 0 e divida pela massa total.",
    funFact: "\"Você sabia?\" — Essa colisão dissipa ⅓ da energia cinética inicial em calor e deformação. É por isso que batidas frontais são tão destrutivas — e por que deformação controlada salva vidas.",
    points: 1,
    options: [
      { id: "A", text: "20 m/s" },
      { id: "B", text: "10 m/s" },
      { id: "C", text: "15 m/s" },
      { id: "D", text: "≈ 13,3 m/s" },
    ],
    correctAnswer: "D",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "Dois patinadores em repouso se empurram: o de 60 kg vai para a direita a 3 m/s. Para qual direção e com qual velocidade vai o de 90 kg?",
    tip: "Momento total inicial = 0. Use conservação: 60×3 + 90×v₂ = 0. Isole v₂.",
    funFact: "\"Você sabia?\" — Essa é a 3ª Lei de Newton vista pela ótica do momento: ação e reação iguais e opostas implicam variações de momento iguais e opostas — por isso o menor vai mais rápido!",
    points: 1,
    options: [
      { id: "A", text: "Direita a 2 m/s" },
      { id: "B", text: "Esquerda a 2 m/s" },
      { id: "C", text: "Direita a 4 m/s" },
      { id: "D", text: "Esquerda a 4 m/s" },
    ],
    correctAnswer: "B",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "Em uma colisão elástica, quais grandezas se conservam simultaneamente?",
    tip: "Colisão elástica é aquela que ocorre sem dissipação de energia. Quais conservações se aplicam?",
    funFact: "\"Você sabia?\" — A colisão de nêutrons com átomos de hidrogênio no moderador de reatores nucleares é quase elástica — e é exatamente por isso que hidrogênio é tão eficaz para frear nêutrons.",
    points: 1,
    options: [
      { id: "A", text: "Apenas a quantidade de movimento" },
      { id: "B", text: "Os corpos ficam presos e conservam energia total" },
      { id: "C", text: "Tanto a quantidade de movimento quanto a energia cinética" },
      { id: "D", text: "A energia cinética se transforma em calor" },
    ],
    correctAnswer: "C",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "Um atleta de 80 kg salta de um barco de 120 kg inicialmente em repouso (sistema isolado). O atleta vai a 3 m/s para frente. Com qual velocidade o barco recua?",
    tip: "Momento inicial = 0. Use 80×3 + 120×v_barco = 0. Isole v_barco.",
    funFact: "\"Você sabia?\" — Essa é a mesma física do lançamento de foguetes: os gases ejetados para trás e o foguete seguem em direções opostas para conservar momento. No vácuo, sem nada para 'empurrar', funciona perfeitamente!",
    points: 1,
    options: [
      { id: "A", text: "2 m/s para trás" },
      { id: "B", text: "3 m/s para trás" },
      { id: "C", text: "0,5 m/s para trás" },
      { id: "D", text: "4 m/s para trás" },
    ],
    correctAnswer: "A",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "A variação da quantidade de movimento de um objeto é diretamente proporcional a qual grandeza?",
    tip: "O teorema impulso-quantidade de movimento estabelece uma igualdade entre Δp e outra grandeza. Qual?",
    funFact: "\"Você sabia?\" — Essa proporcionalidade é outra forma de escrever a 2ª Lei de Newton: F = Δp/Δt. A forma original de Newton era exatamente essa — não F = ma!",
    points: 1,
    options: [
      { id: "A", text: "À massa do objeto" },
      { id: "B", text: "À velocidade do objeto" },
      { id: "C", text: "Ao deslocamento" },
      { id: "D", text: "Ao impulso recebido" },
    ],
    correctAnswer: "D",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "Dois objetos de 2 kg cada se movem em sentidos opostos a 5 m/s e colidem perfeitamente inelasticamente. Qual é a velocidade final?",
    tip: "Quantidade de movimento total: p = 2×5 + 2×(−5). Aplique conservação do momento.",
    funFact: "\"Você sabia?\" — Essa colisão simétrica resulta em repouso e a energia cinética total (100 J) é completamente dissipada. É um exemplo extremo de dissipação máxima em colisão perfeitamente inelástica!",
    points: 1,
    options: [
      { id: "A", text: "5 m/s (na direção do primeiro)" },
      { id: "B", text: "0 m/s (sistema para)" },
      { id: "C", text: "2,5 m/s (na direção do primeiro)" },
      { id: "D", text: "10 m/s (velocidades somadas)" },
    ],
    correctAnswer: "B",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "A conservação da quantidade de movimento em colisões é uma consequência direta de qual lei de Newton?",
    tip: "Durante a colisão, os dois objetos exercem forças iguais e opostas um no outro. Qual lei descreve esse par de forças?",
    funFact: "\"Você sabia?\" — A conservação do momento é mais geral que as leis de Newton: ela vale em contextos relativísticos e quânticos onde F = ma não é mais válida, mas o momento ainda se conserva!",
    points: 1,
    options: [
      { id: "A", text: "3ª Lei de Newton (ação e reação)" },
      { id: "B", text: "1ª Lei de Newton (inércia)" },
      { id: "C", text: "2ª Lei de Newton (F = ma)" },
      { id: "D", text: "Lei da Gravitação Universal" },
    ],
    correctAnswer: "A",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Na colisão elástica entre duas bolas de mesma massa, sendo uma delas inicialmente em repouso, qual é o resultado?",
    tip: "Use conservação de momento e de energia cinética para bolas de mesma massa. O que se pode concluir algebricamente?",
    funFact: "\"Você sabia?\" — Isso é o que acontece nas colisões entre bolas de bilhar: a bola que bate para e a em repouso parte com a mesma velocidade. Newton's cradle (pêndulo de Newton) demonstra isso lindamente!",
    points: 1,
    options: [
      { id: "A", text: "As duas continuam em movimento com metade da velocidade inicial" },
      { id: "B", text: "As duas param completamente" },
      { id: "C", text: "A bola em repouso adquire a velocidade da que colide, e esta para" },
      { id: "D", text: "As duas trocam de direção mantendo suas velocidades" },
    ],
    correctAnswer: "C",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Uma força menor aplicada por mais tempo pode produzir o mesmo impulso que uma força maior por menos tempo. Qual equação descreve isso?",
    tip: "O impulso depende de dois fatores: a intensidade da força e o tempo de aplicação. Qual é a expressão matemática?",
    funFact: "\"Você sabia?\" — Esse princípio é aplicado em pára-quedas: eles aumentam o tempo de desaceleração (Δt maior), reduzindo a força de impacto — mesmo impulso para parar, mas força muito menor.",
    points: 1,
    options: [
      { id: "A", text: "I = m / Δt" },
      { id: "B", text: "I = F / Δt" },
      { id: "C", text: "I = m · Δt" },
      { id: "D", text: "I = F · Δt" },
    ],
    correctAnswer: "D",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "A colisão entre dois veículos em que ficam presos após o impacto é classificada como:",
    tip: "Essa colisão é a mais 'inelástica' possível — os objetos ficam unidos e se movem com a mesma velocidade final.",
    funFact: "\"Você sabia?\" — Em ensaios de colisão, engenheiros usam 'colisão perfeitamente inelástica' propositalmente para medir a quantidade de energia dissipada nas zonas de absorção do veículo.",
    points: 1,
    options: [
      { id: "A", text: "Colisão elástica" },
      { id: "B", text: "Colisão perfeitamente inelástica" },
      { id: "C", text: "Colisão parcialmente elástica" },
      { id: "D", text: "Colisão superelástica" },
    ],
    correctAnswer: "B",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Qual é a unidade de quantidade de movimento no Sistema Internacional (SI)?",
    tip: "A unidade de p = m·v é derivada das unidades de massa e velocidade: kg × m/s.",
    funFact: "\"Você sabia?\" — N·s também é uma unidade válida de quantidade de movimento (e de impulso): N·s = (kg·m/s²)·s = kg·m/s. As duas notações são equivalentes!",
    points: 1,
    options: [
      { id: "A", text: "kg·m/s" },
      { id: "B", text: "N·s²" },
      { id: "C", text: "kg·m/s²" },
      { id: "D", text: "J/m" },
    ],
    correctAnswer: "A",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Em um sistema isolado com dois objetos, se a quantidade de movimento do objeto 1 aumenta 30 kg·m/s, o que acontece com a quantidade de movimento do objeto 2?",
    tip: "O momento total se conserva em sistema isolado. Se um aumenta, o que deve acontecer com o outro?",
    funFact: "\"Você sabia?\" — Esse balanço de momento é a razão pela qual a Lua, ao freiar as marés da Terra, está gradualmente se afastando do nosso planeta — transferência de momento angular!",
    points: 1,
    options: [
      { id: "A", text: "Também aumenta 30 kg·m/s" },
      { id: "B", text: "Permanece igual" },
      { id: "C", text: "Diminui 30 kg·m/s" },
      { id: "D", text: "Dobra em valor absoluto" },
    ],
    correctAnswer: "C",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Uma bola de borracha de 0,5 kg bate elasticamente numa parede e volta com a mesma velocidade de 10 m/s (sentido contrário). Qual é o módulo da variação da quantidade de movimento?",
    tip: "|Δp| = m · |vf − vi|. Atenção ao sentido: vf = +10 m/s, vi = −10 m/s (ou vice-versa). Calcule a diferença.",
    funFact: "\"Você sabia?\" — O módulo de Δp numa colisão elástica com parede é o dobro de mv! É por isso que bolas que ricocheteiam exercem mais impulso nas paredes do que bolas que ficam presas nelas.",
    points: 1,
    options: [
      { id: "A", text: "0 kg·m/s" },
      { id: "B", text: "5 kg·m/s" },
      { id: "C", text: "2,5 kg·m/s" },
      { id: "D", text: "10 kg·m/s" },
    ],
    correctAnswer: "D",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Uma pistola lança uma bala de 0,01 kg que parte do repouso e sai a 400 m/s. Qual é o impulso sofrido pela bala?",
    tip: "Impulso = Δp = m · (vf − vi). Com vi = 0, o impulso é simplesmente m · vf.",
    funFact: "\"Você sabia?\" — Pela 3ª Lei, a pistola recebe o mesmo impulso (4 N·s) em sentido contrário — é o recuo ('coice') da arma. Com massa de ~0,5 kg, o recuo chega a 8 m/s!",
    points: 1,
    options: [
      { id: "A", text: "40 N·s" },
      { id: "B", text: "4 N·s" },
      { id: "C", text: "0,4 N·s" },
      { id: "D", text: "400 N·s" },
    ],
    correctAnswer: "B",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Em uma colisão elástica, a conservação da energia cinética implica que:",
    tip: "O que 'conservar' energia cinética significa matematicamente para o sistema antes e depois da colisão?",
    funFact: "\"Você sabia?\" — A palavra 'elástica' vem de materiais que não se deformam permanentemente. Borrachas ideais e molas são exemplos de materiais que promovem colisões elásticas.",
    points: 1,
    options: [
      { id: "A", text: "A energia cinética total antes e depois da colisão é igual" },
      { id: "B", text: "A energia potencial total aumenta após a colisão" },
      { id: "C", text: "Os corpos perdem velocidade após a colisão" },
      { id: "D", text: "A energia mecânica total do sistema diminui" },
    ],
    correctAnswer: "A",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Dois objetos com m₁ = 3 kg (v₁ = 4 m/s) e m₂ = 1 kg (em repouso) colidem perfeitamente inelasticamente. Qual é a velocidade final?",
    tip: "Conservação do momento: m₁v₁ + m₂v₂ = (m₁ + m₂)vf. Calcule p_total e divida pela massa total.",
    funFact: "\"Você sabia?\" — A velocidade caiu de 4 m/s para 3 m/s, mas a energia cinética caiu de 24 J para 18 J — 6 J foram dissipados. Em colisões reais isso vai para calor, som e deformação.",
    points: 1,
    options: [
      { id: "A", text: "4 m/s" },
      { id: "B", text: "1 m/s" },
      { id: "C", text: "3 m/s" },
      { id: "D", text: "2 m/s" },
    ],
    correctAnswer: "C",
  },
];
