export const questoesCiencias6AnoB3Av1 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'O que é o solo?',
    tip: 'Pensa em tudo que compõe o chão de um jardim: pedacinhos de rocha, restos de folhas, água e ar — tudo junto forma o solo.',
    funFact: 'Uma pequena quantidade de solo pode conter milhões de microrganismos vivos, invisíveis a olho nu!',
    points: 1,
    options: [
      { id: 'A', text: 'Um tipo de rocha maciça, sem nenhuma outra composição' },
      { id: 'B', text: 'Somente areia' },
      { id: 'C', text: 'Apenas água misturada com ar' },
      { id: 'D', text: 'A camada superficial da Terra, formada por rochas desgastadas, água, ar e matéria orgânica' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'O solo se forma principalmente através de:',
    tip: 'Pensa em como uma pedra grande, exposta ao sol, chuva e vento por muitos e muitos anos, vai se quebrando aos poucos.',
    funFact: 'A formação de uma camada de solo pode levar centenas ou até milhares de anos!',
    points: 1,
    options: [
      { id: 'A', text: 'Um processo instantâneo, que acontece em minutos' },
      { id: 'B', text: 'Um processo lento, chamado de intemperismo, que desgasta as rochas ao longo do tempo' },
      { id: 'C', text: 'Apenas a queda de chuva forte' },
      { id: 'D', text: 'A ação exclusiva dos seres humanos' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'O intemperismo é causado, entre outros fatores, por:',
    tip: 'Pensa em vários fatores da natureza que podem "desgastar" uma rocha aos poucos, ao longo de muito tempo.',
    funFact: 'Até as raízes das plantas ajudam no intemperismo, penetrando pequenas rachaduras nas rochas e ajudando a quebrá-las!',
    points: 1,
    options: [
      { id: 'A', text: 'Variações de temperatura, chuva, vento e ação de seres vivos' },
      { id: 'B', text: 'Apenas pela cor do solo' },
      { id: 'C', text: 'Somente pela gravidade' },
      { id: 'D', text: 'Nenhum fator natural, só ação humana' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'A camada de solo mais próxima da superfície, geralmente mais escura e rica em matéria orgânica, é chamada de:',
    tip: 'Pensa na camada mais de cima do solo, onde crescem as raízes das plantas e onde encontramos folhas em decomposição.',
    funFact: 'O solo é organizado em camadas chamadas "horizontes", e cada uma tem características diferentes!',
    points: 1,
    options: [
      { id: 'A', text: 'Rocha matriz' },
      { id: 'B', text: 'Subsolo apenas' },
      { id: 'C', text: 'Horizonte A ou camada superficial' },
      { id: 'D', text: 'Manto terrestre' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'A matéria orgânica presente no solo vem principalmente de:',
    tip: 'Pensa em folhas caídas, galhos secos e restos de animais que, com o tempo, se decompõem e se misturam ao solo.',
    funFact: 'Minhocas e outros pequenos animais ajudam bastante a decompor essa matéria orgânica, enriquecendo o solo!',
    points: 1,
    options: [
      { id: 'A', text: 'Metais e minerais apenas' },
      { id: 'B', text: 'Restos de plantas e animais em decomposição' },
      { id: 'C', text: 'Água do mar' },
      { id: 'D', text: 'Rochas vulcânicas' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'O húmus é:',
    tip: 'Pensa na cor escura de um solo de jardim bem cuidado — essa cor costuma vir dessa substância especial.',
    funFact: 'O húmus é tão rico em nutrientes que muitos jardineiros e agricultores o consideram um verdadeiro "tesouro" para o solo!',
    points: 1,
    options: [
      { id: 'A', text: 'Um tipo de rocha' },
      { id: 'B', text: 'Um metal encontrado no solo' },
      { id: 'C', text: 'Um tipo de argila pura' },
      { id: 'D', text: 'Uma substância escura formada pela decomposição de matéria orgânica, que deixa o solo mais fértil' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'Um solo rico em húmus é geralmente:',
    tip: 'Lembre que o húmus é rico em nutrientes — isso ajuda ou atrapalha o crescimento das plantas?',
    funFact: 'Hortas e jardins costumam usar composto rico em húmus justamente para melhorar a fertilidade do solo!',
    points: 1,
    options: [
      { id: 'A', text: 'Ruim para o plantio' },
      { id: 'B', text: 'Sem nenhuma utilidade' },
      { id: 'C', text: 'Mais fértil e bom para o cultivo de plantas' },
      { id: 'D', text: 'Sempre seco e arenoso' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'O solo arenoso é caracterizado por:',
    tip: 'Pensa na areia da praia — a água que cai nela escorre rapidamente entre os grãos maiores.',
    funFact: 'Por deixar a água passar rápido, o solo arenoso é usado, por exemplo, em campos de golfe, para uma boa drenagem!',
    points: 1,
    options: [
      { id: 'A', text: 'Ter grãos maiores, deixando a água passar rapidamente' },
      { id: 'B', text: 'Reter muita água, sem deixar passar' },
      { id: 'C', text: 'Ser sempre escuro e rico em nutrientes' },
      { id: 'D', text: 'Não existir na natureza' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'O solo argiloso é caracterizado por:',
    tip: 'Pensa numa massa de argila usada para modelar — ela é bem fina e retém bastante água, ficando molhada e moldável.',
    funFact: 'O solo argiloso é usado até na fabricação de tijolos e cerâmicas, por sua textura fina!',
    points: 1,
    options: [
      { id: 'A', text: 'Ter grãos muito grandes' },
      { id: 'B', text: 'Deixar a água passar rapidamente' },
      { id: 'C', text: 'Não conseguir reter nada de água' },
      { id: 'D', text: 'Ter partículas bem pequenas, retendo mais água' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'O solo é importante para os seres vivos principalmente porque:',
    tip: 'Pensa em como as plantas conseguem ficar em pé e de onde elas tiram parte de seus nutrientes para crescer.',
    funFact: 'Sem um solo saudável, seria muito difícil produzir os alimentos que chegam até nossa mesa!',
    points: 1,
    options: [
      { id: 'A', text: 'Não serve para nada' },
      { id: 'B', text: 'Serve de suporte para as plantas e fornece nutrientes para elas crescerem' },
      { id: 'C', text: 'É usado só para construir prédios' },
      { id: 'D', text: 'É feito só de plástico' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'Se um solo é bom para reter água, mas também para deixar o ar circular, ele é considerado ideal para:',
    tip: 'Pensa no que as plantas precisam para crescer bem: um pouco de água retida, mas também ar circulando nas raízes.',
    funFact: 'Um bom equilíbrio entre água e ar no solo é um dos segredos de agricultores para colheitas mais saudáveis!',
    points: 1,
    options: [
      { id: 'A', text: 'O cultivo de diversas plantas' },
      { id: 'B', text: 'Construir estradas apenas' },
      { id: 'C', text: 'Não pode ser usado para nada' },
      { id: 'D', text: 'Só serve para desertos' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'A erosão do solo é causada principalmente por:',
    tip: 'Pensa em como a chuva forte ou o vento intenso podem "levar embora" partes do solo de um terreno.',
    funFact: 'A erosão é um processo natural, mas pode ser acelerada bastante pela ação humana, como o desmatamento!',
    points: 1,
    options: [
      { id: 'A', text: 'A presença de matéria orgânica' },
      { id: 'B', text: 'A fotossíntese das plantas' },
      { id: 'C', text: 'A ação do vento e da água, que desgastam e carregam partículas do solo' },
      { id: 'D', text: 'O calor do núcleo da Terra' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'A presença de raízes de plantas no solo ajuda a:',
    tip: 'Pensa nas raízes como uma espécie de "rede" que segura o solo, evitando que ele seja facilmente carregado.',
    funFact: 'Por isso, áreas com muitas árvores costumam sofrer menos com deslizamentos de terra!',
    points: 1,
    options: [
      { id: 'A', text: 'Aumentar a erosão' },
      { id: 'B', text: 'Prevenir a erosão, segurando as partículas de solo no lugar' },
      { id: 'C', text: 'Destruir completamente o solo' },
      { id: 'D', text: 'Não tem nenhum efeito' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'O desmatamento pode aumentar a erosão do solo porque:',
    tip: 'Lembre da questão anterior: as raízes ajudam a segurar o solo. O que acontece quando as árvores (e suas raízes) são removidas?',
    funFact: 'É por isso que reflorestar áreas desmatadas ajuda tanto a recuperar a saúde do solo!',
    points: 1,
    options: [
      { id: 'A', text: 'As árvores atrapalham o crescimento do solo' },
      { id: 'B', text: 'Sem árvores, o solo fica mais fértil' },
      { id: 'C', text: 'O desmatamento não tem nenhuma relação com erosão' },
      { id: 'D', text: 'Sem as raízes das árvores para segurar o solo, ele fica mais exposto ao vento e à chuva' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'O plantio de diferentes culturas, alternando-as ao longo do tempo em um mesmo terreno, é chamado de:',
    tip: 'Pensa num agricultor que planta feijão em uma temporada e milho na temporada seguinte, no mesmo terreno.',
    funFact: 'Essa técnica é usada há séculos por agricultores para manter a terra produtiva por mais tempo!',
    points: 1,
    options: [
      { id: 'A', text: 'Desmatamento' },
      { id: 'B', text: 'Erosão' },
      { id: 'C', text: 'Rotação de culturas' },
      { id: 'D', text: 'Compactação do solo' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'A rotação de culturas ajuda a:',
    tip: 'Pensa em por que os agricultores usam essa técnica há tanto tempo — ela deve trazer algum benefício importante ao solo.',
    funFact: 'Plantas diferentes retiram e devolvem nutrientes diferentes ao solo — alternar cultivos ajuda a equilibrar isso!',
    points: 1,
    options: [
      { id: 'A', text: 'Manter a fertilidade do solo por mais tempo' },
      { id: 'B', text: 'Destruir o solo mais rapidamente' },
      { id: 'C', text: 'Aumentar a erosão' },
      { id: 'D', text: 'Não tem nenhum benefício' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'O uso excessivo de agrotóxicos no solo pode causar:',
    tip: 'Pensa nos produtos químicos usados para combater pragas — em excesso, eles podem afetar mais do que só as pragas.',
    funFact: 'Por isso, muitos agricultores estão buscando alternativas mais sustentáveis para cuidar das plantações!',
    points: 1,
    options: [
      { id: 'A', text: 'Melhora total da qualidade do solo, sem nenhum problema' },
      { id: 'B', text: 'Aumento da fertilidade natural' },
      { id: 'C', text: 'Nenhum impacto ambiental' },
      { id: 'D', text: 'Contaminação do solo e da água, prejudicando os seres vivos' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'A compostagem é um processo em que:',
    tip: 'Pensa em cascas de frutas e restos de comida que, ao invés de irem para o lixo, viram um adubo natural.',
    funFact: 'A compostagem é uma ótima forma de reaproveitar restos de comida, reduzindo o lixo e ajudando o meio ambiente!',
    points: 1,
    options: [
      { id: 'A', text: 'Se joga lixo tóxico no solo' },
      { id: 'B', text: 'Restos de alimentos e matéria orgânica são transformados em adubo natural' },
      { id: 'C', text: 'O solo é destruído propositalmente' },
      { id: 'D', text: 'Não existe nenhuma relação com o solo' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'O adubo produzido pela compostagem ajuda a:',
    tip: 'Lembre que a compostagem produz um material rico, parecido com o húmus, cheio de nutrientes.',
    funFact: 'Muitas famílias e escolas já fazem suas próprias composteiras em casa, transformando lixo orgânico em adubo!',
    points: 1,
    options: [
      { id: 'A', text: 'Enriquecer o solo com nutrientes, deixando-o mais fértil' },
      { id: 'B', text: 'Tornar o solo mais pobre' },
      { id: 'C', text: 'Aumentar a erosão' },
      { id: 'D', text: 'Poluir o solo' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'Cuidar do solo é importante porque ele é essencial para:',
    tip: 'Pensa em de onde vêm os alimentos que chegam à sua mesa — a maioria depende diretamente de um solo saudável.',
    funFact: 'Estima-se que a maior parte dos alimentos que consumimos no mundo dependem, direta ou indiretamente, de um bom solo agrícola!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas construir casas' },
      { id: 'B', text: 'Somente para fazer cerâmica' },
      { id: 'C', text: 'A produção de alimentos e a manutenção da vida na Terra' },
      { id: 'D', text: 'Nada relevante para os seres vivos' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Bernardo plantou uma muda de feijão em um vaso com solo escuro e rico em restos de folhas decompostas. Esse tipo de solo é rico em:',
    tip: 'Lembre da substância escura formada pela decomposição de matéria orgânica, que enriquece o solo.',
    funFact: 'Plantar feijão é uma atividade clássica em aulas de ciências, porque cresce rápido e é fácil de observar!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas areia' },
      { id: 'B', text: 'Húmus, que deixa o solo mais fértil' },
      { id: 'C', text: 'Somente água' },
      { id: 'D', text: 'Rochas grandes' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Bernardo notou que, em um dos vasos, a água passava muito rápido pelo solo, sem ficar retida. Esse solo provavelmente é:',
    tip: 'Lembre do tipo de solo com grãos maiores, que deixa a água escoar rapidamente.',
    funFact: 'Esse tipo de observação prática é uma ótima forma de aprender sobre os diferentes tipos de solo sem precisar de laboratório!',
    points: 1,
    options: [
      { id: 'A', text: 'Argiloso' },
      { id: 'B', text: 'Rico em húmus' },
      { id: 'C', text: 'Muito compactado' },
      { id: 'D', text: 'Arenoso, com grãos maiores' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Em outro vaso, Bernardo percebeu que a água demorava muito para escoar, deixando o solo encharcado por mais tempo. Esse solo provavelmente é:',
    tip: 'Lembre do tipo de solo com partículas bem pequenas, que retém a água por mais tempo.',
    funFact: 'Diferentes plantas se adaptam melhor a diferentes tipos de solo, dependendo de quanto elas precisam de água!',
    points: 1,
    options: [
      { id: 'A', text: 'Arenoso' },
      { id: 'B', text: 'Rochoso' },
      { id: 'C', text: 'Argiloso, com partículas bem pequenas' },
      { id: 'D', text: 'Feito só de ar' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Bernardo aprendeu na escola que, em terrenos sem árvores e com chuva forte, o solo pode ser facilmente carregado pela água. Esse fenômeno é chamado de:',
    tip: 'Lembre do nome do processo em que o vento e a água desgastam e carregam partículas do solo.',
    funFact: 'A erosão pode até mudar a paisagem ao longo de muitos anos, formando vales e desgastando montanhas!',
    points: 1,
    options: [
      { id: 'A', text: 'Erosão' },
      { id: 'B', text: 'Fotossíntese' },
      { id: 'C', text: 'Fertilização' },
      { id: 'D', text: 'Compostagem' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Bernardo ajudou a montar uma composteira na escola, juntando cascas de frutas e restos de vegetais. Com o tempo, esse material vira:',
    tip: 'Lembre do que acontece com restos de alimentos numa composteira, ao longo do tempo.',
    funFact: 'Fazer compostagem na escola é uma ótima forma de aprender ciência na prática, reduzindo o lixo ao mesmo tempo!',
    points: 1,
    options: [
      { id: 'A', text: 'Um tipo de rocha' },
      { id: 'B', text: 'Um material tóxico' },
      { id: 'C', text: 'Um tipo de plástico' },
      { id: 'D', text: 'Adubo, rico em nutrientes para as plantas' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Bernardo observou que, na horta da escola, os professores plantam vegetais diferentes em épocas diferentes no mesmo canteiro. Essa prática se chama:',
    tip: 'Lembre do nome da técnica agrícola de alternar diferentes plantios num mesmo terreno.',
    funFact: 'Hortas escolares são ótimas para aprender sobre plantio, solo e até sobre alimentação saudável!',
    points: 1,
    options: [
      { id: 'A', text: 'Erosão' },
      { id: 'B', text: 'Rotação de culturas' },
      { id: 'C', text: 'Compactação do solo' },
      { id: 'D', text: 'Desmatamento' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Bernardo aprendeu que essa prática de rotação de culturas ajuda a:',
    tip: 'Lembre do benefício principal dessa técnica para a saúde do solo ao longo do tempo.',
    funFact: 'Agricultores usam essa técnica há séculos, mostrando que é uma solução testada e eficaz!',
    points: 1,
    options: [
      { id: 'A', text: 'Manter o solo fértil por mais tempo' },
      { id: 'B', text: 'Destruir o solo rapidamente' },
      { id: 'C', text: 'Aumentar a erosão do terreno' },
      { id: 'D', text: 'Não tem nenhum efeito sobre o solo' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Na aula de ciências, Bernardo descobriu que as raízes das árvores da praça perto de sua casa ajudam a:',
    tip: 'Lembre do papel das raízes das árvores na prevenção da erosão do solo.',
    funFact: 'É por isso que áreas de encostas, mais sujeitas a deslizamentos, costumam ter bastante vegetação para proteger o solo!',
    points: 1,
    options: [
      { id: 'A', text: 'Aumentar a erosão do solo' },
      { id: 'B', text: 'Destruir completamente o solo' },
      { id: 'C', text: 'Segurar o solo no lugar, evitando que ele seja carregado pela chuva' },
      { id: 'D', text: 'Não tem nenhuma função' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Bernardo percebeu que, depois de um desmatamento em uma área próxima, o solo ficou mais exposto e começou a ser carregado com mais facilidade pela chuva. Isso mostra que:',
    tip: 'Lembre da relação entre a presença de árvores (e suas raízes) e a proteção contra a erosão.',
    funFact: 'Observar consequências reais do desmatamento, como Bernardo fez, ajuda a entender a importância da preservação ambiental!',
    points: 1,
    options: [
      { id: 'A', text: 'O desmatamento sempre melhora o solo' },
      { id: 'B', text: 'A falta de árvores pode aumentar a erosão do solo' },
      { id: 'C', text: 'Árvores não têm relação nenhuma com o solo' },
      { id: 'D', text: 'A erosão não existe de verdade' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'Ao final do simulado, Bernardo entendeu que cuidar do solo é importante porque:',
    tip: 'Pensa em tudo que Bernardo aprendeu nesse simulado: tipos de solo, erosão, compostagem, rotação de culturas... tudo relacionado à importância do solo.',
    funFact: 'Parabéns por terminar o simulado sobre o solo! Agora você já entende como ele se forma, seus tipos e por que é tão importante cuidar dele, assim como o Bernardo aprendeu em sua horta!',
    points: 1,
    options: [
      { id: 'A', text: 'O solo não serve para nada' },
      { id: 'B', text: 'Só interessa para quem trabalha na construção civil' },
      { id: 'C', text: 'O solo é infinito e nunca se esgota' },
      { id: 'D', text: 'O solo é essencial para produzir alimentos e manter a vida na Terra' },
    ],
    correctAnswer: 'D',
  },
];
