export const questoesEducacaoFisica9AnoB2Av2 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'O futebol americano é um esporte de contato muito popular nos EUA. Qual é o objetivo principal do jogo?',
    tip: 'Pense na área de pontuação no final do campo — como os pontos são marcados principalmente?',
    funFact: 'Você sabia? O futebol americano evoluiu do rugby inglês e foi codificado por Walter Camp na Universidade Yale nos anos 1880. O Super Bowl, final do campeonato da NFL, é o evento esportivo de maior audiência televisiva dos EUA — em 2023, teve 113 milhões de telespectadores. O intervalo do Super Bowl é tão famoso que alguns espectadores assistem apenas para ver as apresentações musicais.',
    points: 1,
    options: [
      { id: 'A', text: 'Chutar o maior número possível de gols durante os 4 quartos de jogo' },
      { id: 'B', text: 'Passar a bola oval para um companheiro além da linha de fundo adversária (touchdown) ou chutar entre as traves (field goal)' },
      { id: 'C', text: 'Derrubar o quarterback adversário o maior número de vezes possível' },
      { id: 'D', text: 'Acumular jardas por meio de passes aéreos exclusivamente, sem corridas com a bola' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'O rugby tem várias modalidades. Qual é a diferença entre o rugby union e o rugby league?',
    tip: 'As duas formas são parecidas, mas têm diferenças importantes no número de jogadores e nas regras de ruck.',
    funFact: 'Você sabia? O rugby foi criado em 1823 na cidade de Rugby, Inglaterra, quando um estudante chamado William Webb Ellis pegou a bola no futebol e saiu correndo com ela — pelo menos é o que diz a lenda. O troféu da Copa do Mundo de Rugby chama-se "William Webb Ellis Trophy" em sua homenagem. O Brasil tem uma seleção de rugby que participa de competições sul-americanas.',
    points: 1,
    options: [
      { id: 'A', text: 'Rugby union tem 15 jogadores por time e permite o ruck; rugby league tem 13 jogadores e usa um sistema diferente após a queda' },
      { id: 'B', text: 'Rugby union é jogado em campo aberto; rugby league é exclusivamente em ginásio coberto' },
      { id: 'C', text: 'Rugby union é amador; rugby league é a versão profissional do esporte' },
      { id: 'D', text: 'Rugby union usa bola oval; rugby league usa bola redonda similar ao futebol' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'O beisebol é o esporte nacional dos EUA e muito popular no Japão. Qual é o objetivo básico do jogo?',
    tip: 'O rebatedor tenta enviar a bola para longe e percorrer as bases — como funciona a pontuação?',
    funFact: 'Você sabia? O beisebol teve origem nas ruas de Nova York nos anos 1840, codificado por Alexander Cartwright. O lançador Nolan Ryan arremessou 100 mph (160 km/h) aos 44 anos de idade. No Japão, o beisebol é tão popular que os jogadores mais talentosos frequentemente vão para a MLB (EUA) — Shohei Ohtani (arremessador e rebatedor ao mesmo tempo) é o maior exemplo, com contrato de US$ 700 milhões em 2023.',
    points: 1,
    options: [
      { id: 'A', text: 'Rebater a bola o mais longe possível e marcar pontos percorrendo as 4 bases antes de ser eliminado' },
      { id: 'B', text: 'Lançar a bola contra o adversário e impedir que ele chegue às bases antes do apito' },
      { id: 'C', text: 'Defender 9 posições no campo e impedir que o time adversário marque usando bloqueios' },
      { id: 'D', text: 'Rebater a bola por cima da cerca do campo para marcar automaticamente 4 pontos' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'O badminton é um esporte de raquete olímpico. Qual é o objeto usado para jogar (em vez de uma bola)?',
    tip: 'É um objeto com penas que voa de forma diferente de uma bola — tem uma forma única.',
    funFact: 'Você sabia? O peteca (shuttlecock) do badminton é feito com 16 penas de ganso fixadas em uma base de cortiça. As penas de ganso da asa esquerda são melhores que da asa direita (criam rotação mais estável). O golpe de smash no badminton pode atingir 493 km/h — é o movimento mais rápido de qualquer raquete em qualquer esporte. O badminton é muito popular na Ásia: China, Indonésia e Malásia dominam mundialmente.',
    points: 1,
    options: [
      { id: 'A', text: 'Uma bola de borracha com pressão interna controlada, menor que a de tênis' },
      { id: 'B', text: 'Uma bolinha de couro com miolo de borracha, parecida com uma bola de golfe' },
      { id: 'C', text: 'Uma puck de plástico similar ao usado no hóquei no gelo' },
      { id: 'D', text: 'Uma peteca (shuttlecock) — base de cortiça com penas de ganso que voa de forma parabólica' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'O squash é um esporte de raquete jogado em uma quadra fechada. Qual é sua principal característica que o diferencia do tênis e do badminton?',
    tip: 'No squash, a bola não volta para o adversário diretamente — ela bate em alguma superfície antes.',
    funFact: 'Você sabia? O squash foi inventado por alunos da escola Harrow em Londres nos anos 1830, usando bolas que "esmagavam" (squash) contra a parede. Por décadas tentou ser incluído nas Olimpíadas e finalmente foi aprovado para os Jogos de Los Angeles 2028. O Egito domina o squash mundial: jogadores como Mohamed El Shorbagy e Nouran Gohar são os melhores do mundo.',
    points: 1,
    options: [
      { id: 'A', text: 'A bola é rebatida contra as paredes da quadra fechada, e os dois jogadores compartilham o mesmo espaço' },
      { id: 'B', text: 'A quadra é dividida por uma rede baixa e os jogadores não podem cruzar a linha central' },
      { id: 'C', text: 'O objetivo é rebater a bola no teto o maior número de vezes consecutivas' },
      { id: 'D', text: 'A bola é de borracha sólida e pode ricocheteiar indefinidamente sem perder velocidade' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'O jiu-jitsu brasileiro (BJJ) se diferencia do jiu-jitsu japonês original. Qual é a principal ênfase do BJJ?',
    tip: 'O BJJ ficou famoso por ensinar que uma pessoa menor pode derrotar uma maior — usando qual tipo de técnica?',
    funFact: 'Você sabia? O jiu-jitsu brasileiro foi criado pela família Gracie a partir das técnicas ensinadas pelo judoca Mitsuyo Maeda no Brasil nos anos 1910-20. Os irmãos Carlos e Hélio Gracie adaptaram as técnicas para que pessoas fisicamente fracas pudessem se defender. A família desafiou lutadores de todo o mundo nos "Gracies in Action" — e quase sempre venceram. Isso levou à criação do UFC em 1993, onde Royce Gracie provou a eficácia do BJJ.',
    points: 1,
    options: [
      { id: 'A', text: 'Técnicas de arremesso em pé: projetar o adversário ao chão com a menor força possível' },
      { id: 'B', text: 'Golpes com mãos e pés: usar socos e chutes poderosos para encerrar rapidamente o combate' },
      { id: 'C', text: 'Luta no chão: imobilizações, estrangulamentos e chaves articulares para submeter o adversário' },
      { id: 'D', text: 'Defesa com bloqueios: técnicas estritamente defensivas sem golpes de ataque' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'O caratê foi incluído nas Olimpíadas de Tóquio 2020 (mas não em Paris 2024). Quais são as duas modalidades do caratê olímpico?',
    tip: 'Uma é mais artística (formas coreografadas), a outra é o combate direto.',
    funFact: 'Você sabia? O caratê foi excluído dos Jogos de Paris 2024 e Los Angeles 2028 pelo COI para incluir novos esportes. A decisão causou polêmica: havia mais de 100 milhões de praticantes no mundo. O kata (forma) envolve movimentos codificados há séculos para representar combates imaginários — cada kata conta uma história de batalha. O kumite (combate) usa proteções e sistema de pontuação por golpes limpos.',
    points: 1,
    options: [
      { id: 'A', text: 'Kata (formas coreografadas) e Kumite (combate por pontos com proteções)' },
      { id: 'B', text: 'Shotokan (estilo japonês) e Kyokushin (estilo de contato total)' },
      { id: 'C', text: 'Kihon (técnica isolada) e Randori (combate livre sem regras)' },
      { id: 'D', text: 'Shobu (combate a pontos) e Tameshiwari (quebra de materiais)' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'O MMA (Mixed Martial Arts) é um esporte de combate que combina várias artes marciais. Qual foi o papel do UFC (Ultimate Fighting Championship) na popularização do MMA?',
    tip: 'O UFC começou como um torneio experimental para descobrir qual arte marcial era a mais eficiente.',
    funFact: 'Você sabia? O primeiro UFC aconteceu em 1993 em Denver, Colorado, sem regras claras (apenas proibições de cutucar olhos e golpes na virilha). Royce Gracie (BJJ) venceu lutadores de muay thai, boxe, luta olímpica e outras artes, provando que técnicas de chão eram essenciais. Hoje o UFC é o maior evento de artes marciais do mundo, com mais de 650 atletas contratados e audiências globais.',
    points: 1,
    options: [
      { id: 'A', text: 'O UFC estabeleceu regras rígidas para o MMA antes mesmo que ele se tornasse popular, garantindo sua segurança' },
      { id: 'B', text: 'O UFC foi criado originalmente como entretenimento circense sem qualquer relação com artes marciais reais' },
      { id: 'C', text: 'O UFC criou em 1993 um torneio sem regras para testar qual arte marcial era mais eficiente — popularizando o MMA ao mostrar que a combinação de estilos era superior a qualquer arte isolada' },
      { id: 'D', text: 'O UFC substituiu o boxe olímpico como esporte de combate mais assistido no mundo nos anos 1980' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'O vale-tudo brasileiro antecedeu o MMA moderno. Qual é a principal diferença entre o vale-tudo e o MMA regulamentado atual?',
    tip: 'O nome "vale-tudo" já diz tudo — qual a diferença para o MMA com regras?',
    funFact: 'Você sabia? O "vale-tudo" surgiu no Brasil nos anos 1920 com os desafios da família Gracie a lutadores de outras artes. Na década de 1990, "vale-tudo" era sinônimo de lutas sem regras transmitidas em TV a cabo no Brasil. O programa "Desafio" e eventos como WVC (World Vale Tudo Championship) precederam o UFC. Anderson Silva, Rodrigo Minotauro e outros campeões brasileiros do UFC se formaram nessa tradição.',
    points: 1,
    options: [
      { id: 'A', text: 'O vale-tudo tinha luvas obrigatórias; o MMA moderno permite combate com as mãos nuas' },
      { id: 'B', text: 'O vale-tudo tinha poucas ou nenhuma regra e pouca proteção; o MMA moderno tem regras detalhadas, árbitros, médicos e proteções obrigatórias' },
      { id: 'C', text: 'O vale-tudo só permitia lutas em pé; o MMA moderno inclui luta no chão' },
      { id: 'D', text: 'O vale-tudo era exclusivo de lutadores brasileiros; o MMA é aberto a atletas de qualquer país' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'O futebol americano tem posições especializadas. Qual é a função do quarterback?',
    tip: 'É a posição mais importante e famosa do futebol americano — literalmente o "maestro" da ofensiva.',
    funFact: 'Você sabia? O quarterback Tom Brady venceu 7 Super Bowls (6 pelo New England Patriots e 1 pelo Tampa Bay Buccaneers) — o recorde absoluto. Ele foi selecionado na 199ª rodada do Draft de 2000 (quase não foi contratado) e se tornou o maior jogador da história. O salário de um quarterback de elite pode chegar a US$ 50 milhões por ano — tornando-o o atleta mais bem pago de qualquer esporte em muitas temporadas.',
    points: 1,
    options: [
      { id: 'A', text: 'Bloquear os defensores adversários para abrir caminho para o corredor' },
      { id: 'B', text: 'Chutar o field goal e o ponto extra após o touchdown' },
      { id: 'C', text: 'Receber os passes do quarterback na extremidade do campo' },
      { id: 'D', text: 'Comandar a ofensiva: receber o snap, decidir entre correr, passar ou lançar a bola' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'No rugby, o que é um "try" e quantos pontos vale?',
    tip: 'É a forma principal de pontuação no rugby — o nome em inglês sugere "tentar" cruzar uma linha.',
    funFact: 'Você sabia? O try no rugby vale 5 pontos. Após marcar, a equipe tem a chance de um "conversion kick" (chute de conversão) entre as traves — se converter, ganha mais 2 pontos (total 7). Um drop goal (chute de campo em jogo) vale 3 pontos. Na história, o try valia apenas 1 ponto (daí o nome "try" — tentar para ganhar o chute que valia mais). O Brasil ganhou o direito de disputar o Rugby World Cup 2027 como país anfitrião.',
    points: 1,
    options: [
      { id: 'A', text: 'Um chute entre as traves adversárias, valendo 3 pontos' },
      { id: 'B', text: 'Apoiar a bola no chão após cruzar a linha de try adversária, valendo 5 pontos' },
      { id: 'C', text: 'Um passe que resulta em avanço de mais de 10 metros, valendo 2 pontos' },
      { id: 'D', text: 'Recuperar a bola após uma queda, valendo 1 ponto' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'No badminton, quais são as dimensões oficiais da quadra para um jogo de simples (um contra um)?',
    tip: 'A quadra de simples é mais estreita que a de duplas — é uma das diferenças entre os dois formatos.',
    funFact: 'Você sabia? A quadra de badminton de simples mede 13,4m x 5,18m, enquanto a de duplas é mais larga: 13,4m x 6,1m. A rede tem 1,55m nas extremidades e 1,524m no centro. O badminton exige um dos maiores deslocamentos laterais de qualquer esporte de quadra — pesquisas mostram que um jogador de elite percorre mais de 6 km durante uma partida, com mudanças de direção a cada 1-2 segundos.',
    points: 1,
    options: [
      { id: 'A', text: '13,4 metros de comprimento × 5,18 metros de largura' },
      { id: 'B', text: '23,77 metros de comprimento × 8,23 metros de largura' },
      { id: 'C', text: '18 metros de comprimento × 9 metros de largura' },
      { id: 'D', text: '10 metros de comprimento × 4 metros de largura' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'O caratê tem origem em qual país e em qual cultura?',
    tip: 'É uma arte marcial asiática — mas não é do Japão original. Qual ilha é famosa por ter originado o caratê?',
    funFact: 'Você sabia? O caratê desenvolveu-se em Okinawa, ilha hoje parte do Japão mas com história distinta. Okinawa foi um reino independente (Ryukyu) e tinha seu próprio sistema de combate chamado "te" (mãos). Quando o Japão proibiu armas em Okinawa em 1879, a população desenvolveu o "te" em um sistema completo de defesa sem armas. "Karate" significa literalmente "mãos vazias" em japonês (kara = vazio, te = mãos).',
    points: 1,
    options: [
      { id: 'A', text: 'Da China continental, especificamente do Shaolin Temple na província de Henan' },
      { id: 'B', text: 'Da Coreia, sendo uma variante do tae kwon do adaptada para uso japonês' },
      { id: 'C', text: 'Do Japão feudal, criado pelos samurais como complemento ao uso da katana' },
      { id: 'D', text: 'Da ilha de Okinawa (Reino Ryukyu), influenciado por artes marciais chinesas e adaptado ao contexto local' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'No beisebol, o que significa "home run"?',
    tip: 'É o golpe mais emocionante do beisebol — a bola vai além dos limites do campo.',
    funFact: 'Você sabia? Babe Ruth (1895-1948) foi o primeiro grande rei do home run no beisebol americano, com 714 na carreira. Barry Bonds tem o recorde moderno: 762. Um home run com todas as bases ocupadas chama-se "grand slam" e vale 4 pontos — o máximo possível em um único golpe. Shohei Ohtani é único ao ser ao mesmo tempo lançador de elite e rebatedor de home runs em nível de all-star.',
    points: 1,
    options: [
      { id: 'A', text: 'Quando o rebatedor passa pelas quatro bases sem ser eliminado devido a um erro do time adversário' },
      { id: 'B', text: 'Quando o rebatedor acerta a bola para fora do campo em jogo (além da cerca), percorrendo automaticamente as 4 bases e marcando pelo menos 1 ponto' },
      { id: 'C', text: 'Quando o corredor chega ao home plate antes de ser tocado com a bola após um rebatida normal' },
      { id: 'D', text: 'Quando o lançador consegue eliminar três rebatedores consecutivos com apenas três lançamentos' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'O MMA tem regras específicas para garantir a segurança dos atletas. Quais são os golpes proibidos no MMA moderno (UFC)?',
    tip: 'Algumas técnicas são muito perigosas mesmo para atletas profissionais — quais são proibidas?',
    funFact: 'Você sabia? O "Unified Rules of Mixed Martial Arts" foi criado em 2001 para padronizar as regras do MMA. Antes, cada evento tinha suas próprias regras. A Comissão Atlética de New Jersey (NJSAC) foi a pioneira na regulamentação. Hoje há árbitros treinados, médicos no ringue, e o árbitro pode parar a luta a qualquer momento se o atleta não puder se defender — proteção que não existia no vale-tudo original.',
    points: 1,
    options: [
      { id: 'A', text: 'Socos na cabeça, chutes no corpo e joelhadas no rosto são proibidos' },
      { id: 'B', text: 'Cutucadas nos olhos, golpes na nuca, golpes na virilha, dedos nas articulações e cotoveladas descendentes são proibidos' },
      { id: 'C', text: 'Qualquer golpe aplicado quando o adversário está no chão é proibido' },
      { id: 'D', text: 'Estrangulamentos e chaves articulares são proibidos por serem potencialmente fatais' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'O futebol americano tem uma jogada chamada "blitz". O que ela significa?',
    tip: 'É quando a defesa tenta pressionar o quarterback de forma inesperada — além do esquema normal.',
    funFact: 'Você sabia? O termo "blitz" vem do alemão "blitzkrieg" (guerra-relâmpago) — a tática nazista de ataque rápido e surpresa na Segunda Guerra Mundial. O "blitz" defensivo no futebol americano foi popularizado nos anos 1950 por treinadores que perceberam que pressionar o quarterback antes que ele pudesse passar era uma estratégia eficiente. Tom Brady era famoso por reconhecer e neutralizar blitzes — uma de suas maiores habilidades.',
    points: 1,
    options: [
      { id: 'A', text: 'Quando o quarterback decide correr com a bola em vez de fazer um passe' },
      { id: 'B', text: 'Quando a defesa envia mais jogadores do que o esperado para pressionar o quarterback imediatamente após o snap' },
      { id: 'C', text: 'Quando o time recorre a uma formação especial com 6 wide receivers para um passe longo' },
      { id: 'D', text: 'Quando o time chuta para o adversário nos últimos segundos do jogo para ganhar posição de campo' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'No rugby, o que é o "ruck"?',
    tip: 'Acontece quando um jogador vai ao chão com a bola e os adversários tentam conquistá-la.',
    funFact: 'Você sabia? O ruck é uma das fases mais físicas do rugby — jogadores empurram uns aos outros para ganhar a bola no chão. A regra diz que apenas jogadores em pé podem usar as mãos; quem cai no ruck não pode pegar a bola. A palavra "ruck" em inglês significa bagunça, confusão — bastante apropriado para a aparência dessas disputas que parecem caóticas mas têm regras precisas.',
    points: 1,
    options: [
      { id: 'A', text: 'Uma formação inicial onde os dois times se enfrentam para disputar a posse da bola no início de cada jogo' },
      { id: 'B', text: 'O chute de penalidade executado após uma falta grave no campo adversário' },
      { id: 'C', text: 'Uma disputa ao redor de um jogador derrubado com a bola, onde jogadores em pé tentam ganhar a posse empurrando' },
      { id: 'D', text: 'O espaço entre as traves onde a bola deve passar para marcar pontos' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'O jiu-jitsu brasileiro tem faixas de graduação. Qual faixa indica que o praticante atingiu o nível de mestre no BJJ?',
    tip: 'É uma faixa que mistura duas cores em um padrão específico e é rara de se ver.',
    funFact: 'Você sabia? No BJJ, obter a faixa preta leva em média 10 anos de treino intenso — muito mais do que em artes marciais como judô ou caratê. Acima da faixa preta existem as faixas coral (vermelha e preta) e vermelha, concedidas a grandíssimos mestres. Helio Gracie recebeu a faixa vermelha de 10º grau aos 90 anos. A faixa roxa (nível 3 de 5) já é considerada avançada — muitos praticantes nunca chegam lá.',
    points: 1,
    options: [
      { id: 'A', text: 'Faixa azul — concedida após 2-3 anos de treino dedicado' },
      { id: 'B', text: 'Faixa roxa — indica domínio técnico acima da média no BJJ' },
      { id: 'C', text: 'Faixa verde — indica transição entre nível intermediário e avançado' },
      { id: 'D', text: 'Faixa coral (vermelha e preta) — dada aos grandes mestres do BJJ com 7º-8º grau de faixa preta' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'No beisebol, a defesa tem 9 posições no campo. Qual delas é considerada a mais importante?',
    tip: 'É o jogador que inicia cada jogada com um lançamento — seu papel é central no jogo.',
    funFact: 'Você sabia? O arremessador (pitcher) é tão importante no beisebol que times da MLB pagam os melhores pitchers mais do que qualquer outra posição. Jacob deGrom assinou contrato de US$ 185 milhões em 2022 pelo Texas Rangers. Um bom arremessador pode praticamente sozinho derrotar um time — quando ele lança um "perfect game" (jogo perfeito: 27 rebatidas consecutivas sem nenhum chegando à base), é um dos momentos mais raros do esporte.',
    points: 1,
    options: [
      { id: 'A', text: 'O catcher (receptor) — que dirige toda a estratégia de defesa da equipe' },
      { id: 'B', text: 'O shortstop — jogador de campo que intercepta a maioria das bolas em jogo' },
      { id: 'C', text: 'O pitcher (arremessador) — que inicia cada jogada com um lançamento e tem papel central na estratégia defensiva' },
      { id: 'D', text: 'O right fielder — que cobre a maior área do campo externo' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'O squash é considerado um dos esportes com maior queima calórica. Por quê?',
    tip: 'Pense nas características do squash que tornam o esforço físico muito alto em relação a outros esportes de raquete.',
    funFact: 'Você sabia? O squash foi eleito pelo Forbes como o "esporte mais saudável do mundo" em 2003, com base em critérios como resistência cardiovascular, força muscular e flexibilidade. Em uma hora de squash, uma pessoa de 70 kg queima cerca de 850-1000 calorias — comparado a 600 no tênis. A razão: quadra fechada força movimentos constantes em todas as direções, sem pausa entre jogadas.',
    points: 1,
    options: [
      { id: 'A', text: 'O squash usa raquetes mais pesadas, exigindo mais força muscular para cada golpe' },
      { id: 'B', text: 'A quadra fechada e o jogo contínuo forçam movimentos em todas as direções sem pausas longas, gerando altíssimo gasto energético' },
      { id: 'C', text: 'A bola de squash é mais pesada que a de tênis, exigindo mais força para cada rebatida' },
      { id: 'D', text: 'Os jogadores de squash nunca param para buscar a bola, pois ela fica sempre dentro da quadra' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'O MMA moderno categoriza os lutadores por peso. Qual é o objetivo dessa divisão em categorias de peso?',
    tip: 'Pense em por que esportes de combate sempre dividem os atletas por peso corporal.',
    funFact: 'Você sabia? O UFC tem atualmente 12 categorias de peso, da palha (52 kg) ao peso pesado (até 120 kg). Mas há polêmica sobre a "secagem" (cutting weight): lutadores desidratadam até 10 kg antes da pesagem oficial e tentam recuperar o peso antes da luta. Conor McGregor era famoso por lutar como peso-pena (66 kg) e depois subir para peso-leve (70 kg) após a pesagem — uma prática considerada antiética por muitos.',
    points: 1,
    options: [
      { id: 'A', text: 'Garantir que as lutas sejam equilibradas e reduzir a vantagem de atletas maiores e mais pesados sobre menores' },
      { id: 'B', text: 'Separar atletas profissionais de amadores com base no peso corporal como indicador de experiência' },
      { id: 'C', text: 'Organizar torneios por faixa etária, já que peso e idade geralmente coincidem' },
      { id: 'D', text: 'Facilitar a logística de eventos com muitos lutadores, agrupando-os por características físicas similares' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'O futebol americano tem o "down" como unidade básica de jogo. Quantos downs um time tem para avançar 10 jardas?',
    tip: 'Se o time não conseguir avançar as jardas necessárias no número de tentativas, a bola vai para o adversário.',
    funFact: 'Você sabia? O sistema de downs foi criado em 1882 por Walter Camp, que começou com 3 downs para 5 jardas. Em 1906 mudou para 3 downs para 10 jardas, e em 1912 para 4 downs para 10 jardas — o sistema atual. Essa mecânica cria a tensão mais característica do futebol americano: o "4th and short" (4º down com poucas jardas), quando o treinador decide se tenta avançar ou se chuta para o adversário.',
    points: 1,
    options: [
      { id: 'A', text: '3 downs para avançar 10 jardas — se falhar, a bola passa para o adversário' },
      { id: 'B', text: '5 downs para avançar 15 jardas — dando mais chances de pontuação ao time ofensivo' },
      { id: 'C', text: '4 downs para avançar 10 jardas — se falhar, a bola vai para o adversário no ponto de parada' },
      { id: 'D', text: '2 downs para avançar 5 jardas — tornando o jogo mais dinâmico e com mais trocas de posse' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'No badminton, a pontuação usa o sistema rally point. O que isso significa?',
    tip: 'É uma mudança importante nas regras que aconteceu nos anos 2000 — afeta como os pontos são marcados.',
    funFact: 'Você sabia? O sistema rally point foi adotado no badminton em 2006, alterando as partidas significativamente. Antes, apenas o servidor podia marcar ponto. Com rally point, qualquer rally ganho marca ponto — independentemente de quem serviu. Isso acelerou o jogo e tornou as partidas mais imprevisíveis. Uma partida de simples masculino de alto nível dura em média 60-90 minutos com intensidade cardiovascular comparável ao futebol.',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas o time que está sacando pode marcar ponto em cada rally' },
      { id: 'B', text: 'Os pontos são marcados apenas quando a peteca cai dentro das linhas do campo adversário' },
      { id: 'C', text: 'Qualquer equipe marca ponto ao vencer um rally, independentemente de quem sacou' },
      { id: 'D', text: 'Os pontos são dobrados nos últimos 5 minutos de cada set' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'O BJJ (jiu-jitsu brasileiro) ganhou reconhecimento mundial após qual evento nos anos 1990?',
    tip: 'Foi um evento de artes marciais mistas que mostrou a eficácia do BJJ contra outras artes marciais.',
    funFact: 'Você sabia? Royce Gracie ganhou o UFC 1 (1993), UFC 2 e UFC 4 usando apenas jiu-jitsu brasileiro, derrotando lutadores de boxe, wrestling, kickboxing e outras artes sem usar nenhum golpe de pé ou soco no chão. Ele pesava apenas 82 kg e derrotou adversários que pesavam até 115 kg. Foi a maior demonstração da eficácia das técnicas de solo e hoje o BJJ é parte obrigatória de qualquer treinamento sério de MMA.',
    points: 1,
    options: [
      { id: 'A', text: 'Após a medalha de ouro do Brasil nos Jogos Pan-americanos de 1995' },
      { id: 'B', text: 'Após um campeonato mundial de jiu-jitsu realizado no Rio de Janeiro em 1996' },
      { id: 'C', text: 'Após a vitória de Royce Gracie no UFC 1 (1993) usando apenas técnicas de BJJ contra lutadores de várias artes' },
      { id: 'D', text: 'Após uma série de documentários produzidos pela família Gracie nos anos 1980' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'O rugby sevens é a versão do rugby com 7 jogadores por lado. Em que Jogos Olímpicos o rugby sevens foi incluído?',
    tip: 'Foi incluído nas Olimpíadas no século XXI — um marco para o rugby.',
    funFact: 'Você sabia? O rugby sevens olímpico nasceu nos Jogos do Rio 2016 para homens e mulheres. O Fiji ganhou o ouro masculino — sua primeira medalha olímpica de qualquer esporte na história do país! As ilhas Fiji têm apenas 900 mil habitantes mas são uma potência mundial no rugby sevens. O Brasil masculino ficou em 8º lugar no Rio e continuou desenvolvendo o esporte desde então.',
    points: 1,
    options: [
      { id: 'A', text: 'Jogos Olímpicos de Londres 2012' },
      { id: 'B', text: 'Jogos Olímpicos de Sydney 2000' },
      { id: 'C', text: 'Jogos Olímpicos de Atenas 2004' },
      { id: 'D', text: 'Jogos Olímpicos do Rio de Janeiro 2016' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'O caratê usa o conceito de "kihon". O que é kihon no contexto do treinamento de caratê?',
    tip: 'É a base de tudo — sem kihon, não há kata nem kumite de qualidade.',
    funFact: 'Você sabia? O kihon (técnicas básicas) do caratê inclui centenas de movimentos codificados. Mestre Funakoshi Gichin, o pai do caratê moderno, dizia que a base de todo o caratê estava no kihon — sem domínio das técnicas básicas, as formas avançadas eram impossíveis. Ele passou os últimos 30 anos de sua vida treinando apenas kihon, mesmo sendo o maior mestre de caratê do mundo.',
    points: 1,
    options: [
      { id: 'A', text: 'O combate livre entre dois praticantes de caratê com equipamentos de proteção completos' },
      { id: 'B', text: 'As formas coreografadas que representam combates imaginários contra múltiplos adversários' },
      { id: 'C', text: 'As técnicas básicas (socos, chutes, bloqueios, posições) praticadas repetidamente para desenvolver a base do caratê' },
      { id: 'D', text: 'O ritual de reverência e meditação feito no início e fim de cada aula de caratê' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'O futebol americano tem o "punt" como estratégia defensiva. Quando um time decide usar o punt?',
    tip: 'É quando o time prefere dar a bola ao adversário em posição desfavorável em vez de arriscar uma jogada.',
    funFact: 'Você sabia? O punt é uma das decisões mais estudadas da estatística esportiva moderna. Pesquisas mostram que times deveriam tentar o 4º down em vez de puntar muito mais frequentemente do que fazem — o medo de falhar é maior que a lógica matemática. O técnico Bill Belichick do New England Patriots era famoso por ir no 4º down em situações que outros técnicos sempre puntariam, e frequentemente tinha sucesso.',
    points: 1,
    options: [
      { id: 'A', text: 'No 1º down, para ganhar posição de campo antes de começar a atacar' },
      { id: 'B', text: 'Geralmente no 4º down com muitas jardas a percorrer, quando o time chuta a bola para o adversário começar de posição ruim' },
      { id: 'C', text: 'Após marcar um touchdown, como forma de reiniciar o jogo de posição central' },
      { id: 'D', text: 'Apenas quando o time está perdendo no último quarto, para ganhar tempo' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'No badminton, o serviço (saque) tem regras específicas. Qual é a principal regra sobre a altura do saque?',
    tip: 'Há uma limitação de altura para o saque no badminton que foi modificada recentemente.',
    funFact: 'Você sabia? Em 2018, a BWF (Badminton World Federation) introduziu uma regra revolucionária: o saque deve ser feito com a peteca no máximo a 1,15 metros do chão. Antes, a regra era relativa à cintura do jogador, difícil de fiscalizar. A mudança veio após estudos mostrarem que alguns jogadores serviam a alturas variáveis para ganhar vantagem. Em 2024, câmeras de rastreamento foram implementadas para verificar automaticamente a altura do saque em competições de elite.',
    points: 1,
    options: [
      { id: 'A', text: 'O saque pode ser feito em qualquer altura, mas a raquete deve estar abaixo da cabeça do sacador' },
      { id: 'B', text: 'O saque deve ser executado com a peteca posicionada no máximo a 1,15 metros do chão' },
      { id: 'C', text: 'Não há limite de altura para o saque, desde que seja executado de dentro da área de saque' },
      { id: 'D', text: 'O saque deve ser feito com a peteca abaixo da linha da cintura do sacador' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'No rugby, o que é o "lineout"?',
    tip: 'É uma forma de reiniciar o jogo quando a bola sai lateral — jogadores das duas equipes se posicionam de forma específica.',
    funFact: 'Você sabia? O lineout é uma das jogadas mais técnicas e estratégicas do rugby. O hooker (jogador central do scrum) arremessa a bola entre as duas fileiras de jogadores que saltam para disputar a posse. O "salto" é coordenado por companheiros que elevam o jogador — criando uma "torre humana". Times profissionais ensaiam lineouts por horas — chamadas em código para confundir o adversário sobre para onde a bola vai.',
    points: 1,
    options: [
      { id: 'A', text: 'O reinício de jogo na linha central quando nenhum time pode marcar ponto após 5 minutos' },
      { id: 'B', text: 'Uma formação com jogadores enfileirados para cobrar uma penalidade após falta grave' },
      { id: 'C', text: 'O reinício de jogo quando a bola sai pela lateral: jogadores de ambos os times se alinham perpendicularmente à linha lateral e disputam a bola arremessada pelo hooker' },
      { id: 'D', text: 'O posicionamento em linha dos três-quartos antes de um ataque pelo lado do campo' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'O beisebol tem uma posição chamada "designated hitter" (DH). O que essa posição faz?',
    tip: 'É uma posição especial que não existe em campo — um especialista para uma função específica.',
    funFact: 'Você sabia? O designated hitter foi criado pela Liga Americana (AL) dos EUA em 1973, mas a Liga Nacional (NL) resistiu por décadas — até 2022, quando a MLB padronizou a regra para todas as equipes. Isso causou grande debate no beisebol: puristas argumentavam que o pitcher devendo rebater era parte do jogo "real". O Brasil tem uma liga de beisebol amadora crescente, com forte presença da comunidade nipo-brasileira.',
    points: 1,
    options: [
      { id: 'A', text: 'Um defensor que entra apenas em innings decisivos para cobrir múltiplas posições no campo' },
      { id: 'B', text: 'Um especialista que rebate no lugar do arremessador (pitcher), que permanece apenas para arremessar sem precisar rebater' },
      { id: 'C', text: 'Um rebatedor reserva que entra apenas em situações de bases cheias (full count)' },
      { id: 'D', text: 'O rebatedor que inicia a ordem de rebatida — o primeiro a bater em cada inning' },
    ],
    correctAnswer: 'B',
  },
];
