export const questoesEducacaoFisica7AnoB1Av1 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "Quantos jogadores de cada time ficam em quadra ao mesmo tempo em uma partida oficial de voleibol?",
    tip: "Pense na formação clássica do vôlei, com jogadores divididos em linha de frente e linha de fundo, três de cada.",
    funFact: "\"Você sabia?\" — O voleibol foi criado nos Estados Unidos em 1895, como uma alternativa mais suave ao basquete!",
    points: 1,
    options: [
      { id: "A", text: "5" },
      { id: "B", text: "7" },
      { id: "C", text: "6" },
      { id: "D", text: "11" },
    ],
    correctAnswer: "C",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "No voleibol, o fundamento usado para iniciar a jogada, enviando a bola para o outro lado da quadra, é chamado de:",
    tip: "Pense no fundamento que 'abre' a jogada, feito de fora da quadra, enviando a bola para o adversário.",
    funFact: "\"Você sabia?\" — Existem vários tipos de saque no vôlei, como o saque por baixo, por cima e o saque viagem (jump serve)!",
    points: 1,
    options: [
      { id: "A", text: "Saque" },
      { id: "B", text: "Drible" },
      { id: "C", text: "Chute" },
      { id: "D", text: "Passe de ombro" },
    ],
    correctAnswer: "A",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "No handebol, quantos jogadores de cada time ficam em quadra ao mesmo tempo (sem contar o goleiro)?",
    tip: "Pense em um time parecido em tamanho com o de futsal, mas com um jogador extra: o goleiro.",
    funFact: "\"Você sabia?\" — O handebol combina elementos de basquete e futebol, usando as mãos para jogar e tentando fazer gols!",
    points: 1,
    options: [
      { id: "A", text: "5" },
      { id: "B", text: "7" },
      { id: "C", text: "11" },
      { id: "D", text: "6 (mais o goleiro)" },
    ],
    correctAnswer: "D",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "No voleibol, o fundamento usado para encaminhar a bola ao atacante, geralmente com as duas mãos acima da cabeça, é chamado de:",
    tip: "Pense no fundamento que 'prepara' a bola para o ataque, feito com as mãos acima da cabeça.",
    funFact: "\"Você sabia?\" — O levantador é considerado o 'cérebro' do time de vôlei, pois decide para qual atacante vai enviar a bola!",
    points: 1,
    options: [
      { id: "A", text: "Saque" },
      { id: "B", text: "Levantamento (ou toque)" },
      { id: "C", text: "Bloqueio" },
      { id: "D", text: "Ataque" },
    ],
    correctAnswer: "B",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "No voleibol, o fundamento usado para impedir o ataque adversário, pulando perto da rede com os braços para cima, é chamado de:",
    tip: "Pense no fundamento defensivo feito pulando perto da rede, com as mãos para cima, tentando parar a cortada do adversário.",
    funFact: "\"Você sabia?\" — Jogadores bem altos costumam se destacar no bloqueio, já que a altura ajuda a alcançar a bola mais perto da rede!",
    points: 1,
    options: [
      { id: "A", text: "Bloqueio" },
      { id: "B", text: "Saque" },
      { id: "C", text: "Manchete" },
      { id: "D", text: "Levantamento" },
    ],
    correctAnswer: "A",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "No handebol, é proibido ficar com a bola na mão por mais de:",
    tip: "Pense em um tempo bem curto — o jogador precisa decidir rápido o que fazer com a bola na mão.",
    funFact: "\"Você sabia?\" — Essa regra ajuda a manter o jogo de handebol bem rápido e dinâmico, sem que os jogadores fiquem parados demais!",
    points: 1,
    options: [
      { id: "A", text: "10 segundos" },
      { id: "B", text: "1 minuto" },
      { id: "C", text: "3 segundos" },
      { id: "D", text: "30 segundos" },
    ],
    correctAnswer: "C",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "No voleibol, o fundamento usado para receber uma bola mais baixa, com os braços estendidos e unidos, é chamado de:",
    tip: "Pense no fundamento usado para receber o saque ou uma bola baixa, com os dois braços juntos formando uma 'tábua'.",
    funFact: "\"Você sabia?\" — A técnica correta de manchete evita machucados nos braços — por isso é tão importante treinar bem esse fundamento!",
    points: 1,
    options: [
      { id: "A", text: "Saque" },
      { id: "B", text: "Manchete" },
      { id: "C", text: "Bloqueio" },
      { id: "D", text: "Ataque de cortada" },
    ],
    correctAnswer: "B",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "No handebol, o jogador que fica na posição de defender o gol é chamado de:",
    tip: "Pense na posição que fica dentro da área, protegendo o gol do próprio time, parecida com o futebol.",
    funFact: "\"Você sabia?\" — O goleiro de handebol pode usar todo o corpo, inclusive os pés, para defender, diferente de outras posições!",
    points: 1,
    options: [
      { id: "A", text: "Armador" },
      { id: "B", text: "Pivô" },
      { id: "C", text: "Ponta" },
      { id: "D", text: "Goleiro" },
    ],
    correctAnswer: "D",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "No voleibol, a rede que divide a quadra tem uma altura diferente para jogos femininos e masculinos. No masculino, ela é mais:",
    tip: "Pense na diferença de altura média entre os atletas — isso influencia na altura oficial da rede em cada categoria.",
    funFact: "\"Você sabia?\" — A rede masculina fica a 2,43 metros de altura, enquanto a feminina fica a 2,24 metros!",
    points: 1,
    options: [
      { id: "A", text: "Baixa" },
      { id: "B", text: "Larga" },
      { id: "C", text: "Alta" },
      { id: "D", text: "Estreita" },
    ],
    correctAnswer: "C",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "No handebol, quando um jogador anda ou corre com a bola sem quicá-la, isso é chamado de infração conhecida como:",
    tip: "Pense em uma regra parecida com a do basquete, que limita quantos passos o jogador pode dar sem quicar a bola.",
    funFact: "\"Você sabia?\" — No handebol, o jogador pode dar até 3 passos com a bola na mão antes de precisar quicá-la, passá-la ou arremessá-la!",
    points: 1,
    options: [
      { id: "A", text: "Passos (ou passada)" },
      { id: "B", text: "Bloqueio" },
      { id: "C", text: "Saque" },
      { id: "D", text: "Levantamento" },
    ],
    correctAnswer: "A",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Durante um jogo de voleibol, um jogador recebe o saque adversário com os braços unidos e estendidos para cima. Esse fundamento é chamado de:",
    tip: "Pense no fundamento usado especificamente para receber o saque, com os braços formando uma 'tábua' firme.",
    funFact: "\"Você sabia?\" — Uma boa manchete é essencial para começar bem a jogada — se a recepção falhar, fica difícil organizar o ataque depois!",
    points: 1,
    options: [
      { id: "A", text: "Saque" },
      { id: "B", text: "Manchete" },
      { id: "C", text: "Bloqueio" },
      { id: "D", text: "Levantamento" },
    ],
    correctAnswer: "B",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Em uma partida de handebol, um jogador segura a bola e dá vários passos sem quicá-la no chão. Qual infração ele cometeu?",
    tip: "Pense na regra que limita os passos sem quicar a bola — ela tem um nome específico, já estudado antes.",
    funFact: "\"Você sabia?\" — Essa regra existe para manter o jogo dinâmico, incentivando passes e jogadas em equipe em vez de corridas longas com a bola!",
    points: 1,
    options: [
      { id: "A", text: "Bloqueio" },
      { id: "B", text: "Saque irregular" },
      { id: "C", text: "Dupla contagem" },
      { id: "D", text: "Passos (ou passada)" },
    ],
    correctAnswer: "D",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "No voleibol, depois que a equipe recebe o saque, geralmente o próximo toque é o levantamento, feito para preparar qual fundamento?",
    tip: "Pense na sequência lógica do vôlei: recepção, levantamento e depois o golpe forte na bola. Qual fundamento vem depois do levantamento?",
    funFact: "\"Você sabia?\" — Essa sequência de três toques (recepção, levantamento, ataque) é tão clássica que é ensinada desde as primeiras aulas de vôlei!",
    points: 1,
    options: [
      { id: "A", text: "O saque" },
      { id: "B", text: "O bloqueio" },
      { id: "C", text: "O ataque" },
      { id: "D", text: "A defesa" },
    ],
    correctAnswer: "C",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "Em uma partida de handebol, dois jogadores adversários pulam perto da rede para impedir um ataque com os braços para cima. Isso é chamado de:",
    tip: "Pense no fundamento defensivo feito com salto e braços para cima, tentando impedir o arremesso adversário.",
    funFact: "\"Você sabia?\" — No handebol, o bloqueio pode ser feito tanto pelos jogadores de linha quanto, em alguns casos, ajudando o goleiro!",
    points: 1,
    options: [
      { id: "A", text: "Bloqueio" },
      { id: "B", text: "Saque" },
      { id: "C", text: "Passe de ombro" },
      { id: "D", text: "Drible" },
    ],
    correctAnswer: "A",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "No voleibol, quando um time comete um erro, como deixar a bola cair no próprio lado, o ponto é marcado para:",
    tip: "Pense em como funciona a contagem de pontos no vôlei moderno — todo erro, de qualquer time, gera ponto para o outro lado.",
    funFact: "\"Você sabia?\" — Esse sistema é chamado de 'rally point', em que toda jogada termina em ponto, mesmo que o time não esteja sacando!",
    points: 1,
    options: [
      { id: "A", text: "O próprio time que errou" },
      { id: "B", text: "Ninguém, o ponto é anulado" },
      { id: "C", text: "O árbitro decide depois" },
      { id: "D", text: "O time adversário" },
    ],
    correctAnswer: "D",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "Em uma partida de handebol, o jogador que costuma ficar próximo à área do goleiro adversário, de costas para o gol, geralmente ocupa a posição de:",
    tip: "Pense na posição que fica bem próxima à área adversária, de costas para o gol, tentando criar espaço para os companheiros.",
    funFact: "\"Você sabia?\" — O pivô no handebol precisa ser bem forte fisicamente, pois costuma receber marcação intensa dos defensores adversários!",
    points: 1,
    options: [
      { id: "A", text: "Goleiro" },
      { id: "B", text: "Pivô" },
      { id: "C", text: "Ponta" },
      { id: "D", text: "Armador" },
    ],
    correctAnswer: "B",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "No voleibol, para que uma cortada (ataque forte) seja bem-sucedida, geralmente o levantamento precisa ser feito de forma:",
    tip: "Pense em como o atacante precisa da bola numa altura e posição exatas para conseguir golpeá-la com força e precisão.",
    funFact: "\"Você sabia?\" — Levantadores profissionais treinam anos para conseguir colocar a bola na posição ideal para diferentes tipos de atacantes!",
    points: 1,
    options: [
      { id: "A", text: "Precisa, na altura certa para o atacante" },
      { id: "B", text: "Totalmente aleatória" },
      { id: "C", text: "Sempre muito baixa" },
      { id: "D", text: "Direto para o campo adversário" },
    ],
    correctAnswer: "A",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "Em uma partida de handebol, após o goleiro defender a bola, ele pode iniciar um contra-ataque rápido lançando a bola para um companheiro. Essa jogada rápida é chamada de:",
    tip: "Pense no nome que descreve uma jogada rápida feita logo depois de uma defesa, aproveitando a desorganização do adversário.",
    funFact: "\"Você sabia?\" — O contra-ataque no handebol é uma das jogadas mais emocionantes, pois pode terminar em gol em poucos segundos!",
    points: 1,
    options: [
      { id: "A", text: "Bloqueio defensivo" },
      { id: "B", text: "Saque lateral" },
      { id: "C", text: "Contra-ataque" },
      { id: "D", text: "Passe de ombro apenas" },
    ],
    correctAnswer: "C",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "No voleibol, o fundamento usado quando um jogador salta e golpeia a bola com força para o campo adversário é chamado de:",
    tip: "Pense no fundamento ofensivo mais forte do vôlei, feito com um salto e um golpe potente na bola.",
    funFact: "\"Você sabia?\" — Alguns ataques profissionais de vôlei podem atingir velocidades de mais de 100 km/h!",
    points: 1,
    options: [
      { id: "A", text: "Manchete" },
      { id: "B", text: "Ataque (cortada)" },
      { id: "C", text: "Bloqueio" },
      { id: "D", text: "Saque" },
    ],
    correctAnswer: "B",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "Em uma partida de handebol, a linha que o atacante não pode ultrapassar ao arremessar, próxima à área do goleiro, é chamada de:",
    tip: "Pense na linha que marca o limite da área do goleiro, que os jogadores de linha não podem invadir.",
    funFact: "\"Você sabia?\" — Essa linha é desenhada em forma de semicírculo ao redor do gol, formando a área protegida do goleiro!",
    points: 1,
    options: [
      { id: "A", text: "Linha de fundo" },
      { id: "B", text: "Linha lateral" },
      { id: "C", text: "Linha de saque" },
      { id: "D", text: "Linha de área (dos 6 metros)" },
    ],
    correctAnswer: "D",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Bernardo jogou vôlei na escola e recebeu o saque adversário com os braços unidos, estendidos para cima. Qual fundamento ele usou?",
    tip: "Pense no fundamento usado especificamente para receber o saque, formando uma 'tábua' firme com os braços.",
    funFact: "\"Você sabia?\" — Receber bem o saque é considerado a base de um bom jogo de vôlei — sem isso, fica difícil organizar o ataque!",
    points: 1,
    options: [
      { id: "A", text: "Manchete" },
      { id: "B", text: "Bloqueio" },
      { id: "C", text: "Ataque" },
      { id: "D", text: "Saque" },
    ],
    correctAnswer: "A",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Bernardo jogou handebol e, sem perceber, andou com a bola na mão por mais tempo do que o permitido sem quicá-la. Qual infração ele cometeu?",
    tip: "Pense na regra que limita os passos com a bola na mão sem quicar — foi estudada em questões anteriores desta prova.",
    funFact: "\"Você sabia?\" — Essa regra ajuda a manter o handebol um jogo dinâmico, baseado em passes e trabalho de equipe!",
    points: 1,
    options: [
      { id: "A", text: "Bloqueio irregular" },
      { id: "B", text: "Saque errado" },
      { id: "C", text: "Passos (ou passada)" },
      { id: "D", text: "Dupla contagem" },
    ],
    correctAnswer: "C",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Durante um jogo de vôlei, Bernardo pulou perto da rede com os braços para cima para tentar impedir o ataque do time adversário. Qual fundamento ele usou?",
    tip: "Pense no fundamento defensivo feito perto da rede, com salto e braços para cima.",
    funFact: "\"Você sabia?\" — Um bom bloqueio pode até mudar o rumo de uma partida, desanimando o time atacante adversário!",
    points: 1,
    options: [
      { id: "A", text: "Saque" },
      { id: "B", text: "Bloqueio" },
      { id: "C", text: "Manchete" },
      { id: "D", text: "Levantamento" },
    ],
    correctAnswer: "B",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Bernardo jogou handebol como goleiro durante uma partida na escola. Qual é a função principal dessa posição?",
    tip: "Pense na função principal dessa posição, parecida com a do goleiro de futebol.",
    funFact: "\"Você sabia?\" — No handebol, o goleiro pode usar os pés para defender, algo que não é permitido para os jogadores de linha!",
    points: 1,
    options: [
      { id: "A", text: "Atacar o gol adversário" },
      { id: "B", text: "Fazer o saque inicial" },
      { id: "C", text: "Ficar no meio da quadra" },
      { id: "D", text: "Defender o gol do próprio time" },
    ],
    correctAnswer: "D",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Bernardo levantou a bola com as duas mãos acima da cabeça para preparar o ataque de um colega durante o jogo de vôlei. Qual fundamento ele usou?",
    tip: "Pense no fundamento que 'prepara' a bola para o ataque, feito com as mãos acima da cabeça.",
    funFact: "\"Você sabia?\" — Um bom levantador precisa ter ótima noção de espaço para colocar a bola no lugar certo para cada atacante!",
    points: 1,
    options: [
      { id: "A", text: "Saque" },
      { id: "B", text: "Bloqueio" },
      { id: "C", text: "Levantamento (toque)" },
      { id: "D", text: "Manchete" },
    ],
    correctAnswer: "C",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Bernardo fez um saque forte no início de uma jogada de vôlei, enviando a bola para o lado adversário. Qual fundamento ele usou?",
    tip: "Pense no fundamento que 'abre' cada jogada no vôlei, feito de fora da quadra.",
    funFact: "\"Você sabia?\" — Um saque bem forte pode até ser considerado um 'ponto direto' se o adversário não conseguir recebê-lo!",
    points: 1,
    options: [
      { id: "A", text: "Saque" },
      { id: "B", text: "Bloqueio" },
      { id: "C", text: "Ataque" },
      { id: "D", text: "Manchete" },
    ],
    correctAnswer: "A",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Durante o jogo de handebol, Bernardo arremessou a bola para o gol de uma posição próxima à área do goleiro, mas sem ultrapassar a linha permitida. Qual linha ele respeitou?",
    tip: "Pense na linha em formato de semicírculo que protege a área do goleiro, estudada em questões anteriores.",
    funFact: "\"Você sabia?\" — Se um jogador de linha pisar dentro dessa área durante o ataque, a jogada pode ser anulada pelo árbitro!",
    points: 1,
    options: [
      { id: "A", text: "Linha de fundo" },
      { id: "B", text: "Linha lateral" },
      { id: "C", text: "Linha de saque" },
      { id: "D", text: "Linha de área (dos 6 metros)" },
    ],
    correctAnswer: "D",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Bernardo jogou como pivô em uma partida de handebol, ficando de costas para o gol adversário, próximo à área. Qual é a característica dessa posição?",
    tip: "Pense na posição que já foi explicada: fica perto do gol adversário, criando espaço e recebendo marcação forte.",
    funFact: "\"Você sabia?\" — Jogar de pivô exige bastante força física, pois o jogador costuma disputar espaço corporalmente com os defensores!",
    points: 1,
    options: [
      { id: "A", text: "Defender o próprio gol" },
      { id: "B", text: "Ficar próximo à área adversária, de costas para o gol" },
      { id: "C", text: "Fazer apenas o saque" },
      { id: "D", text: "Ficar fora da quadra" },
    ],
    correctAnswer: "B",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Bernardo tentou fazer uma cortada no vôlei, saltando e golpeando a bola com força para o campo adversário. Qual fundamento ele usou?",
    tip: "Pense no fundamento ofensivo mais potente do vôlei, feito com salto e golpe forte na bola.",
    funFact: "\"Você sabia?\" — A cortada é um dos fundamentos mais espetaculares do vôlei, arrancando aplausos da torcida quando bem executada!",
    points: 1,
    options: [
      { id: "A", text: "Ataque (cortada)" },
      { id: "B", text: "Manchete" },
      { id: "C", text: "Bloqueio" },
      { id: "D", text: "Saque" },
    ],
    correctAnswer: "A",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Depois de defender a bola, o goleiro do time de Bernardo lançou rapidamente a bola para um companheiro avançar pela quadra. Como se chama essa jogada rápida?",
    tip: "Pense no nome da jogada rápida feita logo após uma defesa, aproveitando a desorganização do adversário.",
    funFact: "\"Você sabia?\" — Esse tipo de jogada é tão valorizado no handebol que muitos times treinam especificamente para aproveitar esses momentos!",
    points: 1,
    options: [
      { id: "A", text: "Bloqueio defensivo" },
      { id: "B", text: "Saque lateral" },
      { id: "C", text: "Contra-ataque" },
      { id: "D", text: "Passos permitidos" },
    ],
    correctAnswer: "C",
  },
];
