export const questoesIngles7AnoB4Av1 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "Which phrase do we use to talk about future plans?",
    tip: "As outras palavras falam do passado. Qual expressão fala sobre algo que ainda vai acontecer?",
    funFact: "\"Going to\" é uma das formas mais usadas no inglês falado para falar do futuro, mais até do que \"will\" em muitas situações!",
    points: 1,
    options: [
      { id: "A", text: "Did" },
      { id: "B", text: "Was" },
      { id: "C", text: "Going to" },
      { id: "D", text: "Ago" },
    ],
    correctAnswer: "C",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "Complete: \"I ___ going to visit my cousin next weekend.\"",
    tip: "O sujeito é \"I\" (eu). Qual forma do verbo \"to be\" combina com \"I\"?",
    funFact: "\"I am\" quase sempre é reduzido para \"I'm\" no inglês do dia a dia!",
    points: 1,
    options: [
      { id: "A", text: "am" },
      { id: "B", text: "is" },
      { id: "C", text: "are" },
      { id: "D", text: "was" },
    ],
    correctAnswer: "A",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "Choose the correct structure for \"going to\".",
    tip: "Pense em \"I am going to play\". A estrutura é: sujeito + am/is/are + going to + verbo (sem \"-ing\"). Qual opção mostra isso certinho?",
    funFact: "\"Going to\" é tão usado informalmente que muita gente fala \"gonna\" no lugar, como em \"I'm gonna play\"!",
    points: 1,
    options: [
      { id: "A", text: "Subject + going to + verb+ing" },
      { id: "B", text: "Subject + verb to be + going + verb" },
      { id: "C", text: "Subject + will + going to" },
      { id: "D", text: "Subject + verb to be + going to + verb" },
    ],
    correctAnswer: "D",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "Which word do we use for quick decisions or predictions, often without \"to\"?",
    tip: "Pense em alguém decidindo algo na hora, de repente: \"Ok, I ___ help you!\" Qual palavra combina?",
    funFact: "\"Will\" é uma palavra tão antiga no inglês que já existia há mais de mil anos, bem antes do inglês moderno!",
    points: 1,
    options: [
      { id: "A", text: "Going" },
      { id: "B", text: "Will" },
      { id: "C", text: "Was" },
      { id: "D", text: "Did" },
    ],
    correctAnswer: "B",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "Complete: \"She ___ going to study English next year.\"",
    tip: "\"She\" é terceira pessoa do singular. Qual forma do verbo \"to be\" combina com \"she\"?",
    funFact: "Estudar um novo idioma, como o inglês, ajuda o cérebro a criar novas conexões neurais — é um ótimo exercício mental!",
    points: 1,
    options: [
      { id: "A", text: "is" },
      { id: "B", text: "am" },
      { id: "C", text: "are" },
      { id: "D", text: "was" },
    ],
    correctAnswer: "A",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "Choose the correct sentence using \"will\".",
    tip: "Depois de \"will\", o verbo fica na forma simples, sem \"to\", sem \"-ing\" e sem \"-s\". Qual opção segue essa regra?",
    funFact: "Depois de \"will\", o verbo NUNCA muda, não importa se é \"I\", \"she\" ou \"they\" — sempre na forma base!",
    points: 1,
    options: [
      { id: "A", text: "I will going to the party" },
      { id: "B", text: "I will to go to the party" },
      { id: "C", text: "I will go to the party" },
      { id: "D", text: "I will goes to the party" },
    ],
    correctAnswer: "C",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "Which sentence shows a future plan with \"going to\"?",
    tip: "Procure a frase que tem a estrutura \"verbo to be + going to + verbo\". Qual opção tem isso?",
    funFact: "\"Going to\" costuma ser usado quando já existe um plano ou intenção decidida antes de falar!",
    points: 1,
    options: [
      { id: "A", text: "We will play soccer" },
      { id: "B", text: "We are going to play soccer" },
      { id: "C", text: "We played soccer" },
      { id: "D", text: "We play soccer" },
    ],
    correctAnswer: "B",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "Complete: \"They ___ going to travel to Europe this summer.\"",
    tip: "\"They\" é plural. Qual forma do verbo \"to be\" combina com \"they\"?",
    funFact: "A Europa tem 44 países diferentes — por isso é um destino tão popular para quem gosta de conhecer culturas diferentes!",
    points: 1,
    options: [
      { id: "A", text: "is" },
      { id: "B", text: "am" },
      { id: "C", text: "was" },
      { id: "D", text: "are" },
    ],
    correctAnswer: "D",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "Choose the correct negative sentence with \"going to\".",
    tip: "Para negar frases com \"going to\", colocamos \"not\" depois do verbo \"to be\" (am/is/are). Qual opção faz isso certo?",
    funFact: "\"Amn't\" não existe em inglês padrão — por isso usamos sempre \"I'm not\" para negar frases com \"I\"!",
    points: 1,
    options: [
      { id: "A", text: "I amn't going to go" },
      { id: "B", text: "I not going to go" },
      { id: "C", text: "I'm not going to go" },
      { id: "D", text: "I don't going to go" },
    ],
    correctAnswer: "C",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "Which word often comes after \"will\" in a sentence?",
    tip: "Pense em \"I will play\", \"she will go\", \"they will eat\" — qual forma do verbo aparece sempre depois de \"will\"?",
    funFact: "Essa regra simplifica muito a gramática: depois de \"will\", o verbo nunca muda, seja qual for o sujeito da frase!",
    points: 1,
    options: [
      { id: "A", text: "a verb (base form)" },
      { id: "B", text: "a verb+ing" },
      { id: "C", text: "a verb+ed" },
      { id: "D", text: "to + verb" },
    ],
    correctAnswer: "A",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Complete: \"Look at those clouds! It ___ rain soon.\"",
    tip: "A frase mostra uma evidência visível AGORA (as nuvens). Quando temos uma pista visível no presente, usamos \"going to\", não \"will\".",
    funFact: "Nuvens escuras e carregadas, chamadas \"cumulonimbus\", são as que mais indicam chuva forte se aproximando!",
    points: 1,
    options: [
      { id: "A", text: "will rain" },
      { id: "B", text: "is going to rain" },
      { id: "C", text: "rains" },
      { id: "D", text: "raining" },
    ],
    correctAnswer: "B",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Complete: \"I promise I ___ help you with your homework.\"",
    tip: "A palavra \"promise\" (promessa) é uma pista forte! Promessas e decisões espontâneas geralmente usam \"will\", não \"going to\".",
    funFact: "Em inglês, \"I promise I will...\" é uma das formas mais usadas para fazer promessas sinceras!",
    points: 1,
    options: [
      { id: "A", text: "am going to" },
      { id: "B", text: "is going to" },
      { id: "C", text: "are going to" },
      { id: "D", text: "will" },
    ],
    correctAnswer: "D",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "Complete: \"Based on the weather forecast, it ___ be sunny tomorrow.\"",
    tip: "\"Based on the weather forecast\" (baseado na previsão do tempo) é uma evidência concreta — isso pede \"going to\", não \"will\".",
    funFact: "Previsões do tempo usam satélites e radares para calcular as chances de chuva ou sol com bastante precisão!",
    points: 1,
    options: [
      { id: "A", text: "will" },
      { id: "B", text: "am going to" },
      { id: "C", text: "is going to" },
      { id: "D", text: "are going to" },
    ],
    correctAnswer: "C",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "Complete: \"I think our team ___ win the game.\"",
    tip: "\"I think\" mostra uma opinião, sem evidência concreta — isso é típico do uso de \"will\" para previsões pessoais.",
    funFact: "Usamos \"will\" para opiniões e \"going to\" para evidências — essa é uma das diferenças mais importantes entre os dois!",
    points: 1,
    options: [
      { id: "A", text: "will" },
      { id: "B", text: "is going to" },
      { id: "C", text: "are going to" },
      { id: "D", text: "am going to" },
    ],
    correctAnswer: "A",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Complete: \"She has already bought the tickets. She ___ go to the concert.\"",
    tip: "\"She has already bought the tickets\" mostra um plano JÁ decidido antes — isso pede \"going to\", com \"is\" (pois \"she\" é singular).",
    funFact: "Comprar os ingressos com antecedência costuma garantir melhores preços e lugares em shows e eventos!",
    points: 1,
    options: [
      { id: "A", text: "will" },
      { id: "B", text: "is going" },
      { id: "C", text: "are going to" },
      { id: "D", text: "is going to" },
    ],
    correctAnswer: "D",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "Complete: \"Watch out! That glass ___ fall!\"",
    tip: "\"Watch out!\" mostra que algo está acontecendo bem na frente dos seus olhos AGORA — isso pede \"going to\", não \"will\".",
    funFact: "Reflexos rápidos, como pegar algo antes que caia, são controlados por uma parte do cérebro chamada cerebelo!",
    points: 1,
    options: [
      { id: "A", text: "will fall" },
      { id: "B", text: "is going to fall" },
      { id: "C", text: "falls" },
      { id: "D", text: "falling" },
    ],
    correctAnswer: "B",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "Complete: \"I promise I ___ call you tonight.\"",
    tip: "De novo a palavra \"promise\"! Promessas combinam com \"will\", lembra?",
    funFact: "Cumprir promessas é uma das bases da confiança entre amigos — por isso \"I will\" carrega um compromisso forte!",
    points: 1,
    options: [
      { id: "A", text: "will" },
      { id: "B", text: "am going to" },
      { id: "C", text: "is going to" },
      { id: "D", text: "are going to" },
    ],
    correctAnswer: "A",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "Complete: \"They have already planned their trip. They ___ go to the beach next month.\"",
    tip: "\"They have already planned\" mostra um plano já decidido. \"They\" é plural, então usamos \"are going to\".",
    funFact: "Praias brasileiras estão entre os destinos de viagem mais procurados do mundo, principalmente no verão!",
    points: 1,
    options: [
      { id: "A", text: "will" },
      { id: "B", text: "am going to" },
      { id: "C", text: "are going to" },
      { id: "D", text: "is going to" },
    ],
    correctAnswer: "C",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "Complete: \"I'm so thirsty. I ___ drink some water.\"",
    tip: "\"I'm so thirsty\" mostra uma decisão espontânea, tomada na hora — isso pede \"will\", não \"going to\".",
    funFact: "O corpo humano pode perder até 1 litro de água por dia só respirando e suando, mesmo sem fazer exercícios!",
    points: 1,
    options: [
      { id: "A", text: "am going to" },
      { id: "B", text: "will" },
      { id: "C", text: "is going to" },
      { id: "D", text: "are going to" },
    ],
    correctAnswer: "B",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "Complete: \"Based on these dark clouds, it ___ going to storm.\"",
    tip: "\"It\" (referindo-se ao tempo/clima) é sempre acompanhado de \"is\" no presente. Qual opção é essa forma do verbo \"to be\"?",
    funFact: "Tempestades fortes, com muitos raios, são chamadas de \"thunderstorms\" em inglês!",
    points: 1,
    options: [
      { id: "A", text: "will" },
      { id: "B", text: "am" },
      { id: "C", text: "are" },
      { id: "D", text: "is" },
    ],
    correctAnswer: "D",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Bernardo has already packed his bag for the school trip tomorrow. Which sentence shows his plan?",
    tip: "Se o Bernardo já arrumou a mochila, isso é um plano certo, decidido antes — combina com \"going to\", não com \"will\" (que soa mais incerto, como em \"maybe\").",
    funFact: "Passeios escolares são ótimas oportunidades para aprender fora da sala de aula, de um jeito mais divertido!",
    points: 1,
    options: [
      { id: "A", text: "Bernardo is going to go on a school trip tomorrow" },
      { id: "B", text: "Bernardo will go on a school trip tomorrow, maybe" },
      { id: "C", text: "Bernardo goes on a school trip tomorrow" },
      { id: "D", text: "Bernardo went on a school trip tomorrow" },
    ],
    correctAnswer: "A",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Bernardo looks outside and sees dark clouds. He says a prediction based on what he sees. Which sentence is correct?",
    tip: "A questão já avisa: é uma previsão baseada em uma evidência visível (nuvens escuras). Isso pede \"going to\".",
    funFact: "Quando o céu fica com nuvens bem escuras, dizemos em inglês que o tempo está \"overcast\"!",
    points: 1,
    options: [
      { id: "A", text: "It will rain" },
      { id: "B", text: "It rain going to" },
      { id: "C", text: "It is going to rain" },
      { id: "D", text: "It rained" },
    ],
    correctAnswer: "C",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Bernardo's friend asks for help, and Bernardo decides immediately: \"Don't worry, I'll help you!\" Which structure did he use?",
    tip: "\"I'll\" é a forma reduzida de \"I will\". Qual estrutura ele usou para fazer essa decisão espontânea?",
    funFact: "\"I'll\" é tão comum no inglês falado que aparece em quase toda conversa informal, no lugar de \"I will\"!",
    points: 1,
    options: [
      { id: "A", text: "going to" },
      { id: "B", text: "will" },
      { id: "C", text: "simple present" },
      { id: "D", text: "simple past" },
    ],
    correctAnswer: "B",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Bernardo's family has already booked a hotel for their vacation next month. Which sentence shows this planned future?",
    tip: "A frase diz que o hotel já foi reservado (\"has already booked\") — isso é um plano certo, e por isso usamos \"going to\" no futuro, não o passado nem o \"will\".",
    funFact: "Reservar hotéis com antecedência costuma garantir preços melhores e mais opções de quarto!",
    points: 1,
    options: [
      { id: "A", text: "We will book a hotel" },
      { id: "B", text: "We book a hotel" },
      { id: "C", text: "We booked a hotel" },
      { id: "D", text: "We are going to stay at a hotel" },
    ],
    correctAnswer: "D",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Bernardo already has tickets to the amusement park next Saturday. Which sentence is correct?",
    tip: "Se ele já tem os ingressos, é um plano decidido com antecedência — isso pede \"going to\", não \"will\" nem passado.",
    funFact: "Os primeiros parques de diversões surgiram na Europa, há mais de 400 anos, com os chamados \"pleasure gardens\"!",
    points: 1,
    options: [
      { id: "A", text: "Bernardo will go to the amusement park" },
      { id: "B", text: "Bernardo goes to the amusement park" },
      { id: "C", text: "Bernardo is going to go to the amusement park" },
      { id: "D", text: "Bernardo went to the amusement park" },
    ],
    correctAnswer: "C",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Bernardo makes a quick promise to his mom: \"I ___ clean my room before dinner.\"",
    tip: "É uma promessa feita na hora, de repente. Isso combina com \"will\", lembra da regrinha?",
    funFact: "Manter o quarto organizado é associado, segundo pesquisas, a uma mente mais tranquila e focada!",
    points: 1,
    options: [
      { id: "A", text: "will" },
      { id: "B", text: "am going to" },
      { id: "C", text: "is going to" },
      { id: "D", text: "are going to" },
    ],
    correctAnswer: "A",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Bernardo's teacher announced that the class trip is already scheduled for next Friday. Which sentence is correct?",
    tip: "\"Already scheduled\" (já agendado) mostra um plano certo e decidido — isso pede \"going to\", não um \"will\" incerto como em \"maybe\".",
    funFact: "Viagens escolares costumam ser planejadas com meses de antecedência pelos professores!",
    points: 1,
    options: [
      { id: "A", text: "The class will travel next Friday, maybe" },
      { id: "B", text: "The class travels next Friday" },
      { id: "C", text: "The class traveled next Friday" },
      { id: "D", text: "The class is going to travel next Friday" },
    ],
    correctAnswer: "D",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Bernardo sees his little sister about to drop her ice cream. He quickly says: \"Watch out, it ___ fall!\"",
    tip: "Ele está vendo o sorvete quase caindo AGORA, na frente dele — isso é uma evidência visível, que pede \"going to\".",
    funFact: "O sorvete de casquinha foi popularizado em uma feira mundial nos Estados Unidos, em 1904!",
    points: 1,
    options: [
      { id: "A", text: "will" },
      { id: "B", text: "is going to" },
      { id: "C", text: "are going to" },
      { id: "D", text: "am going to" },
    ],
    correctAnswer: "B",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Bernardo hasn't decided yet, but he says: \"Maybe I ___ play video games later.\"",
    tip: "A palavra \"maybe\" (talvez) mostra que ele ainda não decidiu com certeza — isso combina com \"will\", usado para coisas mais incertas.",
    funFact: "Jogar videogame com moderação pode até ajudar a melhorar reflexos e coordenação, segundo alguns estudos!",
    points: 1,
    options: [
      { id: "A", text: "will" },
      { id: "B", text: "am going to" },
      { id: "C", text: "is going to" },
      { id: "D", text: "are going to" },
    ],
    correctAnswer: "A",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Bernardo's whole family has already planned a trip to Disney next year, with tickets bought. Which sentence shows this?",
    tip: "Ingressos já comprados e viagem já planejada = plano certo, decidido com antecedência. Isso pede \"going to\", não \"will\" nem passado.",
    funFact: "A Disney World, na Flórida, é um dos parques temáticos mais visitados do mundo, recebendo milhões de visitantes por ano!",
    points: 1,
    options: [
      { id: "A", text: "We will go to Disney" },
      { id: "B", text: "We go to Disney" },
      { id: "C", text: "We are going to go to Disney" },
      { id: "D", text: "We went to Disney" },
    ],
    correctAnswer: "C",
  },
];
