export const questoesPortugues1EmB4Av2 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'O cultismo é um dos dois grandes estilos do Barroco literário. Qual é a principal característica do cultismo e como ele se manifesta na poesia de Gregório de Matos?',
    tip: 'O nome "cultismo" tem a ver com "culto" — uma linguagem refinada e difícil. O que esse estilo prioriza: a forma das palavras ou o raciocínio das ideias?',
    funFact: 'Você sabia? O cultismo é chamado de "Gongorismo" em homenagem ao poeta espanhol Luís de Góngora (1561-1627), seu maior representante. Góngora escrevia com tamanha complexidade que poetas rivais diziam que seria preciso um dicionário para ler seus versos. Gregório de Matos conhecia bem a obra de Góngora e a usou como modelo.',
    points: 1,
    options: [
      { id: 'A', text: 'O cultismo privilegia a elaboração formal da linguagem — uso de vocabulário raro e erudito, latinismos, hipérbatos (inversões da ordem normal das palavras), metáforas complexas e jogos sonoros que tornam o texto ornamentado e difícil' },
      { id: 'B', text: 'O cultismo privilegia o raciocínio engenhoso, com argumentação surpreendente e jogos de ideias paradoxais' },
      { id: 'C', text: 'O cultismo é um estilo simples e direto, voltado para o povo, usando linguagem cotidiana' },
      { id: 'D', text: 'O cultismo foi exclusivo da prosa religiosa, nunca aparecendo em poesia' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'O conceptismo é o outro grande estilo do Barroco literário, típico dos sermões do Padre Antônio Vieira. Qual é a principal característica do conceptismo?',
    tip: 'O nome "conceptismo" vem de "conceito" — a ideia engenhosa. O que esse estilo prioriza em relação ao cultismo?',
    funFact: 'Você sabia? O conceptismo é chamado de "Quevedismo" em homenagem ao espanhol Francisco de Quevedo (1580-1645), seu maior mestre. Enquanto Góngora (cultismo) exibia a beleza das palavras, Quevedo exibia a agudeza do raciocínio. Vieira conhecia ambos e levou o conceptismo ao seu nível mais sofisticado em língua portuguesa.',
    points: 1,
    options: [
      { id: 'A', text: 'O conceptismo usa linguagem ornamentada com muitas metáforas elaboradas e vocabulário difícil' },
      { id: 'B', text: 'O conceptismo é característico da poesia épica, nunca aparecendo em prosa ou sermões' },
      { id: 'C', text: 'O conceptismo valoriza a simplicidade e a objetividade, típica do texto jornalístico moderno' },
      { id: 'D', text: 'O conceptismo privilegia o jogo de ideias, com argumentação engenhosa, raciocínios surpreendentes, paradoxos e silogismos que partem de uma imagem e chegam a uma conclusão inesperada — o "conceito" como arma intelectual' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'A antítese é um recurso muito usado no Barroco. No verso "Sou brando e sou cruel, sou manso e sou esquivo", há uma antítese. Por que essa figura é especialmente adequada para a expressão barroca?',
    tip: 'O Barroco vive de contradições. Por que colocar opostos lado a lado num mesmo verso é a expressão perfeita da visão de mundo barroca?',
    funFact: 'Você sabia? O uso intenso de antíteses no Barroco não é apenas estético — é filosófico. O filósofo Nicholas of Cusa (1401-1464) desenvolveu o conceito de "coincidentia oppositorum" (coincidência dos opostos) — a ideia de que Deus e a realidade são apreendidos pelos contrastes. O Barroco tornou essa ideia filosófica em arte.',
    points: 1,
    options: [
      { id: 'A', text: 'A antítese barroca é apenas um recurso retórico decorativo, sem relação com a visão de mundo' },
      { id: 'B', text: 'A antítese é usada no Barroco para simplificar ideias complexas, tornando-as mais fáceis de entender' },
      { id: 'C', text: 'A antítese é adequada ao Barroco porque expressa literalmente a visão de mundo dualista barroca — o ser humano dividido entre forças opostas (Deus/mundo, espírito/carne, razão/paixão), vivendo numa tensão permanente entre extremos' },
      { id: 'D', text: 'A antítese é uma figura exclusiva do Barroco, não encontrada em outros períodos literários' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'O paradoxo barroco vai além da antítese. Como o paradoxo se distingue da antítese e por que é tão frequente no Barroco?',
    tip: 'A antítese apenas coloca opostos lado a lado. O paradoxo vai mais longe — ele une esses opostos num pensamento que parece absurdo mas é profundo. Qual é essa diferença?',
    funFact: 'Você sabia? "Amor é fogo que arde sem se ver" de Camões é um paradoxo — fogo que arde sem ser visto é fisicamente impossível, mas emocionalmente verdadeiro. Essa tensão entre o impossível físico e o verdadeiro emocional é justamente o que o paradoxo barroco captura: realidades que a lógica não alcança, mas o coração conhece.',
    points: 1,
    options: [
      { id: 'A', text: 'A antítese opõe dois termos contrários; o paradoxo vai além: une os opostos numa afirmação que parece logicamente impossível mas revela uma verdade mais profunda sobre a condição humana' },
      { id: 'B', text: 'A antítese e o paradoxo são exatamente a mesma figura, apenas com nomes diferentes' },
      { id: 'C', text: 'O paradoxo barroco é uma antítese ampliada, usada apenas em poesia, nunca em prosa' },
      { id: 'D', text: 'O paradoxo é uma figura retórica que contradiz a realidade para fazer rir — é uma forma de ironia' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'O Barroco literário se opõe ao Classicismo em vários aspectos. Qual é a diferença mais fundamental entre as estéticas barroca e clássica?',
    tip: 'O Classicismo valorizava equilíbrio, clareza e harmonia. O Barroco rejeitou esses ideais. O que o Barroco colocou no lugar deles?',
    funFact: 'Você sabia? A palavra "barroco" tem origem incerta — pode vir do português "barroco" (pérola irregular) ou do espanhol "berrucco" (pedra irregular). De qualquer forma, a metáfora é perfeita: enquanto o Classicismo era como uma pérola perfeita e redonda, o Barroco era como uma pérola irregular, deformada, surpreendente. O "defeito" tornou-se a virtude.',
    points: 1,
    options: [
      { id: 'A', text: 'O Barroco rompe com o equilíbrio, a clareza e a harmonia clássicas em favor da tensão, do excesso, da ornamentação, do dinamismo e da expressão das contradições humanas — priorizando o impacto emocional sobre a razão ordenadora' },
      { id: 'B', text: 'O Barroco e o Classicismo têm exatamente os mesmos valores — apenas diferem nos temas tratados' },
      { id: 'C', text: 'O Barroco é mais simples e popular que o Classicismo, que era elitista e difícil' },
      { id: 'D', text: 'O Barroco rejeita completamente a religião, enquanto o Classicismo era profundamente religioso' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'O Arcadismo é o período literário que sucede o Barroco no Brasil. Em que século ele se desenvolveu e quais são seus marcos históricos no contexto brasileiro?',
    tip: 'O Arcadismo brasileiro está associado a um período muito específico da história colonial. Em que século e em que região do Brasil ele floresceu?',
    funFact: 'Você sabia? O Arcadismo brasileiro tem uma particularidade única no mundo: está diretamente ligado à Inconfidência Mineira de 1789. Nenhum outro movimento literário no mundo foi tão diretamente associado a uma conspiração política. Os poetas árcades eram também os inconfidentes — a literatura e a política eram inseparáveis.',
    points: 1,
    options: [
      { id: 'A', text: 'No século XVI, com a chegada dos primeiros colonizadores e jesuítas ao Brasil' },
      { id: 'B', text: 'No século XIX, com a Independência do Brasil em 1822' },
      { id: 'C', text: 'No século XX, com o Modernismo de 1922' },
      { id: 'D', text: 'Principalmente no século XVIII, com seu epicentro em Vila Rica (Minas Gerais), durante o ciclo do ouro — período de prosperidade econômica que permitiu o florescimento cultural na colônia' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'Cláudio Manuel da Costa (1729-1789) é considerado o precursor do Arcadismo no Brasil. Qual é sua obra mais importante e qual é seu pseudônimo árcade?',
    tip: 'Os poetas árcades adotavam pseudônimos pastorais latinos. Qual era o pseudônimo e a principal obra de Cláudio Manuel da Costa?',
    funFact: 'Você sabia? Cláudio Manuel da Costa foi o único dos poetas inconfidentes que morreu durante o processo da Inconfidência — foi encontrado morto em sua cela em junho de 1789, antes do julgamento. A causa oficial foi suicídio, mas muitos historiadores suspeitam de assassinato. Sua morte silenciou para sempre a sua versão dos fatos.',
    points: 1,
    options: [
      { id: 'A', text: 'Sua obra mais importante é "Marília de Dirceu" e seu pseudônimo é Dirceu' },
      { id: 'B', text: 'Sua obra mais importante é o "Auto da Barca do Inferno" e seu pseudônimo é Glauceste' },
      { id: 'C', text: 'Cláudio Manuel da Costa é o autor das "Obras" (1768), coletânea de sonetos e poemas épicos, e seu pseudônimo árcade era Glauceste Satúrnio — pioneiro ao adaptar o estilo árcade italiano ao contexto mineiro' },
      { id: 'D', text: 'Sua obra mais importante é "Cartas Chilenas" e seu pseudônimo é Critilo' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'Tomás Antônio Gonzaga (1744-1810?) é o maior nome do Arcadismo brasileiro. Por que ele é considerado o poeta mais importante desse período?',
    tip: 'Gonzaga escreveu a obra árcade mais famosa da literatura brasileira. Qual é ela e por que ela é tão importante?',
    funFact: 'Você sabia? Tomás Antônio Gonzaga foi condenado pela Inconfidência Mineira e exilado em Moçambique, onde viveu até morrer. Sua poesia de exílio em Moçambique (ainda pouco estudada) revela um homem destroçado pelo destino, longe de tudo que amava. O destino de Gonzaga é uma das histórias mais trágicas da literatura brasileira.',
    points: 1,
    options: [
      { id: 'A', text: 'Gonzaga é o mais importante por ter sido o primeiro a escrever em língua portuguesa no Brasil' },
      { id: 'B', text: 'Tomás Antônio Gonzaga é o maior nome do Arcadismo por "Marília de Dirceu" (1792) — a coleção de liras que se tornou o mais célebre livro de poesia do período colonial — e pelas "Cartas Chilenas", sátira política de grande audácia' },
      { id: 'C', text: 'Gonzaga é o mais importante por ter fundado a Academia Brasílica dos Esquecidos em Salvador' },
      { id: 'D', text: 'Gonzaga é o mais importante por ter escrito a primeira epopeia sobre a colonização do Brasil' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: '"Marília de Dirceu" é a obra central do Arcadismo brasileiro. Qual é o conteúdo e o contexto de composição dessa obra?',
    tip: 'Pense na história por trás do livro: quem são Marília e Dirceu, e em que circunstâncias Gonzaga escreveu esses poemas?',
    funFact: 'Você sabia? Marília era o pseudônimo árcade de Maria Doroteia Joaquina de Seixas, uma jovem mineira que Gonzaga amava e com quem planejava se casar. Quando ele foi preso pela Inconfidência, ela esperou fielmente por ele durante os anos do processo — mas não pôde acompanhá-lo no exílio. Ficou em Minas e nunca mais o viu.',
    points: 1,
    options: [
      { id: 'A', text: '"Marília de Dirceu" é um conjunto de liras (poemas) escritas por Gonzaga (Dirceu) para sua amada Marília, expressando o amor feliz antes da prisão e a dor da separação após a prisão — um dos mais belos registros do amor e do exílio na literatura brasileira' },
      { id: 'B', text: '"Marília de Dirceu" é uma epopeia sobre as navegações portuguesas, escrita em homenagem à família Marília' },
      { id: 'C', text: '"Marília de Dirceu" é uma obra de teatro barroca com personagens pastorais' },
      { id: 'D', text: '"Marília de Dirceu" é um tratado filosófico sobre o amor platônico, inspirado na filosofia de Platão' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'O Arcadismo tem um conjunto específico de características estéticas e temáticas. Qual das alternativas apresenta corretamente as principais características do movimento?',
    tip: 'O Arcadismo reage contra o Barroco. Pense no que ele valoriza em oposição ao exagero e à angústia barrocos.',
    funFact: 'Você sabia? O nome "Arcadismo" vem da Arcádia, uma região da Grécia antiga famosa por sua beleza natural e pela vida simples e feliz de seus pastores. Os humanistas renascentistas transformaram a Arcádia em símbolo do paraíso perdido — o lugar ideal onde viver em harmonia com a natureza e sem as complicações da vida urbana.',
    points: 1,
    options: [
      { id: 'A', text: 'Valorização do exagero ornamental, da angústia religiosa e do dualismo espírito/carne' },
      { id: 'B', text: 'Ruptura com todas as formas tradicionais, inovação absoluta e experimentação formal' },
      { id: 'C', text: 'Primazia do sentimento individual, exaltação da natureza selvagem e melancolia romântica' },
      { id: 'D', text: 'Pastoralismo (vida no campo como ideal), razão iluminista, equilíbrio formal, imitação dos clássicos greco-latinos, uso de pseudônimos pastorais e reação contra o excesso barroco' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'O Arcadismo tem forte ligação com o Iluminismo europeu do século XVIII. Qual é o elemento iluminista mais presente no Arcadismo literário?',
    tip: 'O Iluminismo valorizava a razão acima de tudo. Como esse valor iluminista da razão se manifesta na estética e nos temas dos poetas árcades?',
    funFact: 'Você sabia? O filósofo iluminista Voltaire e o poeta árcade Gonzaga viveram no mesmo século e compartilhavam ideais: ceticismo em relação às instituições tradicionais, valorização da razão, crença no progresso humano. Não é coincidência que os poetas árcades brasileiros fossem também os conspiradores da Inconfidência — o Iluminismo inspirava tanto a arte quanto a política.',
    points: 1,
    options: [
      { id: 'A', text: 'O elemento iluminista mais presente é a crença no sobrenatural e no milagre divino' },
      { id: 'B', text: 'O elemento iluminista mais presente é o sentimentalismo exacerbado e a valorização das emoções sobre a razão' },
      { id: 'C', text: 'O elemento iluminista mais presente é a valorização da razão como guia da existência — o ideal árcade de uma vida simples e regrada pela razão, longe dos excessos emocionais e materiais, reflete a fé iluminista na razão ordenadora' },
      { id: 'D', text: 'O elemento iluminista mais presente é a valorização do progresso industrial e da ciência aplicada' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'O bucolismo ou pastoralismo é uma das marcas mais características do Arcadismo. O que ele representa e como aparece na poesia árcade?',
    tip: '"Bucólico" vem do grego e se relaciona com pastores e campos. Por que os poetas árcades — que viviam em cidades — escreviam como se fossem pastores?',
    funFact: 'Você sabia? O pastoralismo árcade era completamente artificial — uma convenção literária, não uma realidade vivida. Os poetas que escreviam sobre pastores e ovelhas eram advogados, juízes e magistrados que nunca tinham pastoreado ovelhas na vida. Mas a convenção servia a um propósito: criar um espaço imaginário de pureza e simplicidade em contraste com a vida urbana corrupta.',
    points: 1,
    options: [
      { id: 'A', text: 'O bucolismo árcade expressa uma crítica à vida rural e um elogio à sofisticação urbana' },
      { id: 'B', text: 'O bucolismo ou pastoralismo é a convenção literária árcade de ambientar os poemas no campo, com pastores, ovelhas e fontes — criando um espaço idealizado de inocência, simplicidade e amor puro em contraste com a corrupção e artificialidade da vida cortesã' },
      { id: 'C', text: 'O bucolismo árcade é uma descrição realista do campo brasileiro do século XVIII' },
      { id: 'D', text: 'O bucolismo é exclusivo do Arcadismo europeu, não aparecendo na poesia árcade brasileira' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'O cultismo de Gregório de Matos se manifesta de forma especialmente intensa em qual parte de sua obra?',
    tip: 'Gregório de Matos escrevia três tipos de poesia: religiosa, lírica e satírica. Em qual delas o cultismo — com vocabulário elaborado e metáforas complexas — aparecia com mais força?',
    funFact: 'Você sabia? A poesia lírica amorosa de Gregório de Matos era fortemente cultista — cheia de hipérbatos, metáforas gongoristas e vocabulário latinizado. Mas nas sátiras, ele usava uma linguagem completamente diferente: direta, popular, cheia de palavrões e gírias da Bahia colonial. A mesma pessoa, dois estilos radicalmente diferentes.',
    points: 1,
    options: [
      { id: 'A', text: 'O cultismo aparece com mais força na poesia lírica e religiosa de Gregório, onde ele usa metáforas elaboradas, hipérbatos e vocabulário erudito latinizado para criar um efeito de refinamento e dificuldade expressiva' },
      { id: 'B', text: 'O cultismo aparece principalmente nas sátiras, onde Gregório usa palavras complicadas para atacar seus inimigos' },
      { id: 'C', text: 'O cultismo de Gregório aparece exclusivamente em seus textos em prosa, não em poesia' },
      { id: 'D', text: 'Gregório de Matos não era cultista — era exclusivamente conceptista, como Padre Vieira' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'A Inconfidência Mineira (1789) é o evento histórico mais importante associado ao Arcadismo brasileiro. Qual é a relação entre o movimento literário e a conspiração política?',
    tip: 'Não é coincidência que os poetas árcades fossem também os inconfidentes. Qual é o elo entre a estética árcade e a ideologia política da Inconfidência?',
    funFact: 'Você sabia? Tiradentes não era poeta, mas Cláudio Manuel da Costa, Tomás Antônio Gonzaga e Alvarenga Peixoto — todos inconfidentes — eram poetas árcades. O ideal iluminista que inspirava sua arte (razão, liberdade, igualdade) era o mesmo que os levou a conspirar contra a Coroa. A execução de Tiradentes e o exílio dos poetas marcou o fim do Arcadismo brasileiro.',
    points: 1,
    options: [
      { id: 'A', text: 'Não há relação — o Arcadismo literário e a Inconfidência Mineira foram movimentos completamente independentes' },
      { id: 'B', text: 'A relação é apenas geográfica: ambos aconteceram em Minas Gerais, mas por coincidência' },
      { id: 'C', text: 'Os poetas árcades eram todos a favor da Coroa Portuguesa e se opunham à Inconfidência' },
      { id: 'D', text: 'Os mesmos ideais iluministas que fundamentavam a estética árcade (razão, liberdade individual, critica ao poder arbitrário) alimentaram politicamente a Inconfidência Mineira — e muitos poetas árcades foram também inconfidentes, mostrando como arte e política eram inseparáveis' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'Em "Marília de Dirceu", Gonzaga usa os pseudônimos pastorais "Dirceu" (para ele) e "Marília" (para a amada). Quem era a pessoa real por trás do pseudônimo "Marília"?',
    tip: 'Os pseudônimos árcades eram convenções literárias, mas apontavam para pessoas reais. Qual era o nome real da Marília de Gonzaga?',
    funFact: 'Você sabia? Maria Doroteia Joaquina de Seixas ficou conhecida na história como "A Marília de Dirceu" — o pseudônimo literário apagou seu nome real para a posteridade. Ela viveu até 1853 — mais de 60 anos depois que Gonzaga foi preso — e nunca mais se casou, guardando lealdade ao amado exilado. Uma das histórias de amor mais trágicas da história brasileira.',
    points: 1,
    options: [
      { id: 'A', text: '"Marília" era o pseudônimo de uma personagem completamente fictícia, sem referente real' },
      { id: 'B', text: '"Marília" era o pseudônimo árcade da mãe de Gonzaga, que o inspirou poeticamente' },
      { id: 'C', text: '"Marília" era o pseudônimo árcade de Maria Doroteia Joaquina de Seixas, a jovem mineira com quem Gonzaga planejava se casar antes de ser preso pela Inconfidência' },
      { id: 'D', text: '"Marília" era o pseudônimo de uma poetisa rival que competia com Gonzaga nas academias literárias de Vila Rica' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'O Arcadismo reagiu contra o Barroco valorizando a razão e o equilíbrio. Como essa reação se manifesta na forma e no conteúdo dos poemas árcades?',
    tip: 'Compare o estilo barroco (excessivo, angustiado, ornamentado) com o estilo árcade. O que muda na linguagem, nos temas e na estrutura dos poemas?',
    funFact: 'Você sabia? O lema do Arcadismo era "inutilia truncat" — "corte o inútil". Enquanto o barroco acumulava ornamentos, o árcade podava o excesso. Era uma estética da subtração, não da adição. Essa contenção formal refletia a crença iluminista de que a razão deve controlar os excessos emocionais.',
    points: 1,
    options: [
      { id: 'A', text: 'O Arcadismo reagiu ao Barroco aumentando ainda mais o uso de metáforas e paradoxos' },
      { id: 'B', text: 'Na forma, o Arcadismo buscou clareza, ordem e contenção (menos ornamentos); no conteúdo, substituiu a angústia barroca por uma celebração serena da natureza, do amor simples e da vida regrada — temas que refletem o equilíbrio racional iluminista' },
      { id: 'C', text: 'O Arcadismo reagiu ao Barroco introduzindo temas nacionalistas e heroicos sobre a história do Brasil' },
      { id: 'D', text: 'O Arcadismo rejeita completamente a forma poética — seus textos são sempre em prosa' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'Cláudio Manuel da Costa é chamado de "precursor" do Arcadismo brasileiro. Por que ele recebe esse título?',
    tip: 'Um "precursor" é alguém que chega antes dos outros. O que Cláudio Manuel da Costa fez que o coloca antes dos demais poetas árcades brasileiros?',
    funFact: 'Você sabia? Cláudio Manuel da Costa passou anos em Portugal, onde teve contato com o Arcadismo europeu (especialmente a Nova Arcádia portuguesa). Quando voltou para Minas Gerais, trouxe o estilo árcade consigo e o introduziu no Brasil antes que outros poetas o conhecessem. Foi um verdadeiro importador cultural.',
    points: 1,
    options: [
      { id: 'A', text: 'Cláudio Manuel da Costa é o precursor porque foi o primeiro a adaptar a estética árcade italiana ao contexto colonial brasileiro — publicando em 1768 as "Obras", a primeira coleção de poesia árcade do Brasil, antecipando o movimento que floresceria nas décadas seguintes' },
      { id: 'B', text: 'Cláudio Manuel da Costa é o precursor porque foi o primeiro a escrever em língua portuguesa no Brasil' },
      { id: 'C', text: 'Cláudio Manuel da Costa é o precursor porque fundou as primeiras escolas de literatura no Brasil colonial' },
      { id: 'D', text: 'Cláudio Manuel da Costa é o precursor porque foi o primeiro a criticar o Barroco em textos teóricos' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'Uma das características mais marcantes do Barroco é a obsessão com a transitoriedade — a passagem do tempo, a morte e a efemeridade da beleza. Como esse tema se manifesta na poesia barroca?',
    tip: 'O Barroco está sempre lembrando que tudo passa — a juventude, a beleza, a vida. Que expressão latina resume esse tema e como os poetas barrocos o trabalhavam?',
    funFact: 'Você sabia? A expressão "vanitas vanitatum, omnia vanitas" (vaidade das vaidades, tudo é vaidade) vem do livro bíblico do Eclesiastes. Os pintores barrocos criavam "naturezas-mortas" com caveiras, flores murchas e ampulhetas — chamadas "vanitas" — para lembrar que tudo morre. A poesia barroca fazia o mesmo com palavras.',
    points: 1,
    options: [
      { id: 'A', text: 'O tema da transitoriedade não aparece no Barroco — só surgiu no Romantismo' },
      { id: 'B', text: 'O tema da transitoriedade aparece no Barroco exclusivamente em poesias épicas' },
      { id: 'C', text: 'O tema da transitoriedade no Barroco é sempre otimista — o poeta lembra que tudo passa para animar as pessoas' },
      { id: 'D', text: 'O tema da efemeridade ("tempus fugit", "memento mori") manifesta-se na poesia barroca como meditação angustiada sobre a passagem do tempo, a morte inevitável e a vanidade de tudo que é terreno — expressão da visão dualista que opõe o efêmero ao eterno' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'O "locus amoenus" é um conceito fundamental na poesia árcade. O que significa essa expressão latina e como ela aparece na poesia de Gonzaga?',
    tip: '"Locus" significa "lugar" em latim, e "amoenus" significa "aprazível" ou "agradável". Qual é o papel desse lugar ideal na poesia árcade?',
    funFact: 'Você sabia? O "locus amoenus" tem origem na poesia clássica de Virgílio e Teócrito. Era descrito como um lugar com árvores com sombra, riacho de água cristalina, flores, pássaros cantando e uma brisa suave — um cenário perfeito para o amor e a contemplação. Gonzaga transpôs esse cenário clássico para as paisagens mineiras, com serras e rios do Brasil.',
    points: 1,
    options: [
      { id: 'A', text: 'O locus amoenus é a cidade ideal iluminista, símbolo do progresso e da civilização' },
      { id: 'B', text: 'O locus amoenus é o espaço urbano da corte — o palácio real onde os poetas árcades encontravam seus mecenas' },
      { id: 'C', text: 'O locus amoenus é o "lugar aprazível" — um espaço natural idealizado (bosque, fonte, jardim) que representa o ambiente perfeito para o amor e a vida simples; é o cenário típico da poesia árcade, símbolo da harmonia entre o ser humano e a natureza' },
      { id: 'D', text: 'O locus amoenus é a morte como "lugar de paz" — metáfora barroca para o além-vida' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'O "fugere urbem" é outro conceito central do Arcadismo. O que significa essa expressão latina e como ela se relaciona com os ideais do movimento?',
    tip: '"Fugere" significa "fugir" em latim. O que os poetas árcades queriam fugir e para onde iam nessa "fuga"?',
    funFact: 'Você sabia? A expressão "fugere urbem" vem do poeta romano Horácio (65-8 a.C.), que celebrava sua vida na fazenda sabina, longe de Roma. O ideal horaciano de uma vida simples no campo, em paz com a natureza, foi adotado pelos árcades como modelo de vida ideal — embora a maioria deles vivesse nas cidades e nunca tivesse se mudado para o campo.',
    points: 1,
    options: [
      { id: 'A', text: 'O "fugere urbem" significa fugir da morte — uma expressão de horror barroco pela transitoriedade da vida' },
      { id: 'B', text: 'O "fugere urbem" (fuga da cidade) expressa o ideal árcade de abandonar a vida urbana — com sua artificialidade, corrupção e agitação — em favor de uma existência simples, natural e harmoniosa no campo, longe das ambições cortesãs' },
      { id: 'C', text: 'O "fugere urbem" é uma crítica política — o desejo de fugir do controle do governo colonial português' },
      { id: 'D', text: 'O "fugere urbem" é um convite para os leitores migrarem para o interior do Brasil' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Os poetas árcades adotavam pseudônimos pastorais latinos ao entrar nas academias literárias. Qual era o objetivo dessa prática?',
    tip: 'Por que um poeta chamado Tomás Antônio Gonzaga assinaria seus poemas como "Dirceu"? Que função tinha essa troca de nome?',
    funFact: 'Você sabia? As academias literárias árcades tinham regras muito específicas para a adoção dos pseudônimos. O poeta precisava escolher um nome da mitologia pastoril clássica (greco-romana) que refletisse algo de sua personalidade ou de sua poesia. Gonzaga escolheu "Dirceu" — um pastor da mitologia grega. Cláudio Manuel escolheu "Glauceste Satúrnio" — evocando o deus Saturno e a região de Glauco.',
    points: 1,
    options: [
      { id: 'A', text: 'Os pseudônimos eram usados para esconder a identidade dos poetas que criticavam o governo' },
      { id: 'B', text: 'Os pseudônimos eram obrigatórios por lei — o governo colonial proibia publicações com nomes reais' },
      { id: 'C', text: 'Os pseudônimos pastorais latinos eram uma convenção do Arcadismo que criava uma identidade literária no universo ficcional pastoril — o poeta assumia um alter ego de pastor, integrando-se simbolicamente ao mundo ideal da Arcádia e da Antiguidade Clássica' },
      { id: 'D', text: 'Os pseudônimos árcades eram apenas nomes artísticos sem nenhum significado estético ou simbólico' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'O "carpe diem" é um conceito poético de origem romana muito presente no Arcadismo. O que significa essa expressão e como ela aparece na poesia de Gonzaga?',
    tip: '"Carpe diem" é uma expressão do poeta romano Horácio. O que ela prega e como se relaciona com os ideais árcades?',
    funFact: 'Você sabia? A frase completa de Horácio é "carpe diem, quam minimum credula postero" — "colha o dia de hoje, confiando o mínimo no amanhã". O poeta aconselhava aproveitar a vida no presente, pois o futuro é incerto. Essa mensagem era perfeita para o Arcadismo — que celebrava o presente simples e sereno, sem a angústia barroca sobre o tempo.',
    points: 1,
    options: [
      { id: 'A', text: 'O "carpe diem" (aproveite o dia) é o convite de Horácio — e dos poetas árcades — para viver plenamente o presente, aproveitar os prazeres simples da vida enquanto a juventude e a beleza duram, pois o tempo passa inevitavelmente' },
      { id: 'B', text: 'O "carpe diem" é uma expressão de desespero barroco diante da morte iminente' },
      { id: 'C', text: 'O "carpe diem" é uma crítica à vida prazerosa — um convite à contenção moral e religiosa' },
      { id: 'D', text: 'O "carpe diem" é exclusivo da poesia medieval, não aparecendo no Arcadismo brasileiro' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'As "Cartas Chilenas" é uma obra satírica geralmente atribuída a Tomás Antônio Gonzaga. O que é essa obra e qual é seu alvo?',
    tip: 'As "Cartas Chilenas" usam um disfarce geográfico para criticar alguém real. Por que "Chile" se a obra fala de Minas Gerais?',
    funFact: 'Você sabia? A autoria das "Cartas Chilenas" ainda é debatida pelos críticos — a maioria as atribui a Gonzaga, mas há quem defenda Cláudio Manuel da Costa ou outros inconfidentes. O pseudônimo "Critilo" (o autor das Cartas) é diferente de "Dirceu" (o pseudônimo de Gonzaga em "Marília de Dirceu"), o que alimenta o debate sobre a autoria.',
    points: 1,
    options: [
      { id: 'A', text: 'As "Cartas Chilenas" são um conjunto de cartas reais enviadas da América Espanhola para Portugal' },
      { id: 'B', text: 'As "Cartas Chilenas" são poemas de amor escritos para uma chilena que Gonzaga conheceu no exílio' },
      { id: 'C', text: 'As "Cartas Chilenas" são uma sátira política em verso — atribuídas a Gonzaga ("Critilo") — que critica o governador de Minas Gerais Luís da Cunha Menezes ("Fanfarrão Minésio"), usando o disfarce do Chile para escapar da censura' },
      { id: 'D', text: 'As "Cartas Chilenas" são um conjunto de crônicas sobre a natureza brasileira' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Qual é a diferença mais fundamental entre a visão de mundo barroca e a visão de mundo arcadista em relação à natureza e à vida?',
    tip: 'Compare como o Barroco e o Arcadismo encaram a existência, o tempo e a natureza. São perspectivas radicalmente diferentes.',
    funFact: 'Você sabia? O século XVIII foi chamado de "Século das Luzes" — o Iluminismo prometia que a razão poderia resolver todos os problemas humanos. Essa confiança na razão era completamente oposta ao pessimismo barroco, que via o ser humano como radicalmente dividido e incapaz de se salvar sozinho. O Arcadismo é filho das Luzes; o Barroco, filho da Contrarreforma.',
    points: 1,
    options: [
      { id: 'A', text: 'O Barroco vê a natureza como um paraíso; o Arcadismo a vê como ameaçadora e perigosa' },
      { id: 'B', text: 'O Barroco celebra a vida terrena com alegria; o Arcadismo a vê como lugar de sofrimento e angústia' },
      { id: 'C', text: 'O Barroco é otimista sobre o futuro; o Arcadismo é pessimista sobre a condição humana' },
      { id: 'D', text: 'O Barroco vê a existência como lugar de tensão e angústia entre opostos irreconciliáveis; o Arcadismo busca a serenidade, o equilíbrio e a harmonia entre o ser humano, a natureza e a razão — uma visão otimista do mundo' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Vila Rica (atual Ouro Preto, Minas Gerais) foi o epicentro do Arcadismo brasileiro. Por que essa cidade, e não Salvador ou Rio de Janeiro, foi o principal centro do Arcadismo?',
    tip: 'Pense no que Vila Rica tinha que as outras cidades não tinham no século XVIII. Por que uma cidade mineira seria o centro cultural do Brasil colonial?',
    funFact: 'Você sabia? Ouro Preto tem 13 igrejas barrocas construídas nos séculos XVII e XVIII com o ouro das minas. É uma cidade-monumento ao período colonial e foi declarada Patrimônio da Humanidade pela UNESCO em 1980. Paradoxalmente, a mesma riqueza que produziu toda essa beleza barroca também alimentou a revolta iluminista que tentou criar uma república brasileira.',
    points: 1,
    options: [
      { id: 'A', text: 'Vila Rica foi o epicentro do Arcadismo porque era a capital administrativa do Brasil colonial' },
      { id: 'B', text: 'Vila Rica foi o epicentro porque tinha a maior escola de literatura da América colonial' },
      { id: 'C', text: 'Vila Rica foi o epicentro porque era o único local onde havia liberdade de imprensa no Brasil colonial' },
      { id: 'D', text: 'Vila Rica foi o epicentro porque era a capital da Capitania de Minas Gerais durante o ciclo do ouro — a riqueza mineral gerou uma elite intelectual que frequentava academias literárias, estudava em Portugal e trocava ideias iluministas, criando as condições para o Arcadismo e para a Inconfidência' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'O pastoralismo árcade era uma convenção literária. O que isso significa e quais eram suas regras?',
    tip: 'Uma "convenção" em literatura é um conjunto de regras ou normas aceitas pelos escritores de um mesmo período. Quais eram as convenções pastorais do Arcadismo?',
    funFact: 'Você sabia? O pastoralismo árcade era tão artificial e convencional que os críticos modernos às vezes o chamam de "pastoral de salão" — uma arte feita por intelectuais urbanos que idealizavam o campo como nunca o tinham vivido. Mas essa distância da realidade era justamente o ponto: a Arcádia era um espaço de imaginação, não uma descrição da vida real.',
    points: 1,
    options: [
      { id: 'A', text: 'O pastoralismo árcade era uma convenção que exigia que os poetas vivessem de fato no campo para escrever' },
      { id: 'B', text: 'O pastoralismo árcade era uma convenção que exigia linguagem simples e popular, sem nenhuma erudição' },
      { id: 'C', text: 'O pastoralismo árcade era uma convenção que proibia qualquer referência à história real ou à política' },
      { id: 'D', text: 'O pastoralismo árcade era um conjunto de convenções que incluía: uso de pseudônimos pastorais, ambientação no campo ou em bosques idealizados, personagens de pastores e pastoras, referências à mitologia greco-romana e uma linguagem elegante mas contida' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Além de "Marília de Dirceu", Tomás Antônio Gonzaga escreveu outra obra importante. Qual é essa obra e qual é sua natureza?',
    tip: 'Gonzaga não escreveu apenas poesia lírica de amor. Ele também escreveu um texto satírico muito importante. Qual é esse texto?',
    funFact: 'Você sabia? Gonzaga também escreveu "Tratado de Direito Natural" — uma obra filosófica e jurídica que revela sua formação iluminista. Esse tratado mostra que Gonzaga não era apenas um poeta apaixonado, mas também um intelectual que conhecia as ideias iluministas de Locke, Rousseau e Montesquieu — as mesmas que inspiravam a Inconfidência.',
    points: 1,
    options: [
      { id: 'A', text: 'Gonzaga escreveu "Obras" (1768), coletânea de sonetos precursores do Arcadismo' },
      { id: 'B', text: 'Gonzaga escreveu os sermões religiosos "Missas do Interior", típicos do Barroco colonial' },
      { id: 'C', text: 'Além de "Marília de Dirceu", Gonzaga escreveu as "Cartas Chilenas" — obra satírica atribuída ao pseudônimo "Critilo" que critica o governador Luís da Cunha Menezes com ironia e humor iluminista' },
      { id: 'D', text: 'Gonzaga escreveu "A Vila Rica", epopeia sobre a história das minas de ouro em Minas Gerais' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Cláudio Manuel da Costa se distingue de Gonzaga pela sua formação estética. Como o estilo poético de Cláudio Manuel da Costa se diferencia do de Gonzaga?',
    tip: 'Os dois poetas eram árcades, mas Cláudio Manuel da Costa tinha uma bagagem estética diferente de Gonzaga. O que o distingue?',
    funFact: 'Você sabia? Cláudio Manuel da Costa estudou em Coimbra quando o Marquês de Pombal estava reformando a universidade e o ensino. Ele se formou antes de Gonzaga e trouxe mais influências do Barroco português tardio para sua obra — o que explica por que seus poemas às vezes parecem mais tensos e angustiados que os de Gonzaga, que foi mais fiel ao ideal sereno do Arcadismo.',
    points: 1,
    options: [
      { id: 'A', text: 'Cláudio Manuel da Costa escrevia exclusivamente em verso livre, sem nenhuma forma fixa' },
      { id: 'B', text: 'Cláudio Manuel da Costa apresenta em sua obra uma tensão entre o Barroco (angústia, dualismo, ornamentação) e o Arcadismo (serenidade, pastoralismo), sendo considerado uma figura de transição — sua obra tem mais rugosidade e dramatismo que a de Gonzaga' },
      { id: 'C', text: 'Cláudio Manuel da Costa era mais popular e acessível que Gonzaga, sem nenhuma influência clássica' },
      { id: 'D', text: 'Cláudio Manuel da Costa não escrevia sonetos — sua obra era composta exclusivamente de odes e elegias' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'O Arcadismo e o Iluminismo têm uma relação de profunda afinidade. Qual é o elo mais importante entre os dois movimentos?',
    tip: 'O Iluminismo era político-filosófico; o Arcadismo era literário. Mas eles compartilhavam um valor fundamental. Qual é esse valor?',
    funFact: 'Você sabia? A Encyclopédie de Diderot e D\'Alembert (1751-1772) — a grande obra do Iluminismo — e "Marília de Dirceu" de Gonzaga (1792) foram publicadas na mesma época, respirando o mesmo ar intelectual. A fé na razão, a crítica ao absolutismo e a valorização da natureza eram comuns a ambos os projetos.',
    points: 1,
    options: [
      { id: 'A', text: 'O elo entre Arcadismo e Iluminismo é a religiosidade — ambos são profundamente cristãos em seus valores' },
      { id: 'B', text: 'O elo entre Arcadismo e Iluminismo é o nacionalismo — ambos defendem a independência das colônias americanas' },
      { id: 'C', text: 'O elo entre Arcadismo e Iluminismo é estético — ambos valorizam o exagero e o ornamento barroco' },
      { id: 'D', text: 'O elo mais importante é a valorização da razão como guia supremo — o Iluminismo acreditava que a razão poderia reformar a sociedade; o Arcadismo expressava artisticamente essa fé na razão ao buscar equilíbrio, clareza e harmonia natural, rejeitando os excessos emocionais e formais do Barroco' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'Ao comparar um poema barroco de Gregório de Matos com um poema árcade de Gonzaga, quais são as diferenças mais evidentes que um leitor perceberia?',
    tip: 'Pense na linguagem, nos temas, no tom emocional e na forma de cada um. O que um leitor sente ao ler cada um deles?',
    funFact: 'Você sabia? Um exercício clássico de aula de literatura é ler lado a lado um soneto religioso de Gregório de Matos (tenso, paradoxal, angustiado) e uma lira de Gonzaga para Marília (serena, luminosa, amorosa). O contraste é imediato — são dois mundos estéticos e filosóficos completamente diferentes, separados por menos de um século.',
    points: 1,
    options: [
      { id: 'A', text: 'O poema de Gregório tem linguagem ornamentada e tensa, com antíteses, paradoxos e angústia; enquanto o poema de Gonzaga tem linguagem mais clara e serena, com imagens pastorais aprazíveis e um tom de celebração tranquila do amor e da natureza — refletindo as diferenças filosóficas entre Barroco e Arcadismo' },
      { id: 'B', text: 'O poema de Gregório é simples e popular; o de Gonzaga é complexo e difícil de entender' },
      { id: 'C', text: 'Não há diferenças perceptíveis — Barroco e Arcadismo são estilos muito similares na forma e no conteúdo' },
      { id: 'D', text: 'O poema de Gregório é sempre alegre e festivo; o de Gonzaga é sempre triste e melancólico' },
    ],
    correctAnswer: 'A',
  },
];
