export const questoesArte7AnoB1Av2 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "As cores que não podem ser formadas pela mistura de outras cores são chamadas de cores:",
    tip: "Pense nas cores \"básicas\", aquelas de onde todas as outras nascem, misturando-as.",
    funFact: "As cores primárias também são usadas em telas de celular e TV, mas lá a combinação é um pouco diferente (vermelho, verde e azul)!",
    points: 1,
    options: [
      { id: "A", text: "Secundárias" },
      { id: "B", text: "Terciárias" },
      { id: "C", text: "Neutras" },
      { id: "D", text: "Primárias" },
    ],
    correctAnswer: "D",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "As cores primárias são o vermelho, o azul e o:",
    tip: "As outras três opções são formadas pela mistura de cores — só falta uma cor \"pura\" na lista.",
    funFact: "O amarelo é a cor que reflete mais luz de todas — por isso é tão usada em sinais de trânsito e placas de atenção!",
    points: 1,
    options: [
      { id: "A", text: "Verde" },
      { id: "B", text: "Amarelo" },
      { id: "C", text: "Roxo" },
      { id: "D", text: "Laranja" },
    ],
    correctAnswer: "B",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "Quando misturamos duas cores primárias, criamos uma cor:",
    tip: "Se a cor \"nasce\" da mistura de duas primárias, ela não pode ser primária também. Qual é o nome dessa categoria?",
    funFact: "As cores secundárias são verde, laranja e roxo (violeta) — todas nascidas da mistura de duas primárias!",
    points: 1,
    options: [
      { id: "A", text: "Primária" },
      { id: "B", text: "Neutra" },
      { id: "C", text: "Secundária" },
      { id: "D", text: "Invisível" },
    ],
    correctAnswer: "C",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "Misturando azul e amarelo, obtemos a cor:",
    tip: "Pense na cor das folhas e da grama — ela nasce exatamente dessa mistura.",
    funFact: "O verde é a cor que o olho humano consegue perceber com mais facilidade, por isso é tão usado em sinais de \"livre\" ou \"ok\"!",
    points: 1,
    options: [
      { id: "A", text: "Verde" },
      { id: "B", text: "Vermelho" },
      { id: "C", text: "Roxo" },
      { id: "D", text: "Laranja" },
    ],
    correctAnswer: "A",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "Misturando vermelho e amarelo, obtemos a cor:",
    tip: "Pense na cor de uma fruta cítrica bem conhecida que tem justamente esse nome.",
    funFact: "A fruta laranja ganhou esse nome por causa da cor, e não o contrário — a cor já existia antes do nome da fruta ficar popular no Brasil!",
    points: 1,
    options: [
      { id: "A", text: "Verde" },
      { id: "B", text: "Laranja" },
      { id: "C", text: "Roxo" },
      { id: "D", text: "Azul" },
    ],
    correctAnswer: "B",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "Misturando vermelho e azul, obtemos a cor:",
    tip: "Pense na cor de uma uva madura ou de uma flor de lavanda — ela nasce dessa combinação.",
    funFact: "Na Roma Antiga, o roxo era uma cor tão rara e cara de produzir que só imperadores podiam usá-la em suas roupas!",
    points: 1,
    options: [
      { id: "A", text: "Verde" },
      { id: "B", text: "Amarelo" },
      { id: "C", text: "Laranja" },
      { id: "D", text: "Roxo (violeta)" },
    ],
    correctAnswer: "D",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "As cores que passam a sensação de calor, como vermelho, laranja e amarelo, são chamadas de cores:",
    tip: "Pense no fogo e no sol — essas cores lembram esses elementos quentes.",
    funFact: "Restaurantes muitas vezes usam cores quentes na decoração porque elas estimulam o apetite!",
    points: 1,
    options: [
      { id: "A", text: "Quentes" },
      { id: "B", text: "Frias" },
      { id: "C", text: "Neutras" },
      { id: "D", text: "Primárias" },
    ],
    correctAnswer: "A",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "As cores que passam a sensação de frescor, como azul, verde e roxo, são chamadas de cores:",
    tip: "Pense no mar, no gelo e nas folhas — essas cores lembram elementos frescos e frios.",
    funFact: "Muitas marcas de produtos de limpeza usam azul na embalagem, justamente para transmitir sensação de frescor!",
    points: 1,
    options: [
      { id: "A", text: "Quentes" },
      { id: "B", text: "Primárias" },
      { id: "C", text: "Frias" },
      { id: "D", text: "Secundárias" },
    ],
    correctAnswer: "C",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "O branco e o preto, junto com o cinza, são chamados de cores:",
    tip: "Essas cores não são nem quentes nem frias — elas ficam \"no meio\", sem causar essas sensações. Qual é o nome dessa categoria?",
    funFact: "Tecnicamente, preto e branco nem são consideradas \"cores\" pela física, pois não vêm diretamente do espectro de luz como o vermelho ou o azul!",
    points: 1,
    options: [
      { id: "A", text: "Primárias" },
      { id: "B", text: "Secundárias" },
      { id: "C", text: "Quentes" },
      { id: "D", text: "Neutras" },
    ],
    correctAnswer: "D",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "O círculo que mostra todas as cores organizadas e suas relações é chamado de círculo:",
    tip: "A palavra vem de \"cromo\", que tem relação com cor. Qual opção tem essa raiz?",
    funFact: "O círculo cromático foi estudado até por cientistas famosos, como Isaac Newton, que também estudou a luz e as cores!",
    points: 1,
    options: [
      { id: "A", text: "Musical" },
      { id: "B", text: "Cromático" },
      { id: "C", text: "Numérico" },
      { id: "D", text: "Geométrico" },
    ],
    correctAnswer: "B",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Um artista quer pintar um pôr do sol usando cores que transmitam sensação de calor. Quais cores ele deve escolher?",
    tip: "Pense nas cores que lembram o sol se pondo no horizonte — são tons quentes, como fogo.",
    funFact: "O céu fica alaranjado ao pôr do sol porque a luz do sol atravessa mais atmosfera nesse horário, espalhando mais as cores quentes!",
    points: 1,
    options: [
      { id: "A", text: "Azul e verde" },
      { id: "B", text: "Cinza e preto" },
      { id: "C", text: "Vermelho e laranja" },
      { id: "D", text: "Roxo e azul" },
    ],
    correctAnswer: "C",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Um artista quer pintar um lago gelado e passar uma sensação de frescor. Quais cores combinam melhor?",
    tip: "Pense nas cores frias, que lembram água e gelo.",
    funFact: "A água pura é incolor, mas parece azul porque reflete a cor do céu e absorve outras cores da luz!",
    points: 1,
    options: [
      { id: "A", text: "Azul e verde" },
      { id: "B", text: "Vermelho e laranja" },
      { id: "C", text: "Amarelo e laranja" },
      { id: "D", text: "Preto e vermelho" },
    ],
    correctAnswer: "A",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "Se um pintor misturar as três cores primárias (vermelho, azul e amarelo) em partes iguais, ele tende a obter uma cor:",
    tip: "Quando misturamos muitas cores diferentes juntas, o resultado costuma ficar \"sujo\" e escuro, não vibrante.",
    funFact: "É por isso que pintores costumam ter cuidado ao misturar muitas tintas de uma vez — o resultado pode virar uma cor \"lama\"!",
    points: 1,
    options: [
      { id: "A", text: "Rosa brilhante" },
      { id: "B", text: "Verde vivo" },
      { id: "C", text: "Laranja forte" },
      { id: "D", text: "Marrom escuro ou acinzentado" },
    ],
    correctAnswer: "D",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "Qual par de cores é formado por duas cores primárias?",
    tip: "Lembre-se: as primárias são vermelho, azul e amarelo. Qual par da lista tem só essas duas cores \"puras\"?",
    funFact: "Verde, laranja e roxo são todas secundárias — cada uma nasce da mistura de duas primárias diferentes!",
    points: 1,
    options: [
      { id: "A", text: "Verde e laranja" },
      { id: "B", text: "Azul e amarelo" },
      { id: "C", text: "Roxo e verde" },
      { id: "D", text: "Laranja e roxo" },
    ],
    correctAnswer: "B",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Qual destas é uma cor secundária?",
    tip: "Três dessas opções são primárias (não podem ser formadas por mistura). Só uma delas nasce da mistura de duas outras.",
    funFact: "O verde é uma das cores mais comuns na natureza, presente em quase todas as plantas do planeta!",
    points: 1,
    options: [
      { id: "A", text: "Verde" },
      { id: "B", text: "Vermelho" },
      { id: "C", text: "Azul" },
      { id: "D", text: "Amarelo" },
    ],
    correctAnswer: "A",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "Um quadro pintado principalmente com azul, verde e roxo passa uma sensação geral de:",
    tip: "Essas três cores fazem parte do mesmo grupo — pense em qual sensação elas costumam transmitir juntas.",
    funFact: "Hospitais e consultórios médicos costumam usar tons de azul e verde nas paredes, justamente para passar calma aos pacientes!",
    points: 1,
    options: [
      { id: "A", text: "Calor intenso" },
      { id: "B", text: "Alegria quente" },
      { id: "C", text: "Calma e frescor" },
      { id: "D", text: "Som alto" },
    ],
    correctAnswer: "C",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "Para pintar uma fruta laranja, como uma tangerina, quais cores primárias um artista pode misturar?",
    tip: "Pense em como se forma a cor laranja — ela é secundária, nascida da mistura de duas primárias específicas.",
    funFact: "A tangerina e a laranja pertencem à mesma família de frutas cítricas, mas a tangerina é geralmente menor e mais fácil de descascar!",
    points: 1,
    options: [
      { id: "A", text: "Azul e vermelho" },
      { id: "B", text: "Vermelho e amarelo" },
      { id: "C", text: "Azul e amarelo" },
      { id: "D", text: "Preto e branco" },
    ],
    correctAnswer: "B",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "Em um quadro, usar apenas tons de cinza, preto e branco cria um efeito visual chamado de obra:",
    tip: "Pense no nome que se dá a uma obra sem cores coloridas, usando só tons de cinza, como uma foto antiga.",
    funFact: "As primeiras fotografias e filmes da história eram todos em preto e branco, antes da tecnologia de cores ser inventada!",
    points: 1,
    options: [
      { id: "A", text: "Colorida" },
      { id: "B", text: "Quente" },
      { id: "C", text: "Fria" },
      { id: "D", text: "Em escala de cinza (monocromática/acromática)" },
    ],
    correctAnswer: "D",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "Qual destas cores é considerada neutra?",
    tip: "As outras três fazem parte do grupo das cores quentes ou frias. Só uma delas não entra em nenhum desses dois grupos.",
    funFact: "O cinza é formado pela mistura de preto e branco, e por isso é considerado uma cor neutra, sem calor nem frescor!",
    points: 1,
    options: [
      { id: "A", text: "Vermelho" },
      { id: "B", text: "Azul" },
      { id: "C", text: "Cinza" },
      { id: "D", text: "Amarelo" },
    ],
    correctAnswer: "C",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "No círculo cromático, as cores quentes e frias ficam organizadas de forma a mostrar que elas são:",
    tip: "Pense em como o calor e o frio são sensações contrárias uma da outra — no círculo cromático, as cores seguem essa mesma lógica.",
    funFact: "Artistas costumam usar cores opostas (como azul e laranja) juntas de propósito, para criar contraste e chamar mais atenção na obra!",
    points: 1,
    options: [
      { id: "A", text: "Opostas (contrastantes) entre si" },
      { id: "B", text: "Exatamente iguais" },
      { id: "C", text: "Impossíveis de usar juntas" },
      { id: "D", text: "Apenas musicais" },
    ],
    correctAnswer: "A",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Bernardo está pintando um quadro de uma fogueira e quer que ele pareça bem quentinho. Quais cores ele deve usar?",
    tip: "Pense nas cores que lembram o fogo de verdade — são bem quentes.",
    funFact: "A temperatura de uma fogueira pode passar de 600°C — por isso o fogo tem cores tão vivas e quentes!",
    points: 1,
    options: [
      { id: "A", text: "Azul e verde" },
      { id: "B", text: "Vermelho, laranja e amarelo" },
      { id: "C", text: "Cinza e preto" },
      { id: "D", text: "Roxo e azul" },
    ],
    correctAnswer: "B",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Bernardo misturou tinta azul com tinta amarela em seu desenho. Qual cor ele deve ter obtido?",
    tip: "Pense na cor das árvores e das folhas — ela nasce exatamente dessa combinação de azul e amarelo.",
    funFact: "Essa é uma das misturas mais usadas por crianças pintando paisagens, já que verde aparece em quase todo desenho de natureza!",
    points: 1,
    options: [
      { id: "A", text: "Laranja" },
      { id: "B", text: "Vermelho" },
      { id: "C", text: "Roxo" },
      { id: "D", text: "Verde" },
    ],
    correctAnswer: "D",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Bernardo quer pintar o mar e o céu usando cores que transmitam uma sensação de calma e frescor. Quais cores combinam melhor?",
    tip: "Pense nas cores frias, que lembram água e natureza — elas passam calma.",
    funFact: "Estudos mostram que olhar para tons de azul e verde pode até ajudar a relaxar e diminuir o estresse!",
    points: 1,
    options: [
      { id: "A", text: "Vermelho e laranja" },
      { id: "B", text: "Amarelo e laranja" },
      { id: "C", text: "Azul e verde" },
      { id: "D", text: "Preto e vermelho" },
    ],
    correctAnswer: "C",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Bernardo aprendeu que vermelho, azul e amarelo são cores que não podem ser formadas pela mistura de outras cores. Como essas cores são chamadas?",
    tip: "Lembre-se: são as cores \"base\", de onde todas as outras nascem pela mistura.",
    funFact: "Essas três cores primárias são a base de quase todas as tintas e pigmentos usados em artes visuais no mundo!",
    points: 1,
    options: [
      { id: "A", text: "Primárias" },
      { id: "B", text: "Secundárias" },
      { id: "C", text: "Neutras" },
      { id: "D", text: "Terciárias" },
    ],
    correctAnswer: "A",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Bernardo pintou um desenho usando apenas preto, branco e cinza, sem nenhuma outra cor. Esse tipo de obra é chamada de:",
    tip: "Pense no nome usado para obras feitas só com tons de cinza, sem cores coloridas de verdade.",
    funFact: "Muitos artistas fazem estudos em preto e branco antes de pintar a obra final em cores, para planejar melhor as luzes e sombras!",
    points: 1,
    options: [
      { id: "A", text: "Colorida" },
      { id: "B", text: "Quente" },
      { id: "C", text: "Fria" },
      { id: "D", text: "Monocromática (em tons de cinza)" },
    ],
    correctAnswer: "D",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Bernardo misturou tinta vermelha com tinta azul para pintar as uvas do seu desenho. Qual cor ele obteve?",
    tip: "Pense na cor de uma uva madura — ela nasce exatamente dessa mistura de vermelho e azul.",
    funFact: "Existem uvas de várias cores — verdes, vermelhas e roxas — dependendo da variedade da fruta!",
    points: 1,
    options: [
      { id: "A", text: "Verde" },
      { id: "B", text: "Roxo (violeta)" },
      { id: "C", text: "Laranja" },
      { id: "D", text: "Amarelo" },
    ],
    correctAnswer: "B",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Bernardo quer saber qual é o nome da cor que resulta da mistura de duas cores primárias. Qual é esse nome?",
    tip: "Se ela \"nasce\" da mistura de duas primárias, ela não pode também ser primária. Qual é o nome certo dessa categoria?",
    funFact: "As três cores secundárias (verde, laranja e roxo) ficam exatamente entre as primárias no círculo cromático!",
    points: 1,
    options: [
      { id: "A", text: "Cor secundária" },
      { id: "B", text: "Cor primária" },
      { id: "C", text: "Cor neutra" },
      { id: "D", text: "Cor sonora" },
    ],
    correctAnswer: "A",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Bernardo organizou um desenho mostrando todas as cores em um círculo, para estudar como elas se relacionam. Como se chama esse círculo?",
    tip: "A palavra tem a ver com \"cor\" — pense em qual opção tem essa relação no nome.",
    funFact: "O círculo cromático ajuda os artistas a escolher combinações de cores que ficam bonitas juntas, como as opostas no círculo!",
    points: 1,
    options: [
      { id: "A", text: "Círculo geométrico" },
      { id: "B", text: "Círculo numérico" },
      { id: "C", text: "Círculo cromático" },
      { id: "D", text: "Círculo musical" },
    ],
    correctAnswer: "C",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Bernardo pintou uma floresta usando bastante verde e também um pouco de azul. Essas cores passam uma sensação de:",
    tip: "Pense no que essas cores lembram na natureza — florestas, água, ar puro.",
    funFact: "As florestas tropicais, como a Amazônia, são responsáveis por produzir grande parte do oxigênio que respiramos!",
    points: 1,
    options: [
      { id: "A", text: "Calor intenso" },
      { id: "B", text: "Frescor e natureza" },
      { id: "C", text: "Perigo" },
      { id: "D", text: "Som alto" },
    ],
    correctAnswer: "B",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Bernardo aprendeu que preto, branco e cinza não são consideradas cores quentes nem frias. Como elas são chamadas?",
    tip: "Essas cores ficam \"no meio\", sem transmitir nem calor nem frescor. Qual é o nome dessa categoria especial?",
    funFact: "Roupas em tons neutros, como preto, branco e cinza, são super versáteis porque combinam com quase qualquer outra cor!",
    points: 1,
    options: [
      { id: "A", text: "Primárias" },
      { id: "B", text: "Secundárias" },
      { id: "C", text: "Terciárias" },
      { id: "D", text: "Neutras" },
    ],
    correctAnswer: "D",
  },
];
