export const questoesHistoria6AnoB1Av2 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'O que foi a Revolução Neolítica?',
    tip: 'Pensa numa grande mudança na forma de conseguir alimento, deixando de depender só da caça e coleta.',
    funFact: 'Essa mudança é considerada uma das maiores revoluções da história da humanidade, mudando completamente o modo de vida das pessoas!',
    points: 1,
    options: [
      { id: 'A', text: 'A invenção da escrita' },
      { id: 'B', text: 'A descoberta do fogo' },
      { id: 'C', text: 'O período em que os seres humanos passaram a praticar a agricultura e a domesticar animais' },
      { id: 'D', text: 'A construção das primeiras cidades modernas' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'A prática da agricultura permitiu que os seres humanos:',
    tip: 'Pensa em como cuidar de uma plantação exige ficar perto dela, ao invés de se mudar constantemente.',
    funFact: 'Essa fixação em um só lugar foi o primeiro passo para o surgimento das primeiras aldeias e, depois, das cidades!',
    points: 1,
    options: [
      { id: 'A', text: 'Continuassem sempre nômades' },
      { id: 'B', text: 'Se fixassem em um lugar, tornando-se sedentários' },
      { id: 'C', text: 'Parassem de se alimentar' },
      { id: 'D', text: 'Voltassem a caçar exclusivamente' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'Ser sedentário significa:',
    tip: 'Pensa no oposto de "nômade" — alguém que permanece sempre no mesmo lugar.',
    funFact: 'A palavra "sedentário" vem do latim "sedere", que significa "sentar" ou "ficar parado"!',
    points: 1,
    options: [
      { id: 'A', text: 'Viver fixo em um determinado lugar' },
      { id: 'B', text: 'Se deslocar constantemente' },
      { id: 'C', text: 'Nunca plantar nada' },
      { id: 'D', text: 'Viver exclusivamente da caça' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'A domesticação de animais, no período Neolítico, serviu para:',
    tip: 'Pensa em vários benefícios práticos que animais como cabras, ovelhas e bois trazem até hoje.',
    funFact: 'A domesticação de animais aconteceu quase ao mesmo tempo que o desenvolvimento da agricultura!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas decoração' },
      { id: 'B', text: 'Nenhuma utilidade prática' },
      { id: 'C', text: 'Substituir a agricultura completamente' },
      { id: 'D', text: 'Obter alimento, trabalho e outros recursos, como lã e leite' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'O cultivo de plantas, como trigo e cevada, permitiu aos povos neolíticos:',
    tip: 'Pensa em como plantar e colher garante alimento sem precisar depender só da sorte da caça.',
    funFact: 'O trigo e a cevada estão entre os primeiros grãos cultivados pela humanidade!',
    points: 1,
    options: [
      { id: 'A', text: 'Continuar sempre migrando' },
      { id: 'B', text: 'Garantir uma fonte de alimento mais estável' },
      { id: 'C', text: 'Parar de comer' },
      { id: 'D', text: 'Aumentar o nomadismo' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'Com a fixação em um local e a agricultura, os grupos humanos começaram a formar:',
    tip: 'Pensa no que acontece quando várias famílias se fixam próximas umas das outras, cultivando a terra juntas.',
    funFact: 'Com o passar do tempo, algumas dessas aldeias cresceram e deram origem às primeiras cidades da história!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas cavernas isoladas' },
      { id: 'B', text: 'Grupos sempre em movimento' },
      { id: 'C', text: 'As primeiras aldeias e vilarejos' },
      { id: 'D', text: 'Grandes impérios imediatamente' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'O surgimento da agricultura também está relacionado ao desenvolvimento de:',
    tip: 'Pensa em quais instrumentos seriam necessários para plantar e colher de forma mais eficiente.',
    funFact: 'Essas ferramentas mais elaboradas marcam justamente a passagem do Paleolítico para o Neolítico!',
    points: 1,
    options: [
      { id: 'A', text: 'Computadores' },
      { id: 'B', text: 'Veículos motorizados' },
      { id: 'C', text: 'Redes sociais' },
      { id: 'D', text: 'Ferramentas mais elaboradas, como enxadas e foices de pedra polida' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'O período em que os seres humanos passaram a polir a pedra, ao invés de apenas lascá-la, é chamado de:',
    tip: '"Neo" lembra "novo" — pensa na nova técnica de trabalhar a pedra, mais refinada que o simples lascamento.',
    funFact: 'Ferramentas de pedra polida eram mais resistentes e eficientes que as de pedra lascada do Paleolítico!',
    points: 1,
    options: [
      { id: 'A', text: 'Neolítico' },
      { id: 'B', text: 'Paleolítico' },
      { id: 'C', text: 'Idade Contemporânea' },
      { id: 'D', text: 'Idade Média' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'Com o excedente de alimentos produzido pela agricultura, os povos neolíticos puderam:',
    tip: 'Pensa no que acontece quando sobra comida além do necessário para o consumo imediato.',
    funFact: 'Esse excedente de alimentos foi um dos primeiros passos para o surgimento do comércio entre diferentes grupos!',
    points: 1,
    options: [
      { id: 'A', text: 'Deixar de se alimentar' },
      { id: 'B', text: 'Voltar ao nomadismo' },
      { id: 'C', text: 'Armazenar comida e até realizar trocas com outros grupos' },
      { id: 'D', text: 'Parar de plantar' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'A cerâmica, desenvolvida no período Neolítico, era usada principalmente para:',
    tip: 'Pensa em potes e vasilhas de barro — para que eles costumam servir?',
    funFact: 'A cerâmica também ajudou muito os historiadores a estudar os povos neolíticos, já que muitos desses objetos resistiram ao tempo!',
    points: 1,
    options: [
      { id: 'A', text: 'Fazer roupas' },
      { id: 'B', text: 'Armazenar alimentos e água' },
      { id: 'C', text: 'Construir casas inteiras' },
      { id: 'D', text: 'Substituir ferramentas de caça' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'Por que a Revolução Neolítica é considerada uma mudança tão importante na história da humanidade?',
    tip: 'Pensa em todas as mudanças que vimos: agricultura, sedentarização, aldeias, cerâmica... tudo isso transformou a vida das pessoas.',
    funFact: 'Essa transformação foi tão importante que muitos historiadores a consideram uma verdadeira "revolução" na história humana!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque transformou profundamente o modo de vida das pessoas, da vida nômade para a sedentária' },
      { id: 'B', text: 'Porque não trouxe nenhuma mudança significativa' },
      { id: 'C', text: 'Porque aconteceu em apenas um dia' },
      { id: 'D', text: 'Porque acabou com toda forma de agricultura' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'A formação das primeiras aldeias trouxe, entre outras coisas, a necessidade de:',
    tip: 'Pensa em como viver junto de várias famílias exige alguma forma de organização para tudo funcionar bem.',
    funFact: 'Essa necessidade de organização social é considerada um dos primeiros passos para o surgimento de sociedades mais complexas!',
    points: 1,
    options: [
      { id: 'A', text: 'Voltar a ser nômade' },
      { id: 'B', text: 'Parar de plantar' },
      { id: 'C', text: 'Ignorar a organização social' },
      { id: 'D', text: 'Organizar melhor a convivência entre as pessoas, criando regras e divisão de tarefas' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'Com a vida em aldeias, algumas pessoas começaram a se especializar em tarefas específicas, como:',
    tip: 'Pensa em como, com mais comida disponível, nem todos precisavam mais fazer a mesma tarefa o tempo todo.',
    funFact: 'Essa divisão de tarefas foi um passo importante para o desenvolvimento de habilidades e conhecimentos mais especializados!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas caçar' },
      { id: 'B', text: 'Somente migrar' },
      { id: 'C', text: 'Fazer cerâmica, cultivar a terra ou cuidar dos animais' },
      { id: 'D', text: 'Nenhuma atividade específica' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'A produção de excedente de alimentos, resultado da agricultura, permitiu também que:',
    tip: 'Pensa em como sobrar comida além do necessário libera tempo para outras atividades, como fazer ferramentas ou cerâmica.',
    funFact: 'Esse excedente foi fundamental para o desenvolvimento de artesãos, comerciantes e outras funções na sociedade!',
    points: 1,
    options: [
      { id: 'A', text: 'As pessoas parassem de comer' },
      { id: 'B', text: 'Algumas pessoas se dedicassem a outras atividades além da produção de comida' },
      { id: 'C', text: 'A população diminuísse drasticamente' },
      { id: 'D', text: 'O nomadismo aumentasse' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'As primeiras cidades da história surgiram, tempos depois, a partir:',
    tip: 'Pensa na sequência: primeiro agricultura, depois aldeias, e então, com o tempo, cidades maiores.',
    funFact: 'Algumas das primeiras cidades da história, como Ur e Uruk, surgiram na região da Mesopotâmia, a partir de aldeias agrícolas!',
    points: 1,
    options: [
      { id: 'A', text: 'Diretamente do período Paleolítico' },
      { id: 'B', text: 'Sem nenhuma relação com a agricultura' },
      { id: 'C', text: 'Da vida totalmente nômade' },
      { id: 'D', text: 'Do crescimento das aldeias neolíticas que praticavam agricultura' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'A Revolução Neolítica é considerada um marco importante porque, a partir dela:',
    tip: 'Pensa em como a agricultura passou a garantir uma fonte de alimento mais estável, sem depender tanto da sorte da caça.',
    funFact: 'Essa mudança na forma de obter alimento é considerada uma das bases para o desenvolvimento das civilizações posteriores!',
    points: 1,
    options: [
      { id: 'A', text: 'A humanidade passou a depender menos da caça e coleta para sobreviver' },
      { id: 'B', text: 'A humanidade parou de evoluir' },
      { id: 'C', text: 'Surgiram os primeiros computadores' },
      { id: 'D', text: 'Acabou completamente a necessidade de trabalhar' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'O desenvolvimento de instrumentos como enxadas e foices de pedra polida ajudou os povos neolíticos a:',
    tip: 'Pensa na função prática dessas ferramentas: para que servem enxadas e foices?',
    funFact: 'Muitas dessas ferramentas neolíticas serviram de inspiração para instrumentos agrícolas usados até hoje!',
    points: 1,
    options: [
      { id: 'A', text: 'Caçar exclusivamente' },
      { id: 'B', text: 'Trabalhar a terra de forma mais eficiente' },
      { id: 'C', text: 'Construir prédios modernos' },
      { id: 'D', text: 'Fazer viagens espaciais' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'A vida em aldeias, comparada à vida totalmente nômade, trouxe mudanças como:',
    tip: 'Pensa em como ficar fixo em um lugar permite construir casas mais resistentes, ao invés de abrigos temporários.',
    funFact: 'Algumas casas neolíticas já eram construídas com tijolos de barro secos ao sol!',
    points: 1,
    options: [
      { id: 'A', text: 'Menos organização social' },
      { id: 'B', text: 'Menos segurança para os grupos' },
      { id: 'C', text: 'Mais estabilidade e a possibilidade de construir moradias mais duradouras' },
      { id: 'D', text: 'Nenhuma diferença significativa' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'A domesticação de animais como cães, cabras e ovelhas ajudou os povos neolíticos a obter:',
    tip: 'Pensa em vários benefícios que esses animais trazem, desde comida até ajuda em tarefas do dia a dia.',
    funFact: 'O cachorro é considerado um dos primeiros animais domesticados pelos seres humanos, ainda no período Paleolítico!',
    points: 1,
    options: [
      { id: 'A', text: 'Alimento, companhia e trabalho' },
      { id: 'B', text: 'Nenhum benefício' },
      { id: 'C', text: 'Apenas entretenimento' },
      { id: 'D', text: 'Somente transporte moderno' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'A Revolução Neolítica é um exemplo de como mudanças na forma de produzir alimento podem:',
    tip: 'Pensa em tudo que mudou por causa da agricultura: sedentarização, aldeias, especialização de tarefas...',
    funFact: 'Esse é um ótimo exemplo de como uma mudança tecnológica pode transformar completamente a forma como as pessoas vivem!',
    points: 1,
    options: [
      { id: 'A', text: 'Não afetar em nada a sociedade' },
      { id: 'B', text: 'Sempre piorar a vida das pessoas' },
      { id: 'C', text: 'Impedir qualquer tipo de desenvolvimento' },
      { id: 'D', text: 'Transformar profundamente a organização social dos seres humanos' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Bernardo aprendeu na aula de história que, no período Neolítico, os seres humanos passaram a plantar e colher seus próprios alimentos. Esse processo é chamado de:',
    tip: 'Lembre do nome dado à prática de cultivar plantas para obter alimento.',
    funFact: 'A agricultura é considerada uma das maiores invenções da história da humanidade!',
    points: 1,
    options: [
      { id: 'A', text: 'Nomadismo' },
      { id: 'B', text: 'Agricultura' },
      { id: 'C', text: 'Sedentarismo apenas' },
      { id: 'D', text: 'Comércio moderno' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Bernardo entendeu que, graças à agricultura, os grupos humanos passaram a viver fixos em um só lugar. Isso é chamado de:',
    tip: 'Lembre do nome dado ao processo de fixação em um determinado território.',
    funFact: 'A sedentarização foi um passo fundamental para o surgimento das primeiras aldeias e, depois, cidades!',
    points: 1,
    options: [
      { id: 'A', text: 'Nomadismo' },
      { id: 'B', text: 'Paleolítico' },
      { id: 'C', text: 'Sedentarização' },
      { id: 'D', text: 'Idade Média' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Bernardo viu, em uma maquete na escola, a representação de uma aldeia neolítica com casas simples e plantações ao redor. Isso mostra que os povos neolíticos:',
    tip: 'Pensa no que a maquete mostra: casas e plantações, sinais de uma vida fixa e organizada.',
    funFact: 'Construir maquetes é uma ótima forma de visualizar como eram organizadas as aldeias neolíticas!',
    points: 1,
    options: [
      { id: 'A', text: 'Continuavam totalmente nômades' },
      { id: 'B', text: 'Viviam exclusivamente da caça' },
      { id: 'C', text: 'Não tinham nenhuma organização' },
      { id: 'D', text: 'Já formavam pequenas comunidades fixas' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Bernardo aprendeu que a domesticação de animais, como cabras e ovelhas, ajudava os povos neolíticos a obter:',
    tip: 'Lembre dos vários benefícios práticos que esses animais domesticados traziam para os povos neolíticos.',
    funFact: 'A lã das ovelhas, por exemplo, já era usada para fazer tecidos e roupas desde tempos muito antigos!',
    points: 1,
    options: [
      { id: 'A', text: 'Alimento, lã e outros recursos' },
      { id: 'B', text: 'Apenas companhia, sem nenhuma utilidade' },
      { id: 'C', text: 'Meios de transporte modernos' },
      { id: 'D', text: 'Nenhum benefício' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Bernardo descobriu que, com o excedente de alimentos produzido pela agricultura, algumas pessoas da aldeia podiam se dedicar a outras tarefas, como fazer potes de cerâmica. Isso mostra o início de:',
    tip: 'Lembre de como o excedente de comida permitiu que nem todos precisassem fazer a mesma tarefa.',
    funFact: 'Essa especialização de tarefas é considerada um dos primeiros passos para o desenvolvimento de sociedades mais complexas!',
    points: 1,
    options: [
      { id: 'A', text: 'O fim total da agricultura' },
      { id: 'B', text: 'A volta ao nomadismo' },
      { id: 'C', text: 'Uma certa especialização de tarefas dentro da comunidade' },
      { id: 'D', text: 'O desaparecimento das aldeias' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Bernardo aprendeu que a cerâmica, criada no período Neolítico, era muito usada para:',
    tip: 'Lembre da principal utilidade prática dos potes e vasilhas de cerâmica.',
    funFact: 'Muitos pedaços de cerâmica antiga, chamados de "cacos", ajudam os arqueólogos a estudar os povos do passado!',
    points: 1,
    options: [
      { id: 'A', text: 'Fazer roupas' },
      { id: 'B', text: 'Armazenar alimentos e água' },
      { id: 'C', text: 'Construir casas inteiras' },
      { id: 'D', text: 'Substituir totalmente as ferramentas de caça' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Bernardo entendeu, com a ajuda do professor, que a vida em aldeias trouxe mais estabilidade às comunidades neolíticas, permitindo:',
    tip: 'Lembre de como ficar fixo em um lugar permite investir em construções mais resistentes.',
    funFact: 'Algumas dessas moradias neolíticas já eram construídas com tijolos de barro secos ao sol!',
    points: 1,
    options: [
      { id: 'A', text: 'A construção de moradias mais duradouras' },
      { id: 'B', text: 'Menos organização social' },
      { id: 'C', text: 'Menos segurança' },
      { id: 'D', text: 'O fim de qualquer tipo de trabalho' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Bernardo comparou a vida no Paleolítico (nômade) com a vida no Neolítico (sedentária) e percebeu que essa mudança foi:',
    tip: 'Pensa em tudo que mudou entre esses dois períodos: agricultura, moradia fixa, aldeias...',
    funFact: 'Por isso essa mudança é chamada de "revolução" — ela transformou profundamente a forma como as pessoas viviam!',
    points: 1,
    options: [
      { id: 'A', text: 'Sem nenhuma importância' },
      { id: 'B', text: 'Idêntica em tudo' },
      { id: 'C', text: 'Um retrocesso para a humanidade' },
      { id: 'D', text: 'Uma transformação profunda no modo de vida dos seres humanos' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Bernardo aprendeu que ferramentas como enxadas e foices de pedra polida ajudaram os povos neolíticos a:',
    tip: 'Lembre da função prática dessas ferramentas relacionadas à agricultura.',
    funFact: 'Essas ferramentas mais elaboradas mostram como a tecnologia foi evoluindo junto com as necessidades humanas!',
    points: 1,
    options: [
      { id: 'A', text: 'Caçar exclusivamente' },
      { id: 'B', text: 'Trabalhar a terra de forma mais eficiente' },
      { id: 'C', text: 'Construir prédios modernos' },
      { id: 'D', text: 'Fazer viagens' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'Ao final do simulado, Bernardo compreendeu que a Revolução Neolítica foi um marco importante porque:',
    tip: 'Pensa em tudo que Bernardo aprendeu nesse simulado: agricultura, sedentarização, aldeias, cerâmica...',
    funFact: 'Parabéns por terminar o simulado sobre a Revolução Neolítica! Agora você já entende como essa grande transformação mudou para sempre o modo de vida da humanidade, assim como o Bernardo aprendeu na escola!',
    points: 1,
    options: [
      { id: 'A', text: 'Não trouxe nenhuma mudança para a humanidade' },
      { id: 'B', text: 'Fez os seres humanos voltarem a ser totalmente nômades' },
      { id: 'C', text: 'Transformou a forma como os seres humanos viviam, através da agricultura e da vida em aldeias' },
      { id: 'D', text: 'Acabou com a necessidade de trabalhar' },
    ],
    correctAnswer: 'C',
  },
];
