export const questoesPortugues9AnoB1Av1 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'O que é "variação linguística"?',
    tip: 'Pensa em como seus familiares de outra região falam algumas palavras diferente de você — isso é erro ou é só uma forma diferente de falar a mesma língua?',
    funFact: 'Todas as línguas vivas do mundo têm variações — isso mostra que a língua está sempre em movimento, nunca parada!',
    points: 1,
    options: [
      { id: 'A', text: 'Um erro de português que deve ser sempre corrigido' },
      { id: 'B', text: 'Uma forma de falar usada apenas em livros' },
      { id: 'C', text: 'As diferentes formas de falar e escrever uma mesma língua, de acordo com a região, grupo social ou situação' },
      { id: 'D', text: 'Uma língua estrangeira' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'Qual destes é um exemplo de variação linguística regional?',
    tip: 'Pensa em como a mesma raiz pode ter nomes diferentes dependendo da região do Brasil onde você está.',
    funFact: 'Essa mesma raiz também é chamada de "macaxeira" em algumas regiões do Nordeste!',
    points: 1,
    options: [
      { id: 'A', text: 'Usar gírias' },
      { id: 'B', text: 'Falar errado de propósito' },
      { id: 'C', text: 'Escrever um e-mail formal' },
      { id: 'D', text: 'Palavras e expressões diferentes usadas em diferentes regiões do Brasil, como "mandioca" e "aipim"' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'O que é "preconceito linguístico"?',
    tip: 'Pensa na palavra "preconceito" — ela tem a ver com julgar alguém de forma injusta, antes mesmo de conhecê-la.',
    funFact: 'Linguistas afirmam que não existe uma forma de falar "superior" a outra — todas as variações são válidas dentro de seu contexto!',
    points: 1,
    options: [
      { id: 'A', text: 'Discriminar uma pessoa por causa do seu jeito de falar ou escrever' },
      { id: 'B', text: 'Corrigir um erro de ortografia' },
      { id: 'C', text: 'Estudar gramática na escola' },
      { id: 'D', text: 'Aprender uma língua estrangeira' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'Qual destas situações exige o uso da linguagem formal?',
    tip: 'Pensa em qual dessas situações é mais séria e oficial, exigindo mais cuidado com as regras da língua.',
    funFact: 'A linguagem formal costuma seguir mais rigorosamente a norma padrão da língua, usada em documentos, provas e situações profissionais!',
    points: 1,
    options: [
      { id: 'A', text: 'Uma conversa com amigos no recreio' },
      { id: 'B', text: 'Uma redação para um concurso público' },
      { id: 'C', text: 'Uma mensagem de texto para um amigo' },
      { id: 'D', text: 'Uma piada contada em uma festa' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'A função "referencial" (ou informativa) da linguagem tem como objetivo principal:',
    tip: 'Pensa na palavra "referencial" — ela tem a ver com "referência", ou seja, informações sobre algo real.',
    funFact: 'Notícias de jornal costumam usar bastante a função referencial, já que o objetivo principal é informar os fatos!',
    points: 1,
    options: [
      { id: 'A', text: 'Expressar os sentimentos de quem fala' },
      { id: 'B', text: 'Convencer o leitor a fazer algo' },
      { id: 'C', text: 'Informar e transmitir dados objetivos sobre o mundo' },
      { id: 'D', text: 'Explicar o significado de uma palavra' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'A função "emotiva" (ou expressiva) da linguagem está centrada em:',
    tip: 'Pensa na palavra "emotiva" — ela tem a ver com emoção, ou seja, com o que a pessoa que fala está sentindo.',
    funFact: 'Cartas pessoais e diários costumam usar bastante a função emotiva da linguagem!',
    points: 1,
    options: [
      { id: 'A', text: 'Quem fala, expressando sentimentos e opiniões pessoais' },
      { id: 'B', text: 'Apenas informações objetivas' },
      { id: 'C', text: 'Apenas a explicação da própria língua' },
      { id: 'D', text: 'Apenas o código usado na comunicação' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'A função "conativa" (ou apelativa) da linguagem tem como objetivo:',
    tip: 'Pensa em comerciais de TV que tentam te convencer a comprar algo — qual é o objetivo principal dessa mensagem?',
    funFact: 'A função conativa também é chamada de "apelativa" porque "apela" diretamente para quem está recebendo a mensagem!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas informar fatos' },
      { id: 'B', text: 'Apenas expressar emoções de quem fala' },
      { id: 'C', text: 'Explicar palavras da língua' },
      { id: 'D', text: 'Convencer ou influenciar o receptor da mensagem, como em um anúncio publicitário' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'A função "poética" da linguagem está voltada principalmente para:',
    tip: 'Pensa em um poema: o que importa ali não é só o que é dito, mas também como é dito — o som, o ritmo, as palavras escolhidas.',
    funFact: 'A função poética não aparece só em poemas — ela também pode estar presente em músicas, slogans e até em piadas bem elaboradas!',
    points: 1,
    options: [
      { id: 'A', text: 'A transmissão de informações científicas' },
      { id: 'B', text: 'A forma e a elaboração estética da própria mensagem' },
      { id: 'C', text: 'Apenas corrigir erros gramaticais' },
      { id: 'D', text: 'Apenas a comunicação entre máquinas' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'A função "metalinguística" da linguagem ocorre quando:',
    tip: 'Pensa na palavra "metalinguística" — "meta" indica algo que fala sobre si mesmo. O que fala sobre a própria língua?',
    funFact: 'Quando um professor explica uma regra de gramática, ele também está usando a função metalinguística!',
    points: 1,
    options: [
      { id: 'A', text: 'O texto expressa emoções fortes' },
      { id: 'B', text: 'O texto tenta convencer o leitor' },
      { id: 'C', text: 'A linguagem é usada para explicar a própria linguagem, como em um dicionário' },
      { id: 'D', text: 'O texto é sempre em verso' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'A função "fática" da linguagem tem como objetivo principal:',
    tip: 'Pensa em expressões que usamos só para manter a conversa funcionando, como "entendeu?" ou "não é?".',
    funFact: 'A função fática é muito usada no início e no fim de conversas, para verificar se a comunicação está realmente acontecendo!',
    points: 1,
    options: [
      { id: 'A', text: 'Iniciar, manter ou verificar o contato entre quem fala e quem escuta, como em um "alô?"' },
      { id: 'B', text: 'Explicar regras de gramática' },
      { id: 'C', text: 'Convencer alguém a comprar um produto' },
      { id: 'D', text: 'Descrever cientificamente um fenômeno' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'Por que a variação linguística não deve ser vista como "erro", mas como uma característica natural da língua?',
    tip: 'Lembra da Questão 1 desta prova? Pensa em como a língua portuguesa falada hoje é diferente da falada há 100 anos.',
    funFact: 'O português falado no Brasil tem diferenças importantes do português falado em Portugal, mas os dois são igualmente corretos!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque só existe uma forma correta de falar português' },
      { id: 'B', text: 'Porque as pessoas que falam diferente não sabem português' },
      { id: 'C', text: 'Porque variações são sempre proibidas na escola' },
      { id: 'D', text: 'Porque toda língua viva muda e se adapta de acordo com região, grupo social e contexto histórico' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'Qual é uma consequência negativa do preconceito linguístico?',
    tip: 'Lembra da Questão 3 desta prova? Pensa em como alguém pode se sentir excluído só por falar diferente.',
    funFact: 'Combater o preconceito linguístico é um dos objetivos importantes do ensino de português nas escolas atualmente!',
    points: 1,
    options: [
      { id: 'A', text: 'Ele incentiva o respeito às diferenças culturais' },
      { id: 'B', text: 'Ele pode gerar discriminação e exclusão social de pessoas por causa do seu jeito de falar' },
      { id: 'C', text: 'Ele melhora automaticamente a educação de todos' },
      { id: 'D', text: 'Ele não tem nenhum efeito sobre as pessoas' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'Em qual destas situações seria mais adequado usar a linguagem informal?',
    tip: 'Pensa em qual dessas situações é mais íntima e descontraída, sem exigência de formalidade.',
    funFact: 'A escolha entre linguagem formal e informal depende do contexto, do interlocutor e do objetivo da comunicação!',
    points: 1,
    options: [
      { id: 'A', text: 'Uma entrevista de emprego' },
      { id: 'B', text: 'Um discurso oficial' },
      { id: 'C', text: 'Uma conversa por mensagem com um amigo próximo' },
      { id: 'D', text: 'Um documento jurídico' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'Em um anúncio publicitário que tenta convencer o consumidor a comprar um produto, qual função da linguagem está mais presente?',
    tip: 'É a mesma função da Questão 7 desta prova.',
    funFact: 'Publicitários estudam muito a função conativa para criar anúncios cada vez mais persuasivos!',
    points: 1,
    options: [
      { id: 'A', text: 'Função conativa (apelativa)' },
      { id: 'B', text: 'Função fática' },
      { id: 'C', text: 'Função metalinguística' },
      { id: 'D', text: 'Função referencial' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'Em um poema que valoriza o som e o ritmo das palavras, além do seu significado, qual função da linguagem predomina?',
    tip: 'É a mesma função da Questão 8 desta prova.',
    funFact: 'Recursos como a rima e a aliteração são exemplos de como a função poética valoriza a forma das palavras!',
    points: 1,
    options: [
      { id: 'A', text: 'Função referencial' },
      { id: 'B', text: 'Função conativa' },
      { id: 'C', text: 'Função fática' },
      { id: 'D', text: 'Função poética' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'Quando um dicionário explica o significado de uma palavra, qual função da linguagem está sendo usada?',
    tip: 'É a mesma função da Questão 9 desta prova.',
    funFact: 'Toda vez que alguém explica o significado de uma palavra, está usando a linguagem para falar sobre ela mesma!',
    points: 1,
    options: [
      { id: 'A', text: 'Função emotiva' },
      { id: 'B', text: 'Função conativa' },
      { id: 'C', text: 'Função metalinguística' },
      { id: 'D', text: 'Função fática' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'Em uma notícia de jornal que apenas relata fatos, sem opiniões, qual função da linguagem é predominante?',
    tip: 'É a mesma função da Questão 5 desta prova.',
    funFact: 'Jornalistas são treinados para separar fatos (função referencial) de opiniões em suas matérias!',
    points: 1,
    options: [
      { id: 'A', text: 'Função emotiva' },
      { id: 'B', text: 'Função referencial' },
      { id: 'C', text: 'Função poética' },
      { id: 'D', text: 'Função conativa' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'Quando alguém diz "alô, você está me ouvindo?" ao telefone, qual função da linguagem está sendo usada?',
    tip: 'É a mesma função da Questão 10 desta prova.',
    funFact: 'Expressões como "oi", "alô" e "está me ouvindo?" servem principalmente para garantir que a comunicação está funcionando!',
    points: 1,
    options: [
      { id: 'A', text: 'Função fática' },
      { id: 'B', text: 'Função referencial' },
      { id: 'C', text: 'Função metalinguística' },
      { id: 'D', text: 'Função poética' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'Por que é importante que a escola reconheça e respeite a variação linguística dos alunos, ao mesmo tempo em que ensina a norma padrão?',
    tip: 'Pensa em como é importante tanto respeitar a forma de falar de cada um quanto saber usar a norma padrão em situações formais.',
    funFact: 'Conhecer a norma padrão amplia as oportunidades do aluno, sem que ele precise abandonar sua forma natural de falar!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque a norma padrão não tem nenhuma utilidade' },
      { id: 'B', text: 'Porque não existe diferença entre as variações linguísticas' },
      { id: 'C', text: 'Porque todos devem falar de um único jeito, sempre' },
      { id: 'D', text: 'Porque respeitar a variação evita preconceito, e ensinar a norma padrão amplia as possibilidades de comunicação do aluno' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'Qual é a diferença entre "norma padrão" e "variação linguística regional"?',
    tip: 'Pensa em tudo que você já estudou nesta prova sobre os diferentes contextos de uso da língua.',
    funFact: 'A norma padrão é importante para a comunicação formal e para garantir que pessoas de diferentes regiões se entendam em contextos oficiais!',
    points: 1,
    options: [
      { id: 'A', text: 'Não existe nenhuma diferença entre elas' },
      { id: 'B', text: 'A norma padrão é a única forma correta e todas as outras são erradas' },
      { id: 'C', text: 'A norma padrão é usada em contextos formais, enquanto as variações regionais são formas legítimas da língua usadas em diferentes contextos e regiões' },
      { id: 'D', text: 'A variação regional é superior à norma padrão' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Bernardo percebeu que seu colega de uma cidade do interior usa palavras diferentes das que ele usa na capital, mas as duas formas estão corretas. Isso é um exemplo de:',
    tip: 'É o mesmo conceito das Questões 1 e 2 desta prova.',
    funFact: 'O Brasil é tão grande que existem diversas variações regionais, mesmo dentro de um único país!',
    points: 1,
    options: [
      { id: 'A', text: 'Variação linguística regional' },
      { id: 'B', text: 'Erro grave de português' },
      { id: 'C', text: 'Linguagem metalinguística' },
      { id: 'D', text: 'Função conativa da linguagem' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Bernardo ouviu um colega rir do jeito de falar de outro aluno vindo de outra região. O professor explicou que essa atitude é chamada de:',
    tip: 'É o mesmo conceito das Questões 3 e 12 desta prova.',
    funFact: 'Entender que não existe forma "errada" de falar é um passo importante para combater esse tipo de preconceito!',
    points: 1,
    options: [
      { id: 'A', text: 'Respeito linguístico' },
      { id: 'B', text: 'Preconceito linguístico' },
      { id: 'C', text: 'Variação regional correta' },
      { id: 'D', text: 'Função poética da linguagem' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Bernardo viu um anúncio na TV tentando convencer as pessoas a comprar um produto. Qual função da linguagem está mais presente nesse anúncio?',
    tip: 'É a mesma função das Questões 7 e 14 desta prova.',
    funFact: 'Slogans publicitários são criados justamente pensando em como usar a função conativa de forma criativa!',
    points: 1,
    options: [
      { id: 'A', text: 'Função referencial' },
      { id: 'B', text: 'Função fática' },
      { id: 'C', text: 'Função metalinguística' },
      { id: 'D', text: 'Função conativa' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Bernardo abriu o dicionário para descobrir o significado de uma palavra difícil. Isso é um exemplo de qual função da linguagem?',
    tip: 'É a mesma função das Questões 9 e 16 desta prova.',
    funFact: 'O próprio dicionário é um exemplo completo de função metalinguística, já que ele usa a língua para explicar a própria língua!',
    points: 1,
    options: [
      { id: 'A', text: 'Função emotiva' },
      { id: 'B', text: 'Função conativa' },
      { id: 'C', text: 'Função metalinguística' },
      { id: 'D', text: 'Função fática' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Bernardo escreveu uma redação formal para um concurso da escola. Por que ele usou a norma padrão da língua nesse texto?',
    tip: 'É a mesma ideia das Questões 4 e 20 desta prova.',
    funFact: 'Saber usar a norma padrão em situações formais, como provas e concursos, é uma habilidade muito valorizada!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque contextos formais, como concursos, geralmente exigem o uso da norma padrão' },
      { id: 'B', text: 'Porque a norma padrão é a única forma de falar corretamente em qualquer situação' },
      { id: 'C', text: 'Porque é proibido usar variações linguísticas em qualquer lugar' },
      { id: 'D', text: 'Porque a redação não tinha nenhuma relação com a linguagem formal' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Bernardo mandou uma mensagem de texto informal para um amigo, usando gírias e abreviações. Isso mostra que a linguagem:',
    tip: 'É a mesma ideia das Questões 13 e 20 desta prova.',
    funFact: 'Saber adaptar a linguagem a cada situação é uma habilidade chamada "competência comunicativa"!',
    points: 1,
    options: [
      { id: 'A', text: 'Deve ser sempre formal, em qualquer situação' },
      { id: 'B', text: 'Não varia de acordo com o contexto' },
      { id: 'C', text: 'É sempre igual, independente de quem fala' },
      { id: 'D', text: 'Se adapta de acordo com a situação e o grau de intimidade entre as pessoas' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Bernardo leu um poema em que o som e o ritmo das palavras eram tão importantes quanto o significado. Qual função da linguagem predominava nesse poema?',
    tip: 'É a mesma função das Questões 8 e 15 desta prova.',
    funFact: 'Muitos poetas escolhem palavras pensando tanto no significado quanto no som que elas produzem ao serem lidas!',
    points: 1,
    options: [
      { id: 'A', text: 'Função referencial' },
      { id: 'B', text: 'Função poética' },
      { id: 'C', text: 'Função fática' },
      { id: 'D', text: 'Função conativa' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Bernardo leu uma notícia de jornal que só apresentava fatos, sem opiniões pessoais do autor. Qual função da linguagem predominava nesse texto?',
    tip: 'É a mesma função das Questões 5 e 17 desta prova.',
    funFact: 'Jornais sérios costumam separar claramente as seções de notícias (fatos) e de opinião (artigos)!',
    points: 1,
    options: [
      { id: 'A', text: 'Função emotiva' },
      { id: 'B', text: 'Função conativa' },
      { id: 'C', text: 'Função referencial' },
      { id: 'D', text: 'Função poética' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Bernardo aprendeu que respeitar a forma de falar de cada pessoa é importante para evitar o preconceito linguístico. Isso significa que:',
    tip: 'Pensa em tudo que você aprendeu nesta prova sobre a importância de respeitar as diferentes formas de falar.',
    funFact: 'Reconhecer a legitimidade de todas as variações linguísticas é um dos princípios mais importantes do estudo moderno da língua!',
    points: 1,
    options: [
      { id: 'A', text: 'Todas as variações linguísticas são formas legítimas e válidas de comunicação' },
      { id: 'B', text: 'Só existe uma forma certa de falar português' },
      { id: 'C', text: 'Pessoas de regiões diferentes falam de forma errada' },
      { id: 'D', text: 'A escola nunca deve ensinar a norma padrão' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'No fim da aula, o professor perguntou a Bernardo o que ele aprendeu sobre a variação linguística e as funções da linguagem. Bernardo respondeu corretamente:',
    tip: 'Pensa em tudo que você aprendeu nesta prova sobre variação linguística e as diferentes funções da linguagem.',
    funFact: 'Entender essas funções ajuda a interpretar melhor qualquer texto que você ler, da propaganda ao poema!',
    points: 1,
    options: [
      { id: 'A', text: 'Que só existe uma forma certa de usar a língua, sempre' },
      { id: 'B', text: 'Que a língua varia de acordo com o contexto e a região, e pode cumprir diferentes funções, como informar, convencer ou expressar emoções' },
      { id: 'C', text: 'Que a linguagem nunca muda, em nenhuma situação' },
      { id: 'D', text: 'Que a função da linguagem é sempre a mesma, em qualquer texto' },
    ],
    correctAnswer: 'B',
  },
];
