export const questoesArte1EmB4Av1 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "O Cubismo surgiu em Paris por volta de 1907-1908, desenvolvido por Pablo Picasso e Georges Braque. O que caracteriza a visão cubista de representar o mundo?",
    tip: "O Cubismo rompe radicalmente com a perspectiva linear do Renascimento. Como os cubistas viam e representavam os objetos?",
    funFact: "\"Você sabia?\" — Segundo a lenda, o crítico Louis Vauxcelles (o mesmo que criou o nome 'Fauvismo') também criou o nome 'Cubismo' — ao ver as obras de Braque e comentar que eram compostas de 'cubos'. Vauxcelles teve a incrível (des)sorte de batizar dois dos movimentos mais importantes da arte do século XX.",
    points: 1,
    options: [
      { id: "A", text: "Representação naturalista com técnica de sfumato e perspectiva atmosférica" },
      { id: "B", text: "Representação de objetos a partir de múltiplos pontos de vista simultaneamente, fragmentando as formas em planos geométricos" },
      { id: "C", text: "Representação expressiva de emoções internas através de distorção e cores intensas" },
      { id: "D", text: "Representação abstrata baseada exclusivamente em formas geométricas sem referência ao mundo visível" },
    ],
    correctAnswer: "B",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "'Les Demoiselles d'Avignon' (1907), de Picasso, é considerada a obra que inaugurou o Cubismo. O que tornava essa pintura tão radicalmente nova?",
    tip: "Picasso combinou influências muito diversas — arte africana, escultura ibérica e deformação proposital das figuras. O que o resultado visual provocava?",
    funFact: "\"Você sabia?\" — O próprio Picasso chamou Les Demoiselles de 'meu premier exorcisme' — era uma tela com a qual ele lutou por meses e que nunca considerou terminada. A obra ficou no ateliê por anos e só foi exposta publicamente em 1916, quando o Cubismo já havia sido assimilado pela vanguarda.",
    points: 1,
    options: [
      { id: "A", text: "Por ser a primeira pintura impressionista a usar figuras humanas de tamanho natural" },
      { id: "B", text: "Por ser a primeira obra de arte a usar fotografia como referência para figuras em movimento" },
      { id: "C", text: "Por representar cinco figuras femininas com rostos influenciados por máscaras africanas e ibéricas, rompendo com toda convenção de beleza clássica" },
      { id: "D", text: "Por ser a primeira obra cubista a usar colagem com recortes de jornal sobre tela" },
    ],
    correctAnswer: "C",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "A colaboração entre Picasso e Georges Braque entre 1908 e 1914 foi tão intensa que eles mesmos às vezes não conseguiam distinguir suas obras. O que essa colaboração gerou?",
    tip: "Pense na raridade de dois grandes artistas trabalhando em tão estreita sintonia — como isso é descrito pelos historiadores?",
    funFact: "\"Você sabia?\" — Braque e Picasso se encontravam quase diariamente nos estúdios do Bateau-Lavoir em Montmartre. Braque disse: 'Éramos como alpinistas amarrados um ao outro'. Quando a Primeira Guerra Mundial começou e Braque foi convocado, Picasso foi a estação despedir-se dele e disse: 'Nunca o encontrei mais'.",
    points: 1,
    options: [
      { id: "A", text: "O desenvolvimento completo do Cubismo Analítico — a fase mais radical, com paleta reduzida e formas completamente fragmentadas" },
      { id: "B", text: "A fusão do Cubismo com o Futurismo, criando um novo estilo chamado 'Cubo-Futurismo'" },
      { id: "C", text: "A criação do Surrealismo como tentativa de ir além das limitações do Cubismo" },
      { id: "D", text: "O desenvolvimento do Expressionismo Abstrato americano a partir das experiências cubistas europeias" },
    ],
    correctAnswer: "A",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "'Guernica' (1937), de Pablo Picasso, é considerada a mais poderosa obra de arte política do século XX. O que ela representa?",
    tip: "Foi criada em resposta a um bombardeio específico durante a Guerra Civil Espanhola. O que Picasso quis documentar e denunciar?",
    funFact: "\"Você sabia?\" — Quando um oficial nazista visitou o ateliê de Picasso em Paris durante a ocupação e viu uma fotografia de Guernica, perguntou: 'Você fez isso?' Picasso respondeu: 'Não — vocês fizeram.' Uma das frases mais citadas sobre arte e política do século XX.",
    points: 1,
    options: [
      { id: "A", text: "A chegada de Franco ao poder e a dissolução da República Espanhola em Madrid" },
      { id: "B", text: "A derrota do exército republicano na Batalha do Ebro durante a Guerra Civil" },
      { id: "C", text: "O bombardeio da cidade basca de Guernica pela aviação nazista a serviço de Franco — símbolo do horror da guerra moderna sobre civis" },
      { id: "D", text: "A destruição do Museu do Prado durante os bombardeios de Madrid na Guerra Civil" },
    ],
    correctAnswer: "D",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "O Cubismo se desenvolveu em duas fases principais: Cubismo Analítico e Cubismo Sintético. Qual é a diferença entre elas?",
    tip: "O Analítico desmonta o objeto em pedaços quase irreconhecíveis; o Sintético 'reconstrói' de uma forma diferente. Como cada um funciona?",
    funFact: "\"Você sabia?\" — O Cubismo Analítico chegou a tal grau de fragmentação (c.1910-1912) que as obras usavam quase só marrons e cinzas — as cores poderiam 'distrair' da percepção das formas. Era como uma análise intelectual do espaço levada ao extremo, quase um enigma visual.",
    points: 1,
    options: [
      { id: "A", text: "O Analítico usa cores vivas; o Sintético usa paleta monocromática em marrons e cinzas" },
      { id: "B", text: "O Analítico fragmenta o objeto em múltiplos planos quase abstratos; o Sintético usa planos maiores, mais legíveis, com colagem e símbolos" },
      { id: "C", text: "O Analítico é uma criação de Picasso; o Sintético é exclusivamente de Braque" },
      { id: "D", text: "O Analítico é bidimensional; o Sintético incorpora objetos tridimensionais na tela" },
    ],
    correctAnswer: "B",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "Braque e Picasso introduziram a colagem na arte erudita ao criar os 'papiers collés'. O que eles colavam e qual era o efeito artístico?",
    tip: "Eles não colavam obras de arte — colavam materiais muito comuns do cotidiano. O que havia de revolucionário nisso?",
    funFact: "\"Você sabia?\" — Ao colar uma manchete de jornal numa tela que representava um violão, Braque criou uma ambiguidade radical: o papel de jornal era ao mesmo tempo a textura do violão E um objeto real com texto legível. Essa tensão entre representação e realidade tornou-se uma das questões centrais da arte contemporânea.",
    points: 1,
    options: [
      { id: "A", text: "Colavam retratos fotográficos de artistas famosos como homenagem irônica às tradições acadêmicas" },
      { id: "B", text: "Colavam tecidos e bordados para introduzir texturas têxteis na superfície pictórica" },
      { id: "C", text: "Recortes de jornais, papéis de parede, embalagens — materiais do cotidiano que questionavam a fronteira entre arte e realidade" },
      { id: "D", text: "Fotografias de obras de arte clássicas recortadas e recompostas em novas formações" },
    ],
    correctAnswer: "C",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "O Cubismo foi uma revolução na representação espacial comparável à perspectiva renascentista. Por que os cubistas rejeitaram o ponto de vista único?",
    tip: "Um ponto de vista único captura o objeto num só momento e ângulo. O que os cubistas achavam insuficiente nessa limitação?",
    funFact: "\"Você sabia?\" — O filósofo Henri Bergson publicou 'A Evolução Criadora' (1907) — o mesmo ano de Les Demoiselles. Bergson argumentava que a realidade é movimento contínuo, não instantâneos fixos. Os cubistas nunca citaram Bergson diretamente, mas as ideias estavam no ar — a sincronia intelectual foi impressionante.",
    points: 1,
    options: [
      { id: "A", text: "Porque queriam representar o objeto em toda sua complexidade — como o conhecemos, não como o vemos num único instante" },
      { id: "B", text: "Porque o ponto de vista único era associado ao academicismo do qual queriam se libertar completamente" },
      { id: "C", text: "Porque a perspectiva de ponto único era tecnicamente difícil e os cubistas preferiam técnicas mais simples" },
      { id: "D", text: "Porque seguiam a teoria de Einstein sobre a relatividade do espaço-tempo, publicada em 1905" },
    ],
    correctAnswer: "A",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "O Futurismo italiano foi lançado em 1909 com um manifesto publicado no jornal Le Figaro em Paris. O que esse manifesto proclamava?",
    tip: "O Manifesto Futurista de Marinetti continha propostas radicais sobre arte, cultura e até política. O que glorificava e o que queria destruir?",
    funFact: "\"Você sabia?\" — O Manifesto Futurista dizia explicitamente: 'Queremos destruir os museus, as bibliotecas, lutar contra o moralismo, o feminismo e toda vileza oportunista e utilitária'. Era arte como provocação política radical — e antecipou ligações posteriores com o fascismo italiano.",
    points: 1,
    options: [
      { id: "A", text: "A criação de museus nacionais para preservar o patrimônio da civilização italiana" },
      { id: "B", text: "O retorno às tradições artísticas medievais como antídoto à industrialização moderna" },
      { id: "C", text: "A colaboração internacional entre artistas de todas as correntes contra o academicismo" },
      { id: "D", text: "A glorificação da velocidade, da máquina, do perigo e da guerra — e a destruição dos museus e das tradições como coisas mortas" },
    ],
    correctAnswer: "D",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "Filippo Tommaso Marinetti foi o fundador do Futurismo. O que o Futurismo representava como postura cultural em relação ao passado da Itália?",
    tip: "A Itália era o país do Renascimento, dos museus, das ruínas gregas e romanas — Marinetti tinha uma relação específica com todo esse passado glorioso.",
    funFact: "\"Você sabia?\" — Marinetti escreveu o manifesto futurista após um acidente de carro em que caiu num fosso e emergiu da lama como se estivesse renascendo. Ele interpretou o acidente como um batismo na modernidade industrial — e a obra nasceu dessa experiência quase mítica de quase-morte e renascimento.",
    points: 1,
    options: [
      { id: "A", text: "Uma celebração do patrimônio histórico italiano como a maior riqueza cultural da civilização ocidental" },
      { id: "B", text: "Uma rejeição violenta do passado italiano como um peso morto — museus eram cemitérios, ruínas eram obstáculos ao progresso" },
      { id: "C", text: "Uma síntese da tradição clássica com a modernidade industrial para criar uma identidade italiana única" },
      { id: "D", text: "Uma defesa do artesanato tradicional italiano frente à industrialização que destruía os ofícios manuais" },
    ],
    correctAnswer: "B",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "Umberto Boccioni foi o principal pintor e escultor do Futurismo. Qual obra sua ilustra melhor a representação futurista do movimento?",
    tip: "É uma escultura que mostra uma figura humana em marcha — mas não com a pose estática de uma escultura clássica.",
    funFact: "\"Você sabia?\" — Boccioni morreu em 1916, aos 33 anos, em consequência de uma queda de cavalo durante exercícios militares. Sua morte prematura privou o Futurismo de seu maior talento artístico — e o movimento nunca mais alcançou o nível que havia atingido com ele.",
    points: 1,
    options: [
      { id: "A", text: "'Nu Descendo uma Escada' — a figura humana capturada em múltiplos momentos simultâneos" },
      { id: "B", text: "'Dinamismo de um Cão numa Coleira' — a série de patas do cão capturada como fotografia de longa exposição" },
      { id: "C", text: "'Formas Únicas de Continuidade no Espaço' — escultura de figura em marcha com formas que evocam velocidade e energia cinética" },
      { id: "D", text: "'Composição em Vermelho' — pintura abstrata com formas geométricas em espiral representando a cidade em movimento" },
    ],
    correctAnswer: "C",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "O Futurismo celebrava a velocidade como valor estético supremo. Como os pintores futuristas tentavam representar a velocidade na pintura?",
    tip: "Uma pintura é estática por definição — como representar algo que está em movimento constante numa superfície imóvel?",
    funFact: "\"Você sabia?\" — Os futuristas conheciam a cronofotografia de Étienne-Jules Marey (que fotografava movimentos em sequência numa única imagem). Giacomo Balla pintou 'Dinamismo de um Cão em Coleira' (1912), onde as patas e o focinho do cão se multiplicam como na cronofotografia.",
    points: 1,
    options: [
      { id: "A", text: "Pintando fundo branco para que as figuras em movimento não tivessem nada que as retardasse" },
      { id: "B", text: "Usando o pontilhismo com pontos muito pequenos para sugerir vibração e tremor das figuras" },
      { id: "C", text: "Pintando figuras completamente borradas, como numa fotografia em longa exposição" },
      { id: "D", text: "Mostrando múltiplas fases do movimento simultaneamente, como uma cronofotografia ou uma exposição múltipla" },
    ],
    correctAnswer: "D",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "O Construtivismo surgiu na Rússia após a Revolução Bolchevique de 1917. Qual era sua proposta artística essencial?",
    tip: "Os construtivistas queriam que a arte servisse a um propósito social específico — qual era na Rússia revolucionária?",
    funFact: "\"Você sabia?\" — Os construtivistas russos foram os primeiros artistas na história a defender que 'arte pela arte' era um luxo burguês sem sentido. Para eles, um bom cartaz que ensinava um camponês analfabeto a ler era mais valioso que uma pintura num museu que só a elite via.",
    points: 1,
    options: [
      { id: "A", text: "Colocar a arte a serviço da construção de uma nova sociedade socialista — arte funcional, industrial e de uso coletivo" },
      { id: "B", text: "Construir obras de arte com materiais industriais como aço e vidro ao invés de tinta e madeira" },
      { id: "C", text: "Criar uma arte pura e abstrata desvinculada de qualquer função social ou política" },
      { id: "D", text: "Preservar e construir arquivos da arte russa tradicional ameaçada pela modernização" },
    ],
    correctAnswer: "A",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "Os construtivistas russos aplicaram seu estilo a áreas além da pintura. Onde o Construtivismo teve maior impacto prático?",
    tip: "Se a arte deve servir ao povo, ela não fica em museus — vai para onde as pessoas realmente vivem e trabalham.",
    funFact: "\"Você sabia?\" — O designer gráfico construtivista russo Alexander Rodchenko criou cartazes e fotomontagens que influenciaram toda a identidade visual do século XX — do design de livros à publicidade. Seus experimentos no design gráfico ainda são estudados em escolas de design do mundo todo.",
    points: 1,
    options: [
      { id: "A", text: "Na pintura religiosa ortodoxa, adaptando ícones tradicionais ao estilo geométrico moderno" },
      { id: "B", text: "No design gráfico, cartazes, arquitetura, tipografia e design de objetos de uso cotidiano" },
      { id: "C", text: "Na moda alta, criando vestimentas para a aristocracia russa que permaneceu após a revolução" },
      { id: "D", text: "Na produção de documentários cinematográficos sobre as conquistas da Revolução" },
    ],
    correctAnswer: "B",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "Alexander Rodchenko foi um dos principais artistas construtivistas russos. Por que sua obra 'Jovem Mulher com Leica' (fotografia, 1934) é considerada importante?",
    tip: "Rodchenko via a fotografia de um ângulo diferente do convencional — literalmente. O que havia de original em sua técnica fotográfica?",
    funFact: "\"Você sabia?\" — Rodchenko foi um dos primeiros fotógrafos a explorar sistematicamente ângulos picados (de cima para baixo) e contra-picados (de baixo para cima). Argumentava que a câmera devia mostrar a realidade de ângulos incomuns para sacudir a percepção acomodada do espectador.",
    points: 1,
    options: [
      { id: "A", text: "Por ser a primeira fotografia em cores da história soviética, revelando a vida cotidiana em Moscou" },
      { id: "B", text: "Por ser um retrato de uma operária que se tornou heroína nacional após a Revolução" },
      { id: "C", text: "Por usar ângulos e perspectivas incomuns (picados e contra-picados) que renovaram a linguagem fotográfica" },
      { id: "D", text: "Por ser a primeira fotografia publicada num jornal soviético de grande circulação" },
    ],
    correctAnswer: "C",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "O Suprematismo foi criado pelo artista russo Kazimir Malevich por volta de 1915. O que é o Suprematismo?",
    tip: "O nome vem de 'supremacia' — a supremacia de algo específico sobre tudo o mais na arte. De quê?",
    funFact: "\"Você sabia?\" — Malevich pintou o Quadrado Negro sobre Fundo Branco (1915) como a última obra possível — o ponto zero da pintura, a partir do qual não havia mais o que reduzir. Na exposição onde foi mostrada, foi pendurado no canto da parede, no lugar onde os russos ortodoxos penduravam os ícones religiosos — um gesto carregado de simbolismo.",
    points: 1,
    options: [
      { id: "A", text: "Arte decorativa baseada em padrões geométricos de tecidos tradicionais da Rússia czarista" },
      { id: "B", text: "Arte concreta que usava exclusivamente materiais industriais como aço e cimento armado" },
      { id: "C", text: "Arte de propaganda política do Estado soviético com imagens de trabalhadores e símbolos comunistas" },
      { id: "D", text: "Arte abstrata baseada na supremacia da sensação pura — formas geométricas simples num vazio que transcende qualquer referência ao mundo visível" },
    ],
    correctAnswer: "D",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "'Quadrado Negro sobre Fundo Branco' (1915) de Kazimir Malevich é considerada uma das obras mais radicais da história da arte. Por quê?",
    tip: "É apenas um quadrado preto sobre fundo branco. O que isso significa como manifesto artístico e filosófico?",
    funFact: "\"Você sabia?\" — Malevich expôs 36 obras suprematistas em 1915. A mais simples, o Quadrado Negro, era a mais radical: qualquer referência ao mundo visível havia desaparecido completamente. Para Malevich, isso não era empobrecimento — era a libertação final da arte de qualquer utilidade prática ou referência descritiva.",
    points: 1,
    options: [
      { id: "A", text: "Representa a radicalização máxima da abstração — a eliminação de qualquer referência ao mundo visível, deixando apenas forma e vazio" },
      { id: "B", text: "É um protesto político contra o czarismo, onde o negro representa a morte do regime e o branco a pureza revolucionária" },
      { id: "C", text: "É um estudo técnico sobre como a cor preta absorve a luz, criando a ilusão de profundidade infinita" },
      { id: "D", text: "É uma homenagem às pinturas russas de ícones, reproduzindo seu quadro preto da madeira envelhecida" },
    ],
    correctAnswer: "A",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "O Suprematismo de Malevich propõe uma arte completamente livre de qualquer referência ao mundo natural ou social. Quais formas eram usadas nas obras suprematistas?",
    tip: "Se a arte não representa nada do mundo visível, ela precisa trabalhar com elementos formais muito básicos. Quais?",
    funFact: "\"Você sabia?\" — Malevich escreveu que o Suprematismo era 'a supremacia da sensação pura na arte criativa'. Para ele, um quadrado num fundo branco podia evocar a mesma profundidade espiritual que uma catedral gótica — sem precisar de figuras, histórias ou símbolos reconhecíveis.",
    points: 1,
    options: [
      { id: "A", text: "Figuras humanas estilizadas ao máximo, reduzidas a silhuetas geométricas" },
      { id: "B", text: "Formas geométricas puras (quadrados, círculos, cruzes, retângulos) sobre fundos monocromáticos" },
      { id: "C", text: "Padrões decorativos baseados na geometria da arte islâmica e dos tapetes caucasianos" },
      { id: "D", text: "Formas orgânicas inspiradas em cristais e estruturas minerais observadas ao microscópio" },
    ],
    correctAnswer: "B",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "No Cubismo Sintético (a partir de 1912), Braque e Picasso introduziram uma novidade na pintura que mudou a história da arte: a colagem. Como o Cubismo Sintético diferia visualmente do Analítico?",
    tip: "O Sintético era mais 'legível' que o Analítico — as formas voltaram a ser mais reconhecíveis. Como isso se manifestava?",
    funFact: "\"Você sabia?\" — O Cubismo Sintético levou à Pop Art décadas depois: ao incluir fragmentos de jornal, embalagens e objetos do consumo cotidiano, Braque e Picasso anteciparam a ideia de que a cultura de massa podia ser material artístico. Warhol e Lichtenstein nada fariam sem esse precedente.",
    points: 1,
    options: [
      { id: "A", text: "O Sintético reduzia ainda mais as cores até trabalhar exclusivamente com preto e branco" },
      { id: "B", text: "O Sintético voltou ao naturalismo, aplicando a fragmentação cubista sobre formas mais realistas" },
      { id: "C", text: "O Sintético usava planos maiores e mais coloridos, com colagem de materiais reais, mantendo os objetos mais reconhecíveis" },
      { id: "D", text: "O Sintético era exclusivamente escultura, enquanto o Analítico era exclusivamente pintura" },
    ],
    correctAnswer: "C",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "Guernica (1937) é uma obra-símbolo contra a violência da guerra. Onde a obra está atualmente localizada?",
    tip: "Picasso se recusou a deixar a obra ir para a Espanha enquanto Franco estivesse no poder — e após sua morte, houve uma longa negociação. Onde a obra chegou a ficar em exílio, assim como Picasso?",
    funFact: "\"Você sabia?\" — Guernica ficou no MoMA de Nova York de 1939 a 1981. Picasso deixou instrução de que ela só deveria ir para a Espanha quando a democracia fosse restaurada. Em 1981, após a morte de Franco e a consolidação da democracia espanhola, a obra finalmente chegou a Madri, em meio a grande emoção nacional.",
    points: 1,
    options: [
      { id: "A", text: "No Museu do Louvre, em Paris, onde Picasso viveu e trabalhou durante a ocupação nazista" },
      { id: "B", text: "No Museo Picasso de Barcelona, cidade natal do artista" },
      { id: "C", text: "No MoMA de Nova York, onde permanece desde 1937" },
      { id: "D", text: "No Museu Reina Sofía em Madri, Espanha — para onde foi transferida em 1981 após a redemocratização" },
    ],
    correctAnswer: "D",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "Pablo Picasso é considerado o artista mais influente do século XX. Por que ele ocupa esse lugar na história da arte?",
    tip: "Picasso não ficou num único estilo — ele atravessou e criou vários movimentos diferentes. O que isso diz sobre sua importância?",
    funFact: "\"Você sabia?\" — Picasso produziu ao longo de sua vida (morreu aos 91 anos) mais de 20.000 obras — pinturas, esculturas, cerâmicas, gravuras e desenhos. Trata-se provavelmente do maior volume de trabalho de qualquer artista individual da história, sem queda de qualidade.",
    points: 1,
    options: [
      { id: "A", text: "Por ter cofundado o Cubismo, criado Guernica e transformado a linguagem visual com constante renovação ao longo de 70 anos de carreira" },
      { id: "B", text: "Por ter sido o primeiro artista do século XX a ganhar o Prêmio Nobel de Arte" },
      { id: "C", text: "Por ter fundado o MoMA em Nova York e definido o cânone da arte moderna americana" },
      { id: "D", text: "Por ter vendido a obra mais cara da história da arte a um colecionador americano" },
    ],
    correctAnswer: "A",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "O Futurismo italiano teve ligações com o fascismo de Mussolini. Qual era a base ideológica que unia Futurismo e fascismo?",
    tip: "O Manifesto Futurista glorificava a guerra, o nacionalismo e a destruição do passado — como isso se encaixava na política de Mussolini?",
    funFact: "\"Você sabia?\" — Marinetti assinou o manifesto fundador do partido fascista italiano em 1919. Mais tarde se afastou, pois Mussolini preferiu o classicismo e a monumentalidade romana à vanguarda futurista. Ironicamente, o Futurismo — que queria destruir o passado — foi substituído por um regime que glorificava o Império Romano.",
    points: 1,
    options: [
      { id: "A", text: "Ambos eram pacifistas e buscavam a paz através da arte e da diplomacia cultural" },
      { id: "B", text: "Ambos defendiam o internacionalismo artístico e a abolição das fronteiras nacionais" },
      { id: "C", text: "A glorificação da violência, do nacionalismo, da guerra como purificação e do poder da máquina sobre o indivíduo" },
      { id: "D", text: "A defesa da arte abstrata como linguagem universal que superaria as divisões ideológicas" },
    ],
    correctAnswer: "C",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "El Lissitzky (1890-1941) foi um artista construtivista russo que influenciou profundamente o design gráfico moderno. O que o tornava único entre os construtivistas?",
    tip: "Lissitzky cruzou fronteiras — trabalhou na Alemanha e na Suíça, levando as ideias construtivistas para o design europeu.",
    funFact: "\"Você sabia?\" — El Lissitzky criou o conceito de 'Proun' — uma espécie de estação entre arquitetura e pintura, formas geométricas num espaço que parece girar. Seus Prouns influenciaram desde a Bauhaus até o design de logos corporativos do século XX.",
    points: 1,
    options: [
      { id: "A", text: "Por ser o único construtivista a trabalhar exclusivamente com escultura monumental" },
      { id: "B", text: "Por ser a ponte entre o Construtivismo russo e o design europeu (Bauhaus), influenciando tipografia, cartaz e design de exposições" },
      { id: "C", text: "Por ser o único construtivista que rejeitou a Revolução e emigrou para os Estados Unidos" },
      { id: "D", text: "Por ter criado o estilo do realismo socialista que se tornou a arte oficial soviética nos anos 1930" },
    ],
    correctAnswer: "B",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Picasso foi profundamente influenciado pela arte africana durante a criação das Demoiselles e do Cubismo. Como essa influência se manifestou?",
    tip: "Picasso viu máscaras africanas no Museu do Trocadéro em Paris — o que foi tão impactante nelas para sua arte?",
    funFact: "\"Você sabia?\" — Picasso descreveu a visita ao Museu do Trocadéro como uma 'revelação' e disse: 'As máscaras não eram esculturas comuns — eram intercessoras, medinadoras entre os vivos e os mortos. Eu entendi para que servia a pintura — era uma forma de magia.'",
    points: 1,
    options: [
      { id: "A", text: "A paleta de cores tropicais vibrantes que Picasso incorporou às obras cubistas" },
      { id: "B", text: "Os temas de caça e vida selvagem que aparecem em muitas obras do Cubismo inicial" },
      { id: "C", text: "A técnica de escultura em madeira que Picasso passou a usar como base para suas pinturas" },
      { id: "D", text: "As máscaras africanas mostravam que representar o rosto/corpo em múltiplos ângulos simultaneamente era possível e poderoso" },
    ],
    correctAnswer: "D",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "O Cubismo surgiu num momento em que a fotografia já existia. Como a existência da fotografia influenciou os artistas cubistas?",
    tip: "Se uma máquina pode capturar a realidade visual com perfeição, o que resta para a pintura fazer? Os cubistas responderam de uma forma específica.",
    funFact: "\"Você sabia?\" — O impressionismo também foi parcialmente impulsionado pela fotografia: se a câmera registrava a realidade objetiva, os pintores buscaram capturar o que a câmera não conseguia — a sensação, a atmosfera, a luz em movimento. O Cubismo foi mais longe: buscou o que a câmera nunca poderá capturar — a percepção multifacetada e simultânea.",
    points: 1,
    options: [
      { id: "A", text: "Como a fotografia capturava a aparência externa, a pintura podia se libertar para explorar o que vai além da aparência — a visão intelectual e múltipla do objeto" },
      { id: "B", text: "Os cubistas simplesmente copiavam fotografias com técnica geométrica para criar efeito estilístico" },
      { id: "C", text: "Os cubistas rejeitavam a fotografia por ser tecnologia industrial, incompatível com a arte manual" },
      { id: "D", text: "A fotografia não teve qualquer influência sobre o Cubismo, que surgiu por razões puramente formais" },
    ],
    correctAnswer: "A",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "'Branco sobre Branco' (1918) de Malevich levou o Suprematismo ao seu limite absoluto. O que essa obra representa como posição artística?",
    tip: "Após o Quadrado Negro, Malevich foi ainda mais longe. O que significa pintar branco sobre branco?",
    funFact: "\"Você sabia?\" — 'Branco sobre Branco' foi respondida por um artista rivall, Alexander Rodchenko, com 'Preto sobre Preto'. A 'batalha' entre os dois representava uma disputa real sobre qual era o ponto zero da arte — Malevich via o branco como transcendência espiritual; Rodchenko via no preto a matéria, o material, o social.",
    points: 1,
    options: [
      { id: "A", text: "É uma demonstração técnica de como misturar tintas brancas de diferentes fabricantes" },
      { id: "B", text: "Representa a fusão da arte com a arquitetura — o fundo branco é a parede do museu tornada arte" },
      { id: "C", text: "Representa o ponto final da arte figurativa — a dissolução total de qualquer forma no puro vazio branco de sensação e luz" },
      { id: "D", text: "É uma crítica política à censura soviética, onde o branco representa o silêncio imposto" },
    ],
    correctAnswer: "C",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Giacomo Balla, artista futurista italiano, criou 'Dinamismo de um Cão em Coleira' (1912). Como essa obra representa o movimento?",
    tip: "É literalmente um cão sendo passeado — como Balla conseguiu mostrar dinamismo numa pintura?",
    funFact: "\"Você sabia?\" — A obra de Balla foi inspirada diretamente pela cronofotografia — séries de fotografias que capturavam as fases de um movimento numa única imagem. Étienne-Jules Marey e Eadweard Muybridge criaram essas imagens nos anos 1880; os futuristas foram os primeiros a transferir essa ideia para a pintura.",
    points: 1,
    options: [
      { id: "A", text: "Pintando o cão com linhas muito retas e angulosas que sugerem rigidez mecânica" },
      { id: "B", text: "Multiplicando as posições das patas, do focinho e da coleira para mostrar as fases do movimento simultaneamente" },
      { id: "C", text: "Usando cores complementares que vibram quando justapostas, criando sensação de vibração" },
      { id: "D", text: "Deixando a tela inacabada, com traços incompletos que sugerem rapidez e falta de tempo" },
    ],
    correctAnswer: "B",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Qual foi a principal diferença entre Construtivismo e Suprematismo na arte russa da vanguarda?",
    tip: "Ambos eram movimentos abstratos russos pós-revolução, mas com visões muito diferentes sobre o papel social da arte.",
    funFact: "\"Você sabia?\" — O confronto entre Malevich (Suprematismo) e Rodchenko (Construtivismo) no início dos anos 1920 era, no fundo, um debate filosófico: arte é espiritual e transcendente (Malevich) ou arte é ferramenta social e política (Rodchenko)? É um debate que a arte ainda carrega consigo hoje.",
    points: 1,
    options: [
      { id: "A", text: "O Construtivismo era figurativo; o Suprematismo era geométrico" },
      { id: "B", text: "O Construtivismo era russo; o Suprematismo era uma corrente alemã importada para a Rússia" },
      { id: "C", text: "O Construtivismo usava somente materiais industriais; o Suprematismo usava somente aquarela" },
      { id: "D", text: "O Construtivismo era funcional — arte a serviço da sociedade; o Suprematismo era espiritual — arte como sensação pura transcendente" },
    ],
    correctAnswer: "D",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "'Guernica' de Picasso usa uma paleta de cores muito específica — apenas preto, branco e cinza. Qual foi a intenção artística dessa escolha?",
    tip: "Esse bombardeio aconteceu em 1937 — havia fotojornalismo e imprensa. Como Picasso usou a limitação de cores de forma simbólica?",
    funFact: "\"Você sabia?\" — Picasso fotografou o processo de criação de Guernica em 45 estágios — um documento extraordinário que permite ver a evolução da obra. Na primeira versão, havia cor — um punho com flores. Ao longo do processo, as cores foram eliminadas e a composição tornou-se mais caótica e brutal.",
    points: 1,
    options: [
      { id: "A", text: "As cores em preto, branco e cinza evocam o fotojornalismo e a imprensa que transmitiu o bombardeio, dando à obra um caráter documental e de notícia" },
      { id: "B", text: "Era uma limitação técnica — a tinta do ateliê de Picasso havia acabado no dia do início da pintura" },
      { id: "C", text: "As cores foram escolhidas por razões estéticas, seguindo a tradição cubista de paleta reduzida" },
      { id: "D", text: "Era uma exigência do governo espanhol republicano que encomendou a obra para a Exposição de Paris" },
    ],
    correctAnswer: "A",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Vladimir Tatlin foi um arquiteto e artista construtivista que projetou a 'Torre de Tatlin' (1919-1920). O que era esse projeto monumental?",
    tip: "Era um projeto para um edifício como nenhum outro — que combinava arquitetura, escultura e tecnologia de comunicação.",
    funFact: "\"Você sabia?\" — A Torre de Tatlin nunca foi construída — seria impossível tecnicamente na Rússia de 1920 e o projeto foi abandonado. Mas o modelo em maquete tornou-se um dos símbolos mais poderosos da utopia construtivista — a ideia de que arte, arquitetura e revolução podiam se fundir numa única estrutura.",
    points: 1,
    options: [
      { id: "A", text: "Um museu de arte proletária em Moscou com fachada em aço e vidro sem ornamentação" },
      { id: "B", text: "Um palácio do povo em São Petersburgo para substituir o Palácio de Inverno do czar" },
      { id: "C", text: "Um monumento à Terceira Internacional — estrutura espiral em ferro rotativa que seria mais alta que a Torre Eiffel" },
      { id: "D", text: "Uma escola de arte pública em estilo construtivista para formar artistas da classe trabalhadora" },
    ],
    correctAnswer: "C",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "A influência do Cubismo se estendeu muito além da pintura. Em quais outras áreas artísticas o Cubismo deixou sua marca?",
    tip: "A ideia de fragmentar e recompor, ver de múltiplos ângulos e usar materiais cotidianos se espalhou para além da pintura e escultura.",
    funFact: "\"Você sabia?\" — A arquiteta Le Corbusier (contemporâneo e amigo de Picasso e Léger) usou princípios cubistas no design de interiores e fachadas — a ideia de que um espaço pode ser percebido de múltiplos ângulos, sem ponto de vista dominante único. A Villa Savoye (1931) é um exemplo direto disso.",
    points: 1,
    options: [
      { id: "A", text: "Exclusivamente na pintura e no desenho, sem influência em outras artes" },
      { id: "B", text: "Na escultura, arquitetura, design, literatura (Gertrude Stein, Apollinaire) e cinema de vanguarda" },
      { id: "C", text: "Apenas na literatura, com escritores que fragmentaram a narrativa em capítulos simultâneos" },
      { id: "D", text: "Principalmente na música, onde compositores como Stravinsky fragmentaram a melodia em células atômicas" },
    ],
    correctAnswer: "B",
  },
];
