export const questoesGeografia1EmB4Av2 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "O desmatamento é um dos maiores problemas ambientais do Brasil. Quais são suas principais causas no país?",
    tip: "Pense nos diferentes agentes que destroem a floresta: grandes empresas, pequenos agricultores, madeireiras. Quais motivações os movem?",
    funFact: "\"Você sabia?\" — Cerca de 80% do desmatamento da Amazônia está associado à expansão da pecuária bovina. Um único hambúrguer pode ter custado ao planeta uma área de floresta do tamanho de um campo de futebol!",
    points: 1,
    options: [
      { id: "A", text: "As principais causas do desmatamento no Brasil são a expansão da agropecuária (pastagens e lavouras), a extração ilegal de madeira, o garimpo, a construção de estradas e a especulação imobiliária fundiária." },
      { id: "B", text: "O desmatamento no Brasil é causado exclusivamente por grandes multinacionais, sem envolvimento de produtores nacionais." },
      { id: "C", text: "A principal causa do desmatamento é a expansão urbana das metrópoles em direção às florestas." },
      { id: "D", text: "O desmatamento é causado principalmente por catástrofes naturais, como raios e vendavais." },
    ],
    correctAnswer: "A",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "As queimadas no Brasil causam graves impactos ambientais. Quais biomas são os mais afetados?",
    tip: "As queimadas ocorrem principalmente no período seco. Quais biomas têm uma estação seca prolongada e são alvo de queimadas para abertura de pasto?",
    funFact: "\"Você sabia?\" — Em agosto e setembro de 2019, o Brasil registrou mais de 80.000 focos de incêndio, a maioria concentrada na Amazônia e no Cerrado. A fumaça formou uma nuvem que chegou a São Paulo e escureceu o céu ao meio-dia.",
    points: 1,
    options: [
      { id: "A", text: "Apenas o Pampa gaúcho é afetado pelas queimadas, pois suas gramíneas secas são altamente inflamáveis no inverno." },
      { id: "B", text: "As queimadas afetam apenas a Mata Atlântica, por estar próxima das áreas urbanas mais populosas do Brasil." },
      { id: "C", text: "O Pantanal é o único bioma imune a queimadas, por estar permanentemente alagado." },
      { id: "D", text: "A Amazônia e o Cerrado são os biomas mais afetados pelas queimadas no Brasil, frequentemente usadas ilegalmente para limpar áreas desmatadas para pastagem e lavoura, liberando enorme quantidade de CO2 e particulados na atmosfera." },
    ],
    correctAnswer: "D",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "A desertificação é um processo diferente do avanço natural de desertos. Como ela se forma e onde é mais crítica no Brasil?",
    tip: "Desertificação é causada pela combinação de fatores climáticos e ações humanas. Onde no Brasil o clima semiárido combinado com uso inadequado do solo cria esse problema?",
    funFact: "\"Você sabia?\" — O Brasil possui 9 núcleos de desertificação identificados, sendo o mais grave o de Gilbués (PI/MA/BA), onde o solo vermelho exposto lembra imagens da Lua. Esses núcleos estão avançando em velocidade preocupante.",
    points: 1,
    options: [
      { id: "A", text: "A desertificação ocorre apenas em países africanos, sendo o Brasil imune a esse processo graças à sua alta pluviosidade média." },
      { id: "B", text: "A desertificação no Brasil é causada exclusivamente pela redução das chuvas provocada pelo aquecimento global." },
      { id: "C", text: "A desertificação é a degradação das terras em regiões áridas, semiáridas e subúmidas secas pela combinação de clima vulnerável e ações humanas inadequadas (superpastoreio, desmatamento, agricultura sem conservação do solo), sendo mais crítica no Nordeste semiárido." },
      { id: "D", text: "A desertificação afeta apenas as regiões costeiras, onde a erosão marinha destrói o solo das praias." },
    ],
    correctAnswer: "C",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "A poluição hídrica afeta rios, lagos e lençóis freáticos. Quais são suas principais fontes no Brasil?",
    tip: "Pense nos diferentes tipos de fontes de poluição da água: residenciais, industriais, agrícolas e de mineração.",
    funFact: "\"Você sabia?\" — Segundo o IBGE, apenas 54% dos brasileiros têm acesso à coleta de esgoto. Isso significa que o esgoto de quase metade da população vai para rios, lagos e mar sem tratamento — contaminando as fontes de água potável.",
    points: 1,
    options: [
      { id: "A", text: "A poluição hídrica no Brasil é causada exclusivamente pelas indústrias químicas instaladas às margens dos rios." },
      { id: "B", text: "As principais fontes são o lançamento de esgoto doméstico sem tratamento, os efluentes industriais, o uso de agrotóxicos e fertilizantes na agricultura, e o descarte irregular de lixo, que contaminam rios, lagos e aquíferos." },
      { id: "C", text: "A poluição hídrica ocorre apenas em rios que atravessam zonas industriais, sendo os rios rurais naturalmente limpos." },
      { id: "D", text: "O maior poluidor das águas no Brasil é a chuva ácida, que contamina rios e reservatórios nas regiões metropolitanas." },
    ],
    correctAnswer: "B",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "A poluição do ar é um grave problema ambiental, especialmente nas grandes cidades. Quais são suas principais fontes?",
    tip: "Pense no que libera gases e partículas na atmosfera das cidades e das áreas industriais brasileiras.",
    funFact: "\"Você sabia?\" — São Paulo tem uma das maiores frotas de veículos do mundo. Em 2022, a região metropolitana registrou mais de 21 milhões de veículos para uma população de 21 milhões de habitantes — quase um carro por pessoa!",
    points: 1,
    options: [
      { id: "A", text: "As principais fontes de poluição do ar são a queima de combustíveis fósseis por veículos e indústrias, as queimadas em zonas rurais, a emissão de gases por aterros sanitários e, nas cidades, o material particulado levantado pela falta de pavimentação." },
      { id: "B", text: "A poluição do ar é causada exclusivamente pelas emissões industriais, sendo os veículos responsáveis por menos de 1% da poluição atmosférica." },
      { id: "C", text: "A única fonte relevante de poluição do ar nas cidades brasileiras é a queima de lixo em terrenos baldios." },
      { id: "D", text: "A poluição do ar nas cidades brasileiras é causada principalmente pela evaporação de pesticidas usados na agricultura do interior." },
    ],
    correctAnswer: "A",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "A Conferência de Estocolmo (1972) foi um marco na história do ambientalismo mundial. O que ela representou?",
    tip: "Estocolmo 1972 foi a primeira grande conferência ambiental global. Qual foi sua importância histórica para a criação de uma consciência ambiental planetária?",
    funFact: "\"Você sabia?\" — Na Conferência de Estocolmo, a delegação brasileira, a pedido da ditadura militar, defendeu a tese do 'desenvolvimento a qualquer custo', convidando indústrias poluidoras a se instalar no Brasil. A posição ficou conhecida como 'venham poluir nosso país'.",
    points: 1,
    options: [
      { id: "A", text: "Estocolmo 1972 resultou apenas em um tratado sobre poluição marítima, sem tratar de questões terrestres ou climáticas." },
      { id: "B", text: "Foi a conferência que criou o Protocolo de Kyoto e as metas de redução de CO2 para os países industrializados." },
      { id: "C", text: "Foi a conferência que criou o Acordo de Paris e o conceito de desenvolvimento sustentável." },
      { id: "D", text: "Foi a primeira grande conferência ambiental da ONU, realizada em Estocolmo (Suécia), que colocou o meio ambiente na agenda política global, criou o PNUMA (Programa das Nações Unidas para o Meio Ambiente) e lançou a base para as discussões ambientais futuras." },
    ],
    correctAnswer: "D",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "A Conferência das Nações Unidas sobre Meio Ambiente e Desenvolvimento (Rio-92 / ECO-92) foi realizada no Brasil. Quais foram seus principais resultados?",
    tip: "A Rio-92 foi muito mais abrangente que Estocolmo. Pense nos documentos e convenções que ela produziu.",
    funFact: "\"Você sabia?\" — A Rio-92 reuniu 172 países e 108 chefes de Estado — a maior conferência já realizada até então. O Brasil escolheu o Rio de Janeiro como sede para mostrar ao mundo seu comprometimento com a agenda ambiental.",
    points: 1,
    options: [
      { id: "A", text: "A Rio-92 produziu apenas uma declaração de intenções sem nenhum documento vinculante para os países participantes." },
      { id: "B", text: "A Rio-92 foi um fracasso diplomático, pois os países não chegaram a nenhum acordo sobre questões ambientais." },
      { id: "C", text: "A Rio-92 produziu documentos e convenções fundamentais: a Agenda 21 (plano de ação para o desenvolvimento sustentável), a Convenção sobre Biodiversidade, a Convenção do Clima (base para o Protocolo de Kyoto e o Acordo de Paris) e a Declaração do Rio sobre Meio Ambiente e Desenvolvimento." },
      { id: "D", text: "A Rio-92 resultou apenas na criação do Protocolo de Kyoto, que foi assinado nessa conferência." },
    ],
    correctAnswer: "C",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "O Protocolo de Kyoto (1997) foi um importante acordo climático. Qual foi sua limitação mais criticada?",
    tip: "Kyoto estabeleceu metas apenas para os países desenvolvidos (Anexo I). O que aconteceu com as grandes economias emergentes?",
    funFact: "\"Você sabia?\" — O Protocolo de Kyoto tinha uma brecha: os países em desenvolvimento, incluindo China, Brasil e Índia — que viriam a ser grandes emissores — não tinham metas de redução de emissões. Isso foi uma de suas maiores críticas.",
    points: 1,
    options: [
      { id: "A", text: "A limitação foi que o Protocolo proibia o uso de energias renováveis, impedindo a transição energética." },
      { id: "B", text: "A principal limitação foi que estabelecia metas apenas para os países industrializados (Anexo I), excluindo as grandes economias emergentes como China, Brasil e Índia, além de os EUA nunca o terem ratificado e o Canadá ter se retirado em 2011." },
      { id: "C", text: "O Protocolo foi ineficaz por não incluir metas para o setor agrícola, responsável pela maioria das emissões globais." },
      { id: "D", text: "A limitação principal foi que o Protocolo se restringia apenas às emissões de metano, ignorando o CO2." },
    ],
    correctAnswer: "B",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "O Acordo de Paris (2015) representou um avanço em relação ao Protocolo de Kyoto. Qual é sua principal inovação?",
    tip: "Diferentemente de Kyoto, o Acordo de Paris inclui todos os países, não apenas os desenvolvidos. Como funciona o mecanismo de comprometimento?",
    funFact: "\"Você sabia?\" — O Acordo de Paris foi negociado em tempo recorde na COP21, em dezembro de 2015. Mais de 195 países assinaram o acordo em 2016 — o maior número de países a assinar um tratado internacional em um único dia.",
    points: 1,
    options: [
      { id: "A", text: "A principal inovação do Acordo de Paris é que inclui todos os países signatários (não apenas os desenvolvidos), com Contribuições Nacionalmente Determinadas (NDCs) voluntárias revisadas a cada 5 anos, visando limitar o aquecimento global a 1,5°C acima dos níveis pré-industriais." },
      { id: "B", text: "O Acordo de Paris inovou ao estabelecer multas bilionárias para países que não cumprirem suas metas de redução." },
      { id: "C", text: "A inovação foi criar um banco mundial do carbono com poder de executar as metas dos países signatários." },
      { id: "D", text: "O Acordo de Paris inovou ao proibir completamente o uso de combustíveis fósseis a partir de 2020." },
    ],
    correctAnswer: "A",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "As COPs (Conferências das Partes) são o principal fórum global de negociações climáticas. O que elas são?",
    tip: "COP = Conference of the Parties. Qual é a frequência dessas conferências e qual tratado as rege?",
    funFact: "\"Você sabia?\" — A COP30 de 2025 será realizada em Belém (PA), na Amazônia brasileira. É a primeira COP a ocorrer na maior floresta tropical do mundo — um poderoso símbolo político para as negociações sobre desmatamento e clima.",
    points: 1,
    options: [
      { id: "A", text: "São reuniões mensais de cientistas climáticos que publicam relatórios técnicos sobre o estado do clima." },
      { id: "B", text: "São cúpulas bienais realizadas pelo G7 para coordenar as políticas climáticas dos países mais ricos." },
      { id: "C", text: "São conferências realizadas por organizações não governamentais sem poder de decisão política." },
      { id: "D", text: "São as reuniões anuais dos países signatários da Convenção-Quadro das Nações Unidas sobre Mudança do Clima (UNFCCC), onde se negociam metas, mecanismos de financiamento e os avanços dos acordos climáticos globais." },
    ],
    correctAnswer: "D",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "O conceito de desenvolvimento sustentável foi consolidado pelo Relatório Brundtland (1987). Como ele é definido?",
    tip: "Brundtland propôs uma definição que equilibra as necessidades do presente com as do futuro. Qual é essa definição?",
    funFact: "\"Você sabia?\" — O Relatório Brundtland foi elaborado pela Comissão Mundial sobre Meio Ambiente e Desenvolvimento, presidida pela médica norueguesa Gro Harlem Brundtland. Seu título original é 'Nosso Futuro Comum'.",
    points: 1,
    options: [
      { id: "A", text: "Desenvolvimento sustentável é aquele que prioriza o crescimento econômico, considerando o meio ambiente secundário." },
      { id: "B", text: "É o desenvolvimento que elimina completamente o uso de recursos naturais, preservando o meio ambiente intacto." },
      { id: "C", text: "Desenvolvimento sustentável é 'aquele que atende às necessidades do presente sem comprometer a capacidade das gerações futuras de atenderem às suas próprias necessidades', integrando crescimento econômico, equidade social e proteção ambiental." },
      { id: "D", text: "É o desenvolvimento baseado exclusivamente em energias renováveis, sem uso de combustíveis fósseis." },
    ],
    correctAnswer: "C",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Os ODS (Objetivos de Desenvolvimento Sustentável) são a agenda global para 2030. Quantos objetivos a Agenda 2030 possui e quem a adotou?",
    tip: "Os ODS foram adotados pelas Nações Unidas em 2015, substituindo os Objetivos do Milênio. Quantas metas principais ela tem?",
    funFact: "\"Você sabia?\" — Os 17 ODS têm 169 metas e 231 indicadores. Eles cobrem tudo: desde erradicação da fome e pobreza até ação climática, igualdade de gênero e cidades sustentáveis — uma agenda ambiciosa e integrada para o planeta.",
    points: 1,
    options: [
      { id: "A", text: "A Agenda 2030 possui 8 objetivos, adotados apenas pelos países desenvolvidos membros da OCDE." },
      { id: "B", text: "A Agenda 2030 possui 17 Objetivos de Desenvolvimento Sustentável (ODS), adotados por todos os 193 estados-membros da ONU em 2015, cobrindo dimensões econômicas, sociais e ambientais do desenvolvimento." },
      { id: "C", text: "A Agenda 2030 possui 10 objetivos, focados exclusivamente nas questões climáticas e de biodiversidade." },
      { id: "D", text: "A Agenda 2030 possui 25 objetivos, sendo responsabilidade apenas dos países em desenvolvimento cumpri-los." },
    ],
    correctAnswer: "B",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "A Agenda 21 foi um dos principais documentos produzidos na Rio-92. O que ela propõe?",
    tip: "Agenda 21 foi um dos documentos mais ambiciosos da Rio-92. O que o número '21' no nome representa?",
    funFact: "\"Você sabia?\" — O Brasil elaborou uma Agenda 21 Brasileira e muitos municípios criaram suas Agendas 21 locais, com participação da sociedade civil. Curitiba e São Paulo foram cidades pioneiras na implementação de Agendas 21 locais.",
    points: 1,
    options: [
      { id: "A", text: "A Agenda 21 é um plano de ação global para o desenvolvimento sustentável no século XXI, abrangendo temas como proteção ambiental, erradicação da pobreza, consumo consciente e cooperação internacional — com versões globais, nacionais e locais." },
      { id: "B", text: "A Agenda 21 é um tratado que proíbe 21 substâncias químicas poluidoras específicas identificadas como as mais nocivas ao ambiente." },
      { id: "C", text: "A Agenda 21 foi um acordo assinado por 21 países que se comprometeram a zerar suas emissões de carbono até 2021." },
      { id: "D", text: "A Agenda 21 é um calendário de 21 ações imediatas que os países devem implementar para reduzir o desmatamento." },
    ],
    correctAnswer: "A",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "A pegada ecológica é um indicador ambiental amplamente utilizado. O que ela mede?",
    tip: "Pegada ecológica mede o impacto do consumo humano nos recursos naturais. Como ela é expressa?",
    funFact: "\"Você sabia?\" — Se todos os habitantes da Terra consumissem como os americanos, seriam necessários 5 planetas Terra para suprir a demanda. Se consumissem como os brasileiros, seria necessário 1,8 planeta. A humanidade já usa 1,7 Terras por ano!",
    points: 1,
    options: [
      { id: "A", text: "A pegada ecológica é o rastro visual deixado pelo desmatamento, visível em imagens de satélite." },
      { id: "B", text: "É a quantidade de CO2 emitida por uma pessoa, empresa ou país em um determinado período." },
      { id: "C", text: "É o número de espécies extintas em decorrência das atividades de uma determinada população." },
      { id: "D", text: "É o indicador que mede a área de terra e água biologicamente produtiva necessária para produzir os recursos consumidos e absorver os resíduos gerados por uma pessoa, cidade ou nação — comparada com a capacidade regenerativa do planeta (biocapacidade)." },
    ],
    correctAnswer: "D",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "A economia circular é um modelo alternativo à economia linear. Qual é a diferença entre os dois modelos?",
    tip: "Linear = extrair → produzir → descartar. Circular = o resíduo de uma etapa alimenta outra. Qual é o objetivo central da economia circular?",
    funFact: "\"Você sabia?\" — A Ellen MacArthur Foundation estima que a transição para uma economia circular global poderia gerar US$ 4,5 trilhões em valor econômico até 2030, além de reduzir drasticamente os resíduos e a extração de recursos.",
    points: 1,
    options: [
      { id: "A", text: "A economia circular é igual à linear, diferenciando-se apenas pela preferência por matérias-primas renováveis." },
      { id: "B", text: "A economia circular elimina completamente o consumo, substituindo-o por um sistema de troca e barterecimento." },
      { id: "C", text: "A economia circular é um modelo que busca eliminar o conceito de 'resíduo', mantendo materiais e produtos em uso pelo máximo de tempo possível por meio de reuso, reparo, remanufatura e reciclagem — em contraste com o modelo linear 'extrair-produzir-descartar'." },
      { id: "D", text: "A economia circular é um modelo exclusivamente aplicável a países desenvolvidos, pois requer alta tecnologia e infraestrutura avançada." },
    ],
    correctAnswer: "C",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "Os recursos hídricos são distribuídos de forma desigual no planeta. Qual é a situação global?",
    tip: "Água doce representa uma pequena fração da água total do planeta, e sua distribuição é muito irregular. Como isso se distribui entre as nações?",
    funFact: "\"Você sabia?\" — O Brasil possui 12% de toda a água doce superficial do mundo, mas enfrenta escassez em algumas regiões (semiárido nordestino, áreas metropolitanas). Ter água não significa tê-la onde e quando é necessário!",
    points: 1,
    options: [
      { id: "A", text: "Os recursos hídricos são distribuídos de forma uniforme no planeta, sem diferenças regionais significativas." },
      { id: "B", text: "A água doce é distribuída de forma extremamente desigual: apenas 2,5% da água da Terra é doce, e a maior parte está congelada nos polos. Os países tropicais têm excesso, enquanto as regiões áridas e países densamente populosos enfrentam grave escassez." },
      { id: "C", text: "A distribuição da água é equitativa entre os continentes, sendo a escassez um problema exclusivo da África subsaariana." },
      { id: "D", text: "Todos os países têm acesso suficiente a água doce, sendo a crise hídrica um problema de gestão, não de disponibilidade." },
    ],
    correctAnswer: "B",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "Os aquíferos são reservatórios subterrâneos de água doce de grande importância estratégica. Por que eles são tão relevantes?",
    tip: "Os aquíferos fornecem água a grande parte da humanidade. Mas qual é o risco associado ao seu uso excessivo?",
    funFact: "\"Você sabia?\" — O Aquífero Guarani, que se estende pelo Brasil, Argentina, Paraguai e Uruguai, tem reservas estimadas em 37.000 km³ de água. Se usada sem reposição, poderia abastecer toda a população atual do planeta por 2.000 anos!",
    points: 1,
    options: [
      { id: "A", text: "Os aquíferos são relevantes por serem a principal fonte de água salgada do planeta, usada na dessalinização." },
      { id: "B", text: "São importantes apenas para a navegação fluvial, servindo como reservatório de nível para os rios superficiais." },
      { id: "C", text: "Os aquíferos são relevantes apenas em regiões áridas, sendo irrelevantes nas áreas tropicais úmidas." },
      { id: "D", text: "Os aquíferos são reservatórios subterrâneos que fornecem cerca de 30% de toda a água doce usada pela humanidade, sendo fundamentais para o abastecimento humano, a agricultura irrigada e a manutenção do fluxo dos rios nos períodos secos — mas que, se explorados além da taxa de recarga, podem ser esgotados irreversivelmente." },
    ],
    correctAnswer: "A",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "A escassez de água é uma das maiores ameaças globais do século XXI. Quais fatores a intensificam?",
    tip: "A escassez de água não é só falta de chuva. Pense nos fatores humanos e ambientais que reduzem a disponibilidade de água de qualidade.",
    funFact: "\"Você sabia?\" — A ONU projeta que até 2050, mais de 5 bilhões de pessoas poderão sofrer com escassez de água. Guerras por água já ocorrem no Oriente Médio e na África — alguns geopolíticos preveem que 'as guerras do século XXI serão pela água'.",
    points: 1,
    options: [
      { id: "A", text: "A escassez de água é causada exclusivamente por secas naturais e não tem relação com ações humanas." },
      { id: "B", text: "A escassez afeta apenas países em desenvolvimento sem infraestrutura adequada de captação e distribuição." },
      { id: "C", text: "A escassez de água é um problema apenas de países desérticos, sem relevância para países tropicais como o Brasil." },
      { id: "D", text: "A escassez de água é intensificada pela combinação de crescimento populacional, urbanização acelerada, contaminação por poluição, mudanças climáticas que alteram os padrões de precipitação, desperdício no consumo e irrigação agrícola ineficiente." },
    ],
    correctAnswer: "D",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "A falta de saneamento básico está diretamente ligada à qualidade da água e à saúde pública. Qual é o impacto dessa ausência?",
    tip: "Saneamento básico inclui água potável, esgoto e coleta de lixo. O que acontece quando o esgoto é lançado diretamente nos rios?",
    funFact: "\"Você sabia?\" — Doenças diarreicas causadas por água contaminada matam mais de 525.000 crianças com menos de 5 anos por ano no mundo. Investir em saneamento básico é uma das intervenções de saúde pública com melhor custo-benefício.",
    points: 1,
    options: [
      { id: "A", text: "A falta de saneamento básico causa apenas problemas estéticos de mau cheiro nos rios, sem impacto na saúde humana." },
      { id: "B", text: "A ausência de saneamento afeta apenas as regiões rurais, sendo as cidades totalmente cobertas pelo serviço." },
      { id: "C", text: "A falta de saneamento básico (especialmente coleta e tratamento de esgoto e acesso a água potável) causa surtos de doenças de veiculação hídrica como cólera, febre tifoide, hepatite A, leptospirose e diarreias, afetando principalmente crianças e populações de baixa renda." },
      { id: "D", text: "O saneamento básico é irrelevante para a saúde pública, pois as doenças são causadas por fatores genéticos e não ambientais." },
    ],
    correctAnswer: "C",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "A eutrofização é um problema ambiental que afeta corpos d'água. O que ela é e como ocorre?",
    tip: "Eutrof = bem alimentado (em grego). O excesso de nutrientes na água causa um crescimento excessivo de quê?",
    funFact: "\"Você sabia?\" — A Represa de Guarapiranga, que abastece São Paulo, enfrenta eutrofização crônica. O crescimento de cianobactérias (algas tóxicas) liberou toxinas que chegaram à rede de abastecimento em 2020, colocando 3 milhões de pessoas em risco.",
    points: 1,
    options: [
      { id: "A", text: "A eutrofização é o processo de resfriamento excessivo da água de rios e lagos em regiões frias." },
      { id: "B", text: "A eutrofização é o enriquecimento excessivo de corpos d'água com nutrientes (principalmente nitrogênio e fósforo, provenientes de esgoto e fertilizantes), que provoca crescimento explosivo de algas, redução do oxigênio dissolvido, morte de peixes e colapso do ecossistema aquático." },
      { id: "C", text: "A eutrofização é a contaminação da água por metais pesados como mercúrio e chumbo provenientes da mineração." },
      { id: "D", text: "A eutrofização é o processo natural de envelhecimento dos lagos, sem relação com atividades humanas." },
    ],
    correctAnswer: "B",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "A contaminação por metais pesados é uma forma grave de poluição ambiental. Quais atividades humanas são as principais fontes?",
    tip: "Mercúrio, chumbo, arsênio e cádmio são exemplos de metais pesados. Quais atividades os lançam no meio ambiente?",
    funFact: "\"Você sabia?\" — O mercúrio usado no garimpo na Amazônia contamina os rios e bioconcentra na cadeia alimentar. Peixes como o tambaqui têm concentrações 10.000 vezes maiores que a água do rio — e os peixes chegam ao prato dos ribeirinhos.",
    points: 1,
    options: [
      { id: "A", text: "Os metais pesados no ambiente têm apenas origem natural (vulcões e erosão de rochas), sem contribuição das atividades humanas." },
      { id: "B", text: "A contaminação por metais pesados ocorre exclusivamente em países industrializados, não sendo um problema no Brasil." },
      { id: "C", text: "Os metais pesados são liberados principalmente por vulcões submarinos, sendo as atividades humanas responsáveis por menos de 5% da contaminação total." },
      { id: "D", text: "As principais fontes de contaminação por metais pesados são a mineração e o garimpo (mercúrio), a metalurgia e fundição, os efluentes industriais, os pesticidas e fertilizantes e a queima de lixo — com graves efeitos à saúde humana e aos ecossistemas." },
    ],
    correctAnswer: "D",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "O tratamento de água e esgoto é fundamental para a saúde pública. Quais são as etapas básicas do tratamento de água para abastecimento?",
    tip: "Da água bruta até a torneira, a água passa por várias etapas de purificação. Você consegue listar as principais?",
    funFact: "\"Você sabia?\" — A cloração da água, introduzida no início do século XX, é considerada uma das maiores conquistas da saúde pública da história. O cloro elimina bactérias e vírus na água, prevenindo epidemias como cólera e febre tifoide.",
    points: 1,
    options: [
      { id: "A", text: "O tratamento de água envolve as etapas de coagulação e floculação (agregação de partículas), sedimentação (decantação), filtração (remoção de partículas finas), desinfecção (cloração, ozônio ou UV) e fluoretação para a saúde dentária." },
      { id: "B", text: "O tratamento de água consiste apenas na adição de cloro, que elimina todos os contaminantes possíveis." },
      { id: "C", text: "O tratamento de água é necessário apenas para a água de poços artesianos, sendo a água de rios naturalmente potável." },
      { id: "D", text: "O único tratamento necessário é a fervura, que elimina todos os contaminantes físicos, químicos e biológicos." },
    ],
    correctAnswer: "A",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "A chuva ácida é um problema ambiental associado à poluição do ar. Como ela se forma?",
    tip: "Chuva ácida = chuva + ácidos formados na atmosfera. Quais gases se combinam com a água da chuva para formar ácidos?",
    funFact: "\"Você sabia?\" — A chuva ácida que cai na Escandinávia é frequentemente gerada pela poluição industrial da Alemanha e do Reino Unido, carregada pelos ventos. Isso foi um dos primeiros exemplos de poluição ambiental 'sem fronteiras'.",
    points: 1,
    options: [
      { id: "A", text: "A chuva ácida é formada quando as nuvens absorvem ácidos naturais das plantas, tornando a precipitação levemente ácida." },
      { id: "B", text: "É formada pela reação do vapor d'água com o cloro liberado pelas indústrias químicas." },
      { id: "C", text: "A chuva ácida é formada quando os óxidos de enxofre (SO2) e de nitrogênio (NOx), emitidos pela queima de combustíveis fósseis e pela metalurgia, reagem com o vapor d'água na atmosfera, formando ácido sulfúrico e ácido nítrico, que acidificam rios, lagos, solos e corroem monumentos e edificações." },
      { id: "D", text: "É causada exclusivamente pelo CO2, que se dissolve na água e forma ácido carbônico nas nuvens." },
    ],
    correctAnswer: "C",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "A destruição da camada de ozônio foi um problema ambiental grave do século XX. O que a causou?",
    tip: "A camada de ozônio protege a Terra da radiação UV. Qual substância química, amplamente usada em refrigeradores e aerossóis, foi identificada como a culpada?",
    funFact: "\"Você sabia?\" — O Protocolo de Montreal (1987), que baniu os CFCs, é considerado o acordo ambiental mais bem-sucedido da história. Cientistas estimam que a camada de ozônio deve se recuperar completamente até 2065 — uma vitória da diplomacia ambiental!",
    points: 1,
    options: [
      { id: "A", text: "A destruição da camada de ozônio é causada pelo CO2 emitido pelos automóveis nas grandes cidades." },
      { id: "B", text: "Os clorofluorcarbonos (CFCs), usados em refrigeradores, ar-condicionado e aerossóis, são os principais responsáveis pela destruição da camada de ozônio; seus átomos de cloro reagem com o ozônio (O3), destruindo-o cataliticamente." },
      { id: "C", text: "A destruição do ozônio é um processo natural do ciclo de vida da estratosfera, sem relação com atividades humanas." },
      { id: "D", text: "A principal causa é o metano (CH4) liberado pela pecuária bovina e pelos aterros sanitários." },
    ],
    correctAnswer: "B",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "As fontes de energia renovável são alternativas sustentáveis aos combustíveis fósseis. Quais são os exemplos mais importantes?",
    tip: "Energia renovável é aquela que se regenera naturalmente. Pense nas fontes de energia que não se esgotam com o uso.",
    funFact: "\"Você sabia?\" — O Brasil é um dos líderes mundiais em energia renovável. Em 2022, mais de 85% da energia elétrica brasileira veio de fontes renováveis: hidrelétricas (65%), eólica (12%), solar (4%) e biomassa (9%).",
    points: 1,
    options: [
      { id: "A", text: "As fontes renováveis incluem apenas a energia hidrelétrica e a nuclear, pois são as únicas capazes de suprir grandes demandas." },
      { id: "B", text: "As principais fontes renováveis são o petróleo de produção sustentável e o gás natural de poços de baixo impacto." },
      { id: "C", text: "A única fonte renovável viável é a energia solar, pois as demais fontes alternativas têm eficiência muito baixa." },
      { id: "D", text: "As principais fontes de energia renovável são a solar (fotovoltaica e térmica), a eólica (ventos), a hidráulica (rios), a biomassa (matéria orgânica), a geotérmica (calor interno da Terra) e a maremotriz (marés) — que não emitem CO2 em sua operação." },
    ],
    correctAnswer: "D",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "A Política Nacional de Resíduos Sólidos (Lei 12.305/2010) introduziu no Brasil um conceito hierárquico de gestão de resíduos. Qual é essa hierarquia?",
    tip: "A hierarquia dos resíduos prioriza a prevenção antes de qualquer tratamento. Qual é a ordem de preferência do mais sustentável ao menos sustentável?",
    funFact: "\"Você sabia?\" — O Brasil produzia, em 2022, cerca de 81 milhões de toneladas de resíduos sólidos por ano. Desses, apenas 4% era reciclado. O resto ia para aterros sanitários, lixões ou tinha destino inadequado.",
    points: 1,
    options: [
      { id: "A", text: "A hierarquia da Política Nacional de Resíduos Sólidos prioriza, nessa ordem: não geração → redução → reutilização → reciclagem → tratamento dos resíduos → disposição final ambientalmente adequada — valorizando a prevenção antes do tratamento." },
      { id: "B", text: "A hierarquia prioriza a reciclagem como primeira opção, seguida da reutilização, da redução e, por último, da não geração." },
      { id: "C", text: "A lei estabelece que todos os resíduos devem ser incinerados, pois a queima gera energia e elimina os resíduos." },
      { id: "D", text: "A hierarquia determina que lixões são a forma preferencial de disposição, pois são mais baratos que aterros sanitários." },
    ],
    correctAnswer: "A",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "A poluição plástica nos oceanos é uma crise ambiental global. Quais são os principais impactos?",
    tip: "O plástico não se decompõe facilmente. O que acontece quando ele chega ao oceano e se fragmenta em partículas cada vez menores?",
    funFact: "\"Você sabia?\" — Existe uma 'sopa de plástico' no Pacífico Norte chamada de 'Grande Ilha de Lixo do Pacífico', com tamanho estimado de 1,6 milhão de km² — maior que a França, Espanha e Portugal juntos!",
    points: 1,
    options: [
      { id: "A", text: "O plástico nos oceanos não causa danos biológicos, apenas estéticos — a fauna marinha não ingere plástico." },
      { id: "B", text: "O impacto do plástico é apenas econômico, afetando o turismo costeiro, sem consequências para os ecossistemas marinhos." },
      { id: "C", text: "A poluição plástica oceânica causa aprisionamento e asfixia de animais marinhos (tartarugas, aves, baleias), ingestão de microplásticos por organismos que entram na cadeia alimentar (chegando ao ser humano), degradação de recifes de coral e contaminação química do oceano." },
      { id: "D", text: "O plástico nos oceanos é benéfico, pois serve como substrato para a fixação de algas e espécies bentônicas." },
    ],
    correctAnswer: "C",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "A bioinvasão (invasão de espécies exóticas) é um sério problema ambiental. Como ela ocorre e quais são seus impactos?",
    tip: "Espécies exóticas invasoras são aquelas introduzidas fora de sua área de origem. Por que elas se tornam problemas nos novos ambientes?",
    funFact: "\"Você sabia?\" — O mexilhão-dourado, originário da bacia do Prata, invadiu todas as bacias hidrográficas do Brasil e entope as turbinas de hidrelétricas, causando prejuízos de centenas de milhões de reais por ano ao setor elétrico.",
    points: 1,
    options: [
      { id: "A", text: "A bioinvasão é benéfica ao ambiente, pois aumenta a biodiversidade local ao acrescentar novas espécies." },
      { id: "B", text: "A bioinvasão ocorre quando espécies introduzidas acidentalmente ou intencionalmente em novos ambientes, sem inimigos naturais, se reproduzem sem controle e competem com as espécies nativas por espaço e recursos, podendo levá-las à extinção local e desestruturar o ecossistema." },
      { id: "C", text: "A bioinvasão afeta apenas ambientes aquáticos, sendo os ecossistemas terrestres naturalmente resistentes à invasão de espécies exóticas." },
      { id: "D", text: "A bioinvasão é sempre reversível e as espécies nativas se readaptam rapidamente após a introdução de exóticas." },
    ],
    correctAnswer: "B",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "A mineração é uma atividade econômica fundamental, mas gera impactos ambientais severos. Quais são os principais?",
    tip: "A mineração a céu aberto e o processamento de minérios causam diferentes tipos de impacto. Pense no solo, na água e no ar.",
    funFact: "\"Você sabia?\" — O rompimento da Barragem de Brumadinho (MG) em 2019 matou 272 pessoas e lançou 12 milhões de m³ de lama tóxica no rio Paraopeba. O desastre foi classificado como o maior acidente de trabalho do Brasil.",
    points: 1,
    options: [
      { id: "A", text: "A mineração não gera impactos ambientais significativos, pois a legislação brasileira exige a recuperação total das áreas após a extração." },
      { id: "B", text: "Os impactos da mineração se limitam ao período de extração, sendo totalmente revertidos após o fechamento da mina." },
      { id: "C", text: "A mineração afeta apenas as áreas diretamente escavadas, sem impacto sobre rios, fauna ou comunidades vizinhas." },
      { id: "D", text: "Os principais impactos da mineração incluem destruição de relevo e vegetação, contaminação de rios por metais pesados e rejeitos (com risco de rompimento de barragens), geração de poeira e gases, compactação do solo, rebaixamento do lençol freático e deslocamento de comunidades locais." },
    ],
    correctAnswer: "D",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "A educação ambiental é considerada essencial para a construção de uma sociedade sustentável. Qual é seu papel?",
    tip: "A educação ambiental vai além de ensinar sobre a natureza — ela busca formar cidadãos críticos e participativos. Como isso contribui para resolver os problemas ambientais?",
    funFact: "\"Você sabia?\" — O Brasil foi um dos primeiros países do mundo a tornar a educação ambiental obrigatória em todos os níveis de ensino, por meio da Lei 9.795/1999 (Política Nacional de Educação Ambiental), que antecedeu a maioria dos países desenvolvidos.",
    points: 1,
    options: [
      { id: "A", text: "A educação ambiental forma cidadãos críticos capazes de compreender as causas dos problemas ambientais, participar de decisões coletivas, adotar práticas sustentáveis e pressionar por políticas públicas que protejam o ambiente — sendo essencial para a mudança de comportamentos em escala social." },
      { id: "B", text: "A educação ambiental é suficiente por si só para resolver os problemas ambientais, dispensando políticas públicas e legislação." },
      { id: "C", text: "A educação ambiental é relevante apenas para crianças, pois os adultos já têm seus comportamentos consolidados e não mudam." },
      { id: "D", text: "A educação ambiental se limita ao ensino de botânica e zoologia nas escolas, sem relação com questões socioeconômicas." },
    ],
    correctAnswer: "A",
  },
];
