export const questoesIngles7AnoB2Av2 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "Which food is countable (we can count it)?",
    tip: "Pense: você consegue contar \"uma maçã, duas maçãs\"? E com água, consegue contar \"uma água, duas águas\"?",
    funFact: "Existem mais de 7.500 variedades de maçãs no mundo — dá para contar bastante!",
    points: 1,
    options: [
      { id: "A", text: "Water" },
      { id: "B", text: "Apples" },
      { id: "C", text: "Rice" },
      { id: "D", text: "Milk" },
    ],
    correctAnswer: "B",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "Which food is uncountable (we cannot count it)?",
    tip: "Açúcar vem em grãozinhos tão pequenos que não contamos um por um — por isso ele é diferente de ovos, bananas e biscoitos.",
    funFact: "Como o açúcar não pode ser contado, usamos palavras como \"a spoon of sugar\" (uma colher de açúcar) para medir a quantidade!",
    points: 1,
    options: [
      { id: "A", text: "Sugar" },
      { id: "B", text: "Eggs" },
      { id: "C", text: "Bananas" },
      { id: "D", text: "Cookies" },
    ],
    correctAnswer: "A",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "Choose the correct word: \"There is ___ milk in the fridge.\"",
    tip: "\"Milk\" é incontável, então não usamos \"a\" ou \"an\". Qual palavra da lista combina com coisas incontáveis?",
    funFact: "\"Some\" é uma das palavras mais usadas em inglês do dia a dia — significa \"um pouco\" ou \"algum(a)\"!",
    points: 1,
    options: [
      { id: "A", text: "a" },
      { id: "B", text: "an" },
      { id: "C", text: "many" },
      { id: "D", text: "some" },
    ],
    correctAnswer: "D",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "Choose the correct word for a question: \"Is there ___ bread at home?\"",
    tip: "Em perguntas e frases negativas, geralmente usamos \"any\" em vez de \"some\". Lembra dessa regrinha?",
    funFact: "\"Some\" é mais comum em frases afirmativas, e \"any\" aparece mais em perguntas e negativas — são como dupla de amigos que se revezam!",
    points: 1,
    options: [
      { id: "A", text: "some" },
      { id: "B", text: "a" },
      { id: "C", text: "any" },
      { id: "D", text: "many" },
    ],
    correctAnswer: "C",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "Which word do we use with countable nouns in the plural?",
    tip: "\"Many\" combina com coisas que podem ser contadas, como \"many apples\". Qual opção serve para isso?",
    funFact: "Uma forma fácil de lembrar: \"many\" tem \"any\" dentro dela, e \"any\" é usada com substantivos contáveis no plural também!",
    points: 1,
    options: [
      { id: "A", text: "many" },
      { id: "B", text: "much" },
      { id: "C", text: "a little" },
      { id: "D", text: "a bottle of" },
    ],
    correctAnswer: "A",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "Which word do we use with uncountable nouns?",
    tip: "\"Much\" é a parceira de palavras incontáveis, como \"much water\". As outras opções são para coisas contáveis.",
    funFact: "Uma dica rápida: \"much\" combina com \"milk\" — e as duas palavras começam parecido com \"m\"!",
    points: 1,
    options: [
      { id: "A", text: "many" },
      { id: "B", text: "much" },
      { id: "C", text: "two" },
      { id: "D", text: "three" },
    ],
    correctAnswer: "B",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "Choose the uncountable noun.",
    tip: "Cenouras, batatas e tomates dá para contar um por um. Mas e o queijo, dá para contar \"um queijo, dois queijos\" do mesmo jeito?",
    funFact: "Existem mais de 1.800 tipos de queijo no mundo, mas ainda assim tratamos \"cheese\" como algo incontável em inglês!",
    points: 1,
    options: [
      { id: "A", text: "Carrots" },
      { id: "B", text: "Potatoes" },
      { id: "C", text: "Tomatoes" },
      { id: "D", text: "Cheese" },
    ],
    correctAnswer: "D",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "Choose the countable noun.",
    tip: "Farinha, mel e manteiga a gente mede (em gramas, colheres...), mas tem uma opção que podemos contar uma a uma. Qual é?",
    funFact: "Uma galinha pode colocar até 300 \"eggs\" por ano!",
    points: 1,
    options: [
      { id: "A", text: "Flour" },
      { id: "B", text: "Honey" },
      { id: "C", text: "Eggs" },
      { id: "D", text: "Butter" },
    ],
    correctAnswer: "C",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "Complete: \"I would like ___ oranges, please.\"",
    tip: "A frase é um pedido educado (afirmativo), e \"oranges\" está no plural. Qual palavra combina melhor aqui?",
    funFact: "\"I would like\" é uma forma mais educada de dizer \"I want\" — ótima para usar em restaurantes!",
    points: 1,
    options: [
      { id: "A", text: "much" },
      { id: "B", text: "some" },
      { id: "C", text: "a" },
      { id: "D", text: "any" },
    ],
    correctAnswer: "B",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "Complete: \"There isn't ___ juice left in the bottle.\"",
    tip: "A frase tem \"isn't\" (negativa). Lembra que em frases negativas usamos \"any\" em vez de \"some\"?",
    funFact: "O suco mais consumido no mundo é o de laranja — então essa garrafa vazia é bem comum!",
    points: 1,
    options: [
      { id: "A", text: "any" },
      { id: "B", text: "some" },
      { id: "C", text: "many" },
      { id: "D", text: "a" },
    ],
    correctAnswer: "A",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Complete: \"How ___ sugar do you want in your tea?\"",
    tip: "\"Sugar\" é incontável. Quando perguntamos sobre quantidade de algo incontável, usamos \"how much\" ou \"how many\"?",
    funFact: "No Reino Unido, perguntar \"how much sugar\" é super comum, porque o chá com açúcar é parte da cultura britânica!",
    points: 1,
    options: [
      { id: "A", text: "many" },
      { id: "B", text: "a" },
      { id: "C", text: "much" },
      { id: "D", text: "some" },
    ],
    correctAnswer: "C",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Complete: \"How ___ apples are there in the basket?\"",
    tip: "\"Apples\" está no plural, ou seja, são contáveis. Para perguntar sobre quantidade de coisas contáveis, usamos \"how much\" ou \"how many\"?",
    funFact: "Uma macieira adulta pode produzir mais de 800 maçãs em uma única estação!",
    points: 1,
    options: [
      { id: "A", text: "much" },
      { id: "B", text: "a" },
      { id: "C", text: "any" },
      { id: "D", text: "many" },
    ],
    correctAnswer: "D",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "Choose the correct sentence.",
    tip: "\"Cookies\" está no plural, então o verbo deve ser \"are\", não \"is\". E a palavra para quantidade com plural é \"some\", não \"much\".",
    funFact: "A expressão \"that's the way the cookie crumbles\" é um ditado em inglês que significa algo como \"assim é a vida\"!",
    points: 1,
    options: [
      { id: "A", text: "There are some cookies on the table" },
      { id: "B", text: "There are much cookies on the table" },
      { id: "C", text: "There is some cookies on the table" },
      { id: "D", text: "There are a cookies on the table" },
    ],
    correctAnswer: "A",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "Choose the correct sentence.",
    tip: "\"Water\" é incontável e vem sempre no singular, então usamos \"is\" (não \"are\") e \"some\" (não \"many\" ou \"a\").",
    funFact: "O corpo humano é formado por cerca de 60% de \"water\" — por isso é tão importante beber bastante água!",
    points: 1,
    options: [
      { id: "A", text: "There is many water in the glass" },
      { id: "B", text: "There is some water in the glass" },
      { id: "C", text: "There are some water in the glass" },
      { id: "D", text: "There is a water in the glass" },
    ],
    correctAnswer: "B",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Complete: \"We don't have ___ bananas today.\"",
    tip: "A frase está negativa (\"don't have\"). Lembra qual palavra combina com negativas?",
    funFact: "As bananas não crescem em árvores — elas crescem em plantas gigantes chamadas \"herbs\" (ervas)!",
    points: 1,
    options: [
      { id: "A", text: "some" },
      { id: "B", text: "much" },
      { id: "C", text: "a" },
      { id: "D", text: "any" },
    ],
    correctAnswer: "D",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "Complete: \"She bought ___ bread from the bakery.\"",
    tip: "\"Bread\" é incontável e a frase é afirmativa. Qual palavra combina com isso: \"many\", \"a\", \"some\" ou \"any\"?",
    funFact: "A palavra \"bakery\" (padaria) vem de \"bake\", que significa \"assar\" no forno!",
    points: 1,
    options: [
      { id: "A", text: "many" },
      { id: "B", text: "a" },
      { id: "C", text: "some" },
      { id: "D", text: "any" },
    ],
    correctAnswer: "C",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "Choose the correct question.",
    tip: "\"Eggs\" está no plural, então o verbo certo é \"are\", não \"is\". E em perguntas, usamos \"any\".",
    funFact: "Em inglês britânico, às vezes se usa \"have you got any eggs?\" como alternativa a \"is/are there\"!",
    points: 1,
    options: [
      { id: "A", text: "Are there any eggs in the fridge?" },
      { id: "B", text: "Is there any eggs in the fridge?" },
      { id: "C", text: "Are there some eggs in the fridge, isn't it?" },
      { id: "D", text: "Have there any eggs?" },
    ],
    correctAnswer: "A",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "Complete: \"There is too ___ salt in this soup!\"",
    tip: "\"Salt\" é incontável, igual \"sugar\" e \"water\". Qual palavra de quantidade combina com ela?",
    funFact: "\"Too much\" significa \"demais\"! Se a sopa tem \"too much salt\", ela ficou salgada demais.",
    points: 1,
    options: [
      { id: "A", text: "many" },
      { id: "B", text: "much" },
      { id: "C", text: "a" },
      { id: "D", text: "some" },
    ],
    correctAnswer: "B",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "Complete: \"I need ___ tomatoes for the salad.\"",
    tip: "\"Tomatoes\" está no plural (contável) e a frase é afirmativa. Qual palavra combina melhor?",
    funFact: "Tecnicamente, o tomate é uma fruta, não um vegetal — mas na cozinha ele é tratado como vegetal mesmo assim!",
    points: 1,
    options: [
      { id: "A", text: "much" },
      { id: "B", text: "a" },
      { id: "C", text: "some" },
      { id: "D", text: "any" },
    ],
    correctAnswer: "C",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "Choose the correct sentence.",
    tip: "\"Rice\" é incontável (não existe \"rices\"), então usamos \"how much\" e o verbo \"is\", no singular.",
    funFact: "O arroz é o alimento básico de mais da metade da população mundial!",
    points: 1,
    options: [
      { id: "A", text: "How much rice are there?" },
      { id: "B", text: "How many rice is there?" },
      { id: "C", text: "How much rices is there?" },
      { id: "D", text: "How much rice is there?" },
    ],
    correctAnswer: "D",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Bernardo is making a shopping list with his mom. He wants to buy fruit that can be counted, like apples. Which word is correct? \"We need ___ apples.\"",
    tip: "\"Apples\" é contável e a frase é afirmativa. Qual das palavras combina com isso?",
    funFact: "Fazer listas de compras ajuda a economizar — estudos mostram que quem usa lista gasta menos no supermercado!",
    points: 1,
    options: [
      { id: "A", text: "some" },
      { id: "B", text: "much" },
      { id: "C", text: "a" },
      { id: "D", text: "any" },
    ],
    correctAnswer: "A",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Bernardo looks in the fridge and there's no more milk. How should he say it?",
    tip: "Se não tem mais leite, a frase precisa ser negativa. E \"milk\" é incontável, então o verbo é \"is\", não \"are\".",
    funFact: "O leite pode durar mais tempo fechado na geladeira, mas depois de aberto costuma durar só uma semana!",
    points: 1,
    options: [
      { id: "A", text: "There is some milk" },
      { id: "B", text: "There are some milk" },
      { id: "C", text: "There isn't any milk" },
      { id: "D", text: "There is many milk" },
    ],
    correctAnswer: "C",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Bernardo is helping his mom cook rice. Rice is an uncountable noun. Which word fits? \"How ___ rice do we need?\"",
    tip: "A questão já avisa: \"rice is an uncountable noun\". Para perguntar quantidade de algo incontável, usamos \"how much\" ou \"how many\"?",
    funFact: "Existem mais de 40 mil variedades diferentes de arroz plantadas no mundo!",
    points: 1,
    options: [
      { id: "A", text: "many" },
      { id: "B", text: "much" },
      { id: "C", text: "a" },
      { id: "D", text: "some" },
    ],
    correctAnswer: "B",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Bernardo wants to ask his mom if there are cookies in the kitchen. Which question is correct?",
    tip: "\"Cookies\" está no plural, então o verbo é \"are\". E em perguntas usamos \"any\", não \"some\" ou \"much\".",
    funFact: "Os biscoitos \"chocolate chip cookies\" foram inventados por acaso, nos Estados Unidos, nos anos 1930!",
    points: 1,
    options: [
      { id: "A", text: "Is there some cookies?" },
      { id: "B", text: "Are there much cookies?" },
      { id: "C", text: "Is there any cookie?" },
      { id: "D", text: "Are there any cookies?" },
    ],
    correctAnswer: "D",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Bernardo is setting the table and needs forks, which are countable. He says: \"We need ___ forks for everyone.\"",
    tip: "\"Forks\" é contável e plural, e a frase é afirmativa. Qual palavra combina?",
    funFact: "Garfos só se tornaram populares na Europa há cerca de 500 anos — antes disso, as pessoas comiam mais com as mãos!",
    points: 1,
    options: [
      { id: "A", text: "some" },
      { id: "B", text: "much" },
      { id: "C", text: "a" },
      { id: "D", text: "any" },
    ],
    correctAnswer: "A",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Bernardo's mom asks him to check the sugar for a cake. Sugar is uncountable. He should ask:",
    tip: "\"Sugar\" é incontável, então não existe \"sugars\" no plural aqui, e usamos \"how much\" com \"is\".",
    funFact: "O açúcar branco que usamos em casa passa por um processo chamado refino, que remove a cor natural da cana!",
    points: 1,
    options: [
      { id: "A", text: "How many sugar is there?" },
      { id: "B", text: "How much sugars are there?" },
      { id: "C", text: "How much sugar is there?" },
      { id: "D", text: "How many sugars is there?" },
    ],
    correctAnswer: "C",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Bernardo wants a snack but there are no bananas left. Which sentence is correct?",
    tip: "Se não sobrou nenhuma banana, a frase deve ser negativa, com \"aren't\" e \"any\", já que \"bananas\" está no plural.",
    funFact: "As bananas ajudam a repor energia rapidamente — por isso muitos atletas comem uma antes de competições!",
    points: 1,
    options: [
      { id: "A", text: "There are some bananas" },
      { id: "B", text: "There aren't any bananas" },
      { id: "C", text: "There is any banana" },
      { id: "D", text: "There are much bananas" },
    ],
    correctAnswer: "B",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Bernardo's family is having soup. He wants to say there's a small amount of salt needed. Which phrase fits?",
    tip: "\"Salt\" é incontável, então não usamos \"many\" com ela. \"A little\" significa \"um pouquinho\" e combina com coisas incontáveis como sal.",
    funFact: "\"A little\" é usado com incontáveis (a little salt) e \"a few\" é usado com contáveis (a few eggs) — duas expressões parecidas, mas para situações diferentes!",
    points: 1,
    options: [
      { id: "A", text: "many salt" },
      { id: "B", text: "a little milk" },
      { id: "C", text: "some eggs" },
      { id: "D", text: "a little salt" },
    ],
    correctAnswer: "D",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Bernardo is counting eggs for breakfast. Eggs are countable. He says: \"There are ___ eggs in the box.\"",
    tip: "\"Eggs\" é contável e plural, e a frase é afirmativa. Qual palavra combina?",
    funFact: "Uma caixa de ovos padrão geralmente vem com 12 unidades — essa quantidade é chamada de \"a dozen\"!",
    points: 1,
    options: [
      { id: "A", text: "some" },
      { id: "B", text: "much" },
      { id: "C", text: "a" },
      { id: "D", text: "any" },
    ],
    correctAnswer: "A",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Bernardo's mom is making juice and asks how much orange juice is left. Which question is correct?",
    tip: "\"Juice\" é incontável, então usamos \"how much\" e o verbo \"is\", no singular, igual na própria pergunta que a mãe do Bernardo fez.",
    funFact: "Para fazer um litro de suco de laranja, são necessárias em média 8 a 10 laranjas espremidas!",
    points: 1,
    options: [
      { id: "A", text: "How many orange juice is left?" },
      { id: "B", text: "How much oranges juice are left?" },
      { id: "C", text: "How much orange juice is left?" },
      { id: "D", text: "How many orange juice are there?" },
    ],
    correctAnswer: "C",
  },
];
