export const questoesPortugues8AnoB3Av2 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "O que é \"voz ativa\"?",
    tip: "Pense em uma frase em que o sujeito está \"fazendo\" a ação, e não \"recebendo\" ela.",
    funFact: "A maioria das frases que usamos no dia a dia está na voz ativa, como \"o menino chutou a bola\" — o menino é quem pratica a ação!",
    points: 1,
    options: [
      { id: "A", text: "Quando o verbo está no modo subjuntivo" },
      { id: "B", text: "Quando a frase não tem nenhum verbo" },
      { id: "C", text: "Um tipo de figura de linguagem" },
      { id: "D", text: "Quando o sujeito da frase pratica a ação expressa pelo verbo" },
    ],
    correctAnswer: "D",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "O que é \"voz passiva\"?",
    tip: "Pense em uma frase em que o sujeito não está fazendo a ação, mas sim recebendo o resultado dela.",
    funFact: "Na frase \"a bola foi chutada pelo menino\", a bola (sujeito) não chuta ninguém — ela é quem recebe a ação de ser chutada!",
    points: 1,
    options: [
      { id: "A", text: "Quando o verbo está no futuro" },
      { id: "B", text: "Quando o sujeito da frase sofre (recebe) a ação expressa pelo verbo, em vez de praticá-la" },
      { id: "C", text: "Um tipo de pontuação" },
      { id: "D", text: "Quando não existe nenhum verbo na frase" },
    ],
    correctAnswer: "B",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "Na frase \"O gato comeu o peixe\", em qual voz verbal essa frase está?",
    tip: "Pense em quem está praticando a ação de comer nessa frase — o gato está fazendo ou recebendo a ação?",
    funFact: "Para transformar essa frase para a voz passiva, ela ficaria assim: \"O peixe foi comido pelo gato\" — nesse caso, o peixe passa a ser o sujeito que sofre a ação!",
    points: 1,
    options: [
      { id: "A", text: "Voz ativa" },
      { id: "B", text: "Voz passiva analítica" },
      { id: "C", text: "Voz passiva sintética" },
      { id: "D", text: "Nenhuma das anteriores" },
    ],
    correctAnswer: "A",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "Na frase \"O peixe foi comido pelo gato\", em qual voz verbal essa frase está?",
    tip: "Pense em quem está sofrendo a ação de ser comido nessa frase — é o peixe ou o gato?",
    funFact: "A voz passiva analítica é formada com um verbo auxiliar, como \"ser\" ou \"estar\", seguido do verbo principal no particípio — nesse caso, \"foi comido\"!",
    points: 1,
    options: [
      { id: "A", text: "Voz ativa" },
      { id: "B", text: "Nenhuma voz verbal específica" },
      { id: "C", text: "Voz passiva analítica" },
      { id: "D", text: "Discurso direto" },
    ],
    correctAnswer: "C",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "Na voz passiva analítica, qual é o nome dado ao termo que indica quem pratica a ação (como \"pelo gato\" na frase \"o peixe foi comido pelo gato\")?",
    tip: "Pense em quem realmente \"age\" na frase, mesmo não sendo o sujeito gramatical — essa pessoa ou coisa recebe um nome especial.",
    funFact: "O agente da passiva geralmente aparece introduzido pela preposição \"por\" (ou suas variações, como \"pelo\" e \"pela\"), indicando quem pratica a ação de verdade!",
    points: 1,
    options: [
      { id: "A", text: "Sujeito paciente" },
      { id: "B", text: "Agente da passiva" },
      { id: "C", text: "Objeto direto" },
      { id: "D", text: "Predicado nominal" },
    ],
    correctAnswer: "B",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "O que é a \"voz passiva sintética\"?",
    tip: "Pense em frases como \"vendem-se casas\" — como essa frase é formada, sem usar o verbo \"ser\"?",
    funFact: "A voz passiva sintética é muito usada em anúncios e placas, como \"aluga-se apartamento\" ou \"compram-se carros usados\"!",
    points: 1,
    options: [
      { id: "A", text: "Uma voz verbal usada apenas em poemas" },
      { id: "B", text: "Quando a frase não tem nenhum sujeito" },
      { id: "C", text: "Um tipo de discurso direto" },
      { id: "D", text: "Quando a voz passiva é formada com o verbo principal acompanhado do pronome \"se\"" },
    ],
    correctAnswer: "D",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "Na frase \"Vende-se esta casa\", qual voz verbal está sendo usada?",
    tip: "Pense em como essa frase usa o pronome \"se\" junto ao verbo, sem o auxiliar \"ser\" — isso é característico de qual tipo de voz passiva?",
    funFact: "Esse tipo de construção é muito comum em anúncios de venda e aluguel, sendo uma forma mais direta e econômica de expressar a voz passiva!",
    points: 1,
    options: [
      { id: "A", text: "Voz passiva sintética" },
      { id: "B", text: "Voz ativa" },
      { id: "C", text: "Voz passiva analítica" },
      { id: "D", text: "Discurso indireto" },
    ],
    correctAnswer: "A",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "Para transformar uma frase da voz ativa para a voz passiva analítica, o que geralmente acontece com o objeto direto da frase ativa?",
    tip: "Pense em como, na frase ativa \"o menino quebrou o vaso\", o vaso é o objeto direto; e na frase passiva \"o vaso foi quebrado pelo menino\", o que aconteceu com a palavra \"vaso\"?",
    funFact: "Essa é a principal mudança na transformação da voz ativa para a passiva — o que era objeto direto na voz ativa passa a ser o sujeito da voz passiva!",
    points: 1,
    options: [
      { id: "A", text: "Ele desaparece completamente da frase" },
      { id: "B", text: "Ele se transforma em um adjetivo" },
      { id: "C", text: "Ele se transforma no sujeito da frase passiva" },
      { id: "D", text: "Ele permanece exatamente igual, sem nenhuma mudança de função" },
    ],
    correctAnswer: "C",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "Por que é importante entender a diferença entre voz ativa e voz passiva?",
    tip: "Pense em como saber identificar quem \"faz\" e quem \"recebe\" a ação ajuda a compreender melhor o sentido das frases.",
    funFact: "Escritores usam a voz ativa e a passiva estrategicamente para dar diferentes ênfases às frases — a voz ativa destaca quem age, e a passiva destaca quem recebe a ação!",
    points: 1,
    options: [
      { id: "A", text: "Porque é proibido usar a voz passiva em qualquer situação" },
      { id: "B", text: "Porque não existe nenhuma diferença real entre elas" },
      { id: "C", text: "Porque a voz ativa não pode ser usada em textos formais" },
      { id: "D", text: "Porque isso ajuda a entender melhor quem pratica e quem sofre a ação em uma frase, além de variar o estilo da escrita" },
    ],
    correctAnswer: "D",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "Na frase \"A carta foi escrita por Maria\", qual é o sujeito da frase?",
    tip: "Pense em quem está sofrendo a ação de ser escrita nessa frase — é a carta ou Maria?",
    funFact: "Apesar de Maria ser quem realmente \"escreve\" a carta (o agente da passiva), o sujeito gramatical da frase passiva é \"a carta\", que recebe a ação!",
    points: 1,
    options: [
      { id: "A", text: "\"Maria\"" },
      { id: "B", text: "\"A carta\"" },
      { id: "C", text: "\"Por\"" },
      { id: "D", text: "\"Escrita\"" },
    ],
    correctAnswer: "B",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Transforme a frase da voz ativa \"Os alunos entregaram os trabalhos\" para a voz passiva analítica.",
    tip: "Pense em qual palavra deveria se tornar o novo sujeito da frase passiva — o que estava sendo entregue?",
    funFact: "Observe como \"os trabalhos\" (objeto direto na voz ativa) se tornou o sujeito da voz passiva, enquanto \"os alunos\" se tornou o agente da passiva!",
    points: 1,
    options: [
      { id: "A", text: "\"Os trabalhos foram entregues pelos alunos\"" },
      { id: "B", text: "\"Os alunos foram entregues pelos trabalhos\"" },
      { id: "C", text: "\"Entregam-se os alunos\"" },
      { id: "D", text: "\"Os trabalhos entregaram os alunos\"" },
    ],
    correctAnswer: "A",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Transforme a frase da voz passiva \"O bolo foi feito pela vovó\" para a voz ativa.",
    tip: "Pense em quem realmente pratica a ação de fazer o bolo — quem deveria ser o sujeito na voz ativa?",
    funFact: "Ao transformar para a voz ativa, o agente da passiva (\"pela vovó\") se torna o sujeito da frase, e o antigo sujeito passivo (\"o bolo\") se torna o objeto direto!",
    points: 1,
    options: [
      { id: "A", text: "\"O bolo fez a vovó\"" },
      { id: "B", text: "\"Feito foi o bolo pela vovó\"" },
      { id: "C", text: "\"A vovó fez o bolo\"" },
      { id: "D", text: "\"A vovó foi feita pelo bolo\"" },
    ],
    correctAnswer: "C",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "Por que os textos jornalísticos, às vezes, preferem usar a voz passiva ao relatar uma notícia?",
    tip: "Pense em frases como \"a ponte foi inaugurada\" — às vezes, o importante é destacar o fato em si, e não necessariamente quem o praticou.",
    funFact: "Muitas manchetes de notícias usam a voz passiva justamente para focar no acontecimento, como em \"novo hospital é construído na cidade\"!",
    points: 1,
    options: [
      { id: "A", text: "Porque a voz passiva é proibida em outros tipos de texto" },
      { id: "B", text: "Porque a voz ativa não existe no jornalismo" },
      { id: "C", text: "Porque a voz passiva torna as notícias mais curtas sempre" },
      { id: "D", text: "Para dar destaque à ação ou ao resultado, mesmo quando não se sabe (ou não é importante dizer) quem praticou a ação" },
    ],
    correctAnswer: "D",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "Na frase \"O prédio foi construído\", sem a presença de um agente da passiva, podemos dizer que:",
    tip: "Pense em como, às vezes, não sabemos ou não precisamos dizer quem praticou a ação, mesmo usando a voz passiva.",
    funFact: "Esse tipo de construção, sem agente da passiva expresso, é muito comum quando o foco está no resultado da ação, e não em quem a praticou!",
    points: 1,
    options: [
      { id: "A", text: "A frase está incorreta gramaticalmente" },
      { id: "B", text: "É possível usar a voz passiva mesmo sem mencionar quem praticou a ação" },
      { id: "C", text: "Essa frase está na voz ativa" },
      { id: "D", text: "É obrigatório sempre mencionar o agente da passiva" },
    ],
    correctAnswer: "B",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Qual destas frases apresenta um erro comum na concordância da voz passiva analítica?",
    tip: "Observe o sujeito \"os documentos\" (plural) e compare com a forma do verbo \"ser\" em cada frase — em qual delas a concordância está incorreta?",
    funFact: "Na voz passiva analítica, tanto o verbo \"ser\" quanto o verbo principal (no particípio) devem concordar em gênero e número com o sujeito da frase!",
    points: 1,
    options: [
      { id: "A", text: "\"Os documentos foram assinados pelo diretor.\"" },
      { id: "B", text: "\"A carta foi enviada pelo correio.\"" },
      { id: "C", text: "\"Os documentos foi assinado pelo diretor.\"" },
      { id: "D", text: "\"As cartas foram escritas por Maria.\"" },
    ],
    correctAnswer: "C",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "Qual é a principal diferença de ênfase entre a frase ativa \"O professor corrigiu as provas\" e a passiva \"As provas foram corrigidas pelo professor\"?",
    tip: "Pense em qual das duas frases dá mais destaque ao professor, e qual dá mais destaque às provas.",
    funFact: "Essa diferença de ênfase é uma ferramenta importante para escritores e jornalistas, que escolhem a voz verbal de acordo com o que querem destacar na frase!",
    points: 1,
    options: [
      { id: "A", text: "Na voz ativa, o foco está em quem praticou a ação (o professor); na passiva, o foco está em quem recebeu a ação (as provas)" },
      { id: "B", text: "Não existe nenhuma diferença de ênfase entre elas" },
      { id: "C", text: "A voz passiva sempre esconde quem praticou a ação" },
      { id: "D", text: "A voz ativa é sempre mais longa que a passiva" },
    ],
    correctAnswer: "A",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "Em placas e anúncios, como \"aluga-se sala comercial\", qual voz verbal está sendo usada?",
    tip: "Lembra da voz passiva formada com o pronome \"se\" junto ao verbo principal, sem o uso do verbo \"ser\"?",
    funFact: "Esse tipo de construção é muito comum em anúncios e placas, por ser uma forma mais direta e econômica de expressar a voz passiva!",
    points: 1,
    options: [
      { id: "A", text: "Voz ativa" },
      { id: "B", text: "Discurso direto" },
      { id: "C", text: "Voz passiva analítica" },
      { id: "D", text: "Voz passiva sintética" },
    ],
    correctAnswer: "D",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "Em textos científicos, por que a voz passiva é frequentemente usada para descrever experimentos e procedimentos?",
    tip: "Pense em frases como \"a reação foi observada\" — o importante, em muitos textos científicos, é o que aconteceu, e não necessariamente quem fez a observação.",
    funFact: "Em artigos científicos, é comum encontrar frases como \"foram coletadas amostras\" ou \"os dados foram analisados\", dando destaque ao processo em si!",
    points: 1,
    options: [
      { id: "A", text: "Porque é proibido usar a voz ativa em ciência" },
      { id: "B", text: "Para dar foco ao procedimento ou resultado, em vez de destacar quem o realizou" },
      { id: "C", text: "Porque a voz passiva é sempre mais fácil de entender" },
      { id: "D", text: "Porque cientistas não sabem usar a voz ativa" },
    ],
    correctAnswer: "B",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "Na frase do dia a dia \"A mensagem foi enviada\", podemos identificar que essa frase está na voz:",
    tip: "Pense em quem está sofrendo a ação de ser enviada — é a mensagem. E note que não foi dito quem enviou a mensagem.",
    funFact: "É super comum usarmos frases assim no dia a dia, sem mencionar o agente da passiva, principalmente quando essa informação não é importante no contexto!",
    points: 1,
    options: [
      { id: "A", text: "Passiva, sem agente da passiva expresso" },
      { id: "B", text: "Ativa" },
      { id: "C", text: "Nenhuma das alternativas" },
      { id: "D", text: "Discurso direto" },
    ],
    correctAnswer: "A",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "Qual destas frases está na voz ativa?",
    tip: "Observe qual frase tem o sujeito praticando diretamente a ação do verbo, sem a estrutura típica da voz passiva.",
    funFact: "Na frase \"a mamãe preparou o jantar\", a mamãe é quem pratica a ação de preparar, por isso a frase está na voz ativa!",
    points: 1,
    options: [
      { id: "A", text: "\"O jantar foi preparado pela mamãe.\"" },
      { id: "B", text: "\"Compram-se livros usados.\"" },
      { id: "C", text: "\"A mamãe preparou o jantar.\"" },
      { id: "D", text: "\"O livro foi lido pela turma.\"" },
    ],
    correctAnswer: "C",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Bernardo escreveu na redação: \"O goleiro defendeu o pênalti.\" Essa frase está em qual voz verbal?",
    tip: "Lembra de quem está praticando a ação de defender nessa frase — o goleiro está fazendo ou recebendo a ação?",
    funFact: "Bernardo poderia transformar essa frase para a voz passiva assim: \"O pênalti foi defendido pelo goleiro\" — mudando o foco da frase!",
    points: 1,
    options: [
      { id: "A", text: "Voz passiva analítica" },
      { id: "B", text: "Voz ativa" },
      { id: "C", text: "Voz passiva sintética" },
      { id: "D", text: "Discurso indireto" },
    ],
    correctAnswer: "B",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Bernardo transformou a frase \"O goleiro defendeu o pênalti\" para a voz passiva analítica. Qual destas opções está correta?",
    tip: "Lembra de que o objeto direto da frase ativa (\"o pênalti\") se transforma no sujeito da frase passiva?",
    funFact: "Bernardo aplicou corretamente a regra — \"o pênalti\" se tornou o sujeito, e \"pelo goleiro\" se tornou o agente da passiva, indicando quem realmente praticou a ação!",
    points: 1,
    options: [
      { id: "A", text: "\"O goleiro foi defendido pelo pênalti\"" },
      { id: "B", text: "\"Defende-se o goleiro\"" },
      { id: "C", text: "\"O pênalti defendeu o goleiro\"" },
      { id: "D", text: "\"O pênalti foi defendido pelo goleiro\"" },
    ],
    correctAnswer: "D",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Bernardo leu uma placa na rua que dizia \"vende-se esta casa\". Ele identificou corretamente que essa frase está na voz:",
    tip: "Lembra da voz passiva formada com o pronome \"se\" junto ao verbo, sem o auxiliar \"ser\"?",
    funFact: "Bernardo percebeu que esse tipo de construção é muito comum em placas e anúncios, sendo uma forma mais direta de expressar a voz passiva!",
    points: 1,
    options: [
      { id: "A", text: "Passiva sintética" },
      { id: "B", text: "Ativa" },
      { id: "C", text: "Passiva analítica" },
      { id: "D", text: "Discurso direto" },
    ],
    correctAnswer: "A",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Bernardo leu uma notícia que dizia \"o novo hospital foi inaugurado ontem\", sem mencionar quem o inaugurou. Ele percebeu que essa frase está na voz passiva:",
    tip: "Lembra de que é possível usar a voz passiva analítica (com o verbo \"ser\") mesmo sem mencionar quem praticou a ação?",
    funFact: "Bernardo identificou corretamente — esse tipo de construção é muito usado em notícias, quando o foco está no acontecimento em si, e não em quem o realizou!",
    points: 1,
    options: [
      { id: "A", text: "Sintética" },
      { id: "B", text: "Nenhuma das alternativas" },
      { id: "C", text: "Analítica, sem agente da passiva expresso" },
      { id: "D", text: "Ativa" },
    ],
    correctAnswer: "C",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Bernardo quis dar mais destaque ao resultado de uma ação, em vez de destacar quem a praticou, em uma frase de sua redação. Para isso, ele decidiu usar a voz:",
    tip: "Lembra de qual voz verbal dá mais destaque a quem recebe a ação, em vez de quem a pratica?",
    funFact: "Bernardo fez uma boa escolha estilística — usar a voz passiva é uma estratégia comum quando se quer destacar o resultado de uma ação, e não necessariamente quem a praticou!",
    points: 1,
    options: [
      { id: "A", text: "Ativa, sempre" },
      { id: "B", text: "Nenhuma voz verbal específica" },
      { id: "C", text: "Discurso direto" },
      { id: "D", text: "Passiva" },
    ],
    correctAnswer: "D",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Bernardo transformou a frase passiva \"O bolo foi comido pelas crianças\" para a voz ativa. Qual destas opções está correta?",
    tip: "Lembra de que o agente da passiva (\"pelas crianças\") se transforma no sujeito da frase ativa?",
    funFact: "Bernardo aplicou corretamente a transformação — \"as crianças\" (agente da passiva) se tornou o sujeito, e \"o bolo\" (antigo sujeito passivo) se tornou o objeto direto na voz ativa!",
    points: 1,
    options: [
      { id: "A", text: "\"O bolo comeu as crianças\"" },
      { id: "B", text: "\"As crianças comeram o bolo\"" },
      { id: "C", text: "\"Comem-se bolos pelas crianças\"" },
      { id: "D", text: "\"As crianças foram comidas pelo bolo\"" },
    ],
    correctAnswer: "B",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Bernardo percebeu que, em um artigo científico que leu, a frase \"foram coletadas amostras de água do rio\" estava na voz passiva, dando destaque:",
    tip: "Lembra de por que textos científicos costumam usar a voz passiva, dando foco ao processo e ao resultado, em vez de destacar quem o realizou?",
    funFact: "Bernardo percebeu uma característica comum em textos científicos — o uso da voz passiva ajuda a manter o foco no processo investigado, e não necessariamente em quem o conduziu!",
    points: 1,
    options: [
      { id: "A", text: "Ao procedimento realizado, e não a quem o realizou" },
      { id: "B", text: "Apenas ao pesquisador que coletou as amostras" },
      { id: "C", text: "À cor da água do rio" },
      { id: "D", text: "Ao nome do rio estudado" },
    ],
    correctAnswer: "A",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Bernardo identificou um erro de concordância na frase \"Os relatórios foi entregue pela secretária\". Qual seria a forma correta, de acordo com a norma padrão?",
    tip: "Lembra de que, na voz passiva analítica, tanto o verbo \"ser\" quanto o particípio devem concordar em número com o sujeito \"os relatórios\"?",
    funFact: "Bernardo identificou corretamente o erro — \"os relatórios\" (plural) exige que tanto \"foram\" quanto \"entregues\" também estejam no plural!",
    points: 1,
    options: [
      { id: "A", text: "\"Os relatórios foi entregues pela secretária\"" },
      { id: "B", text: "\"O relatório foram entregue pela secretária\"" },
      { id: "C", text: "\"Os relatórios foram entregues pela secretária\"" },
      { id: "D", text: "\"Os relatório foi entregue pelas secretárias\"" },
    ],
    correctAnswer: "C",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Depois de estudar vozes verbais, Bernardo concluiu que a principal diferença entre a voz ativa e a voz passiva é:",
    tip: "Pense em tudo que você aprendeu sobre quem \"age\" e quem \"recebe\" a ação, dependendo da voz verbal usada na frase.",
    funFact: "Parabéns, Bernardo! Você aprendeu a diferença fundamental entre essas duas vozes verbais, muito importantes para variar o estilo e a ênfase dos seus textos!",
    points: 1,
    options: [
      { id: "A", text: "A voz ativa nunca pode ser usada em textos formais" },
      { id: "B", text: "Na voz ativa, o sujeito pratica a ação; na voz passiva, o sujeito a recebe" },
      { id: "C", text: "Não existe diferença alguma entre elas" },
      { id: "D", text: "A voz passiva é sempre mais curta que a ativa" },
    ],
    correctAnswer: "B",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Depois de todo esse estudo, Bernardo resumiu para a família: \"quando o sujeito pratica a ação do verbo, a frase está na voz ativa; quando o sujeito recebe a ação, a frase está na voz...\". Qual palavra completa essa frase?",
    tip: "Pense na palavra que você aprendeu desde a segunda questão desse simulado, usada para descrever quando o sujeito sofre a ação do verbo.",
    funFact: "Parabéns, Bernardo! Você aprendeu a diferenciar claramente a voz ativa da voz passiva, uma habilidade importante tanto para a leitura quanto para a escrita de bons textos!",
    points: 1,
    options: [
      { id: "A", text: "Indireta" },
      { id: "B", text: "Nominal" },
      { id: "C", text: "Textual" },
      { id: "D", text: "Passiva" },
    ],
    correctAnswer: "D",
  },
];
