export const questoesPortugues9AnoB2Av1 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'Quando dizemos "Bernardo é um leão em campo!", sem usar a palavra "como", estamos usando qual figura de linguagem?',
    tip: 'Pense bem: Bernardo não é literalmente um leão, né? Quando a gente afirma uma coisa no lugar da outra, sem usar "como" ou "tal qual", é porque estamos comparando de um jeito mais direto, quase como se fosse verdade!',
    funFact: 'A metáfora é tão usada que às vezes nem percebemos! Quando dizemos "ele tem um coração de pedra" ou "ela é um anjo", estamos criando metáforas sem nem pensar!',
    points: 1,
    options: [
      { id: 'A', text: 'Onomatopeia' },
      { id: 'B', text: 'Antítese' },
      { id: 'C', text: 'Comparação' },
      { id: 'D', text: 'Metáfora' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: '"Bernardo correu como um raio até a escola." Essa frase usa qual figura de linguagem?',
    tip: 'Repare na palavinha "como" no meio da frase. Ela é a pista que liga duas coisas diferentes (o Bernardo e o raio) mostrando uma semelhança entre elas!',
    funFact: 'A comparação é "prima" da metáfora, mas usa sempre uma palavra de ligação como "como", "tal qual" ou "assim como". É a figura mais fácil de identificar!',
    points: 1,
    options: [
      { id: 'A', text: 'Comparação (símile)' },
      { id: 'B', text: 'Metonímia' },
      { id: 'C', text: 'Eufemismo' },
      { id: 'D', text: 'Gradação' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: '"O vento sussurrava segredos para as árvores." Isso é um exemplo de:',
    tip: 'O vento pode mesmo sussurrar, como uma pessoa faz? Quando damos características humanas (como falar, sentir, sussurrar) para coisas ou animais, isso tem um nome especial!',
    funFact: 'A personificação também é chamada de "prosopopeia" — um nome difícil, mas que aparece bastante em poesias e músicas!',
    points: 1,
    options: [
      { id: 'A', text: 'Hipérbole' },
      { id: 'B', text: 'Personificação' },
      { id: 'C', text: 'Ironia' },
      { id: 'D', text: 'Aliteração' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: '"Eu já disse isso um milhão de vezes!" Essa frase é um exemplo de:',
    tip: 'Será que alguém realmente fala a mesma coisa um milhão de vezes? Quando exageramos bastante para mostrar uma emoção forte, usamos essa figura de linguagem!',
    funFact: 'A hipérbole está em frases do dia a dia como "morri de rir" ou "estou morrendo de fome" — ninguém morreu de verdade, é só um exagero para dar emoção à fala!',
    points: 1,
    options: [
      { id: 'A', text: 'Metáfora' },
      { id: 'B', text: 'Antítese' },
      { id: 'C', text: 'Onomatopeia' },
      { id: 'D', text: 'Hipérbole' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'Quando alguém diz "Que ótimo!" depois de derrubar o suco na mesa, está usando:',
    tip: 'A pessoa realmente está feliz com o suco derramado? Quando falamos uma coisa querendo dizer o contrário, de um jeito meio de brincadeira ou crítica, é essa figura!',
    funFact: 'A ironia é muito usada em humor e em memes! Ela faz a gente rir justamente porque entendemos que o sentido é o oposto do que foi dito.',
    points: 1,
    options: [
      { id: 'A', text: 'Comparação' },
      { id: 'B', text: 'Personificação' },
      { id: 'C', text: 'Ironia' },
      { id: 'D', text: 'Aliteração' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: '"O Brasil ganhou a partida de futebol" (referindo-se ao time brasileiro) é um exemplo de:',
    tip: 'O país inteiro jogou bola? Não, né! Usamos o nome do lugar para representar as pessoas (o time) que são de lá. Essa troca de uma palavra por outra relacionada é a dica!',
    funFact: 'Usamos metonímia o tempo todo sem notar! Quando dizemos "vou ler Machado de Assis", queremos dizer "ler um livro dele", não o autor em pessoa!',
    points: 1,
    options: [
      { id: 'A', text: 'Metonímia' },
      { id: 'B', text: 'Eufemismo' },
      { id: 'C', text: 'Antítese' },
      { id: 'D', text: 'Paradoxo' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'Dizer que uma pessoa "partiu dessa para uma melhor" em vez de dizer que ela morreu é um exemplo de:',
    tip: 'Pensa em uma forma mais suave e delicada de falar sobre algo triste ou difícil. Quando trocamos uma palavra "pesada" por uma mais gentil, é essa figura!',
    funFact: 'O eufemismo é muito usado para falar de assuntos delicados com mais cuidado e respeito, como em notícias ou em conversas sobre temas sensíveis!',
    points: 1,
    options: [
      { id: 'A', text: 'Gradação' },
      { id: 'B', text: 'Catacrese' },
      { id: 'C', text: 'Hipérbole' },
      { id: 'D', text: 'Eufemismo' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: '"A sala estava em silêncio, mas o coração de Bernardo gritava de nervosismo." Esse contraste de ideias é:',
    tip: 'Repare: "silêncio" e "gritava" são ideias opostas colocadas lado a lado de propósito. Quando juntamos palavras ou ideias contrárias na mesma frase, temos essa figura!',
    funFact: 'A antítese é muito usada em frases de efeito e discursos famosos, como "um pequeno passo para o homem, um grande salto para a humanidade"!',
    points: 1,
    options: [
      { id: 'A', text: 'Onomatopeia' },
      { id: 'B', text: 'Antítese' },
      { id: 'C', text: 'Comparação' },
      { id: 'D', text: 'Metonímia' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'A palavra "miau", usada para representar o som do gato, é um exemplo de:',
    tip: 'Pensa em quadrinhos! Quando uma palavra tenta "imitar" um som da natureza ou de um objeto (como "boom", "tique-taque", "au au"), essa é a figura procurada!',
    funFact: 'As onomatopeias mudam de um idioma para o outro! O galo brasileiro canta "cocoricó", mas em inglês ele canta "cock-a-doodle-doo"!',
    points: 1,
    options: [
      { id: 'A', text: 'Hipérbole' },
      { id: 'B', text: 'Eufemismo' },
      { id: 'C', text: 'Onomatopeia' },
      { id: 'D', text: 'Antítese' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: '"O rato roeu a roupa do rei de Roma" é um exemplo famoso de qual figura, por repetir sons parecidos (como o "r")?',
    tip: 'Fala essa frase em voz alta e preste atenção no som que se repete bastante no começo das palavras. Essa repetição de sons parecidos tem um nome!',
    funFact: 'Esse trava-língua é usado há gerações para treinar a pronúncia! A aliteração também é muito usada em propagandas e títulos para ficarem mais "gostosos" de ouvir.',
    points: 1,
    options: [
      { id: 'A', text: 'Aliteração' },
      { id: 'B', text: 'Hipérbole' },
      { id: 'C', text: 'Ironia' },
      { id: 'D', text: 'Metonímia' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: '"Ecoa a brisa macia na mata" repete o som da vogal "a" várias vezes. Isso é um exemplo de:',
    tip: 'Lembra que a aliteração repete sons de consoantes? Pois essa figura é "parecida", mas repete sons de vogais! Preste atenção nas vogais que mais aparecem na frase.',
    funFact: 'Poetas adoram usar a assonância para dar musicalidade aos versos, criando um efeito quase de canção só com a escolha das palavras!',
    points: 1,
    options: [
      { id: 'A', text: 'Metáfora' },
      { id: 'B', text: 'Assonância' },
      { id: 'C', text: 'Ironia' },
      { id: 'D', text: 'Catacrese' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'Quando dizemos "vou pegar o ônibus" (mesmo sabendo que ônibus não se "pega" com as mãos, mas sim embarcamos nele), estamos usando:',
    tip: 'Pensa em palavras que usamos no sentido errado há tanto tempo que já ficou "normal", como "descascar a laranja" ou "colocar o dedo na tomada". Esse uso "torto" tem nome!',
    funFact: 'A catacrese acontece porque, às vezes, a língua não tem uma palavra exata para algo, então "pegamos emprestada" outra palavra que já existe, mesmo não sendo 100% precisa!',
    points: 1,
    options: [
      { id: 'A', text: 'Hipérbole' },
      { id: 'B', text: 'Antítese' },
      { id: 'C', text: 'Catacrese' },
      { id: 'D', text: 'Onomatopeia' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: '"Ele entrou na sala, olhou, sorriu, gritou de alegria e pulou de felicidade." Essa sequência de ações cada vez mais intensa é chamada de:',
    tip: 'Olha como as ações vão aumentando de intensidade, uma depois da outra: olhar, sorrir, gritar, pular. Quando as ideias crescem em grau, pouco a pouco, temos essa figura!',
    funFact: 'A gradação é muito usada em discursos para criar um clima de emoção crescente, levando o público para um ponto alto de empolgação!',
    points: 1,
    options: [
      { id: 'A', text: 'Eufemismo' },
      { id: 'B', text: 'Onomatopeia' },
      { id: 'C', text: 'Antítese' },
      { id: 'D', text: 'Gradação' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: '"É um silêncio ensurdecedor" é uma frase que mistura duas ideias que parecem impossíveis juntas (silêncio não faz barulho, mas aqui "ensurdece"). Isso é chamado de:',
    tip: 'Pensa bem: como um silêncio pode "ensurdecer" alguém, se silêncio é justamente a ausência de som? Quando duas ideias parecem se contradizer, mas fazem sentido juntas, temos essa figura!',
    funFact: 'O paradoxo é diferente da antítese porque aqui as ideias contraditórias ficam numa mesma expressão, criando um efeito de mistério ou reflexão!',
    points: 1,
    options: [
      { id: 'A', text: 'Paradoxo' },
      { id: 'B', text: 'Metonímia' },
      { id: 'C', text: 'Comparação' },
      { id: 'D', text: 'Aliteração' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: '"A lua observava a cidade adormecida" usa a mesma figura da Questão 3. Qual é ela?',
    tip: 'A lua tem olhos para "observar" de verdade? Quando damos ações humanas para coisas da natureza, estamos usando a mesma figura que vimos com o vento que "sussurrava"!',
    funFact: 'Muitos contos de fadas e fábulas usam a personificação para dar vida a objetos, animais e elementos da natureza, tornando a história mais mágica!',
    points: 1,
    options: [
      { id: 'A', text: 'Hipérbole' },
      { id: 'B', text: 'Personificação' },
      { id: 'C', text: 'Eufemismo' },
      { id: 'D', text: 'Metonímia' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'Qual frase abaixo é um exemplo de HIPÉRBOLE?',
    tip: 'Lembra que a hipérbole é sempre um EXAGERO enorme, impossível de ser verdade. Procure a frase que exagera demais numa ideia simples, como cansaço.',
    funFact: 'Cientistas descobriram que exagerar ao contar histórias (como fazemos com a hipérbole) ajuda as pessoas a prestarem mais atenção e lembrarem melhor do que foi dito!',
    points: 1,
    options: [
      { id: 'A', text: '"A Lua parecia sorrir para nós."' },
      { id: 'B', text: '"Estou tão cansado que poderia dormir um ano inteiro!"' },
      { id: 'C', text: '"Ele é rápido como um foguete."' },
      { id: 'D', text: '"O silêncio gritava naquela sala vazia."' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'Qual frase abaixo é um exemplo de METÁFORA?',
    tip: 'Procure a frase que afirma que uma coisa É a outra, sem usar "como". A vida realmente é feita de trilhos e carrinhos? Não, mas a ideia de subidas e descidas combina com ela!',
    funFact: 'Grandes escritores e compositores usam metáforas para expressar sentimentos complexos de um jeito mais bonito e criativo, como "o tempo é um rio que não para"!',
    points: 1,
    options: [
      { id: 'A', text: '"A chuva batia como tambores no telhado."' },
      { id: 'B', text: '"Minha vida é uma montanha-russa."' },
      { id: 'C', text: '"Psiu! Silêncio na biblioteca."' },
      { id: 'D', text: '"Trim, trim! O telefone tocou."' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'Qual frase abaixo é um exemplo de COMPARAÇÃO (símile)?',
    tip: 'Procure a frase que tem a palavrinha "como" ligando duas coisas diferentes. Ela é como um peixe? Não é, mas nada parecido com um!',
    funFact: 'Comparações aparecem em quase toda música que você escuta no rádio! Preste atenção na próxima vez e você vai notar várias "como" escondidas nas letras!',
    points: 1,
    options: [
      { id: 'A', text: '"Ela nada como um peixe."' },
      { id: 'B', text: '"O tempo voou nessa prova."' },
      { id: 'C', text: '"Já contei isso mil vezes!"' },
      { id: 'D', text: '"A esperança é a última a morrer."' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'Bernardo disse: "Que surpresa boa, chover justamente no dia do piquenique!" — sendo que ele estava, na verdade, bem chateado. Isso é um exemplo de:',
    tip: 'Será que o Bernardo está mesmo feliz com a chuva estragando o piquenique? Quando a gente diz o contrário do que sente, de um jeito irônico, essa é a figura!',
    funFact: 'A ironia é tão usada no dia a dia que ganhou até um sinalzinho de "sarcasmo" em algumas redes sociais, para deixar claro que a pessoa quis dizer o oposto!',
    points: 1,
    options: [
      { id: 'A', text: 'Gradação' },
      { id: 'B', text: 'Catacrese' },
      { id: 'C', text: 'Assonância' },
      { id: 'D', text: 'Ironia' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: '"Ela é tão alegre quanto triste ao mesmo tempo, rindo e chorando de emoção." Esse encontro de sentimentos opostos é exemplo de:',
    tip: '"Alegre" e "triste", "rindo" e "chorando" — são palavras que se opõem na mesma frase. Essa é a mesma figura que vimos com "silêncio" e "gritava"!',
    funFact: 'Na vida real, é bem comum sentir emoções opostas ao mesmo tempo, como ficar feliz e nervoso antes de uma apresentação — a antítese ajuda a expressar bem esse sentimento misto!',
    points: 1,
    options: [
      { id: 'A', text: 'Onomatopeia' },
      { id: 'B', text: 'Antítese' },
      { id: 'C', text: 'Eufemismo' },
      { id: 'D', text: 'Hipérbole' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Bernardo escreveu na redação: "Meu quarto é um verdadeiro campo de batalha de brinquedos!" Que figura de linguagem ele usou?',
    tip: 'O quarto do Bernardo tem soldados e tanques de guerra de verdade? Não! Ele está comparando de forma direta (sem "como") a bagunça com uma batalha. Essa é a mesma figura da Questão 1!',
    funFact: 'Usar metáforas na redação é uma ótima forma de deixar o texto mais criativo e de chamar a atenção de quem está lendo — os professores adoram ver isso!',
    points: 1,
    options: [
      { id: 'A', text: 'Metáfora' },
      { id: 'B', text: 'Onomatopeia' },
      { id: 'C', text: 'Eufemismo' },
      { id: 'D', text: 'Assonância' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Bernardo disse para a mãe: "Estou com uma fome de leão, poderia comer como um elefante!" Que figura ele usou?',
    tip: 'Repare na palavrinha "como" ligando a fome do Bernardo a um elefante. Ele é um elefante de verdade? Claro que não — ele está só comparando!',
    funFact: 'Comparar sentimentos com animais é super comum! Dizemos "forte como um touro", "ágil como um gato" — isso ajuda a gente a imaginar melhor o que a pessoa está sentindo!',
    points: 1,
    options: [
      { id: 'A', text: 'Antítese' },
      { id: 'B', text: 'Metonímia' },
      { id: 'C', text: 'Eufemismo' },
      { id: 'D', text: 'Comparação' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Na redação, Bernardo exagerou: "Esperei um século para a prova de Matemática acabar!" Isso é um exemplo de:',
    tip: 'Será que o Bernardo esperou mesmo cem anos? Claro que não! Quando exageramos tanto assim para mostrar como o tempo pareceu longo, usamos essa figura.',
    funFact: 'Usar hipérboles na escrita ajuda o leitor a sentir, de um jeito mais forte, a emoção que você quer transmitir — por isso ela é tão usada em textos divertidos!',
    points: 1,
    options: [
      { id: 'A', text: 'Personificação' },
      { id: 'B', text: 'Antítese' },
      { id: 'C', text: 'Hipérbole' },
      { id: 'D', text: 'Onomatopeia' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Bernardo escreveu: "O caderno dele sorria de tão organizado que estava." Que figura de linguagem aparece aqui?',
    tip: 'Um caderno pode sorrir de verdade? Quando damos características humanas, como sorrir, para objetos, estamos usando a mesma figura do vento e da lua que vimos antes!',
    funFact: 'Dar vida a objetos através da personificação é uma técnica muito usada em desenhos animados, como em histórias onde brinquedos falam e sentem emoções!',
    points: 1,
    options: [
      { id: 'A', text: 'Eufemismo' },
      { id: 'B', text: 'Personificação' },
      { id: 'C', text: 'Gradação' },
      { id: 'D', text: 'Aliteração' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Enquanto brincava, Bernardo imitou o som do trovão dizendo "Bum! Bum!". Isso é um exemplo de:',
    tip: 'Lembra da figura que imita sons, como "miau" e "tique-taque"? O Bernardo está fazendo a mesma coisa, só que com o som do trovão!',
    funFact: 'Os quadrinhos usam muitas onomatopeias para representar sons de ação, como "POW!", "BANG!" e "SPLASH!", tornando a leitura mais divertida e cheia de energia!',
    points: 1,
    options: [
      { id: 'A', text: 'Onomatopeia' },
      { id: 'B', text: 'Metáfora' },
      { id: 'C', text: 'Ironia' },
      { id: 'D', text: 'Catacrese' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Bernardo tirou uma nota baixa e disse, de brincadeira: "Que ótimo, mais uma matéria para eu \'adorar\' estudar de novo!" Isso é um exemplo de:',
    tip: 'O Bernardo realmente adora estudar aquela matéria de novo? Pelo visto, não! Quando ele diz o contrário do que sente, com aquele tom de brincadeira, é a mesma figura da Questão 5 e 19!',
    funFact: 'Usar a ironia com bom humor é uma forma saudável de lidar com situações difíceis, rindo um pouco de si mesmo — isso é comum até entre adultos!',
    points: 1,
    options: [
      { id: 'A', text: 'Gradação' },
      { id: 'B', text: 'Assonância' },
      { id: 'C', text: 'Ironia' },
      { id: 'D', text: 'Eufemismo' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Em vez de dizer que seu cachorro "morreu", Bernardo contou para o amigo que o cachorro "foi para o céu dos animais". Que figura ele usou?',
    tip: 'Lembra da figura que usa palavras mais suaves para falar de assuntos tristes? O Bernardo escolheu uma forma mais gentil de contar uma notícia difícil — é a mesma da Questão 7!',
    funFact: 'Usar o eufemismo com cuidado e carinho em momentos tristes é uma forma bonita de demonstrar sensibilidade ao falar sobre perdas e despedidas.',
    points: 1,
    options: [
      { id: 'A', text: 'Hipérbole' },
      { id: 'B', text: 'Antítese' },
      { id: 'C', text: 'Onomatopeia' },
      { id: 'D', text: 'Eufemismo' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Bernardo escreveu: "Na mesma hora em que ria da piada, suas lágrimas de tristeza também caíam." Essa mistura de alegria e tristeza é exemplo de:',
    tip: '"Rir" e "lágrimas de tristeza" são ideias que parecem opostas na mesma frase. Essa é a mesma figura que apareceu nas Questões 8 e 20!',
    funFact: 'Emoções misturadas como essa acontecem bastante na vida real — dá até um nome especial: "agridoce"! E a antítese é perfeita para descrever esse tipo de sentimento.',
    points: 1,
    options: [
      { id: 'A', text: 'Metonímia' },
      { id: 'B', text: 'Antítese' },
      { id: 'C', text: 'Eufemismo' },
      { id: 'D', text: 'Hipérbole' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Bernardo criou um trava-língua para brincar com o irmão: "O bicho bravo berrava bem bravo no bosque." Qual figura de linguagem ele usou?',
    tip: 'Repare no som que se repete bastante no começo de várias palavras da frase do Bernardo. É a mesma figura do trava-língua "o rato roeu a roupa do rei de Roma"!',
    funFact: 'Criar trava-línguas com aliteração é uma brincadeira muito antiga, usada em várias culturas do mundo para treinar a fala e se divertir com as palavras!',
    points: 1,
    options: [
      { id: 'A', text: 'Aliteração' },
      { id: 'B', text: 'Gradação' },
      { id: 'C', text: 'Metáfora' },
      { id: 'D', text: 'Eufemismo' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'Depois de estudar tanto, Bernardo quer fazer uma revisão geral. Qual das opções abaixo é uma HIPÉRBOLE?',
    tip: 'Lembre-se: a hipérbole é sempre um exagero GIGANTE, quase impossível de acontecer na vida real. Procure a frase com o número mais exagerado!',
    funFact: 'Parabéns por chegar até aqui! Agora você já conhece várias figuras de linguagem — elas tornam qualquer texto mais bonito, divertido e cheio de emoção. Continue usando-as nas suas redações!',
    points: 1,
    options: [
      { id: 'A', text: '"O rio sussurrava histórias antigas." (personificação)' },
      { id: 'B', text: '"Ele é ligeiro como um raio." (comparação)' },
      { id: 'C', text: '"Já te disse isso um bilhão de vezes!" (exagero impossível)' },
      { id: 'D', text: '"A alegria e a tristeza se misturavam nele." (antítese)' },
    ],
    correctAnswer: 'C',
  },
];
