export const questoesMatematica9AnoB2Av1 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "Uma EQUAÇÃO DO 2º GRAU é uma equação polinomial em que o maior expoente da variável é:",
    tip: "O 'grau' de uma equação é dado pelo maior expoente da variável — o 2º grau tem expoente...",
    funFact: "\"Você Sabia?\" — As equações do 2º grau foram estudadas pelos babilônios há mais de 4.000 anos. Uma tábua de argila de 1800 a.C. contém a solução de equações equivalentes às do 2º grau.",
    points: 1,
    options: [
      { id: "A", text: "1" },
      { id: "B", text: "2" },
      { id: "C", text: "3" },
      { id: "D", text: "0" },
    ],
    correctAnswer: "B",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "A forma geral de uma equação do 2º grau é ax² + bx + c = 0. Qual condição é obrigatória?",
    tip: "Sem essa condição, a equação seria do 1º grau, não do 2º.",
    funFact: "\"Você Sabia?\" — A condição a ≠ 0 é essencial: se a = 0, temos bx + c = 0, que é uma equação do 1º grau. O coeficiente 'a' define o grau da equação.",
    points: 1,
    options: [
      { id: "A", text: "b ≠ 0" },
      { id: "B", text: "c ≠ 0" },
      { id: "C", text: "b ≠ 0 e c ≠ 0" },
      { id: "D", text: "a ≠ 0" },
    ],
    correctAnswer: "D",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "Uma equação do 2º grau COMPLETA é aquela em que:",
    tip: "Completa significa que todos os termos estão presentes.",
    funFact: "\"Você Sabia?\" — A equação x² + 3x + 2 = 0 é completa (a=1, b=3, c=2). Já x² − 4 = 0 é incompleta (b=0) e x² = 0 é a mais simples de todas (b=0 e c=0).",
    points: 1,
    options: [
      { id: "A", text: "Os coeficientes a, b e c são todos diferentes de zero." },
      { id: "B", text: "Tem apenas uma solução." },
      { id: "C", text: "O coeficiente a é igual a zero." },
      { id: "D", text: "Tem o coeficiente b igual a zero." },
    ],
    correctAnswer: "A",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "Qual é o conjunto solução da equação incompleta x² = 0?",
    tip: "Que número, ao ser elevado ao quadrado, resulta em zero?",
    funFact: "\"Você Sabia?\" — A equação x² = 0 tem raiz dupla x = 0. Diz-se que 0 é uma 'raiz de multiplicidade 2' — isso tem importância em cálculo diferencial e geometria analítica.",
    points: 1,
    options: [
      { id: "A", text: "{−1, 1}" },
      { id: "B", text: "∅ (conjunto vazio)" },
      { id: "C", text: "{0}" },
      { id: "D", text: "{0, 0} = {0, −0}" },
    ],
    correctAnswer: "C",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "Resolva a equação incompleta x² − 16 = 0:",
    tip: "Isole o x²: x² = 16. Quais números ao quadrado dão 16?",
    funFact: "\"Você Sabia?\" — A equação x² = k tem sempre duas soluções reais e opostas (√k e −√k) quando k > 0; nenhuma quando k < 0; e uma única solução (0) quando k = 0.",
    points: 1,
    options: [
      { id: "A", text: "x = 4" },
      { id: "B", text: "x = 4 ou x = −4" },
      { id: "C", text: "x = 8" },
      { id: "D", text: "x = ±√16 = ±4 (apenas a positiva vale)" },
    ],
    correctAnswer: "B",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "Resolva a equação incompleta 3x² − 6x = 0:",
    tip: "Coloque x em evidência: x(3x − 6) = 0. Quando um produto é zero?",
    funFact: "\"Você Sabia?\" — A regra do produto nulo ('se A × B = 0, então A = 0 ou B = 0') é um dos princípios fundamentais da álgebra e é usada para resolver equações fatoradas.",
    points: 1,
    options: [
      { id: "A", text: "x = 2" },
      { id: "B", text: "x = 0 ou x = −2" },
      { id: "C", text: "x = 3 ou x = −6" },
      { id: "D", text: "x = 0 ou x = 2" },
    ],
    correctAnswer: "D",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "O DISCRIMINANTE (Δ) de uma equação do 2º grau ax² + bx + c = 0 é calculado por:",
    tip: "O discriminante determina a quantidade e a natureza das raízes.",
    funFact: "\"Você Sabia?\" — A palavra 'discriminante' vem do latim 'discriminare' (separar, distinguir) — ele distingue os três casos: duas raízes reais distintas, raiz dupla ou sem raízes reais.",
    points: 1,
    options: [
      { id: "A", text: "Δ = b² − 4ac" },
      { id: "B", text: "Δ = b² + 4ac" },
      { id: "C", text: "Δ = −b² + 4ac" },
      { id: "D", text: "Δ = 4ac − b²" },
    ],
    correctAnswer: "A",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "Quando Δ > 0, a equação do 2º grau possui:",
    tip: "O discriminante positivo indica... quantas raízes reais?",
    funFact: "\"Você Sabia?\" — Geometricamente, quando Δ > 0, a parábola y = ax² + bx + c corta o eixo x em dois pontos distintos — as duas raízes reais e distintas da equação.",
    points: 1,
    options: [
      { id: "A", text: "Nenhuma raiz real." },
      { id: "B", text: "Uma raiz real dupla." },
      { id: "C", text: "Duas raízes reais e distintas." },
      { id: "D", text: "Três raízes reais." },
    ],
    correctAnswer: "C",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "Quando Δ = 0, a equação do 2º grau possui:",
    tip: "Δ = 0 é o caso especial de toque — a parábola é tangente ao eixo x.",
    funFact: "\"Você Sabia?\" — Quando Δ = 0, a raiz dupla x = −b/(2a) é exatamente o vértice da parábola no eixo x — é o ponto de mínimo (ou máximo) da função quadrática.",
    points: 1,
    options: [
      { id: "A", text: "Nenhuma raiz real." },
      { id: "B", text: "Uma raiz real dupla (raiz repetida)." },
      { id: "C", text: "Duas raízes reais e distintas." },
      { id: "D", text: "Infinitas raízes reais." },
    ],
    correctAnswer: "B",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "Quando Δ < 0, a equação do 2º grau no conjunto dos números reais possui:",
    tip: "Não é possível extrair raiz quadrada de número negativo nos reais.",
    funFact: "\"Você Sabia?\" — Quando Δ < 0, as soluções existem no conjunto dos números complexos. Os números complexos foram criados exatamente para resolver equações com Δ < 0.",
    points: 1,
    options: [
      { id: "A", text: "Duas raízes reais e distintas." },
      { id: "B", text: "Uma raiz real dupla." },
      { id: "C", text: "Uma raiz real e uma complexa." },
      { id: "D", text: "Nenhuma raiz real." },
    ],
    correctAnswer: "D",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "A FÓRMULA DE BHASKARA para resolver a equação ax² + bx + c = 0 é:",
    tip: "Bhaskara é o método universal para equações do 2º grau completas.",
    funFact: "\"Você Sabia?\" — A fórmula que chamamos de 'Bhaskara' no Brasil foi na verdade desenvolvida por vários matemáticos ao longo dos séculos. O matemático indiano Bhaskara II (1114-1185) popularizou uma versão dessa fórmula.",
    points: 1,
    options: [
      { id: "A", text: "x = (−b ± √Δ) / (2a)" },
      { id: "B", text: "x = (b ± √Δ) / (2a)" },
      { id: "C", text: "x = (−b ± √Δ) / a" },
      { id: "D", text: "x = (b ± √Δ) / a" },
    ],
    correctAnswer: "A",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Resolva a equação x² − 5x + 6 = 0 usando Bhaskara:",
    tip: "Identifique a=1, b=−5, c=6. Calcule Δ = b² − 4ac = 25 − 24 = 1. Então x = (5 ± 1)/2.",
    funFact: "\"Você Sabia?\" — A equação x² − 5x + 6 = 0 tem raízes 2 e 3, pois 2 + 3 = 5 e 2 × 3 = 6. Isso ilustra as relações de Girard (soma = −b/a e produto = c/a).",
    points: 1,
    options: [
      { id: "A", text: "x = 1 e x = 6" },
      { id: "B", text: "x = −2 e x = −3" },
      { id: "C", text: "x = 2 e x = 3" },
      { id: "D", text: "x = −1 e x = 6" },
    ],
    correctAnswer: "C",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "Pelas RELAÇÕES DE GIRARD, se x₁ e x₂ são as raízes de ax² + bx + c = 0, então a soma x₁ + x₂ é igual a:",
    tip: "As relações de Girard ligam as raízes aos coeficientes sem precisar resolver a equação.",
    funFact: "\"Você Sabia?\" — As relações de Girard foram publicadas pelo matemático francês Albert Girard em 1629. Elas permitem encontrar equações cujas raízes somam e multiplicam a valores dados.",
    points: 1,
    options: [
      { id: "A", text: "c/a" },
      { id: "B", text: "−b/a" },
      { id: "C", text: "b/a" },
      { id: "D", text: "−c/a" },
    ],
    correctAnswer: "B",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "Pelas RELAÇÕES DE GIRARD, o produto das raízes x₁ × x₂ é igual a:",
    tip: "O produto das raízes depende dos coeficientes a e c da equação geral.",
    funFact: "\"Você Sabia?\" — O produto das raízes c/a é usado na criptografia RSA — o produto de dois números primos grandes (as 'raízes') forma a chave pública, difícil de fatorar.",
    points: 1,
    options: [
      { id: "A", text: "−b/a" },
      { id: "B", text: "b/a" },
      { id: "C", text: "−c/a" },
      { id: "D", text: "c/a" },
    ],
    correctAnswer: "D",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Identifique os coeficientes a, b e c da equação 2x² − 3x + 1 = 0:",
    tip: "Compare com a forma geral ax² + bx + c = 0.",
    funFact: "\"Você Sabia?\" — A correta identificação de a, b, c é o primeiro passo para qualquer método de resolução. Um erro aqui contamina todo o cálculo seguinte.",
    points: 1,
    options: [
      { id: "A", text: "a = 2, b = −3, c = 1" },
      { id: "B", text: "a = 2, b = 3, c = 1" },
      { id: "C", text: "a = 2, b = −3, c = −1" },
      { id: "D", text: "a = −2, b = 3, c = 1" },
    ],
    correctAnswer: "A",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "Resolva a equação x² − 9 = 0 usando fatoração (diferença de quadrados):",
    tip: "x² − 9 = (x + 3)(x − 3) = 0. Aplique a regra do produto nulo.",
    funFact: "\"Você Sabia?\" — Toda equação do tipo x² = k pode ser resolvida sem Bhaskara, apenas isolando x e extraindo a raiz quadrada (ou usando diferença de quadrados). Economiza muito tempo!",
    points: 1,
    options: [
      { id: "A", text: "x = 9" },
      { id: "B", text: "x = 3" },
      { id: "C", text: "x = 3 ou x = −3" },
      { id: "D", text: "x = ±√9 = não existe" },
    ],
    correctAnswer: "C",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "Resolva 2x² + 3x = 0:",
    tip: "Coloque x em evidência: x(2x + 3) = 0. Aplique a regra do produto nulo.",
    funFact: "\"Você Sabia?\" — Equações do tipo ax² + bx = 0 (sem o termo independente c) SEMPRE têm x = 0 como uma das soluções — nunca use Bhaskara para elas, pois a fatoração é muito mais rápida.",
    points: 1,
    options: [
      { id: "A", text: "x = −3/2" },
      { id: "B", text: "x = 0 ou x = −3/2" },
      { id: "C", text: "x = 0 ou x = 3/2" },
      { id: "D", text: "x = 2/3 ou x = 3" },
    ],
    correctAnswer: "B",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "Resolva x² + 4x + 4 = 0:",
    tip: "Reconheça o trinômio do quadrado perfeito: x² + 4x + 4 = (x + 2)².",
    funFact: "\"Você Sabia?\" — A equação (x + 2)² = 0 tem raiz dupla x = −2. Geometricamente, a parábola y = x² + 4x + 4 é tangente ao eixo x no ponto (−2, 0).",
    points: 1,
    options: [
      { id: "A", text: "x = 2 ou x = −2" },
      { id: "B", text: "x = 4" },
      { id: "C", text: "x = 2" },
      { id: "D", text: "x = −2 (raiz dupla)" },
    ],
    correctAnswer: "D",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "Um retângulo tem comprimento 3 cm a mais que a largura. Se a área é 28 cm², qual é a largura?",
    tip: "Se a largura é x, o comprimento é x + 3. Monte a equação: x(x + 3) = 28.",
    funFact: "\"Você Sabia?\" — Problemas de área de retângulo gerando equações do 2º grau aparecem em construção civil, design de interiores e até em problemas de economia (otimização de produção).",
    points: 1,
    options: [
      { id: "A", text: "4 cm" },
      { id: "B", text: "7 cm" },
      { id: "C", text: "14 cm" },
      { id: "D", text: "3 cm" },
    ],
    correctAnswer: "A",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "Para a equação 3x² − 2x + k = 0 ter uma raiz real dupla, qual deve ser o valor de k?",
    tip: "Para raiz dupla, Δ = 0. Calcule b² − 4ac = 0 e resolva para k.",
    funFact: "\"Você Sabia?\" — A condição Δ = 0 é usada em engenharia de controle para encontrar o 'amortecimento crítico' — o ponto em que um sistema oscilante retorna ao equilíbrio sem oscilar.",
    points: 1,
    options: [
      { id: "A", text: "k = 3" },
      { id: "B", text: "k = −1/3" },
      { id: "C", text: "k = 1/3" },
      { id: "D", text: "k = −3" },
    ],
    correctAnswer: "C",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Determine o discriminante da equação x² + 6x + 9 = 0 e classifique suas raízes:",
    tip: "Calcule Δ = 6² − 4(1)(9) = 36 − 36. Qual é o resultado?",
    funFact: "\"Você Sabia?\" — x² + 6x + 9 = (x + 3)² — é um trinômio do quadrado perfeito! Sempre que Δ = 0, a equação pode ser escrita como (x − r)² = 0 para alguma raiz r.",
    points: 1,
    options: [
      { id: "A", text: "Δ = 72 → duas raízes reais distintas" },
      { id: "B", text: "Δ = 0 → uma raiz real dupla: x = −3" },
      { id: "C", text: "Δ = −72 → nenhuma raiz real" },
      { id: "D", text: "Δ = 9 → duas raízes reais distintas" },
    ],
    correctAnswer: "B",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "A EQUAÇÃO BIQUADRADA tem a forma ax⁴ + bx² + c = 0. Para resolvê-la, fazemos a substituição:",
    tip: "A substituição transforma a equação biquadrada em uma equação do 2º grau em outra variável.",
    funFact: "\"Você Sabia?\" — Equações biquadradas aparecem na física ao calcular a velocidade de ondas em meios bidimensionais — a equação de dispersão frequentemente é biquadrada.",
    points: 1,
    options: [
      { id: "A", text: "y = x³" },
      { id: "B", text: "y = x" },
      { id: "C", text: "y = x + 2" },
      { id: "D", text: "y = x²" },
    ],
    correctAnswer: "D",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Resolva a equação x² − 7x + 10 = 0:",
    tip: "Use Bhaskara com a=1, b=−7, c=10. Δ = 49 − 40 = 9. x = (7 ± 3)/2.",
    funFact: "\"Você Sabia?\" — x² − 7x + 10 = 0 tem raízes 2 e 5. Verifique: 2 + 5 = 7 = −(−7)/1 ✓ e 2 × 5 = 10 = 10/1 ✓. As relações de Girard confirmam o resultado!",
    points: 1,
    options: [
      { id: "A", text: "x = 2 e x = 5" },
      { id: "B", text: "x = 1 e x = 10" },
      { id: "C", text: "x = −2 e x = −5" },
      { id: "D", text: "x = 7 e x = 10" },
    ],
    correctAnswer: "A",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Determine a natureza das raízes de x² + 2x + 5 = 0 sem resolver a equação:",
    tip: "Calcule Δ = 4 − 20 e interprete o sinal.",
    funFact: "\"Você Sabia?\" — Saber a natureza das raízes (sem calculá-las) é muito útil em problemas de otimização — se Δ < 0, a função quadrática não tem zeros reais e é sempre positiva ou sempre negativa.",
    points: 1,
    options: [
      { id: "A", text: "Duas raízes reais iguais (Δ = 0)." },
      { id: "B", text: "Nenhuma raiz real (Δ < 0)." },
      { id: "C", text: "Duas raízes reais distintas positivas." },
      { id: "D", text: "Duas raízes reais distintas, uma positiva e uma negativa." },
    ],
    correctAnswer: "B",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Uma bola é lançada para cima. Sua altura h (em metros) em função do tempo t (em segundos) é h = −5t² + 20t. Em que instante a bola atinge o solo novamente (h = 0, t > 0)?",
    tip: "Resolva −5t² + 20t = 0 para t > 0. Fatore: −5t(t − 4) = 0.",
    funFact: "\"Você Sabia?\" — O movimento de projéteis é regido por equações do 2º grau — é por isso que os gregos antigos conseguiram construir catapultas e balistas surpreendentemente precisas mesmo sem álgebra formal.",
    points: 1,
    options: [
      { id: "A", text: "t = 10 segundos" },
      { id: "B", text: "t = 5 segundos" },
      { id: "C", text: "t = 4 segundos" },
      { id: "D", text: "t = 20 segundos" },
    ],
    correctAnswer: "C",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Construa uma equação do 2º grau com raízes x₁ = 3 e x₂ = −5:",
    tip: "Use as relações de Girard: Soma = 3 + (−5) = −2 e Produto = 3 × (−5) = −15. A equação é x² − (soma)x + (produto) = 0.",
    funFact: "\"Você Sabia?\" — A capacidade de construir equações a partir de suas raízes é o inverso da resolução e é muito usada em controle automático — você define as 'raízes desejadas' (comportamento do sistema) e encontra a equação correspondente.",
    points: 1,
    options: [
      { id: "A", text: "x² + 2x + 15 = 0" },
      { id: "B", text: "x² − 2x + 15 = 0" },
      { id: "C", text: "x² − 3x + 5 = 0" },
      { id: "D", text: "x² + 2x − 15 = 0" },
    ],
    correctAnswer: "D",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Resolva a equação 4x² − 1 = 0:",
    tip: "Reconheça como diferença de quadrados: (2x)² − 1² = (2x + 1)(2x − 1) = 0.",
    funFact: "\"Você Sabia?\" — A equação 4x² − 1 = 0 pode ser resolvida em menos de 5 segundos por quem reconhece a diferença de quadrados. Bhaskara levaria mais tempo e daria o mesmo resultado.",
    points: 1,
    options: [
      { id: "A", text: "x = 1/2 ou x = −1/2" },
      { id: "B", text: "x = 1/4 ou x = −1/4" },
      { id: "C", text: "x = 2 ou x = −2" },
      { id: "D", text: "x = 1" },
    ],
    correctAnswer: "A",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Verifique se x = −1 é raiz da equação x² + 3x + 2 = 0:",
    tip: "Substitua x = −1 na equação e verifique se o resultado é zero.",
    funFact: "\"Você Sabia?\" — A verificação de raízes por substituição é o método mais simples e confiável para confirmar uma solução — é a primeira coisa que um matemático faz antes de publicar um resultado.",
    points: 1,
    options: [
      { id: "A", text: "Não, pois (−1)² + 3(−1) + 2 = 1 − 3 + 2 = 0 → espera, é zero!" },
      { id: "B", text: "Sim, pois (−1)² + 3(−1) + 2 = 1 − 3 + 2 = 0 ✓" },
      { id: "C", text: "Não, pois (−1)² + 3(−1) + 2 = 1 + 3 + 2 = 6 ≠ 0" },
      { id: "D", text: "Sim, mas apenas coincidência — não é raiz formal." },
    ],
    correctAnswer: "B",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Resolva x² + 2x − 15 = 0:",
    tip: "Use Bhaskara: a=1, b=2, c=−15. Calcule Δ = 4 + 60 = 64. x = (−2 ± 8)/2.",
    funFact: "\"Você Sabia?\" — As raízes 3 e −5 de x² + 2x − 15 = 0 têm soma 3 + (−5) = −2 = −b/a ✓ e produto 3 × (−5) = −15 = c/a ✓. Sempre verifique com Girard!",
    points: 1,
    options: [
      { id: "A", text: "x = 5 e x = 3" },
      { id: "B", text: "x = 5 e x = −3" },
      { id: "C", text: "x = 3 e x = −5" },
      { id: "D", text: "x = −3 e x = −5" },
    ],
    correctAnswer: "C",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Uma fazenda quadrada tem área de 225 m². Um agricultor quer aumentar cada lado em x metros para dobrar a área. Qual equação modela o problema?",
    tip: "O lado atual é 15 m (pois √225 = 15). A nova área deve ser 450 m². Nova equação: (15 + x)² = 450.",
    funFact: "\"Você Sabia?\" — Problemas de otimização de área com equações do 2º grau são a base do cálculo de projetos em engenharia civil, arquitetura paisagística e planejamento agrícola.",
    points: 1,
    options: [
      { id: "A", text: "x² + 225 = 450" },
      { id: "B", text: "15x = 450" },
      { id: "C", text: "225 + x² = 450" },
      { id: "D", text: "x² + 30x + 225 = 450" },
    ],
    correctAnswer: "D",
  },
];
