export const questoesBiologia1EmB2Av2 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "O tecido epitelial é um dos quatro tipos de tecido animal. Qual é a principal característica estrutural e função do tecido epitelial de revestimento?",
    tip: "O epitélio reveste superfícies: a pele é epitélio, o interior do intestino é epitélio. Pense em como essas células se organizam para cobrir superfícies.",
    funFact: "\"Você sabia?\" — A pele humana inteira é formada por tecido epitelial e é considerada o maior órgão do corpo. Ela se renova completamente a cada 2 a 4 semanas por mitose das células basais do epitélio.",
    points: 1,
    options: [
      { id: "A", text: "Células frouxamente organizadas com muito material intercelular, responsável pelo preenchimento e suporte dos órgãos." },
      { id: "B", text: "Células justapostas (muito próximas), com pouco material intercelular, que revestem superfícies internas e externas do corpo, protegendo contra agressões e regulando trocas." },
      { id: "C", text: "Células altamente especializadas na contração, com filamentos de actina e miosina." },
      { id: "D", text: "Células com longos prolongamentos que transmitem impulsos elétricos pelo corpo." },
    ],
    correctAnswer: "B",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "O tecido conjuntivo é o mais variado dos quatro tecidos fundamentais animais. Quais são os principais tipos de tecido conjuntivo?",
    tip: "O tecido conjuntivo tem muitos subtipos porque realiza funções muito diferentes: preencher, sustentar, transportar, defender... Pense nos tecidos que cumprem essas funções.",
    funFact: "\"Você sabia?\" — O sangue é classificado como tecido conjuntivo especializado porque suas células (hemácias, leucócitos, plaquetas) ficam suspensas no plasma, que funciona como a 'matriz extracelular líquida' desse tecido.",
    points: 1,
    options: [
      { id: "A", text: "Epitélio simples, pseudoestratificado e estratificado." },
      { id: "B", text: "Tecido muscular liso, estriado e cardíaco." },
      { id: "C", text: "Neurônios sensoriais, motores e de associação." },
      { id: "D", text: "Tecido conjuntivo frouxo, denso, adiposo, cartilaginoso, ósseo e sanguíneo." },
    ],
    correctAnswer: "D",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "O tecido epitelial glandular é especializado em secreção. Como as glândulas são classificadas de acordo com a forma de secreção?",
    tip: "Glândulas podem secretar diretamente para o sangue (sem ducto) ou por meio de ductos para superfícies. Essa é a base da classificação principal.",
    funFact: "\"Você sabia?\" — O pâncreas é uma glândula mista: possui porção exócrina (produz suco pancreático que vai ao intestino) e porção endócrina (produz insulina e glucagon que vão para o sangue).",
    points: 1,
    options: [
      { id: "A", text: "Glândulas exócrinas, que secretam por meio de ductos para superfícies ou cavidades, e glândulas endócrinas, que lançam secreções diretamente na corrente sanguínea." },
      { id: "B", text: "Glândulas superficiais e glândulas profundas, de acordo com a localização." },
      { id: "C", text: "Glândulas mononucleadas e polinucleadas, de acordo com o número de núcleos." },
      { id: "D", text: "Glândulas proteicas e lipídicas, de acordo com o tipo de substância secretada." },
    ],
    correctAnswer: "A",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "O tecido ósseo é um tipo de tecido conjuntivo especializado. Qual é a principal característica do tecido ósseo que o torna resistente?",
    tip: "O osso é rígido porque sua matriz extracelular é diferente dos outros tecidos conjuntivos. O que ela contém que dá essa rigidez?",
    funFact: "\"Você sabia?\" — O osso está em constante renovação: osteoblastos formam novo osso enquanto osteoclastos destroem osso velho. Esse equilíbrio é perturbado na osteoporose, onde a destruição supera a formação.",
    points: 1,
    options: [
      { id: "A", text: "Possui matriz gelatinosa rica em colágeno tipo II, sem mineralização, o que garante flexibilidade e resistência à compressão." },
      { id: "B", text: "É formado por células altamente contráteis com muitas mitocôndrias." },
      { id: "C", text: "Não possui matriz extracelular, sendo composto apenas por células densamente empacotadas." },
      { id: "D", text: "Possui matriz extracelular mineralizada com cristais de fosfato de cálcio (hidroxiapatita), que confere dureza e resistência ao tecido." },
    ],
    correctAnswer: "D",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "O tecido muscular é especializado em contração. Qual característica celular é responsável pela capacidade de contração do tecido muscular?",
    tip: "As células musculares são chamadas de fibras musculares. Elas são alongadas e possuem proteínas especiais que deslizam entre si para contrair.",
    funFact: "\"Você sabia?\" — A miosina, proteína do tecido muscular, é a proteína mais abundante do corpo humano. Um único filamento de miosina pode fazer 100 'passos' por segundo durante a contração muscular.",
    points: 1,
    options: [
      { id: "A", text: "Presença de muitos lisossomos para degradar proteínas durante o repouso." },
      { id: "B", text: "Presença de filamentos proteicos de actina e miosina organizados em sarcômeros, que interagem e deslizam entre si durante a contração." },
      { id: "C", text: "Abundância de ribossomos para síntese constante de glicose." },
      { id: "D", text: "Presença de centríolos que organizam os microtúbulos de contração." },
    ],
    correctAnswer: "B",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "O tecido nervoso é responsável pela recepção, processamento e transmissão de informações. Qual é a principal célula do tecido nervoso e qual é sua estrutura especializada?",
    tip: "A célula do tecido nervoso tem prolongamentos especializados para receber e enviar sinais elétricos. Como esses prolongamentos se chamam?",
    funFact: "\"Você sabia?\" — Um único neurônio pode receber até 10.000 conexões de outros neurônios. O cérebro humano tem cerca de 86 bilhões de neurônios e 100 trilhões de conexões (sinapses) entre eles.",
    points: 1,
    options: [
      { id: "A", text: "Fibroblasto, com prolongamentos que produzem fibras colágenas." },
      { id: "B", text: "Osteócito, com prolongamentos que se comunicam através dos canalículos ósseos." },
      { id: "C", text: "Macrófago, com prolongamentos que capturam patógenos por fagocitose." },
      { id: "D", text: "Neurônio, com dendrites (que recebem sinais) e axônio (que transmite o impulso nervoso para outras células)." },
    ],
    correctAnswer: "D",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "O tecido adiposo é um tipo de tecido conjuntivo. Qual é a principal função do tecido adiposo?",
    tip: "Tecido adiposo = tecido de gordura. Pense em todas as funções que a gordura tem no corpo: energética, de isolamento, de proteção mecânica...",
    funFact: "\"Você sabia?\" — O tecido adiposo branco armazena energia em forma de gordura, enquanto o tecido adiposo marrom (presente em bebês e em pequena quantidade em adultos) queima gordura para gerar calor.",
    points: 1,
    options: [
      { id: "A", text: "Transmissão de impulsos nervosos entre diferentes partes do corpo." },
      { id: "B", text: "Contração para produção de movimentos corporais." },
      { id: "C", text: "Armazenar energia em forma de lipídios, isolar termicamente o corpo, amortecer órgãos contra impactos e secretar hormônios (adipocinas como a leptina)." },
      { id: "D", text: "Revestir as superfícies externas do corpo contra a dessecação." },
    ],
    correctAnswer: "C",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "O tecido epitelial possui características gerais que o distinguem dos outros tecidos. Quais são essas características gerais?",
    tip: "O tecido epitelial tem células muito unidas, quase sem espaço entre elas. Ele reveste superfícies e não tem vasos sanguíneos próprios.",
    funFact: "\"Você sabia?\" — O epitélio não possui vasos sanguíneos (é avascular). Todos os nutrientes e o oxigênio chegam ao epitélio por difusão a partir do tecido conjuntivo subjacente.",
    points: 1,
    options: [
      { id: "A", text: "Células justapostas com pouco material intercelular, sem vasos sanguíneos (avascular), aderidas à lâmina basal, com alta capacidade de renovação por mitose." },
      { id: "B", text: "Células com grandes espaços entre si, ricas em fibras colágenas e elásticas, com abundante vascularização." },
      { id: "C", text: "Células multinucleadas, com estriações transversais e controle voluntário." },
      { id: "D", text: "Células com longos prolongamentos, ricas em mitocôndrias, sem capacidade de mitose." },
    ],
    correctAnswer: "A",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "O tecido cartilaginoso é um tipo de tecido conjuntivo especializado. O que torna a cartilagem flexível e resistente à pressão?",
    tip: "A cartilagem é firme mas não dura como o osso — você pode dobrar a orelha sem quebrar. O que há na matriz da cartilagem que permite essa característica?",
    funFact: "\"Você sabia?\" — A cartilagem não tem vasos sanguíneos nem nervos. Por isso, lesões na cartilagem articular (como no joelho) cicatrizam muito lentamente, pois o transporte de nutrientes é feito só por difusão.",
    points: 1,
    options: [
      { id: "A", text: "Sua matriz é mineralizada com hidroxiapatita, conferindo rigidez máxima." },
      { id: "B", text: "Sua matriz extracelular é rica em colágeno tipo II e proteoglicanos (que retêm água), conferindo flexibilidade e resistência à compressão." },
      { id: "C", text: "Suas células (condrócitos) possuem muitos filamentos de actina que contraem para absorver impactos." },
      { id: "D", text: "É altamente vascularizada, com sangue preenchendo os espaços entre os condrócitos." },
    ],
    correctAnswer: "B",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "O tecido muscular esquelético apresenta características microscópicas distintas. O que são as estriações transversais observadas no músculo esquelético?",
    tip: "Ao microscópio, o músculo esquelético mostra listras claras e escuras alternadas. Essas listras são geradas pela organização dos filamentos proteicos dentro das células.",
    funFact: "\"Você sabia?\" — O músculo esquelético é o único dos três tipos musculares sob controle voluntário. Quando você decide levantar o braço, seu cérebro envia um impulso nervoso que ativa as fibras musculares esqueléticas.",
    points: 1,
    options: [
      { id: "A", text: "São causadas pela presença de múltiplos núcleos alinhados nas bordas das fibras musculares." },
      { id: "B", text: "São artefatos do processo de coloração histológica, sem significado funcional." },
      { id: "C", text: "São causadas pelo acúmulo de mitocôndrias em regiões específicas das fibras." },
      { id: "D", text: "São resultantes da organização dos filamentos de actina e miosina em sarcômeros, que criam bandas claras (banda I e zona H) e escuras (banda A) alternadas." },
    ],
    correctAnswer: "D",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Os neurônios possuem estruturas especializadas para receber e transmitir impulsos nervosos. Como as partes do neurônio são denominadas e quais são suas funções?",
    tip: "O neurônio tem três partes principais: o corpo celular (com o núcleo), os prolongamentos que recebem sinais e o prolongamento que envia o sinal para outra célula.",
    funFact: "\"Você sabia?\" — O axônio mais longo do corpo humano vai da base da medula espinhal até os dedos dos pés — pode medir mais de 1 metro em pessoas altas, mas ainda é uma única célula (neurônio).",
    points: 1,
    options: [
      { id: "A", text: "Corpo celular (soma) com o núcleo; dendrites, que recebem sinais de outras células; axônio, que conduz o impulso para outras células." },
      { id: "B", text: "Cabeça, que contém enzimas; cauda, que gera força de contração; região do meio, que fornece energia." },
      { id: "C", text: "Membrana, citoplasma e núcleo, sem estruturas especializadas para condução de sinais." },
      { id: "D", text: "Fibras colágenas, fibras elásticas e células de suporte, sem capacidade de conduzir impulsos." },
    ],
    correctAnswer: "A",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "O tecido conjuntivo frouxo é o mais distribuído pelo corpo. Qual é a principal função do tecido conjuntivo frouxo?",
    tip: "O 'frouxo' tem fibras esparsas e muitas células. Ele está embaixo da pele e entre os órgãos. Para que serve essa distribuição tão ampla?",
    funFact: "\"Você sabia?\" — O tecido conjuntivo frouxo abriga muitos tipos de células imunológicas, como macrófagos e mastócitos. Quando ocorre uma infecção, essas células são as primeiras a agir na defesa local.",
    points: 1,
    options: [
      { id: "A", text: "Armazenar reservas de gordura para uso energético durante o jejum." },
      { id: "B", text: "Transmitir impulsos nervosos para os músculos esqueléticos." },
      { id: "C", text: "Preencher espaços entre órgãos, proporcionar suporte e nutrição a epitélios e tecidos, e abrigar células de defesa imunológica." },
      { id: "D", text: "Contrair para movimentar os órgãos internos durante a digestão." },
    ],
    correctAnswer: "C",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "O tecido muscular liso difere do músculo esquelético em características importantes. Quais são as principais características do tecido muscular liso?",
    tip: "O músculo liso reveste órgãos ocos como intestino, vasos sanguíneos e útero. Pense em como ele funciona: você controla conscientemente o seu intestino?",
    funFact: "\"Você sabia?\" — As contrações peristálticas que movem o alimento pelo intestino são realizadas pelo músculo liso do intestino. Esse processo ocorre automaticamente, sem qualquer esforço consciente.",
    points: 1,
    options: [
      { id: "A", text: "Apresenta estriações transversais, é multinucleado, possui controle voluntário e é encontrado nos músculos do esqueleto." },
      { id: "B", text: "Não apresenta estriações (liso), possui células fusiformes com núcleo central único, contração involuntária e é encontrado em órgãos como intestino, vasos e útero." },
      { id: "C", text: "Apresenta células ramificadas com discos intercalares, é involuntário e encontrado exclusivamente no coração." },
      { id: "D", text: "É altamente resistente à fadiga por possuir muitas mitocôndrias e mioglobina vermelha." },
    ],
    correctAnswer: "B",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "O tecido sanguíneo é um tipo de tecido conjuntivo especializado. Quais são os principais componentes celulares do sangue e suas funções?",
    tip: "O sangue tem células vermelhas (transporte de O₂), células brancas (defesa) e fragmentos celulares (coagulação), tudo suspenso em um líquido.",
    funFact: "\"Você sabia?\" — As hemácias humanas não têm núcleo quando maduras — o eliminam para ter mais espaço para hemoglobina. Com isso, não conseguem se dividir e vivem apenas 120 dias, sendo renovadas na medula óssea.",
    points: 1,
    options: [
      { id: "A", text: "Neurônios (transmissão elétrica), células de Schwann (mielinização) e células da glia (suporte)." },
      { id: "B", text: "Fibroblastos (colágeno), mastócitos (inflamação) e macrófagos (fagocitose), suspensos no plasma." },
      { id: "C", text: "Condrocitos (sustentação), osteoblastos (formação óssea) e osteoclastos (reabsorção), em matriz sólida." },
      { id: "D", text: "Hemácias (transporte de O₂), leucócitos (defesa imunológica) e plaquetas (coagulação), suspensos no plasma (matriz líquida)." },
    ],
    correctAnswer: "D",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "O epitélio pseudoestratificado é um tipo de epitélio que reveste certas vias respiratórias. Por que ele é chamado de 'pseudoestratificado'?",
    tip: "Pseudo = falso. Esse epitélio parece ter várias camadas, mas na verdade todas as células tocam a lâmina basal. Por que parece ter camadas então?",
    funFact: "\"Você sabia?\" — O epitélio pseudoestratificado ciliado das vias respiratórias produz muco que captura poeira e microorganismos. Os cílios batem continuamente para mover esse muco em direção à faringe — um processo chamado depuração mucociliar.",
    points: 1,
    options: [
      { id: "A", text: "É formado por células verdadeiramente em várias camadas, com as camadas internas sem contato com a lâmina basal." },
      { id: "B", text: "Parece estratificado porque os núcleos das células estão em alturas diferentes, criando aparência de camadas ao microscópio, mas todas as células tocam a lâmina basal." },
      { id: "C", text: "Possui apenas uma camada de células muito altas, como colunas, sem aparência estratificada." },
      { id: "D", text: "É chamado assim por ser composto por células de dois tipos diferentes que se alternam em camadas." },
    ],
    correctAnswer: "A",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "A sinapse é o local de comunicação entre neurônios ou entre neurônio e outra célula. Como ocorre a transmissão sináptica química?",
    tip: "Na sinapse química, não há contato físico direto. A informação é transmitida por moléculas químicas liberadas de um lado e captadas do outro.",
    funFact: "\"Você sabia?\" — A acetilcolina foi o primeiro neurotransmissor identificado, por Otto Loewi em 1921. Ele fez o experimento clássico: o líquido de um coração estimulado eletricamente, ao ser transferido para outro coração, o desacelerou.",
    points: 1,
    options: [
      { id: "A", text: "Os neurônios se fundem temporariamente na sinapse para trocar informação elétrica diretamente." },
      { id: "B", text: "O impulso elétrico pula diretamente do axônio pré-sináptico para o dendrite pós-sináptico sem intermediários." },
      { id: "C", text: "O neurônio pré-sináptico libera neurotransmissores na fenda sináptica; eles se ligam a receptores no neurônio pós-sináptico, gerando novo impulso elétrico." },
      { id: "D", text: "O neurônio pré-sináptico transfere DNA para o pós-sináptico como forma de comunicação." },
    ],
    correctAnswer: "C",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "O tecido conjuntivo denso é diferente do frouxo em termos de composição. Qual é a principal característica do tecido conjuntivo denso?",
    tip: "O tecido conjuntivo denso tem muito mais fibras que células. Pense onde ele é encontrado: tendões e ligamentos — estruturas que precisam suportar muita tensão.",
    funFact: "\"Você sabia?\" — Os tendões, compostos por tecido conjuntivo denso regular (fibras paralelas), são extraordinariamente resistentes. O tendão de Aquiles suporta uma força equivalente a 12 vezes o peso corporal durante uma corrida.",
    points: 1,
    options: [
      { id: "A", text: "Possui grande quantidade de células adiposas para armazenar energia." },
      { id: "B", text: "Possui grande quantidade de fibras colágenas densamente empacotadas, conferindo alta resistência mecânica; é encontrado em tendões, ligamentos e fáscias." },
      { id: "C", text: "É composto principalmente por células de defesa como macrófagos e neutrófilos." },
      { id: "D", text: "Possui matriz mineralizada com cálcio, sendo mais rígido que o tecido ósseo." },
    ],
    correctAnswer: "B",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "O músculo cardíaco é o terceiro tipo de tecido muscular. Quais são suas características que o distinguem dos outros dois tipos musculares?",
    tip: "O coração bate automaticamente, sem você precisar pensar nisso, e não cansa como os músculos dos braços. O que torna o músculo cardíaco diferente?",
    funFact: "\"Você sabia?\" — O músculo cardíaco possui discos intercalares com junções comunicantes (gap junctions), que permitem que o impulso elétrico se propague rapidamente por todo o coração, garantindo a contração sincronizada das câmaras.",
    points: 1,
    options: [
      { id: "A", text: "É estriado, voluntário e possui células mononucleadas sem conexões especiais." },
      { id: "B", text: "É liso, involuntário e possui células fusiformes com núcleo central." },
      { id: "C", text: "É liso, voluntário e possui células cilíndricas com múltiplos núcleos nas bordas." },
      { id: "D", text: "É estriado, involuntário, possui células ramificadas com discos intercalares (junções especializadas) e é exclusivo do coração." },
    ],
    correctAnswer: "D",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "As células de Schwann são células do tecido nervoso que envolvem os axônios. Qual é a função da bainha de mielina formada pelas células de Schwann?",
    tip: "A mielina é uma capa de gordura que envolve o axônio como a borracha de um fio elétrico. Pense no que acontece com a velocidade do impulso nervoso com essa cobertura.",
    funFact: "\"Você sabia?\" — Na esclerose múltipla, o sistema imune ataca a bainha de mielina dos neurônios do sistema nervoso central. Isso causa falhas na transmissão de impulsos, resultando em sintomas como fraqueza, dormência e problemas de visão.",
    points: 1,
    options: [
      { id: "A", text: "Produzir neurotransmissores para as sinapses ao longo do axônio." },
      { id: "B", text: "Nutrir o neurônio com glicose produzida pela fotossíntese." },
      { id: "C", text: "Fagocitar patógenos que tentam infectar o sistema nervoso." },
      { id: "D", text: "Aumentar a velocidade de condução do impulso nervoso por meio de condução saltatória entre os nós de Ranvier, isolando eletricamente o axônio." },
    ],
    correctAnswer: "A",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "O epitélio estratificado é composto por várias camadas de células. Onde ele é encontrado e qual é a vantagem funcional de ser estratificado?",
    tip: "O epitélio estratificado está onde há muito atrito e desgaste — como a pele e o interior da boca. Por que ter várias camadas é útil nesses locais?",
    funFact: "\"Você sabia?\" — O epitélio estratificado pavimentoso queratinizado da pele forma uma barreira impermeável que nos protege da desidratação. Sem essa barreira, perderíamos água continuamente e não poderíamos viver fora da água.",
    points: 1,
    options: [
      { id: "A", text: "É encontrado em regiões de trocas rápidas como alvéolos pulmonares; a estratificação aumenta a superfície de troca." },
      { id: "B", text: "É encontrado em glândulas endócrinas; a estratificação aumenta a quantidade de células secretoras." },
      { id: "C", text: "É encontrado em regiões sujeitas a atrito intenso (pele, esôfago, vagina); as várias camadas garantem que a descamação não exponha os tecidos profundos." },
      { id: "D", text: "É encontrado em vasos capilares; a estratificação reduz a permeabilidade para substâncias tóxicas." },
    ],
    correctAnswer: "C",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "As hemácias (eritrócitos) são as células mais abundantes do sangue. Qual é a principal característica estrutural das hemácias maduras e como isso se relaciona à sua função?",
    tip: "Hemácias maduras de mamíferos não têm núcleo. Por que isso seria uma vantagem para células que transportam oxigênio?",
    funFact: "\"Você sabia?\" — Uma hemácia transporta cerca de 250 milhões de moléculas de hemoglobina, e cada hemoglobina pode carregar até 4 moléculas de oxigênio. Uma única hemácia pode carregar 1 bilhão de moléculas de O₂.",
    points: 1,
    options: [
      { id: "A", text: "Possuem múltiplos núcleos para coordenar a síntese contínua de hemoglobina." },
      { id: "B", text: "São células cúbicas com grande vacúolo central para armazenar oxigênio dissolvido." },
      { id: "C", text: "São células esféricas e rígidas para resistir ao fluxo sanguíneo de alta pressão." },
      { id: "D", text: "São células anucleadas (sem núcleo) em forma de disco bicôncavo, o que maximiza a superfície para troca de gases e aumenta a flexibilidade para passar por capilares estreitos." },
    ],
    correctAnswer: "D",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "O tecido muscular esquelético e o liso apresentam diferenças importantes quanto ao controle nervoso. Como eles se diferenciam nesse aspecto?",
    tip: "Você consegue controlar conscientemente quando flexiona o bíceps? E quando seu estômago contrai para digerir o alimento? Esse controle diferente reflete o tipo de inervação.",
    funFact: "\"Você sabia?\" — A separação entre controle voluntário e involuntário dos músculos é essencial para a sobrevivência: não poderíamos nos concentrar em outras tarefas se tivéssemos que controlar conscientemente cada batimento cardíaco e cada peristaltismo.",
    points: 1,
    options: [
      { id: "A", text: "Ambos são controlados voluntariamente pelo sistema nervoso somático." },
      { id: "B", text: "O músculo esquelético é controlado voluntariamente pelo sistema nervoso somático; o músculo liso é controlado involuntariamente pelo sistema nervoso autônomo." },
      { id: "C", text: "O músculo liso é voluntário e o esquelético é involuntário." },
      { id: "D", text: "Ambos são involuntários, controlados pelo sistema nervoso autônomo." },
    ],
    correctAnswer: "B",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Os fibroblastos são as células mais comuns do tecido conjuntivo. Qual é a principal função dos fibroblastos?",
    tip: "O nome 'fibroblasto' já indica: fabrica fibras. Pense nos componentes da matriz extracelular do tecido conjuntivo que precisam ser produzidos.",
    funFact: "\"Você sabia?\" — Após uma lesão, os fibroblastos migram para o local e intensificam a produção de colágeno para formar tecido cicatricial. O excesso de colágeno pode formar queloides (cicatrizes elevadas) em pessoas geneticamente predispostas.",
    points: 1,
    options: [
      { id: "A", text: "Sintetizar e secretar as fibras colágenas e elásticas, além dos componentes da substância fundamental da matriz extracelular do tecido conjuntivo." },
      { id: "B", text: "Fagocitar patógenos e debris celulares no tecido conjuntivo." },
      { id: "C", text: "Liberar histamina e heparina durante reações alérgicas e inflamatórias." },
      { id: "D", text: "Conduzir impulsos nervosos entre os órgãos do tecido conjuntivo." },
    ],
    correctAnswer: "A",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Os neurotransmissores são moléculas fundamentais para a comunicação nervosa. Qual é o processo pelo qual eles agem na transmissão sináptica?",
    tip: "Os neurotransmissores são liberados pelo neurônio que envia o sinal e precisam ser reconhecidos pelo neurônio que recebe o sinal. Como esse reconhecimento ocorre?",
    funFact: "\"Você sabia?\" — Muitas drogas atuam alterando o funcionamento dos neurotransmissores. Antidepressivos como o Prozac aumentam a disponibilidade de serotonina na fenda sináptica, melhorando o humor.",
    points: 1,
    options: [
      { id: "A", text: "São injetados diretamente no citoplasma do neurônio pós-sináptico por proteínas de fusão de membrana." },
      { id: "B", text: "São liberados pelo neurônio pré-sináptico na fenda sináptica e se ligam a receptores específicos no neurônio pós-sináptico, desencadeando resposta elétrica ou química." },
      { id: "C", text: "São transportados pelo sangue até o neurônio-alvo, funcionando como hormônios neurais." },
      { id: "D", text: "São moléculas elétrica que saltam diretamente entre neurônios sem passar pela fenda sináptica." },
    ],
    correctAnswer: "C",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "A matriz extracelular (MEC) é um componente fundamental dos tecidos conjuntivos. O que é a MEC e de que ela é composta?",
    tip: "A MEC é o 'material entre as células' do tecido conjuntivo. Pense em colágeno, fibras elásticas e uma substância gelatinosa que preenche os espaços.",
    funFact: "\"Você sabia?\" — O colágeno é a proteína mais abundante no corpo humano, representando cerca de 30% de toda a proteína corporal. Existem pelo menos 28 tipos diferentes de colágeno com funções distintas nos diversos tecidos.",
    points: 1,
    options: [
      { id: "A", text: "É formada exclusivamente por água e sais minerais dissolvidos." },
      { id: "B", text: "É composta por neurônios e células gliais que formam uma rede de suporte." },
      { id: "C", text: "É formada por células musculares lisas que preenchem os espaços entre os órgãos." },
      { id: "D", text: "É um conjunto de macromoléculas secretadas pelas células (fibras colágenas, fibras elásticas, proteoglicanos e glicoproteínas) que formam um arcabouço de suporte para os tecidos." },
    ],
    correctAnswer: "D",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "As células do tecido epitelial se unem umas às outras por estruturas de adesão especializadas. Quais são os principais tipos de junções celulares no epitélio?",
    tip: "O epitélio precisa ser um revestimento coeso. As células se 'colam' entre si de várias formas: algumas firmemente, outras permitindo pequenas passagens.",
    funFact: "\"Você sabia?\" — O vírus da hepatite C e algumas bactérias entram no organismo 'enganando' as proteínas das junções oclusivas do epitélio intestinal. Ao se ligarem a essas proteínas, conseguem ultrapassar a barreira epitelial.",
    points: 1,
    options: [
      { id: "A", text: "Sinapses químicas e elétricas, que transmitem sinais entre células epiteliais." },
      { id: "B", text: "Junções oclusivas (vedação), desmossomos (adesão mecânica) e junções comunicantes (gap junctions, troca de moléculas entre células adjacentes)." },
      { id: "C", text: "Somente a lâmina basal, que ancora todas as células do epitélio ao tecido conjuntivo." },
      { id: "D", text: "Apenas fibras colágenas e elásticas que costuram as células epiteliais entre si." },
    ],
    correctAnswer: "B",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "As células da glia (células gliais) constituem grande parte do tecido nervoso. Qual é a principal função das células gliais?",
    tip: "Glia vem do grego e significa 'cola'. As células gliais são o suporte do sistema nervoso, mas suas funções vão muito além de simplesmente sustentar os neurônios.",
    funFact: "\"Você sabia?\" — As células gliais são mais numerosas que os neurônios — estima-se que para cada neurônio haja de 3 a 10 células gliais no cérebro. Longe de serem coadjuvantes, elas regulam ativamente a função sináptica.",
    points: 1,
    options: [
      { id: "A", text: "Proporcionar suporte estrutural e nutricional aos neurônios, formar a bainha de mielina, remover detritos, regular o microambiente iônico e modular a atividade sináptica." },
      { id: "B", text: "Transmitir impulsos nervosos em paralelo aos neurônios, aumentando a velocidade de condução." },
      { id: "C", text: "Produzir os neurotransmissores que serão utilizados pelos neurônios nas sinapses." },
      { id: "D", text: "Dividir-se por meiose para regenerar neurônios danificados após lesões." },
    ],
    correctAnswer: "A",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "O tecido ósseo possui células com funções antagônicas mas complementares. Quais são as funções dos osteoblastos e dos osteoclastos?",
    tip: "Os dois tipos celulares do osso trabalham em oposição: um constrói, o outro destrói. Esse equilíbrio é o que mantém os ossos saudáveis e permite sua remodelação.",
    funFact: "\"Você sabia?\" — Os osteoclastos são células gigantes multinucleadas derivadas de macrófagos. Eles secretam ácidos e enzimas que dissolvem a matriz óssea mineralizada, liberando cálcio na corrente sanguínea quando necessário.",
    points: 1,
    options: [
      { id: "A", text: "Osteoblastos sintetizam e secretam a matriz óssea (formação óssea), enquanto osteoclastos reabsorvem (destroem) a matriz óssea mineralizada, liberando cálcio." },
      { id: "B", text: "Osteoblastos destroem o tecido ósseo velho e osteoclastos constroem tecido novo." },
      { id: "C", text: "Ambos os tipos sintetizam colágeno, mas em quantidades diferentes dependendo da fase de crescimento." },
      { id: "D", text: "Osteoblastos produzem sangue na medula vermelha e osteoclastos armazenam gordura na medula amarela." },
    ],
    correctAnswer: "C",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "O tecido muscular cardíaco possui características únicas que permitem ao coração bater continuamente por décadas. Qual característica celular é responsável pela sincronização das contrações cardíacas?",
    tip: "Para o coração bombear o sangue eficientemente, todas as células musculares precisam contrair juntas. O que permite essa sincronia elétrica entre as células?",
    funFact: "\"Você sabia?\" — O coração humano bate em média 70 vezes por minuto, 100.000 vezes por dia, e cerca de 3 bilhões de vezes durante uma vida de 80 anos. Cada batimento é coordenado pelos discos intercalares que conectam as células cardíacas.",
    points: 1,
    options: [
      { id: "A", text: "A presença de fibras nervosas dentro de cada célula cardíaca que geram impulsos elétricos individuais." },
      { id: "B", text: "A contração simultânea de todos os filamentos de miosina por ativação química do cálcio." },
      { id: "C", text: "A liberação de hormônios pela glândula pituitária que sinalizam cada contração." },
      { id: "D", text: "Os discos intercalares, estruturas que conectam células cardíacas adjacentes e contêm junções comunicantes (gap junctions) que propagam rapidamente o impulso elétrico por todo o músculo cardíaco." },
    ],
    correctAnswer: "D",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "As fibras colágenas são os componentes mais abundantes do tecido conjuntivo. Qual é a principal característica e função das fibras colágenas?",
    tip: "Colágeno é a proteína mais abundante do corpo humano. As fibras colágenas são brancas, inextensíveis e muito resistentes à tração. Onde você esperaria encontrá-las?",
    funFact: "\"Você sabia?\" — O escorbuto, doença causada pela deficiência de vitamina C, resulta na produção deficiente de colágeno. Sem colágeno adequado, as gengivas sangram, os dentes caem e as feridas não cicatrizam — foi uma doença mortal de marinheiros por séculos.",
    points: 1,
    options: [
      { id: "A", text: "São elásticas e retornam ao comprimento original após serem esticadas, sendo encontradas em pele e vasos sanguíneos." },
      { id: "B", text: "São fibras proteicas resistentes à tração, compostas principalmente por colágeno, que conferem resistência mecânica ao tecido conjuntivo em tendões, ligamentos, pele e órgãos." },
      { id: "C", text: "São fibras lipídicas que formam a membrana de isolamento ao redor das células nervosas." },
      { id: "D", text: "São fibras de DNA condensado que organizam os cromossomos durante a divisão celular." },
    ],
    correctAnswer: "B",
  },
];
