export const questoesEducacaoFisica8AnoB1Av2 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'O atletismo é considerado o esporte mais antigo do mundo porque:',
    tip: 'Pensa nas primeiras Olimpíadas da história, na Grécia Antiga — corrida, salto e lançamento já existiam lá!',
    funFact: 'As primeiras Olimpíadas da Grécia Antiga aconteceram em 776 a.C., e o atletismo já era a principal atração!',
    points: 1,
    options: [
      { id: 'A', text: 'Foi inventado no século XX' },
      { id: 'B', text: 'Já era praticado há milhares de anos, inclusive nos Jogos Olímpicos da Grécia Antiga' },
      { id: 'C', text: 'Só começou a existir depois da Copa do Mundo' },
      { id: 'D', text: 'Foi criado só para competições de TV' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'Qual destas é uma prova de corrida do atletismo?',
    tip: 'Pensa na única opção que tem a ver com correr — as outras três são saltos ou lançamentos.',
    funFact: 'A corrida de 100 metros é considerada a prova mais rápida e emocionante do atletismo, durando poucos segundos!',
    points: 1,
    options: [
      { id: 'A', text: 'Salto em altura' },
      { id: 'B', text: 'Lançamento de dardo' },
      { id: 'C', text: 'Arremesso de peso' },
      { id: 'D', text: 'Corrida de 100 metros' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'Na natação, qual destes é um dos quatro estilos oficiais?',
    tip: 'Pensa num estilo em que os braços e as pernas se movem como um "sapinho" nadando.',
    funFact: 'Os quatro estilos oficiais da natação são: nado livre (crawl), nado de costas, nado peito e nado borboleta!',
    points: 1,
    options: [
      { id: 'A', text: 'Nado de peito' },
      { id: 'B', text: 'Nado de lado' },
      { id: 'C', text: 'Nado sentado' },
      { id: 'D', text: 'Nado parado' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'No tênis, como os jogadores rebatem a bola?',
    tip: 'Pensa no equipamento que o jogador segura com a mão, com uma rede esticada na ponta, para bater na bola.',
    funFact: 'As raquetes de tênis modernas são feitas de materiais bem leves, como carbono, para facilitar os movimentos rápidos!',
    points: 1,
    options: [
      { id: 'A', text: 'Com os pés' },
      { id: 'B', text: 'Com a cabeça' },
      { id: 'C', text: 'Com uma raquete' },
      { id: 'D', text: 'Com as mãos apenas' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'Qual destas é uma prova de salto do atletismo?',
    tip: 'Pensa na única opção que tem a ver com pular o mais longe possível — as outras são corrida, natação ou lançamento.',
    funFact: 'No salto em distância, o atleta corre, pula numa tábua marcada e tenta cair o mais longe possível na caixa de areia!',
    points: 1,
    options: [
      { id: 'A', text: 'Corrida de revezamento' },
      { id: 'B', text: 'Salto em distância' },
      { id: 'C', text: 'Nado livre' },
      { id: 'D', text: 'Arremesso de peso' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'Na natação, o que é o "nado livre" (ou crawl)?',
    tip: 'Pensa no estilo mais comum e rápido de natação, com uma braçada puxando a água de cada vez, alternando os braços.',
    funFact: 'O nado livre é o estilo mais rápido entre todos, por isso é usado na maioria das provas de longa distância!',
    points: 1,
    options: [
      { id: 'A', text: 'Um estilo rápido em que o nadador escolhe a técnica, geralmente usando braçadas alternadas' },
      { id: 'B', text: 'Um estilo em que é proibido usar os braços' },
      { id: 'C', text: 'Uma prova feita só de costas, parado' },
      { id: 'D', text: 'Um estilo que só pode ser feito em piscina funda' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'O que diferencia esportes individuais de esportes coletivos?',
    tip: 'Pensa na palavra "individual" — ela tem a ver com uma só pessoa competindo, diferente de um time.',
    funFact: 'Mesmo em esportes individuais, muitos atletas têm uma equipe de apoio nos bastidores: treinador, fisioterapeuta e nutricionista!',
    points: 1,
    options: [
      { id: 'A', text: 'Esportes individuais não têm regras' },
      { id: 'B', text: 'Esportes coletivos são sempre mais fáceis' },
      { id: 'C', text: 'Esportes individuais só existem em piscinas' },
      { id: 'D', text: 'Nos esportes individuais, o atleta compete sozinho, sem formar uma equipe em quadra' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'No tênis, quando um jogador vence o primeiro ponto de um game, o placar costuma ser contado em:',
    tip: 'O tênis tem uma forma bem diferente de contar pontos, usando palavras em inglês em vez de números simples.',
    funFact: '"Love" significa zero no placar do tênis, e ninguém sabe exatamente por que esse nome tão curioso foi escolhido!',
    points: 1,
    options: [
      { id: 'A', text: 'Pontos corridos (1, 2, 3, 4...)' },
      { id: 'B', text: 'Minutos' },
      { id: 'C', text: '"Love", 15, 30, 40 e game' },
      { id: 'D', text: 'Apenas "sim" ou "não"' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'Qual destas é uma prova de lançamento do atletismo?',
    tip: 'Pensa na única opção que tem a ver com jogar um objeto o mais longe possível — as outras são corrida, salto ou natação.',
    funFact: 'O dardo usado no atletismo pode ser lançado a mais de 90 metros de distância pelos melhores atletas do mundo!',
    points: 1,
    options: [
      { id: 'A', text: 'Corrida com barreiras' },
      { id: 'B', text: 'Lançamento de dardo' },
      { id: 'C', text: 'Salto em altura' },
      { id: 'D', text: 'Nado borboleta' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'Qual destes esportes é praticado dentro da água?',
    tip: 'Pensa no único esporte da lista que precisa de uma piscina ou de água para ser praticado.',
    funFact: 'A natação é um dos esportes mais completos, pois trabalha praticamente todos os músculos do corpo!',
    points: 1,
    options: [
      { id: 'A', text: 'Natação' },
      { id: 'B', text: 'Tênis' },
      { id: 'C', text: 'Atletismo' },
      { id: 'D', text: 'Vôlei' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'Por que o atletismo é chamado de "esporte-base" ou "esporte mãe"?',
    tip: 'Pensa: correr, saltar e lançar são movimentos usados em quase todos os esportes, não só no atletismo.',
    funFact: 'Muitos treinadores de outros esportes usam exercícios de atletismo para melhorar a velocidade e a força de seus atletas!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque só pode ser praticado por adultos' },
      { id: 'B', text: 'Porque não tem nenhuma prova de corrida' },
      { id: 'C', text: 'Porque reúne habilidades básicas (correr, saltar, lançar) usadas em muitos outros esportes' },
      { id: 'D', text: 'Porque foi inventado depois de todos os outros esportes' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'Na natação, qual estilo é nadado de costas, com braçadas alternadas para cima e para trás?',
    tip: 'O próprio nome do estilo já dá a resposta — pensa na posição do corpo do nadador na água.',
    funFact: 'No nado de costas, a largada é diferente dos outros estilos: o nadador começa dentro da água, agarrado à borda da piscina!',
    points: 1,
    options: [
      { id: 'A', text: 'Nado peito' },
      { id: 'B', text: 'Nado borboleta' },
      { id: 'C', text: 'Nado livre' },
      { id: 'D', text: 'Nado de costas' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'No tênis, o que acontece se a bola bater duas vezes no chão antes de ser rebatida pelo adversário?',
    tip: 'Pensa: o jogador tem só uma chance de rebater a bola depois que ela toca o chão uma vez. E se ela quicar de novo?',
    funFact: 'Essa regra é chamada de "quique duplo" e é um dos erros mais comuns entre jogadores iniciantes de tênis!',
    points: 1,
    options: [
      { id: 'A', text: 'O ponto é repetido' },
      { id: 'B', text: 'O ponto é perdido por quem deveria ter rebatido' },
      { id: 'C', text: 'O jogo é cancelado' },
      { id: 'D', text: 'Nada, o jogo continua normalmente' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'Qual destas provas de atletismo exige que o atleta ultrapasse obstáculos durante a corrida?',
    tip: 'Pensa no nome da prova — "barreiras" são obstáculos que o atleta precisa saltar enquanto corre.',
    funFact: 'As barreiras usadas nessa prova são feitas para cair com facilidade, caso o atleta bata nelas, evitando acidentes graves!',
    points: 1,
    options: [
      { id: 'A', text: 'Corrida com barreiras' },
      { id: 'B', text: 'Corrida de revezamento' },
      { id: 'C', text: 'Salto em distância' },
      { id: 'D', text: 'Lançamento de martelo' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'O nado borboleta é conhecido por ser:',
    tip: 'Pensa no nome do estilo — os braços se movem parecido com as asas de uma borboleta, os dois juntos.',
    funFact: 'O nado borboleta foi o último dos quatro estilos oficiais a ser criado, só no início do século XX!',
    points: 1,
    options: [
      { id: 'A', text: 'O estilo mais lento e fácil de aprender' },
      { id: 'B', text: 'Proibido em competições oficiais' },
      { id: 'C', text: 'Um dos estilos mais difíceis, com movimento simultâneo dos braços por cima da água' },
      { id: 'D', text: 'Feito sempre sem usar as pernas' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'No tênis, o que é um "saque"?',
    tip: 'Esse termo também apareceu no vôlei, lembra? No tênis tem o mesmo significado: começar a jogada.',
    funFact: 'Alguns saques de tênis profissional podem passar de 200 km/h, mais rápido que muitos carros na estrada!',
    points: 1,
    options: [
      { id: 'A', text: 'Quando o jogador desiste da partida' },
      { id: 'B', text: 'O golpe que inicia cada ponto, feito por um dos jogadores' },
      { id: 'C', text: 'Quando a bola sai da quadra' },
      { id: 'D', text: 'O momento em que o árbitro troca de cadeira' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'Na corrida de revezamento do atletismo, o que os atletas de uma mesma equipe precisam fazer?',
    tip: 'Pensa num objeto pequeno que passa de mão em mão entre os corredores de um mesmo time, sem cair no chão.',
    funFact: 'Se o bastão cair no chão durante a troca, a equipe pode ser desclassificada da prova!',
    points: 1,
    options: [
      { id: 'A', text: 'Correr sozinhos, sem contato com os colegas' },
      { id: 'B', text: 'Nadar juntos na mesma raia' },
      { id: 'C', text: 'Pular ao mesmo tempo' },
      { id: 'D', text: 'Passar um bastão de um corredor para o outro, dentro de uma zona marcada' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'O que é preciso ter cuidado antes de qualquer atividade física intensa, como uma corrida de atletismo?',
    tip: 'Pensa no que os atletas fazem antes de qualquer prova, para preparar os músculos e evitar se machucar.',
    funFact: 'Um bom aquecimento aumenta a temperatura dos músculos e melhora o desempenho do atleta na prova!',
    points: 1,
    options: [
      { id: 'A', text: 'Fazer um aquecimento adequado do corpo' },
      { id: 'B', text: 'Comer uma refeição muito pesada' },
      { id: 'C', text: 'Usar roupas bem apertadas' },
      { id: 'D', text: 'Correr o mais rápido possível desde o início, sem preparo' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'Qual destas é uma característica do nado peito?',
    tip: 'Lembra da Questão 3 desta prova? Esse estilo tem um movimento bem parecido com o de um sapo nadando.',
    funFact: 'O nado peito é considerado o estilo mais antigo da natação, praticado desde a época dos egípcios!',
    points: 1,
    options: [
      { id: 'A', text: 'É nadado só de costas' },
      { id: 'B', text: 'É o estilo mais rápido de todos' },
      { id: 'C', text: 'As braçadas e pernadas são feitas de forma simétrica, como um "sapinho"' },
      { id: 'D', text: 'É proibido em qualquer competição' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'No tênis, quantos sets costuma ter uma partida masculina em torneios importantes como Grand Slams?',
    tip: 'Pensa: as partidas de Grand Slam masculinas costumam ser bem longas, podendo durar várias horas.',
    funFact: 'A partida mais longa da história do tênis durou mais de 11 horas, entre John Isner e Nicolas Mahut, em Wimbledon 2010!',
    points: 1,
    options: [
      { id: 'A', text: 'Sempre 1' },
      { id: 'B', text: 'Sempre 2' },
      { id: 'C', text: 'Sempre 10' },
      { id: 'D', text: 'Até 5 (o jogador que vence 3 sets primeiro, ganha a partida)' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Bernardo participou de uma corrida de 100 metros na escola. Essa prova pertence a qual esporte?',
    tip: 'Lembra da Questão 2 desta prova? É a mesma prova de corrida que apareceu ali.',
    funFact: 'O recorde mundial dos 100 metros é de Usain Bolt, com um tempo de 9,58 segundos!',
    points: 1,
    options: [
      { id: 'A', text: 'Atletismo' },
      { id: 'B', text: 'Natação' },
      { id: 'C', text: 'Tênis' },
      { id: 'D', text: 'Handebol' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Na aula de natação, Bernardo aprendeu um estilo em que nada de costas, com braçadas alternadas para cima. Qual é esse estilo?',
    tip: 'É o mesmo estilo da Questão 12 desta prova — pensa na posição do corpo do nadador na água.',
    funFact: 'No nado de costas, o nadador sempre fica de olho no teto ou no céu, já que não pode ver para onde está indo de frente!',
    points: 1,
    options: [
      { id: 'A', text: 'Nado peito' },
      { id: 'B', text: 'Nado de costas' },
      { id: 'C', text: 'Nado borboleta' },
      { id: 'D', text: 'Nado sentado' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Bernardo jogou tênis com o pai no fim de semana e usou um equipamento para rebater a bola. Qual é esse equipamento?',
    tip: 'É o mesmo equipamento da Questão 4 desta prova — pensa em algo com uma rede esticada numa das pontas.',
    funFact: 'As primeiras raquetes de tênis, no século XIX, eram feitas de madeira, bem mais pesadas que as atuais!',
    points: 1,
    options: [
      { id: 'A', text: 'Uma luva' },
      { id: 'B', text: 'Um taco' },
      { id: 'C', text: 'Uma raquete' },
      { id: 'D', text: 'Um bastão' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Bernardo participou de uma prova de salto na Olimpíada da escola, tentando pular o mais longe possível. Essa prova se chama:',
    tip: 'É a mesma prova da Questão 5 desta prova — pensa em correr e depois pular numa caixa de areia.',
    funFact: 'O salto em distância é uma das provas mais antigas dos Jogos Olímpicos modernos, desde 1896!',
    points: 1,
    options: [
      { id: 'A', text: 'Lançamento de dardo' },
      { id: 'B', text: 'Corrida com barreiras' },
      { id: 'C', text: 'Nado livre' },
      { id: 'D', text: 'Salto em distância' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Bernardo fez um bom aquecimento antes de correr na aula de Educação Física. Por que isso é importante?',
    tip: 'Lembra da Questão 18 desta prova? O aquecimento prepara os músculos para o esforço que vem depois.',
    funFact: 'Alongamentos e corridas leves são formas comuns de aquecimento antes de qualquer atividade física mais intensa!',
    points: 1,
    options: [
      { id: 'A', text: 'Para preparar o corpo e evitar lesões antes do esforço físico' },
      { id: 'B', text: 'Porque é obrigatório por lei' },
      { id: 'C', text: 'Porque deixa o atleta mais cansado' },
      { id: 'D', text: 'Porque não tem nenhuma função' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Bernardo observou que, na natação, existe um estilo considerado um dos mais difíceis, com os dois braços se movendo juntos por cima da água. Qual é esse estilo?',
    tip: 'É o mesmo estilo da Questão 15 desta prova — pensa no nome que lembra um inseto com asas bonitas.',
    funFact: 'O nado borboleta exige muita força na parte de cima do corpo, por isso é considerado o mais cansativo entre os quatro estilos!',
    points: 1,
    options: [
      { id: 'A', text: 'Nado peito' },
      { id: 'B', text: 'Nado de costas' },
      { id: 'C', text: 'Nado borboleta' },
      { id: 'D', text: 'Nado livre' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'No jogo de tênis, Bernardo contou os pontos e disse "15 a 0". Essa forma de contar pontos é característica de qual esporte?',
    tip: 'Lembra da Questão 8 desta prova? É o mesmo esporte que conta pontos de um jeito bem diferente dos outros.',
    funFact: 'Depois de "40", se o jogo empata, chama-se "deuce" (igualdade), e é preciso vencer dois pontos seguidos para fechar o game!',
    points: 1,
    options: [
      { id: 'A', text: 'Atletismo' },
      { id: 'B', text: 'Tênis' },
      { id: 'C', text: 'Natação' },
      { id: 'D', text: 'Vôlei' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Na corrida de revezamento da escola, Bernardo precisou passar um objeto para o próximo colega da equipe. Que objeto é esse?',
    tip: 'É o mesmo objeto da Questão 17 desta prova — pensa num item pequeno que não pode cair no chão durante a troca.',
    funFact: 'A troca do bastão precisa acontecer dentro de uma zona marcada na pista, chamada "zona de transferência"!',
    points: 1,
    options: [
      { id: 'A', text: 'Uma bola' },
      { id: 'B', text: 'Uma raquete' },
      { id: 'C', text: 'Um aro' },
      { id: 'D', text: 'Um bastão' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Bernardo aprendeu que o atletismo reúne corrida, salto e lançamento, sendo considerado a base de muitos esportes. Por isso ele é chamado de:',
    tip: 'É o mesmo nome que você viu na Questão 11 desta prova — pensa em quem "dá origem" a outros esportes.',
    funFact: 'Muitas habilidades do atletismo, como correr e saltar, são a base de esportes como futebol, basquete e vôlei!',
    points: 1,
    options: [
      { id: 'A', text: 'Esporte-base (ou esporte mãe)' },
      { id: 'B', text: 'Esporte proibido' },
      { id: 'C', text: 'Esporte coletivo' },
      { id: 'D', text: 'Esporte só de inverno' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'No fim da aula, o professor perguntou a Bernardo: qual a principal diferença entre esportes individuais e esportes coletivos? Bernardo respondeu corretamente:',
    tip: 'Lembra da Questão 7 desta prova? A resposta certa é sobre quem compete sozinho e quem compete em time.',
    funFact: 'Tanto esportes individuais quanto coletivos ajudam a desenvolver disciplina, foco e saúde — cada um com seu próprio charme!',
    points: 1,
    options: [
      { id: 'A', text: 'Esportes individuais não têm regras' },
      { id: 'B', text: 'Nos esportes individuais, o atleta compete sozinho; nos coletivos, em equipe' },
      { id: 'C', text: 'Esportes coletivos só acontecem na água' },
      { id: 'D', text: 'Não existe diferença nenhuma' },
    ],
    correctAnswer: 'B',
  },
];
