export const questoesArte8AnoB1Av1 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'Em que século surgiu o estilo artístico conhecido como Barroco?',
    tip: 'Pense num período logo depois do Renascimento, já na época das grandes igrejas europeias!',
    funFact: 'O Barroco surgiu principalmente ligado à Igreja Católica, num momento de forte disputa religiosa na Europa!',
    points: 1,
    options: [
      { id: 'A', text: 'Século XV' },
      { id: 'B', text: 'Século XVII' },
      { id: 'C', text: 'Século XIX' },
      { id: 'D', text: 'Século XX' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'Qual é uma das principais características da arte Barroca?',
    tip: 'Pense em pinturas com um efeito bem teatral, quase como um holofote iluminando partes da cena!',
    funFact: 'Essa técnica de contraste entre luz e sombra é chamada de "claro-escuro" e dava muita emoção às obras barrocas!',
    points: 1,
    options: [
      { id: 'A', text: 'Cores simples e sem contraste' },
      { id: 'B', text: 'Formas geométricas abstratas' },
      { id: 'C', text: 'Ausência total de detalhes' },
      { id: 'D', text: 'Uso dramático de luz e sombra (claro-escuro)' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'Quem foi o famoso escultor brasileiro do período barroco, conhecido por suas obras em igrejas de Minas Gerais?',
    tip: 'Esse artista mineiro é famoso por suas esculturas e talhas em igrejas de Ouro Preto!',
    funFact: 'Aleijadinho é considerado um dos maiores artistas do Barroco no mundo, mesmo enfrentando grandes dificuldades de saúde!',
    points: 1,
    options: [
      { id: 'A', text: 'Aleijadinho' },
      { id: 'B', text: 'Victor Meirelles' },
      { id: 'C', text: 'Tarsila do Amaral' },
      { id: 'D', text: 'Di Cavalcanti' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'Qual religião teve forte influência na criação da arte Barroca?',
    tip: 'Pense na instituição religiosa que usava a arte para impressionar e emocionar os fiéis nas igrejas!',
    funFact: 'A Igreja Católica usava o Barroco como forma de reforçar sua presença durante a Contrarreforma!',
    points: 1,
    options: [
      { id: 'A', text: 'Budismo' },
      { id: 'B', text: 'Islamismo' },
      { id: 'C', text: 'Igreja Católica' },
      { id: 'D', text: 'Judaísmo' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'Qual é um tema comum nas pinturas e esculturas barrocas?',
    tip: 'Pense em obras feitas para igrejas, contando histórias sagradas!',
    funFact: 'Muitas obras barrocas retratavam santos, anjos e passagens da Bíblia de forma bem dramática!',
    points: 1,
    options: [
      { id: 'A', text: 'Paisagens urbanas modernas' },
      { id: 'B', text: 'Temas religiosos e bíblicos' },
      { id: 'C', text: 'Retratos de celebridades atuais' },
      { id: 'D', text: 'Cenas de ficção científica' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'Qual material era muito usado nas igrejas barrocas brasileiras, especialmente em Minas Gerais?',
    tip: 'Pense num metal precioso usado para decorar altares e interiores de igrejas de forma luxuosa!',
    funFact: 'A riqueza do ouro extraído em Minas Gerais ajudou a financiar a decoração suntuosa das igrejas barrocas da região!',
    points: 1,
    options: [
      { id: 'A', text: 'Vidro colorido' },
      { id: 'B', text: 'Plástico' },
      { id: 'C', text: 'Concreto armado' },
      { id: 'D', text: 'Ouro (talha dourada)' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'Qual cidade brasileira é famosa por suas igrejas e esculturas barrocas, muitas delas feitas por Aleijadinho?',
    tip: 'Pense numa cidade histórica de Minas Gerais, famosa pelo ciclo do ouro e por suas igrejas barrocas!',
    funFact: 'Ouro Preto é Patrimônio Mundial da UNESCO, justamente por preservar essa riqueza arquitetônica barroca!',
    points: 1,
    options: [
      { id: 'A', text: 'Rio de Janeiro' },
      { id: 'B', text: 'Salvador' },
      { id: 'C', text: 'Ouro Preto' },
      { id: 'D', text: 'Brasília' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'Qual é uma característica geral das obras barrocas em relação ao movimento e à emoção?',
    tip: 'Pense em esculturas e pinturas que parecem "vivas", cheias de energia e sentimento!',
    funFact: 'Essa intensidade emocional é uma das marcas mais importantes da arte Barroca!',
    points: 1,
    options: [
      { id: 'A', text: 'Elas tentam transmitir muito movimento e emoção intensa' },
      { id: 'B', text: 'Elas são sempre estáticas e sem expressão' },
      { id: 'C', text: 'Elas evitam qualquer tipo de emoção' },
      { id: 'D', text: 'Elas são feitas só com formas simples' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'Qual famoso compositor é associado à música do período Barroco?',
    tip: 'Pense num compositor alemão muito importante, conhecido por suas complexas composições corais e para órgão!',
    funFact: 'A música Barroca, assim como as artes visuais da época, também valorizava a complexidade e a emoção!',
    points: 1,
    options: [
      { id: 'A', text: 'Beethoven' },
      { id: 'B', text: 'Johann Sebastian Bach' },
      { id: 'C', text: 'Villa-Lobos' },
      { id: 'D', text: 'Mozart' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'Qual estilo artístico veio antes do Barroco, servindo de base para seu desenvolvimento?',
    tip: 'Pense num movimento artístico anterior, muito valorizado pela harmonia e pela proporção, que depois foi ampliado pelo exagero barroco!',
    funFact: 'Enquanto o Renascimento valorizava o equilíbrio, o Barroco trouxe mais drama, movimento e emoção às obras!',
    points: 1,
    options: [
      { id: 'A', text: 'Modernismo' },
      { id: 'B', text: 'Impressionismo' },
      { id: 'C', text: 'Cubismo' },
      { id: 'D', text: 'Renascimento' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'Por que a Igreja Católica incentivou a produção de arte Barroca?',
    tip: 'Pense num momento de disputa religiosa na Europa, em que a Igreja queria reforçar sua presença e emocionar o povo!',
    funFact: 'Esse período é chamado de Contrarreforma, uma resposta católica ao avanço do protestantismo!',
    points: 1,
    options: [
      { id: 'A', text: 'Para impressionar e emocionar os fiéis durante a Contrarreforma' },
      { id: 'B', text: 'Para proibir qualquer tipo de decoração nas igrejas' },
      { id: 'C', text: 'Para tornar as igrejas mais simples e vazias' },
      { id: 'D', text: 'Porque não tinha nenhum interesse na arte' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'Qual foi a importância de Aleijadinho para a arte brasileira?',
    tip: 'Pense num artista que, apesar de enfrentar sérios problemas de saúde, criou obras incríveis em igrejas mineiras!',
    funFact: 'Seu talento era tão grande que suas obras são admiradas até hoje em todo o mundo!',
    points: 1,
    options: [
      { id: 'A', text: 'Ele foi o primeiro a pintar paisagens urbanas no Brasil' },
      { id: 'B', text: 'Ele introduziu o Modernismo no Brasil' },
      { id: 'C', text: 'Ele é considerado um dos maiores escultores do Barroco mundial, mesmo enfrentando grandes desafios de saúde' },
      { id: 'D', text: 'Ele não teve nenhuma importância histórica' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'Qual é o efeito do uso do "claro-escuro" nas obras barrocas?',
    tip: 'Pense num efeito teatral, como um holofote de teatro iluminando partes específicas de uma cena!',
    funFact: 'Esse contraste forte ajudava a destacar os personagens e criar mais emoção na obra!',
    points: 1,
    options: [
      { id: 'A', text: 'Tornar a obra toda na mesma cor' },
      { id: 'B', text: 'Criar um forte contraste dramático entre luz e sombra' },
      { id: 'C', text: 'Esconder completamente os detalhes da pintura' },
      { id: 'D', text: 'Deixar a obra sem nenhum brilho' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'Por que as igrejas barrocas de Minas Gerais eram decoradas com tanto ouro?',
    tip: 'Pense na economia da região de Minas Gerais na época: havia muita extração de ouro!',
    funFact: 'Essa riqueza mineira ajudou a criar algumas das igrejas mais ricamente decoradas do Brasil!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque o ouro era muito barato na época' },
      { id: 'B', text: 'Porque não existia outro material disponível' },
      { id: 'C', text: 'Porque era proibido usar outros materiais' },
      { id: 'D', text: 'Porque a riqueza do ciclo do ouro permitia financiar decorações luxuosas' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'Qual é uma diferença entre o Renascimento e o Barroco?',
    tip: 'Pense em como as obras do Barroco parecem mais "agitadas" e emocionais do que as do Renascimento!',
    funFact: 'O Barroco pode ser visto como uma evolução mais dramática das técnicas renascentistas!',
    points: 1,
    options: [
      { id: 'A', text: 'O Renascimento valorizava o equilíbrio, enquanto o Barroco trouxe mais drama e movimento' },
      { id: 'B', text: 'O Renascimento era mais dramático que o Barroco' },
      { id: 'C', text: 'Os dois estilos são exatamente iguais' },
      { id: 'D', text: 'O Barroco não teve nenhuma relação com o Renascimento' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'Qual é a importância histórica de Ouro Preto para o estudo da arte Barroca no Brasil?',
    tip: 'Pense numa cidade histórica preservada, famosa por seu patrimônio artístico e arquitetônico!',
    funFact: 'Ouro Preto é Patrimônio Mundial da UNESCO desde 1980!',
    points: 1,
    options: [
      { id: 'A', text: 'A cidade não tem nenhuma relevância artística' },
      { id: 'B', text: 'Ela é famosa apenas por sua arquitetura moderna' },
      { id: 'C', text: 'Ela preserva um rico conjunto de igrejas e esculturas barrocas, reconhecido pela UNESCO' },
      { id: 'D', text: 'Ela foi construída só no século XX' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'Como a música barroca se relaciona com as outras artes do período?',
    tip: 'Pense em como todas as artes do período Barroco buscavam causar forte impacto emocional!',
    funFact: 'Compositores como Bach criavam obras musicais tão complexas e emocionantes quanto as pinturas e esculturas da época!',
    points: 1,
    options: [
      { id: 'A', text: 'Ela era completamente diferente, sem nenhuma relação' },
      { id: 'B', text: 'Ela evitava qualquer tipo de complexidade' },
      { id: 'C', text: 'Ela era simples e sem emoção' },
      { id: 'D', text: 'Ela também valorizava a complexidade e a emoção intensa, como as artes visuais' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'Qual é uma característica comum entre as esculturas de Aleijadinho e as pinturas barrocas europeias?',
    tip: 'Pense na emoção intensa presente tanto nas esculturas mineiras quanto nas pinturas europeias do período!',
    funFact: 'Essa busca por emoção é uma marca registrada de todo o movimento Barroco, onde quer que ele tenha acontecido!',
    points: 1,
    options: [
      { id: 'A', text: 'Ambas evitam temas religiosos' },
      { id: 'B', text: 'Ambas buscam transmitir forte emoção e movimento' },
      { id: 'C', text: 'Ambas são extremamente simples' },
      { id: 'D', text: 'Ambas não têm nenhuma relação com a Igreja' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'Por que o Barroco é considerado um estilo artístico muito expressivo?',
    tip: 'Pense em como as obras barrocas tentam "tocar" o espectador emocionalmente, não só mostrar uma cena!',
    funFact: 'Essa busca por expressividade ajudou o Barroco a se tornar um dos estilos mais marcantes da história da arte!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque buscava emocionar o espectador através do movimento, da luz e do drama' },
      { id: 'B', text: 'Porque usava apenas formas geométricas simples' },
      { id: 'C', text: 'Porque evitava qualquer tipo de expressão' },
      { id: 'D', text: 'Porque era feito apenas em preto e branco' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'Qual é a importância de se estudar o Barroco para entender a história da arte no Brasil?',
    tip: 'Pense nas igrejas e esculturas barrocas que ainda existem em cidades históricas brasileiras!',
    funFact: 'Esse legado barroco brasileiro é admirado e estudado no mundo inteiro até hoje!',
    points: 1,
    options: [
      { id: 'A', text: 'O Barroco não teve nenhuma influência no Brasil' },
      { id: 'B', text: 'O Barroco só existiu na Europa' },
      { id: 'C', text: 'O Barroco deixou um importante legado artístico, especialmente em Minas Gerais' },
      { id: 'D', text: 'O Barroco só é estudado fora do Brasil' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Bernardo está estudando sobre o Barroco. Em que século esse estilo artístico surgiu?',
    tip: 'Pense num período logo depois do Renascimento, já na época das grandes igrejas europeias!',
    funFact: 'O Barroco surgiu ligado principalmente à Igreja Católica!',
    points: 1,
    options: [
      { id: 'A', text: 'Século XV' },
      { id: 'B', text: 'Século XIX' },
      { id: 'C', text: 'Século XX' },
      { id: 'D', text: 'Século XVII' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Bernardo quer saber quem foi o famoso escultor brasileiro do Barroco, conhecido por suas obras em Minas Gerais. Quem foi ele?',
    tip: 'Esse artista mineiro é famoso por suas esculturas e talhas em igrejas de Ouro Preto!',
    funFact: 'Aleijadinho é considerado um dos maiores artistas do Barroco no mundo!',
    points: 1,
    options: [
      { id: 'A', text: 'Aleijadinho' },
      { id: 'B', text: 'Tarsila do Amaral' },
      { id: 'C', text: 'Victor Meirelles' },
      { id: 'D', text: 'Di Cavalcanti' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Bernardo descobriu uma técnica muito usada nas pinturas barrocas, com forte contraste entre luz e sombra. Como ela é chamada?',
    tip: 'Pense num efeito teatral, com partes bem iluminadas e outras na sombra!',
    funFact: 'Esse contraste forte ajudava a criar muita emoção nas obras barrocas!',
    points: 1,
    options: [
      { id: 'A', text: 'Pontilhismo' },
      { id: 'B', text: 'Claro-escuro' },
      { id: 'C', text: 'Colagem' },
      { id: 'D', text: 'Aquarela' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Bernardo quer saber qual religião teve forte influência na criação da arte Barroca. Qual foi ela?',
    tip: 'Pense na instituição religiosa que usava a arte para impressionar e emocionar os fiéis!',
    funFact: 'A Igreja Católica usava o Barroco durante um período chamado Contrarreforma!',
    points: 1,
    options: [
      { id: 'A', text: 'Budismo' },
      { id: 'B', text: 'Islamismo' },
      { id: 'C', text: 'Igreja Católica' },
      { id: 'D', text: 'Judaísmo' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Bernardo quer saber qual material era muito usado nas igrejas barrocas de Minas Gerais. Qual foi esse material?',
    tip: 'Pense num metal precioso usado para decorar altares de forma luxuosa!',
    funFact: 'A riqueza do ciclo do ouro ajudou a financiar essa decoração suntuosa!',
    points: 1,
    options: [
      { id: 'A', text: 'Vidro colorido' },
      { id: 'B', text: 'Plástico' },
      { id: 'C', text: 'Concreto armado' },
      { id: 'D', text: 'Ouro (talha dourada)' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Bernardo quer saber qual cidade brasileira é famosa por suas igrejas e esculturas barrocas. Qual é essa cidade?',
    tip: 'Pense numa cidade histórica de Minas Gerais, famosa pelo ciclo do ouro!',
    funFact: 'Ouro Preto é Patrimônio Mundial da UNESCO!',
    points: 1,
    options: [
      { id: 'A', text: 'Brasília' },
      { id: 'B', text: 'Ouro Preto' },
      { id: 'C', text: 'Rio de Janeiro' },
      { id: 'D', text: 'Salvador' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Bernardo quer saber qual é uma característica da arte Barroca em relação ao movimento e à emoção. Qual é essa característica?',
    tip: 'Pense em esculturas e pinturas que parecem "vivas", cheias de energia!',
    funFact: 'Essa intensidade emocional é uma marca importante da arte Barroca!',
    points: 1,
    options: [
      { id: 'A', text: 'Ela busca transmitir muito movimento e emoção intensa' },
      { id: 'B', text: 'Ela é sempre estática e sem expressão' },
      { id: 'C', text: 'Ela evita qualquer tipo de emoção' },
      { id: 'D', text: 'Ela é feita só com formas simples' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Bernardo quer saber qual compositor famoso é associado à música do período Barroco. Quem foi ele?',
    tip: 'Pense num compositor alemão conhecido por suas complexas composições corais e para órgão!',
    funFact: 'A música Barroca também valorizava a complexidade e a emoção, como as artes visuais!',
    points: 1,
    options: [
      { id: 'A', text: 'Beethoven' },
      { id: 'B', text: 'Mozart' },
      { id: 'C', text: 'Johann Sebastian Bach' },
      { id: 'D', text: 'Villa-Lobos' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Bernardo quer saber qual estilo artístico veio antes do Barroco. Qual foi ele?',
    tip: 'Pense num movimento artístico anterior, valorizado pela harmonia e proporção!',
    funFact: 'O Barroco trouxe mais drama e emoção às técnicas renascentistas!',
    points: 1,
    options: [
      { id: 'A', text: 'Modernismo' },
      { id: 'B', text: 'Impressionismo' },
      { id: 'C', text: 'Cubismo' },
      { id: 'D', text: 'Renascimento' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'Para resumir seus estudos sobre o Barroco, Bernardo quer lembrar sua principal característica. Qual é ela?',
    tip: 'Pense em tudo que você aprendeu: o drama, a luz e a sombra, e a emoção das obras barrocas!',
    funFact: 'Essas características tornaram o Barroco um dos estilos mais marcantes da história da arte mundial!',
    points: 1,
    options: [
      { id: 'A', text: 'Simplicidade extrema e ausência de detalhes' },
      { id: 'B', text: 'Dramaticidade, contraste de luz e sombra, e forte expressão emocional' },
      { id: 'C', text: 'Formas totalmente abstratas e geométricas' },
      { id: 'D', text: 'Ausência total de temas religiosos' },
    ],
    correctAnswer: 'B',
  },
];
