export const questoesMatematica7AnoB2Av1 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'Uma fração representa uma parte de um todo dividido em partes iguais. Na fração 3/4, o número 4 (embaixo) é chamado de:',
    tip: 'O número de baixo mostra em quantas partes o todo foi dividido — ele "denomina" o tamanho de cada pedaço!',
    funFact: 'A palavra "denominador" vem do latim e significa "aquele que dá nome"!',
    points: 1,
    options: [
      { id: 'A', text: 'Numerador' },
      { id: 'B', text: 'Resultado' },
      { id: 'C', text: 'Denominador' },
      { id: 'D', text: 'Quociente' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'Na fração 3/4, o número 3 (em cima) é chamado de:',
    tip: 'O número de cima conta quantas partes você está considerando — ele "numera" as partes!',
    funFact: 'Se você lembrar que "numerador" tem a ver com "número de partes tomadas", nunca mais vai confundir!',
    points: 1,
    options: [
      { id: 'A', text: 'Numerador' },
      { id: 'B', text: 'Denominador' },
      { id: 'C', text: 'Resto' },
      { id: 'D', text: 'Divisor' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'Qual fração é MAIOR: 2/5 ou 4/5?',
    tip: 'Quando o denominador é igual, basta comparar o numerador — quem tem mais partes é maior!',
    funFact: 'Comparar frações com o mesmo denominador é o caso mais fácil de todos!',
    points: 1,
    options: [
      { id: 'A', text: '2/5' },
      { id: 'B', text: 'São iguais' },
      { id: 'C', text: 'Não dá para comparar' },
      { id: 'D', text: '4/5' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'Qual fração é equivalente a 1/2?',
    tip: 'Frações equivalentes representam a mesma quantidade. Multiplique o numerador e o denominador de 1/2 pelo mesmo número e veja o que aparece!',
    funFact: 'Existem infinitas frações equivalentes a 1/2: 2/4, 3/6, 4/8, 50/100...',
    points: 1,
    options: [
      { id: 'A', text: '1/3' },
      { id: 'B', text: '2/4' },
      { id: 'C', text: '1/4' },
      { id: 'D', text: '3/4' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'O número decimal 0,75 é lido como:',
    tip: 'Conte as casas depois da vírgula: são duas, então lemos em "centésimos" (como se fosse uma fração de denominador 100).',
    funFact: '0,75 é exatamente a mesma coisa que 75/100, que pode ser simplificada para 3/4!',
    points: 1,
    options: [
      { id: 'A', text: 'setenta e cinco' },
      { id: 'B', text: 'sete vírgula cinco' },
      { id: 'C', text: 'setenta e cinco centésimos' },
      { id: 'D', text: 'sete inteiros e cinco décimos' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'Qual é a forma decimal da fração 1/4?',
    tip: 'Faça a divisão 1 ÷ 4 e observe o resultado com calma!',
    funFact: '1/4 também é conhecido como "um quarto" — por isso dizemos "um quarto de hora" para 15 minutos!',
    points: 1,
    options: [
      { id: 'A', text: '0,25' },
      { id: 'B', text: '0,4' },
      { id: 'C', text: '0,14' },
      { id: 'D', text: '1,4' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'Qual é o resultado de 2/7 + 3/7?',
    tip: 'Quando os denominadores são iguais, você só soma os numeradores e mantém o denominador!',
    funFact: 'Esse é o tipo mais simples de soma de frações — o "verdadeiro desafio" começa quando os denominadores são diferentes!',
    points: 1,
    options: [
      { id: 'A', text: '5/14' },
      { id: 'B', text: '5/7' },
      { id: 'C', text: '6/7' },
      { id: 'D', text: '1/7' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'Qual é o resultado de 2,5 + 1,3?',
    tip: 'Alinhe a vírgula embaixo da vírgula, como faria numa soma normal, e some casa por casa!',
    funFact: 'Alinhar a vírgula é o segredo para nunca errar contas com números decimais!',
    points: 1,
    options: [
      { id: 'A', text: '3,7' },
      { id: 'B', text: '3,9' },
      { id: 'C', text: '4,8' },
      { id: 'D', text: '3,8' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'Qual é o resultado de 5/8 - 2/8?',
    tip: 'Com denominadores iguais, subtraia só os numeradores e mantenha o denominador embaixo!',
    funFact: 'O denominador nunca muda na soma ou subtração de frações com o mesmo denominador — só ele "define o tamanho" das partes!',
    points: 1,
    options: [
      { id: 'A', text: '3/16' },
      { id: 'B', text: '7/8' },
      { id: 'C', text: '3/8' },
      { id: 'D', text: '2/8' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'Qual é o resultado de 5,0 - 1,8?',
    tip: 'Pode ser útil "pegar emprestado" na subtração, igual você faz com números inteiros. Vá com calma, casa por casa!',
    funFact: '5,0 é o mesmo que 5,00 — você pode sempre completar com zeros à direita sem mudar o valor!',
    points: 1,
    options: [
      { id: 'A', text: '3,2' },
      { id: 'B', text: '3,8' },
      { id: 'C', text: '4,2' },
      { id: 'D', text: '3,4' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'Qual é o resultado de 1/2 + 1/4?',
    tip: 'Antes de somar, transforme 1/2 em quartos: 1/2 = 2/4. Agora some 2/4 + 1/4!',
    funFact: 'Esse processo de igualar denominadores é chamado de "tirar o MMC" — o mesmo MMC que você aprendeu no bimestre passado!',
    points: 1,
    options: [
      { id: 'A', text: '2/6' },
      { id: 'B', text: '1/6' },
      { id: 'C', text: '2/4' },
      { id: 'D', text: '3/4' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'Qual é o resultado de 2/3 x 3/4?',
    tip: 'Na multiplicação de frações, multiplique numerador com numerador e denominador com denominador: (2x3)/(3x4). Depois simplifique!',
    funFact: 'Multiplicar frações é mais fácil do que somar — não precisa igualar denominador nenhum!',
    points: 1,
    options: [
      { id: 'A', text: '5/7' },
      { id: 'B', text: '1/2' },
      { id: 'C', text: '6/7' },
      { id: 'D', text: '5/12' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'Qual é o resultado de 1/2 ÷ 1/4?',
    tip: 'Para dividir frações, "multiplique pela fração invertida": 1/2 x 4/1.',
    funFact: 'Essa regra é conhecida como "regra do multiplica cruzado" ou "inverte e multiplica"!',
    points: 1,
    options: [
      { id: 'A', text: '1/8' },
      { id: 'B', text: '1/2' },
      { id: 'C', text: '2' },
      { id: 'D', text: '4/8' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'Qual é o resultado de 0,5 x 0,2?',
    tip: 'Multiplique como se não tivesse vírgula (5 x 2 = 10) e depois conte as casas decimais dos dois números para posicionar a vírgula!',
    funFact: 'Multiplicação de decimais sempre "encolhe" o número — por isso o resultado é menor que os dois fatores originais!',
    points: 1,
    options: [
      { id: 'A', text: '0,10' },
      { id: 'B', text: '1,0' },
      { id: 'C', text: '0,7' },
      { id: 'D', text: '0,05' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'Qual é o resultado de 4,8 ÷ 2?',
    tip: 'Divida como se fosse um número inteiro e mantenha a vírgula na mesma posição relativa do resultado.',
    funFact: 'Dividir um decimal por um número inteiro é bem parecido com dividir números inteiros comuns!',
    points: 1,
    options: [
      { id: 'A', text: '2,8' },
      { id: 'B', text: '24' },
      { id: 'C', text: '0,24' },
      { id: 'D', text: '2,4' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'Qual é o resultado de 3/4 - 1/2?',
    tip: 'Transforme 1/2 em quartos primeiro: 1/2 = 2/4. Agora é só fazer 3/4 - 2/4!',
    funFact: 'Sempre que os denominadores forem diferentes, o primeiro passo é igualá-los usando o MMC!',
    points: 1,
    options: [
      { id: 'A', text: '2/2' },
      { id: 'B', text: '1/4' },
      { id: 'C', text: '2/4' },
      { id: 'D', text: '1/2' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'Quanto é 1/3 de 90 canetas?',
    tip: '"Fração de um número" é sempre uma divisão: divida 90 pelo denominador (3).',
    funFact: 'Calcular "fração de quantidade" é uma das aplicações mais usadas de frações no dia a dia, como em receitas de comida!',
    points: 1,
    options: [
      { id: 'A', text: '30' },
      { id: 'B', text: '3' },
      { id: 'C', text: '60' },
      { id: 'D', text: '27' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'Qual das alternativas é VERDADEIRA?',
    tip: 'Transforme as frações em decimais para comparar mais fácil: 1/4 = 0,25 e 1/2 = 0,5.',
    funFact: 'Transformar tudo em decimal é um truque ótimo para comparar frações e decimais ao mesmo tempo!',
    points: 1,
    options: [
      { id: 'A', text: '1/2 < 0,3' },
      { id: 'B', text: '3/4 < 0,5' },
      { id: 'C', text: '1/4 < 0,5' },
      { id: 'D', text: '0,9 < 1/2' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'A fração 7/2 pode ser escrita como número misto:',
    tip: 'Divida 7 por 2: o quociente (3) é a parte inteira, e o resto (1) vira o numerador da fração, mantendo o mesmo denominador.',
    funFact: 'Frações como 7/2, com numerador maior que o denominador, são chamadas de "frações impróprias"!',
    points: 1,
    options: [
      { id: 'A', text: '2 e 1/2' },
      { id: 'B', text: '3 e 1/7' },
      { id: 'C', text: '1 e 3/2' },
      { id: 'D', text: '3 e 1/2' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'Uma pizza foi dividida em 8 pedaços iguais. Se Bernardo comeu 3 pedaços, que fração da pizza ele comeu?',
    tip: 'O denominador é o total de pedaços da pizza, e o numerador é quantos pedaços foram comidos.',
    funFact: 'Pizza é um dos exemplos favoritos dos professores para ensinar frações — dá pra "ver" a fração de verdade!',
    points: 1,
    options: [
      { id: 'A', text: '8/3' },
      { id: 'B', text: '3/8' },
      { id: 'C', text: '3/5' },
      { id: 'D', text: '5/8' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Bernardo dividiu uma barra de chocolate em 6 pedaços iguais e comeu 2. Que fração ele comeu?',
    tip: 'O total de pedaços vai embaixo, e o que foi comido vai em cima. Depois, se der, simplifique!',
    funFact: '2/6 simplificada vira 1/3 — dividindo numerador e denominador pelo mesmo número (2), a fração continua representando a mesma quantidade!',
    points: 1,
    options: [
      { id: 'A', text: '2/6 (ou 1/3)' },
      { id: 'B', text: '6/2' },
      { id: 'C', text: '4/6' },
      { id: 'D', text: '2/4' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Bernardo tinha 3/4 de um pacote de biscoitos e deu 1/4 para sua irmã. Com quanto ele ficou?',
    tip: 'Como os denominadores já são iguais, é só subtrair os numeradores: 3/4 - 1/4.',
    funFact: '2/4 pode ser simplificada para 1/2 — Bernardo ficou com metade do pacote!',
    points: 1,
    options: [
      { id: 'A', text: '4/4' },
      { id: 'B', text: '1/4' },
      { id: 'C', text: '2/4' },
      { id: 'D', text: '3/8' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Na mesada de Bernardo, ele gastou R$ 12,50 em um brinquedo e R$ 3,25 em um doce. Quanto ele gastou no total?',
    tip: 'Alinhe as vírgulas e some casa por casa, começando pela direita, igual você faria com números inteiros!',
    funFact: 'Dinheiro é sempre representado com números decimais — reais e centavos!',
    points: 1,
    options: [
      { id: 'A', text: '15,25' },
      { id: 'B', text: '15,75' },
      { id: 'C', text: '16,75' },
      { id: 'D', text: '9,25' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Bernardo tem uma corda de 2,4 metros e quer cortá-la em pedaços de 0,6 metro cada. Quantos pedaços ele vai conseguir?',
    tip: 'Divida 2,4 por 0,6. Uma dica: multiplique os dois números por 10 para eliminar a vírgula (24 ÷ 6)!',
    funFact: 'Multiplicar os dois números por 10, 100 ou 1000 não muda o resultado da divisão — é um truque que facilita muito as contas!',
    points: 1,
    options: [
      { id: 'A', text: '6' },
      { id: 'B', text: '0,4' },
      { id: 'C', text: '14' },
      { id: 'D', text: '4' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Se Bernardo acertou 18 de 24 questões de uma prova, que fração representa seus acertos?',
    tip: 'O total de questões vai no denominador, e os acertos no numerador. Depois, se quiser, simplifique dividindo os dois por 6!',
    funFact: '18/24 simplificada é 3/4 — ou seja, Bernardo acertou 75% da prova!',
    points: 1,
    options: [
      { id: 'A', text: '18/24 (ou 3/4)' },
      { id: 'B', text: '24/18' },
      { id: 'C', text: '6/24' },
      { id: 'D', text: '18/6' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Bernardo comeu 1/2 de uma pizza e seu irmão comeu 1/4 da mesma pizza. Que fração da pizza sobrou?',
    tip: 'Some o que os dois comeram (1/2 + 1/4 = 3/4) e depois subtraia de um inteiro (4/4 - 3/4).',
    funFact: 'Lembre-se: "um inteiro" pode sempre ser escrito como uma fração igual ao próprio denominador, como 4/4!',
    points: 1,
    options: [
      { id: 'A', text: '1/2' },
      { id: 'B', text: '3/4' },
      { id: 'C', text: '1/4' },
      { id: 'D', text: '2/4' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Bernardo comprou um lápis por R$ 1,75 e uma borracha por R$ 0,90. Quanto ele gastou no total?',
    tip: 'Alinhe as vírgulas certinho e some com atenção, casa por casa!',
    funFact: 'Somar preços de compras é uma das aplicações mais úteis da matemática no dia a dia!',
    points: 1,
    options: [
      { id: 'A', text: '2,55' },
      { id: 'B', text: '2,75' },
      { id: 'C', text: '1,85' },
      { id: 'D', text: '2,65' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Bernardo dividiu igualmente R$ 7,50 entre 3 amigos. Quanto cada um recebeu?',
    tip: 'Divida 7,50 por 3 com calma — pode ser mais fácil pensar em 750 centavos divididos por 3!',
    funFact: 'Dividir dinheiro igualmente entre amigos é chamado de "dividir em partes iguais" ou "repartir proporcionalmente"!',
    points: 1,
    options: [
      { id: 'A', text: '3,50' },
      { id: 'B', text: '2,50' },
      { id: 'C', text: '4,50' },
      { id: 'D', text: '2,25' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Se 2/5 dos alunos da turma de Bernardo são meninas, que fração representa os meninos (considerando só meninos e meninas)?',
    tip: 'O total da turma é sempre "um inteiro", ou seja, 5/5. Subtraia a fração das meninas: 5/5 - 2/5.',
    funFact: 'Essa é uma aplicação super comum de frações: descobrir "o resto" de um grupo quando você já sabe uma parte dele!',
    points: 1,
    options: [
      { id: 'A', text: '3/5' },
      { id: 'B', text: '2/5' },
      { id: 'C', text: '5/2' },
      { id: 'D', text: '2/3' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'No fim de semana, Bernardo percorreu 0,75 km andando e depois mais 1,25 km de bicicleta. Qual foi a distância total percorrida?',
    tip: 'Alinhe as vírgulas e some 0,75 + 1,25 com atenção — repare que as casas decimais somam um número redondo!',
    funFact: 'Quando as casas decimais de dois números somam exatamente 100 centésimos, o resultado vira um número "inteiro e redondo" — nesse caso, 2,00 km!',
    points: 1,
    options: [
      { id: 'A', text: '1,90 km' },
      { id: 'B', text: '1,5 km' },
      { id: 'C', text: '2,00 km' },
      { id: 'D', text: '2,50 km' },
    ],
    correctAnswer: 'C',
  },
];
