export const questoesHistoria5AnoB1Av2 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'De onde vieram os povos africanos que chegaram ao Brasil a partir do século 16?',
    tip: 'Pensa: os povos africanos trazidos ao Brasil vieram de um continente inteiro, com muitos países e culturas diferentes dentro dele. Qual continente é esse?',
    funFact: 'A África é o segundo maior continente do mundo, com uma enorme diversidade de povos, línguas e culturas! 🌍',
    points: 1,
    options: [
      { id: 'A', text: 'Da Ásia' },
      { id: 'B', text: 'Da Europa' },
      { id: 'C', text: 'Da América do Norte' },
      { id: 'D', text: 'Do continente africano, de diferentes regiões e povos, como os bantos, iorubás e outros' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'Os povos africanos trazidos ao Brasil eram:',
    tip: 'Pensa: será que todos os africanos trazidos ao Brasil eram do mesmo lugar, com a mesma cultura, ou vinham de regiões bem diferentes da África?',
    funFact: 'Estima-se que existiam centenas de grupos étnicos africanos diferentes entre as pessoas trazidas ao Brasil durante o período colonial! 🌍',
    points: 1,
    options: [
      { id: 'A', text: 'Todos do mesmo povo, com a mesma língua e cultura' },
      { id: 'B', text: 'Muito diversos, vindos de diferentes regiões da África, com línguas, religiões e costumes variados' },
      { id: 'C', text: 'Originários apenas de um único país africano' },
      { id: 'D', text: 'Recém-chegados da Europa' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'Como os africanos chegaram ao Brasil durante o período colonial?',
    tip: 'Pensa: essas pessoas vieram ao Brasil por escolha própria, como turistas, ou foram trazidas contra a vontade delas, de forma forçada?',
    funFact: 'A travessia do Atlântico durava semanas e era feita em condições muito difíceis e desumanas dentro dos navios negreiros. 🌊',
    points: 1,
    options: [
      { id: 'A', text: 'Como turistas visitando o país' },
      { id: 'B', text: 'Como comerciantes que vieram por vontade própria' },
      { id: 'C', text: 'Foram trazidos à força, escravizados, em navios conhecidos como navios negreiros, em uma viagem sofrida chamada travessia do Atlântico' },
      { id: 'D', text: 'Como exploradores em busca de riquezas' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'O que era o trabalho escravo, imposto às pessoas africanas e afrodescendentes no Brasil colonial?',
    tip: 'Pensa: um sistema em que pessoas não podiam escolher onde trabalhar, eram tratadas como objetos e não recebiam nada em troca é um sistema justo ou muito injusto?',
    funFact: 'O Brasil foi o país das Américas que mais recebeu pessoas escravizadas vindas da África, e também o último a abolir esse sistema. 📜',
    points: 1,
    options: [
      { id: 'A', text: 'Um sistema extremamente injusto e cruel, em que pessoas eram forçadas a trabalhar sem liberdade nem direitos, sendo tratadas como propriedade' },
      { id: 'B', text: 'Um tipo de emprego remunerado e escolhido livremente' },
      { id: 'C', text: 'Uma tradição cultural africana' },
      { id: 'D', text: 'Um trabalho voluntário e bem recompensado' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'Apesar do sofrimento imposto pela escravidão, os povos africanos e seus descendentes:',
    tip: 'Pensa: mesmo diante de tanto sofrimento, será que os povos africanos e seus descendentes conseguiram manter e passar adiante partes importantes de sua cultura?',
    funFact: 'Muitas tradições culturais brasileiras de hoje, como certas danças, comidas e religiões, têm raízes diretas na cultura africana! 🎶',
    points: 1,
    options: [
      { id: 'A', text: 'Perderam completamente sua cultura e identidade' },
      { id: 'B', text: 'Não deixaram nenhuma contribuição para o Brasil' },
      { id: 'C', text: 'Aceitaram passivamente todas as injustiças, sem nenhuma forma de resistência' },
      { id: 'D', text: 'Resistiram de diversas formas e preservaram e transmitiram elementos importantes de suas culturas, que fazem parte do Brasil até hoje' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'O que significa "resistência", no contexto da história dos povos africanos escravizados no Brasil?',
    tip: 'Pensa: "resistir" significa aceitar tudo calado ou lutar e se posicionar contra uma injustiça?',
    funFact: 'As fugas para os quilombos foram uma das formas mais importantes de resistência à escravidão no Brasil! ✊🏾',
    points: 1,
    options: [
      { id: 'A', text: 'Trabalhar ainda mais rápido' },
      { id: 'B', text: 'Concordar com todas as injustiças sofridas' },
      { id: 'C', text: 'As diversas formas de luta e enfrentamento contra a escravidão, como fugas, revoltas e a formação de comunidades livres' },
      { id: 'D', text: 'Um tipo de dança africana apenas' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'O Brasil foi o último país das Américas a abolir oficialmente a escravidão, em 1888, por meio de uma lei chamada:',
    tip: 'Pensa no nome dessa lei: ela tem a ver com algo precioso e valioso, como o ouro (aurum, em latim).',
    funFact: 'A Lei Áurea foi assinada pela Princesa Isabel em 13 de maio de 1888! 📜',
    points: 1,
    options: [
      { id: 'A', text: 'Lei da Boa Vontade' },
      { id: 'B', text: 'Lei Áurea' },
      { id: 'C', text: 'Lei do Ventre Livre' },
      { id: 'D', text: 'Lei dos Sexagenários' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'Por que é importante estudar a história da escravidão no Brasil com seriedade e respeito?',
    tip: 'Pensa: entender um período difícil da história ajuda a evitar repetir erros e valorizar quem lutou contra as injustiças, ou é melhor esquecer tudo?',
    funFact: 'Estudar história com seriedade ajuda a construir uma sociedade mais justa e consciente! 📚',
    points: 1,
    options: [
      { id: 'A', text: 'Para entender esse período doloroso da história e valorizar a luta e a contribuição dos povos africanos e afrodescendentes na formação do Brasil' },
      { id: 'B', text: 'Porque esse assunto não tem nenhuma relevância hoje em dia' },
      { id: 'C', text: 'Porque foi um período sem nenhuma importância histórica' },
      { id: 'D', text: 'Porque assim podemos repetir os mesmos erros do passado' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'A escravidão no Brasil durou aproximadamente:',
    tip: 'Pensa: a escravidão no Brasil durou pouquíssimo tempo ou foi um período bem longo, de vários séculos?',
    funFact: 'A escravidão durou no Brasil de 1500 até 1888, quase 400 anos de história! ⏳',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas 10 anos' },
      { id: 'B', text: 'Menos de 1 ano' },
      { id: 'C', text: 'Cerca de 50 anos' },
      { id: 'D', text: 'Mais de 300 anos, sendo um dos períodos mais longos de escravidão das Américas' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'O que a Lei 10.639/2003 determina sobre o ensino nas escolas brasileiras?',
    tip: 'Pensa: existe uma lei brasileira, parecida com a que vimos sobre os povos indígenas, mas voltada para a história africana e afro-brasileira. Ela obriga ou proíbe esse ensino?',
    funFact: 'A Lei 10.639, de 2003, foi um passo importante para garantir que a história completa do Brasil fosse ensinada nas escolas! 📖',
    points: 1,
    options: [
      { id: 'A', text: 'Que a história africana não deve ser estudada' },
      { id: 'B', text: 'Que apenas alunos afrodescendentes devem estudar esse tema' },
      { id: 'C', text: 'Que é obrigatório o ensino da história e cultura afro-brasileira e africana em todas as escolas do Brasil' },
      { id: 'D', text: 'Que esse assunto é opcional' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'O que eram os quilombos?',
    tip: 'Pensa: esse era o nome dado às comunidades formadas por pessoas que conseguiam fugir da escravidão e viver livremente, organizando sua própria vida.',
    funFact: 'Existiram centenas de quilombos espalhados por todo o Brasil durante o período da escravidão! 🏘️',
    points: 1,
    options: [
      { id: 'A', text: 'Comunidades formadas por pessoas escravizadas que conseguiam fugir, organizando-se livremente e preservando suas culturas' },
      { id: 'B', text: 'Fazendas onde os africanos eram escravizados' },
      { id: 'C', text: 'Um tipo de embarcação usada no tráfico de pessoas' },
      { id: 'D', text: 'Escolas construídas pelos colonizadores portugueses' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'Qual foi o quilombo mais famoso da história do Brasil, localizado na região que hoje é o estado de Alagoas?',
    tip: 'Pensa: esse foi um dos quilombos mais famosos e duradouros da história do Brasil, ficando conhecido em todo o país.',
    funFact: 'O Quilombo dos Palmares resistiu por quase 100 anos, sendo uma das maiores comunidades de resistência das Américas! 🌴',
    points: 1,
    options: [
      { id: 'A', text: 'Quilombo de São Paulo' },
      { id: 'B', text: 'Quilombo da Bahia' },
      { id: 'C', text: 'Quilombo dos Palmares' },
      { id: 'D', text: 'Quilombo do Rio de Janeiro' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'Quem foi Zumbi dos Palmares?',
    tip: 'Pensa: essa pessoa é lembrada até hoje como um símbolo de coragem e luta pela liberdade, tendo liderado um dos quilombos mais importantes do Brasil.',
    funFact: 'Zumbi dos Palmares é homenageado até hoje, e seu nome está ligado ao Dia da Consciência Negra! 🦁',
    points: 1,
    options: [
      { id: 'A', text: 'Um colonizador português' },
      { id: 'B', text: 'Um comerciante de escravos' },
      { id: 'C', text: 'Um rei europeu' },
      { id: 'D', text: 'Um dos principais líderes do Quilombo dos Palmares, símbolo de resistência e luta contra a escravidão' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'Por que a data 20 de novembro é conhecida como Dia da Consciência Negra?',
    tip: 'Pensa: essa data está relacionada a um acontecimento importante na vida de Zumbi dos Palmares, um símbolo de resistência.',
    funFact: 'O Dia da Consciência Negra é celebrado em 20 de novembro, data da morte de Zumbi dos Palmares, em 1695! 🕊️',
    points: 1,
    options: [
      { id: 'A', text: 'Porque é o dia em que a escravidão foi criada no Brasil' },
      { id: 'B', text: 'Porque marca a data da morte de Zumbi dos Palmares, um símbolo de luta e resistência' },
      { id: 'C', text: 'Porque é o aniversário da Lei Áurea' },
      { id: 'D', text: 'Porque é uma data sem nenhum significado histórico' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'Qual é uma importante contribuição cultural africana presente na culinária brasileira?',
    tip: 'Pensa em pratos brasileiros bem conhecidos, com temperos e ingredientes que vieram da culinária africana.',
    funFact: 'O acarajé, bolinho feito de feijão-fradinho frito no azeite de dendê, é um prato de origem africana muito popular na Bahia! 🍽️',
    points: 1,
    options: [
      { id: 'A', text: 'Pratos como acarajé, vatapá e feijoada têm forte influência africana' },
      { id: 'B', text: 'A pizza, trazida da Itália' },
      { id: 'C', text: 'O sushi, de origem japonesa' },
      { id: 'D', text: 'O croissant, de origem francesa' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'A capoeira é uma manifestação cultural brasileira que:',
    tip: 'Pensa: essa arte que mistura luta, dança e música ao som do berimbau tem sua origem ligada a qual cultura trazida ao Brasil?',
    funFact: 'A capoeira foi criada pelos povos africanos escravizados como uma forma de resistência disfarçada de dança! 🥁',
    points: 1,
    options: [
      { id: 'A', text: 'Não tem nenhuma relação com a cultura africana' },
      { id: 'B', text: 'Foi criada pelos colonizadores europeus' },
      { id: 'C', text: 'É praticada apenas fora do Brasil' },
      { id: 'D', text: 'Combina luta, dança e música, tendo origem entre os povos africanos escravizados no Brasil' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'Muitas religiões praticadas no Brasil hoje, como o candomblé e a umbanda, têm forte influência:',
    tip: 'Pensa: essas religiões têm rituais, cantos e tradições que vieram de qual continente, trazidas pelos povos escravizados?',
    funFact: 'O candomblé e a umbanda fazem parte da rica herança religiosa afro-brasileira, com influências de diferentes povos africanos! 🕯️',
    points: 1,
    options: [
      { id: 'A', text: 'Europeia' },
      { id: 'B', text: 'Asiática' },
      { id: 'C', text: 'Africana' },
      { id: 'D', text: 'Norte-americana' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'Além da capoeira e da culinária, outra contribuição africana importante para a cultura brasileira é:',
    tip: 'Pensa em um instrumento musical usado na capoeira, e em um ritmo brasileiro super famoso no mundo todo, que também tem raízes africanas.',
    funFact: 'O samba, um dos ritmos mais famosos do Brasil, tem forte influência dos ritmos e tambores africanos! 🥁🎶',
    points: 1,
    options: [
      { id: 'A', text: 'O idioma português, que veio de Portugal' },
      { id: 'B', text: 'A música, com instrumentos como o berimbau e ritmos que deram origem ao samba' },
      { id: 'C', text: 'A arquitetura das igrejas coloniais' },
      { id: 'D', text: 'O sistema de escrita usado no Brasil' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'Muitas palavras usadas no português falado no Brasil têm origem africana. Qual dessas é um exemplo?',
    tip: 'Pensa em uma palavra usada para se referir, de forma carinhosa, a um menino ou garoto, muito comum no vocabulário brasileiro.',
    funFact: 'A palavra "moleque" vem do quimbundo, uma língua africana, e é usada no Brasil há séculos! 🗣️',
    points: 1,
    options: [
      { id: 'A', text: 'Moleque' },
      { id: 'B', text: 'Computador' },
      { id: 'C', text: 'Bicicleta' },
      { id: 'D', text: 'Televisão' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'Por que é importante reconhecer e valorizar as contribuições dos povos africanos na formação da cultura brasileira?',
    tip: 'Pensa: se a cultura brasileira tem tantas raízes na cultura africana, faz sentido ignorar ou desvalorizar essa contribuição, ou é importante reconhecê-la?',
    funFact: 'Reconhecer as raízes africanas da cultura brasileira ajuda a valorizar a diversidade que forma a identidade do nosso país! 🇧🇷',
    points: 1,
    options: [
      { id: 'A', text: 'Porque essas contribuições não têm nenhuma importância' },
      { id: 'B', text: 'Porque só interessam a uma parte da população' },
      { id: 'C', text: 'Porque a cultura brasileira não tem nenhuma influência africana' },
      { id: 'D', text: 'Porque essas contribuições fazem parte fundamental da identidade e da riqueza cultural do Brasil, e merecem ser conhecidas e respeitadas' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Na escola, Bernardo aprendeu que pratos como a feijoada têm influência:',
    tip: 'Lembra da pergunta 15: esse prato brasileiro tem raízes bem fortes em qual cultura?',
    funFact: 'A feijoada é considerada um dos pratos mais tradicionais do Brasil, com origem ligada à culinária afro-brasileira! 🍲',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas europeia' },
      { id: 'B', text: 'Africana, um exemplo da rica contribuição cultural dos povos africanos na culinária brasileira' },
      { id: 'C', text: 'Apenas indígena' },
      { id: 'D', text: 'Apenas asiática' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Bernardo assistiu a uma roda de capoeira na sua cidade e ficou encantado com os movimentos e a música. Ele aprendeu que a capoeira:',
    tip: 'Lembra da pergunta 16: essa arte, que mistura dança, luta e música, tem origem em qual cultura trazida ao Brasil?',
    funFact: 'Hoje a capoeira é praticada em vários países do mundo, sendo reconhecida como Patrimônio Cultural Imaterial da Humanidade pela UNESCO! 🌎',
    points: 1,
    options: [
      { id: 'A', text: 'Não tem relação com a cultura brasileira' },
      { id: 'B', text: 'Foi inventada recentemente, sem nenhuma origem histórica' },
      { id: 'C', text: 'É uma tradição vinda apenas da Europa' },
      { id: 'D', text: 'Tem origem na cultura dos povos africanos escravizados no Brasil, unindo luta, dança e música' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'No dia 20 de novembro, a escola de Bernardo promoveu atividades sobre a Consciência Negra. Essa data é importante porque:',
    tip: 'Lembra da pergunta 14: essa data homenageia um grande líder de resistência contra a escravidão. Qual é o nome dele?',
    funFact: 'Em muitas cidades brasileiras, o 20 de novembro é feriado municipal ou estadual, dedicado a refletir sobre a luta do povo negro! 🎗️',
    points: 1,
    options: [
      { id: 'A', text: 'Marca o início da escravidão no Brasil' },
      { id: 'B', text: 'É um feriado sem nenhum significado histórico' },
      { id: 'C', text: 'Homenageia a luta de Zumbi dos Palmares e a resistência do povo negro contra a escravidão' },
      { id: 'D', text: 'Celebra a chegada dos portugueses ao Brasil' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Bernardo aprendeu que os quilombos eram importantes porque:',
    tip: 'Lembra da pergunta 11: os quilombos representavam um lugar de que tipo de vida para quem conseguia fugir da escravidão?',
    funFact: 'Hoje existem comunidades quilombolas em várias regiões do Brasil, que preservam tradições herdadas de seus antepassados! 🏡',
    points: 1,
    options: [
      { id: 'A', text: 'Representavam espaços de liberdade e resistência, organizados pelas pessoas que fugiam da escravidão' },
      { id: 'B', text: 'Eram fazendas onde a escravidão continuava normalmente' },
      { id: 'C', text: 'Foram criados pelos colonizadores portugueses' },
      { id: 'D', text: 'Não tiveram nenhuma importância histórica' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Se Bernardo perguntar por que a escravidão foi injusta, a resposta correta é:',
    tip: 'Pensa: tratar uma pessoa como se fosse um objeto, sem liberdade nem direitos, respeita ou fere a dignidade dela?',
    funFact: 'A dignidade humana é um princípio tão importante que está garantida na Constituição Federal brasileira! ⚖️',
    points: 1,
    options: [
      { id: 'A', text: 'Porque as pessoas escravizadas não trabalhavam direito' },
      { id: 'B', text: 'Porque pessoas eram forçadas a trabalhar sem liberdade, sendo tratadas como propriedade, o que fere a dignidade humana' },
      { id: 'C', text: 'Porque era muito caro manter pessoas escravizadas' },
      { id: 'D', text: 'Porque a escravidão não trouxe nenhum lucro aos donos de escravos' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Bernardo entendeu que, apesar do sofrimento da escravidão, os povos africanos e seus descendentes:',
    tip: 'Pensa em tudo que vimos hoje: comida, música, religião, palavras... Isso mostra que a cultura africana desapareceu ou deixou marcas riquíssimas no Brasil?',
    funFact: 'A cultura brasileira é resultado da mistura de povos indígenas, africanos e europeus, entre outros, cada um contribuindo de forma única! 🌈',
    points: 1,
    options: [
      { id: 'A', text: 'Perderam toda a sua identidade cultural' },
      { id: 'B', text: 'Não contribuíram em nada para o Brasil' },
      { id: 'C', text: 'Resistiram e deixaram contribuições culturais riquíssimas, como música, culinária, religião e línguas' },
      { id: 'D', text: 'Deixaram de existir no Brasil após a abolição' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Bernardo aprendeu que a Lei Áurea, assinada em 1888, foi importante porque:',
    tip: 'Lembra da pergunta 7: essa lei tem um nome relacionado a algo valioso, e foi ela que encerrou oficialmente um período muito longo e injusto da história do Brasil.',
    funFact: 'Mesmo depois da Lei Áurea, muitas pessoas negras ainda enfrentaram (e enfrentam) desafios para conquistar seus direitos plenamente na sociedade! ⚖️',
    points: 1,
    options: [
      { id: 'A', text: 'Criou a escravidão no Brasil' },
      { id: 'B', text: 'Aumentou o número de pessoas escravizadas' },
      { id: 'C', text: 'Não teve nenhum efeito prático' },
      { id: 'D', text: 'Aboliu oficialmente a escravidão no Brasil' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Qual atitude mostra respeito à história e cultura afro-brasileira?',
    tip: 'Pensa: aprender com seriedade e valorizar as contribuições culturais é uma atitude respeitosa, ou ignorar e fazer piadas seria mais respeitoso?',
    funFact: 'Conhecer a história e a cultura afro-brasileira com profundidade ajuda a combater o preconceito e o racismo! 🤝',
    points: 1,
    options: [
      { id: 'A', text: 'Aprender sobre essa história com seriedade e valorizar as contribuições culturais dos povos africanos' },
      { id: 'B', text: 'Ignorar completamente esse tema' },
      { id: 'C', text: 'Fazer piadas sobre a cultura afro-brasileira' },
      { id: 'D', text: 'Achar que esse assunto não é importante' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Depois de estudar sobre a presença africana na formação do Brasil, Bernardo concluiu que a cultura brasileira:',
    tip: 'Pensa em tudo que aprendemos hoje sobre comida, música, religião e palavras. Isso mostra que a cultura brasileira tem pouca ou muita influência africana?',
    funFact: 'O Brasil tem a maior população de origem africana fora do continente africano, o que mostra a força dessa herança cultural! 🇧🇷',
    points: 1,
    options: [
      { id: 'A', text: 'Não tem nenhuma influência africana' },
      { id: 'B', text: 'É formada, entre outras influências, por uma riquíssima contribuição africana, presente na comida, música, religião e línguas' },
      { id: 'C', text: 'É idêntica à cultura europeia, sem nenhuma diferença' },
      { id: 'D', text: 'Surgiu apenas com a chegada dos portugueses' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'Qual conclusão importante Bernardo pode tirar sobre a história da escravidão e a luta dos povos africanos no Brasil?',
    tip: 'Pensa em tudo que estudamos: a escravidão foi um período fácil ou muito difícil e injusto? E, apesar disso, os povos africanos apenas sofreram ou também resistiram e deixaram uma herança importante?',
    funFact: 'Conhecer essa história completa, com seus sofrimentos e suas lutas, é fundamental para entender e valorizar o Brasil de hoje! 💛',
    points: 1,
    options: [
      { id: 'A', text: 'Foi um período sem nenhuma consequência para o Brasil de hoje' },
      { id: 'B', text: 'As pessoas escravizadas aceitaram tudo sem resistir' },
      { id: 'C', text: 'Foi um período de grande sofrimento e injustiça, mas também de resistência e luta, que deixou uma herança cultural fundamental para o Brasil' },
      { id: 'D', text: 'Esse assunto não deveria ser estudado nas escolas' },
    ],
    correctAnswer: 'C',
  },
];
