export const questoesArte7AnoB3Av2 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "O principal 'instrumento' usado para se expressar na dança é o:",
    tip: "Pense no que o dançarino usa diretamente para criar os movimentos — não é uma roupa nem um objeto.",
    funFact: "\"Você sabia?\" — O corpo humano tem mais de 600 músculos, e a dança pode usar muitos deles ao mesmo tempo!",
    points: 1,
    options: [
      { id: "A", text: "Figurino" },
      { id: "B", text: "Corpo" },
      { id: "C", text: "Cenário" },
      { id: "D", text: "Texto" },
    ],
    correctAnswer: "B",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "A ação de mover o corpo de diferentes formas durante a dança é chamada de:",
    tip: "Pense na palavra mais simples que descreve 'o corpo se deslocando ou mudando de posição'.",
    funFact: "\"Você sabia?\" — Existem milhares de tipos de movimentos de dança diferentes catalogados em culturas de todo o mundo!",
    points: 1,
    options: [
      { id: "A", text: "Figurino" },
      { id: "B", text: "Cenário" },
      { id: "C", text: "Sonoplastia" },
      { id: "D", text: "Movimento" },
    ],
    correctAnswer: "D",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "O local, maior ou menor, por onde o dançarino se move durante a dança é chamado de:",
    tip: "Pense no 'lugar físico' que o dançarino ocupa e percorre durante a apresentação.",
    funFact: "\"Você sabia?\" — Alguns bailarinos de balé usam o palco inteiro, enquanto outras danças são feitas em espaços bem pequenos e fechados!",
    points: 1,
    options: [
      { id: "A", text: "Espaço" },
      { id: "B", text: "Tempo" },
      { id: "C", text: "Figurino" },
      { id: "D", text: "Som" },
    ],
    correctAnswer: "A",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "O elemento da dança relacionado à velocidade e à duração dos movimentos (rápido, lento, longo, curto) é chamado de:",
    tip: "Pense na 'velocidade' e 'duração' dos movimentos — essa característica tem relação direta com o relógio.",
    funFact: "\"Você sabia?\" — O tempo na dança costuma estar diretamente ligado ao ritmo da música que está sendo tocada!",
    points: 1,
    options: [
      { id: "A", text: "Espaço" },
      { id: "B", text: "Figurino" },
      { id: "C", text: "Tempo" },
      { id: "D", text: "Cenário" },
    ],
    correctAnswer: "C",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "Uma sequência organizada de movimentos de dança, criada e planejada, é chamada de:",
    tip: "Pense no nome dado a uma sequência de passos de dança planejada e decorada antes da apresentação.",
    funFact: "\"Você sabia?\" — Grandes coreografias de shows e filmes podem levar semanas ou até meses para serem criadas e ensaiadas!",
    points: 1,
    options: [
      { id: "A", text: "Improviso puro" },
      { id: "B", text: "Figurino" },
      { id: "C", text: "Sonoplastia" },
      { id: "D", text: "Coreografia" },
    ],
    correctAnswer: "D",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "O frevo, dançado durante o carnaval de Pernambuco, é conhecido por seus movimentos:",
    tip: "Pense na dança de carnaval que usa pequenas sombrinhas e movimentos ágeis das pernas, quase como acrobacias.",
    funFact: "\"Você sabia?\" — O frevo é tão rápido e exigente que muitos dançarinos precisam de bastante preparo físico, como atletas!",
    points: 1,
    options: [
      { id: "A", text: "Lentos e suaves" },
      { id: "B", text: "Rápidos e acrobáticos" },
      { id: "C", text: "Parados, sem movimento" },
      { id: "D", text: "Apenas com os braços" },
    ],
    correctAnswer: "B",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "O carimbó é uma dança tradicional de qual região brasileira?",
    tip: "Pense na região amazônica, onde essa dança tem forte influência indígena e africana.",
    funFact: "\"Você sabia?\" — O carimbó é dançado em roda, com as mulheres usando saias bem rodadas que se destacam durante os giros!",
    points: 1,
    options: [
      { id: "A", text: "Sul" },
      { id: "B", text: "Sudeste" },
      { id: "C", text: "Norte (Pará)" },
      { id: "D", text: "Nordeste" },
    ],
    correctAnswer: "C",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "O samba de roda, manifestação cultural muito presente na Bahia, é dançado geralmente:",
    tip: "O próprio nome já dá uma pista — pense na formação que as pessoas fazem para dançar esse estilo.",
    funFact: "\"Você sabia?\" — O samba de roda é tão importante culturalmente que já foi reconhecido pela UNESCO como Patrimônio Cultural Imaterial da Humanidade!",
    points: 1,
    options: [
      { id: "A", text: "Em círculo, com os participantes se revezando no centro" },
      { id: "B", text: "Apenas sozinho, sem roda" },
      { id: "C", text: "Apenas em duplas fixas" },
      { id: "D", text: "Sem nenhum ritmo" },
    ],
    correctAnswer: "A",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "O jongo é uma dança de origem africana, muito ligada à cultura:",
    tip: "Pense na origem citada na própria questão — essa dança tem raízes de um continente específico, combinadas com a cultura brasileira.",
    funFact: "\"Você sabia?\" — O jongo é dançado ao som de tambores e costuma envolver versos cantados com rimas improvisadas!",
    points: 1,
    options: [
      { id: "A", text: "Indígena apenas" },
      { id: "B", text: "Afro-brasileira" },
      { id: "C", text: "Europeia" },
      { id: "D", text: "Asiática" },
    ],
    correctAnswer: "B",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "A dança do pau de fitas, muito vista em festas juninas, é dançada ao redor de um:",
    tip: "Pense em um objeto alto, no centro da dança, com várias fitas penduradas que os dançarinos entrelaçam enquanto se movem.",
    funFact: "\"Você sabia?\" — Durante a dança do pau de fitas, os dançarinos criam padrões trançados nas fitas conforme se movem ao redor do mastro!",
    points: 1,
    options: [
      { id: "A", text: "Tambor grande" },
      { id: "B", text: "Rio" },
      { id: "C", text: "Fogo" },
      { id: "D", text: "Mastro alto com fitas coloridas" },
    ],
    correctAnswer: "D",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Durante uma apresentação de dança, os bailarinos usam todo o palco, se movendo de um lado para o outro e em diferentes alturas. Eles estão explorando principalmente o elemento:",
    tip: "Pense no elemento relacionado ao 'lugar' que os bailarinos ocupam e percorrem no palco.",
    funFact: "\"Você sabia?\" — Usar bem o espaço do palco é uma das técnicas mais valorizadas em coreografias de grandes companhias de dança!",
    points: 1,
    options: [
      { id: "A", text: "Espaço" },
      { id: "B", text: "Figurino" },
      { id: "C", text: "Sonoplastia" },
      { id: "D", text: "Texto" },
    ],
    correctAnswer: "A",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Em uma coreografia, os dançarinos alternam entre movimentos bem rápidos e momentos de pausa lenta. Eles estão trabalhando o elemento:",
    tip: "Pense no elemento relacionado à velocidade e duração dos movimentos — rápido, lento, pausado.",
    funFact: "\"Você sabia?\" — Alternar velocidades diferentes em uma coreografia ajuda a criar contrastes que tornam a apresentação mais interessante!",
    points: 1,
    options: [
      { id: "A", text: "Espaço" },
      { id: "B", text: "Figurino" },
      { id: "C", text: "Tempo" },
      { id: "D", text: "Cenário" },
    ],
    correctAnswer: "C",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "Em uma apresentação de frevo, os dançarinos fazem movimentos muito rápidos com as pernas, quase como acrobacias. Esse estilo de dança tem origem em qual estado?",
    tip: "Pense no carnaval das cidades de Recife e Olinda, onde essa dança é tradição.",
    funFact: "\"Você sabia?\" — O frevo surgiu misturando ritmos de marchas militares com influências da capoeira, criando aquele estilo tão ágil!",
    points: 1,
    options: [
      { id: "A", text: "Bahia" },
      { id: "B", text: "Pernambuco" },
      { id: "C", text: "São Paulo" },
      { id: "D", text: "Rio Grande do Sul" },
    ],
    correctAnswer: "B",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "O maracatu combina música e dança em um cortejo que representa a corte de reis e rainhas, com raízes na cultura:",
    tip: "Pense na origem dessa tradição, ligada à história da escravidão e da cultura trazida da África para o Brasil.",
    funFact: "\"Você sabia?\" — O maracatu é tão rico culturalmente que tem até uma boneca especial chamada 'calunga', carregada durante o cortejo!",
    points: 1,
    options: [
      { id: "A", text: "Europeia" },
      { id: "B", text: "Indígena" },
      { id: "C", text: "Asiática" },
      { id: "D", text: "Afro-brasileira" },
    ],
    correctAnswer: "D",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Antes de uma apresentação de dança, o grupo pratica várias vezes os movimentos, decorando a sequência inteira. Esse processo cuidadoso de criar os movimentos é chamado de:",
    tip: "Pense no nome que já apareceu antes — a sequência planejada e decorada de passos de dança.",
    funFact: "\"Você sabia?\" — Coreógrafos profissionais costumam criar as sequências de movimentos antes mesmo de ensinar aos dançarinos!",
    points: 1,
    options: [
      { id: "A", text: "Improviso espontâneo" },
      { id: "B", text: "Figurino" },
      { id: "C", text: "Coreografia" },
      { id: "D", text: "Sonoplastia" },
    ],
    correctAnswer: "C",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "Quando um dançarino se move pelo espaço sem seguir uma sequência pronta, criando movimentos no momento, ele está fazendo uma dança:",
    tip: "Pense na palavra que descreve 'criar algo na hora', sem planejamento prévio, usada também no teatro.",
    funFact: "\"Você sabia?\" — Alguns estilos de dança, como o breaking (break dance), valorizam bastante a improvisação durante as apresentações!",
    points: 1,
    options: [
      { id: "A", text: "Improvisada" },
      { id: "B", text: "Totalmente decorada" },
      { id: "C", text: "Sem nenhum movimento" },
      { id: "D", text: "Apenas sentada" },
    ],
    correctAnswer: "A",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "O balé clássico, uma forma de dança bem técnica e refinada, costuma usar sapatilhas especiais e exigir muito treino de:",
    tip: "Pense nas habilidades físicas necessárias para fazer os movimentos elegantes e precisos do balé, como ficar na ponta dos pés.",
    funFact: "\"Você sabia?\" — Bailarinos de balé clássico começam a treinar muitas vezes desde criança, pois é uma dança que exige anos de prática!",
    points: 1,
    options: [
      { id: "A", text: "Apenas respiração" },
      { id: "B", text: "Apenas voz" },
      { id: "C", text: "Apenas maquiagem" },
      { id: "D", text: "Equilíbrio, flexibilidade e força" },
    ],
    correctAnswer: "D",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "A dança de rua, como o hip-hop e o breaking, costuma ter origem em:",
    tip: "Pense no ambiente onde esses estilos de dança surgiram, geralmente ligados a festas e movimentos culturais das grandes cidades.",
    funFact: "\"Você sabia?\" — O hip-hop e o breaking surgiram nos Estados Unidos, nos anos 1970, em bairros com grande população afro-americana e latina!",
    points: 1,
    options: [
      { id: "A", text: "Palácios europeus" },
      { id: "B", text: "Comunidades urbanas e festas de rua" },
      { id: "C", text: "Templos antigos" },
      { id: "D", text: "Apenas escolas de balé" },
    ],
    correctAnswer: "B",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "Quando dançarinos se movem rapidamente pelo palco, cobrindo uma grande distância, eles estão usando bastante o elemento:",
    tip: "Pense no elemento relacionado à área percorrida pelo corpo do dançarino durante a apresentação.",
    funFact: "\"Você sabia?\" — Dançarinos de companhias grandes treinam para ocupar bem o espaço do palco, mesmo em teatros enormes!",
    points: 1,
    options: [
      { id: "A", text: "Espaço" },
      { id: "B", text: "Figurino" },
      { id: "C", text: "Maquiagem" },
      { id: "D", text: "Som apenas" },
    ],
    correctAnswer: "A",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "Uma dança que mistura movimentos lentos e rápidos ao longo da apresentação está explorando bastante o elemento:",
    tip: "Pense no elemento relacionado à velocidade dos movimentos, que já apareceu em questões anteriores.",
    funFact: "\"Você sabia?\" — Misturar velocidades diferentes é uma técnica usada em quase todos os estilos de dança para criar emoção na apresentação!",
    points: 1,
    options: [
      { id: "A", text: "Espaço" },
      { id: "B", text: "Figurino" },
      { id: "C", text: "Tempo" },
      { id: "D", text: "Cenário" },
    ],
    correctAnswer: "C",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Bernardo assistiu a uma apresentação de frevo no carnaval e ficou impressionado com os movimentos rápidos e acrobáticos das pernas dos dançarinos. De qual estado é essa dança?",
    tip: "Pense no estado onde fica o carnaval famoso de Recife e Olinda, berço dessa dança ágil.",
    funFact: "\"Você sabia?\" — Assistir ao frevo de pertinho mostra como os dançarinos conseguem fazer movimentos super rápidos sem perder o equilíbrio!",
    points: 1,
    options: [
      { id: "A", text: "Bahia" },
      { id: "B", text: "Pernambuco" },
      { id: "C", text: "Rio Grande do Sul" },
      { id: "D", text: "São Paulo" },
    ],
    correctAnswer: "B",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Bernardo participou de uma roda de samba de roda em uma festa baiana, onde os participantes se revezavam dançando no centro do círculo. Qual é a origem cultural dessa dança?",
    tip: "Pense na origem ligada à cultura trazida da África, muito presente na Bahia.",
    funFact: "\"Você sabia?\" — No samba de roda, é comum que as pessoas cantem e batam palmas junto, criando uma energia coletiva muito especial!",
    points: 1,
    options: [
      { id: "A", text: "Europeia" },
      { id: "B", text: "Indígena" },
      { id: "C", text: "Asiática" },
      { id: "D", text: "Afro-brasileira" },
    ],
    correctAnswer: "D",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Na aula de dança, Bernardo usou todo o espaço da sala, se movendo de um canto para o outro. Qual elemento da dança ele estava explorando?",
    tip: "Pense no elemento relacionado à área que o corpo ocupa e percorre durante a dança.",
    funFact: "\"Você sabia?\" — Explorar bem o espaço disponível é uma das primeiras habilidades ensinadas em aulas de dança para crianças!",
    points: 1,
    options: [
      { id: "A", text: "Espaço" },
      { id: "B", text: "Figurino" },
      { id: "C", text: "Sonoplastia" },
      { id: "D", text: "Texto" },
    ],
    correctAnswer: "A",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Bernardo e seus colegas decoraram uma sequência de movimentos de dança para apresentar na festa da escola. Como se chama essa sequência planejada?",
    tip: "Pense no nome dado a uma sequência de passos de dança criada e decorada antes da apresentação.",
    funFact: "\"Você sabia?\" — Criar uma coreografia em grupo exige bastante coordenação, já que todos precisam se mover de forma sincronizada!",
    points: 1,
    options: [
      { id: "A", text: "Improviso puro" },
      { id: "B", text: "Figurino" },
      { id: "C", text: "Coreografia" },
      { id: "D", text: "Sonoplastia" },
    ],
    correctAnswer: "C",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Bernardo dançou ao redor de um mastro alto decorado com fitas coloridas durante a festa junina da escola. Como se chama essa dança tradicional?",
    tip: "Pense no objeto central dessa dança — um mastro alto com fitas penduradas, bem típico das festas de junho.",
    funFact: "\"Você sabia?\" — Durante essa dança, cada dançarino segura a ponta de uma fita e, ao se mover, cria padrões trançados ao redor do mastro!",
    points: 1,
    options: [
      { id: "A", text: "Carimbó" },
      { id: "B", text: "Jongo" },
      { id: "C", text: "Maracatu" },
      { id: "D", text: "Dança do pau de fitas" },
    ],
    correctAnswer: "D",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Bernardo alternou entre movimentos bem rápidos e pausas lentas durante sua apresentação de dança. Qual elemento ele estava trabalhando?",
    tip: "Pense no elemento relacionado à velocidade e à duração dos movimentos, já estudado anteriormente.",
    funFact: "\"Você sabia?\" — Alternar entre rápido e lento é uma técnica usada para criar emoção e surpresa durante uma apresentação de dança!",
    points: 1,
    options: [
      { id: "A", text: "Espaço" },
      { id: "B", text: "Tempo" },
      { id: "C", text: "Figurino" },
      { id: "D", text: "Cenário" },
    ],
    correctAnswer: "B",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Bernardo experimentou se mover livremente pela sala, sem seguir uma sequência decorada, criando passos na hora. Como se chama essa forma de dançar?",
    tip: "Pense na palavra que descreve criar movimentos 'na hora', sem planejamento, usando a criatividade espontânea.",
    funFact: "\"Você sabia?\" — A improvisação na dança ajuda a desenvolver a criatividade e a conexão natural do corpo com a música!",
    points: 1,
    options: [
      { id: "A", text: "Coreografia fixa" },
      { id: "B", text: "Figurino livre" },
      { id: "C", text: "Improvisação" },
      { id: "D", text: "Sonoplastia" },
    ],
    correctAnswer: "C",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Bernardo assistiu a uma apresentação de balé clássico e notou que os bailarinos precisavam de muito equilíbrio e força para fazer os movimentos. O que mais o balé clássico costuma exigir dos dançarinos?",
    tip: "Pense em outra habilidade física importante para fazer os movimentos elegantes do balé, além de equilíbrio e força.",
    funFact: "\"Você sabia?\" — Bailarinos de balé clássico costumam fazer alongamentos intensos todos os dias para manter a flexibilidade necessária!",
    points: 1,
    options: [
      { id: "A", text: "Flexibilidade" },
      { id: "B", text: "Apenas voz forte" },
      { id: "C", text: "Apenas maquiagem colorida" },
      { id: "D", text: "Nenhum treino especial" },
    ],
    correctAnswer: "A",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Bernardo viu um grupo de dança de rua se apresentando em uma praça, com movimentos de hip-hop e breaking. Onde costuma ter origem esse tipo de dança?",
    tip: "Pense no ambiente urbano onde esses estilos de dança nasceram, ligados a movimentos culturais das cidades.",
    funFact: "\"Você sabia?\" — Hoje em dia, a dança de rua é tão popular que já faz parte de competições internacionais e até de eventos esportivos!",
    points: 1,
    options: [
      { id: "A", text: "Palácios europeus" },
      { id: "B", text: "Comunidades urbanas e festas de rua" },
      { id: "C", text: "Templos antigos" },
      { id: "D", text: "Apenas escolas de balé" },
    ],
    correctAnswer: "B",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Bernardo participou de uma dança em que o grupo se movia bem rápido por todo o espaço do salão, cobrindo uma grande distância. Qual elemento da dança ele estava explorando principalmente?",
    tip: "Pense no elemento relacionado à área percorrida pelo corpo durante a dança, mencionado várias vezes nesta prova.",
    funFact: "\"Você sabia?\" — Dançar cobrindo grandes distâncias exige bastante energia e condicionamento físico, parecido com praticar um esporte!",
    points: 1,
    options: [
      { id: "A", text: "Figurino" },
      { id: "B", text: "Maquiagem" },
      { id: "C", text: "Som apenas" },
      { id: "D", text: "Espaço" },
    ],
    correctAnswer: "D",
  },
];
