export const questoesFisica1EmB1Av1 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "Um carro parte da posição s₀ = 20 m e se move com velocidade constante de 15 m/s. Qual é a equação horária da posição do carro?",
    tip: "Na equação horária do MRU, a posição inicial aparece somada ao produto velocidade × tempo.",
    funFact: "\"Você sabia?\" — O MRU (Movimento Retilíneo Uniforme) é a base para entender todos os outros movimentos; até o espaço sideral usa esse conceito para calcular trajetórias de sondas.",
    points: 1,
    options: [
      { id: "A", text: "s = 15t" },
      { id: "B", text: "s = 20 + 15" },
      { id: "C", text: "s = 20 + 15t" },
      { id: "D", text: "s = 15 + 20t" },
    ],
    correctAnswer: "C",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "No gráfico posição × tempo (s × t) de um Movimento Retilíneo Uniforme, o que representa o coeficiente angular (inclinação) da reta?",
    tip: "Pense em como a posição muda ao longo do tempo no MRU: uma razão entre variação de posição e variação de tempo.",
    funFact: "\"Você sabia?\" — Graficamente, qualquer reta inclinada num gráfico s × t indica velocidade constante; quanto mais inclinada, maior a velocidade.",
    points: 1,
    options: [
      { id: "A", text: "A velocidade do móvel" },
      { id: "B", text: "A aceleração do móvel" },
      { id: "C", text: "O deslocamento total" },
      { id: "D", text: "A posição inicial" },
    ],
    correctAnswer: "A",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "Como é representado o gráfico de velocidade × tempo (v × t) de um objeto em Movimento Retilíneo Uniforme?",
    tip: "No MRU, a velocidade não varia; pense em como um valor constante aparece num gráfico.",
    funFact: "\"Você sabia?\" — A área sob o gráfico v × t representa o deslocamento — no MRU essa área é um retângulo simples!",
    points: 1,
    options: [
      { id: "A", text: "Uma parábola voltada para cima" },
      { id: "B", text: "Uma reta inclinada passando pela origem" },
      { id: "C", text: "Uma curva exponencial crescente" },
      { id: "D", text: "Uma reta horizontal (paralela ao eixo do tempo)" },
    ],
    correctAnswer: "D",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "Usando a equação de Torricelli (v² = v₀² + 2aΔs), um móvel parte do repouso e acelera a 4 m/s² durante 18 m. Qual é a velocidade final?",
    tip: "Substitua os valores na equação: v₀ = 0, a = 4 m/s² e Δs = 18 m. Não esqueça de tirar a raiz quadrada.",
    funFact: "\"Você sabia?\" — Evangelista Torricelli foi aluno de Galileu; além da equação cinemática, ele inventou o barômetro de mercúrio em 1644.",
    points: 1,
    options: [
      { id: "A", text: "6 m/s" },
      { id: "B", text: "12 m/s" },
      { id: "C", text: "8 m/s" },
      { id: "D", text: "16 m/s" },
    ],
    correctAnswer: "B",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "Um carro aumenta sua velocidade de 10 m/s para 30 m/s em 5 segundos. Qual é a aceleração média do carro?",
    tip: "Aceleração média é a variação de velocidade dividida pelo intervalo de tempo: a = Δv/Δt.",
    funFact: "\"Você sabia?\" — Carros esportivos de corrida chegam a ter acelerações de até 20 m/s², o que equivale a 2g (duas vezes a gravidade)!",
    points: 1,
    options: [
      { id: "A", text: "2 m/s²" },
      { id: "B", text: "3 m/s²" },
      { id: "C", text: "4 m/s²" },
      { id: "D", text: "5 m/s²" },
    ],
    correctAnswer: "C",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "Um objeto é solto do repouso em queda livre (g = 10 m/s²). Qual é a velocidade do objeto após 3 segundos?",
    tip: "Na queda livre, a velocidade cresce a cada segundo: v = g × t. Multiplique g pelo tempo.",
    funFact: "\"Você sabia?\" — Galileu demonstrou que objetos de massas diferentes caem com a mesma aceleração, derrubando uma crença de quase 2000 anos de Aristóteles.",
    points: 1,
    options: [
      { id: "A", text: "30 m/s" },
      { id: "B", text: "45 m/s" },
      { id: "C", text: "15 m/s" },
      { id: "D", text: "60 m/s" },
    ],
    correctAnswer: "A",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "Um trem percorre 240 km em 3 horas com velocidade constante. Qual é a velocidade do trem?",
    tip: "No MRU, velocidade = espaço ÷ tempo. Certifique-se de usar as mesmas unidades.",
    funFact: "\"Você sabia?\" — O trem-bala Shinkansen no Japão opera a velocidades acima de 300 km/h, mantendo MRU nos trechos retos da linha.",
    points: 1,
    options: [
      { id: "A", text: "40 km/h" },
      { id: "B", text: "60 km/h" },
      { id: "C", text: "70 km/h" },
      { id: "D", text: "80 km/h" },
    ],
    correctAnswer: "D",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "Um móvel em MRUV tem velocidade inicial v₀ = 5 m/s e aceleração a = 3 m/s². Qual é a velocidade após 4 segundos?",
    tip: "Use a equação v = v₀ + a·t. Substitua os valores diretamente.",
    funFact: "\"Você sabia?\" — A equação v = v₀ + at é linear: quando grafamos v × t num MRUV, obtemos sempre uma reta inclinada.",
    points: 1,
    options: [
      { id: "A", text: "12 m/s" },
      { id: "B", text: "17 m/s" },
      { id: "C", text: "20 m/s" },
      { id: "D", text: "15 m/s" },
    ],
    correctAnswer: "B",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "Um objeto é largado do repouso e leva 4 segundos para atingir o solo em queda livre (g = 10 m/s²). De que altura foi lançado?",
    tip: "A equação da altura em queda livre é h = ½g·t². Substitua g = 10 e t = 4.",
    funFact: "\"Você sabia?\" — Em 4 segundos de queda livre, um objeto percorre 80 m — o equivalente a um prédio de aproximadamente 27 andares!",
    points: 1,
    options: [
      { id: "A", text: "40 m" },
      { id: "B", text: "160 m" },
      { id: "C", text: "80 m" },
      { id: "D", text: "120 m" },
    ],
    correctAnswer: "C",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "Um ciclista em MRU parte da origem (s₀ = 0) com velocidade de 8 m/s. Qual é a posição do ciclista após 10 segundos?",
    tip: "Com posição inicial zero, a equação fica simples: s = v·t.",
    funFact: "\"Você sabia?\" — Em 10 segundos a 8 m/s, o ciclista percorre 80 m — a distância de uma piscina olímpica!",
    points: 1,
    options: [
      { id: "A", text: "80 m" },
      { id: "B", text: "88 m" },
      { id: "C", text: "160 m" },
      { id: "D", text: "40 m" },
    ],
    correctAnswer: "A",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Usando a equação de Torricelli, um objeto passa de v₀ = 20 m/s a v = 30 m/s percorrendo 25 m. Qual é a aceleração?",
    tip: "Isole 'a' na equação de Torricelli: a = (v² − v₀²) / (2Δs).",
    funFact: "\"Você sabia?\" — A equação de Torricelli é extremamente útil porque elimina o tempo da equação — ideal quando o tempo não é fornecido no problema.",
    points: 1,
    options: [
      { id: "A", text: "5 m/s²" },
      { id: "B", text: "10 m/s²" },
      { id: "C", text: "15 m/s²" },
      { id: "D", text: "20 m/s²" },
    ],
    correctAnswer: "B",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "No gráfico s × t de um MRU, se a reta passa pela origem e tem inclinação negativa (caindo da esquerda para a direita), como é o movimento?",
    tip: "Inclinação negativa no gráfico s × t significa velocidade negativa, ou seja, o objeto se afasta no sentido oposto ao positivo.",
    funFact: "\"Você sabia?\" — A escolha do sentido positivo é convencional: o que importa é a consistência dentro do problema, não qual sentido é 'melhor'.",
    points: 1,
    options: [
      { id: "A", text: "Em sentido positivo com velocidade crescente" },
      { id: "B", text: "Em sentido positivo com velocidade decrescente" },
      { id: "C", text: "Em repouso" },
      { id: "D", text: "Em sentido negativo com velocidade constante" },
    ],
    correctAnswer: "D",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "Um objeto em queda livre parte do repouso (g = 10 m/s²) e cai durante 5 segundos. Qual é a velocidade no instante do impacto com o solo?",
    tip: "Use v = g·t. Multiplique a aceleração gravitacional pelo tempo total de queda.",
    funFact: "\"Você sabia?\" — 50 m/s equivale a 180 km/h! É por isso que a queda livre é tão perigosa sem equipamento adequado.",
    points: 1,
    options: [
      { id: "A", text: "100 m/s" },
      { id: "B", text: "25 m/s" },
      { id: "C", text: "50 m/s" },
      { id: "D", text: "125 m/s" },
    ],
    correctAnswer: "C",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "A equação horária de um MRU é s = 10 + 5t (em metros e segundos). Quais são a posição inicial e a velocidade do móvel?",
    tip: "Na equação s = s₀ + v·t, o termo independente é s₀ e o coeficiente de t é a velocidade.",
    funFact: "\"Você sabia?\" — A equação horária do MRU é matematicamente idêntica à função afim y = b + ax estudada em matemática.",
    points: 1,
    options: [
      { id: "A", text: "s₀ = 10 m e v = 5 m/s" },
      { id: "B", text: "s₀ = 5 m e v = 10 m/s" },
      { id: "C", text: "s₀ = 0 m e v = 15 m/s" },
      { id: "D", text: "s₀ = 15 m e v = 0 m/s" },
    ],
    correctAnswer: "A",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Um carro desacelera de 20 m/s até parar completamente em 4 segundos. Qual é o módulo da aceleração (desaceleração)?",
    tip: "Aceleração = variação de velocidade / tempo. A velocidade final é zero.",
    funFact: "\"Você sabia?\" — A distância de frenagem de um carro a 72 km/h (= 20 m/s) com essa desaceleração é de 40 m — quase meio quarteirão!",
    points: 1,
    options: [
      { id: "A", text: "4 m/s²" },
      { id: "B", text: "5 m/s²" },
      { id: "C", text: "6 m/s²" },
      { id: "D", text: "8 m/s²" },
    ],
    correctAnswer: "B",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "Um corpo percorre 90 m em 6 segundos com velocidade constante. Qual é a velocidade média do corpo?",
    tip: "Velocidade média = espaço percorrido ÷ tempo gasto.",
    funFact: "\"Você sabia?\" — 15 m/s equivale a 54 km/h — uma velocidade típica de ciclistas de estrada profissionais em trechos planos!",
    points: 1,
    options: [
      { id: "A", text: "6 m/s" },
      { id: "B", text: "9 m/s" },
      { id: "C", text: "12 m/s" },
      { id: "D", text: "15 m/s" },
    ],
    correctAnswer: "D",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "Um MRUV tem velocidade inicial v₀ = 0 e aceleração a = 5 m/s², partindo da posição s₀ = 0. Qual é a equação horária da posição?",
    tip: "Use s = s₀ + v₀·t + ½a·t². Com s₀ = 0 e v₀ = 0, simplifica bastante.",
    funFact: "\"Você sabia?\" — A equação s = ½at² para queda livre foi deduzida por Galileu, que media o tempo com um pêndulo e usava planos inclinados para diminuir a aceleração e poder fazer medições precisas.",
    points: 1,
    options: [
      { id: "A", text: "s = 5t" },
      { id: "B", text: "s = 5t²" },
      { id: "C", text: "s = 2,5t²" },
      { id: "D", text: "s = 0,5t" },
    ],
    correctAnswer: "C",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "De que altura mínima deve cair um objeto para atingir velocidade de 20 m/s ao tocar o solo? (g = 10 m/s²)",
    tip: "Use a equação de Torricelli com v₀ = 0: v² = 2gh. Isole h.",
    funFact: "\"Você sabia?\" — Para atingir 20 m/s (72 km/h), basta cair de apenas 20 m — a altura de um prédio de 6 andares!",
    points: 1,
    options: [
      { id: "A", text: "20 m" },
      { id: "B", text: "40 m" },
      { id: "C", text: "10 m" },
      { id: "D", text: "30 m" },
    ],
    correctAnswer: "A",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "Um trem em MRU parte da posição s₀ = 100 m com velocidade v = 20 m/s. Em que instante o trem passa pela posição s = 300 m?",
    tip: "Use a equação s = s₀ + v·t e substitua s = 300. Isole t.",
    funFact: "\"Você sabia?\" — Estações de metrô usam MRU entre paradas: nos trechos retos, o trem mantém velocidade constante antes de frear.",
    points: 1,
    options: [
      { id: "A", text: "5 s" },
      { id: "B", text: "10 s" },
      { id: "C", text: "15 s" },
      { id: "D", text: "20 s" },
    ],
    correctAnswer: "B",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "Um objeto em MRUV parte com v₀ = 10 m/s e aceleração a = 2 m/s². Qual é o deslocamento total nos primeiros 5 segundos?",
    tip: "Use Δs = v₀·t + ½a·t². Substitua v₀ = 10, a = 2 e t = 5.",
    funFact: "\"Você sabia?\" — O MRUV com aceleração positiva descreve o movimento de um foguete logo após o lançamento, enquanto os motores aceleram.",
    points: 1,
    options: [
      { id: "A", text: "50 m" },
      { id: "B", text: "60 m" },
      { id: "C", text: "70 m" },
      { id: "D", text: "75 m" },
    ],
    correctAnswer: "D",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Qual é o valor da aceleração gravitacional (g) adotado nos cálculos de queda livre no Ensino Médio brasileiro?",
    tip: "Esse valor é uma convenção pedagógica para facilitar cálculos; o valor real varia um pouco com a latitude e altitude.",
    funFact: "\"Você sabia?\" — O valor exato de g varia de 9,78 m/s² no Equador a 9,83 m/s² nos polos; o Brasil usa 9,8 ou 10 m/s² dependendo do contexto.",
    points: 1,
    options: [
      { id: "A", text: "10 m/s²" },
      { id: "B", text: "9 m/s²" },
      { id: "C", text: "8 m/s²" },
      { id: "D", text: "12 m/s²" },
    ],
    correctAnswer: "A",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Em um MRU com velocidade negativa, como é a inclinação da reta no gráfico s × t?",
    tip: "O sinal da velocidade determina o sinal da inclinação da reta no gráfico s × t.",
    funFact: "\"Você sabia?\" — Uma reta com inclinação negativa em s × t indica que o objeto se aproxima da origem, podendo até cruzá-la e continuar para posições negativas.",
    points: 1,
    options: [
      { id: "A", text: "Inclinação positiva (reta subindo)" },
      { id: "B", text: "Reta horizontal (sem inclinação)" },
      { id: "C", text: "Inclinação negativa (reta descendo)" },
      { id: "D", text: "Curva parabólica" },
    ],
    correctAnswer: "C",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Usando a equação de Torricelli, um corpo parte do repouso e percorre 45 m com aceleração de 10 m/s². Qual é a velocidade final?",
    tip: "v² = v₀² + 2aΔs, com v₀ = 0, a = 10 m/s² e Δs = 45 m. Calcule v² e tire a raiz.",
    funFact: "\"Você sabia?\" — 30 m/s é equivalente a 108 km/h — velocidade de rodovias brasileiras. Esses 45 m representam a distância de frenagem de um carro nessa velocidade!",
    points: 1,
    options: [
      { id: "A", text: "20 m/s" },
      { id: "B", text: "30 m/s" },
      { id: "C", text: "40 m/s" },
      { id: "D", text: "50 m/s" },
    ],
    correctAnswer: "B",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Como é representado o gráfico de velocidade × tempo (v × t) de um MRUV (Movimento Retilíneo Uniformemente Variado)?",
    tip: "No MRUV, a velocidade varia uniformemente com o tempo. Pense em como esse comportamento aparece num gráfico.",
    funFact: "\"Você sabia?\" — A área sob a reta do gráfico v × t do MRUV corresponde ao deslocamento — ela forma um trapézio ou triângulo, dependendo da situação.",
    points: 1,
    options: [
      { id: "A", text: "Uma parábola côncava para cima" },
      { id: "B", text: "Uma curva exponencial" },
      { id: "C", text: "Uma reta horizontal" },
      { id: "D", text: "Uma reta oblíqua (inclinada)" },
    ],
    correctAnswer: "D",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Em queda livre com g = 10 m/s², qual é a relação correta entre a altura percorrida h e o tempo de queda t (partindo do repouso)?",
    tip: "Derive da equação do MRUV com v₀ = 0: quais termos sobram na equação de posição?",
    funFact: "\"Você sabia?\" — Essa relação quadrática (h ∝ t²) significa que nos primeiros 1 s o objeto cai 5 m, nos primeiros 2 s cai 20 m, e nos primeiros 3 s cai 45 m.",
    points: 1,
    options: [
      { id: "A", text: "h = ½g·t²" },
      { id: "B", text: "h = g·t" },
      { id: "C", text: "h = 2g·t²" },
      { id: "D", text: "h = ½g/t²" },
    ],
    correctAnswer: "A",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Um móvel em MRUV tem v₀ = 6 m/s e a = 4 m/s². Usando a equação de Torricelli, qual é a velocidade após percorrer 20 m?",
    tip: "v² = v₀² + 2aΔs. Substitua: v₀ = 6, a = 4 e Δs = 20. Calcule v² e extraia a raiz.",
    funFact: "\"Você sabia?\" — v² = 36 + 160 = 196, portanto v = √196 = 14 m/s. Lembre: √196 = 14 porque 14² = 196.",
    points: 1,
    options: [
      { id: "A", text: "10 m/s" },
      { id: "B", text: "12 m/s" },
      { id: "C", text: "14 m/s" },
      { id: "D", text: "16 m/s" },
    ],
    correctAnswer: "C",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "A equação horária de um MRU é s = 5 + 3t (m, s). Em que posição estará o objeto no instante t = 7 s?",
    tip: "Substitua t = 7 diretamente na equação e calcule.",
    funFact: "\"Você sabia?\" — Equações horárias são chamadas assim porque descrevem o estado do objeto em qualquer instante ('hora') do movimento.",
    points: 1,
    options: [
      { id: "A", text: "21 m" },
      { id: "B", text: "26 m" },
      { id: "C", text: "35 m" },
      { id: "D", text: "30 m" },
    ],
    correctAnswer: "B",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Um objeto cai em queda livre de uma altura de 125 m (g = 10 m/s²). Qual é a velocidade ao atingir o solo?",
    tip: "Use v² = 2gh, com h = 125 m e g = 10 m/s². Calcule v² e extraia a raiz quadrada.",
    funFact: "\"Você sabia?\" — 50 m/s são 180 km/h! Isso explica por que paraquedistas abrem o paraquedas bem antes do solo — a resistência do ar desacelera de ~60 m/s para ~5 m/s.",
    points: 1,
    options: [
      { id: "A", text: "25 m/s" },
      { id: "B", text: "35 m/s" },
      { id: "C", text: "40 m/s" },
      { id: "D", text: "50 m/s" },
    ],
    correctAnswer: "D",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Um carro em MRUV parte do repouso e atinge 30 m/s em 6 segundos. Qual é a aceleração do carro?",
    tip: "Com v₀ = 0 e conhecendo v e t, use a = (v − v₀)/t.",
    funFact: "\"Você sabia?\" — 5 m/s² equivale a 0,5 g; pilotos de Fórmula 1 suportam até 5 g na frenagem — 50 m/s²!",
    points: 1,
    options: [
      { id: "A", text: "5 m/s²" },
      { id: "B", text: "4 m/s²" },
      { id: "C", text: "6 m/s²" },
      { id: "D", text: "3 m/s²" },
    ],
    correctAnswer: "A",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Um objeto em MRU se move com velocidade de 12 m/s. Qual é o deslocamento total em 15 segundos?",
    tip: "No MRU, deslocamento = velocidade × tempo.",
    funFact: "\"Você sabia?\" — 180 m é a distância de dois campos de futebol lado a lado! Em apenas 15 segundos a 12 m/s (43 km/h) você os percorre completamente.",
    points: 1,
    options: [
      { id: "A", text: "27 m" },
      { id: "B", text: "144 m" },
      { id: "C", text: "180 m" },
      { id: "D", text: "120 m" },
    ],
    correctAnswer: "C",
  },
];
