export const questoesPortugues6AnoB3Av1 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'O que são pronomes pessoais retos?',
    tip: 'Pensa assim: quando você fala "eu" ou "ele" em vez do seu próprio nome, você está usando um pronome pessoal. Ele "faz o papel" da pessoa na frase!',
    funFact: 'A palavra "pronome" vem do latim e quer dizer "no lugar do nome"! Por isso ela sempre substitui um nome numa frase.',
    points: 1,
    options: [
      { id: 'A', text: 'Palavras que substituem o nome de quem fala ou de quem se fala, como "eu, tu, ele"' },
      { id: 'B', text: 'Palavras que indicam quantidade' },
      { id: 'C', text: 'Palavras que indicam ação' },
      { id: 'D', text: 'Palavras que indicam qualidade' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'Qual pronome pessoal reto substitui "o Bernardo" na frase "Bernardo foi à escola"?',
    tip: 'Bernardo é uma pessoa do sexo masculino, falada por outra pessoa (não é quem fala nem quem ouve). Qual pronome combina com isso?',
    funFact: '"Ele" e "ela" são chamados de 3ª pessoa — porque não são quem fala (1ª) nem quem ouve (2ª), e sim de quem se fala!',
    points: 1,
    options: [
      { id: 'A', text: 'Eu' },
      { id: 'B', text: 'Ele' },
      { id: 'C', text: 'Nós' },
      { id: 'D', text: 'Vocês' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'Os pronomes "meu, teu, seu, nosso" são chamados de:',
    tip: 'Repara na palavra "possessivos" — ela lembra "possuir", que é o mesmo que "ter" ou "ser dono de algo". Esses pronomes mostram de quem é a coisa!',
    funFact: 'Quando você diz "meu lanche", ninguém mais pode reclamar dele — o pronome possessivo já deixou bem claro de quem é!',
    points: 1,
    options: [
      { id: 'A', text: 'Pronomes pessoais' },
      { id: 'B', text: 'Pronomes demonstrativos' },
      { id: 'C', text: 'Pronomes possessivos' },
      { id: 'D', text: 'Pronomes indefinidos' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'Na frase "Este livro é meu", a palavra "este" é um pronome:',
    tip: '"Este" mostra que o livro está pertinho de quem fala. Pronomes que mostram a posição de algo (perto, longe) são demonstrativos!',
    funFact: 'Existem três "distâncias" nos pronomes demonstrativos: este (perto de mim), esse (perto de você) e aquele (longe dos dois)!',
    points: 1,
    options: [
      { id: 'A', text: 'Pessoal' },
      { id: 'B', text: 'Possessivo' },
      { id: 'C', text: 'Indefinido' },
      { id: 'D', text: 'Demonstrativo' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'Qual das opções abaixo é um pronome possessivo?',
    tip: 'Pergunte: essa palavra mostra de quem é alguma coisa? "Nosso lanche" é o lanche que pertence a "nós".',
    funFact: '"Nosso" é um dos poucos pronomes que já vem no plural de gente — ele sempre fala de duas ou mais pessoas, incluindo quem está falando!',
    points: 1,
    options: [
      { id: 'A', text: 'Aquele' },
      { id: 'B', text: 'Nosso' },
      { id: 'C', text: 'Isto' },
      { id: 'D', text: 'Algum' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'Complete: "___ estudo todos os dias para a prova." Qual pronome pessoal completa corretamente?',
    tip: 'Quem está "estudando" na frase é a própria pessoa que fala. Qual pronome representa quem fala sozinho?',
    funFact: '"Eu" é sempre a 1ª pessoa do singular — é o pronome que você usa quando fala de si mesmo!',
    points: 1,
    options: [
      { id: 'A', text: 'Eu' },
      { id: 'B', text: 'Ele' },
      { id: 'C', text: 'Eles' },
      { id: 'D', text: 'Vós' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'Os pronomes demonstrativos servem para:',
    tip: 'Pensa em "isto", "isso" e "aquilo" — eles ajudam a "apontar" para onde ou quando algo está.',
    funFact: 'Os demonstrativos também marcam tempo! "Este ano" fala do presente, e "aquele dia" fala de um tempo bem distante no passado.',
    points: 1,
    options: [
      { id: 'A', text: 'Indicar posse' },
      { id: 'B', text: 'Indicar quantidade' },
      { id: 'C', text: 'Substituir nomes próprios' },
      { id: 'D', text: 'Indicar a posição de algo no espaço ou no tempo' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'Qual pronome indica algo indefinido, sem precisar quem ou quanto?',
    tip: 'Repare que "algum" não diz exatamente quem é — é por isso que ele é chamado de "indefinido", ou seja, sem definição clara.',
    funFact: 'Pronomes indefinidos são ótimos para mistérios! "Alguém" bateu na porta... mas quem será?',
    points: 1,
    options: [
      { id: 'A', text: 'Este' },
      { id: 'B', text: 'Meu' },
      { id: 'C', text: 'Algum' },
      { id: 'D', text: 'Ele' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'Na frase "Nós vamos ao parque", o pronome pessoal "nós" se refere a:',
    tip: '"Nós" sempre inclui a pessoa que está falando, junto com mais alguém. É diferente de "eu", que é só uma pessoa.',
    funFact: '"Nós" é a 1ª pessoa do plural — perfeito para quando você e seus amigos combinam de fazer algo juntos!',
    points: 1,
    options: [
      { id: 'A', text: 'Quem fala, incluindo outras pessoas' },
      { id: 'B', text: 'Só quem ouve' },
      { id: 'C', text: 'Uma pessoa distante' },
      { id: 'D', text: 'Um objeto' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: '"Aquele carro é bonito." A palavra destacada é um pronome:',
    tip: '"Aquele" mostra que o carro está longe de quem fala e de quem ouve. Isso é uma pista de localização — típico dos demonstrativos!',
    funFact: '"Aquele" é o pronome demonstrativo campeão de distância — ele serve para apontar coisas bem longe, até em outro país!',
    points: 1,
    options: [
      { id: 'A', text: 'Possessivo' },
      { id: 'B', text: 'Pessoal' },
      { id: 'C', text: 'Indefinido' },
      { id: 'D', text: 'Demonstrativo' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'Substitua "a Maria" pelo pronome pessoal correto na frase "A Maria comprou um presente":',
    tip: 'Maria é uma pessoa do sexo feminino, e é dela que se fala (não é quem fala nem quem ouve). Qual pronome combina?',
    funFact: '"Ela" pode substituir qualquer nome feminino — de uma colega de classe até uma personagem de história!',
    points: 1,
    options: [
      { id: 'A', text: 'Eu' },
      { id: 'B', text: 'Ela' },
      { id: 'C', text: 'Eles' },
      { id: 'D', text: 'Nós' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: '"Vossa Senhoria" é um pronome de tratamento usado para:',
    tip: 'Pense em cartas muito formais, como as que se escrevem para autoridades importantes. Esse tipo de pronome mostra bastante respeito.',
    funFact: 'Existem vários pronomes de tratamento formais, como "Vossa Excelência" (para presidentes) e "Vossa Majestade" (para reis e rainhas)!',
    points: 1,
    options: [
      { id: 'A', text: 'Amigos próximos' },
      { id: 'B', text: 'Crianças' },
      { id: 'C', text: 'Pessoas com quem se tem grande respeito/formalidade' },
      { id: 'D', text: 'Animais de estimação' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'Na frase "O caderno é seu, não é meu", os pronomes destacados indicam:',
    tip: '"Seu" e "meu" respondem à pergunta "de quem é?". Isso é a marca registrada dos pronomes possessivos.',
    funFact: 'Numa mesma frase você pode comparar posses diferentes, como nesse exemplo — isso ajuda a deixar bem claro de quem é cada coisa!',
    points: 1,
    options: [
      { id: 'A', text: 'Posse' },
      { id: 'B', text: 'Lugar' },
      { id: 'C', text: 'Tempo' },
      { id: 'D', text: 'Quantidade' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'Qual frase usa corretamente um pronome demonstrativo?',
    tip: 'Procure a palavra que "aponta" para algo que foi dito, sem repetir tudo de novo. "Isso" está no lugar da frase inteira que a pessoa falou!',
    funFact: '"Isso" é super prático — ele evita que a gente repita frases inteiras, deixando a conversa mais rápida e leve!',
    points: 1,
    options: [
      { id: 'A', text: 'Ele foi à escola' },
      { id: 'B', text: 'Nosso time venceu' },
      { id: 'C', text: 'Alguém chegou' },
      { id: 'D', text: 'Isso que você disse foi engraçado' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'Complete com o pronome pessoal correto: "___ (vocês) vão à festa?"',
    tip: 'A dica já está entre parênteses na pergunta! Qual pronome representa um grupo de pessoas com quem se fala?',
    funFact: '"Vocês" é usado no Brasil no lugar de "vós", que hoje em dia quase não é mais usado no dia a dia!',
    points: 1,
    options: [
      { id: 'A', text: 'Eu' },
      { id: 'B', text: 'Ele' },
      { id: 'C', text: 'Vocês' },
      { id: 'D', text: 'Eu e ele' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'Na frase "Estes brinquedos são meus, aqueles são teus", quantos pronomes diferentes aparecem?',
    tip: 'Conte com calma: "estes", "meus", "aqueles" e "teus" — mas repare que "meus" e "teus" são do mesmo tipo (possessivos) e "estes"/"aqueles" são do mesmo tipo (demonstrativos). Quantos tipos diferentes existem no total contando cada palavra?',
    funFact: 'Nessa frase dá pra ver dois tipos de pronomes trabalhando juntos: demonstrativos (mostrando qual brinquedo) e possessivos (mostrando de quem é)!',
    points: 1,
    options: [
      { id: 'A', text: 'Um' },
      { id: 'B', text: 'Três' },
      { id: 'C', text: 'Cinco' },
      { id: 'D', text: 'Nenhum' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'Qual pronome indefinido completa: "___ pessoa viu o acidente."',
    tip: 'A frase fala de uma quantidade que não existiu — ninguém viu! Qual palavra mostra "quantidade zero" de forma indefinida?',
    funFact: '"Nenhuma" e "nenhum" são pronomes indefinidos negativos — eles dizem que a quantidade de algo é zero!',
    points: 1,
    options: [
      { id: 'A', text: 'Nenhuma' },
      { id: 'B', text: 'Minha' },
      { id: 'C', text: 'Aquela' },
      { id: 'D', text: 'Ela' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'Assinale a frase com pronome possessivo:',
    tip: 'Procure a palavra que mostra de quem é o livro. Ela está bem ao lado da palavra "livro"!',
    funFact: 'Repare que essa frase tem dois tipos de pronome ao mesmo tempo: "este" (demonstrativo) e "meu" (possessivo) trabalhando juntos!',
    points: 1,
    options: [
      { id: 'A', text: 'Isso é interessante' },
      { id: 'B', text: 'Alguém chamou' },
      { id: 'C', text: 'Eles saíram' },
      { id: 'D', text: 'Este é o meu livro favorito' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'O pronome "tu" é usado para se referir a:',
    tip: '"Tu" é a 2ª pessoa do singular — pense em quem está do outro lado da conversa, ouvindo o que você fala.',
    funFact: 'Em alguns estados do Brasil, como o Rio Grande do Sul, as pessoas usam "tu" no dia a dia com muita frequência!',
    points: 1,
    options: [
      { id: 'A', text: 'Um grupo de pessoas' },
      { id: 'B', text: 'A pessoa com quem se fala' },
      { id: 'C', text: 'Algo distante' },
      { id: 'D', text: 'Um objeto' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'Na frase "Aquilo não me pertence", o pronome demonstrativo indica algo:',
    tip: '"Aquilo" é da mesma família de "aquele" — lembra que essa família de pronomes indica sempre a maior distância possível!',
    funFact: '"Aquilo" é usado para coisas sem nome definido ou para ideias, como em "Aquilo que ele fez foi muito gentil"!',
    points: 1,
    options: [
      { id: 'A', text: 'Perto de quem fala' },
      { id: 'B', text: 'Perto de quem ouve' },
      { id: 'C', text: 'Distante de ambos' },
      { id: 'D', text: 'Que pertence a alguém' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Bernardo disse: "Este é o meu caderno de matemática." Qual pronome indica que o caderno pertence a Bernardo?',
    tip: 'Procure a palavrinha que responde "de quem é o caderno?" — ela está bem colada ao nome "caderno".',
    funFact: 'O pronome "meu" muda de acordo com quem fala: se fosse a irmã do Bernardo falando, ela diria "meu" também, mas se referindo ao caderno dela!',
    points: 1,
    options: [
      { id: 'A', text: 'Este' },
      { id: 'B', text: 'É' },
      { id: 'C', text: 'Meu' },
      { id: 'D', text: 'De' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Bernardo e seus amigos combinaram um passeio. Ele disse: "Nós vamos ao museu no sábado." O pronome "nós" mostra que:',
    tip: 'Lembra que "nós" sempre inclui quem fala mais outras pessoas. Bernardo está falando de um grupo, não sozinho!',
    funFact: 'Museus são lugares incríveis para descobrir coisas novas — alguns têm até dinossauros e naves espaciais de verdade (ou réplicas bem realistas)!',
    points: 1,
    options: [
      { id: 'A', text: 'Só Bernardo vai' },
      { id: 'B', text: 'Ninguém vai' },
      { id: 'C', text: 'Alguém desconhecido vai' },
      { id: 'D', text: 'Bernardo e mais pessoas vão juntos' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'A professora perguntou a Bernardo: "De quem é esta mochila?" Bernardo respondeu: "É minha." Qual é o pronome possessivo na resposta?',
    tip: 'A resposta de Bernardo responde diretamente "de quem é" — essa palavrinha mostra a posse da mochila.',
    funFact: '"Minha" e "meu" são a mesma ideia de posse, só que "minha" combina com palavras femininas, como "mochila"!',
    points: 1,
    options: [
      { id: 'A', text: 'É' },
      { id: 'B', text: 'Minha' },
      { id: 'C', text: 'Esta' },
      { id: 'D', text: 'De' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Bernardo apontou para um livro na estante e disse: "Aquele é o livro que eu quero ler." O pronome "aquele" indica que o livro está:',
    tip: 'Se Bernardo está "apontando" de longe, que tipo de pronome demonstrativo ele usaria — o de perto ou o de longe?',
    funFact: 'Se o livro estivesse na mão de Bernardo, ele diria "este" em vez de "aquele" — os pronomes mudam conforme a distância real da coisa!',
    points: 1,
    options: [
      { id: 'A', text: 'Longe de Bernardo' },
      { id: 'B', text: 'Na mão de Bernardo' },
      { id: 'C', text: 'Dentro da mochila' },
      { id: 'D', text: 'Perto de Bernardo' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Bernardo escreveu um bilhete: "Alguém esqueceu este estojo na sala." O pronome "alguém" é do tipo:',
    tip: 'Bernardo não sabe quem esqueceu o estojo — por isso usa uma palavra que não define exatamente a pessoa.',
    funFact: 'Bilhetes de "achados e perdidos" usam muito pronomes indefinidos, como "alguém" e "qualquer pessoa", porque ainda não se sabe quem é o dono!',
    points: 1,
    options: [
      { id: 'A', text: 'Possessivo' },
      { id: 'B', text: 'Demonstrativo' },
      { id: 'C', text: 'Indefinido' },
      { id: 'D', text: 'Pessoal' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'No recreio, Bernardo disse ao amigo: "Você quer brincar comigo?" O pronome pessoal "você" se refere a:',
    tip: 'Quem está sendo convidado para brincar? É a pessoa que está ouvindo Bernardo falar.',
    funFact: 'No Brasil, "você" é usado no lugar de "tu" na maioria das regiões — é uma forma mais informal e super comum entre amigos!',
    points: 1,
    options: [
      { id: 'A', text: 'Bernardo' },
      { id: 'B', text: 'Um grupo' },
      { id: 'C', text: 'Um objeto' },
      { id: 'D', text: 'A pessoa com quem Bernardo fala' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Bernardo organizou seus brinquedos e disse: "Estes são meus carrinhos, aqueles são da minha irmã." Quantos pronomes possessivos aparecem na frase?',
    tip: 'Procure as palavras que mostram "de quem é" cada grupo de carrinhos — são duas palavrinhas parecidas!',
    funFact: '"Meus" e "minha" vêm da mesma família de posse, mas mudam de forma para combinar com "carrinhos" (masculino/plural) e "irmã" (feminino/singular)!',
    points: 1,
    options: [
      { id: 'A', text: 'Dois' },
      { id: 'B', text: 'Um' },
      { id: 'C', text: 'Três' },
      { id: 'D', text: 'Nenhum' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Bernardo perguntou: "Isso que você fez foi muito legal!" O pronome "isso" está classificado como:',
    tip: '"Isso" está apontando para uma ação que já aconteceu, sem repetir tudo de novo — essa é a função dos pronomes que "mostram" algo.',
    funFact: 'Usar "isso" no lugar de explicar tudo de novo é um jeito esperto de economizar palavras numa conversa!',
    points: 1,
    options: [
      { id: 'A', text: 'Possessivo' },
      { id: 'B', text: 'Demonstrativo' },
      { id: 'C', text: 'Pessoal' },
      { id: 'D', text: 'Indefinido' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Na agenda de Bernardo estava escrito: "Nenhum aluno pode faltar à excursão." O pronome "nenhum" indica:',
    tip: '"Nenhum" está dizendo que a quantidade de alunos que podem faltar é zero — repare que ele não define uma pessoa específica.',
    funFact: 'Excursões escolares são ótimas para aprender fora da sala de aula — museus, parques e até fábricas podem virar uma aula diferente!',
    points: 1,
    options: [
      { id: 'A', text: 'Posse' },
      { id: 'B', text: 'Lugar' },
      { id: 'C', text: 'Uma quantidade indefinida/negativa' },
      { id: 'D', text: 'Tempo' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'Bernardo terminou a prova e disse à professora: "Este exercício foi mais fácil que aquele." Os pronomes "este" e "aquele" servem para:',
    tip: 'Bernardo está comparando dois exercícios diferentes, um mais perto na memória (este) e outro mais distante (aquele) — isso é bem típico dos demonstrativos.',
    funFact: 'Parabéns por terminar o simulado de pronomes! Agora você já sabe identificar pessoais, possessivos, demonstrativos e indefinidos como um verdadeiro detetive da língua portuguesa!',
    points: 1,
    options: [
      { id: 'A', text: 'Indicar posse' },
      { id: 'B', text: 'Substituir nomes de pessoas' },
      { id: 'C', text: 'Indicar quantidade' },
      { id: 'D', text: 'Comparar a posição/distância de dois exercícios' },
    ],
    correctAnswer: 'D',
  },
];
