export const questoesCiencias8AnoB3Av2 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "Qual é a função principal do sistema locomotor?",
    tip: "Pense em tudo que te permite ficar de pé e se mover: ossos e músculos trabalhando juntos.",
    funFact: "O corpo humano tem mais de 600 músculos diferentes!",
    points: 1,
    options: [
      { id: "A", text: "digerir os alimentos" },
      { id: "B", text: "filtrar o sangue" },
      { id: "C", text: "bombear o sangue" },
      { id: "D", text: "sustentar o corpo e permitir o movimento, através do trabalho conjunto de ossos e músculos" },
    ],
    correctAnswer: "D",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "O conjunto de todos os ossos do corpo é chamado de:",
    tip: "Pense na \"estrutura\" que sustenta todo o seu corpo, formada só por ossos.",
    funFact: "O esqueleto também serve como uma espécie de \"armadura\" para proteger órgãos importantes!",
    points: 1,
    options: [
      { id: "A", text: "sistema nervoso" },
      { id: "B", text: "esqueleto" },
      { id: "C", text: "sistema digestório" },
      { id: "D", text: "sistema circulatório" },
    ],
    correctAnswer: "B",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "Aproximadamente, quantos ossos tem o esqueleto de um adulto?",
    tip: "É um número bem maior do que parece — pense em todos os ossinhos das mãos e dos pés, por exemplo.",
    funFact: "Bebês nascem com mais ossos (cerca de 300), mas alguns se fundem conforme crescem!",
    points: 1,
    options: [
      { id: "A", text: "206" },
      { id: "B", text: "50" },
      { id: "C", text: "1000" },
      { id: "D", text: "20" },
    ],
    correctAnswer: "A",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "Além de sustentar o corpo, qual é outra função importante dos ossos?",
    tip: "Pense no crânio protegendo o cérebro, ou nas costelas protegendo o coração e os pulmões.",
    funFact: "O crânio é formado por vários ossos encaixados, como um quebra-cabeça!",
    points: 1,
    options: [
      { id: "A", text: "digerir alimentos" },
      { id: "B", text: "bombear sangue" },
      { id: "C", text: "proteger órgãos internos" },
      { id: "D", text: "filtrar substâncias" },
    ],
    correctAnswer: "C",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "Dentro de alguns ossos existe a medula óssea, responsável por:",
    tip: "Pense em outro lugar além do coração onde o corpo \"fabrica\" células do sangue.",
    funFact: "A medula óssea produz hemácias, leucócitos e plaquetas — as mesmas células que vimos no sistema cardiovascular!",
    points: 1,
    options: [
      { id: "A", text: "digerir alimentos" },
      { id: "B", text: "produzir células sanguíneas" },
      { id: "C", text: "filtrar o ar" },
      { id: "D", text: "produzir hormônios do crescimento somente" },
    ],
    correctAnswer: "B",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "Os pontos de encontro entre dois ou mais ossos são chamados de:",
    tip: "Pense no joelho ou no cotovelo — qual é o nome desse \"encontro\" entre ossos que permite dobrar o corpo?",
    funFact: "Sem as articulações, seria impossível dobrar os braços ou as pernas!",
    points: 1,
    options: [
      { id: "A", text: "tendões" },
      { id: "B", text: "ligamentos" },
      { id: "C", text: "músculos" },
      { id: "D", text: "articulações" },
    ],
    correctAnswer: "D",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "As articulações que permitem bastante movimento, como o joelho e o cotovelo, são chamadas de:",
    tip: "Pense no nome que indica que essas articulações se movem bastante.",
    funFact: "O joelho é uma das articulações mais usadas do corpo, suportando bastante peso durante os movimentos!",
    points: 1,
    options: [
      { id: "A", text: "articulações fixas" },
      { id: "B", text: "articulações nervosas" },
      { id: "C", text: "articulações móveis" },
      { id: "D", text: "articulações digestivas" },
    ],
    correctAnswer: "C",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "As articulações do crânio, que quase não se movem, são chamadas de:",
    tip: "Pense no contrário de \"móvel\" — essas articulações praticamente não se movem.",
    funFact: "Essas articulações fixas ajudam a manter o crânio bem protegido e firme!",
    points: 1,
    options: [
      { id: "A", text: "articulações fixas" },
      { id: "B", text: "articulações móveis" },
      { id: "C", text: "articulações musculares" },
      { id: "D", text: "articulações sanguíneas" },
    ],
    correctAnswer: "A",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "Os músculos são tecidos capazes de:",
    tip: "Pense no que acontece com seu braço quando você o dobra — o músculo \"aperta\" e depois \"solta\".",
    funFact: "Os músculos só conseguem puxar (se contrair), nunca empurrar — por isso trabalham em pares!",
    points: 1,
    options: [
      { id: "A", text: "produzir hormônios somente" },
      { id: "B", text: "se contrair e relaxar, gerando movimento" },
      { id: "C", text: "filtrar o sangue" },
      { id: "D", text: "digerir alimentos" },
    ],
    correctAnswer: "B",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "Os músculos que controlamos de forma voluntária, como os dos braços e pernas, são chamados de:",
    tip: "Pense no nome que indica a ligação desses músculos com os ossos do esqueleto.",
    funFact: "Esses são os únicos músculos que você controla conscientemente, decidindo quando se mover!",
    points: 1,
    options: [
      { id: "A", text: "músculos lisos" },
      { id: "B", text: "músculos cardíacos" },
      { id: "C", text: "músculos nervosos" },
      { id: "D", text: "músculos esqueléticos" },
    ],
    correctAnswer: "D",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "O coração é formado por um tipo especial de músculo, chamado de:",
    tip: "Pense no nome que vem diretamente de \"coração\" (em latim, cardio).",
    funFact: "O músculo cardíaco nunca se cansa e trabalha sem parar durante toda a vida!",
    points: 1,
    options: [
      { id: "A", text: "músculo cardíaco" },
      { id: "B", text: "músculo esquelético" },
      { id: "C", text: "músculo liso" },
      { id: "D", text: "músculo ósseo" },
    ],
    correctAnswer: "A",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Os músculos que trabalham de forma involuntária, como os do estômago e intestino, são chamados de:",
    tip: "Pense no nome que indica a aparência \"lisinha\" desse tipo de músculo, sem listras.",
    funFact: "Você não controla esses músculos por vontade — eles trabalham sozinhos, como na digestão!",
    points: 1,
    options: [
      { id: "A", text: "músculos esqueléticos" },
      { id: "B", text: "músculos cardíacos" },
      { id: "C", text: "músculos lisos" },
      { id: "D", text: "músculos nervosos" },
    ],
    correctAnswer: "C",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "As estruturas que ligam os músculos aos ossos são chamadas de:",
    tip: "Pense na estrutura que \"amarra\" o músculo ao osso, permitindo que o movimento aconteça.",
    funFact: "O tendão de Aquiles, no calcanhar, é um dos tendões mais fortes do corpo!",
    points: 1,
    options: [
      { id: "A", text: "ligamentos" },
      { id: "B", text: "tendões" },
      { id: "C", text: "articulações" },
      { id: "D", text: "neurônios" },
    ],
    correctAnswer: "B",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "As estruturas que ligam um osso a outro osso, dando estabilidade às articulações, são chamadas de:",
    tip: "Pense na estrutura que \"segura\" dois ossos juntos numa articulação.",
    funFact: "Quando alguém torce o tornozelo, geralmente é um ligamento que se machuca!",
    points: 1,
    options: [
      { id: "A", text: "tendões" },
      { id: "B", text: "músculos" },
      { id: "C", text: "nervos" },
      { id: "D", text: "ligamentos" },
    ],
    correctAnswer: "D",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Qual é a diferença entre tendão e ligamento?",
    tip: "Lembre das Questões 13 e 14 — o que cada estrutura conecta?",
    funFact: "Apesar de parecidos, tendões e ligamentos têm funções bem diferentes no corpo!",
    points: 1,
    options: [
      { id: "A", text: "o tendão liga músculo a osso; o ligamento liga osso a osso" },
      { id: "B", text: "são a mesma coisa" },
      { id: "C", text: "o tendão liga osso a osso; o ligamento liga músculo a osso" },
      { id: "D", text: "nenhum dos dois tem função real" },
    ],
    correctAnswer: "A",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "Por que é importante manter uma boa postura ao sentar e ficar em pé?",
    tip: "Pense em como uma postura errada, mantida por muito tempo, pode sobrecarregar a coluna.",
    funFact: "Manter uma boa postura desde criança ajuda a evitar dores nas costas na vida adulta!",
    points: 1,
    options: [
      { id: "A", text: "porque fica mais bonito só" },
      { id: "B", text: "não tem nenhuma importância real" },
      { id: "C", text: "para evitar problemas na coluna vertebral e nos músculos" },
      { id: "D", text: "só importa para atletas" },
    ],
    correctAnswer: "C",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "Praticar exercícios físicos regularmente ajuda a:",
    tip: "Pense no mesmo princípio que vimos no sistema cardiovascular — o exercício fortalece as estruturas do corpo.",
    funFact: "Atividades como caminhar e correr ajudam a manter os ossos fortes e saudáveis!",
    points: 1,
    options: [
      { id: "A", text: "enfraquecer os ossos" },
      { id: "B", text: "não tem nenhum efeito nos ossos e músculos" },
      { id: "C", text: "prejudicar as articulações sempre" },
      { id: "D", text: "fortalecer ossos e músculos" },
    ],
    correctAnswer: "D",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "Quando uma pessoa quebra um osso, dizemos que ela teve:",
    tip: "Pense no nome específico usado para quando um osso se quebra.",
    funFact: "Os ossos têm a capacidade incrível de se regenerar e se curar depois de uma fratura!",
    points: 1,
    options: [
      { id: "A", text: "uma luxação só" },
      { id: "B", text: "uma fratura" },
      { id: "C", text: "uma digestão" },
      { id: "D", text: "um reflexo" },
    ],
    correctAnswer: "B",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "Quando uma articulação \"sai do lugar\", como pode acontecer no ombro, dizemos que a pessoa teve:",
    tip: "Cuidado para não confundir com \"fratura\" — isso é sobre o osso saindo do lugar na articulação, não quebrando.",
    funFact: "Uma luxação pode ser bem dolorida, porque também machuca os ligamentos da articulação!",
    points: 1,
    options: [
      { id: "A", text: "uma luxação" },
      { id: "B", text: "uma fratura" },
      { id: "C", text: "uma coagulação" },
      { id: "D", text: "uma digestão" },
    ],
    correctAnswer: "A",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "O leite e outros alimentos ricos em cálcio são importantes para:",
    tip: "Pense em qual estrutura do corpo precisa de cálcio para ficar forte e resistente.",
    funFact: "Durante a infância e adolescência, o cálcio é ainda mais importante, porque os ossos ainda estão crescendo!",
    points: 1,
    options: [
      { id: "A", text: "fortalecer os músculos cardíacos só" },
      { id: "B", text: "digerir melhor" },
      { id: "C", text: "fortalecer os ossos" },
      { id: "D", text: "melhorar a visão" },
    ],
    correctAnswer: "C",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Bernardo caiu de bicicleta e machucou o braço. No hospital, o médico disse que ele teve uma fratura. Isso significa que:",
    tip: "Lembre da Questão 18 — o que significa \"ter uma fratura\"?",
    funFact: "Com o tempo e o tratamento certo, o osso de Bernardo vai se regenerar!",
    points: 1,
    options: [
      { id: "A", text: "um músculo rasgou" },
      { id: "B", text: "uma articulação saiu do lugar" },
      { id: "C", text: "um nervo foi cortado" },
      { id: "D", text: "um dos ossos do braço de Bernardo quebrou" },
    ],
    correctAnswer: "D",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Bernardo está jogando futebol e corre, chuta e pula o tempo todo. Quais estruturas estão trabalhando juntas para permitir esses movimentos?",
    tip: "Pense em tudo que estudamos hoje — quais estruturas precisam trabalhar juntas para o corpo se mover?",
    funFact: "É exatamente esse trabalho em conjunto que define o \"sistema locomotor\"!",
    points: 1,
    options: [
      { id: "A", text: "só os ossos" },
      { id: "B", text: "ossos, músculos e articulações" },
      { id: "C", text: "só o sistema nervoso" },
      { id: "D", text: "só os músculos lisos" },
    ],
    correctAnswer: "B",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Bernardo sentiu o coração batendo mais forte depois de correr. Esse batimento é produzido por qual tipo de músculo?",
    tip: "Lembre da Questão 11 — qual tipo de músculo forma o coração?",
    funFact: "O músculo cardíaco de Bernardo trabalha sem descanso desde antes dele nascer!",
    points: 1,
    options: [
      { id: "A", text: "músculo cardíaco" },
      { id: "B", text: "músculo esquelético" },
      { id: "C", text: "músculo liso" },
      { id: "D", text: "músculo ósseo" },
    ],
    correctAnswer: "A",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Bernardo aprendeu que, quando ele levanta o braço, um músculo se contrai enquanto outro relaxa. Esses músculos, que ele controla por vontade, são chamados de:",
    tip: "Lembre da Questão 10 — qual é o nome dos músculos que controlamos por vontade?",
    funFact: "Os músculos esqueléticos geralmente trabalham em pares, um puxando para um lado e outro para o lado contrário!",
    points: 1,
    options: [
      { id: "A", text: "músculos lisos" },
      { id: "B", text: "músculos cardíacos" },
      { id: "C", text: "músculos esqueléticos (voluntários)" },
      { id: "D", text: "músculos nervosos" },
    ],
    correctAnswer: "C",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Bernardo quer saber qual estrutura liga o músculo da sua coxa ao osso da perna, permitindo que ele chute a bola.",
    tip: "Lembre da Questão 13 — qual estrutura liga músculo a osso?",
    funFact: "Sem os tendões, a força dos músculos de Bernardo não chegaria até os ossos para gerar movimento!",
    points: 1,
    options: [
      { id: "A", text: "o ligamento" },
      { id: "B", text: "o nervo" },
      { id: "C", text: "a articulação" },
      { id: "D", text: "o tendão" },
    ],
    correctAnswer: "D",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Bernardo torceu o tornozelo jogando bola e o médico disse que ele machucou um ligamento. Qual é a função dos ligamentos?",
    tip: "Lembre da Questão 14 — qual é a função específica dos ligamentos?",
    funFact: "Esse tipo de lesão é bem comum em esportes que envolvem corrida e mudanças rápidas de direção!",
    points: 1,
    options: [
      { id: "A", text: "ligar um osso a outro, dando estabilidade à articulação" },
      { id: "B", text: "ligar músculo a osso" },
      { id: "C", text: "bombear sangue" },
      { id: "D", text: "produzir células sanguíneas" },
    ],
    correctAnswer: "A",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Bernardo bebe leite todos os dias. Isso ajuda principalmente a:",
    tip: "Lembre da Questão 20 — para que serve o cálcio presente no leite?",
    funFact: "Além do leite, outros alimentos como queijo e iogurte também são boas fontes de cálcio!",
    points: 1,
    options: [
      { id: "A", text: "fortalecer só os músculos cardíacos" },
      { id: "B", text: "fortalecer os ossos, por causa do cálcio" },
      { id: "C", text: "melhorar a audição" },
      { id: "D", text: "melhorar a digestão" },
    ],
    correctAnswer: "B",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Bernardo pratica exercícios físicos regularmente. Isso ajuda a fortalecer:",
    tip: "Lembre da Questão 17 — o que o exercício físico fortalece no corpo?",
    funFact: "Os exercícios também ajudam a manter as articulações de Bernardo mais saudáveis e flexíveis!",
    points: 1,
    options: [
      { id: "A", text: "só os ossos" },
      { id: "B", text: "só os músculos" },
      { id: "C", text: "os ossos e os músculos" },
      { id: "D", text: "nenhum dos dois" },
    ],
    correctAnswer: "C",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Bernardo está estudando as articulações do corpo e quer saber qual tipo permite mais movimento: a do crânio ou a do joelho.",
    tip: "Lembre das Questões 7 e 8 — qual é a diferença entre articulações móveis e fixas?",
    funFact: "Cada tipo de articulação tem uma função específica: as fixas protegem, as móveis permitem o movimento!",
    points: 1,
    options: [
      { id: "A", text: "a do crânio, porque é fixa" },
      { id: "B", text: "nenhuma das duas se move" },
      { id: "C", text: "as duas se movem igualmente" },
      { id: "D", text: "a do joelho, porque é uma articulação móvel, diferente da fixa do crânio" },
    ],
    correctAnswer: "D",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Revisando tudo: qual é a principal função do sistema locomotor no corpo de Bernardo?",
    tip: "Pense em tudo que vimos hoje: ossos, articulações, músculos, tendões e ligamentos — todos trabalham juntos para esse objetivo final.",
    funFact: "Parabéns! Agora você entende como o seu corpo consegue se sustentar e se mover todos os dias!",
    points: 1,
    options: [
      { id: "A", text: "digerir os alimentos que ele come" },
      { id: "B", text: "sustentar o corpo e permitir o movimento, através do trabalho conjunto de ossos, músculos e articulações" },
      { id: "C", text: "filtrar o sangue nos rins" },
      { id: "D", text: "realizar a troca gasosa nos pulmões" },
    ],
    correctAnswer: "B",
  },
];
