export const questoesIngles9AnoB4Av2 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "Read this excerpt: \"Scientists at Cambridge announced they have developed a new vaccine showing 70% effectiveness against a form of malaria affecting millions in sub-Saharan Africa, marking a significant breakthrough in tropical disease research.\" What is the MAIN IDEA of this passage?",
    tip: "A ideia principal é a informação mais importante do texto — é o que o parágrafo inteiro está comunicando, em uma frase.",
    funFact: "Reading for main idea is a key academic skill. In journalism, it is called the 'inverted pyramid': the most important information comes first, followed by supporting details. This is why the first sentence of a news article is crucial.",
    points: 1,
    options: [
      { id: "A", text: "Scientists have developed a potentially effective new vaccine against malaria" },
      { id: "B", text: "Cambridge University is the world's leading institution for medical research" },
      { id: "C", text: "Malaria has been completely eliminated from sub-Saharan Africa" },
      { id: "D", text: "Vaccines are always 100% effective against all tropical diseases" },
    ],
    correctAnswer: "A",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "Using the same Cambridge vaccine excerpt: \"...a new vaccine that may prevent a form of malaria affecting millions in sub-Saharan Africa.\" What can we INFER about malaria in sub-Saharan Africa?",
    tip: "Inferir significa concluir algo que não está dito explicitamente no texto, mas que é sugerido pelas informações presentes.",
    funFact: "Inference is the most sophisticated reading comprehension skill. It requires combining what the text says with what you already know. The word 'affecting millions' implies the disease is widespread and ongoing — a classic reading inference.",
    points: 1,
    options: [
      { id: "A", text: "A complete cure for malaria already exists and is widely available" },
      { id: "B", text: "The new vaccine will be distributed to the public within the next week" },
      { id: "C", text: "Cambridge scientists have no previous experience with tropical diseases" },
      { id: "D", text: "Malaria remains a serious, ongoing health challenge in sub-Saharan Africa" },
    ],
    correctAnswer: "D",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "In the sentence \"...marking a significant breakthrough in tropical disease research,\" the phrase 'breakthrough' most closely means:",
    tip: "Use o contexto da frase para descobrir o significado — o que acontece com o avanço científico que torna a notícia relevante?",
    funFact: "The word 'breakthrough' literally means breaking through an obstacle. In science journalism, it describes a discovery that overcomes a major barrier — like developing a vaccine for a disease that has resisted treatments for decades.",
    points: 1,
    options: [
      { id: "A", text: "A small and relatively unimportant change in the field" },
      { id: "B", text: "A major, important advance that overcomes a previous barrier" },
      { id: "C", text: "A serious problem or failure in the research process" },
      { id: "D", text: "A repetition of something scientists already knew and published before" },
    ],
    correctAnswer: "B",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "Read this opinion piece: \"Every government has a moral obligation to fight climate change. Those who deny the urgency of this crisis are ignoring overwhelming scientific evidence and failing future generations.\" What is the author's PRIMARY purpose?",
    tip: "O propósito do autor é a razão pela qual ele escreveu o texto — o que ele quer que o leitor pense, faça ou sinta.",
    funFact: "Opinion pieces (also called 'op-eds', from 'opposite the editorial page') are explicitly persuasive texts. Unlike news articles, they take a clear position. Recognizing an author's purpose is key to reading critically.",
    points: 1,
    options: [
      { id: "A", text: "To entertain readers with amusing stories about climate events" },
      { id: "B", text: "To present both sides of the climate debate in a perfectly balanced way" },
      { id: "C", text: "To persuade readers that governments have a duty to act on climate change" },
      { id: "D", text: "To explain the scientific method used by climate researchers" },
    ],
    correctAnswer: "C",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "In English, when is the definite article 'the' correctly used?",
    tip: "O artigo definido 'the' indica que o falante e o ouvinte já sabem do que se está falando — o referente é específico e conhecido para ambos.",
    funFact: "English learners often struggle with articles because many languages (like Portuguese) use them differently. Portuguese 'o/a' and English 'the' overlap but don't match exactly — for example, 'I love music' in English needs no article, but Portuguese requires 'Eu amo a música'.",
    points: 1,
    options: [
      { id: "A", text: "Before a specific noun already known to both speaker and listener, or unique in context (e.g., 'the sun', 'the president')" },
      { id: "B", text: "Before any noun the first time it is introduced in a conversation" },
      { id: "C", text: "Only before plural nouns, never before singular nouns" },
      { id: "D", text: "Only before proper nouns such as the names of specific people" },
    ],
    correctAnswer: "A",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "Which sentence uses the indefinite article 'a' or 'an' correctly?",
    tip: "Use 'a' antes de sons consonantais e 'an' antes de sons vocálicos — o que importa é o som, não a letra escrita.",
    funFact: "'An hour' uses 'an' because the 'h' in 'hour' is silent, making it start with a vowel sound. 'A university' uses 'a' because 'university' starts with a /j/ sound (like 'you'), not a vowel. It's about sound, not spelling!",
    points: 1,
    options: [
      { id: "A", text: "\"I need a information about the course.\" (wrong: 'information' is uncountable)" },
      { id: "B", text: "\"She is a honest person.\" (wrong: 'honest' has a silent 'h' — should be 'an')" },
      { id: "C", text: "\"There is a umbrella on the table.\" (wrong: 'umbrella' starts with a vowel sound — should be 'an')" },
      { id: "D", text: "\"I saw an elephant at the zoo.\" (correct: 'elephant' starts with a vowel sound)" },
    ],
    correctAnswer: "D",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "Which sentence is grammatically correct in English regarding the form of adjectives?",
    tip: "Em inglês, os adjetivos não mudam de forma para indicar plural — ao contrário do português, onde dizemos 'carros grandes' com o adjetivo no plural.",
    funFact: "In English, adjectives never change for gender or number: 'a big car', 'big cars', 'a big house', 'big houses'. This is unlike many other languages including Portuguese, Spanish, French, and Italian, which all change adjective endings.",
    points: 1,
    options: [
      { id: "A", text: "\"She bought three bigs bags.\" (wrong: adjectives have no plural form)" },
      { id: "B", text: "\"She bought three big bags.\" (correct: 'big' stays unchanged before plural noun)" },
      { id: "C", text: "\"She has two beautifuls dresses.\" (wrong: adjectives have no plural form)" },
      { id: "D", text: "\"He drives two fasts cars.\" (wrong: adjectives have no plural form)" },
    ],
    correctAnswer: "B",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "Which sentence uses the correct verb pattern with 'enjoy'?",
    tip: "O verbo 'enjoy' pertence a um grupo de verbos que sempre precisa ser seguido por um gerúndio (-ing), nunca pelo infinitivo.",
    funFact: "Verb patterns are one of the trickiest aspects of English. 'Enjoy', 'finish', 'avoid', 'suggest', and 'keep' all take -ing. 'Want', 'decide', 'hope', 'promise', and 'seem' all take the infinitive. There is no simple rule — they must be memorized.",
    points: 1,
    options: [
      { id: "A", text: "\"She enjoys to swim every morning.\" (wrong: enjoy + -ing, not infinitive)" },
      { id: "B", text: "\"She enjoys swim every morning.\" (wrong: bare infinitive not allowed here)" },
      { id: "C", text: "\"She enjoys swimming every morning.\" (correct: enjoy + gerund -ing)" },
      { id: "D", text: "\"She enjoys to swimming every morning.\" (wrong: double marking)" },
    ],
    correctAnswer: "C",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "Which sentence uses the correct verb pattern with 'want'?",
    tip: "O verbo 'want' pertence ao grupo de verbos que são seguidos pelo infinitivo com 'to', nunca pelo gerúndio.",
    funFact: "The 'want to' pattern is so common in spoken English that it often becomes 'wanna' in informal speech: 'I wanna learn English.' However, in writing, the full form 'want to' is always required.",
    points: 1,
    options: [
      { id: "A", text: "\"He wants to learn English.\" (correct: want + to + infinitive)" },
      { id: "B", text: "\"He wants learning English.\" (wrong: want does not take -ing)" },
      { id: "C", text: "\"He wants learn English.\" (wrong: bare infinitive after 'wants' is incorrect)" },
      { id: "D", text: "\"He wants of learning English.\" (wrong: preposition 'of' is not used here)" },
    ],
    correctAnswer: "A",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "The English word 'sensible' is a FALSE COGNATE for Portuguese speakers. What does 'sensible' actually mean in English?",
    tip: "Esse falso cognato é armadilha frequente — parece que significa 'sensível', mas na verdade tem um significado completamente diferente.",
    funFact: "'Sensible' and 'sensitive' are often confused even by native speakers. A sensible person makes practical decisions; a sensitive person reacts strongly to emotions or stimuli. 'Sensível' in Portuguese translates to 'sensitive', not 'sensible'.",
    points: 1,
    options: [
      { id: "A", text: "Sensitive — easily affected by emotions or physical stimuli (the meaning of 'sensível')" },
      { id: "B", text: "Noticeable — possible to feel or perceive physically" },
      { id: "C", text: "Related to the five senses — about sensory perception" },
      { id: "D", text: "Practical and showing good judgment — making reasonable decisions (sensato)" },
    ],
    correctAnswer: "D",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "The English word 'pretend' is a FALSE COGNATE. What does 'pretend' mean in English?",
    tip: "Em português, 'pretender' significa planejar ou ter intenção de fazer algo. Em inglês, 'pretend' tem um significado completamente diferente.",
    funFact: "'Pretend' comes from the Latin 'praetendere', meaning to hold out as a shield or claim falsely. In English, it kept the idea of false claiming. Portuguese 'pretender' (to intend) comes from a different evolution of the same Latin root.",
    points: 1,
    options: [
      { id: "A", text: "To plan or intend to do something in the future" },
      { id: "B", text: "To claim or apply formally for a position or right" },
      { id: "C", text: "To act as if something is true when it is not; to fake or make-believe" },
      { id: "D", text: "To extend or stretch something beyond its normal limits" },
    ],
    correctAnswer: "C",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Which is the correct meaning of the English word 'actually'?",
    tip: "Esse falso cognato parece significar 'atualmente' (como em 'currently'), mas na verdade tem outro sentido — ele é usado para corrigir ou esclarecer.",
    funFact: "Brazilian learners often write 'Actually I am living in São Paulo' to mean 'Currently I live in São Paulo.' The correct translation of 'atualmente' is 'currently' or 'nowadays' — 'actually' means 'na verdade' and signals a correction or surprise.",
    points: 1,
    options: [
      { id: "A", text: "Currently — at this present moment in time (false cognate of 'atualmente')" },
      { id: "B", text: "In reality; in truth — used to correct a misunderstanding or reveal a surprising fact (na verdade)" },
      { id: "C", text: "Eventually — at some point in the future after a long time" },
      { id: "D", text: "Actively — in an active and energetic manner" },
    ],
    correctAnswer: "B",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "\"It's cold in here. I'll close the window.\" Which future form is used, and WHY is it used here?",
    tip: "A pessoa toma essa decisão neste exato momento, em resposta ao frio que sente agora — ela não planejou isso antes de entrar no quarto.",
    funFact: "'Will' for spontaneous decisions sounds natural because it reflects real-time thinking. Saying 'I'm going to close the window' here would imply you had already planned to do it before you felt cold — which would be strange.",
    points: 1,
    options: [
      { id: "A", text: "'Will' — used because it is a spontaneous decision made at the moment of speaking" },
      { id: "B", text: "'Will' — used because the speaker planned this action in advance" },
      { id: "C", text: "'Going to' — used because the speaker sees physical evidence of a future event" },
      { id: "D", text: "Present continuous — used because this is a fixed, pre-arranged future event" },
    ],
    correctAnswer: "A",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "\"I'm going to visit Paris next summer. I've already booked the hotel.\" Which future form is used, and WHY?",
    tip: "A chave está na informação 'I've already booked' — isso mostra que a decisão foi tomada antes desse momento.",
    funFact: "'Going to' comes from the idea of physically moving toward something. Over centuries it became a grammatical future marker for prior decisions. When you say 'I'm going to Paris', you're metaphorically already 'in motion' toward that plan.",
    points: 1,
    options: [
      { id: "A", text: "'Will' — because it is a spontaneous decision just decided" },
      { id: "B", text: "'Will' — because it is a general prediction based on the speaker's intuition" },
      { id: "C", text: "Present continuous — because all future travel uses the continuous form" },
      { id: "D", text: "'Going to' — because the plan was already decided before the moment of speaking" },
    ],
    correctAnswer: "D",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "\"I'm having dinner with my boss tomorrow at 7 PM.\" This sentence uses the present continuous form to express:",
    tip: "Esse uso do presente contínuo não indica o que está acontecendo agora — ele refere-se a um compromisso futuro já marcado na agenda.",
    funFact: "Using the present continuous for future arrangements sounds very natural in English: 'We're flying to Rome next week', 'She's presenting at the conference on Friday'. It implies the plan is as real and fixed as something already happening.",
    points: 1,
    options: [
      { id: "A", text: "An action that is happening right now, at this exact moment" },
      { id: "B", text: "A spontaneous decision the speaker just made while speaking" },
      { id: "C", text: "A future arrangement that has already been organized and confirmed" },
      { id: "D", text: "A habitual action that the speaker does regularly or repeatedly" },
    ],
    correctAnswer: "C",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "What does the phrasal verb 'give up' mean?",
    tip: "Esse phrasal verb é usado quando alguém decide parar permanentemente com uma atividade ou hábito.",
    funFact: "Phrasal verbs are one of the most challenging aspects of English for learners because their meaning cannot be guessed from the individual words. 'Give up' has nothing to do with giving or upward movement — it means to quit or stop.",
    points: 1,
    options: [
      { id: "A", text: "To increase effort and try even harder at something" },
      { id: "B", text: "To stop doing something permanently; to quit or abandon an activity" },
      { id: "C", text: "To return something to its original owner" },
      { id: "D", text: "To search for something in many different places" },
    ],
    correctAnswer: "B",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "Read this advertisement: \"Tired of bad hair days? ForceGloss repairs damage in just one wash. Try ForceGloss today — your hair will thank you!\" What is the MAIN IDEA of this advertisement?",
    tip: "O objetivo de todo anúncio é apresentar um produto ou serviço de forma que o consumidor queira comprá-lo.",
    funFact: "Advertising language uses specific techniques: the problem-solution structure ('Tired of X? Try Y'), personification ('your hair will thank you'), and informal direct address ('you') to create a personal connection with the consumer.",
    points: 1,
    options: [
      { id: "A", text: "ForceGloss shampoo is promoted as the solution for damaged hair" },
      { id: "B", text: "All shampoos on the market can repair damaged hair in one wash" },
      { id: "C", text: "Bad hair days are exclusively caused by using the wrong shampoo brand" },
      { id: "D", text: "You should thank your hair for growing and being healthy every day" },
    ],
    correctAnswer: "A",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "Based on the climate change opinion piece from Q4, what can we INFER about the author's beliefs?",
    tip: "A inferência aqui vai além do que é dito — use o tom, as escolhas de palavras e os argumentos para concluir o que o autor acredita.",
    funFact: "Authors reveal their beliefs through word choice even when stating 'facts'. Calling climate deniers people who are 'failing future generations' reveals strong personal conviction — it is not neutral language.",
    points: 1,
    options: [
      { id: "A", text: "The author believes climate change is not a real or proven problem" },
      { id: "B", text: "The author wants to present a completely neutral view with no personal position" },
      { id: "C", text: "The author is a climate scientist who wants to present new research data" },
      { id: "D", text: "The author strongly believes humans have a moral responsibility to address climate change" },
    ],
    correctAnswer: "D",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "The word 'eventually' is sometimes confused by Portuguese speakers. In \"He eventually became a famous actor,\" what does 'eventually' mean?",
    tip: "Este é um falso cognato parcial — 'eventually' em inglês NÃO significa 'possivelmente' ou 'às vezes'. Indica algo diferente sobre o tempo.",
    funFact: "'Eventually' and 'possibly' are completely different. 'He eventually became famous' = it took a long time, but he did become famous. 'He possibly became famous' = maybe he did, maybe he didn't. Always check context before translating.",
    points: 1,
    options: [
      { id: "A", text: "Immediately or very soon — without any delay" },
      { id: "B", text: "Possibly or perhaps — with some uncertainty about whether it happened" },
      { id: "C", text: "After a long period of time; in the end — the outcome that finally occurred" },
      { id: "D", text: "Unfortunately or sadly — with a negative emotional tone" },
    ],
    correctAnswer: "C",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "Which sentence correctly uses TWO verb patterns in a single sentence?",
    tip: "Preste atenção: 'decide' precisa do infinitivo com 'to', e 'give up' (quando usado como gerúndio de objeto) precisa do -ing.",
    funFact: "Having two different verb patterns in one sentence is common: 'I decided to stop smoking' uses 'decide + to + infinitive' AND 'stop + -ing'. Mastering these chains is what makes writing sound truly fluent in English.",
    points: 1,
    options: [
      { id: "A", text: "\"He decided giving up smoking.\" (wrong: decide + to-infinitive, not gerund)" },
      { id: "B", text: "\"He decided to give up smoking.\" (correct: decide + to-infinitive; give up + gerund)" },
      { id: "C", text: "\"He decided to give up to smoke.\" (wrong: give up + -ing, not infinitive)" },
      { id: "D", text: "\"He decided giving up to smoke.\" (wrong: both patterns are incorrect)" },
    ],
    correctAnswer: "B",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Choose the sentence that correctly uses 'going to' for a future plan that was already decided BEFORE the moment of speaking.",
    tip: "A chave para identificar o uso correto de 'going to' para planos é encontrar evidências de que a decisão foi tomada antes — não agora.",
    funFact: "The distinction between 'will' and 'going to' reflects how English marks time of decision. 'I'll help you' = I just decided NOW. 'I'm going to help you' = I already decided BEFORE this conversation. Small but meaningful difference.",
    points: 1,
    options: [
      { id: "A", text: "\"Oh, the phone is ringing. I'll get it!\" (spontaneous decision — correct use of 'will')" },
      { id: "B", text: "\"I think the team will win tomorrow.\" (prediction/opinion — correct use of 'will')" },
      { id: "C", text: "\"Wait, I'll help you carry that!\" (spontaneous offer — correct use of 'will')" },
      { id: "D", text: "\"I'm going to study engineering next year — I already applied to the university.\" (prior decision — correct 'going to')" },
    ],
    correctAnswer: "D",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "In English, when do you NOT use any article (zero article)?",
    tip: "Há situações em inglês onde não se usa nenhum artigo — especialmente com certos substantivos abstratos e conceitos gerais.",
    funFact: "Zero article (no article at all) is common in English: 'I love music', 'She studies medicine', 'He goes to school'. Portuguese uses the definite article in many of these cases: 'Eu amo a música', 'Ela estuda medicina', 'Ele vai à escola'.",
    points: 1,
    options: [
      { id: "A", text: "Before general uncountable nouns and abstract concepts used in their general sense (e.g., 'Music is beautiful', 'Love is powerful')" },
      { id: "B", text: "Only before vowels, when using 'an' would be required" },
      { id: "C", text: "Before all nouns in every situation, regardless of context" },
      { id: "D", text: "Only before specific, countable nouns in the plural form" },
    ],
    correctAnswer: "A",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Why is the sentence \"She has three beautifuls cats\" grammatically incorrect in English?",
    tip: "Compare com o português: 'três gatos bonitos' — o adjetivo concorda com o plural. Em inglês, essa concordância não existe.",
    funFact: "English lost grammatical gender and adjective agreement around the 14th century. Before that, Old English adjectives changed endings like German or Latin. Modern English simplification makes it easier in some ways — but harder for learners because it defies their native language intuition.",
    points: 1,
    options: [
      { id: "A", text: "\"Cats\" should be singular — the sentence needs 'cat', not 'cats'" },
      { id: "B", text: "\"Beautiful\" is spelled incorrectly — it should be 'beautifull'" },
      { id: "C", text: "Adjectives in English have no plural form — the correct sentence is 'three beautiful cats'" },
      { id: "D", text: "\"Three\" cannot be used with the word 'cats' in standard English" },
    ],
    correctAnswer: "C",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Read: \"The scientists published their findings in a peer-reviewed journal, which added credibility to their claims.\" In this context, 'credibility' most closely means:",
    tip: "Pense no papel de uma publicação revisada por outros especialistas — o que ela garante sobre as informações apresentadas?",
    funFact: "Peer review is the gold standard of science. Before a study is published in a reputable journal, it is reviewed by other experts in the field who check for errors and validity. This is why 'peer-reviewed' is synonymous with trustworthiness in academia.",
    points: 1,
    options: [
      { id: "A", text: "Complexity — how difficult and technical the research is to understand" },
      { id: "B", text: "Trustworthiness and reliability — the quality of being believable and dependable" },
      { id: "C", text: "Fame — how well-known the researchers are in their field" },
      { id: "D", text: "Length — the amount of detail included in the published paper" },
    ],
    correctAnswer: "B",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Read this advertisement text: \"Join millions of satisfied customers! Our vitamin supplement boosts energy, improves mood, and strengthens the immune system. Order now and get 50% off!\" What is the author's PRIMARY purpose?",
    tip: "O propósito de um texto publicitário é diferente de um texto informativo ou educativo — o autor quer que você tome uma ação específica.",
    funFact: "Advertisement language uses classic persuasion techniques: social proof ('millions of satisfied customers'), benefit listing ('boosts energy, improves mood'), and urgency ('Order now'). Identifying these helps you become a more critical consumer.",
    points: 1,
    options: [
      { id: "A", text: "To inform readers objectively about the science of vitamins and supplements" },
      { id: "B", text: "To entertain readers with testimonials from satisfied customers" },
      { id: "C", text: "To explain the chemistry of how vitamin supplements work in the body" },
      { id: "D", text: "To persuade readers to purchase the vitamin supplement product" },
    ],
    correctAnswer: "D",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "\"It's getting very dark and cloudy. It's going to rain soon.\" / \"I think she will get the job — she's very qualified.\" Which statement correctly explains the difference between these two uses?",
    tip: "Em um caso há evidência visível e imediata; no outro, há apenas uma opinião ou previsão geral. Qual é qual?",
    funFact: "The 'going to for evidence' rule is powerful in English: look up at a dark sky and say 'It's going to rain' — everyone understands you see evidence. But 'It will rain tomorrow' is just a general prediction, perhaps from a weather app.",
    points: 1,
    options: [
      { id: "A", text: "'Going to' is used when there is present evidence pointing to a future event; 'will' is used for general predictions and opinions" },
      { id: "B", text: "'Going to' is used in formal writing; 'will' is used in informal spoken English" },
      { id: "C", text: "'Will' can only be used in question forms, never in statements" },
      { id: "D", text: "Both 'going to' and 'will' always mean exactly the same thing in all contexts" },
    ],
    correctAnswer: "A",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "What does the phrasal verb 'turn down' mean?",
    tip: "Quando alguém recusa uma oferta, convite ou proposta, usamos esse phrasal verb — não confunda com diminuir o volume (turn down the music).",
    funFact: "Context determines which meaning of 'turn down' applies. 'Turn down the music' means reduce the volume. 'Turn down a job offer' means refuse it. This ambiguity is one reason phrasal verbs are so challenging — context is everything.",
    points: 1,
    options: [
      { id: "A", text: "To increase the volume or intensity of something" },
      { id: "B", text: "To accept an offer, invitation, or proposal" },
      { id: "C", text: "To refuse or reject an offer, invitation, or proposal" },
      { id: "D", text: "To complete or successfully finish a task or project" },
    ],
    correctAnswer: "C",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Which sentence contains the FALSE COGNATE 'actually' used INCORRECTLY?",
    tip: "Identifique a frase onde 'actually' está sendo usado como se significasse 'atualmente' (currently) — que é seu falso cognato em português.",
    funFact: "This is one of the most common errors made by Brazilian English learners. The sentence 'I'm actually living in São Paulo' in English means 'I really am living in São Paulo (contrary to what you might think)' — NOT 'I'm currently living in São Paulo'.",
    points: 1,
    options: [
      { id: "A", text: "\"She is sensible — she always makes practical decisions.\" (correct: sensible = sensato)" },
      { id: "B", text: "\"I am actually very tired right now, in this current moment.\" (incorrect: 'actually' ≠ 'currently'/'atualmente')" },
      { id: "C", text: "\"He pretended to be sick, but he was actually fine.\" (correct: actually = in truth)" },
      { id: "D", text: "\"Eventually, after many years of training, she became a doctor.\" (correct: eventually = after a long time)" },
    ],
    correctAnswer: "B",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Which sentence correctly uses 'going to' to express a future plan already decided BEFORE the moment of speaking?",
    tip: "Procure a frase onde há uma indicação clara de que a decisão foi tomada antes — como um contrato assinado ou um plano confirmado.",
    funFact: "The 'going to' future is sometimes called the 'intention future'. When plans are already in motion — tickets booked, contracts signed, forms submitted — 'going to' is the natural choice, not 'will'.",
    points: 1,
    options: [
      { id: "A", text: "\"Oh, the phone is ringing. I'll answer it!\" (spontaneous decision — use 'will')" },
      { id: "B", text: "\"I think tomorrow will be a beautiful day.\" (general prediction — use 'will')" },
      { id: "C", text: "\"She is meeting the clients tomorrow at 3 PM.\" (fixed arrangement — present continuous)" },
      { id: "D", text: "\"They're going to renovate the office next month — they already signed the contract last week.\" (prior decision — correct 'going to')" },
    ],
    correctAnswer: "D",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Read: \"LOCAL SCHOOL WINS NATIONAL COMPETITION. A team from Jardim das Flores school took first place in the National Science Olympiad, defeating 150 competing schools from across the country.\" What is the MAIN IDEA?",
    tip: "A ideia principal de uma notícia está geralmente no título e reforçada na primeira frase — ela resume o acontecimento mais importante.",
    funFact: "News headline writing is an art form. A good headline must be accurate, short, informative, and attention-grabbing — all in under 10 words. The body of the article then provides the details: who, what, where, when, why, and how.",
    points: 1,
    options: [
      { id: "A", text: "A local school's student team won a national science competition, defeating 150 other schools" },
      { id: "B", text: "There are exactly 150 schools participating in science programs across the country" },
      { id: "C", text: "Science competitions are always organized at a national level in this country" },
      { id: "D", text: "Jardim das Flores school is recognized as having the best science teachers in the nation" },
    ],
    correctAnswer: "A",
  },
];
