export const questoesGeografia8AnoB2Av2 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "O que é 'urbanização'?",
    tip: "Pense na palavra 'urbano', que significa cidade — urbanização é o crescimento das cidades.",
    funFact: "\"Você sabia?\" — Atualmente, mais da metade da população mundial já vive em áreas urbanas, e esse número continua crescendo!",
    points: 1,
    options: [
      { id: "A", text: "O crescimento da área rural" },
      { id: "B", text: "O processo de crescimento das cidades e aumento da população urbana" },
      { id: "C", text: "O movimento de pessoas do campo para o exterior" },
      { id: "D", text: "A criação de novas cidades no campo" },
    ],
    correctAnswer: "B",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "O que é 'zona rural'?",
    tip: "Pense na palavra 'rural' — ela é o oposto de urbano e está ligada ao campo e à natureza.",
    funFact: "\"Você sabia?\" — Mesmo com o crescimento das cidades, a zona rural continua essencial para produzir alimentos para toda a população do planeta!",
    points: 1,
    options: [
      { id: "A", text: "O centro das grandes cidades" },
      { id: "B", text: "Uma área industrial afastada das cidades" },
      { id: "C", text: "Uma área de muitos prédios e trânsito" },
      { id: "D", text: "A área fora das cidades, geralmente ligada à agricultura e à natureza" },
    ],
    correctAnswer: "D",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "O movimento de pessoas que saem do campo para morar nas cidades é chamado de:",
    tip: "Pense em 'êxodo', que significa saída em massa, e 'rural', que se refere ao campo — juntos, formam esse conceito.",
    funFact: "\"Você sabia?\" — O êxodo rural foi intenso no Brasil nas décadas de 1950 a 1970, transformando o país em um dos mais urbanizados da América Latina!",
    points: 1,
    options: [
      { id: "A", text: "Êxodo rural" },
      { id: "B", text: "Urbanização industrial" },
      { id: "C", text: "Migração internacional" },
      { id: "D", text: "Desertificação" },
    ],
    correctAnswer: "A",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "Uma enorme área urbana formada por várias cidades grandes que cresceram e se fundiram é chamada de:",
    tip: "Pense em um aglomerado de cidades tão grandes que formam uma só área urbana gigante.",
    funFact: "\"Você sabia?\" — O eixo São Paulo–Rio de Janeiro é considerada uma grande região urbana do Brasil, com dezenas de cidades conectadas!",
    points: 1,
    options: [
      { id: "A", text: "Município" },
      { id: "B", text: "Distrito rural" },
      { id: "C", text: "Uma enorme área urbana formada pela união de várias cidades grandes" },
      { id: "D", text: "Região agrícola" },
    ],
    correctAnswer: "C",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "O que é 'conurbação'?",
    tip: "Pense em 'con' (junto) + 'urbano' (cidade) — é quando duas cidades crescem tanto que se unem.",
    funFact: "\"Você sabia?\" — A Grande São Paulo é um exemplo de conurbação, com dezenas de municípios que formam uma área urbana contínua!",
    points: 1,
    options: [
      { id: "A", text: "A diminuição do tamanho de uma cidade" },
      { id: "B", text: "A divisão de uma cidade em bairros" },
      { id: "C", text: "O aumento da área rural ao redor das cidades" },
      { id: "D", text: "Quando duas ou mais cidades crescem tanto que suas áreas urbanas se encontram e se misturam" },
    ],
    correctAnswer: "D",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "O que é 'infraestrutura urbana'?",
    tip: "Pense no que toda cidade precisa ter para funcionar bem e oferecer qualidade de vida para seus moradores.",
    funFact: "\"Você sabia?\" — A qualidade da infraestrutura urbana é um dos principais fatores que determinam a qualidade de vida nas cidades!",
    points: 1,
    options: [
      { id: "A", text: "Apenas os prédios altos de uma cidade" },
      { id: "B", text: "Ruas, água encanada, esgoto, luz elétrica e transporte público" },
      { id: "C", text: "As áreas verdes de uma cidade" },
      { id: "D", text: "Apenas as escolas e hospitais" },
    ],
    correctAnswer: "B",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "O que é 'saneamento básico'?",
    tip: "Pense nas condições mínimas de higiene e saúde que uma cidade precisa ter para seus moradores não adoecerem.",
    funFact: "\"Você sabia?\" — No Brasil, ainda há milhões de pessoas sem acesso a saneamento básico adequado, o que causa doenças evitáveis!",
    points: 1,
    options: [
      { id: "A", text: "O conjunto de serviços de água tratada, coleta de esgoto e lixo" },
      { id: "B", text: "Apenas o sistema de energia elétrica" },
      { id: "C", text: "Os hospitais públicos de uma cidade" },
      { id: "D", text: "As escolas públicas municipais" },
    ],
    correctAnswer: "A",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "O que são as 'periferias urbanas'?",
    tip: "Pense em 'periferia', que significa 'ao redor' — são as áreas mais distantes do centro das cidades.",
    funFact: "\"Você sabia?\" — As periferias das grandes cidades brasileiras cresceram muito a partir do êxodo rural das décadas de 1950 a 1970!",
    points: 1,
    options: [
      { id: "A", text: "O centro histórico das cidades" },
      { id: "B", text: "As áreas mais ricas de uma cidade" },
      { id: "C", text: "Áreas mais afastadas do centro, muitas vezes com menos infraestrutura" },
      { id: "D", text: "As áreas de preservação ambiental" },
    ],
    correctAnswer: "C",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "O crescimento vertical de uma cidade, com a construção de muitos prédios altos, é chamado de:",
    tip: "Pense em 'vertical' — é o crescimento para cima, por meio de edifícios altos, em vez de se expandir horizontalmente.",
    funFact: "\"Você sabia?\" — Cidades como São Paulo e Hong Kong cresceram muito verticalmente, porque o espaço horizontal era escasso e caro!",
    points: 1,
    options: [
      { id: "A", text: "Expansão horizontal" },
      { id: "B", text: "O crescimento das cidades através da construção de prédios altos" },
      { id: "C", text: "Degradação urbana" },
      { id: "D", text: "Desertificação" },
    ],
    correctAnswer: "B",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "O que é 'planejamento urbano'?",
    tip: "Pense no trabalho dos governos para organizar como as cidades crescem, pensando em todo mundo que vive nelas.",
    funFact: "\"Você sabia?\" — Cidades como Curitiba são exemplos de planejamento urbano bem-sucedido no Brasil, com transporte público eficiente!",
    points: 1,
    options: [
      { id: "A", text: "A construção aleatória de prédios sem regras" },
      { id: "B", text: "Apenas o planejamento de estradas" },
      { id: "C", text: "A organização dos bairros mais ricos" },
      { id: "D", text: "Para organizar o crescimento da cidade, pensando em moradia, transporte e serviços" },
    ],
    correctAnswer: "D",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Em países mais desenvolvidos, a urbanização costuma ocorrer:",
    tip: "Pense na diferença entre os países desenvolvidos e os em desenvolvimento no processo de urbanização — geralmente a diferença está na qualidade do crescimento.",
    funFact: "\"Você sabia?\" — Nos países ricos, a urbanização ocorreu de forma mais lenta e planejada ao longo de décadas, diferente do que aconteceu em muitos países em desenvolvimento!",
    points: 1,
    options: [
      { id: "A", text: "De forma mais planejada, com melhor infraestrutura para a maioria da população" },
      { id: "B", text: "De forma caótica e sem planejamento" },
      { id: "C", text: "Apenas nas capitais" },
      { id: "D", text: "Sem nenhum investimento público" },
    ],
    correctAnswer: "A",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "No Brasil e em muitos países em desenvolvimento, a urbanização ocorreu de forma:",
    tip: "Pense na velocidade e qualidade com que as cidades brasileiras cresceram — foi muito rápido e nem sempre bem distribuído.",
    funFact: "\"Você sabia?\" — O Brasil passou de um país com 70% da população rural nos anos 1950 para mais de 87% de população urbana hoje!",
    points: 1,
    options: [
      { id: "A", text: "Muito lenta e bem planejada" },
      { id: "B", text: "Apenas nas regiões Sul e Sudeste" },
      { id: "C", text: "Rápida e desigual, criando áreas com boa infraestrutura e outras com muitas dificuldades" },
      { id: "D", text: "Igual em todo o território" },
    ],
    correctAnswer: "C",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "O que é a 'taxa de urbanização'?",
    tip: "Pense em uma porcentagem que mostra o quanto da população vive em áreas urbanas — cidades.",
    funFact: "\"Você sabia?\" — A taxa de urbanização do Brasil supera 87%, sendo uma das mais altas entre os países em desenvolvimento!",
    points: 1,
    options: [
      { id: "A", text: "O número de prédios construídos por ano" },
      { id: "B", text: "A quantidade de migrantes que chegam às cidades" },
      { id: "C", text: "A porcentagem da população que vive em áreas urbanas" },
      { id: "D", text: "O tamanho médio das cidades" },
    ],
    correctAnswer: "B",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "Qual é a maior megalópole do mundo em número de habitantes?",
    tip: "Pense na enorme cidade-capital do Japão, que concentra milhões de pessoas na maior área metropolitana do mundo.",
    funFact: "\"Você sabia?\" — A região metropolitana de Tóquio tem cerca de 37 milhões de habitantes, tornando-a a maior do mundo!",
    points: 1,
    options: [
      { id: "A", text: "São Paulo" },
      { id: "B", text: "Nova York" },
      { id: "C", text: "Xangai" },
      { id: "D", text: "Tóquio" },
    ],
    correctAnswer: "D",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "O que é 'mobilidade urbana'?",
    tip: "Pense na palavra 'mobilidade', que tem relação com se mover — é sobre como as pessoas se locomovem pelas cidades.",
    funFact: "\"Você sabia?\" — O congestionamento causado pela falta de mobilidade urbana causa prejuízos bilionários às cidades todos os anos!",
    points: 1,
    options: [
      { id: "A", text: "A capacidade de uma cidade de receber migrantes" },
      { id: "B", text: "A quantidade de carros em circulação" },
      { id: "C", text: "A facilidade (ou dificuldade) de se locomover dentro de uma cidade, usando transporte" },
      { id: "D", text: "A migração entre cidades" },
    ],
    correctAnswer: "C",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "A existência de bairros muito ricos ao lado de bairros muito pobres numa mesma cidade é chamada de:",
    tip: "Pense no contraste extremo que existe dentro de algumas cidades, com riqueza e pobreza lado a lado.",
    funFact: "\"Você sabia?\" — Cidades como Rio de Janeiro são famosas por essa divisão, com favelas ao lado de bairros nobres!",
    points: 1,
    options: [
      { id: "A", text: "A separação entre áreas ricas e pobres dentro de uma mesma cidade" },
      { id: "B", text: "Planejamento urbano bem-sucedido" },
      { id: "C", text: "Verticalização urbana" },
      { id: "D", text: "Conurbação" },
    ],
    correctAnswer: "A",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "Uma 'cidade sustentável' é aquela que:",
    tip: "Pense no que significa 'sustentável' — é algo que se preocupa com o futuro e com o bem-estar de todos.",
    funFact: "\"Você sabia?\" — Cidades como Curitiba e Copenhague são frequentemente citadas como exemplos de cidades que avançam nessa direção!",
    points: 1,
    options: [
      { id: "A", text: "Cresce apenas em altura, com muitos prédios" },
      { id: "B", text: "Uma cidade que cuida do meio ambiente e pensa no bem-estar das próximas gerações" },
      { id: "C", text: "Possui apenas áreas verdes e parques" },
      { id: "D", text: "Não possui indústrias" },
    ],
    correctAnswer: "B",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "O que é 'especulação imobiliária'?",
    tip: "Pense em quando o preço dos imóveis sobe de forma artificial, não pelo valor real, mas pelo interesse de lucro de quem vende.",
    funFact: "\"Você sabia?\" — A especulação imobiliária é apontada como uma das causas do aumento do custo de vida em grandes cidades ao redor do mundo!",
    points: 1,
    options: [
      { id: "A", text: "A construção de muitas casas populares" },
      { id: "B", text: "O planejamento de novos bairros" },
      { id: "C", text: "A expansão de áreas verdes nas cidades" },
      { id: "D", text: "Quando o valor de terrenos e imóveis sobe muito, às vezes de forma exagerada, por interesse de lucro" },
    ],
    correctAnswer: "D",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "O que é 'gentrificação'?",
    tip: "Pense em quando um bairro popular passa por mudanças que o tornam caro, afastando os moradores originais.",
    funFact: "\"Você sabia?\" — A gentrificação acontece em muitas cidades do mundo, como São Paulo, Rio de Janeiro, Lisboa e Nova York!",
    points: 1,
    options: [
      { id: "A", text: "Quando um bairro mais simples passa por mudanças e fica caro, afastando os moradores originais" },
      { id: "B", text: "O processo de degradação de um bairro" },
      { id: "C", text: "A construção de parques em bairros pobres" },
      { id: "D", text: "A chegada de imigrantes em bairros ricos" },
    ],
    correctAnswer: "A",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "O que é 'periferização'?",
    tip: "Pense em 'periferia' — é o processo pelo qual a população mais pobre é empurrada para as bordas da cidade.",
    funFact: "\"Você sabia?\" — A periferização é um dos maiores desafios das cidades brasileiras, afetando milhões de pessoas que vivem longe dos serviços e do emprego!",
    points: 1,
    options: [
      { id: "A", text: "O crescimento dos bairros centrais" },
      { id: "B", text: "A construção de condomínios fechados" },
      { id: "C", text: "O processo pelo qual a população mais pobre é empurrada para áreas mais afastadas da cidade" },
      { id: "D", text: "A chegada de empresas às periferias" },
    ],
    correctAnswer: "C",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Bernardo percebeu que no centro da cidade há muitos prédios altos. Esse crescimento para cima é chamado de:",
    tip: "Pense na direção desse crescimento — é para cima, com muitos prédios e torres.",
    funFact: "\"Você sabia?\" — Cidades como São Paulo e Nova York são exemplos clássicos desse tipo de crescimento urbano!",
    points: 1,
    options: [
      { id: "A", text: "Expansão horizontal" },
      { id: "B", text: "Degradação urbana" },
      { id: "C", text: "Êxodo rural" },
      { id: "D", text: "Verticalização urbana" },
    ],
    correctAnswer: "D",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Bernardo morou em um bairro que tinha asfalto e esgoto, mas outro bairro da mesma cidade não tinha nada disso. Isso é um exemplo de:",
    tip: "Pense na diferença de infraestrutura entre bairros numa mesma cidade — essa desigualdade tem um nome.",
    funFact: "\"Você sabia?\" — Essa desigualdade de infraestrutura entre bairros é um dos maiores problemas das cidades brasileiras e de outros países em desenvolvimento!",
    points: 1,
    options: [
      { id: "A", text: "Planejamento urbano eficiente" },
      { id: "B", text: "Desigualdade na infraestrutura urbana entre bairros" },
      { id: "C", text: "Cidade sustentável" },
      { id: "D", text: "Conurbação" },
    ],
    correctAnswer: "B",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Bernardo estudou que muita gente saiu do campo para a cidade no Brasil nas décadas de 1950 a 1970. Esse processo é chamado de:",
    tip: "Pense no nome do movimento de saída em massa das pessoas do campo para as cidades.",
    funFact: "\"Você sabia?\" — O êxodo rural transformou o Brasil de um país agrário em um dos mais urbanizados do mundo em apenas algumas décadas!",
    points: 1,
    options: [
      { id: "A", text: "Êxodo rural" },
      { id: "B", text: "Migração internacional" },
      { id: "C", text: "Periferização" },
      { id: "D", text: "Gentrificação" },
    ],
    correctAnswer: "A",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Bernardo aprendeu sobre a Grande São Paulo, onde várias cidades cresceram tanto que se uniram. Esse fenômeno é chamado de:",
    tip: "Pense em quando cidades vizinhas crescem tanto que suas áreas se encontram e se misturam.",
    funFact: "\"Você sabia?\" — A Grande São Paulo envolve dezenas de municípios que formam uma área urbana contínua com quase 22 milhões de habitantes!",
    points: 1,
    options: [
      { id: "A", text: "Êxodo rural" },
      { id: "B", text: "Urbanização sustentável" },
      { id: "C", text: "Conurbação" },
      { id: "D", text: "Gentrificação" },
    ],
    correctAnswer: "C",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Bernardo descobriu sobre cidades que economizam energia, cuidam do lixo e têm bom transporte público. Esse tipo de cidade é chamada de:",
    tip: "Pense em um tipo de cidade que pensa no futuro e no meio ambiente, cuidando do bem-estar das próximas gerações.",
    funFact: "\"Você sabia?\" — Curitiba é frequentemente citada como uma das cidades brasileiras que mais avança em direção a esse ideal!",
    points: 1,
    options: [
      { id: "A", text: "Megalópole" },
      { id: "B", text: "Cidade sustentável" },
      { id: "C", text: "Cidade industrial" },
      { id: "D", text: "Metrópole" },
    ],
    correctAnswer: "B",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Bernardo leu que, em muitas cidades, o preço dos apartamentos subiu muito por causa de investidores que compraram para valorizar e vender depois. Isso é chamado de:",
    tip: "Pense em quando alguém compra um imóvel não para morar, mas para esperar ele valorizar e vender mais caro depois.",
    funFact: "\"Você sabia?\" — A especulação imobiliária é uma das causas do encarecimento da moradia em grandes cidades ao redor do mundo!",
    points: 1,
    options: [
      { id: "A", text: "Mobilidade urbana" },
      { id: "B", text: "Periferização" },
      { id: "C", text: "Saneamento básico" },
      { id: "D", text: "Gentrificação" },
    ],
    correctAnswer: "D",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Bernardo aprendeu que, nas cidades, saber como as pessoas se movem — de bicicleta, metrô ou carro — é parte do conceito de:",
    tip: "Pense no conceito que se refere à capacidade de se movimentar dentro de uma cidade usando diferentes meios de transporte.",
    funFact: "\"Você sabia?\" — Cidades com boa mobilidade urbana tendem a ter menos congestionamentos, menos poluição e melhor qualidade de vida!",
    points: 1,
    options: [
      { id: "A", text: "Mobilidade urbana" },
      { id: "B", text: "Verticalização urbana" },
      { id: "C", text: "Especulação imobiliária" },
      { id: "D", text: "Urbanização" },
    ],
    correctAnswer: "A",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Bernardo entendeu que a população mais pobre vai parar nas bordas da cidade, longe dos empregos e serviços. Esse processo é chamado de:",
    tip: "Pense em 'periferia' — é para lá que a população mais pobre acaba sendo empurrada.",
    funFact: "\"Você sabia?\" — A periferização faz com que muitos trabalhadores passem horas nos transportes, perdendo qualidade de vida!",
    points: 1,
    options: [
      { id: "A", text: "Conurbação" },
      { id: "B", text: "Gentrificação" },
      { id: "C", text: "Periferização" },
      { id: "D", text: "Êxodo rural" },
    ],
    correctAnswer: "C",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Bernardo concluiu que uma cidade ideal deveria oferecer à sua população:",
    tip: "Pense no que toda pessoa precisa para viver bem em uma cidade — os serviços e estruturas básicas que garantem qualidade de vida.",
    funFact: "\"Você sabia?\" — A busca por cidades mais justas e bem estruturadas é um dos grandes temas da geografia urbana contemporânea!",
    points: 1,
    options: [
      { id: "A", text: "Apenas muitos prédios e shoppings" },
      { id: "B", text: "Apenas áreas verdes sem construções" },
      { id: "C", text: "Apenas boas estradas para carros" },
      { id: "D", text: "Boa infraestrutura, como água, luz, transporte e saneamento, de forma mais igual possível" },
    ],
    correctAnswer: "D",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Bernardo aprendeu que o crescimento organizado das cidades, com leis que definem onde morar, trabalhar e ter lazer, é chamado de:",
    tip: "Pense no conceito que envolve organizar o espaço da cidade de forma pensada e com regras.",
    funFact: "\"Você sabia?\" — O planejamento urbano inclui o 'Plano Diretor', que é uma lei que toda cidade brasileira com mais de 20.000 habitantes deve ter!",
    points: 1,
    options: [
      { id: "A", text: "Periferização" },
      { id: "B", text: "Planejamento urbano" },
      { id: "C", text: "Gentrificação" },
      { id: "D", text: "Conurbação" },
    ],
    correctAnswer: "B",
  },
];
