export const questoesPortugues6AnoB2Av1 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'O que é um verbo?',
    tip: 'Pense na palavra que indica o que alguém "faz" ou "é" na frase.',
    funFact: 'Verbos podem indicar não só ações, como "correr", mas também estados, como "ser" e "estar"!',
    points: 1,
    options: [
      { id: 'A', text: 'Uma palavra que nomeia seres ou objetos' },
      { id: 'B', text: 'Uma palavra que descreve uma característica' },
      { id: 'C', text: 'Uma palavra que indica ação, estado ou fenômeno' },
      { id: 'D', text: 'Uma palavra que liga duas orações' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'Na frase "Bernardo estudou muito para a prova", qual é o verbo?',
    tip: 'Pense na palavra que indica a ação realizada por Bernardo.',
    funFact: '"Estudou" está no passado, indicando algo que já aconteceu!',
    points: 1,
    options: [
      { id: 'A', text: 'Estudou' },
      { id: 'B', text: 'Bernardo' },
      { id: 'C', text: 'Muito' },
      { id: 'D', text: 'Prova' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'Quais são as três conjugações verbais da língua portuguesa?',
    tip: 'Pense nas terminações dos verbos no infinitivo: "cantar", "correr" e "partir".',
    funFact: 'A maioria dos verbos da língua portuguesa pertence à primeira conjugação, terminada em "-ar"!',
    points: 1,
    options: [
      { id: 'A', text: 'Passado, presente e futuro' },
      { id: 'B', text: 'Indicativo, subjuntivo e imperativo' },
      { id: 'C', text: 'Singular, plural e coletivo' },
      { id: 'D', text: 'Primeira (-ar), segunda (-er) e terceira (-ir)' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'A que conjugação pertence o verbo "correr"?',
    tip: 'Pense na terminação do verbo no infinitivo: "-er".',
    funFact: 'Verbos da segunda conjugação, como "correr" e "comer", são bem comuns no dia a dia!',
    points: 1,
    options: [
      { id: 'A', text: 'Primeira conjugação' },
      { id: 'B', text: 'Segunda conjugação' },
      { id: 'C', text: 'Terceira conjugação' },
      { id: 'D', text: 'Não pertence a nenhuma conjugação' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'A que conjugação pertence o verbo "partir"?',
    tip: 'Pense na terminação do verbo no infinitivo: "-ir".',
    funFact: 'Verbos da terceira conjugação, como "partir" e "dormir", têm essa terminação característica!',
    points: 1,
    options: [
      { id: 'A', text: 'Terceira conjugação' },
      { id: 'B', text: 'Primeira conjugação' },
      { id: 'C', text: 'Segunda conjugação' },
      { id: 'D', text: 'Não pertence a nenhuma conjugação' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'Quando dizemos que um verbo está no "tempo presente", isso indica que a ação:',
    tip: 'Pense em algo que está acontecendo "agora".',
    funFact: 'O tempo presente também pode indicar hábitos, como em "Bernardo estuda todos os dias"!',
    points: 1,
    options: [
      { id: 'A', text: 'Já aconteceu há muito tempo' },
      { id: 'B', text: 'Vai acontecer no futuro distante' },
      { id: 'C', text: 'Está acontecendo no momento em que se fala' },
      { id: 'D', text: 'Nunca aconteceu' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'Quando dizemos que um verbo está no "tempo passado" (pretérito), isso indica que a ação:',
    tip: 'Pense em algo que já ocorreu, antes de agora.',
    funFact: 'Existem diferentes tipos de pretérito em português, como o perfeito e o imperfeito!',
    points: 1,
    options: [
      { id: 'A', text: 'Está acontecendo agora' },
      { id: 'B', text: 'Já aconteceu antes do momento em que se fala' },
      { id: 'C', text: 'Ainda vai acontecer' },
      { id: 'D', text: 'Nunca vai acontecer' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'Quando dizemos que um verbo está no "tempo futuro", isso indica que a ação:',
    tip: 'Pense em algo que ainda não aconteceu, mas vai acontecer depois.',
    funFact: 'Podemos expressar o futuro de mais de uma forma em português, como em "vou estudar" ou "estudarei"!',
    points: 1,
    options: [
      { id: 'A', text: 'Já aconteceu' },
      { id: 'B', text: 'Está acontecendo agora' },
      { id: 'C', text: 'Nunca vai acontecer' },
      { id: 'D', text: 'Ainda vai acontecer' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'Na frase "Amanhã, Bernardo viajará com a família", em que tempo verbal está o verbo "viajará"?',
    tip: 'Pense na palavra "amanhã", que indica algo que ainda vai acontecer.',
    funFact: 'A terminação "-á" no final do verbo é uma das formas de indicar o futuro em português!',
    points: 1,
    options: [
      { id: 'A', text: 'Futuro' },
      { id: 'B', text: 'Presente' },
      { id: 'C', text: 'Passado' },
      { id: 'D', text: 'Nenhum tempo específico' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'Por que é importante saber usar corretamente os tempos verbais em um texto?',
    tip: 'Pense em como usar o tempo verbal errado pode confundir quem está lendo.',
    funFact: 'Usar os tempos verbais corretamente ajuda o leitor a entender a ordem dos acontecimentos!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque isso não tem nenhuma importância na escrita' },
      { id: 'B', text: 'Porque serve só para decorar regras de gramática' },
      { id: 'C', text: 'Porque ajuda a deixar claro quando cada ação aconteceu, está acontecendo ou vai acontecer' },
      { id: 'D', text: 'Porque substitui a necessidade de usar substantivos' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'O que é o "modo indicativo" de um verbo?',
    tip: 'Pense em frases que afirmam algo com certeza, como "Bernardo estuda todos os dias".',
    funFact: 'O modo indicativo é o mais usado no dia a dia, já que falamos sobre fatos reais o tempo todo!',
    points: 1,
    options: [
      { id: 'A', text: 'O modo usado apenas para dar ordens' },
      { id: 'B', text: 'O modo que expressa desejo ou possibilidade' },
      { id: 'C', text: 'O modo usado apenas em perguntas' },
      { id: 'D', text: 'O modo que expressa fatos certos e reais' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'O que é o "modo imperativo" de um verbo?',
    tip: 'Pense em frases como "Estude para a prova!" ou "Feche a porta, por favor".',
    funFact: 'O modo imperativo pode soltar uma ordem direta ou um pedido mais educado, dependendo do tom!',
    points: 1,
    options: [
      { id: 'A', text: 'O modo usado para contar uma história no passado' },
      { id: 'B', text: 'O modo usado para dar ordens, pedidos ou conselhos' },
      { id: 'C', text: 'O modo usado apenas para verbos no futuro' },
      { id: 'D', text: 'O modo que nunca é usado na fala' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'Na frase "Estude bastante para a prova, Bernardo!", em que modo está o verbo "estude"?',
    tip: 'Pense em como essa frase está dando um "conselho" ou uma "ordem" para Bernardo.',
    funFact: 'O modo imperativo muda um pouco dependendo de quem recebe a ordem: "estude" ou "estudem"!',
    points: 1,
    options: [
      { id: 'A', text: 'Imperativo' },
      { id: 'B', text: 'Indicativo' },
      { id: 'C', text: 'Nenhum modo específico' },
      { id: 'D', text: 'Apenas no infinitivo' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'O que é o "modo subjuntivo" de um verbo?',
    tip: 'Pense em frases como "Espero que Bernardo passe na prova", que expressam um desejo.',
    funFact: 'O subjuntivo costuma aparecer bastante depois de palavras como "que", "se" e "talvez"!',
    points: 1,
    options: [
      { id: 'A', text: 'O modo usado apenas para afirmar fatos absolutamente certos' },
      { id: 'B', text: 'O modo usado apenas em títulos de livros' },
      { id: 'C', text: 'O modo que expressa dúvida, desejo ou possibilidade' },
      { id: 'D', text: 'O modo que nunca aparece em frases com "se"' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'Na frase "Se Bernardo estudasse mais, tiraria notas melhores", o verbo "estudasse" está no modo:',
    tip: 'Pense em como essa frase expressa uma possibilidade, e não um fato certo.',
    funFact: 'Frases que começam com "se" costumam usar o modo subjuntivo, por indicarem uma condição!',
    points: 1,
    options: [
      { id: 'A', text: 'Imperativo' },
      { id: 'B', text: 'Subjuntivo' },
      { id: 'C', text: 'Apenas no infinitivo' },
      { id: 'D', text: 'Indicativo' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'Qual é a diferença principal entre o modo indicativo e o modo subjuntivo?',
    tip: 'Pense em como um deles fala de "certezas" e o outro fala de "possibilidades".',
    funFact: 'Saber usar corretamente os modos verbais ajuda a expressar melhor suas ideias e intenções!',
    points: 1,
    options: [
      { id: 'A', text: 'Não existe nenhuma diferença entre eles' },
      { id: 'B', text: 'O indicativo é usado só para o passado, e o subjuntivo só para o futuro' },
      { id: 'C', text: 'O subjuntivo é usado só em títulos de livros' },
      { id: 'D', text: 'O indicativo expressa fatos certos; o subjuntivo expressa dúvida, desejo ou possibilidade' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'Na frase "Feche a janela, por favor", o verbo "feche" está sendo usado no modo:',
    tip: 'Pense em como essa frase está pedindo para alguém fazer algo.',
    funFact: 'O modo imperativo também é muito usado em receitas culinárias, como "misture os ingredientes"!',
    points: 1,
    options: [
      { id: 'A', text: 'Subjuntivo' },
      { id: 'B', text: 'Indicativo' },
      { id: 'C', text: 'Imperativo' },
      { id: 'D', text: 'Nenhum modo específico' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'Por que é importante saber diferenciar os modos verbais (indicativo, subjuntivo e imperativo)?',
    tip: 'Pense em como cada modo verbal ajuda a expressar uma intenção diferente na frase.',
    funFact: 'Usar o modo verbal certo evita confusões, como misturar uma ordem com uma simples afirmação!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque ajuda a expressar corretamente fatos, desejos ou ordens em uma frase' },
      { id: 'B', text: 'Porque isso não tem nenhuma utilidade na comunicação' },
      { id: 'C', text: 'Porque serve apenas para decorar regras sem aplicação prática' },
      { id: 'D', text: 'Porque substitui a necessidade de aprender substantivos' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'Qual das frases abaixo está no modo imperativo?',
    tip: 'Pense na frase que está dando uma ordem ou um conselho direto.',
    funFact: 'Frases no imperativo costumam terminar com exclamação, reforçando o tom de ordem ou pedido!',
    points: 1,
    options: [
      { id: 'A', text: 'Bernardo estuda todos os dias' },
      { id: 'B', text: 'Estude todos os dias, Bernardo!' },
      { id: 'C', text: 'Bernardo estudaria, se tivesse tempo' },
      { id: 'D', text: 'Bernardo estudou ontem' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'Qual das frases abaixo está no modo subjuntivo?',
    tip: 'Pense na frase que expressa um desejo, e não uma certeza.',
    funFact: 'A palavra "espero" costuma vir acompanhada de um verbo no subjuntivo, como em "espero que chova"!',
    points: 1,
    options: [
      { id: 'A', text: 'Bernardo estuda todos os dias' },
      { id: 'B', text: 'Estude mais, Bernardo!' },
      { id: 'C', text: 'Bernardo estudou a matéria toda' },
      { id: 'D', text: 'Espero que Bernardo estude para a prova' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Na redação sobre o fim de semana, Bernardo escreveu: "Eu brinquei no parque com meus amigos." O verbo "brinquei" está no tempo:',
    tip: 'Pense em como a brincadeira já aconteceu, antes do momento em que Bernardo escreve.',
    funFact: 'O pretérito perfeito, como em "brinquei", é um dos tempos mais usados para contar histórias!',
    points: 1,
    options: [
      { id: 'A', text: 'Passado (pretérito)' },
      { id: 'B', text: 'Presente' },
      { id: 'C', text: 'Futuro' },
      { id: 'D', text: 'Nenhum tempo específico' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Bernardo disse à mãe: "Amanhã, vou estudar para a prova de matemática." O verbo dessa frase está no tempo:',
    tip: 'Pense na palavra "amanhã", que indica algo que ainda vai acontecer.',
    funFact: '"Vou estudar" é uma forma bem comum de indicar o futuro na fala do dia a dia!',
    points: 1,
    options: [
      { id: 'A', text: 'Passado' },
      { id: 'B', text: 'Presente' },
      { id: 'C', text: 'Futuro' },
      { id: 'D', text: 'Nenhum tempo específico' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Bernardo pertence ao time de futebol da escola. Ao descrever sua rotina, ele escreveu: "Eu treino todas as terças-feiras." O verbo "treino" está no tempo:',
    tip: 'Pense em como essa frase descreve um hábito, algo que Bernardo faz regularmente.',
    funFact: 'O tempo presente é muito usado para descrever hábitos e rotinas, além de ações acontecendo agora!',
    points: 1,
    options: [
      { id: 'A', text: 'Passado' },
      { id: 'B', text: 'Presente' },
      { id: 'C', text: 'Futuro' },
      { id: 'D', text: 'Nenhum tempo específico' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Na aula de Português, a professora pediu para Bernardo dar um exemplo de verbo no modo imperativo. Ele respondeu corretamente com a frase:',
    tip: 'Pense na frase que está dando uma ordem ou conselho direto.',
    funFact: 'O modo imperativo é muito usado por professores e pais no dia a dia, para dar instruções!',
    points: 1,
    options: [
      { id: 'A', text: '"Bernardo estuda todos os dias"' },
      { id: 'B', text: '"Bernardo estudou ontem"' },
      { id: 'C', text: '"Bernardo estudaria, se pudesse"' },
      { id: 'D', text: '"Estude com atenção, Bernardo!"' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Bernardo escreveu na sua redação: "Espero que a viagem seja divertida." O verbo "seja" está no modo:',
    tip: 'Pense em como essa frase expressa um desejo, e não uma certeza.',
    funFact: 'Frases que começam com "espero que" quase sempre usam o modo subjuntivo!',
    points: 1,
    options: [
      { id: 'A', text: 'Indicativo' },
      { id: 'B', text: 'Imperativo' },
      { id: 'C', text: 'Subjuntivo' },
      { id: 'D', text: 'Nenhum modo específico' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Na aula de gramática, a professora pediu para Bernardo classificar o verbo "partir" quanto à conjugação. Ele respondeu corretamente:',
    tip: 'Pense na terminação do verbo no infinitivo: "-ir".',
    funFact: 'Verbos irregulares, como "ir" e "vir", também pertencem à terceira conjugação!',
    points: 1,
    options: [
      { id: 'A', text: 'Terceira conjugação' },
      { id: 'B', text: 'Primeira conjugação' },
      { id: 'C', text: 'Segunda conjugação' },
      { id: 'D', text: 'Nenhuma conjugação' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Bernardo comparou dois verbos: "cantar" e "comer". Ele percebeu corretamente que eles pertencem a conjugações diferentes porque:',
    tip: 'Pense nas terminações dos verbos no infinitivo.',
    funFact: 'Saber identificar a conjugação de um verbo ajuda bastante na hora de conjugá-lo em outros tempos!',
    points: 1,
    options: [
      { id: 'A', text: 'Um deles não é um verbo de verdade' },
      { id: 'B', text: 'Ambos pertencem exatamente à mesma conjugação' },
      { id: 'C', text: 'A conjugação depende apenas do tempo verbal usado' },
      { id: 'D', text: '"Cantar" termina em "-ar" (primeira conjugação) e "comer" termina em "-er" (segunda conjugação)' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Na redação, Bernardo quis expressar uma ordem gentil para o irmão mais novo, escrevendo: "Guarde os brinquedos, por favor." Esse verbo está no modo:',
    tip: 'Pense em como essa frase está pedindo para o irmão fazer algo.',
    funFact: 'Mesmo pedidos educados, com "por favor", continuam sendo classificados no modo imperativo!',
    points: 1,
    options: [
      { id: 'A', text: 'Subjuntivo' },
      { id: 'B', text: 'Imperativo' },
      { id: 'C', text: 'Indicativo' },
      { id: 'D', text: 'Nenhum modo específico' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Ao revisar sua redação, Bernardo percebeu que havia escrito "Se eu tivesse mais tempo, viajaria para a praia." O verbo "tivesse" está no modo:',
    tip: 'Pense em como essa frase expressa uma condição, e não um fato certo.',
    funFact: 'Frases condicionais, começando com "se", costumam usar o modo subjuntivo!',
    points: 1,
    options: [
      { id: 'A', text: 'Indicativo' },
      { id: 'B', text: 'Imperativo' },
      { id: 'C', text: 'Subjuntivo' },
      { id: 'D', text: 'Nenhum modo específico' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'Ao final do bimestre, a professora pediu para Bernardo explicar por que é importante entender os tempos e modos verbais. Ele respondeu corretamente que isso ajuda a:',
    tip: 'Pense em tudo que aprendemos sobre tempos e modos verbais ao longo deste simulado.',
    funFact: 'Parabéns, Bernardo! Agora você já sabe identificar tempos verbais e os modos indicativo, subjuntivo e imperativo!',
    points: 1,
    options: [
      { id: 'A', text: 'Expressar com clareza quando algo aconteceu e qual é a intenção da frase (afirmação, ordem ou desejo)' },
      { id: 'B', text: 'Substituir todos os substantivos de um texto' },
      { id: 'C', text: 'Escrever textos sem nenhum verbo' },
      { id: 'D', text: 'Memorizar apenas o alfabeto' },
    ],
    correctAnswer: 'A',
  },
];
