export const questoesHistoria1EmB4Av1 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "Os historiadores convencionaram uma data para o início da Idade Média. Qual evento marca, por convenção, o começo desse período?",
    tip: "Esse evento ocorreu em 476 d.C. e envolveu o fim de uma das maiores civilizações da história. Pense no colapso que fragmentou a Europa Ocidental politicamente.",
    funFact: "\"Você sabia?\" — A divisão da História em Antiguidade, Idade Média e Modernidade é uma convenção criada pelos próprios humanistas renascentistas, que viam a Idade Média como um período de 'trevas' entre duas épocas de esplendor.",
    points: 1,
    options: [
      { id: "A", text: "A conquista da Grécia pelos romanos em 146 a.C." },
      { id: "B", text: "A queda do Império Romano do Ocidente em 476 d.C., quando o chefe bárbaro Odoacro depôs o último imperador Rômulo Augústulo, fragmentando a Europa em reinos germânicos" },
      { id: "C", text: "A morte de Alexandre Magno em 323 a.C." },
      { id: "D", text: "O nascimento de Jesus Cristo no ano 1 d.C." },
    ],
    correctAnswer: "B",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "O feudalismo foi o sistema que organizou a sociedade medieval europeia por séculos. Como ele pode ser definido?",
    tip: "O feudalismo era ao mesmo tempo um sistema político, econômico e social. O que estava no centro desse sistema era uma troca específica entre dois grupos de pessoas.",
    funFact: "\"Você sabia?\" — A palavra 'feudalismo' deriva de 'feudum' (feudo em latim), que por sua vez pode vir do germânico 'feh' (gado/propriedade). O feudo era a unidade básica da economia medieval.",
    points: 1,
    options: [
      { id: "A", text: "Um sistema econômico baseado no comércio marítimo entre as cidades medievais europeias" },
      { id: "B", text: "Uma organização política em que o papa controlava diretamente todos os reinos europeus" },
      { id: "C", text: "Sistema político, econômico e social baseado na concessão de terras (feudos) por um senhor a um vassalo em troca de lealdade e serviço militar, que organizou a Europa após o colapso romano" },
      { id: "D", text: "Um regime democrático em que os camponeses elegiam seus governantes locais" },
    ],
    correctAnswer: "C",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "Na relação de suserania e vassalagem, quais eram as obrigações do vassalo para com seu senhor (suserano)?",
    tip: "A cerimônia de vassalagem (homenagem e investidura) formalizava uma troca clara de obrigações. O vassalo recebia o feudo e em troca devia algo muito específico.",
    funFact: "\"Você sabia?\" — A cerimônia de vassalagem era solene: o vassalo se ajoelhava, colocava as mãos entre as mãos do senhor (homenagem) e jurava fidelidade numa Bíblia ou relíquia sagrada. Quebrar esse juramento era considerado crime hediondo e pecado mortal.",
    points: 1,
    options: [
      { id: "A", text: "Prestar serviço militar ao senhor, oferecer conselho (consilium), auxílio financeiro em ocasiões especiais e hospedar o senhor quando necessário, em troca do feudo concedido" },
      { id: "B", text: "Pagar impostos anuais ao senhor e ao papa sem qualquer obrigação militar" },
      { id: "C", text: "Cultivar as terras do senhor e entregar toda a produção agrícola a ele" },
      { id: "D", text: "Servir ao senhor apenas em tempos de guerra, sem obrigações em tempos de paz" },
    ],
    correctAnswer: "A",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "Os servos da gleba (servos) eram a maioria da população medieval. Qual era a condição jurídica e social desses camponeses?",
    tip: "Os servos não eram escravos (tinham direito à família e à vida), mas tampouco eram livres. Havia uma restrição fundamental que os prendia a um lugar específico.",
    funFact: "\"Você sabia?\" — O servo da gleba não pertencia ao senhor como um escravo, mas estava vinculado à terra. Se a terra mudasse de dono, o servo mudava junto. Estima-se que 90% da população da Europa medieval era camponesa.",
    points: 1,
    options: [
      { id: "A", text: "Eram cidadãos livres que cultivavam suas próprias terras sem obrigações com senhores" },
      { id: "B", text: "Eram escravos que podiam ser comprados e vendidos em mercados medievais" },
      { id: "C", text: "Eram soldados profissionais contratados pelos senhores para defender os feudos" },
      { id: "D", text: "Eram camponeses presos à terra que não podiam abandonar sem permissão do senhor, pagavam tributos em trabalho, produtos e dinheiro, mas tinham direito à família, à vida e ao lote para subsistência" },
    ],
    correctAnswer: "D",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "A Igreja Católica era a instituição mais poderosa da Europa medieval. O que dava a ela tamanha influência sobre reis, senhores e camponeses?",
    tip: "A Igreja controlava aspectos da vida que nenhuma outra instituição controlava — do nascimento à morte, do casamento à condenação. E tinha uma arma que aterrorizava até os reis.",
    funFact: "\"Você sabia?\" — A excomunhão era a pena mais temida da Idade Média: o excomungado era expulso da comunidade cristã, não podia receber sacramentos e era visto como condenado ao inferno. Em 1076, o papa excomungou o imperador Henrique IV.",
    points: 1,
    options: [
      { id: "A", text: "A Igreja controlava exclusivamente o comércio de especiarias, tornando-se a maior riqueza da Europa" },
      { id: "B", text: "A Igreja era a única instituição pan-europeia com estrutura organizada, controlava a educação, o casamento, o enterro e os sacramentos, e ameaçava pecadores e governantes com excomunhão e interdito" },
      { id: "C", text: "A Igreja tinha o maior exército da Europa medieval, superando todos os reinos combinados" },
      { id: "D", text: "A Igreja controlava o abastecimento de alimentos para todos os mosteiros e cidades medievais" },
    ],
    correctAnswer: "B",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "A simonia era uma prática corrupta comum na Igreja medieval. O que ela consistia?",
    tip: "O nome 'simonia' vem do mago Simão, que na Bíblia tentou comprar poderes espirituais dos apóstolos com dinheiro. A prática medieval era análoga: dinheiro comprava posições sagradas.",
    funFact: "\"Você sabia?\" — A luta contra a simonia foi um dos motores da Reforma Gregoriana do século XI, liderada pelo Papa Gregório VII. Ele afirmou que apenas o papa podia nomear ou destituir bispos — o que gerou o conflito com o imperador Henrique IV.",
    points: 1,
    options: [
      { id: "A", text: "O celibato obrigatório para os padres, controverso na Igreja medieval" },
      { id: "B", text: "A prática de rezar sete vezes ao dia, obrigação dos monges beneditinos" },
      { id: "C", text: "A compra e venda de cargos eclesiásticos (bispos, abades) e sacramentos por dinheiro, prática que corrompia a Igreja e que o papado tentou erradicar nas reformas do século XI" },
      { id: "D", text: "A leitura pública da Bíblia em latim que apenas os sacerdotes podiam realizar" },
    ],
    correctAnswer: "C",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "Maomé (Muhammad), fundador do Islamismo, nasceu em qual cidade da Península Arábica?",
    tip: "Essa cidade era um importante centro comercial e religioso da Península Arábica, famosa por abrigar a Caaba, santuário pré-islâmico. É a cidade mais sagrada do Islã.",
    funFact: "\"Você sabia?\" — A Caaba, cubo de pedra negro no centro da Grande Mesquita de Meca, é o ponto para o qual todos os muçulmanos do mundo se voltam durante as cinco orações diárias. Maomé a purificou de ídolos pagãos após a conquista de Meca em 630.",
    points: 1,
    options: [
      { id: "A", text: "Meca, importante centro comercial e religioso da Península Arábica, onde Maomé nasceu por volta de 570 d.C. e onde fica a cidade mais sagrada do Islã" },
      { id: "B", text: "Medina, a segunda cidade mais sagrada do Islã, para onde Maomé migrou" },
      { id: "C", text: "Jerusalém, cidade sagrada para as três religiões monoteístas" },
      { id: "D", text: "Bagdá, capital do Califado Abássida e centro cultural islâmico medieval" },
    ],
    correctAnswer: "A",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "A Hégira (622 d.C.) é o evento mais importante do calendário islâmico. O que foi a Hégira e qual a sua importância para o Islã?",
    tip: "Essa data marca o início do calendário muçulmano — como o nascimento de Cristo marca o ano 1 para os cristãos. Pense no que aconteceu de significativo em 622 d.C. na vida de Maomé.",
    funFact: "\"Você sabia?\" — Em árabe, 'hégira' significa 'emigração' ou 'fuga'. A viagem de Meca a Medina durou cerca de doze dias. Em Medina, Maomé deixou de ser apenas um pregador e tornou-se também o chefe político de uma comunidade.",
    points: 1,
    options: [
      { id: "A", text: "A vitória militar de Maomé sobre os exércitos do Império Persa" },
      { id: "B", text: "O nascimento de Maomé em Meca, data que inicia o calendário islâmico" },
      { id: "C", text: "A revelação do Alcorão ao profeta Maomé pelo arcanjo Gabriel" },
      { id: "D", text: "A migração de Maomé de Meca para Medina em 622 d.C., que marca o ano 1 do calendário islâmico e o início da comunidade muçulmana (umma) como força política e religiosa organizada" },
    ],
    correctAnswer: "D",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "O Islã se organiza em torno de cinco práticas fundamentais obrigatórias a todo muçulmano. Quais são os Cinco Pilares do Islã?",
    tip: "Esses cinco pilares são as obrigações práticas que sustentam a vida de todo muçulmano, do mais humilde ao mais poderoso. Um deles é a declaração de fé; outros envolvem oração, generosidade, jejum e peregrinação.",
    funFact: "\"Você sabia?\" — O Hajj (peregrinação a Meca) é realizado anualmente por 2 a 3 milhões de muçulmanos. É obrigatório pelo menos uma vez na vida para quem tiver saúde e recursos. É a maior reunião humana periódica do mundo.",
    points: 1,
    options: [
      { id: "A", text: "Oração, jejum, batalha, peregrinação e construção de mesquitas" },
      { id: "B", text: "Shahada (profissão de fé: 'não há deus senão Allah e Maomé é seu profeta'), Salat (cinco orações diárias), Zakat (esmola), Sawm (jejum no Ramadã) e Hajj (peregrinação a Meca)" },
      { id: "C", text: "Leitura do Alcorão, ablução, guerra santa, esmola e casamento" },
      { id: "D", text: "Fé, esperança, caridade, oração e penitência" },
    ],
    correctAnswer: "B",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "Após a morte de Maomé (632 d.C.), o Islã se expandiu com uma velocidade extraordinária. Até onde chegou a expansão islâmica em menos de 100 anos?",
    tip: "Em apenas um século, o Islã saiu da Península Arábica e se expandiu em múltiplas direções. Pense no tamanho do território que foi conquistado nesse período histórico.",
    funFact: "\"Você sabia?\" — Em 711 d.C., exércitos islâmicos atravessaram o Estreito de Gibraltar e em poucos anos dominaram quase toda a Península Ibérica. O nome 'Gibraltar' vem do árabe 'Jabal al-Tariq' (Monte de Tariq), o general que liderou a conquista.",
    points: 1,
    options: [
      { id: "A", text: "O Islã expandiu-se apenas pela Península Arábica, sem sair de suas fronteiras originais" },
      { id: "B", text: "O Islã chegou apenas ao Egito e à Síria, sendo barrado pelo Império Bizantino" },
      { id: "C", text: "Em menos de 100 anos, o Islã se expandiu da Península Arábica até a Espanha no oeste, norte da África, Pérsia e noroeste da Índia no leste, criando um vasto califado" },
      { id: "D", text: "O Islã se expandiu pelo continente africano, chegando até a África do Sul em 100 anos" },
    ],
    correctAnswer: "C",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "A Batalha de Poitiers (ou Tours), em 732 d.C., foi um confronto decisivo entre francos e muçulmanos. Qual foi sua importância histórica?",
    tip: "Essa batalha envolveu o avanço islâmico além dos Pireneus para dentro do atual território francês. O resultado desta batalha moldou o futuro religioso e cultural da Europa Ocidental.",
    funFact: "\"Você sabia?\" — O general franco que venceu em Poitiers foi Carlos Martel ('o Martelo'), avô de Carlos Magno. Sua vitória foi decisiva para a herança política carolíngia que dominou a Europa medieval.",
    points: 1,
    options: [
      { id: "A", text: "Marcou o início da expansão islâmica pela Europa Ocidental" },
      { id: "B", text: "Foi a primeira derrota do Islã na Península Ibérica, iniciando a Reconquista" },
      { id: "C", text: "Permitiu que os muçulmanos estabelecessem um emirado permanente no sul da França" },
      { id: "D", text: "Carlos Martel derrotou o avanço islâmico na Europa Ocidental, impedindo que os muçulmanos ultrapassassem os Pireneus e conquistassem os reinos francos — provavelmente mudando o rumo da história europeia" },
    ],
    correctAnswer: "D",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Carlos Magno (Carlos I) foi coroado imperador em uma cerimônia memorável. Como e quando aconteceu essa coroação?",
    tip: "Essa coroação foi um evento político calculado que restaurou simbolicamente o Império Romano do Ocidente — e foi feita por alguém com autoridade para legitimar essa pretensão.",
    funFact: "\"Você sabia?\" — Carlos Magno disse a seus biógrafos que não teria ido à basílica naquela noite de Natal se soubesse o que o papa planejava. Provavelmente mentiu: a cerimônia era do interesse de ambos, mas Magno queria parecer que recebeu o título espontaneamente, não que o mendigou ao papa.",
    points: 1,
    options: [
      { id: "A", text: "Coroado pelo Papa Leão III na noite de Natal de 800 d.C. em Roma, tornando-se imperador do Ocidente e criando o precedente do Sacro Império Romano-Germânico" },
      { id: "B", text: "Coroado pelos barões francos após vitória na batalha de Roncevales" },
      { id: "C", text: "Autocoroado em Aachen após derrotar os vikings e os magiares" },
      { id: "D", text: "Coroado pelo Patriarca de Constantinopla com aprovação do Imperador Bizantino" },
    ],
    correctAnswer: "A",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "O governo de Carlos Magno promoveu um importante renascimento cultural, chamado Renascimento Carolíngio. O que ele realizou nesse campo?",
    tip: "Carlos Magno era um governante analfabeto que aprendeu a ler tarde, mas tinha uma visão clara de que a cultura e a educação eram ferramentas de poder e coesão do seu Império.",
    funFact: "\"Você sabia?\" — O alcuíno de York, monge inglês convocado por Carlos Magno para dirigir a escola palaciana, padronizou a escrita carolíngia (minúscula carolíngia), que substituiu scripts regionais caóticos. Essa escrita influenciou os tipos das primeiras impressoras e as fontes que ainda usamos hoje.",
    points: 1,
    options: [
      { id: "A", text: "Traduziu todos os textos gregos para o latim e os distribuiu às igrejas da Europa" },
      { id: "B", text: "Criou as primeiras universidades europeias em Paris e Bolonha" },
      { id: "C", text: "Proibiu o latim e promoveu as línguas vernáculas germânicas como idiomas oficiais" },
      { id: "D", text: "Fundou escolas em mosteiros e catedrais (Renascimento Carolíngio), padronizou a escrita (minúscula carolíngia), e convocou intelectuais como Alcuíno de York, preservando e difundindo o saber clássico" },
    ],
    correctAnswer: "B",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "A hierarquia feudal era uma pirâmide de poder e dependência. Qual era a ordem correta, do topo à base?",
    tip: "A lógica é simples: quem está em cima concede terras a quem está abaixo em troca de serviço. Mas os servos, na base, não são vassalos — eles produzem o sustento de todos.",
    funFact: "\"Você sabia?\" — Na teoria, um mesmo senhor podia ser vassalo de outro, que por sua vez era vassalo de outro, formando uma cadeia de lealdades sobrepostas que frequentemente geravam conflitos sobre a quem se devia lealdade primária.",
    points: 1,
    options: [
      { id: "A", text: "Serfs → Cavaleiros → Condes → Duques → Rei" },
      { id: "B", text: "Papa → Imperador → Reis → Duques → Cavaleiros → Servos" },
      { id: "C", text: "Rei (no topo) → Grandes senhores (duques, condes) → Cavaleiros e senhores menores → Camponeses livres → Servos da gleba (na base)" },
      { id: "D", text: "Imperador → Papa → Bispos → Senhores → Servos" },
    ],
    correctAnswer: "C",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Os mosteiros medievais exerciam funções que iam muito além da vida religiosa. Qual era o papel dos mosteiros na sociedade medieval europeia?",
    tip: "Num mundo de guerras e instabilidade, os mosteiros eram ilhas de ordem. Pense no que eles preservavam, produziam e ofereciam à comunidade ao redor.",
    funFact: "\"Você sabia?\" — Os monges medievais salvaram grande parte da literatura grega e romana que conhecemos. Sem os scriptoria (salas de cópia dos mosteiros), obras de Virgílio, Cícero, Aristóteles e muitos outros teriam se perdido para sempre.",
    points: 1,
    options: [
      { id: "A", text: "Os mosteiros serviam apenas como locais de isolamento espiritual, sem qualquer função social" },
      { id: "B", text: "Os mosteiros eram principalmente fortalezas militares que defendiam as populações rurais" },
      { id: "C", text: "Os mosteiros funcionavam apenas como bancos, emprestando dinheiro aos senhores feudais" },
      { id: "D", text: "Centros de preservação do saber clássico (scriptoria), produção agrícola e artesanal, assistência social (hospitais, albergues) e evangelização — ilhas de estabilidade cultural no mundo feudal fragmentado" },
    ],
    correctAnswer: "D",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "A Querela das Investiduras (1076-1122) foi um dos maiores conflitos da Idade Média. O que estava em disputa?",
    tip: "A questão central era: quem tem o direito de nomear bispos e abades — autoridades religiosas que também controlavam enormes territórios? A resposta a isso determinava quem tinha mais poder na Europa.",
    funFact: "\"Você sabia?\" — Em janeiro de 1077, o imperador Henrique IV ficou três dias descalço na neve, no castelo de Canossa, esperando para pedir perdão ao papa Gregório VII. A cena da 'Humilhação de Canossa' tornou-se símbolo da supremacia papal sobre o poder secular.",
    points: 1,
    options: [
      { id: "A", text: "O conflito entre o Papa Gregório VII e o Imperador Henrique IV sobre o direito de nomear bispos e abades — o que resultou na Humilhação de Canossa (1077) e no Concordato de Worms (1122)" },
      { id: "B", text: "A disputa entre a Igreja e os comerciantes sobre os juros cobrados nos empréstimos medievais" },
      { id: "C", text: "O conflito entre papas rivais sobre quem era o legítimo representante de Cristo na Terra" },
      { id: "D", text: "A guerra entre o Sacro Império e o sultanato islâmico pelo controle de Jerusalém" },
    ],
    correctAnswer: "A",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "O Alcorão (Quran) é o texto sagrado central do Islã. O que ele representa para os muçulmanos?",
    tip: "Para os muçulmanos, o Alcorão não é uma obra humana — tem uma origem e uma natureza muito específicas que o diferenciam de outros textos sagrados.",
    funFact: "\"Você sabia?\" — O Alcorão tem 114 capítulos (suras) e foi revelado ao longo de 23 anos. Como Maomé era analfabeto, as revelações foram memorizadas e registradas por seus companheiros. Foi organizado em livro após a morte de Maomé.",
    points: 1,
    options: [
      { id: "A", text: "Uma coletânea de histórias e lendas do povo árabe pré-islâmico" },
      { id: "B", text: "O livro sagrado do Islã, considerado a palavra direta de Allah (Deus) revelada ao profeta Maomé pelo arcanjo Gabriel ao longo de 23 anos, guia supremo da vida muçulmana" },
      { id: "C", text: "A biografia de Maomé escrita por seus discípulos após sua morte" },
      { id: "D", text: "O código jurídico criado pelos califas para governar o Império Islâmico" },
    ],
    correctAnswer: "B",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "As invasões vikings (séculos IX-X d.C.) aterrorizaram a Europa Ocidental. Como essas invasões contribuíram paradoxalmente para fortalecer o feudalismo?",
    tip: "Quando o poder central é fraco e os ataques são imprevisíveis, as pessoas buscam proteção onde conseguem encontrá-la. Os vikings criaram exactamente esse ambiente de insegurança.",
    funFact: "\"Você sabia?\" — Os vikings chegaram ao nordeste da América do Norte (Vinland, atual Newfoundland, Canadá) por volta de 1000 d.C. — 500 anos antes de Colombo. Mas não se estabeleceram permanentemente.",
    points: 1,
    options: [
      { id: "A", text: "Os vikings trouxeram o sistema feudal da Escandinávia, ensinando os europeus a organizar seus territórios" },
      { id: "B", text: "As invasões vikings enriqueceram os comerciantes europeus, que usaram o ouro roubado para comprar feudos" },
      { id: "C", text: "As invasões vikings geraram insegurança generalizada, levando a população a buscar proteção junto a senhores locais em troca de terra e serviço, intensificando os vínculos feudais de dependência" },
      { id: "D", text: "Os vikings converteram-se ao Cristianismo e tornaram-se aliados dos papas no combate ao feudalismo" },
    ],
    correctAnswer: "C",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "O mundo islâmico medieval foi um dos maiores centros de produção e transmissão de conhecimento. Quais foram as principais contribuições intelectuais islâmicas na Idade Média?",
    tip: "Enquanto a Europa Ocidental passava por um período de menor atividade intelectual, o mundo islâmico era o principal herdeiro e desenvolvedor do conhecimento grego e persa.",
    funFact: "\"Você sabia?\" — A palavra 'álgebra' vem do árabe 'al-jabr', título de uma obra do matemático Al-Khwarizmi (séc. IX). 'Algoritmo' vem do próprio nome Al-Khwarizmi. Os algarismos que usamos (0, 1, 2…) também são de origem árabe-indiana.",
    points: 1,
    options: [
      { id: "A", text: "O mundo islâmico não teve nenhuma contribuição intelectual relevante na Idade Média" },
      { id: "B", text: "Os muçulmanos contribuíram apenas com arquitetura e arte decorativa" },
      { id: "C", text: "A contribuição islâmica se limitou à medicina, sem influência nas outras ciências" },
      { id: "D", text: "Preservação e tradução dos textos greco-romanos, avanços decisivos em matemática (álgebra, algarismos arábicos, zero), astronomia, medicina (Avicena), filosofia (Averróis) e química, que chegaram à Europa medieval" },
    ],
    correctAnswer: "D",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "O Império Carolíngio, construído por Carlos Magno, fragmentou-se logo após sua morte. O que determinou essa divisão?",
    tip: "A tradição franca de dividir os territórios entre os filhos do rei foi aplicada também ao Império Carolíngio — com consequências duradouras para o mapa político da Europa.",
    funFact: "\"Você sabia?\" — O Tratado de Verdun (843) é considerado o 'atestado de nascimento' da Europa moderna: a divisão entre França, Alemanha e Itália ainda hoje reflete grosseiramente as fronteiras estabelecidas nesse tratado de quase 1.200 anos atrás.",
    points: 1,
    options: [
      { id: "A", text: "Dividido entre os netos de Carlos Magno pelo Tratado de Verdun (843), formando as bases dos futuros reinos da França (Carlos, o Calvo), Lotaríngia (Lotário) e Germânia (Luís, o Germânico)" },
      { id: "B", text: "Destruído pelos vikings, que saquearam Aachen e mataram todos os herdeiros carolíngios" },
      { id: "C", text: "Conquistado pelo califado islâmico que avançou pela Espanha até o centro da França" },
      { id: "D", text: "Transformado numa república após uma revolta dos senhores feudais contra a monarquia carolíngia" },
    ],
    correctAnswer: "A",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "As mulheres na sociedade feudal medieval tinham um papel complexo, variando conforme a classe social. Qual era a situação típica das mulheres nobres?",
    tip: "As mulheres nobres estavam sob autoridade masculina (pai, marido), mas tinham responsabilidades que outras mulheres não tinham — especialmente quando os homens partiam para guerras.",
    funFact: "\"Você sabia?\" — Hildegarda de Bingen (1098-1179), abadessa alemã, foi compositora, escritora, naturalista e visionária mística — uma das figuras intelectuais mais notáveis da Idade Média, reconhecida pelo papa como Doutora da Igreja em 2012.",
    points: 1,
    options: [
      { id: "A", text: "As mulheres nobres tinham completa igualdade jurídica com os homens e podiam ocupar qualquer cargo político" },
      { id: "B", text: "As mulheres medievais, de qualquer classe, eram completamente excluídas da vida pública e religiosa" },
      { id: "C", text: "Mulheres nobres viviam sob autoridade do pai ou marido, mas podiam administrar feudos e mosteiros na ausência dos esposos, participando de decisões importantes — com mais autonomia que mulheres camponesas" },
      { id: "D", text: "As mulheres nobres controlavam a política da Igreja Católica através do poder dos conventos" },
    ],
    correctAnswer: "C",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "A economia feudal tinha características muito diferentes da economia moderna. O que a distinguia fundamentalmente?",
    tip: "Pense na escala e no objetivo da produção medieval: não se produzia para vender num mercado amplo — produzia-se para sobreviver. O dinheiro era raro e o comércio local.",
    funFact: "\"Você sabia?\" — As feiras medievais eram os principais eventos comerciais do feudalismo. As feiras de Champanha (França), no século XII-XIII, atraíam mercadores de toda a Europa, sendo precursoras do comércio capitalista que voltaria a crescer nas cidades.",
    points: 1,
    options: [
      { id: "A", text: "Era uma economia industrializada, com produção em larga escala para exportação" },
      { id: "B", text: "Era predominantemente agrária e de subsistência: pouca circulação monetária, produção para o autoconsumo no feudo, intercâmbio local e dependência quase total da terra" },
      { id: "C", text: "Era uma economia comercial baseada no comércio marítimo entre os feudos europeus" },
      { id: "D", text: "Era uma economia controlada centralmente pelos reis, que distribuíam os recursos igualmente" },
    ],
    correctAnswer: "B",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "O sistema feudal impunha aos servos uma série de obrigações chamadas 'banalidades' e 'corveia'. Em que consistiam essas obrigações?",
    tip: "Os servos não apenas cultivavam — deviam ao senhor trabalho gratuito em suas terras (corveia) e pagavam para usar os equipamentos que pertenciam ao senhor (banalidades).",
    funFact: "\"Você sabia?\" — As banalidades incluíam taxas para usar o moinho do senhor para moer trigo, o forno para cozer pão e o lagar para fazer vinho. O senhor detinha o monopólio desses equipamentos essenciais.",
    points: 1,
    options: [
      { id: "A", text: "Apenas rezas e missas que os servos deviam patrocinar na igreja do feudo" },
      { id: "B", text: "Obrigações militares de servir no exército do senhor por até 40 dias ao ano" },
      { id: "C", text: "Pagamentos em moeda de ouro que os servos deviam ao senhor trimestral mente" },
      { id: "D", text: "A corveia era o trabalho gratuito nas terras do senhor (manancial); as banalidades eram taxas pelo uso obrigatório do moinho, forno e lagar do senhor — formas de extração do excedente no feudalismo" },
    ],
    correctAnswer: "D",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "O Califado foi a principal forma de organização política islâmica após a morte de Maomé. O que era o Califado?",
    tip: "Com a morte de Maomé, os muçulmanos precisavam de alguém que assumisse a liderança — não como profeta (que só pode haver um), mas como chefe político e guardião da fé.",
    funFact: "\"Você sabia?\" — A divisão entre sunitas e xiitas surgiu justamente da questão da sucessão: os sunitas aceitavam qualquer líder competente eleito pela comunidade; os xiitas acreditavam que o líder devia ser da família de Maomé (começando pelo primo Ali).",
    points: 1,
    options: [
      { id: "A", text: "O Estado islâmico governado pelo Califa, sucessor de Maomé como líder político e religioso da comunidade muçulmana (umma), que unificava poder temporal e espiritual numa única autoridade" },
      { id: "B", text: "Uma ordem religiosa de guerreiros islâmicos dedicados à expansão do Islã pela força" },
      { id: "C", text: "O título dado ao imã responsável pela Grande Mesquita de Meca" },
      { id: "D", text: "Um conselho de sábios islâmicos que interpretavam o Alcorão e julgavam disputas religiosas" },
    ],
    correctAnswer: "A",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Carlos Magno era incomum entre os governantes medievais por seu comprometimento com a educação. O que ele fez de notável nesse campo, apesar de suas próprias limitações?",
    tip: "Carlos Magno aprendeu a ler na maturidade e tentava aprender geometria e astronomia com o auxílio de intelectuais. Paradoxalmente, esse homem pouco letrado foi o grande mecenas da cultura medieval.",
    funFact: "\"Você sabia?\" — Carlos Magno dormia com uma lousa ao lado da cama para praticar caligrafia à noite. Mas seus biógrafos dizem que nunca conseguiu dominar bem a escrita — seu 'monograma' real era um símbolo gráfico, não sua assinatura cursiva.",
    points: 1,
    options: [
      { id: "A", text: "Fundou a Universidade de Paris, a primeira universidade do mundo ocidental" },
      { id: "B", text: "Traduziu pessoalmente toda a Bíblia do latim para o alemão para evangelizar os saxões" },
      { id: "C", text: "Incentivou a educação apesar de ser pouco letrado, criando a escola palaciana em Aachen, convocando o intelectual inglês Alcuíno e obrigando bispos e abades a manterem escolas em suas sedes" },
      { id: "D", text: "Proibiu o ensino em latim e impôs que todo conhecimento fosse transmitido oralmente em línguas germânicas" },
    ],
    correctAnswer: "C",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "O Islã reconhecia uma relação especial com o judaísmo e o Cristianismo. Como o Islã via essas religiões e seus seguidores?",
    tip: "As três religiões compartilham a crença num único Deus e honram figuras como Abraão. O Islã tinha uma categoria especial para os seguidores das outras duas religiões monoteístas.",
    funFact: "\"Você sabia?\" — O status de 'Povo do Livro' dava a judeus e cristãos proteção em territórios islâmicos: podiam praticar sua religião, mas pagavam uma taxa especial (jizya) e tinham algumas restrições. Em geral, eram mais tolerados no mundo islâmico do que judeus e muçulmanos no mundo cristão medieval.",
    points: 1,
    options: [
      { id: "A", text: "Considerava judeus e cristãos como hereges que deveriam ser convertidos ou mortos" },
      { id: "B", text: "Considerava judeus e cristãos 'Povos do Livro' (Ahl al-Kitab), reconhecia Abraão, Moisés e Jesus como profetas verdadeiros, mas ensinava que Maomé era o último e definitivo profeta, completando as revelações anteriores" },
      { id: "C", text: "Não reconhecia qualquer relação entre o Islã e as religiões anteriores" },
      { id: "D", text: "Considerava judeus e cristãos superiores aos muçulmanos por receberem revelações mais antigas" },
    ],
    correctAnswer: "B",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "A 'Paz de Deus' e a 'Trégua de Deus' foram iniciativas da Igreja Católica medieval. O que eram esses movimentos?",
    tip: "No contexto de guerras constantes entre senhores feudais, a Igreja tentou impor limitações ao conflito armado usando sua autoridade espiritual.",
    funFact: "\"Você sabia?\" — A Trégua de Deus proibia guerras às quartas, quintas e sextas (em memória da traição, crucificação e morte de Cristo), sábados (descanso sabático) e domingos (dia do Senhor). Na prática, restava pouco tempo para guerrear.",
    points: 1,
    options: [
      { id: "A", text: "Tratados diplomáticos entre o papa e os reis para dividir a Europa em zonas de influência" },
      { id: "B", text: "Movimentos de paz entre muçulmanos e cristãos durante as Cruzadas" },
      { id: "C", text: "Alianças militares formadas pela Igreja para combater os vikings e magiares" },
      { id: "D", text: "Movimentos eclesiásticos que proibiam ataques a igrejas, clérigos, peregrinos e camponeses (Paz de Deus) e restringiam guerras a certos dias da semana e épocas do ano (Trégua de Deus), tentando limitar a violência feudal" },
    ],
    correctAnswer: "D",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "O feudo era a unidade básica do sistema feudal. O que era exatamente um feudo?",
    tip: "O feudo era mais do que apenas um pedaço de terra — era um pacote de direitos e responsabilidades que incluía poder sobre as pessoas que viviam nele.",
    funFact: "\"Você sabia?\" — Os feudos variavam enormemente em tamanho: de um pequeno vilarejo a imensos condados com dezenas de vilarejos. O conde ou duque que recebia um feudo grande podia, por sua vez, conceder partes dele a cavaleiros vassalos seus.",
    points: 1,
    options: [
      { id: "A", text: "Concessão territorial feita por um senhor a seu vassalo incluindo a terra, a jurisdição sobre quem nela vivia e os direitos de cobrar tributos, em troca de serviço militar e lealdade" },
      { id: "B", text: "Apenas um contrato de arrendamento em que o camponês alugava a terra do nobre" },
      { id: "C", text: "Uma fortaleza militar construída pelo rei para defender as fronteiras do reino" },
      { id: "D", text: "Qualquer propriedade pertencente à Igreja Católica na Europa medieval" },
    ],
    correctAnswer: "A",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "O poder temporal da Igreja Católica medieval era uma realidade concreta. O que significava a Igreja ter poder temporal?",
    tip: "A Igreja não apenas guiava as almas — ela possuía terras, cobrava impostos, tinha tribunais próprios e às vezes até exércitos. Isso é o que se chama de poder temporal.",
    funFact: "\"Você sabia?\" — No auge de seu poder temporal, a Igreja Católica possuía entre 1/4 e 1/3 de todas as terras cultiváveis da Europa Ocidental. Os bispos eram frequentemente mais ricos e poderosos que os senhores laicos ao redor.",
    points: 1,
    options: [
      { id: "A", text: "O poder de absolver pecados e garantir a salvação eterna das almas" },
      { id: "B", text: "A autoridade espiritual exclusiva sobre a liturgia e os sacramentos da Igreja" },
      { id: "C", text: "O poder concreto sobre bens materiais e assuntos terrenos: propriedades de terra, cobranças de impostos (dízimo), tribunais eclesiásticos, exércitos e influência direta na política dos reinos medievais" },
      { id: "D", text: "A autoridade religiosa de interpretar os textos sagrados e definir a doutrina cristã" },
    ],
    correctAnswer: "C",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "A Igreja Católica medieval exercia dois tipos de poder que frequentemente entravam em conflito com o poder dos reis. Quais eram esses dois poderes?",
    tip: "Há uma distinção clássica que os papas medievais defendiam entre dois tipos de autoridade: uma sobre a alma, outra sobre o corpo (no sentido político). Os papas reivindicavam superioridade sobre ambas.",
    funFact: "\"Você sabia?\" — A teoria das 'duas espadas' (formulada pelo papa Gelásio I em 494) dizia que Deus concedeu à humanidade duas espadas — a espiritual (ao papa) e a temporal (ao imperador) — e que a espiritual era superior à temporal.",
    points: 1,
    options: [
      { id: "A", text: "Poder militar e poder econômico, que frequentemente se sobrepunham ao poder dos reis" },
      { id: "B", text: "O poder espiritual (autoridade sobre as almas, sacramentos, destino eterno) e o poder temporal (propriedades, exércitos, tribunais e influência política), dois âmbitos que frequentemente entravam em conflito com os governantes leigos" },
      { id: "C", text: "Poder doutrinário e poder artístico, exercidos respectivamente pelo papa e pelos bispos" },
      { id: "D", text: "Poder sobre os vivos e poder sobre os mortos, por meio dos sacramentos e das missas fúnebres" },
    ],
    correctAnswer: "B",
  },
];
