export const questoesGeografia8AnoB1Av1 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "O processo em que as potências europeias ocuparam e dominaram territórios na África e na Ásia, principalmente no século XIX, é chamado de:",
    tip: "Pense no prefixo 'neo', que significa 'novo' — é uma nova fase de colonização, diferente da mais antiga feita nas Américas.",
    funFact: "\"Você sabia?\" — Em pouco mais de 20 anos, no final do século XIX, quase todo o continente africano foi dividido entre as potências europeias!",
    points: 1,
    options: [
      { id: "A", text: "Neocolonialismo (ou Imperialismo)" },
      { id: "B", text: "Globalização" },
      { id: "C", text: "Industrialização" },
      { id: "D", text: "Urbanização" },
    ],
    correctAnswer: "A",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "A reunião realizada em 1884-1885, em que as potências europeias decidiram como dividir o território africano entre si, é conhecida como:",
    tip: "Pense na capital alemã, que deu nome a essa reunião decisiva sobre o destino do continente africano.",
    funFact: "\"Você sabia?\" — Nessa conferência, nenhum representante africano foi convidado a participar das decisões sobre seu próprio continente!",
    points: 1,
    options: [
      { id: "A", text: "Revolução Industrial" },
      { id: "B", text: "Tratado de Versalhes" },
      { id: "C", text: "Conferência de Berlim" },
      { id: "D", text: "Congresso de Viena" },
    ],
    correctAnswer: "C",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "Um dos principais motivos que levaram os países europeus a dominar territórios na África e na Ásia foi a busca por:",
    tip: "Pense no motivo econômico mais forte — os europeus precisavam de recursos para suas indústrias e de lugares para vender seus produtos.",
    funFact: "\"Você sabia?\" — A Revolução Industrial, que acontecia na Europa nessa época, aumentou muito a necessidade de matérias-primas, como algodão, minérios e borracha!",
    points: 1,
    options: [
      { id: "A", text: "Apenas terras vazias" },
      { id: "B", text: "Apenas aventura" },
      { id: "C", text: "Apenas conhecimento científico" },
      { id: "D", text: "Matérias-primas e novos mercados consumidores" },
    ],
    correctAnswer: "D",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "As fronteiras de muitos países africanos foram traçadas pelos europeus sem considerar:",
    tip: "Pense no que realmente importava para a identidade dos povos locais — não eram apenas elementos geográficos, mas sim quem eram essas pessoas.",
    funFact: "\"Você sabia?\" — Essa falta de cuidado com as culturas locais é uma das causas de vários conflitos étnicos que existem na África até hoje!",
    points: 1,
    options: [
      { id: "A", text: "A localização dos rios" },
      { id: "B", text: "As etnias, línguas e culturas dos povos locais" },
      { id: "C", text: "O clima da região" },
      { id: "D", text: "O tamanho do território" },
    ],
    correctAnswer: "B",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "O neocolonialismo na África e na Ásia ocorreu principalmente durante o século:",
    tip: "Pense no período logo após a Revolução Industrial se consolidar na Europa, bem diferente da colonização mais antiga das Américas.",
    funFact: "\"Você sabia?\" — Esse período também é conhecido como 'a corrida pela África', de tão rápida que foi a partilha do continente entre as potências!",
    points: 1,
    options: [
      { id: "A", text: "XV" },
      { id: "B", text: "XVII" },
      { id: "C", text: "XIX" },
      { id: "D", text: "XX" },
    ],
    correctAnswer: "C",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "Diferente do colonialismo mais antigo, o neocolonialismo teve forte apoio em avanços:",
    tip: "Pense nas armas, navios e outras tecnologias que permitiram aos europeus dominar territórios tão distantes com mais facilidade.",
    funFact: "\"Você sabia?\" — Armas de fogo mais avançadas deram uma grande vantagem militar aos europeus durante esse processo de dominação!",
    points: 1,
    options: [
      { id: "A", text: "Tecnológicos e industriais" },
      { id: "B", text: "Apenas religiosos" },
      { id: "C", text: "Apenas artísticos" },
      { id: "D", text: "Apenas agrícolas" },
    ],
    correctAnswer: "A",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "Muitos conflitos atuais em países africanos têm relação com as fronteiras artificiais criadas durante o período:",
    tip: "Pense no período em que as fronteiras africanas foram desenhadas por europeus, sem considerar os povos locais, já mencionado nesta prova.",
    funFact: "\"Você sabia?\" — Muitas fronteiras africanas atuais ainda seguem linhas retas, mostrando como foram traçadas artificialmente, sem considerar a geografia ou os povos locais!",
    points: 1,
    options: [
      { id: "A", text: "Pré-histórico" },
      { id: "B", text: "Do neocolonialismo europeu" },
      { id: "C", text: "Da Idade Média" },
      { id: "D", text: "Dos primeiros povos indígenas" },
    ],
    correctAnswer: "B",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "A exploração de recursos naturais, como minérios e produtos agrícolas, nas colônias africanas e asiáticas beneficiava principalmente:",
    tip: "Pense em quem realmente ficava com os lucros dessa exploração — os países que dominavam, e não os territórios explorados.",
    funFact: "\"Você sabia?\" — Muitos países africanos e asiáticos continuam, até hoje, enfrentando desafios econômicos ligados a esse período de exploração!",
    points: 1,
    options: [
      { id: "A", text: "As populações locais" },
      { id: "B", text: "Nenhum dos envolvidos" },
      { id: "C", text: "Igualmente todos os povos" },
      { id: "D", text: "As metrópoles europeias" },
    ],
    correctAnswer: "D",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "O Reino Unido e a França foram dois dos principais países europeus envolvidos no processo de:",
    tip: "Pense nos dois países europeus que mais se destacaram na disputa por territórios no continente africano e asiático.",
    funFact: "\"Você sabia?\" — O Reino Unido chegou a controlar território suficiente na África para se tornar o maior império colonial da história!",
    points: 1,
    options: [
      { id: "A", text: "Partilha da África e da Ásia" },
      { id: "B", text: "Independência da América" },
      { id: "C", text: "Revolução Francesa" },
      { id: "D", text: "Unificação da Alemanha" },
    ],
    correctAnswer: "A",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "A resistência dos povos africanos e asiáticos à dominação europeia muitas vezes resultou em:",
    tip: "Pense em como os povos locais normalmente reagem quando seus territórios são invadidos e controlados por forças externas.",
    funFact: "\"Você sabia?\" — Vários movimentos de resistência africanos e asiáticos continuaram lutando por décadas, até conquistarem a independência no século XX!",
    points: 1,
    options: [
      { id: "A", text: "Aceitação pacífica imediata" },
      { id: "B", text: "Nenhuma reação" },
      { id: "C", text: "Conflitos e lutas por independência" },
      { id: "D", text: "Aliança total com os europeus" },
    ],
    correctAnswer: "C",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Um país africano cuja fronteira atual atravessa territórios de diferentes grupos étnicos, criando tensões internas, provavelmente teve suas fronteiras definidas durante:",
    tip: "Pense em quem realmente definiu essas fronteiras, sem considerar os grupos étnicos locais, já discutido nesta prova.",
    funFact: "\"Você sabia?\" — Esse tipo de problema fronteiriço é uma das razões pelas quais alguns países africanos enfrentam conflitos internos até os dias de hoje!",
    points: 1,
    options: [
      { id: "A", text: "A época pré-colonial, pelos próprios povos locais" },
      { id: "B", text: "O processo de partilha colonial europeia" },
      { id: "C", text: "Um referendo democrático recente" },
      { id: "D", text: "Uma votação na ONU" },
    ],
    correctAnswer: "B",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "A exploração de borracha no Congo, controlada pela Bélgica durante o neocolonialismo, é um exemplo de como as potências europeias:",
    tip: "Pense no verdadeiro objetivo dessa exploração — era para beneficiar a metrópole, não a população local.",
    funFact: "\"Você sabia?\" — A exploração da borracha no Congo Belga ficou conhecida por ser extremamente violenta, causando grande sofrimento à população local!",
    points: 1,
    options: [
      { id: "A", text: "Ajudaram a desenvolver a região de forma justa" },
      { id: "B", text: "Compartilhavam os lucros igualmente com a população local" },
      { id: "C", text: "Investiram prioritariamente em educação" },
      { id: "D", text: "Exploravam os recursos naturais em benefício próprio" },
    ],
    correctAnswer: "D",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "A Conferência de Berlim, realizada sem a participação de nenhum representante africano, mostra como a partilha do continente foi decidida:",
    tip: "Pense em quem realmente teve voz nessa decisão — apenas as potências europeias, sem nenhuma consulta aos africanos.",
    funFact: "\"Você sabia?\" — Essa exclusão total dos africanos nas decisões sobre seu próprio continente é hoje vista como um dos maiores exemplos de injustiça histórica!",
    points: 1,
    options: [
      { id: "A", text: "De forma unilateral pelas potências europeias" },
      { id: "B", text: "Com total participação dos povos africanos" },
      { id: "C", text: "Através de um acordo justo entre todos os envolvidos" },
      { id: "D", text: "Por meio de uma votação popular africana" },
    ],
    correctAnswer: "A",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "Muitos países asiáticos, como a Índia, foram colonizados pelos europeus e tiveram suas economias voltadas principalmente para:",
    tip: "Pense no papel econômico que as colônias desempenhavam para as metrópoles europeias — fornecer recursos, não desenvolver sua própria indústria.",
    funFact: "\"Você sabia?\" — A Índia era conhecida como 'a joia da coroa britânica', por causa da enorme riqueza que fornecia ao Império Britânico!",
    points: 1,
    options: [
      { id: "A", text: "O desenvolvimento tecnológico próprio" },
      { id: "B", text: "A produção cultural local" },
      { id: "C", text: "Fornecer matérias-primas para a metrópole" },
      { id: "D", text: "O turismo internacional" },
    ],
    correctAnswer: "C",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Após a Segunda Guerra Mundial, muitos países africanos e asiáticos que haviam sido colonizados passaram por um processo de:",
    tip: "Pense no movimento histórico que ocorreu depois da guerra, quando vários territórios conquistaram sua autonomia política.",
    funFact: "\"Você sabia?\" — A década de 1960 é conhecida como 'o ano da África', pois muitos países africanos conquistaram sua independência nesse período!",
    points: 1,
    options: [
      { id: "A", text: "Recolonização" },
      { id: "B", text: "Isolamento total" },
      { id: "C", text: "Nenhuma mudança política" },
      { id: "D", text: "Independência (descolonização)" },
    ],
    correctAnswer: "D",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "As divisões étnicas e culturais causadas pelas fronteiras artificiais do neocolonialismo ainda influenciam hoje:",
    tip: "Pense nas consequências de longo prazo desse processo histórico, que vão muito além de apenas questões econômicas.",
    funFact: "\"Você sabia?\" — Entender essa história ajuda a compreender melhor diversos conflitos atuais que ainda acontecem em partes da África!",
    points: 1,
    options: [
      { id: "A", text: "Apenas questões econômicas pontuais" },
      { id: "B", text: "Conflitos e tensões políticas em diversos países africanos" },
      { id: "C", text: "Nenhuma questão atual" },
      { id: "D", text: "Apenas o clima da região" },
    ],
    correctAnswer: "B",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "Um dos legados negativos do neocolonialismo para muitos países africanos e asiáticos foi a:",
    tip: "Pense no tipo de relação econômica que continuou existindo entre as antigas colônias e metrópoles, mesmo depois da independência.",
    funFact: "\"Você sabia?\" — Essa dependência econômica é um dos temas mais estudados por economistas que pesquisam o desenvolvimento dos países africanos atualmente!",
    points: 1,
    options: [
      { id: "A", text: "Total independência econômica imediata" },
      { id: "B", text: "Ausência completa de conflitos" },
      { id: "C", text: "Dependência econômica das antigas metrópoles" },
      { id: "D", text: "Riqueza equilibrada entre todos os povos" },
    ],
    correctAnswer: "C",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "A ideia de que os europeus tinham o 'dever' de civilizar outros povos, usada para justificar o neocolonialismo, é conhecida como:",
    tip: "Pense em uma expressão que usa a palavra 'fardo' (peso, responsabilidade) relacionada a uma ideia europeia equivocada da época.",
    funFact: "\"Você sabia?\" — Essa ideia foi até transformada em um poema famoso, escrito pelo escritor britânico Rudyard Kipling em 1899!",
    points: 1,
    options: [
      { id: "A", text: "O \"fardo do homem branco\"" },
      { id: "B", text: "O princípio da igualdade" },
      { id: "C", text: "A teoria da evolução" },
      { id: "D", text: "O conceito de soberania popular" },
    ],
    correctAnswer: "A",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "A disputa entre potências europeias por territórios na África e na Ásia também contribuiu, mais tarde, para tensões que ajudaram a desencadear:",
    tip: "Pense no grande conflito mundial do início do século XX, que teve entre suas causas as rivalidades imperialistas entre as potências europeias.",
    funFact: "\"Você sabia?\" — As disputas coloniais foram uma das várias causas que levaram ao clima de tensão que resultou na Primeira Guerra Mundial, em 1914!",
    points: 1,
    options: [
      { id: "A", text: "A Revolução Francesa" },
      { id: "B", text: "A Primeira Guerra Mundial" },
      { id: "C", text: "A Idade Média" },
      { id: "D", text: "O Renascimento" },
    ],
    correctAnswer: "B",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "A exploração de diamantes e ouro na África do Sul durante o período colonial beneficiou principalmente:",
    tip: "Pense em quem realmente controlava e lucrava com essas minas, geralmente empresas e governos ligados à Europa.",
    funFact: "\"Você sabia?\" — A África do Sul ainda é um dos maiores produtores mundiais de ouro e diamantes, com uma história de mineração que remonta a esse período colonial!",
    points: 1,
    options: [
      { id: "A", text: "Os trabalhadores locais igualmente" },
      { id: "B", text: "Nenhum dos envolvidos" },
      { id: "C", text: "Toda a população africana" },
      { id: "D", text: "As empresas e governos europeus" },
    ],
    correctAnswer: "D",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Bernardo estudou sobre a Conferência de Berlim e descobriu que as potências europeias dividiram a África entre si sem a participação de nenhum representante africano. Esse processo é conhecido como:",
    tip: "Pense no nome dado a essa nova fase de dominação colonial europeia, diferente da colonização mais antiga das Américas.",
    funFact: "\"Você sabia?\" — Em pouco mais de 20 anos, quase todo o continente africano foi dividido entre as potências europeias!",
    points: 1,
    options: [
      { id: "A", text: "Neocolonialismo (ou Imperialismo)" },
      { id: "B", text: "Globalização" },
      { id: "C", text: "Industrialização" },
      { id: "D", text: "Urbanização" },
    ],
    correctAnswer: "A",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Bernardo leu sobre a reunião de 1884-1885 em que as potências europeias decidiram como dividir o território africano. Como se chama esse encontro histórico?",
    tip: "Pense na capital alemã que deu nome a essa reunião decisiva sobre o destino do continente africano.",
    funFact: "\"Você sabia?\" — Nessa conferência, nenhum africano teve voz sobre o futuro de seu próprio continente!",
    points: 1,
    options: [
      { id: "A", text: "Revolução Industrial" },
      { id: "B", text: "Tratado de Versalhes" },
      { id: "C", text: "Conferência de Berlim" },
      { id: "D", text: "Congresso de Viena" },
    ],
    correctAnswer: "C",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Bernardo percebeu, ao estudar o mapa da África, que muitas fronteiras são retas e não seguem características naturais ou étnicas. Isso tem relação direta com:",
    tip: "Pense em quem realmente definiu essas fronteiras retas, sem considerar as características locais.",
    funFact: "\"Você sabia?\" — Esse tipo de fronteira artificial é uma das razões por trás de alguns conflitos internos que existem na África até hoje!",
    points: 1,
    options: [
      { id: "A", text: "A escolha livre dos povos africanos" },
      { id: "B", text: "O processo de partilha colonial europeia" },
      { id: "C", text: "Um planejamento cuidadoso recente" },
      { id: "D", text: "A geografia natural da região" },
    ],
    correctAnswer: "B",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Bernardo descobriu que a exploração de recursos naturais nas colônias da África e da Ásia, durante o neocolonialismo, beneficiava principalmente:",
    tip: "Pense em quem realmente ficava com os lucros dessa exploração de recursos.",
    funFact: "\"Você sabia?\" — Muitos países continuam enfrentando desafios econômicos ligados a esse período de exploração histórica!",
    points: 1,
    options: [
      { id: "A", text: "As populações locais" },
      { id: "B", text: "Nenhum dos envolvidos" },
      { id: "C", text: "Igualmente todos os povos" },
      { id: "D", text: "As metrópoles europeias" },
    ],
    correctAnswer: "D",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Bernardo aprendeu que muitos países asiáticos, como a Índia, colonizados pelos europeus, tiveram suas economias voltadas principalmente para:",
    tip: "Pense no papel econômico das colônias para as metrópoles europeias — fornecer recursos, e não desenvolver sua própria indústria.",
    funFact: "\"Você sabia?\" — A Índia era conhecida como 'a joia da coroa britânica' por causa de sua enorme importância econômica para o império!",
    points: 1,
    options: [
      { id: "A", text: "O desenvolvimento tecnológico próprio" },
      { id: "B", text: "A produção cultural local" },
      { id: "C", text: "Fornecer matérias-primas para a metrópole" },
      { id: "D", text: "O turismo internacional" },
    ],
    correctAnswer: "C",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Bernardo descobriu que a expressão usada para justificar o domínio europeu sobre outros povos, como se fosse um 'dever' dos europeus, é chamada de:",
    tip: "Pense na expressão com a palavra 'fardo', relacionada a essa ideia equivocada da época colonial.",
    funFact: "\"Você sabia?\" — Essa ideia virou até um poema famoso, escrito pelo escritor britânico Rudyard Kipling em 1899!",
    points: 1,
    options: [
      { id: "A", text: "O \"fardo do homem branco\"" },
      { id: "B", text: "O princípio da igualdade" },
      { id: "C", text: "A teoria da evolução" },
      { id: "D", text: "O conceito de soberania popular" },
    ],
    correctAnswer: "A",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Bernardo aprendeu que a disputa entre potências europeias por territórios na África e na Ásia também contribuiu para tensões que ajudaram a desencadear:",
    tip: "Pense no grande conflito mundial do início do século XX, que teve entre suas causas as rivalidades coloniais.",
    funFact: "\"Você sabia?\" — As disputas por territórios foram uma das várias causas que levaram à Primeira Guerra Mundial, em 1914!",
    points: 1,
    options: [
      { id: "A", text: "A Revolução Francesa" },
      { id: "B", text: "A Idade Média" },
      { id: "C", text: "O Renascimento" },
      { id: "D", text: "A Primeira Guerra Mundial" },
    ],
    correctAnswer: "D",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Bernardo descobriu que, depois da Segunda Guerra Mundial, muitos países africanos e asiáticos colonizados passaram por um processo de:",
    tip: "Pense no movimento histórico de conquista da autonomia política, que ocorreu depois da guerra.",
    funFact: "\"Você sabia?\" — A década de 1960 é conhecida como 'o ano da África', quando muitos países conquistaram sua independência!",
    points: 1,
    options: [
      { id: "A", text: "Recolonização" },
      { id: "B", text: "Independência (descolonização)" },
      { id: "C", text: "Isolamento total" },
      { id: "D", text: "Nenhuma mudança política" },
    ],
    correctAnswer: "B",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Bernardo entendeu que um dos legados negativos do neocolonialismo para muitos países foi a:",
    tip: "Pense no tipo de relação econômica que continuou existindo entre antigas colônias e metrópoles, mesmo após a independência.",
    funFact: "\"Você sabia?\" — Esse tema é muito estudado por economistas que pesquisam o desenvolvimento dos países africanos hoje!",
    points: 1,
    options: [
      { id: "A", text: "Dependência econômica das antigas metrópoles" },
      { id: "B", text: "Total independência econômica imediata" },
      { id: "C", text: "Ausência completa de conflitos" },
      { id: "D", text: "Riqueza equilibrada entre todos os povos" },
    ],
    correctAnswer: "A",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Bernardo concluiu, após estudar o tema, que as divisões étnicas e culturais causadas pelas fronteiras artificiais do neocolonialismo ainda influenciam hoje:",
    tip: "Pense nas consequências de longo prazo desse processo histórico, que vão além de apenas questões econômicas pontuais.",
    funFact: "\"Você sabia?\" — Entender essa história ajuda a compreender melhor diversos conflitos que ainda ocorrem em partes da África atualmente!",
    points: 1,
    options: [
      { id: "A", text: "Apenas questões econômicas pontuais" },
      { id: "B", text: "Nenhuma questão atual" },
      { id: "C", text: "Conflitos e tensões políticas em diversos países africanos" },
      { id: "D", text: "Apenas o clima da região" },
    ],
    correctAnswer: "C",
  },
];
