export const questoesHistoria9AnoB4Av1 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "O governo de JUSCELINO KUBITSCHEK (JK, 1956–1961) ficou marcado pelo slogan '50 anos em 5'. O que isso significava?",
    tip: "JK prometeu desenvolver o Brasil em velocidade inédita — quais foram os principais projetos e qual foi o preço?",
    funFact: "\"Você Sabia?\" — JK atraiu as grandes montadoras ao Brasil: Volkswagen (VW Fusca), Ford, General Motors e Mercedes-Benz se instalaram no ABC Paulista. O Brasil passou de importador a produtor de automóveis em 4 anos. Mas JK financiou o desenvolvimento com emissão de moeda — criando inflação crônica. A dívida externa triplicou. O 'otimismo desenvolvimentista' escondia problemas estruturais que o Brasil pagaria nas décadas seguintes.",
    points: 1,
    options: [
      { id: "A", text: "JK era contrário à industrialização — seu slogan significava que o Brasil demoraria 50 anos para se modernizar, não 5." },
      { id: "B", text: "JK prometeu comprimir 50 anos de desenvolvimento em 5 — construiu Brasília, atraiu a indústria automobilística, expandiu a malha rodoviária. O PIB cresceu 8% ao ano, mas inflação e dívida externa comprometeram os resultados." },
      { id: "C", text: "JK era comunista que planejava estatizar toda a indústria brasileira em 5 anos, completando em 50 anos." },
      { id: "D", text: "JK representou o fim do desenvolvimento industrial no Brasil — seu governo devolveu as empresas estatais ao setor privado." },
    ],
    correctAnswer: "B",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "A construção de BRASÍLIA (1957–1960) foi um dos maiores projetos da história do Brasil. O que motivou a mudança da capital?",
    tip: "Por que mudar a capital de uma cidade costeira (Rio de Janeiro) para o interior do Brasil?",
    funFact: "\"Você Sabia?\" — Brasília foi construída em 41 meses — por 'candangos', trabalhadores vindos principalmente do Nordeste. Eles viviam em condições precárias nas 'cidades-satélite' ao redor do canteiro de obras. Em 21 de abril de 1960, JK inaugurou a capital — um prazo que parecia impossível. Oscar Niemeyer (edifícios) e Lúcio Costa (urbanismo) criaram o projeto. Brasília foi tombada Patrimônio Cultural da Humanidade pela UNESCO em 1987.",
    points: 1,
    options: [
      { id: "A", text: "Brasília foi construída durante a ditadura militar para criar um símbolo do desenvolvimento autoritário." },
      { id: "B", text: "Brasília foi construída com trabalho escravo importado da África." },
      { id: "C", text: "Construída em 41 meses (1957–1960) pelos 'candangos' vindos do Nordeste, Brasília deveria integrar o interior do Brasil, criar emprego e projetar a modernidade nacional. Projetada por Oscar Niemeyer e Lúcio Costa — Patrimônio da Humanidade (UNESCO, 1987)." },
      { id: "D", text: "Brasília levou 5 anos para ser construída e só foi inaugurada em 1965, já durante a ditadura militar." },
    ],
    correctAnswer: "C",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "A RENÚNCIA DE JÂNIO QUADROS (agosto de 1961) foi um dos episódios mais desconcertantes da história política brasileira. O que aconteceu?",
    tip: "Por que um presidente eleito com a maior votação da história renunciou depois de apenas 7 meses?",
    funFact: "\"Você Sabia?\" — Jânio era excêntrico: proibiu biquínis nas praias, corridas de galo e lança-perfume no carnaval. Condecorou Che Guevara com a mais alta honraria brasileira — irritando os militares. Sua campanha usava uma vassoura como símbolo ('vou varrer a corrupção'). A teoria mais aceita: Jânio acreditava que o Congresso o chamaria de volta com poderes ampliados. O Congresso aceitou a renúncia. Jânio ficou sem cargo, sem poder e sem a dignidade que esperava.",
    points: 1,
    options: [
      { id: "A", text: "Jânio Quadros foi deposto pelos militares que se opunham à sua política externa independente com o condecoramento de Che Guevara." },
      { id: "B", text: "Jânio morreu de infarto em agosto de 1961, sem completar seu mandato." },
      { id: "C", text: "Jânio foi reeleito em agosto de 1961 numa eleição convocada por aclamação popular." },
      { id: "D", text: "Jânio Quadros renunciou após 7 meses (agosto de 1961) numa jogada política que pretendia ser chamado de volta com mais poderes. O Congresso aceitou a renúncia — abrindo caminho para a crise em torno da posse do vice João Goulart." },
    ],
    correctAnswer: "D",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "A POSSE DE JANGO GOULART (1961) foi dificultada por uma crise institucional. Como o vice-presidente tomou posse?",
    tip: "Jango estava na China quando Jânio renunciou — os ministros militares vetaram sua posse. Como a crise foi resolvida?",
    funFact: "\"Você Sabia?\" — O governador gaúcho Leonel Brizola organizou a resistência armada: militares leais ao Estado de Direito, 'Rádio da Legalidade' transmitindo para todo o Brasil, 'Cadeia da Legalidade' pedindo que o povo defendesse a Constituição. O III Exército (Sul) ficou leal à posse de Goulart. A crise foi resolvida pela adoção do parlamentarismo — reduzindo os poderes de Goulart como condição para que os militares aceitassem sua posse.",
    points: 1,
    options: [
      { id: "A", text: "Os ministros militares vetaram a posse de Goulart. Leonel Brizola organizou resistência armada no Sul ('Campanha da Legalidade'). A solução: adoção do regime parlamentarista (que reduzia os poderes de Goulart). Um plebiscito em 1963 restaurou o presidencialismo pleno." },
      { id: "B", text: "Os militares receberam Goulart de braços abertos como o sucessor constitucional legítimo, sem nenhuma resistência." },
      { id: "C", text: "Goulart nunca tomou posse — os militares nomearam um presidente provisório até as eleições de 1962." },
      { id: "D", text: "O Supremo Tribunal Federal bloqueou a posse de Goulart e convocou novas eleições, que foram vencidas pela UDN." },
    ],
    correctAnswer: "A",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "As REFORMAS DE BASE de Goulart causaram polarização extrema na sociedade brasileira. O que eram essas reformas?",
    tip: "Quais medidas Goulart propôs que assustaram tanto os conservadores a ponto de justificarem um golpe?",
    funFact: "\"Você Sabia?\" — A Reforma Agrária proposta por Goulart desapropriaria terras ao longo das rodovias federais e margens de açudes públicos. Apenas isso — uma fatia pequena do total de terras. Mesmo assim, foi o suficiente para galvanizar os grandes proprietários rurais contra ele. O Brasil tinha um dos maiores índices de concentração de terra do mundo — e 30 anos após o golpe, a situação não havia mudado significativamente.",
    points: 1,
    options: [
      { id: "A", text: "As Reformas de Base eram programas de ajuste fiscal para reduzir a inflação herdada do governo JK." },
      { id: "B", text: "As Reformas de Base incluíam reforma agrária, reforma bancária, nacionalização de refinarias privadas, voto para analfabetos e reforma universitária — medidas que assustaram conservadores, militares e o governo americano, que as via como 'ameaça comunista'." },
      { id: "C", text: "As Reformas de Base foram aprovadas pelo Congresso antes do golpe — o golpe impediu sua implementação." },
      { id: "D", text: "As Reformas de Base foram criadas pelos militares como pretexto para tirar Goulart do poder." },
    ],
    correctAnswer: "B",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "O GOLPE DE 1964 (31 de março – 1.º de abril) teve apoio amplo na sociedade civil. Quem apoiou o golpe?",
    tip: "Costuma-se dizer que o golpe foi 'militar' — mas quem mais estava do lado dos militares naquele momento?",
    funFact: "\"Você Sabia?\" — O embaixador americano Lincoln Gordon telefonou para Washington dizendo que o golpe era 'a mais importante vitória para a liberdade no mundo na segunda metade do século XX'. Os EUA já tinham navios de guerra e combustível posicionados para apoiar os golpistas caso necessário (Operação Brother Sam). O Globo publicou editorial na manhã do golpe parabenizando os militares. IBAD e IPES — organizações empresariais financiadas pelos EUA — haviam financiado a campanha de oposição a Goulart por anos.",
    points: 1,
    options: [
      { id: "A", text: "Apenas os militares apoiaram o golpe — a sociedade civil era unânime em defender o governo constitucional de Goulart." },
      { id: "B", text: "Ninguém apoiou o golpe espontaneamente — foi puramente uma decisão de generais, sem apoio externo ou da sociedade." },
      { id: "C", text: "O golpe teve apoio de empresários (FIESP), classe média, Igreja Católica conservadora, imprensa (O Globo, O Estado), UDN e governo americano. A 'Marcha com Deus pela Família e pela Liberdade' (19/3/1964) levou 500.000 pessoas às ruas de São Paulo. Não foi apenas militar." },
      { id: "D", text: "Apenas os comunistas se opuseram ao golpe — o restante da sociedade o aceitou sem resistência." },
    ],
    correctAnswer: "C",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "O ATO INSTITUCIONAL N.º 5 (AI-5) de dezembro de 1968 é chamado de 'golpe dentro do golpe'. Por quê?",
    tip: "Se o golpe foi em 1964, o que mudou em 1968 para que fosse necessário um novo ato institucional?",
    funFact: "\"Você Sabia?\" — Em setembro de 1968, o deputado Márcio Moreira Alves fez um discurso na Câmara chamando os militares de 'torturadores' e pedindo às mulheres que não namorassem militares. O ministro do Exército pediu ao Congresso que cassasse Alves — o Congresso recusou. Esse foi o pretexto para o AI-5. O regime não tolerava que o Congresso resistisse. O AI-5 fechou o Congresso e eliminou qualquer resistência institucional.",
    points: 1,
    options: [
      { id: "A", text: "O AI-5 (13 de dezembro de 1968) encerrou a fase de 'ditadura com fachada' — fechou o Congresso, suspendeu o habeas corpus, autorizou a tortura. Inaugurou o período mais repressivo da ditadura (1968–1978), apesar de coincidir com o 'Milagre Econômico'." },
      { id: "B", text: "O AI-5 foi o primeiro ato institucional emitido logo após o golpe de 1964, instaurando a ditadura." },
      { id: "C", text: "O AI-5 foi uma emenda constitucional que legalizou retroativamente todos os atos da ditadura." },
      { id: "D", text: "O AI-5 foi rejeitado pelo Congresso e nunca entrou em vigor, sendo substituído pelo estado de sítio." },
    ],
    correctAnswer: "A",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "O conteúdo do ATO INSTITUCIONAL N.º 5 (AI-5). Quais poderes ele conferiu ao regime?",
    tip: "O AI-5 eliminou quais garantias constitucionais que existiam mesmo durante a ditadura?",
    funFact: "\"Você Sabia?\" — O ministro da Justiça que assinou o AI-5, Luís Antônio da Gama e Silva, era jurista e professor da USP. Quando questionado sobre a suspensão do habeas corpus, ele disse que 'não havia presos políticos no Brasil — havia apenas criminosos'. O AI-5 vigorou por 10 anos (1968–1978). Nesse período, funcionaram o DOI-CODI (centro de tortura) e o DOPS. O delegado Sérgio Paranhos Fleury foi o mais notório torturador do período.",
    points: 1,
    options: [
      { id: "A", text: "O AI-5 garantiu eleições livres e diretas para todos os cargos executivos e legislativos do país." },
      { id: "B", text: "O AI-5 foi um conjunto de reformas sociais que garantiram mais direitos trabalhistas aos operários." },
      { id: "C", text: "O AI-5 re-estabeleceu os direitos civis suspensos nos primeiros atos institucionais de 1964." },
      { id: "D", text: "O AI-5 fechou o Congresso, suspendeu o habeas corpus (permitindo detenção arbitrária), autorizou confisco de bens e cassação de direitos políticos. Abriu caminho para a tortura sistemática no DOI-CODI. Os 10 anos do AI-5 (1968–1978) foram os mais duros da ditadura." },
    ],
    correctAnswer: "D",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "O 'MILAGRE ECONÔMICO' brasileiro (1968–1974). O que foi e quais foram suas contradições?",
    tip: "O PIB cresceu mais de 10% ao ano — por que isso foi chamado de 'milagre' e quais foram seus custos?",
    funFact: "\"Você Sabia?\" — A frase mais famosa do período foi do ministro da Fazenda Delfim Netto: 'É preciso fazer o bolo crescer primeiro para depois distribuir.' O bolo cresceu — mas nunca foi dividido. Em 1960, os 10% mais ricos detinham 39% da renda. Em 1970, 47%. Em 1980, 51%. Quanto mais crescia a economia, mais concentrada ficava a renda. O 'milagre' foi financiado com dívida externa que sufocaria o Brasil nos anos 1980.",
    points: 1,
    options: [
      { id: "A", text: "O Milagre Econômico criou igualdade social no Brasil — a renda foi distribuída igualitariamente durante o governo Médici." },
      { id: "B", text: "O PIB cresceu 10–12% ao ano (1968–74): construção da Transamazônica, usina nuclear, Itaipu. Mas a desigualdade aumentou ('o bolo cresceu mas não foi dividido'), o modelo foi financiado por dívida externa e reprimiu salários via ditadura." },
      { id: "C", text: "O Milagre Econômico acabou em 1968 por causa do choque do petróleo — durou apenas um ano." },
      { id: "D", text: "O Milagre Econômico criou um Estado de bem-estar social no Brasil, com saúde e educação pública universais." },
    ],
    correctAnswer: "B",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "A GUERRILHA URBANA contra a ditadura militar — MR-8, ALN e outros grupos. O que fizeram?",
    tip: "Qual foi a ação mais famosa da guerrilha urbana brasileira, e qual foi o resultado geral dessa estratégia?",
    funFact: "\"Você Sabia?\" — O sequestro do embaixador americano Charles Burke Elbrick (1969) foi realizado pelo MR-8 e ALN juntos. Os guerrilheiros exigiram a libertação de 15 presos políticos em troca do embaixador. O governo cedeu — os 15 foram exilados no México. Foi a ação mais bem-sucedida da guerrilha. Mas o regime reagiu com brutalidade ampliada. O guerrilheiro que dirigia o carro do sequestro era um jovem de 22 anos — Fernando Gabeira, que décadas depois tornou-se deputado federal e criou a 'sacolinha' ambiental.",
    points: 1,
    options: [
      { id: "A", text: "Os grupos guerrilheiros foram movimentos pacíficos que não usaram nenhuma forma de violência contra a ditadura." },
      { id: "B", text: "O Brasil nunca teve oposição armada à ditadura militar — a resistência foi exclusivamente política e sindical." },
      { id: "C", text: "MR-8, ALN (Carlos Marighella) e outros realizaram assaltos a bancos, sequestros de embaixadores e ações de guerrilha — mas foram brutalmente derrotados. A guerrilha do Araguaia (PCdoB, 1972–74) foi extermada pelo Exército. A estratégia de 'fomentar o terror para radicalizar o povo' não funcionou." },
      { id: "D", text: "As guerrilhas foram invasões estrangeiras financiadas por Cuba e URSS — não eram brasileiros opositores da ditadura." },
    ],
    correctAnswer: "C",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "A TORTURA E OS DESAPARECIDOS POLÍTICOS da ditadura militar. O que revelou a Comissão Nacional da Verdade?",
    tip: "Quantas pessoas foram mortas ou desaparecidas pela ditadura? Quais foram os mecanismos de tortura?",
    funFact: "\"Você Sabia?\" — Dilma Rousseff, que seria presidente do Brasil décadas depois, foi presa em 1970 como militante da VAR-Palmares. Foi torturada no DOI-CODI de São Paulo durante semanas. Sua expressão ao descobrir que era candidata à presidência e que seus torturadores ainda estavam vivos foi documentada em entrevistas. O Brasil nunca julgou seus torturadores — diferente da Argentina, que condenou os ditadores e membros da Junta Militar.",
    points: 1,
    options: [
      { id: "A", text: "A tortura nunca foi praticada pela ditadura militar brasileira — os relatos são invenções de comunistas." },
      { id: "B", text: "A tortura foi usada apenas contra espiões estrangeiros, nunca contra cidadãos brasileiros." },
      { id: "C", text: "A ditadura militar brasileira tratava seus presos políticos com respeito total — era diferente das ditaduras sul-americanas." },
      { id: "D", text: "A Comissão Nacional da Verdade (2012–2014) confirmou ao menos 434 mortos e desaparecidos, e o 'Brasil: Nunca Mais' (1985) documentou 17.000 casos de tortura. O DOI-CODI era o principal centro de tortura. Os torturadores nunca foram julgados." },
    ],
    correctAnswer: "D",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "O governo MÉDICI (1969–1974) — o mais repressivo da ditadura. O que o caracterizou?",
    tip: "Como o regime conseguiu ter o período mais violento e ao mesmo tempo o crescimento econômico mais alto de sua história?",
    funFact: "\"Você Sabia?\" — Em 1970, o Brasil ganhou a Copa do Mundo no México com Pelé, Tostão e Rivelino — e a ditadura usou o título para reforçar o nacionalismo. 'Brasil: ame-o ou deixe-o' era o slogan do regime. A seleção de 1970 é até hoje considerada a melhor de todos os tempos — mas sua vitória foi politicamente explorada para encobrir as torturas do DOI-CODI que aconteciam ao mesmo tempo.",
    points: 1,
    options: [
      { id: "A", text: "O governo Médici (1969–1974) foi o mais repressivo, coincidindo com o 'Milagre Econômico'. Tortura sistemática, guerrilha urbana e do Araguaia esmagadas, Carlos Marighella morto (1969). A repressão era 'escondida' pelo crescimento econômico e pelo futebol (Copa de 1970)." },
      { id: "B", text: "Médici foi o ditador mais moderado — durante seu governo, presos políticos foram libertados e a imprensa ganhou liberdade." },
      { id: "C", text: "Médici realizou eleições diretas para presidente em 1973 e perdeu para o candidato da oposição." },
      { id: "D", text: "Médici foi deposto em golpe por militares moderados que queriam iniciar a abertura política." },
    ],
    correctAnswer: "A",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "O governo GEISEL (1974–1979) e a abertura 'lenta, gradual e segura'. O que isso significava?",
    tip: "Geisel queria democratizar — mas em que condições e a que velocidade?",
    funFact: "\"Você Sabia?\" — Em 1976, o jornalista Vladimir Herzog foi convocado pelo DOI-CODI e encontrado 'enforcado' — suicídio impossível dado como estava amarrado. Dom Paulo Evaristo Arns organizou uma missa ecumênica lotada na Catedral da Sé em São Paulo. Geisel, para mostrar que 'era diferente', afastou o comandante do II Exército responsável pela morte de Herzog. Um gesto pequeno, mas simbólico da 'abertura' que tentava manter.",
    points: 1,
    options: [
      { id: "A", text: "Geisel acelerou a repressão após Médici — não houve nenhuma abertura durante seu governo." },
      { id: "B", text: "Geisel (1974–1979) iniciou a abertura controlada — revogou o AI-5 em 1978, permitiu imprensa mais plural, reduziu assassinatos políticos. Mas controlava o ritmo: o 'Pacote de Abril' (1977) manipulou as regras eleitorais para manter a maioria do regime. Abertura nos termos do regime." },
      { id: "C", text: "Geisel foi removido por militares radicais que queriam manter a repressão e nunca fazer abertura." },
      { id: "D", text: "Geisel foi o último ditador — após seu governo, a democracia plena foi restaurada imediatamente em 1979." },
    ],
    correctAnswer: "B",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "O BIPARTIDARISMO da ditadura — ARENA e MDB. Como funcionava o sistema político durante a ditadura?",
    tip: "A ditadura extinguiu os partidos existentes mas criou dois novos — qual era a lógica?",
    funFact: "\"Você Sabia?\" — Nas eleições de 1974, o MDB fez uma campanha com frases de duplo sentido: 'Vote MDB para ter quem diga não' e 'a oposição que o povo precisou criar'. O MDB elegeu Orestes Quércia, Montoro, Brossard — grandes nomes que o regime tentou suprimir. A vitória inesperada do MDB no Senado (ganhou 16 de 22 vagas disputadas) mostrou que, mesmo com regras desfavoráveis, o povo rejeitava o regime.",
    points: 1,
    options: [
      { id: "A", text: "Durante a ditadura, todos os partidos políticos existentes continuaram funcionando normalmente." },
      { id: "B", text: "A ditadura não permitiu nenhum partido político — todas as eleições foram suspensas por 21 anos." },
      { id: "C", text: "O Ato Institucional de 1965 criou o bipartidarismo: ARENA (partido governista) e MDB (oposição legal e limitada). Nas eleições de 1974, o MDB ganhou 16 das 22 vagas do Senado — mostrando a rejeição popular ao regime apesar das regras desfavoráveis." },
      { id: "D", text: "Arena e MDB eram ambos partidos pró-governo — não havia oposição real permitida durante toda a ditadura." },
    ],
    correctAnswer: "C",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "A LEI DA ANISTIA (1979) — sua ambiguidade histórica até hoje. O que ela estabeleceu?",
    tip: "A Anistia libertou presos políticos — mas o que foi esquecido em troca?",
    funFact: "\"Você Sabia?\" — Em 2010, o Supremo Tribunal Federal (7 a 2) decidiu que a Lei da Anistia cobre também os agentes do Estado que praticaram torturas — impedindo qualquer julgamento. O Brasil foi o único país do Cone Sul que não julgou seus torturadores. Argentina condenou Videla e outros. Chile julgou Pinochet. Uruguai e Paraguai também. A OAB, a ONU e juristas internacionais criticaram a interpretação brasileira como 'anistia aos torturadores, não para as vítimas'.",
    points: 1,
    options: [
      { id: "A", text: "A Lei da Anistia só beneficiou as vítimas — os torturadores foram todos julgados e condenados pela Justiça brasileira." },
      { id: "B", text: "A Lei da Anistia foi rejeitada pelos militares e nunca entrou em vigor no Brasil." },
      { id: "C", text: "A Lei da Anistia foi declarada inconstitucional pelo Supremo Tribunal Federal em 1985, logo após a redemocratização." },
      { id: "D", text: "A Lei da Anistia (1979) libertou presos políticos e permitiu o retorno dos exilados — mas também anistiou quem praticou 'crimes políticos' (interpretado como incluindo torturadores). Os torturadores nunca foram julgados. Divisão que polariza a sociedade brasileira até hoje." },
    ],
    correctAnswer: "D",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "O governo FIGUEIREDO (1979–1985) — o fim da ditadura. O que caracterizou esse último governo militar?",
    tip: "Figueiredo prometeu 'abrir esta nação à democracia' — o que efetivamente aconteceu durante seu mandato?",
    funFact: "\"Você Sabia?\" — Em 30 de abril de 1981, uma bomba explodiu num carro no Riocentro, durante um show do Dia do Trabalho, matando o próprio sargento que a transportava (Guilherme Pereira do Rosário). O caso mostrou que grupos dentro das Forças Armadas ainda resistiam à abertura. Figueiredo protegeu os envolvidos — a bomba foi explodida por militares de linha-dura para atribuir o ato a esquerdistas e justificar interrupção da abertura. O atentado fracassou e a abertura continuou.",
    points: 1,
    options: [
      { id: "A", text: "Figueiredo (1979–1985) encerrou a ditadura: Lei da Anistia, restauração do multipartidarismo, eleições diretas para governadores (1982), eleição indireta de Tancredo Neves (1985). Governou em crise econômica (dívida externa, inflação). O movimento 'Diretas Já' (1983–84) nasceu durante seu mandato." },
      { id: "B", text: "Figueiredo reverteu a abertura e aprofundou a repressão — seu governo foi mais violento que o de Médici." },
      { id: "C", text: "Figueiredo foi eleito em eleições diretas — o primeiro presidente eleito pelo povo desde Jânio Quadros." },
      { id: "D", text: "Figueiredo se recusou a devolver o poder aos civis e proclamou-se presidente vitalício em 1984." },
    ],
    correctAnswer: "A",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "A 'DÉCADA PERDIDA' dos anos 1980 no Brasil. O que aconteceu com a economia?",
    tip: "Após o 'Milagre', o que causou o colapso econômico dos anos 1980?",
    funFact: "\"Você Sabia?\" — Em março de 1990, no dia da posse de Collor, a inflação era de 80% ao mês. O Plano Cruzado (1986) de Sarney congelou preços — e criou o fenômeno do 'ágio': produtos sumiram das prateleiras, eram vendidos por baixo do pano com sobrepreço. A carne some, o leite some, o açúcar some. Sarney ganha as eleições de 1986 com o Cruzado em vigor. Dois meses após as eleições, os preços são liberados e a inflação explode. O Brasil passaria por 8 planos econômicos fracassados entre 1986 e 1994.",
    points: 1,
    options: [
      { id: "A", text: "Os anos 1980 foram a melhor década econômica do Brasil — o PIB cresceu mais do que durante o Milagre Econômico." },
      { id: "B", text: "Os anos 1980 foram ótimos para o Brasil graças ao Plano Cruzado, que controlou definitivamente a inflação." },
      { id: "C", text: "A 'Década Perdida': fim do Milagre, crise da dívida externa (moratória em 1987), hiperinflação (80% ao mês em 1989), 8 planos econômicos fracassados. Pobreza aumentou. O modelo de crescimento com dívida externa da ditadura cobrou sua conta." },
      { id: "D", text: "O Brasil quitou toda a dívida externa nos anos 1980 sem nenhum sacrifício social, demonstrando a força da economia nacional." },
    ],
    correctAnswer: "C",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "O COMÍCIO DE 13 DE MARÇO DE 1964 na Central do Brasil (Rio de Janeiro). O que foi e qual seu impacto?",
    tip: "O maior comício político da história do Brasil até então — o que Goulart anunciou e o que aconteceu 18 dias depois?",
    funFact: "\"Você Sabia?\" — Goulart anunciou no comício de 13 de março de 1964 a desapropriação de refinarias privadas de petróleo por decreto. Também assinou o Decreto de Reforma Agrária da margem das rodovias federais. Era o menor ato possível de reforma agrária — mas foi suficiente. O general Olímpio Mourão Filho deu início ao golpe em Minas Gerais em 31 de março. O restante do Exército seguiu. Em 1.º de abril, Goulart já havia fugido para o Uruguai.",
    points: 1,
    options: [
      { id: "A", text: "O comício de 13 de março de 1964 foi uma manifestação conservadora contra as reformas comunistas de Goulart." },
      { id: "B", text: "Goulart reuniu 150.000 pessoas na Central do Brasil e anunciou decretos de reforma agrária e nacionalização de refinarias — assustando conservadores e dando o pretexto final para o golpe 18 dias depois (31 de março–1.º de abril de 1964)." },
      { id: "C", text: "O comício de 13 de março de 1964 foi o próprio golpe militar — nele, os generais anunciaram a deposição de Goulart." },
      { id: "D", text: "O comício de 13 de março foi em favor do governo militar que já havia assumido o poder em janeiro de 1964." },
    ],
    correctAnswer: "B",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "A OPERAÇÃO LIMPEZA (1964) — as cassações imediatas após o golpe. O que aconteceu?",
    tip: "O que os militares fizeram com os opositores políticos imediatamente após o golpe de 1964?",
    funFact: "\"Você Sabia?\" — Entre os cassados estavam: o ex-presidente João Goulart (e mais tarde Kubitschek), os governadores Miguel Arraes (Pernambuco) e Mauro Borges (Goiás), o ex-governador Leonel Brizola, 6 generais, 55 coronéis, 90 majores, 44 capitães e centenas de oficiais de menor patente. Também foram cassados parlamentares, líderes sindicais, intelectuais, professores e artistas. Caetano Veloso, Gilberto Gil e Chico Buarque são exemplos de artistas perseguidos e exilados.",
    points: 1,
    options: [
      { id: "A", text: "Os militares não fizeram nenhuma cassação após o golpe — respeitaram todos os mandatos e cargos vigentes." },
      { id: "B", text: "As cassações afetaram apenas comunistas confessados — políticos democratas não foram atingidos." },
      { id: "C", text: "O golpe foi seguido de uma transição pacífica — Goulart continuou como presidente até entregar o cargo em dezembro de 1964." },
      { id: "D", text: "A 'Operação Limpeza' pós-golpe: cerca de 10.000 servidores públicos, militares, sindicalistas, políticos e intelectuais tiveram direitos políticos cassados nos primeiros anos. Goulart, Brizola, Arraes e Kubitschek foram exilados ou perderam mandatos." },
    ],
    correctAnswer: "D",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "O 'PACOTE DE ABRIL' de 1977 — como o regime manipulou as regras durante a 'abertura'. O que foi?",
    tip: "Mesmo durante a abertura, o regime manipulou as regras eleitorais quando a oposição ficou forte demais — o que Geisel fez?",
    funFact: "\"Você Sabia?\" — Com o sucesso eleitoral do MDB em 1974, o regime precisava de proteção para 1978. O 'Pacote de Abril': 1/3 dos senadores passou a ser indicado indiretamente (os 'senadores biônicos'). Criou-se a sublegenda para dividir o voto do MDB. O voto em banco para o Senado foi substituído por voto por estado. Resultado: Arena ganhou a maioria mesmo com menos votos populares que o MDB. A ditadura alterava as regras do jogo quando estava perdendo.",
    points: 1,
    options: [
      { id: "A", text: "O 'Pacote de Abril' de 1977 foi criado por Geisel para acelerar a transição democrática, estabelecendo eleições diretas imediatas." },
      { id: "B", text: "O 'Pacote de Abril' abriu o Brasil à democracia plena — foi o decreto que encerrou a ditadura em 1977." },
      { id: "C", text: "O 'Pacote de Abril' foi criado pela oposição para forçar o regime a realizar eleições diretas." },
      { id: "D", text: "O 'Pacote de Abril' foi algum outro evento de 1964 que não tem relação com o governo Geisel." },
    ],
    correctAnswer: "A",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "O papel da REDE GLOBO durante a ditadura militar. Qual foi a relação entre a emissora e o regime?",
    tip: "Como a Globo se tornou a maior rede de televisão do país durante um regime ditatorial?",
    funFact: "\"Você Sabia?\" — A prova mais escandalosa da relação Globo-ditadura foi a cobertura das 'Diretas Já' em São Paulo (16 de abril de 1984): cerca de 1,7 milhão de pessoas foram às ruas. O Jornal Nacional da Globo noticiou o evento como 'show de Roberto Carlos no Vale do Anhangabaú'. Apenas décadas depois, Roberto Marinho Filho pediu desculpas publicamente pela cobertura. A Globo passou das trevas à redenção: em 1984 escondia as Diretas; em 1989, Collor vs. Lula, a edição manipulada do debate foi o último escândalo da parceria.",
    points: 1,
    options: [
      { id: "A", text: "A Rede Globo foi fundada para se opor à ditadura militar — era o principal veículo de resistência." },
      { id: "B", text: "A Rede Globo (fundada 1965) recebeu proteção do regime (parceria com capital americano da Time-Life) em troca de cobertura favorável. Em 1984, manipulou a cobertura das 'Diretas Já'. Tornaram-se a maior emissora do país com apoio institucional do regime." },
      { id: "C", text: "A Rede Globo foi estatizada pela ditadura militar e só foi devolvida ao setor privado após a redemocratização." },
      { id: "D", text: "A ditadura militar proibiu a televisão como instrumento subversivo, fechando todas as emissoras." },
    ],
    correctAnswer: "B",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "A ESCOLA SUPERIOR DE GUERRA (ESG) e a 'Doutrina de Segurança Nacional'. O que foi essa doutrina?",
    tip: "Qual foi a base ideológica que justificou as ditaduras militares no Brasil e em toda a América do Sul?",
    funFact: "\"Você Sabia?\" — A 'Escola das Américas' (Fort Gulick, Panamá) treinou mais de 60.000 militares latino-americanos em técnicas de contra-insurgência — muitos dos quais tornaram-se torturadores em seus países. Bispos, professores e padres que eram defensores dos direitos humanos foram classificados como 'subversivos comunistas' pela Doutrina de Segurança Nacional. O curso incluía técnicas de interrogatório que eram, na prática, manuais de tortura.",
    points: 1,
    options: [
      { id: "A", text: "A ESG foi criada para treinar soldados brasileiros que voltavam da Guerra da Coreia." },
      { id: "B", text: "A ESG foi criada pela oposição para treinar guerrilheiros contra a ditadura." },
      { id: "C", text: "A ESG nunca existiu — a doutrina militar brasileira foi inteiramente importada dos EUA sem nenhuma produção própria." },
      { id: "D", text: "A ESG (1949) desenvolveu a 'Doutrina de Segurança Nacional': qualquer dissidência interna era vista como infiltração comunista ameaçando 'segurança e desenvolvimento'. Esse framework ideológico, compartilhado pelas ditaduras sulamericanas, justificou a tortura como 'necessidade da segurança nacional'." },
    ],
    correctAnswer: "D",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "As ELEIÇÕES DE 1974 e o crescimento do MDB. O que revelaram para o regime?",
    tip: "Qual foi o resultado surpresa das eleições de 1974 que assustou o governo Geisel?",
    funFact: "\"Você Sabia?\" — O senador eleito pelo MDB em São Paulo em 1974 foi Franco Montoro. Em 1982, ele seria o primeiro governador eleito diretamente em São Paulo desde o golpe. Na esteira das eleições de 1974, o PMDB elegeria André Franco Montoro governador de SP, Tancredo Neves de MG, Brizola no Rio — todos em 1982. O MDB plantou em 1974 o que colheria em 1982 e 1985.",
    points: 1,
    options: [
      { id: "A", text: "A Arena venceu as eleições de 1974 com maioria ainda maior — aprovando o retorno à democracia plena." },
      { id: "B", text: "As eleições de 1974 foram canceladas por Geisel ao perceber que perderia para o MDB." },
      { id: "C", text: "Nas eleições de 1974, o MDB quase dobrou sua bancada no Senado (de 7 para 16 vagas). Mesmo com regras desfavoráveis, o resultado mostrou rejeição popular ao regime e forçou Geisel a manipular as regras (Pacote de Abril, 1977)." },
      { id: "D", text: "A Arena venceu 100% das vagas em 1974 porque a oposição era ilegal naquele período da ditadura." },
    ],
    correctAnswer: "C",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "CARLOS MARIGHELLA e a teoria da guerrilha urbana no Brasil. Qual era sua estratégia?",
    tip: "O que Marighella esperava que aconteceria depois das ações armadas — e por que essa teoria falhou?",
    funFact: "\"Você Sabia?\" — Marighella foi morto em 4 de novembro de 1969 numa emboscada em São Paulo, organizada pelo delegado Sérgio Fleury. Tinha 57 anos — o 'guerrilheiro mais velho do mundo'. Seu 'Mini-Manual do Guerrilheiro Urbano' foi traduzido para dezenas de idiomas e usado por grupos armados em todo o mundo. Ele acreditava que a violência forçaria o regime a revelar sua face repressiva. O regime não hesitou — e a tortura foi sua resposta. A maioria da população não se radicalizou como Marighella esperava.",
    points: 1,
    options: [
      { id: "A", text: "Marighella (ALN) teorizou que ações armadas forçariam o regime a aumentar a repressão, o que radicalizaria o povo contra a ditadura. A teoria falhou: a repressão alienou, não radicalizou. Marighella foi morto numa emboscada em 1969." },
      { id: "B", text: "Marighella era um pacifista que nunca usou violência — foi morto pelos militares por meras atividades jornalísticas." },
      { id: "C", text: "Marighella era o líder do PCdoB, que organizou a guerrilha do Araguaia." },
      { id: "D", text: "Marighella escapou para Cuba após o golpe e nunca voltou ao Brasil, sendo morto em combate em Angola." },
    ],
    correctAnswer: "A",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "A IGREJA CATÓLICA e a oposição à ditadura nos anos 1970. Como ela se posicionou?",
    tip: "A Igreja havia apoiado o golpe de 1964 — como sua posição mudou nos anos 1970?",
    funFact: "\"Você Sabia?\" — Dom Paulo Evaristo Arns, arcebispo de São Paulo, guardou em segredo na Alemanha cópias de processos militares — a base do livro 'Brasil: Nunca Mais' (1985). 7.367 processos do Superior Tribunal Militar foram fotocopiados clandestinamente com ajuda ecumênica. O projeto durou 5 anos. Quando publicado, o livro ficou 40 semanas na lista de best-sellers. A ditadura não podia prender um arcebispo — então ele se tornou a memória do horror.",
    points: 1,
    options: [
      { id: "A", text: "A Igreja Católica apoiou a ditadura militar brasileira do início ao fim — nunca se opôs ao regime." },
      { id: "B", text: "A ala progressista da Igreja (Teologia da Libertação, dom Hélder Câmara, dom Paulo Arns) tornou-se nos anos 1970 uma das principais vozes contra a tortura e a repressão — abrigando ativistas, denunciando crimes, produzindo o 'Brasil: Nunca Mais'." },
      { id: "C", text: "A Igreja Católica foi fechada pela ditadura militar, que proibiu qualquer atividade religiosa no Brasil." },
      { id: "D", text: "A Teologia da Libertação nunca existiu no Brasil — foi um movimento exclusivamente da América Central." },
    ],
    correctAnswer: "B",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Os POVOS INDÍGENAS durante a ditadura militar. Como o regime tratou as comunidades indígenas?",
    tip: "Os projetos 'desenvolvimentistas' da ditadura (Transamazônica, usinas hidrelétricas) afetaram especialmente quais grupos?",
    funFact: "\"Você Sabia?\" — A operação contra os Waimiri-Atroari, no Amazonas, foi uma das mais documentadas. A população caiu de 6.000 em 1967 para 374 em 1983 — uma redução de 94% em 16 anos. O motivo: a construção da BR-174 e da usina hidrelétrica de Balbina cortou seus territórios. A Comissão Nacional da Verdade dedicou um capítulo específico às violações contra indígenas — a primeira vez que o Estado brasileiro reconheceu oficialmente o genocídio indígena na ditadura.",
    points: 1,
    options: [
      { id: "A", text: "A ditadura militar protegeu e demarcou as terras indígenas — foi o período de maior avanço dos direitos indígenas." },
      { id: "B", text: "A ditadura militar resolveu a 'questão indígena' integrando todos os povos à sociedade nacional sem violência." },
      { id: "C", text: "Os povos indígenas apoiaram a ditadura militar em troca de proteção contra madeireiros e fazendeiros." },
      { id: "D", text: "O 'desenvolvimentismo' da ditadura (Transamazônica, hidrelétricas, garimpo) destruiu comunidades indígenas inteiras. Os Waimiri-Atroari perderam 94% da população entre 1967 e 1983. A Comissão da Verdade reconheceu violações como genocídio." },
    ],
    correctAnswer: "D",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "A restauração do MULTIPARTIDARISMO em 1979 — por que Figueiredo extinguiu a Arena e o MDB?",
    tip: "Se o objetivo da ditadura era o controle, por que criar mais partidos em 1979?",
    funFact: "\"Você Sabia?\" — A estratégia funcionou parcialmente: o MDB se dividiu em PMDB (herdeiro direto), PDT (Brizola), PTB (fragmento mais conservador) e outros. Mas o regime não esperava o PT: fundado por Lula, intelectuais, teólogos da libertação e sindicalistas, o PT foi um partido com base social real, não um produto das elites. 23 anos depois de fundado, o PT venceu a presidência com Lula. A abertura controlada criou inadvertidamente a principal força de oposição do século XXI.",
    points: 1,
    options: [
      { id: "A", text: "Figueiredo (1979) extinguiu Arena e MDB e criou o multipartidarismo — estratégia para dividir a oposição concentrada no MDB. Criaram-se PMDB, PT (Partido dos Trabalhadores — Lula), PDT (Brizola), PTB e PDS (antigo Arena). O PT surgiu como força inesperada." },
      { id: "B", text: "Figueiredo restaurou o bipartidarismo Arena-MDB como única forma de garantir eleições controladas." },
      { id: "C", text: "Figueiredo aboliu todos os partidos políticos em 1979 para governar sem interferência parlamentar." },
      { id: "D", text: "O multipartidarismo foi restaurado por eleições diretas em 1978, não por decisão do governo Figueiredo." },
    ],
    correctAnswer: "A",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "A LEI FALCÃO (1976) e o controle da propaganda eleitoral. O que foi?",
    tip: "Por que o regime criou uma lei restringindo o que candidatos podiam dizer no rádio e na TV em período eleitoral?",
    funFact: "\"Você Sabia?\" — O nome 'Lei Falcão' veio do ministro Armando Falcão, que a elaborou. No horário eleitoral, o candidato aparecia numa foto estática com seu nome, número e currículo lido num tom monocorde de locutor. Nenhuma voz emocionante, nenhum discurso, nenhuma promessa. Comparado ao dinamismo dos comícios reais, o horário eleitoral era catastroficamente tedioso — mas igualava artificialmente os candidatos do regime e da oposição, impedindo que oradores mais talentosos do MDB mobilizassem eleitores.",
    points: 1,
    options: [
      { id: "A", text: "A Lei Falcão garantiu à oposição tempo igual ao governo no rádio e na TV para equilibrar a disputa eleitoral." },
      { id: "B", text: "A Lei Falcão foi o nome popular da Lei de Anistia de 1979." },
      { id: "C", text: "A Lei Falcão (1976) restringiu a propaganda eleitoral: candidatos só podiam exibir foto, nome e currículo no rádio e TV, sem discurso. Impedia que o crescimento eleitoral do MDB (com oradores mais talentosos) se traduzisse em votos." },
      { id: "D", text: "A Lei Falcão estabeleceu eleições diretas livres como único mecanismo de escolha de candidatos." },
    ],
    correctAnswer: "C",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "O II PND (Plano Nacional de Desenvolvimento, 1974–1979) — a aposta do Brasil contra a crise do petróleo. O que foi?",
    tip: "O choque do petróleo de 1973 atingiu o Brasil duramente — qual foi a resposta do governo Geisel?",
    funFact: "\"Você Sabia?\" — O Proálcool (1975) foi uma das apostas mais bem-sucedidas do II PND. O Brasil desenvolveu o carro a álcool e, décadas depois, a tecnologia flex-fuel (2003) — que permite usar álcool, gasolina ou qualquer mistura. Hoje o Brasil é o segundo maior produtor mundial de etanol (depois dos EUA). A crise do petróleo dos anos 1970 plantou a semente da matriz energética renovável brasileira do século XXI — um dos raros casos em que uma crise gerou uma resposta positiva de longo prazo.",
    points: 1,
    options: [
      { id: "A", text: "O II PND foi um plano social do governo Geisel focado em reduzir a pobreza e distribuir renda no Brasil." },
      { id: "B", text: "O II PND (1974–79) apostou em petroquímica, energia nuclear, Itaipu (hidrelétrica), Proálcool (etanol, 1975) e reserva de mercado para informática — para reduzir a dependência do petróleo importado. Criou legados duradouros (Itaipu, flex-fuel) mas também aprofundou a dívida externa." },
      { id: "C", text: "O II PND foi um plano de modernização das Forças Armadas para equipar o Exército com armamentos nacionais." },
      { id: "D", text: "O II PND foi um plano fracassado sem nenhum legado positivo para o Brasil — todos seus projetos foram abandonados." },
    ],
    correctAnswer: "B",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "A MORTE DE VLADIMIR HERZOG (outubro de 1975) — um marco da resistência à ditadura. O que aconteceu?",
    tip: "Como um caso de assassinato em custódia se transformou num ponto de inflexão para a abertura política?",
    funFact: "\"Você Sabia?\" — A versão oficial do 'suicídio' de Herzog era impossível: as fotos mostravam que o nó da corda estava no nível do chão — impossível para um enforcamento real. Era a posição de uma pessoa ajoelhada com a corda no pescoço, incapaz de se enforcar. O laudo era uma farsa grosseira que o regime nem se preocupou em tornar plausível. A missa ecumênica de dom Paulo Arns na Catedral da Sé (reunindo cristãos, judeus e outros, 8.000 pessoas) foi um ato de resistência coletiva sem precedentes.",
    points: 1,
    options: [
      { id: "A", text: "Herzog era um militar morto por guerrilheiros do MR-8 em outubro de 1975." },
      { id: "B", text: "A morte de Herzog foi aceita com passividade pela sociedade — não gerou nenhuma reação ou mobilização." },
      { id: "C", text: "Herzog era um político morto num confronto armado com a polícia." },
      { id: "D", text: "Vladimir Herzog, jornalista e diretor da TV Cultura, morreu nas dependências do DOI-CODI (outubro de 1975) — a versão de 'suicídio' foi desacreditada. A missa ecumênica de dom Paulo Arns na Catedral da Sé, a pressão da imprensa e da OAB forçaram Geisel a afastar o comandante responsável — símbolo de que a abertura era irrevogável." },
    ],
    correctAnswer: "D",
  },
];
