export const questoesPortugues7AnoB4Av2 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'Um texto que conta uma história, com personagens, tempo e espaço, é chamado de gênero textual:',
    tip: 'Pense no gênero textual que você estudou lá no início do ano, usado para "contar histórias".',
    funFact: 'Contos, romances, fábulas e crônicas são todos exemplos de textos narrativos!',
    points: 1,
    options: [
      { id: 'A', text: 'Receita' },
      { id: 'B', text: 'Notícia' },
      { id: 'C', text: 'Narrativo (conto, por exemplo)' },
      { id: 'D', text: 'Anúncio' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'Os elementos da narrativa incluem personagens, tempo, espaço, enredo e:',
    tip: 'Pense em quem "conta" a história para o leitor.',
    funFact: 'O narrador pode contar a história de dentro dela (narrador-personagem) ou de fora, apenas observando (narrador-observador)!',
    points: 1,
    options: [
      { id: 'A', text: 'Narrador' },
      { id: 'B', text: 'Rima' },
      { id: 'C', text: 'Sujeito' },
      { id: 'D', text: 'Verbo' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'O narrador que conta a história participando dela, usando a primeira pessoa ("eu"), é chamado de narrador:',
    tip: 'Pense em um narrador que também é um dos personagens da própria história.',
    funFact: 'Esse tipo de narrador costuma usar a palavra "eu" o tempo todo ao longo da narrativa!',
    points: 1,
    options: [
      { id: 'A', text: 'Onisciente' },
      { id: 'B', text: 'Observador' },
      { id: 'C', text: 'Em terceira pessoa' },
      { id: 'D', text: 'Personagem (ou narrador-personagem)' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'O conjunto de acontecimentos de uma história, em ordem, é chamado de:',
    tip: 'Pense na "trama" da história, tudo o que acontece do começo ao fim.',
    funFact: 'O enredo costuma seguir uma estrutura com início, desenvolvimento, clímax e desfecho!',
    points: 1,
    options: [
      { id: 'A', text: 'Narrador' },
      { id: 'B', text: 'Enredo' },
      { id: 'C', text: 'Figura de linguagem' },
      { id: 'D', text: 'Pronome' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'Uma notícia de jornal é um exemplo de gênero textual:',
    tip: 'Pense no objetivo de uma notícia: informar fatos reais, e não contar uma ficção.',
    funFact: 'Diferente do conto, a notícia precisa ser sempre baseada em fatos reais e verificáveis!',
    points: 1,
    options: [
      { id: 'A', text: 'Narrativo (ficção)' },
      { id: 'B', text: 'Poético' },
      { id: 'C', text: 'Jornalístico (informativo)' },
      { id: 'D', text: 'Dramático' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'Pronomes são palavras que substituem ou acompanham um substantivo. "Meu", "teu", "seu" são pronomes:',
    tip: 'Pense em palavras que indicam posse, como "meu caderno" ou "teu livro".',
    funFact: 'Os pronomes possessivos sempre concordam com a coisa possuída, não com o dono dela!',
    points: 1,
    options: [
      { id: 'A', text: 'Possessivos' },
      { id: 'B', text: 'Demonstrativos' },
      { id: 'C', text: 'Interrogativos' },
      { id: 'D', text: 'Indefinidos' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: '"Este", "esse", "aquele" são pronomes:',
    tip: 'Pense em palavras que indicam a posição de algo em relação a quem fala e a quem ouve.',
    funFact: 'Esses pronomes ajudam a "apontar" para coisas no espaço ou dentro do próprio texto!',
    points: 1,
    options: [
      { id: 'A', text: 'Possessivos' },
      { id: 'B', text: 'Demonstrativos' },
      { id: 'C', text: 'Pessoais' },
      { id: 'D', text: 'Relativos' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'O verbo "estudar" no pretérito perfeito do indicativo, na primeira pessoa do singular, fica:',
    tip: 'Pense em como você diria que já terminou de estudar, no passado.',
    funFact: 'O pretérito perfeito indica uma ação já concluída, pontual no passado!',
    points: 1,
    options: [
      { id: 'A', text: 'Estudo' },
      { id: 'B', text: 'Estudava' },
      { id: 'C', text: 'Estudarei' },
      { id: 'D', text: 'Estudei' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'O modo verbal usado para dar ordens é chamado de:',
    tip: 'Pense no modo verbal usado quando alguém dá um pedido ou uma ordem direta.',
    funFact: 'O imperativo também é muito usado em receitas e manuais de instrução!',
    points: 1,
    options: [
      { id: 'A', text: 'Indicativo' },
      { id: 'B', text: 'Subjuntivo' },
      { id: 'C', text: 'Imperativo' },
      { id: 'D', text: 'Infinitivo' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'A forma do verbo sem indicar tempo nem pessoa, terminando em -ar, -er ou -ir, é chamada de:',
    tip: 'É a forma "original" do verbo, a mesma que aparece no dicionário.',
    funFact: 'Todo verbo, ao ser procurado no dicionário, aparece sempre na forma do infinitivo!',
    points: 1,
    options: [
      { id: 'A', text: 'Infinitivo' },
      { id: 'B', text: 'Gerúndio' },
      { id: 'C', text: 'Particípio' },
      { id: 'D', text: 'Imperativo' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'Atribuir características humanas a seres não humanos é a figura de linguagem chamada de:',
    tip: 'Pense em animais ou objetos "agindo" como se fossem pessoas.',
    funFact: 'Essa figura de linguagem é muito usada em fábulas e histórias infantis!',
    points: 1,
    options: [
      { id: 'A', text: 'Metáfora' },
      { id: 'B', text: 'Hipérbole' },
      { id: 'C', text: 'Comparação' },
      { id: 'D', text: 'Personificação' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'Na frase "Ela é um anjo", sem usar a palavra "como", temos a figura de linguagem chamada de:',
    tip: 'Repare que não há a palavra "como" — a comparação é feita de forma direta.',
    funFact: 'A metáfora é considerada uma comparação "implícita", sem o uso de conectivos como "como"!',
    points: 1,
    options: [
      { id: 'A', text: 'Comparação' },
      { id: 'B', text: 'Metáfora' },
      { id: 'C', text: 'Onomatopeia' },
      { id: 'D', text: 'Antítese' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'Um exagero proposital para dar ênfase a uma ideia é chamado de:',
    tip: 'Pense em frases bem exageradas, como "já te falei mil vezes!".',
    funFact: 'A hipérbole é uma das figuras de linguagem mais usadas no dia a dia, muitas vezes sem percebermos!',
    points: 1,
    options: [
      { id: 'A', text: 'Eufemismo' },
      { id: 'B', text: 'Metáfora' },
      { id: 'C', text: 'Hipérbole' },
      { id: 'D', text: 'Antítese' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'A reprodução de um som através de uma palavra, como "au au" ou "tique-taque", é chamada de:',
    tip: 'Pense em palavras que imitam sons reais.',
    funFact: 'As onomatopeias são muito usadas em histórias em quadrinhos!',
    points: 1,
    options: [
      { id: 'A', text: 'Onomatopeia' },
      { id: 'B', text: 'Metáfora' },
      { id: 'C', text: 'Antítese' },
      { id: 'D', text: 'Eufemismo' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'Unir palavras ou ideias opostas na mesma frase é a figura de linguagem chamada de:',
    tip: 'Pense em duas ideias contrárias colocadas lado a lado.',
    funFact: '"Antítese" vem do grego e significa "colocar contra"!',
    points: 1,
    options: [
      { id: 'A', text: 'Metáfora' },
      { id: 'B', text: 'Onomatopeia' },
      { id: 'C', text: 'Hipérbole' },
      { id: 'D', text: 'Antítese' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'A ligação gramatical entre as partes de um texto, feita por conectivos e pronomes, é chamada de:',
    tip: 'Pense na "costura" gramatical que une as partes de um texto.',
    funFact: 'A coesão cuida da ligação das palavras e frases, enquanto a coerência cuida do sentido lógico do texto!',
    points: 1,
    options: [
      { id: 'A', text: 'Coerência' },
      { id: 'B', text: 'Coesão' },
      { id: 'C', text: 'Concordância' },
      { id: 'D', text: 'Regência' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'O sentido lógico de um texto, fazendo as ideias se conectarem de forma compreensível, é chamado de:',
    tip: 'Pense no significado da palavra "coerente" — algo que faz sentido.',
    funFact: 'Um texto pode ter boa coesão e, mesmo assim, não ter coerência, se as ideias não fizerem sentido juntas!',
    points: 1,
    options: [
      { id: 'A', text: 'Coerência' },
      { id: 'B', text: 'Coesão' },
      { id: 'C', text: 'Concordância' },
      { id: 'D', text: 'Pontuação' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'Na frase "Estudei bastante, mas fiquei nervoso na prova", o conectivo "mas" indica uma relação de:',
    tip: 'Pense no contraste entre estudar bastante e, mesmo assim, ficar nervoso.',
    funFact: '"Mas" é um dos conectivos mais usados na língua portuguesa para mostrar contrastes!',
    points: 1,
    options: [
      { id: 'A', text: 'Causa' },
      { id: 'B', text: 'Adição' },
      { id: 'C', text: 'Oposição' },
      { id: 'D', text: 'Conclusão' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'Na frase "Estudei bastante, por isso fui bem na prova", o conectivo "por isso" indica uma relação de:',
    tip: 'Pense no resultado de ter estudado bastante — "por isso" liga a causa ao seu efeito.',
    funFact: '"Por isso" tem o mesmo sentido de "portanto" e "logo"!',
    points: 1,
    options: [
      { id: 'A', text: 'Oposição' },
      { id: 'B', text: 'Tempo' },
      { id: 'C', text: 'Adição' },
      { id: 'D', text: 'Consequência (conclusão)' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'Usar sinônimos e pronomes para evitar repetir sempre a mesma palavra é uma estratégia que melhora a:',
    tip: 'Pense no que você estudou sobre a ligação gramatical entre as partes de um texto.',
    funFact: 'Essa é uma das estratégias mais simples e eficazes para deixar um texto mais agradável de ler!',
    points: 1,
    options: [
      { id: 'A', text: 'Coerência apenas' },
      { id: 'B', text: 'Coesão do texto' },
      { id: 'C', text: 'Rima do texto' },
      { id: 'D', text: 'Pontuação do texto' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'A concordância verbal é a regra que faz o verbo concordar em número e pessoa com o:',
    tip: 'Pense em quem pratica a ação do verbo na frase.',
    funFact: 'A concordância verbal é uma das regras mais importantes para deixar uma frase gramaticalmente correta!',
    points: 1,
    options: [
      { id: 'A', text: 'Sujeito da frase' },
      { id: 'B', text: 'Objeto da frase' },
      { id: 'C', text: 'Adjetivo da frase' },
      { id: 'D', text: 'Advérbio da frase' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Complete corretamente: "Os alunos ______ para a prova" (verbo estudar).',
    tip: '"Os alunos" é um sujeito no plural — o verbo precisa concordar com ele.',
    funFact: '"Estudaram" está no pretérito perfeito, na terceira pessoa do plural!',
    points: 1,
    options: [
      { id: 'A', text: 'Estudou' },
      { id: 'B', text: 'Estuda' },
      { id: 'C', text: 'Estudaram' },
      { id: 'D', text: 'Estudo' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'A concordância nominal faz o artigo, o adjetivo e o pronome concordarem em gênero e número com o:',
    tip: 'Pense na palavra principal que o artigo e o adjetivo estão acompanhando.',
    funFact: 'É por isso que dizemos "a casa bonita" e "o carro bonito" — tudo concorda com o substantivo!',
    points: 1,
    options: [
      { id: 'A', text: 'Verbo' },
      { id: 'B', text: 'Substantivo' },
      { id: 'C', text: 'Advérbio' },
      { id: 'D', text: 'Conectivo' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Complete corretamente: "As casas ______ foram vendidas" (adjetivo "bonito").',
    tip: '"Casas" é um substantivo feminino plural — o adjetivo precisa concordar nos dois aspectos.',
    funFact: 'A concordância nominal exige atenção tanto ao gênero quanto ao número do substantivo!',
    points: 1,
    options: [
      { id: 'A', text: 'Bonito' },
      { id: 'B', text: 'Bonitos' },
      { id: 'C', text: 'Bonita' },
      { id: 'D', text: 'Bonitas' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Na frase "A maioria dos alunos foi ao passeio", o verbo "foi" está no singular porque concorda com:',
    tip: 'Pense que "a maioria" é uma expressão no singular, mesmo representando várias pessoas.',
    funFact: 'Essa regra vale também para expressões parecidas, como "a maior parte de" ou "grande parte dos"!',
    points: 1,
    options: [
      { id: 'A', text: 'A maioria (expressão no singular)' },
      { id: 'B', text: 'Os alunos (plural)' },
      { id: 'C', text: 'O passeio (singular)' },
      { id: 'D', text: 'Ao (preposição+artigo)' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Bernardo escreveu uma história com início, meio e fim, contando as aventuras de um personagem. Esse tipo de texto é um gênero:',
    tip: 'Pense no gênero textual usado para contar histórias com personagens e enredo.',
    funFact: 'Bernardo está seguindo a mesma estrutura usada em contos, fábulas e romances!',
    points: 1,
    options: [
      { id: 'A', text: 'Jornalístico' },
      { id: 'B', text: 'Publicitário' },
      { id: 'C', text: 'Narrativo' },
      { id: 'D', text: 'Instrucional' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Na redação de Bernardo, a frase "Meu cachorro é um furacão quando vê a bola" usa a figura de linguagem chamada de:',
    tip: 'Repare que o cachorro está sendo chamado diretamente de "furacão", sem usar a palavra "como".',
    funFact: 'Bernardo usou essa metáfora para mostrar, de forma criativa, a energia do seu cachorro!',
    points: 1,
    options: [
      { id: 'A', text: 'Comparação' },
      { id: 'B', text: 'Onomatopeia' },
      { id: 'C', text: 'Antítese' },
      { id: 'D', text: 'Metáfora' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Bernardo revisou seu texto e trocou a palavra repetida "bola" por "ela" na segunda vez que apareceu. Essa troca melhora a:',
    tip: 'Pense no que você aprendeu sobre o uso de pronomes para evitar repetições.',
    funFact: 'Essa é uma das formas mais simples de melhorar a coesão de um texto!',
    points: 1,
    options: [
      { id: 'A', text: 'Concordância do texto' },
      { id: 'B', text: 'Coesão do texto' },
      { id: 'C', text: 'Figura de linguagem do texto' },
      { id: 'D', text: 'Pontuação do texto' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Bernardo corrigiu a frase "Os meninos chegou atrasado" para a forma correta, usando a concordância verbal certa:',
    tip: 'Verifique se o verbo e o adjetivo concordam corretamente com o sujeito "os meninos", no plural.',
    funFact: 'A frase original tinha erros tanto na concordância verbal quanto na nominal — ambos precisavam ser corrigidos!',
    points: 1,
    options: [
      { id: 'A', text: 'Os meninos chegaram atrasados' },
      { id: 'B', text: 'Os menino chegaram atrasado' },
      { id: 'C', text: 'Os meninos chegou atrasados' },
      { id: 'D', text: 'O meninos chegaram atrasado' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'No fim do ano letivo, Bernardo resumiu tudo o que aprendeu em Português: gêneros textuais, elementos da narrativa, pronomes, verbos, figuras de linguagem, coesão, coerência e concordância. Todo esse conhecimento ajuda a:',
    tip: 'Pense no objetivo final de estudar gramática e interpretação de texto ao longo do ano.',
    funFact: 'Parabéns, Bernardo! Você completou um ano inteiro de estudos de Português — gêneros textuais, gramática e muito mais. Você está cada vez mais preparado para ler, escrever e se comunicar bem!',
    points: 1,
    options: [
      { id: 'A', text: 'Confundir quem lê um texto' },
      { id: 'B', text: 'Decorar regras sem necessidade' },
      { id: 'C', text: 'Ler, escrever e se comunicar melhor' },
      { id: 'D', text: 'Substituir a leitura de livros' },
    ],
    correctAnswer: 'C',
  },
];
