export const questoesGeografia9AnoB2Av1 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'Os Estados Unidos estão localizados em qual continente?',
    tip: 'Pensa no nome do continente que fica acima da América do Sul, incluindo também o Canadá e o México.',
    funFact: 'Os Estados Unidos são o terceiro maior país do mundo em território, atrás apenas de Rússia e Canadá!',
    points: 1,
    options: [
      { id: 'A', text: 'América do Sul' },
      { id: 'B', text: 'Europa' },
      { id: 'C', text: 'Ásia' },
      { id: 'D', text: 'América do Norte' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'Qual é a capital dos Estados Unidos?',
    tip: 'A capital não é a cidade mais famosa do país — pensa numa cidade que leva o nome de um dos fundadores dos EUA.',
    funFact: 'Washington, D.C. foi nomeada em homenagem a George Washington, o primeiro presidente dos Estados Unidos!',
    points: 1,
    options: [
      { id: 'A', text: 'Washington, D.C.' },
      { id: 'B', text: 'Nova York' },
      { id: 'C', text: 'Los Angeles' },
      { id: 'D', text: 'Chicago' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'Os Estados Unidos fazem fronteira com quais países?',
    tip: 'Pensa nos dois países vizinhos: um ao norte e outro ao sul dos Estados Unidos.',
    funFact: 'A fronteira entre Estados Unidos e Canadá é considerada a maior fronteira terrestre do mundo entre dois países!',
    points: 1,
    options: [
      { id: 'A', text: 'Brasil e Argentina' },
      { id: 'B', text: 'Canadá e México' },
      { id: 'C', text: 'França e Espanha' },
      { id: 'D', text: 'China e Japão' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'Por que os Estados Unidos são considerados uma das maiores potências econômicas do mundo?',
    tip: 'Pensa em tudo que você já sabe sobre empresas americanas de tecnologia, bancos e indústrias conhecidas no mundo todo.',
    funFact: 'Os Estados Unidos têm, historicamente, uma das maiores economias do mundo, ao lado da China!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque não têm nenhuma indústria' },
      { id: 'B', text: 'Porque dependem apenas da agricultura' },
      { id: 'C', text: 'Porque possuem grande desenvolvimento industrial, tecnológico e financeiro' },
      { id: 'D', text: 'Porque não participam do comércio internacional' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'O Vale do Silício, nos Estados Unidos, é famoso por reunir empresas de qual setor?',
    tip: 'Pensa em grandes empresas de computadores, celulares e internet que você já ouviu falar — muitas têm sede nessa região.',
    funFact: 'O Vale do Silício fica no estado da Califórnia e reúne empresas de tecnologia conhecidas no mundo todo!',
    points: 1,
    options: [
      { id: 'A', text: 'Agricultura' },
      { id: 'B', text: 'Pesca' },
      { id: 'C', text: 'Mineração' },
      { id: 'D', text: 'Tecnologia' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'Qual destes é um importante produto agrícola dos Estados Unidos?',
    tip: 'Pensa em grãos muito produzidos em grandes fazendas americanas, usados tanto na alimentação quanto na indústria.',
    funFact: 'Os Estados Unidos são um dos maiores produtores mundiais de milho e soja, assim como o Brasil!',
    points: 1,
    options: [
      { id: 'A', text: 'Café exclusivamente' },
      { id: 'B', text: 'Milho e soja' },
      { id: 'C', text: 'Apenas arroz' },
      { id: 'D', text: 'Apenas cacau' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'Os Estados Unidos são formados por quantos estados?',
    tip: 'Pensa na bandeira dos Estados Unidos — cada estrela nela representa um estado do país.',
    funFact: 'A bandeira americana tem 50 estrelas, uma para cada estado, e 13 listras, representando as colônias originais!',
    points: 1,
    options: [
      { id: 'A', text: '50 estados' },
      { id: 'B', text: '10 estados' },
      { id: 'C', text: '100 estados' },
      { id: 'D', text: '27 estados' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'A população dos Estados Unidos é marcada por qual característica histórica importante?',
    tip: 'Pensa na história dos Estados Unidos: pessoas de várias partes do mundo foram para lá ao longo dos séculos.',
    funFact: 'A Estátua da Liberdade, em Nova York, é um símbolo histórico de boas-vindas aos imigrantes que chegavam ao país!',
    points: 1,
    options: [
      { id: 'A', text: 'Isolamento total de outros povos' },
      { id: 'B', text: 'Ausência completa de imigração' },
      { id: 'C', text: 'Forte diversidade cultural, formada por imigrantes de diversas partes do mundo' },
      { id: 'D', text: 'Homogeneidade cultural total' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'Qual destes é um bioma ou característica natural encontrada nos Estados Unidos?',
    tip: 'Pensa no tamanho do país — ele é tão grande que abriga vários tipos de paisagens diferentes ao mesmo tempo.',
    funFact: 'Os Estados Unidos têm desde desertos no Arizona até florestas no nordeste e montanhas nevadas no oeste!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas desertos' },
      { id: 'B', text: 'Apenas florestas tropicais' },
      { id: 'C', text: 'Apenas geleiras' },
      { id: 'D', text: 'Grande diversidade de climas e relevos, de desertos a florestas e montanhas' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'Os Estados Unidos são frequentemente descritos como uma das principais potências mundiais em qual área, além da economia?',
    tip: 'Lembra da Questão 5 desta prova? Pensa na região famosa por empresas de tecnologia.',
    funFact: 'Muitas invenções importantes, como o smartphone moderno, tiveram grande desenvolvimento em empresas americanas!',
    points: 1,
    options: [
      { id: 'A', text: 'Tecnologia e inovação' },
      { id: 'B', text: 'Pesca artesanal' },
      { id: 'C', text: 'Agricultura de subsistência' },
      { id: 'D', text: 'Artesanato tradicional' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'Por que a localização geográfica dos Estados Unidos, entre dois oceanos, é considerada estratégica?',
    tip: 'Pensa nos dois oceanos que tocam o território americano — um do lado do Atlântico e outro do Pacífico.',
    funFact: 'Essa posição entre dois oceanos ajuda os EUA a comercializar facilmente com praticamente qualquer continente do mundo!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque impede qualquer tipo de comércio internacional' },
      { id: 'B', text: 'Porque isola o país completamente do resto do mundo' },
      { id: 'C', text: 'Porque facilita o comércio marítimo tanto com a Europa/África quanto com a Ásia' },
      { id: 'D', text: 'Porque não tem nenhuma relação com a economia' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'O que torna o Vale do Silício um polo tão importante para a economia mundial?',
    tip: 'Lembra das Questões 5 e 10 desta prova? Pensa em como a tecnologia criada ali chega até você, no celular ou computador.',
    funFact: 'Produtos e aplicativos criados no Vale do Silício são usados por pessoas em praticamente todos os países do mundo!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque lá só existe agricultura' },
      { id: 'B', text: 'Porque concentra grandes empresas de tecnologia e inovação, influenciando o mundo todo' },
      { id: 'C', text: 'Porque é uma região isolada, sem nenhuma conexão internacional' },
      { id: 'D', text: 'Porque não tem nenhuma relação com a tecnologia' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'Por que os Estados Unidos recebem o apelido de "terra das oportunidades" por muitos imigrantes?',
    tip: 'Lembra da Questão 8 desta prova? Pensa no que leva tantas pessoas a se mudarem para outro país em busca de uma vida melhor.',
    funFact: 'Esse apelido existe há mais de um século, desde as grandes ondas de imigração europeia para os Estados Unidos!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque é proibido imigrar para o país' },
      { id: 'B', text: 'Porque o país não aceita nenhum imigrante' },
      { id: 'C', text: 'Porque a economia do país está sempre em crise' },
      { id: 'D', text: 'Porque muitas pessoas migraram para lá em busca de melhores condições de vida e trabalho' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'Qual é uma das razões para os Estados Unidos terem uma agricultura tão produtiva?',
    tip: 'Lembra da Questão 6 desta prova? Pensa no tipo de terreno necessário para plantar milho e soja em grande escala.',
    funFact: 'A região central dos Estados Unidos, conhecida como "Corn Belt" (cinturão do milho), é uma das áreas agrícolas mais produtivas do mundo!',
    points: 1,
    options: [
      { id: 'A', text: 'Grandes extensões de terras planas e férteis, aliadas à tecnologia no campo' },
      { id: 'B', text: 'A ausência completa de máquinas agrícolas' },
      { id: 'C', text: 'O uso exclusivo de trabalho manual' },
      { id: 'D', text: 'A falta de água em todo o território' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'Como a diversidade cultural dos Estados Unidos está relacionada à sua história?',
    tip: 'É a mesma ideia das Questões 8 e 13 desta prova.',
    funFact: 'Hoje, é comum encontrar bairros nos Estados Unidos com forte influência cultural italiana, chinesa, mexicana e de muitos outros povos!',
    points: 1,
    options: [
      { id: 'A', text: 'O país nunca recebeu imigrantes' },
      { id: 'B', text: 'A diversidade não tem relação com a história do país' },
      { id: 'C', text: 'Ao longo da história, o país recebeu grandes ondas de imigração de diferentes partes do mundo' },
      { id: 'D', text: 'Toda a população é descendente de um único povo' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'Por que os Estados Unidos são considerados uma superpotência global?',
    tip: 'Pensa em tudo que você já estudou nesta prova sobre a economia, a tecnologia e a cultura americana.',
    funFact: 'A influência dos Estados Unidos é tão grande que decisões econômicas do país podem afetar mercados financeiros no mundo inteiro!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque não têm nenhuma influência fora do seu território' },
      { id: 'B', text: 'Porque possuem apenas força militar, sem nenhuma influência econômica' },
      { id: 'C', text: 'Porque isolam sua economia do resto do mundo' },
      { id: 'D', text: 'Porque combinam grande poder econômico, militar, tecnológico e cultural, influenciando o mundo todo' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'O que caracteriza o relevo dos Estados Unidos, de forma geral?',
    tip: 'Lembra da Questão 9 desta prova? Pensa no tamanho do país e na diversidade de paisagens que ele abriga.',
    funFact: 'As Montanhas Rocosas atravessam boa parte do território americano, de norte a sul!',
    points: 1,
    options: [
      { id: 'A', text: 'É formado apenas por desertos' },
      { id: 'B', text: 'É bastante variado, com planícies, montanhas (como as Montanhas Rocosas) e litoral' },
      { id: 'C', text: 'É formado só por geleiras' },
      { id: 'D', text: 'Não existe nenhuma variação de relevo' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'Por que o comércio entre Estados Unidos, Canadá e México é tão importante na América do Norte?',
    tip: 'Lembra da Questão 3 desta prova? Pensa na proximidade geográfica entre esses três países.',
    funFact: 'Esses três países têm um acordo de livre comércio, parecido com o Mercosul que você estudou na prova anterior!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque esses países são vizinhos e mantêm fortes laços econômicos entre si' },
      { id: 'B', text: 'Porque esses países nunca comercializam entre si' },
      { id: 'C', text: 'Porque esses países não têm nenhuma relação geográfica' },
      { id: 'D', text: 'Porque o comércio entre eles é proibido' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'Qual é uma característica da indústria cultural dos Estados Unidos (cinema, música, tecnologia) com alcance mundial?',
    tip: 'Pensa em filmes de Hollywood ou aplicativos americanos que você já usou ou assistiu.',
    funFact: 'Hollywood, nos Estados Unidos, é considerada uma das maiores indústrias de cinema do mundo!',
    points: 1,
    options: [
      { id: 'A', text: 'Ela não tem nenhuma influência fora do país' },
      { id: 'B', text: 'Ela é totalmente desconhecida fora dos Estados Unidos' },
      { id: 'C', text: 'Ela influencia fortemente a cultura de diversos países, através de filmes, músicas e aplicativos' },
      { id: 'D', text: 'Ela é proibida de ser exportada' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'Por que os Estados Unidos são um dos principais destinos de imigrantes no mundo?',
    tip: 'É a mesma ideia das Questões 8, 13 e 15 desta prova.',
    funFact: 'Milhões de pessoas de diferentes países já se mudaram para os Estados Unidos ao longo da história em busca de uma vida melhor!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque o país não aceita nenhum estrangeiro' },
      { id: 'B', text: 'Porque a economia do país está sempre em crise' },
      { id: 'C', text: 'Porque é proibido entrar no país' },
      { id: 'D', text: 'Porque muitas pessoas buscam melhores oportunidades econômicas, educacionais e sociais no país' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Bernardo estudou um mapa e descobriu que os Estados Unidos fazem fronteira com dois países vizinhos. Quais são eles?',
    tip: 'É a mesma resposta da Questão 3 desta prova.',
    funFact: 'Essas três nações (EUA, Canadá e México) formam a região conhecida como América do Norte!',
    points: 1,
    options: [
      { id: 'A', text: 'Canadá e México' },
      { id: 'B', text: 'Brasil e Argentina' },
      { id: 'C', text: 'França e Espanha' },
      { id: 'D', text: 'China e Japão' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Bernardo leu sobre uma região dos Estados Unidos famosa por reunir grandes empresas de tecnologia. Qual é essa região?',
    tip: 'É a mesma região das Questões 5, 10 e 12 desta prova.',
    funFact: 'O nome "Vale do Silício" vem do silício, material usado para fabricar chips de computador!',
    points: 1,
    options: [
      { id: 'A', text: 'Montanhas Rocosas' },
      { id: 'B', text: 'Vale do Silício' },
      { id: 'C', text: 'Grandes Lagos' },
      { id: 'D', text: 'Deserto do Saara' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Bernardo descobriu que a capital dos Estados Unidos não é a cidade mais famosa do país, mas sim outra cidade. Qual é a capital?',
    tip: 'É a mesma capital da Questão 2 desta prova.',
    funFact: 'Em Washington, D.C., fica a Casa Branca, residência oficial do presidente dos Estados Unidos!',
    points: 1,
    options: [
      { id: 'A', text: 'Nova York' },
      { id: 'B', text: 'Los Angeles' },
      { id: 'C', text: 'Washington, D.C.' },
      { id: 'D', text: 'Chicago' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Bernardo aprendeu que a população dos Estados Unidos é marcada por uma grande mistura de culturas. Por que isso acontece historicamente?',
    tip: 'É a mesma explicação das Questões 8, 15 e 20 desta prova.',
    funFact: 'Essa diversidade cultural é visível até hoje nas diferentes comidas, festas e tradições encontradas em várias cidades americanas!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque o país nunca recebeu imigrantes' },
      { id: 'B', text: 'Porque todos os habitantes descendem de um único povo' },
      { id: 'C', text: 'Porque a imigração é proibida no país' },
      { id: 'D', text: 'Porque o país recebeu, ao longo da história, grandes ondas de imigrantes de diferentes partes do mundo' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Bernardo quis saber por que os Estados Unidos têm uma agricultura tão produtiva. A resposta certa é:',
    tip: 'É a mesma resposta das Questões 6 e 14 desta prova.',
    funFact: 'Grandes máquinas agrícolas, como colheitadeiras modernas, ajudam os Estados Unidos a produzir alimentos em grande escala!',
    points: 1,
    options: [
      { id: 'A', text: 'Grandes extensões de terras férteis, combinadas com tecnologia no campo' },
      { id: 'B', text: 'A ausência completa de máquinas agrícolas' },
      { id: 'C', text: 'O uso exclusivo de trabalho manual' },
      { id: 'D', text: 'A falta de água em todo o território' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Bernardo observou, no mapa, que os Estados Unidos têm litoral tanto no Oceano Atlântico quanto no Oceano Pacífico. Por que essa localização é considerada estratégica?',
    tip: 'É a mesma ideia da Questão 11 desta prova.',
    funFact: 'Grandes portos americanos, como o de Los Angeles e o de Nova York, são fundamentais para o comércio internacional do país!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque impede qualquer comércio internacional' },
      { id: 'B', text: 'Porque isola totalmente o país' },
      { id: 'C', text: 'Porque facilita o comércio marítimo com diferentes regiões do mundo' },
      { id: 'D', text: 'Porque não tem relação com a economia' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Bernardo assistiu a um filme americano e percebeu como a cultura dos Estados Unidos influencia outros países. Isso é um exemplo de:',
    tip: 'É a mesma ideia da Questão 19 desta prova.',
    funFact: 'Muitos filmes e séries vistos no Brasil e em outros países são produzidos nos Estados Unidos!',
    points: 1,
    options: [
      { id: 'A', text: 'Isolamento cultural total' },
      { id: 'B', text: 'Forte influência cultural internacional, através de filmes, músicas e tecnologia' },
      { id: 'C', text: 'Ausência de qualquer exportação cultural' },
      { id: 'D', text: 'Proibição de produtos culturais estrangeiros' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Bernardo percebeu que muitos imigrantes buscam os Estados Unidos em busca de melhores oportunidades. Esse fenômeno mostra que o país é visto, por muitos, como:',
    tip: 'É a mesma ideia das Questões 13 e 20 desta prova.',
    funFact: 'Esse apelido de "terra das oportunidades" é usado há mais de um século para descrever os Estados Unidos!',
    points: 1,
    options: [
      { id: 'A', text: 'Um país isolado do resto do mundo' },
      { id: 'B', text: 'Um país sem nenhuma oportunidade econômica' },
      { id: 'C', text: 'Um país fechado para estrangeiros' },
      { id: 'D', text: 'Um destino de oportunidades econômicas, educacionais e sociais' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Bernardo aprendeu que os Estados Unidos combinam grande poder econômico, militar, tecnológico e cultural. Por isso, o país é chamado de:',
    tip: 'É o mesmo termo da Questão 16 desta prova.',
    funFact: 'Esse termo "superpotência" também foi usado para descrever a União Soviética durante a Guerra Fria, que você estudou na prova anterior!',
    points: 1,
    options: [
      { id: 'A', text: 'Superpotência global' },
      { id: 'B', text: 'País isolado' },
      { id: 'C', text: 'Nação sem influência internacional' },
      { id: 'D', text: 'Pequena economia regional' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'No fim da aula, o professor perguntou a Bernardo o que torna os Estados Unidos uma das maiores potências do mundo. Bernardo respondeu corretamente:',
    tip: 'Pensa em tudo que você aprendeu nesta prova sobre os diferentes pontos fortes dos Estados Unidos.',
    funFact: 'Essa combinação de forças é o que faz muitos geógrafos considerarem os Estados Unidos uma das nações mais influentes da história recente!',
    points: 1,
    options: [
      { id: 'A', text: 'O isolamento completo da economia americana' },
      { id: 'B', text: 'A combinação de grande desenvolvimento econômico, tecnológico, agrícola e cultural' },
      { id: 'C', text: 'A ausência de qualquer comércio internacional' },
      { id: 'D', text: 'A falta de diversidade cultural' },
    ],
    correctAnswer: 'B',
  },
];
