export const questoesPortugues6AnoB3Av2 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'Qual sinal de pontuação é usado para indicar uma pergunta?',
    tip: 'Pensa numa pergunta que você faz em voz alta — a "curvinha com um pontinho embaixo" é a marca registrada dela!',
    funFact: 'O ponto de interrogação tem esse formato de gancho porque, há muito tempo, representava a curva da voz quando fazemos uma pergunta!',
    points: 1,
    options: [
      { id: 'A', text: 'Ponto final' },
      { id: 'B', text: 'Vírgula' },
      { id: 'C', text: 'Exclamação' },
      { id: 'D', text: 'Ponto de interrogação' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'O ponto final é usado para:',
    tip: 'Pense no sinal mais simples de todos — só uma bolinha. Ele marca que a ideia da frase terminou, sem pergunta e sem susto.',
    funFact: 'O ponto final é o sinal de pontuação mais antigo e mais usado em qualquer texto — sem ele, os textos virariam uma bagunça sem fim!',
    points: 1,
    options: [
      { id: 'A', text: 'Terminar uma frase declarativa' },
      { id: 'B', text: 'Fazer uma pergunta' },
      { id: 'C', text: 'Mostrar surpresa' },
      { id: 'D', text: 'Separar itens de uma lista' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'Qual sinal indica surpresa, alegria ou espanto?',
    tip: 'Imagine alguém gritando "Que incrível!" — qual sinal combina com essa emoção forte?',
    funFact: 'O ponto de exclamação também é usado para dar ordens fortes, como "Pare agora!" — ele mostra intensidade na frase!',
    points: 1,
    options: [
      { id: 'A', text: 'Vírgula' },
      { id: 'B', text: 'Ponto de exclamação' },
      { id: 'C', text: 'Dois-pontos' },
      { id: 'D', text: 'Reticências' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'A vírgula é usada principalmente para:',
    tip: 'Pensa numa lista de compras: "pão, leite, ovos" — o que separa cada item?',
    funFact: 'A vírgula é tão importante que pode até mudar o sentido de uma frase! "Vamos comer, vovó" é bem diferente de "Vamos comer vovó"!',
    points: 1,
    options: [
      { id: 'A', text: 'Terminar uma frase' },
      { id: 'B', text: 'Fazer uma pergunta' },
      { id: 'C', text: 'Separar elementos em uma frase, como itens de uma lista' },
      { id: 'D', text: 'Indicar uma fala' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'Os dois-pontos podem ser usados antes de:',
    tip: 'Pensa em uma frase como "Faltam três coisas: lápis, borracha e caderno" — o que vem logo depois dos dois-pontos?',
    funFact: 'Os dois-pontos também "avisam" que uma fala de personagem vai começar, como em histórias em quadrinhos!',
    points: 1,
    options: [
      { id: 'A', text: 'Uma enumeração ou explicação' },
      { id: 'B', text: 'Uma vírgula' },
      { id: 'C', text: 'Um ponto final' },
      { id: 'D', text: 'Um acento' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'As reticências (...) indicam:',
    tip: 'Repare que as reticências são feitas de três pontinhos seguidos — como se a frase fosse "sumindo" aos poucos, sem terminar de vez.',
    funFact: 'As reticências são ótimas para criar suspense em histórias! "De repente, a porta se abriu..." deixa o leitor querendo saber o que vem depois!',
    points: 1,
    options: [
      { id: 'A', text: 'Uma pergunta' },
      { id: 'B', text: 'Uma exclamação' },
      { id: 'C', text: 'Separação de itens' },
      { id: 'D', text: 'Uma ideia incompleta ou suspensa' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'Em "Maria, venha aqui!", a vírgula é usada para:',
    tip: 'Repare que "Maria" é o nome da pessoa sendo chamada — a vírgula separa esse "chamado" do resto da frase.',
    funFact: 'Esse uso da vírgula se chama "vocativo", que vem da palavra "vocare", que em latim quer dizer "chamar"!',
    points: 1,
    options: [
      { id: 'A', text: 'Separar uma lista' },
      { id: 'B', text: 'Isolar quem está sendo chamado (vocativo)' },
      { id: 'C', text: 'Indicar pergunta' },
      { id: 'D', text: 'Fechar a frase' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'Qual sinal aparece no final de uma frase que expressa uma ordem forte ou emoção?',
    tip: 'Pensa em alguém gritando "Corra!" — esse sinal combina com força e emoção na voz.',
    funFact: 'Em quadrinhos, o ponto de exclamação às vezes aparece repetido "!!!" para mostrar uma emoção ainda mais forte!',
    points: 1,
    options: [
      { id: 'A', text: 'Ponto final' },
      { id: 'B', text: 'Vírgula' },
      { id: 'C', text: 'Ponto de exclamação' },
      { id: 'D', text: 'Dois-pontos' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'As aspas são usadas para:',
    tip: 'Pensa em quando alguém repete exatamente o que outra pessoa disse — que sinal "abraça" essas palavras?',
    funFact: 'As aspas também são usadas para dar um sentido especial ou de brincadeira a uma palavra, como em: ele é um "gênio" da bagunça!',
    points: 1,
    options: [
      { id: 'A', text: 'Separar números' },
      { id: 'B', text: 'Indicar pergunta' },
      { id: 'C', text: 'Terminar frases' },
      { id: 'D', text: 'Marcar a fala de alguém ou uma citação' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'Qual frase termina corretamente com ponto de interrogação?',
    tip: 'Procure a frase que está perguntando algo, esperando uma resposta de sim ou não.',
    funFact: 'Em espanhol, as perguntas têm ponto de interrogação também no começo da frase, ao contrário! Por exemplo: ¿Cómo estás?',
    points: 1,
    options: [
      { id: 'A', text: 'Você já fez a lição de casa?' },
      { id: 'B', text: 'Que dia lindo!' },
      { id: 'C', text: 'Ele foi embora.' },
      { id: 'D', text: 'Compre pão, leite e ovos.' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'Na frase "Comprei maçã, banana e uva", a vírgula separa:',
    tip: 'Repare que "maçã", "banana" e "uva" são frutas diferentes numa mesma lista — o que costuma separar itens de uma lista?',
    funFact: 'Repare que antes da última palavra da lista normalmente usamos "e" no lugar da vírgula — por isso não há vírgula antes de "uva"!',
    points: 1,
    options: [
      { id: 'A', text: 'Itens de uma enumeração' },
      { id: 'B', text: 'Uma pergunta' },
      { id: 'C', text: 'Um vocativo' },
      { id: 'D', text: 'Uma exclamação' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'Complete com o sinal correto: "Que dia maravilhoso___"',
    tip: 'A palavra "maravilhoso" já mostra uma emoção forte de alegria — que sinal combina com isso?',
    funFact: 'Frases que começam com "Que..." quase sempre terminam em exclamação, porque mostram admiração, como "Que dia lindo!" ou "Que susto!"',
    points: 1,
    options: [
      { id: 'A', text: '.' },
      { id: 'B', text: '!' },
      { id: 'C', text: ':' },
      { id: 'D', text: ',' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'Qual frase está pontuada corretamente?',
    tip: 'Repare qual frase usa os dois-pontos antes da fala de alguém e as aspas ao redor do que foi dito — esse é o jeito certo de mostrar uma fala.',
    funFact: 'Em livros e histórias em quadrinhos, também é comum usar o travessão (—) no lugar das aspas para mostrar quem está falando!',
    points: 1,
    options: [
      { id: 'A', text: 'Onde você está.' },
      { id: 'B', text: 'Cuidado?' },
      { id: 'C', text: 'Ele disse, "Vou sair"' },
      { id: 'D', text: 'Ele disse: "Vou sair."' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'A frase "João, traga o livro, por favor" usa a vírgula para:',
    tip: '"João" é o nome de quem está sendo chamado para fazer algo — a vírgula separa esse chamado do pedido.',
    funFact: 'Pedidos educados costumam vir acompanhados de "por favor" — e olha, ele também fica separado por vírgula no final da frase!',
    points: 1,
    options: [
      { id: 'A', text: 'Fazer uma pergunta' },
      { id: 'B', text: 'Terminar a frase' },
      { id: 'C', text: 'Isolar o nome de quem é chamado' },
      { id: 'D', text: 'Indicar surpresa' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'Qual pontuação falta em "Nossa___ que susto"?',
    tip: '"Nossa" é uma interjeição, uma palavrinha que mostra emoção forte, como espanto. Que sinal combina com emoção forte?',
    funFact: '"Nossa", "Uau" e "Eita" são interjeições — palavras curtinhas que expressam sentimentos, e quase sempre pedem ponto de exclamação!',
    points: 1,
    options: [
      { id: 'A', text: '.' },
      { id: 'B', text: '!' },
      { id: 'C', text: '?' },
      { id: 'D', text: ':' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'Escolha a frase corretamente pontuada:',
    tip: 'É uma pergunta com uma lista de itens dentro dela — precisa de vírgulas separando a lista e do sinal certo de pergunta no final.',
    funFact: 'Uma frase pode ter vírgulas E ponto de interrogação ao mesmo tempo — cada sinal cuida de uma parte diferente da frase!',
    points: 1,
    options: [
      { id: 'A', text: 'Você trouxe o material, o lápis e a borracha?' },
      { id: 'B', text: 'Você trouxe o material o lápis e a borracha' },
      { id: 'C', text: 'Você trouxe: o material, o lápis, a borracha!' },
      { id: 'D', text: 'Você trouxe. o material, o lápis, a borracha' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'Os dois-pontos na frase "Faltam três coisas: caderno, lápis e borracha" servem para:',
    tip: 'Repare que logo depois dos dois-pontos vem justamente a lista das três coisas que faltam — eles "anunciam" o que vem a seguir.',
    funFact: 'Os dois-pontos são como um "olha só o que vem agora!" dentro da frase — eles chamam atenção para uma explicação!',
    points: 1,
    options: [
      { id: 'A', text: 'Fazer pergunta' },
      { id: 'B', text: 'Indicar exclamação' },
      { id: 'C', text: 'Anunciar uma explicação/lista' },
      { id: 'D', text: 'Separar sujeito e verbo' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'Em uma história, quando um personagem fala, geralmente usamos:',
    tip: 'Pensa em como os livros de histórias mostram quando alguém está falando — geralmente tem um tracinho ou aspas antes da fala.',
    funFact: 'O travessão (—) é um tracinho maior que o hífen, e serve justamente para separar a fala dos personagens dentro de um texto!',
    points: 1,
    options: [
      { id: 'A', text: 'Ponto de interrogação apenas' },
      { id: 'B', text: 'Vírgula apenas' },
      { id: 'C', text: 'Reticências apenas' },
      { id: 'D', text: 'Dois-pontos e travessão ou aspas' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'Qual das frases pede uma resposta?',
    tip: 'Procure a frase que está perguntando alguma coisa para outra pessoa, esperando que ela responda.',
    funFact: 'Perguntas que esperam "sim" ou "não" como resposta são chamadas de perguntas fechadas — bem diferentes de perguntas abertas, como "O que você fez hoje?"',
    points: 1,
    options: [
      { id: 'A', text: 'Você viu meu lápis?' },
      { id: 'B', text: 'Que legal!' },
      { id: 'C', text: 'Ele chegou.' },
      { id: 'D', text: 'Comprei pão, leite e café.' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: '"Eu não sei... talvez ele volte" — as reticências mostram:',
    tip: 'Repare na palavra "talvez" logo depois das reticências — ela já dá uma pista de que a pessoa não tem certeza de nada.',
    funFact: 'As reticências são ótimas para mostrar quando alguém está pensando ou hesitando antes de continuar a falar!',
    points: 1,
    options: [
      { id: 'A', text: 'Certeza' },
      { id: 'B', text: 'Dúvida ou hesitação' },
      { id: 'C', text: 'Alegria' },
      { id: 'D', text: 'Uma pergunta direta' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Bernardo escreveu no quadro: "Você trouxe caderno, lápis e borracha?" Que sinais de pontuação ele usou corretamente?',
    tip: 'Repare que a frase tem uma lista de materiais E é uma pergunta ao mesmo tempo — quais dois sinais Bernardo precisou usar juntos?',
    funFact: 'Organizar o material escolar com uma lista bem pontuada ajuda a não esquecer nada na mochila — a pontuação também serve pra vida prática!',
    points: 1,
    options: [
      { id: 'A', text: 'Só o ponto final' },
      { id: 'B', text: 'Vírgulas para separar a lista e ponto de interrogação no final' },
      { id: 'C', text: 'Só exclamação' },
      { id: 'D', text: 'Só dois-pontos' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Bernardo ficou muito feliz ao ganhar uma medalha na gincana e gritou: "Eu ganhei___" Que sinal ele deve usar?',
    tip: 'Pensa na emoção de Bernardo nesse momento — ele está gritando de alegria! Que sinal combina com esse sentimento forte?',
    funFact: 'Gincanas escolares são cheias de desafios divertidos, como corridas e jogos em equipe — ótimas para comemorar junto com os amigos!',
    points: 1,
    options: [
      { id: 'A', text: '.' },
      { id: 'B', text: ',' },
      { id: 'C', text: '!' },
      { id: 'D', text: ':' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Bernardo escreveu um bilhete para a mãe: "Mãe, ele disse: \'Vou chegar mais tarde.\'" O uso dos dois-pontos e das aspas serve para:',
    tip: 'Repare que Bernardo está repetindo exatamente o que "ele" disse — os dois-pontos e as aspas mostram que essa é a fala de outra pessoa, não a de Bernardo.',
    funFact: 'Quando repetimos exatamente as palavras de alguém, chamamos isso de "discurso direto" — e ele quase sempre vem com aspas ou travessão!',
    points: 1,
    options: [
      { id: 'A', text: 'Fazer uma pergunta' },
      { id: 'B', text: 'Separar uma lista' },
      { id: 'C', text: 'Mostrar surpresa' },
      { id: 'D', text: 'Indicar a fala de outra pessoa dentro do bilhete' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Bernardo estava fazendo a lista de material escolar: "Preciso de régua, caderno e apontador." As vírgulas nessa frase servem para:',
    tip: 'Repare que "régua", "caderno" e "apontador" são itens diferentes de uma mesma lista de material — o que costuma separar os itens?',
    funFact: 'Fazer listas organizadas com vírgulas ajuda muito na hora de não esquecer nada — os adultos usam esse truque até para fazer compras no mercado!',
    points: 1,
    options: [
      { id: 'A', text: 'Separar os itens da lista' },
      { id: 'B', text: 'Indicar uma pergunta' },
      { id: 'C', text: 'Mostrar espanto' },
      { id: 'D', text: 'Terminar a frase' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'No fim do dia, Bernardo escreveu em seu diário: "Hoje foi um dia incrível___" Qual pontuação combina melhor com o sentimento dele?',
    tip: 'A palavra "incrível" já mostra que Bernardo está empolgado com o dia. Que sinal combina com empolgação?',
    funFact: 'Escrever um diário é uma ótima forma de guardar boas lembranças — e usar a pontuação certa ajuda a mostrar os sentimentos de cada dia!',
    points: 1,
    options: [
      { id: 'A', text: '?' },
      { id: 'B', text: '!' },
      { id: 'C', text: ':' },
      { id: 'D', text: ',' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Bernardo ficou em dúvida sobre ir ou não à festa e escreveu: "Não sei se vou___ talvez sim, talvez não." Qual pontuação mostra essa hesitação?',
    tip: 'Repare que logo depois vem "talvez sim, talvez não" — isso mostra que Bernardo está bem indeciso. Qual sinal combina com essa sensação de "ainda pensando"?',
    funFact: 'As reticências são perfeitas para mostrar personagens pensativos ou indecisos — muito usadas em diários e histórias!',
    points: 1,
    options: [
      { id: 'A', text: '!' },
      { id: 'B', text: '?' },
      { id: 'C', text: ':' },
      { id: 'D', text: '...' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Bernardo perguntou à professora sobre a lista de compras da feira de ciências: "Precisamos de três coisas: cartolina, cola e tesoura." Os dois-pontos aqui indicam:',
    tip: 'Repare que logo depois dos dois-pontos vêm justamente as três coisas citadas — eles "avisam" que a lista vai começar.',
    funFact: 'Feiras de ciências são um jeito divertido de aprender fazendo experimentos — cartolina, cola e tesoura são materiais clássicos para montar cartazes explicativos!',
    points: 1,
    options: [
      { id: 'A', text: 'Uma pergunta' },
      { id: 'B', text: 'Uma exclamação' },
      { id: 'C', text: 'Que uma explicação ou lista vai começar' },
      { id: 'D', text: 'O fim da frase' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Bernardo quis saber se o amigo tinha entendido a tarefa e perguntou: "Você entendeu o exercício___" Que sinal falta?',
    tip: 'Bernardo está fazendo uma pergunta para o amigo, esperando uma resposta. Qual sinal sempre aparece no final de perguntas?',
    funFact: 'Ajudar um colega que ficou com dúvida na tarefa é um gesto bem legal — trabalhar em equipe deixa o aprendizado mais divertido!',
    points: 1,
    options: [
      { id: 'A', text: '?' },
      { id: 'B', text: '!' },
      { id: 'C', text: ':' },
      { id: 'D', text: ',' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Chamando o colega no pátio, Bernardo disse: "Pedro, espera por mim!" A vírgula depois de "Pedro" serve para:',
    tip: '"Pedro" é o nome de quem Bernardo está chamando — assim como em "Maria, venha aqui!", essa vírgula separa o chamado do resto da frase.',
    funFact: 'Esse tipo de vírgula (para separar quem está sendo chamado) aparece em quase todo diálogo de história — fica de olho na próxima leitura!',
    points: 1,
    options: [
      { id: 'A', text: 'Separar uma lista' },
      { id: 'B', text: 'Isolar o nome da pessoa chamada' },
      { id: 'C', text: 'Indicar pergunta' },
      { id: 'D', text: 'Fechar a frase' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'Bernardo terminou de escrever uma cena de sua historinha e um personagem disse: "Corra, o dragão está vindo!" Qual conjunto de sinais aparece nessa fala?',
    tip: 'Repare que tem uma vírgula separando "Corra" do resto da frase, e a frase toda termina com um sinal de emoção forte por causa do perigo do dragão.',
    funFact: 'Parabéns, você terminou o simulado de pontuação! Agora você já sabe usar ponto, vírgula, exclamação, interrogação, dois-pontos, reticências e aspas para deixar seus textos ainda mais claros e cheios de emoção!',
    points: 1,
    options: [
      { id: 'A', text: 'Só ponto final' },
      { id: 'B', text: 'Só interrogação' },
      { id: 'C', text: 'Só reticências' },
      { id: 'D', text: 'Vírgula para separar e exclamação para mostrar urgência' },
    ],
    correctAnswer: 'D',
  },
];
