export const questoesEducacaoFisica7AnoB2Av1 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "A ginástica que reúne diferentes manifestações corporais, sem competição, valorizando a participação e a diversidade de movimentos, é chamada de:",
    tip: "Pense no nome que já sugere 'para todo mundo', sem o foco em competir ou vencer, mas sim em participar.",
    funFact: "\"Você sabia?\" — A Ginástica Geral tem até festivais mundiais, reunindo milhares de participantes de diferentes países, sem nenhuma competição entre eles!",
    points: 1,
    options: [
      { id: "A", text: "Ginástica artística" },
      { id: "B", text: "Ginástica geral" },
      { id: "C", text: "Ginástica rítmica" },
      { id: "D", text: "Ginástica olímpica" },
    ],
    correctAnswer: "B",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "A ginástica que usa exercícios para desenvolver força, resistência e flexibilidade do corpo é chamada de ginástica de:",
    tip: "Pense no objetivo principal dessa prática — preparar e 'condicionar' o corpo física e fisicamente.",
    funFact: "\"Você sabia?\" — Exercícios de condicionamento físico são usados até por atletas de outros esportes, para melhorar o desempenho geral do corpo!",
    points: 1,
    options: [
      { id: "A", text: "Solo apenas" },
      { id: "B", text: "Aparelhos apenas" },
      { id: "C", text: "Competição" },
      { id: "D", text: "Condicionamento físico" },
    ],
    correctAnswer: "D",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "O movimento feito antes da prática de exercícios, para preparar o corpo e evitar lesões, é chamado de:",
    tip: "Pense no momento inicial de uma atividade física, quando o corpo precisa 'esquentar' antes do esforço maior.",
    funFact: "\"Você sabia?\" — Um bom aquecimento aumenta a temperatura dos músculos, tornando-os mais flexíveis e menos propensos a lesões!",
    points: 1,
    options: [
      { id: "A", text: "Aquecimento" },
      { id: "B", text: "Desaquecimento" },
      { id: "C", text: "Repouso" },
      { id: "D", text: "Sedentarismo" },
    ],
    correctAnswer: "A",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "O movimento feito após o exercício físico, estendendo os músculos para relaxá-los, é chamado de:",
    tip: "Pense no movimento de 'esticar' os músculos, geralmente feito no final de uma atividade física.",
    funFact: "\"Você sabia?\" — Alongar depois do exercício ajuda a reduzir dores musculares e melhora a flexibilidade do corpo com o tempo!",
    points: 1,
    options: [
      { id: "A", text: "Aquecimento" },
      { id: "B", text: "Repouso total" },
      { id: "C", text: "Alongamento" },
      { id: "D", text: "Treino de força" },
    ],
    correctAnswer: "C",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "Na ginástica artística, o aparelho em que o ginasta realiza movimentos de equilíbrio sobre uma superfície estreita e elevada é a:",
    tip: "Pense no nome do aparelho que já descreve exatamente sua função: manter o equilíbrio em uma superfície estreita.",
    funFact: "\"Você sabia?\" — A trave de equilíbrio oficial tem apenas 10 centímetros de largura, exigindo muita concentração dos ginastas!",
    points: 1,
    options: [
      { id: "A", text: "Argola" },
      { id: "B", text: "Barra fixa" },
      { id: "C", text: "Cavalo com alças" },
      { id: "D", text: "Trave de equilíbrio" },
    ],
    correctAnswer: "D",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "Na ginástica artística, os movimentos realizados diretamente no colchão, sem nenhum aparelho, formam a modalidade chamada de:",
    tip: "Pense no nome que já indica o 'lugar' onde os movimentos acontecem — diretamente no chão, sobre um colchão.",
    funFact: "\"Você sabia?\" — No solo, os ginastas combinam acrobacias, saltos e até elementos de dança em uma sequência contínua!",
    points: 1,
    options: [
      { id: "A", text: "Trave" },
      { id: "B", text: "Solo" },
      { id: "C", text: "Argolas" },
      { id: "D", text: "Barra fixa" },
    ],
    correctAnswer: "B",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "A capacidade do corpo de alcançar grandes amplitudes de movimento nas articulações é chamada de:",
    tip: "Pense na capacidade de se 'dobrar' e alongar bem o corpo, como fazem os ginastas e bailarinos.",
    funFact: "\"Você sabia?\" — A flexibilidade pode ser treinada e melhorada com alongamentos regulares, mesmo em pessoas que não são naturalmente flexíveis!",
    points: 1,
    options: [
      { id: "A", text: "Força" },
      { id: "B", text: "Resistência" },
      { id: "C", text: "Flexibilidade" },
      { id: "D", text: "Velocidade" },
    ],
    correctAnswer: "C",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "A capacidade física de sustentar um esforço por um longo período de tempo sem se cansar é chamada de:",
    tip: "Pense na capacidade de 'resistir' ao cansaço durante um longo período de atividade física.",
    funFact: "\"Você sabia?\" — Corredores de longa distância, como maratonistas, costumam ter muita resistência física bem desenvolvida!",
    points: 1,
    options: [
      { id: "A", text: "Resistência" },
      { id: "B", text: "Flexibilidade" },
      { id: "C", text: "Agilidade" },
      { id: "D", text: "Equilíbrio" },
    ],
    correctAnswer: "A",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "A capacidade física relacionada à potência dos músculos para empurrar, levantar ou puxar objetos pesados é chamada de:",
    tip: "Pense na capacidade que permite levantar ou empurrar algo pesado, usando a potência dos músculos.",
    funFact: "\"Você sabia?\" — A força muscular pode ser desenvolvida com exercícios de musculação, feitos com o peso do próprio corpo ou com equipamentos!",
    points: 1,
    options: [
      { id: "A", text: "Flexibilidade" },
      { id: "B", text: "Força" },
      { id: "C", text: "Velocidade" },
      { id: "D", text: "Coordenação" },
    ],
    correctAnswer: "B",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "Praticar exercícios físicos regularmente ajuda a prevenir o estilo de vida conhecido como:",
    tip: "Pense no nome que descreve o estilo de vida de quem passa muito tempo sentado, sem se exercitar.",
    funFact: "\"Você sabia?\" — O sedentarismo é considerado um dos principais fatores de risco para diversos problemas de saúde, segundo a Organização Mundial da Saúde!",
    points: 1,
    options: [
      { id: "A", text: "Alongamento excessivo" },
      { id: "B", text: "Treinamento intenso" },
      { id: "C", text: "Aquecimento diário" },
      { id: "D", text: "Sedentarismo" },
    ],
    correctAnswer: "D",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Durante uma aula de educação física, os alunos fazem corridas leves e movimentos de alongamento antes da atividade principal. Esse momento inicial é chamado de:",
    tip: "Pense no momento que prepara o corpo antes do esforço principal da aula.",
    funFact: "\"Você sabia?\" — Pular essa etapa pode aumentar bastante o risco de lesões musculares durante a atividade principal!",
    points: 1,
    options: [
      { id: "A", text: "Aquecimento" },
      { id: "B", text: "Repouso" },
      { id: "C", text: "Sedentarismo" },
      { id: "D", text: "Competição" },
    ],
    correctAnswer: "A",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Um ginasta realiza giros, saltos e acrobacias diretamente sobre o colchão, sem usar nenhum aparelho. Essa modalidade é chamada de:",
    tip: "Pense no nome que descreve exatamente o 'lugar' onde os movimentos acontecem — sobre o colchão, sem aparelhos.",
    funFact: "\"Você sabia?\" — As apresentações de solo na ginástica artística costumam ter acompanhamento musical, principalmente nas competições femininas!",
    points: 1,
    options: [
      { id: "A", text: "Trave" },
      { id: "B", text: "Argolas" },
      { id: "C", text: "Solo" },
      { id: "D", text: "Barra fixa" },
    ],
    correctAnswer: "C",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "Um atleta consegue fazer um espacate completo, alcançando grande amplitude de movimento com as pernas. Essa capacidade física é chamada de:",
    tip: "Pense na capacidade de alcançar grandes amplitudes de movimento nas articulações, como nas pernas.",
    funFact: "\"Você sabia?\" — Bailarinos e ginastas treinam flexibilidade desde muito jovens, pois ela fica mais fácil de desenvolver na infância e adolescência!",
    points: 1,
    options: [
      { id: "A", text: "Força" },
      { id: "B", text: "Flexibilidade" },
      { id: "C", text: "Resistência" },
      { id: "D", text: "Velocidade" },
    ],
    correctAnswer: "B",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "Um atleta consegue correr por 30 minutos seguidos, sem parar, mantendo um ritmo constante. Essa capacidade física é chamada de:",
    tip: "Pense na capacidade de sustentar um esforço por um longo período de tempo, sem se cansar rapidamente.",
    funFact: "\"Você sabia?\" — A resistência cardiovascular pode ser melhorada com treinos regulares, fortalecendo o coração e os pulmões!",
    points: 1,
    options: [
      { id: "A", text: "Flexibilidade" },
      { id: "B", text: "Velocidade" },
      { id: "C", text: "Agilidade" },
      { id: "D", text: "Resistência" },
    ],
    correctAnswer: "D",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Antes de uma atividade intensa, é importante alongar os músculos e fazer movimentos leves, pois isso ajuda a:",
    tip: "Pense no principal objetivo de se preparar bem o corpo antes de um esforço físico maior.",
    funFact: "\"Você sabia?\" — Músculos 'frios' (sem aquecimento) são mais propensos a se machucar durante exercícios intensos!",
    points: 1,
    options: [
      { id: "A", text: "Cansar o corpo mais rápido" },
      { id: "B", text: "Diminuir a flexibilidade" },
      { id: "C", text: "Prevenir lesões musculares" },
      { id: "D", text: "Aumentar o sedentarismo" },
    ],
    correctAnswer: "C",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "Uma ginasta se equilibra sobre uma superfície estreita e elevada, realizando giros e saltos. Qual aparelho da ginástica artística ela está usando?",
    tip: "Pense no aparelho já descrito anteriormente nesta prova, cujo nome indica exatamente sua função.",
    funFact: "\"Você sabia?\" — A trave de equilíbrio é considerada um dos aparelhos mais desafiadores da ginástica artística, por sua largura reduzida!",
    points: 1,
    options: [
      { id: "A", text: "Trave de equilíbrio" },
      { id: "B", text: "Barra fixa" },
      { id: "C", text: "Argolas" },
      { id: "D", text: "Cavalo com alças" },
    ],
    correctAnswer: "A",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "Um grupo de alunos participa de uma apresentação de ginástica geral na escola, com diferentes movimentos corporais em grupo, sem nenhuma competição entre eles. O objetivo principal dessa prática é:",
    tip: "Pense na característica principal dessa modalidade, que já foi explicada no início desta prova — ela não tem competição.",
    funFact: "\"Você sabia?\" — Na Ginástica Geral, pessoas de diferentes idades e habilidades podem participar juntas da mesma apresentação!",
    points: 1,
    options: [
      { id: "A", text: "Vencer uma competição" },
      { id: "B", text: "Bater um recorde mundial" },
      { id: "C", text: "Eliminar os mais fracos" },
      { id: "D", text: "Valorizar a participação e a diversidade de movimentos" },
    ],
    correctAnswer: "D",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "Um atleta realiza exercícios de musculação regularmente para aumentar a capacidade dos músculos de empurrar e levantar pesos. Essa capacidade física é chamada de:",
    tip: "Pense na capacidade relacionada diretamente à potência dos músculos, usada para levantar ou empurrar objetos pesados.",
    funFact: "\"Você sabia?\" — A força muscular também ajuda a proteger as articulações e a melhorar a postura do corpo no dia a dia!",
    points: 1,
    options: [
      { id: "A", text: "Flexibilidade" },
      { id: "B", text: "Força" },
      { id: "C", text: "Resistência" },
      { id: "D", text: "Equilíbrio" },
    ],
    correctAnswer: "B",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "Depois de uma atividade física intensa, os alunos fazem exercícios de alongamento para relaxar os músculos. Esse momento final é chamado de:",
    tip: "Pense no momento que é o 'oposto' do aquecimento, feito no final da atividade, para relaxar o corpo.",
    funFact: "\"Você sabia?\" — O desaquecimento ajuda o corpo a voltar gradualmente ao estado de repouso, evitando desconfortos depois do exercício!",
    points: 1,
    options: [
      { id: "A", text: "Desaquecimento (ou alongamento final)" },
      { id: "B", text: "Aquecimento" },
      { id: "C", text: "Sedentarismo" },
      { id: "D", text: "Treino de força" },
    ],
    correctAnswer: "A",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "Uma pessoa que não pratica nenhuma atividade física regularmente e passa a maior parte do tempo sentada corre maior risco de desenvolver:",
    tip: "Pense no nome do estilo de vida descrito na questão, e nos riscos associados a ele, já mencionados nesta prova.",
    funFact: "\"Você sabia?\" — Pequenas mudanças, como caminhar mais e usar escadas, já ajudam bastante a combater o sedentarismo no dia a dia!",
    points: 1,
    options: [
      { id: "A", text: "Mais flexibilidade" },
      { id: "B", text: "Mais resistência física" },
      { id: "C", text: "Problemas de saúde ligados ao sedentarismo" },
      { id: "D", text: "Mais força muscular" },
    ],
    correctAnswer: "C",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Antes da aula de educação física, Bernardo fez corridas leves e alongamentos para preparar o corpo. Como se chama esse momento inicial?",
    tip: "Pense no momento que prepara o corpo antes do esforço físico principal.",
    funFact: "\"Você sabia?\" — Esse cuidado ajuda bastante a evitar lesões durante as atividades da aula!",
    points: 1,
    options: [
      { id: "A", text: "Sedentarismo" },
      { id: "B", text: "Aquecimento" },
      { id: "C", text: "Desaquecimento" },
      { id: "D", text: "Competição" },
    ],
    correctAnswer: "B",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Bernardo participou de uma apresentação de ginástica geral na escola, com vários colegas fazendo diferentes movimentos corporais juntos, sem competição entre eles. Qual é o objetivo principal dessa prática?",
    tip: "Pense na característica principal dessa modalidade, sem foco em vencer ou competir.",
    funFact: "\"Você sabia?\" — Essas apresentações costumam reunir alunos de diferentes idades e habilidades, todos participando juntos!",
    points: 1,
    options: [
      { id: "A", text: "Vencer uma competição" },
      { id: "B", text: "Eliminar os mais fracos" },
      { id: "C", text: "Bater recordes mundiais" },
      { id: "D", text: "Valorizar a participação e a diversidade de movimentos" },
    ],
    correctAnswer: "D",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Bernardo tentou fazer um espacate na aula de educação física, alcançando uma grande amplitude de movimento com as pernas. Qual capacidade física ele estava trabalhando?",
    tip: "Pense na capacidade de alcançar grandes amplitudes de movimento nas articulações.",
    funFact: "\"Você sabia?\" — A flexibilidade costuma ser mais fácil de desenvolver quando se começa a treinar desde a infância!",
    points: 1,
    options: [
      { id: "A", text: "Flexibilidade" },
      { id: "B", text: "Força" },
      { id: "C", text: "Resistência" },
      { id: "D", text: "Velocidade" },
    ],
    correctAnswer: "A",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Bernardo correu por 20 minutos seguidos sem parar, mantendo um ritmo constante durante a aula. Qual capacidade física ele estava desenvolvendo?",
    tip: "Pense na capacidade de sustentar um esforço por um longo período de tempo, sem se cansar rapidamente.",
    funFact: "\"Você sabia?\" — Correr regularmente ajuda a fortalecer o coração e a melhorar a capacidade pulmonar!",
    points: 1,
    options: [
      { id: "A", text: "Flexibilidade" },
      { id: "B", text: "Velocidade" },
      { id: "C", text: "Resistência" },
      { id: "D", text: "Equilíbrio" },
    ],
    correctAnswer: "C",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Bernardo tentou se equilibrar em uma superfície estreita e elevada durante uma atividade de ginástica artística na escola. Qual aparelho ele estava usando?",
    tip: "Pense no aparelho cujo nome já descreve sua função principal: manter o equilíbrio em uma superfície estreita.",
    funFact: "\"Você sabia?\" — Esse aparelho é considerado um dos mais desafiadores da ginástica artística, exigindo muita concentração!",
    points: 1,
    options: [
      { id: "A", text: "Barra fixa" },
      { id: "B", text: "Argolas" },
      { id: "C", text: "Cavalo com alças" },
      { id: "D", text: "Trave de equilíbrio" },
    ],
    correctAnswer: "D",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Bernardo fez exercícios de musculação leve, com a orientação do professor, para fortalecer os músculos dos braços. Qual capacidade física ele estava trabalhando?",
    tip: "Pense na capacidade relacionada à potência dos músculos, treinada com exercícios de musculação.",
    funFact: "\"Você sabia?\" — Fortalecer os músculos desde jovem, com orientação adequada, ajuda a melhorar a postura e prevenir lesões no futuro!",
    points: 1,
    options: [
      { id: "A", text: "Flexibilidade" },
      { id: "B", text: "Força" },
      { id: "C", text: "Resistência" },
      { id: "D", text: "Equilíbrio" },
    ],
    correctAnswer: "B",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Depois de uma atividade física intensa, Bernardo fez alongamentos para relaxar os músculos antes de ir para casa. Como se chama esse momento final?",
    tip: "Pense no momento que é o 'oposto' do aquecimento, feito no final da atividade física.",
    funFact: "\"Você sabia?\" — Esse cuidado ajuda o corpo a relaxar gradualmente, evitando desconfortos musculares depois do exercício!",
    points: 1,
    options: [
      { id: "A", text: "Aquecimento" },
      { id: "B", text: "Sedentarismo" },
      { id: "C", text: "Desaquecimento (ou alongamento final)" },
      { id: "D", text: "Treino de força" },
    ],
    correctAnswer: "C",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Bernardo fez giros e acrobacias diretamente sobre o colchão durante a aula de ginástica artística, sem usar nenhum aparelho. Qual modalidade ele praticou?",
    tip: "Pense no nome que descreve exatamente o 'lugar' onde os movimentos aconteceram — sobre o colchão, sem aparelhos.",
    funFact: "\"Você sabia?\" — Essa modalidade combina acrobacias, saltos e até elementos de dança em uma sequência contínua!",
    points: 1,
    options: [
      { id: "A", text: "Solo" },
      { id: "B", text: "Trave" },
      { id: "C", text: "Argolas" },
      { id: "D", text: "Barra fixa" },
    ],
    correctAnswer: "A",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "O professor explicou que praticar exercícios físicos regularmente ajuda Bernardo a prevenir problemas de saúde relacionados a ficar muito tempo sentado, sem se mexer. Como se chama esse estilo de vida pouco ativo?",
    tip: "Pense no nome do estilo de vida de quem passa muito tempo parado, sem se exercitar.",
    funFact: "\"Você sabia?\" — Pequenas mudanças no dia a dia, como caminhar mais, já ajudam bastante a combater esse estilo de vida!",
    points: 1,
    options: [
      { id: "A", text: "Flexibilidade excessiva" },
      { id: "B", text: "Sedentarismo" },
      { id: "C", text: "Treinamento intenso" },
      { id: "D", text: "Resistência alta" },
    ],
    correctAnswer: "B",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Bernardo aprendeu que alongar os músculos antes de uma atividade intensa ajuda a prevenir lesões. Esse cuidado faz parte de qual momento da aula de educação física?",
    tip: "Pense no momento inicial da aula, que prepara o corpo antes do esforço físico principal.",
    funFact: "\"Você sabia?\" — Um bom aquecimento torna os músculos mais flexíveis, reduzindo bastante o risco de lesões durante a atividade!",
    points: 1,
    options: [
      { id: "A", text: "Desaquecimento apenas" },
      { id: "B", text: "Sedentarismo" },
      { id: "C", text: "Competição" },
      { id: "D", text: "Aquecimento" },
    ],
    correctAnswer: "D",
  },
];
