export const questoesHistoria6AnoB4Av1 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'Segundo a lenda, Roma foi fundada por:',
    tip: 'São dois irmãos, criados por uma loba, segundo a lenda romana.',
    funFact: 'A cidade de Roma recebeu esse nome em homenagem a um dos dois irmãos: Rômulo!',
    points: 1,
    options: [
      { id: 'A', text: 'Zeus e Hera' },
      { id: 'B', text: 'Cleópatra' },
      { id: 'C', text: 'Hamurábi' },
      { id: 'D', text: 'Rômulo e Remo' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'Roma Antiga ficava localizada em qual território, hoje?',
    tip: 'É o país em formato de "bota", na Europa, famoso pela pizza e pela massa.',
    funFact: 'A cidade de Roma ainda existe hoje e é a capital da Itália!',
    points: 1,
    options: [
      { id: 'A', text: 'Itália' },
      { id: 'B', text: 'Grécia' },
      { id: 'C', text: 'Egito' },
      { id: 'D', text: 'Espanha' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'A lenda conta que Rômulo e Remo foram criados, quando bebês, por:',
    tip: 'É um animal selvagem, parecido com um cachorro grande, que amamentou os dois irmãos, segundo a lenda.',
    funFact: 'Até hoje existem estátuas famosas mostrando essa loba amamentando os dois bebês!',
    points: 1,
    options: [
      { id: 'A', text: 'Um faraó' },
      { id: 'B', text: 'Um pastor de ovelhas apenas' },
      { id: 'C', text: 'Uma loba' },
      { id: 'D', text: 'Um rei grego' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'O sistema de governo em que várias pessoas (e não um só rei) participavam das decisões, adotado por Roma depois da monarquia, era chamado de:',
    tip: 'É uma palavra parecida com o sistema de governo do Brasil hoje!',
    funFact: 'A palavra "república" significa "coisa pública", ou seja, algo que pertence a todos!',
    points: 1,
    options: [
      { id: 'A', text: 'Império' },
      { id: 'B', text: 'República' },
      { id: 'C', text: 'Ditadura' },
      { id: 'D', text: 'Teocracia' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'Na sociedade romana, os patrícios eram:',
    tip: 'Pensa em quem tinha mais poder e riqueza dentro da sociedade romana.',
    funFact: 'Só os patrícios podiam, no início, ocupar os cargos políticos mais importantes de Roma!',
    points: 1,
    options: [
      { id: 'A', text: 'Escravizados' },
      { id: 'B', text: 'Estrangeiros' },
      { id: 'C', text: 'Comerciantes pobres' },
      { id: 'D', text: 'Membros das famílias mais ricas e nobres' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'Já os plebeus eram:',
    tip: 'Pensa no "resto" da população romana, que não fazia parte das famílias mais ricas.',
    funFact: 'Com o tempo, os plebeus lutaram e conquistaram mais direitos políticos em Roma!',
    points: 1,
    options: [
      { id: 'A', text: 'Somente os governantes' },
      { id: 'B', text: 'A maior parte da população, formada por camponeses, artesãos e comerciantes' },
      { id: 'C', text: 'Apenas soldados estrangeiros' },
      { id: 'D', text: 'Apenas escravizados' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'Um grupo de pessoas escolhidas para governar Roma durante a República era chamado de:',
    tip: 'É uma palavra que ainda é usada hoje em muitos países para nomear um grupo de políticos.',
    funFact: 'A palavra "Senado" é usada até hoje no Congresso Nacional do Brasil!',
    points: 1,
    options: [
      { id: 'A', text: 'Senado' },
      { id: 'B', text: 'Faraós' },
      { id: 'C', text: 'Zigurates' },
      { id: 'D', text: 'Olimpo' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'Os romanos construíram estradas, pontes e aquedutos, mostrando grande habilidade em:',
    tip: 'Pensa em quem projeta e constrói estradas e pontes — que tipo de profissional faz isso hoje?',
    funFact: 'Algumas estradas romanas eram tão bem construídas que partes delas existem até hoje, com mais de 2 mil anos!',
    points: 1,
    options: [
      { id: 'A', text: 'Culinária' },
      { id: 'B', text: 'Pintura' },
      { id: 'C', text: 'Engenharia' },
      { id: 'D', text: 'Costura' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'Como eram chamados os grandes combates entre gladiadores, muito populares em Roma Antiga?',
    tip: 'Pensa no imenso anfiteatro romano onde esses combates aconteciam.',
    funFact: 'O Coliseu de Roma podia reunir dezenas de milhares de espectadores para assistir às lutas!',
    points: 1,
    options: [
      { id: 'A', text: 'Jogos Olímpicos' },
      { id: 'B', text: 'Democracia' },
      { id: 'C', text: 'Assembleias' },
      { id: 'D', text: 'Lutas de gladiadores no Coliseu' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'O idioma falado pelos romanos, que deu origem ao português, ao espanhol e a outras línguas, era o:',
    tip: 'Muitas palavras do português têm origem direta nessa língua antiga dos romanos.',
    funFact: 'Línguas como português, espanhol, italiano e francês são chamadas de "línguas latinas" justamente por causa dessa origem!',
    points: 1,
    options: [
      { id: 'A', text: 'Latim' },
      { id: 'B', text: 'Grego' },
      { id: 'C', text: 'Egípcio' },
      { id: 'D', text: 'Sumério' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'Se um romano quisesse participar das decisões políticas durante a República, ele poderia, dependendo de sua posição, votar ou até:',
    tip: 'Lembra do grupo de governantes estudado na questão 7 — quem podia participar dele?',
    funFact: 'Assim como em Atenas, a participação política em Roma também tinha suas próprias regras e limitações!',
    points: 1,
    options: [
      { id: 'A', text: 'Ser proibido de opinar sobre qualquer assunto' },
      { id: 'B', text: 'Fazer parte do Senado ou de assembleias, dependendo de seu status social' },
      { id: 'C', text: 'Ser expulso de Roma automaticamente' },
      { id: 'D', text: 'Nada, pois Roma nunca teve participação política' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'Por que os patrícios tinham mais poder do que os plebeus na sociedade romana?',
    tip: 'Volta na questão 5 sobre quem eram os patrícios.',
    funFact: 'Essa diferença de poder gerou muitos conflitos entre patrícios e plebeus ao longo da história romana!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque eram mais altos' },
      { id: 'B', text: 'Porque moravam mais longe' },
      { id: 'C', text: 'Porque pertenciam às famílias ricas e tradicionais, com mais influência política' },
      { id: 'D', text: 'Porque corriam mais rápido' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'Imagine um romano usando uma estrada construída pelo Império para viajar rapidamente entre cidades. Isso mostra a importância de que área do conhecimento romano?',
    tip: 'Volta na questão 8 sobre as grandes obras que os romanos construíam.',
    funFact: 'Existia até um ditado que dizia "todos os caminhos levam a Roma", por causa da imensa rede de estradas do Império!',
    points: 1,
    options: [
      { id: 'A', text: 'Pintura' },
      { id: 'B', text: 'Culinária' },
      { id: 'C', text: 'Poesia' },
      { id: 'D', text: 'Engenharia e construção' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'Por que a língua latina é tão importante para entendermos o português de hoje?',
    tip: 'Volta na questão 10 sobre a origem do português.',
    funFact: 'Muitas palavras que você usa todo dia, como "água" (de "aqua") e "escola" (de "schola"), vêm direto do latim!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque o português e outras línguas (como espanhol e italiano) vieram do latim' },
      { id: 'B', text: 'Porque o latim é uma língua inventada recentemente' },
      { id: 'C', text: 'Porque o latim não tem nenhuma relação com o português' },
      { id: 'D', text: 'Porque o latim era falado apenas no Egito' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'Se os plebeus quisessem ter mais participação política em Roma, o que a história mostra que eles fizeram ao longo do tempo?',
    tip: 'Pensa em como grupos com menos poder, ao longo da história, costumam agir para conquistar mais direitos.',
    funFact: 'Esse processo de luta dos plebeus por direitos é estudado até hoje como um exemplo importante de conquista política!',
    points: 1,
    options: [
      { id: 'A', text: 'Desistiram completamente de ter qualquer direito' },
      { id: 'B', text: 'Lutaram e conquistaram, aos poucos, mais direitos e representação política' },
      { id: 'C', text: 'Foram todos expulsos de Roma' },
      { id: 'D', text: 'Nunca houve nenhum conflito entre patrícios e plebeus' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'Por que o Coliseu é considerado uma grande obra da engenharia romana?',
    tip: 'Volta na questão 9 sobre o que acontecia dentro do Coliseu.',
    funFact: 'O Coliseu ainda existe em Roma até hoje e é visitado por milhões de turistas todos os anos!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque era pequeno e simples' },
      { id: 'B', text: 'Porque era feito só de madeira fraca' },
      { id: 'C', text: 'Porque não tinha nenhuma função' },
      { id: 'D', text: 'Porque era um imenso anfiteatro, capaz de reunir milhares de pessoas para assistir aos espetáculos' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'O que a construção de aquedutos, estradas e pontes revela sobre a organização do governo romano?',
    tip: 'Pensa em quanto planejamento é preciso para construir uma estrada ou um aqueduto enorme, sem máquinas modernas.',
    funFact: 'Os aquedutos romanos levavam água limpa de longe até as cidades, usando apenas a força da gravidade!',
    points: 1,
    options: [
      { id: 'A', text: 'Que os romanos não se importavam com infraestrutura' },
      { id: 'B', text: 'Que essas construções eram feitas por acaso, sem planejamento' },
      { id: 'C', text: 'Que havia um governo organizado, capaz de planejar grandes obras públicas' },
      { id: 'D', text: 'Que Roma nunca teve governo nenhum' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'Comparando a República romana com a democracia ateniense, é correto dizer que:',
    tip: 'Pensa no que você já sabe sobre a democracia de Atenas e agora sobre a República romana — as duas tinham alguma participação do povo, mesmo que diferente.',
    funFact: 'Essas duas formas antigas de governo influenciaram muito as democracias modernas, incluindo a do Brasil!',
    points: 1,
    options: [
      { id: 'A', text: 'As duas envolviam alguma forma de participação política, mas com regras e grupos diferentes' },
      { id: 'B', text: 'As duas eram exatamente iguais em tudo' },
      { id: 'C', text: 'Só a democracia grega existiu de verdade' },
      { id: 'D', text: 'Nenhuma das duas teve qualquer forma de governo' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'Por que a sociedade romana era dividida entre patrícios e plebeus?',
    tip: 'Volta nas questões 5 e 6 sobre as diferenças entre esses dois grupos.',
    funFact: 'Essa divisão em grupos sociais com direitos diferentes existiu em várias civilizações antigas, não só em Roma!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque não existia nenhum tipo de organização social' },
      { id: 'B', text: 'Porque havia uma hierarquia social baseada em riqueza e tradição familiar' },
      { id: 'C', text: 'Porque todos nasciam exatamente com os mesmos direitos' },
      { id: 'D', text: 'Porque isso era sorteado todo ano' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'Se um historiador encontrasse hoje os restos de uma antiga estrada romana, o que isso ajudaria a entender sobre o Império?',
    tip: 'Volta na questão 13 sobre a importância das estradas para o Império Romano.',
    funFact: 'Graças a essas estradas, arqueólogos ainda hoje encontram vestígios do antigo Império Romano em vários países da Europa!',
    points: 1,
    options: [
      { id: 'A', text: 'Que os romanos nunca viajavam' },
      { id: 'B', text: 'Que Roma não tinha nenhuma tecnologia' },
      { id: 'C', text: 'Que os romanos tinham grande capacidade de conectar regiões distantes através de obras de engenharia' },
      { id: 'D', text: 'Que as estradas eram feitas de areia' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Bernardo está contando para a turma a lenda da fundação de Roma. Quem são os personagens principais dessa lenda?',
    tip: 'É a mesma dupla de irmãos da questão 1.',
    funFact: 'Bernardo pode até desenhar a famosa loba amamentando os dois irmãos para deixar a apresentação mais divertida!',
    points: 1,
    options: [
      { id: 'A', text: 'Rômulo e Remo' },
      { id: 'B', text: 'Zeus e Hera' },
      { id: 'C', text: 'Sócrates e Platão' },
      { id: 'D', text: 'Hamurábi e seu filho' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Na maquete de Bernardo, ele representa um animal que, segundo a lenda, cuidou dos bebês fundadores de Roma. Que animal é esse?',
    tip: 'É o mesmo animal da questão 3.',
    funFact: 'Essa imagem da loba com os dois bebês é um dos símbolos mais famosos de Roma até hoje!',
    points: 1,
    options: [
      { id: 'A', text: 'Um cavalo' },
      { id: 'B', text: 'Uma águia' },
      { id: 'C', text: 'Um leão' },
      { id: 'D', text: 'Uma loba' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'A professora pergunta a Bernardo o nome do sistema de governo romano em que várias pessoas participavam das decisões, sem ter um rei. Qual é a resposta?',
    tip: 'É o mesmo sistema de governo da questão 4.',
    funFact: 'A palavra "república" é usada até hoje para descrever o sistema de governo do Brasil!',
    points: 1,
    options: [
      { id: 'A', text: 'Monarquia' },
      { id: 'B', text: 'República' },
      { id: 'C', text: 'Teocracia' },
      { id: 'D', text: 'Anarquia' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Bernardo explica ao colega que, em Roma, as famílias mais ricas e tradicionais eram chamadas de:',
    tip: 'É o mesmo grupo social da questão 5.',
    funFact: 'A palavra "patrício" vem de "pater", que em latim significa "pai" — remetendo às famílias tradicionais!',
    points: 1,
    options: [
      { id: 'A', text: 'Plebeus' },
      { id: 'B', text: 'Escravizados' },
      { id: 'C', text: 'Patrícios' },
      { id: 'D', text: 'Gladiadores' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'No quiz de Bernardo, a pista é: "Sou um imenso anfiteatro romano, onde aconteciam lutas de gladiadores." Qual é a resposta?',
    tip: 'É a mesma construção das questões 9 e 16.',
    funFact: 'O Coliseu conseguia até ser inundado com água para simular batalhas navais como espetáculo!',
    points: 1,
    options: [
      { id: 'A', text: 'Coliseu' },
      { id: 'B', text: 'Zigurate' },
      { id: 'C', text: 'Pirâmide' },
      { id: 'D', text: 'Partenon' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Bernardo pergunta ao pai por que os romanos construíram tantas estradas por todo o império. O pai explica que:',
    tip: 'Volta nas questões 8, 13 e 20 sobre a importância das estradas romanas.',
    funFact: 'Algumas estradas romanas seguiam praticamente em linha reta por centenas de quilômetros!',
    points: 1,
    options: [
      { id: 'A', text: 'Era só para decoração' },
      { id: 'B', text: 'Para que os animais tivessem onde caminhar' },
      { id: 'C', text: 'Para facilitar o transporte de pessoas, exércitos e mercadorias entre as regiões' },
      { id: 'D', text: 'Porque não tinham mais nada para fazer' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Bernardo aprende que o português tem muitas palavras parecidas com outra língua antiga. Qual é essa língua, falada pelos romanos?',
    tip: 'É a mesma língua das questões 10 e 14.',
    funFact: 'Até hoje, médicos e cientistas usam palavras em latim para nomear espécies de animais e plantas!',
    points: 1,
    options: [
      { id: 'A', text: 'Grego' },
      { id: 'B', text: 'Egípcio' },
      { id: 'C', text: 'Sumério' },
      { id: 'D', text: 'Latim' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Ao montar a linha do tempo, Bernardo posiciona Roma Antiga depois da Grécia Antiga. Isso mostra que Roma:',
    tip: 'Pensa em tudo que você já estudou este ano: Pré-História, Mesopotâmia, Egito, Grécia e agora Roma.',
    funFact: 'Os romanos, inclusive, foram muito influenciados pela cultura e pela mitologia dos gregos!',
    points: 1,
    options: [
      { id: 'A', text: 'Existiu antes de todas as outras civilizações' },
      { id: 'B', text: 'Faz parte de uma sequência de grandes civilizações da Antiguidade' },
      { id: 'C', text: 'Não teve nenhuma relação com a Grécia' },
      { id: 'D', text: 'Só existiu no século 21' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Bernardo pergunta à professora qual era a diferença entre patrícios e plebeus em Roma. Ela explica que:',
    tip: 'É a mesma explicação das questões 5, 6, 12 e 19.',
    funFact: 'Com o tempo, alguns plebeus ricos conseguiram conquistar mais poder e até ocupar cargos políticos importantes!',
    points: 1,
    options: [
      { id: 'A', text: 'Os patrícios eram famílias ricas e tradicionais, e os plebeus formavam a maior parte da população, com menos privilégios' },
      { id: 'B', text: 'Os plebeus eram mais ricos que os patrícios' },
      { id: 'C', text: 'Não existia nenhuma diferença entre eles' },
      { id: 'D', text: 'Só os patrícios podiam morar em Roma' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'Para fechar sua apresentação, Bernardo resume: "Roma Antiga é importante porque..." Como ele pode completar a frase?',
    tip: 'Pensa em tudo que você aprendeu neste simulado sobre estradas, Senado, República e latim.',
    funFact: 'No próximo simulado, Bernardo vai revisar tudo que aprendeu sobre as civilizações antigas deste ano inteiro!',
    points: 1,
    options: [
      { id: 'A', text: '"...não deixou nenhuma herança para o mundo atual."' },
      { id: 'B', text: '"...foi construída em um único dia."' },
      { id: 'C', text: '"...ficava embaixo do oceano."' },
      { id: 'D', text: '"...criou grandes obras de engenharia, um sistema de governo (a República) e uma língua (o latim) que influenciam o mundo até hoje."' },
    ],
    correctAnswer: 'D',
  },
];
