export const questoesIngles9AnoB2Av1 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "Fill in the blank with the correct comparative form: 'John is _____ than his brother.'",
    tip: "Adjetivos curtos (uma sílaba) formam o comparativo de superioridade de maneira diferente dos longos.",
    funFact: "Short adjectives (1 syllable) add '-er': tall → taller. Long adjectives (3+ syllables) use 'more': beautiful → more beautiful. Two-syllable adjectives can go either way!",
    points: 1,
    options: [
      { id: "A", text: "more tall" },
      { id: "B", text: "tallest" },
      { id: "C", text: "the tallest" },
      { id: "D", text: "taller" },
    ],
    correctAnswer: "D",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "Choose the correct superlative form: 'She is _____ student in the class.'",
    tip: "Adjetivos longos (mais de duas sílabas) como 'intelligent' formam o superlativo de qual forma?",
    funFact: "Superlatives use 'the most' with long adjectives: the most intelligent, the most beautiful, the most expensive. Short adjectives use 'the + adjective + -est': the tallest, the smallest!",
    points: 1,
    options: [
      { id: "A", text: "the most intelligent" },
      { id: "B", text: "more intelligent" },
      { id: "C", text: "most intelligent" },
      { id: "D", text: "the more intelligent" },
    ],
    correctAnswer: "A",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "Choose the correct quantifier: 'There are _____ students in the classroom — it's almost empty.'",
    tip: "'Students' é contável (countable). Qual quantificador expressa 'poucos' com substantivos contáveis?",
    funFact: "'Few' (countable) and 'little' (uncountable) both mean 'not much/many'. But 'a few' and 'a little' are positive — they mean 'some, which is good'! The 'a' makes a big difference!",
    points: 1,
    options: [
      { id: "A", text: "much" },
      { id: "B", text: "a lot of" },
      { id: "C", text: "few" },
      { id: "D", text: "little" },
    ],
    correctAnswer: "C",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "Choose the correct preposition: 'The library is _____ the post office and the bank.'",
    tip: "Quando algo está no meio de dois outros lugares ou objetos, qual preposição usamos?",
    funFact: "'Between' is used for two items; 'among' is used for three or more. 'The library is between the post office and the bank' — there are exactly two reference points!",
    points: 1,
    options: [
      { id: "A", text: "in front of" },
      { id: "B", text: "between" },
      { id: "C", text: "behind" },
      { id: "D", text: "next to" },
    ],
    correctAnswer: "B",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "Choose the correct relative pronoun: 'The book _____ I borrowed from the library was very interesting.'",
    tip: "O pronome relativo substitui 'the book' — uma coisa, não uma pessoa. Qual pronome é usado para coisas?",
    funFact: "Use 'who' for people, 'which' for things, and 'that' for both (in defining clauses). 'Whose' shows possession. 'Whom' is the formal/objective form of 'who'!",
    points: 1,
    options: [
      { id: "A", text: "who" },
      { id: "B", text: "whose" },
      { id: "C", text: "whom" },
      { id: "D", text: "which" },
    ],
    correctAnswer: "D",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "What does the idiom 'Break a leg!' mean?",
    tip: "Essa expressão é frequentemente usada antes de apresentações teatrais, provas ou shows. Não é literal!",
    funFact: "The origin of 'break a leg' is unclear, but one theory links it to theatre: in a successful show, actors had to 'break' (cross) the leg-line — the side curtain — to take a bow. So it wishes success!",
    points: 1,
    options: [
      { id: "A", text: "Good luck!" },
      { id: "B", text: "Be careful!" },
      { id: "C", text: "Try your best!" },
      { id: "D", text: "Hurry up!" },
    ],
    correctAnswer: "A",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "Fill in the blank with the correct passive form: 'The cake _____ by my mother yesterday.'",
    tip: "A ação está no passado e o sujeito recebe a ação (passiva). Qual é a forma da voz passiva no passado simples?",
    funFact: "The passive voice is formed with 'to be' + past participle. Simple past passive: was/were + past participle. 'My mother made the cake' → 'The cake was made by my mother'!",
    points: 1,
    options: [
      { id: "A", text: "made" },
      { id: "B", text: "is made" },
      { id: "C", text: "was made" },
      { id: "D", text: "has made" },
    ],
    correctAnswer: "C",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "Choose the correct preposition: 'The cat jumped _____ the fence.'",
    tip: "O gato está se movendo de um lado para outro, passando por cima de um obstáculo. Qual preposição indica movimento acima de algo?",
    funFact: "'Over' indicates movement above and across something. Compare: the bird flew over the mountain (above), the cat jumped over the fence (above and across), the bridge over the river!",
    points: 1,
    options: [
      { id: "A", text: "between" },
      { id: "B", text: "over" },
      { id: "C", text: "behind" },
      { id: "D", text: "beside" },
    ],
    correctAnswer: "B",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "What does the idiom 'a piece of cake' mean?",
    tip: "Essa expressão é usada para descrever algo que parece muito fácil ou simples de fazer.",
    funFact: "English has many food idioms! 'A piece of cake' (very easy), 'spill the beans' (reveal a secret), 'bite the bullet' (endure pain bravely). Language is deliciously creative!",
    points: 1,
    options: [
      { id: "A", text: "The exam had food as a reward" },
      { id: "B", text: "The exam was sweet and pleasant" },
      { id: "C", text: "The exam was very important" },
      { id: "D", text: "The exam was very easy" },
    ],
    correctAnswer: "D",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "Choose the correct comparative form for the irregular adjective 'bad': 'This road is _____ than the one we took yesterday.'",
    tip: "O adjetivo 'bad' é irregular. Ele não segue a regra normal de comparativo. Qual é sua forma comparativa?",
    funFact: "English has irregular comparatives: good → better → best, bad → worse → worst, far → farther/further → farthest/furthest. These must be memorized — there's no shortcut!",
    points: 1,
    options: [
      { id: "A", text: "worse" },
      { id: "B", text: "more bad" },
      { id: "C", text: "baddest" },
      { id: "D", text: "worst" },
    ],
    correctAnswer: "A",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Choose the correct passive form: 'English _____ all over the world.'",
    tip: "A frase expressa um fato geral no presente. O sujeito ('English') recebe a ação de ser falado. Qual é a forma passiva do presente simples?",
    funFact: "The passive voice is especially common in English when describing processes, scientific facts, and news: 'English is spoken by over 1.5 billion people worldwide' — that's a lot of speakers!",
    points: 1,
    options: [
      { id: "A", text: "speak" },
      { id: "B", text: "speaks" },
      { id: "C", text: "is spoken" },
      { id: "D", text: "speaking" },
    ],
    correctAnswer: "C",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Choose the correct quantifier: 'How _____ time do we have left?'",
    tip: "'Time' neste contexto é um substantivo incontável (uncountable). Qual quantificador é usado com incontáveis em perguntas?",
    funFact: "'Much' is used with uncountable nouns (time, money, water, information). 'Many' is used with countable nouns (students, books, ideas). This is a key grammar rule!",
    points: 1,
    options: [
      { id: "A", text: "many" },
      { id: "B", text: "much" },
      { id: "C", text: "few" },
      { id: "D", text: "little" },
    ],
    correctAnswer: "B",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "Choose the correct preposition: 'Please put the books _____ the shelf.'",
    tip: "Livros são colocados em uma superfície horizontal de uma prateleira. Qual preposição usamos para posição sobre superfícies?",
    funFact: "Preposition choice can be tricky: 'on' (surface contact), 'in' (inside a container), 'at' (a point/location). Books go 'on' the shelf because they rest on its surface!",
    points: 1,
    options: [
      { id: "A", text: "in" },
      { id: "B", text: "at" },
      { id: "C", text: "between" },
      { id: "D", text: "on" },
    ],
    correctAnswer: "D",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "Choose the correct relative pronoun: 'The girl _____ bag was stolen reported it to the police.'",
    tip: "O pronome relativo se refere a uma relação de posse: a bolsa pertence à garota. Qual pronome relativo indica posse?",
    funFact: "'Whose' is the possessive relative pronoun. It works for both people and things: 'the girl whose bag was stolen' / 'the car whose door is broken'. It replaces 'her/his/its'!",
    points: 1,
    options: [
      { id: "A", text: "whose" },
      { id: "B", text: "which" },
      { id: "C", text: "that" },
      { id: "D", text: "who" },
    ],
    correctAnswer: "A",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Choose the correct passive form: 'The results _____ announced tomorrow.'",
    tip: "A ação vai acontecer no futuro e o sujeito 'the results' recebe a ação. Qual é a forma passiva do futuro?",
    funFact: "Future passive = will be + past participle. Examples: 'The winner will be announced', 'The building will be demolished', 'New laws will be introduced'. Very common in formal announcements!",
    points: 1,
    options: [
      { id: "A", text: "announce" },
      { id: "B", text: "are announced" },
      { id: "C", text: "will be announced" },
      { id: "D", text: "will announce" },
    ],
    correctAnswer: "C",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "Choose the correct superlative: 'What is _____ mountain in the world?'",
    tip: "A pergunta é sobre o extremo absoluto entre todas as montanhas. Qual é a forma superlativa de 'tall'?",
    funFact: "Mount Everest is the world's tallest mountain at 8,849 metres! The superlative '-est' is used when comparing one thing to all others in its group. Don't forget 'the' before superlatives!",
    points: 1,
    options: [
      { id: "A", text: "the more tall" },
      { id: "B", text: "the tallest" },
      { id: "C", text: "the most tall" },
      { id: "D", text: "taller" },
    ],
    correctAnswer: "B",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "What does the idiom 'cost an arm and a leg' mean?",
    tip: "Essa expressão descreve o preço de algo. Pense no exagero humorístico: perder um braço e uma perna seria um custo enorme!",
    funFact: "The origin is uncertain, but this idiom likely dates from the 19th century. Similar expressions exist in other languages too! In Portuguese, we might say 'custar os olhos da cara' (cost the eyes from your face)!",
    points: 1,
    options: [
      { id: "A", text: "To be very light and portable" },
      { id: "B", text: "To be very old and worn out" },
      { id: "C", text: "To be very popular" },
      { id: "D", text: "To be very expensive" },
    ],
    correctAnswer: "D",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "Choose the correct preposition: 'She walked _____ the building and sat down.'",
    tip: "Ela está se movendo de fora para dentro do edifício. Qual preposição indica movimento para o interior de um espaço fechado?",
    funFact: "'Into' shows movement toward the inside: walk into, run into, jump into. 'In' shows location (she is in the building). The difference between location and movement is key!",
    points: 1,
    options: [
      { id: "A", text: "into" },
      { id: "B", text: "out of" },
      { id: "C", text: "behind" },
      { id: "D", text: "beside" },
    ],
    correctAnswer: "A",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "Choose the correct quantifier: 'I have _____ money, so I can't go to the cinema.'",
    tip: "'Money' é incontável (uncountable). Qual quantificador significa 'pouco/a' com substantivos incontáveis?",
    funFact: "'Little' (uncountable) = not much. 'Few' (countable) = not many. But notice: 'I have little money' = negative (not enough), while 'I have a little money' = positive (some, which is okay)!",
    points: 1,
    options: [
      { id: "A", text: "many" },
      { id: "B", text: "few" },
      { id: "C", text: "little" },
      { id: "D", text: "much" },
    ],
    correctAnswer: "C",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "Choose the correct relative pronoun: 'The movie _____ we watched last night was amazing.'",
    tip: "O pronome relativo substitui 'the movie' — uma coisa. Qual pronome relativo é usado para coisas em orações relativas?",
    funFact: "'Which' introduces non-defining relative clauses for things. 'That' can replace 'which' in defining clauses. But after commas (non-defining), only 'which' is used: 'The movie, which won an Oscar, was amazing.'",
    points: 1,
    options: [
      { id: "A", text: "who" },
      { id: "B", text: "which" },
      { id: "C", text: "whose" },
      { id: "D", text: "whom" },
    ],
    correctAnswer: "B",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Choose the correct passive form: 'The letter _____ already.'",
    tip: "A carta foi enviada em algum momento antes do presente, e isso ainda é relevante agora. Qual tempo verbal combina com 'already'?",
    funFact: "Present perfect passive = has/have been + past participle. Common with 'already', 'yet', 'just', 'recently': 'The email has been sent', 'The decision has been made'!",
    points: 1,
    options: [
      { id: "A", text: "has been sent" },
      { id: "B", text: "have been sent" },
      { id: "C", text: "was sent" },
      { id: "D", text: "had sent" },
    ],
    correctAnswer: "A",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Fill in the blanks with the correct structure: 'This test is not _____ difficult _____ the last one.'",
    tip: "A frase compara dois elementos e indica que são iguais (ou nesse caso, que um não é igual ao outro). Qual estrutura é usada para comparações de igualdade/desigualdade?",
    funFact: "The structure 'as...as' makes equal comparisons: 'She is as tall as her brother'. With 'not', it becomes unequal: 'This isn't as hard as I expected'. It's one of the most elegant comparison structures!",
    points: 1,
    options: [
      { id: "A", text: "more ... than" },
      { id: "B", text: "so ... then" },
      { id: "C", text: "as ... that" },
      { id: "D", text: "as ... as" },
    ],
    correctAnswer: "D",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Choose the correct preposition: 'The meeting will take place _____ Monday morning.'",
    tip: "Quando indicamos um dia da semana específico, qual preposição de tempo é usada em inglês?",
    funFact: "Time prepositions: AT (specific time: at 3pm, at noon), ON (days and dates: on Monday, on May 5th), IN (months, years, seasons: in June, in 2025, in winter). Remember: AT, ON, IN!",
    points: 1,
    options: [
      { id: "A", text: "in" },
      { id: "B", text: "on" },
      { id: "C", text: "at" },
      { id: "D", text: "by" },
    ],
    correctAnswer: "B",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "What does the idiom 'it's raining cats and dogs' mean?",
    tip: "Essa expressão inglesa descreve o clima de forma exagerada e humorística. Gatos e cães caindo do céu — imagine o caos!",
    funFact: "One theory traces this to 17th-century England, when heavy rains would wash cats and dogs that had sheltered in thatched roofs down into the streets. Today it simply means very heavy rain!",
    points: 1,
    options: [
      { id: "A", text: "There are animals walking in the rain" },
      { id: "B", text: "The rain is very light" },
      { id: "C", text: "It's raining very heavily" },
      { id: "D", text: "The rain is stopping" },
    ],
    correctAnswer: "C",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Choose the correct passive form: 'The bridge _____ in 1850.'",
    tip: "A ação de construir aconteceu em um momento específico no passado. Qual é a forma passiva do passado simples?",
    funFact: "Passive voice is very common when describing historical events and constructions: 'The Eiffel Tower was built in 1889', 'The Great Wall was constructed over many centuries'!",
    points: 1,
    options: [
      { id: "A", text: "was built" },
      { id: "B", text: "built" },
      { id: "C", text: "has been built" },
      { id: "D", text: "is built" },
    ],
    correctAnswer: "A",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Choose the correct quantifier: 'There are _____ people at the party — it's crowded!'",
    tip: "O local está lotado. 'People' é contável. Qual expressão indica grande quantidade com substantivos contáveis?",
    funFact: "'A lot of' can be used with both countable and uncountable nouns: 'a lot of people', 'a lot of water'. In formal writing, prefer 'many' (countable) or 'much' (uncountable) instead!",
    points: 1,
    options: [
      { id: "A", text: "few" },
      { id: "B", text: "little" },
      { id: "C", text: "much" },
      { id: "D", text: "a lot of" },
    ],
    correctAnswer: "D",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Choose the correct relative pronoun: 'This is the restaurant _____ we always come to.'",
    tip: "O pronome relativo se refere a 'the restaurant' — um lugar. Qual pronome relativo pode ser usado para coisas e lugares em orações definidoras?",
    funFact: "'That' is often preferred over 'which' in defining (essential) relative clauses in American English. It can refer to people OR things! 'The restaurant that we visit', 'The person that helped me'.",
    points: 1,
    options: [
      { id: "A", text: "who" },
      { id: "B", text: "that" },
      { id: "C", text: "whose" },
      { id: "D", text: "whom" },
    ],
    correctAnswer: "B",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Choose the correct superlative: 'This is _____ meal I've ever had.'",
    tip: "O adjetivo 'delicious' tem três sílabas. Como se forma o superlativo de adjetivos longos?",
    funFact: "With long adjectives (3+ syllables), the superlative uses 'the most + adjective': the most delicious, the most interesting, the most comfortable. Never add '-est' to long adjectives!",
    points: 1,
    options: [
      { id: "A", text: "more delicious" },
      { id: "B", text: "the more delicious" },
      { id: "C", text: "the most delicious" },
      { id: "D", text: "deliciously" },
    ],
    correctAnswer: "C",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Choose the correct preposition: 'The children ran _____ the field, from one end to the other.'",
    tip: "As crianças estão se movendo de um lado ao outro de um espaço aberto. Qual preposição indica movimento de um extremo ao outro de uma superfície?",
    funFact: "'Across' implies moving over a flat or open surface from one side to the other (across a field, across the street, across the ocean). 'Through' is used for enclosed or dense spaces (through the forest)!",
    points: 1,
    options: [
      { id: "A", text: "across" },
      { id: "B", text: "through" },
      { id: "C", text: "around" },
      { id: "D", text: "over" },
    ],
    correctAnswer: "A",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Choose the correct passive form with a modal verb: 'This door _____ at all times.'",
    tip: "A regra é que a porta sempre deve estar fechada. Combine o modal 'must' com a voz passiva do verbo 'lock'.",
    funFact: "Modal passive = modal + be + past participle: must be locked, should be checked, can be opened, will be fixed. This structure is very common in rules, signs, and instructions!",
    points: 1,
    options: [
      { id: "A", text: "must lock" },
      { id: "B", text: "must locked" },
      { id: "C", text: "must be locking" },
      { id: "D", text: "must be locked" },
    ],
    correctAnswer: "D",
  },
];
