export const questoesSociologia1EmB4Av2 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'O Índice de Gini é a principal medida estatística utilizada para medir a desigualdade de renda de um país. Como ele funciona?',
    tip: 'O Gini varia entre 0 e 1 — quanto mais próximo de 0, mais igual é a distribuição; quanto mais próximo de 1, mais desigual.',
    funFact: 'Você sabia? O Brasil historicamente possui um dos índices de Gini mais altos do mundo — em 2022, foi de 0,518, colocando o país entre os mais desiguais do planeta. Para efeito de comparação, países escandinavos como a Dinamarca têm Gini em torno de 0,28!',
    points: 1,
    options: [
      { id: 'A', text: 'Medida que varia de 0 (perfeita igualdade de renda) a 1 (máxima concentração de renda em uma só pessoa); quanto mais próximo de 1, maior a desigualdade' },
      { id: 'B', text: 'Medida do PIB per capita de um país, indicando a riqueza média de cada habitante' },
      { id: 'C', text: 'Índice que mede apenas a pobreza absoluta, sem considerar a distribuição de renda entre os mais ricos' },
      { id: 'D', text: 'Percentual da população que vive abaixo da linha da pobreza definida pelo Banco Mundial' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'A concentração de renda no Brasil é historicamente elevada. Como se distribui a renda entre os diferentes grupos da população brasileira?',
    tip: 'Os dados de concentração de renda no Brasil mostram uma estrutura em que uma parcela muito pequena da população detém uma fatia enorme da renda total do país.',
    funFact: 'Você sabia? Segundo o IBGE, o 1% mais rico do Brasil recebe cerca de 33% de toda a renda do país, enquanto os 50% mais pobres recebem apenas 14,7%. É como se em cada R$ 100 de renda gerados no Brasil, R$ 33 fossem para apenas uma pessoa em cada cem!',
    points: 1,
    options: [
      { id: 'A', text: 'A renda no Brasil é distribuída de forma relativamente equilibrada, com pequenas diferenças entre os grupos' },
      { id: 'B', text: 'Os 50% mais pobres brasileiros recebem mais da metade de toda a renda nacional' },
      { id: 'C', text: 'A concentração de renda no Brasil está em queda acelerada e em breve atingirá o nível de países europeus' },
      { id: 'D', text: 'O 1% mais rico concentra aproximadamente 33% de toda a renda nacional, enquanto os 50% mais pobres ficam com menos de 15% — evidência da extrema concentração de renda no país' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'A desigualdade regional é uma característica marcante do Brasil. Como ela se manifesta entre as regiões do país?',
    tip: 'O Brasil é um país de contrastes regionais profundos — o Sudeste industrializado versus o Nordeste e Norte mais pobres. Isso é resultado de processos históricos.',
    funFact: 'Você sabia? O PIB per capita do Distrito Federal é mais de 5 vezes maior que o do Maranhão, o estado mais pobre do Brasil. São Paulo sozinho responde por cerca de 32% do PIB nacional, enquanto os nove estados do Nordeste juntos respondem por apenas 13%!',
    points: 1,
    options: [
      { id: 'A', text: 'As desigualdades regionais brasileiras são mínimas e resultam apenas de diferenças culturais entre as populações' },
      { id: 'B', text: 'O Brasil é internacionalmente reconhecido por ter as regiões mais homogêneas em termos de desenvolvimento entre todos os países americanos' },
      { id: 'C', text: 'O Brasil apresenta profundas disparidades regionais: o Sudeste concentra a maior parte do PIB e infraestrutura, enquanto Norte e Nordeste têm menores índices de desenvolvimento humano, reflexo da colonização desigual e dos ciclos econômicos históricos' },
      { id: 'D', text: 'As desigualdades regionais foram completamente eliminadas com o Plano Real em 1994 e as políticas de transferência de renda' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'O Programa Bolsa Família foi um dos mais importantes programas de transferência de renda do Brasil. Quais eram suas principais características e resultados?',
    tip: 'O Bolsa Família tinha uma lógica específica: não era uma esmola — era uma transferência de renda condicionada ao cumprimento de contrapartidas pelas famílias.',
    funFact: 'Você sabia? O Bolsa Família chegou a atender 14 milhões de famílias em seu auge. Estudos acadêmicos mostraram que o programa foi responsável por cerca de 28% da redução da extrema pobreza no Brasil entre 2003 e 2013, e teve impacto positivo na frequência escolar e na saúde das crianças das famílias beneficiadas!',
    points: 1,
    options: [
      { id: 'A', text: 'Programa que criava empregos diretos para os pobres por meio da construção de obras públicas nas periferias' },
      { id: 'B', text: 'Programa federal de transferência de renda condicionada a famílias em situação de pobreza e extrema pobreza, vinculado ao cumprimento de contrapartidas como frequência escolar das crianças e acompanhamento de saúde' },
      { id: 'C', text: 'Programa municipal voltado exclusivamente para a geração de renda por meio do microempreendedorismo individual' },
      { id: 'D', text: 'Programa privado de filantropia empresarial para doação de alimentos e roupas às famílias pobres' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'A extrema pobreza é uma condição específica dentro do espectro mais amplo da pobreza. Como ela é definida e qual é sua realidade no Brasil?',
    tip: 'A extrema pobreza não é apenas "pouca renda" — é a condição em que a pessoa não consegue satisfazer nem suas necessidades alimentares básicas.',
    funFact: 'Você sabia? O Brasil chegou a sair do Mapa da Fome da FAO (2014) após reduções expressivas na extrema pobreza nos anos 2000. No entanto, retornou ao mapa em 2022, com estimativas de 33 milhões de pessoas em insegurança alimentar grave — um retrocesso de mais de 20 anos!',
    points: 1,
    options: [
      { id: 'A', text: 'Condição de renda insuficiente para garantir alimentação adequada e necessidades básicas de sobrevivência; no Brasil, estima-se que dezenas de milhões de pessoas viviam nessa condição em 2022' },
      { id: 'B', text: 'Condição exclusiva de pessoas sem teto que vivem nas ruas das grandes cidades' },
      { id: 'C', text: 'Condição de quem vive sem acesso a bens supérfluos como televisão e internet, mas com necessidades básicas atendidas' },
      { id: 'D', text: 'Condição temporária que afeta apenas imigrantes recém-chegados ao Brasil sem documentação' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'O Benefício de Prestação Continuada (BPC) é um direito constitucional previsto na Constituição de 1988. A quem ele se destina e qual é seu valor?',
    tip: 'O BPC é um benefício previdenciário não contributivo — a pessoa recebe mesmo sem ter contribuído para a Previdência Social. Para quem ele é voltado?',
    funFact: 'Você sabia? O BPC foi uma conquista do movimento de pessoas com deficiência e dos idosos na Constituinte de 1988. Ele garante 1 salário mínimo mensal para idosos acima de 65 anos e pessoas com deficiência que comprovem não ter meios de prover sua subsistência. Em 2023, mais de 5,5 milhões de pessoas eram beneficiadas!',
    points: 1,
    options: [
      { id: 'A', text: 'Benefício destinado a desempregados de qualquer idade que percam emprego formal com carteira assinada' },
      { id: 'B', text: 'Benefício previdenciário contributivo pago a todos os trabalhadores que se aposentam após 35 anos de contribuição' },
      { id: 'C', text: 'Benefício municipal destinado exclusivamente a famílias com filhos em idade escolar que mantêm frequência regular' },
      { id: 'D', text: 'Benefício constitucional não contributivo de 1 salário mínimo mensal destinado a idosos acima de 65 anos e pessoas com deficiência em situação de pobreza extrema' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'O PROUNI (Programa Universidade para Todos) foi criado em 2005 como política de inclusão no ensino superior. Qual é seu objetivo e mecanismo?',
    tip: 'O PROUNI oferece bolsas em faculdades privadas — mas para quem? E em troca de quê para as instituições participantes?',
    funFact: 'Você sabia? Desde sua criação em 2005 até 2023, o PROUNI concedeu mais de 4 milhões de bolsas em faculdades privadas para estudantes de baixa renda. Estudos mostram que o programa aumentou significativamente o acesso ao ensino superior de jovens negros e das classes mais baixas!',
    points: 1,
    options: [
      { id: 'A', text: 'Programa que cria universidades públicas federais em cidades do interior para democratizar o acesso ao ensino superior' },
      { id: 'B', text: 'Programa de financiamento estudantil com juros baixos para estudantes de faculdades privadas que precisam de crédito' },
      { id: 'C', text: 'Programa que oferece bolsas integrais ou parciais em faculdades privadas para estudantes de baixa renda, em troca de isenção fiscal para as instituições participantes' },
      { id: 'D', text: 'Programa exclusivo para estudantes negros que queiram ingressar em universidades públicas por meio de cotas raciais' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'O FIES (Fundo de Financiamento Estudantil) é outra política de acesso ao ensino superior. Como ele funciona e qual é sua diferença em relação ao PROUNI?',
    tip: 'PROUNI é bolsa (não precisa pagar de volta); FIES é financiamento (precisa pagar, mas com condições facilitadas). Isso faz uma diferença enorme na vida dos estudantes.',
    funFact: 'Você sabia? O FIES entrou em crise em 2014-2015 quando muitos formandos não conseguiram empregos com salários suficientes para pagar as dívidas. O governo teve que renegociar os contratos e tornar as condições mais restritivas para evitar um colapso financeiro do programa!',
    points: 1,
    options: [
      { id: 'A', text: 'Fundo que financia exclusivamente cursos de pós-graduação em universidades públicas para pesquisadores' },
      { id: 'B', text: 'Programa federal de financiamento de mensalidades em faculdades privadas para estudantes de baixa renda, com pagamento a ser realizado após a conclusão do curso com juros subsidiados pelo governo' },
      { id: 'C', text: 'Fundo que cobre apenas os custos de material didático (livros, computador) para estudantes do ensino médio público' },
      { id: 'D', text: 'Programa de isenção total de mensalidade em faculdades privadas sem necessidade de pagamento futuro' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'A mobilidade social é um conceito central na análise da desigualdade. O que significa mobilidade social vertical ascendente?',
    tip: 'Mobilidade social é o movimento de pessoas entre as diferentes posições (classes, estratos) na hierarquia social — pode ser para cima (ascendente) ou para baixo (descendente).',
    funFact: 'Você sabia? A mobilidade social no Brasil aumentou nas décadas de 1990-2010, quando milhões de pessoas passaram da classe D/E para a classe C (chamada "nova classe média"). Mas estudos mostram que a mobilidade intergeracional ainda é baixa: filhos de pobres têm grande dificuldade de alcançar posições elevadas na hierarquia social!',
    points: 1,
    options: [
      { id: 'A', text: 'Movimento de indivíduos ou grupos para posições mais elevadas na hierarquia social em relação à posição de seus pais ou à própria posição anterior' },
      { id: 'B', text: 'Movimento de pessoas entre regiões geográficas diferentes dentro do mesmo país em busca de emprego' },
      { id: 'C', text: 'Situação em que as classes sociais são fixas e imutáveis, sem possibilidade de mudança de posição' },
      { id: 'D', text: 'Passagem de uma classe social para outra em direção a posições menos valorizadas na hierarquia social' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'A desigualdade racial é uma dimensão específica da desigualdade brasileira. Como ela se manifesta no mercado de trabalho?',
    tip: 'A desigualdade racial no Brasil não é apenas uma questão de percepção — os dados estatísticos documentam diferenças sistemáticas entre negros e brancos no mercado de trabalho.',
    funFact: 'Você sabia? Segundo o IBGE, trabalhadores negros ganham em média 57% do salário de trabalhadores brancos. Na chefia de grandes empresas, menos de 5% são negros, embora negros e pardos sejam mais de 56% da população. A pirâmide racial corporativa brasileira é invertida em relação à pirâmide demográfica!',
    points: 1,
    options: [
      { id: 'A', text: 'A desigualdade racial no mercado de trabalho foi completamente eliminada com as políticas de cotas e o Estatuto da Igualdade Racial' },
      { id: 'B', text: 'A desigualdade racial não existe no mercado de trabalho brasileiro — as diferenças se devem apenas a níveis de escolaridade distintos' },
      { id: 'C', text: 'A desigualdade racial no Brasil beneficia trabalhadores negros, que têm prioridade no acesso aos melhores empregos por força das cotas' },
      { id: 'D', text: 'Trabalhadores negros e pardos recebem salários menores, ocupam cargos de menor prestígio, têm maiores taxas de desemprego e estão sobre-representados na informalidade em relação aos trabalhadores brancos' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'A desigualdade de gênero nos salários é um fenômeno documentado no Brasil. O que explica a diferença salarial entre homens e mulheres para funções equivalentes?',
    tip: 'A sociologia aponta múltiplos fatores que explicam a diferença salarial de gênero — não apenas discriminação explícita, mas estruturas sociais mais amplas.',
    funFact: 'Você sabia? As mulheres brasileiras estudam em média mais que os homens (escolaridade média maior) — mas ainda ganham menos! Isso refuta o argumento de que a diferença salarial se deve apenas à qualificação. O fenômeno do "teto de vidro" (barreira invisível que impede mulheres de chegarem a cargos de liderança) explica parte importante dessa diferença!',
    points: 1,
    options: [
      { id: 'A', text: 'Não existe diferença salarial real entre homens e mulheres — as estatísticas não consideram diferenças de função e jornada' },
      { id: 'B', text: 'A diferença se deve exclusivamente à menor qualificação das mulheres, que estudam e se especializam menos' },
      { id: 'C', text: 'A desigualdade salarial de gênero resulta da combinação de discriminação direta (pagar menos pelo mesmo trabalho), segregação ocupacional (mulheres em setores menos valorizados) e penalização da maternidade no mercado de trabalho' },
      { id: 'D', text: 'A diferença salarial beneficia as mulheres em setores considerados "femininos", compensando as desvantagens em outros setores' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'A estrutura de classes sociais no Brasil é objeto de debate entre sociólogos. Qual é a visão mais aceita sobre como a sociedade brasileira se estrutura?',
    tip: 'As classes sociais no Brasil não são apenas diferentes faixas de renda — elas envolvem acesso diferenciado a bens, serviços, capital cultural e poder político.',
    funFact: 'Você sabia? O sociólogo Jessé Souza propõe que o Brasil tem uma "ralé estrutural" — uma classe formada por trabalhadores precarizados, muitos descendentes de escravizados, que nunca foram incorporados ao projeto nacional moderno. Diferente da "classe média" e dos "batalhadores", essa classe enfrenta exclusão sistemática que vai além da renda!',
    points: 1,
    options: [
      { id: 'A', text: 'O Brasil é uma sociedade sem classes — as diferenças são apenas de "estilo de vida" e preferências individuais' },
      { id: 'B', text: 'A sociedade brasileira é marcada por profunda hierarquia de classes, combinando desigualdade de renda com desigualdade de acesso a capital cultural, poder político e reconhecimento social, com forte influência da herança colonial e escravista' },
      { id: 'C', text: 'As classes sociais no Brasil estão em processo de homogeneização — a desigualdade existe mas está rapidamente diminuindo' },
      { id: 'D', text: 'O Brasil tem apenas duas classes: os muito ricos e os muito pobres, sem uma classe média expressiva' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'A teoria funcionalista de Davis e Moore sobre a desigualdade social argumenta que a estratificação social é funcional para a sociedade. Qual é o argumento central e a crítica a ele?',
    tip: 'Davis e Moore defendiam que a desigualdade era necessária — pois funcionaria como incentivo para que as pessoas se esforcem para ocupar posições mais importantes. Como os críticos respondem?',
    funFact: 'Você sabia? O argumento de Davis e Moore foi publicado em 1945 e gerou um dos debates mais acirrados da sociologia do século XX. O sociólogo Melvin Tumin criticou a teoria mostrando que ela ignora como a origem social, o racismo e o sexismo bloqueiam o "talento" de chegar às posições mais importantes — a teoria pressupõe uma igualdade de oportunidades que não existe!',
    points: 1,
    options: [
      { id: 'A', text: 'Davis e Moore argumentam que a desigualdade motiva pessoas talentosas a ocupar posições socialmente importantes, mas críticos apontam que a teoria ignora como origem social, racismo e sexismo bloqueiam o acesso a oportunidades, tornando a meritocracia uma ideologia' },
      { id: 'B', text: 'Davis e Moore argumentam que a desigualdade é um crime social que deve ser eliminado por meio de revolução, mas os funcionalistas discordam' },
      { id: 'C', text: 'Davis e Moore propõem que todas as sociedades têm exatamente os mesmos níveis de desigualdade, independentemente do sistema econômico' },
      { id: 'D', text: 'Davis e Moore são marxistas que defendem a eliminação das classes sociais por meio da luta do proletariado' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'A segregação residencial é uma forma de desigualdade espacial visível nas grandes cidades brasileiras. Como ela se manifesta?',
    tip: 'Nas grandes cidades brasileiras, a localização geográfica da moradia é fortemente determinada pela classe social e pela raça — o que tem consequências profundas para o acesso a serviços e oportunidades.',
    funFact: 'Você sabia? Em São Paulo, a expectativa de vida de uma pessoa que mora no Jardins (bairro rico) é 23 anos maior do que a de quem mora no Jardim Ângela (periferia)! Isso não é apenas renda diferente — é acesso diferenciado a saúde, saneamento, segurança e qualidade de vida determinado pelo CEP da moradia!',
    points: 1,
    options: [
      { id: 'A', text: 'Segregação residencial é apenas a separação entre áreas comerciais e residenciais, sem relação com desigualdade social' },
      { id: 'B', text: 'A segregação residencial é um fenômeno que afeta apenas as cidades de países desenvolvidos, não o Brasil' },
      { id: 'C', text: 'A segregação residencial no Brasil existe mas diminuiu após o Minha Casa Minha Vida, que integrou ricos e pobres nos mesmos bairros' },
      { id: 'D', text: 'A separação espacial de grupos por classe social e raça nas cidades brasileiras, com as populações mais pobres e negras concentradas em periferias com menor acesso a serviços públicos de qualidade, empregos e infraestrutura' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'A teoria do capital humano, associada ao economista Gary Becker, é frequentemente usada para explicar desigualdades salariais. Qual é a crítica sociológica a essa teoria?',
    tip: 'A teoria do capital humano diz que quem estuda mais ganha mais — mas os sociólogos mostram que a relação entre educação e renda é mais complexa do que isso.',
    funFact: 'Você sabia? Pierre Bourdieu expandiu o conceito de capital além do econômico e do humano: ele identificou o "capital cultural" (conhecimento, disposições, títulos) e o "capital social" (redes de relações) como fundamentais. A origem de classe não determina apenas quanto você pode estudar — determina a QUALIDADE e o TIPO de educação ao qual você tem acesso!',
    points: 1,
    options: [
      { id: 'A', text: 'A teoria do capital humano é completamente correta — a desigualdade se deve apenas a diferenças de esforço individual no estudo' },
      { id: 'B', text: 'A teoria do capital humano defende que a educação é desnecessária — o talento natural é suficiente para o sucesso' },
      { id: 'C', text: 'A crítica sociológica é que a teoria ignora como o capital cultural herdado da família, as redes sociais e a discriminação por raça e gênero determinam os retornos da educação de forma desigual para diferentes grupos' },
      { id: 'D', text: 'A teoria é correta para os países desenvolvidos mas não se aplica ao Brasil por razões culturais específicas' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'O conceito de exclusão social, desenvolvido principalmente por sociólogos europeus, foi incorporado ao debate sobre desigualdade no Brasil. O que significa ser socialmente excluído?',
    tip: 'Exclusão social é mais do que pobreza — envolve múltiplas dimensões de privação que se reforçam mutuamente, impedindo o pleno exercício da cidadania.',
    funFact: 'Você sabia? O sociólogo brasileiro José de Souza Martins criticou o uso do termo "exclusão social" no Brasil, argumentando que os pobres brasileiros não estão "excluídos" da sociedade — eles estão INCLUÍDOS de forma perversa e subordinada, como consumidores de crédito predatório e trabalhadores explorados. O problema é a qualidade da inclusão, não a exclusão!',
    points: 1,
    options: [
      { id: 'A', text: 'Exclusão social significa apenas não ter acesso à internet e às novas tecnologias digitais' },
      { id: 'B', text: 'Situação de privação multidimensional em que indivíduos ou grupos são impedidos de participar plenamente da vida econômica, social, política e cultural da sociedade, acumulando desvantagens em várias dimensões simultaneamente' },
      { id: 'C', text: 'Exclusão social é sinônimo de pobreza — todo pobre é excluído e todo excluído é pobre' },
      { id: 'D', text: 'Exclusão social é um fenômeno voluntário: as pessoas escolhem se excluir ao rejeitar as normas da sociedade dominante' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'As cotas raciais nas universidades públicas e no serviço público federal foram implementadas no Brasil. Quais são os principais argumentos a favor dessa política?',
    tip: 'Os defensores das cotas raciais apresentam argumentos históricos, sociais e práticos. Qual é o raciocínio central?',
    funFact: 'Você sabia? Em 2012, o STF julgou as cotas raciais constitucionais por unanimidade (10 a 0). Em 2021, uma pesquisa do IBGE mostrou que entre 2012 e 2019, o percentual de jovens negros nas universidades quase dobrou, passando de 12,8% para 24,9%. As cotas produziram resultados concretos!',
    points: 1,
    options: [
      { id: 'A', text: 'As cotas corrigem historicamente a exclusão sistemática de negros da educação de qualidade causada pela escravidão e pela discriminação persistente, promovendo representação proporcional em espaços de poder e mobilidade social' },
      { id: 'B', text: 'As cotas são desnecessárias porque o Brasil nunca teve discriminação racial institucionalizada como nos EUA' },
      { id: 'C', text: 'As cotas são uma forma de discriminação reversa que prejudica estudantes brancos pobres que merecem as vagas' },
      { id: 'D', text: 'As cotas foram abandonadas por todos os países que as experimentaram por terem se mostrado ineficientes' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'Os gastos sociais no Brasil representam uma parcela significativa do orçamento federal. Qual é o debate sobre sua eficiência e distribuição?',
    tip: 'O Brasil gasta muito com políticas sociais — mas quem são os maiores beneficiários? O gasto social brasileiro é verdadeiramente redistributivo?',
    funFact: 'Você sabia? O Brasil gasta cerca de 25% do PIB em despesas sociais (saúde, educação, previdência, assistência social). Porém, a maior parte desse gasto vai para a previdência social — que beneficia desproporcionalmente as classes médias e altas com aposentadorias mais altas, enquanto as classes populares têm benefícios menores!',
    points: 1,
    options: [
      { id: 'A', text: 'Os gastos sociais no Brasil são mínimos e insuficientes para atender às necessidades básicas da população' },
      { id: 'B', text: 'Os gastos sociais no Brasil são perfeitamente distribuídos entre todos os grupos sociais de forma igualitária' },
      { id: 'C', text: 'Os gastos sociais beneficiam exclusivamente os mais pobres — os ricos não recebem nenhum benefício do Estado' },
      { id: 'D', text: 'Embora o Brasil invista expressivos recursos em políticas sociais, parte significativa beneficia desproporcionalmente as classes médias e altas (especialmente via previdência), com menor eficiência redistributiva do que países com menor desigualdade' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'A ideologia da meritocracia é muito presente no discurso sobre desigualdade no Brasil. Qual é a crítica sociológica à meritocracia como explicação para as desigualdades?',
    tip: 'A meritocracia soa justa — "cada um tem o que merece pelo seu esforço". Mas o que os sociólogos mostram sobre as condições reais em que as pessoas "competem" na sociedade?',
    funFact: 'Você sabia? O sociólogo Michael Sandel, em seu livro "A Tirania do Mérito" (2020), argumenta que a meritocracia cria um problema moral duplo: os "vencedores" acreditam que merecem tudo que têm (arrogância), enquanto os "perdedores" são levados a acreditar que seu fracasso é culpa deles mesmos (humilhação). Isso destrói o senso de solidariedade social!',
    points: 1,
    options: [
      { id: 'A', text: 'A meritocracia é um sistema completamente justo que garante que cada pessoa receba exatamente o que merece pelo esforço e talento' },
      { id: 'B', text: 'A crítica à meritocracia vem apenas de pessoas preguiçosas que não querem se esforçar para melhorar de vida' },
      { id: 'C', text: 'A crítica sociológica é que a meritocracia funciona como ideologia ao ignorar as condições desiguais de partida: filhos de ricos têm capital econômico, cultural e social que os colocam em vantagem estrutural sobre filhos de pobres desde o nascimento' },
      { id: 'D', text: 'A meritocracia é um sistema típico de países socialistas, não funcionando da mesma forma em economias capitalistas' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'A Previdência Social brasileira é um dos maiores gastos do orçamento federal. Qual é o debate sociológico sobre seu papel na desigualdade?',
    tip: 'A Previdência Social deveria proteger os mais vulneráveis na velhice e na invalidez. Mas quem são os maiores beneficiários do sistema previdenciário brasileiro?',
    funFact: 'Você sabia? Em 2019, os 20% mais ricos do Brasil recebiam cerca de 56% dos benefícios previdenciários do INSS, enquanto os 20% mais pobres recebiam apenas 2,6%. Isso ocorre porque as aposentadorias são calculadas com base no salário — quem ganhou mais, recebe mais, e por mais tempo (pois vivem mais)!',
    points: 1,
    options: [
      { id: 'A', text: 'A Previdência Social redistribui perfeitamente a renda dos mais ricos para os mais pobres ao longo de toda a vida' },
      { id: 'B', text: 'A Previdência Social tem caráter contraditório: ao mesmo tempo em que protege trabalhadores na velhice, seu modelo contributivo beneficia desproporcionalmente quem teve maiores salários, enquanto trabalhadores informais ficam desprotegidos' },
      { id: 'C', text: 'A Previdência Social no Brasil beneficia exclusivamente os trabalhadores do setor privado com carteira assinada' },
      { id: 'D', text: 'A Previdência Social brasileira é completamente deficitária e não paga nenhum benefício real aos aposentados' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'A desigualdade educacional é uma das dimensões mais importantes da desigualdade social brasileira. Como ela se manifesta?',
    tip: 'No Brasil, o acesso à educação de qualidade varia enormemente conforme a classe social, a raça e a região geográfica do estudante.',
    funFact: 'Você sabia? Segundo dados do PISA (exame internacional de educação), há uma diferença de até 5 anos de aprendizado entre alunos de famílias ricas e pobres no Brasil. Um estudante rico de 15 anos aprende o equivalente ao que um estudante pobre aprenderá só aos 20 anos — em parte, pela diferença de qualidade entre escolas privadas caras e escolas públicas precárias!',
    points: 1,
    options: [
      { id: 'A', text: 'A desigualdade educacional no Brasil está em extinção porque a universalização do ensino médio garantiu qualidade igual a todos' },
      { id: 'B', text: 'A desigualdade educacional afeta apenas o ensino superior — no ensino básico há igualdade plena de condições' },
      { id: 'C', text: 'A desigualdade educacional é um problema exclusivo do Nordeste, inexistente nas regiões Sul e Sudeste' },
      { id: 'D', text: 'A desigualdade educacional no Brasil se manifesta na diferença de qualidade entre escolas (públicas x privadas, urbanas x rurais), na evasão escolar concentrada nos mais pobres e na sub-representação de negros e pobres no ensino superior' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'O Brasil tem uma das maiores economias do mundo (entre as 10 maiores), mas também uma das maiores desigualdades. Como os sociólogos explicam essa aparente contradição?',
    tip: 'Crescimento econômico não significa automaticamente redução da desigualdade — depende de COMO a riqueza é distribuída.',
    funFact: 'Você sabia? O Brasil já foi a 6ª maior economia do mundo (em 2011), mas ao mesmo tempo tinha o 11º maior índice de Gini do planeta! Isso mostra que riqueza nacional e distribuição de renda são coisas completamente diferentes. Um país pode crescer economicamente e se tornar mais desigual ao mesmo tempo!',
    points: 1,
    options: [
      { id: 'A', text: 'A coexistência de alto PIB e alta desigualdade no Brasil resulta de um modelo de desenvolvimento que historicamente concentrou os ganhos do crescimento nas mãos de uma elite, sem distribuição equitativa para a maioria da população' },
      { id: 'B', text: 'Essa contradição é apenas aparente: países ricos são necessariamente mais iguais do que países pobres' },
      { id: 'C', text: 'O Brasil não tem alta desigualdade — os dados do Gini superestimam o problema por metodologia inadequada' },
      { id: 'D', text: 'Alto PIB e alta desigualdade são incompatíveis — o Brasil não pode ter os dois ao mesmo tempo' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'A relação entre desigualdade social e saúde é estudada pela sociologia da saúde. Como a posição socioeconômica afeta a saúde das pessoas?',
    tip: 'Há uma relação clara e documentada entre classe social e saúde — os ricos vivem mais e com melhor saúde. Por quê?',
    funFact: 'Você sabia? O sociólogo Michael Marmot descobriu o "gradiente social em saúde": não é apenas que os pobres têm pior saúde que os ricos — há uma escada de saúde em que cada degrau acima na hierarquia social corresponde a melhor saúde. Não é só falta de dinheiro para remédio — é o estresse crônico da hierarquia social que adoece!',
    points: 1,
    options: [
      { id: 'A', text: 'A saúde depende exclusivamente de fatores genéticos e hábitos individuais, sem relação com posição socioeconômica' },
      { id: 'B', text: 'Apenas os muito pobres têm problemas de saúde — a partir da classe média, todos têm acesso igual à saúde' },
      { id: 'C', text: 'A posição socioeconômica determina diferencialmente o acesso a saúde de qualidade, saneamento, alimentação adequada, moradia saudável e menor exposição a riscos, gerando um gradiente social em saúde que reproduz e aprofunda a desigualdade' },
      { id: 'D', text: 'No Brasil, o SUS garante igualdade plena de saúde entre todas as classes sociais, eliminando as diferenças socioeconômicas em saúde' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'A questão da concentração fundiária (de terra) no Brasil é um dos fatores históricos da desigualdade. Como ela se relaciona com a desigualdade social?',
    tip: 'O Brasil herdou da colonização um padrão de distribuição de terra extremamente concentrado — a grande propriedade (latifúndio) foi a base do poder econômico e político das elites agrárias por séculos.',
    funFact: 'Você sabia? Segundo o IBGE, em 2017, 1% dos proprietários rurais detinham 48% de toda a área agricultável do Brasil, enquanto os 50% menores proprietários detinham apenas 2,3% das terras. É a mesma lógica da concentração de renda aplicada à terra — e com raízes que remontam às sesmarias coloniais do século XVI!',
    points: 1,
    options: [
      { id: 'A', text: 'A concentração fundiária não tem relação com a desigualdade social — são fenômenos completamente independentes' },
      { id: 'B', text: 'A alta concentração fundiária no Brasil (herança colonial) impede o acesso de trabalhadores rurais pobres à terra, perpetua o poder econômico e político das elites agrárias e está na raiz da pobreza rural e da migração para as cidades' },
      { id: 'C', text: 'A concentração fundiária é irrelevante no Brasil moderno porque a maioria da população já vive em áreas urbanas' },
      { id: 'D', text: 'A concentração fundiária no Brasil está sendo rapidamente corrigida pela reforma agrária, que distribuiu quase toda a terra disponível para pequenos agricultores' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'O neoliberalismo, implantado no Brasil a partir dos anos 1990 (governo Collor e FHC), trouxe reformas econômicas significativas. Qual foi seu impacto sobre a desigualdade social?',
    tip: 'O neoliberalismo propõe que o mercado livre distribui recursos de forma mais eficiente que o Estado. A experiência brasileira confirmou essa tese?',
    funFact: 'Você sabia? Os anos 1990 foram marcados pela estabilidade econômica (Plano Real) mas também pelo aumento do desemprego (que chegou a 12% em 1999) e pela explosão do trabalho informal. A privatização de estatais como a Vale e a Embratel concentrou patrimônio público nas mãos de poucos grandes grupos econômicos nacionais e estrangeiros!',
    points: 1,
    options: [
      { id: 'A', text: 'O neoliberalismo no Brasil reduziu drasticamente a desigualdade ao eliminar os privilégios corporativistas do Estado' },
      { id: 'B', text: 'O neoliberalismo não produziu nenhum efeito mensurável sobre a distribuição de renda no Brasil' },
      { id: 'C', text: 'O neoliberalismo no Brasil reduziu o tamanho do Estado mas redistribuiu a riqueza de forma mais igualitária via mercado' },
      { id: 'D', text: 'O neoliberalismo no Brasil aprofundou desigualdades ao reduzir direitos trabalhistas, aumentar o desemprego via abertura econômica e privatizações, e concentrar as oportunidades de acumulação nos grupos com maior capital' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'A Constituição Federal de 1988 é chamada de "Constituição Cidadã". Qual foi seu impacto sobre os direitos sociais e a desigualdade no Brasil?',
    tip: 'A Constituição de 1988 foi uma ruptura com a ditadura militar e trouxe um extenso catálogo de direitos. Mas direitos no papel e direitos na prática são coisas diferentes.',
    funFact: 'Você sabia? A Constituição de 1988 foi elaborada com ampla participação popular: mais de 100 grupos organizados apresentaram emendas populares com 12 milhões de assinaturas. O resultado foi uma constituição com um dos mais extensos sistemas de direitos sociais do mundo — incluindo saúde, educação, previdência e assistência social como direitos de cidadania!',
    points: 1,
    options: [
      { id: 'A', text: 'A Constituição de 1988 estabeleceu direitos sociais universais (saúde, educação, previdência) que criaram as bases legais para a redução da desigualdade, mas sua implementação ainda é incompleta devido a tensões entre direitos e ajuste fiscal' },
      { id: 'B', text: 'A Constituição de 1988 não trouxe nenhuma inovação — apenas reafirmou os direitos já existentes na ditadura militar' },
      { id: 'C', text: 'A Constituição de 1988 aprofundou a desigualdade ao criar privilégios para grupos específicos como servidores públicos' },
      { id: 'D', text: 'A Constituição de 1988 foi um fracasso completo que não implementou nenhum dos direitos sociais nela previstos' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'A política habitacional no Brasil, especialmente nas periferias e favelas, reflete as desigualdades sociais. Qual é a análise sociológica sobre o problema habitacional brasileiro?',
    tip: 'O déficit habitacional no Brasil não é resultado apenas de falta de casas — é resultado de como o espaço urbano foi historicamente organizado de forma excludente.',
    funFact: 'Você sabia? O Brasil tem cerca de 8 milhões de unidades habitacionais no déficit (2022), mas ao mesmo tempo tem mais de 6 milhões de imóveis vazios. Isso revela que o problema não é falta de imóveis — é a especulação imobiliária que mantém imóveis desocupados enquanto milhões de famílias não têm onde morar!',
    points: 1,
    options: [
      { id: 'A', text: 'O problema habitacional brasileiro foi completamente resolvido pelo programa Minha Casa Minha Vida, que construiu todas as moradias necessárias' },
      { id: 'B', text: 'O problema habitacional é de responsabilidade individual — quem não tem casa própria não trabalhou o suficiente para comprá-la' },
      { id: 'C', text: 'O problema habitacional brasileiro reflete a segregação histórica das cidades: as classes populares foram empurradas para periferias sem infraestrutura, enquanto a especulação imobiliária mantém imóveis ociosos nas áreas centrais valorizadas' },
      { id: 'D', text: 'O problema habitacional brasileiro é exclusivo das favelas do Rio de Janeiro, não sendo um problema nas demais cidades' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'A estrutura tributária brasileira é apontada por especialistas como um fator de aprofundamento da desigualdade. Por quê?',
    tip: 'Existem dois tipos principais de impostos: os que incidem sobre a renda e o patrimônio (progressivos) e os que incidem sobre o consumo (regressivos). Qual predomina no Brasil?',
    funFact: 'Você sabia? No Brasil, os impostos sobre o consumo (IPI, ICMS, PIS, COFINS) representam cerca de 55% da arrecadação. Como todos pagam a mesma alíquota no consumo, quem ganha menos paga proporcionalmente mais do que quem ganha mais. Um trabalhador que ganha 2 salários mínimos paga cerca de 49% de sua renda em impostos, enquanto um empresário de alta renda paga proporcionalmente menos!',
    points: 1,
    options: [
      { id: 'A', text: 'A tributação brasileira é altamente progressiva porque os ricos pagam muito mais impostos que os pobres' },
      { id: 'B', text: 'A tributação no Brasil é regressiva porque predominam impostos sobre o consumo (que pesam mais sobre quem tem menor renda) em detrimento de impostos sobre grandes patrimônios e fortunas' },
      { id: 'C', text: 'A estrutura tributária brasileira é irrelevante para a desigualdade — o que importa é apenas o gasto público' },
      { id: 'D', text: 'O Brasil tem um dos sistemas tributários mais progressivos do mundo, com forte taxação de heranças e grandes fortunas' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'A sociologia distingue entre desigualdade de oportunidades e desigualdade de resultados. Qual é a diferença entre esses dois conceitos?',
    tip: 'Dois conceitos diferentes de justiça distributiva: o que importa é que todos tenham as mesmas condições de partida, ou que todos cheguem ao mesmo destino?',
    funFact: 'Você sabia? John Rawls, em "Uma Teoria da Justiça" (1971), propôs o "princípio da diferença": as desigualdades de resultado são aceitáveis desde que beneficiem os mais desfavorecidos da sociedade. Isso pressupõe que as oportunidades sejam genuinamente iguais — o que, como vimos, está longe de ser realidade no Brasil!',
    points: 1,
    options: [
      { id: 'A', text: 'Os dois conceitos são idênticos — não há diferença entre igualdade de oportunidades e igualdade de resultados' },
      { id: 'B', text: 'Desigualdade de oportunidades é sempre preferível à desigualdade de resultados em qualquer análise sociológica' },
      { id: 'C', text: 'Desigualdade de resultados é sempre justa, enquanto desigualdade de oportunidades é sempre injusta' },
      { id: 'D', text: 'Desigualdade de oportunidades refere-se a condições desiguais de partida (acesso à educação, saúde, redes sociais por origem), enquanto desigualdade de resultados refere-se às diferenças de renda, riqueza e status ao final do processo social' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'O conceito de cidadania, desenvolvido pelo sociólogo T.H. Marshall, relaciona-se diretamente com a questão da desigualdade social. Qual é essa relação no contexto brasileiro?',
    tip: 'Marshall identificou três dimensões da cidadania: civil (direitos individuais), política (direito ao voto) e social (direitos a bem-estar). Em que ordem elas se desenvolveram no Brasil?',
    funFact: 'Você sabia? T.H. Marshall escreveu sobre a Inglaterra, onde os direitos civis vieram no século XVIII, os políticos no XIX e os sociais no XX. O sociólogo José Murilo de Carvalho notou que no Brasil a sequência foi invertida: os direitos sociais vieram antes dos políticos e civis, porque Vargas os concedeu como dádiva do Estado antes da democracia — o que criou uma cidadania "passiva" dependente do Estado, não conquista da sociedade!',
    points: 1,
    options: [
      { id: 'A', text: 'No Brasil, o desenvolvimento incompleto da cidadania social (direitos a educação, saúde, moradia) contribui para perpetuar a desigualdade, pois a garantia formal de direitos não se traduz em acesso real para os mais pobres' },
      { id: 'B', text: 'Marshall demonstrou que a cidadania e a desigualdade são fenômenos completamente independentes, sem relação entre si' },
      { id: 'C', text: 'No Brasil, todos os direitos de cidadania foram plenamente implementados, eliminando as desigualdades sociais' },
      { id: 'D', text: 'A cidadania social de Marshall nunca foi aplicada em nenhum país — é apenas uma utopia teórica' },
    ],
    correctAnswer: 'A',
  },
];
