export const questoesEducacaoFisica1EmB3Av2 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "A capoeira angola e a capoeira regional são as duas principais vertentes da capoeira brasileira. Qual é a principal diferença entre elas?",
    tip: "Pense no ritmo, na postura e na intenção de cada estilo — um é mais lento e ritualístico, o outro mais dinâmico.",
    funFact: "\"Você sabia?\" — A capoeira foi reconhecida como Patrimônio Cultural Imaterial da Humanidade pela UNESCO em 2014. É o único esporte de origem afro-brasileira com esse reconhecimento, celebrando sua importância para a cultura e identidade do Brasil.",
    points: 1,
    options: [
      { id: "A", text: "A angola usa somente golpes com os pés; a regional usa somente as mãos" },
      { id: "B", text: "A angola é praticada apenas por homens; a regional permite a participação feminina" },
      { id: "C", text: "A angola usa berimbau tenor; a regional usa somente atabaque como instrumento principal" },
      { id: "D", text: "A angola é mais lenta, ritualística e próxima ao solo; a regional é mais dinâmica, com golpes acrobáticos e ritmo mais rápido" },
    ],
    correctAnswer: "D",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "Mestre Bimba é considerado o criador da capoeira regional. Qual era seu nome completo?",
    tip: "Pense no fundador da academia de capoeira regional em Salvador, Bahia, no início do século XX.",
    funFact: "\"Você sabia?\" — Mestre Bimba abriu a primeira academia oficial de capoeira do Brasil em 1932, em Salvador. Para isso, precisou convencer o então presidente Getúlio Vargas de que a capoeira era um esporte nacional — o que ajudou a tirar a modalidade da ilegalidade.",
    points: 1,
    options: [
      { id: "A", text: "Manoel dos Reis Machado" },
      { id: "B", text: "Vicente Ferreira Pastinha" },
      { id: "C", text: "João Pereira dos Santos" },
      { id: "D", text: "Antonio Cosme Damião Nunes" },
    ],
    correctAnswer: "A",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "O berimbau é o instrumento principal da capoeira. Na roda de capoeira, ele define:",
    tip: "Pense no papel do berimbau para os capoeiristas durante a roda.",
    funFact: "\"Você sabia?\" — O berimbau é feito de um arco de madeira (verga), um arame de aço (arame), uma cabaça (caxixi) e uma pedra ou moeda. Cada timbre produzido pelo berimbau comunica uma instrução específica aos capoeiristas — é uma linguagem musical.",
    points: 1,
    options: [
      { id: "A", text: "Apenas o acompanhamento festivo sem influência no jogo" },
      { id: "B", text: "O tempo máximo de duração de cada luta" },
      { id: "C", text: "O ritmo, o tipo de jogo e a velocidade da capoeira que deve ser praticada na roda" },
      { id: "D", text: "A ordem em que os capoeiristas entram na roda para disputar" },
    ],
    correctAnswer: "C",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "Mestre Pastinha é considerado o grande guardião da capoeira angola. Qual era a sua visão sobre a capoeira?",
    tip: "Pense no mestre que preservou as tradições mais antigas da capoeira, em contraste com as inovações de Bimba.",
    funFact: "\"Você sabia?\" — Mestre Pastinha fundou a academia de capoeira angola em Salvador em 1941. Ele viveu até os 92 anos e ficou cego no fim da vida, mas continuou a ensinar capoeira até não poder mais. Sua frase mais famosa é: 'Capoeira é tudo que a boca come'.",
    points: 1,
    options: [
      { id: "A", text: "Defendia que a capoeira deveria se modernizar e incorporar técnicas de outras lutas" },
      { id: "B", text: "Acreditava que a capoeira angola era a forma original e mais autêntica da capoeira, devendo preservar suas raízes africanas" },
      { id: "C", text: "Era contra a existência de academias formais — preferia ensinar nas ruas" },
      { id: "D", text: "Considerava a capoeira apenas uma dança, não uma luta" },
    ],
    correctAnswer: "B",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "A ladainha na capoeira angola é:",
    tip: "Pense no canto que abre a roda de capoeira angola, normalmente executado pelo mestre.",
    funFact: "\"Você sabia?\" — As ladainhas da capoeira angola contam histórias sobre a vida dos escravizados, sobre heróis africanos e sobre a própria capoeira. Elas são uma forma de preservar a memória e a história oral da diáspora africana no Brasil.",
    points: 1,
    options: [
      { id: "A", text: "O conjunto de golpes proibidos na roda de angola" },
      { id: "B", text: "O nome da academia de Mestre Pastinha em Salvador" },
      { id: "C", text: "A sequência de movimentos básicos ensinados aos iniciantes" },
      { id: "D", text: "Um canto solo que abre a roda, narrado geralmente pelo mestre, com conteúdo histórico e filosófico" },
    ],
    correctAnswer: "D",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "O MMA (Mixed Martial Arts) é um esporte de combate que combina técnicas de diferentes artes marciais. Qual organização é considerada a maior e mais reconhecida do MMA mundial?",
    tip: "Pense na organização americana que domina o cenário mundial do MMA desde os anos 2000.",
    funFact: "\"Você sabia?\" — O UFC (Ultimate Fighting Championship) foi criado em 1993 para descobrir qual seria a arte marcial mais eficiente em um combate sem regras. Com o tempo, as regras foram adicionadas para tornar o esporte mais seguro e atrativo para televisão.",
    points: 1,
    options: [
      { id: "A", text: "UFC (Ultimate Fighting Championship)" },
      { id: "B", text: "WBC (World Boxing Council)" },
      { id: "C", text: "PRIDE FC (Pride Fighting Championships)" },
      { id: "D", text: "Bellator MMA" },
    ],
    correctAnswer: "A",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "Na capoeira, o 'ginga' é o movimento base fundamental. Qual é sua função principal?",
    tip: "Pense no que o ginga permite ao capoeirista durante o jogo.",
    funFact: "\"Você sabia?\" — O ginga da capoeira é considerado um dos movimentos mais inteligentes de qualquer arte marcial, pois combina defesa, ataque, observação e engano simultâneos. Pesquisadores de biomecânica já estudaram o ginga como modelo de eficiência motora.",
    points: 1,
    options: [
      { id: "A", text: "Descansar entre os golpes sem perder o ritmo da música" },
      { id: "B", text: "Marcar o ritmo do berimbau com os pés" },
      { id: "C", text: "Manter o capoeirista em movimento constante para desequilibrar o adversário, criar oportunidades de ataque e dificultar golpes contra si mesmo" },
      { id: "D", text: "Demonstrar ao mestre que o aluno conhece o ritmo da música" },
    ],
    correctAnswer: "C",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "No MMA profissional (UFC), quais são as principais técnicas permitidas?",
    tip: "Pense na amplitude de técnicas que fazem do MMA um esporte verdadeiramente 'misto'.",
    funFact: "\"Você sabia?\" — O brasileiro Royce Gracie foi o primeiro grande campeão do UFC (1993-1994), usando principalmente o jiu-jitsu brasileiro (BJJ). Sua dominância mostrou ao mundo que técnica de solo e submissão podiam vencer lutadores fisicamente maiores e mais fortes.",
    points: 1,
    options: [
      { id: "A", text: "Apenas socos e chutes — técnicas de solo são proibidas" },
      { id: "B", text: "Socos, chutes, joelhadas, cotoveladas, projeções, clinch e técnicas de submissão no solo" },
      { id: "C", text: "Socos e técnicas de judô — sem chutes ao adversário parado no solo" },
      { id: "D", text: "Qualquer técnica, incluindo cabeçadas e golpes na parte de trás da cabeça" },
    ],
    correctAnswer: "B",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "A capoeira foi declarada ilegal no Brasil durante grande parte do século XIX e início do XX. Qual foi a principal razão dessa proibição?",
    tip: "Pense no contexto histórico do Brasil escravocrata e pós-abolição.",
    funFact: "\"Você sabia?\" — O Código Penal brasileiro de 1890 criminalizava a capoeira com pena de prisão. Os capoeiristas eram presos e alguns deportados para Fernando de Noronha. Apesar disso, a prática continuou clandestinamente, com os capoeiristas usando apelidos para não serem identificados.",
    points: 1,
    options: [
      { id: "A", text: "Por ser considerada uma arte marcial estrangeira incompatível com a cultura brasileira" },
      { id: "B", text: "Por causar muitos acidentes durante as apresentações públicas" },
      { id: "C", text: "Por ser considerada uma ameaça à ordem pública — era praticada por escravizados e libertos que a usavam para resistir à opressão" },
      { id: "D", text: "Por ser uma competição violenta que atraía apostas ilegais" },
    ],
    correctAnswer: "D",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "Na luta olímpica greco-romana, a principal restrição técnica é:",
    tip: "Pense na diferença entre a luta greco-romana e a luta livre no wrestling.",
    funFact: "\"Você sabia?\" — A luta greco-romana foi incluída nos Jogos Olímpicos desde 1896, sendo uma das modalidades mais antigas. O nome sugere origens gregas e romanas, mas na verdade foi desenvolvida na França no século XIX — o nome era uma forma de dar prestígio à modalidade.",
    points: 1,
    options: [
      { id: "A", text: "São proibidos golpes de projeção acima da cintura" },
      { id: "B", text: "São proibidos contatos físicos diretos com o adversário" },
      { id: "C", text: "São permitidas apenas técnicas de solo, sem projeções" },
      { id: "D", text: "São proibidos golpes nas pernas — nenhum atleta pode segurar as pernas do adversário abaixo da cintura" },
    ],
    correctAnswer: "A",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "No MMA, a vitória por 'submissão' ocorre quando:",
    tip: "Pense na forma de vitória no MMA onde o atleta força o adversário a desistir.",
    funFact: "\"Você sabia?\" — As técnicas de submissão mais comuns no MMA são o 'rear naked choke' (estrangulamento por trás) e a 'arm bar' (chave de braço). O jiu-jitsu brasileiro (BJJ) é considerado o sistema mais completo para ensinar submissões.",
    points: 1,
    options: [
      { id: "A", text: "O árbitro interrompe a luta por nocaute técnico" },
      { id: "B", text: "O adversário bate (toca o tapete) ou verbaliza sua desistência ao ser preso em uma chave ou estrangulamento" },
      { id: "C", text: "Os juízes concedem a vitória por pontos ao fim dos rounds" },
      { id: "D", text: "O médico interrompe o combate por lesão do adversário" },
    ],
    correctAnswer: "B",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "A capoeira incorpora, além dos golpes, elementos culturais importantes. Quais são eles?",
    tip: "Pense na riqueza cultural da capoeira além do aspecto marcial.",
    funFact: "\"Você sabia?\" — A capoeira é ensinada em mais de 150 países. Em países como Israel, Rússia e Alemanha, existem grupos ativos de capoeira que viajam regularmente ao Brasil para aprender com mestres brasileiros — levando a cultura afro-brasileira ao mundo.",
    points: 1,
    options: [
      { id: "A", text: "Apenas música (berimbau e atabaque) sem outros elementos culturais" },
      { id: "B", text: "Somente a dança folclórica sem componente de luta" },
      { id: "C", text: "Música (berimbau, atabaque, pandeiro, agogô, reco-reco), canto, dança, filosofia e história afro-brasileira" },
      { id: "D", text: "Apenas os golpes de luta, sem elementos musicais ou culturais na prática moderna" },
    ],
    correctAnswer: "C",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "No MMA, o octógono (Octagon) é:",
    tip: "Pense no nome e na forma da área de combate usada no UFC.",
    funFact: "\"Você sabia?\" — O octógono do UFC tem 9,1 metros de diâmetro e é cercado por uma grade de 1,83m de altura. Sua forma de oito lados foi escolhida para maximizar o espaço de luta enquanto elimina os cantos retos encontrados em ringues de boxe.",
    points: 1,
    options: [
      { id: "A", text: "O nome dado ao árbitro principal no UFC" },
      { id: "B", text: "O sistema de pontuação usado pelos juízes no MMA" },
      { id: "C", text: "O protocolo de aquecimento antes das lutas no UFC" },
      { id: "D", text: "A área de combate de formato octogonal usada pelo UFC, cercada por grade" },
    ],
    correctAnswer: "D",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "A luta livre olímpica (freestyle wrestling) se diferencia da greco-romana porque:",
    tip: "Pense na técnica que é permitida no freestyle mas proibida na greco-romana.",
    funFact: "\"Você sabia?\" — O wrestling (luta olímpica) é considerado o esporte de combate mais antigo do mundo — já era praticado na Grécia Antiga há mais de 3.000 anos. As pinturas em vasos gregos mostram lutadores em posições idênticas às usadas no wrestling moderno.",
    points: 1,
    options: [
      { id: "A", text: "Na luta livre olímpica, os atletas podem agarrar as pernas do adversário e usar as pernas ativamente nas técnicas" },
      { id: "B", text: "Na luta livre olímpica, somente técnicas de estrangulamento são válidas" },
      { id: "C", text: "Na luta livre olímpica, são proibidas quaisquer projeções — apenas técnicas de solo são permitidas" },
      { id: "D", text: "Na luta livre olímpica, qualquer contato físico é proibido acima da cintura" },
    ],
    correctAnswer: "A",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "A ginga da capoeira é realizada com uma característica corporal específica. Qual é ela?",
    tip: "Pense na postura corporal do capoeirista durante o ginga — como é a posição do corpo?",
    funFact: "\"Você sabia?\" — A postura baixa e agachada da capoeira tem origem histórica: os escravizados praticavam disfarçando como dança, para não ser reconhecida pelos senhores. A proximidade com o solo também facilita golpes rasteiros e aumenta a estabilidade.",
    points: 1,
    options: [
      { id: "A", text: "Corpo ereto e rígido, com braços levantados para proteger o rosto" },
      { id: "B", text: "Corpo inclinado para frente com os braços balançando lateralmente em posição baixa e oscilante, com constante mudança de peso entre as pernas" },
      { id: "C", text: "Posição completamente agachada sem movimento lateral" },
      { id: "D", text: "Posição de guarda similar ao boxe, com punhos fechados na frente do rosto" },
    ],
    correctAnswer: "B",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "No MMA, as categorias de peso masculinas variam do peso palha (até 52,2 kg) ao peso pesado (até 120,2 kg). Qual é a categoria de peso mais disputada e popular no UFC?",
    tip: "Pense na categoria do meio, que equilibra velocidade e força e produz os combates mais técnicos.",
    funFact: "\"Você sabia?\" — Anderson Silva, brasileiro, foi campeão peso médio do UFC por 2.457 dias consecutivos — o reinado mais longo da história do UFC. Ele venceu 16 lutas seguidas, estabelecendo um recorde que permanece até hoje como um dos mais impressionantes da história do esporte.",
    points: 1,
    options: [
      { id: "A", text: "Peso palha (até 52,2 kg)" },
      { id: "B", text: "Peso pesado (até 120,2 kg)" },
      { id: "C", text: "Peso médio (até 83,9 kg), que atraiu campeões icônicos como Anderson Silva" },
      { id: "D", text: "Peso pena (até 65,8 kg)" },
    ],
    correctAnswer: "C",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "O 'au' (aú) na capoeira é um movimento fundamental que consiste em:",
    tip: "Pense no movimento acrobático básico da capoeira que envolve o corpo passando de lado.",
    funFact: "\"Você sabia?\" — O 'aú' é chamado de 'cartwheel' em inglês. Na capoeira, ele serve tanto como esquiva (desviar de golpes) quanto como ataque, quando executado em direção ao adversário. É ensinado logo no início da formação de qualquer capoeirista.",
    points: 1,
    options: [
      { id: "A", text: "Um salto frontal completo com aterrissagem sobre os dois pés" },
      { id: "B", text: "Um giro de 360° sobre o próprio eixo com o corpo ereto" },
      { id: "C", text: "Uma rasteira aplicada na perna de apoio do adversário" },
      { id: "D", text: "Uma roda lateral (cartwheel) em que o capoeirista apoia as mãos no solo e passa as pernas lateralmente" },
    ],
    correctAnswer: "D",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "O wrestling (luta olímpica) faz parte do programa olímpico há mais de um século. Qual é o objetivo principal em uma luta de wrestling?",
    tip: "Pense no que constitui a vitória imediata no wrestling — o equivalente ao ippon do judô.",
    funFact: "\"Você sabia?\" — O wrestling esteve na ameaça de ser removido do programa olímpico em 2013, decisão que causou grande comoção mundial. Após intensa campanha dos países praticantes, foi reintegrado ao programa olímpico para os Jogos de 2020.",
    points: 1,
    options: [
      { id: "A", text: "Imobilizar o adversário com as duas escápulas tocando o solo simultaneamente (pin ou tombamento) ou acumular mais pontos por ações técnicas" },
      { id: "B", text: "Empurrar o adversário para fora do tatami" },
      { id: "C", text: "Fazer o adversário desistir aplicando uma chave de braço" },
      { id: "D", text: "Derrubar o adversário mais de três vezes durante o combate" },
    ],
    correctAnswer: "A",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "O MMA é frequentemente criticado por questões de segurança. Quais regras foram criadas para proteger os atletas?",
    tip: "Pense nas regras do MMA moderno que diferenciam o esporte de um combate sem regras.",
    funFact: "\"Você sabia?\" — As 'Regras Unificadas do MMA', adotadas em 2000 nos EUA, standardizaram as proibições no esporte. Hoje, o MMA tem mais de 30 proibições específicas, tornando-o mais seguro do que muitas pessoas acreditam.",
    points: 1,
    options: [
      { id: "A", text: "No MMA moderno não há regras — qualquer técnica é permitida" },
      { id: "B", text: "São proibidos golpes na nuca, na coluna, na virilha, cotoveladas na cabeça e outros golpes perigosos específicos" },
      { id: "C", text: "São proibidos quaisquer golpes com o cotovelo ou joelho" },
      { id: "D", text: "Apenas socos são permitidos — chutes e agarrões são proibidos" },
    ],
    correctAnswer: "B",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "A capoeira regional criada por Mestre Bimba incorporou elementos de outras artes marciais. Qual elemento específico ele adicionou à capoeira tradicional?",
    tip: "Pense na arte marcial baiana que Bimba incorporou à capoeira regional para torná-la mais eficiente em combate.",
    funFact: "\"Você sabia?\" — Mestre Bimba criou a 'sequência formada' — um método pedagógico com 8 sequências fixas para ensinar as técnicas básicas da capoeira regional. Esse método tornou o ensino mais sistemático e eficiente do que o método tradicional da capoeira angola.",
    points: 1,
    options: [
      { id: "A", text: "Técnicas de judô japonês, introduzidas por imigrantes no Brasil" },
      { id: "B", text: "Técnicas de boxe inglês, adaptadas para golpes de punho" },
      { id: "C", text: "Técnicas exclusivamente africanas do batuque, uma luta de origem da Bahia" },
      { id: "D", text: "Algumas técnicas do batuque (luta baiana de origem africana) e incorporou golpes mais diretos e eficientes" },
    ],
    correctAnswer: "C",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "No wrestling olímpico, uma situação em que o atleta coloca o adversário de costas no tatami por 2 a 4 segundos recebe qual pontuação?",
    tip: "Pense na pontuação específica no wrestling por colocar o adversário em posição desfavorável sem fazer o tombamento completo.",
    funFact: "\"Você sabia?\" — O wrestling universitário americano (college wrestling) é diferente do wrestling olímpico em algumas regras. O 'takedown' (derrubada e controle) vale 2 pontos no wrestling americano, enquanto no olímpico a valorização das ações é diferente.",
    points: 1,
    options: [
      { id: "A", text: "Exposição — vale 2 pontos e representa o controle técnico sobre o adversário" },
      { id: "B", text: "Ippon — vitória imediata por exposição" },
      { id: "C", text: "Não é pontuado — apenas o tombamento completo conta" },
      { id: "D", text: "Waza-ari — equivale a meio ponto" },
    ],
    correctAnswer: "A",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "O MMA moderno foi fortemente influenciado pelo 'jiu-jitsu brasileiro' (BJJ). Qual família brasileira foi responsável por desenvolver e popularizar o BJJ no Brasil e no mundo?",
    tip: "Pense na família brasileira que transformou o jiu-jitsu japonês em um sistema completo de combate e o levou ao mundo.",
    funFact: "\"Você sabia?\" — Carlos Gracie aprendeu jiu-jitsu com o japonês Mitsuyo Maeda, que veio ao Brasil em 1914. A família Gracie adaptou o estilo para funcionar em situações reais de combate, enfatizando o trabalho de solo e as submissões.",
    points: 1,
    options: [
      { id: "A", text: "Família Nogueira" },
      { id: "B", text: "Família Dias" },
      { id: "C", text: "Família Maia" },
      { id: "D", text: "Família Gracie, que desenvolveu o jiu-jitsu brasileiro (BJJ) a partir do jiu-jitsu japonês no início do século XX" },
    ],
    correctAnswer: "D",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Na capoeira, o 'chamado' é um gesto realizado durante a roda. O que ele representa?",
    tip: "Pense no gesto de convite que um capoeirista faz ao adversário durante o jogo.",
    funFact: "\"Você sabia?\" — Na capoeira angola, o 'chamado' é um dos elementos que torna o jogo mais estratégico e teatral. Responder ao chamado é uma questão de respeito e tradição — recusá-lo pode ser visto como falta de cortesia durante a roda.",
    points: 1,
    options: [
      { id: "A", text: "Uma punição aplicada pelo mestre quando um jogador comete uma falta" },
      { id: "B", text: "Um convite gestual para que o adversário se aproxime para uma interação específica durante o jogo" },
      { id: "C", text: "O sinal para que todos os capoeiristas presentes entrem na roda juntos" },
      { id: "D", text: "A indicação de que a música deve mudar de ritmo imediatamente" },
    ],
    correctAnswer: "B",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "O wrestling (luta olímpica) divide-se em duas modalidades olímpicas. Quais são elas?",
    tip: "Pense nas duas categorias do wrestling que fazem parte do programa olímpico.",
    funFact: "\"Você sabia?\" — O wrestling feminino olímpico foi introduzido apenas em Atenas 2004. Desde então, países como Estados Unidos, Japão e Rússia competem pelo domínio da modalidade feminina, que cresceu exponencialmente em popularidade.",
    points: 1,
    options: [
      { id: "A", text: "Wrestling profissional e wrestling de areia" },
      { id: "B", text: "Wrestling de contato e wrestling de pressão" },
      { id: "C", text: "Luta greco-romana e luta livre (freestyle wrestling)" },
      { id: "D", text: "Sumo olímpico e wrestling tradicional" },
    ],
    correctAnswer: "C",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "A 'galpão' ou roda de capoeira é o espaço onde o jogo acontece. Quem controla a roda é:",
    tip: "Pense na figura de autoridade que organiza e conduz a roda de capoeira.",
    funFact: "\"Você sabia?\" — O mestre que toca o berimbau guia não apenas a velocidade do jogo, mas também sinaliza quando os jogadores devem sair da roda, quando entrar em 'jogo bonito' ou quando as coisas estão ficando tensas demais. É um papel de grande responsabilidade.",
    points: 1,
    options: [
      { id: "A", text: "O mestre, que toca o berimbau maior e comanda todo o andamento da roda" },
      { id: "B", text: "O capoeirista mais jovem presente, como forma de respeito à renovação" },
      { id: "C", text: "Um árbitro externo que não participa da roda nem da música" },
      { id: "D", text: "Os dois capoeiristas que estão jogando no centro da roda" },
    ],
    correctAnswer: "A",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "No MMA, as lutas de título no UFC têm duração de:",
    tip: "Pense na diferença de duração entre lutas de título e lutas comuns no UFC.",
    funFact: "\"Você sabia?\" — Um combate de MMA pode terminar a qualquer momento por nocaute, submissão ou interrupção do árbitro. Quando vai aos rounds completos, são os juízes quem decidem — usando o sistema de 10 pontos por round, igual ao boxe.",
    points: 1,
    options: [
      { id: "A", text: "3 rounds de 5 minutos cada, como as lutas comuns" },
      { id: "B", text: "5 rounds de 3 minutos cada" },
      { id: "C", text: "4 rounds de 5 minutos com intervalo obrigatório de 2 minutos" },
      { id: "D", text: "5 rounds de 5 minutos cada (enquanto lutas comuns têm 3 rounds de 5 minutos)" },
    ],
    correctAnswer: "D",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "No wrestling greco-romano, quando um atleta levanta e projeta o adversário de forma espetacular acima da linha da cintura, isso é chamado de:",
    tip: "Pense na projeção mais vistosa do wrestling greco-romano, que pode valer os pontos máximos.",
    funFact: "\"Você sabia?\" — Na greco-romana, um grand amplitude (projeção espetacular) pode valer até 5 pontos de uma vez — o máximo possível em uma única ação. Isso torna a greco-romana um esporte onde um único momento pode virar completamente o resultado da luta.",
    points: 1,
    options: [
      { id: "A", text: "Tombamento direto — vale 3 pontos automáticos" },
      { id: "B", text: "Grand amplitude — projeção de grande amplitude que levanta o adversário acima da linha da cintura, valendo 5 pontos" },
      { id: "C", text: "Classement — técnica de finalização da greco-romana que vale a vitória imediata" },
      { id: "D", text: "Revers — técnica de reversão de posição no solo que vale 1 ponto" },
    ],
    correctAnswer: "B",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "A capoeira foi incluída como esporte oficial nos Jogos Mundiais em 2021. Isso representa:",
    tip: "Pense no significado desse reconhecimento para a capoeira como esporte e manifestação cultural.",
    funFact: "\"Você sabia?\" — Os Jogos Mundiais incluem esportes que não fazem parte do programa olímpico. A capoeira concorre ao status olímpico, mas enfrenta o desafio de padronizar as regras internacionalmente, mantendo ao mesmo tempo sua riqueza cultural.",
    points: 1,
    options: [
      { id: "A", text: "Que a capoeira já foi incluída nos Jogos Olímpicos de Paris 2024" },
      { id: "B", text: "Que a capoeira perdeu todas as suas características culturais para se tornar um esporte competitivo" },
      { id: "C", text: "Um importante reconhecimento internacional da capoeira como esporte e manifestação cultural brasileira, com potencial caminho para as Olimpíadas" },
      { id: "D", text: "Que a capoeira não pode mais ser praticada fora do contexto competitivo regulamentado" },
    ],
    correctAnswer: "C",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "O 'berimbau de barriga' na capoeira é:",
    tip: "Pense nos diferentes tipos de berimbau usados na roda de capoeira e seus papéis.",
    funFact: "\"Você sabia?\" — A orquestra completa de capoeira angola usa três berimbaus afinados em alturas diferentes: o gunga (mais grave), o meio (médio) e o viola (mais agudo). Cada um tem papel específico na condução da roda.",
    points: 1,
    options: [
      { id: "A", text: "O berimbau mais grave (gunga), que dita o ritmo base da roda e é tocado pelo mestre" },
      { id: "B", text: "Um berimbau menor usado exclusivamente pelos iniciantes" },
      { id: "C", text: "Um berimbau modificado com mais cordas, usado somente em apresentações teatrais" },
      { id: "D", text: "O berimbau mais agudo da orquestra, responsável por improvisações e variações melódicas" },
    ],
    correctAnswer: "A",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "O jiu-jitsu brasileiro (BJJ), amplamente utilizado no MMA, foi adaptado a partir do jiu-jitsu japonês. A principal contribuição da família Gracie foi:",
    tip: "Pense nas inovações que tornaram o BJJ diferente e mais eficaz que o jiu-jitsu japonês original.",
    funFact: "\"Você sabia?\" — Helio Gracie, o menor dos irmãos Gracie, pesava apenas 63 kg. Por não conseguir usar as técnicas originais do jiu-jitsu japonês com eficiência, ele as adaptou para usar alavancas e posições que permitissem a uma pessoa menor vencer alguém maior — criando assim o BJJ moderno.",
    points: 1,
    options: [
      { id: "A", text: "Criar as primeiras competições de jiu-jitsu no Brasil sem regras" },
      { id: "B", text: "Introduzir o jiu-jitsu no Brasil sem qualquer modificação técnica" },
      { id: "C", text: "Adaptar o jiu-jitsu japonês enfatizando o trabalho de solo, posicionamento e submissões, tornando-o eficaz para pessoas de menor estatura e força física" },
      { id: "D", text: "Criar o primeiro torneio de MMA no Brasil nos anos 1960" },
    ],
    correctAnswer: "D",
  },
];
