export const questoesPortugues1EmB2Av1 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'Na poesia, a menor unidade rítmica de um texto em verso é denominada:',
    tip: 'Pense na estrutura básica da poesia: ela é organizada em linhas. Qual é o nome de cada uma dessas linhas individuais?',
    funFact: 'Você sabia? A palavra "verso" vem do latim "versus", que significa "linha arada" ou "volta do arado" — a analogia era com o lavrador que, ao fim de cada fileira de terra, virava o arado e começava outra. Assim como o lavrador, o poeta "vira" ao final de cada linha.',
    points: 1,
    options: [
      { id: 'A', text: 'Verso, que é cada linha individual de um poema, a menor unidade estrutural da composição poética' },
      { id: 'B', text: 'Estrofe, que é o conjunto de linhas de um poema' },
      { id: 'C', text: 'Sílaba, que é a menor unidade sonora da língua' },
      { id: 'D', text: 'Metro, que é a medida rítmica do poema' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'Em um poema, um conjunto de versos agrupados que formam uma unidade rítmica e de sentido é chamado de:',
    tip: 'Assim como o texto em prosa é dividido em parágrafos, o poema é dividido em blocos de versos. Qual é o nome desses blocos?',
    funFact: 'Você sabia? A palavra "estrofe" vem do grego "strophé", que significa "volta" ou "giro". Na tragédia grega, o coro se movia pelo palco em direções alternadas enquanto cantava: a estrofe era cantada num movimento, a antiestrofe no movimento contrário.',
    points: 1,
    options: [
      { id: 'A', text: 'Parágrafo, que é a divisão utilizada em textos em prosa' },
      { id: 'B', text: 'Metro, que é a medida das sílabas do verso' },
      { id: 'C', text: 'Estrofe, que é o conjunto de versos agrupados que formam uma unidade dentro do poema' },
      { id: 'D', text: 'Rima, que é a repetição de sons no final dos versos' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'Na rima consoante (ou perfeita), a semelhança sonora entre dois versos começa:',
    tip: 'Existem dois tipos de rima baseados em qual parte das palavras se repetem. Na rima mais completa, qual parte das palavras precisa ser igual?',
    funFact: 'Você sabia? A rima consoante ou perfeita é o tipo mais comum na poesia clássica portuguesa e brasileira. Camões, Bocage e Bilac eram mestres da rima consoante — a musicalidade precisa de seus poemas era uma das fontes de seu prestígio.',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas nas vogais tônicas das palavras finais dos versos' },
      { id: 'B', text: 'A partir da vogal tônica, incluindo todas as letras (vogais e consoantes) que a seguem' },
      { id: 'C', text: 'Somente nas consoantes finais das palavras' },
      { id: 'D', text: 'Em qualquer sílaba das palavras, não necessariamente nas finais' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'Na rima toante (ou imperfeita), a correspondência sonora é incompleta porque:',
    tip: 'Essa rima é "imperfeita" porque não há identidade total de sons. Qual é o elemento que se repete e qual é o que não precisa ser idêntico?',
    funFact: 'Você sabia? A rima toante é muito comum na poesia popular nordestina e no repente. O cantador usa a rima toante para ter mais flexibilidade na improvisação — é mais fácil encontrar palavras que rimam apenas nas vogais do que em vogais e consoantes.',
    points: 1,
    options: [
      { id: 'A', text: 'A rima ocorre em qualquer posição dentro do verso, não apenas no final' },
      { id: 'B', text: 'A rima se dá entre palavras do início dos versos, não do final' },
      { id: 'C', text: 'A rima reproduz apenas os sons consonantais das palavras' },
      { id: 'D', text: 'Apenas as vogais tônicas e as que as seguem são idênticas, enquanto as consoantes podem ser diferentes — como "amor/senhor" ou "vento/dentro"' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'Observe o esquema de rimas: "A chuva cai tão suave (A) / E a brisa sopra gentil (B) / A tarde parece uma nave (A) / No céu azul de abril (B)". O padrão de rimas desse esquema (ABAB) é chamado de rima:',
    tip: 'Observe como as rimas se alternam: o primeiro verso rima com o terceiro, o segundo com o quarto. Como se chama esse padrão?',
    funFact: 'Você sabia? A rima alternada (ABAB) é uma das mais usadas na poesia lírica europeia. O soneto petrarquista, que influenciou toda a poesia ocidental, usa rimas alternadas e emparelhadas em combinação, criando uma estrutura musical complexa e equilibrada.',
    points: 1,
    options: [
      { id: 'A', text: 'Rima alternada ou cruzada (ABAB), pois os versos alternam o padrão de sons, com o 1º rimando com o 3º e o 2º com o 4º' },
      { id: 'B', text: 'Rima emparelhada (AABB), pois os versos consecutivos rimam entre si' },
      { id: 'C', text: 'Rima abraçada (ABBA), pois o primeiro e o último verso rimam, envolvendo os do meio' },
      { id: 'D', text: 'Rima interpolada, pois os versos rimam de maneira não convencional' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'Num poema com o esquema de rimas "AABB" — onde o 1º verso rima com o 2º, e o 3º com o 4º —, o tipo de rima utilizado é chamado de:',
    tip: 'Nesse padrão, os versos "andam em pares" — cada dois versos consecutivos formam um par que rima. Como esse padrão é chamado?',
    funFact: 'Você sabia? A rima emparelhada ou paralela é muito comum em textos medievais e em cordéis. Os poetas de cordel nordestino frequentemente usam a sextilha (ABCBDB) ou o martelo agalopado, mas a rima emparelhada aparece em muitas composições mais simples e diretas.',
    points: 1,
    options: [
      { id: 'A', text: 'Rima alternada (ABAB), pois os versos se alternam no padrão de sons' },
      { id: 'B', text: 'Rima abraçada (ABBA), pois o primeiro verso "abraça" o último' },
      { id: 'C', text: 'Rima emparelhada ou paralela (AABB), pois os versos consecutivos rimam dois a dois' },
      { id: 'D', text: 'Rima interpolada, pois os pares de versos se intercalam no poema' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'O verso com sete sílabas poéticas é chamado de redondilha maior e é muito comum na poesia popular e nas canções tradicionais portuguesas e brasileiras. Um verso de sete sílabas tem quantas unidades métricas?',
    tip: 'O nome "redondilha maior" já diz tudo — é um verso de sete sílabas. Contar as sílabas poéticas (não gramaticais) até a última tônica é a base da métrica.',
    funFact: 'Você sabia? A redondilha maior (7 sílabas) é o metro mais usado na poesia popular portuguesa e brasileira há séculos. Camões usou-a em suas redondilhas; os repentistas nordestinos e os compositores de modas de viola continuam usando esse metro até hoje.',
    points: 1,
    options: [
      { id: 'A', text: 'Cinco sílabas poéticas — é chamado de redondilha menor' },
      { id: 'B', text: 'Sete sílabas poéticas — por isso é denominado heptassílabo ou redondilha maior' },
      { id: 'C', text: 'Oito sílabas poéticas — é chamado de octossílabo' },
      { id: 'D', text: 'Dez sílabas poéticas — é o verso heroico por excelência' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'O verso de dez sílabas poéticas — predominante na épica clássica portuguesa, especialmente em "Os Lusíadas" de Camões — é chamado de:',
    tip: 'Esse verso é considerado o mais nobre e heroico da tradição poética em língua portuguesa. Seu nome vem do número de sílabas que possui.',
    funFact: 'Você sabia? O decassílabo é o metro da epopeia e do soneto na poesia clássica. Em inglês, seu equivalente é o "iambic pentameter" de Shakespeare. Ambos têm dez sílabas, mas com padrões de acentuação diferentes — o que mostra como cada língua desenvolveu seu próprio "verso nobre".',
    points: 1,
    options: [
      { id: 'A', text: 'Redondilha maior — verso de sete sílabas muito usado na poesia popular' },
      { id: 'B', text: 'Alexandrino — verso de doze sílabas usado na poesia neoclássica francesa' },
      { id: 'C', text: 'Octossílabo — verso de oito sílabas usado em baladas medievais' },
      { id: 'D', text: 'Decassílabo — verso de dez sílabas, considerado o verso heroico da tradição poética em língua portuguesa' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'O soneto é uma das formas poéticas mais tradicionais da literatura ocidental. Qual é a estrutura padrão de um soneto clássico?',
    tip: 'Lembre-se das aulas sobre a forma fixa do soneto: ele tem um número fixo de versos divididos em estrofes de formatos específicos.',
    funFact: 'Você sabia? O soneto foi criado na Itália no século XIII e chegou a Portugal no século XVI. Sá de Miranda trouxe a forma italiana para Portugal, e Camões a aperfeiçoou. Hoje, é uma das formas poéticas mais cultivadas no mundo inteiro — de Shakespeare a Fernando Pessoa.',
    points: 1,
    options: [
      { id: 'A', text: 'Quatorze versos organizados em duas quartetos e dois tercetos, com versos decassílabos, rimados e com uma estrutura argumentativa clássica' },
      { id: 'B', text: 'Doze versos organizados em três quadras de quatro versos' },
      { id: 'C', text: 'Oito versos em duas estrofes de quatro linhas cada' },
      { id: 'D', text: 'Dezesseis versos organizados em quatro quartetos rimados' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'A poesia concreta, movimento que surgiu no Brasil na década de 1950 com o grupo Noigandres, se diferencia da poesia tradicional principalmente porque:',
    tip: 'Pense em como essa poesia foi chamada de "concreta": ela não é apenas lida, ela é também vista. O que muda na relação entre o texto e a página?',
    funFact: 'Você sabia? O grupo Noigandres — formado por Augusto de Campos, Haroldo de Campos e Décio Pignatari — publicou o "Plano Piloto para Poesia Concreta" em 1958. O manifesto propunha uma poesia em que a palavra fosse tratada como objeto visual, sonoro e semântico ao mesmo tempo.',
    points: 1,
    options: [
      { id: 'A', text: 'Usa apenas versos de quatorze sílabas e rimas toantes' },
      { id: 'B', text: 'É escrita em latim, como os poetas clássicos da antiguidade faziam' },
      { id: 'C', text: 'Explora a disposição visual das palavras na página como elemento poético, criando uma fusão entre texto, imagem e espaço' },
      { id: 'D', text: 'Usa rimas perfeitas e metros regulares para criar musicalidade intensa' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'O ritmo poético resulta da combinação de vários elementos sonoros e estruturais do verso. Qual das opções define corretamente o ritmo em poesia?',
    tip: 'Pense no que cria a "música" de um poema quando lido em voz alta. Não é só a rima — há algo mais profundo na distribuição dos sons e dos acentos.',
    funFact: 'Você sabia? O ritmo em poesia é tão poderoso que pode sobreviver mesmo quando o sentido das palavras é incompreensível. O poeta húngaro Sándor Weöres escreveu poemas em língua inexistente — mas as pessoas conseguiam sentir a emoção pelo ritmo, mesmo sem entender nenhuma palavra.',
    points: 1,
    options: [
      { id: 'A', text: 'É a repetição de sons idênticos no final de dois ou mais versos' },
      { id: 'B', text: 'É o número exato de sílabas que cada verso deve ter' },
      { id: 'C', text: 'É o conjunto de imagens visuais criadas pelo poema' },
      { id: 'D', text: 'É o padrão de acentuação, duração e pausas que cria a musicalidade do poema, resultante da distribuição das sílabas tônicas e átonas' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'Versos que não seguem um padrão métrico fixo nem têm rimas obrigatórias são chamados de:',
    tip: 'No século XX, a poesia moderna rompeu com muitas das regras tradicionais. Como se chamam os versos que não seguem metro nem rima fixos?',
    funFact: 'Você sabia? O modernismo brasileiro de 1922 foi marcado justamente pela libertação do verso das regras métricas. Manuel Bandeira escreveu em 1919 o poema "Os Sapos", uma paródia dos poetas parnasianos que só se preocupavam com a forma. Mas foi em "Pneumotórax" (1930) que ele usou com maestria o verso livre.',
    points: 1,
    options: [
      { id: 'A', text: 'Versos brancos, que têm metro regular mas não têm rima' },
      { id: 'B', text: 'Versos livres, pois dispensam tanto o metro fixo quanto a rima obrigatória, dando ao poeta liberdade formal' },
      { id: 'C', text: 'Versos brancos e livres são a mesma coisa — ambos dispensam a rima' },
      { id: 'D', text: 'Versos soltos, que têm metro irregular mas mantêm a rima' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'As estrofes têm nomes de acordo com o número de versos que as compõem. Como são chamadas as estrofes de dois, três e quatro versos, respectivamente?',
    tip: 'Os nomes vêm das raízes latinas e gregas para os números. Dois versos, três versos, quatro versos — cada um tem seu nome específico.',
    funFact: 'Você sabia? O dístico (dois versos) é a menor estrofe possível e era muito usado nos epigramas da antiguidade clássica. Marcial, poeta romano do século I d.C., escrevia epigramas curtos e afiados em dísticos — alguns eram elogios, outros eram ataques ferozes a pessoas reais.',
    points: 1,
    options: [
      { id: 'A', text: 'Dístico (2 versos), terceto (3 versos) e quadra ou quarteto (4 versos)' },
      { id: 'B', text: 'Monóstico (2 versos), dístico (3 versos) e terceto (4 versos)' },
      { id: 'C', text: 'Par (2 versos), trio (3 versos) e quarteto (4 versos)' },
      { id: 'D', text: 'Dístico (2 versos), quadra (3 versos) e quintilha (4 versos)' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'O esquema de rimas ABBA, em que o primeiro verso rima com o quarto e o segundo com o terceiro, formando uma estrutura em que os versos externos "abraçam" os internos, é chamado de rima:',
    tip: 'O nome dessa rima dá uma pista visual: os versos de fora "envolvem" os de dentro como um abraço.',
    funFact: 'Você sabia? A rima abraçada (ABBA) é usada nos quartetos do soneto petrarquista clássico. Camões e Bocage a utilizaram extensamente. Essa estrutura cria um efeito de "fechamento" e completude — o último verso retorna ao som do primeiro, criando um círculo sonoro.',
    points: 1,
    options: [
      { id: 'A', text: 'Rima alternada (ABAB), pois os sons se alternam nos versos' },
      { id: 'B', text: 'Rima emparelhada (AABB), pois os versos rimam dois a dois' },
      { id: 'C', text: 'Rima abraçada ou interpolada (ABBA), pois os versos externos envolvem os internos, "abraçando-os"' },
      { id: 'D', text: 'Rima livre, pois não segue um padrão regular' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'O verso de doze sílabas poéticas, muito usado na poesia épica francesa clássica (como na "Canção de Rolando") e adotado por poetas neoclássicos portugueses, é chamado de:',
    tip: 'Esse verso tem doze sílabas e é muito mais longo e solene que a redondilha. Seu nome está ligado à cidade onde a forma ganhou prestígio.',
    funFact: 'Você sabia? O alexandrino é o equivalente francês do decassílabo português. Molière e Racine escreveram suas peças clássicas em alexandrinos. No Brasil, os poetas parnasianos como Olavo Bilac e Raimundo Correia cultivaram o alexandrino como símbolo de elegância e erudição.',
    points: 1,
    options: [
      { id: 'A', text: 'Decassílabo — verso de dez sílabas característico da épica portuguesa' },
      { id: 'B', text: 'Redondilha maior — verso de sete sílabas da poesia popular' },
      { id: 'C', text: 'Octossílabo — verso de oito sílabas usado nas baladas medievais' },
      { id: 'D', text: 'Alexandrino — verso de doze sílabas poéticas, associado à poesia épica francesa e adotado por poetas neoclássicos' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'O verso com cinco sílabas poéticas, muito usado em quadras populares, cantigas infantis e alguns poemas medievais portugueses, é denominado:',
    tip: 'Esse é o "irmão menor" da redondilha maior — com apenas cinco sílabas, é mais curto e tem um ritmo mais ligeiro.',
    funFact: 'Você sabia? A redondilha menor (5 sílabas) aparece muito em cantigas medievais e em brincadeiras infantis de roda. "A, e, i, o, u / o burro sabe mais que tu" é uma quadra em redondilha menor — simples, ritmada e fácil de memorizar.',
    points: 1,
    options: [
      { id: 'A', text: 'Decassílabo — verso de dez sílabas da poesia clássica' },
      { id: 'B', text: 'Redondilha menor — verso de cinco sílabas poéticas, frequente em cantigas infantis e populares' },
      { id: 'C', text: 'Octossílabo — verso de oito sílabas' },
      { id: 'D', text: 'Hexassílabo — verso de seis sílabas também chamado de redondilha menor' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'A cesura é um elemento importante da versificação. O que é a cesura num verso?',
    tip: 'Pense no que acontece quando lemos um verso longo em voz alta: há um ponto onde fazemos uma pausa natural. Esse ponto tem nome.',
    funFact: 'Você sabia? No alexandrino francês clássico, a cesura é obrigatória: ela divide o verso sempre no meio, após a sexta sílaba. Isso cria um ritmo binário muito característico (6+6). Os poetas modernos brincaram muito com o deslocamento dessa cesura obrigatória para criar efeitos de surpresa.',
    points: 1,
    options: [
      { id: 'A', text: 'A pausa interna de um verso, que o divide em dois hemistíquios, criando uma respiração rítmica no interior do verso' },
      { id: 'B', text: 'O final do verso, onde a rima se realiza' },
      { id: 'C', text: 'O prolongamento de uma frase de um verso para o seguinte' },
      { id: 'D', text: 'A última sílaba tônica do verso, que determina o metro' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'Quando uma frase ou oração poética não termina com o verso, mas continua no verso seguinte, criando um efeito de fluxo contínuo, esse recurso é chamado de:',
    tip: 'Há um recurso que "desborda" os limites do verso — a frase continua para além do final da linha poética, forçando o leitor a seguir para o próximo verso sem pausa.',
    funFact: 'Você sabia? O enjambement (ou encavalgamento) foi muito usado pelos poetas românticos para criar um ritmo mais próximo da fala natural. Shakespeare usava extensivamente esse recurso em seus monólogos — para dar ao verso uma sensação de pensamento vivo e fluindo.',
    points: 1,
    options: [
      { id: 'A', text: 'Cesura, pois divide o verso em duas partes' },
      { id: 'B', text: 'Rima alternada, pois os versos se alternam no padrão sonoro' },
      { id: 'C', text: 'Enjambement ou encavalgamento, pois a frase transborda o limite do verso e continua no verso seguinte' },
      { id: 'D', text: 'Elipse, pois há omissão de palavras no final do verso' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'Uma das principais características da poesia concreta é o uso da página como espaço expressivo. Isso significa que:',
    tip: 'Na poesia concreta, a forma visual do poema na página não é acidental — ela faz parte do significado da obra. O poema pode ser lido, mas também "visto".',
    funFact: 'Você sabia? O poema "Tensão" de Augusto de Campos dispõe as letras em espiral na página. O poema "Pós-tudo" pode ser lido em múltiplas direções. A poesia concreta questionou tudo o que era "óbvio" na poesia: que ela se lê de cima para baixo, da esquerda para a direita.',
    points: 1,
    options: [
      { id: 'A', text: 'O poema é sempre impresso em papel de alta qualidade e com tipografia especial' },
      { id: 'B', text: 'O poema usa apenas palavras de uma sílaba para simplificar a leitura' },
      { id: 'C', text: 'O poema precisa obrigatoriamente ser lido em voz alta para ser compreendido' },
      { id: 'D', text: 'A distribuição das palavras, letras e espaços em branco na página é parte integrante do significado do poema, tornando-o ao mesmo tempo visual e verbal' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'Qual é a diferença entre metro e ritmo em poesia?',
    tip: 'São conceitos relacionados, mas diferentes. Um é a medida quantitativa (número de sílabas); o outro é a qualidade expressiva criada pelo padrão sonoro.',
    funFact: 'Você sabia? Poetas parnasianos como Olavo Bilac eram obcecados com o metro — contavam e recontavam as sílabas de seus versos para garantir a perfeição métrica. Já os modernistas como Drummond preferiam o ritmo expressivo ao metro rígido, usando versos livres que soassem naturais.',
    points: 1,
    options: [
      { id: 'A', text: 'Metro e ritmo são sinônimos — ambos se referem à musicalidade do poema' },
      { id: 'B', text: 'Metro é a medida quantitativa das sílabas do verso (número de sílabas poéticas); ritmo é o padrão qualitativo de acentos, pausas e duração que cria a musicalidade' },
      { id: 'C', text: 'Metro é a rima do poema; ritmo é o número de versos em cada estrofe' },
      { id: 'D', text: 'Metro refere-se à forma do poema; ritmo refere-se ao conteúdo temático' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Para contar as sílabas poéticas de um verso, usamos regras específicas. Uma delas é a sinalefa (ou elisão), que consiste em:',
    tip: 'No verso poético, palavras que terminam em vogal e são seguidas de palavras que começam com vogal se fundem numa única sílaba. Esse fenômeno tem um nome.',
    funFact: 'Você sabia? A sinalefa é tão importante para a métrica poética que poetas clássicos deliberadamente escolhiam palavras que terminavam ou começavam com vogais para facilitar a fusão e manter o metro. Às vezes, uma vogal a mais ou a menos "quebrava" o verso — e isso era considerado um erro grave.',
    points: 1,
    options: [
      { id: 'A', text: 'Separar sílabas de palavras longas para facilitar a pronúncia no verso' },
      { id: 'B', text: 'Contar as sílabas átonas ao final do verso, após a última tônica' },
      { id: 'C', text: 'A fusão de duas sílabas vizinhas pertencentes a palavras diferentes (uma terminando em vogal, a outra começando com vogal), que se pronunciam como uma única sílaba na leitura do verso' },
      { id: 'D', text: 'A repetição de uma mesma sílaba para criar efeito de eco no poema' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Uma estrofe composta por um único verso é chamada de:',
    tip: 'Os nomes das estrofes seguem a sequência numérica: um verso, dois versos, três versos... Qual é o nome da menor estrofe possível — aquela com apenas um verso?',
    funFact: 'Você sabia? O monóstico é raro, mas memorável. "Ouvir estrelas" de Olavo Bilac tem estrofes de vários versos, mas poemas compostos de um único e impactante verso existem na tradição japonesa do haiku reduzido ao extremo, e na poesia concreta contemporânea.',
    points: 1,
    options: [
      { id: 'A', text: 'Monóstico, que é uma estrofe de um único verso' },
      { id: 'B', text: 'Dístico, que é uma estrofe de dois versos' },
      { id: 'C', text: 'Verso livre, que é um verso sem metro definido' },
      { id: 'D', text: 'Hemistíquio, que é a metade de um verso dividido por cesura' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Uma estrofe de três versos é denominada:',
    tip: 'Lembre-se da estrutura do soneto clássico: após os dois quartetos, vêm duas estrofes de três versos. Como essas estrofes se chamam?',
    funFact: 'Você sabia? O terceto é a unidade fundamental da Divina Comédia de Dante Alighieri, escrita no século XIV. Dante usou a "terza rima" (ABA, BCB, CDC...), em que cada terceto introduz uma nova rima que será retomada no terceto seguinte, criando uma cadeia contínua e inquebrável de rimas.',
    points: 1,
    options: [
      { id: 'A', text: 'Quadra, que é uma estrofe de quatro versos' },
      { id: 'B', text: 'Dístico, que é uma estrofe de dois versos' },
      { id: 'C', text: 'Quintilha, que é uma estrofe de cinco versos' },
      { id: 'D', text: 'Terceto, que é uma estrofe composta por três versos' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'A estrofe de quatro versos, um dos formatos mais comuns na poesia popular e erudita de língua portuguesa, é chamada de:',
    tip: 'Essa é a estrofe mais usada em cantigas populares, cordéis e até em hinos. Seu nome é muito próximo de uma palavra do cotidiano.',
    funFact: 'Você sabia? A quadra (ou quarteto) é a base da maioria das canções populares no mundo inteiro. O "verso-refrão-verso-refrão" de quase toda música pop segue variações dessa estrutura de quatro versos, mostrando como essa estrofe é fundamental na tradição musical e poética humana.',
    points: 1,
    options: [
      { id: 'A', text: 'Terceto, que é uma estrofe de três versos' },
      { id: 'B', text: 'Quadra ou quarteto, que é uma estrofe de quatro versos — uma das mais utilizadas na poesia popular e erudita' },
      { id: 'C', text: 'Quintilha, que é uma estrofe de cinco versos' },
      { id: 'D', text: 'Dístico, que é uma estrofe de dois versos' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'A estrofe de cinco versos é chamada de:',
    tip: 'Seguindo a sequência das estrofes: um verso (monóstico), dois (dístico), três (terceto), quatro (quadra/quarteto), cinco (?).',
    funFact: 'Você sabia? A quintilha é muito comum nas cantorias do Nordeste brasileiro. O "galope à beira-mar" é um tipo de improviso poético nordestino em quintilhas. Repentistas e poetas de bancada dominam a arte de criar quintilhas improvisadas sobre qualquer tema, com rimas AABAB ou ABABB.',
    points: 1,
    options: [
      { id: 'A', text: 'Sextilha, que é uma estrofe de seis versos' },
      { id: 'B', text: 'Quadra, que é uma estrofe de quatro versos' },
      { id: 'C', text: 'Quintilha, que é uma estrofe de cinco versos' },
      { id: 'D', text: 'Terceto, que é uma estrofe de três versos' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'A estrofe de seis versos tem o nome de:',
    tip: 'A sequência continua: após a quintilha (5 versos), qual é o nome da estrofe com seis versos?',
    funFact: 'Você sabia? A sextilha é muito popular na literatura de cordel do Nordeste. O esquema de rimas mais comum da sextilha de cordel é ABCBDB — apenas os versos pares rimam. Isso permite ao poeta mudar o "A" e o "C" livremente, facilitando a improvisação.',
    points: 1,
    options: [
      { id: 'A', text: 'Sextilha, que é uma estrofe de seis versos' },
      { id: 'B', text: 'Quintilha, que é uma estrofe de cinco versos' },
      { id: 'C', text: 'Septilha, que é uma estrofe de sete versos' },
      { id: 'D', text: 'Oitava, que é uma estrofe de oito versos' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'A estrofe de oito versos, usada por Camões na estrutura de "Os Lusíadas", é denominada:',
    tip: 'Cada canto de "Os Lusíadas" é composto por estrofes de oito versos decassílabos. Esse formato de estrofe tem um nome específico na tradição poética.',
    funFact: 'Você sabia? "Os Lusíadas" é composto por 1.102 oitavas (estrofes de oito versos), totalizando 8.816 versos! Camões usou o esquema de rimas ABABABCC para cada oitava — seis versos alternados e uma copla final de rima emparelhada. Essa estrutura cria um ritmo de "avanço e conclusão" muito elegante.',
    points: 1,
    options: [
      { id: 'A', text: 'Décima, que é uma estrofe de dez versos' },
      { id: 'B', text: 'Sextilha, que é uma estrofe de seis versos' },
      { id: 'C', text: 'Soneto, que é um poema de quatorze versos' },
      { id: 'D', text: 'Oitava ou oitava rima, que é uma estrofe de oito versos usada na épica clássica' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'A estrofe de dez versos, muito usada na poesia palaciana medieval ibérica e em algumas formas do cordel nordestino, é chamada de:',
    tip: 'Após a oitava (8 versos), há a nona (9) e depois a de dez versos. Qual é o nome da estrofe com dez versos?',
    funFact: 'Você sabia? A décima espinela é uma forma poética de dez versos com esquema ABBAACCDDC, criada pelo poeta espanhol Vicente Espinel no século XVI. No Brasil, é muito cultivada pelos poetas improvisadores de viola e cantoria, especialmente no Rio Grande do Sul e no Nordeste.',
    points: 1,
    options: [
      { id: 'A', text: 'Oitava, que é uma estrofe de oito versos' },
      { id: 'B', text: 'Décima, que é uma estrofe de dez versos, usada na poesia popular e na cantoria improvisada' },
      { id: 'C', text: 'Soneto, que possui catorze versos divididos em estrofes menores' },
      { id: 'D', text: 'Vilancete, que é uma forma poética medieval de estrutura variável' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Observe os versos: "A rosa é bela, a rosa cheira, / A rosa murcha na ribeira." Qual é o esquema de rimas desses dois versos?',
    tip: 'Olhe para as palavras finais de cada verso: "cheira" e "ribeira". Elas rimam? É uma rima perfeita (consoante) ou imperfeita (toante)? E qual o esquema (AA, AB, etc.)?',
    funFact: 'Você sabia? "Cheira" e "ribeira" formam uma rima consoante perfeita, pois a partir da vogal tônica "ei" todos os sons são idênticos: ei-ra / ei-ra. A qualidade da rima consoante é fundamental para a poesia clássica — era considerada sinal de domínio técnico do poeta.',
    points: 1,
    options: [
      { id: 'A', text: 'Rima alternada (AB), pois os sons finais dos dois versos são diferentes' },
      { id: 'B', text: 'Versos sem rima (verso branco), pois não há repetição de sons' },
      { id: 'C', text: 'Rima consoante emparelhada (AA), pois os dois versos consecutivos rimam com rima perfeita: "cheira/ribeira"' },
      { id: 'D', text: 'Rima toante (AA), pois as vogais rimam, mas as consoantes são diferentes' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'O movimento da poesia concreta no Brasil defendia que a palavra devia ser tratada simultaneamente como:',
    tip: 'Os poetas concretos não queriam separar a palavra de suas dimensões. Qual era a proposta deles para integrar as diferentes dimensões da palavra?',
    funFact: 'Você sabia? O grupo Noigandres se inspirou em três fontes principais: o poeta norte-americano E. E. Cummings (que brincava com a forma tipográfica), o poeta galês Dylan Thomas (que valorizava o som) e o poeta francês Stéphane Mallarmé (que usou o espaço da página como elemento poético em "Un Coup de Dés", de 1897).',
    points: 1,
    options: [
      { id: 'A', text: 'Um objeto icônico, sonoro e semântico ao mesmo tempo — a palavra como unidade de som, imagem e sentido integrados num espaço visual' },
      { id: 'B', text: 'Um texto com rima obrigatória e métrica clássica' },
      { id: 'C', text: 'Um objeto de museu e um documento histórico da língua portuguesa' },
      { id: 'D', text: 'Um texto livre de qualquer regra gramatical ou convenção linguística' },
    ],
    correctAnswer: 'A',
  },
];
