export const questoesIngles7AnoB3Av1 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "Which is the past tense of \"play\"?",
    tip: "Verbos regulares no passado geralmente terminam com \"-ed\". Qual opção tem essa terminação?",
    funFact: "A maioria dos verbos em inglês (cerca de 80%) são regulares e seguem essa regrinha do \"-ed\"!",
    points: 1,
    options: [
      { id: "A", text: "Played" },
      { id: "B", text: "Plays" },
      { id: "C", text: "Playing" },
      { id: "D", text: "Play" },
    ],
    correctAnswer: "A",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "Which is the past tense of \"go\"?",
    tip: "\"Go\" é um verbo irregular — ele não segue a regra do \"-ed\". Tente lembrar dessa forma sozinha, sem o \"-ed\"!",
    funFact: "\"Went\" é tão diferente de \"go\" que parece outra palavra! Isso acontece porque os verbos irregulares vêm de formas muito antigas do inglês.",
    points: 1,
    options: [
      { id: "A", text: "Goed" },
      { id: "B", text: "Going" },
      { id: "C", text: "Went" },
      { id: "D", text: "Goes" },
    ],
    correctAnswer: "C",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "Which is the past tense of \"eat\"?",
    tip: "\"Eat\" também é irregular. Pense: \"ontem eu já ___ o almoço\" — qual palavra parece mais com um verbo no passado?",
    funFact: "\"Ate\" se pronuncia parecido com \"eight\" (oito) em inglês — uma boa dica para memorizar o som!",
    points: 1,
    options: [
      { id: "A", text: "Eated" },
      { id: "B", text: "Ate" },
      { id: "C", text: "Eats" },
      { id: "D", text: "Eating" },
    ],
    correctAnswer: "B",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "Which sentence is in the simple past?",
    tip: "Passado é algo que já aconteceu. As outras frases falam do presente, do presente contínuo ou do futuro. Qual sobrou?",
    funFact: "\"Breakfast\" vem de \"break\" (quebrar) + \"fast\" (jejum) — literalmente \"quebrar o jejum\" da noite!",
    points: 1,
    options: [
      { id: "A", text: "I eat breakfast" },
      { id: "B", text: "I am eating breakfast" },
      { id: "C", text: "I will eat breakfast" },
      { id: "D", text: "I ate breakfast" },
    ],
    correctAnswer: "D",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "Which is the past tense of \"see\"?",
    tip: "Outro verbo irregular! Pense em \"eu ___ um filme ontem\" — qual palavra combina?",
    funFact: "Cuidado para não confundir \"saw\" (viu, passado de \"see\") com \"saw\" (serra, a ferramenta)! São palavras iguais mas com significados diferentes.",
    points: 1,
    options: [
      { id: "A", text: "Seed" },
      { id: "B", text: "Seeing" },
      { id: "C", text: "Saw" },
      { id: "D", text: "Sees" },
    ],
    correctAnswer: "C",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "Which is the past tense of \"watch\"?",
    tip: "\"Watch\" é regular, então só precisa do \"-ed\" no final. Qual opção segue essa regra certinho?",
    funFact: "\"Watch\" também significa \"relógio de pulso\" em inglês — tudo que você observa de perto usa esse mesmo verbo!",
    points: 1,
    options: [
      { id: "A", text: "Watched" },
      { id: "B", text: "Watching" },
      { id: "C", text: "Watchs" },
      { id: "D", text: "Watchied" },
    ],
    correctAnswer: "A",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "Which word do we use to make past tense questions?",
    tip: "\"Do\" e \"Does\" são usados no presente. Qual dessas palavras é a versão desse auxiliar no passado?",
    funFact: "\"Did\" é o passado de \"do\" e \"does\" ao mesmo tempo — ele serve para qualquer pessoa (eu, você, ele, nós)!",
    points: 1,
    options: [
      { id: "A", text: "Do" },
      { id: "B", text: "Does" },
      { id: "C", text: "Is" },
      { id: "D", text: "Did" },
    ],
    correctAnswer: "D",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "Which is the past tense of \"have\"?",
    tip: "\"Have\" é irregular. Pense: \"ontem eu ___ uma festa de aniversário\" — qual palavra combina melhor?",
    funFact: "\"Had\" é uma das palavras mais curtas e mais usadas em inglês — só três letrinhas para falar de tudo que você já teve!",
    points: 1,
    options: [
      { id: "A", text: "Haved" },
      { id: "B", text: "Had" },
      { id: "C", text: "Haves" },
      { id: "D", text: "Having" },
    ],
    correctAnswer: "B",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "Which sentence is correct for a regular verb in the past?",
    tip: "A palavra \"yesterday\" (ontem) na opção D é uma pista de que o verbo precisa estar no passado. Qual frase já tem o verbo certinho no passado?",
    funFact: "\"Walk\" é regular, então basta adicionar \"-ed\" para formar \"walked\" — fácil assim!",
    points: 1,
    options: [
      { id: "A", text: "She walked to school" },
      { id: "B", text: "She walk to school" },
      { id: "C", text: "She walking to school" },
      { id: "D", text: "She walks to school yesterday" },
    ],
    correctAnswer: "A",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "Which is the past tense of \"come\"?",
    tip: "Mais um irregular! Pense: \"ela ___ à minha festa ontem\" — qual palavra soa certo?",
    funFact: "\"Come\" e \"became\" (de \"become\") têm mudanças parecidas na vogal — isso é bem comum entre verbos irregulares em inglês!",
    points: 1,
    options: [
      { id: "A", text: "Comed" },
      { id: "B", text: "Comes" },
      { id: "C", text: "Came" },
      { id: "D", text: "Coming" },
    ],
    correctAnswer: "C",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Choose the correct negative sentence in the past.",
    tip: "Quando usamos \"didn't\", o verbo principal volta para a forma simples (sem \"-ed\"). Qual frase segue essa regra?",
    funFact: "\"Didn't\" é a forma reduzida de \"did not\" — em inglês falado, quase sempre usamos a forma reduzida!",
    points: 1,
    options: [
      { id: "A", text: "I no watched TV" },
      { id: "B", text: "I didn't watched TV" },
      { id: "C", text: "I don't watch TV yesterday" },
      { id: "D", text: "I didn't watch TV" },
    ],
    correctAnswer: "D",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Choose the correct question in the past.",
    tip: "Depois de \"Did\", o verbo principal fica na forma simples, sem \"-ed\" ou forma irregular do passado. Qual opção faz isso certo?",
    funFact: "Essa regra existe porque o \"did\" já \"carrega\" o passado sozinho — não precisa repetir a informação no verbo principal!",
    points: 1,
    options: [
      { id: "A", text: "Did you went to the park?" },
      { id: "B", text: "Did you go to the park?" },
      { id: "C", text: "Do you went to the park?" },
      { id: "D", text: "You did go to the park?" },
    ],
    correctAnswer: "B",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "Complete: \"Yesterday, we ___ a movie at the cinema.\"",
    tip: "A palavra \"yesterday\" (ontem) mostra que a ação já aconteceu. Qual opção está no passado?",
    funFact: "O primeiro filme com som e cor ao mesmo tempo foi lançado em 1935, chamado \"Becky Sharp\"!",
    points: 1,
    options: [
      { id: "A", text: "watched" },
      { id: "B", text: "watch" },
      { id: "C", text: "watches" },
      { id: "D", text: "watching" },
    ],
    correctAnswer: "A",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "Complete: \"Last week, my family ___ to the beach.\"",
    tip: "\"Last week\" (semana passada) indica passado. \"Go\" é irregular — qual é a forma certa dele no passado?",
    funFact: "O Brasil tem mais de 8 mil km de litoral — são muitas praias para visitar!",
    points: 1,
    options: [
      { id: "A", text: "go" },
      { id: "B", text: "goes" },
      { id: "C", text: "went" },
      { id: "D", text: "going" },
    ],
    correctAnswer: "C",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Complete: \"She ___ her homework before dinner.\"",
    tip: "Pense em qual dessas palavras é a forma de \"do\" usada para falar de algo que já aconteceu.",
    funFact: "\"Did\" pode ser usado tanto como verbo principal (\"she did it\") quanto como auxiliar em perguntas e negativas!",
    points: 1,
    options: [
      { id: "A", text: "do" },
      { id: "B", text: "did" },
      { id: "C", text: "does" },
      { id: "D", text: "doing" },
    ],
    correctAnswer: "B",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "Choose the correct sentence.",
    tip: "Depois de \"didn't\", o verbo fica na forma simples (sem \"-ed\"). Qual frase segue essa regra?",
    funFact: "O futebol é o esporte mais praticado no mundo, com mais de 250 milhões de jogadores registrados!",
    points: 1,
    options: [
      { id: "A", text: "He didn't played football" },
      { id: "B", text: "He not played football" },
      { id: "C", text: "He don't play football yesterday" },
      { id: "D", text: "He didn't play football" },
    ],
    correctAnswer: "D",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "Complete: \"___ you like the birthday party?\"",
    tip: "A pergunta é sobre uma festa que já aconteceu. Qual palavra usamos para perguntas no passado?",
    funFact: "A tradição de cantar \"Happy Birthday\" em festas de aniversário começou nos Estados Unidos, no final do século 19!",
    points: 1,
    options: [
      { id: "A", text: "Do" },
      { id: "B", text: "Does" },
      { id: "C", text: "Did" },
      { id: "D", text: "Were" },
    ],
    correctAnswer: "C",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "Complete: \"They ___ very happy when they won the game.\"",
    tip: "\"They\" é plural, e a frase fala de algo no passado (eles \"won\", ganharam). Qual forma do verbo \"to be\" no passado combina com \"they\"?",
    funFact: "\"Were\" é usado com \"you, we, they\" no passado, enquanto \"was\" é usado com \"I, he, she, it\"!",
    points: 1,
    options: [
      { id: "A", text: "were" },
      { id: "B", text: "was" },
      { id: "C", text: "is" },
      { id: "D", text: "are" },
    ],
    correctAnswer: "A",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "Complete: \"I ___ a letter to my grandmother last month.\"",
    tip: "\"Last month\" (mês passado) indica que a ação já aconteceu. \"Write\" é irregular — qual é a forma certa no passado?",
    funFact: "Antes dos celulares existirem, escrever cartas era a principal forma das famílias manterem contato quando moravam longe!",
    points: 1,
    options: [
      { id: "A", text: "write" },
      { id: "B", text: "writes" },
      { id: "C", text: "writing" },
      { id: "D", text: "wrote" },
    ],
    correctAnswer: "D",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "Choose the correct sentence about something that already happened.",
    tip: "As outras opções falam do presente, futuro ou estão com erro de gramática. Qual frase mostra algo que já foi feito?",
    funFact: "\"Study\" é regular, mas como termina em consoante + \"y\", trocamos o \"y\" por \"i\" antes do \"-ed\": \"studied\"!",
    points: 1,
    options: [
      { id: "A", text: "I am study for the test" },
      { id: "B", text: "I studied for the test" },
      { id: "C", text: "I study for the test tomorrow" },
      { id: "D", text: "I will studied for the test" },
    ],
    correctAnswer: "B",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Last Saturday, Bernardo visited his grandparents. Which sentence describes this correctly?",
    tip: "\"Last Saturday\" (sábado passado) já nos conta que isso aconteceu no passado. Qual frase está no tempo certo?",
    funFact: "Visitar os avós regularmente é associado, em estudos, a crianças mais felizes e seguras emocionalmente!",
    points: 1,
    options: [
      { id: "A", text: "Bernardo visited his grandparents" },
      { id: "B", text: "Bernardo visits his grandparents" },
      { id: "C", text: "Bernardo is visiting his grandparents" },
      { id: "D", text: "Bernardo will visit his grandparents" },
    ],
    correctAnswer: "A",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Bernardo wants to ask his friend if he watched the soccer game yesterday. Which question is correct?",
    tip: "A palavra \"yesterday\" mostra que é uma pergunta no passado. Qual palavra auxiliar usamos para perguntas no passado?",
    funFact: "Jogos de futebol transmitidos na TV começaram no Brasil oficialmente na Copa do Mundo de 1950!",
    points: 1,
    options: [
      { id: "A", text: "Do you watched the game yesterday?" },
      { id: "B", text: "Were you watch the game yesterday?" },
      { id: "C", text: "Do you watch the game yesterday?" },
      { id: "D", text: "Did you watch the game yesterday?" },
    ],
    correctAnswer: "D",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Bernardo didn't do his homework last night. Which sentence is correct?",
    tip: "Lembre-se: depois de \"didn't\", o verbo volta para a forma simples, sem repetir o passado. Qual frase faz isso certo?",
    funFact: "\"Homework\" vem de \"home\" (casa) + \"work\" (trabalho) — literalmente \"trabalho de casa\"!",
    points: 1,
    options: [
      { id: "A", text: "Bernardo don't did his homework" },
      { id: "B", text: "Bernardo not did his homework" },
      { id: "C", text: "Bernardo didn't do his homework" },
      { id: "D", text: "Bernardo didn't did his homework" },
    ],
    correctAnswer: "C",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Bernardo went to a birthday party and ate a lot of cake. Which verb form completes: \"Bernardo ___ a lot of cake.\"?",
    tip: "A frase já conta a história no passado (\"went to a birthday party\"). Qual forma de \"eat\" também está no passado?",
    funFact: "O bolo de aniversário com velinhas é uma tradição que remonta à Alemanha antiga, há mais de 200 anos!",
    points: 1,
    options: [
      { id: "A", text: "eat" },
      { id: "B", text: "ate" },
      { id: "C", text: "eats" },
      { id: "D", text: "eating" },
    ],
    correctAnswer: "B",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Last year, Bernardo's family traveled to Rio de Janeiro. Which sentence is correct?",
    tip: "\"Last year\" (ano passado) indica que a viagem já aconteceu. Qual frase está certinha no passado?",
    funFact: "O Rio de Janeiro recebe milhões de turistas todos os anos, principalmente por causa do Cristo Redentor e do Carnaval!",
    points: 1,
    options: [
      { id: "A", text: "Bernardo's family traveled to Rio de Janeiro" },
      { id: "B", text: "Bernardo's family travel to Rio de Janeiro" },
      { id: "C", text: "Bernardo's family traveling to Rio de Janeiro" },
      { id: "D", text: "Bernardo's family will traveled to Rio de Janeiro" },
    ],
    correctAnswer: "A",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Bernardo's team won the school championship last month. Which sentence is correct?",
    tip: "\"Win\" é irregular. \"Last month\" mostra que já aconteceu. Qual forma do verbo está certa no passado?",
    funFact: "A palavra \"championship\" vem de \"champion\" (campeão) — alguém que já \"won\" (venceu) uma competição!",
    points: 1,
    options: [
      { id: "A", text: "Bernardo's team win the championship" },
      { id: "B", text: "Bernardo's team wins the championship" },
      { id: "C", text: "Bernardo's team winning the championship" },
      { id: "D", text: "Bernardo's team won the championship" },
    ],
    correctAnswer: "D",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Bernardo wants to say he was very tired after playing soccer. Which sentence is correct?",
    tip: "\"Bernardo\" é uma pessoa só (singular), então usamos \"was\", não \"were\". E a frase fala do passado, não do presente.",
    funFact: "Depois de exercícios físicos, o corpo libera substâncias que causam aquela sensação boa de cansaço — isso se chama \"endorfina\"!",
    points: 1,
    options: [
      { id: "A", text: "Bernardo is very tired" },
      { id: "B", text: "Bernardo be very tired" },
      { id: "C", text: "Bernardo was very tired" },
      { id: "D", text: "Bernardo were very tired" },
    ],
    correctAnswer: "C",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Bernardo's dog ran away yesterday, but he found it later. Which sentence is correct?",
    tip: "\"Find\" é irregular (não existe \"founded\" para esse sentido). Pense: \"ontem ele ___ o cachorro\" — qual opção soa certo?",
    funFact: "Cuidado para não confundir \"found\" (achou) com \"founded\" (fundou, como fundar uma empresa)! São palavras bem parecidas, mas com sentidos diferentes.",
    points: 1,
    options: [
      { id: "A", text: "Bernardo find his dog" },
      { id: "B", text: "Bernardo found his dog" },
      { id: "C", text: "Bernardo founded his dog" },
      { id: "D", text: "Bernardo finds his dog" },
    ],
    correctAnswer: "B",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Bernardo didn't like the movie he watched last weekend. Which sentence is correct?",
    tip: "Depois de \"didn't\", o verbo volta para a forma simples (sem \"-ed\"). Qual frase segue essa regra?",
    funFact: "Gostar ou não de um filme é bem pessoal — por isso existem sites como críticas de cinema, para ajudar a escolher o que assistir!",
    points: 1,
    options: [
      { id: "A", text: "Bernardo didn't like the movie" },
      { id: "B", text: "Bernardo don't liked the movie" },
      { id: "C", text: "Bernardo not liked the movie" },
      { id: "D", text: "Bernardo didn't liked the movie" },
    ],
    correctAnswer: "A",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Bernardo's mom asked him what he did at school yesterday. Which question did she ask?",
    tip: "A pergunta é sobre \"yesterday\" (ontem), então precisa estar no passado, com \"did\" antes do sujeito.",
    funFact: "Perguntar \"o que você fez hoje?\" é uma ótima forma de manter conversas em família — ajuda a fortalecer os laços!",
    points: 1,
    options: [
      { id: "A", text: "What do you do at school?" },
      { id: "B", text: "What you did at school?" },
      { id: "C", text: "What does you do at school?" },
      { id: "D", text: "What did you do at school?" },
    ],
    correctAnswer: "D",
  },
];
