export const questoesHistoria7AnoB3Av2 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "Em qual região do Brasil foram encontradas, no final do século XVII, as primeiras grandes descobertas de ouro?",
    tip: "O próprio nome do estado já dá uma grande pista sobre essa riqueza!",
    funFact: "O nome \"Minas Gerais\" vem justamente da grande quantidade de minas de ouro e outros metais encontradas na região!",
    points: 1,
    options: [
      { id: "A", text: "Rio Grande do Sul" },
      { id: "B", text: "Maranhão" },
      { id: "C", text: "Minas Gerais" },
      { id: "D", text: "Amazonas" },
    ],
    correctAnswer: "C",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "A descoberta do ouro em Minas Gerais provocou um fenômeno conhecido como:",
    tip: "Pensa: quando se descobre uma riqueza assim, as pessoas tendem a fugir dali ou correr para lá?",
    funFact: "Esse fenômeno de \"corrida do ouro\" também aconteceu depois em outros lugares do mundo, como nos Estados Unidos, no século XIX!",
    points: 1,
    options: [
      { id: "A", text: "Corrida do ouro, com grande migração de pessoas para a região" },
      { id: "B", text: "Esvaziamento total da região" },
      { id: "C", text: "Proibição de qualquer exploração mineral" },
      { id: "D", text: "Abandono imediato da área" },
    ],
    correctAnswer: "A",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "Qual era a origem de muitas das pessoas que migraram para Minas Gerais durante a corrida do ouro?",
    tip: "Pensa em quem já vivia no Brasil, quem vinha de Portugal em busca de riqueza, e quem era forçado a trabalhar!",
    funFact: "Minas Gerais se tornou, durante o século XVIII, uma das regiões mais povoadas de toda a colônia!",
    points: 1,
    options: [
      { id: "A", text: "Apenas da Europa" },
      { id: "B", text: "Apenas da África, de forma livre" },
      { id: "C", text: "Apenas do Rio de Janeiro" },
      { id: "D", text: "De diversas regiões do Brasil e também de Portugal, além de um grande número de pessoas escravizadas trazidas à força" },
    ],
    correctAnswer: "D",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "A exploração do ouro nas minas utilizava principalmente qual tipo de mão de obra?",
    tip: "Lembra do simulado anterior sobre a escravidão africana e seu uso em diferentes atividades econômicas!",
    funFact: "O trabalho nas minas era extremamente árduo e perigoso, e a exploração da mão de obra escravizada foi uma grave injustiça histórica também nesse período!",
    points: 1,
    options: [
      { id: "A", text: "Apenas trabalho voluntário remunerado" },
      { id: "B", text: "Nenhum tipo de trabalho humano, apenas máquinas" },
      { id: "C", text: "Mão de obra escravizada, em grande parte de origem africana" },
      { id: "D", text: "Apenas trabalho de crianças europeias" },
    ],
    correctAnswer: "C",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "Para controlar a extração de ouro e arrecadar impostos, a Coroa portuguesa criou qual mecanismo de cobrança?",
    tip: "Pensa no nome: \"quinto\" tem a ver com uma fração, uma parte do total!",
    funFact: "O quinto correspondia a 20% de todo o ouro extraído, que deveria ser destinado à Coroa portuguesa!",
    points: 1,
    options: [
      { id: "A", text: "O imposto sobre pau-brasil" },
      { id: "B", text: "O \"quinto\", que cobrava uma parte do ouro extraído" },
      { id: "C", text: "Um imposto apenas sobre a pesca" },
      { id: "D", text: "Nenhum tipo de cobrança foi criado" },
    ],
    correctAnswer: "B",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "As \"Casas de Fundição\" foram criadas pela Coroa portuguesa para:",
    tip: "Pensa na palavra \"fundição\" — ela tem a ver com transformar metal em outra forma, como barras!",
    funFact: "Depois de passar pelas Casas de Fundição, o ouro já circulava com uma espécie de \"selo oficial\" comprovando o pagamento do imposto!",
    points: 1,
    options: [
      { id: "A", text: "Fundir o ouro em barras, já com o imposto do quinto cobrado, antes de sua circulação" },
      { id: "B", text: "Ensinar línguas estrangeiras" },
      { id: "C", text: "Produzir açúcar" },
      { id: "D", text: "Administrar o comércio de especiarias" },
    ],
    correctAnswer: "A",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "A região da mineração, incluindo cidades como Ouro Preto e Mariana, teve um crescimento importante também em qual aspecto cultural?",
    tip: "Pensa em igrejas antigas e cheias de detalhes que você talvez já tenha visto em fotos de Minas Gerais!",
    funFact: "Aleijadinho é considerado um dos maiores artistas do Brasil colonial, com obras incríveis esculpidas em pedra e madeira!",
    points: 1,
    options: [
      { id: "A", text: "Nenhum desenvolvimento cultural ocorreu" },
      { id: "B", text: "Apenas o aumento da produção de açúcar" },
      { id: "C", text: "O desenvolvimento exclusivo da pecuária" },
      { id: "D", text: "A arquitetura e a arte barroca, incluindo igrejas e esculturas, muitas vezes atribuídas a artistas como Aleijadinho" },
    ],
    correctAnswer: "D",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "Por que o descontentamento com a cobrança de impostos sobre o ouro, como o quinto, gerou tensões entre a população mineradora e a Coroa portuguesa?",
    tip: "Pensa: ninguém gosta de pagar impostos considerados injustos ou altos demais — isso gera conflito ou paz total?",
    funFact: "Esse descontentamento com impostos sobre o ouro é um dos temas que também aparecem em movimentos de resistência estudados mais à frente na história do Brasil!",
    points: 1,
    options: [
      { id: "A", text: "Porque não existia nenhum imposto sobre o ouro" },
      { id: "B", text: "Porque a cobrança era considerada excessiva por muitos mineradores, gerando insatisfação e conflitos" },
      { id: "C", text: "Porque a Coroa nunca cobrou nenhum imposto" },
      { id: "D", text: "Porque todos os mineradores concordavam totalmente com os impostos" },
    ],
    correctAnswer: "B",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "A transferência da capital colonial de Salvador para o Rio de Janeiro, em 1763, está relacionada principalmente a:",
    tip: "Pensa na localização do Rio de Janeiro em relação a Minas Gerais, comparada à distância de Salvador!",
    funFact: "O Rio de Janeiro continuou sendo capital do Brasil por quase 200 anos, até a construção de Brasília no século XX!",
    points: 1,
    options: [
      { id: "A", text: "O fim completo da produção de açúcar" },
      { id: "B", text: "Uma decisão aleatória, sem nenhuma relação econômica" },
      { id: "C", text: "A importância crescente da região das minas e a necessidade de um porto mais próximo para escoar o ouro" },
      { id: "D", text: "O abandono total da região Nordeste" },
    ],
    correctAnswer: "C",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "Por que o \"ciclo do ouro\" é considerado um período importante na história econômica e social do Brasil colonial?",
    tip: "Pensa em tudo que você estudou até aqui: migração, impostos, cidades crescendo!",
    funFact: "O \"ciclo do ouro\" é considerado um dos períodos mais ricos e importantes de toda a história colonial brasileira!",
    points: 1,
    options: [
      { id: "A", text: "Porque, durante o século XVIII, o ouro se tornou a principal riqueza da colônia, atraindo migração, urbanização e criando tensões com a Coroa" },
      { id: "B", text: "Porque o ouro nunca teve nenhuma importância econômica" },
      { id: "C", text: "Porque não houve nenhuma migração durante esse período" },
      { id: "D", text: "Porque o ouro foi descoberto apenas no século XX" },
    ],
    correctAnswer: "A",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Comparando o \"ciclo do açúcar\" com o \"ciclo do ouro\", qual foi uma diferença importante entre essas duas fases econômicas?",
    tip: "Lembra do simulado anterior sobre a economia açucareira e onde ela se concentrava!",
    funFact: "Essa mudança do litoral para o interior ajudou a expandir ainda mais a ocupação do território brasileiro!",
    points: 1,
    options: [
      { id: "A", text: "Os dois ciclos ocorreram exatamente na mesma região e no mesmo século" },
      { id: "B", text: "O ciclo do açúcar se concentrou principalmente no litoral nordestino; o ciclo do ouro, no interior, especialmente em Minas Gerais" },
      { id: "C", text: "Nenhum dos dois ciclos envolveu mão de obra escravizada" },
      { id: "D", text: "O ciclo do ouro ocorreu antes do ciclo do açúcar" },
    ],
    correctAnswer: "B",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Por que a descoberta de ouro em Minas Gerais provocou uma intensa migração de pessoas para a região, incluindo de outras partes do Brasil e de Portugal?",
    tip: "Lembra da questão 2 e 3 deste simulado sobre a \"corrida do ouro\"!",
    funFact: "Essa migração foi tão intensa que algumas cidades mineradoras cresceram muito mais rápido do que outras cidades coloniais mais antigas!",
    points: 1,
    options: [
      { id: "A", text: "Porque ninguém tinha interesse em enriquecer rapidamente" },
      { id: "B", text: "Porque a região já estava completamente povoada antes da descoberta" },
      { id: "C", text: "Porque o ouro não tinha nenhum valor comercial" },
      { id: "D", text: "Porque a possibilidade de enriquecimento rápido através da extração de ouro atraiu grande quantidade de pessoas em busca de oportunidades" },
    ],
    correctAnswer: "D",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "Se a Coroa portuguesa criou o \"quinto\" para cobrar uma parte do ouro extraído, o que isso revela sobre o interesse português na exploração mineradora?",
    tip: "Lembra da questão 5 deste simulado sobre o que era o quinto!",
    funFact: "A cobrança de impostos sobre riquezas coloniais, como o quinto, era uma das principais formas de Portugal se beneficiar economicamente de suas colônias!",
    points: 1,
    options: [
      { id: "A", text: "Que Portugal não tinha nenhum interesse econômico na mineração" },
      { id: "B", text: "Que o ouro era doado inteiramente aos mineradores, sem nenhuma cobrança" },
      { id: "C", text: "Que a Coroa buscava garantir uma parte significativa da riqueza gerada pela mineração através de impostos" },
      { id: "D", text: "Que o quinto nunca foi realmente cobrado" },
    ],
    correctAnswer: "C",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "Por que as Casas de Fundição foram criadas como parte do controle português sobre o ouro extraído?",
    tip: "Lembra da questão 6 deste simulado sobre a função das Casas de Fundição!",
    funFact: "Esse processo ajudava a Coroa a saber exatamente quanto ouro estava sendo extraído e quanto imposto deveria ser pago!",
    points: 1,
    options: [
      { id: "A", text: "Para produzir açúcar nas regiões de mineração" },
      { id: "B", text: "Para fundir o ouro em barras já com o imposto cobrado, facilitando o controle da Coroa sobre a produção e circulação do metal" },
      { id: "C", text: "Para ensinar técnicas de agricultura aos mineradores" },
      { id: "D", text: "Para proibir totalmente a extração de ouro" },
    ],
    correctAnswer: "B",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Comparando a sociedade formada ao redor da mineração com a sociedade dos engenhos de açúcar, qual foi uma semelhança entre elas?",
    tip: "Lembra do simulado anterior sobre escravidão e sua relação com diferentes atividades econômicas!",
    funFact: "Essa dependência da mão de obra escravizada é uma triste semelhança entre praticamente todos os \"ciclos\" econômicos do Brasil colonial!",
    points: 1,
    options: [
      { id: "A", text: "Ambas dependiam fortemente do trabalho forçado de pessoas escravizadas para sustentar a atividade econômica principal" },
      { id: "B", text: "As duas sociedades não tinham nenhuma relação com trabalho escravizado" },
      { id: "C", text: "Nenhuma das duas sociedades teve qualquer tipo de desigualdade social" },
      { id: "D", text: "As duas sociedades eram organizadas de forma totalmente igualitária" },
    ],
    correctAnswer: "A",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "Por que cidades como Ouro Preto se tornaram importantes centros de arte e arquitetura durante o período da mineração?",
    tip: "Lembra da questão 7 deste simulado sobre a arte barroca das cidades mineradoras!",
    funFact: "Hoje, Ouro Preto é reconhecida pela UNESCO como Patrimônio Cultural da Humanidade, justamente por essa riqueza artística!",
    points: 1,
    options: [
      { id: "A", text: "Porque a riqueza gerada pelo ouro não tinha nenhuma relação com investimentos culturais" },
      { id: "B", text: "Porque não havia nenhum interesse artístico na região das minas" },
      { id: "C", text: "Porque as cidades mineradoras eram proibidas de ter qualquer tipo de construção" },
      { id: "D", text: "Porque a riqueza gerada pela mineração permitiu investimentos em igrejas, esculturas e outras obras de arte, como as atribuídas a Aleijadinho" },
    ],
    correctAnswer: "D",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "Se muitos mineradores consideravam excessiva a cobrança de impostos como o quinto, que tipo de consequência social e política isso poderia gerar?",
    tip: "Lembra da questão 8 deste simulado sobre o descontentamento com os impostos!",
    funFact: "Esse tipo de tensão sobre impostos vai aparecer com ainda mais força em movimentos estudados no próximo bimestre, como a Inconfidência Mineira!",
    points: 1,
    options: [
      { id: "A", text: "Concordância total e pacífica com qualquer decisão da Coroa" },
      { id: "B", text: "Nenhuma consequência, já que ninguém se incomodava com os impostos" },
      { id: "C", text: "Tensões e conflitos entre a população mineradora e a Coroa portuguesa, descontente com a carga tributária" },
      { id: "D", text: "O fim imediato de qualquer cobrança de impostos" },
    ],
    correctAnswer: "C",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "Por que a transferência da capital colonial para o Rio de Janeiro, em 1763, está relacionada à importância da região mineradora?",
    tip: "Lembra da questão 9 deste simulado sobre essa transferência de capital!",
    funFact: "Essa mudança de capital mostra como a geografia econômica influenciava diretamente decisões políticas e administrativas na colônia!",
    points: 1,
    options: [
      { id: "A", text: "Porque o Rio de Janeiro era um porto mais próximo e estratégico para escoar o ouro extraído em Minas Gerais" },
      { id: "B", text: "Porque Salvador deixou de existir como cidade" },
      { id: "C", text: "Porque a região das minas não tinha nenhuma importância econômica" },
      { id: "D", text: "Porque a decisão não teve nenhuma relação com a economia do ouro" },
    ],
    correctAnswer: "A",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "Comparando o início da colonização (focada no litoral) com o período da mineração, qual foi uma mudança importante na ocupação do território?",
    tip: "Lembra de tudo que estudamos sobre a formação territorial do Brasil, com a expansão para o interior!",
    funFact: "Esse movimento de ocupação do interior, impulsionado pelo ouro, ajuda a explicar por que o Brasil é hoje um país tão grande!",
    points: 1,
    options: [
      { id: "A", text: "A mineração não provocou nenhuma mudança na ocupação territorial" },
      { id: "B", text: "A mineração intensificou a ocupação do interior do Brasil, especialmente em Minas Gerais, ampliando a presença portuguesa para além do litoral" },
      { id: "C", text: "O litoral deixou de ser ocupado após a descoberta do ouro" },
      { id: "D", text: "A mineração ocorreu exclusivamente no litoral brasileiro" },
    ],
    correctAnswer: "B",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "Por que entender o \"ciclo do ouro\" é importante para compreender a formação social e econômica do Brasil colonial no século XVIII?",
    tip: "Pensa em tudo que você revisou neste simulado sobre o ciclo do ouro!",
    funFact: "Esse período é considerado uma das fases mais estudadas e marcantes de toda a história do Brasil colonial!",
    points: 1,
    options: [
      { id: "A", text: "Porque esse ciclo não teve nenhuma relevância histórica" },
      { id: "B", text: "Porque o ouro nunca foi extraído no Brasil" },
      { id: "C", text: "Porque esse período não envolveu nenhuma mudança social" },
      { id: "D", text: "Porque esse período trouxe migração intensa, urbanização, desenvolvimento cultural e tensões entre colonos e a Coroa, moldando profundamente essa fase da história brasileira" },
    ],
    correctAnswer: "D",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Bernardo está estudando um mapa da região das Minas Gerais durante o século XVIII e percebe uma grande concentração de povoados próximos às áreas de extração de ouro. O que ele pode concluir sobre esse período?",
    tip: "Lembra da questão 2, 3 e 12 deste simulado sobre a migração provocada pela descoberta do ouro!",
    funFact: "Vários desses antigos povoados mineradores se tornaram cidades históricas importantes, preservadas até hoje!",
    points: 1,
    options: [
      { id: "A", text: "Que a descoberta do ouro provocou intensa migração e ocupação dessa região do interior do Brasil" },
      { id: "B", text: "Que a região nunca foi povoada durante o período colonial" },
      { id: "C", text: "Que não existia nenhuma relação entre ouro e ocupação territorial" },
      { id: "D", text: "Que a mineração ocorreu apenas no litoral brasileiro" },
    ],
    correctAnswer: "A",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Na aula de História, Bernardo aprende sobre o \"quinto\", imposto cobrado pela Coroa portuguesa sobre o ouro extraído. Qual explicação ele deve dar sobre esse imposto em um trabalho escolar?",
    tip: "Lembra da questão 5 e 13 deste simulado sobre o que era o quinto!",
    funFact: "Esse tipo de imposto sobre riquezas minerais ainda existe hoje em muitos países, embora com outros nomes e regras!",
    points: 1,
    options: [
      { id: "A", text: "O quinto era um imposto sobre a produção de açúcar" },
      { id: "B", text: "O quinto nunca foi realmente cobrado" },
      { id: "C", text: "O quinto era a cobrança de uma parte do ouro extraído pela Coroa portuguesa, como forma de arrecadação" },
      { id: "D", text: "O quinto proibia totalmente a extração de ouro" },
    ],
    correctAnswer: "C",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Bernardo descobre que muitos mineradores ficavam descontentes com a cobrança de impostos como o quinto. O que isso demonstra sobre a relação entre a população mineradora e a Coroa portuguesa?",
    tip: "Lembra da questão 8 e 17 deste simulado sobre esse descontentamento!",
    funFact: "Esse tipo de tensão sobre impostos é um tema recorrente em praticamente toda a história, até os dias atuais!",
    points: 1,
    options: [
      { id: "A", text: "Que havia total concordância e harmonia entre os dois grupos" },
      { id: "B", text: "Que existiam tensões e conflitos relacionados à carga tributária imposta pela Coroa sobre a produção de ouro" },
      { id: "C", text: "Que a Coroa nunca cobrou nenhum imposto" },
      { id: "D", text: "Que os mineradores nunca se importaram com os impostos" },
    ],
    correctAnswer: "B",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Durante uma visita a Ouro Preto, Bernardo se impressiona com as igrejas e esculturas barrocas da cidade. Qual explicação ele pode dar sobre a origem dessa riqueza artística?",
    tip: "Lembra da questão 7 e 16 deste simulado sobre a arte barroca das cidades mineradoras!",
    funFact: "Muitas dessas obras de arte levaram anos, até décadas, para serem concluídas, mostrando o nível de investimento feito na época!",
    points: 1,
    options: [
      { id: "A", text: "A riqueza gerada pela extração de ouro permitiu investimentos em arte e arquitetura, incluindo obras atribuídas a Aleijadinho" },
      { id: "B", text: "As igrejas foram construídas sem nenhum recurso econômico" },
      { id: "C", text: "A cidade nunca teve nenhuma relação com a mineração" },
      { id: "D", text: "A arte barroca não tinha nenhuma relação com a riqueza da região" },
    ],
    correctAnswer: "A",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Bernardo pesquisa sobre a transferência da capital colonial de Salvador para o Rio de Janeiro, em 1763. Qual explicação ele deve usar para esse acontecimento?",
    tip: "Lembra da questão 9 e 18 deste simulado sobre essa transferência de capital!",
    funFact: "Essa decisão também ajudava a Coroa a fiscalizar mais de perto o comércio e o transporte do ouro extraído!",
    points: 1,
    options: [
      { id: "A", text: "A decisão não teve nenhuma relação com a economia do ouro" },
      { id: "B", text: "Salvador deixou de existir como cidade" },
      { id: "C", text: "A região das minas não tinha nenhuma importância para a Coroa" },
      { id: "D", text: "O Rio de Janeiro, por ser um porto mais próximo e estratégico para escoar o ouro de Minas Gerais, ganhou importância, levando à transferência da capital" },
    ],
    correctAnswer: "D",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Bernardo organiza um resumo sobre a mão de obra utilizada na extração de ouro em Minas Gerais. Qual frase resume corretamente essa informação?",
    tip: "Lembra da questão 4 e 15 deste simulado sobre a mão de obra nas minas!",
    funFact: "O trabalho de extração de ouro, feito de forma manual e por pessoas escravizadas, era extremamente desgastante e perigoso!",
    points: 1,
    options: [
      { id: "A", text: "A extração de ouro era feita exclusivamente por máquinas" },
      { id: "B", text: "Apenas trabalhadores portugueses livres atuavam nas minas" },
      { id: "C", text: "A extração de ouro dependia fortemente de mão de obra escravizada, em grande parte de origem africana" },
      { id: "D", text: "Não havia nenhum tipo de trabalho humano envolvido na mineração" },
    ],
    correctAnswer: "C",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Na prova, Bernardo precisa comparar o ciclo do açúcar com o ciclo do ouro em termos de localização geográfica. Qual é a resposta correta?",
    tip: "Lembra da questão 11 e 19 deste simulado sobre essa comparação geográfica!",
    funFact: "Essa mudança de região também ajudou a formar a identidade cultural própria de Minas Gerais, diferente do Nordeste açucareiro!",
    points: 1,
    options: [
      { id: "A", text: "Os dois ciclos ocorreram exatamente na mesma região" },
      { id: "B", text: "O ciclo do açúcar se concentrou no litoral nordestino; o ciclo do ouro, no interior, especialmente em Minas Gerais" },
      { id: "C", text: "O ciclo do ouro ocorreu apenas no litoral" },
      { id: "D", text: "O ciclo do açúcar ocorreu apenas no interior do Brasil" },
    ],
    correctAnswer: "B",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Bernardo quer explicar por que o \"ciclo do ouro\" é considerado tão importante para entender o Brasil colonial do século XVIII. Qual explicação ele deve usar?",
    tip: "Lembra da questão 10 e 20 deste simulado sobre a importância do ciclo do ouro!",
    funFact: "Esse tema vai se conectar diretamente com o próximo simulado, sobre as revoltas coloniais que surgiram nesse período!",
    points: 1,
    options: [
      { id: "A", text: "Porque esse período não trouxe nenhuma mudança para a colônia" },
      { id: "B", text: "Porque o ouro nunca foi extraído de fato no Brasil" },
      { id: "C", text: "Porque esse período não teve nenhuma relação com migração ou urbanização" },
      { id: "D", text: "Porque esse período trouxe intensa migração, urbanização, desenvolvimento artístico e tensões entre colonos e a Coroa, moldando profundamente essa fase histórica" },
    ],
    correctAnswer: "D",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Para seu resumo final sobre a mineração e a sociedade do ouro, Bernardo escreve: \"O ciclo do ouro transformou profundamente a ocupação do território, a economia e a sociedade do Brasil colonial no século XVIII.\" Essa afirmação está:",
    tip: "Pensa em tudo que você revisou neste simulado: migração, impostos, arte, mudança de capital!",
    funFact: "Esse é considerado um dos períodos de maior transformação social e econômica de toda a história colonial brasileira!",
    points: 1,
    options: [
      { id: "A", text: "Correta, pois a descoberta do ouro gerou migração, urbanização, riqueza cultural e também tensões entre colonos e a Coroa portuguesa" },
      { id: "B", text: "Errada, o ouro nunca foi encontrado no Brasil colonial" },
      { id: "C", text: "Errada, a mineração não teve nenhuma relação com a sociedade da época" },
      { id: "D", text: "Errada, apenas o litoral foi afetado pela descoberta do ouro" },
    ],
    correctAnswer: "A",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Bernardo conclui seu caderno de estudos destacando que \"entender o ciclo do ouro ajuda a entender também a importância histórica de cidades como Ouro Preto e a transferência da capital colonial para o Rio de Janeiro.\" Essa conclusão está:",
    tip: "Pensa em tudo que você revisou sobre Ouro Preto e a transferência da capital para o Rio!",
    funFact: "Esse legado do ciclo do ouro ainda pode ser visto hoje em diversas cidades históricas de Minas Gerais, preservadas como patrimônio cultural!",
    points: 1,
    options: [
      { id: "A", text: "Errada, o ciclo do ouro não tem relação com nenhuma cidade brasileira" },
      { id: "B", text: "Errada, a capital colonial nunca foi transferida" },
      { id: "C", text: "Correta, pois a riqueza da mineração moldou cidades históricas e influenciou decisões administrativas importantes, como a mudança da capital" },
      { id: "D", text: "Correta, mas apenas para a região Sul do Brasil" },
    ],
    correctAnswer: "C",
  },
];
