export const questoesEducacaoFisica7AnoB1Av2 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "O atletismo é considerado um esporte de modalidades:",
    tip: "Pense em como as provas de atletismo costumam ser disputadas — cada atleta correndo, saltando ou lançando por conta própria, mesmo quando representa um time.",
    funFact: "\"Você sabia?\" — O atletismo é considerado um dos esportes mais antigos do mundo, presente desde os Jogos Olímpicos da Grécia Antiga!",
    points: 1,
    options: [
      { id: "A", text: "Apenas coletivas" },
      { id: "B", text: "Apenas aquáticas" },
      { id: "C", text: "Apenas com bola" },
      { id: "D", text: "Individuais (cada atleta compete por si)" },
    ],
    correctAnswer: "D",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "A prova de corrida mais curta e rápida do atletismo, como os 100 metros, é chamada de corrida de:",
    tip: "Pense na característica principal dessa prova — ela dura poucos segundos e exige explosão física.",
    funFact: "\"Você sabia?\" — O recorde mundial dos 100 metros rasos é de pouco menos de 9,6 segundos, estabelecido por Usain Bolt!",
    points: 1,
    options: [
      { id: "A", text: "Fundo" },
      { id: "B", text: "Velocidade" },
      { id: "C", text: "Revezamento" },
      { id: "D", text: "Obstáculos" },
    ],
    correctAnswer: "B",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "A prova em que o atleta corre uma longa distância, como a maratona, é chamada de corrida de:",
    tip: "Pense no oposto da corrida de velocidade — uma prova bem mais longa, que exige resistência física.",
    funFact: "\"Você sabia?\" — A maratona tem 42,195 km e sua distância tem origem em uma lenda da Grécia Antiga, sobre um soldado que correu para avisar sobre uma vitória!",
    points: 1,
    options: [
      { id: "A", text: "Fundo" },
      { id: "B", text: "Velocidade" },
      { id: "C", text: "Salto" },
      { id: "D", text: "Lançamento" },
    ],
    correctAnswer: "A",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "A prova de corrida em que vários atletas de um time se revezam carregando um bastão é chamada de:",
    tip: "Pense na palavra que descreve a troca entre os corredores, passando um bastão de mão em mão.",
    funFact: "\"Você sabia?\" — A prova de revezamento 4x100 metros é uma das mais emocionantes do atletismo, pois qualquer erro na passagem do bastão pode custar a vitória!",
    points: 1,
    options: [
      { id: "A", text: "Corrida de velocidade apenas" },
      { id: "B", text: "Corrida de obstáculos" },
      { id: "C", text: "Revezamento" },
      { id: "D", text: "Maratona" },
    ],
    correctAnswer: "C",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "A prova em que o atleta precisa saltar o mais longe possível, a partir de uma corrida de aproximação, é chamada de salto em:",
    tip: "Pense no objetivo principal dessa prova: não é saltar alto, mas sim saltar o mais longe possível.",
    funFact: "\"Você sabia?\" — No salto em distância, o atleta pode correr mais de 40 metros antes de saltar, ganhando velocidade para o impulso final!",
    points: 1,
    options: [
      { id: "A", text: "Altura" },
      { id: "B", text: "Distância" },
      { id: "C", text: "Vara" },
      { id: "D", text: "Triplo" },
    ],
    correctAnswer: "B",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "A prova em que o atleta usa uma vara flexível para se impulsionar e superar uma barra bem alta é chamada de salto com:",
    tip: "Pense no objeto especial usado nessa prova para ajudar o atleta a ganhar altura — ele dá o nome da modalidade.",
    funFact: "\"Você sabia?\" — Atletas de salto com vara podem superar barras de mais de 6 metros de altura, usando a flexibilidade da vara para ganhar impulso!",
    points: 1,
    options: [
      { id: "A", text: "Obstáculos" },
      { id: "B", text: "Distância" },
      { id: "C", text: "Altura simples" },
      { id: "D", text: "Vara" },
    ],
    correctAnswer: "D",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "A prova em que o atleta precisa saltar o mais alto possível, superando uma barra, sem usar vara, é chamada de salto em:",
    tip: "Pense no nome da prova que tem como objetivo principal superar uma barra, usando apenas o próprio corpo, sem nenhum objeto de apoio.",
    funFact: "\"Você sabia?\" — A técnica mais usada atualmente no salto em altura é o 'Fosbury Flop', em que o atleta salta de costas para a barra!",
    points: 1,
    options: [
      { id: "A", text: "Distância" },
      { id: "B", text: "Vara" },
      { id: "C", text: "Altura" },
      { id: "D", text: "Triplo apenas" },
    ],
    correctAnswer: "C",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "O lançamento de um objeto comprido e pontudo, parecido com uma lança, é chamado de lançamento de:",
    tip: "Pense no formato do objeto — comprido e pontudo, parecido com uma lança usada antigamente.",
    funFact: "\"Você sabia?\" — O lançamento de dardo tem origem em práticas militares antigas, quando soldados treinavam a precisão com lanças!",
    points: 1,
    options: [
      { id: "A", text: "Dardo" },
      { id: "B", text: "Disco" },
      { id: "C", text: "Peso" },
      { id: "D", text: "Martelo" },
    ],
    correctAnswer: "A",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "O arremesso de uma bola de metal pesada, feito com apenas uma mão, é chamado de arremesso de:",
    tip: "Pense no nome da prova que já descreve o próprio objeto: uma bola bem pesada.",
    funFact: "\"Você sabia?\" — A bola usada no arremesso de peso pode pesar mais de 7 kg na categoria masculina adulta!",
    points: 1,
    options: [
      { id: "A", text: "Dardo" },
      { id: "B", text: "Disco" },
      { id: "C", text: "Martelo" },
      { id: "D", text: "Peso" },
    ],
    correctAnswer: "D",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "O lançamento de um objeto redondo e achatado, feito com um movimento de giro do corpo, é chamado de lançamento de:",
    tip: "Pense no formato do objeto — redondo e achatado, bem diferente do dardo comprido ou da bola de peso.",
    funFact: "\"Você sabia?\" — O lançamento de disco é uma das provas mais antigas do atletismo, já disputada nos primeiros Jogos Olímpicos da Grécia Antiga!",
    points: 1,
    options: [
      { id: "A", text: "Dardo" },
      { id: "B", text: "Disco" },
      { id: "C", text: "Peso" },
      { id: "D", text: "Martelo" },
    ],
    correctAnswer: "B",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Um atleta corre os 100 metros rasos em poucos segundos, usando toda a sua força explosiva no início da prova. Essa prova é classificada como corrida de:",
    tip: "Pense na característica 'explosiva e rápida' descrita na questão — essa é a marca dessa modalidade de corrida.",
    funFact: "\"Você sabia?\" — Os atletas de velocidade costumam ter um tipo de fibra muscular diferente dos corredores de longa distância, mais voltada para explosão!",
    points: 1,
    options: [
      { id: "A", text: "Velocidade" },
      { id: "B", text: "Fundo" },
      { id: "C", text: "Revezamento" },
      { id: "D", text: "Meio-fundo apenas" },
    ],
    correctAnswer: "A",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Durante uma corrida de revezamento 4x100 metros, o momento mais delicado e treinado da prova é a:",
    tip: "Pense no momento em que um corredor passa o bastão para o próximo — isso precisa ser muito bem treinado para não perder tempo.",
    funFact: "\"Você sabia?\" — Times de revezamento treinam a passagem do bastão por meses, pois um erro nesse momento pode desclassificar a equipe inteira!",
    points: 1,
    options: [
      { id: "A", text: "Largada apenas" },
      { id: "B", text: "Chegada apenas" },
      { id: "C", text: "Passagem do bastão entre os corredores" },
      { id: "D", text: "Contagem de voltas" },
    ],
    correctAnswer: "C",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "Um atleta corre uma distância bem longa, como 5 ou 10 quilômetros, controlando o ritmo da respiração ao longo de toda a prova. Essa prova é chamada de corrida de:",
    tip: "Pense na prova de longa distância, que exige resistência e controle de ritmo, diferente da corrida explosiva de velocidade.",
    funFact: "\"Você sabia?\" — Corredores de fundo costumam treinar a respiração de forma especial, aprendendo a controlar o ar durante toda a prova!",
    points: 1,
    options: [
      { id: "A", text: "Velocidade" },
      { id: "B", text: "Obstáculos" },
      { id: "C", text: "Revezamento" },
      { id: "D", text: "Fundo" },
    ],
    correctAnswer: "D",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "No salto em distância, o atleta corre em uma pista de aproximação e depois impulsiona o corpo para frente, caindo em uma:",
    tip: "Pense no local especial onde o atleta cai depois do salto, projetado para amortecer a queda com segurança.",
    funFact: "\"Você sabia?\" — A areia da caixa de salto é constantemente revirada entre as tentativas, para garantir uma aterrissagem segura para o próximo atleta!",
    points: 1,
    options: [
      { id: "A", text: "Piscina" },
      { id: "B", text: "Caixa de areia" },
      { id: "C", text: "Pista de atletismo apenas" },
      { id: "D", text: "Quadra de vôlei" },
    ],
    correctAnswer: "B",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "No salto em altura, o atleta costuma usar uma técnica chamada 'Fosbury Flop', em que ele salta de costas para a barra. Essa técnica revolucionou essa modalidade porque permitiu:",
    tip: "Pense no motivo pelo qual essa técnica se popularizou tanto — ela ajudou os atletas a superar barras ainda mais altas.",
    funFact: "\"Você sabia?\" — Essa técnica foi criada pelo atleta americano Dick Fosbury, que a usou pela primeira vez nas Olimpíadas de 1968!",
    points: 1,
    options: [
      { id: "A", text: "Saltar com menos esforço" },
      { id: "B", text: "Usar uma vara" },
      { id: "C", text: "Alcançar alturas maiores de forma mais eficiente" },
      { id: "D", text: "Correr mais rápido" },
    ],
    correctAnswer: "C",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "No lançamento de dardo, o atleta corre antes de lançar o objeto o mais longe possível. Essa corrida de aproximação ajuda a:",
    tip: "Pense no motivo físico pelo qual correr antes de lançar algo ajuda a jogá-lo mais longe — tem a ver com velocidade acumulada.",
    funFact: "\"Você sabia?\" — A corrida de aproximação no dardo pode chegar a mais de 30 metros antes do atleta soltar o objeto!",
    points: 1,
    options: [
      { id: "A", text: "Aumentar a força e a velocidade do lançamento" },
      { id: "B", text: "Diminuir a distância do lançamento" },
      { id: "C", text: "Confundir os adversários" },
      { id: "D", text: "Nenhuma vantagem real" },
    ],
    correctAnswer: "A",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "No arremesso de peso, diferente do lançamento de dardo e disco, o movimento é feito:",
    tip: "Pense na diferença entre 'lançar' (dardo, disco) e 'empurrar' (peso) — o arremesso de peso é feito com um movimento de empurrão a partir do ombro.",
    funFact: "\"Você sabia?\" — A técnica correta do arremesso de peso usa a rotação do corpo inteiro, não só a força do braço, para alcançar distâncias maiores!",
    points: 1,
    options: [
      { id: "A", text: "Com os dois braços ao mesmo tempo" },
      { id: "B", text: "Com apenas um braço, empurrando o peso a partir do ombro" },
      { id: "C", text: "Com os pés apenas" },
      { id: "D", text: "Com uma vara de apoio" },
    ],
    correctAnswer: "B",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "No salto com vara, quanto mais flexível e bem controlada for a vara durante a impulsão, maior é a chance de o atleta:",
    tip: "Pense no objetivo principal dessa prova — usar bem a vara ajuda o atleta a alcançar exatamente esse resultado.",
    funFact: "\"Você sabia?\" — As varas usadas atualmente são feitas de fibra de vidro ou carbono, bem mais flexíveis do que as varas de bambu usadas no passado!",
    points: 1,
    options: [
      { id: "A", text: "Cair fora da área de aterrissagem" },
      { id: "B", text: "Perder o equilíbrio na corrida" },
      { id: "C", text: "Desclassificar a prova" },
      { id: "D", text: "Superar barras mais altas" },
    ],
    correctAnswer: "D",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "Em uma prova de corrida de velocidade, a reação rápida do atleta ao som do tiro de largada é fundamental para um bom resultado. Essa reação rápida é chamada de:",
    tip: "Pense no nome que descreve exatamente 'o tempo que o atleta leva para reagir' ao sinal de largada.",
    funFact: "\"Você sabia?\" — Um tempo de reação muito rápido, abaixo de 0,1 segundo, é considerado tecnicamente impossível e pode até ser penalizado como falsa largada!",
    points: 1,
    options: [
      { id: "A", text: "Tempo de reação" },
      { id: "B", text: "Tempo de chegada" },
      { id: "C", text: "Revezamento" },
      { id: "D", text: "Fundo de pista" },
    ],
    correctAnswer: "A",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "No lançamento de disco, o atleta gira o corpo várias vezes antes de soltar o objeto, para ganhar:",
    tip: "Pense no motivo físico de girar o corpo antes de soltar o disco — isso acumula energia para o lançamento.",
    funFact: "\"Você sabia?\" — Os melhores lançadores de disco do mundo conseguem lançar o objeto por mais de 70 metros!",
    points: 1,
    options: [
      { id: "A", text: "Apenas altura" },
      { id: "B", text: "Apenas direção certa" },
      { id: "C", text: "Mais velocidade e força no lançamento" },
      { id: "D", text: "Nenhuma vantagem" },
    ],
    correctAnswer: "C",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Bernardo participou de uma corrida de 100 metros na gincana da escola, usando toda a força logo no início da prova. Essa prova é classificada como corrida de:",
    tip: "Pense na prova rápida e explosiva, que dura poucos segundos, bem diferente de uma corrida longa.",
    funFact: "\"Você sabia?\" — Treinar sprints curtos, como os 100 metros, ajuda a melhorar a explosão muscular!",
    points: 1,
    options: [
      { id: "A", text: "Fundo" },
      { id: "B", text: "Velocidade" },
      { id: "C", text: "Revezamento" },
      { id: "D", text: "Obstáculos" },
    ],
    correctAnswer: "B",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Bernardo correu uma prova bem mais longa, de 5 quilômetros, controlando o ritmo da respiração durante todo o percurso. Essa prova é chamada de corrida de:",
    tip: "Pense na prova de longa distância, que exige resistência e controle de ritmo ao longo de todo o percurso.",
    funFact: "\"Você sabia?\" — Correr longas distâncias ajuda bastante a fortalecer o coração e os pulmões!",
    points: 1,
    options: [
      { id: "A", text: "Velocidade" },
      { id: "B", text: "Obstáculos" },
      { id: "C", text: "Revezamento" },
      { id: "D", text: "Fundo" },
    ],
    correctAnswer: "D",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Bernardo participou de uma corrida de revezamento com seus colegas de turma, passando um bastão de mão em mão. Como se chama essa prova?",
    tip: "Pense no nome da prova em que vários corredores de um time se revezam, carregando um bastão.",
    funFact: "\"Você sabia?\" — A passagem do bastão precisa ser feita dentro de uma zona especial da pista, chamada 'zona de transferência'!",
    points: 1,
    options: [
      { id: "A", text: "Revezamento" },
      { id: "B", text: "Maratona" },
      { id: "C", text: "Salto em distância" },
      { id: "D", text: "Lançamento de dardo" },
    ],
    correctAnswer: "A",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Bernardo tentou o salto em distância na aula de educação física, correndo e depois impulsionando o corpo para caírem uma área especial. Onde ele caiu?",
    tip: "Pense no local especial, com uma superfície mais fofa, projetado para amortecer a queda do atleta depois do salto.",
    funFact: "\"Você sabia?\" — A areia dessa caixa precisa ser revirada regularmente para ficar sempre fofa e segura para os saltos!",
    points: 1,
    options: [
      { id: "A", text: "Em uma piscina" },
      { id: "B", text: "Em uma pista comum" },
      { id: "C", text: "Em uma caixa de areia" },
      { id: "D", text: "Em uma quadra de vôlei" },
    ],
    correctAnswer: "C",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Bernardo tentou o salto em altura, superando uma barra sem usar vara nenhuma. Qual modalidade de atletismo ele praticou?",
    tip: "Pense no nome da modalidade descrita na própria questão: superar uma barra, sem usar nenhum objeto de apoio.",
    funFact: "\"Você sabia?\" — A técnica mais usada hoje nessa prova é saltar de costas para a barra, chamada 'Fosbury Flop'!",
    points: 1,
    options: [
      { id: "A", text: "Salto com vara" },
      { id: "B", text: "Salto triplo" },
      { id: "C", text: "Salto em distância" },
      { id: "D", text: "Salto em altura" },
    ],
    correctAnswer: "D",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Bernardo arremessou uma bola pesada de metal usando apenas um braço, empurrando-a a partir do ombro. Qual modalidade ele praticou?",
    tip: "Pense no movimento de 'empurrar' descrito na questão, bem diferente de 'lançar' como no dardo ou no disco.",
    funFact: "\"Você sabia?\" — A técnica correta usa a rotação do corpo inteiro, não só a força do braço, para alcançar mais distância!",
    points: 1,
    options: [
      { id: "A", text: "Lançamento de dardo" },
      { id: "B", text: "Arremesso de peso" },
      { id: "C", text: "Lançamento de disco" },
      { id: "D", text: "Salto com vara" },
    ],
    correctAnswer: "B",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Bernardo girou o corpo várias vezes antes de soltar um objeto redondo e achatado durante a aula de atletismo. Qual modalidade ele praticou?",
    tip: "Pense no formato do objeto descrito — redondo e achatado, diferente da lança do dardo ou da bola do peso.",
    funFact: "\"Você sabia?\" — Essa modalidade já era disputada na Grécia Antiga, há mais de 2.700 anos!",
    points: 1,
    options: [
      { id: "A", text: "Lançamento de dardo" },
      { id: "B", text: "Arremesso de peso" },
      { id: "C", text: "Lançamento de disco" },
      { id: "D", text: "Salto em altura" },
    ],
    correctAnswer: "C",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Bernardo treinou sua reação rápida ao som do apito para começar a corrida de velocidade o mais rápido possível. Como se chama essa reação rápida?",
    tip: "Pense no nome que descreve exatamente 'o tempo que o atleta leva para reagir' a um sinal de largada.",
    funFact: "\"Você sabia?\" — Treinar o tempo de reação pode fazer uma diferença enorme no resultado final de uma corrida de velocidade!",
    points: 1,
    options: [
      { id: "A", text: "Tempo de reação" },
      { id: "B", text: "Tempo de chegada" },
      { id: "C", text: "Revezamento" },
      { id: "D", text: "Fundo de pista" },
    ],
    correctAnswer: "A",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Bernardo lançou um objeto comprido e pontudo, parecido com uma lança, durante a aula de atletismo. Qual modalidade ele praticou?",
    tip: "Pense no formato comprido e pontudo do objeto, parecido com uma lança usada antigamente.",
    funFact: "\"Você sabia?\" — Essa modalidade tem origem em treinos militares antigos, quando soldados praticavam a precisão com lanças!",
    points: 1,
    options: [
      { id: "A", text: "Arremesso de peso" },
      { id: "B", text: "Lançamento de dardo" },
      { id: "C", text: "Lançamento de disco" },
      { id: "D", text: "Salto com vara" },
    ],
    correctAnswer: "B",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Bernardo usou uma vara flexível para se impulsionar e tentar superar uma barra bem alta na aula de atletismo. Qual modalidade ele praticou?",
    tip: "Pense no objeto especial usado para ajudar o atleta a ganhar altura, que dá nome à própria modalidade.",
    funFact: "\"Você sabia?\" — Atletas profissionais de salto com vara podem superar alturas de mais de 6 metros!",
    points: 1,
    options: [
      { id: "A", text: "Salto em distância" },
      { id: "B", text: "Salto em altura simples" },
      { id: "C", text: "Arremesso de peso" },
      { id: "D", text: "Salto com vara" },
    ],
    correctAnswer: "D",
  },
];
