export const questoesGeografia8AnoB4Av2 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "O que foi o \"Neocolonialismo\", processo que ocorreu principalmente no século XIX?",
    tip: "Lembra da \"Partilha da África\" que você estudou? Pense em que direção aconteceu essa colonização — da Europa para onde?",
    funFact: "\"Você sabia?\" — O Neocolonialismo deixou marcas até hoje, como fronteiras retas em países africanos e asiáticos, desenhadas sem respeitar os povos que já viviam ali!",
    points: 1,
    options: [
      { id: "A", text: "Quando países africanos colonizaram a Europa" },
      { id: "B", text: "Quando países europeus dividiram territórios da África e da Ásia entre si" },
      { id: "C", text: "Uma nova forma de agricultura" },
      { id: "D", text: "Um tipo de dança tradicional" },
    ],
    correctAnswer: "B",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "O que é \"globalização\"?",
    tip: "Pense em como hoje é possível comprar um produto feito do outro lado do mundo, ou conversar com alguém de outro país em segundos. Isso tem a ver com o quê?",
    funFact: "\"Você sabia?\" — Graças à globalização, um celular pode ter peças fabricadas em vários países diferentes antes de chegar às nossas mãos!",
    points: 1,
    options: [
      { id: "A", text: "O processo de maior integração e conexão entre países, através do comércio, tecnologia e cultura" },
      { id: "B", text: "A separação total entre os países do mundo" },
      { id: "C", text: "Um tipo de clima" },
      { id: "D", text: "Uma competição esportiva mundial" },
    ],
    correctAnswer: "A",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "O Mercosul é um exemplo de:",
    tip: "Lembra do bloco que facilita o comércio entre países vizinhos da América do Sul?",
    funFact: "\"Você sabia?\" — Graças ao Mercosul, é mais fácil para empresas brasileiras venderem produtos para a Argentina e outros países vizinhos, sem tantas taxas!",
    points: 1,
    options: [
      { id: "A", text: "Um país da América do Sul" },
      { id: "B", text: "Uma guerra histórica" },
      { id: "C", text: "Um tipo de vegetação" },
      { id: "D", text: "Um bloco econômico formado por países como Brasil, Argentina, Paraguai e Uruguai" },
    ],
    correctAnswer: "D",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "O que é \"densidade demográfica\"?",
    tip: "Pense em \"denso\" como algo \"cheio\". Que tipo de informação sobre população isso mediria?",
    funFact: "\"Você sabia?\" — Cidades como Tóquio e São Paulo têm altíssima densidade demográfica — muita gente vivendo em espaços relativamente pequenos!",
    points: 1,
    options: [
      { id: "A", text: "A altura média das pessoas" },
      { id: "B", text: "A quantidade de dinheiro de um país" },
      { id: "C", text: "A quantidade de pessoas vivendo em um determinado espaço" },
      { id: "D", text: "O tamanho de um continente" },
    ],
    correctAnswer: "C",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "O que mostra uma \"pirâmide etária\"?",
    tip: "Lembra que \"etária\" tem a ver com idade? Que tipo de informação sobre a população esse gráfico mostraria?",
    funFact: "\"Você sabia?\" — Olhando o formato da pirâmide etária, os geógrafos descobrem se um país tem mais jovens ou mais idosos!",
    points: 1,
    options: [
      { id: "A", text: "A quantidade de pessoas em cada faixa de idade de um lugar" },
      { id: "B", text: "A altura das montanhas de um país" },
      { id: "C", text: "A quantidade de prédios de uma cidade" },
      { id: "D", text: "O clima de uma região" },
    ],
    correctAnswer: "A",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "O que é \"urbanização\"?",
    tip: "Pense na palavra \"urbano\", relacionada a cidade. O que estaria crescendo?",
    funFact: "\"Você sabia?\" — Hoje, mais da metade da população mundial vive em cidades — um grande contraste com há cem anos, quando a maioria vivia no campo!",
    points: 1,
    options: [
      { id: "A", text: "O crescimento das áreas rurais" },
      { id: "B", text: "O processo de crescimento das cidades e da população urbana" },
      { id: "C", text: "A diminuição da população mundial" },
      { id: "D", text: "Um tipo de clima tropical" },
    ],
    correctAnswer: "B",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "O que é uma \"conurbação\"?",
    tip: "Lembra de cidades vizinhas tão próximas que é difícil saber onde uma termina e a outra começa?",
    funFact: "\"Você sabia?\" — A região metropolitana de São Paulo é um exemplo de conurbação, com várias cidades praticamente coladas umas nas outras!",
    points: 1,
    options: [
      { id: "A", text: "Um tipo de deserto" },
      { id: "B", text: "Uma guerra entre cidades" },
      { id: "C", text: "Um bloco econômico" },
      { id: "D", text: "Quando duas ou mais cidades crescem tanto que se misturam, formando uma área urbana só" },
    ],
    correctAnswer: "D",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "Qual é a capital dos Estados Unidos?",
    tip: "Essa cidade não é a mais famosa, mas é onde fica a Casa Branca.",
    funFact: "\"Você sabia?\" — Washington D.C. é um distrito federal especial, assim como Brasília é no Brasil!",
    points: 1,
    options: [
      { id: "A", text: "Nova York" },
      { id: "B", text: "Los Angeles" },
      { id: "C", text: "Washington D.C." },
      { id: "D", text: "Miami" },
    ],
    correctAnswer: "C",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "Qual é o maior deserto do mundo, localizado na África?",
    tip: "Esse deserto fica no norte da África e é enorme, quase do tamanho dos Estados Unidos.",
    funFact: "\"Você sabia?\" — O Saara é tão grande que poderia cobrir o Brasil inteiro e ainda sobraria espaço!",
    points: 1,
    options: [
      { id: "A", text: "Deserto de Gobi" },
      { id: "B", text: "Deserto do Saara" },
      { id: "C", text: "Deserto do Atacama" },
      { id: "D", text: "Deserto da Patagônia" },
    ],
    correctAnswer: "B",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "O que é a ONU?",
    tip: "Pense na \"grande reunião\" de quase todos os países do mundo, criada depois da Segunda Guerra Mundial.",
    funFact: "\"Você sabia?\" — A sede da ONU fica em Nova York, mas ela tem representantes em quase todos os países do mundo, incluindo o Brasil!",
    points: 1,
    options: [
      { id: "A", text: "Uma organização internacional criada para promover a paz entre os países" },
      { id: "B", text: "Um bloco econômico da América do Sul" },
      { id: "C", text: "Uma cidade dos Estados Unidos" },
      { id: "D", text: "Um tipo de vegetação africana" },
    ],
    correctAnswer: "A",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Por que o Brasil tem uma taxa de urbanização tão alta, de mais de 85%?",
    tip: "Pense em \"taxa de urbanização\" como a porcentagem de pessoas vivendo em cidades. O Brasil tem mais gente na cidade ou no campo?",
    funFact: "\"Você sabia?\" — Essa alta taxa de urbanização é resultado, entre outros fatores, do êxodo rural que aconteceu no Brasil ao longo do século XX!",
    points: 1,
    options: [
      { id: "A", text: "Porque quase ninguém mora no Brasil" },
      { id: "B", text: "Porque não existe zona rural no país" },
      { id: "C", text: "Porque a maioria dos brasileiros vive em cidades, não no campo" },
      { id: "D", text: "Porque o Brasil é o menor país do mundo" },
    ],
    correctAnswer: "C",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Por que, em muitos países em desenvolvimento, a urbanização aconteceu de forma mais desigual do que em países desenvolvidos?",
    tip: "Pense em cidades que cresceram tão rápido que não deu tempo de planejar bem a infraestrutura para todos os bairros.",
    funFact: "\"Você sabia?\" — Esse crescimento desigual é um dos motivos de problemas como falta de moradia e trânsito em algumas grandes cidades brasileiras!",
    points: 1,
    options: [
      { id: "A", text: "Porque esses países não têm nenhuma cidade" },
      { id: "B", text: "Porque todos os bairros são exatamente iguais" },
      { id: "C", text: "Porque não existe nenhum problema de infraestrutura" },
      { id: "D", text: "Porque o crescimento das cidades foi muito rápido, sem planejamento suficiente para todos" },
    ],
    correctAnswer: "D",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "O que é uma \"explosão demográfica\"?",
    tip: "Pense na palavra \"explosão\" — ela dá ideia de algo rápido e grande. O que estaria crescendo tão rápido assim?",
    funFact: "\"Você sabia?\" — O mundo viveu uma explosão demográfica no século 20, passando de 1,6 bilhão para mais de 8 bilhões de pessoas!",
    points: 1,
    options: [
      { id: "A", text: "Um terremoto muito forte" },
      { id: "B", text: "Um crescimento muito rápido e acelerado da população" },
      { id: "C", text: "A diminuição total da população de um país" },
      { id: "D", text: "Uma guerra entre países" },
    ],
    correctAnswer: "B",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "O que são os \"Grandes Lagos\", na fronteira entre Estados Unidos e Canadá?",
    tip: "Pense em um grupo de lagos tão grandes que parecem mares, localizados no norte dos EUA.",
    funFact: "\"Você sabia?\" — Os Grandes Lagos formam a maior reserva de água doce da superfície da Terra!",
    points: 1,
    options: [
      { id: "A", text: "Um conjunto de cinco enormes lagos de água doce" },
      { id: "B", text: "Um deserto gigante" },
      { id: "C", text: "Uma cordilheira de montanhas" },
      { id: "D", text: "Uma floresta tropical" },
    ],
    correctAnswer: "A",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "O Rio Nilo, um dos mais longos do mundo, está localizado em qual continente?",
    tip: "Esse rio atravessa o Egito, país que você já estudou como parte de qual continente?",
    funFact: "\"Você sabia?\" — O Rio Nilo foi fundamental para o desenvolvimento da civilização egípcia antiga, ajudando na agricultura em pleno deserto!",
    points: 1,
    options: [
      { id: "A", text: "América do Sul" },
      { id: "B", text: "Ásia" },
      { id: "C", text: "Europa" },
      { id: "D", text: "África" },
    ],
    correctAnswer: "D",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "O que foi a Guerra Fria?",
    tip: "Lembra do período histórico de forte tensão entre essas duas superpotências, mas sem batalhas diretas entre elas?",
    funFact: "\"Você sabia?\" — Durante esse período, aconteceu a corrida espacial, que levou o ser humano à Lua por primeira vez!",
    points: 1,
    options: [
      { id: "A", text: "Uma guerra com batalhas de neve no Polo Norte" },
      { id: "B", text: "Um conflito direto entre Brasil e Argentina" },
      { id: "C", text: "Um período de tensão política entre Estados Unidos e União Soviética, sem guerra direta entre eles" },
      { id: "D", text: "Uma competição esportiva mundial" },
    ],
    correctAnswer: "C",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "O que é \"gentrificação\"?",
    tip: "Pense em um bairro que \"vira moda\" e fica caro demais para quem sempre morou lá.",
    funFact: "\"Você sabia?\" — Esse processo já mudou bairros inteiros no mundo, com cafés chiques substituindo o comércio simples que existia antes!",
    points: 1,
    options: [
      { id: "A", text: "A construção de novas florestas" },
      { id: "B", text: "Quando um bairro simples fica caro e os moradores originais são afastados" },
      { id: "C", text: "Um tipo de eleição política" },
      { id: "D", text: "A criação de um novo país" },
    ],
    correctAnswer: "B",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "O que é o \"bônus demográfico\"?",
    tip: "Pense em \"bônus\" como uma vantagem. Ter muita gente podendo trabalhar pode ser bom para a economia de um país, certo?",
    funFact: "\"Você sabia?\" — O Brasil viveu seu bônus demográfico nas últimas décadas, com muitos jovens em idade de trabalhar!",
    points: 1,
    options: [
      { id: "A", text: "Quando um país tem muitas pessoas em idade de trabalhar, podendo crescer economicamente" },
      { id: "B", text: "Um prêmio dado aos países com menos habitantes" },
      { id: "C", text: "Um tipo de imposto" },
      { id: "D", text: "Uma taxa cobrada de turistas" },
    ],
    correctAnswer: "A",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "Por que a diplomacia é considerada melhor do que a guerra para resolver conflitos entre países?",
    tip: "Pense em como conversar para resolver um problema é geralmente melhor do que usar violência.",
    funFact: "\"Você sabia?\" — Muitos conflitos históricos foram resolvidos através da diplomacia, evitando guerras e salvando vidas!",
    points: 1,
    options: [
      { id: "A", text: "Porque é mais cara" },
      { id: "B", text: "Porque demora mais tempo e não resolve nada" },
      { id: "C", text: "Porque evita perdas de vidas e busca soluções duradouras através do diálogo" },
      { id: "D", text: "Porque não existe diplomacia no mundo" },
    ],
    correctAnswer: "C",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "Como a globalização pode estar relacionada a desigualdades entre países?",
    tip: "Pense em como nem todos os países conseguem as mesmas vantagens no comércio mundial.",
    funFact: "\"Você sabia?\" — Entender essa desigualdade ajuda a explicar por que algumas regiões do mundo são mais ricas que outras, mesmo estando todas conectadas pela globalização!",
    points: 1,
    options: [
      { id: "A", text: "Porque todos os países ficam igualmente ricos automaticamente" },
      { id: "B", text: "Porque ela impede qualquer tipo de comércio" },
      { id: "C", text: "Porque só existe dentro de um único país" },
      { id: "D", text: "Porque alguns países e empresas se beneficiam mais do comércio internacional do que outros" },
    ],
    correctAnswer: "D",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Bernardo lembrou que seu avô se mudou do campo para a cidade em busca de trabalho, há muitos anos. Esse movimento é chamado de:",
    tip: "Lembra da palavra que descreve a saída de pessoas do campo para morar nas cidades?",
    funFact: "\"Você sabia?\" — Esse movimento foi muito comum no Brasil entre os anos 1950 e 1980, mudando completamente a forma como vivemos hoje, majoritariamente em cidades!",
    points: 1,
    options: [
      { id: "A", text: "Globalização" },
      { id: "B", text: "Êxodo rural" },
      { id: "C", text: "Neocolonialismo" },
      { id: "D", text: "Diplomacia" },
    ],
    correctAnswer: "B",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "Bernardo quer escrever a capital dos Estados Unidos em seu mapa. A resposta certa é:",
    tip: "Lembra que essa cidade não é a maior, mas é onde fica a Casa Branca?",
    funFact: "\"Você sabia?\" — Washington D.C. recebe visitantes do mundo todo interessados em conhecer museus e monumentos históricos dos Estados Unidos!",
    points: 1,
    options: [
      { id: "A", text: "Nova York" },
      { id: "B", text: "Los Angeles" },
      { id: "C", text: "Washington D.C." },
      { id: "D", text: "Chicago" },
    ],
    correctAnswer: "C",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Bernardo assistiu a um documentário sobre leões e girafas vivendo em grandes campos abertos na África. Esse tipo de vegetação se chama:",
    tip: "Lembra da vegetação cheia de animais selvagens e árvores espalhadas que você estudou sobre a África?",
    funFact: "\"Você sabia?\" — A savana africana é um dos ecossistemas com maior diversidade de animais selvagens do mundo!",
    points: 1,
    options: [
      { id: "A", text: "Savana" },
      { id: "B", text: "Floresta temperada" },
      { id: "C", text: "Deserto" },
      { id: "D", text: "Tundra" },
    ],
    correctAnswer: "A",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "Bernardo descobriu que uma organização internacional trabalha para manter a paz entre os países desde 1945. Essa organização é:",
    tip: "Lembra da organização criada depois da Segunda Guerra Mundial, reunindo quase todos os países do mundo?",
    funFact: "\"Você sabia?\" — A ONU também cuida de outros temas importantes, como direitos humanos, saúde e meio ambiente, além da paz entre os países!",
    points: 1,
    options: [
      { id: "A", text: "O Mercosul" },
      { id: "B", text: "A NATO" },
      { id: "C", text: "O G20" },
      { id: "D", text: "A ONU" },
    ],
    correctAnswer: "D",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "Bernardo visitou duas cidades vizinhas tão próximas que pareciam uma cidade só. Isso é um exemplo de:",
    tip: "Lembra da palavra para cidades vizinhas que crescem tanto que se misturam?",
    funFact: "\"Você sabia?\" — Isso acontece em várias regiões metropolitanas do Brasil e do mundo, como a região de São Paulo!",
    points: 1,
    options: [
      { id: "A", text: "Megalópole apenas" },
      { id: "B", text: "Zona rural" },
      { id: "C", text: "Conurbação" },
      { id: "D", text: "Explosão demográfica" },
    ],
    correctAnswer: "C",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Bernardo comparou dois países: um com muitas crianças nascendo e outro com muitos idosos. Para fazer essa comparação, ele usou um gráfico chamado:",
    tip: "Lembra do gráfico que mostra a quantidade de pessoas em cada faixa de idade de um país?",
    funFact: "\"Você sabia?\" — Esse tipo de gráfico ajuda governos a planejar quantas escolas ou hospitais serão necessários no futuro!",
    points: 1,
    options: [
      { id: "A", text: "Mapa político" },
      { id: "B", text: "Pirâmide etária" },
      { id: "C", text: "Gráfico de pizza sobre o clima" },
      { id: "D", text: "Linha do tempo histórica" },
    ],
    correctAnswer: "B",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Bernardo descobriu que o Brasil faz parte de um bloco econômico com Argentina, Paraguai e Uruguai. Esse bloco é chamado de:",
    tip: "Lembra do bloco econômico da América do Sul que facilita o comércio entre esses países vizinhos?",
    funFact: "\"Você sabia?\" — Graças a esse bloco, produtos podem circular com mais facilidade entre esses países, fortalecendo a economia de toda a região!",
    points: 1,
    options: [
      { id: "A", text: "Mercosul" },
      { id: "B", text: "NATO" },
      { id: "C", text: "ONU" },
      { id: "D", text: "G20" },
    ],
    correctAnswer: "A",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "Bernardo ficou curioso sobre um muro que dividiu uma cidade da Alemanha durante a Guerra Fria. Esse muro é conhecido como:",
    tip: "Lembra do muro derrubado em 1989, que foi um símbolo do fim da Guerra Fria?",
    funFact: "\"Você sabia?\" — Hoje, pedaços desse muro são guardados em museus pelo mundo, como lembrança desse importante momento histórico!",
    points: 1,
    options: [
      { id: "A", text: "Muralha da China" },
      { id: "B", text: "Muro das Lamentações" },
      { id: "C", text: "Muro de Adriano" },
      { id: "D", text: "Muro de Berlim" },
    ],
    correctAnswer: "D",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Depois de estudar sobre conflitos mundiais, Bernardo concluiu que a melhor forma de resolver disputas entre países é através do(a):",
    tip: "Lembra da palavra que significa resolver problemas através do diálogo e da negociação, em vez da violência?",
    funFact: "\"Você sabia?\" — Parabéns, Bernardo! Você aprendeu uma lição valiosa: o diálogo é sempre o melhor caminho para resolver conflitos entre pessoas e entre países!",
    points: 1,
    options: [
      { id: "A", text: "Guerra" },
      { id: "B", text: "Diplomacia" },
      { id: "C", text: "Isolamento total entre os países" },
      { id: "D", text: "Ignorando o problema" },
    ],
    correctAnswer: "B",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Depois de revisar tudo o que aprendeu sobre geografia neste bimestre, Bernardo resumiu: \"o mundo é formado por países com populações, cidades e histórias diferentes, mas que estão cada vez mais conectados pela...\". Qual palavra completa essa frase?",
    tip: "Pense na palavra que você aprendeu logo na primeira questão desse simulado, sobre a conexão entre países através do comércio, tecnologia e cultura.",
    funFact: "\"Você sabia?\" — Parabéns, Bernardo! Você completou a revisão geral de Geografia do 8º ano, entendendo desde a população mundial até os conflitos geopolíticos — um verdadeiro especialista em geografia mundial!",
    points: 1,
    options: [
      { id: "A", text: "Guerra" },
      { id: "B", text: "Isolamento" },
      { id: "C", text: "Globalização" },
      { id: "D", text: "Ausência de comércio" },
    ],
    correctAnswer: "C",
  },
];
