export const questoesCiencias9AnoB2Av1 = [
  {
    id: 1,
    type: "multiple_choice",
    text: "A ELETRICIDADE é um fenômeno físico relacionado a:",
    tip: "Pense no que existe dentro de cada átomo e o que pode se mover livremente nos metais.",
    funFact: "\"Você Sabia?\" — A eletricidade é tão fundamental que está presente em tudo: nos neurônios que carregam pensamentos, no coração que bate com impulsos elétricos, nos raios das tempestades e nos semicondutores dos chips. O corpo humano opera com tensões de milivolts, e um raio pode chegar a 300 milhões de volts.",
    points: 1,
    options: [
      { id: "A", text: "A geração de calor por combustão de materiais condutores." },
      { id: "B", text: "O movimento das moléculas de água nos geradores hidrelétricos." },
      { id: "C", text: "O fluxo de ar quente em transformadores de alta tensão." },
      { id: "D", text: "A presença e o movimento de cargas elétricas (elétrons e prótons)." },
    ],
    correctAnswer: "D",
  },
  {
    id: 2,
    type: "multiple_choice",
    text: "Qual das afirmações sobre CARGAS ELÉTRICAS está correta?",
    tip: "Lembre da estrutura atômica: o núcleo tem prótons e nêutrons, e ao redor ficam os elétrons.",
    funFact: "\"Você Sabia?\" — A carga do elétron (1,6 × 10⁻¹⁹ C) é a menor carga elétrica livre da natureza. Um fio comum conduzindo 1 ampere de corrente tem cerca de 6 × 10¹⁸ elétrons passando por um ponto por segundo — mais do que estrelas na Via Láctea.",
    points: 1,
    options: [
      { id: "A", text: "Elétrons têm carga negativa, prótons têm carga positiva e nêutrons não têm carga." },
      { id: "B", text: "Prótons têm carga negativa e elétrons têm carga positiva." },
      { id: "C", text: "Nêutrons conduzem eletricidade e elétrons são neutros." },
      { id: "D", text: "Todos os átomos têm carga elétrica negativa por padrão." },
    ],
    correctAnswer: "A",
  },
  {
    id: 3,
    type: "multiple_choice",
    text: "Os materiais CONDUTORES elétricos são aqueles que:",
    tip: "Em metais, há elétrons 'livres' que se movem com facilidade entre os átomos.",
    funFact: "\"Você Sabia?\" — A prata é o melhor condutor elétrico natural, seguida do cobre e do ouro. O cobre é usado em fios elétricos por ser excelente condutor e relativamente barato. O grafeno (camada única de carbono) é o melhor condutor já criado — 40× mais condutor que o cobre — e pode revolucionar a eletrônica.",
    points: 1,
    options: [
      { id: "A", text: "Impedem o fluxo de elétrons, protegendo os circuitos elétricos." },
      { id: "B", text: "Armazenam cargas elétricas sem permitir seu movimento." },
      { id: "C", text: "Permitem o fluxo livre de elétrons, facilitando a passagem da corrente elétrica." },
      { id: "D", text: "Transformam energia elétrica em luz sem perda de energia." },
    ],
    correctAnswer: "C",
  },
  {
    id: 4,
    type: "multiple_choice",
    text: "A CORRENTE ELÉTRICA é definida como:",
    tip: "Corrente é o 'fluxo' de algo. O que flui nos fios elétricos?",
    funFact: "\"Você Sabia?\" — A corrente elétrica é medida em Amperes (A) em homenagem a André-Marie Ampère. Um fio doméstico típico suporta 10-20 A. O raio pode ter pico de 20.000 a 30.000 A! O coração humano para com apenas 0,1 A de corrente alternada passando por ele — por isso choques elétricos são perigosos mesmo com tensões modestas.",
    points: 1,
    options: [
      { id: "A", text: "A diferença de potencial entre dois pontos de um circuito." },
      { id: "B", text: "O fluxo ordenado de cargas elétricas (elétrons) por um condutor." },
      { id: "C", text: "A resistência que um material oferece à passagem de elétrons." },
      { id: "D", text: "A energia consumida por um aparelho elétrico por unidade de tempo." },
    ],
    correctAnswer: "B",
  },
  {
    id: 5,
    type: "multiple_choice",
    text: "A diferença entre CORRENTE CONTÍNUA (CC) e CORRENTE ALTERNADA (CA) é:",
    tip: "Contínua flui sempre na mesma direção; alternada muda de direção — com que frequência?",
    funFact: "\"Você Sabia?\" — A 'Guerra das Correntes' entre Edison (CC) e Tesla/Westinghouse (CA) no fim do século XIX determinou que a CA seria adotada mundialmente para distribuição. A CA vence em transmissão a longas distâncias (transformadores a alteram facilmente), mas baterias e eletrônica funcionam em CC — por isso carregadores de celular convertem CA em CC.",
    points: 1,
    options: [
      { id: "A", text: "A CC é mais perigosa que a CA, sendo usada apenas em laboratórios." },
      { id: "B", text: "A CA flui em uma única direção; a CC muda de direção periodicamente." },
      { id: "C", text: "A CC é usada em linhas de transmissão; a CA é usada em baterias." },
      { id: "D", text: "A CC flui em uma única direção; a CA inverte sua direção periodicamente (no Brasil, 60 vezes por segundo)." },
    ],
    correctAnswer: "D",
  },
  {
    id: 6,
    type: "multiple_choice",
    text: "A TENSÃO ELÉTRICA (voltagem) é:",
    tip: "É a 'diferença de nível' que faz os elétrons se moverem — como a diferença de altura que faz a água cair.",
    funFact: "\"Você Sabia?\" — A tensão é medida em Volts (V) em homenagem a Alessandro Volta, inventor da pilha elétrica em 1800. Uma pilha AA tem 1,5 V; um raio pode ter 300.000.000 V; a tensão das linhas de transmissão chega a 750.000 V. O coração gera tensões de 1 mV, detectáveis no eletrocardiograma (ECG).",
    points: 1,
    options: [
      { id: "A", text: "A diferença de potencial elétrico entre dois pontos de um circuito, medida em volts (V)." },
      { id: "B", text: "A quantidade de cargas elétricas que passa por um fio em um segundo." },
      { id: "C", text: "A oposição ao fluxo de corrente oferecida por um material, medida em ohms (Ω)." },
      { id: "D", text: "A força magnética gerada pela passagem de corrente elétrica em um fio." },
    ],
    correctAnswer: "A",
  },
  {
    id: 7,
    type: "multiple_choice",
    text: "A RESISTÊNCIA ELÉTRICA é:",
    tip: "Todo material 'resiste' um pouco à passagem de elétrons — uns mais, outros menos.",
    funFact: "\"Você Sabia?\" — A resistência de um fio depende do material, do comprimento (quanto mais longo, mais resistência) e da espessura (quanto mais grosso, menos resistência). O filamento de uma lâmpada incandescente tem resistência muito alta de propósito — isso o aquece até 2.500°C, tornando-o incandescente.",
    points: 1,
    options: [
      { id: "A", text: "A diferença de tensão entre a entrada e saída de um resistor." },
      { id: "B", text: "A capacidade de um material de armazenar cargas elétricas." },
      { id: "C", text: "A oposição que um material oferece à passagem de corrente elétrica, medida em ohms (Ω)." },
      { id: "D", text: "A potência dissipada como calor em um circuito elétrico." },
    ],
    correctAnswer: "C",
  },
  {
    id: 8,
    type: "multiple_choice",
    text: "A LEI DE OHM estabelece que, para um condutor ôhmico a temperatura constante:",
    tip: "Georg Ohm descobriu a relação entre V (tensão), I (corrente) e R (resistência). Qual é essa relação?",
    funFact: "\"Você Sabia?\" — Georg Ohm publicou sua lei em 1827 e foi ridicularizado pela comunidade científica alemã, que considerou o trabalho 'indigno de um professor'. Ele perdeu o emprego. Anos depois, a Royal Society de Londres premiou-o com a Medalha Copley — uma das maiores honrarias científicas. Hoje, seu nome é uma unidade fundamental.",
    points: 1,
    options: [
      { id: "A", text: "A corrente é diretamente proporcional à resistência e inversamente proporcional à tensão." },
      { id: "B", text: "A resistência é proporcional ao quadrado da corrente elétrica." },
      { id: "C", text: "A tensão é inversamente proporcional à corrente elétrica." },
      { id: "D", text: "A tensão (V) é igual ao produto da corrente (I) pela resistência (R): V = R · I." },
    ],
    correctAnswer: "D",
  },
  {
    id: 9,
    type: "multiple_choice",
    text: "Um resistor de 10 Ω é conectado a uma fonte de 30 V. Qual é a corrente que passa por ele?",
    tip: "Use I = V/R.",
    funFact: "\"Você Sabia?\" — I = 30/10 = 3 A. Esse resistor dissiparia P = V·I = 30·3 = 90 W de potência — suficiente para aquecer um cubo d'água de 90°C por segundo. A Lei de Ohm permite calcular corrente, tensão ou resistência desde que as outras duas sejam conhecidas — é a ferramenta mais usada em eletrônica.",
    points: 1,
    options: [
      { id: "A", text: "300 A" },
      { id: "B", text: "3 A" },
      { id: "C", text: "0,33 A" },
      { id: "D", text: "20 A" },
    ],
    correctAnswer: "B",
  },
  {
    id: 10,
    type: "multiple_choice",
    text: "A unidade de medida da resistência elétrica é o OHM (Ω). Essa unidade foi batizada em homenagem a:",
    tip: "Qual cientista descobriu a relação matemática entre tensão, corrente e resistência?",
    funFact: "\"Você Sabia?\" — As unidades elétricas básicas foram batizadas em homenagem a cientistas que revolucionaram a área: Volt (Volta), Ampere (Ampère), Ohm (Ohm), Watt (Watt), Coulomb (Coulomb), Farad (Faraday), Henry (Henry) e Tesla (Tesla). É como se cada fórmula elétrica tivesse o nome de seu descobridor embutido.",
    points: 1,
    options: [
      { id: "A", text: "Georg Simon Ohm, físico alemão que estabeleceu a relação entre tensão, corrente e resistência." },
      { id: "B", text: "Alessandro Volta, inventor da pilha elétrica." },
      { id: "C", text: "André-Marie Ampère, que estudou as forças entre condutores." },
      { id: "D", text: "James Watt, que calculou a potência das máquinas a vapor." },
    ],
    correctAnswer: "A",
  },
  {
    id: 11,
    type: "multiple_choice",
    text: "Um CIRCUITO ELÉTRICO básico é composto por:",
    tip: "Todo circuito precisa de três elementos essenciais para funcionar.",
    funFact: "\"Você Sabia?\" — O primeiro circuito elétrico foi criado por Alessandro Volta em 1800 com sua 'pilha voltaica' (bateria primitiva). Hoje, um chip de processador moderno contém mais de 50 bilhões de transistores em um circuito do tamanho de uma moeda. A evolução do circuito simples ao chip moderno levou apenas 200 anos.",
    points: 1,
    options: [
      { id: "A", text: "Apenas fios condutores e uma lâmpada." },
      { id: "B", text: "Um gerador, fios e pelo menos dois resistores em paralelo." },
      { id: "C", text: "Uma fonte de energia (gerador), fios condutores e receptores (como resistores ou lâmpadas)." },
      { id: "D", text: "Uma bateria, um interruptor e obrigatoriamente um fusível." },
    ],
    correctAnswer: "C",
  },
  {
    id: 12,
    type: "multiple_choice",
    text: "Em um circuito em SÉRIE, os componentes estão ligados:",
    tip: "Imagine vagões de um trem — um após o outro, em fila única.",
    funFact: "\"Você Sabia?\" — As antigas luzes de árvore de Natal usavam circuito em série: se uma lâmpada queimava, todas apagavam (havia apenas um caminho para a corrente). As luzes modernas usam circuito em paralelo — se uma apaga, as outras continuam. Um defeito frustrante se tornou uma aula de circuitos para milhões de crianças.",
    points: 1,
    options: [
      { id: "A", text: "Em ramos paralelos, de forma que cada um recebe a mesma tensão." },
      { id: "B", text: "Um após o outro, formando um único caminho para a corrente elétrica." },
      { id: "C", text: "Diretamente à fonte, sem resistores intermediários." },
      { id: "D", text: "Em grupos alternados de paralelo e série simultaneamente." },
    ],
    correctAnswer: "B",
  },
  {
    id: 13,
    type: "multiple_choice",
    text: "Em um circuito em PARALELO, os componentes estão ligados:",
    tip: "Imagine várias estradas indo ao mesmo destino — cada carro pode tomar um caminho diferente.",
    funFact: "\"Você Sabia?\" — A instalação elétrica residencial é em paralelo: cada tomada recebe a mesma tensão (127V ou 220V) independentemente dos outros aparelhos ligados. Se fosse em série, ligar mais um aparelho reduziria a corrente (e a potência) de todos os outros.",
    points: 1,
    options: [
      { id: "A", text: "Em sequência, um após o outro, formando um único caminho para a corrente." },
      { id: "B", text: "Apenas em circuitos de corrente alternada, não em corrente contínua." },
      { id: "C", text: "Com resistências iguais para garantir a mesma corrente em cada ramo." },
      { id: "D", text: "Em ramos separados, de forma que todos recebem a mesma tensão da fonte." },
    ],
    correctAnswer: "D",
  },
  {
    id: 14,
    type: "multiple_choice",
    text: "Uma vantagem do circuito em PARALELO sobre o circuito em SÉRIE é que:",
    tip: "O que acontece se um componente falhar em cada tipo de circuito?",
    funFact: "\"Você Sabia?\" — O sistema nervoso do corpo humano funciona em paralelo: se um nervo é danificado, outros nervos em rotas paralelas ainda podem transmitir sinais. A redundância dos circuitos em paralelo é usada em aviões, hospitais e servidores de internet — sistemas críticos que não podem parar.",
    points: 1,
    options: [
      { id: "A", text: "Se um componente queimar, os outros continuam funcionando, pois cada um tem seu próprio caminho de corrente." },
      { id: "B", text: "A resistência total é sempre maior que a de cada resistor isolado." },
      { id: "C", text: "A corrente é igual em todos os componentes, facilitando o controle." },
      { id: "D", text: "O consumo total de energia é sempre menor que em circuitos equivalentes em série." },
    ],
    correctAnswer: "A",
  },
  {
    id: 15,
    type: "multiple_choice",
    text: "Dois resistores de 4 Ω e 6 Ω estão em SÉRIE. Qual é a resistência equivalente?",
    tip: "Em série, as resistências se somam: Req = R1 + R2.",
    funFact: "\"Você Sabia?\" — Req = 4 + 6 = 10 Ω. Em série, a resistência total é sempre maior que qualquer resistor individual — o caminho único fica mais 'difícil'. Isso explica por que fios muito longos (comprimento = mais resistência em série) perdem mais energia como calor — problema real nas redes de distribuição elétrica.",
    points: 1,
    options: [
      { id: "A", text: "2,4 Ω" },
      { id: "B", text: "5 Ω" },
      { id: "C", text: "10 Ω" },
      { id: "D", text: "1 Ω" },
    ],
    correctAnswer: "C",
  },
  {
    id: 16,
    type: "multiple_choice",
    text: "Dois resistores iguais de 10 Ω cada estão em PARALELO. Qual é a resistência equivalente?",
    tip: "Em paralelo: 1/Req = 1/R1 + 1/R2. Para dois resistores iguais, há uma regra prática.",
    funFact: "\"Você Sabia?\" — Req = 5 Ω — metade de cada resistor! Para dois resistores iguais em paralelo, a resistência equivalente é sempre metade. Em paralelo, a resistência total é sempre MENOR que a menor resistência individual — mais caminhos = mais facilidade para a corrente passar.",
    points: 1,
    options: [
      { id: "A", text: "20 Ω" },
      { id: "B", text: "5 Ω" },
      { id: "C", text: "10 Ω" },
      { id: "D", text: "0,2 Ω" },
    ],
    correctAnswer: "B",
  },
  {
    id: 17,
    type: "multiple_choice",
    text: "A POTÊNCIA ELÉTRICA de um aparelho é definida como:",
    tip: "Potência = taxa de uso de energia. P = energia/tempo = ?",
    funFact: "\"Você Sabia?\" — P = V · I (também P = R·I² = V²/R). Um chuveiro de 5.500 W consome 5.500 joules de energia por segundo. Para comparar: um adulto em repouso metaboliza cerca de 80 W, e correndo intensamente chega a 500-1.000 W. O chuveiro consome mais energia em 10 min do que uma pessoa em um dia.",
    points: 1,
    options: [
      { id: "A", text: "A carga elétrica armazenada pela bateria em coulombs." },
      { id: "B", text: "O produto da resistência pelo quadrado da tensão." },
      { id: "C", text: "A razão entre a energia consumida e a resistência do aparelho." },
      { id: "D", text: "A taxa de transformação de energia elétrica, dada por P = V · I, medida em watts (W)." },
    ],
    correctAnswer: "D",
  },
  {
    id: 18,
    type: "multiple_choice",
    text: "A unidade de medida da potência elétrica é o WATT (W). 1 W é equivalente a:",
    tip: "Watt relaciona energia (joule) com tempo (segundo).",
    funFact: "\"Você Sabia?\" — 1 W = 1 J/s. James Watt inventou a medida de potência das máquinas a vapor no século XVIII, usando o cavalo como referência: 1 cavalo-vapor (cv) = 746 W. Assim, um motor de 100 cv tem 74.600 W. O próprio Watt calculou que um cavalo pode realizar cerca de 33.000 libras-pé de trabalho por minuto.",
    points: 1,
    options: [
      { id: "A", text: "1 joule de energia por segundo (1 W = 1 J/s)." },
      { id: "B", text: "1 volt multiplicado por 1 ohm." },
      { id: "C", text: "1 ampere de corrente por 1 ohm de resistência." },
      { id: "D", text: "1 coulomb de carga por 1 ohm de resistência." },
    ],
    correctAnswer: "A",
  },
  {
    id: 19,
    type: "multiple_choice",
    text: "A ENERGIA ELÉTRICA consumida por um aparelho é calculada por:",
    tip: "Se potência é energia por tempo, então energia é potência × tempo.",
    funFact: "\"Você Sabia?\" — E = P · t. Para calcular em kWh: converta P para kW (divida por 1.000) e t para horas. Um notebook de 50 W ligado 8h/dia consome 0,05 × 8 = 0,4 kWh/dia = 12 kWh/mês. Um chuveiro de 5.500 W por 15 min/dia consome 5,5 × 0,25 × 30 = 41,25 kWh/mês — mais que o notebook em 3 meses.",
    points: 1,
    options: [
      { id: "A", text: "E = V/I" },
      { id: "B", text: "E = R · I²" },
      { id: "C", text: "E = P · t" },
      { id: "D", text: "E = V² / R" },
    ],
    correctAnswer: "C",
  },
  {
    id: 20,
    type: "multiple_choice",
    text: "O QUILOWATT-HORA (kWh) é:",
    tip: "kWh = unidade de energia na conta de luz. 1 kWh = 1.000 W por 1 hora.",
    funFact: "\"Você Sabia?\" — 1 kWh = 3.600.000 joules (3,6 MJ). Uma lâmpada LED de 10 W ligada 100 horas consome 1 kWh. O brasileiro médio consome cerca de 160 kWh/mês. A tarifa residencial gira em torno de R$ 0,70 a R$ 1,00 por kWh — por isso o chuveiro elétrico, consumindo 162 kWh/mês (no exemplo do simulado), pode representar metade da conta de energia.",
    points: 1,
    options: [
      { id: "A", text: "A potência máxima suportada por um circuito residencial." },
      { id: "B", text: "A unidade de energia elétrica usada nas contas de luz: equivale à energia de 1 kW durante 1 hora." },
      { id: "C", text: "A unidade de corrente elétrica em circuitos industriais." },
      { id: "D", text: "A tensão máxima de operação de aparelhos domésticos." },
    ],
    correctAnswer: "B",
  },
  {
    id: 21,
    type: "multiple_choice",
    text: "Um chuveiro de 5.400 W é usado 1 hora por dia. Qual é o seu consumo em 30 dias?",
    tip: "Converta para kW: 5.400 W = 5,4 kW. Depois: E = P(kW) × t(h) × dias.",
    funFact: "\"Você Sabia?\" — 5,4 kW × 1 h × 30 dias = 162 kWh/mês. Com tarifa de R$ 0,90/kWh, isso é R$ 145,80/mês só no chuveiro! Trocar por aquecedor solar pode reduzir 30-40% da conta de energia elétrica residencial. O Brasil tem irradiação solar média de 4,5 a 6,5 kWh/m²/dia — perfeito para energia solar.",
    points: 1,
    options: [
      { id: "A", text: "162 kWh" },
      { id: "B", text: "180 kWh" },
      { id: "C", text: "54 kWh" },
      { id: "D", text: "5.400 kWh" },
    ],
    correctAnswer: "A",
  },
  {
    id: 22,
    type: "multiple_choice",
    text: "O chuveiro elétrico é um dos maiores consumidores de energia em uma residência porque:",
    tip: "O que torna um aparelho 'gastão'? Potência alta, uso frequente, ou os dois?",
    funFact: "\"Você Sabia?\" — O chuveiro elétrico tem potência de 4.400 a 7.500 W e é usado em média 15-30 min/dia. Nos EUA e Europa, o chuveiro quase não existe com resistência elétrica — usa-se aquecedor a gás ou solar. No Brasil, o chuveiro elétrico representa 24% do consumo residencial médio, sendo o campeão isolado.",
    points: 1,
    options: [
      { id: "A", text: "Usa corrente alternada, que consome mais energia que a corrente contínua." },
      { id: "B", text: "Precisa de um circuito de alta resistência para funcionar corretamente." },
      { id: "C", text: "Tem potência muito alta (5.000 a 7.500 W) e é usado diariamente, acumulando grande consumo." },
      { id: "D", text: "Opera na tensão mais baixa (110 V) e por isso consome mais energia." },
    ],
    correctAnswer: "C",
  },
  {
    id: 23,
    type: "multiple_choice",
    text: "Um CURTO-CIRCUITO ocorre quando:",
    tip: "O nome diz tudo: o caminho da corrente fica 'curto demais' — com pouca resistência.",
    funFact: "\"Você Sabia?\" — Em um curto-circuito, a resistência cai quase a zero, e pela Lei de Ohm (I = V/R), a corrente sobe para valores enormes. Um curto em uma instalação de 220 V com resistência de 0,01 Ω geraria 22.000 A — capaz de fundir o fio em milissegundos e iniciar um incêndio. O fusível ou disjuntor 'salva' o circuito antes disso.",
    points: 1,
    options: [
      { id: "A", text: "A tensão da rede elétrica é maior que a especificada para um aparelho." },
      { id: "B", text: "Dois aparelhos de alta potência são ligados simultaneamente na mesma tomada." },
      { id: "C", text: "A corrente elétrica para de fluir por um resistor queimado no circuito." },
      { id: "D", text: "Dois pontos de diferente potencial de um circuito são ligados diretamente por um condutor de baixa resistência, causando corrente excessiva e superaquecimento." },
    ],
    correctAnswer: "D",
  },
  {
    id: 24,
    type: "multiple_choice",
    text: "A função de FUSÍVEIS e DISJUNTORES em uma instalação elétrica é:",
    tip: "São os 'guardiões' do circuito — o que eles fazem quando a corrente passa do limite?",
    funFact: "\"Você Sabia?\" — O fusível é um fio de liga metálica que funde (e interrompe o circuito) quando a corrente ultrapassa o limite. O disjuntor faz o mesmo, mas pode ser religado manualmente. Disjuntores residenciais são calibrados em 10 A, 20 A, 30 A etc. — por isso alguns tomadas 'caem' quando se liga muitos aparelhos ao mesmo tempo.",
    points: 1,
    options: [
      { id: "A", text: "Aumentar a tensão da rede elétrica para aparelhos de alta potência." },
      { id: "B", text: "Proteger o circuito contra sobrecarga e curto-circuito, interrompendo a corrente quando ela ultrapassa o limite seguro." },
      { id: "C", text: "Regular a frequência da corrente alternada residencial." },
      { id: "D", text: "Armazenar energia elétrica para uso em caso de falta de luz." },
    ],
    correctAnswer: "B",
  },
  {
    id: 25,
    type: "multiple_choice",
    text: "O ATERRAMENTO ELÉTRICO tem a função de:",
    tip: "'Terra' é um reservatório infinito de cargas — conectar ao solo elimina cargas perigosas.",
    funFact: "\"Você Sabia?\" — O aterramento é obrigatório em instalações elétricas modernas (norma ABNT NBR 5410). Um chuveiro sem aterramento pode acumular cargas no seu gabinete metálico — e ao tocar, o usuário vira o 'caminho para a terra', levando um choque. O pino redondo das tomadas de 3 pinos é exatamente o fio de aterramento.",
    points: 1,
    options: [
      { id: "A", text: "Conduzir correntes de fuga para a terra (solo), protegendo pessoas de choques elétricos em caso de falha no isolamento dos aparelhos." },
      { id: "B", text: "Aumentar a tensão da instalação elétrica residencial." },
      { id: "C", text: "Melhorar a eficiência de aparelhos eletroeletrônicos sensíveis." },
      { id: "D", text: "Garantir que os circuitos em paralelo recebam a mesma corrente." },
    ],
    correctAnswer: "A",
  },
  {
    id: 26,
    type: "multiple_choice",
    text: "Qual das práticas a seguir é CORRETA em relação à segurança elétrica?",
    tip: "Pense em qual ação realmente protege o circuito e as pessoas.",
    funFact: "\"Você Sabia?\" — As tempestades com raios são a principal causa de surtos de tensão nas residências — podendo queimar TVs, computadores e geladeiras. Um para-raio e um estabilizador ou DPS (Dispositivo de Proteção contra Surtos) protegem os equipamentos. No Brasil, são registrados cerca de 78 milhões de raios por ano.",
    points: 1,
    options: [
      { id: "A", text: "Utilizar fios de menor espessura para economizar material em instalações de alta potência." },
      { id: "B", text: "Ligar vários aparelhos em um mesmo benjamim (T) para aproveitar melhor as tomadas." },
      { id: "C", text: "Realizar reparos elétricos sem desligar o disjuntor para manter a conveniência." },
      { id: "D", text: "Desligar os aparelhos da tomada durante tempestades com raios, para evitar sobretensões." },
    ],
    correctAnswer: "D",
  },
  {
    id: 27,
    type: "multiple_choice",
    text: "Os SUPERCONDUTORES são materiais que:",
    tip: "O prefixo 'super' indica algo extraordinário — o que acontece com a resistência desses materiais?",
    funFact: "\"Você Sabia?\" — Supercondutores têm resistência elétrica ZERO abaixo de uma temperatura crítica. Isso permite correntes circulando sem perda de energia por tempo indefinido! São usados nos imãs dos aceleradores de partículas (como o LHC do CERN), em trens maglev japoneses e em máquinas de ressonância magnética (MRI). O grande desafio é criar supercondutores que operem à temperatura ambiente.",
    points: 1,
    options: [
      { id: "A", text: "Conduzem eletricidade com resistência muito alta, dissipando toda a energia como calor." },
      { id: "B", text: "Transformam energia elétrica em mecânica com 100% de eficiência." },
      { id: "C", text: "A temperaturas muito baixas, apresentam resistência elétrica praticamente zero, conduzindo corrente sem perda de energia." },
      { id: "D", text: "Armazenam cargas elétricas sem precisar de bateria, sendo fontes de energia renováveis." },
    ],
    correctAnswer: "C",
  },
  {
    id: 28,
    type: "multiple_choice",
    text: "O EFEITO JOULE é o fenômeno em que:",
    tip: "O que acontece com a energia elétrica quando a corrente passa por um resistor?",
    funFact: "\"Você Sabia?\" — James Prescott Joule foi um dos primeiros a demonstrar matematicamente a conversão de energia elétrica em calor (Q = R·I²·t). Em sistemas de transmissão de energia de alta tensão, o efeito Joule é minimizado: ao aumentar 10× a tensão, a corrente cai 10×, e a perda cai 100× (proporcional a I²). Por isso as linhas de transmissão operam em centenas de milhares de volts.",
    points: 1,
    options: [
      { id: "A", text: "A passagem de corrente elétrica por um resistor gera calor proporcional à resistência e ao quadrado da corrente (Q = R · I² · t)." },
      { id: "B", text: "O calor do ambiente aumenta a resistência elétrica dos metais." },
      { id: "C", text: "A corrente elétrica causa uma força magnética em fios paralelos." },
      { id: "D", text: "A tensão elétrica cria cargas induzidas em materiais dielétricos." },
    ],
    correctAnswer: "A",
  },
  {
    id: 29,
    type: "multiple_choice",
    text: "Qual dos aparelhos a seguir NÃO utiliza o efeito Joule como princípio de funcionamento?",
    tip: "O efeito Joule converte energia elétrica em calor. Qual aparelho usa a eletricidade de forma diferente?",
    funFact: "\"Você Sabia?\" — O ventilador converte energia elétrica em energia mecânica (rotação das pás) usando um motor elétrico. Ferro de passar, chuveiro, torradeira, forno elétrico e secador de cabelo usam o efeito Joule (calor). A eficiência do motor elétrico é de 85-95%, muito superior à de motores a combustão (25-35%) — razão do sucesso dos veículos elétricos.",
    points: 1,
    options: [
      { id: "A", text: "Ferro de passar roupa" },
      { id: "B", text: "Chuveiro elétrico" },
      { id: "C", text: "Torradeira" },
      { id: "D", text: "Ventilador elétrico" },
    ],
    correctAnswer: "D",
  },
  {
    id: 30,
    type: "multiple_choice",
    text: "Georg Simon Ohm descobriu que, em um condutor ôhmico, a resistência elétrica é:",
    tip: "A lei leva o nome dele — o que ela afirma sobre a relação V, I e R?",
    funFact: "\"Você Sabia?\" — R = V/I é constante para materiais ôhmicos à temperatura constante. Materiais não-ôhmicos (como diodos e transistores) têm R variável — e são exatamente esses que tornam a eletrônica moderna possível. Sem materiais não-ôhmicos, não haveria computadores, smartphones nem LEDs.",
    points: 1,
    options: [
      { id: "A", text: "Diretamente proporcional à tensão e inversamente proporcional à corrente." },
      { id: "B", text: "A razão constante entre a tensão e a corrente: R = V/I." },
      { id: "C", text: "Inversamente proporcional ao quadrado da corrente elétrica." },
      { id: "D", text: "Igual ao produto da tensão pela corrente: R = V · I." },
    ],
    correctAnswer: "B",
  },
];
