export const questoesSociologia1EmB3Av2 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'A divisão do trabalho foi analisada de formas distintas por Durkheim e por Marx. Qual das alternativas apresenta a visão de Émile Durkheim sobre a divisão do trabalho?',
    tip: 'Durkheim tinha uma visão funcionalista — para ele, a divisão do trabalho cumpre uma função social positiva, criando interdependência.',
    funFact: 'Você sabia? Durkheim escreveu "A Divisão do Trabalho Social" em 1893 como sua tese de doutorado. Ele queria mostrar que a coesão social moderna não dependia mais de todos serem iguais, mas de todos precisarem uns dos outros!',
    points: 1,
    options: [
      { id: 'A', text: 'A divisão do trabalho é um mecanismo de exploração que aliena o trabalhador e o separa do produto de seu trabalho' },
      { id: 'B', text: 'A divisão do trabalho só beneficia os capitalistas, aumentando a extração de mais-valia dos operários' },
      { id: 'C', text: 'A divisão do trabalho cria desigualdades artificiais que devem ser eliminadas pela revolução socialista' },
      { id: 'D', text: 'A divisão do trabalho cria solidariedade orgânica ao tornar as pessoas especializadas e interdependentes, contribuindo para a coesão social moderna' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'O taylorismo, desenvolvido por Frederick Winslow Taylor no final do século XIX, ficou conhecido como "organização científica do trabalho". Qual era seu princípio central?',
    tip: 'Taylor queria eliminar o "tempo morto" e os movimentos desnecessários da produção — para isso, estudou cada gesto do trabalhador e cronometrou cada tarefa.',
    funFact: 'Você sabia? Taylor realizou famosos experimentos com trabalhadores em siderúrgicas americanas no final do século XIX. Ele descobriu que um trabalhador poderia transportar três vezes mais aço por dia se soubesse COMO mover seu corpo eficientemente!',
    points: 1,
    options: [
      { id: 'A', text: 'Separar o planejamento (feito por gerentes/engenheiros) da execução (feita pelos operários), aumentando a eficiência por meio da especialização e do controle científico do tempo e dos movimentos' },
      { id: 'B', text: 'Dar mais autonomia aos trabalhadores para que escolhessem seus próprios métodos de trabalho' },
      { id: 'C', text: 'Reduzir a jornada de trabalho para aumentar a produtividade por meio do descanso adequado' },
      { id: 'D', text: 'Pagar salários mais altos para motivar os trabalhadores a produzir voluntariamente mais' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'O fordismo é o modelo de produção desenvolvido por Henry Ford no início do século XX. Qual foi sua principal inovação?',
    tip: 'Ford não inventou a linha de montagem do zero, mas a aplicou de forma revolucionária na produção do Modelo T — o que mudou completamente a indústria.',
    funFact: 'Você sabia? Em 1913, Ford produzia um carro novo a cada 12 horas. Com a linha de montagem, passou a produzir um carro a cada 93 minutos! Isso reduziu o preço do Modelo T em 75%, tornando o automóvel acessível para a classe trabalhadora americana.',
    points: 1,
    options: [
      { id: 'A', text: 'A produção sob encomenda, adaptando cada produto às especificações individuais do cliente' },
      { id: 'B', text: 'O retorno ao trabalho artesanal, valorizando a qualidade individual de cada produto' },
      { id: 'C', text: 'A linha de montagem com esteiras rolantes que move o produto pelo trabalhador fixo, permitindo produção em massa padronizada e barata' },
      { id: 'D', text: 'A produção just-in-time, fabricando apenas o necessário para atender à demanda imediata' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'O toyotismo (ou Sistema Toyota de Produção) surgiu no Japão do pós-Segunda Guerra. Qual é o princípio do "just-in-time" que o caracteriza?',
    tip: 'O Japão dos anos 1950 era um país devastado pela guerra, com poucos recursos e espaço para estoques enormes — isso moldou a lógica do toyotismo.',
    funFact: 'Você sabia? Taiichi Ohno, engenheiro da Toyota, teve a ideia do just-in-time ao observar o funcionamento dos supermercados americanos: os supermercados só repõem o estoque quando o produto é retirado da prateleira — sem desperdício!',
    points: 1,
    options: [
      { id: 'A', text: 'Produzir o máximo possível para criar grandes estoques que garantam o abastecimento em qualquer situação' },
      { id: 'B', text: 'Produzir apenas o necessário, no momento necessário e na quantidade necessária, eliminando estoques desnecessários e reduzindo desperdícios' },
      { id: 'C', text: 'Padronizar completamente todos os produtos para reduzir a variedade e simplificar a produção' },
      { id: 'D', text: 'Substituir todos os trabalhadores por máquinas automatizadas para eliminar erros humanos' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'A crítica marxista ao taylorismo aponta que esse modelo de gestão aprofundou a alienação do trabalhador. Por quê?',
    tip: 'O taylorismo separou radicalmente o pensar do fazer — o trabalhador não pensa mais sobre como produzir, apenas executa movimentos prescritos.',
    funFact: 'Você sabia? Harry Braverman, em "Trabalho e Capital Monopolista" (1974), analisou como o taylorismo destruiu os ofícios tradicionais: artesãos que detinham o conhecimento completo do seu trabalho foram substituídos por operários que faziam apenas um gesto repetitivo infinitamente!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque o taylorismo aumentou os salários, fazendo os trabalhadores se preocuparem apenas com dinheiro' },
      { id: 'B', text: 'Porque o taylorismo exigia nível superior de escolaridade, excluindo os trabalhadores menos instruídos' },
      { id: 'C', text: 'Porque o taylorismo reduziu a jornada de trabalho, dando menos significado à vida profissional' },
      { id: 'D', text: 'Porque ao separar planejamento de execução, o taylorismo expropria do trabalhador o conhecimento e o controle sobre o processo produtivo, aprofundando a alienação' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'O fordismo criou não apenas um modelo de produção, mas também um modelo de consumo. Como Henry Ford relacionou produção e consumo?',
    tip: 'Ford percebeu uma contradição: como vender carros em massa se os trabalhadores não ganhavam o suficiente para comprá-los?',
    funFact: 'Você sabia? Em 1914, Ford dobrou os salários dos operários para US$ 5 por dia (o dobro da média do setor) e reduziu a jornada para 8 horas. Muitos chamaram isso de loucura — mas Ford explicou: "Quero que meus trabalhadores possam comprar meus carros!"',
    points: 1,
    options: [
      { id: 'A', text: 'Ford propunha produção em massa combinada com salários mais altos para os trabalhadores, que se tornariam consumidores dos próprios produtos que fabricavam' },
      { id: 'B', text: 'Ford defendia que apenas as classes médias e altas deveriam consumir os produtos industrializados das fábricas' },
      { id: 'C', text: 'Ford acreditava que os trabalhadores não deveriam consumir produtos industrializados, mantendo-se como poupadores' },
      { id: 'D', text: 'Ford defendia que o Estado deveria subsidiar o consumo das classes trabalhadoras com vouchers de compra' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'O "kanban" é um dos elementos do sistema toyotista. Como funciona esse mecanismo?',
    tip: 'Kanban em japonês significa "cartão" ou "sinal visual". É um sistema de controle de estoque e produção baseado em sinais simples.',
    funFact: 'Você sabia? O sistema kanban foi criado pela Toyota nos anos 1940 e hoje é amplamente usado em empresas de tecnologia (como a metodologia Agile/Scrum). Até hospitais e editoras usam kanban para controlar fluxos de trabalho!',
    points: 1,
    options: [
      { id: 'A', text: 'Um sistema de punição para trabalhadores que não atingem as metas de produção diária' },
      { id: 'B', text: 'Um programa de treinamento intensivo para trabalhadores aprenderem múltiplas funções ao mesmo tempo' },
      { id: 'C', text: 'Um sistema de sinalização visual que controla o fluxo de produção e o reabastecimento de materiais conforme a demanda real, evitando estoques excessivos' },
      { id: 'D', text: 'Um sistema de avaliação de desempenho dos trabalhadores baseado em metas individuais e coletivas' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'Uma diferença fundamental entre o fordismo e o toyotismo é a relação com a variedade de produtos. Como cada modelo aborda isso?',
    tip: 'Ford ficou famoso por dizer que o cliente podia escolher qualquer cor, "desde que seja preto" — o toyotismo inverteu essa lógica.',
    funFact: 'Você sabia? O Modelo T de Ford foi fabricado com a mesma cor (preto) por anos porque a tinta preta secava mais rápido, não interrompendo a linha de montagem. O toyotismo reverteu essa lógica ao permitir personalização sem perder eficiência!',
    points: 1,
    options: [
      { id: 'A', text: 'O fordismo permite alta variedade; o toyotismo exige padronização absoluta de todos os produtos' },
      { id: 'B', text: 'O fordismo produz em série com produtos padronizados para o mercado de massa; o toyotismo produz de forma flexível, adaptando-se às variações da demanda' },
      { id: 'C', text: 'Ambos produzem produtos padronizados — a diferença está apenas na velocidade de produção' },
      { id: 'D', text: 'O fordismo é exclusivo para automóveis; o toyotismo foi criado especificamente para eletroeletrônicos' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'O "Estado de bem-estar social" (welfare state) surgiu no pós-Segunda Guerra associado ao modelo fordista-keynesiano. Qual era sua lógica?',
    tip: 'O Estado de bem-estar social não era apenas filantropia — tinha uma lógica econômica: trabalhadores com renda e seguridade social são também consumidores que mantêm a economia funcionando.',
    funFact: 'Você sabia? Os países escandinavos (Suécia, Noruega, Dinamarca) construíram os Estados de bem-estar social mais robustos do mundo. Curiosamente, isso não impediu o capitalismo de florescer — são alguns dos países com maior IDH e mais ricos do mundo!',
    points: 1,
    options: [
      { id: 'A', text: 'Eliminar completamente a desigualdade social por meio da coletivização dos meios de produção' },
      { id: 'B', text: 'Substituir o sistema capitalista pelo socialismo de forma gradual e democrática' },
      { id: 'C', text: 'Reduzir os impostos das empresas para estimular o investimento e a geração de empregos' },
      { id: 'D', text: 'O Estado garante direitos trabalhistas, saúde pública, educação e previdência social para manter o consumo em massa e a coesão social dentro do capitalismo' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'O trabalhador polivalente é uma característica do toyotismo. O que é a polivalência no contexto do trabalho?',
    tip: 'Ao contrário do taylorismo (um trabalhador, uma função especializada), o toyotismo quer trabalhadores capazes de fazer várias coisas diferentes.',
    funFact: 'Você sabia? No toyotismo, a polivalência é exigida dos trabalhadores como "flexibilidade" — mas os sociólogos críticos apontam que isso transfere os riscos da produção para os trabalhadores: eles precisam se adaptar a qualquer demanda, inclusive trabalhar em funções para as quais não foram contratados!',
    points: 1,
    options: [
      { id: 'A', text: 'A capacidade do trabalhador de exercer múltiplas funções e tarefas diferentes dentro do processo produtivo, aumentando a flexibilidade da empresa' },
      { id: 'B', text: 'A especialização extrema do trabalhador em uma única e específica função para maximizar a eficiência' },
      { id: 'C', text: 'A habilidade do trabalhador de operar várias máquinas ao mesmo tempo sem necessidade de treinamento' },
      { id: 'D', text: 'A capacidade do gerente de controlar todos os aspectos do processo produtivo sem a participação dos trabalhadores' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'O filme "Tempos Modernos" (1936), de Charles Chaplin, é uma crítica icônica a qual modelo de produção?',
    tip: 'Chaplin retratou um operário preso numa linha de montagem, apertando parafusos numa velocidade absurda, até enlouquecer — qual modelo esse filme satiriza?',
    funFact: 'Você sabia? Chaplin pesquisou sobre Taylor e Ford antes de fazer "Tempos Modernos". A cena em que o personagem é literalmente "engolido" pela máquina é uma metáfora perfeita para a crítica marxista de que o capitalismo industrial transforma o humano em extensão da máquina!',
    points: 1,
    options: [
      { id: 'A', text: 'Ao toyotismo e à exploração dos trabalhadores polivalentes pelo sistema just-in-time japonês' },
      { id: 'B', text: 'Ao fordismo/taylorismo: a desumanização do trabalho pela linha de montagem, a repetição mecânica e o controle total sobre os movimentos do trabalhador' },
      { id: 'C', text: 'Ao sistema de trabalho artesanal pré-industrial que explorava os aprendizes nos ateliês medievais' },
      { id: 'D', text: 'Ao neoliberalismo e à terceirização do trabalho que surgiu nos anos 1980' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'A crise do fordismo nos anos 1970-1980 foi precipitada por vários fatores. Qual foi a causa fundamental?',
    tip: 'O fordismo funcionou bem enquanto havia mercados em expansão e trabalhadores sindicalizados com poder de compra — o que mudou nos anos 1970?',
    funFact: 'Você sabia? A crise do petróleo de 1973 foi o gatilho imediato do fim do "fordismo dourado". Com o aumento brutal do petróleo, as indústrias de automóveis americanas e europeias pararam, revelando fragilidades estruturais do modelo de produção em massa!',
    points: 1,
    options: [
      { id: 'A', text: 'O fordismo foi proibido pelos governos por causar danos ao meio ambiente' },
      { id: 'B', text: 'Os trabalhadores passaram a rejeitar o trabalho industrial, preferindo empregos no setor de serviços' },
      { id: 'C', text: 'A saturação dos mercados de massa, a crise do petróleo e a crescente concorrência global exigiram produção mais flexível e diversificada, para o que o fordismo rígido não estava preparado' },
      { id: 'D', text: 'O fordismo tornou-se obsoleto porque os computadores eliminaram completamente a necessidade de trabalho humano' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'O neoliberalismo, a partir dos anos 1980, transformou as relações de trabalho. Qual foi o impacto principal dessa transformação?',
    tip: 'O neoliberalismo defendia a redução do papel do Estado e a liberalização dos mercados — o que isso significou para os trabalhadores?',
    funFact: 'Você sabia? Margaret Thatcher, primeira-ministra britânica (1979-1990), tornou-se símbolo do neoliberalismo ao quebrar os sindicatos britânicos, especialmente na famosa greve dos mineiros de 1984-1985. Ela declarou: "Não existe sociedade, existem apenas indivíduos e famílias"!',
    points: 1,
    options: [
      { id: 'A', text: 'Fortalecimento dos sindicatos e aumento dos direitos trabalhistas conquistados' },
      { id: 'B', text: 'Redução das jornadas de trabalho e aumento dos salários reais dos trabalhadores' },
      { id: 'C', text: 'Expansão do Estado de bem-estar social e dos investimentos em serviços públicos' },
      { id: 'D', text: 'Flexibilização e precarização das relações de trabalho: enfraquecimento dos sindicatos, terceirização, contratos temporários e redução de direitos' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'O estudo de tempos e movimentos, proposto por Taylor, foi desenvolvido para:',
    tip: 'Taylor queria transformar o trabalho em ciência — mas de que ponto de vista? Para benefício de quem?',
    funFact: 'Você sabia? Taylor cronometrou os trabalhadores sem lhes dizer o que estava fazendo — e depois usou os dados para aumentar as metas. Os trabalhadores sabiam disso e passaram a trabalhar mais lento quando viam Taylor com seu cronômetro: criou-se uma guerra de sabotagem mútua!',
    points: 1,
    options: [
      { id: 'A', text: 'Identificar e eliminar movimentos e pausas desnecessários, definindo cientificamente o método mais eficiente para cada tarefa e o tempo padrão para executá-la' },
      { id: 'B', text: 'Garantir a segurança dos trabalhadores identificando movimentos que causavam lesões ocupacionais' },
      { id: 'C', text: 'Aumentar os intervalos de descanso para recuperação física dos trabalhadores durante a jornada' },
      { id: 'D', text: 'Demonstrar que os trabalhadores precisavam de menos horas para realizar as mesmas tarefas' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'No toyotismo, o conceito de "kaizen" é central. O que é kaizen?',
    tip: 'Kaizen em japonês significa literalmente "melhoria contínua" ou "mudança para melhor". No toyotismo, isso é uma filosofia de gestão aplicada à produção.',
    funFact: 'Você sabia? O kaizen envolve todos os trabalhadores — do operário ao gerente — na identificação de problemas e propostas de melhoria. Isso é diferente do taylorismo, onde apenas os engenheiros pensavam. Mas críticos apontam que no toyotismo, os trabalhadores "voluntariamente" intensificam sua própria exploração!',
    points: 1,
    options: [
      { id: 'A', text: 'O sistema de rodízio de trabalhadores entre diferentes postos de trabalho para reduzir a fadiga' },
      { id: 'B', text: 'A filosofia de melhoria contínua e incremental de todos os processos, com participação de todos os trabalhadores na identificação e solução de problemas' },
      { id: 'C', text: 'O sistema de remuneração variável baseado na produtividade individual de cada trabalhador' },
      { id: 'D', text: 'O processo de automação completa da produção para eliminar erros humanos no chão de fábrica' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'A automação e a robótica, ao substituírem trabalhadores nas indústrias, geraram um debate sociológico importante. Qual é esse debate?',
    tip: 'A automação aumenta a produtividade — mas o que acontece com os trabalhadores substituídos pelas máquinas? E com os salários de quem permanece?',
    funFact: 'Você sabia? Estudos do Instituto McKinsey estimam que a automação pode eliminar 50% dos empregos existentes até 2055. Isso retoma o debate do século XIX: os ludistas (trabalhadores ingleses) quebravam máquinas nos anos 1810 pelo mesmo temor de perder emprego para a mecanização!',
    points: 1,
    options: [
      { id: 'A', text: 'Não há debate — todos os sociólogos concordam que a automação é sempre benéfica para os trabalhadores' },
      { id: 'B', text: 'O debate é apenas técnico — sobre qual tipo de robô é mais eficiente para cada tipo de tarefa' },
      { id: 'C', text: 'O debate sociológico gira em torno de quem se beneficia do aumento de produtividade: os ganhos vão para salários e direitos dos trabalhadores ou para os lucros dos proprietários?' },
      { id: 'D', text: 'O debate é sobre como treinar os trabalhadores para que nunca sejam substituídos por máquinas' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'A terceirização (outsourcing) é uma estratégia de gestão do trabalho amplamente usada no toyotismo e no pós-fordismo. Do ponto de vista sociológico crítico, qual é seu impacto principal?',
    tip: 'A terceirização fragmenta a relação de trabalho — o trabalhador não é mais "empregado" da grande empresa, mas de uma empresa menor subcontratada.',
    funFact: 'Você sabia? No Brasil, a chamada "Reforma Trabalhista" de 2017 ampliou a terceirização para todas as atividades (inclusive a atividade-fim das empresas), o que gerou intenso debate entre sociólogos sobre os impactos para os direitos dos trabalhadores!',
    points: 1,
    options: [
      { id: 'A', text: 'Fortalece os vínculos empregatícios ao distribuir os riscos entre mais empresas e trabalhadores' },
      { id: 'B', text: 'Aumenta a estabilidade dos trabalhadores por meio de múltiplos contratos com diferentes empresas' },
      { id: 'C', text: 'Cria empregos de melhor qualidade ao especializar as empresas em suas competências centrais' },
      { id: 'D', text: 'Fragmenta os coletivos de trabalhadores, enfraquece os sindicatos, reduz salários e transfere riscos da empresa para o trabalhador' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'Henry Ford ficou famoso pela frase sobre o Modelo T: o cliente poderia escolher qualquer cor "desde que fosse preto". Que princípio de produção essa afirmação ilustra?',
    tip: 'Essa frase revela a lógica de produção do fordismo: o que importa não é a preferência individual do cliente, mas a eficiência máxima da linha de montagem.',
    funFact: 'Você sabia? Essa limitação do fordismo foi justamente o que abriu oportunidade para a General Motors superar a Ford nos anos 1920! A GM começou a oferecer "um carro para cada bolso e propósito" — variedade que o Ford Model T não podia oferecer!',
    points: 1,
    options: [
      { id: 'A', text: 'A padronização e a produção em série que privilegia a eficiência sobre a personalização, produzindo produtos idênticos em grande escala' },
      { id: 'B', text: 'A estratégia de marketing que associa a cor preta ao luxo e à sofisticação dos automóveis' },
      { id: 'C', text: 'O racismo cultural que associava a cor preta a qualidades negativas na sociedade americana' },
      { id: 'D', text: 'A preocupação ambiental de Ford com o uso de tintas que não poluíssem durante a produção' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'O "trabalho em equipe" (teamwork) promovido pelo toyotismo foi criticado por alguns sociólogos. Qual é a crítica?',
    tip: 'No toyotismo, as equipes não têm apenas função produtiva — elas também funcionam como mecanismo de controle mútuo entre os próprios trabalhadores.',
    funFact: 'Você sabia? O sociólogo britânico Paul Thompson chamou o toyotismo de "neo-taylorismo" — para ele, por baixo da aparência de participação e autonomia das equipes, há um controle ainda mais intenso do trabalho, agora exercido pelos próprios colegas de trabalho!',
    points: 1,
    options: [
      { id: 'A', text: 'Que o trabalho em equipe aumenta excessivamente os conflitos interpessoais entre os trabalhadores' },
      { id: 'B', text: 'Que o trabalho em equipe pode funcionar como mecanismo de controle mútuo entre trabalhadores, que se pressionam uns aos outros a atingir metas, transferindo o controle gerencial para o grupo' },
      { id: 'C', text: 'Que o trabalho em equipe é muito lento para produzir resultados imediatos e visíveis nas empresas' },
      { id: 'D', text: 'Que o trabalho em equipe impede a especialização necessária para a alta qualidade dos produtos finais' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'A "acumulação flexível", conceito de David Harvey, descreve o pós-fordismo. Qual é a característica central desse novo regime?',
    tip: 'Harvey quis capturar o que é radicalmente novo no capitalismo pós-fordista: não apenas a mudança técnica, mas uma nova forma de acumular capital com máxima flexibilidade.',
    funFact: 'Você sabia? David Harvey cunhou o conceito de "acumulação flexível" em seu livro "A Condição Pós-Moderna" (1989). Para ele, a flexibilidade não libertou os trabalhadores — ela os tornou mais vulneráveis, pois perderam os direitos associados ao emprego estável fordista!',
    points: 1,
    options: [
      { id: 'A', text: 'A volta ao artesanato e à produção manual como reação à automação industrial excessiva' },
      { id: 'B', text: 'A solidificação das relações de trabalho com contratos permanentes e benefícios garantidos por lei' },
      { id: 'C', text: 'A acumulação flexível descreve o regime de produção pós-fordista, caracterizado por processos de trabalho flexíveis, mercados voláteis, integração geográfica global e enfraquecimento do trabalho organizado' },
      { id: 'D', text: 'A consolidação das grandes corporações fordistas com maior poder de negociação com governos e sindicatos' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'A greve é um dos principais instrumentos de luta dos trabalhadores. Qual é o significado sociológico da greve?',
    tip: 'A greve não é apenas um instrumento econômico (para conseguir melhores salários) — tem uma dimensão sociológica mais ampla.',
    funFact: 'Você sabia? A greve geral de 1917 em São Paulo, que durou 20 dias, foi organizada por trabalhadores anarquistas e socialistas imigrantes italianos e espanhóis. Ela conseguiu as primeiras conquistas trabalhistas do Brasil, como jornada de 8 horas e abolição do trabalho infantil em algumas fábricas!',
    points: 1,
    options: [
      { id: 'A', text: 'Uma manifestação coletiva em que trabalhadores interrompem voluntariamente o trabalho para pressionar o empregador a atender suas demandas, expressando o conflito inerente às relações de trabalho capitalistas' },
      { id: 'B', text: 'Um ato criminoso que deve ser proibido pelo Estado para garantir a ordem econômica e a continuidade da produção' },
      { id: 'C', text: 'Uma estratégia de marketing utilizada por empresas para criar escassez artificial e aumentar o preço dos produtos' },
      { id: 'D', text: 'Uma prática exclusiva dos países socialistas, incompatível com o sistema capitalista de livre mercado' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'No toyotismo, a filosofia de "zero defeito" representa uma mudança na gestão da qualidade. O que isso implica para os trabalhadores?',
    tip: 'No fordismo, havia departamentos específicos de controle de qualidade. No toyotismo, a qualidade passa a ser responsabilidade de todos — inclusive do trabalhador individual.',
    funFact: 'Você sabia? O sistema Toyota permite que qualquer trabalhador PARE a linha de produção se identificar um defeito — algo impensável no fordismo rígido. Isso parece mais autonomia, mas também transfere para o trabalhador a responsabilidade por problemas que antes eram gerenciais!',
    points: 1,
    options: [
      { id: 'A', text: 'Os trabalhadores recebem mais descanso para trabalhar sem pressão e com mais precisão' },
      { id: 'B', text: 'O Estado contrata inspetores independentes para verificar a qualidade sem envolver os trabalhadores' },
      { id: 'C', text: 'A qualidade é terceirizada para fornecedores externos que respondem contratualmente por defeitos' },
      { id: 'D', text: 'A responsabilidade pela qualidade é descentralizada e transferida para cada trabalhador individualmente, que deve inspecionar e corrigir seu próprio trabalho em tempo real' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Os sindicatos surgiram como forma de organização coletiva dos trabalhadores durante a Revolução Industrial. Qual é a função sociológica dos sindicatos?',
    tip: 'Um trabalhador individual tem muito menos poder de negociação com um empregador do que um coletivo organizado — essa assimetria é a razão de ser dos sindicatos.',
    funFact: 'Você sabia? No Brasil, o Dia do Trabalhador (1º de maio) foi estabelecido por Getúlio Vargas em 1939 como parte de uma estratégia de cooptar os sindicatos para o Estado. Curiosamente, a data foi criada nos EUA em 1886 para lembrar a massacre de trabalhadores em Chicago que lutavam pela jornada de 8 horas!',
    points: 1,
    options: [
      { id: 'A', text: 'Promover a harmonia entre capitalistas e trabalhadores, eliminando os conflitos de interesse entre eles' },
      { id: 'B', text: 'Representar coletivamente os trabalhadores em negociações com empregadores e o Estado, equilibrando o poder entre as partes desiguais na relação de trabalho' },
      { id: 'C', text: 'Administrar os fundos de pensão e seguros de saúde dos trabalhadores de forma independente do Estado' },
      { id: 'D', text: 'Substituir o Estado na regulação das relações de trabalho, tornando desnecessária a legislação trabalhista' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'O sistema de "gerência científica" proposto por Taylor estabelecia que a responsabilidade pelo planejamento do trabalho deveria pertencer:',
    tip: 'Taylor argumentava que havia um "princípio da separação" fundamental — e quem deveria pensar sobre o trabalho não era o mesmo que o executava.',
    funFact: 'Você sabia? Antes de Taylor, eram os próprios trabalhadores experientes (especialmente os "soldados" ou "velhos de ofício") que detinham o conhecimento de como fazer o trabalho. Taylor chamou isso de "regra do polegar" — e quis substituir por métodos científicos controlados pela gerência!',
    points: 1,
    options: [
      { id: 'A', text: 'Exclusivamente ao Estado, que criaria agências científicas para planejar a produção nacional' },
      { id: 'B', text: 'Ao sindicato, que representaria os interesses dos trabalhadores no planejamento das tarefas' },
      { id: 'C', text: 'À gerência e aos engenheiros, que deteriam o conhecimento científico sobre os métodos mais eficientes, separando o pensar (gerência) do fazer (operário)' },
      { id: 'D', text: 'Ao próprio trabalhador, que conhecia melhor do que ninguém as especificidades de sua tarefa' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'O conceito de "alienação do trabalho" de Marx é especialmente relevante na análise do taylorismo e do fordismo. Por quê?',
    tip: 'Marx descreveu a alienação como a separação do trabalhador do produto, do processo e de seu próprio ser genérico — o taylorismo e o fordismo aprofundaram esse processo.',
    funFact: 'Você sabia? Na linha de montagem fordista clássica, um trabalhador podia passar anos apertando os mesmos 4 parafusos, repetindo o mesmo gesto 500 vezes por dia, nunca vendo o carro completo que ajudava a fabricar — a alienação em forma de rotina industrial!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque taylorismo e fordismo aprofundaram a alienação ao fragmentar ao máximo o processo produtivo, separando o trabalhador do produto final, do processo como um todo e do conhecimento sobre o trabalho' },
      { id: 'B', text: 'Porque taylorismo e fordismo reduziram a alienação ao aumentar os salários e melhorar as condições materiais dos trabalhadores' },
      { id: 'C', text: 'Porque a alienação de Marx era apenas filosófica e não se aplicava às condições concretas das fábricas industriais' },
      { id: 'D', text: 'Porque taylorismo e fordismo eliminaram o trabalho manual e, portanto, eliminaram a alienação descrita por Marx' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'A produção enxuta (lean production), versão ocidentalizada do toyotismo, foi popularizada pelo MIT nos anos 1990. Qual é sua premissa central?',
    tip: 'A palavra "enxuta" revela a premissa: eliminar tudo que é gordura — tempo perdido, estoques desnecessários, movimentos inúteis, defeitos.',
    funFact: 'Você sabia? O livro "A Máquina que Mudou o Mundo" (1990), resultado de pesquisa do MIT, popularizou o toyotismo no Ocidente chamando-o de "produção enxuta". Ele compara diretamente a produtividade das fábricas japonesas com as americanas e europeias — as japonesas eram muito mais eficientes!',
    points: 1,
    options: [
      { id: 'A', text: 'Contratar trabalhadores com habilidades mínimas para reduzir custos com treinamento' },
      { id: 'B', text: 'Produzir com alto volume de estoques para garantir o abastecimento ininterrupto da linha' },
      { id: 'C', text: 'Concentrar a produção em um único local centralizado para maximizar as economias de escala' },
      { id: 'D', text: 'Eliminar sistematicamente todos os tipos de desperdício (muda) no processo produtivo: estoques excessivos, defeitos, esperas, transporte desnecessário e movimentos inúteis' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'O fordismo foi possível graças ao acordo tácito entre capital e trabalho conhecido como "compromisso fordista". Em que consistia esse compromisso?',
    tip: 'Nos "30 anos gloriosos" (1945-1975), houve uma espécie de trégua histórica entre capitalistas e trabalhadores. Qual era o acordo implícito?',
    funFact: 'Você sabia? Os "Trente Glorieuses" (Trinta Gloriosos), como os franceses chamam o período de 1945-1975, foi um período sem precedentes de crescimento econômico, aumento de salários reais e expansão do Estado social nos países capitalistas avançados — e foi justamente o período do fordismo!',
    points: 1,
    options: [
      { id: 'A', text: 'Os trabalhadores aceitavam a propriedade privada dos meios de produção em troca de participação nos lucros' },
      { id: 'B', text: 'Os trabalhadores aceitavam as condições de trabalho rígidas e a disciplina fordista em troca de salários crescentes, direitos trabalhistas e proteção do Estado de bem-estar social' },
      { id: 'C', text: 'Os capitalistas aceitavam socializar os meios de produção em troca de segurança política e jurídica' },
      { id: 'D', text: 'O Estado assumia a gestão das fábricas para garantir que tanto capitalistas quanto trabalhadores fossem beneficiados' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'A ergonomia surgiu como ciência aplicada ao trabalho. Qual é sua relação com os modelos de produção taylorista e toyotista?',
    tip: 'A ergonomia estuda a relação entre o trabalhador e seu ambiente de trabalho — mas essa relação pode ter objetivos muito diferentes dependendo de quem a utiliza.',
    funFact: 'Você sabia? Taylor também se preocupava com o corpo do trabalhador — mas apenas para maximizar a eficiência. A ergonomia moderna vai além: considera o bem-estar, a saúde e a prevenção de lesões, especialmente as LERs (Lesões por Esforços Repetitivos) causadas justamente pelo trabalho repetitivo taylorista/fordista!',
    points: 1,
    options: [
      { id: 'A', text: 'A ergonomia é usada exclusivamente pelo Estado para fiscalizar as condições de trabalho nas fábricas' },
      { id: 'B', text: 'A ergonomia foi criada pelos sindicatos como ferramenta de luta contra as condições insalubres de trabalho' },
      { id: 'C', text: 'A ergonomia adapta o trabalho ao ser humano, prevenindo lesões e doenças ocupacionais, mas pode também ser instrumentalizada pelas empresas para otimizar a produtividade com conforto mínimo' },
      { id: 'D', text: 'A ergonomia é irrelevante para o toyotismo, que superou todos os problemas de saúde do taylorismo' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'A socióloga brasileira Helena Hirata estudou as "bifurcações do modelo japonês" quando ele foi transplantado para outros países. O que ela descobriu?',
    tip: 'Os modelos de organização do trabalho não são neutros — quando são transplantados para outros contextos, eles interagem com as relações de gênero, raça e classe locais.',
    funFact: 'Você sabia? Helena Hirata comparou fábricas japonesas no Japão, na França e no Brasil. No Brasil, ela descobriu que o toyotismo era aplicado de forma mais autoritária e menos participativa do que no Japão original — e que as trabalhadoras mulheres eram mais exploradas do que os homens!',
    points: 1,
    options: [
      { id: 'A', text: 'O toyotismo é idêntico em todos os países onde é aplicado, sem nenhuma adaptação local' },
      { id: 'B', text: 'O toyotismo é inaplicável em países em desenvolvimento por falta de infraestrutura tecnológica' },
      { id: 'C', text: 'O toyotismo, ao ser transplantado para outros países como o Brasil, interage com desigualdades locais de gênero, raça e classe, produzindo versões distintas e frequentemente mais precarizadas do modelo original' },
      { id: 'D', text: 'O toyotismo elimina automaticamente as desigualdades de gênero nas fábricas por promover a polivalência' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'Do ponto de vista sociológico, qual é a principal diferença entre o trabalho no taylorismo/fordismo e no toyotismo no que se refere ao envolvimento subjetivo do trabalhador?',
    tip: 'O taylorismo queria um trabalhador que NÃO pensasse — apenas executasse. O toyotismo quer que o trabalhador pense — mas de uma forma específica e controlada.',
    funFact: 'Você sabia? O sociólogo italiano Luciano Ferrari Bravo argumentou que no toyotismo há uma "mobilização total" do trabalhador — não apenas seus músculos, como no fordismo, mas sua inteligência, criatividade e envolvimento emocional com a empresa. Isso é mais humanizador ou mais explorador?',
    points: 1,
    options: [
      { id: 'A', text: 'O toyotismo exige menos envolvimento do trabalhador, pois as máquinas fazem a maior parte do trabalho' },
      { id: 'B', text: 'O taylorismo exige o envolvimento total do trabalhador; o toyotismo não faz nenhuma exigência subjetiva' },
      { id: 'C', text: 'Não há diferença relevante — ambos tratam o trabalhador como simples peça substituível no processo produtivo' },
      { id: 'D', text: 'O taylorismo exige apenas a força física do trabalhador; o toyotismo exige também seu envolvimento intelectual e emocional, mobilizando sua subjetividade a favor dos objetivos da empresa' },
    ],
    correctAnswer: 'D',
  },
];
