export const questoesMatematica5AnoB1Av2 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'Na adição 4 + 3 = 7, os números 4 e 3 são chamados de:',
    tip: 'Pensa nos números que são "somados" para chegar ao resultado...',
    funFact: 'Você sabia que o resultado de uma adição também é chamado de soma ou total?',
    points: 1,
    options: [
      { id: 'A', text: 'Diferença' },
      { id: 'B', text: 'Parcelas' },
      { id: 'C', text: 'Produto' },
      { id: 'D', text: 'Quociente' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'Na subtração 9 - 4 = 5, o número 9 é chamado de:',
    tip: 'Pensa no número "de onde tiramos" a quantidade...',
    funFact: 'Você sabia que o número 4, que tiramos do 9, é chamado de subtraendo, e o resultado, 5, é a diferença?',
    points: 1,
    options: [
      { id: 'A', text: 'Subtraendo' },
      { id: 'B', text: 'Diferença' },
      { id: 'C', text: 'Resto apenas' },
      { id: 'D', text: 'Minuendo' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'Quanto é 8 + 5?',
    tip: 'Pensa em juntar 8 com mais 5 unidades...',
    funFact: 'Você sabia que decorar as somas básicas ajuda bastante a fazer contas maiores de cabeça?',
    points: 1,
    options: [
      { id: 'A', text: '13' },
      { id: 'B', text: '12' },
      { id: 'C', text: '14' },
      { id: 'D', text: '15' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'Quanto é 15 - 7?',
    tip: 'Pensa em quanto sobra depois de tirar 7 de 15...',
    funFact: 'Você sabia que a subtração é o "caminho inverso" da adição?',
    points: 1,
    options: [
      { id: 'A', text: '9' },
      { id: 'B', text: '7' },
      { id: 'C', text: '8' },
      { id: 'D', text: '6' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'A propriedade comutativa da adição diz que:',
    tip: 'Pensa: 3 + 5 dá o mesmo resultado que 5 + 3?',
    funFact: 'Você sabia que essa propriedade não vale para a subtração? 9 - 4 não dá o mesmo resultado que 4 - 9!',
    points: 1,
    options: [
      { id: 'A', text: 'A ordem das parcelas muda o resultado' },
      { id: 'B', text: 'A ordem das parcelas não muda o resultado da soma' },
      { id: 'C', text: 'A adição sempre dá resultado zero' },
      { id: 'D', text: 'Não é possível somar mais de dois números' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'Uma escola tem 245 alunos no turno da manhã e 198 alunos no turno da tarde. Quantos alunos a escola tem ao todo?',
    tip: 'Some os alunos dos dois turnos: 245 + 198...',
    funFact: 'Você sabia que muitas escolas brasileiras funcionam em mais de um turno para atender mais alunos?',
    points: 1,
    options: [
      { id: 'A', text: '343' },
      { id: 'B', text: '433' },
      { id: 'C', text: '543' },
      { id: 'D', text: '443' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'Uma loja tinha 520 brinquedos em estoque e vendeu 275. Quantos brinquedos restaram?',
    tip: 'Subtraia a quantidade vendida do total: 520 - 275...',
    funFact: 'Você sabia que lojas costumam controlar o estoque para saber quando precisam comprar mais produtos?',
    points: 1,
    options: [
      { id: 'A', text: '355' },
      { id: 'B', text: '235' },
      { id: 'C', text: '245' },
      { id: 'D', text: '265' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'Para verificar se a subtração 10 - 4 = 6 está correta, podemos fazer a chamada "prova real", que consiste em:',
    tip: 'Pensa: se 10 - 4 = 6, então 6 + 4 deveria dar de volta o número 10!',
    funFact: 'Você sabia que fazer a prova real é um ótimo hábito para conferir se uma conta está certa?',
    points: 1,
    options: [
      { id: 'A', text: 'Somar o resultado (6) com o subtraendo (4) e ver se dá o minuendo (10)' },
      { id: 'B', text: 'Multiplicar o resultado pelo minuendo' },
      { id: 'C', text: 'Dividir o minuendo pelo resultado' },
      { id: 'D', text: 'Não existe forma de verificar uma subtração' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'Bernardo tinha 150 figurinhas, ganhou mais 80 de um amigo e depois deu 60 para outro amigo. Com quantas figurinhas ele ficou?',
    tip: 'Primeiro some as figurinhas ganhas (150 + 80) e depois subtraia as que ele deu (- 60)...',
    funFact: 'Você sabia que trocar e presentear figurinhas com os amigos é uma forma divertida de completar coleções?',
    points: 1,
    options: [
      { id: 'A', text: '160' },
      { id: 'B', text: '170' },
      { id: 'C', text: '190' },
      { id: 'D', text: '150' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'De forma geral, usamos a adição para:',
    tip: 'Lembra de tudo que vimos sobre juntar quantidades nesse bloco...',
    funFact: 'Você sabia que a adição é uma das primeiras operações matemáticas que aprendemos, ainda muito pequenos?',
    points: 1,
    options: [
      { id: 'A', text: 'Separar uma quantidade em partes iguais' },
      { id: 'B', text: 'Descobrir quantas vezes um número cabe em outro' },
      { id: 'C', text: 'Diminuir uma quantidade' },
      { id: 'D', text: 'Juntar quantidades ou aumentar um valor' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'Na multiplicação 4 x 3 = 12, os números 4 e 3 são chamados de:',
    tip: 'Pensa nos números que são "multiplicados" para chegar ao resultado...',
    funFact: 'Você sabia que o resultado de uma multiplicação é chamado de produto?',
    points: 1,
    options: [
      { id: 'A', text: 'Fatores' },
      { id: 'B', text: 'Quociente' },
      { id: 'C', text: 'Diferença' },
      { id: 'D', text: 'Resto' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'Na divisão 20 ÷ 4 = 5, o número 20 é chamado de:',
    tip: 'Pensa no número que está "sendo dividido"...',
    funFact: 'Você sabia que o número 4 é o divisor, e o resultado, 5, é o quociente?',
    points: 1,
    options: [
      { id: 'A', text: 'Divisor' },
      { id: 'B', text: 'Quociente' },
      { id: 'C', text: 'Dividendo' },
      { id: 'D', text: 'Resto' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'Quanto é 7 x 6?',
    tip: 'Pensa na tabuada do 7 ou do 6...',
    funFact: 'Você sabia que saber bem a tabuada facilita muito contas de multiplicação e divisão maiores?',
    points: 1,
    options: [
      { id: 'A', text: '36' },
      { id: 'B', text: '40' },
      { id: 'C', text: '48' },
      { id: 'D', text: '42' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'Quanto é 48 ÷ 8?',
    tip: 'Pensa quantas vezes o número 8 cabe dentro de 48...',
    funFact: 'Você sabia que a divisão pode ser vista como o "caminho inverso" da multiplicação?',
    points: 1,
    options: [
      { id: 'A', text: '5' },
      { id: 'B', text: '6' },
      { id: 'C', text: '7' },
      { id: 'D', text: '8' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'A propriedade comutativa da multiplicação diz que:',
    tip: 'Pensa: 4 x 3 dá o mesmo resultado que 3 x 4?',
    funFact: 'Você sabia que essa propriedade não vale para a divisão? 20 ÷ 4 não dá o mesmo resultado que 4 ÷ 20!',
    points: 1,
    options: [
      { id: 'A', text: 'A ordem dos fatores não muda o resultado do produto' },
      { id: 'B', text: 'A ordem dos fatores sempre muda o resultado' },
      { id: 'C', text: 'A multiplicação sempre dá resultado zero' },
      { id: 'D', text: 'Não é possível multiplicar mais de dois números' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'A multiplicação 5 x 3 pode ser entendida como:',
    tip: 'Pensa na multiplicação como uma "soma de parcelas iguais"...',
    funFact: 'Você sabia que entender a multiplicação como soma de parcelas iguais ajuda a construir a tabuada sozinho, sem precisar decorar tudo de uma vez?',
    points: 1,
    options: [
      { id: 'A', text: 'Dividir 5 em 3 partes iguais' },
      { id: 'B', text: 'Subtrair 3 de 5, cinco vezes' },
      { id: 'C', text: 'Somar o número 5 três vezes seguidas (5 + 5 + 5)' },
      { id: 'D', text: 'Somar o número 3 apenas uma vez' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'Uma caixa tem 12 pacotes de biscoito, e cada pacote tem 8 biscoitos. Quantos biscoitos há ao todo na caixa?',
    tip: 'Multiplique a quantidade de pacotes pela quantidade de biscoitos em cada um: 12 x 8...',
    funFact: 'Você sabia que embalagens costumam informar exatamente quantas unidades vêm dentro delas?',
    points: 1,
    options: [
      { id: 'A', text: '20' },
      { id: 'B', text: '96' },
      { id: 'C', text: '84' },
      { id: 'D', text: '108' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'Ao dividir 17 por 5, o resultado é 3, e sobra:',
    tip: 'Pensa: 5 x 3 = 15, e quanto falta para chegar a 17?',
    funFact: 'Você sabia que, quando a divisão não é exata, o número que sobra é chamado de resto?',
    points: 1,
    options: [
      { id: 'A', text: '0' },
      { id: 'B', text: '1' },
      { id: 'C', text: '3' },
      { id: 'D', text: '2' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'Uma divisão é chamada de EXATA quando:',
    tip: 'Pensa: se não sobra nada depois de dividir, a divisão é...',
    funFact: 'Você sabia que quando o resto não é zero, chamamos a divisão de "não exata"?',
    points: 1,
    options: [
      { id: 'A', text: 'O resto é igual a zero' },
      { id: 'B', text: 'O resto é sempre maior que o divisor' },
      { id: 'C', text: 'O quociente é sempre zero' },
      { id: 'D', text: 'O dividendo é menor que o divisor' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'De forma geral, usamos a divisão para:',
    tip: 'Lembra de tudo que vimos sobre repartir quantidades nesse bloco...',
    funFact: 'Você sabia que dividir igualmente é uma forma justa de repartir algo entre várias pessoas?',
    points: 1,
    options: [
      { id: 'A', text: 'Juntar quantidades' },
      { id: 'B', text: 'Aumentar um valor' },
      { id: 'C', text: 'Repartir uma quantidade em partes iguais' },
      { id: 'D', text: 'Comparar dois números' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Bernardo comprou 3 livros que custam R$ 25 cada um. Quanto ele gastou ao todo?',
    tip: 'Multiplique o preço de um livro pela quantidade comprada: 25 x 3...',
    funFact: 'Você sabia que ler bastante ajuda a aumentar o vocabulário e a imaginação?',
    points: 1,
    options: [
      { id: 'A', text: 'R$ 28' },
      { id: 'B', text: 'R$ 50' },
      { id: 'C', text: 'R$ 65' },
      { id: 'D', text: 'R$ 75' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Bernardo tinha R$ 100 e gastou R$ 35 em um brinquedo. Quanto sobrou?',
    tip: 'Subtraia o valor gasto do valor que Bernardo tinha: 100 - 35...',
    funFact: 'Você sabia que guardar parte do dinheiro, mesmo depois de uma compra, é um ótimo hábito para o futuro?',
    points: 1,
    options: [
      { id: 'A', text: 'R$ 75' },
      { id: 'B', text: 'R$ 65' },
      { id: 'C', text: 'R$ 55' },
      { id: 'D', text: 'R$ 135' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Bernardo comprou 6 pacotes de figurinhas, e cada pacote tem 5 figurinhas. Quantas figurinhas ele comprou ao todo?',
    tip: 'Multiplique a quantidade de pacotes pela quantidade de figurinhas em cada um: 6 x 5...',
    funFact: 'Você sabia que álbuns de figurinhas fazem sucesso no Brasil há muitas décadas?',
    points: 1,
    options: [
      { id: 'A', text: '11' },
      { id: 'B', text: '25' },
      { id: 'C', text: '30' },
      { id: 'D', text: '35' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'Bernardo quer dividir suas 24 figurinhas igualmente entre ele e mais 3 amigos (4 pessoas no total). Quantas figurinhas cada um vai receber?',
    tip: 'Divida o total de figurinhas pela quantidade de pessoas: 24 ÷ 4...',
    funFact: 'Você sabia que dividir igualmente entre os amigos é uma boa forma de garantir que todos fiquem satisfeitos?',
    points: 1,
    options: [
      { id: 'A', text: '6' },
      { id: 'B', text: '8' },
      { id: 'C', text: '4' },
      { id: 'D', text: '24' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Bernardo tinha 40 figurinhas, ganhou mais 2 pacotes com 5 figurinhas cada e depois dividiu 10 figurinhas entre 2 amigos. Com quantas figurinhas Bernardo ficou?',
    tip: 'Primeiro calcule quantas figurinhas ele ganhou (2 x 5 = 10), some ao total (40 + 10 = 50) e depois subtraia as que ele deu (50 - 10)...',
    funFact: 'Você sabia que combinar várias operações em um só problema é uma ótima forma de treinar o raciocínio matemático?',
    points: 1,
    options: [
      { id: 'A', text: '50' },
      { id: 'B', text: '55' },
      { id: 'C', text: '30' },
      { id: 'D', text: '40' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Revisão: na adição 6 + 9 = 15, os números 6 e 9 são chamados de:',
    tip: 'Lembra do nome que damos aos números que são somados...',
    funFact: 'Você sabia que o resultado de uma adição pode ser chamado tanto de "soma" quanto de "total"?',
    points: 1,
    options: [
      { id: 'A', text: 'Produto' },
      { id: 'B', text: 'Parcelas' },
      { id: 'C', text: 'Dividendo' },
      { id: 'D', text: 'Diferença' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Revisão: na multiplicação 5 x 4 = 20, os números 5 e 4 são chamados de:',
    tip: 'Lembra do nome que damos aos números que são multiplicados...',
    funFact: 'Você sabia que "fator" também é usado em outras áreas, como quando falamos em "fator de risco" ou "fator decisivo"?',
    points: 1,
    options: [
      { id: 'A', text: 'Fatores' },
      { id: 'B', text: 'Quociente' },
      { id: 'C', text: 'Resto' },
      { id: 'D', text: 'Minuendo' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Revisão: para verificar (fazer a prova real de) uma divisão exata, como 20 ÷ 4 = 5, podemos:',
    tip: 'Pensa: se 20 ÷ 4 = 5, então 5 x 4 deveria dar de volta o número 20!',
    funFact: 'Você sabia que fazer a prova real ajuda a ter mais confiança de que o resultado de uma conta está certo?',
    points: 1,
    options: [
      { id: 'A', text: 'Somar 20 com 4' },
      { id: 'B', text: 'Subtrair 4 de 20' },
      { id: 'C', text: 'Multiplicar o quociente (5) pelo divisor (4) e ver se dá o dividendo (20)' },
      { id: 'D', text: 'Não existe forma de verificar uma divisão' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Revisão geral: por que é importante saber usar as quatro operações (adição, subtração, multiplicação e divisão)?',
    tip: 'Pensa em quantas vezes você soma, subtrai, multiplica ou divide algo durante o seu dia...',
    funFact: 'Você sabia que até brincadeiras e jogos usam bastante essas quatro operações, mesmo sem a gente perceber?',
    points: 1,
    options: [
      { id: 'A', text: 'Porque elas não têm nenhuma utilidade' },
      { id: 'B', text: 'Porque servem só para provas de matemática' },
      { id: 'C', text: 'Porque só existe uma operação realmente útil' },
      { id: 'D', text: 'Porque usamos essas operações em muitas situações do dia a dia, como compras, divisão de tarefas e organização de quantidades' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'Parabéns por aprender sobre as quatro operações! O que é mais importante lembrar desse conteúdo?',
    tip: 'Pensa em tudo que aprendemos: adição, subtração, multiplicação e divisão, cada uma com sua função...',
    funFact: 'Você sabia que dominar bem essas quatro operações é a base para aprender praticamente todo o resto da matemática?',
    points: 1,
    options: [
      { id: 'A', text: 'Que só a adição é uma operação válida' },
      { id: 'B', text: 'Que cada operação tem uma função diferente: juntar, tirar, multiplicar quantidades iguais ou repartir igualmente' },
      { id: 'C', text: 'Que a matemática não tem nenhuma aplicação prática' },
      { id: 'D', text: 'Que a divisão nunca tem resto' },
    ],
    correctAnswer: 'B',
  },
];
