export const questoesHistoria6AnoB3Av2 = [
  {
    id: 1,
    type: 'multiple_choice',
    text: 'Os gregos antigos acreditavam em vários deuses. Esse conjunto de crenças é chamado de:',
    tip: 'Pensa nas histórias de deuses e heróis gregos que você já deve ter visto em filmes ou desenhos.',
    funFact: 'Muitos filmes e séries de hoje, como sobre o Hércules, se inspiram diretamente na mitologia grega!',
    points: 1,
    options: [
      { id: 'A', text: 'Monoteísmo' },
      { id: 'B', text: 'Ateísmo' },
      { id: 'C', text: 'Mitologia grega' },
      { id: 'D', text: 'Cristianismo' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 2,
    type: 'multiple_choice',
    text: 'Quem era considerado o "rei dos deuses" na mitologia grega?',
    tip: 'É o deus mais poderoso, associado a raios e trovões — o "chefe" do Monte Olimpo.',
    funFact: 'Zeus é representado segurando um raio, como símbolo do seu poder sobre o céu!',
    points: 1,
    options: [
      { id: 'A', text: 'Zeus' },
      { id: 'B', text: 'Netuno' },
      { id: 'C', text: 'Hades' },
      { id: 'D', text: 'Apolo' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 3,
    type: 'multiple_choice',
    text: 'Onde os gregos antigos acreditavam que os deuses viviam?',
    tip: 'É uma montanha bem alta, que até deu nome aos Jogos Olímpicos!',
    funFact: 'O Monte Olimpo existe de verdade e é a montanha mais alta da Grécia atual!',
    points: 1,
    options: [
      { id: 'A', text: 'No fundo do mar' },
      { id: 'B', text: 'No Monte Olimpo' },
      { id: 'C', text: 'Dentro de uma pirâmide' },
      { id: 'D', text: 'No centro da Terra' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 4,
    type: 'multiple_choice',
    text: 'Os Jogos Olímpicos da Antiguidade eram realizados em homenagem a qual deus?',
    tip: 'É o mesmo deus "chefe" que mora no Monte Olimpo.',
    funFact: 'Os vencedores dos jogos antigos ganhavam uma coroa feita de folhas de oliveira, em vez de medalhas!',
    points: 1,
    options: [
      { id: 'A', text: 'Poseidon' },
      { id: 'B', text: 'Ares' },
      { id: 'C', text: 'Hermes' },
      { id: 'D', text: 'Zeus' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 5,
    type: 'multiple_choice',
    text: 'Além dos deuses, os gregos também contavam histórias sobre heróis, como:',
    tip: 'Pense em um herói famoso, conhecido pela força, que enfrentava monstros nas histórias gregas.',
    funFact: 'Hércules teve que cumprir 12 trabalhos impossíveis, segundo a mitologia grega!',
    points: 1,
    options: [
      { id: 'A', text: 'Tutancâmon' },
      { id: 'B', text: 'Hamurábi' },
      { id: 'C', text: 'Hércules' },
      { id: 'D', text: 'Napoleão' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 6,
    type: 'multiple_choice',
    text: 'O teatro grego era uma forma importante de arte e contava histórias sobre:',
    tip: 'Pensa em tudo que os gregos gostavam de contar em suas histórias — deuses, heróis, guerras.',
    funFact: 'Os gregos criaram as máscaras de teatro que representam comédia e tragédia, usadas como símbolo até hoje!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas receitas culinárias' },
      { id: 'B', text: 'Apenas mapas' },
      { id: 'C', text: 'Apenas números' },
      { id: 'D', text: 'Deuses, heróis e temas da vida em sociedade' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 7,
    type: 'multiple_choice',
    text: 'A palavra "filosofia" tem origem grega e significa:',
    tip: '"Filo" quer dizer amor, e "sofia" quer dizer sabedoria — junta as duas partes!',
    funFact: 'A filosofia grega tentava responder perguntas como "o que é a felicidade?" e "o que é justo?"!',
    points: 1,
    options: [
      { id: 'A', text: 'Amor pela sabedoria' },
      { id: 'B', text: 'Amor pelo esporte' },
      { id: 'C', text: 'Amor pela comida' },
      { id: 'D', text: 'Amor pela guerra' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 8,
    type: 'multiple_choice',
    text: 'Qual destes é considerado um famoso filósofo grego da Antiguidade?',
    tip: 'Os outros nomes são de um rei da Mesopotâmia, um faraó egípcio e um general romano — nenhum deles é grego!',
    funFact: 'Sócrates não deixou nada escrito — conhecemos suas ideias porque seus alunos, como Platão, as registraram!',
    points: 1,
    options: [
      { id: 'A', text: 'Hamurábi' },
      { id: 'B', text: 'Sócrates' },
      { id: 'C', text: 'Tutancâmon' },
      { id: 'D', text: 'Júlio César' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 9,
    type: 'multiple_choice',
    text: 'Os primeiros Jogos Olímpicos da Antiguidade aconteciam na cidade de:',
    tip: 'O nome da cidade é bem parecido com o nome dos próprios jogos!',
    funFact: 'Em Olímpia ainda existem ruínas do antigo estádio onde os jogos aconteciam há milhares de anos!',
    points: 1,
    options: [
      { id: 'A', text: 'Atenas' },
      { id: 'B', text: 'Esparta' },
      { id: 'C', text: 'Olímpia' },
      { id: 'D', text: 'Tebas' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 10,
    type: 'multiple_choice',
    text: 'Por que os Jogos Olímpicos antigos eram tão importantes para os gregos?',
    tip: 'Pensa em duas coisas importantes para os gregos: a religião (deuses) e a relação entre as pólis.',
    funFact: 'Durante os jogos, muitas guerras entre as pólis eram até pausadas, em respeito à competição!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque uniam as pólis em competições e homenageavam os deuses' },
      { id: 'B', text: 'Porque só serviam para vender comida' },
      { id: 'C', text: 'Porque eram um tipo de guerra' },
      { id: 'D', text: 'Porque não tinham nenhum significado' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 11,
    type: 'multiple_choice',
    text: 'Se um grego antigo quisesse explicar por que havia trovões e relâmpagos, ele provavelmente diria que era obra de:',
    tip: 'Lembra qual deus segura um raio como símbolo de poder?',
    funFact: 'Antes da ciência explicar os fenômenos da natureza, muitos povos antigos usavam mitos para isso!',
    points: 1,
    options: [
      { id: 'A', text: 'Um vulcão apenas' },
      { id: 'B', text: 'Zeus, o deus do trovão' },
      { id: 'C', text: 'Uma máquina' },
      { id: 'D', text: 'Um vento forte' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 12,
    type: 'multiple_choice',
    text: 'Por que os mitos gregos, com deuses e heróis, eram importantes para a sociedade da época?',
    tip: 'Pensa no que a questão 11 mostrou sobre os trovões — os mitos serviam para explicar o quê?',
    funFact: 'Muitos mitos também ensinavam lições, como a importância da coragem ou o perigo da vaidade excessiva!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque eram apenas brincadeiras sem sentido' },
      { id: 'B', text: 'Porque só serviam para assustar crianças' },
      { id: 'C', text: 'Porque não tinham nenhuma função' },
      { id: 'D', text: 'Porque ajudavam a explicar o mundo, a natureza e ensinar valores' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 13,
    type: 'multiple_choice',
    text: 'Imagine um atleta grego se preparando para competir nos Jogos Olímpicos da Antiguidade. Isso mostra que os gregos valorizavam:',
    tip: 'Pensa no motivo dos jogos existirem, estudado na questão 10.',
    funFact: 'Os atletas gregos competiam sem roupas — a palavra "ginástica" vem do grego "gymnos", que significa "nu"!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas a escrita' },
      { id: 'B', text: 'Apenas a política' },
      { id: 'C', text: 'O desenvolvimento físico e a competição saudável entre as pólis' },
      { id: 'D', text: 'Apenas o comércio' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 14,
    type: 'multiple_choice',
    text: 'Por que Sócrates é lembrado até hoje na história da filosofia?',
    tip: 'Volta na questão 8 — o que fazia dele um filósofo tão especial?',
    funFact: 'Essa técnica de ensinar fazendo perguntas é usada até hoje em escolas e é chamada de "método socrático"!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque incentivava as pessoas a pensar e questionar por meio de perguntas' },
      { id: 'B', text: 'Porque construiu pirâmides' },
      { id: 'C', text: 'Porque criou os Jogos Olímpicos' },
      { id: 'D', text: 'Porque governava Esparta' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 15,
    type: 'multiple_choice',
    text: 'Se uma peça de teatro grego contava a história de um herói enfrentando um monstro, isso mostra que o teatro servia para:',
    tip: 'Volta na questão 6 — para que servia o teatro grego, além de contar histórias?',
    funFact: 'As peças de teatro gregas eram apresentadas em anfiteatros ao ar livre, que podiam receber milhares de pessoas!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas fazer barulho' },
      { id: 'B', text: 'Contar histórias que divertiam e também ensinavam algo ao público' },
      { id: 'C', text: 'Vender produtos' },
      { id: 'D', text: 'Ensinar matemática apenas' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 16,
    type: 'multiple_choice',
    text: 'Por que os Jogos Olímpicos da Antiguidade aconteciam sempre na mesma cidade, Olímpia?',
    tip: 'Lembra a quem os jogos eram dedicados — por que a cidade escolhida tinha esse significado?',
    funFact: 'Em Olímpia havia um enorme templo dedicado a Zeus, com uma estátua gigante do deus dentro dele!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque era um local sagrado, ligado à homenagem a Zeus' },
      { id: 'B', text: 'Porque era a única cidade grega que existia' },
      { id: 'C', text: 'Porque ficava mais perto do Egito' },
      { id: 'D', text: 'Porque não havia outro lugar disponível' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 17,
    type: 'multiple_choice',
    text: 'O que a existência de vários deuses, cada um com uma função (mar, guerra, sabedoria, etc.), revela sobre a mitologia grega?',
    tip: 'Pensa em como cada deus (Zeus do trovão, Poseidon do mar) cuidava de uma parte diferente do mundo.',
    funFact: 'Existiam dezenas de deuses na mitologia grega, cada um com histórias e poderes próprios!',
    points: 1,
    options: [
      { id: 'A', text: 'Que os gregos não tinham imaginação' },
      { id: 'B', text: 'Que só existia um deus, na verdade' },
      { id: 'C', text: 'Que os deuses gregos eram todos iguais' },
      { id: 'D', text: 'Que os gregos explicavam diferentes aspectos da vida e da natureza através de diferentes divindades' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 18,
    type: 'multiple_choice',
    text: 'Por que a filosofia grega é considerada uma base importante para o pensamento ocidental até hoje?',
    tip: 'Pensa no significado da palavra "filosofia" — sobre que tipo de assunto ela se debruçava?',
    funFact: 'Muitas ideias de filósofos gregos, como Sócrates, Platão e Aristóteles, ainda são estudadas em faculdades hoje!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque não influenciou nada depois' },
      { id: 'B', text: 'Porque só era usada para adivinhar o futuro' },
      { id: 'C', text: 'Porque discutia questões como ética, conhecimento e sociedade que ainda estudamos hoje' },
      { id: 'D', text: 'Porque era proibida na época' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 19,
    type: 'multiple_choice',
    text: 'Durante os Jogos Olímpicos antigos, as guerras entre as pólis gregas muitas vezes eram interrompidas. O que isso demonstra?',
    tip: 'Volta na questão 10 — o que os Jogos Olímpicos representavam para a relação entre as pólis?',
    funFact: 'Esse período de paz durante os jogos era chamado de "trégua olímpica" — uma ideia retomada até hoje!',
    points: 1,
    options: [
      { id: 'A', text: 'Que os jogos não tinham importância nenhuma' },
      { id: 'B', text: 'Que os Jogos Olímpicos eram tão importantes que geravam uma espécie de trégua entre as cidades' },
      { id: 'C', text: 'Que as pólis nunca brigavam' },
      { id: 'D', text: 'Que só Esparta participava dos jogos' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 20,
    type: 'multiple_choice',
    text: 'Por que podemos dizer que a cultura grega (mitologia, teatro, filosofia e jogos) deixou uma grande herança para o mundo?',
    tip: 'Pensa nos Jogos Olímpicos modernos, no teatro, na filosofia estudada em escolas — tudo isso ainda existe hoje!',
    funFact: 'As Olimpíadas modernas, criadas em 1896, foram inspiradas diretamente nos Jogos Olímpicos da Grécia Antiga!',
    points: 1,
    options: [
      { id: 'A', text: 'Porque foi totalmente esquecida com o tempo' },
      { id: 'B', text: 'Porque só interessava aos próprios gregos' },
      { id: 'C', text: 'Porque não existe mais nenhum vestígio dela' },
      { id: 'D', text: 'Porque muitas dessas ideias e tradições influenciam a arte, a política e o esporte até os dias de hoje' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 21,
    type: 'multiple_choice',
    text: 'Bernardo está desenhando o Monte Olimpo para o trabalho de História. Ele explica à turma que ali os gregos acreditavam que viviam:',
    tip: 'É a mesma resposta da questão 3.',
    funFact: 'Desenhar o Monte Olimpo com os deuses no topo é uma forma bem divertida de memorizar a mitologia grega!',
    points: 1,
    options: [
      { id: 'A', text: 'Os deuses' },
      { id: 'B', text: 'Apenas os reis' },
      { id: 'C', text: 'Os primeiros humanos' },
      { id: 'D', text: 'Os animais sagrados' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 22,
    type: 'multiple_choice',
    text: 'Na apresentação, Bernardo mostra a imagem de um deus segurando um raio e explica que ele é o "rei dos deuses" na mitologia grega. De quem ele está falando?',
    tip: 'É o mesmo deus das questões 2, 4 e 11.',
    funFact: 'Em algumas representações antigas, Zeus aparece com uma águia ao lado, seu animal sagrado!',
    points: 1,
    options: [
      { id: 'A', text: 'Hades' },
      { id: 'B', text: 'Poseidon' },
      { id: 'C', text: 'Zeus' },
      { id: 'D', text: 'Ares' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 23,
    type: 'multiple_choice',
    text: 'Bernardo monta uma pequena pista de corrida na escola para representar uma competição da Grécia Antiga, feita em homenagem aos deuses. Que evento ele está representando?',
    tip: 'Volta nas questões 4, 9 e 10 sobre esse grande evento esportivo grego.',
    funFact: 'Bernardo pode até criar sua própria "tocha olímpica" de papel para deixar a brincadeira mais divertida!',
    points: 1,
    options: [
      { id: 'A', text: 'Uma guerra' },
      { id: 'B', text: 'Um teatro' },
      { id: 'C', text: 'Uma eleição' },
      { id: 'D', text: 'Os Jogos Olímpicos da Antiguidade' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 24,
    type: 'multiple_choice',
    text: 'No quiz de Bernardo, a pista é: "Sou um filósofo grego famoso por fazer perguntas que faziam as pessoas pensarem." Quem é a resposta?',
    tip: 'É o mesmo filósofo das questões 8 e 14.',
    funFact: 'Sócrates dizia uma frase famosa: "Só sei que nada sei" — mostrando a importância de sempre continuar aprendendo!',
    points: 1,
    options: [
      { id: 'A', text: 'Hamurábi' },
      { id: 'B', text: 'Sócrates' },
      { id: 'C', text: 'Zeus' },
      { id: 'D', text: 'Hércules' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 25,
    type: 'multiple_choice',
    text: 'Bernardo pergunta ao pai por que os gregos antigos contavam tantas histórias sobre deuses e heróis. O pai explica que:',
    tip: 'Volta na questão 12 sobre a função dos mitos gregos.',
    funFact: 'Até hoje usamos expressões como "calcanhar de Aquiles" (um ponto fraco) que vêm direto da mitologia grega!',
    points: 1,
    options: [
      { id: 'A', text: 'Essas histórias ajudavam a explicar o mundo e ensinar valores para as pessoas' },
      { id: 'B', text: 'Eram apenas desenhos animados da época' },
      { id: 'C', text: 'Não tinham nenhum propósito' },
      { id: 'D', text: 'Serviam só para assustar' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 26,
    type: 'multiple_choice',
    text: 'Na peça de teatro que a turma de Bernardo vai apresentar, inspirada na Grécia Antiga, o enredo mistura deuses, heróis e uma lição de vida. Isso mostra que o teatro grego servia para:',
    tip: 'Volta nas questões 6 e 15 sobre a função do teatro na Grécia Antiga.',
    funFact: 'As máscaras que os atores gregos usavam ajudavam o público, mesmo de longe, a entender se a cena era triste ou engraçada!',
    points: 1,
    options: [
      { id: 'A', text: 'Apenas fazer barulho na plateia' },
      { id: 'B', text: 'Divertir e também transmitir ensinamentos ao público' },
      { id: 'C', text: 'Vender ingressos apenas' },
      { id: 'D', text: 'Substituir a escola' },
    ],
    correctAnswer: 'B',
  },
  {
    id: 27,
    type: 'multiple_choice',
    text: 'Bernardo explica ao colega que a palavra "filosofia" vem do grego e quer dizer:',
    tip: 'É a mesma explicação da questão 7.',
    funFact: 'Um "filósofo", literalmente, é alguém que "ama" buscar conhecimento e entender o mundo!',
    points: 1,
    options: [
      { id: 'A', text: 'Amor pela guerra' },
      { id: 'B', text: 'Amor pela comida' },
      { id: 'C', text: 'Amor pela sabedoria' },
      { id: 'D', text: 'Amor pelo esporte' },
    ],
    correctAnswer: 'C',
  },
  {
    id: 28,
    type: 'multiple_choice',
    text: 'Bernardo pergunta à professora por que os Jogos Olímpicos aconteciam sempre na cidade de Olímpia. Ela explica que:',
    tip: 'É a mesma explicação da questão 16.',
    funFact: 'Hoje, antes de cada Olimpíada moderna, uma tocha é acesa justamente em Olímpia, na Grécia, como uma homenagem à tradição antiga!',
    points: 1,
    options: [
      { id: 'A', text: 'Era a maior cidade da Grécia' },
      { id: 'B', text: 'Era a capital do país' },
      { id: 'C', text: 'Era onde morava o rei da Grécia' },
      { id: 'D', text: 'Era um local sagrado, ligado à homenagem ao deus Zeus' },
    ],
    correctAnswer: 'D',
  },
  {
    id: 29,
    type: 'multiple_choice',
    text: 'Bernardo resume para a turma: "Os Jogos Olímpicos hoje em dia têm uma ligação direta com:" Como ele deve completar a frase?',
    tip: 'Volta na questão 20 sobre a herança deixada pela cultura grega.',
    funFact: 'O símbolo dos cinco anéis olímpicos representa os cinco continentes unidos pelo esporte!',
    points: 1,
    options: [
      { id: 'A', text: '"...os Jogos Olímpicos realizados na Grécia Antiga, há milhares de anos."' },
      { id: 'B', text: '"...uma invenção totalmente moderna, sem nenhuma origem antiga."' },
      { id: 'C', text: '"...um jogo inventado no Egito Antigo."' },
      { id: 'D', text: '"...uma brincadeira criada ontem."' },
    ],
    correctAnswer: 'A',
  },
  {
    id: 30,
    type: 'multiple_choice',
    text: 'Para encerrar sua apresentação sobre a cultura grega, Bernardo resume: "A Grécia Antiga nos deixou de herança..." Como ele pode completar a frase?',
    tip: 'Pensa em tudo que você aprendeu neste simulado — mitologia, filosofia, teatro e jogos.',
    funFact: 'No próximo simulado, você vai conhecer outra grande civilização antiga que também deixou uma enorme herança: Roma!',
    points: 1,
    options: [
      { id: 'A', text: '"...nada, pois tudo foi esquecido."' },
      { id: 'B', text: '"...apenas construções, sem nenhuma ideia importante."' },
      { id: 'C', text: '"...ideias de mitologia, filosofia, teatro e os Jogos Olímpicos, que influenciam o mundo até hoje."' },
      { id: 'D', text: '"...somente comidas típicas."' },
    ],
    correctAnswer: 'C',
  },
];
